### ISSUE TITLE
Transparency will not be preserve in screenshot

### ISSUE THREAD

**Issue by FWeinb** [atom/electron#1011]
Using `capturePage` will return a `png` where the transparent color is replaced by just black. Is it possible to include transparency in a screenshot?

**Comment by zcbenz** [comment]
It should be possible, but we may have to dig into Chromium's source code to find out how.

**Comment by bsudekum** [comment]
+1

**Comment by FWeinb** [comment]
Just tested it with the latest version (`v0.25.1`) of electron and now instead of transparence a chessboard pattern like you see in photoshop is rendered.

**Comment by FWeinb** [comment]
This is fixed in `v0.27.0` PNG screenshot contains a full alpha channel.
