### ISSUE TITLE
Issue with BrowserWindow height in Mac OS X

### ISSUE THREAD

**Issue by unindented** [atom/electron#1024]
If I instantiate `BrowserWindow` on Mac OS X Mavericks with `height: 384, frame: true`, I get a window with height 384px, including title bar. My content is 384px high, so the bottom gets cut:

![With frame](https://cloud.githubusercontent.com/assets/69485/5793465/33eb8986-9f3c-11e4-8761-ec58d4e2bb1e.png)

If I instantiate `BrowserWindow` with `height: 384, frame: false`, I get a window with height 406px (notice the empty stripe at the bottom of the image):

![Without frame](https://cloud.githubusercontent.com/assets/69485/5793467/3c7f8124-9f3c-11e4-9fe7-5fef0139147a.png)

It looks like an `if` statement somewhere is checking for the opposite condition. If `frame: true`, then the window should be 406px (384px from the content + 22px from the title bar). Otherwise, the window should be 384px (just the content). Currently the opposite happens.

Am I missing something?

**Comment by zcbenz** [comment]
For window that has frame, you need to set `use-content-size` to `true` if you don't want the size to include window frame.

It is a bug that frameless window has a slightly larger height.

**Comment by JFrolich** [comment]
I would like to comment that the content-size for frameless windows is a mac-only bug.

Before I look into this myself, is there anyone already looking into this bug?

**Comment by hokein** [comment]
Also the return values of `BrowserWindow.getSize()` and `BrowserWindow.getContentSize()` are different in frameless window(The behavior still looks like in frame window).
```
win = new BrowserWindow({
   width:800,
   height: 600,
   frame: false
});

// returns [800, 600]
win.getContentSize();

// returns [800, 622]
win.getSize();
```
