### ISSUE TITLE
Notification icon can't be changed

### ISSUE THREAD

**Issue by shaunlebron** [atom/electron#1025]
We sort of stumbled upon the undocumented Notification API, which is working on Mac.

```js
new Notification("title", {body: "message", icon: "path/to/image.png"});
```

![screen shot 2015-01-18 at 8 57 06 pm](https://cloud.githubusercontent.com/assets/116838/5795389/97b2e91a-9f54-11e4-9e1e-7cebe35df202.png)

But we can't change the icon.  Tried using paths and Data URIs, and even when changing the App icon in Info.plist, it still somehow manages to find the default Atom icon.

**Comment by paulcbetts** [comment]
That icon is always going to be your app's icon (OS X doesn't let you set it to arbitrary images), if you're seeing the Atom Shell icon, you may be setting your icon incorrectly.

**Comment by zcbenz** [comment]
Yeah unless we implement the notifications ourselves, the icon will always be your app's icon. I'm closing this as won't fix since I don't think we will ever do it.

> when changing the App icon in Info.plist, it still somehow manages to find the default Atom icon.

You also need to check whether you have changed the bundle ID, and notification center also has [cache on icons](http://stackoverflow.com/questions/11856766/osx-notification-center-icon).

**Comment by shaunlebron** [comment]
Changing the bundle ID, removing the notification center cache, and some waiting worked. Thanks!

**Comment by gillesdemey** [comment]
NW.js has implemented this feature somewhat different, they map the icon property to something that looks like this:
![screenshot 2015-05-25 00 42 44](https://cloud.githubusercontent.com/assets/868844/7790085/98275fa6-0279-11e5-9c7a-7532b57c6322.png)

Any chance that Atom could tackle this in a similar fashion?

**Comment by paulcbetts** [comment]
@gillesdemey Hm, not a terrible idea

**Comment by zcbenz** [comment]
nw.js rewrites the whole notification window from scratch, this can not be implemented with native notification APIs.

**Comment by paulcbetts** [comment]
> nw.js rewrites the whole notification window from scratch, this can not be implemented with native notification APIs.

I think this was added as a standard feature in >= 10.9, check out https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSUserNotification_Class/index.html#//apple_ref/occ/instp/NSUserNotification/contentImage

**Comment by zcbenz** [comment]
@paulcbetts Thanks for the link, I'm reopening this.

**Comment by zcbenz** [comment]
Fixed by https://github.com/atom/brightray/pull/118.

**Comment by shaunlebron** [comment]
thanks everyone :+1:
