### ISSUE TITLE
 Linux video acceleration support for Intel hardware

### ISSUE THREAD

**Issue by mgcrea** [atom/electron#1032]
Would it be possible for atom-shell to bypass existing protections in chromium preventing hardware video decode on intel chipset with linux? The idea would be to implement this chromium ticket [Issue 176883018: Remove additional protection of kDisableAcceleratedVideoDecode in bpf_gpu_policy_linux.cc.](https://codereview.chromium.org/176883018) that has been closed for the [sake of stability](https://codereview.chromium.org/176883018/#msg6).

That would be a great addition for linux app builders out there.

Some more context: [Video Acceleration Takes The Backseat On Chrome For Linux](http://www.phoronix.com/scan.php?page=news_item&px=MTYyMDk)

This issue might be better suited in https://github.com/brightray/libchromiumcontent, if you want I can move it there.

**Comment by zcbenz** [comment]
By adding a patch in libchromiumcontent we should be able to enable video acceleration on Linux, but it should still be disabled by default for stability.

**Comment by paulcbetts** [comment]
The likelihood that this code actually works is probably pretty low if it's been disabled for forever, if only because of bitrot

**Comment by mgcrea** [comment]
@paulcbetts, I have been using VAAPI for a while on recent (HD4000+) Intel hardware and it has always worked flawlessly. It won't probably work on every Linux/chipset combo but I think there is a high chance that it would just work on many setups. And it looks like the code has been activated for ChromeOS for a while now.

**Comment by zcbenz** [comment]
@mgcrea It seems that Chrome 42 has enabled accelerated video decode by default:
https://code.google.com/p/chromium/codesearch#chromium/src/content/common/sandbox_linux/bpf_gpu_policy_linux.cc&sq=package:chromium&l=106

Can you try if latest Electron release (v0.25.1) works for you?

**Comment by mgcrea** [comment]
@zcbenz just tried electron v0.26 and I still get `[6517:0518/190622:ERROR:gpu_video_decode_accelerator.cc(300)] Not implemented reached in void content::GpuVideoDecodeAccelerator::Initialize(const media::VideoCodecProfile, IPC::Message *)HW video decode acceleration not available.`.

I'm running electron with `["--ignore-gpu-blacklist", "--touch-events=enabled", "--disable-touch-editing", "--disable-http-cache"]` cli-args.

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/atom/libchromiumcontent/issues/92.
