### ISSUE TITLE
Possible bug calculating display.workAreaSize

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1058]
I think there is an issue calculating the height of the taskbar on Windows when `scaleFactor` is > 1.0. To reproduce this issue:

1. Set the DPI / text scaling of your display to, say, 150%.
2. Snap the app window to the left / right of the display.
3. Compare the result of `BrowserWindow.getSize()` with `display.workAreaSize`.

You will find that the height of the window is always greater than `workAreaSize.height`, even though they should be exactly equal. Here is an example from my machine:
`window.getSize: [0,0,854,1030], display.workAreaSize: [0,0,1706,1010]`

Printing the full `display` structure:
``` javascript 
{"id":2528732444,"bounds":{"x":0,"y":0,"width":1706,"height":1066},"workArea":{"x":0,"y":0,"width":1706,"height":1010},"size":{"width":1706,"height":1066},"workAreaSize":{"width":1706,"height":1010},"scaleFactor":1.5,"rotation":0,"touchSupport":"unknown"}
```
Repeat the same experiment after dropping DPI back to 100%. The heights will be equal.

**Comment by zcbenz** [comment]
The [code to get work area size](https://code.google.com/p/chromium/codesearch#chromium/src/ui/gfx/screen_win.cc&sq=package:chromium&q=GetDisplay&type=cs&l=26) is implemented in Chromium, and as far as I can see it just returns the work area size returned by win32 API, not sure why it is not correct.

**Comment by CharlieHess** [comment]
In addition, when I get the `bounds` of a maximized window, the position returned is negative (`[-8, -8]`). :cry: For any logic that tries to bound these coordinates within the display area, this will be error-prone.

**Comment by zcbenz** [comment]
> In addition, when I get the bounds of a maximized window, the position returned is negative ([-8, -8]).  For any logic that tries to bound these coordinates within the display area, this will be error-prone.

This is unfortunately an expected behavior on Windows, see:
http://blogs.msdn.com/b/oldnewthing/archive/2012/03/26/10287385.aspx

To work around this you should treat maximized window specially in your logic.

**Comment by zcbenz** [comment]
display.workAreaSize seems to work as expected in v0.33.0.
