### ISSUE TITLE
node.js or io.js?

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1108]
The readme.md still links to node.js as being used in atom shell, but when I run the hello world application, the printed node.js version seems to be following io.js version spec.

I am a bit puzzled, did Atom Shell move to io.js and when did this happen if so?

**Comment by frankhale** [comment]
Yes I was also confused about this especially when I looked at the release notes for the latest version of the Atom Editor https://github.com/atom/atom/releases/tag/v0.177.0

```
Atom now runs on top of Chrome 40 and io.js
```

**Comment by bwin** [comment]
AFAIK Atom-Shell uses io.js and Chromium 40 since v0.21.0

**Comment by thedaniel** [comment]
@bwin is correct, the README should be updated.

**Comment by kevinsawicki** [comment]
> did Atom Shell move to io.js and when did this happen if so?

It happened as part of the Chrome 40 upgrade in https://github.com/atom/atom-shell/pull/1002

**Comment by reggi** [comment]
This is very unclear. Just found out via this youtube meme video ["Hitler finds out about io.js"](https://www.youtube.com/watch?v=1IOukA10QeQ). I'd like to see it in the [README.md](https://github.com/atom/atom-shell/blob/master/README.md). Perhaps [atom/node](https://github.com/atom/node) should be change to [atom/io.js](https://github.com/atom/io.js)? It would have been nice if it was in a bullet in the [v0.21.0 changelog](https://github.com/atom/atom-shell/releases/tag/v0.21.0). :umbrella: :inbox_tray: :outbox_tray:

**Comment by mark-hahn** [comment]
atom/node was already a fork of node.  So now it is just a fork of a fork.

**Comment by zcbenz** [comment]
Technically we are using neither Node nor io.js, because we forked io.js. In practical using `Node.js` in our docs is safe because both our fork and io.js are compatible with Node.

But I agree we should replace Node with io.js in the docs to reduce confusions.

**Comment by steelbrain** [comment]
@reggi That video is awesome! :laughing: 
+1 for having it in docs

**Comment by paulyoung** [comment]
I think this issue can be closed now.

**Comment by zcbenz** [comment]
@paulyoung There are still many places in the docs using Node.js.

**Comment by paulyoung** [comment]
My mistake. This issue seemed to only refer to the README.

**Comment by zcbenz** [comment]
All docs are updated now.
