### ISSUE TITLE
webview reloads and goes blank until resize

### ISSUE THREAD

**Issue by mark-hahn** [atom/electron#1110]
I have a repeatable problem when an existing webview tag is hidden and then shown, but only in a specific situation (see instructions to repeat the problem below).  The webview does a reload even though nothing in my code told it to.  And then it shows an empty white area.  If I resize the containing DIV it is repaired and the page appears again.

I'm not sure exactly what triggers this.  It happens when Atom splits a pane and then I go back to a tab with a webview.  I've walked through the split code and it just creates a new pane and then attaches a new text editor to it. 

To recreate the problem ...

- Install the package `web-browser`, branch `blank-webview`.
- open any text file in one pane
- add a webpage to that pane (ctrl-alt-b)
- select the text file and split right
- select the original text file again
- select web page tab

Then the webpage shows a reload indicator and comes up all white.  Resizing the page fixes it..

**Edit:** branch is at https://github.com/mark-hahn/web-browser/tree/blank-webview.

**Comment by steelbrain** [comment]
Bump.

**Comment by zcbenz** [comment]
@mark-hahn Can you try if it is fixed in latest Atom?

**Comment by steelbrain** [comment]
@zcbenz I just tried the latest release and it's segmentation faulting in my app that uses web view, works fine on other apps though. The core dump ids are (I believe atom-shell uploads it's crash logs automatically)
```
1428388528,2180f4a1-def1-4c5e-bb78-ec36549ca304
1428388665,3333971a-55c8-4160-997b-3619b4e07eba
1428388680,b02fc622-f10d-47bc-b42a-c79726ae75b5
1428388773,d1658308-c16c-4d9d-98e4-aa79b1bff8e3
```

**Comment by zcbenz** [comment]
Doesn't seem to be a problem anymore, Atom still needs to update to latest Electron to have this fix though.

**Comment by jschmidt42** [comment]
I am still getting this issue when resizing `webview`. I get blank/white rectangles for a few seconds until everything fully refreshes. I don't get this display issue when using `iframe`. I am using electron 0.36. Is there something I can do to workaround this?
![image](https://cloud.githubusercontent.com/assets/4054655/12060327/35897e28-af3b-11e5-9516-2d2d85c786af.png)
