### ISSUE TITLE
Add a generic mechanism for hooking window messages

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1121]
There are many native Windows features that will require listening to some `WM` or another. Right now there isn't a great way in Atom Shell to do this. AFAICT, your best bet is to:

1. Create your own native node module
2. Include `<windows.h>`
3. Create a message-only `Hwnd` that is a child of your Atom window
4. Hook `WndProc` for whatever message you're interested in
5. Fire a callback to the JS

It would be _awesome_ if there was a generic way to add a handler for a window message, and Atom Shell took care of the above steps natively. Something like:

``` coffeescript
messageCode = 262 # WM_SYSCHAR
browserWindow.hookWindowMessage messageCode, (wParam, lParam) ->
  # Do your dirty work
```

**Comment by frankhale** [comment]
:+1:

**Comment by omrilitov** [comment]
Merged in https://github.com/atom/electron/pull/3231, can be closed
