### ISSUE TITLE
Unable to debug past webview.parentNode.removeChild(webview)

### ISSUE THREAD

**Issue by mcdermed** [atom/electron#1173]
Like the title says I'm running into a problem while debugging my app. 

I'm using the debugger from ```BrowserWindow#openDevTools```. I have not tried using the remote debugging port.

The problem happens when I stepping over the line that removes my webview. ```webview.parentNode.removeChild(webview)```. I can set a breakpoint on or before the line but after the debugger will not pause code execution. Console messages and code after the line executes just fine.

A follow up question: Is this the best way to remove a webview? I am getting the ```destoryed``` event but it seems like ```ipc``` is still retaining a reference to the detached DOM tree.

![screen shot 2015-02-24 at 1 57 45 pm](https://cloud.githubusercontent.com/assets/1432369/6359061/68f6fdaa-bc2d-11e4-923a-713d32041f2b.png)

**Comment by zcbenz** [comment]
> A follow up question: Is this the best way to remove a webview? I am getting the destoryed event but it seems like ipc is still retaining a reference to the detached DOM tree.

This is a bug, I have created a separate issue at #1185.

**Comment by zcbenz** [comment]
I can reproduce this on Chrome's webview tag, I suggest reporting it to Chromium's issue tracker since we can not fix it on our side.
