### ISSUE TITLE
Invalid Bundle Identifier com.Breakpad.crash_report_sender

### ISSUE THREAD

**Issue by bostondv** [atom/electron#1174]
I'm aware of #249, but trying to go through submit process anyway.

When submitted via the Application Loader, it gives this error:

`ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework crash_report_sender [come.scendix.pamfax.osx.pkg/Payload/PamFax.app/Contents/Frameworks/Atom Framework.framework/Versions/A/Resources/crash_report_sender.app] using the bundle identifier 'com.Breakpad.crash_report_sender', which is not a valid bundle identifier."`

Seems underscores are not valid, because changing the identifier to `com.Breakpad.crashreportsender` fixes the error.

**Comment by zcbenz** [comment]
Closing since breakpad is not being used on OS X anymore.
