### ISSUE TITLE
Error feedback with custom protocol handler

### ISSUE THREAD

**Issue by Wortex17** [atom/electron#1189]
Is there any way we can send back errors with custom protocols?
E.g. when i access a file that doesn exists with the ```file://``` protocoll, chrome does know the file does not exist (in the devConsole this is logged as ```net::ERR_FILE_NOT_FOUND```)
With my custom ```foobar://``` protocoll, i want to look up files, but trigger errors when specific (e.g. forbidden) files are accessed.

The only current way i can think of is redirecting the call to a file that does not exist for sure:
```
return new protocol.RequestFileJob('#');
```
but a specifically triggered error (event with "Forbiden" or "Access Denied" messages) would be much nicer.

I guess it shouldn't be hard to implement, as error feedback already exists [here](https://github.com/atom/atom-shell/blob/master/atom/browser/api/atom_api_protocol.cc#L109).

**Comment by zcbenz** [comment]
Currently there is no way for this, I'll expose something like `protocol.Error` to return a custom error.
