### ISSUE TITLE
OS X fullscreen button doesn't trigger events

### ISSUE THREAD

**Issue by incanus** [atom/electron#1211]
The fullscreen button on the window itself doesn't fire the `browser-window.enter-full-screen` or `browser-window.exit-full-screen` events, only the menu item does this. 

Background: https://github.com/mapbox/mapbox-studio/pull/1234#issuecomment-77483286

**Comment by deepak1556** [comment]
on `10.9.5` it seems to be working fine, is this problem still on yosemite ?

**Comment by zcbenz** [comment]
Unable to reproduce with v0.33.0 on Yosemite, it is probably a OS X bug that had already been fixed, please report if you still see it.
