### ISSUE TITLE
Tabulator key not working as expected in webview panel

### ISSUE THREAD

**Issue by pbihler** [atom/electron#1214]
Tested on OS X

When I directly add a webview as a panel:

```coffeescript
  activate: (state) ->
    @blaPackageView = new BlaPackageView(state.blaPackageViewState)
    @modalPanel = atom.workspace.addRightPanel item: @blaPackageView
```
```coffeescript
{$, View} = require 'atom-space-pen-views'

module.exports =
class BlaPackageView extends View

  @content = ->
    @div class:'browser-page', tabindex:-1

  initialize: (serializeState) ->
    # Create message element
    @webview = $ """
      <webview class="native-key-bindings" src="http://www.google.com"
               plugins disablewebsecurity></webview>
    """
    @append @webview
    @webviewEle = @webview[0]
```
The <kbd>tab</kbd> key does not work as expected (= moving to the next input field), but inserts a tabulator into the input field! I can press <kbd>alt</kbd>+<kbd>tab</kbd> to move to next field, but this is very inconvenient.

If I put the webview in a pane (`.getActivePane().activateItem`) as @mark-hahn's [web-broswer](https://github.com/mark-hahn/web-browser) does, everything works fine?!? Am I missing a setting?

**Comment by bwin** [comment]
Hi pbihler, sorry for not solving your problem, but thanks for showing me (unintentionally) that  `<kbd>tab</kbd>` = <kbd>tab</kbd>. :+1:

**Comment by zcbenz** [comment]
What do you mean by "next input field"? Can you provide a screenshot of what you meant?

**Comment by pbihler** [comment]
![web-tabbing](https://cloud.githubusercontent.com/assets/84478/6562380/eb2f5b62-c698-11e4-8f30-1503d3cd3c43.gif)

**Comment by zcbenz** [comment]
I can reproduce this on Chrome's webview tag, I suggest reporting it to Chromium's issue tracker since we can not fix it on our side.
