### ISSUE TITLE
Allow adding/deleting properties of remote objects

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/electron#1217]
(I've editted this to refine it to a simpler question!) :)

I've spent EONS tracking down an issue related to the limitations placed on 'proxy objects' shared through remote - and I wondered there's a way of perhaps making this easier to trap in future?

I was using delete to remove a (nested) object's properties but that object was created from an object which came from remote.getGlobal - something like this

var PREFS = remote.getGlobal("prefs")
var MYOBJ = {exampleproperty: 1}
$.extend(MYOBJ,PREFS)

I'm trying to 

delete MYOBJ["xxx"]

Where "xxx" might be a property from PREFS or MYOBJ

I'd assumed that $.extend would copy properties from the 'proxy' object to the local one - but somehow MYOBJ ends-up being unmodifiable (delete does NOT remove properties - you can't add new properties either)

Switching to 

var PREFS = JSON.parse(JSON.stringify(remote.getGlobal("prefs)))

fixes the problem BUT I have a TONNE of code to go through to find any possible reference to this - therefore I wondered if there was a way to trap this?

It would be nice if attempts to add/delete properties from a proxy object failed with an error/threw an exception perhaps?

**Comment by shrewdlogarithm** [comment]
TO answer my own question - yes, using $.extend doesn't "free" the proxy object limitation unless you JSON.parse(JSON.stringify... the object in question...

Is there any way to get some sort of error thrown if someone attempts to remove/add a property to a proxy object - because I have about 2500 lines of code which 'may' be doing that and I can't really face trawling it by hand???

**Comment by zcbenz** [comment]
> It would be nice if attempts to add/delete properties from a proxy object failed with an error/threw an exception perhaps?

It sounds like a good idea to me.

**Comment by deepak1556** [comment]
Is there way to trap those cases without using es6 proxies, one way i can think of is create a `non-configurable` remote object with `preventExtension` that would throw in `strict mode` . Or another silly way is using an interceptor in v8 for setter and throw if key is not already present on the object. @zcbenz any ideas for implementation ? also should we change the remote object creation to use `defineProperty` instead of `__defineMethods__` which are non-standard https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__ ?

**Comment by zcbenz** [comment]
We can expose some low level V8 APIs to emulate es6 proxy, but it is too heavy for this. I think we can just wait until es6 proxy becomes stable.

Replacing `__defineMethods__` with `defineProperty` looks good to me.

**Comment by shrewdlogarithm** [comment]
Did anything ever happen with this (there's been a lot of changes in the meanwhile?)

**Comment by zcbenz** [comment]
Having this would be cool, but current capacity of the `remote` module is enough to match most use cases, and it is also not designed to be a generic RPC module. So I'm closing this we don't have any interest in implementing this, but pull request for adding it is still welcomed.

**Comment by wadjeroudi** [comment]
@zcbenz Is there any news about this? 
With this PR #6867, can we use some method to add a new property to a remote object ?
