### ISSUE TITLE
Re-read asar package on page reload

### ISSUE THREAD

**Issue by YuriSolovyov** [atom/electron#1219]
it can lead to artifacts otherwise, because it is probably reads file with old offset
![image](https://cloud.githubusercontent.com/assets/2168518/6545323/9b0d5988-c592-11e4-845b-089400a953f9.png)

**Comment by zcbenz** [comment]
The asar archive's meta information is only read for once and cached during app's whole life time, we should probably check the file's modification date before reading.

**Comment by dustinblackman** [comment]
Is there a method to clear cache? I've run in the a similar problem.

**Comment by YuriSolovyov** [comment]
Thanks a lot, development workflow is much better now.

**Comment by dustinblackman** [comment]
Appreciated! Will give it a shot tonight.

**Comment by YuriSolovyov** [comment]
Now the problem is that `.asar` file is blocked for overwriting while app is running
/cc @zcbenz

**Comment by zcbenz** [comment]
@YuriSolovyov This is intended, reloading page only re-read renderer process code, so updating the asar archive while app is running will result in the main process running old code while the renderer process running the new code, it is definitely going to cause troubles.

**Comment by YuriSolovyov** [comment]
@zcbenz
Why can't we re-read file on reload without locking it?
Even if we can't restart browser process, it is fine, renderer process restart should work in most cases, since it is what usually gets updated (styles, images, scripts).

This is a problem because it kind of breaks typical web development workfow like:
`change -> reload page -> check it`

**Comment by valtersboze** [comment]
any solution to this? i ran in this locked file problem trying to push update to electron app, but cant overwrite asar file in windows, even with admin privileges (in linux sudo ./app solves permissions, file is not locked). need a way to push app.asar updates to clients

**Comment by Daaru00** [comment]
My workaround was an application restart
```javascript
const app = require('electron').remote.app;
app.relaunch();
app.exit();
```

**Comment by Daaru00** [comment]
+1
