### ISSUE TITLE
HTTP requests may never be sent when watching a file

### ISSUE THREAD

**Issue by BenoitZugmeyer** [atom/electron#1268]
I am building a twitter client with `atom-shell`, and I struggle to send http requests sometimes, with the standard `http` library. I create a request, send it (with `.end()`), and sometimes the callback is never called. When a request is stuck like this, opening the devtools and sending another request (to any URL, really, like `require('http').request('http://twitter.com')`) will unstuck the previous request!

After narowing down the issue, I figured out that I reproduced this only when I watch some files with `fs.watch`. But maybe that's not limited to this function.

Here is a minimal application to reproduce:
```js
var app = require('app');
var BrowserWindow = require('browser-window');

app.on('ready', function () {
    // Create a simple window
    var mainWindow = new BrowserWindow({});

    // Load a blank html file
    mainWindow.loadUrl('file://' + __dirname + '/blank.html');

    mainWindow.webContents.executeJavaScript(
        // Here we launch a request. We expect the callback to be called quickly
        "var http = require('http').request('http://www.google.com', function () {" +
        "  console.log('done');" +
        "}).end();"

        // But with this line (watching any file will do), the request is never sent!
        // When commenting this line, the request works as expected
        + "var fs = require('fs').watch('./blank.html', function () {});"
    );
});
```

How I test it:
```
curl 'http://graou.eu/~alk/atom-shell-request.tgz' | tar xvzf -
npm install
npm start
```

* Reproduced in all recent `atom-shell` versions (0.21.2, 0.21.3 and 0.22.1)
* By installing `atom-shell` with `npm install atom-shell`
* On Archlinux, 64bits
* I can't reproduce on OSX
* I don't have this issue with `nw.js`

**Comment by zcbenz** [comment]
It seems to be a bug of our node integration on Linux, thanks for narrowing it down!

As a workaround, you can use [pathwatcher](https://github.com/atom/node-pathwatcher) to watch files, it is a much better alternative than `fs.watch`.

**Comment by deepak1556** [comment]
I am unable to reproduce this with the test case provided on archlinux 64bits, does this happen rarely under some conditions ?

**Comment by BenoitZugmeyer** [comment]
A friend and I reproduce this every time, on different laptops running ArchLinux.

**Comment by BenoitZugmeyer** [comment]
Ok using yet another computer, I can't reproduce the use-case above, but I still have the issue in my application, without any `fs.watch` involved. I try to narrow down the issue, but I can't manage (yet) to reproduce it outside my application. I'll let you know.

**Comment by BenoitZugmeyer** [comment]
Well, I tried really hard to narrow down the issue, still without any success. Sometimes, I reproduce it by adding a `for (var a = 0; a < 1000000; a++) {}` before a request. Sometimes, I can't reproduce anymore when I remove a random JS function before a request.

I feel like this is an atom-shell event loop issue, but I can't prove it. So frustating.

**Comment by BenoitZugmeyer** [comment]
I tried to step inside the code of electron to give you more background on this issue. I figured out that the request blocked just after the TCP `connect` system call: in the node [net.js](https://github.com/atom/node/blob/e5aaa1ad33b3479dbb29df797beca5873e7490dc/lib/net.js#L806-L812) library, `self._handle.connect(req, address, port)` was called but `afterConnect` wasn't.

With my fellow `printf` and my poor knowledge of all this C stuff, I digged inside libuv and the electron code, and it turns out that `uv_run` wasn't called after the `connect` call was sent. It looks like (but excuse my noobiness) `uv__tcp_connect` does not immediately register the new TCP file descriptor to epoll (this is done in the next loop run), so nothing new happens on the epoll fd, and thus `NodeBindingsLinux::PollEvents` is stuck on `epoll_wait`. Thus, the loop is not run, and the `afterConnect` callback is never called.

This explains why if I run another, completely separate http request, the previous one is finally running: the loop is run for the new request, and the `afterConnect` callback of the previous one is called.

You may reproduce with my project:
```
$ git clone https://github.com/BenoitZugmeyer/chwitt-react
$ cd chwitt-react
$ npm install
$ NODE_ENV=production node_modules/.bin/electron .
```
Login, then if your timelines are stuck on loading for more than a few seconds, then you reproduce the issue.

Please let me know if I can help you further for this issue.

**Comment by BenoitZugmeyer** [comment]
I can't reproduce this issue since v0.29.0. I'd have done a git bisect, but since vendors/node history is rewritten each time you update node, older versions can't compile anymore.
