### ISSUE TITLE
HTML5 full-screen API is not implemented

### ISSUE THREAD

**Issue by thyrrestrup** [atom/electron#1314]
Hi
I have embedded a couple of videos from youtube and vimeo in my app. 
But the fullscreen feature does not work - furthermore if the fullscreen button is clicked the scroll functionality of the app stops working until the page is refreshed..

-Tobias

**Comment by bwin** [comment]
Please provide your Atom-Shell and OS version.

Tobias Thyrrestrup <notifications@github.com> schrieb am Do., 26. Mär. 2015
17:32:

**Comment by thyrrestrup** [comment]
Atom.app - v0.22.2
OS X - 10.10.2

Here is my sample app:
```html
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css" media="screen">
            div {
                width:640px;
                margin:0px auto;
                padding:15px;
            }
        </style>
        <title>Hello World!</title>
    </head>
    <body>
        <div>
            <iframe width="640" height="360" src="https://www.youtube.com/embed/dIkHPxeslHQ" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://player.vimeo.com/video/106724185?color=ffffff&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://www.youtube.com/embed/dIkHPxeslHQ" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://player.vimeo.com/video/106724185?color=ffffff&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://www.youtube.com/embed/dIkHPxeslHQ" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://player.vimeo.com/video/106724185?color=ffffff&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://www.youtube.com/embed/dIkHPxeslHQ" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <iframe width="640" height="360" src="https://player.vimeo.com/video/106724185?color=ffffff&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
    </body>
</html>
```

**Comment by zcbenz** [comment]
Currently we don't have HTML5 full-screen API implemented, so the HTML5 version of YouTube player can not enter fullscreen.

**Comment by gliurn** [comment]
will you do it soon? it interest me too

**Comment by zcbenz** [comment]
> will you do it soon? it interest me too

No, it is quite low priority.

**Comment by jameslk** [comment]
I ran into this issue as well. Devs- it seems this has been fixed on nwjs, so if it's any help in getting the problem resolved, here's the relevant commit and ticket:
https://github.com/nwjs/nw.js/commit/a3a537bb354f709172e71e7c985d4ac6b8ee1d48
https://github.com/nwjs/nw.js/issues/55

For the time being, I'm guessing I will have to mock the html5 fullscreen API, reimplementing it via calls to the [equivalent features in the BrowserWindow API](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#browserwindowsetfullscreenflag). If anyone else has any other ideas, I'd be interested to know.

**Comment by jameslk** [comment]
Here's my fullscreen monkey patch script if anyone needs it (note: its using ES6):
https://gist.github.com/jameslk/f59714b04d6c199ecd2b

I didin't go through the additional steps of figuring out how to mock trigger the :full-screen pseudo classes and centering on content. My guess is the easiest way to handle that will be to use z-index with a maximum value on the content and set it to 100% width/height.

**Comment by thyrrestrup** [comment]
Hi
I'm curious how to use the fullscreen patch?
Could you please give an example?

-Tobias

**Comment by jameslk** [comment]
@thyrrestrup The monkey patch should fix the HTML5 API without having to do anything else. For example, if [`requestFullscreen`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen) is called on an element, the app will go into fullscreen. This is how to load it:

```javascript
var fullscreen = new Fullscreen();
fullscreen.implementHtml5FullscreenApi();
```

**Comment by thyrrestrup** [comment]
@jameslk thanks  I'm unsure how I should require or import the atom-shell-fullscreen.js file and if this is done in the renderer or in the browser? - If this is done in the renderer could this be done through the preload script?

**Comment by jameslk** [comment]
@thyrrestrup You will need to run it through an ES6 to 5 transpiler if you haven't done that already ([like this one](https://babeljs.io/repl/)). Then require it in on the browser side (where things are displayed, like HTML and CSS--*not* on the side that loads the browser frames).

**Comment by steelbrain** [comment]
@jameslk in case you don't wanna go through the transpilation process https://github.com/atom/electron/issues/1328#issuecomment-89810268

**Comment by jameslk** [comment]
@steelbrain Ah nice, thanks for the tip. I'll try that out.
