### ISSUE TITLE
WebView tag doesn't pass along NTLM (Windows) Authentication credentials

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1318]
To repro: (it sucks)

1. Set up a Windows Active Directory Domain
1. Set up an IIS server that _only_ accepts Windows Auth authenticated users
1. Visit it in Chrome - hooray! 
1. Create an Atom Shell app with a WebView tag that points to said IIS server
1. Now you get 401 Sad Panda

**Comment by zcbenz** [comment]
Does the page in `BrowserWindow` pass NTLM?

**Comment by paulcbetts** [comment]
@zcbenz Not sure, it's hard to test because we don't actually use NTLM either, we're just seeing reports of it at other companies. I'll try to set something up locally.

**Comment by felicienfrancois** [comment]
It does not pass basic authentication neither
https://github.com/atom/atom-shell/issues/1362
