### ISSUE TITLE
API to inspect Service Workers

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1331]
One of the things that will be super useful for Desktop applications that build on top of remote content is the Shared [Service Workers API](http://www.html5rocks.com/en/tutorials/service-worker/introduction/), which basically lets you have a programmable "proxy" for network requests at a high-level and trump normal browser caching rules. With this, you can write offline apps without having to ship all of your app locally / your update story is way saner, etc etc etc.

This is super cool, but without `chrome://serviceworker-internals` it's *way* harder (read: impossible) to know what's going on (if your list is empty, visit https://events.google.com/io2015 a few times). 

To that end, I propose a few additions to the WebContents API:

* `hasServiceWorker` - determine if this page has a registration for a service worker
* `unregisterServiceWorker` - Kill any registration for a service worker if it exists
* `openServiceWorkerDevTools` - Open DevTools for the service worker associated with this page

Thoughts?

**Comment by zcbenz** [comment]
I'm not familiar with Service Workers, but the APIs look good to me. And in latest release you should be able to visit `chrome://serviceworker-internals` in atom-shell (thanks to @hokein).

**Comment by paulcbetts** [comment]
@zcbenz That looks like it works, I think we might be able to work with that. Thanks for the tip!
