### ISSUE TITLE
enforce a aspect ratio when resizing

### ISSUE THREAD

**Issue by mafintosh** [atom/electron#1336]
Is there a way to enforce a aspect ratio over the browser window so when the user resizes the window it will force him/her to keep that aspect ratio? (similar to how quicktime resizes on osx)

**Comment by zcbenz** [comment]
Currently there is no API to do that.

**Comment by mbarthelemy** [comment]
[Now there is a way to do this on Mac OS X.](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowsetaspectratioaspectratio-extrasize)

**Comment by zcbenz** [comment]
Fixed by #2250.

**Comment by bluntspoon** [comment]
Is there any plan to implement something similar for Windows?

**Comment by jaehayoo** [comment]
ref : https://github.com/electron/electron/pull/18306
