### ISSUE TITLE
Tray does not appears on Linux

### ISSUE THREAD

**Issue by remss** [atom/electron#1347]
The tray example does not work on Linux. The tray is not shown.
Tested with atom-shell 0.22.3 + Ubuntu 14 and atom-shell 0.22.3 + Debian Jessi

    var app = require('app');
    var Menu = require('menu');
    var Tray = require('tray');

    var appIcon = null;

    app.on('ready', function(){
      appIcon = new Tray('icon.png');
      var contextMenu = Menu.buildFromTemplate([
        { label: 'Item1', type: 'radio' },
        { label: 'Item2', type: 'radio' },
        { label: 'Item3', type: 'radio', checked: true },
        { label: 'Item4', type: 'radio' },
      ]);
      appIcon.setToolTip('This is my application.');
      appIcon.setContextMenu(contextMenu);
    });

**Comment by paulcbetts** [comment]
Tray has been working for us, though whether the tray icon actually shows up is super distro-specific (some distros don't allow tray icons at all)

**Comment by remss** [comment]
I agree that it is distro specific, but atom-shell doc says that Tray is supported on Linux with AppIndicator or GTK => https://github.com/atom/atom-shell/blob/master/docs/api/tray.md
So i think this is a bug because both Ubutu 14 and Debian Jessi use AppIndicator.

**Comment by zcbenz** [comment]
Yeah it supports app indicator, and it used to work on Ubuntu 14.04, it seems to be a regression.

**Comment by davej** [comment]
Can confirm, also experiencing this issue on Ubuntu 14.04.

**Comment by sergiovilar** [comment]
I'm having this issue in Electron 0.29.2

**Comment by alexandrkazah** [comment]
I'm having an issue in Electrong 0.29.1 when trying to initialise tray, give me following error "A JavaScript error occured in the browser process
Uncaught Exception:
TypeError: Error processing argument 0.
    at TypeError (native)
    at EventEmitter.<anonymous> (/Users/xxxxxxx/xxxxxxx/first-electron-app/main.js:34:13)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)" 
Line 34 in "main.js" is the initialisation line. Here it is ("appIcon = new Tray('file://' + __dirname + '/tree.png');"
Any help would be much appreciated.

**Comment by alexandrkazah** [comment]
Found the problem I had. When creating a new Tray it does not recognise the path I put in the argument. I had to use 'path' module to load the location of the image for the icon. 
I.e.: var iconIdle = path.join(__dirname, 'images', 'tree.png');
  appIcon = new Tray(iconIdle);
Then it works.

**Comment by sergiovilar** [comment]
I need to install `libappindicator1` to get the tray working, is that right?

**Comment by alexandrkazah** [comment]
sergiovilar, no you do not need it at all, only "tray".

**Comment by sergiovilar** [comment]
@alexandrkazah unfortunately I had to install `libappindicator1` on Ubuntu 14.04+ to get the Tray working.

**Comment by zcbenz** [comment]
@sergiovilar Yeah the `libappindicator1` has to be installed to make Tray working on Ubuntu, thanks for finding it out!

**Comment by sergiovilar** [comment]
@zcbenza any clue to get the Tray working on Fedora 22? `libappindicator1` is not available on dnf repositories.

**Comment by sergiovilar** [comment]
@zcbenz any clue to get the Tray working on Debian 8? The Tray doesn't appear even with `libappindicator1` installed.
