### ISSUE TITLE
Cursor functionality broken on Ubuntu when running in Virtualbox

### ISSUE THREAD

**Issue by gossel-j** [atom/electron#1352]
I tested on v0.22.3, v0.22.2, v0.22.1 and v.0.21.3 with a simple hello world program.
At v0.21.3 everything works fine.
But since v0.22.1 the cursor always stay normal (not the one for selecting text) and I can't select text anymore, I found this bug updating from atom v0.188.0 to v0.189.0, this is my issue on atom [#6219](https://github.com/atom/atom/issues/6219)

Archlinux up-to-date
io.js v1.6.3
npm 2.7.4

**Comment by paulcbetts** [comment]
Are you using a virtual machine? What is the output of `xinput`?

**Comment by gossel-j** [comment]
Yes i use a VM
```
% xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ VirtualBox mouse integration            	id=9	[slave  pointer  (2)]
⎜   ↳ VirtualBox USB Tablet                   	id=10	[slave  pointer  (2)]
⎜   ↳ VirtualBox USB Multi-Touch              	id=11	[slave  pointer  (2)]
⎜   ↳ ImExPS/2 Generic Explorer Mouse         	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
```

**Comment by gossel-j** [comment]
chromium since version 43 works again in virtualbox, tested on my own VM

**Comment by zcbenz** [comment]
Closed by #1755.

**Comment by seanohollaren** [comment]
Is there an ETA for these changes being reflected in the stable, released codebase?  I'm on Atom 1.0.2 and the issue is still there.

**Comment by chrisabrams** [comment]
I'm on latest VBox and Atom, and having this issue.

**Comment by kad0xf** [comment]
Same issue happens with me on a Ubuntu running as inside a VirtualBox virtual machine.

**Comment by johny-mnemonic** [comment]
Which Atom release you are trying guys?
If I am not mistaken, latest release of Atom (1.0.11) doesn't contain this fix.
This fix went to electron v0.27.0 and update of Atom from electron v0.26.0 to electron v0.30.6 was done after release of Atom 1.0.11. It is stil in Atom master branch, waiting for release, if I understand it correctly.

**Comment by kad0xf** [comment]
Yes, I am using Atom 1.0.11. Is there a way to try the fix?

**Comment by johny-mnemonic** [comment]
I guess, the correct answer is, you need to wait for new Atom release.
Unless you are skilled enough to build Atom from source. I am not.

**Comment by gossel-j** [comment]
Actually I built it from master few days ago and works great now
Waiting for next release now

**Comment by kad0xf** [comment]
@gossel-j  can you share your build from master?

**Comment by gossel-j** [comment]
atom has been upgraded already
