### ISSUE TITLE
-webkit cursors don't work (-webkit-drag, -webkit-zoom-in, ...)

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1361]
The following css properties have no effect:
```css
cursor: -webkit-drag;
cursor: -webkit-dragging;
cursor: -webkit-zoom-in;
cursor: -webkit-zoom-out;
```

**Comment by zcbenz** [comment]
Can you provide the information of you operating system?

**Comment by felicienfrancois** [comment]
Windows 8.1 x64 with atom-shell 0.22.3

**Comment by bengotow** [comment]
We've run in to this as well. It seems only a subset of cursors are available on Windows. We found that `cursor: row-resize` didn't work, but `ns-resize` did.

**Comment by graphnode** [comment]
Why the difference between Chrome and Electron? It's because of Chromium?

I tested [this page](http://trac.webkit.org/export/37902/trunk/WebCore/manual-tests/cursor.html) on Electron and a great number of cursors were missing.

**Comment by felicienfrancois** [comment]
Thank you @zcbenz for the fix
