### ISSUE TITLE
HTTP Basic Authentication support

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1362]
It seems atom shell does not support basic authentication, neither in BrowserWindow nor in webview.

It could be provided with an event in BrowserWindow and webview which defaults to a native dialog prompt.

**Comment by felicienfrancois** [comment]
This feature is important as there is no possible workaround.
Also, in the webdev world, a lot of people uses basic authentication for development/test server and it may be blocking for some people.
So Atom editor and other dev tools based on atom shell should be able to support that.

**Comment by steelbrain** [comment]
:+1:

**Comment by mark-hahn** [comment]
I just had a user of the atom `web-browser` complain about this. https://github.com/mark-hahn/web-browser/issues/49

**Comment by FLasH3r** [comment]
+1

**Comment by MihaiValentin** [comment]
+1, this is a very important feature, which currently has no workaround

**Comment by Clarkey** [comment]
+1. Getting 401 when authenticating to IIS web servers. Fine in Chrome.

**Comment by MihaiValentin** [comment]
However, on the https://github.com/atom/electron/releases page, at release `electron v0.25.3` is mentioned "Enable NTLM / Kerberos authentication.", though I can't find any commit regarding it.

Any idea what has been done here?

**Comment by paulcbetts** [comment]
https://github.com/atom/brightray/pull/104 is the fix to enable NTLM auth

**Comment by MihaiValentin** [comment]
@paulcbetts thanks, there was the confusion between taking the NTLM from the system and allowing the user to login through NTLM from a prompt, just like in Chrome

**Comment by MihaiValentin** [comment]
Would the answer from http://stackoverflow.com/a/16613116/1030269 help here?

Is `chrome.webRequest.*` API available in atom shell?

**Comment by paulcbetts** [comment]
> thanks, there was the confusion between taking the NTLM from the system and allowing the user to login through NTLM from a prompt, just like in Chrome

Aha, this is the disconnect. Yeah, so basically anything that requires us to ask a username/password will currently fail at the moment. This is On My List for some point soon

**Comment by dataich** [comment]
+1

**Comment by reinpk** [comment]
+1

**Comment by vai** [comment]
Any movement on this? Latest release from electron home page still fails on even the simple windows authentication scenario. Opening up electron to the intranet app space (and killing 15yo legacy browsers) would be fantastic.

**Comment by mkozakov** [comment]
+1

**Comment by mcasperson** [comment]
+1

**Comment by chrisdewar** [comment]
+1

**Comment by flashhhh** [comment]
+1

**Comment by petrfelzmann** [comment]
+1

**Comment by Kikketer** [comment]
+1

**Comment by Anduin2017** [comment]
+1

**Comment by harryi3t** [comment]
I can see that support for basic auth was added. What about windows (NTLM) and digest auth which also results in a pop-up in a browser? Any workaround for these other auths?

**Comment by sibaz** [comment]
or add WebRequest.OnAuthRequest as per https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired so it can be worked around
