### ISSUE TITLE
webview redirects dont update the url

### ISSUE THREAD

**Issue by awsmsrc** [atom/electron#1364]
WebView is not updating its src url on redirect as I would expect. 
What I expect could be wrong and this could be intentional

Below is a contrived example, consider a webview showing a very simple local server

'http://localhost:8080/a' has a link to 'http://localhost:8080/b'
'http://localhost:8080/b' redirects to ''http://localhost:8080/c'
'http://localhost:8080/c' is rendered
but getUrl() returns 'http://localhost:8080/b'

I have a repo with a reproducible example if this is unclear

**Comment by deepak1556** [comment]
Server-side redirects dont get committed to navigation entry which is what `getUrl` depends on. But there are events that can be triggered during [redirects](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/browser/web_contents_observer.h&sq=package:chromium&rcl=1428305908&l=219), probably can have an api `did-redirect` with the original and new urls as payload. Would that help ?

/cc @zcbenz

**Comment by awsmsrc** [comment]
I'm not sure what the right way to do it is.

i feel like there *should* be some UI for current location?
I'm implementing an oauth client and the access token is provided as a get parameter on redirect.

I'm now relying on the did-get-redirect-request event which works.

As stated in the original comment this *may* be a non issue
