### ISSUE TITLE
Transparent window renders 1px white line when given odd size

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1366]
On Windows (I'm on Windows 8.1, specifically), create a transparent window (with `resizable` and `frame` set to false).
After the window is shown, call `setSize` and pass in an odd number for the width and/or height.
You will see a rendering artifact, a 1px white line on the right or bottom edge of the window, as follows:
![](https://s3.amazonaws.com/f.cl.ly/items/1Y1C3J1B3d3w2s0W472v/Image%202015-04-06%20at%2012.16.13%20PM.png)

For now our workaround is to simply ensure that we never pick an odd window size, but this is a little wonky.

**Comment by tommoor** [comment]
@CharlieHess have you seen a flash of white when resizing the transparent window? We're seeing this and it seems as though it might be related to your 1px of white...

**Comment by CharlieHess** [comment]
@tommoor: We noticed too many rendering glitches when resizing the window, so we avoid it altogether and only set an initial size.

**Comment by zcbenz** [comment]
Unable to reproduce on 0.36.2.
