### ISSUE TITLE
console.log in renderer process only prints the first argument in stdout

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1368]
Expected behavior, to be able to call something like:

`console.log(arg1, arg2, arg3)` and see the output in stdout separated by commas.

Actual behavior is that only the first argument is output.

**Comment by deepak1556** [comment]
yup was observing this for quite sometime wasnt sure of the cause though, as we just print the message obtained from the webcontents [here](https://github.com/atom/brightray/blob/master/browser/inspectable_web_contents_impl.cc#L351)

**Comment by maxogden** [comment]
this issue is a duplicate of https://github.com/atom/atom-shell/issues/621

**Comment by tommoor** [comment]
I _did_ search for open issues but I guess the previous was closed. I think that at least one of these issues should be left open - perhaps tagged as blocked upstream?

**Comment by zcbenz** [comment]
We now disabled Chromium's logging completely and nothing from renderer will be printed anymore by default.
