### ISSUE TITLE
Adding LSUIElement to Info.plist crashed

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#1369]
Adding LSUIElement to my app's info.plist causes the app to crash at launch.

I think this is similar to issues with NW.js:

https://github.com/nwjs/nw.js/issues/451
https://github.com/nwjs/nw.js/issues/1462

**Comment by zcbenz** [comment]
The same thing happens for Chrome browser too, so we are not going to fix this.

**Comment by jorangreef** [comment]
Do you understand why it happens for Chrome?

**Comment by pronebird** [comment]
Is it fixed?

**Comment by ryemundo** [comment]
I had the same problem so instead of using LSUIElement I used NSUIElement and it worked perfectly.
