### ISSUE TITLE
Ctrl-C (copy) Keyboard Shortcut causes application to lock

### ISSUE THREAD

**Issue by mattcollier** [atom/electron#1372]
atom-shell v0.22.3, Debian Jessie 64bit / Gnome.

I recently noticed that if I attempt to copy text from my app by highlighting text and using the Ctrl-C keyboard shortcut, my app locks  up completely.  The close window will not function.  I terminate the app by doing Ctrl-c at the console.

On another system with Debian Jessie 32 bit and atom-shell 0.22.1 I do not have this issue.  Ctrl-c functions as expected.

I am not doing anything to override the global defaults.

**Comment by zcbenz** [comment]
Currently using clipboard in renderer process would crash on some Linux distributions, you can use `require('remote').require('clipboard')` to work around it.

**Comment by mattcollier** [comment]
This issue appears to be resolved in 0.24.0.
