### ISSUE TITLE
Geolocation doesn't work

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1376]
Useful to use HTML5 geolocation API for example

Part of chrome webview API
https://developer.chrome.com/apps/tags/webview#permissionrequest

**Comment by paulcbetts** [comment]
Permissions are automatically rigged to just say Yes, you don't need to do this

**Comment by felicienfrancois** [comment]
Does not seems to work with geolocation under windows 8.1 (both webview and browser-window)
Permission request is never answered.

```javascript
navigator.geolocation.getCurrentPosition(function success(position) {
    // never called
}, function error(error) {
    // never called
});
```

**Comment by paulcbetts** [comment]
Hm, I think this is a bug specific to Geolocation, WebRTC works currently without permission requests

**Comment by zcbenz** [comment]
It is a regression that geolocation doesn't work, Google might have changed their geolocation API.

**Comment by owencm** [comment]
I'm also seeing this. The geolocation example given in MDN (https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) is simply returning `ERROR(3): Timeout expired` to me.

**Comment by bruce** [comment]
Any update on this? Any pointers on what can someone can do to help?

**Comment by aarongifford** [comment]
I am also stuck on this issue.  Would appreciate an update.

**Comment by payne8** [comment]
Also stuck on this issue.

**Comment by payne8** [comment]
It doesn't look like Google has changed the API endpoint.

```
From Google documentation:  https://www.googleapis.com/geolocation/v1/geolocate?key=
From Electron repo: https://www.googleapis.com/geolocation/v1/geolocate?key=
```

(Google Documentation)[https://developers.google.com/maps/documentation/geolocation/intro?hl=en]
(Electron repo source)[https://github.com/atom/electron/blob/db2042f5618a41747a2beb66cbc112c589e3a197/atom/browser/atom_access_token_store.cc]
They might have changed the format expected on the return. I am not sure.

**Comment by payne8** [comment]
I just built with my own Google API key and it doesn't seem to have made a difference. I am very new at this so I am not sure about the best way to debug this. Does anybody have any ideas?

**Comment by payne8** [comment]
Verified it works! Thank you so much @zcbenz

**Comment by Nashorn** [comment]
Running Electron 6.0.0-beta.4 - Geolocation access is not prompted, fails silently, no error. Works in chrome. Using localhost to test.

**Comment by chenxizhang** [comment]
same issue ,it looks not work in China anyway. Do we have some workaround?

**Comment by sirnewton01** [comment]
> same issue ,it looks not work in China anyway. Do we have some workaround?

It appears that China is a special case according to the HTML geolocation API. See the notes at the bottom of this page for more details: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
