### ISSUE TITLE
chrome.desktopCapture API

### ISSUE THREAD

**Issue by maxogden** [atom/electron#1380]
Currently in Chromium there is only support for capturing the entire desktop (using getUserMedia with `chromeMediaSource: "screen"`. I looked at the Chromium issue tracker and I can't find anything on the roadmap for better sharing granularity (e.g. to only share 1 app window instead of the entire screen). In Chrome there is a much nicer [`desktopCapture`](https://developer.chrome.com/extensions/desktopCapture) API that implements this really nice popup UI  as well as per-OS-window or per-browser-tab or entire screen sharing.

![screen shot 2015-04-07 at 1 08 35 pm](https://cloud.githubusercontent.com/assets/39759/7032411/7c3f1af8-dd27-11e4-8bdf-47147a271b15.png)

This is probably a longshot, but how hard would it be to add the desktopCapture Chrome Platform API to Atom Shell? I can't even find the google repo where desktopCapture is implemented...

**Comment by paulcbetts** [comment]
This would be :cool:, looks like it starts in https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/media/desktop_media_picker.h&sq=package:chromium&rcl=1428421466 and https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/extensions/api/desktop_capture/desktop_capture_api.cc&sq=package:chromium

**Comment by ffdd** [comment]
+1 especially https://developer.chrome.com/extensions/tabCapture

**Comment by petethepig** [comment]
+1

**Comment by Quramy** [comment]
+1

**Comment by icetraxx** [comment]
+1

**Comment by hotrush** [comment]
:+1:

**Comment by octalmage** [comment]
Would love to see this implemented!

**Comment by tommoor** [comment]
If anyone is interested in taking this on, we'd be willing to sponsor someone to work on this, get in touch with me if that sounds like an interesting challenge :smile: 

There is a lot of reference code in nw.js as they have already implemented this feature, albeit with some questionable api design choices.

**Comment by rogeru** [comment]
+1

**Comment by johrue** [comment]
+1

**Comment by hokein** [comment]
I will take this issue. But before implementation, some details of the API design are needed to be disscussed. There are two options we can provide in Electron as far as I can see:

* Option1: Align with Chromoium upstream way by implementing a `win.mainContents.chooseMediaList` API. The API will prompt a Chromium picker dialog to allow user choose which window/screen they want to share.
The API usage is illustrated as follows:

```javascript
mainWindow.webContents.chooseDesktopMedia(["screen", "window"], function(error, desktopId) {
  if (error) {
    console.log('Desktop Capture access rejected.');
    return;
  }
  navigator.webkitGetUserMedia({
    audio: false,
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: desktopId,
        minWidth: 1280,
        maxWidth: 1280,
        minHeight: 720,
        maxHeight: 720
      }
    }
  }, gotStream, getUserMediaError);
});
```

* Option2: We don't implement the Chromium picker dialog in Electron side by providing a more details information for each captured window/screen. So the API is like:

```javascript
var screenCapture = win.webContents.getMediaList(["window", "screen"]);

screenCapture.on('source-add', function(item) {
 // item.name: the name of captured screen/window shown to the user
 // item.image: the thumbnail NativeImage of captured screen/window.
 // item.id: the id of captured screen/window used in navigator.webkitGetUserMedia 
 if (item.name == 'Electron') {
   navigator.webkitGetUserMedia({
     audio: false,
     video: {
       mandatory: {
         chromeMediaSource: 'desktop',
         chromeMediaSourceId: item.id,
         minWidth: 1280,
         maxWidth: 1280,
         minHeight: 720,
         maxHeight: 720
       }
     }
   }, gotStream, getUserMediaError);
 }
});

screenCapture.on('source-change', function(item) {});
screenCapture.on('source-remove', function(item) {});
```

Compared to option 1, option 2 provides the possibility of custumization to users of Electron(They can do whaterver they need, e.g. implement a customized dialog, and select a fixed window in code). On the other side, user are benefited from the nice Chromium picker dialog in option 1, but they also loose customization in cost. 

We would like to hear the feedbacks from users. Suggestions are welcomed :smile:

**Comment by ffdd** [comment]
I think most Electron based apps visually 'pretend' not to be a browser,
while simultaneously taking advantage of all the features browsers can
offer. My suggestion is to start with option 2 because If you only
implement option 1, some Electron user will want to create a custom picker
dialog that fits their application's design and this ticket will re-open
soon enough.

rey.sc

**Comment by paulcbetts** [comment]
Option 2 makes more sense to me, you can always use the information in a JS-based API to build that picker

**Comment by tommoor** [comment]
Another advantage of Option 2 is that you could add cleverness, like adding a shortcut to share the same screen as you previously shared or defaulting to it. The implementation could end up even nicer than Chrome's.

Gets my vote :+1:

**Comment by octalmage** [comment]
All about option 2 here. If it's implemented in a way that the picker from option 1 could be created in userland, it's a win-win.

**Comment by RDLemos** [comment]
+1

**Comment by adileo** [comment]
+1

**Comment by mzahor** [comment]
+1

**Comment by SidneyS** [comment]
+1

**Comment by Morantron** [comment]
+1

**Comment by ayhankuru** [comment]
:+1:

**Comment by apurv** [comment]
+1

**Comment by Raj123456788** [comment]
Hey Guys,
                I am unable to get desktop picker dialog for available  sources.  I am newbie can someone guide me what am I missing?

**Comment by jlord** [comment]
Hi @Raj123456788 — Can you open a new issue describing your problem, the operating system you're using and version of Electron? If you can also provide code that can be used to reproduce your issue that would be spectacular. Thanks, that will help us get to the root of your issue :sparkles:

**Comment by Raj123456788** [comment]
Done!!

**Comment by Raj123456788** [comment]
Can anyone please answer this question: atom/electron#4432

**Comment by iclems** [comment]
FYI when Electron updates to Chrome 70, we should get getdisplaymedia automatically when using experimental features.

**Comment by CapOM** [comment]
See https://github.com/electron/electron/issues/16513
