### ISSUE TITLE
Transparent windows can't be created below a certain size threshold

### ISSUE THREAD

**Issue by willbarrett** [atom/electron#1392]
Observed on Windows 8.1 and Ubuntu 14.04 (unity). Does not appear to affect Mac OSX

Creating a transparent window smaller than 160px square results in a white background. If both sides are shorter than 160px, the window will not be transparent. If one side is longer than 160px, the window will have transparency.

**Comment by zcbenz** [comment]
Unable to reproduce on 0.36.2.
