### ISSUE TITLE
Tray context menu should open with a single left click on Windows

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#1393]
The tray context menu only opens with a right click or a double left click on Windows.

It should open with a single left click on Windows or have the option to do this.

**Comment by mib4fun** [comment]
+1

**Comment by hokein** [comment]
On Windows, a single left click on tray icon will trigger the `clicked` event of `Tray`.

@zcbenz , how about providing a `tray.popContextMenu()` API allowing developer to pop the context menu without user's interface. Currently we can implement this API on Windows and OS X(there is no such API in current Linux implements).

With this API, we can achieve this issue's feature via the following code:
```
tray.on('clicked', function() {
   tray.popContextMenu();
})
```

**Comment by jorangreef** [comment]
That would be great. It would also leave the choice up to the developer, what they want the left click to do. I know some people like to use the left click to toggle the status and then use the right click to open the menu.

**Comment by jorangreef** [comment]
At the moment, there is also no way to update a tray menu item label, without recreating the tray menu, but this causes the tray menu to disappear if the user has it open so there is no way to give constantly updating status information via the tray menu at the moment, e.g. "Searching for networks...", "Found 3 networks..." etc. while the user is watching.

Would popContextMenu be a way to provide this? i.e. After recreating the tray menu, the tray menu would be hidden, but then popContextMenu could be called to keep it showing?

**Comment by zcbenz** [comment]
@hokein This solution looks good to me.

**Comment by hokein** [comment]
Closing it since a `popContextMenu` API has been supported in #2232.

**Comment by postadelmaga** [comment]
@hokein 
On Linux _["clicked"](https://github.com/electron/electron/issues/1393#issuecomment-121129103)_ event  ( ) do not work  for left click.
  
Anyway to open the tray menu with left click on Linux ?
