### ISSUE TITLE
Global shortcut API: add support for meta-key / windows-key

### ISSUE THREAD

**Issue by FunkMonkey** [atom/electron#1395]
It is currently not possible to assign global shortcuts to a windows-key-combination.

Thanks!

**Comment by paulcbetts** [comment]
Assigning shortcuts to the Windows key is a pretty bad idea in general, Explorer owns that key and very often changes / claims new shortcuts with different OS releases

**Comment by FunkMonkey** [comment]
I agree that there is a certain chance of collisions, but...

a) I believe there is a higher chance of accidentally overriding application-specific shortcuts with a global shortcut like `ctrl+alt+b` than with a windows-key-shortcut (even the [global-shortcut documentation](https://github.com/atom/atom-shell/blob/master/docs/api/global-shortcut.md) overrides `ctrl+x` globally in its example...)

b) I don't believe atom-shell should enforce its beliefs about what good shortcut-combinations are and what not upon the developers and users (especially if users can choose shortcuts themselves - they should not be restricted in the way they want to customize their applications and can make their own informed decisions). This is even more true in terms of point a).

c) Not sure, but I believe reserved windows-key-shortcuts can not be easily overwritten anyway, but have to be disabled first in the [registry](http://windowssecrets.com/forums/showthread.php/153042-Disable-some-hotkeys-in-Win-7-Home-Premium).

**Comment by zcbenz** [comment]
Windows forbids overriding many <kbd>Win</kbd> global shortcuts, to override them the program has to install keyboard hooks or low level drivers, there is no normal way to work around the limitation.

I'm closing this as won't fix.

**Comment by FunkMonkey** [comment]
@zcbenz: Not wanting to install keyboard hooks is absolutely reasonable and I'd also argue against that. My intention was not to be able to override existing `win` shortcuts, but to be able to use the ones that are free (which including shortcuts with multiple modifiers are still a lot). 

Considering shortcut collisions between applications may exist with and without the `win` key, I don't think the `win` key should be treated any different than `ctrl` or `alt`. Trying to register a global shortcut that already exists in the system should always throw an exception anyway (again: no matter whether `win` or not).

Independent of the state on Windows, Linux users should be able to use a meta key like the `win` key. 

Having said all that, implementing the behaviour seems complicated at the moment anyway, as Chromium's [accelerators](https://code.google.com/p/chromium/codesearch#chromium/src/ui/base/accelerators/accelerator.h&sq=package:chromium&type=cs&rcl=1429443319&l=27) don't provide `win` key support and the `win` modifier is also not passed to Windows' [RegisterHotKey](https://msdn.microsoft.com/de-de/library/windows/desktop/ms646309%28v=vs.85%29.aspx) function from the [GlobalShortcutListener](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/extensions/global_shortcut_listener_win.cc&sq=package:chromium&type=cs&q=RegisterAcceleratorImpl&l=67)... Thus I guess Chromium would need to be updated first...

**Comment by zcbenz** [comment]
@FunkMonkey I didn't realize the <kbd>Win</kbd> is ignored in GlobalShortcutListener, it makes sense to add support for it.

**Comment by muelphil** [comment]
As there currently was no solution to register hotkeys including the <kbd>Win</kbd> key, I created a native node module to handle this: `global-hotkey`. You can find it by following [this link](https://www.npmjs.com/package/global-hotkey).

**Comment by jdms754** [comment]
> As there currently was no solution to register hotkeys including the Win key, I created a native node module to handle this: `global-hotkey`. You can find it by following [this link](https://www.npmjs.com/package/global-hotkey).

The repository is private - can you please make it public?

**Comment by muelphil** [comment]
> The repository is private - can you please make it public?

The repository is not public - thanks for pointing it out! Please note that it is under development. If you encounter any issues, please let me know.
