### ISSUE TITLE
power-monitor module causes segfault on Mac

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1420]
The following code on the last two versions of atom-shell causes the app to segfault on start:

```javascript
var power = require('power-monitor')
```

results in:

```
Segmentation fault: 11
```

@paulcbetts mentioned that they are using this module without troubles - I believe on Windows. We've reproduced this on two Mac's so far.

**Comment by paulcbetts** [comment]
We're using it on all platforms without issues

**Comment by zcbenz** [comment]
You have to use it after the `ready` event of `app` gets emitted. We should throw an exception instead of crashing though.

**Comment by tommoor** [comment]
Oh wow, we should update the documentation to state this at the least :smile:

**Comment by paulcbetts** [comment]
> Oh wow, we should update the documentation to state this at the least :smile:

Sure, but that's basically everything in Atom Shell, if you try to do stuff before `ready` that is more complicated than "parse arguments", you're gonna have a Bad Time

**Comment by tommoor** [comment]
It's common practice to include require's at the top of a file though, I wouldn't expect that to cause a segfault if I'm not actively using it until after the ready event.. I believe this is easily solved for others with my doc PR anyway..

**Comment by paulcbetts** [comment]
> It's common practice to include require's at the top of a file though, I wouldn't expect that to cause a segfault if I'm not actively using it until after the ready event.

That's legit, `require`ing itself shouldn't ever cause a crash
