### ISSUE TITLE
about vlc npapi  not smooth and not load in extra-plugin-dirs

### ISSUE THREAD

**Issue by bushadam** [atom/electron#1423]
i want play .mov  and do with vlc plugin

one of my video file  it work perfectly in chrome and nw.js 
this video in atom-shell not smooth

and on widows the npapi only can load in registry,not load in extra-plugin-dirs

**Comment by bushadam** [comment]
use vlc npapi plugin 2.2 not smooth,but use vlc 2.1.5 it work perfectly

**Comment by zcbenz** [comment]
NPAPI support is going to be disabled after we upgraded to Chrome 42 and removed after Chrome 45, so we will not fix bugs with NPAPI plugins.

I'm closing this as won't fix.
