### ISSUE TITLE
Add "" to search paths for package.json to allow package.json to be placed in resources

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#1425]
It would be great if "" could be added to the search paths for the app's package.json at:

https://github.com/atom/atom-shell/blob/master/atom/browser/lib/init.coffee#L58

This would make it possible for an app to keep all it's resources in the resources directory without having to create an additional app directory just to store the main.js and package.json files. This simplifies app management, e.g. resourcesPath can be used directly to access all resources including js, and also simplifies build scripts which don't need to create an additional app directory.

This could be added last to the search paths so as not to cause any unnecessary cache misses for people who use app/package.json or app.asar.

**Comment by zcbenz** [comment]
The resourcesPath is also used to store Chromium's resource files, and on different platforms we have different resource files under resourcesPath. So putting your app under resourcesPath will mess up your app's files with Chromium's resource files, and some important files might be overwritten in future when Chromium have more resource files.

I'm closing this as won't fix.
