### ISSUE TITLE
Accessing process.stderr from renderer process

### ISSUE THREAD

**Issue by Trixt0r** [atom/electron#1429]
Is it correct that I get such an error when I access `process.stderr` from the renderer process:

`[21892:0416/110229:INFO:CONSOLE(123)] "Error: UnknownSystemError: Unknown system error, uv_pipe_open`

Got this error when requiring the [bluebird](https://www.npmjs.com/package/bluebird) package.
The error occurred on OS X 10.9. I didn't test it on other platforms.

If the behavior is correct, I will forward this issue to the bluebird devs.

-Trixt0r

**Comment by steelbrain** [comment]
Note: Atom-Shell uses io.js which has promises natively, You don't need bluebird with it.

**Comment by Trixt0r** [comment]
Yes, I know. But I am also using [sharp](https://www.npmjs.com/package/sharp), which relies on bluebird...

**Comment by zcbenz** [comment]
The `UnknownSystemError` means something between OS X and Electron has interrupted the system call, it could be virus scanner or firewall software.
