### ISSUE TITLE
async fs methods create errors synchronously

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron#1432]
Calling `fs.readdir` on a path inside an `.asar` archive that does not exist seems to create the error synchronously and calls the callback before `fs.readdir` returns.

Should this follow the node convention and not invoke the callback before a next tick completes?

I noticed this from profiling startup in Atom and saw `createNotFoundError` show up in the profile a lot but associated with `fs.readdir` calls.

**Comment by zcbenz** [comment]
> Should this follow the node convention and not invoke the callback before a next tick completes?

Yeah we should definitely follow Node's convention.
