### ISSUE TITLE
webview.getUrl() is incorrect after redirecting

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1435]
Set src to `http://github.com`,
The page redirects to https (`https://github.com`)
but the result of `webview.getUrl()` remains `http://github.com`.

**Comment by qq150871483** [comment]
https://github.com/

**Comment by deepak1556** [comment]
dupe https://github.com/atom/electron/issues/1364

**Comment by zcbenz** [comment]
Closing as a duplicate of #1364.
