### ISSUE TITLE
Integration with forge module

### ISSUE THREAD

**Issue by mattcollier** [atom/electron#1436]
I'm attempting to get the [forge module](https://github.com/digitalbazaar/forge) to work with [atom-shell](https://github.com/atom/electron/).

Forge module mods:
https://github.com/mattcollier/forge/blob/master/js/prng.js#L23

Atom-shell renderer code
https://gist.github.com/mattcollier/3a713b4a076cd65257fe

The code as shown allows one to utilize webworkers while still getting a CSPRNG from io.js via openssl.

I found that I am unable to call include('remote') on line 23 as shown

All of this works as shown, but I would like to have a solution that could be incorporated into forge. Ideally, the code would behave properly whether it is loaded from the renderer or the main process.

**Comment by paulcbetts** [comment]
Check out #797, you can't require in web worker context :(

**Comment by steelbrain** [comment]
I have a question, Why use web workers when there's child_process?

**Comment by Hossein1995** [comment]
Because i am love it
در تاریخ ۱۷ آوریل ۲۰۱۵ ۲۳:۰۹، "Steel Brain" <notifications@github.com> نوشت:

**Comment by steelbrain** [comment]
I love them too :)
But when we have a better option, like child processes and a super-smooth way of communication with those child processes like [ChildProcess-Promise][CPP]. I don't see a point in using them.
[CPP]:https://github.com/steelbrain/ChildProcess-Promise

**Comment by Hossein1995** [comment]
I just know this way have problem,(s)
در تاریخ ۱۷ آوریل ۲۰۱۵ ۲۳:۱۶، "Steel Brain" <notifications@github.com> نوشت:

**Comment by mattcollier** [comment]
@steelbrain, I think the motivation for having web workers in node is well articulated here: http://blog.std.in/2010/07/08/nodejs-webworker-design/

I thought it would be easy to take advantage of the webworker functionality already built into forge.

Based on the aforementioned thread that explains that this would not be a thread safe configuration, I will not pursue this course any further.  I can add that we did encounter some segmentation faults during our testing.

Thanks for the recommendations!
