### ISSUE TITLE
Mac OS X Contextual Menus: Services menu items appear inconsistently

### ISSUE THREAD

**Issue by bengotow** [atom/electron#1440]
When creating contextual menus in Atom Shell, the Services menu seems to appear automatically, but differently in different scenarios:

1: No text in the window is selected

![screen shot 2015-04-17 at 6 50 31 pm](https://cloud.githubusercontent.com/assets/1037212/7213584/ab521ee4-e538-11e4-8d0f-534da0675739.png)

2: Text in the window is selected, but the text does not contain the element triggering the menu:

![screen shot 2015-04-17 at 6 50 26 pm](https://cloud.githubusercontent.com/assets/1037212/7213585/b4b63c36-e538-11e4-8f46-6f2bfd90d0da.png)

3: Text in the window is selected, and the selection includes the element triggering the menu. (Not sure this is the scenario that triggers this, but currently my best guess.)

![screen shot 2015-04-17 at 7 30 31 pm](https://cloud.githubusercontent.com/assets/1037212/7213586/b6b319f0-e538-11e4-88e0-ae5f1e9bf329.png)

Optimally, contextual menus would work the same way as Application menus. We could include a `Services` menu item when creating the `Menu` to indicate that the Services submenu should appear.

**Comment by zcbenz** [comment]
The services showed in context menu is automatically generated by OS X based on the selected text of current window, and there is no way to control how the services show, so I'm closing this as won't fix.
