### ISSUE TITLE
Flash of window in wrong position when using setSize and setPosition

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1445]
In order to overcome some of the limitations with transparency we've been resizing windows dynamically depending on the content. One thing that we've run into is when attempting to resize from the right instead of the left - you have to do something like the following:

```javascript
browserWindow.setSize(100,500);
browserWindow.setPosition(screenWidth-100, 0);
```

This results in a flash as the window size is changed, rendered, and then moved. It would be **GREAT** to have access to (optionally) [set the origin](https://github.com/atom/electron/blob/master/atom/browser/native_window_mac.mm#L483) when setting the size of a window. This would benefit folks whenever there is a need to move and resize a window in one operation.

I believe this could be added in a backwards compatible manner through a second/third argument to the setSize method, something like:

```javascript
browserWindow.setSize(100, 500, 0, 0);
```

thoughts?

**Comment by zcbenz** [comment]
I think we can add a new set of APIs to set bounds:

```coffeescript
browserWindow.setBounds({width: 100, height: 100, x: 0, y:0});
browserWindow.getBounds()  # Returns {width: 100, height: 100, x: 0, y:0}
```

**Comment by tommoor** [comment]
Hey @zcbenz sounds interesting, are you suggesting that Atom would do the calculations behind the scenes to the origin to make this happen? Whilst this would work for our usecase :smile:  I can't help but think direct access to the origin property would be more future flexible..

**Comment by paulcbetts** [comment]
The other thing we could do is schedule setSize and setPosition for the next tick of the runloop so that they happen at the same time (i.e. both setSize and setPosition just set a value and schedule a `doResize` method)

**Comment by tommoor** [comment]
I like @paulcbetts suggestion if it's possible as you'd achieve the same thing without needing any new API's at all..

**Comment by zcbenz** [comment]
> Hey @zcbenz sounds interesting, are you suggesting that Atom would do the calculations behind the scenes to the origin to make this happen?

All platforms have APIs to set both window size and position in the same time, so we don't have to do the calculation ourselves.

> The other thing we could do is schedule setSize and setPosition for the next tick of the runloop so that they happen at the same time (i.e. both setSize and setPosition just set a value and schedule a doResize method)

Scheduling API calls make the implementation complicated, and it makes APIs hard to test too.

**Comment by tommoor** [comment]
> All platforms have APIs to set both window size and position in the same time, so we don't have to do the calculation ourselves.

I'm sold!
