### ISSUE TITLE
File descriptors leaked to spawned child processes

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#1447]
I am auto-restarting an Electron app by spawning a detached version of the binary, which then shuts the existing binary down. After spawning Electron 24 times, the 25th time fails with EMFILE.

More information is here: https://github.com/iojs/io.js/issues/1474

Related discussions:
https://medium.com/@fun_cuddles/opening-files-in-node-js-considered-harmful-d7de566d499f
https://github.com/joyent/libuv/commit/6abe1e4b953bda1e9bd5dab33826bfead591551d
https://github.com/joyent/node/issues/6905

**Comment by Hossein1995** [comment]
!!!
در تاریخ ۲۰ آوریل ۲۰۱۵ ۱۴:۴۲، "Joran Dirk Greef" <notifications@github.com>
نوشت:

**Comment by jorangreef** [comment]
When you spawn subprocesses they inherit all the open file descriptors of the parent process unless those descriptors have been specifically flagged as FD_CLOEXEC.

Do Electron and Chromium set the close-on-exec flag for all file descriptors?

Re-spawning my app, I see the first instance has 99 fd's, the second instance has 139 fd's, the third instance has 179 fd's etc., and so on until the last instance has 1040 fd's at which point no more instances can be spawned.

**Comment by zcbenz** [comment]
Chromium doesn't set `FD_CLOEXEC` for all file operations, I think it could be the reason of your problem. It is nearly impossible to patch all the file operations in Chromium, so I'm afraid you have to use a separate executable to restart Electron.
