### ISSUE TITLE
menu item - allow to add any label as accelerator

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1449]
I would like to put any string as accelerator to a menu item. The menu item should ignore this string and just display it. In other words, it should not react to it when the accelerator is pressed. This is purely for UI reasons, all key handling happens within the app and not outside.

**Comment by zcbenz** [comment]
Unfortunately OS X doesn't allow setting arbitrary string as accelerator, the only way to implement it is to draw custom menu items, which I don't think we will do. Pull requests for that would still be welcomed though.

I'm closing this as won't fix.
