### ISSUE TITLE
Not stripping Linux binaries results in 1.5GB executable

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1451]
On Linux, running script/bootstrap && script/build will result in a 1.5GB executable. Release build probably needs to strip them somewhere (either here or in atom/atom)

**Comment by zcbenz** [comment]
Running `./script/create-dist.py` will strip the binaries, you can find the stripped binaries under `dist` directory.

And I don't think you need to build electron yourself anymore, now renaming `electron.exe` won't break native modules on Windows, and you can rename the helper app to arbitrary name on OS X.

**Comment by paulcbetts** [comment]
@zcbenz We're working on moving to that, we have to come up with a process to do it though
