### ISSUE TITLE
Right-click breaks `webview`'s devtools on OS X

### ISSUE THREAD

**Issue by mark-wagon** [atom/electron#1456]
* Electron versions: at least 0.23.0 and 0.24.0
* OS: Mac

Right-clicking (or control-clicking) in the devtools belonging to a `webview` DOM element
causes the devtools to break: the open devtools tab can be interacted with but does not
update its state, and the window's contents appear blank when certain other tabs are selected.

A minimal Electron app that demonstrates this behavior can be found [in this gist](https://gist.github.com/mark-wagon/f7eeebf3613d9df8df11).  Repro steps are outlined in the gist's readme.

**Comment by lin-chao** [comment]
I have encountered this problem
OS: Mac && Win7 64
Electron versions: 0.31.2
