### ISSUE TITLE
webview should expose inspectElement method

### ISSUE THREAD

**Issue by mark-wagon** [atom/electron#1457]
Feature request:

It would be useful for the `webview` API to include an `inspectElement` method like exists in the [`BrowserWindow` API](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowinspectelementx-y).  Debugging content in a `webview` would be all the more convenient if this method were available.

**Comment by CharlieHess** [comment]
:+1:, I'd dig this.

**Comment by pekim** [comment]
I was slightly surprised a few days ago at this omission; devtools can be opened and closed, so it seemed reasonable to be able to inspectElement. I too would appreciated its addition.

**Comment by christoth** [comment]
+1
