### ISSUE TITLE
fakepath

### ISSUE THREAD

**Issue by Chibaheit** [atom/electron#1460]
I use the <input type="file" id="file-asm-path"> to get the filepath 
but i get C:\fakepath\tmp.asm
I don't know how to change the settings about the chromium

**Comment by Chibaheit** [comment]
input type="file" id="file-asm-path"

**Comment by magicae** [comment]
refer to [File Object](https://github.com/atom/electron/blob/master/docs/api/file-object.md)

**Comment by zcbenz** [comment]
The [example in docs](https://github.com/atom/electron/blob/master/docs/api/file-object.md) seems to work fine with v0.25.0.

**Comment by Chibaheit** [comment]
THX。I have found the solve

**Comment by appsparkler** [comment]
I'm accessing `file path` from the `evt` object:

```javascript
const handleChange = (evt) => {
  evt.target.files.forEach(file => console.log(file.path));
}

```

Good Luck...
