### ISSUE TITLE
Missing BluetoothApis.dll

### ISSUE THREAD

**Issue by romovs** [atom/electron#1462]
Electron v0.25.0 i32, Windows 7
![error screenshot](http://i.imgur.com/s67AfCt.png)
Possibly related to #1442

**Comment by romovs** [comment]
v0.24.0 runs fine on the same machine (Windows 7 Pro N with Media Foundation installed) so this is probably related to Chrome 42 upgrade and has nothing to do with #1442

Is BluetoothApis.dll even available on Windows 7? I can't seem to find any definite confirmation on MSDN regarding it.

**Comment by christoth** [comment]
Had the same error on Win7 x64.
