### ISSUE TITLE
ATOM_SHELL_INTERNAL_RUN_AS_NODE not working on Windows

### ISSUE THREAD

**Issue by Trixt0r** [atom/electron#1463]
If I set ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 on Windows 10 x64 TP, my app does not get loaded, i.e. Electron immediately stops executing without any error messages. In atom-shell v0.22.3 it worked like expected.

Edit: Same problem on Win 7 x32.
Edit2: This problem occurs since v0.23.0, btw...

Any suggestions?

-Trixt0r

**Comment by Trixt0r** [comment]
This is still a problem in 0.25.0 and 0.25.1...

**Comment by Trixt0r** [comment]
Did someone look into this issue and consider to fix it? My app depends heavily on the ATOM_SHELL_INTERNAL_RUN_AS_NODE variable...

**Comment by paulcbetts** [comment]
Why did you build an app around a variable which explicitly has the world "Internal" (i.e. not a public API) in the name?

**Comment by Trixt0r** [comment]
I need to run electron in node mode, because I have to start background processes and do some post installation and pre uninstallation stuff...

**Comment by zcbenz** [comment]
It seems to work fine on Windows 8, can you provide a reproducible example?

**Comment by Trixt0r** [comment]
package.json:

`{
  "main": "main.js",
  "name": "dropclient",
  "version": "1.0.0"
}`

main.js:
`console.log('test');`

Both files are in `resources\app`

I type the following command into the console (cmd.exe):
`set ATOM_SHELL_INTERNAL_RUN_AS_NODE=1`

Then I run electron.exe and nothing gets logged to the console. I also tried to write a simple text file with 'fs'... doesn't work either.

**Comment by zcbenz** [comment]
This only seems to happen when running under cmd.exe, it works when either ran by child_process or in ran in cygwin.
