### ISSUE TITLE
Implement OnFocusedNodeChanged

### ISSUE THREAD

**Issue by thyrrestrup** [atom/electron#1465]
Hi 
Is it possible to get an event or set a callback for when the user focuses a text field?
The reason I ask is because I am doing a kiosk touch screen setup where I would like to show an onscreen keyboard when the user needs to enter text. Like on mobile devices.
This needs to work on pages I have no control over as-well as my own application.
I was looking through the Cocoa WebView reference and came across the "WebViewDidBeginEditingNotification" which seems like what I need - is there a similar thing for chrome webview?
I was thinking about implementing this in java-script as an alternate route - any pointers would be greatly appreciated.

-Tobias

**Comment by steelbrain** [comment]
```html
<!-- index.html -->
<!DOCTYPE HTML>
<html>
  <body>
    <input id="TextInput" type="text" />
    <script src="main.js"></script>
  </body>
</html>
```
```js
// main.js
var Element = document.getElementById("TextInput");
Element.addEventListener("focus", function(){
  console.log("Input Element was focused");
}, false);
```

**Comment by thyrrestrup** [comment]
@steelbrain - Thanks for the example but this will only work as long as I know the id of the input field and I really have no way of knowing because the client can link to all sorts of webpages from within the kiosk.
I was thinking something along these lines:
```javascript
window.addEventListener('click', function(event) {
    var type = event.toElement.type.toLowerCase();
    var tag = event.toElement.tagName.toLowerCase();
    
    if((tag == 'input' && (type == 'text' || type == 'password' || type == 'url' || type == 'email') )
       || tag == 'textarea' )
    {
        console.log('show keyboard');    
    }
});
```

**Comment by steelbrain** [comment]
I would still prefer something like this
```js
(document.querySelectorAll('input[type=text], input[type=password], input[type=url], input[type=email]') || [])
  .forEach(function(Input){
    Input.addEventListener("focus", function(){
      console.log("Input Element was focused");
    }, true);
  });
```

**Comment by thyrrestrup** [comment]
@steelbrain - Yes that's interesting, Thanks
I'm wondering if any of these will work if the page contains iframes which contains input fields I'll do some more testing.

**Comment by steelbrain** [comment]
Note: It's a javascript thing as you can see and not related to electron, IMHO it makes no sense to add it to core as this can be done in JS easily. so this issue should be closed.

**Comment by thyrrestrup** [comment]
I agree this could possibly be hacked together in javascript.. but it is very difficult to get working on every web site out there.
It would be a great feature if this was a native event.

Chromium Embedded Framework has the following method:
OnFocusedNodeChanged - Called when a new node in the the browser gets focus. The |node| value may be empty if no specific node has gained focus. The node object passed to this method represents a snapshot of the DOM at the time this method is executed. DOM objects are only valid for the scope of this method. Do not keep references to or attempt to access any DOM objects outside the scope of this method.

**Comment by steelbrain** [comment]
Hahaha, You are kidding me, aren't You?
If we are gonna embed everything in the core, then what do we have JS for?
and Please do explain how is it "very" difficult to get working on every website out there, I had heard that things work differently from browser to browser.
But site-to-site is something I am hearing for the first time.

Anyways, The JS way is the "right" way to do it, and If you find it hacky, then You need to work on your JS skills my friend :) http://www.codecademy.com/en/tracks/javascript would be a good starting point.

**Comment by thyrrestrup** [comment]
You should learn some manners.
I'm only suggesting to implement a feature already present in other frameworks built on top of chromium.

I see the following problems using javascript:
What if the input fields are inside multiple levels of iframe.
What if the input fields are added per user interaction after the script has run.

By the way: http://toddmotto.com/ditch-the-array-foreach-call-nodelist-hack/

**Comment by steelbrain** [comment]
I meant disrespect by no means.
and I don't agree with 99% part of that article, and I don't believe whatever I find online. I am the author of [dQuery][dQuery], and if you would goto the pull requests there and check out the latest rewrite pull request I am working on, You will realize that I am using `HTMLCollection`, `NodeList` and various others instead of mutating the type each time. and Array Prototype's methods work without a single problems on objects that have a length attribute and that keep their values in proper indexes, They can even work on a class like jQuery which uses the similar behavior.

and trust me, It really doesn't make any sense to include this in the core. If one way doesn't work for you, then you can use an alternative way using javascript. I have been writing in javascript for years and haven't come across a single limitation that I was not able to come across using an alternative technique.

For your specific problem, that alternative technique would be to capture all click events to the DOM and filter them using e.target. Because it would be complex in vanilla, and You probably don't want that much complexity, You could use that rewrite branch of dQuery or jQuery maybe and set up something like.
```js
var $Document = $(document);
$Document.ready(function(){
  $Document.on('click', 'input, textarea',function(e){
    console.log("an input like thing was selected");
  });
});
```

[dQuery]:https://github.com/dQuery/dQuery

**Comment by zcbenz** [comment]
All those C++ events like `OnFocusedNodeChanged` or `WebViewDidBeginEditingNotification` are emitted on the main process side, exposing them is meaningless if you want to handle them on renderer process side.

I'm closing this as won't fix.

**Comment by thyrrestrup** [comment]
My original intention was to handle them on the main process. The javascript was just a work-around.

**Comment by kidwm** [comment]
@zcbenz Or is it possible to emit an event for such like TEXT_FIELD_GET_FOCUS ?
I'm also doing a kiosk with touch screen, this would be very helpful.

**Comment by Hakim2014** [comment]
Hi All,
I am doing the same type of application on raspberry pi. I need to get a keyboard open when user click on input field. As of now keyboard gets open but its always behind the electron app. I am using matchbox-keyboard and 'child-process' to open the keyboard on the click event of the input field but the keyboard never comes in foreground. Any help would be great help. Thanks
