### ISSUE TITLE
Webview preload JavaScript does not load when a page is loaded from cache

### ISSUE THREAD

**Issue by christoth** [atom/electron#1467]
This can be duplicated by loading a web page in a Webview with a preload script defined (the preload can just print to the console), e.g. www.nytimes.com (preload JavaScript loads), clicking on a link, e.g. "World" www.nytimes.com/pages/world/index.html (preload JavaScript loads).

Click on a link taking you back to the original page, e.g. www.nytimes.com in the top left corner (preload JavaScript DOES NOT load), then click on the same link, "World" www.nytimes.com/pages/world/index.html (preload JavaScript DOES NOT load).

Using the Webview methods goBack() & goForward() also cause the aforementioned behaviour.

My environment is Win7 x64, Electron v0.24 x64.

Thanks in advance

**Comment by steelbrain** [comment]
I am not sure if it's a bug, 'cause I experience the same behavior with Google Chrome, doing a goBack doesn't re-run all the scripts, it just resumes the previous state. Even stuff like scroll position and input values

**Comment by christoth** [comment]
My issue is that I initialize a variable on the window object, on the first load that is not initialized when the page is revisited. Hence, my script does not execute.
