### ISSUE TITLE
Add DOMContentLoaded event to Webview and allow Webview.executeJavaScript() to execute

### ISSUE THREAD

**Issue by christoth** [atom/electron#1469]
It would be great for the Webview parent to be able to subscribe to the DOMContentLoaded event (i.e. similar to the did-finish-load event, but earlier) for the Webview content and to use Webview.executeJavaScript() at that point.

Currently, Webview.executeJavaScript() is only allowed after the load event.

TIA

**Comment by steelbrain** [comment]
How about a preload hook along with ipc?

**Comment by christoth** [comment]
That was my original plan, but the preload script does not load when the page loads from cache (#1467), hence preload with ipc won't always work.

**Comment by zcbenz** [comment]
When the page is loaded from cache most events including `DOMContentLoaded ` can not be received on C++ side, we have to find a way to fix #1467.
