### ISSUE TITLE
console.log doesn't work in scripts forked by child_process

### ISSUE THREAD

**Issue by romovs** [atom/electron#1471]
On Windows console.log() invoked from child process results in EBADF:
```
{"errno":-4083,"code":"EBADF","syscall":"write"}
```
main.js
```js
var child = require('child_process').fork(
    require('path').resolve(__dirname, 'child.js')
); 
child.on('message', function(m) {
    if (m.event === 'exc-event') {
        console.log("no it doesn't: " + m.exc);
    }
});
```

child.js
```js
try {
    console.log("hooray it works!");
} catch(exc) {
    process.send({ event: 'exc-event', exc: JSON.stringify(exc) });
}
```
WIndows 7, Electron v0.25.1 (v0.22.3 didn't have this issue)

**Comment by deepak1556** [comment]
Related https://github.com/atom/electron/issues/1463

**Comment by romovs** [comment]
Oh it's not just the `child_process.fork`, stdout is broken in `child_process.exec` as well

`require('child_process').execSync('node -v'); // -> EBADF`

**Comment by zcbenz** [comment]
I didn't succeed to reproduce on Windows 8 :(

**Comment by romovs** [comment]
Sorry I haven't noticed this at first, but execSync fails (`"Uncaught Error: EBADF: bad file descriptor, write", source: fs.js (659)`) only when invoked from the renderer process. It works as expected in main process. 

The original console.log example fails in both processes though - renderer and main.

Were you unable to reproduce either of the examples @zcbenz ? I am seeing same behavior on a freshly installed Windows 8 ia32 VM.

**Comment by davej** [comment]
I'm still seeing this issue in the renderer process of 0.34.3 on Yosemite.

Works fine in the main (browser) process but to recreate in the renderer, just do:
```js
require('child_process').execSync('echo $PATH');
```

The error backtrace:
```
events.js:141 Uncaught Error: write EBADF
exports._errnoException @ util.js:837
exports._exceptionWithHostPort @ util.js:860
afterWrite @ net.js:760
```

**Comment by silverwind** [comment]
@davej I think your issue is a different one than OPs, which looks to be Windows-specific. I suggest opening a seperate issue.

**Comment by davej** [comment]
@silverwind: Thanks, I think it might be the same issue as @romovs mentioned in his last comment but I agree that it doesn't match the title, so I've created a new issue instead: https://github.com/atom/electron/issues/3482

**Comment by joaomoreno** [comment]
I just hit this issue. I'm not sure whether it is really a dupe of #3482. In the negative case, I suggest we reopen this.

The bug is: writing to `stdout` from a process forked from the main process throws. **But** it only reproduces if you double click the `.exe`. If you launch it from the command line, it does not.

**Steps:**

Get the vanilla Electron release.

Add the following code to the end of `default_app.js`:
```javascript
var path = require('path');
var cp = require('child_process');
cp.fork(path.join(__dirname, 'child.js'));
```

Create a `child.js` file next to it with the following content:
```javascript
var cp = require('child_process');

try {
	console.log('hello from child');
} catch (err) {
	cp.exec('start "New Window" echo ' + err.message);
}
```

Simply double click `Electron.exe`. It will promptly open a command prompt with the following error message: `EBADF: bad file descriptor, write`.

**Comment by zcbenz** [comment]
@joaomoreno It is the same type of bug with #3482, once I came up with a solution for #3482 it should be able to fix both issues.

**Comment by joaomoreno** [comment]
@zcbenz That would be great. Note that my issue doesn't reproduce on OS X, while #3482 only repros in it.

**Comment by joaomoreno** [comment]
Also, this issue repros only when spawning/forking from the main process. #3482 seems to happen when spawning/forking from the renderer process.
