### ISSUE TITLE
Tray icon and tray icon menu cannot be changed after initialization

### ISSUE THREAD

**Issue by willbarrett** [atom/electron#1473]
Seen on Ubuntu 14.04

Setting attributes on a menu item in the tray icon menu does not update the tray icon menu. E.G., setting .visible = false after initialization does not hide the item.

Changing the tray icon itself via the built in functions does not change the icon.

It seems like there are some missing binds related to the tray icon and tray icon menu on linux that keep it from re-rendering?

**Comment by pekim** [comment]
For me the tray icon does update, but I have noticed that it takes a couple of seconds before it changes.

This is on Ubuntu 14.04, with atom v0.22.3. (I'll be upgrading, to at least, electron v0.25.1 soon.)
With which version do you see no updates? (So that I can avoid it. :smile: )

**Comment by willbarrett** [comment]
Both latest and 0.22.3 - it doesn't update, no matter how long I wait. I've ensured that the code is being called.

**Comment by pekim** [comment]
I was using unity. I've switched to xcfe, and I'm seeing the same issue as you; the icon cannot be changed.

**Comment by pekim** [comment]
Sorry, I spoke too soon. My image updating code was unchanged, but I was testing it incorrectly.
Updating of the tray icon works fine for me on xfce. In fact it updates nicely, without the delay that I was seeing under unity.

**Comment by willbarrett** [comment]
The tray icon appears to be working fine now, so that was a red herring. The tray icon menu will update when setContextMenu is called, but not when the individual menu items are mutated.

**Comment by jorangreef** [comment]
I think calling setContextMenu will hide the tray menu if it is open so it is not ideal.

Often one needs to make a tray menu which has status items which change while the user has it open: e.g. WiFi, Battery, Dropbox.

I think at the moment there is no way to do this?

**Comment by M0rph3v5** [comment]
+1 at what @jorangreef is talking about, is there a way to dynamically update a menu / submenu while keeping it open and visible for the user?

**Comment by destan** [comment]
moreover I think this very unintuitive behavior should be documented. made a pr https://github.com/atom/electron/pull/4498
