### ISSUE TITLE
Slow start up time with recent builds on Windows

### ISSUE THREAD

**Issue by romovs** [atom/electron#1474]
Looks like Electron has put up some weight in recent releases and takes noticeably more time to load now on Windows 7 ia32. While v0.22.3 took around 1.5 seconds to load the default app, v0.25.1 takes almost twice of that - 3 seconds :worried:. 
On Linux both versions load equally fast though.

**Comment by paulcbetts** [comment]
We actually are finding that (anecdotally) the latest version loads much faster than previous versions on Windows, this might be based on what your app is doing at startup?

**Comment by romovs** [comment]
It happens with the default_app which comes bundled with Electron. My app which is a bit heavier also loads faster on previous versions.
Strangely enough it seems that only one specific machine is affected by this. I just tested on two more almost identical Windows installations and everything is fine there - latest version indeed loads faster. Weird.

I guess we can close this as it doesn't seem like something reproducible...
