### ISSUE TITLE
Upgrade to chrome 43

### ISSUE THREAD

**Issue by bpmarinho** [atom/electron#1478]
Chrome 43 fixes a huge problem affecting mouse usage on virtual box and is affecting atom after version 0.188.0. Next version had chrome 41 that showed the bug for the first time.

Here is the thread:
https://code.google.com/p/chromium/issues/detail?id=456222

Thank you,

Bruno

**Comment by paulcbetts** [comment]
This will happen once Chrome 43 moves to the stable channel

**Comment by ijuma** [comment]
Chrome 43 is now stable.

**Comment by skitoo** [comment]
I always have this problem. when will the integration of Chrome 43 is provided?

Thank you.
