### ISSUE TITLE
Automatic updates?

### ISSUE THREAD

**Issue by pakastin** [atom/electron#1479]
You say here, that Electron now includes automatic updates:
http://electron.atom.io/

Where's the documentation? Or still only Mac?
https://github.com/atom/electron/blob/master/docs/api/auto-updater.md

**Comment by kevinsawicki** [comment]
It does support Windows now when using [Squirrel for Windows](https://github.com/Squirrel/Squirrel.Windows/), you can generate an installer for your app that will automatically update using https://github.com/atom/grunt-electron-installer

The docs do need to be updated and there are still plans to adds more APIs for the auto-updater module for windows things such as desktop/start menu shortcuts, etc via https://github.com/atom/electron/issues/939

**Comment by pakastin** [comment]
What about Linux?

Does this kind of updating work:
https://github.com/edjafarov/node-webkit-updater

1) download to temp folder
2) restart from there
3) copy to original place
4) restart at original place

..in Mac / Windows you need signing, so that's why it wouldn't work? Needs to be native somehow?

**Comment by kevinsawicki** [comment]
> What about Linux?

I'm not sure, but nothing is built in currently for it.

**Comment by paulcbetts** [comment]
On Linux you should add yourself as an entry in sources.list and let the system update you like any other package

**Comment by zcbenz** [comment]
On Linux the tradition is to auto update your app with distribution's package manager, the app itself usually does nothing with auto updating.
