### ISSUE TITLE
Running without the SUID sandbox

### ISSUE THREAD

**Issue by bhargavrpatel** [atom/electron#1482]
Hello, 
I am running a VirtualBox of the Ubuntu distro. It is a fresh install with no possible conflicts to cause this error. From my research it is a chromium problem that is fixed by changing some parameters, not sure how this is done in electron. I have shown the error in the image below. 
![Image of error](http://img.prntscr.com/img?url=http://i.imgur.com/foI3lXI.png)

**Comment by steelbrain** [comment]
That message is perfectly normal and is something related to chromium and not electron itself.
You will get the same message if you run chrome from command line. You can safely ignore it.

**Comment by bhargavrpatel** [comment]
Thanks!
