### ISSUE TITLE
document.ondrop can't receive event and so can't prevent drop file in to app

### ISSUE THREAD

**Issue by superluffy** [atom/electron#1483]
I try to write app with atom shell. but when I drop a new file (like html or any file) in to the window, the app just load the file. and my old app just gone.

![image](https://cloud.githubusercontent.com/assets/394794/7312737/38a5d0b6-ea83-11e4-931e-721b9b237bf7.png)

I typed the above codes and want to use preventDefault to stop this. but the console.log('fucked') log never printed. 

And it load new file everytime

**Comment by paulcbetts** [comment]
Put this in the browser process:

```coffee
    @window.webContents.on 'will-navigate', (e, url) ->
      logger.info "Preventing navigation to: #{url}"
      e.preventDefault()
```

**Comment by superluffy** [comment]
Thank you very much. It works.
