### ISSUE TITLE
Support for multi-touch gestures on OS X

### ISSUE THREAD

**Issue by petrbrzek** [atom/electron#1486]

**Comment by zcbenz** [comment]
I think Chrome 42 which is used by latest Electron already has some support of it.

**Comment by petrbrzek** [comment]
I'm unable to find some information about it. Can you provide some source?

**Comment by marekhrabe** [comment]
This will probably be implemented as [Touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events), right?

**Comment by zcbenz** [comment]
@petrbrzek "multi-touch gestures" is a too general topic, can you say more specific about what you want?

**Comment by petrbrzek** [comment]
Yes, I want to be able to listen on trackpad gestures events (swipe, pinch to zoom, rotate with two finders, etc.) from JavaScript. As far as I know, trackpad fires only the mousewheel event so you cannot distinguish between scrolling and swiping...

![multitouch](https://cloud.githubusercontent.com/assets/879564/7400775/8f957a44-eebf-11e4-8f3b-e9d842cf163c.gif)

**Comment by zcbenz** [comment]
@petrbrzek For that part of APIs I think you have to wait until Chrome supports some HTML5 standards on touch events, exposing them in JS is huge work and it is not practically to implement them alone in Electron.

**Comment by mandric** [comment]
Can you use a JS touch library? http://hammerjs.github.io/

**Comment by jacwright** [comment]
@mandric unfortunately no. Those touch events that hammerjs relies on aren't fired on desktop when using the trackpad. Only on mobile.

**Comment by jacwright** [comment]
@petrbrzek Chrome already supports touch events on mobile and desktops with touch screens. It just doesn't recognize trackpad gestures.

Also, I believe trying tying into the OS-supported trackpad gestures is a different task than dealing with touch events.

**Comment by drw158** [comment]
Why was this closed? Has the issue been fixed?

**Comment by timfish** [comment]
Its non trivial to add and only supported on Mac.

Check out the discussion [here](https://groups.google.com/a/chromium.org/forum/#!topic/input-dev/D_5vfmRAU_c) over why this hasn't been added to Chrome.

**Comment by timfish** [comment]
Btw, pinch-zoom events come through in electron as standard JavaScript `WheelEvent` with `ctrlKey` set to `true`

**Comment by philfreo** [comment]
I see that 3-finger swipe gestures are already supported: https://electronjs.org/docs/api/browser-window#event-swipe-macos

But is there a way to easily detect 2-finger swipe gestures, similar to what Chrome & Safari on mac use for Back/Forward navigation?

**Comment by bermanboris** [comment]
Any news on this issue?

**Comment by msynk** [comment]
Any updates?

**Comment by ngmartins** [comment]
I am experiencing similar problems with 2 finger gestures on electron when running in Linux.
Any update on this?

**Comment by maccman** [comment]
Any updates?

**Comment by raphaelschaad** [comment]
Related to https://github.com/electron/electron/issues/2683
