### ISSUE TITLE
Bump version of npm electron-prebuilt module when publishing a new release

### ISSUE THREAD

**Issue by zcbenz** [atom/electron#1488]
Currently @maxogden is managing it manually, we should make it a part of `./script/upload.py -p`.

**Comment by maxogden** [comment]
Excellent. I opened an issue here https://github.com/mafintosh/electron-prebuilt/issues/16 for us to add a script that can be called from your `upload.py` to easily publish. I already added @zcbenz to https://www.npmjs.com/package/electron-prebuilt, is there anyone else I should add?

**Comment by johnmuhl** [comment]
I've created a [web service][ws] running on [Heroku][hk] that can be added as a Webhook on the Release event that triggers an update and release of electron-prebuilt.

My forks of [Electron][el] and [electron-prebuilt][ep] have these hooks setup and are publishing to npm as [moustached-ironman][mi]. The 0.28.x releases were done through the web service.

There are setup instructions in the readme and I'd be happy to help get it going for the official repositories if there is interest pursuing this route.

@mafintosh thoughts?

[ws]: /johnmuhl/electron-prebuilt-updater
[hk]: https://electron-prebuilt-updater.herokuapp.com/
[el]: /johnmuhl/electron
[ep]: /johnmuhl/electron-prebuilt
[mi]: https://www.npmjs.com/package/mustached-ironman

**Comment by maxogden** [comment]
We are now using @johnmuhl's server running on heroku to listen to release webhooks from this repo and publish to npm automatically. So hopefully next time an electron release happens it automatically publishes to npm!
