### ISSUE TITLE
[Windows] App crash when long log message is printing out.

### ISSUE THREAD

**Issue by popopome** [atom/electron#1489]
In my windows dev environment, `electron-prebuilt` version is crashed when long log messages are printed. 
If the app is launched via command line, the length of log message does not cause app crash. 
But when I launch the app by dropping app folder into electron standalone app, my app is crashed.

I found the issue when I printed out JSON.stringify() message. You can reproduce by using my sample application.

[testapp_crash.zip](https://www.dropbox.com/s/zgtdb30v2ynso35/testapp_crash.zip?dl=0)

**Comment by mattcollier** [comment]
@popopome Thank you for creating the test app!  Providing the app in a zip archive is not recommended.  Would it be possible for you to create a gist or a full on github repo (as necessary)?

**Comment by zcbenz** [comment]
I can not reproduce with your app, can you provide more information about for OS? And are you using the latest release (v0.25.1)?
