### ISSUE TITLE
Error: '/bin/bash' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by chaliy** [atom/electron#1492]
Subj when run under Windows. It is only to execute run.bat that just run specific electron.exe. May be it is better to use cmd for this purposes on Windows?

**Comment by maxogden** [comment]
@chaliy what shell did you use to install it? we currently test using `CMD.EXE` on windows, but are working on support for third party shells like msysgit in this PR https://github.com/mafintosh/electron-prebuilt/pull/13

in the meantime you can just download the exe directly from the releases page: https://github.com/atom/electron/releases

**Comment by chaliy** [comment]
I use just plain cmd or powershell. It is  C:\Users\...\AppData\Roaming\npm\electron.cmd for some reasons try to execute run.bat with /bin/bash.exe which is not present on my computer in that folder (I do not have bash in PATH at all). 

Workaround for me was to replace /bin/bash with just cmd.exe in electron.cmd and it works as expected. 

Looks like PR you referring fixes this issue.

**Comment by frabert** [comment]
I have the same issue, and I had to replace /bin/bash with cmd.exe /c to make it work.

**Comment by zcbenz** [comment]
I'm closing this since it is actually an issue of electron-prebuilt and there is already a PR for it.
