### ISSUE TITLE
[windows]gulp.src(pattern) can't find files inside asar package.

### ISSUE THREAD

**Issue by nantas** [atom/electron#1493]
I have some code to read files with a certain glob pattern inside asar package:

```js
    var Fs = require('fs');
    //gulp glob search
    gulp.src(someGlobPath).pipe(someOperation);
   //fs readdir 
    var fileList = Fs.readdirSync(someGlobPath);
    //do something with the fileList
```

In the above code, I tried `gulp.src ` and `fs.readdirSync` to read the same path, `gulp.src` can't find any files to operate, while `fs.readdirSync` works fine.

Where lies the problem? Is node-glob not supported with asar package? Are there any workarounds?

**Comment by nantas** [comment]
btw, this issue is windows only.

**Comment by nantas** [comment]
hello, any feedback on this? @zcbenz

**Comment by zcbenz** [comment]
Unable to reproduce on 0.36.2.
