### ISSUE TITLE
Desktop Notification doesnt show up on Mac OS

### ISSUE THREAD

**Issue by maxogden** [atom/electron#1494]
E.g. when doing `new Notification('hello')` or running `window.location.href = "http://ttsvetko.github.io/HTML5-Desktop-Notifications/"` and then clicking the button, in both cases no desktop notification shows up.

I found this old issue which seems to suggest that it used to work https://github.com/atom/electron/issues/1269 so maybe this is a regression, or maybe I'm doing something wrong?

I'm using electron 0.25.1

**Comment by paulcbetts** [comment]
This definitely works on OS X and Linux, at least as of awhile ago. `new Notification('hello')` is the right syntax

**Comment by paulcbetts** [comment]
This works on master for me (ca5ee0f)

**Comment by maxogden** [comment]
AHHHH Ok thanks, got it working.

The problem was I had 'Do Not Disturb' on in my OS X Notifications. When I turned it off the notification shows up:

![screen shot 2015-04-26 at 11 13 36 pm](https://cloud.githubusercontent.com/assets/39759/7342490/f72041d8-ec69-11e4-917b-365c083aa1ab.png)

I assumed it wasn't working because in Chrome notifications showed up even though I had Do Not Disturb on

**Comment by rmanalan** [comment]
Works on osx and linux for me, but not on windows? What's the story there?

**Comment by paulcbetts** [comment]
@rmanalan There is no way to open notifications on Windows that works on all versions (specifically, Win7). I'm going to be porting over the Win8+ notifications to Electron soon, but for now you need to implement notifications yourself

**Comment by rgbkrk** [comment]
> The problem was I had 'Do Not Disturb' on in my OS X Notifications. When I turned it off the notification shows up.

Are there ways to detect that Do Not Disturb is set to provide a fallback when notifications are unavailable?

**Comment by paulcbetts** [comment]
> Are there ways to detect that Do Not Disturb is set to provide a fallback when notifications are unavailable?

No

**Comment by rgbkrk** [comment]
Works for me, I'll use them sparingly. Going to have to figure out something else for in app notifications.

**Comment by michaelb-01** [comment]
I can't get this to work on mac..

I'm sending an event with ipcRender:

```
  simpleNotification(obj) {
    this.ipcRenderer.send('notification',obj);
  }
```

Then listening for it in my main.js with ipcMain and creating the notification. The console prints true (notifications are supported) but my notification doesn't show up.. (Do Not Disturb is turned off):

```
ipcMain.on('notification', (event, args) => {
  console.log('Notification support: ' + Notification.isSupported());

  new Notification('hello');
})

```

**Comment by jfrux** [comment]
Same issue, notification not showing or well... showing intermittently...?
Using IPC as well.

**Comment by bernatfortet** [comment]
@jfrux did you find out what was the issue with notifications showing intermittently?

**Comment by kevinelliott** [comment]
I can not seem to get them to show on macOS either.
