### ISSUE TITLE
Update China Mirrors

### ISSUE THREAD

**Issue by Tribex** [atom/electron#1497]
The Chinese mirror listed in `README.md` (https://npm.taobao.org/mirrors/atom-shell) appears to have not been updated since the rename of atom-shell to electron. https://npm.taobao.org/mirrors/electron 404's as well, implying that there is currently no up-to-date mirror on that site.

The mirror is incredibly useful for those in China, as getting electron from the releases page requires many retries and is generally tricky to download due to the poor access to amazon's S3 service here.

Thank you @fengmk2 for your work on that mirror, and it would be great if you could update it to the latest release of electron!

**Comment by magicae** [comment]
I've submitted a new [issue](https://github.com/cnpm/mirrors/issues/47) on cnpm/mirrors about this.

**Comment by fengmk2** [comment]
I will fixed this today.

**Comment by Tribex** [comment]
@fengmk2 Excellent, thank you very much!

**Comment by fengmk2** [comment]
@Tribex transfer to https://npm.taobao.org/mirrors/electron/ now

**Comment by Tribex** [comment]
@fengmk2 Bookmarked, thanks a lot!
