### ISSUE TITLE
can you use chrome extension with electron?

### ISSUE THREAD

**Issue by whatsdis** [atom/electron#1498]
nw.js is slowly supporting chrome extension api like cookies, storage, etc.

can you do the same with electron?

**Comment by Tribex** [comment]
@whatsdis Could you elaborate a bit? As far as I know, nw.js doesn't support chrome extension APIs, though they do have some similar APIs.

That being said, electron doesn't support chrome extensions out of the box, though it might be possible write a semi-compatible environment and API set.

**Comment by zcbenz** [comment]
We don't have any plan to support Chrome extension APIs.

**Comment by ungerik** [comment]
What about APIs like chrome.sockets, chrome.serial, chrome.bluetooth?

**Comment by paulcbetts** [comment]
@ungerik You can do most of these things via node modules, though the API is probably a bit different

**Comment by cesarmarinhorj** [comment]
But, there will be any kind of plugin, extension system?

There are tons of usefull extensions. Maybe later, could be great ideia to support them.

An example: The Great Suspender, that disables all tabs that are not used.

Even in Brave, as many tabs are used, more memory are consumed.
Thanks.

**Comment by thomasdarimont** [comment]
Seems to be possible now via `BrowserWindow.addDevToolsExtension`

See:
https://github.com/electron/electron/blob/5dcc354432bd9b6ca09c5cb887eac3a216820b8a/lib/browser/chrome-extension.js#L360
https://www.xplatform.rocks/2016/07/02/using-augury-inside-of-your-electron-apps/

**Comment by ThorstenHans** [comment]
Yeah as @thomasdarimont pointed out it's possible. I wrote that dedicated article in addition to the official electron docs right [here](http://electron.atom.io/docs/tutorial/devtools-extension/) because you've to ensure that you're using the path to the folder containing the `mainfest.json` file. 

It's also important to know that this will only work if the used extension is installed on the system actually running the app

**Comment by Tribex** [comment]
Isn't there a difference between DevTools extensions and Chrome Extensions?

**Comment by ThorstenHans** [comment]
@Tribex it depends. For the extension I've mentioned above, Augury. It's an regular Chrome Extensions integrating into the chrome dev tools. for regular extensions integrating in the app to empower the user, I dont know at the moment. Don't think this is possible because chromium comes without direct access to Chrome Web Store. So my article was covering the developer side.

**Comment by tomasro27** [comment]
I followed the guide, and electron opens correctly but the tab is not there.  I can't see any errors, or indications that something wrong happened.  I followed everything exactly.  Downloaded directly from chrome, added path correctly.  I'm using electron 0.37.6

**Comment by MarshallOfSound** [comment]
> I'm using electron 0.37.6

That is far too old to use most Chrome DevTools Extensions.  You probably need to update to at least `1.2.x+`

**Comment by tomasro27** [comment]
@marshallofsound thanks for the reply. I assumed there was a chance for it to work since the API call is there. But good to know. I'll have to wait to update electron version then

**Comment by AndyNormore** [comment]
This is still an issue in 2016. I have a website at www.SkyRooms.IO that uses an extension to do screen capturing with WebRTC. This feature is not available to my desktop users now. What should I do?

**Comment by bugdanov** [comment]
What about Google Input Tools ?... :-1:

**Comment by Arti3DPlayer** [comment]
chrome usb is super important :( Other usb libs have a lot of crossplatform issues

**Comment by alexstrat** [comment]
I listed [there](https://gist.github.com/alexstrat/0bc561e769664fc9ab520b73c0a2dd2c) all the Electron related blockers I face trying to load 2 popular Chrome extensions (Mailtracker and Grammarly) in Electron. I added references to electron's issue or PR.

**Comment by sferoze** [comment]
@alexstrat I checked that list of blockers you made and it looks like most of them are fixed...

So is the Grammarly plugin working right now in your electron app? If so can you point me in the right direction of how I can add it to my app? It seems rather complication....

**Comment by bianxg** [comment]
@AndyNormore  Have you fixed the issue? I meet the same one.

**Comment by bianxg** [comment]
@liguanpei  I give up to use chrome extension. I use desktop-capture api instead to desktop share.
https://electronjs.org/docs/api/desktop-capturer
