### ISSUE TITLE
build.py script freeze at LINK electron 

### ISSUE THREAD

**Issue by gliurn** [atom/electron#1501]
hi, so i try to build Electron but he block at build.py:

+ ./script/bootstrap.py
+ ./script/build.py
ninja: Entering directory `out/R'
[965/965] LINK electron

i work with version 0.25.1

it worked fine with version 0.21.3

ps: bootstrap.py take really more time than before

**Comment by zcbenz** [comment]
It is not frozen, it just takes too much time.

[A recent update](https://github.com/atom/electron/pull/1384) has traded build time for binary size and performance, you can still build Debug version quickly with [minimal bootstrapping](https://github.com/atom/electron/blob/master/docs/development/build-system-overview.md#minimal-bootstrapping) though.
