### ISSUE TITLE
WebContents `dom-ready` event

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#1504]
I would like to use `WebContents.insertCSS()` as soon as the DOM is ready.

I tried using `WebContents.on('did-finish-load')`, but you can see the page being loaded before the CSS is applied.

My workaround is to have the following in a `preload` JS file:

```js
document.addEventListener('DOMContentLoaded', function () {
	ipc.send('dom-ready');
});
```

and listen to the IPC event in the main renderer.

But it would be a lot nicer to have an event for this.

**Comment by kylebrowning** [comment]
How does one use this? Id like to add CSS for the whole app.

**Comment by sindresorhus** [comment]
@kylebrowning Like you should always do before asking, [read the docs](http://electron.atom.io/docs/v0.31.0/api/browser-window/#event-39-dom-ready-39).

**Comment by kylebrowning** [comment]
@sindresorhus Yeah I've gone over that I should have been more clear. Id like to add a whole file, not just some string.
