### ISSUE TITLE
Blocking navigation in WebView tag, post #1502

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1508]
Against the current master branch in the Slack app (05ae1960d1e421cf057a960b0526890665983c47), the shortcut for Back now works (Cmd-Left arrow on OS X), which now kills the WebView and restarts it. Since we don't have `webContents.will-navigate` on WebView tags, I can't find any way to block the navigation (`preventDefault` on `beforeunload` doesn't seem to work unless I'm doing it wrong)

**Comment by zcbenz** [comment]
The `will-navigate` event is synchronous in the main process, so exposing it for `<webview>` would be quite hard and I haven't found a decent way.

Making `beforeunload` handler work in webivew is totally achievable.

**Comment by paulcbetts** [comment]
> Making beforeunload handler work in webview is totally achievable.

That works for us

**Comment by paulcbetts** [comment]
@zcbenz Hm, this seems to work, but now when back gets hit, the page blanks out - DevTools still shows the content as being there, but the page is empty:

![](http://cl.ly/image/2u370J0q2z2Z/content#png)

**Comment by zcbenz** [comment]
I tried a simple page:

```html
<html>
<body>
test
<script type="text/javascript" charset="utf-8">
  window.onbeforeunload = function() {
    return false;
  };
</script>
</body>
</html>
```

in devtools:
```js
var w = new WebView;
w.src = 'http://google.com';
document.body.appendChild(w);
setTimeout(function() {
  w.src = '/tmp/test.html';
  setTimeout(function() {
    w.goBack();
  }, 1000);
}, 1000);
```

It seems to work fine.

**Comment by paulcbetts** [comment]
Doesn't explicit calls to `goBack` skip onbeforeunload?

**Comment by zcbenz** [comment]
In latest release it will call onbeforeunload handler.

**Comment by paulcbetts** [comment]
Is there a good place I can break in with WinDbg to try to poke around this some?

**Comment by zcbenz** [comment]
Hmm I don't know where to beak to debug the blank page, to debug onbeforeunload devtools should just work.

**Comment by paulcbetts** [comment]
I know that I'm at least hitting the onbeforeunload - I see different behavior when I return false (also I nslog'd the fuck out of it)

**Comment by zcbenz** [comment]
The result of `onbeforeunload` is compared at `atom::AtomJavaScriptDialogManager::RunBeforeUnloadDialog`, returning `false` has the same effect of returning nothing.

**Comment by paulcbetts** [comment]
Ah, I just meant, I see different behavior when I hook onbeforeunload vs. not connecting the event

**Comment by paulcbetts** [comment]
Alright, I think the real problem is #1608, gonna close this bug
