### ISSUE TITLE
[windows] crash-reporter process remains after quit app

### ISSUE THREAD

**Issue by nantas** [atom/electron#1509]
We are trying to implementing crash-report like this:
```js
App.on('will-finish-launching', function() {
        var crashReporter = require('crash-reporter');
        crashReporter.start({
            productName: 'Fireball',
            companyName: 'FireBox',
            submitUrl: 'some.url/crash-report',
            autoSubmit: false,
        });
});
```

But on windows no matter how we quit the app ( press 'X' to close window, ctrl+c to terminate process in command line, or call `app.quit()` in program), there will be a sticky Electron process left no matter what.

I downloaded process explorer and the sticky process command line looks like this:

`path\to\myapp\fireball.exe --reporter-url=some.url/crash-report --application-name=Fireball --v=1`

I checked crash-report docs but there's no mention how to close the process or prevent this from happening. Is there a bug or I missed something?

**Comment by zcbenz** [comment]
Will the process quit if you just call `crashReporter.start()` without parameters?

**Comment by nantas** [comment]
Yes, without parameter it will still stick around.
