### ISSUE TITLE
`./script/bootstrap.py -v` failed on v0.25.1

### ISSUE THREAD

**Issue by mizchi** [atom/electron#1511]
`gyp http GET https://atom.io/download/atom-shell/v0.25.1/iojs-v0.25.1.tar.gz`
`gyp http 403 https://atom.io/download/atom-shell/v0.25.1/iojs-v0.25.1.tar.gz`

It looks already released but can't access. Is it temporary?
https://github.com/atom/electron/releases

**Comment by djohns32** [comment]
I am seeing the same thing.  I tried to build it because I got a similar error when trying to run node-gyp for my own app using the released version.  So far, I have not had success building a plugin app using 64-bit electron.

**Comment by zcbenz** [comment]
It seems that iojs has changed the header name from `node-*.tar.gz` to `iojs-*.tar.gz`, we need to upload node headers also to the new locations.

**Comment by mizchi** [comment]
:+1:
