### ISSUE TITLE
[Windows] electron-prebuilt not able to find batch file

### ISSUE THREAD

**Issue by frabert** [atom/electron#1513]
I installed electron-prebuilt using npm the following way:
`npm install -g electron-prebuilt`. The procedure went ok and everything it's in its place. The problem is, when I try to run `electron` from my shell, i get:
`Unable to find the specified path` (or the equivalent, I actually translated the message).
I investigated a bit, and I found out that running
`C:\Users\MYUSER\AppData\Roaming\npm\node_modules\electron-prebuilt\run.bat` works just fine, while the problem is with `C:\Users\MYUSER\AppData\Roaming\npm\electron.cmd`, whose contents are listed below:
```
@IF EXIST "%~dp0\/bin/bash.exe" (
  "%~dp0\/bin/bash.exe"  "%~dp0\node_modules\electron-prebuilt\run.bat" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/bash  "%~dp0\node_modules\electron-prebuilt\run.bat" %*
)
```

Please note I have both cygwin64 and GitHub installed on my machine, as I suspect this to be related to some bash incompatibility.

**Comment by abacaj** [comment]
This sounds like a windows PATH issue, please try the following tutorial, http://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/

Instead substitute the path as: ```C:\Users\MYUSER\AppData\Roaming\npm\node_modules\electron-prebuilt\```

**Comment by frabert** [comment]
It doesn't work either, and anyway I wouldn't say adding electron's dir to PATH would be a great solution... In fact I don't even understand what electron.cmd tries to do by looking for bash...

**Comment by romovs** [comment]
#1492 seems related

**Comment by frabert** [comment]
Agreed. Same issue, same solution.
