### ISSUE TITLE
Framed window draggable

### ISSUE THREAD

**Issue by RileySpiller** [atom/electron#1517]
I'd like to have draggable regions of a framed window via the `-webkit-app-region: drag`. It seems that Electron ignores these style attributes unless it is a frameless window. 

Are there plans to allow for this?

**Comment by zcbenz** [comment]
Enabling draggable regions in framed window would complicates our implementation a lot, and I think it is also a bad design for most apps, so we won't support it unless there is very strong need for it.

**Comment by RileySpiller** [comment]
Many Mac windows have a full sized tool bars which are draggable and, until fully natively supported, could be created in HTML/CSS.

![image](https://cloud.githubusercontent.com/assets/1385324/7405960/3e1958ce-eec0-11e4-85d4-cedc2afd89e3.png)

I can't argue with the complexity of implementing it but ability to specify draggable regions would also allow for more unique app designs. See attached image. Both top and bottom bars are draggable. Designs such as these could be created in HTML/CSS if Electron would respect the `-webkit-app-region: drag`. 

![image](https://cloud.githubusercontent.com/assets/1385324/7405930/b6d0b6f0-eebf-11e4-866d-0c1c88a80f18.png)

**Comment by paulcbetts** [comment]
If you want to do something snazzy like this, I would actually just make it a frameless window, then reimplement the Yosemite window controls in HTML / JS. I did this for the Slack app and it was fairly easy (the only trick is handing Option-clicking the Zoom button)
