### ISSUE TITLE
Linux: ./electron: error while loading shared libraries: libgconf-2.so.4

### ISSUE THREAD

**Issue by maxogden** [atom/electron#1518]
to reproduce:

```
$ wget https://github.com/atom/electron/releases/download/v0.25.1/electron-v0.25.1-linux-x64.zip
$ unzip electron-v0.25.1-linux-x64.zip
$ ./electron
./electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

this is on Ubuntu:

```
$ uname -a
Linux burrito 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by maxogden** [comment]
workaround is `apt-get install libgconf-2-4` but I figured since this isn't mentioned anywhere in the docs or previous issues it might be a bug

**Comment by zcbenz** [comment]
After Chrome 42 libgconf has become a requirement for running on Linux.

**Comment by Martialhimanshu** [comment]
Try this trick, It worked for me:
after unzipping postman type following command in your terminal
`sudo apt-get install libgconf-2-4`
after running above command your postman will work for definitely. Surving to Ubuntu happily..

**Comment by joaoe** [comment]
The documentation is incorrect 

https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates

It says `libconfig-2-4`. There is no such thing.

**Comment by Yogesh9900** [comment]
sudo apt -y install libgconf2-4

**Comment by Stevengu999** [comment]
It's worked for me. Ubuntu18.
Linux i386 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitin7068** [comment]
> workaround is `apt-get install libgconf-2-4` but I figured since this isn't mentioned anywhere in the docs or previous issues it might be a bug

if this is not working then try with " sudo apt-get install libgconf-2-4"

**Comment by NickkoG** [comment]
I tried this but on a fresh install of LUbuntu 19.10 it dosen't work.

**Comment by sanket143** [comment]
What about arch linux?

**Comment by KevinWelton** [comment]
What exactly requires libgconf? Electron? We don't want users to have to
depend on _any_ external library being installed separately from Unity. CEF
used to require this in the editor, but the CEF dependency is finally gone.

I don't think _any_ of our supported distros (*only *Ubuntu 16.04/18.04 and
CentOS 7) have libgconf installed by default.

**Comment by ZishanAdThandar** [comment]
### **Here is the simplest solution** 
`sudo ln -s /usr/lib/libre2.so /usr/lib/libre2.so.4`
 
Replace the last digit as in error. 

_LIKE THIS COMMENT IF IT SOLVES THE ISSUE._

**Comment by sep2** [comment]
> What about arch linux?

`sudo pacman -S gconf`

**Comment by W1N3** [comment]
> What about arch linux?

Make the [AUR package](https://aur.archlinux.org/packages/gconf/).

**Comment by Immortalt** [comment]
> apt-get install libgconf-2-4

This works. Thanks!

**Comment by kkofler** [comment]
According to the comments on the AUR package:

> flying-sheep commented on 2020-01-06 19:20 
> Most of the packages that “require” it are actually Electron apps that copy&pasted their dependency lists from elsewhere or failed to update them: Chromium (and subsequently Electron) haven’t been dependent on this for years.

So if you still get pointed to this bug, it is probably a red herring.
