### ISSUE TITLE
Tray icon throws exception in production

### ISSUE THREAD

**Issue by oleander** [atom/electron#1522]
If I add this code to my `main.js` file I get an error.

code: 

``` javascript
appIcon = new Tray("assets/star-o.png"); // main.js:88
```

error:

```
Uncaught Exception:
TypeError: Error processing argument 0.
    at TypeError (native)
    at EventEmitter.<anonymous> (/Users/linus/Documents/projects/MyApp.app/Contents/Resources/app/main.js:88:13)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
```

The code works if I just use `node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron .` to start it, but not when the files are moved directly into `MyApp.app/Contents/Resources/app/`.

I'm using Electron `0.25.1` in OS X `10.10.3`.

**Comment by tommoor** [comment]
See previous answer here: https://github.com/atom/electron/issues/1299 :smile:

**Comment by oleander** [comment]
Using an absolute path worked, thanks!

**Comment by JoeGrasso** [comment]
If you are a Windows user, the problem had nothing to do with the image path but rather the setBounds values. The short of it is you must parseInt the values for the coordinates. This works for me:

>       const {app, BrowserWindow, Menu, Tray} = require('electron');
>       const {join} = require('path');
> 
>       let mainWindow, tray;
> 
>       app.on('ready', () => {
>       mainWindow = new BrowserWindow({
>         height: 500,
>         width: 300,
>         frame: false,
>         resizable: false,
>         // draggable: true,
>         show: false
>     });
>     mainWindow.loadURL(`file://${__dirname}/src/index.html`);
> 
>     const iconName = process.platform === 'win32' ? 'windows-icon@2x.png' : 'iconTemplate.png';
>     const iconPath = join(__dirname, `./src/assets/${iconName}`);
>     tray = new Tray(iconPath);
>     const contextMenu = Menu.buildFromTemplate([
>         {label: 'Item1', type: 'radio'},
>         {label: 'Item2', type: 'radio'},
>         {label: 'Item3', type: 'radio', checked: true},
>         {label: 'Item4', type: 'radio'}
>     ]);
>     tray.setToolTip('Right Click Icon for Options.');
>     tray.setContextMenu(contextMenu);
>     tray.on('click', (ev, bounds) => {
>         // Click event bounds
>         const {x, y} = bounds;
>         // Window height & width
>         const {height, width} = mainWindow.getBounds();
> 
>         if (mainWindow.isVisible()) {
>             mainWindow.hide();
>         } else {
>    
>        /////////////////////////////////////////////////////////////////////////////////////////////
>        // On Windows I had to parseInt the corrdinates
>        /////////////////////////////////////////////////////////////////////////////////////////////
>         const yPosition = process.platform === 'darwin' ? y : parseInt(y - height);
>         const xPosition = process.platform === 'darwin' ? x - width / 2 : parseInt(x - (width/2));
> 
>             mainWindow.setBounds({
>                 x: xPosition,
>                 y: yPosition,
>                 height,
>                 width
>             });
>             mainWindow.show();
>         }
>     })
>       });

**Comment by JHanLu** [comment]
@oleander Using an absolute path by how? Can u show me how does your path look like? Thanks

**Comment by dphans** [comment]
In production build, all resources has been archived into asar file (see: https://github.com/electron/electron/blob/master/docs/tutorial/application-distribution.md), so you can't use relation path to point the icon location into, read file inside asar instead:

For example, resource structure:
```
├── package.json
├── public
│   ├── img
│   │   ├── icons
│   │   ├── tray.png  <--- get this resource
│   │   ├── tray@2x.png
│   │   └── tray@3x.png
│   ├── index.html
├── src
│   ├── background.ts
```

Inside `background.ts` (which declare `Tray` instance), you should get inside `app.asar` archive:

```typescript
import path from 'path';

const trayIcnName = process.platform === 'win32' ? 'tray@2x.png' : 'tray.png';
const trayIcnPath = path.join(__dirname, `../app.asar/img/${trayIcnName}`);
tray = new Tray(trayIcnPath);
```

Final for both development/production builds:

```typescript
const trayIcnPath = process.env.WEBPACK_DEV_SERVER_URL
    ? path.join(__dirname, `../public/img/${trayIcnName}`)
    : path.join(__dirname, `../app.asar/img/${trayIcnName}`);
```

Hole useful for you!
