### ISSUE TITLE
File-Object not logging a path.

### ISSUE THREAD

**Issue by caseymorrisus** [atom/electron#1526]
Copied the example in [File Path](https://github.com/atom/electron/blob/master/docs/api/file-object.md) and cannot get it to work. Currently using Electron 0.25.1 and io.js 1.6.3

This is what is in my console log:

    "File you dragged here is"

Is there something I need to require to get this to work?

**Comment by caseymorrisus** [comment]
Funny how that works, but I figured out my issue immediately after posting this. The comma in the console.log was messing it up. 

Changing: `console.log('File you dragged here is' , file.path);`

To : `console.log('File you dragged here is' + file.path);`

Fixed the issue for me, now prints out the file path.

**Comment by thebouv** [comment]
I've only heard about electron as of today. Checking it out on github, saw this issue and thought "Oh, maybe I can go fix the File Path example as a real quickie."

But comma shouldn't have anything to do with your fix, as console.log takes a comma separated list of objects.

In fact, I just made a barebones electron app, copied the File Path example you linked as-is, and it worked fine with the comma.

Wonder what other change you could have made to make it work.

That [example code I made is here](https://github.com/thebouv/electron-file-example-fix)

**Comment by caseymorrisus** [comment]
Ahhh, I figured it might work on a barebones app. Obviously something in my code is making it mess up, not sure why changing the comma to a plus sign would fix it, but it did in my case.
