### ISSUE TITLE
OS idle time

### ISSUE THREAD

**Issue by rmanalan** [atom/electron#1528]
Our app needs access to the OS' idle time (mouse/keyboard idle). I don't see this supported anywhere. I also looked to see if there were any existing node modules that we could use... found none. So, now trying to figure out how to build a native extension. Electron could really use a dev guide on how to build native extensions that don't exists.

**Comment by paulcbetts** [comment]
You don't need a native node module on Windows or OS X to do this, you can actually use `node-ffi` - we've done the Windows one, I'll leave the OS X one as an exercise to the reader :)

```js
'use babel';

let ref = require('ref');
let refStruct = require('ref-struct');
let refArray = require('ref-array');
let ffi = require('ffi-atom-shell');

var intPtr = null;
var boolPtr = null;
var LASTINPUTINFO = null;
var OSVERSIONINFO = null;
var pOSVERSIONINFO = null;
var pLASTINPUTINFO = null;
var shell32 = null;
var user32 = null;
var kernel32 = null;
var dwmApi = null;

let setupWindowsLibs = function() {
  intPtr = intPtr || ref.refType(ref.types.int32);
  boolPtr = boolPtr || ref.refType(ref.types.bool);

  LASTINPUTINFO = LASTINPUTINFO || refStruct({
    cbSize: ref.types.int32,
    dwTime: ref.types.uint32,
  });

  pLASTINPUTINFO = pLASTINPUTINFO || ref.refType(LASTINPUTINFO);

  user32 = user32 || ffi.Library('user32', {
    'GetLastInputInfo': [ 'int', [ pLASTINPUTINFO ] ]
  });
};

exports = {
  'win32': {
    getIdleTimeInMs: () => {
      setupWindowsLibs();

      let result = new LASTINPUTINFO();
      result.cbSize = LASTINPUTINFO.size;

      let failed = (user32.GetLastInputInfo(result.ref()) === 0);

      if (failed) {
        throw new Error("Couldn't get idle time");
      }

      let ret = kernel32.GetTickCount() - result.dwTime;
      return ret;
    },
  },

  'darwin': {

    getIdleTimeInMs: () => {
      // TODO: Replace with a call to CGEventSourceCounterForEventType
      return 100000000;
    },

  },

  'linux': {
    getIdleTimeInMs: () => {
      return 100000000;
    },
};

module.exports = exports[process.platform];
```

**Comment by zcbenz** [comment]
For building a native module that doesn't exist, you can seek help from io.js's docs and community:
https://iojs.org/api/addons.html

**Comment by iamdriz** [comment]
@paulcbetts How do you use what you have posted in Electron if you don't need a Node module?

**Comment by paulcbetts** [comment]
> How do you use what you have posted in Electron if you don't need a Node module?

I phrased this badly - I mean, you don't need to _write a custom_ native Node module. You just use `node-ffi`

**Comment by iamdriz** [comment]
@paulcbetts I'm still not following what you mean mate. Could you show an example of how you could use what you posted inside an electron app? That'd be awesome, thanks.

**Comment by chandrachivukula** [comment]
@iamdriz did you get an example code that could be tested inside an electron app?

**Comment by nickaversano** [comment]
For anyone else who has this issue in the future, see: https://github.com/paulcbetts/node-system-idle-time

**Comment by watsoncj** [comment]
To expand on @paulcbetts excellent answer:

```

**Comment by robverhoef** [comment]
This works for me in OS X. I have a timer running, in Electron+Vue, after pressing a button. 
And I need to know the Idle time while it is running:
```
    import shell from 'shelljs'
    //
    // In the Vue methods block:
    //
      starttimer (event) {
        event.preventDefault()
        this.startDate = new Date()
        this.intv = setInterval(() => {
          this.endDate = new Date()
          const command = "/usr/sbin/ioreg -c IOHIDSystem | /usr/bin/awk '/HIDIdleTime/ {print int($NF/1000000000); exit}'"
          var child = shell.exec(command, {async: true, silent: true})
          child.stdout.on('data', (seconds) => {
            // do something after a certain amount of idle time
            console.log(seconds)
          })
        }, 1000)
      },
      stoptimer (event) {
        event.preventDefault()
        clearInterval(this.intv)
        this.intv = -1
      },
```

**Comment by cristian-datu** [comment]
@paulcbetts  You are a life saver. Thanks man.

**Comment by asinbow** [comment]
You can also use nodobjc in OSX:
```javascript
const $ = require('nodobjc');
$.framework('CoreGraphics');

let lastCount = 0;
let lastActiveTime = Date.now();
// start a timer
setInterval(() => {
  const kCGEventSourceStateCombinedSessionState = 0;
  const kCGEventSourceStateHIDSystemState = 1;

  const kCGAnyInputEventType = 0xffffffff;

  const count = $.CGEventSourceCounterForEventType(kCGEventSourceStateHIDSystemState, kCGAnyInputEventType);
  if (count > lastCount) {
    lastCount = count;
    lastActiveTime = Date.now();
  }
}, 100); // 100ms

const getIdleTime = () => {
  return (Date.now() - lastActiveTime)/1000;
}
```

**Comment by asinbow** [comment]
In Electron 3.x, https://electronjs.org/docs/api/power-monitor#powermonitorquerysystemidlestateidlethreshold-callback
https://electronjs.org/docs/api/power-monitor#powermonitorquerysystemidletimecallback

**Comment by bhagyakns** [comment]
@asinbow 

Hi,

I have a Java application for Win & Mac where I need to know if the user is in an 'idle' status (no user interaction in X minutes).

In Windows I am using GetLastInputInfo and it is working perfectly:
For Mac I have read that CGEventSourceCounterForEventType could help me. But I can not find how to use it in a Java method

I would thank any help,

**Comment by tmarwen** [comment]
For any future person who may land in this thread looking for idle time detection, you can use the [powerMonitor](https://www.electronjs.org/docs/api/power-monitor) API (available since Electron v3 under the name `querySystemIdle` as an asynchronous function and reviewed in Electron v6 as a synchronous function):
```js
const idleTime = powerMonitor.getSystemIdleTime()
```

**Comment by felipecrs** [comment]
Is there a better way to handle it as an event or should I code a cron to run every second just to check if the system is idle or not?
