### ISSUE TITLE
Accessing the Windows registry and reading/writing files

### ISSUE THREAD

**Issue by alexcroox** [atom/electron#1530]
Is it possible to access the Windows registry? I want to download some files via FTP to a STEAM game folder, but I'd rather not ask the user manually where STEAM is installed when I can work it out from the registry entry.

Also I can't find any documentation about reading and writing files to the filesystem like there is with nw.js. Has this been implemented?

**Comment by circuitbomb** [comment]
You might be able to use the shell module to run a shell-script that pipes what your looking for to the clipboard, retrieves it using the clipboard module, and then clears the clipboard when its done(or gets whats already there and rewrites it when its finished). Not sure about r/w files though.

**Comment by justinmchase** [comment]
Take a look at the `windows` package in npm:
https://www.npmjs.com/package/windows

It has some registry apis. They only work on windows of course.

**Comment by paulcbetts** [comment]
You should just use node.js modules to do this (`winreg` is a good one), you don't need to do anything special in Electron for this

**Comment by digitalextremist** [comment]
Came looking for the same thing... followed @justinmchase link; found updated `ffi` version:

`node-windows` https://www.npmjs.com/package/node-windows
