### ISSUE TITLE
It should crash on uncaughtException

### ISSUE THREAD

**Issue by mafintosh** [atom/electron#1536]
Currently if there is a uncaught exception, electron will catch that and print a message in the terminal. Personally I think it should just crash the process instead (and print an error dialog) so that you know this is happening.

If a user wants to override that behaviour they could just setup their own listener error listener - similar to how you do it in node (`process.on('uncaughtException', console.log.bind(console)`).

Otherwise it's hard to know that something bad happened and your app can enter some weird state because a callback wasn't called because there was an uncaught exception etc.

**Comment by zcbenz** [comment]
Electron follows io.js on this behavior, so changing it will cause confusions and might break existing apps.

**Comment by mafintosh** [comment]
io.js crashes on uncaught exceptions as well so i'm not completely sure what you mean by that?

**Comment by mark-hahn** [comment]
> io.js crashes on uncaught exceptions

I know what you mean but actually it just closes, not crashes.

**Comment by mafintosh** [comment]
@mark-hahn right yea :+1: my point is electron should close as well imo
