### ISSUE TITLE
Linux: Shell.openExternal with a link fails with Firefox

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1537]
This is a weird one: On my Ubuntu with Firefox installed as default browser, Shell.openExternal() with a http URL only works if Firefox is running. If it is not running, it does not start after calling the method. When I then click on Firefox from the task bar in my desktop, I get a message telling me that Firefox is already running and that I have to shutdown the process. Somehow Firefox gets stuck when being opened through Shell.openExternal().

I dont see this behavior when Firefox is opened and I can also not reproduce when using Google Chrome.

**Comment by zcbenz** [comment]
`Shell.openExternal` is a wrapper of `xdg-open` under Linux, I think you can try to reproduce the problem with `xdg-open` and then report it to Firefox.

**Comment by kevinushey** [comment]
For anyone else who stumbles upon this... this was eventually determined to be a Firefox bug, with some description of the issue here:

https://bbs.archlinux.org/viewtopic.php?id=284906
https://bugzilla.mozilla.org/show_bug.cgi?id=1820896
