### ISSUE TITLE
dialog.showSaveDialog cannot set the default filename

### ISSUE THREAD

**Issue by lealife** [atom/electron#1541]
```
dialog.showSaveDialog({title:"Untitled.png"}, function(targetPath) {
});
```
![image](https://cloud.githubusercontent.com/assets/1699428/7428374/332d8ed6-f022-11e4-8806-3d25442c864d.png)

mac os x Yosemite, electron v0.25.2

**Comment by lealife** [comment]
closed,  The dialog doc https://github.com/atom/electron/blob/master/docs/api/dialog.md isn't clearly, it can set defaultPath (filepath or filename) as the default filename.

**Comment by ThorstenHans** [comment]
works for me when passing options like this

````
dialog.showSaveDialog(mainWindow, {
    title: 'foo',
    defaultPath: '~/foo.xml'
  }, function(result){
});
````

**Comment by DavidVorick** [comment]
@ThorstenHans: That method only works for me if the file already exists. (Linux). Is there a way to set a default file that doesn't yet exist?

**Comment by Imskull** [comment]
`title` doesn't work on OSX
```
dialog.showSaveDialog({
  title: "abc.mp3",
},...)
```
Electron: v0.30.4

**Comment by hokein** [comment]
@Imskull 
You should use `defaultPath` to set the file name. The `title` is about the showing dialog's title.

**Comment by Imskull** [comment]
wow, `title` is for dialog's title!? I thought it was the filename, like the field in Google Drive API. thanks.

**Comment by resistdesign** [comment]
I used `*/MyDefaultFileName` as the `defaultPath` and that seems to work as the default file name and keeps the last used directory. :)
