### ISSUE TITLE
Porting Electron to android.

### ISSUE THREAD

**Issue by v3ss0n** [atom/electron#1542]
As more people are using Electron to make cross platform desktop apps , and Chromium already works on android very well  since like 10 released ago , how about porting Electron to Android? 
This will enable truly cross platform apps and performance will be better than Cordova because Electron is not using native webview.

This will make it possible for later porting of Atom to Android too. 

~ Coding on tablet dream comes true.

**Comment by zcbenz** [comment]
Chrome rewrote the whole interface for Android, and we don't have resources to do the same, so I don't think we will ever do this.
