### ISSUE TITLE
how can i use lokijs ?

### ISSUE THREAD

**Issue by tcdona** [atom/electron#1544]
http://lokijs.org/

the code db.js
```
var loki = require('lokijs')
var db =  new loki('./loki.json')
db.save()
```
worked by cmd node db.js and by node-webkit[nwjs.io]

but didn't work [electron] neither main.js [main process] or page.js required by main.html [render process] 
and i have try require('remote').require('lokijs') from page.js [render process]

**Comment by zcbenz** [comment]
I suggest reporting this to lokijs, if it is caused by some bugs in electron we can create a new issue for it.

**Comment by tcdona** [comment]
i think it maybe not cause by a bug, because i tried this code and it didn't work [i can'f find test.json file made in project folder ] too
```
var fs = require('fs')
fs.writeFileSync('./test.json', {encoding:'utf8'})
```

it's nothing about lokijs , and i can't find how. i must miss something ...

**Comment by tcdona** [comment]
i just find why i can't get my data "loki.json". 
that's all because the path! "./loki.json" is some where else i run the electron app
```
new loki(require('path').resolve(__dirname, './loki.json'))
```
this is what i need
or you have some way better, plz tell me !


the end.
