### ISSUE TITLE
API for ability to drag/drop item to menubar event?

### ISSUE THREAD

**Issue by niftylettuce** [atom/electron#1549]
In Mac OS X toolbar/menubar - if you drag and drop an item - is there an API for this?  e.g. to catch the file path etc or whatever it is that you're dragging to the toolbar icon?

**Comment by zcbenz** [comment]
As far as I know no platform has provided such APIs.

**Comment by sindresorhus** [comment]
It's possible on OS X at least: https://www.google.com/search?q=NSStatusItem+drag+drop

Would be a handy feature for menubar apps. Imagine having a menubar app for sharing photos. When you drag an image onto the menubar icon it get's published. Please reconsider.

**Comment by niftylettuce** [comment]
Thanks @sindresorhus for chiming in.  Let's get this in!  Who can take a stab at this?

**Comment by robincrorie** [comment]
I think i have a fix for this - will give it a go

**Comment by MarcFowler** [comment]
This is something I'd love to have as well, even if it was OSX-only. It would be awesome!

**Comment by sebcl** [comment]
CloudApp does this, I've been using it for at least 6 years. You drop any file and it gives you a short URL right on your clipboard.

http://www.getcloudapp.com/

**Comment by niftylettuce** [comment]
So does Dropbox Evernote etc

**Comment by niftylettuce** [comment]
Not sure how to delegate to the button of status item/menu... but this example makes the text "Hello" appear as an icon.

```
var $ = require('NodObjC')
$.import('Cocoa')
$.import('Foundation');
$.import('AppKit');
$.import('QuartzCore');

var pool = $.NSAutoreleasePool('alloc')('init'),
    app  = $.NSApplication('sharedApplication'),
    statusItem;

// set up the app delegate
var AppDelegate = $.NSObject.extend('AppDelegate')
AppDelegate.addMethod('applicationDidFinishLaunching:', 'v@:@', function (self, _cmd, notif) {

  var systemStatusBar = $.NSStatusBar('systemStatusBar');
  statusItem = systemStatusBar('statusItemWithLength', $.NSSquareStatusItemLength);
  statusItem('retain');

  var title = $.NSString('stringWithUTF8String', "Hello World");
  statusItem('setTitle', title);

  var dragView = $.DragStatusView('alloc')('initWithFrame', $.NSMakeRect(0, 0, 24, 24));
  dragView('registerForDraggedTypes', $.NSArray('arrayWithObjects', $.NSFilenamesPboardType()));
  statusItem('setView', dragView);
  dragView('release');

  /*
  // register with an array of types you'd like to accept
  [statusItem.button.window registerForDraggedTypes:@[NSFilenamesPboardType]];
  statusItem.button.window.delegate = self;
  */

})

AppDelegate.register()

var delegate = new AppDelegate('alloc')('init')
app('setDelegate', delegate)

app('activateIgnoringOtherApps', true)
app('run')

pool('release');
```

**Comment by robincrorie** [comment]
Ok... So below is what I came up with. The issue currently is that NodObjC doesn't allow me to specify protocols (or the implemented methods) for the `NSWindowDelegate`. In ObjC I would normally define this in `< SomeProtocol >` as follows:

`@interface AppDelegate : NSObject <NSApplicationDelegate, NSWindowDelegate> { `

There is a line in the example below: `statusMenu('button')('window')('setDelegate', self);` this would normally make the NSWindow "ask" the AppDelegate what to do for certain method calls..

This doesn't seem possible, or at least I couldn't find a way to achieve this.

```
var $ = require('NodObjC')
$.import('Cocoa')
$.import('Foundation');
$.import('AppKit');
$.import('QuartzCore');

var pool = $.NSAutoreleasePool('alloc')('init'),
    app  = $.NSApplication('sharedApplication'),
    statusMenu;

var AppDelegate = $.NSObject.extend('AppDelegate')

AppDelegate.addMethod('applicationDidFinishLaunching:', 'v@:@', function (self, _cmd, notif) {

  var systemStatusBar = $.NSStatusBar('systemStatusBar');
  statusMenu = systemStatusBar('statusItemWithLength', -1);
  statusMenu('retain');

  var title = $.NSString('stringWithUTF8String', "DragDrop");
  statusMenu('setTitle', title);
  statusMenu('setHighlightMode', true);

  var arrayDraggedTypes = $.NSMutableArray('alloc')('init')
  arrayDraggedTypes('addObject', $.NSFilenamesPboardType);
  
  statusMenu('button')('window')('registerForDraggedTypes', arrayDraggedTypes);
  statusMenu('button')('window')('setDelegate', self);
  console.log(self);
})

AppDelegate.addMethod('draggingEntered:', 'v@:@', function (self, _cmd, sender) {
  return $.NSDragOperationCopy;
})

AppDelegate.addMethod('performDragOperation:', 'v@:@', function (self, _cmd, sender) {
  console.log("WOWZA");
})

AppDelegate.register()

var delegate = AppDelegate('alloc')('init')
app('setDelegate', delegate)

app('activateIgnoringOtherApps', true)
app('run')

pool('release');
```

@niftylettuce; remember we where getting `undefined` on the `statusMenu.button.window`? I managed to get a reference to it by using `statusMenu('button')('window')` - just FYI

**Comment by niftylettuce** [comment]
@MarcFowler @sebcl @zcbenz @sindresorhus Any advice here?

**Comment by niftylettuce** [comment]
Can anyone help?

**Comment by hokein** [comment]
Recently I'm working on supporting 'right-clicked' event in tray #2232 , and I will take a look on this.

**Comment by MarcFowler** [comment]
Would be awesome!

**Comment by hokein** [comment]
I have implemented a `dragged-files` event in tray in #2232.

Feedbacks are welcomed.

**Comment by niftylettuce** [comment]
!!!!!!!!!!!!!!!!!!!!  :thumbsup:

**Comment by hokein** [comment]
Closing it since it has been supported in #2232.

**Comment by sebcl** [comment]
AWESOME! thank you, lots of love

**Comment by kemuri** [comment]
Is it possible to drag not jus files, but URLs and texts as well?
