### ISSUE TITLE
Is there a "reopen" event for Mac os x ? 

### ISSUE THREAD

**Issue by lealife** [atom/electron#1550]
On Mac, when close the window, we want to hide the window, and show it when user click the dock. Is there a "reopen" event for Mac os x ?  I know NW support it.

**Comment by zcbenz** [comment]
https://github.com/atom/electron/blob/master/docs/api/app.md#event-open-file

**Comment by lealife** [comment]
Hi, @zcbenz, "show it when user click the dock", when I click the docker to active hide window, Electron don't trigger "open-file" event

**Comment by lealife** [comment]
I find "activate-with-no-open-windows" works. thanks.

**Comment by Ivshti** [comment]
@lealife @zcbenz why don't we have an event for "activate" whether or not there are open windows. I find the better approach to be to keep the window open, but just hide it, which would eliminate the need to load it every time and it still allows it to do some background work (e.g notifications). Therefore, my app does not close the window and this event is useless.

**Comment by Ivshti** [comment]
Sorry, I was listening on the window instead on the app. It works fine with a hidden window.

However, does that work for Windows?
