### ISSUE TITLE
Tray icon with title text is cut off / hidden

### ISSUE THREAD

**Issue by ryanseys** [atom/electron#1552]
Hi I'm messing around with trying to create an alternative to the Degrees app using Electron. When setting the title on the tray icon it gets cut off.

Here's a screenshot of my version on the left and the Degrees.app running on the right. As you can see the text in mine is cut off and hidden. I can't seem to find a way to set the size of this area to fix this issue.

![image](https://cloud.githubusercontent.com/assets/163873/7438713/b117322a-f036-11e4-8736-44efc00cbed6.png)

**Comment by ryanseys** [comment]
I found that if I added a bunch of spaces to the end of the text, this helped to make it all show up.

``` js
tray.setTitle('19°C     ');
```

Not the most ideal work-around but a work-around nonetheless.

![image](https://cloud.githubusercontent.com/assets/163873/7439104/9d7bf72a-f03e-11e4-98be-6851d42209dd.png)

**Comment by cloudlakecho** [comment]
Where is this on the code? I couldn't find it.

**Comment by ryanseys** [comment]
Oh that's in my code, not Electron code

**Comment by zcbenz** [comment]
This is a bug of OS X, it seems that OS X didn't calculate the width of `°C` correctly. Setting title to other text works as expected.

More interestingly, following code works correctly:

```js
tray.setTitle('19');
tray.setTitle('19°C');
```
