### ISSUE TITLE
Tray image should be optional

### ISSUE THREAD

**Issue by ryanseys** [atom/electron#1553]
Why does a tray item need to have an image icon? We should be able to set it to just text, like the native OSX date tray item.

**Comment by YuriSolovyov** [comment]
True for OSX and, maybe, Linux, but what about Windows?

**Comment by paulcbetts** [comment]
Not true for Linux either

**Comment by zcbenz** [comment]
Unfortunately icon is required on Windows and Linux, you might try using a transparent image to work around it.

**Comment by bjornoj** [comment]
> Unfortunately icon is required on Windows and Linux, you might try using a transparent image to work around it.

You can set it in the library instead of forcing the user to pass `nativeImage.createEmpty()`.
