### ISSUE TITLE
BrowserWindow setProgressBar Indeterminate not working on Win 7

### ISSUE THREAD

**Issue by Akryum** [atom/electron#1555]
Hi,
I have trouble making my app to show the 'indeterminate' progress bar in the taskbar, using:

```javascript
mainWindow.setProgressBar(2);
```

Unfortunately, the taskbar deosn't show the animated 'Indeterminate' green progress bar.

My OS is Windows 7 64bit.

**Comment by zcbenz** [comment]
It seems to work on a fresh installed 32bit Windows 7 provided by modern.IE.
![screen shot 2015-05-04 at 4 04 42 pm](https://cloud.githubusercontent.com/assets/639601/7450464/db5c5072-f277-11e4-9826-363779df0380.png)

**Comment by Akryum** [comment]
It seems to come from my computer, I tested on my laptop running Win 8.1 64 bits and it works fine. I will try to find a program not being related to electron and having a indeterminate progress state to confirm that.
