### ISSUE TITLE
[windows] Option for not attaching to current console

### ISSUE THREAD

**Issue by terrajobst** [atom/electron#1556]
It seems electron is [always attaching](https://github.com/atom/electron/blob/922def8ce06b1dcec9c513f6512d0d224c9a68c9/atom/app/atom_main.cc#L90) to the current console session. That causes some weirdness on Windows.

For example, I'm using the command line a lot and I'm quite used to opening editors such as Sublime in the current directory. When doing this with electron-based apps, this results in the following (and from my point of view) non-desired behavior:

1. The electron instance is tied to the process of the shell. In other words, exiting the shell will not terminate before the instance of electron is closed.

2. A whole bunch of logging is printed to the current console window. I understand that logging can be useful, but most users really just want to launch their electron-based tools and not debug them. Thus, it feels weird to force the output spew on everyone (yes, I can suppress the logging via `--v=-1` but that seems reversed and doesn't solve the attach issue).

I suggest to either add a command line argument to suppress attaching or (my preference) making attaching opt-in. For now, I've solved the issue by setting the `OS` environment variable to `cygwin` prior to launching the tool, but I'm not sure this doesn't have undesired side-effects.

Thoughts?

**Comment by zcbenz** [comment]
I'm fine making it opt-in by setting some environment variable like `ATOM_SHELL_ATTACH_CONSOLE`.

@paulcbetts It was introduced by #122, how do you think?

**Comment by paulcbetts** [comment]
Nobody will find that environment variable, and having `console.log` not work in the browser process unless you say Magic Words is pretty bad for developers, that would make it even _more_ undebuggable than it is now. 

I think a better solution would be for editors that expect to be invoked by the command-line to use a cmd-based wrapper like Atom does

**Comment by terrajobst** [comment]
> I think a better solution would be for editors that expect to be invoked by the command-line to use a cmd-based wrapper like Atom does

To be clear, Atom.exe does attach to the existing console as well, which is undesired.

**Comment by etiktin** [comment]
The second point of the OP will no longer be relevant, once https://github.com/atom/electron/commit/cb903a09c0cd281f2cb934afe981b7a4f37d8bc3 is released. All internal logs are not printed, unless you pass `--enable-logging`.

**Comment by terrajobst** [comment]
I think @paulcbetts proposal is sound, i.e. provide the means for a command line wrapper to disable attaching. If `atom.exe` is using that it would be simple to add that to other hosts, such as VS code, as well.

**Comment by terrajobst** [comment]
Better late than never: Thanks! :+1:
