### ISSUE TITLE
little more info on node integration

### ISSUE THREAD

**Issue by zaggino** [atom/electron#1557]
Hi, I've been going a bit through the docs but I didn't find more detailed info about node-integration `true` vs `false`. I understand what it does, what I don't know are the consequences of enabling it. Say I want to keep memory usage of the browser process low, should I leave it off and use `require('remote')` calls instead, or it doesn't matter? I'm worried that using (loading) too many node modules may cause shell problems.

**Comment by cloudlakecho** [comment]
Node module and shell (operating system)...Would you explain in detail?

**Comment by zaggino** [comment]
Shell as a container in which the application lives - in this case its electron. Node modules like nodegit libraries or npm itself. For example npm peaks in hundreds of megabytes in ram when search feature is used. To be safe Id like to spawn a worker, do business there, send results to the browser process and kill the worker. Is this possible with electron?

**Comment by cloudlakecho** [comment]
Sorry, I need to study the electron to answer your question.

**Comment by zaggino** [comment]
Here's maybe a better description if I haven't made myself clear enough: https://github.com/rvagg/node-worker-farm#my-use-case

**Comment by cloudlakecho** [comment]
Thanks, it sounds like child process could be stopped by Java virtual machine garbage collector. On the Durability section on your link, I see there is Worker Farm. Where I can find the Worker Farm code?

**Comment by cloudlakecho** [comment]
Thanks, it sounds like child process could be stopped by Java virtual machine garbage collector. On the

**Comment by zcbenz** [comment]
Turning `node-integration` on or off doesn't have any difference on performance, and using `remote` module is slower than using those modules directly in the main process, because all `remote` calls will be executed in the main process.

**Comment by cloudlakecho** [comment]
Where could I find remote module in the code of electron?
