### ISSUE TITLE
inconsistency between require and require('remote').require

### ISSUE THREAD

**Issue by zaggino** [atom/electron#1559]
I have a following snippet of code:
*get-date.js*
```
module.exports = {
    obj: new Date()
};
```
in my index.html, when I use normal `require`, all is fine, but when I use `require('remote').require` on the same file, result is different:
```
var d = require('./get-date.js');
console.log({}.toString.call(d.obj)); // [object Date]
console.log(typeof d.obj.valueOf()); // number
console.log(typeof d.obj.getTime()); // number
        
var d2 = require('remote').require('./get-date.js');
console.log({}.toString.call(d2.obj)); // [object Date]
console.log(typeof d2.obj.valueOf()); // object
console.log(typeof d2.obj.getTime()); // Uncaught TypeError: d2.obj.getTime is not a function
```

using `electron-prebuilt 0.25.1-1`

**Comment by zcbenz** [comment]
Electron uses the `for in` loop to get members of an object, but it doesn't seem to work for `Date` instances. This behavior is unexpected but I'm afraid it is a limitation of JavaScript or a Chrome bug, so I'm closing this as won't fix.

**Comment by zaggino** [comment]
As far as I know, it should be possible to handle dates - https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/The_structured_clone_algorithm

There's a special case for Date which may be needed to apply here:
```
case Date:
      objectClone = new Constructor(objectToBeCloned.getTime());
      break;
```

**Comment by zaggino** [comment]
Should it be possible to fix it in https://github.com/atom/electron/blob/master/atom/renderer/api/lib/remote.coffee

**Comment by zcbenz** [comment]
It can only clone objects, to fix this we have to find a way to iterate the object's members.

**Comment by zaggino** [comment]
I don't think you need to iterate on `Date` members, just serialize to `getTime` which is a number and deserialize accordingly.

**Comment by zcbenz** [comment]
I'm not in favor of dealing with some types specially, it breaks the simplicity of the `remote` module. If we do this for `Date`, we will have to do the same for `RegExp`, `Symbol`... which is a quite long list. I would rather sacrifice the universality of the `remote` module instead of paying for JavaScript's stupidity.

**Comment by zaggino** [comment]
Disappointing, this basically breaks any library which returns some kind of Date information. Could you at least provide means of overriding `metaToValue` and `valueToMeta` methods per application? Currently they're private.

**Comment by zcbenz** [comment]
It is not recommended to use `remote` to pass complex data, its major purpose is to call methods in the main process. If you are using any library you should use it directly in the web page, calling via `remote` module is very slow and won't save you much memory.

**Comment by zaggino** [comment]
Thanks for the explanations. I'll avoid using `remote` then.
