### ISSUE TITLE
Electron won't read from asar archive

### ISSUE THREAD

**Issue by kand** [atom/electron#1563]
Following the pretty simple [Application Packaging](https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md) directions, I cannot get ```electron.exe``` to read from my asar archive.

This is the hello world app from the tutorial, which executes correctly with ```electron.exe``` if I copy the original source into the resources directory under an ```app/``` folder. However, when I package this in an asar archive, remove the original source from the resources directory and put the asar archive there, running ```electron.exe``` does nothing.

Is there a way to debug what's going on here? Is there a step/file I'm missing?

**Comment by kand** [comment]
Ah figured it out, I had entirely emptied out the resources directory, but it looks like you need to keep the ```atom.asar``` file.

**Comment by cloudlakecho** [comment]
I wonder what is the function of asar type file.

**Comment by frankhale** [comment]
The asar file type is there to allow a developer to package up all his
assets into one file.

**Comment by cloudlakecho** [comment]
Thanks for the information, Frank.

I have other question. When I read the source code in atom/electron version 0.25.2. I found this code section in atom_main.cc;

int APIENTRY wWinMain(HINSTANCE instance, HINSTANCE, wchar_t* cmd, int) {
  int argc = 0;
  wchar_t** wargv = ::CommandLineToArgvW(::GetCommandLineW(), &argc);

  scoped_ptr<base::Environment> env(base::Environment::Create());

I just wonder how I understand this line in the section;
"wchar_t** wargv = ::CommandLineToArgvW(::GetCommandLineW(), &argc);"

the ** and :: Would you able to interpret? I know that the * normally use to point and :: for member function, but in the line there is two * and :: is used without her class name. Do I miss something?

**Comment by frankhale** [comment]
I'm definitely not a good C++ programmer so I'm going to guess here. I think wargv is a pointer to an array of arguments. The :: makes sure that the function resolution happens in the global namespace.

**Comment by cloudlakecho** [comment]
Thanks for the response. I understand the global namespace. For the double asterisks, I will search around Internet.
