### ISSUE TITLE
How do I set favicon for browserWindow on Windows OS?

### ISSUE THREAD

**Issue by JW-Vinayak** [atom/electron#1569]
I want to set favicon for my app. So I have set config options as follows.

  `mainWindow = new BrowserWindow({width: 285, height: 350, icon: 'play.png'});
    mainWindow.loadUrl('index.html');`

The above code does not seem to work. Also tried following in index.html head section
`<link rel="icon" type="image/x-icon" href="play.png">` 
but this too doesn't load favicon.

**Comment by zcbenz** [comment]
The `icon` needs to be absolute path.

**Comment by JW-Vinayak** [comment]
@zcbenz Thanks !
