### ISSUE TITLE
did-get-response-details for Page

### ISSUE THREAD

**Issue by steelbrain** [atom/electron#1570]
It would be awesome to have a way to recognize the response details of the page itself and not it's resources.

**Comment by deepak1556** [comment]
`did-get-response-details` will be emitted for all `url_requests` occurring, which includes all schemes supported by `electron` (file, http, chrome-extension, asar, custom etc). Is there some resource that is not tracked by this event ?

**Comment by steelbrain** [comment]
They are all tracked, yes. But I only want to track the html files.
For example, There's a page called index.html and it has iframes to multiple html files and imports various scripts.
I only want to get the response details of the main index.html and not the html files it loads via iframes and the scripts it imports.
What I am trying to implement with it, is automatic downloading of resources when an archive link is clicked (is navigated to), instead of the archive links imported as other stuff in the page.

**Comment by steelbrain** [comment]
Nevermind, this is something that can be easily worked around in user land.
