### ISSUE TITLE
ondrop event problem.

### ISSUE THREAD

**Issue by koalaylj** [atom/electron#1576]
In [`File` Object](https://github.com/atom/electron/blob/master/docs/api/file-object.md) Document.
```javascript
    var file = e.dataTransfer.files[0];
    console.log('File you dragged here is', file.path);
```
file.path is not the path of the file you dragged in, it's always app's path.

**Comment by burakvarli** [comment]
file.path gives the dropped file's path actually. 
try this;
```javascript
console.log('File you dragged here is ' + file.path);
```

**Comment by zcbenz** [comment]
I belive @burakvarli has answered the question, thanks!
