### ISSUE TITLE
Invoke crash-reporter from custom code

### ISSUE THREAD

**Issue by ThorstenHans** [atom/electron#1577]
When using crash-reporter, it would be great to have a function that allows developers to send a custom crash report by using crash-reporter's API.

Right now it's a kind of black-box. You can set it up, but it's up to electron itself to send the crash reports. 

Having such a API endpoint would also allow devs to test the crash-reporter handling on both sides (within tha App and on the server side)

**Comment by zcbenz** [comment]
Calling `process.crash()` will force the process to crash and send the crash reports.

**Comment by ThorstenHans** [comment]
cool, thx @zcbenz

**Comment by ThorstenHans** [comment]
@zcbenz tried it yesterday with latest electorn-prebuilt version on OSX Yosemite. 

I've created a short node app which allows any data to be posted to a given url (http). Ive tried to invoke `process.crash()` from both processes but from none of them I received anything on the serverside, do you have any further tips?

**Comment by zcbenz** [comment]
Currently we have trouble using crash reporter on Yosemite, see also #1638.
