### ISSUE TITLE
Can't intsall using npm

### ISSUE THREAD

**Issue by burdokz** [atom/electron#1578]
I was trying to get started with electron but I got an error log during install

![Error Log](http://i.imgur.com/qkEZwR1.png)

I wonder if is something wrong I am doing or is something with the package since installing with npm is usualy simple.

**Comment by RinatMullayanov** [comment]
I get the same error.

**Comment by thesbros** [comment]
Are you using a proxy?

**Comment by RinatMullayanov** [comment]
https://github.com/atom/electron/issues/1578#issuecomment-99255271
Yes, and I added settings in .apmrc file(https-proxy and http-proxy)

**Comment by thesbros** [comment]
electron-prebuilt doesn't respect .apmrc proxy settings. It uses [nugget](http://npm.im/nugget) to download Electron, which doesn't seem to work with proxies.

You should raise an issue on [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) or [nugget](https://github.com/maxogden/nugget)'s repos.

**Comment by zcbenz** [comment]
I'm closing this since there is a corresponding issue in electron-prebuilt.
