### ISSUE TITLE
preload is not executed unless html contain script tags

### ISSUE THREAD

**Issue by thyrrestrup** [atom/electron#1580]
I have a problem with preload on webviews.
If the html page linked to in webview src does not contain the following:
```javascript
<script>
</script>
```
somewhere on the page the preload script is not executed.
The following does not work.
```javascript
<script></script>
```

I'm on OS X running Electron 0.25.2

**Comment by zcbenz** [comment]
This is caused by the same bug with #1117, I'm merging this issue to it.
