### ISSUE TITLE
RPC calls delay angular $digest

### ISSUE THREAD

**Issue by tonypee** [atom/electron#1581]
**EDIT**
the issue isn't with file:// - it seems to be RPC calls - read below
**
When running loadUrl('file://' + __dirname + 'index.html')  my angular application to has unexpected flickers, showing uncompiled templates - even though they are preloaded into the template cache (dont 'load' from external files at all). This seems fixed when running a local express server and using loadUrl('http://localhost:12345/index.html') things act normally. 

Interestingly, using node-webkit, it loads the files via file:// and things work fine. Im not sure where i should start looking. any ideas?

**Comment by tonypee** [comment]
It seems that the rpc calls block the code execution of angular, but not the render? If i run an rpc call at startup to say, create the menu, then the template will 1st be rendered un-compiled.

eg. require('remote').require('menu').buildFromTemplate(template)

So, does that call delay the code execution of angular, so that its compile pipeline is blocked. Therefore the un-compiled template is flashed? If i put other blocking code in there, then it works fine

eg: var c = 0;
while(c<10000000){
     c++;
}

**Comment by zcbenz** [comment]
Using `remote` blocks both the main process and renderer process because it sends synchronous messages, you might want to use `ipc` to send asynchronous messages explicitly to work around this.

**Comment by tonypee** [comment]
It makes sense that it should block (being synchronous), but then, i'm wondering why it fails. I dont want it to asynchronous, i want it to block the render too. 

I'll make a small example

**Comment by davej** [comment]
@tonypee: I'm having similar issues with Angular, were you able to come to a resolution?
