### ISSUE TITLE
Launched from tmux, keyboard input isn't handled

### ISSUE THREAD

**Issue by yuya-takeyama** [atom/electron#1588]
# Environment

![my environment](http://gyazo-yuyat.herokuapp.com/e2e35352b8598fef81e26cb718579d01.png)

And using electron installed using `npm install electron-prebuilt`.

```
$ electron -v
v0.25.2
```

# Steps to reproduce

Do below from tmux.

```
$ git clone https://gist.github.com/yuya-takeyama/a46008aeecb4c9a1c29b
$ cd a46008aeecb4c9a1c29b
$ electron `pwd`
```

`BrowserWindow` will be shown and it has text input.
But I can't input any characters.
Nevertheless `delete` key works.

**Comment by zcbenz** [comment]
Launching GUI applications from tmux causes various troubles, see also #916 and #3093 for some discussions and possible workarounds.
