### ISSUE TITLE
FileSystem: no such directory 

### ISSUE THREAD

**Issue by nebnes** [atom/electron#1589]
I am trying open a file: 

fs = require('fs')
fs.readFile('yo.txt', 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  console.log(data);
});

yo.txt exist but the error say: "no such directory"

**Comment by arthurakay** [comment]
You may have to try something like `path.join(__dirname, 'yo.txt');`

**Comment by ThorstenHans** [comment]
that's because you're only passing `yo.txt` to the fs module which is a valid directory name.  
In order to remain cross-platform compatible you should follow @arthurakay and change your code to

```
var fs = require('fs'),
  path = require('path');

fs.readFile(path.join(__dirname, 'yo.txt'), 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  console.log(data);
});
```
