### ISSUE TITLE
Upgrade to io.js 2.0.0

### ISSUE THREAD

**Issue by pauliusuza** [atom/electron#1591]
https://github.com/iojs/io.js/blob/master/CHANGELOG.md

Highlights:
- V8 4.2.77.18
- `class` keyword is now usable in strict mode without flags
- os.tmpdir() is now cross-platform consistent

**Comment by zcbenz** [comment]
We don't create issues to track upgrading to latest io.js and Chrome because we are already doing it regularly. We usually do the upgrade within 1 or 2 weeks after the new release.

For V8 4.2.77.18 and `class` keyword, we already have it in Electron.

**Comment by pauliusuza** [comment]
Thanks for explanation!

**Comment by mcz** [comment]
Is there any reason why 0.27.3 electron is still using io.js 1.6.3? There are already newer io.js versions released. Thank you.
