### ISSUE TITLE
Can I load WebPage without loading image?

### ISSUE THREAD

**Issue by zheung** [atom/electron#1592]
Can I load WebPage without loading image?
it seems not work like that:
```javascript
mainWindow = new BrowserWindow({
	'width': 1280,
	'height': 720,
	'web-preferences': {
		'javascript': false, //also not work
		'images': false
	}
});
```

**Comment by zcbenz** [comment]
Currently there is no option for it.

**Comment by zheung** [comment]
https://github.com/atom/electron/blob/master/docs/api/browser-window.md
but these options in the docs

should be removed from the docs?

**Comment by sebastienbarre** [comment]
Still not possible?
