### ISSUE TITLE
"Memory block is unallocated" messages flood the console in v0.25.2

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1597]
On the latest Electron, `stdout` is flooded with scary-looking messages when running the Slack app on OS X:
```
[15:07:36.182] CMBlockBufferGetDataPointer signalled err=-12707 (kFigBlockBufferUnallocatedBlockErr) (memory block is unallocated) at /SourceCache/CoreMedia_frameworks/CoreMedia-1562.235/Sources/Core/FigBlockBuffer/FigBlockBuffer.c line 1395
```

These messages start appearing once the `webview` tag has finished loading, but we don't have any other helpful information. :cry:

**Comment by CharlieHess** [comment]
Better steps to repro:
View a video or media plug-in (YouTube / Rdio embeds, etc.) within the `webview` tag.

**Comment by maxogden** [comment]
all messages that start with `[` are from chromium. You can [control the log level](https://github.com/atom/electron/blob/cd0aa4a956cb7a13cbe0e12029e6156c3e892924/docs/api/chrome-command-line-switches.md#--vlog_level) or just ignore the messages

**Comment by CharlieHess** [comment]
@maxogden: I tried disabling the logging with
``` coffeescript
  app.commandLine.appendSwitch 'v', -1
  app.commandLine.appendSwitch 'vmodule', 'console=0'
```
But it had no effect. Also feels a bit like brushing it under the rug; these messages only started in Chrome 42.

**Comment by Ivshti** [comment]
I also have this. Is there anything critical here?

**Comment by Ivshti** [comment]
@CharlieHess it makes sense to add the parameters to the cmd line earlier on, before initializing the processes. I'll try that way and report

**Comment by deepak1556** [comment]
yeah cant possibly disable these with switches as they are from coremedia framwork not chromium. @CharlieHess are those video embeds in webview using HTML5 or Flash based (just want to know if you get those messages in both the cases), @Ivshti you have these messages appearing under the same criteria (video embeds) ? Electron does nothing weird here to cause them so yeah can ignore.

**Comment by Ivshti** [comment]
@deepak1556 the HTML5 ``<video>`` tag for me. Sorry about not posting details, but actually besides that there is no specific circumstance - it happens on most mp4 videos.

**Comment by benmkramer** [comment]
Any information on this? I am having the same issue also using an html5 video tag.

**Comment by zcbenz** [comment]
I'm afraid there is nothing we can do to fix this, we can wait for upgrading to Chrome 43 and see if it fixes this.

**Comment by zcbenz** [comment]
It seems that Chrome43 has fixed this.

**Comment by saschagehlich** [comment]
These messages are still appearing with 0.28.1 / Chrome 43

**Comment by paulcbetts** [comment]
Looks like a patch has landed to fix this, we might consider including it early into libchromiumcontent:

https://code.google.com/p/chromium/issues/detail?id=498988

**Comment by zcbenz** [comment]
The Chrome 44 upgrade has fixed this.
