### ISSUE TITLE
fullscreen is not working

### ISSUE THREAD

**Issue by ashengwang** [atom/electron#1598]
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window'); 
require('crash-reporter').start();
var mainWindow = null;
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({kiosk:true});
  mainWindow.loadUrl('file://' + __dirname + '/index.htm');

  // Emitted when the window is closed.	
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});

**Comment by ashengwang** [comment]
I just test in windows 7

**Comment by sebcl** [comment]
works fine in osx 10.10.3

**Comment by TomMalbran** [comment]
I am having the same issue in windows 8.1
I would like to switch from nwjs to electron, but I need this feature.

**Comment by maxkueng** [comment]
I've just tried it in v0.26.1 with the same window options as in [my comment in issue 1721](https://github.com/atom/electron/issues/1721#issuecomment-103227974) on Manjaro Linux which is very similar to Arch. And kiosk mode seems to work equally well as in v0.25.1.

I don't have a Windows computer here but from my point of view, so far:

 - v0.26.1: WORKS
 - v0.26.0: BROKEN
 - v0.25.3: BROKEN
 - v0.25.2: BROKEN
 - v0.25.1: WORKS

**Comment by zcbenz** [comment]
@maxkueng I believe it has been fixed by #1616, thanks for tracking it!
