### ISSUE TITLE
Support "--proxy-pac-url"

### ISSUE THREAD

**Issue by magicae** [atom/electron#1599]
As Chromium, PAC for detecting correct proxy for current uri is useful. Any supports or plans about it?

**Comment by zcbenz** [comment]
As far as I now it is supported.

**Comment by magicae** [comment]
Any documents about it? I havent found docs about it

**Comment by zcbenz** [comment]
Electron just uses the system proxy settings.

**Comment by magicae** [comment]
With Chromium's commandLine switch
--proxy-pac-url=<pac-file-url>
This tells Chrome to use the PAC file at the specified URL.
For example,
  --proxy-pac-url="http://wpad/windows.pac"
will tell Chrome to resolve proxy information for URL requests using the windows.pac file. 

It makes proxy setting more elegant. Any plans about it? Related https://github.com/nwjs/nw.js/issues/916 on NW.js.

**Comment by zcbenz** [comment]
The `--proxy-pac-url` switch is not supported yet.

**Comment by adwilk** [comment]
+1 for --proxy-pac-url support

**Comment by jeromebenois** [comment]
+1 for --proxy-pac-url support

**Comment by dandruff123** [comment]
I am trying to create websocket connection with this PAC setting. Everything works when I connect to webSocket in the console in **Devtools** (which I believe is native to Chrome), however it doesn't work when I do the same from the **app** where I have to `require('ws')`.
Can you help me how to use Chrome websocket function or to find equivalent setting for the app that works?
