### ISSUE TITLE
Navigating to non-local URL using loadUrl displays blank screen in v0.25.2-win32-ia32

### ISSUE THREAD

**Issue by davewthompson** [atom/electron#1602]
Using latest version of v0.25.2-win32-ia32 download on Windows 7 x64.

Electron works file if you're browsing to a local URL. Browsing to a remote URL using either a redirect or a call to loadUrl results in a blank window.

**Comment by zcbenz** [comment]
Will `loadUrl('https://google.com')` work? And can you try with v0.25.3?

**Comment by zcbenz** [comment]
Closing until there is more information provided.

**Comment by TomasHubelbauer** [comment]
I am having the same issue with Electron 2.0.1:

```typescript
const { app, BrowserWindow } = require('electron');

app.on('ready', launchInfo => {
  const window = new BrowserWindow({ width: 800, height: 600 });
  window.webContents.loadURL('http://hubelbauer.net/');
  setTimeout(() => {
    window.webContents.capturePage(image => {
      const dataUrl = image.toDataURL();
      window.webContents.loadURL(dataUrl);
    });
  }, 1000);
});
```

![image](https://user-images.githubusercontent.com/6831144/40266499-658b8d36-5b4c-11e8-883e-411da1624827.png)

**Comment by TomasHubelbauer** [comment]
This is no longer problem with Electron 5.0.1 (probably much earlier).
