### ISSUE TITLE
No default font on Linux

### ISSUE THREAD

**Issue by zcbenz** [atom/electron#1605]
On Linux if no font is specified CJK characters will be showed as unrecognized characters, see also atom/atom#6214.

**Comment by paulcbetts** [comment]
I think this is perhaps a result of us not passing the correct OS language to the renderer (this might not be true anymore, I was looking into this long ago) - it seems to do different things based on it.

**Comment by bundyo** [comment]
Electron seems to choose different fonts on Linux. For instance for monospace Chrome 43 chooses Liberation Mono on my machine, while Electron chooses Courier New...
