### ISSUE TITLE
PushState doesn't work in WebViews, causes page refresh

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1608]
To repro:

1. Create a WebView tag whose source is "https://github.com/atom/electron"
1. `webView.openDevTools()` to see when the page refreshes
1. Click on folders, which would normally PJAX in the file listing
1. Page does a full refresh
1. Open Chrome, do the same thing, page doesn't refresh

**Comment by zcbenz** [comment]
@paulcbetts It is strange that the GitHub page only does partial refreshes on my machine (tested on Windows and OS X), though `webview.goBack()` would do a full refresh.

I tested by:

1) Open a webview tag
```js
var w = new WebView;
w.src = 'https://github.com/atom/electron';
document.body.appendChild(w);
```
2) Type some text in the page's text box
3) Click a folder
4) Page refreshes and the text is still there

**Comment by paulcbetts** [comment]
Ask J O S H P E E K about it, the way that the file view works is through https://github.com/defunkt/jquery-pjax - it's loading HTML via an AJAX call, calling `pushState` to change the URL, then loading the content. When it works, you shouldn't see the page content reload (i.e. if you have DevTools open and some console output in the window, it should still be there once a folder link is clicked - in Electron atm, that console output disappears)

**Comment by zcbenz** [comment]
I did a full rebuild and now I see it.

**Comment by zcbenz** [comment]
So this is actually a side effect of Electron's restarting renderer process for every navigation policy, pushState used to work in webview because webview didn't take that policy. We should find a way to recognize navigations started by pushState and make navigation work like normal browser for them.

**Comment by deepak1556** [comment]
weird that i am able to reproduce this issue only if i have `nodeIntegration` in the webview tag, otherwise i dont see the reload.

**Comment by zcbenz** [comment]
> weird that i am able to reproduce this issue only if i have nodeIntegration in the webview tag, otherwise i dont see the reload.

Ah turning off node integration solves this in both webview and `BrowserWindow`! It seems that this is actually caused by jQuery not being loaded?

**Comment by deepak1556** [comment]
Yup console cries with `$` is not defined with nodeIntegration.

**Comment by paulcbetts** [comment]
> weird that i am able to reproduce this issue only if i have nodeIntegration in the webview tag, otherwise i dont see the reload.

This is super surprising to me, I'd expect the opposite to happen - since PJAX is a jQuery plugin, I'd expect PJAX to only work if `nodeIntegration` is **disabled**, since otherwise jQuery doesn't load. GitHub probably falls back to full page loads in the absence of the PJAX plugin

**Comment by zcbenz** [comment]
@paulcbetts Are we good to close this?

**Comment by paulcbetts** [comment]
@zcbenz We're still completely busted on our end - for some reason that I have yet to track down, we always see a full page reload when you hit Back, even when you're pushState'd. The GitHub page doesn't repro it though, so I'll have to dig more.

**Comment by zcbenz** [comment]
@paulcbetts Navigating back will always cause a full page reload in Electron, because pushState only says it will add an entry in history without refresh, and says nothing about navigating back. 

In normal browser hitting Back gets you to previous page by loading it from cache, and I think the page knows nothing about it. And in Electron we have to do a full refresh to force renderer process to restart.

**Comment by paulcbetts** [comment]
> In normal browser hitting Back gets you to previous page by loading it from cache, and I think the page knows nothing about it

@zcbenz Hm, I'm not so sure - so here's the feature I'm trying to fix in Chrome 42; go to https://my.slack.com, then when it loads, click on a few channels / users. Then, hit the keyboard Back button - it'll instantly switch to the previous channel, no beforeunload, no content loaded from cache. There's some difference where browser Chrome doesn't do anything other than change the URL, and where we now full refresh.

**Comment by zcbenz** [comment]
> @zcbenz Hm, I'm not so sure - so here's the feature I'm trying to fix in Chrome 42; go to https://my.slack.com, then when it loads, click on a few channels / users. Then, hit the keyboard Back button - it'll instantly switch to the previous channel, no beforeunload, no content loaded from cache.

I see the difference now, it seems that hitting Back should emit the `popstate` event in the page.

**Comment by zcbenz** [comment]
@paulcbetts Navigating back now will not do full page refreshes if it is navigated with pushState, but pressing <kbd>delete</kbd> still does full page refresh, Chromium has this shortcut hard-coded somewhere and I didn't succeed to find it out, you may capture this key in the web page to prevent it from working.

**Comment by mkscrg** [comment]
We ran into this issue this week. Is there currently a way to make <kbd>backspace</kbd> work normally with `push`/`popState` in a `webview`?

> you may capture this key in the web page to prevent it from working

We tried capturing <kbd>backspace</kbd> on `window` and calling `window.history.back()`, but events from `<input>`s, `<textarea>`s, `contenteditables`, etc get there too. It seems brittle to blacklist elements from which <kbd>backspace</kbd> shouldn't cause navigation.

**Comment by zcbenz** [comment]
> We ran into this issue this week. Is there currently a way to make backspace work normally with push/popState in a webview?

It is quite hard to do, the best way is to find out where Chromium is doing this and patch it.
