### ISSUE TITLE
Clang requirement

### ISSUE THREAD

**Issue by sarnex** [atom/electron#1609]
Hi. Why clang is required? I am on gentoo and I can compile and use Atom/electron fine without it, and it doesn't seem that any clang atom packages are installed by default.

Thanks alot,
sarnex

**Comment by zcbenz** [comment]
Because clang is required by Chromium for building, and the prebuilt binaries of libchromiumcontent which used by Electron are built with clang. Also Electron uses some C++11 features which might not work older GCC.
