### ISSUE TITLE
BrowserWindow options minimum size on XFCE

### ISSUE THREAD

**Issue by gjuchault** [atom/electron#1610]
Hi,

I use Xubuntu (XFCE 4.12). Minimum sizing does not work :

```javascript
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    'min-width': 400,
    'min-height': 210,
    icon: 'icon.png'
  });
```

And i can get : `[340, 156]` when calling `remote.getCurrentWindow().getSize()̀̀` after over minifying the window.

And the window manager (xfwm4) does seem to support. Chrom* has a minimum size, along that others apps.

**Comment by gjuchault** [comment]
Note : with a frameless window, the min-x is working.

**Comment by thesbros** [comment]
Same problem on Arch Linux, XFCE/Xfwm4 v4.12.3.
