### ISSUE TITLE
Using electron and React

### ISSUE THREAD

**Issue by mderazon** [atom/electron#1611]
Hi, trying to understand how use IPC from a React view. I am using browserify + react and I want my component to send an IPC to the main process. is that even possible ?

there's no use to `require('ipc')` in the component as browserify doesn't know that module so it can't bundle it.

**Comment by marekhrabe** [comment]
best choice might be to avoid using browserify in electron. just load the main script directly without any transforms. you can just do `require('react'), require('ipc'), require('fs')` or anything in the script directly without any browserify shimming, because you are in fact in a node environment

**Comment by mderazon** [comment]
I would prefer not using browserify but my react is written with jsx so I still have to transform that...
Any way around it ?

**Comment by mderazon** [comment]
I think I see what you mean now,

I've been able to import jsx successfully using [node-jsx](https://github.com/petehunt/node-jsx):
```
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Castflix</title>
		<link rel="stylesheet" href="index.css">
	</head>
	<body>
		<div id="container">
		</div>
	</body>
	<script>
		require('node-jsx').install({ harmony: true, extension: '.jsx' });
		require('./app/main.jsx');
	</script>
</html>
```

pretty neat :-)

**Comment by marekhrabe** [comment]
You actually posted few seconds before my response :smile: I will put it here anyway as an alternative approach — a solution to actually run browserified code with electron's features. I wrote this:

> The main thing that makes it not work is that browserify will try to replace all `require` calls with some inlined code, so you can't use for example `require('ipc')` there, because it doesn't know that ipc module natively exists in environment you will be running the script at (Electron in this case). You can work around this by renaming the electron's require to something else like this:

> ```html
> <script>var electronRequire = require;</script>
> <script src="main.browserified.js"></script>
> ```

> And use `electronRequire('ipc')` in your browserified React component. 

Going the most native way (thus without browserify) will probably have most benefits.

**Comment by mderazon** [comment]
Thanks !

**Comment by LongLiveCHIEF** [comment]
A better solution, is to install [babel](https://babeljs.io/docs/using-babel/#babel_register), and then require it in to the global space of your main app file like so:

`require("babel/register")`

It will then auto-transpile `.es`, `.es6` and even `.jsx` files as they're executed from their required files.

I you're using Atom for developing your project, you can also use the babel pragma at the top of a `.jsx` file:

`"use babel";`

**Comment by locksmithdon** [comment]
@LongLiveCHIEF this would be my preference also, but I can't get it to work. I keep getting `Uncaught SyntaxError: Unexpected reserved word` errors. I'm using ES6 with React in an Electron app and it seems Babel isn't auto-transpiling. I'm using `require('babel/register')` in both of Electron's main and renderer processes, but it seems to not work in the renderer process. Can you point me to some documentation or a GitHub repo that uses this approach? 

I got @marekhrabe's `electronRequire` approach to work, but that doesn't seem as clean as not bundling the jsx files. Much thanks.

**Comment by Granze** [comment]
@locksmithdon thank you so much! I was struggling with the same problem and you approach solved it. :)

**Comment by LongLiveCHIEF** [comment]
:+1: Sorry I didn't reply to this sooner. I "unwatched" everything in github because I had spammed the watch button years ago. After going back and re-watching the important ones, I finally saw your note.

**Comment by jgod** [comment]
Thanks @mderazon, I got stuck on this forever and your solution seems to be the simplest one that works for my project!

**Comment by jgod** [comment]
I've also noticed that I have to require electron-specific modules "dynamically" (in function scope) so that Flow doesn't detect it as a non-valid module. Hope this helps someone that's using the same React/Flow + Electron stack.

**Comment by b52** [comment]
I compiled the proposed solution into a (minimal boilerplate app](https://github.com/b52/electron-es6-react).

**Comment by martin-brennan** [comment]
@marekhrabe thank you so much for that `electronRequire` solution, worked perfectly for me. I'm using jspm with ES6 for the record.

**Comment by singhshashi** [comment]
Thanks @b52  for the boilerplate. It served as a reference and helped me fix my issue. In your main.js you have a window.onload which calls the ReactDOM.render. I was previously trying as @locksmithdon has shown in his example, but that was not displaying the output and neither throwing any errors. By Adding window.onload I now get the output.

**Comment by H2OOPS** [comment]
I recommend something like this:
```html
<script>
(function() {
 const script = document.createElement('script');
 window.electronRequire = require; // => To Global Context
 script.src = (process.env.NODE_ENV !== 'production') ? 'http://localhost:8080/build/bundle.js' : '../build/bundle.js';
   document.write(script.outerHTML);
 }());
</script>
```

I'm using webpack and webpack-dev-server. This is an simple [example](https://github.com/jpetitcolas/webpack-react) of an single stack.

**Comment by ctsbala4587** [comment]
@marekhrabe thank you so much for that electronRequire solution, worked perfectly for me.

**Comment by fwextensions** [comment]
For anyone who might be trying to use the handy boilerplate from @b52 as model for updating an existing app and is getting `Unexpected token` errors when requiring a .jsx file (indicating that Babel isn't transpiling the JSX), don't forget to copy the `.babelrc` from the boilerplate repo to the root of your app directory.  I'd ignored it initially, but it's apparently crucial for getting Babel to work correctly.

**Comment by vernondegoede** [comment]
@fwextensions Or include your Babel settings in your `package.json` file :)

**Comment by fwextensions** [comment]
@vernondegoede Interesting, didn't know about that: https://babeljs.io/docs/usage/babelrc/#use-via-package-json

**Comment by tybro0103** [comment]
Let's not forget https://github.com/electron/electron-compile

**Comment by deecoolist** [comment]
I use babel-standalone on the renderer side, there for I could test es2015 so on without compiling the files.

```html
<script>
    require('babel-standalone')
</script>
<script type="text/babel"
    data-presets="es2017, react"
    data-plugins="transform-class-properties, transform-async-to-generator, transform-runtime"
    src="./test/test.jsx"></script>
```

good luck!
