### ISSUE TITLE
setBounds is not a function

### ISSUE THREAD

**Issue by sebcl** [atom/electron#1617]
Trying to use setBounds or getBounds in a BrowserWindow object, shows this error. 

Other methods like `show()` work quite well. 

`electron -v` reports `v0.25.2` (installed with npm -g)

**Comment by deepak1556** [comment]
`v0.25.2` doesnt have those apis, its only on master for now.

**Comment by sebcl** [comment]
is it on v0.25.3? is there a change log to know what changes does this version have?

**Comment by deepak1556** [comment]
Yup its there, you can check [releases](https://github.com/atom/electron/releases) for the changelog.
