### ISSUE TITLE
FileSystem API Crash

### ISSUE THREAD

**Issue by edoardocavazza** [atom/electron#1622]
Hi,

I have tried to port a html5 application to Electron, but the usage of FileSystem API makes Electron crash.

First of all, is this a wanted behaviour in favour of Node FileSystem API?

If not, I am going to write what happens:
- When I request quota using `navigator.webkitPersistentStorage.queryUsageAndQuota`, the method returns used and total quota == 0
- When I call `window.requestFileSystem` the app crashes.
- In the shell, I have this log `** Unknown exception behavior: 0`

Thanks for your job and your help!

**Comment by sapandiwakar** [comment]
I have the same problem (#1618)

**Comment by paulcbetts** [comment]
This probably fails because we have no way to prompt the user wired up - instead, you should just use `fs` from node

**Comment by edoardocavazza** [comment]
Thank you @paulcbetts !!

We already use the browser api in our chrome and cordova app, so I guess that the best (and painless) option is to create a browser-like api interface backed by the node FS. 

Could you point me the proper way (if it exists) to detect the Electron environment?

Thank you again!

**Comment by paulcbetts** [comment]
`let isElectron = process && process.versions['atom-shell']`

**Comment by zcbenz** [comment]
I'm merging this to #1618.
