### ISSUE TITLE
Build issues on Windows 8.1

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#1623]
Rather than bloating issue #1351 (which has been closed) I hope someone can help me with this related error.

```
C:\Users\Art\Desktop\Git Repos\sencha\electron>python script\build.py
ninja: Entering directory `out\R'
[328/961] CC obj\vendor\node\deps\openssl\openssl\crypto\dso\openssl.dso_win32.obj
c:\users\art\desktop\git repos\sencha\electron\vendor\node\deps\openssl\openssl\crypto\dso\dso_win32.c(289) : warning C4055: 'type cast' : from data pointe
r 'void *' to function pointer 'DSO_FUNC_TYPE'
[921/961] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True node.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment
.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.manifest" ob
j\vendor\node\node.node.dll.generated.manifest
LINK : fatal error LNK1181: cannot open input file 'C:\Users\Art\Desktop\Git.obj'
Traceback (most recent call last):
  File "gyp-win-tool", line 316, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /
OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1181
[921/961] CXX obj\atom\browser\electron_lib.web_dialog_helper.obj
ninja: build stopped: subcommand failed.
```

I have Visual Studio Professional installed, with Update 4. Git and Python 2.7.9. I'm using Windows Command Prompt for my shell.

I can run `clean.py` and `bootstrap.py` without any problems.

The interesting part of the error is:
```
LINK : fatal error LNK1181: cannot open input file 'C:\Users\Art\Desktop\Git.obj'
```

Why would it be looking on my desktop for `Git.obj`?

[edit] I have tried running with both Node 0.12.2 and 0.10.33 but both hit the error. (Swap via nvmw)

**Comment by romovs** [comment]
It's because of the space in your path `C:\Users\Art\Desktop\Git Repos\sencha\electron`. `build.py` probably isn't enclosing the paths within quotes somewhere...
Try moving it to some other path without spaces.

**Comment by thomasjo** [comment]
I'm 99% sure this is caused by the space in the path to the repo—`C:\Users\Art\Desktop\Git Repos\sencha\electron`. Either change "Git Repos" to "GitRepos", or clone the electron repo to another folder.

**Comment by thomasjo** [comment]
And for reference, the problem is rooted in `node-gyp`: https://github.com/TooTallNate/node-gyp/issues/65.

**Comment by arthurakay** [comment]
![image](https://cloud.githubusercontent.com/assets/401229/7549966/5712d3dc-f613-11e4-9a3a-5ecc29900fbc.png)

Thanks guys, that was totally the problem!
