### ISSUE TITLE
app.terminate() still calls beforeunload an emits window close

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#1624]
Calling ``app.terminate()``, contrary to what the docs say, still tries to close windows by emitting their close events and calls the DOM beforeunload/unload. It still allows them to be intercepted, therefore it's not any different to ``app.quit()``.

It should not emit those events

**Comment by zcbenz** [comment]
The `app.terminate` API has been deprecated a long ago, sorry I forgot to remove the docs. You can use Node's `process.exit` to replace it.

**Comment by Ivshti** [comment]
I tried process.exit and it didn't work from the renderer process - should I use it from the main process?

**Comment by zcbenz** [comment]
It works for the current process, if you want to exit the main process then you should call it there.

It is also possible to call it for main process in the renderer process too:

```js
require('remote').process.exit(0);
```

**Comment by Ivshti** [comment]
Okay. This should be documented.
