### ISSUE TITLE
Window position reported incorrectly in multi-monitor scenarios

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1625]
Starting in v0.25.2, I'm seeing an inconsistency in what `window.getPosition` returns. The bug seems to be exclusive to OS X. I have two monitors set up, with the primary display set as the rightmost (thus placing the secondary display in a negative coordinate space). Here's what the `screen` API returns for their bounds:
```
[0,0,1280,800]
[-2560,0,0,1440]
```
On Windows, when I position the window at the top of the secondary display, the bounds of the window (i.e., `p[0], p[1], p[0]+s[0], p[1]+s[1]`) seem reasonable:
```
[-1799,0,-712,746]
```
But on OS X, the y-coordinate has an offset applied:
```
[-1652,925,-742,1629]
```
That throws off all of our bounds checks. :cry:

**Comment by paulcbetts** [comment]
I think @tommoor was mentioning he was seeing similar strangeness

**Comment by tommoor** [comment]
@paulcbetts Indeed - I have an issue that I think might be related. Using either setPosition or the new setBounds API the position is set on the *currently focused* screen rather than being fixed. Ie:

- Click to focus some other application on screen 1
- setPosition(100,100)
- Click to focus some other application on screen 2
- setPosition(100,100)

The window will move to two different locations. I can split this out into a separate issue if needed.

**Comment by deepak1556** [comment]
@tommoor @CharlieHess  i know wats causing your issue [mainScreen](https://github.com/atom/electron/blob/06834b723ba211d0270ae3016690de9c0cee498b/atom/browser/native_window_mac.mm#L466) . @zcbenz `setPosition` and `getPosition` relying on `setBounds` and `getBounds` now, on OSX are using the current focused screen values. Should move it to primary screen instead ? I dont have a multi monitor setup to patch and test , can anyone here try a PR ?

**Comment by tommoor** [comment]
I can test an osx binary :wink: but not set up to build the code locally. I think that's almost definitely the issue though @deepak1556

**Comment by zcbenz** [comment]
> @tommoor @CharlieHess i know wats causing your issue mainScreen . @zcbenz setPosition and getPosition relying on setBounds and getBounds now, on OSX are using the current focused screen values. Should move it to primary screen instead ? I dont have a multi monitor setup to patch and test , can anyone here try a PR ?

Yeah we should use the primary screen, sorry that's my fault.
