### ISSUE TITLE
White flash on transparent window when shown

### ISSUE THREAD

**Issue by pimartin** [atom/electron#1626]
I have noticed a white flash when showing (using show() ) a transparent window on Linux (Ubuntu Gnome 14.10). I thought at first that it was due to the fact that the CSS wasn't fully applied when I tried to show the window, but the problem occurs even when show() is called on the 'dom-ready' event or after a setTimeout() of multiple seconds.

Here is the code in the main process :
```javascript
window = new BrowserWindow({
     'always-on-top': true,
     'skip-taskbar': true,
     'resizable': false,
     'frame': false,
     'transparent': true,
     'type': 'notification', // you can ignore this line, the bug appears even without it
     'height': 100,
     'width': 300,
     'show': false
});
window.webContents.on('dom-ready', function () {
    window.show();
});
window.loadUrl('...');
```

The HTML page:
```html
<!DOCTYPE HTML>
<html>
   <head>
      <meta charset="UTF-8">
      <title>Test</title>
   </head>
   <body>
      <p>Content</p>
   </body>
</html>
```

I've tried different CSS values for the background-color on html/body. It looks like the transparency is computed as if the environment below the window was white, then becomes what it should actually be. I've also noticed that there is an animation on the window (it expands). It might be the cause of the problem (this is a behaviour which does not seem present for all applications on my system).

EDIT: Electron is launched with the `--enable-transparent-visuals --disable-gpu` parameters.

**Comment by CharlieHess** [comment]
+1 to this issue; it seems to happen on Windows as well. I only noticed it around the time of the Chrome 42 upgrade.

Here's a video of the issue affecting Slack notifications: http://cl.ly/image/1P0k3n0k1v2V

**Comment by davej** [comment]
+1 also happens on Mac. Curiously when I run the app electron-prebuilt I can't recreate it but when I package my app up for distribution it occurs everytime. Tested with `0.27.1` and `0.27.2`.

@CharlieHess @pimartin: Can you verify if this issue still occurs when running your app with `electron-prebuilt` (instead of the packaged version).

**Comment by pimartin** [comment]
I did not specify it but that bug occurred with `electron-prebuilt`. I did not try with a packaged version of my "app" (which is just a bit of code that isn't really worth packaging or being called an app).

**Comment by davej** [comment]
Ok, I guess we are seeing different issues then.

FYI: I was able to fix the issue with a simple hack where I set the window size to `(0,0)` before showing and then setting it back to the original size after calling the `show` method call:

```javascript
window.setSize(0, 0)
window.show()
window.setSize(400, 400)
```

**Comment by davej** [comment]
Just to add, I am now seeing this issue with `electron-prebuilt` also. Not sure why I wasn't before. My hack above still works though.

**Comment by feross** [comment]
Can confirm this is still an issue.
