### ISSUE TITLE
Fullscreen exits when calling loadUrl, 0.25.2 on Windows

### ISSUE THREAD

**Issue by marwanhilmi** [atom/electron#1627]
It appears there was a bug introduced in 0.25.2 with the BrowserWindow class.
With the following code:
```
@window.loadUrl(targetUrl);
@window.setFullScreen(true);
@window.show();
```
The call to ```loadUrl``` will always exit the window out of fullscreen mode. If you call ```setFullScreen``` before ```loadUrl```, the window will enter fullscreen mode for a moment and then also exit out. Without a ```loadUrl``` call, the window stays in fullscreen mode.

This behavior was noted on Windows using electron-ia32 on 0.25.2 and above - have looked into changes introduced in 0.25.2 and have not noticed anything obvious that would cause this.

**Comment by zcbenz** [comment]
I'm merging this to #1598.
