### ISSUE TITLE
Custom Request Headers

### ISSUE THREAD

**Issue by kjlaw89** [atom/electron#1628]
Hello,

It would be useful to have the ability to modify the request headers before they're sent out, possibly an additional event ("did-begin-request" or something on webview or WebContents):

var loadrequest = function(requests) {
      requests["secretkey"] = "abc123";
      return requests;
}
webview.addEventListener("did-begin-request", loadrequest);

I've got a project where I need to pass special headers to a web server in order to access it and provide details about the application running.

Thanks!

**Comment by zcbenz** [comment]
I'm merging this to #2115.
