### ISSUE TITLE
packaging applications

### ISSUE THREAD

**Issue by wormen** [atom/electron#1629]
I have an application using the express, tell me how to package an application without using asar

**Comment by ThorstenHans** [comment]
you can distribute an application without packaging all the bits and bytes with asar as described within the docs at https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md

**Comment by wormen** [comment]
там не написано как упаковать в исполняемый файл

**Comment by ThorstenHans** [comment]
Download electron binaries install the app in the applications folder on OSX for example and put the app files (html, js,...) in

`/Applications/Electron.App/Contents/Resources/`

**Comment by wormen** [comment]
@ThorstenHans 
electron downloaded and installed, the application corresponds to the structure
how to pack it into exe file?

**Comment by ThorstenHans** [comment]
I've no Windows machine right here, but I think it's mentioned in the docs above. there are dedicated sections for OSX, Linux and Windows

**Comment by wormen** [comment]
I have looked everywhere where possible, 2 days it killed, and did not find how to package an application

**Comment by wormen** [comment]
here https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md
have information, how to run, but how to pack the executable is not present, as in the whole documentation

**Comment by paulcbetts** [comment]
There is no feature that lets you embed ASAR as a resource

**Comment by wormen** [comment]
I was interested in another time, already described above

**Comment by imcaffrey** [comment]
Does electron support transforming source codes into binary files?

**Comment by paulcbetts** [comment]
@imcaffrey No

**Comment by imcaffrey** [comment]
@paulcbetts Thanks.

**Comment by etiktin** [comment]
For future reference, it's possible to pack the entire app into a single executable on Windows using [Enigma Virtual Box](http://enigmaprotector.com/en/aboutvb.html).

**Comment by imcaffrey** [comment]
I prefer [`electron-packager`](https://www.npmjs.com/package/electron-packager).
