### ISSUE TITLE
Can i make a desktop mode app ?

### ISSUE THREAD

**Issue by crapthings** [atom/electron#1631]
Is there any possibility to make electron as a desktop mode app ?

**Comment by zcbenz** [comment]
What did you mean by "desktop mode app"?

**Comment by crapthings** [comment]
the app that run as wallpaper somehow.

**Comment by zcbenz** [comment]
You can set the `type` option of `BrowserWindow` to `desktop` to achieve that.

**Comment by gpsbird** [comment]
> You can set the `type` option of `BrowserWindow` to `desktop` to achieve that.

but it only works on mac and linux, how can it work on windows? is there any schedule or plan?
