### ISSUE TITLE
Electron PPAPI flash plugins shows no description

### ISSUE THREAD

**Issue by magicae** [atom/electron#1637]
OS: ArchLinux x86_64

In a normal chrome browser, `navigator.plugins["Shockwave Flash"]` shows
Plugin {0: MimeType, 1: MimeType, length: 2, description: "Shockwave Flash 17.0 r0", filename: "libpepflashplayer.so", name: "Shockwave Flash", item: function…}

But in electron#master, `navigator.plugins["Shockwave Flash"]` shows
Plugin {0: MimeType, 1: MimeType, length: 2, description: "", filename: "libpepflashplayer.so", name: "Shockwave Flash", item: function…}

Description of plugin object is important for many websites to auto detect the version of user's flash player, but it seems lost in Electron.
@zcbenz @deepak1556

**Comment by magicae** [comment]
It seems in `atom/app/atom_content_client.cc`, content::PepperPluginInfo CreatePepperFlashInfo
plugin.description is not set.

**Comment by deepak1556** [comment]
Oh didnt know that, thought the computation happens with name and version. Will add it, anyways chrome also does its computation with the [name and version](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/common/chrome_content_client.cc&cl=GROK&l=257)
