### ISSUE TITLE
Use crashpad for crash reporting on Mac

### ISSUE THREAD

**Issue by zcbenz** [atom/electron#1638]
Currently the `breakpad` library which is used by Electron for crash reporting doesn't work on Yosemite, and Chromium has migrated to use [crashpad](http://docs.crashpad.googlecode.com/git/doc/index.html) to replace it on Mac. We should do the same in Electron.

**Comment by lepinay** [comment]
Is there any plan to do the same for windows ?
As I understand, Crashpad should be the long term replacement for Breakpad on all platforms.

Have been having some corner cases with sandboxing and crash reporter in renderer processes on Windows which doesn't happen on mac.

I suspect it's an issue with breakpad on windows, so I could either try to fix Breakpad directly or migrate to Crashpad...any thought ?

Here is the issue I've been investigating https://github.com/electron/electron/issues/11072
