### ISSUE TITLE
CSS is only applied properly on resize

### ISSUE THREAD

**Issue by oleander** [atom/electron#1640]
I'm having some problems with my window not applying the CSS properly.

This how the window look at startup (note the big white box in the bottom).

![skarmavbild 2015-05-10 kl 17 38 51](https://cloud.githubusercontent.com/assets/220827/7555000/8c623250-f73d-11e4-8095-4d5f5b7b7097.png)

and this is how it looks after it's resized a few mm

![skarmavbild 2015-05-10 kl 17 38 56](https://cloud.githubusercontent.com/assets/220827/7555002/a7878a6c-f73d-11e4-8e75-4a9750360260.png)

Note that it disappeared in the bottom one. Does anyone know why this is happening?

I'm using Electron 0.25.1.

**Comment by zcbenz** [comment]
I suggest using devtools to investigate the style issues.
