### ISSUE TITLE
Entry * .asar

### ISSUE THREAD

**Issue by wormen** [atom/electron#1641]
Tell me, does the record in the files that are in the * .asar?

**Comment by sindresorhus** [comment]
It's unclear what you're asking. Can you elaborate?

**Comment by wormen** [comment]
for example, the archive is a config file or sqlite database ... that are in the * .asar if I have to write something?

**Comment by ThorstenHans** [comment]
what do you mean whith "I have to write something?"? by reading the title I would guess that you're asking how to specify the default asar file when distributing, or are you asking for the "entry" script that will be executed when starting your app?

**Comment by paulcbetts** [comment]
@wormen ASAR archives are read-only, you need to write to a different directory, you can't write to your own directory if you're in an archive

**Comment by wormen** [comment]
@paulcbetts thanks, I got it
