### ISSUE TITLE
Failed at the electron-prebuilt@0.25.3-2 install script 'node install.js'

### ISSUE THREAD

**Issue by nomosyn** [atom/electron#1643]
`$ sudo npm install electron-prebuilt -g` fails (see log below)

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion: 10.10.3
BuildVersion: 14D136

$ npm -v
2.7.4
```

[npm-debug.log](https://gist.github.com/nomosyn/8c9068c9b4f06f9257e6)

**Comment by atom2ueki** [comment]
+1

**Comment by NathanJang** [comment]
+1

**Comment by NathanJang** [comment]
This appears to be an issue with [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt/). Installing v0.25.2-1 instead appears to be working. @nomosyn would you mind creating an issue there?

**Comment by nomosyn** [comment]
Done: https://github.com/mafintosh/electron-prebuilt/issues/27

**Comment by NathanJang** [comment]
:+1:
