### ISSUE TITLE
DevTools extension

### ISSUE THREAD

**Issue by wormen** [atom/electron#1644]
you have the documentation
https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md
It described that can use plug-ins from google chrome, made as described therein, and then get an error

Uncaught TypeError: Cannot read property 'getURL' of undefined", source: chrome-extension://extension-1//panes/assets/ember-inspector.js (1)

code, a request of this type 
```
chrome.extension.getURL("/panes/ember_debug.js")
```

so that the error is not exactly in the plugin, as it is normal in the google chrome working

**Comment by sbruchmann** [comment]
Hello @wormen,

citing [docs you’ve linked](https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md):

> # `chrome.*` APIs

> Some chrome extensions use chrome.* APIs for some features, there is some effort to implement those APIs in Electron to make them work, but we have only implemented few for now.

> So if the devtools extension is using APIs other than chrome.devtools.*, it is very likely to fail, but you can report those extensions in the issues tracker so we can add support for those APIs.

These paragraphs should answer your original issue.

Would you like to request that the team and/or the community implement `chrome.extension.getURL`?

**Comment by wormen** [comment]
Yes, if you can, it would be a good idea to implement support Ember and React

**Comment by bruce** [comment]
I'd also like to request this feature; we're building an Ember-based application that interacts with hardware on top of Electron, and this would be extremely useful for debugging during development.

**Comment by bobisjan** [comment]
It would be great if Electron will support Ember Inspector.

Except `chrome.extension.getURL`, `chrome.extension.connect` is also being used by inspector.

**Comment by paulcbetts** [comment]
This is weird because according to the code, `chrome.extension.getURL` is already implemented (in fact, it's the _only_ chrome.* API implemented)

**Comment by deepak1556** [comment]
@wormen did you load with absolute path ? 

```
>  require('remote').require('browser-window').addDevToolsExtension(require('path').join(__dirname, 'ember-inspector', 'dist_chrome'))
<- "Ember Inspector"
```


But yeah we need to support content-scripts for react. ember and like extensions. can we track this under one issue #915

**Comment by wormen** [comment]
@deepak1556  yes

**Comment by zcbenz** [comment]
I'm merging this to #915.
