### ISSUE TITLE
What files are actually needed for a Windows distribution?

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#1648]
Now that I finally have electron building locally on my Windows machine, I see the `/out/R/` folder. Running the app from there works fine.

However, I notice that `/out/R/` contains 1.5GB of stuff... whereas the "release" zip files here on GitHub for either Windows 32/64 bit systems are considerably smaller (~100MB after unzip). Clearly a lot of the stuff inside `/out/R/` is not included in a "release" -- is there another script I can run to package only the files necessary for a "release"? Or what can we cull without breaking everything?

**Comment by paulcbetts** [comment]
@arthurakay https://github.com/atom/grunt-electron-installer/blob/master/template.nuspec#L14 is a pretty good list

**Comment by arthurakay** [comment]
@paulcbetts Thanks, that helps a great deal. Any particular reason the `out/R/` folder isn't "release-ready"? I expected the build scripts to automate this, considering it's "R" for "Release"... but perhaps I expect too much :-)

Also, I notice that the template you linked doesn't include an "Update.exe" or "LICENSE" -- but maybe those are products of the grunt plugin.

**Comment by paulcbetts** [comment]
@arthurakay Because deleting all of the PDB files sure would make it hard to debug :)
