### ISSUE TITLE
Make original-fs available in forked processes

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron#1652]
Currently a module not found error is thrown when doing `require('original-fs')` in a forked process.

**Comment by deepak1556** [comment]
@zcbenz `original-fs` is available in forked process as `require('originalFs')` [here](https://github.com/atom/electron/blob/master/atom/common/lib/asar_init.coffee#L12) .

**Comment by deepak1556** [comment]
should we change it to `original_fs` for consistency ?
