### ISSUE TITLE
package.json in UTF8

### ISSUE THREAD

**Issue by sartrey** [atom/electron#1654]
I tried quick-start example, but it worked not well.
After testing a few points, I found that maybe encoding of package.json causes problems.

My package.json:
![s1](https://cloud.githubusercontent.com/assets/3841135/7579650/95bb61b6-f899-11e4-9509-09b9a43596b8.png)

and then save it as UTF-8
![s2](https://cloud.githubusercontent.com/assets/3841135/7579655/ad9bc47e-f899-11e4-81c8-4bc58c9e0013.png)

run the app and get error
![s3](https://cloud.githubusercontent.com/assets/3841135/7579659/b86e5588-f899-11e4-89f6-d9bca5184137.png)

electron processes will stay alive
![s4](https://cloud.githubusercontent.com/assets/3841135/7579664/e0b754e0-f899-11e4-976b-9392943ca1b8.png)

try to save package.json as ANSI
![s5](https://cloud.githubusercontent.com/assets/3841135/7579669/f3e68f7c-f899-11e4-9a00-7d716e1fc63d.png)
then the app works well !

Is this a bug or special design?

**Comment by paulcbetts** [comment]
@sartrey I suspect that Notepad is including a UTF-8 BOM which is throwing us off. Can you upload an exact copy of the non-working package.json?

**Comment by sartrey** [comment]
@paulcbetts Thank you for your answer !
I use VS 2013 Express to save package.json as UTF-8 without BOM and it works.
How about appending the issue in quick-start document ?

And another problem, electron processes stay running after error.
Is this a bug ?

**Comment by paulcbetts** [comment]
> And another problem, electron processes stay running after error.

@sartrey It's a side-effect of how io.js works, it's not really ideal but it's expected at the moment

**Comment by sartrey** [comment]
@paulcbetts 
Thank you very much, I will close the issue.
Electron is an brilliant project !
