### ISSUE TITLE
Can't use MaterializeCSS

### ISSUE THREAD

**Issue by Jessestr** [atom/electron#1655]
http://materializecss.com/

Can't use it, always saying jQuery is not defined. So I fixed it by adding this:

    window.$ = window.jQuery = require('./bower_components/jquery/dist/jquery.min.js');

But then it said, it couldn't load HammerJS.... But you don't have to include that lib yourself. So kinda weird. Anyone any ideas?

**Comment by builden** [comment]
+1

**Comment by steelbrain** [comment]
It's a jQuery thingy, I think inside `jquery.min.js` is a code that checks for stuff like
```
if(typeof module !== 'undefined'){
  module.exports = jQuery;
} else if(typeof window !== 'undefined'){
  window.jQuery = jQuery;
}
```
The only __workaround__ I can think of is to disable node integration. or Maybe open up a bug @jquery and ask them guys to fix it.

**Comment by zcbenz** [comment]
See #254 for discussions on this.

**Comment by skewedlines** [comment]
A possible workaround for me would be to find and replace `require('jquery')` with `require('../../../../bower_components/jquery/dist/jquery.js')`, as well as `require('hammer')` and `require('./pickle')`. It's tedious but I don't have to disable node integration when I do this.

**Comment by imcaffrey** [comment]
I required 'hammer' manually and fixed.

Added

```
window.$ = window.jQuery = require('../assets/jquery/jquery-2.1.4.min.js');
window.Hammer = require('../assets/hammer/hammer.min.js');
```

**Comment by geogy** [comment]
thanks @Ir1d it works me perfectly, I have to add that all of these Javascript must to be put it before call the materialize.js

**Comment by scribnibblers** [comment]
For me to use Materialize-CSS with Electron I needed 3 lines:

```
window.$ = window.jQuery = require('./node_modules/jquery/dist/jquery.js');
window.Hammer = require('./node_modules/materialize-css/js/hammer.min.js');
require('materialize-css');
```

**Comment by Aceix** [comment]
just require('hammerjs') before <script src="materialize.js">
...and of course you have to run npm i hammerjs before all this. It WORKS for me!

**Comment by Serhioromano** [comment]
My renderer file

```js
"use strict";

window.$ = window.jQuery = require('jquery');
window.Hammer = require('hammerjs');
window._ = require('underscore');
require('materialize-css');
```

But does not work. Why? I've inserted example of collapsable from materialize site

```html
<ul class="collapsible">
    <li>
      <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
  </ul>
```

But it does not work.
