### ISSUE TITLE
No contextmenu in Developer Tools

### ISSUE THREAD

**Issue by jerone** [atom/electron#1656]
The contextmenu within the Developer Tools won't show in a specific situation. And with contextmenu I mean the contextmenu that shows up when you right-click inside a tab/panel withing the Developer Tools. For example right-click an element in the <kbd>Elements</kbd> tab. It only happens when I open in dev-mode and choose <kbd>Inspect Element</kbd> from Atom's contextmenu.

**Steps to reproduce issue:**

1. Open Atom in dev-mode (make sure Developer Tools is _not_ open already)
2. Right-click somewhere in Atom
3. Choose <kbd>Inspect Element</kbd>
4. Developer Tools will open
5. Right-click an element in the <kbd>Element</kbd> tab/panel from the Developer Tools
6. See no contextmenu appearing

**Working situations:**
* If I start the Developer Tools from the main-menu <kbd>View</kbd> > <kbd>Developer Tools</kbd> > <kbd>Toggle Developer Tools</kbd> this issue won't happen and the contextmenu shows up with all normal menu-items (e.g. <kbd>Add attribute</kbd>, etc.)
* Same goes for the shortcut <kbd>Alt + Ctrl + I</kbd>.
* Starting not in dev-mode doesn't have the contextmenu <kbd>Inspect Element</kbd>.

**Specs:**
Windows 8.1 Pro 64-bits
Atom 0.198.0

**Comment by zcbenz** [comment]
This had been fixed in recent releases of Electron, once we upgraded the version of Electron in Atom, this will gone.

**Comment by jerone** [comment]
[**@zcbenz**](https://github.com/zcbenz) commented on [20 mei 2015 07:59 CEST](https://github.com/atom/electron/issues/1656#issuecomment-103770839 "2015-05-20T05:59:51Z - Replied by Github Comment Enhancer"):
> This had been fixed in recent releases of Electron, once we upgraded the version of Electron in Atom, this will gone.

Thnx for letting me know, great to hear it's fixed. I'll follow Atom's commits to see when Electron is upgraded.

**Comment by ncortines** [comment]
Seems like it works for BrowserWindow but not for WebView tags. Anyone else having this issue?

**Comment by ncortines** [comment]
@zcbenz , can you please comment on the above? Thanks
