### ISSUE TITLE
fs - reading asar files fails

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1658]
I find electrons patching of fs functions a bit harsh. If you have code that fs.readFileSync() and you accidentaly read a foo.asar file that is just a text file renamed to foo.asar, you get an error "Invalid Package".

For Atom that uses asar this might make sense, but please make this configurable in Electron for clients that do not leverage asar.

**Comment by YuriSolovyov** [comment]
There is an `'original-fs'` module that you can require, which as you can see from it's name is not patched.
```js
var originalFs = require('original-fs');
originalFs.readFileSync('/path/to/example.asar');
```

**Comment by bpasero** [comment]
That is quite insane, it should be the other way around. A client can opt in to asar support with a method call and then things just work.

Now I have to change my node only code to use a module which might not be in all environments, specifically those where Atom is not around.

Atom should not temper with core modules and should not require me to write custom code that only works in the Atom environment. The code I write should run anywhere, either node.js, io.js or Atom.

**Comment by YuriSolovyov** [comment]
Well you have to have either special `asar-fs` module or patched node's `fs` + `original-fs` and I'm still not sure what's better.

**Comment by bpasero** [comment]
Well, graceful-fs is showing how to do it, just require it once and it patches the fs module. Thats how I would expect asar support to work too.

**Comment by paulcbetts** [comment]
> That is quite insane, it should be the other way around. A client can opt in to asar support with a method call and then things just work.

What you're describing is the *opposite* of "things just work", it means that every library that uses Electron now has to be ASAR aware (including ones that were not designed for Electron)

**Comment by bpasero** [comment]
Oh yeah, don't get me wrong, I like if things just work without custom
modules! But then don't throw a very weird non-node error when
fs.readFile() or fs.stat() a text file that happens to have a asar
extension.

If you overwrite a module, play by the rules of the module and don't break
its contract.
Am 13.05.2015 1:57 vorm. schrieb "Paul Betts" <notifications@github.com>:

**Comment by zcbenz** [comment]
This behavior has been there for a long time and many code are already relying on it, I'm afraid no matter whether it is good or not it has been too late to change this behavior, so I'm closing this as won't fix.

**Comment by Ivshti** [comment]
This is just frustrating.

Currently most extractor node.js modules do not work with the tarballs of our application because they contain an empty atom.asar.

Please think a bit more about what can be done about this. I'm not suggesting an opt-out of ASAR, but just for an option of handling ASAR errors separately somehow before they reach unsuspecting node.js modules.

**Comment by busticated** [comment]
for others running into this you can set `process.noAsar = true;` ([docs](https://electronjs.org/docs/tutorial/application-packaging#treating-an-asar-archive-as-a-normal-file)) and you'll get the normal node `fs` behavior
