### ISSUE TITLE
can't build for native modules

### ISSUE THREAD

**Issue by vid** [atom/electron#1659]
I'm seeing an http 403 error when trying to use [node-rebuild](https://github.com/paulcbetts/electron-rebuild/issues/2) and when trying to use ["the npm way"](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-npm-way)

**Comment by mattcollier** [comment]
vid, have you attempted the [node-gyp way](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-node-gyp-way)?  That's how I build native modules.

If that doesn't work, perhaps you can give us a gist of your error output.

Some people have had difficulty downloading the headers etc due to firewall policies and the like.

**Comment by vid** [comment]
I don't think it's firewall etc related. 

electron-rebuild worked until yesterday. I am hoping @paulcbetts can fix that problem since it was straightforward for different developers (including myself) to use.

      $ node_modules/.bin/electron-rebuild 
      gyp info it worked if it ends with ok
      gyp info using node-gyp@1.0.3
      gyp info using node@2.0.1 | linux | x64
      gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.25.3-2/node-v0.25.3-2.tar.gz
      gyp http 403 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.25.3-2/node-v0.25.3-2.tar.gz
      gyp WARN install got an error, rolling back install
      gyp ERR! install error 
      gyp ERR! stack Error: 403 status code downloading tarball
      gyp ERR! stack     at Request.<anonymous> (/home/vid/D/ix/ixnode/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
      gyp ERR! stack     at emitOne (events.js:82:20)
      gyp ERR! stack     at Request.emit (events.js:166:7)
      gyp ERR! stack     at Request.onRequestResponse (/home/vid/D/ix/ixnode/node_modules/electron-rebuild/node_modules/npm/node_modules/request/request.js:1156:10)
      gyp ERR! stack     at emitOne (events.js:77:13)
      gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
      gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
      gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
      gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:304:20)
      gyp ERR! stack     at emitOne (events.js:77:13)
      gyp ERR! System Linux 3.16.0-34-generic
      gyp ERR! command "/home/vid/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/vid/D/ix/ixnode/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.25.3-2" "--arch=x64" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
      gyp ERR! cwd /home/vid/D/ix/ixnode
      gyp ERR! node -v v2.0.1
      gyp ERR! node-gyp -v v1.0.3
      gyp ERR! not ok 

      Process exited with code: 1
      Error: Process exited with code: 1
          at ChildProcess.<anonymous> (/home/vid/D/ix/ixnode/node_modules/electron-rebuild/lib/spawn.js:53:26)
          at emitTwo (events.js:87:13)
          at ChildProcess.emit (events.js:169:7)
          at maybeClose (child_process.js:953:16)
          at Process.ChildProcess._handle.onexit (child_process.js:1020:5)

Here's output from the node-gyp way. I may be doing something wrong since I don't understand this stack entirely. I'm on Ubuntu 14.04.

        $ node -v
        v2.0.1
        $ HOME=~/.electron-gyp node-gyp rebuild --target=0.25.0 --arch=ia64 --dist-url=https://atom.io/download/atom-shell
        gyp info it worked if it ends with ok
        gyp info using node-gyp@1.0.3
        gyp info using node@2.0.1 | linux | x64
        gyp info spawn python
        gyp info spawn args [ '/home/vid/.nvm/versions/io.js/v2.0.1/lib/node_modules/node-gyp/gyp/gyp_main.py',
        gyp info spawn args   'binding.gyp',
        gyp info spawn args   '-f',
        gyp info spawn args   'make',
        gyp info spawn args   '-I',
        gyp info spawn args   '/home/vid/D/ix/ixnode/build/config.gypi',
        gyp info spawn args   '-I',
        gyp info spawn args   '/home/vid/.nvm/versions/io.js/v2.0.1/lib/node_modules/node-gyp/addon.gypi',
        gyp info spawn args   '-I',
        gyp info spawn args   '/home/vid/.electron-gyp/.node-gyp/0.25.0/common.gypi',
        gyp info spawn args   '-Dlibrary=shared_library',
        gyp info spawn args   '-Dvisibility=default',
        gyp info spawn args   '-Dnode_root_dir=/home/vid/.electron-gyp/.node-gyp/0.25.0',
        gyp info spawn args   '-Dmodule_root_dir=/home/vid/D/ix/ixnode',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp: binding.gyp not found (cwd: /home/vid/D/ix/ixnode) while trying to load binding.gyp
        gyp ERR! configure error 
        gyp ERR! stack Error: `gyp` failed with exit code: 1
        gyp ERR! stack     at ChildProcess.onCpExit (/home/vid/.nvm/versions/io.js/v2.0.1/lib/node_modules/node-gyp/lib/configure.js:343:16)
        gyp ERR! stack     at emitTwo (events.js:87:13)
        gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
        gyp ERR! System Linux 3.16.0-34-generic
        gyp ERR! command "/home/vid/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/vid/.nvm/versions/io.js/v2.0.1/bin/node-gyp" "rebuild" "--target=0.25.0" "--arch=ia64" "--dist-url=https://atom.io/download/atom-shell"
        gyp ERR! cwd /home/vid/D/ix/ixnode
        gyp ERR! node -v v2.0.1
        gyp ERR! node-gyp -v v1.0.3
        gyp ERR! not ok

**Comment by paulcbetts** [comment]
@vid It looks like some permissions got messed up in S3, it's probably fine to use `0.25.2` as your `nodeVersion`

**Comment by vid** [comment]
Thank you @paulcbetts , that worked.
