### ISSUE TITLE
Transparent frameless windows no longer work

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1665]
It appears that the latest release v0.26.0 broke transparent frameless windows, a small grey bar of chrome now appears across the top in OSX. I'm not sure if this is also the case on other platforms.

**Comment by joshaber** [comment]
Almost certainly caused by https://github.com/atom/electron/pull/1585.

If you use `'standard-window': false` in your window options, does it work?

**Comment by tommoor** [comment]
@joshaber that fixes it, thanks! I'd say this issue should remain open as the default behaviour here is now quite odd - you need to get the combination of window options just right

**Comment by joshaber** [comment]
Yup, you're right. We should infer that from `transparent`.
