### ISSUE TITLE
transparent window resize

### ISSUE THREAD

**Issue by sartrey** [atom/electron#1671]
Frameless non-transparent window will flash when resizing,
while transparent windows flash not very obviously.

I found some improper points.

First, transparent window will not fill screen when max,
it will keep a gap between window border and screen edge
![s2](https://cloud.githubusercontent.com/assets/3841135/7603152/e2034e22-f960-11e4-93ac-10a30ea0478e.png)
this is a top-right corner of my test window, the white and light gray border is gap.

Second, transparent window can be resized when max,
maybe it is because of the first point ?

Third, if transparent window is resized when max, it will not remember the right max bounds.

**Comment by amberjs** [comment]
Fourth (If I may add it here):
When setting resize to false on a Frameles, Transparent window, resizing remains possible.

**Comment by zcbenz** [comment]
Please break this issue into separate ones with demo code and screenshots, and please also provide information about your operating system.
