### ISSUE TITLE
How to open js console  panel in windows?

### ISSUE THREAD

**Issue by litehot** [atom/electron#1672]
It's command + alt + i on mac,but I can't open it on windows

**Comment by CharlieHess** [comment]
@litehot: Try `Ctrl`+`Shift`+`I`.

**Comment by litehot** [comment]
No,not work,I was try many like Ctrl Shift Alt + I key combinations。

**Comment by zcbenz** [comment]
Hi, the GitHub issues page is only used for feature requests and bug reports, for questions it is recommended to ask on the [`electron` category on the Atom forums](http://discuss.atom.io/category/electron).
