### ISSUE TITLE
window.open questions

### ISSUE THREAD

**Issue by zaggino** [atom/electron#1673]
1) should using `window.open` spawn a window which will have node-integration?
2) if I spawn a window through `BrowserWindow` to have proper node-integration, can I access its `window` object space directly?

Basically Brackets is doing integration tests like this:
```
 _testWindow = window.open(getBracketsSourceRoot() + "/index.html?" + params.toString(), "_blank", optionsStr);
_testWindow.brackets.test.CommandManager.execute(cmd, args);
```

I'd like to see if I can somehow port these tests into Electron.

**Comment by zaggino** [comment]
This would be a minimum sample of how Bracekets (and maybe other apps too) work: https://github.com/zaggino/electron-sample

**Comment by ThorstenHans** [comment]
what do you mean with "node-integration" there are several modules available to both processes `main` and `renderer` you can either use `remote` to interact with node modules form the `renderer` or you can use `ipc` to communicate between both processes.

**Comment by zaggino** [comment]
I don't want to open a new process with `window.open`, I just want to open a new window and have control over it like in the traditional browser environment. Is that possible?

**Comment by paulcbetts** [comment]
> 1) should using window.open spawn a window which will have node-integration?

Good question. The ideal answer to this should probably be that it inherits whatever its parent is doing. 

> 2) if I spawn a window through BrowserWindow to have proper node-integration, can I access its window object space directly?

No, you need to call the `executeJavaScript` method. This method returns `void`, but with a few backflips you can make it return a JSONish value asynchronously by injecting some code into the target page that will respond to requests to eval code and send the result back over IPC. Something like:

```js
// Inject this into the child window:
window.rendererEvalAsync = (blob) => {
  let data = JSON.parse(decodeURIComponent(blob));
  try {
    data.result = JSON.stringify(eval(data.code));
  } catch (error) {
    data.error = { stack: error.stack, message: error.message };
  }

  ipc.sendToHost('eval-async', data);
};

// In the parent
  // Public: Executes JavaScript in the context of the SSB and returns the
  // result, as long as it is JSON-serializable (unlike the built-in
  // executeJavaScript)
  //
  // Returns an Observable Promise which is either the return value of the
  // code that was invoked, or onErrors with the Error that was thrown.
  executeJavaScript(code) {
    let msg = { code: code, id: uuid.v4() };

    // TODO: Listen to IPC messages with 'eval-async' and return a Promise.
    // Our implementation is very Rx'y and I didn't want to make this sample super
    // complicated

    // NB: This is a secret handshake with the embedded page    this.wv.executeJavaScript(`global.rendererEvalAsync(\"${encodeURIComponent(JSON.stringify(msg))}\")`);
    return ret;
  }
```

**Comment by zcbenz** [comment]
The `window.open` in Electron is only used for being compatible with traditional web pages, its API is very limited so it is not possible to find out a behavior that works for all cases. For any complex app it is recommended to use `browser-window` module directly.
