### ISSUE TITLE
Not loading ppapi flash in windows 8.1 x64

### ISSUE THREAD

**Issue by MikeGCV** [atom/electron#1674]
I don't know if i'm doing this correctly, i copy the PepperFlash folder from a chrome intallation inside electron folder (x64). Inside this folder there's libpepflashplayer.dll and manifest.json.

I start electron with the following command:
electron.exe . --ppapi-flash-path=PepperFlash\libpepflashplayer.dll --ppapi-flash-version=17.0.0.188

In the app i open an external webpage that uses flash like http://taggalaxy.de/ 
It's says i need a new version of flash and when i go to http://www.adobe.com/software/flash/about/
it says "couldn't load plugin"

Thank you

**Comment by deepak1556** [comment]
Do you have 

```
'web-preferences': {
   'plugins': true
}
```

option set when creating browser-window ?

**Comment by magicae** [comment]
Because http://taggalaxy.de uses SwfObject.js(http://taggalaxy.de/assets/swfobject.js) to auto detect the flash version of browser. Such detecting is always based on plugins.description. But in current electron, it's missing, refer to https://github.com/atom/electron/issues/1637

**Comment by deepak1556** [comment]
@magicae  that shouldnt apply to [http://www.adobe.com/software/flash/about/](http://www.adobe.com/software/flash/about/) . `Couldnt load plugin` will be caused only if renderer doesnt have the permission to load the plugin, which is enabled in browser with the option as quoted above or in webview tag as `plugins`

**Comment by magicae** [comment]
@deepak1556
I only test on http://taggalaxy.de/ before, and now I test it on http://www.adobe.com/software/flash/about/. ppapi is ok on this Adobe page.

**Comment by MikeGCV** [comment]
@deepak1556

Ok, sorry, i didn't have 

'web-preferences': {
   'plugins': true
}

in my script. Now in the logs i have the following error:

[15212:0513/142716:ERROR:ppapi_thread.cc(278)] Failed to load Pepper module from PepperFlash/libpepflashplayer.dll (error: 126)

**Comment by deepak1556** [comment]
Did you copy the DLL from the same location as chrome is using ? `chrome://plugins` should help with that. Or else can you try downloading the pepper flash from adobe and try using that. Don't have a windows machine to test, sorry.

**Comment by MikeGCV** [comment]
@deepak1556

Thank you, adobe pepper did the trick, so now the only thing missing is issue #1637

**Comment by hokein** [comment]
I think we should add some tutorials about how to use ppapi plugin in electron. It will really helpful for people.

**Comment by Gregg8** [comment]
We are having a similar problem. We copied the pepper flash dll from the location specified in chrome://plugins but that didn't work. We get the message "To view this page ensure that Adobe Flash Player version 11.5.0 or greater is installed".

Could you please provide a link to where you downloaded the Adobe Pepper Flash plugin?

**Comment by MikeGCV** [comment]
https://get.adobe.com/flashplayer/otherversions/

Choose windows version and the ppapi version installer

The dll will bee in the following folder:

C:\Windows/SysWOW64\Macromed\Flash

**Comment by deepak1556** [comment]
i guess this needs to be documented, as the dll required for chromium is different from the one shipped with chrome. @magicae can you add this extra doc to your existing PR fixing the plugin description if possible ?

**Comment by magicae** [comment]
OK but i dont know how to get windows / macos pepper flash, only on linux it can be easily found in chrome's install path and can be used for electron directly.

**Comment by Gregg8** [comment]
Thanks everyone for responding so quickly and yes, it would be great to have good documentation for this. I am finishing up today so will test this in the morning and report back. I could be a set of Windows eyes and ears for you if required.

**Comment by deepak1556** [comment]
Thanks @magicae , the problem is only with windows dll. Even on OS X you can use the same path specified under `chrome://plugins` . It would be better if any windows user documents this.

**Comment by MikeGCV** [comment]
builded with magicae patch and now http://taggalaxy.de works

**Comment by Gregg8** [comment]
Like MikeGCV, I can get Flash working, but only with the default/installed Flash player. I cannot get it working when I specify a `ppapi-flash-path`.

To make this easy to replicate, I have created a small repo with a README.

https://github.com/Gregg8/electron-ppapi-test

Am I doing anything wrong here?

I'd be most curious to know if other Windows users could get this simple code to work.

@MikeGCV, is your code working with a custom `ppapi-flash-path`? If so, would you mind sharing the line of code that specifies this?

I am also on Win8.1 x64.

**Comment by magicae** [comment]
@Gregg8 
Try this url, http://www.adobe.com/software/flash/about/, is flash working?
Sorry for typo in document, I've created a new pr.

**Comment by Gregg8** [comment]
Yes:
 - In Chrome (42), it declares: "You have version 17,0,0,188 installed"
 - If I open that url in my app in the above repo, it says: "You have version 17,0,0,169 installed"

**Comment by magicae** [comment]
@Gregg8 
It's related to https://github.com/atom/electron/issues/1637. And now fixed. Your code is all right but you should compile current electron#master yourself or wait for next release. :D

**Comment by Gregg8** [comment]
Ok then, am crossing my fingers that will solve it. Will wait for next release as I don't have a C++ compiler set up here.

Any ideas on a next release date?

Another conclusion would be that @MikeGCV is experiencing the same issue and therefore if his app is working, it will be working with the default Flash player rather than any specified by `ppapi-flash-path`. Any thoughts, @MikeGCV ?
