### ISSUE TITLE
Cross-compiling x86 on Linux fails with mixed architecture linking

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1677]
I'd like to compile 32-bit Electron on amd64 Ubuntu. To that end, I try to bootstrap with `--target_arch`:

```sh
script/bootstrap.py --target_arch ia32
script/build.py -c Release
```

However, some of the binaries I pull down (or build) end up being 64-bit, so we fail at the link step. Any clues?

**Comment by zcbenz** [comment]
Cross-compiling on Linux requires installing packages for 32bit target, Electron doesn't download external binaries for building on Linux so it is very likely that you lack some necessary 32bit libraries on your system.

I suggest using chroot for building 32bit target on 64bit machine, it is much more easier to get things right, Chromium has a nice script to install chroot environment:
https://code.google.com/p/chromium/codesearch#chromium/src/build/install-chroot.sh&sq=package:chromium&type=cs&l=7

**Comment by paulcbetts** [comment]
@zcbenz :cool:, thanks for the tip
