### ISSUE TITLE
Setting max/min height and resizable false causes a small resize adjustment [OSX]

### ISSUE THREAD

**Issue by Somiac** [atom/electron#1678]
If I have these traits:
```
  mainWindow = new BrowserWindow({
    transparent: false,
    frame: true,
    resizeable: false,
    fullscreen: false,
    "max-height": 600,
    "max-width": 800,
    "min-height": 600,
    "min-width": 800
  });
```

Pressing the green icon (maximize) on OS X causes it to resize slightly, I am assuming this is compensating for the title-bar on the top.

Expected result: no resizing; the window should already be the max height/width.

**Comment by zcbenz** [comment]
It has been fixed since v0.30.3.
