### ISSUE TITLE
WebView tag can't load HTTPS on Fedora 21

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1680]
To repro:

1. Install Fedora 21
1. Open up Electron and create a WebView tag that goes to Google / GitHub / wherever

You'll see this in the console:

```
[6047:0513/153641:ERROR:cert_verify_proc_openssl.cc(231)] X509 Verification error unable to get local issuer certificate : 20 : 1 : 4
```

and the page won't load

**Comment by magicae** [comment]
Also on ArchLinux

**Comment by paulcbetts** [comment]
Doesn't seem to repro on Debian 8 or any recent versions of Ubuntu

**Comment by zcbenz** [comment]
It is probably related to the locations of system-installed certificates.

**Comment by paulcbetts** [comment]
@zcbenz Agree - I tried to strace it to track down the files it wasn't finding, but didn't have much luck (though I didn't put _too_ much time into it)

**Comment by kidwm** [comment]
Is there any workaround for this issue?
