### ISSUE TITLE
The file input element doesn't return selected file path correctly on Windows.

### ISSUE THREAD

**Issue by hokein** [atom/electron#1683]
The `<input type=''file">` element always return `C:\fakepath\<selected_file_name>` as a path value in callback.
Test v0.26.0 on Windows. But the `dialog` API will return correct path.

a minimal sample can be found in: https://gist.github.com/hokein/1dd14b4f464968eca607

**Comment by zcbenz** [comment]
Closing for the reason in https://github.com/atom/libchromiumcontent/pull/117#issuecomment-104877516.
