### ISSUE TITLE
electron crashes on window close

### ISSUE THREAD

**Issue by Arcath** [atom/electron#1685]
I have an app that on start up appears as an icon in the system tray, it then has a window you can open from the context menu. The window opens no problem but when you close it electron crashes out.

The error I get in console is:

```
[60172:0514/091856:WARNING:raw_channel_win.cc(473)] WriteFile: The pipe is being closed. (0xE8)
[60172:0514/091856:WARNING:channel.cc(547)] Failed to send message to ack remove remote endpoint (local ID 2147483648, remote ID 2)
[60172:0514/091856:WARNING:channel.cc(314)] RawChannel write error
```

And my window opening/handling code is:

```coffee
  detailsWindow = new BrowserWindow {width: 400, height: 600, center: true, icon: icoPath}

  detailsPath = path.join __dirname, '..', 'assets', 'html', 'details.html'

  detailsWindow.loadUrl detailsPath

  detailsWindow.on 'closed', ->
    detailsWindow = null
```

**Comment by deepak1556** [comment]
Can you provide the sample code creating the browser-window from context menu ? I dont see anything wrong with this window handling code to cause the crash.

**Comment by bengotow** [comment]
Hey Arcath,

This may or may not be related, but I've noticed that Electron crashes in some specific scenarios when you try to close a window from a window event handler in the parent process. (So for example if you were to listen for `blur` and then call `window.close` in the handler.) I believe there's a ticket about it somewhere, but it's easy to fix by waiting one tick before you close the window. Maybe try that and see if it works?

**Comment by Arcath** [comment]
The `detailsWindow` code is called by the listener, `eem.emitter.on 'tray:view-details', ->` which is triggered by this menu item `trayMenu.append new MenuItem({label: 'View Details', click: -> eem.emitter.emit 'tray:view-details' })`

@bengotow I'm just hitting the X in the corner to close the window, not doing anything with my code.

**Comment by Arcath** [comment]
Did some more looking into it and when I close the window the `will-quit` event is being emitted for `app`

adding:
```coffee
app.on 'will-quit', (event) ->
  event.preventDefault()
```
solves the problem.

Is it on windows where electron assumes that after all windows are closed it should quit?

**Comment by zcbenz** [comment]
If you run your app with electron-prebuilt the default behavior is to quit when all windows have been closed, you can set up a [window-all-closed](https://github.com/atom/electron/blob/master/docs/api/app.md#event-window-all-closed) handler to prevent this behavior.
