### ISSUE TITLE
showMessageBox options are surprising

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#1693]
When calling showMessageBox:

On Mac:

1. Options.title has no effect on Mac, the title of the message box is always empty.

2. Options.message uses a bold font on Mac, and acts more like the title on Mac (unless the title issue above will be fixed).

3. Options.detail is the best way to set the actual message on Mac (otherwise using Options.message leads to an all-bold message).

On Windows:

1. Options.title works as the title on Windows.

2. Options.message works as the message on Windows.

**Comment by zcbenz** [comment]
The message box on Mac doesn't have title, and the `message` is expected to show int bold.

**Comment by jorangreef** [comment]
Would it not be better then if the "title" option mapped to "message" on Mac, and if the "message" option mapped to "detail" on Mac (with the "detail" option on Mac then doing nothing)?

By the way, I noticed that message boxes from native Mac apps do show a title in the window bar, but Electron does not?

Thanks for the great work.

**Comment by jorangreef** [comment]
For example at the moment I have code which has to do:
```
if (Environment.mac) {
  var options = { message: title, detail: message, buttons: buttons };
} else {
  var options = { title: title, message: message, buttons: buttons };
}
Electron.dialog.showMessageBox(options);
```
