### ISSUE TITLE
Update defaults: Stop adding the context menus!

### ISSUE THREAD

**Issue by prasannavl** [atom/electron#1697]
Its incredibly annoying if I remove the all Shell context menus manually, and then on each minor update, it keeps re-creating them. I had to write a scavenging script to overcome this. 

And if the propagation of Electron app is expected, then its make no sense to clutter with a ton of context menus, for each of them. And now even worse, its incredibly annoying to keep recreating, even if one removes it manually. 

Please make the shell context menu creation optional on updates, as default with an option to over-ride. With default options to auto-create, its leading up to a disastrous end-user experience with cluttered menus. Let the developers do a little extra work, and opt-in, if it is absolutely required. Do not auto-create them, by default.

PS: Is this more appropriate to be filed under Squirrel? But since this is the packaged app framework, I thought it'd be appropriate to file it here, regardless of Squirrel.

**Comment by paulcbetts** [comment]
Are you possibly talking about https://github.com/atom/atom/issues/5901?

**Comment by prasannavl** [comment]
Yes. I believe it is the issue. Thanks for noting that. I'll close this.
