### ISSUE TITLE
Support for Menu Item Access Keys in Windows

### ISSUE THREAD

**Issue by waynebloss** [atom/electron#1698]
In Windows there is a standard basic feature of menu items called Access Keys whereby the underlined letter of a menu item label indicates to the user which key can be pressed in combination with`Alt` to activate that item.

Will Electron support this?

![Image of Access Keys](https://i-msdn.sec.s-msft.com/dynimg/IC725653.png)

_In the image above, the letter `O` is the access key for the Open menu item._

This is pretty easy to implement if you are using native Win32 menus because an ampersand in the label string [1] is used to indicate which letter should be underlined (So a label string of `&File` would result in the F in File being underlined. In other systems that map to or emulate Win32 menus, an underscore is commonly used. (So `_File` instead of `&File`...))

[1] - [MSDN - Menu Access Keys](https://msdn.microsoft.com/en-us/library/windows/desktop/ms647553(v=vs.85).aspx#_win32_Menu_Access_Keys)
[2] - [MSDN - Keyboard Access to Menus](https://msdn.microsoft.com/en-us/library/windows/desktop/ms647553(v=vs.85).aspx#keyboard_access)

**Comment by paulcbetts** [comment]
Menu hints are already supported in Electron, use & in the label

**Comment by miloszfalinski** [comment]
@paulcbetts I know this is old, but.. if you want to show an '&' in the label then - how do you do that? eg. like the native 'Edit' > 'Emoji & Symbols' menu item
