### ISSUE TITLE
Menu Item Access Keys not underlined, system preference ignored

### ISSUE THREAD

**Issue by waynebloss** [atom/electron#1699]
Electron does not underline menu item access keys until the `Alt` key is pressed. As you can see in the image below, the program in the background (Visual Studio) has underlined menu items, but the Electron program in the foreground does not.

![Image of Electron without underlined menu item labels](http://i.imgur.com/QU9zmGR.png)

The Windows setting that changes this behavior is located in the Control Panel, Ease of Access, Make the keyboard easier to use, "Underline keyboard shortcuts and access keys".

If you are not using native Win32 menus which would already be following this setting, then you can programmatically get the value of this setting by checking that the following registry value is set to "1".

Registry Key: `HKEY_CURRENT_USER\Control Panel\Accessibility\Keyboard Preference`
Registry Value: `On` (type: `REG_SZ`)

[(via stackoverflow.com and windowsvalley.com)](http://stackoverflow.com/questions/1328078/how-do-i-programatically-change-the-underline-keyboard-shortcuts-control-panel/7684801#7684801)

**Comment by zcbenz** [comment]
I'm merging this to #2504.
