### ISSUE TITLE
Cannot navigate menus with left and right arrow keys in Windows

### ISSUE THREAD

**Issue by waynebloss** [atom/electron#1700]
Electron is missing a basic standard feature of the menu system in Windows whereby the user can activate any menu and then use the left and right arrow keys to navigate the entire menu bar.

Here is a [short video on youtube](https://youtu.be/ANnOtQxrUOc?t=56s) which illustrates this behavior at ~0:56.

**Comment by zcbenz** [comment]
I'm merging this to #2504.
