### ISSUE TITLE
"display-metrics-changed" event does not trigger when changing resolution 

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1704]
I just tried something simple like this:

```javascript
var screen = require('screen');
screen.on('display-metrics-changed', function(ev, display){
  console.log(display);
});
```

And then changed the scaling on my retina screen (aka resolution):

![image](https://cloud.githubusercontent.com/assets/380914/7661196/652e5d64-fb05-11e4-98d9-ffd36203aac1.png)

The event is not triggered as expected

**Comment by paulcbetts** [comment]
I don't know that changing the scaling factor counts as a metrics change at the moment, but it definitely should. Does plugging in a monitor fire it?

**Comment by deepak1556** [comment]
> I don't know that changing the scaling factor counts as a metrics change at the moment, but it definitely should

Yup , these are the [metrics](https://code.google.com/p/chromium/codesearch#chromium/src/ui/gfx/display_observer.h&q=ondisplaymetrics&sq=package:chromium&l=20) being tracked.
