### ISSUE TITLE
Error: EACCES at npm install with sudo

### ISSUE THREAD

**Issue by rcotrina94** [atom/electron#1709]
I run this command `sudo npm install -g electron-prebuilt`, then I get this error (not sure if it's electron fault):
```
$ npm install -g electron-prebuilt
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.26.0 install /usr/lib/node_modules/electron-prebuilt
> node install.js


/usr/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, mkdir '/home/rc/.electron'

npm ERR! electron-prebuilt@0.26.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.26.0 install script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-37-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "electron-prebuilt"
npm ERR! cwd /home/rc
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

To void this error, I just manually created `/home/rc/.electron` folder. Then it installs normally.

**Comment by maxogden** [comment]
@rcotrina94 in the output you pasted it shows you didn't use sudo, it has `$ npm install -g electron-prebuilt`. Are you sure you typed sudo when you ran it? The `EACCES` error means it didn't have permission to create a new folder in the `/home/rc/` directory

**Comment by leafo** [comment]
Getting the same problem. Creating the `/root/.electron` directory did not help.

```
> sudo npm install electron-prebuilt -g
/usr/bin/electron -> /usr/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.26.0 install /usr/lib/node_modules/electron-prebuilt
> node install.js

/usr/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, mkdir '/root/.electron'
    at Error (native)
npm ERR! Linux 4.0.1-1-ARCH
npm ERR! argv "node" "/usr/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE
```

Running Arch linux

```
> npm -v
2.10.0
> node -v
v0.12.3
```

**Comment by kaidesu** [comment]
This isn't an issue with electron, but with your installation of node/npm and the permissions on your machine. I'd probably purge node and npm and re-install them.

**Comment by leafo** [comment]
Uninstalling and re-installing nodejs and npm from my system fixed the issue for me. Thanks

**Comment by kazuki-k** [comment]
In my case, npm install run successfully after creating .electron directory and granting write permission to it.
```
# at your home directory
> mkdir .electron
> chmod 777 .electron
> sudo npm install -g electron-prebuilt
> chmod 755 .electron
```
OSX 10.10.3
node v0.12.3
npm 2.9.1

**Comment by zcbenz** [comment]
This issue is now tracked at https://github.com/mafintosh/electron-prebuilt/issues/27.

**Comment by mauris** [comment]
Had the issue. Reinstall node/npm does not work. Only `chmod 777` for `~/.electron` solved it. 
Not sure why `.electron` suddenly have no write perms

**Comment by Nejat** [comment]
reinstalling node/npm did not work for me, so i tried the following and it with worked perfectly

`sudo npm uninstall electron-prebuilt -g`
`rm -rf ~/.electron`
`sudo npm install electron-prebuilt -g`

**Comment by moda20** [comment]
Can't install electron, tried everything. creating `electron` directory doesn't work as running the `npm install electron -g` again with `sudo` deletes the directory. this is annoying.
