### ISSUE TITLE
uft-8 not supported

### ISSUE THREAD

**Issue by uyghur2014** [atom/electron#1711]
i already started working electron shell ,but my index html file encoded uft-8 with meta tag,after i build app's utf-8 chracter suddenly converted to not human readable mode.how i can solve this problem?

**Comment by sbruchmann** [comment]
Hello @uyghur2014,

There two things that come to mind:

  * It is spelled U**T**F-8, not UFT-8
  * Check the charset settings in your editor; maybe they are wrong

**Comment by uyghur2014** [comment]
hello@sbruchmann
sorry ,i'm spelled as uft-8 here,but my index html file correct utf-8,i'm lot trying also saved as encode with utf-8,but same resulting happened,there are any idea ?please help me ,i'm using right-to-left language like arabic and uyghur,so i need to solve this problem for my project.thanks

**Comment by paulcbetts** [comment]
@uyghur2014 One thing that will trip up Electron is having a UTF-8 BOM in your source files. Make sure your files are BOM-free (let me know if you're not sure how to check that and I can help out)

**Comment by uyghur2014** [comment]
@paulcbetts 
ok,so how i can BOM-free my source file,help me?

**Comment by paulcbetts** [comment]
http://stackoverflow.com/questions/295472/how-do-i-remove-the-bom-character-from-my-xml-file looks promising

**Comment by uyghur2014** [comment]
@paulcbetts 
no solved,just atom shell browser window did not correct rendered,but chrome or firefox will nice rendered.have you any idea?

**Comment by zcbenz** [comment]
You might want to try the solutions in #1093.

**Comment by hamidabdulmalik** [comment]
UTF-8 still not supported guys, any other ideas?

**Comment by eyalzek** [comment]
I'm having the same problems with Hebrew. I tried all the solutions I could find. Running a simple .js file with node that just logs Hebrew works fine, with Electron it just doesn't work.

**Comment by eyalzek** [comment]
Why is this issue closed btw?

**Comment by hamidabdulmalik** [comment]
You need to upgrade electron to the latest version. I was having problems with Arabic text, but now I am good

**Comment by eyalzek** [comment]
Just tried with v0.37.2, still having the same problem. logging on the client side works fine, logging on the server side produces squares. Attached image of the output on the client compared to server.
![test](https://cloud.githubusercontent.com/assets/6243438/13916759/c8a1a86e-ef5c-11e5-9099-448bf603239e.jpg)

**Comment by rgiosa** [comment]
Try add `<meta charset="utf-8">` in <head> section of index.html file.

**Comment by xiexiaopeng2016** [comment]
![S@KC$ QW6I87PQPP`XH%AH](https://github.com/user-attachments/assets/ce15898f-f7d0-4d1f-8f51-19c45a254396)

The content of the page and the original interface of the browser cannot display UTF-8 characters, how to solve this problem?
