### ISSUE TITLE
Tray not firing clicked event when tray icon is clicked

### ISSUE THREAD

**Issue by twolfson** [atom/electron#1715]
I am attempting to set up a tray click binding but it seems to not be functioning properly. I have created a gist to reproduce the issue in a minimal case:

https://gist.github.com/twolfson/528dbbd3e1bee6e6a3a1

Steps taken:

1. Run `electron main.js`
2. Click tray icon

Expected behavior: "Hello World!" and "Tray clicked" should be logged

Actual behavior: "Hello World!" is logged but "Tray clicked" is not

Configuration: I am running `electron-prebuilt@0.26.0` on Linux Mint 17.1 64-bit with a Cinnamon desktop environment

**Comment by maxogden** [comment]
have you seen the platform limitations section of https://github.com/atom/electron/blob/master/docs/api/tray.md ?

**Comment by twolfson** [comment]
I missed those and the "App Indicators" notes might apply to me but I am having trouble finding out if I am using them or not. Most of my search results are talking about packages/implementing `libappindicator` on a package, not about using App Indicator itself. How would I find out if I am?

For what it's worth, I have had success with `nw.js'` click events on tray icons on the same setup.

**Comment by twolfson** [comment]
Woo hoo! Thanks for the fix. I can't wait for the next release to try it out =)

**Comment by twolfson** [comment]
Tried it out today. It works great! Thanks =D
