### ISSUE TITLE
<webview>tag how to change content

### ISSUE THREAD

**Issue by a348730140** [atom/electron#1716]
```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>T</title>
    <style type="text/css">
      body{background-color: #242424}
    </style>
    <script type="text/javascript">
      onload = function () {
        alert('x');//show
        console.log('x');//not show
        alert(__dirname);//not show
      }

      function BtnClick () {
        document.getElementById('p').innerHTML = "x"  //change
        document.getElementById('p').innerHTML = __dirname //not change
      }
    </script>
  </head>
  <body>
    <div id="content">
      <button onclick="BtnClick()">Btn</button>
      <p id="p"></p>
    </div>
  </body>
</html>
```

**Comment by myfrndjk** [comment]
hi can you able to change the html content

**Comment by RobinCodeX** [comment]
@myfrndjk You can use jquery to change html content.

**Comment by MarshallOfSound** [comment]
@myfrndjk @RobinCodeX Please don't recommend jQuery to do something as simple as changing HTML content.  Especially when in this case it wouldn't work.

A webview is a completely separate process, to change it's content you have to use it's method `loadURL` or change the `src` attribute to point it to a new URL.  You can also use IPC to communicate with the inner webpage.  You can't adjust the content of a webview like other HTML elements

**Comment by myfrndjk** [comment]
@RobinCodeX  @MarshallOfSound  Thanks for you suggestion
I used jquery to modify html content based on this 
[https://github.com/electron/electron/issues/2048]( https://github.com/electron/electron/issues/2048 ) and it is working fine. If Jquery this is not the right way of  modifying content then i try to use IPC
