### ISSUE TITLE
CMD+OPT+I to open DevTools isn't enabled by default anymore

### ISSUE THREAD

**Issue by maxogden** [atom/electron#1718]
In older releases of Electron/Atom Shell in any app you could do `CMD+OPT+I` to open DevTools. Now this is disabled. I'm not sure when this got disabled (I looked in PRs, Issues, Commits, Changelog but couldnt find any reference). 

It's enabled in the default app: https://github.com/atom/electron/blob/f5fbd52dbdd0a27e7a19725be86b94cc35119739/atom/browser/default_app/default_app.js#L121

I think devtools is super useful and hope we can add the keybindings back by default :)

**Comment by sindresorhus** [comment]
:+1:

**Comment by paulcbetts** [comment]
I don't think this has to do specifically with DevTools, I think there's a more general glitch in the menu system where accelerators are being eaten somehow (or alternatively, where `openDevTools` is not working) - we've seen this in the Slack app too with our own custom menus

**Comment by zcbenz** [comment]
It was removed in #1491, this is to make OS X have the same behavior with Linux and Windows, there is no default menus in the last two platforms.

For nearly all apps they will have their own menus, so I want to make the default menu on OS X as simple as possible.

**Comment by sindresorhus** [comment]
We're not asking about the menu, but rather the keybinding. Being able to do Cmd+Opt+I by default to get devtools without any setup is very useful.

**Comment by yoshuawuyts** [comment]
Additionally, copy + pasting also seems to have been disabled by default. Having devtools work out of the box again would be grand.

**Comment by steelbrain** [comment]
I achieve the goal by listening to the keydown event and opening dev tools on the desired key downs. Using `remote.getCurrentWindow().toggleDevTools()`

**Comment by paulcbetts** [comment]
> We're not asking about the menu, but rather the keybinding. Being able to do Cmd+Opt+I by default to get devtools without any setup is very useful.

In the default app, the menus _are_ the keybinding, that's the only way those shortcuts get invoked. What we probably need here is a "MenuItem.createDefaultMenus()" that would return a pre-canned menu that sets a lot of these up. Right now it's too hard to get back to the default behavior, you have to figure out weirdo Selector Magic and stuff on OS X and on other platforms you have to go digging around in webContents.

**Comment by sindresorhus** [comment]
I don't want the Dev Tools menu item, just the key binding. The key binding is helpful to be able to easily debug even production apps.

**Comment by maxogden** [comment]
maybe we just need a 'electron-debug' module that has the api: `require('electron-debug')()` which would bind CMD+CTRL+I to open devtools in a cross platform way

**Comment by sindresorhus** [comment]
@maxogden Good idea! Done => https://github.com/sindresorhus/electron-debug

*Suggestions for more debug features welcome, on the `electron-debug` issue tracker.*

**Comment by Dashed** [comment]
Man I've missed this feature. Thanks @sindresorhus! :+1:

**Comment by gliheng** [comment]
Walked into this problem today. global-shortcut has a minor flaw that it will block application shortcuts, eg. chrome devtools won't respond CMD+OPT+I. Maybe a better solution is `NODE_ENV=development electron .` and open devtools if env is set.
