### ISSUE TITLE
Fullscreen not working anymore on linux x64 with v0.26?

### ISSUE THREAD

**Issue by mgcrea** [atom/electron#1721]
The following BrowserWindow config does not appear in fullscreen anymore in ubuntu 14.04:

```
{ show: true,
  resizable: false,
  frame: false,
  'enable-larger-than-screen': true,
  'node-integration': false,
  'web-preferences': { plugins: true },
  'always-on-top': true,
  kiosk: true,
  fullscreen: true }
```

Tested with `v0.26`, used to work with `v0.23`

**Comment by maxkueng** [comment]
Can confirm on Manjaro Linux. 

 - v0.26.0: BROKEN
 - v0.25.3: BROKEN
 - v0.25.2: BROKEN
 - v0.25.1: WORKS

Window options: 

```
{
  title: 'Test',
  kiosk: true,
  fullscreen: true,
  'always-on-top': true,
  show: true,
  width: 960,
  height: 540,
  'min-width': null,
  'min-height': null,
  'zoom-factor': 1,
  'web-preferences': 
   { java: false,
     webgl: true,
     plugins: true,
     webaudio: true,
     'web-security': false } }
```

**Comment by mgcrea** [comment]
So the broken commit must be one of [theses](https://github.com/atom/electron/compare/v0.25.1...v0.25.2). Maybe 20b4cae980cf45c336e235128aaac2032bf7953e?

**Comment by marwanhilmi** [comment]
Noticed similar broken behavior with full screen on Windows after 0.25.2. The ```fullscreen: true``` option to the window does not work at all.

https://github.com/atom/electron/issues/1627

**Comment by MikeGCV** [comment]
no fullscreen on linux x64

**Comment by deepak1556** [comment]
Sorry about this, have fixed it here https://github.com/atom/electron/pull/1616 . Just tested on archlinux with your configs and it works, if possible can you guys test it out too ? Thanks! Also @mgcrea you need to drop `resizable: false` in your configuration.

**Comment by zcbenz** [comment]
I'm merging this to #1598.
