### ISSUE TITLE
Select currently used iojs version in readme

### ISSUE THREAD

**Issue by 3y3** [atom/electron#1722]
This is useful for debugging. For example then users install `node-inspector` to debug electron, they need to know which target node version to select `npm install -g node-inspector --target 1.6.3`

**Comment by deepak1556** [comment]
Hmm then we would have to do a readme update everytime we upgrade `node` , not an issue but they can read the version from `process` object ?

**Comment by 3y3** [comment]
This is useful for developers like me. I don't use electron, but I should provide some prebuilt binaries to be compatible with electron (`v8-debug`, `v8-profiler`). So, each time, when users report that node-inspector doesn't work with electron, I need to dig into electron sources to check which version of io.js there was used.

Also I opened one other issue in io.js related with C++ addons support. https://github.com/nodejs/io.js/issues/1738

**Comment by zcbenz** [comment]
You can get the version of io.js used by Electron in https://atom.io/download/atom-shell/index.json.
