### ISSUE TITLE
Timing of app.ready event

### ISSUE THREAD

**Issue by sridharv** [atom/electron#1726]
If the `app.on('ready', function(){...})` is called from inside a callback, the ready event is never received. ~~I'm not sure if this is a bug / the expected behaviour / I've gotten something confused~~. However, here's some simplified code to reproduce the issue:

EDIT: The behaviour described below happens due to the app.ready event being sent once the main script has been executed. It might be useful to have some documentation to that effect. I'd be happy to send a pull request if required. If not, please feel free to close/ignore this issue. I will wait for a week and then close it myself. 

`package.json`

```json
{
  "name": "electron-indirect-startup",
  "description": "Reproduce the indirect startup issue in electron",
  "main": "main.js",
  "dependencies": {
    "electron-prebuilt": "^0.26.0"
  }
}
```

`main.js`

```javascript
var app = require('app');
var fs = require('fs');


function configureTimeout() {
	var timeout = 5 * 1000;
	console.log('Configuring timeout of ' + timeout + "ms");
	return setTimeout(function () {
		console.log('app.ready signal not sent after ' + timeout + 'ms');
		app.quit();
	}, timeout);
}

function electronApp() {
	console.log('Callback called');
	var timeout = configureTimeout();
	console.log('Setting up app.ready event handler');
	
	app.on('ready', function() {
		console.log('Electron application ready');
		clearTimeout(timer);
		app.quit();
	});
}

fs.readFile(process.argv[1], electronApp);
```

#### Versions

  * OS X 10.9.5
  * io.js v1.8.1
  * electron v0.26

#### Steps to reproduce

1. Create `package.json` and `main.js` as described above in a directory
2. Run `npm install` in the directory
3. Run `./node_modules/.bin/electron .` inside the directory

#### Output received

```
Callback called
Configuring timeout of 5000ms
Setting up app.ready event handler
app.ready signal not sent after 5000ms
```

#### Expected output

```
Callback called
Configuring timeout of 5000ms
Setting up app.ready event handler
Electron application ready
```

#### Context

I'm working on a bridge between Go and Electron to allow me to build cross-platform UI application in Go. In the process of doing so I ran into this issue. I'm currently working around this by starting the bridge after the app.ready event has been received, but I thought I'd ask here first.

**Comment by sridharv** [comment]
I forgot to add that this is likely due to the ready event being dispatched before the listener is added, but I'm not certain this is the case. Is there any way to control the timing of when that event is emitted or is a race always possible?

**Comment by sridharv** [comment]
I was able to confirm my suspicion with a custom electron build. The callback is being called after the event has been fired. Would it be useful to document this so it's easy for folks to understand the lifecycle better? Maybe something to the effect that electron will first process the main script and only then emit the ready event? I'll also edit this issue description and title to reflect this.

**Comment by zcbenz** [comment]
There is no guarantee when the `ready` event is called, unless you are doing some Chromium related things you should run all your code after the `ready` event.

In your code the `ready` event has been emitted before the callback of `fs.readFile` runs.

**Comment by cdaringe** [comment]
thanks @zcbenz :)

**Comment by Petah** [comment]
Is there any way to check if ready has already been fired?

**Comment by kevinsawicki** [comment]
> Is there any way to check if ready has already been fired?

You can call `app.isReady()`
