### ISSUE TITLE
Use EGL only

### ISSUE THREAD

**Issue by piranna** [atom/electron#1727]
How can I be able to compile electron from scratch to use EGL only, without needing X11 at all?

**Comment by zcbenz** [comment]
There is no way to do that, you can propose this to Chromium project.

**Comment by piranna** [comment]
I know Chromium is capable of doing it, it's just how ChromeOS works but it's difficult to configure and it's widely undocumented. I only though it could be easier with electron.

**Comment by zcbenz** [comment]
ChromeOS is an operating system so it can choose any graphic library that works, but Electron is a desktop application on Linux, and X11 is required for GUI on desktop Linux.

**Comment by piranna** [comment]
You are right, but internally it's just Chrome running on Linux using EGL. X11 is not required to have a GUI on desktop Linux, you can use Wayland, fbdev, EGL... and also X11 is too much bloated.

**Comment by akihikodaki** [comment]
QtWebEngine, using Chromium, is actually capable to do that.
