### ISSUE TITLE
Documentation implies Squirrel checks for updates regularly, but it doesn't

### ISSUE THREAD

**Issue by bengotow** [atom/electron#1735]
The [Electron documentation](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md) mentions that "Squirrel will check for an update again at the interval you specify." This doesn't seem to be true—the auto-updater seems to check for updates at launch, and again if manually invoked, but the Electron source code never calls Squirrel's [`startAutomaticChecksWithInterval`](https://github.com/Squirrel/Squirrel.Mac/blob/b1f4ecf615ad3b9f4b92929eb7ed6427993ecd09/Squirrel/SQRLUpdater.m#L280) to enable periodic checking.

I think it'd make sense to expose an API on the `auto-updater` module that calls through to `startAutomaticChecksWithInterval`, or update the docs. I'd be happy to submit a pull request if this is already on the wish list!

**Comment by zcbenz** [comment]
The misunderstanding description is already gone.
