### ISSUE TITLE
Dialog.showMessageBox() does not return the correct button index when using keyboard

### ISSUE THREAD

**Issue by nizachon** [atom/electron#1739]
I have noticed that when running the following code on **Windows**:

```javascript
.....................
var buttons = ['OK', 'Cancel'];

dialog.showMessageBox({ type: 'info', buttons: buttons, message: 'Exit?' }, function (buttonIndex) {
	updateFooter("Exit: " + buttons[buttonIndex]);
});
```

and using arrow keys to navigate between the OK and Cancel buttons, and then using Enter key to close the dialog, I am always getting back 0 regardless of which button was actually selected.

When I click on the button with a mouse, the code works as expected.

Has anyone else observed the same behavior?

**Comment by zcbenz** [comment]
I'm merging this to #2090.
