### ISSUE TITLE
does fav-icon-updated event get triggered...I am not able to get it working.

### ISSUE THREAD

**Issue by skandasoft** [atom/electron#1743]
I am working on this package browser-plus(http://atom.io/packages/browser-plus) for atom using webview. I wanted to see if I can set the fav-icon using the fav-icon-updated event of the webview.. when I register for it/put debugger doesn't seem to stop there..

**Comment by deepak1556** [comment]
hmm there is no event as `fav-icon-updated` , there is only [page-favicon-updated](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#page-favicon-updated) . Is it a typo ?

**Comment by skandasoft** [comment]
yes it is a typo
