### ISSUE TITLE
'open-file' and 'open-url' on Windows

### ISSUE THREAD

**Issue by Trixt0r** [atom/electron#1746]
Quick question:

How do I have to invoke an electron app on Windows if I want that the 'open-file' and the 'open-url' events get triggered? I already set up the Windows registry correctly for associating files and url protocols with my app. Just appending the file to the arguments does not seem to work. My app gets invoked like this:

```
"C:\Path\To\Electron" "C:\Path\To\My\App" "%1"
```

where %1 is the path to the file/url.

-Trixt0r

**Comment by zcbenz** [comment]
These events are only available on OS X, on Windows you have to parse `process.argv` to get the file.

**Comment by ricardomatias** [comment]
Is it possible on Windows to open a file in a already opened electron app with file association ?

**Comment by mahnunchik** [comment]
Maybe there is sense to emulate `open-file` and `open-url` on platforms other then macOS?

**Comment by ANF-Studios** [comment]
@zcbenz, can you show an example for that? I didn't quite understand.
