### ISSUE TITLE
Open external file with Electron

### ISSUE THREAD

**Issue by cadizjavier** [atom/electron#1749]
I have a running Electron app and is working great so far. For context, I need to run/open a external file which is a Go-lang binary that will do some background tasks. Basically it will act as a backend and exposing an API that the Electron app will consume.

So far this is what i get into:

- I tried to open the file with the "node way" using `child_process` but i have fail opening the a sample txt file probably due to path issues.

- The Electron API expose a open-file event but it lacks of documentation/example and i don't know if it could be useful.

That's it. How i open an external file in Electron ?

*This question is asked in [Stackoverflow](http://stackoverflow.com/q/30381450/1373105) too.*

**Comment by zcbenz** [comment]
There [shell module](https://github.com/atom/electron/blob/master/docs/api/shell.md).

**Comment by pdoh00** [comment]
I have commented on SO. It's not exactly what you are asking for, but I have done this by exposing the golang binary as a web service then using ajax from Electron to call it.  I think it is a clean separation and worked well for me.

**Comment by cadizjavier** [comment]
@pdoh00 Yes, that's exactly what i'm trying to accomplish. As you mention is a really nice approach.
The main problem is that i want to open that Go-lang backend automatically after opening the Electron app, so it will work more brainless for the end user. 
I don't know exactly how to integrate the shell module mentioned before.
Any idea how to approach this ?

**Comment by astaxie** [comment]
@zcbenz shell module can't solve these problem. shell module only can run the file, like `shell.openItem('simple');` but it just open a terminal as the Electron app started, but we just want to run the service in the backend as a service. So could the shell module provide a new API like `shell.openItemBackground('simple')`
