### ISSUE TITLE
ipc tutorial is not working.

### ISSUE THREAD

**Issue by asdfghjkl42** [atom/electron#1750]
hi, this ipc tutorial just give me "pong" print on console logs. ( https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md#ipc-main-process ).

why is not sending message from index.html to main.js, what's the problem? thanks for responses.

**Comment by ThorstenHans** [comment]
hey,

which electron version are you running on and which OS are you using? It would also be great if you can provide any further details like code :smile_cat:

**Comment by asdfghjkl42** [comment]
ah sorry. windows 8.1, electron: 0.25.3

quick start project: package.json, main.js, index.html

**Comment by adamhoracek** [comment]
I also have a problem with that... Electron 0.26.1. 
Even though I have var ipc = require('ipc'); and run npm install ipc... it still gives me "ipc.on is not a function" err...

![screen shot 2015-05-22 at 11 56 19 pm](https://cloud.githubusercontent.com/assets/734739/7780371/4ca8e230-00de-11e5-8e5e-d23739c5499a.png)

**Comment by ekonstantinidis** [comment]
In my case - from within a react component (so similar to `index.html`) I had to require ipc like that:

    // index.html
    var ipc = window.require('ipc');
    ipc.sendChannel('update-icon', "IconGreen");

    // main.js
    ipc.on('update-icon', function(event, arg) {
        console.log(arg);
    });

**Comment by zcbenz** [comment]
Please make sure you didn't install `ipc` module with `npm`, `ipc` is a built-in module in Electron.

**Comment by asdfghjkl42** [comment]
my problem is still not solved. im using electron.exe. drag n drop renderer type. even so, thanks to everyone.

**Comment by gabriel** [comment]
I am having the same problem in 0.30.1

**Comment by gabriel** [comment]
if you are using browserify, it rewrites your require... you might have to do window.require or `var _require = require` before loading browserify-ied script and using that.

**Comment by ekonstantinidis** [comment]
I agree with @gabriel . First of make sure you removed ipc from npm (`npm uninstall ipc`) and then require it with `window.require(...)`. Example https://github.com/ekonstantinidis/gitify/blob/master/src/js/components/notification.js#L2
