### ISSUE TITLE
How to integrate an existent webapp?

### ISSUE THREAD

**Issue by hadrienl** [atom/electron#1751]
Hi,

I'm trying to integrate an existing webapp built with angularjs and some bower components which are agnostic and test presence of `module` and `require`. So if I load my webapp in an iframe, it displays correctly, but I don't know how to access remote app object. And if I load directly my webapp from index.js, it crash caused to my components thinking they are in a node environment.

What is the good way to make all this work ?

**Comment by ThorstenHans** [comment]
true, your app crashes because electron makes several packages available in the renderer process. For example the `require` method is also available in the renderer process. If any of your logic looks for the `require` method and uses this as indicator if the app is running in node or not... this may cause the issue.

To answer your other question, check the docs at https://github.com/atom/electron/blob/master/docs/api/remote.md here it's fully documented how to get started with remoting in electron

**Comment by hadrienl** [comment]
Thanks

**Comment by kevin-smets** [comment]
If you don't need a tight integration, you can initialise the browser window like this:

    mainWindow = new BrowserWindow({
        width: 1280, 
        height: 768,
        'node-integration': false
    });

Does remoting make this possible (I'm not really sure what is meant by it)? I'm facing the exact same issue, trying to integrate an AngularJS app into Electron.

**Comment by hadrienl** [comment]
Thanks @kevin-smets, It's a good way to load my webapp without errors. But now, how can I get access to the app object to be able to interact with the desktop environment?

**Comment by hadrienl** [comment]
Oh! I think I've found the solution. I load my webapp directly :

`mainWindow.loadUrl('http://mywebapp.dev');`

then in the index.html of my webapp, I add the first script :

```
<script>
      if (window.require) {
        window.app = require('remote').require('app');
        console.log('COINCOIN', window.app);
        delete window.require;
        delete window.module;
      }
</script>
```

Then I can access the app object in my angular code.

**Comment by zcbenz** [comment]
You can set the `node-integration` option of `BrowserWindow` to `false` if you don't need the built-in `require`.

**Comment by hadrienl** [comment]
I need it to access native functionnalities. How will I be able to set Dock badge or display a notification?
