### ISSUE TITLE
Playing MP4 videos with Electron: Seeking

### ISSUE THREAD

**Issue by saschagehlich** [atom/electron#1757]
Hey,

we're currently building a VJ software with Electron which involves the playback of video files. It seems that Chrome automatically does partial requests when seeking larger files if the server supports it, which is quite nice. But there's one problem: Even though the video is entirely loaded, seeking causes a short lag due to another "network" request being made. So it looks like it loads the video again when seeking.

Now this is not fatal for most use cases. But in our use case (we want to skip to a random position in a specific interval) it is. Is there a way to either tell Chrome to not do these partial requests, or to make sure that `protocol` (I think that's the module responsible for serving local files?) does not serve partial requests?

Thanks!

**Comment by paulcbetts** [comment]
Are you seeking to arbitrary positions? My entirely uninformed psychic debugger is saying that this lag is because Chrome is trying to decode up to a point where it finds the next keyframe maybe?

**Comment by saschagehlich** [comment]
Yes, i'm seeking to arbitrary positions. But the lag does not appear with videos that are shorter, so that chrome does not split it up into multiple requests.

**Comment by zcbenz** [comment]
I suggest asking about it on chromium-dev google group, the video playing is handle completely on Chromium side and I'm afraid there is nothing we can do on Electron side.
