### ISSUE TITLE
Custom protocol won't load additional resources without trailing slash

### ISSUE THREAD

**Issue by maxkueng** [atom/electron#1759]
When using a custom protocol e.g. `app://` using `protocol.registerProtocol()` that resolves requests to a `RequestFileJob` it won't load additional resources such as CSS if the URL doesn't have a trailing slash.

For example `app://myapp` (notice no slash at the end) will load the HTML file but it won't load any CSS included with a `<link />` tag. On the other hand, `app://myapp/` (notice slash at the end) will successfully load all resources.

If I `console.log` the request in the protocol handler it won't even try to load the CSS without a trailing slash. It doesn't try to request it. So I'm assuming it has nothing to do with not finding the file.

**Comment by maxkueng** [comment]
I have created an example app in [maxkueng/electron-issue-1759](https://github.com/maxkueng/electron-issue-1759) to reproduce the issue.

It provides two "apps" (app1, app2) under `app://app1` and `app://app2` that will resolve to `./apps/app1` and `./apps/app2` respectively.  
Both apps have an `index.html` and a `styles.css` file. 

The custom protocol handler will print out every single request.

When loading `app://app1/` it will print out the path to both `index.html` and `styles.css`. But when loading `app://app1` (without trailing slash) it will only print the path to `index.html` and won't even try to load `styles.css`.

Comment and uncomment the different `openWindow()` calls [here](https://github.com/maxkueng/electron-issue-1759/blob/master/main.js#L56-L62) to try out different URLs.

**Comment by deepak1556** [comment]
isnt that how relative reference works https://tools.ietf.org/html/rfc3986#section-5 . If the example was written to 
```js
var path = require('path');
var url = require('url');
var app = require('app');
var BrowserWindow = require('browser-window');

// This is a simple regsistry to register apps.
var registry = {
  apps: {},
  register: function (name, dir) {
    console.log('Registered', name, 'with path', dir);
    this.apps[name] = dir;
  },
  getPath: function (name) {
    return this.apps[name];
  }
};

function setupProtocol () {
  var protocol = require('protocol');

  protocol.registerProtocol('app', function (request) {

    // Parse the URL
    var parsedUri = url.parse(request.url);

    // If the URL is, app://app1 the hostname will be 'app1'
    // which we'll use to look up the path.
    var appName = parsedUri.hostname;

    // Get the app directory from the registry.
    var appPath = registry.getPath(parsedUri.hostname);

    // The default path is '/index.html'.
    if (parsedUri.pathname === "/test")
      parsedUri.pathname = "/index.html"

    var filePath = path.join(appPath, parsedUri.pathname || '');
    console.log('Requesting', filePath);

    return new protocol.RequestFileJob(filePath);
  });
}

function openWindow (uri) {
  var win = new BrowserWindow({ width: 800, height: 600 });
  win.loadUrl(uri);

  win.openDevTools();
}

// Register some apps.
registry.register('app1', path.join(__dirname, 'apps/app1'));
registry.register('app2', path.join(__dirname, 'apps/app2'));

app.on('ready', function () {
  setupProtocol();

  openWindow('app://app1/test'); // Works
});
```

will work too. Besides `GURL::resolve` wont work correctly if there is no trailing slash for relative reference . Servers usually do a 301 redirect to fix this and `URLRequestFileJob` does [too](https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_request_file_job.cc&sq=package:chromium&rcl=1432683946&l=125) but i am not sure why the job stops after redirect. @zcbenz did you mark the `filejob` behaviour as bug? just curious.

**Comment by zcbenz** [comment]
You can now use `protocol.registerStandardSchemes` to register the custom standard as standard scheme to change this behavior.
