### ISSUE TITLE
Question: Is there a trick to enable rubber-band scrolling for <webview>?

### ISSUE THREAD

**Issue by steverandy** [atom/electron#1764]
Is there a trick to enable the rubber-band scroll for <webview> on Mac OS?

**Comment by zcbenz** [comment]
I don't know if there is such trick, but the webview in Electron behaves exactly the same with Chromium, so you can ask for advices in Chrome extension development related forums.

**Comment by paulcbetts** [comment]
@zcbenz There was originally a patch to disable this in libchromiumcontent though that is no longer there right? Or am I remembering poorly

**Comment by zcbenz** [comment]
@paulcbetts It was used to disable the native rubber-band, recent Chromium has changed to implement it in blink.
