### ISSUE TITLE
App Region Drag Not Working

### ISSUE THREAD

**Issue by Subash** [atom/electron#1765]
Drag region doesn't work where normal osx title bar is but works where title bar is not placed.
![developer_tools_and_prepros_and_atom_electron](https://cloud.githubusercontent.com/assets/3478693/7787896/727e0bbe-0243-11e5-8c0c-dabd0d35e796.png)

**Comment by Subash** [comment]
@zcbenz , this issue is blocking the relese of my app :'( 

You can see a title bar when setting transparent true 

![screenshot_5_24_15__7_27_pm](https://cloud.githubusercontent.com/assets/3478693/7788060/1c8ae80a-024b-11e5-8f6f-563373d76b4e.png)

**Comment by zcbenz** [comment]
Can you share the options of your `BrowserWindow`?

**Comment by Subash** [comment]
```js
width: 1000,
            height: 700,
            frame: process.platform === 'win32' && windows7,
            icon: __dirname + '/assets/icons/128x128.png',
            'min-width': 900,
            'min-height': 700,
            show: false,
            'web-preferences': {
                'direct-write': process.platform === 'win32',
                'experimental-features': true,
                'overlay-scrollbars': process.platform === 'win32'
            }
```

```'standard-window': false``` looks like solves the problem.

**Comment by zcbenz** [comment]
Sounds like #1661 which has already been fixed in latest release.
