### ISSUE TITLE
Still issues running Flash under Windows

### ISSUE THREAD

**Issue by Gregg8** [atom/electron#1767]
I have created a new issue as the previous #1674 issue is now closed.

Electron 0.26.1 has certainly improved the situation as it will now load a Flash player dll from any desired directory.

However, this is the `ppapi-flash-path` option which is supposed to load a "pepper flash plugin".

The problem I am experiencing is that it will only load an NPAPI plugin!?

The only one I can get it to load is called NPSWF64_17_0_0_169.dll (which as the name suggests, is the old style NPAPI plugin).

Whenever I attempt to load a PPAPI plugin, I get the following error:

[5480:0525/080243:ERROR:ppapi_thread.cc(278)] Failed to load Pepper module from /dev/...etc..../plugins/pepflashplayer32_17_0_0_188.dll (error: 193)

I have had a little look for ppapi_thread.cc but this is not in the Electron package so probably somewhere in the bowls of Chromium.

Doesn't make sense, I know, but this is what I am experiencing.

**Comment by paulcbetts** [comment]
It looks like you're trying to load 32-bit Pepper Flash in a 64-bit process, since NPSWF64 works for you. Reopen this if you've confirmed you're not mixing up the architectures

**Comment by Gregg8** [comment]
Thanks, that did point me in the right direction. 

There is certainly some weirdness with Flash installs under Windows (8.1 in my case). Here are my findings, in case it helps anyone:

 - Chrome pepper flash plugin is in: C:\Program Files (x86)\Google\Chrome\Application\XX.XX.XX.XX\PepperFlash\pepflashplayer.dll.
 - Chrome Canary plugins are in: C:\Users\XXX\AppData\Local\Google\Chrome SxS\Application\XX.XX.XX.XX\PepperFlash\pepflashplayer.dll.
 - These are both 32-bit. To get the 64-bit version of Chrome, you need to specify "another platform" from the Chrome install page.

When you manually install Flash:

 - 32-bit plugins are installed in C:\Windows\SysWOW64\Macromed\Flash (notice the helpful 64 in the folder name).
 - 64-bit plugins are installed in C:\Windows\System32\Macromed\Flash (notice the helpful 32 in the folder name).
 - Both Chrome and Canary will continue to use their own pepflash.dll versions and ignore these.

**Comment by paulcbetts** [comment]
> (notice the helpful 64 in the folder name)

WOW64 is the name of the subsystem that handles running 32-bit apps on a 64-bit OS - basically everyone writing Windows apps should read https://msdn.microsoft.com/en-us/library/windows/desktop/aa384249(v=vs.85).aspx and all the subsections, especially the redirector bits. Everything will make sense then :)

**Comment by Gregg8** [comment]
Thanks, very useful info.

**Comment by cniemann88** [comment]
Just wanted to add this:

If your plugin works in DEBUG but not in RELEASE, then it could still be the architecture. I was convinced it has to be something else, since my DEBUG was always working with the provided .dll, but i would always see 'plugin couldn't be loaded' whenever i ran release. 

It was just the architecture. Copy&Pasting the other (32bit) .dll fixed everything. 

For being stubborn i had to research this for 16hours, and wanted to safe someone else the troubles.
