### ISSUE TITLE
<input type="file"> ignores accept attribute

### ISSUE THREAD

**Issue by Gregg8** [atom/electron#1768]
I notice that PR #777 added support for input elements with type "file" (and "color").

However, the `accept` attribute is ignored.

For example,

```
<input type="file" accept=".txt">
```

Will add a "Text Document" option to the list of file types in the Open dialog if you simply run this in a browser.

If you run it under Electron, it does not appear.

Tested only under Windows (8.1).

**Comment by paulcbetts** [comment]
If you're writing custom Electron code, you should just use the dialog module directly, there's no reason to use the input picker

**Comment by Gregg8** [comment]
If that's the case, I wonder why support was added for it in the first place as per #777 ? 

I think that while there is support for it, it should work as expected and specifying your own file specs is a very common use case. 

Also, in some circumstances, we want to use our html in a standard web browser.

Would be grateful if this could be included in some future release.

**Comment by Gregg8** [comment]
bump :-)

**Comment by Gregg8** [comment]
@zcbenz bump :-)

**Comment by frankhale** [comment]
@hokein, you are a super hero, thank you for this patch!

**Comment by Gregg8** [comment]
@hokein, thanks very much. I can't test it right now as I don't have the necessary compiler but will test it as soon as it's released.

**Comment by Gregg8** [comment]
Tested...works...thanks!

**Comment by ducky427** [comment]
On a successful `<input type="file" accept=".txt">`, I get a path like `C:\FakePath\data.txt`.

Is that the expected behaviour?

**Comment by Gregg8** [comment]
Yes that is expected behaviour. Under this circumstance, you're in the context of a sandboxed browser environment so that file path is a virtual one (read-only) to the real file and your JS code can open and process it as required.

If you want the real file path then as @paulcbetts mentions above, you would use the "dialog module" and you'll get exactly what you want.

The reason I raised this issue is because although our app is an Electron app, it loads standard html pages which make use of this tag and when running them under Electron, they suddenly lost this feature.

**Comment by ducky427** [comment]
thanks a lot for clarifying my understanding @Gregg8. much appreciated.

**Comment by nuthinking** [comment]
I use this [FileSelector](https://github.com/muaz-khan/FileBufferReader/blob/master/dev/FileSelector.js) and Electron still seems to ignore the accept parameter.
