### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///D:/css/app.css

### ISSUE THREAD

**Issue by RinatMullayanov** [atom/electron#1769]
I have such a structure in the application:
![file struct](https://cloud.githubusercontent.com/assets/7579698/7792911/fb0c2a54-02d1-11e5-9656-ceee18a79006.PNG)

I write in head my index.html:
```
<link rel="stylesheet" href="css/app.css"/>
```
 run electron and get error:

![capture](https://cloud.githubusercontent.com/assets/7579698/7792884/95d6092a-02d1-11e5-913e-a1f58e8ffbd7.PNG)
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///D:/css/app.css
Please everyone, tell me, how should I set the path to the file?

**Comment by lolmaus** [comment]
Related issue: #1747.

**Comment by shama** [comment]
Try this as an alternative way to get around this path issue:

```html
<html>
  <head>
    <title></title>
  </head>
  <body>
    <script>
    var link = document.createElement('link')
    link.setAttribute('rel', 'stylesheet')
    link.setAttribute('href', require('path').join(__dirname, 'css', 'app.css'))
    document.head.appendChild(link)
    </script>
  </body>
</html>
```

**Comment by RinatMullayanov** [comment]
@shama Thanks for snippet.
I get an error because the use <base href="/">, without this error does not occur.

**Comment by odragora** [comment]
Have the same issue too. Electron tries to load resources from C:/ , relative paths not working.
Setting full path is not an option, files will not be loading if we will place application on another path.

**Comment by BesatZardosht** [comment]
I have the same issue getting some font

I have added this to my CSS
`@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);
`
I have even tried adding this to my html:
`<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />`

but I get this error:
`Failed to load resource: net::ERR_CONNECTION_REFUSED`

**Comment by Myrga** [comment]
If this occur when having `<base href="/">` in the index.html, just replace it by `<base href="./">`.

**Comment by guibot17** [comment]
@Myrga you're a life save. I've been looking for an answer for 5 days now, no doc on this, until I came across this old post. Thanks a lot

**Comment by johnmw** [comment]
ps: if you happen to be using create-react-app and see this message, try putting 

`"homepage": "./",`

is your package.json

**Comment by breaded** [comment]
thank you so much

**Comment by paulcbetts** [comment]
@BesatZardosht You've got a typo in your URL:

```
<link rel="stylesheet" type="text/css" href="https//fonts.googleapis.com/css?family=Open+Sans" />
```

should be:

```
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans" />
```

(note the `:`)

**Comment by mim-Armand** [comment]
In case you are here with the same problem using `Webpack 2.x`, `React` and/or `Redux`, there is a chance that this would solve your problem:
> Search your project directory for "publicPath" and change its value from `/` to `./`
> with all the different available boilerplates this setting may be found in different locations, In my case using `redux-cli` which uses `redux-starter-kit`, it was in the `project.config.js`:
``` javascript
publicPath: './',
```
Also if you are building for `Electron` you may need to add/modify the Webpack `target` property.
Stay Happy!! 😄

**Comment by superjamesmccafferty** [comment]
Had same problem, Myrga's solution worked. I think <base href="/"> must consider / as global root directory for the PC when using file protocol. While "./" works as a relative reference to the current folder. Just a guess, when using http:// protocol on port 4200 (Where I serve my Angular4 app) everything works with "/". For file protocol have to use "./"

**Comment by superjamesmccafferty** [comment]
Decided to remake my application in React. Once I added file-loader to my project, I started getting this issue again. changing the publicPath property in webpack.config.js to a relative path (for me ./app/ rather than /app/) fixed the problem.

**Comment by emirpoy** [comment]
You can save the html file as "save as web page" then try to open in chrome. 
This worked for me.

**Comment by Tahawahid** [comment]
how to solve "*Failed to load resource: net::ERR_FILE_NOT_FOUND*"
whenever I add an image using "CSS" it throws this **error.** Do you guys have any solution for it???

**Comment by itsaakashpatel** [comment]
It's because of your all files are being served from the local file system rather than the relative app path.
The solution is to intercept the file protocol. Do following changes in main.js file
### Main.js
`mainWindow = new BrowserWindow({width: 1100, height: 700, icon: __dirname + '/icon.ico'})
  mainWindow.loadURL(url.format({
   pathname:'index.html',
   protocol: 'file',
   slashes: true
 }))`

`app.on('ready', () => {
  protocol.interceptFileProtocol('file', (request, callback) => {
   const url = request.url.substr(7)    /* all urls start with 'file://' */
   callback({ path: path.normalize(`${__dirname}/${url}`)})
 }, (err) => {
   if (err) console.error('Failed to register protocol')
 })
 createWindow() /* callback function */
})`

**Comment by rkmyowin** [comment]
a

**Comment by xiaomizhou66** [comment]
> @Tahawahid @RinatMullayanov
> It's because of your all files are being served from the local file system rather than the relative app path.
> The solution is to intercept the file protocol. Do following changes in main.js file
> 
> ### Main.js
> `mainWindow = new BrowserWindow({width: 1100, height: 700, icon: __dirname + '/icon.ico'}) mainWindow.loadURL(url.format({ pathname:'index.html', protocol: 'file', slashes: true }))`
> 
> `app.on('ready', () => { protocol.interceptFileProtocol('file', (request, callback) => { const url = request.url.substr(7) /* all urls start with 'file://' */ callback({ path: path.normalize(`${__dirname}/${url}`)}) }, (err) => { if (err) console.error('Failed to register protocol') }) createWindow() /* callback function */ })`

？

**Comment by Yuresh** [comment]
Path issue. Browser search your file in D:/css/app.css. This because somewhere in your code, have mentioned a wrong path.

**Comment by leodutra** [comment]
This also did the trick. Thanks for Mr. @itsaakashpatel for the insight.
```js

// ...
const { protocol } = require('electron')
// ... 
// run the next block right before <BrowserWindow>.loadFile()
const htmlRootDir = 'dist/'
const indexFile = 'index.html'

protocol.interceptFileProtocol(
    'file',
    (request, callback) => {
        const url = request.url.substr(7) // strip "file://" out of all urls
        if (request.url.endsWith(indexFile)) {
            callback({ path: url })
        } else {
            callback({ path: path.normalize(`${__dirname}/${htmlRootDir}/${url}`) })
        }
    }, 
    error => console.error(error) 
) 
// ...

**Comment by leodutra** [comment]
This also did the trick. Thanks for Mr. @itsaakashpatel for the insight.
```js

// ...
const { protocol } = require('electron')
// ... 
// run the next block right before <BrowserWindow>.loadFile()
const htmlRootDir = 'dist/'
const indexFile = 'index.html'

protocol.interceptFileProtocol(
    'file',
    (request, callback) => {
        const url = request.url.substr(7) // strip "file://" out of all urls
        if (request.url.endsWith(indexFile)) {
            callback({ path: url })
        } else {
            callback({ path: path.normalize(`${__dirname}/${htmlRootDir}/${url}`) })
        }
    }, 
    error => console.error(error) 
) 
// ...
```

**Just replace `htmlRootDir` and/or `indexFile` for your expectations.**
_Tested on Linux_

**Comment by zearaez** [comment]
@Myrga Thanks for saving my day. Loved your answer :)

**Comment by defusioner** [comment]
@Myrga well, you would probably set "homepage": "./" in the package.json instead of hard-coding these things.

**Comment by leodutra** [comment]
> @Myrga well, you would probably set `"homepage": "./"` in the `package.json` instead of hard-coding these things.

Please @defusioner, is there any doc on this?

**Comment by defusioner** [comment]
@leodutra humm, I'm using react-cra and they are able to produce such config: https://create-react-app.dev/docs/deployment#building-for-relative-paths

**Comment by leodutra** [comment]
@defusioner Hum, that explains a lot.
Looks like this is not on the **electron** level, it's more a **base url** for react apps, where this will replace the default root for any relative or root link.

In my case, using a Vue.js dist or raw electron, this probably won't work.

I think this package approach should be taken in consideration... like some `electronBasePath` on package.json

**Comment by johnfidel98** [comment]
> ps: if you came here and are using create-react-app, try putting `"homepage": "./",` in your package.json. (Although apparently this is not currently supported so you might have other issues with fonts and such, which might require moving those assets to your /public folder)

this worked... thanks man!

**Comment by yingshaoxo** [comment]
I think the `win.loadFile('index.html')` is like a shit! After we compile it to EXE file by using `electron-builder`. It'll always show `DevTools failed to load SourceMap: Could not load content for file:///C:/User..../resources/app.asar/bootstrap.min.css.map`.

But the `win.loadURL()` works well.

**I spent 8 hours to find out that this is a bug that I can't solve.**

https://yingshaoxo.blogspot.com/2020/06/about-electron.html

**Comment by m-emre-yalcin** [comment]
I got the same issue too.

it seems fine here:
![image](https://user-images.githubusercontent.com/61562772/112757329-0ee9e800-8ff2-11eb-9b3d-a0b73e6f3502.png)

but when I open developer tool>network and check the request URL of my unfounded file

![image](https://user-images.githubusercontent.com/61562772/112757269-ba466d00-8ff1-11eb-8a85-49652c0a03d3.png)

request URL wasn't correct. So, it could be related to internal options in background code.

**Comment by maoAmanda** [comment]
> In case you are here with the same problem using `Webpack 2.x`, `React` and/or `Redux`, there is a chance that this would solve your problem:
> 
> > Search your project directory for "publicPath" and change its value from `/` to `./`
> > with all the different available boilerplates this setting may be found in different locations, In my case using `redux-cli` which uses `redux-starter-kit`, it was in the `project.config.js`:
> 
> ```js
> publicPath: './',
> ```
> 
> Also if you are building for `Electron` you may need to add/modify the Webpack `target` property.
> Stay Happy!! 😄

it works for me

**Comment by r-shafi** [comment]
Having this same error. Can't load image and other contents from **assets** folder in Angular 12. When I look in the console I see that it is skipping the project-name-directory and directly looking into the assets folder from the root of my system

**Comment by r-shafi** [comment]
Sorry I'm dumb.

> In the Angular project, you don't have to add the relative path from your file to image file.
Angular resolves this problem for you, and in a component, you have to only add a path to the assets folder, instead of **../../assets**.

**Comment by eezz4** [comment]
If `react-app-rewired` is used in `CRA`, it can be changed as below instead of `"homepage": "./"`
```js
  webpack: (reactConfig, env) => {
    reactConfig.output.publicPath = "./";
    return reactConfig;
  },
```

**Comment by Ilya-Meer** [comment]
> This also did the trick. Thanks for Mr. @itsaakashpatel for the insight.
> 
> ```js
> // ...
> const { protocol } = require('electron')
> // ... 
> // run the next block right before <BrowserWindow>.loadFile()
> const htmlRootDir = 'dist/'
> const indexFile = 'index.html'
> 
> protocol.interceptFileProtocol(
>     'file',
>     (request, callback) => {
>         const url = request.url.substr(7) // strip "file://" out of all urls
>         if (request.url.endsWith(indexFile)) {
>             callback({ path: url })
>         } else {
>             callback({ path: path.normalize(`${__dirname}/${htmlRootDir}/${url}`) })
>         }
>     }, 
>     error => console.error(error) 
> ) 
> // ...
> ```
> 
> **Just replace `htmlRootDir` and/or `indexFile` for your expectations.** _Tested on Linux_

This did the trick for me while working with a Vue.js application, thanks!
