### ISSUE TITLE
Global shortcut and previously focused application

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [atom/electron#1771]
I have a question and I can't ind any documentation about it.

I would like to have a global shortcut that opens a form, but depending on which app had the focus at the moment the shortcut was triggered, I would like to fill up the form.

So in a nutshell, is there a way to know which application had the focus when the shortcut is triggered? Or should I try to have an ad-hoc solution for each OS?

Thanks in advance

**Comment by zcbenz** [comment]
Electron (and most other GUI framework) is only aware of windows opened in its own app, inspecting operating system's other windows is out of Electron's scope. But you can always write a native node module to achieve this.

**Comment by BenjaminVanRyseghem** [comment]
Thanks :+1:
