### ISSUE TITLE
Navigating to javascript: URLs desyncs renderer and developer tools

### ISSUE THREAD

**Issue by joepie91** [atom/electron#1772]
When attempting to `window.loadUrl("javascript:...")`, the renderer and developer tools appear to desynchronize somehow:

![aatt studio_263](https://cloud.githubusercontent.com/assets/1663259/7803002/350ed572-0344-11e5-9950-4adc57fbd3bb.png)

The original markup was as follows:

```html
<html>
	<head>
		<meta charset="UTF-8">
		<title>AATT Studio</title>
	</head>
	<body>
		Test 
	</body>
</html>
```

The code triggering the navigation in an attempt to 'inject' the JS into the page (compiled from Coffeescript):

```javascript
  var scriptUrl;
  scriptUrl = "javascript:(function(){_lr_script=document.createElement('SCRIPT');_lr_script.type='text/javascript';_lr_script.src='http://127.0.0.1:35729/livereload.js?x='+(Math.random());document.getElementsByTagName('head')[0].appendChild(_lr_script);})();";
  if (window.webContents.isLoading()) {
    return window.webContents.on("dom-ready", function() {
      return window.loadUrl(scriptUrl);
    });
  } else {
    return window.loadUrl(scriptUrl);
  }
```

As you can see in the screenshot, there are two different states:

* __Renderer:__ Believes we still have the original markup loaded.
* __Developer tools:__ Has loaded a new, blank document without any of the original markup, just with the injected script.

The 'page' that developer tools believe to be operating on, has `document.location.href == 'about:blank';`, whereas the original page was loaded as a HTML file from a `file://` url.

__Version:__ 0.26.1 (via `electron-prebuilt` on npm)

__Operating system:__ openSUSE 13.1 x86_64, XFCE

__Expected behaviour:__ Either disallow loading `javascript:` URLs if this is not supported, or execute them in the context of the currently loaded page.

**Comment by paulcbetts** [comment]
This is probably a bug, but also there's no reason to do this, just use `executeJavaScript`

**Comment by joepie91** [comment]
@paulcbetts Yeah, I found that after a second read of the documentation - I'd probably missed it because it's listed under WebContents rather than BrowserWindow. Perhaps a note about `executeJavaScript` should be added under `loadUrl`? As it's commonplace to use use `javascript:` URLs in most 'embedded browsers' for injecting JS, I imagine this may be a frequent thing for people to run into.

Aside from that, I was alerted by a friend that this bug may point at a deeper potential security issue; its behaviour is very similar to that of IE, that made the [Universal XSS](http://seclists.org/fulldisclosure/2015/Feb/0) bug possible. This should probably be looked into further, potentially treated as a security issue.

**Comment by paulcbetts** [comment]
> Aside from that, I was alerted by a friend that this bug may point at a deeper potential security issue; its behaviour is very similar to that of IE, when it made the Universal XSS bug possible. This should probably be looked into further, potentially treated as a security issue.

This page is pretty light on the details, can you explain further why you think this is the case?

**Comment by joepie91** [comment]
> This page is pretty light on the details, can you explain further why you think this is the case?

As I understand it, the UXSS bug in IE was a result of different parts of the browser believing they were on a different 'origin' (due to the setTimeout only triggering *after* navigation to a different origin), leading to cross-origin protection not working.

Looking at this bug, different parts of the 'browser' (specifically, renderer and developer tools, as far as I can tell) believe they are in a different context, which points at a potential missing check somewhere.

I'm far from qualified with regards to CEF, so I don't know whether this actually *is* a security issue, I'm really just observing that it's doing something that shouldn't be possible, and treating it as a 'smell' :)
