### ISSUE TITLE
can not run on windows xp 32bit

### ISSUE THREAD

**Issue by ParkerLiu** [atom/electron#1775]
I Have tried to electron.exe on winXP 32bit with electron-v0.26.1-win32-ia32. Got the error "...not win32 program"

**Comment by paulcbetts** [comment]
Won't fix, Electron is Win7 or higher

**Comment by lashanchenqi** [comment]
So sad about  not  support for Windows XP.   So Electron  is invalid in china  as  most of  chinese (60 percent or more)  are still  using  XP.

**Comment by baconface** [comment]
Keep in mind that that Chromium no longer supports XP. The Electron team would have to continue patching Chromium to support XP as well as re-add previous XP specific code the Chromium team striped. And Node.js re-added support but they are likely unsupporting it in 0.6.0.

And everyone that supports a nonsupported OS are contributing to the problem.

If you really must, the 0.12.X releases of NW.js use an older version of Chromium thus supporting XP. But NW.js is going to run into the same issue as Electron with their future releases.

**Comment by paulcbetts** [comment]
XP support in official Electron is a non-starter. You could attempt to patch an older version on your own but it won't be supported, sorry

**Comment by salaad** [comment]
Does anybody know that United States Navy using Windows XP? Not just kidding!!!

**Comment by baconface** [comment]
I am not debating that XP is still widely used in the wild. But it doesn't change the fact that the Electron team would have to constantly fix Chromium for it to work. And it also doesn't change the fact that the problem isn't developers are not supporting it but people are willingly and knowingly using an unsupported operating system. They should put less work into getting them to work and finally upgrade.

As far as the Navy goes using XP was a temporary solution until they migrated. But they also [paid heavily](http://money.cnn.com/2015/06/26/technology/microsoft-windows-xp-navy-contract/) for Microsoft to continue updates while they migrated to a newer OS which should be complete in a few months.

**Comment by salaad** [comment]
Breaking news on White House :smile: 
http://www.nytimes.com/2016/04/04/us/politics/technology-upgrades-get-white-house-out-of-the-20th-century.html

**Comment by jetiny** [comment]
the windows xp version https://github.com/jetiny/electron-xp

**Comment by alainazpe** [comment]
need xp version please, no way to found it in the web :(

**Comment by LFF5644** [comment]
i m still using XP in 2025 on my old PC sometimes when i have to much free time i try to find old programs that work ;-)
