### ISSUE TITLE
WebGL problems starting Electron on Windows 7 VM

### ISSUE THREAD

**Issue by gregdelozier** [atom/electron#1778]
Hi,

I've looked around a bit for this issue being reported and the only related bug seems to be closed.

When starting the Electron.exe app (0.26.1) using either of the 32-bit or 64-bit builds on a Windows VM via RDP, I get the following message, though the default app appears to bring up its window and work correctly. 

```
C:\Projects\Grace>[5196:0526/165733:INFO:renderer_main.cc(200)] Renderer process started
[3232:0526/165734:ERROR:gl_surface_egl.cc(161)] eglInitialize failed with error UNKNOWN
[3232:0526/165734:ERROR:gl_surface_win.cc(164)] GLSurfaceEGL::InitializeOneOff failed.
[3232:0526/165734:ERROR:gpu_child_thread.cc(161)] Exiting GPU process due to errors during initialization
```

So this doesn't seem to be working properly. I don't know if this is due to being on a VM. For what it's worth, the site https://get.webgl.org/ works fine. 

Any thoughts? 

Perhaps some way to start Electron without WebGL? I'm assuming that with these messages happening that WebGL isn't starting. The applications I'm writing don't seem to be bothered by that. 

Thanks for any help, and if I can be of assistance in testing this in, I'd be happy to.

**Comment by zcbenz** [comment]
GPU accelerations do not work on most VMs, WebGL works on real machines. You can just ignore those warnings if you don't use WebGL in your app.
