### ISSUE TITLE
<input type="file"> doesn't remember last directory used

### ISSUE THREAD

**Issue by Gregg8** [atom/electron#1780]
When running in a browser, the <input type="file"> component remembers the last directory you were using. When running under electron it does not, which can be be rather frustrating.

Could we please mimic this functionality while running under electron.

Link to related <input type="file"> issue: #1768

**Comment by jorangreef** [comment]
Or perhaps just a way to control which directory will be the default, that would allow even more flexibility for this and other use cases as well.

**Comment by hokein** [comment]
Closing it since it has been implemented.

**Comment by Gregg8** [comment]
Tested...works...thanks!
