### ISSUE TITLE
WebGL2 Support?

### ISSUE THREAD

**Issue by mattdesl** [atom/electron#1781]
I did a quick search and couldn't find anything. Using `canvas.getContext('webgl2')` returns null (but `'webgl'` works fine).

WebGL2 is supported in Chrome v43 if launched with the following flag: `--enable-unsafe-es3-apis`
Not sure about Chromium versions.

There's a lot of great things WebGL2 brings that would be ideal for games, 3D software, image editors, and other tools built on Electron.

**Comment by paulcbetts** [comment]
Electron just hit Chrome 43 like 30sec ago, wait until the next release :)

**Comment by zcbenz** [comment]
For new Chrome features you should wait for Electron release with Chrome upgrade.

**Comment by mattdesl** [comment]
Ok, I'll ask again next release. :smile:

**Comment by jsonnull** [comment]
Is this supported yet? There's been several releases, but I don't know how to check the chrome version for the latest release.

**Comment by mattdesl** [comment]
I think in order for this to work we would need a way to pass switches to Chromium. It seems better than enabling it by default or having a flag specifically for webgl2.

**Comment by jsonnull** [comment]
@mattdesl Electron lets you pass (some) command-line switches to Chrome, but the wording of the documentation suggests that only those listed will work.

See: http://electron.atom.io/docs/v0.29.0/api/chrome-command-line-switches

**Comment by jsonnull** [comment]
So WebGL2 can be enabled on current Electron versions, which still use Chrome 43 (supports the command-line switch):

```javascript
app.commandLine.appendSwitch('enable-unsafe-es3-apis');
```

**Comment by hokein** [comment]
Yes, current release Electron support it. You can view http://webglreport.com/?v=2 to check it.
