### ISSUE TITLE
[Windows] libchromiumcontent download failed during bootstrap

### ISSUE THREAD

**Issue by nantas** [atom/electron#1782]
```bash
c:\Python27\python.exe d:\projects\fireball\atom-shell\vendor\brightray\script\b
ootstrap --commit fa886209473d40eafda4e8263a79b5cf83eef95e --target_arch ia32 ht
tp://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent
Downloading libchromiumcontent.zip...
http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent/win/ia32/fa88620
9473d40eafda4e8263a79b5cf83eef95e/libchromiumcontent.zip
```

When I try to bootstrap and build electron v0.26.1, I always get the following error trying to extract the downloaded `libchromiumcontent.zip` file.

```bash
zipfile.BadZipfile: File is not a zip file
```

I also tried the url http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent/win/ia32/fa886209473d40eafda4e8263a79b5cf83eef95e/libchromiumcontent.zip in browser and it also gives me an empty file.

The mac download link http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent/osx/x64/fa886209473d40eafda4e8263a79b5cf83eef95e/libchromiumcontent.zip seems to work fine.

Could you verify if the libchromiumcontent.zip file link for windows works? @zcbenz

**Comment by zcbenz** [comment]
I hadn't uploaded it yet, it should work now. You should checkout the `v0.26.1` tag if you want to build a specified version, the master branch is not always ready for building.

**Comment by nantas** [comment]
I see. thx!
