### ISSUE TITLE
incompatible with uim (linux input method for japanese)

### ISSUE THREAD

**Issue by despairblue** [atom/electron#1783]
See [this](https://discuss.atom.io/t/atom-does-not-run-on-linux-related-to-protobuf/16424) discourse thread and the following [aur](https://aur.archlinux.org/packages/atom-editor-bin/?comments=all) comments (copied here since the aur provides no direct links to comments):

**Vortico**
> This might not be the best place to ask this question, but I've been having the issue for months, and I don't know where to ask it.

> I can compile atom just fine or simply use this package, but when attempting to run, I get the error message

> [libprotobuf FATAL ../../third_party/protobuf/src/google/protobuf/stubs/common.cc:61] This program requires version 2.5.1 of the Protocol Buffer runtime library, but the installed version is 2.5.0. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "gen/proto_out/config/config.pb.cc".)

> I believe this is emitting from libchromiumcontent.so, which is a build of most of Chromium's libraries (including a second copy of V8) except its specific application code. This error message doesn't seem to be effected by whether I have protobuf installed or its version, so it must be referring to an internally linked copy of protobuf 2.5.0.

> Has anyone run into this problem or have any idea what I can do to research it further? Sublime Text is the only software I'm using which is nonfree, so it would be fantastic to have a fully free system (besides firmware).

**cemsbr**
> @Vortico, I also have problems with protobuf version. I'm still having with version 0.200.0

**despairblue**
> @cemsbr and @Vortico does that help: https://discuss.atom.io/t/atom-does-not-run-on-linux-related-to-protobuf/16424/5 ?

**cemsbr**
> @despairblue, that post does not include a solution, but finds the reason. I posted a workaround, but their anti-spam is buffering it. The following work for me:

> ```
$ unset GTK_IM_MODULE QT_IM_MODULE XMODIFIERS
$ atom
```
> Maybe you want to patch or add a wrapper to the package until it is solved.

I'm also not sure if this still affects the current electron version since atom's internal electron version is quite old. I could also open an issue in the atom repo so they can add a workaround to the atom startup script.

**Comment by zcbenz** [comment]
It has been months I believe the problem caused by libprotobuf versions is not there anymore.
