### ISSUE TITLE
Remove setTimeout Throttle

### ISSUE THREAD

**Issue by Subash** [atom/electron#1786]
Chrome throttles setTimeout to 1 second when app is minimized, which is ok for a browser but for an app platform that delay might slow down promises and other functions that rely on `setTimeout 0`. Can you please fix that.

http://blog.pivotal.io/labs/labs/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs

https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/frame/DOMTimer.cpp

**Comment by Subash** [comment]
@zcbenz, I am always in hurry :laughing:

**Comment by Subash** [comment]
https://codereview.chromium.org/6546021/patch/1001/2001

**Comment by Subash** [comment]
Angularjs promises are resolving after 1 second because of this when app is minimized.

**Comment by zcbenz** [comment]
They only do it in inactive tabs, in Electron every window is an active tab.

**Comment by Subash** [comment]
@zcbenz, Sorry for not being clear, being active doesn't matter. The window needs to be visible too.  Here is a video demonstrating the problem. 
https://www.youtube.com/watch?v=YKobBQ5bAIk&feature=youtu.be

**Comment by Subash** [comment]
I am sorry for being unclear. Please see this video for explanation. Window must be visible otherwise chrome will throttle.
https://www.youtube.com/watch?v=YKobBQ5bAIk

**Comment by Subash** [comment]
Temporary fix is,  
```javascript
window.setTimeout = require('remote').getGlobal('setTimeout');
window.clearTimeout = require('remote').getGlobal('clearTimeout');
```

**Comment by Subash** [comment]
@zcbenz , hmm the temporary fix causes more errors then it solves. Can you please reopen the issue ?

**Comment by zcbenz** [comment]
As workaround, you can use `setImmediate` or `process.nextTick` instead of `setTimeout 0`. I'm :-1: on fixing this though.

**Comment by Subash** [comment]
Why thumbs down?  I cant really control the timeout because it's used by angular promises library.

**Comment by Subash** [comment]
My app is taking 100x time to compile a simple less file from 500 milliseconds to 5 seconds because of this issue.

**Comment by Subash** [comment]
I've put $150 bounty on this. https://twitter.com/sbspk/status/604250752769335296

**Comment by steelbrain** [comment]
@Subash clone this repo locally, open your index.html and keep your eye on the console
https://github.com/steelbrain/Chrome-Throttle-Workaround

**Comment by Subash** [comment]
@steelbrain, I am expecting a patch on chrome source because this is a custom build of chrome.
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/frame/DOMTimer.cpp
I will look at your workaround though.

**Comment by Subash** [comment]
I already have some workarounds but they are not working well.
```javascript
/** Temporary Fix for https://github.com/atom/electron/issues/1786**/

    window.setTimeout = require('remote').getGlobal('setTimeout');
    window.clearTimeout = require('remote').getGlobal('clearTimeout');

    /** END Temporary Fix **/
```

**Comment by Subash** [comment]
So I am expecting a permanent fix in Chrome code.

**Comment by Subash** [comment]
https://github.com/atom/libchromiumcontent/pull/130 should fix this issue.

**Comment by deepak1556** [comment]
Sorry for pitching in late on this, actually @zcbenz this can be fixed without patching chromium by setting  `override_state` to `blink::WebPageVisibilityStateVisible` [here](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/renderer/content_renderer_client.h&rcl=1433115003&l=245) .  We could provide this as an optional feature for users as a option during browser window creation and override the state to always visible whenever the flag is present, can send a PR if sounds good.

**Comment by Subash** [comment]
@deepak1556 I emailed about this. I guess my email got filtered by spam or something.

**Comment by paulcbetts** [comment]
I would prefer @deepak1556's solution because we've now significantly impacted battery life impact for Electron application

**Comment by zcbenz** [comment]
@Subash I have reverted the patch in libchromiumcontent, from next release you will need to set the `page-visibility` property of `web-preferences` to `true` to achieve the same effect.
