### ISSUE TITLE
does fav-icon-updated event get triggered...I am not able to get it working

### ISSUE THREAD

**Issue by skandasoft** [atom/electron#1787]
I am working on this package browser-plus(http://atom.io/packages/browser-plus) for atom using webview. I wanted to see if I can set the fav-icon using the page-favicon-updated event of the webview.. when I register for it/put debugger doesn't seem to stop there..

**Comment by deepak1556** [comment]
can you provide a sample scenario that reproduces this behaviour ? i am unable to reproduce it..

```html
<webview src="http://github.com"></webview>
<script>
  <webview>.addEventListener('page-favicon-updated', function() {
    debugger;
  })
</script>
```

**Comment by skandasoft** [comment]
you can install plugin browser-plus for atom editor and I have hard debugger in the code..which doesn't get triggered..
https://github.com/skandasoft/browser-plus/blob/master/lib/browser-plus-view.coffee
line 69 and line 72

**Comment by zcbenz** [comment]
The electron version used by Atom is a bit old, you can track https://github.com/atom/atom/pull/6877 for progress.
