### ISSUE TITLE
Implemented `chrome.*` APIs

### ISSUE THREAD

**Issue by fhur** [atom/electron#1791]
There is a note [here](https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md#chrome-apis) that mentions:

`Some chrome extensions use chrome.* APIs for some features, there is some effort to implement those APIs in Electron to make them work, but we have only implemented few for now.`

Is there a list of implemented `chrome.*` APIs? Typing `console.log(chrome)` yields a `chrome is not defined error` in both the main and rendered processes.

**Comment by paulcbetts** [comment]
`chrome.*` will only be defined in a DevTools extension, and the only method implemented is `getURL`

**Comment by zcbenz** [comment]
We won't implement `chrome.*` except for the ones that can be used in devtools extension.

**Comment by digital-flowers** [comment]
chrome api has many useful tools like accessing usb also intercepting webview i was thinking to move my application from nwjs to electron but now this is really huge problem

**Comment by noahbenham** [comment]
Are there any plans to implement `chrome.*` in the future?

**Comment by kevinsawicki** [comment]
> Are there any plans to implement chrome.* in the future since this post is a bit old?

There isn't a plan to add 100% of them right now, but many ave been added so many extensions do work. If there are ones you specifically want added to enable an extension to work then please feel free to add them in a pull request.

There are other issues to track specific Chrome APIs: https://github.com/electron/electron/issues?q=is%3Aopen+is%3Aissue+label%3Achrome-api
