### ISSUE TITLE
Trouble saving dev tools profile data on Linux

### ISSUE THREAD

**Issue by nathansobo** [atom/electron#1795]
I'm hearing reports from Linux users that they are unable to save profile data. They get a "Save As" dialog but the file is empty. If this is indeed an Electron issue, it would be nice to get this for debugging performance problems.

**Comment by deepak1556** [comment]
yup can confirm the issue on linux, seems long traces arent written to the file.

**Comment by deepak1556** [comment]
@zcbenz this no longer seems to be an issue, tested with master branch.

**Comment by zcbenz** [comment]
:+1:
