### ISSUE TITLE
Electron 0.27.0: devtools sometimes crashes the app

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1798]
When using 0.27.0 I notice that sometimes when I toggle dev tools, the entire app just crashes. I have not yet found the error message in the logs when this happens, but wanted to let you know in case you have an idea.

**Comment by zcbenz** [comment]
This has been fixed by #1797 and a new release will be published today.

**Comment by bpasero** [comment]
Oh excellent, thanks!
