### ISSUE TITLE
Quick start improvement

### ISSUE THREAD

**Issue by fpinzn** [atom/electron#1800]
If electron is installed following the instructions either of the readme or the website, it's possible to run your application by simply doing `electron <path>`.

**Comment by frankhale** [comment]
The answer to this is yes. If you install Electron using the npm module like this:

```
# Install the `electron` command globally in your $PATH
npm install electron-prebuilt -g
```

Then you can simply run electron from the command line and point it to the path of your app folder. The app folder containing all the necessary bits needed to run your app.

I just test this against my own app.

**Comment by zcbenz** [comment]
The quick start guide now mentions electron-prebuilt.
