### ISSUE TITLE
Flash plugin can't be found in asar package

### ISSUE THREAD

**Issue by Gregg8** [atom/electron#1802]
The Flash plugin is now running very nicely in our app (ref #1767) and so the next thing we're working on is packaging.

Having proved the app works under a standard directory structure, we have packaged it into an `app.asar` file in the `resources` directory as per the instructions and everything works fine until we try to launch a page requiring Flash. We get the following error:

```
[55852:0528/201524:ERROR:ppapi_thread.cc(278)] Failed to load Pepper module from D:\dev\...etc...\run\node_modules\electron-prebuilt\dist\resources\app.asar\js\compiled/../../plugins/pepflashplayer64_17_0_0_188.dll (error: 126)
```

As you can see, we have our required Flash plugin in a plugins directory in the asar file.

We can use the electron command line to point to a Flash dll outside the asar and it works fine.

It is looking like the plugin loader within Chromium does not recognise the asar file system, but if we're doing something wrong, I'd be happy to hear what it is.

Tested under Windows 7/8 only.

**Comment by paulcbetts** [comment]
You need to use the "unpacked" feature of ASAR to make the Flash plugin not end up in an ASAR package (or just save it off in a separate directory), you can't load DLLs out of ASAR

**Comment by Gregg8** [comment]
Thanks for confirming this. I didn't glean that information out of the [packaging](https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md) doco so it might be helpful to others to list this and any further limitations there.

I used your "separate directory" suggestion in the end because the unpack feature will now place the dll in a different folder (`app.asar.unpacked/plugins` instead of `app/plugins`) so I would have to determine if I am in "asar mode" or "directory mode" and adjust the value passed to `ppapi-flash-path` accordingly.

Can you suggest the best way to determine if the app is being run from an asar file or an actual directory? One thought is to use `originalFs.readFileSync('/path/to/app.asar')` to see if the asar file is there but this is not bullet proof.

I also found an issue with the asar utility which I [reported separately](https://github.com/atom/asar/issues/36).

**Comment by zcbenz** [comment]
Files in asar archive can only be read by Node.js APIs or `file://` requests started by the browser.

> Can you suggest the best way to determine if the app is being run from an asar file or an actual directory?

You can check if `__filename` is under an asar archive.
