### ISSUE TITLE
Getting "Uncaught ReferenceError: process is not defined" when requiring remote app

### ISSUE THREAD

**Issue by somebody32** [atom/electron#1803]
Hi!

Just noticed that when I'm trying to do `var App = remote.require('app');` inside the preload script I get `Uncaught ReferenceError: process is not defined", source: module.js (461)` error message in the console. But everything is working though. 
Is there are any hidden problem with that?

Electron v 0.27

**Comment by steelbrain** [comment]
the error `process` is not defined is clearly not related to remote. Can you provide a minimal repro preload script?

**Comment by somebody32** [comment]
@steelbrain, of course.

`main.js`:
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');
var mainWindow = null;
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 800, height: 600, preload: __dirname + '/client.js', 'node-integration': false});
  mainWindow.loadUrl('http://google.com');
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
```

`client.js`:
```javascript
(function() {
  'use strict';
  var remote = require('remote');
  var app = remote.require('app');
})(this);
```

And this error happens only when `node-integration` set to `false`.
