### ISSUE TITLE
Unable to upload files to the server

### ISSUE THREAD

**Issue by fsainz** [atom/electron#1805]
This looks like a node related issue but i'm reaching a level of desperation in which I though it was worth asking here in case it's connect to electron somehow.

Basically, i'm trying to upload the contents of a file stored on the filesystem. I've tried it with different methods, but in general what I have is the blob of the file, for example after doing the following
```
contents = fs.readFileSync fileLocation
blob = new Blob([contents])
```
and on the server side, I end up with a file with invalid bytes. It seams that readFile is transforming the original byte array (from a a png) into UTF-8 forcing some replacements due to invalid characters.  That made me try to convert to the other available encodings ("raw", "binary", etc..) without too much success until I tried with base64

```
contents = fs.readFileSync fileLocation, "base64"
blob = new Blob([contents])
```
and decoded it on the server. The new problem is that my test file of 20k worked pretty well, but any larger file (about 200k for example, nothing huge) will just crash electron when trying to turn it into a blob. If I don't use "base64", then the file could be several megabytes without crashing. 

Is there another preferred way of uploading files? Do I have some very small memory limit that I have to expand on electron for handling this base64 conversion?

Any help would be very appreciated

**Comment by steelbrain** [comment]
Why not use the traditional html forms?

**Comment by fsainz** [comment]
We are syncing files between the web app and the offline app. At some point we want to substitute the local files with the ones remotely and viceversa, some files never go through a Form.  I thought of creating a form with a file input pointed to the local file but I believe that's disabled for security reasons : (

**Comment by zcbenz** [comment]
You can use Node's `http` module for communications with server, HTML5 doesn't work well together with Node.js's `Buffer`.

**Comment by fsainz** [comment]
I followed your suggestion, at the end using the [request module](https://github.com/request/request) which makes writing the http post request a little nicer

It worked at the first try, thanks a lot @zcbenz, you've made us very happy :)

```
nodeRequest = require('request')

formData =
  file:
    value: fs.createReadStream( fileLocation )
    options:
      filename: filename

nodeRequest.post {
  url: url
  formData: formData
}, (err, httpResponse, body) ->
  if err
    console.error('upload failed:', err)
  console.log 'Upload successful!  Server responded with:', body
```
