### ISSUE TITLE
Build instructions are out of date, and do not work for Ubuntu 14.04 LTS out of the box

### ISSUE THREAD

**Issue by apm** [atom/electron#1809]
https://github.com/atom/electron/blob/master/docs/development/build-instructions-linux.md

It refers to the old nodejs repo, and has some details talking about Ubuntu 12 & 13.  If the instructions do not work out of the box for a fresh Ubuntu 14.04 LTS system, it probably needs attention.  I got the following error:

/usr/bin/ld: /home/adam/src/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libaccessibility.a(accessibility.atk_util_auralinux.o): undefined reference to symbol 'g_module_symbol'
//usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

The doc addresses this symptom telling you to downgrade from clang 3.4 to 3.0.  If this really is the fix (which it shouldn't be), instructions would be helpful.  Also, the system requirements should not say clang 3.4+ if it doesn't work without a very old version of clang.

**Comment by capouch** [comment]
I just did a complete fresh checkout and build, and I'm still getting this error.  I am using a new clang, though, 3.6.1.

**Comment by BobCochran** [comment]
I cloned electron today (2015-06-01). I am using a virtual machine of Ubuntu 14.04.2 LTS, fully up to date. Build failed on a linker error. You should be able to zoom this photo of the error. There must be another preequisite package missing from the build instructions for Linux.

![electron_build_linker_error_2015-06-01_small](https://cloud.githubusercontent.com/assets/2460105/7915298/95dd8a1e-084a-11e5-9d1c-ff2a30c003e5.jpg)

**Comment by capouch** [comment]
This is the missing library error I was referring to in my original post.  

You can fix it--although I'm certain it's not a blessed manner--by adding "-lgmodule" to an appropriate spot in the file ~/out/[Release|Debug]/build.ninja (line begins with rspfile_content).

Hopefully one of the developers will see this and lead us to the correct solution.  That still leaves the issue of the humungous binary.

**Comment by BobCochran** [comment]
Can you show me how you code that? I tried

'rspfile_content = -lgmodule [...]'

(where [...] means "all the other text in that line"

and

'rspfile_content = -lgmodule-2.0'

and variations of same, and in these files:

out/R/build.ninja
out/Release/build.ninja
out/D/build.ninja
out/Debug/build.ninja


...all without success.

I am new to building with Ninja and my Python experience is practically
nil.

I wonder if I need to begin the build process totally fresh?

Thanks

Bob

**Comment by capouch** [comment]
In ~/out/Release/build.ninja; at/about line 51, here is the line--with the change--and the one above it for context:

** snip **
  rspfile_content = -Wl,--start-group $in -Wl,--end-group $solibs $libs
rule link
  command = $ld $ldflags -o $out -Wl,--start-group $in -Wl,--end-group
-lgmodule-2.0 $solibs $libs

**Comment by zcbenz** [comment]
Can you try adding `gmodule-2.0` to `vendor/brightray/brightray.gyp`'s `linux_system_libraries` variable?

**Comment by apm** [comment]
@zcbenz - I tried that and got the same error.

/usr/bin/ld: /home/adam/src/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libaccessibility.a(accessibility.atk_util_auralinux.o): undefined reference to symbol 'g_module_symbol'
//usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by capouch** [comment]
Did you try the manual patch to the ninja file?

**Comment by BobCochran** [comment]
@apm @capouch @zcbenz I tried Brian's manual patch and it worked for me. I apologize for not commenting on this sooner. I will check the build instructions in a couple days and if they have not been updated, I plan to do a PR.

**Comment by capouch** [comment]
@BobCochran was your binary as big as the one that resulted from the build I did?

**Comment by BobCochran** [comment]
@capouch Yes it was! 1,419,724,529 bytes. I actually talked about this on the Atom discuss thread. I am wondering if the "debug" and "release " binaries were switched accidentally? I think release may be in the debug directory: 11,014,510 bytes.

**Comment by zcbenz** [comment]
@apm Did you run `./script/update.py` after changing the line?

**Comment by capouch** [comment]
@zcbenz I'm a newbie at electron and the whole ninja build system.  I didn't know to run that.  I added the line as you indicated above, ran ~/script/update.py, and the ~/script/build.py and things DID in fact build just fine.

Could you comment on the contents of the out/R and out/D directories?  The "D" (assume Debug) version is only 11MB, but has shared object dependencies on a 88 different libraries also located in that directory.  The Release version has no such dependencies, but is 1.35+ GB.  I assume that is because links all those same libraries statically?  

Thank you for the guidance.

**Comment by zcbenz** [comment]
> @zcbenz I'm a newbie at electron and the whole ninja build system. I didn't know to run that. I added the line as you indicated above, ran ~/script/update.py, and the ~/script/build.py and things DID in fact build just fine.

Thanks for testing it, I'll add it to the build script.

> Could you comment on the contents of the out/R and out/D directories? The "D" (assume Debug) version is only 11MB, but has shared object dependencies on a 88 different libraries also located in that directory. The Release version has no such dependencies, but is 1.35+ GB. I assume that is because links all those same libraries statically?

You can find information about Electron's build system here:
https://github.com/atom/electron/blob/master/docs/development/build-system-overview.md

The binaries of Release build include debugging symbols so they can be huge. You should run `./script/create-dist.py` to create a working distribution which will be placed in `dist` directory.

**Comment by apm** [comment]
Aha, thanks.  I rebooted that machine for the first time in a while, and permissions must have reverted to the broken state.

**Comment by apm** [comment]
Thanks @zcbenz, I didn't know to run update.py

**Comment by BobCochran** [comment]
@zcbenz @capouch @apm I have forked electron to https://github.com/BobCochran/electron.git and created a new branch called linux-build-instructions-issue-1809. I've updated the linux build instructions document. You might want to review them and suggest changes to me. If you are happy with the changes I'll do a pull request. Thank you very much.

**Comment by obvio171** [comment]
Changing the line, running update.py and then build.py again did not work for me. Same error :/
