### ISSUE TITLE
Building master on Windows x64 fails half way through

### ISSUE THREAD

**Issue by frankhale** [atom/electron#1819]
Anyone else seeing this issue when building on Windows x64? It fails half way through with the following error. I've previously been able to build Electron so I'm confident my toolchain is installed correctly.

```
[474/983] CXX obj\vendor\brightray\bro...rightray.devtools_manager_delegate.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Vi
sual Studio 14.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\vendor\brig
htray\browser\brightray.devtools_manager_delegate.obj.rsp /c ..\..\vendor\bright
ray\browser\devtools_manager_delegate.cc /Foobj\vendor\brightray\browser\brightr
ay.devtools_manager_delegate.obj /Fdobj\vendor\brightray\brightray.cc.pdb
c:\users\frankdev\desktop\build\electron\vendor\brightray\browser\devtools_manag
er_delegate.cc(65): error C2248: 'scoped_ptr<net::ServerSocket,base::DefaultDele
ter<T>>::scoped_ptr': cannot access private member declared in class 'scoped_ptr
<net::ServerSocket,base::DefaultDeleter<T>>'
        with
        [
            T=net::ServerSocket
        ]
c:\users\frankdev\desktop\build\electron\vendor\brightray\vendor\download\libchr
omiumcontent\src\base\memory\scoped_ptr.h(313): note: see declaration of 'scoped
_ptr<net::ServerSocket,base::DefaultDeleter<T>>::scoped_ptr'
        with
        [
            T=net::ServerSocket
        ]
[474/983] CXX obj\vendor\brightray\bro...tray.inspectable_web_contents_impl.obj
ninja: build stopped: subcommand failed.
```

**Comment by frankhale** [comment]
Interesting 0.27.1 is also doing the same thing but it's weird because if I run the build multiple times it will fail at different points in the process with the same error as above. Maybe there is now a problem with my toolchain. I recently installed VS 2015 RC but I'm not using that. I'm using VS 2013 with the build prompt.

**Comment by frankhale** [comment]
I think it's a toolchain issue. I'm closing this. I'll report back if I ever figure out what is going on.

**Comment by frankhale** [comment]
I have another machine that was previously able to compile and now cannot but for different reasons. I'll try to sort out my issues and see if there is any common thing about them.

**Comment by frankhale** [comment]
I got my second machine squared away. Something was going wrong definitely with my toolchain. Node was screwed up some how. Uninstalling/reinstalling fixed my issue there. As for the other machine, I have no idea what is going on with it. I think I'll set up a VM to do this and then just take a snapshot once the toolchain install is installed and working nicely.

**Comment by paulcbetts** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio 14.0

You installed VS2015, but you need to be building with VS2013. Set `GYP_MSVS_VERSION=2013` as an environment variable then bootstrap the world again

**Comment by frankhale** [comment]
I only mentioned that as a side note. I've been using VS 2013. I got one of my machines to work again. One is completely hosed. I'm about to see if my third machine is able to still compile.

**Comment by frankhale** [comment]
Thanks for the tip on setting GYP_MSVS_VERSION=2013. I'm giving that a shot now.

**Comment by paulcbetts** [comment]
> I only mentioned that as a side note. I've been using VS 2013.

The problem is, if you have both installed, node-gyp will somehow always manage to pick the wrong one :-/

**Comment by frankhale** [comment]
setting GYP_MSVS_VERSION=2013 really helps and the machine I care about most is now able to compile Electron again. Thanks!

**Comment by frankhale** [comment]
Thanks @paulcbetts the GYP_MSVS_VERSION resolved for the machine that I originally posted this question for. YAY! Life is awesome again!!!
