### ISSUE TITLE
Unable to get BankingJS working

### ISSUE THREAD

**Issue by GradyD** [atom/electron#1824]
I have created an electron app, https://github.com/GradyD/finance. It sucks in BankingJS https://github.com/euforic/banking.js/. 

The problem is that when I require Banking JS I get "module did not self register". When I follow https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

Trying the easy way nothing happens and I still see the same error. 

Trying the node-gyp way. Gets me a new error "%1 is not a valid Win32 application". 
Copy/pasteing the provided commands did not work on Windows 8.1 so I ran the following. 
```
cd .\node_modules\banking
node-gyp rebuild --target=0.27.1 --arch=Win64 --dist-url=https://atom.io/download/atom-shell --msvs_version=2013 --verbose
```

I was able to run node-gyp and install this module without any issues using strait nodeJS. When I run the above command I get "Error: 'gyp' failed with exit code: 1". 

Node Version: 0.12.2
Electron-prebuilt: 0.27.1
Visual Studio 2013 Express for Desktops installed

I also tried running the commands in VS command prompt 64X as admin and ran into the same error. 

My question is what am I doing wrong that I can not rebuild the package for electron?

**Comment by paulcbetts** [comment]
`--arch=Win64` isn't valid, you want `--arch=x64`

**Comment by GradyD** [comment]
I fixed that but am still getting the error when I run npm-gyp rebuild.

I removed the folder and reinstalled the package, `npm install banking --msvs-version=2013`, and when I tried to rebuild I got the same error.

Is there a reason why the easy way wouldn't rebuild it?

**Comment by zcbenz** [comment]
Can you remove the `node_modules` and try the npm way? `banking` itself is not a native module so `node-gyp` doesn't work for it, using npm can handle the dependencies for you.

If it still doesn't work, please paste the `npm-debug.log` file.
