### ISSUE TITLE
Quick successive clicks on tray do not fire `clicked` event

### ISSUE THREAD

**Issue by davej** [atom/electron#1825]
I have only tested this on OS X. But I consistently see the same result. OS X 10.10.3, Electron 0.27.1.

[Here's a quick video demonstrating the issue](https://dl.dropboxusercontent.com/u/22748/tray-click-electron.mov) (~300KB).

```javascript
menubar.tray = new Tray(iconPath);
menubar.tray.on('clicked', function (e, bounds) {
  console.log('clicked'); // doesn't fire after quick successive clicks
});
```

**Comment by zcbenz** [comment]
You should [turn off highlight mode](https://github.com/atom/electron/blob/master/docs/api/tray.md#traysethighlightmodehighlight), otherwise OS X would try to toggle between different states during your clicks.

**Comment by davej** [comment]
@zcbenz: Thanks, I will do that. Is this not a bug though? Native apps are able to highlight the icon and still respond to clicks.

**Comment by zcbenz** [comment]
It is an expected behavior of OS X.

**Comment by davej** [comment]
Sorry for labouring the issue and thank you for replying but could you explain why it is expected behaviour?

**Comment by zcbenz** [comment]
You can write a simple Cocoa app to reproduce this behavior, no one knows the reason of it except for the Apple devs.

**Comment by davej** [comment]
@zcbenz Thanks!

Would it be possible to implement this by introducing a `stateChanged` event that listens for changes in the tray's state? This could be Mac OS X only (or it could probably be easily polyfilled on other platforms by listening for clicks and toggling the pseudo-state internally in Electron).

HighlightMode is necessary for a native feel on Mac, it would be very nice to have it.

**Comment by davej** [comment]
I have tried `tray.setHighlightMode(false)` and the issue is still there. The icon no longer highlights but it still doesn't respond to clicks in quick succession.

**Comment by zcbenz** [comment]
Your clicks might have been trapped as `double-clicked`:
https://github.com/atom/electron/blob/master/docs/api/tray.md#event-double-clicked

**Comment by davej** [comment]
That was the issue, huge thanks! I'm now performing the show/hide action on `double-click` also and it works perfectly.

Should the tray icon be trapping double-clicks if the app doesn't use them? Could Electron listen for new `double-clicked` listeners and add a double click action dynamically to the tray button, instead of always adding a double click action? Perhaps this could be done by listening for `newListener` events on the EventEmitter?

**Comment by zcbenz** [comment]
> Should the tray icon be trapping double-clicks if the app doesn't use them? Could Electron listen for new double-clicked listeners and add a double click action dynamically to the tray button, instead of always adding a double click action? Perhaps this could be done by listening for newListener events on the EventEmitter?

This behavior has been there for quite a long time, changing it would break existing apps. So no matter whether it is a good behavior or not, I think we should stick to it.

**Comment by davej** [comment]
I think the behaviour I have suggested should be backwards compatible with existing Electron apps though, I don't understand how it would break them if they're not listening for the `double-clicked` event. It's also possible to have a more explicit `Tray.setIgnoreDoubleClicks()` method but this introduces API bloat.
