### ISSUE TITLE
Best way to create/store a database?

### ISSUE THREAD

**Issue by GradyD** [atom/electron#1827]
I am building an app that will hold bank statements in a database, of some form. Each transaction will be a line item and I will add data about the transaction. 

Using electron what is the best way to create a database? Do you recommend using SQLite or is there something else I should be looking into using?

**Comment by paulcbetts** [comment]
How about Local Storage?

**Comment by GradyD** [comment]
I'm still getting up to speed on all the APIs. Is there a tutorial on local storage?

When you say local storage are you referring to using the FS module?

**Comment by baconface** [comment]
[This](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) is what he means. All baked into the browser.

**Comment by Dashed** [comment]
Since your environment is just Chrome (electron), you can do better than local storage with IndexedDB through pouchdb (browser version): https://github.com/pouchdb/pouchdb

**Comment by steelbrain** [comment]
@GradyD do me a favor a remove that `[QUESTION]` from the title, it's all caps and I get annoyed everytime I read it.

**Comment by GradyD** [comment]
Thanks for the feedback guys! I have a better handle on how to go about this. I will probably use pouchDB since it appears to have the easiest API to get off the ground quickly.

Thanks again!

**Comment by frankhale** [comment]
There are a lot of database options. Here is one NeDB https://github.com/louischatriot/nedb

**Comment by baconface** [comment]
I would also use something other than LocalStorage for your case. Unsure what limitations Electron imposes or lifts on it but I know in web development it has roughly a 5mb cap in most browsers. And you can only query by key name. There are some libraries online to improve on this but it would make sense to use something that naturally has the functionality. If you are saving, say, application options LocalStorage is a great option.

**Comment by GradyD** [comment]
I would estimate that we would be dealing with file sizes at 50mb and up from what I have seen so far.

I like the idea of using SQLite for the SQL aspects but I haven't quite figured out how I would save that into AppData. We are already using the FS module and app data for a config file, probably move this into local storage.

**Comment by baconface** [comment]
If you are saving configuration to a file then you are fine. No need to switch that to LocalStorage unless you absolutely wanted to.

As far as SQLite goes. If that is what you are comfortable with then roll with it. If you are looking for a good way to implement it with Electron [this](https://github.com/kripken/sql.js) should get you there.

**Comment by bansalvks** [comment]
local storage is loosing its values when closing the window. Is there something that I need to do to make it persistent? I am using **localStorage** from my angular app services.


```

myAppServices.service('localStorageService', [function () {

	/// userdetails
	this.setUserDetailsGoogle = function (userDetailsGoogle) {

		if (userDetailsGoogle === undefined) {
			return false
		}

		localStorage.userDetailsGoogle = JSON.stringify(userDetailsGoogle);
		return true;
	};

	this.getUserDetailsGoogle = function () {
		if (localStorage.userDetailsGoogle === undefined) {
			return null;
		}

		return JSON.parse(localStorage.userDetailsGoogle);
	};


	/// googleauth details
	this.setOauthDetailsGoogle = function (oauthDetailsGoogle) {

		if (oauthDetailsGoogle === undefined) {
			return false;
		}

		localStorage.oauthDetailsGoogle = JSON.stringify(oauthDetailsGoogle);
		return true;
	}

	this.getOauthDetailsGoogle = function () {
		if (localStorage.oauthDetailsGoogle === undefined) {
			return null;
		}

		return JSON.parse(localStorage.oauthDetailsGoogle);
	};

	return this;
}]);
```

**Comment by Deltaspectro** [comment]
hi friend, use toggle developer tools, you are websql and other options  ;)

**Comment by danielsun174** [comment]
You should also try [RxDB](https://github.com/pubkey/rxdb) which is based on the previous mentioned pouchdb.

**Comment by four-eyes-04-04** [comment]
Hi, I am currently having the same issue, I want to use something like sqlite, but so far the most promising module I have seen is [sqlite3](https://github.com/mapbox/node-sqlite3) and [sequelize](https://github.com/sequelize/sequelize) (which uses sqlite3) but I am having [trouble integrating them into electron](https://github.com/mapbox/node-sqlite3/issues/838).

I'm Glad I saw this, I will look into [RxDB](https://github.com/pubkey/rxdb).

**Comment by ssimo3lsuhsc** [comment]
I'm in need of a database for a small app whose raison d'etre is modifying the data in the database. I would like one contained in a single file if possible. The users of my app will e-mail their database files back to me when finished. I will then run further tests by running queries across all the individual versions of the database file. I have tried node-sqlite, and it is full of errors even for NW.js at this point. SQL.js looks promising, but I'm not looking forward to asking people to have the extra step of saving their database file every time they close the app. I like the idea that the changes will be persisted back to this database in a live fashion. And preferably, I would like no beta software: please look at the version number and make sure it is greater than or equal to 1 before recommending anything.

**Comment by IranCanul** [comment]
What about Mysql?
