### ISSUE TITLE
Using Google drive API

### ISSUE THREAD

**Issue by benrs** [atom/electron#1828]
I've been trying to implement Google's drive API with electron for the past few hours but I seem to have hit a bug which is stopping me from moving forward. I am currently following this google guide:

https://developers.google.com/drive/web/auth/web-client

to handle authorization requests. The problem is google seems to load iframes (asynchronously) onto the webpage and I get this following error:

```
Refused to display '[link]' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'
```

I have been reading around and the problem lies in the fact that google's iframe has it's X-Frame-Options header set to SAMEORIGIN. I am also new to electron so I could potentially be doing something wrong and if I am please point it out. If not then is there a potential solution to this problem? Also let me know if you need more details.

**Comment by zcbenz** [comment]
It looks quite reasonable to throw the error if the script tries to load iframe with `X-Frame-Options` in a local page?

I think you may try to make google drive API work in a normal Chrome and then run it in Electron. I'm closing this unless you can provide an example that can run in Chrome browser but not in Electron, you can also look for help in the [forum](https://discuss.atom.io/c/electron) or [Slack](https://discuss.atom.io/t/join-us-on-slack/16638).
