### ISSUE TITLE
Building the app using electron for distribution.

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#1829]
In the past to build the app for distribution I have downloaded a binary and then copied my app folder into the Resources folder and then renamed a few things.

With the rename of atom shell to Electron it says I can use electron /my-application via the NPM electron-prebuilt module. However when testing this, all I can do is run the app, not actually build it.

Does this mean in order to build the app, you still need to download the actual binary in the releases?

I looked at https://github.com/paulcbetts/grunt-build-atom-shell but this doesn't seem to have been updated for Electron and all it seems to do for me is create a folder of the atom shell source and doesn't actually create the compile atom.exe / atom.app or (electron.exe).

The docs are a little vague on this, what's the easiest way to take an app folder and then have it be compiled into a ready to send Atom/Electron application.

**Comment by sindresorhus** [comment]
You can use [`electron-packager`](https://github.com/maxogden/electron-packager) to build your app.

**Comment by paulcbetts** [comment]
^^ what @sindresorhus said, unless you need to run custom builds (i.e. non-released) versions of Electron, `electron-prebuilt` is a better idea

**Comment by zcbenz** [comment]
Closing since it has been answered.
