### ISSUE TITLE
Linux Build Instructions Need To List Expected Python Version

### ISSUE THREAD

**Issue by BobCochran** [atom/electron#1830]
In https://github.com/atom/electron/blob/master/docs/development/build-instructions-linux.md

Under Prerequisites, the Python version ought to be listed. I am under the impression that the bootstrap script at script/bootstrap.py has a hard requirement for Python 2.7 because of this:

`AttributeError: ZipFile instance has no attribute '__exit__'`

Thanks

**Comment by paulcbetts** [comment]
Yep, it does - send a PR?
