### ISSUE TITLE
Mac OS yosemite WebView not work on 0.27.1

### ISSUE THREAD

**Issue by TomomiSawako** [atom/electron#1831]
```
  webView = $ "<webview class='web-view' nodeintegration></webview>"
  app.view.append webView
```

It's doesn't work on 0.27.1, no anythings show, but still loading.
My prebuilt is 0.26.1, it's works

**Comment by Tedko** [comment]
![2015-05-31 11 49 40](https://cloud.githubusercontent.com/assets/6687437/7902600/220fc77c-07f1-11e5-8331-99a964cc605b.png)
![2015-05-31 11 52 52](https://cloud.githubusercontent.com/assets/6687437/7902603/2bab8aa0-07f1-11e5-86c4-a3d257340574.png)

**Comment by Tedko** [comment]
#1816

**Comment by Tedko** [comment]
@zcbenz

**Comment by frankhale** [comment]
This is resolved in master see issue: https://github.com/atom/electron/issues/1816

**Comment by frankhale** [comment]
If you have the capability you can compile master. I've verified webview is working in my app by doing this. Or you can wait until next week when a new version is published.

**Comment by TomomiSawako** [comment]
thanks, i'll wait next week, or use 26.1 to release my game.

**Comment by frankhale** [comment]
0.27.2 was just released with the webview fix. Thank you @zcbenz !!!!
