### ISSUE TITLE
<webview> clear cache

### ISSUE THREAD

**Issue by thyrrestrup** [atom/electron#1832]
Is it possible to clear webview cache including cookies and localStorage?
nw.js has a `App.clearCache()` feature - can this be implemented in Electron?

**Comment by deepak1556** [comment]
nw.js `clearCache` will clear only http disk cache, DOMStorage and cookie monsters needs to handled separately not affected by disk cache. So what feature is requested here, `<webview>.clearDiskCache` or api to destroy everything ?

**Comment by thyrrestrup** [comment]
I believe it clears both disk cache and memory [link](https://github.com/nwjs/nw.js/blob/757cfcb1ebdec803fec30059e3b9ff189d1847c7/CHANGELOG.md#060--06-17-2013-)
But I would be interested in the clear memory behaviour if not both.

**Comment by deepak1556** [comment]
yup disk cache contains only http transaction related stuff (headers, response etc) and yeah they will get cleared with that method not cookies and localstorage data. Just wanted to confirm if your need was to clear only the transaction data or everything, thanks.

**Comment by thyrrestrup** [comment]
I see - sorry for the misunderstanding on my part.
What I need is a way to clear cookies and local storage while the application runs.
It could be when creating a new webview or while the webview is running is that possible?

**Comment by deepak1556** [comment]
yup, #959  needs to be done before this.

**Comment by ChangMM** [comment]
Help!!! I want to know if we can get the cookies of webview!!

**Comment by sajeeldigitali** [comment]
> Help!!! I want to know if we can get the cookies of webview!!

Yes, we can
using Session module from electron in the main process
`const { session } = require('electron');`
`const result = await session.defaultSession.cookies.get({ url: url });
`
`return result;`

you can communicate with main process from your renderer process where webview is defined
