### ISSUE TITLE
Node scope not reset on webview remove from dom.

### ISSUE THREAD

**Issue by TomomiSawako** [atom/electron#1840]
I just require a module(like util) both BrowserWindow's page and webview's page.
And this module save a variable, so this two page could share data.
But when i remove this webview, change data, and recreate webview, this data is not change.
I know maybe this bug is "Webview's page require a module and this module still have data." or "Webview removed but something still here."

**Comment by steelbrain** [comment]
I would love to see a minimal repro example

**Comment by zcbenz** [comment]
I can not reproduce according to your descriptions, please provide a reproducible example for this.
