### ISSUE TITLE
DevTools source maps behaving oddly

### ISSUE THREAD

**Issue by mattdesl** [atom/electron#1842]
Running a file through browserify using [wzrd](https://github.com/maxogden/wzrd/) to serve the content on `localhost:9966`.

```sh
wzrd index.js -- -d
```

This works fine in regular Chrome DevTools. However, opening `http://localhost:9966/` in Electron and viewing its DevTools is not working with source maps. (They are enabled in the DevTools options).

![screen shot 2015-06-01 at 4 44 19 pm](https://cloud.githubusercontent.com/assets/1383811/7922933/8f434a26-087d-11e5-9460-67eadadf8165.png)

Is there a particular switch that needs to be set, or is this just not supported in Electron? Or maybe a bug? Couldn't find much after googling and searching through issues.

Cheers. :beer:

**Comment by zcbenz** [comment]
Can you provide a sample app? It is not easy to setup a working page with source maps.

**Comment by mattdesl** [comment]
Thanks @zcbenz, here's a sample app to run that uses browserify to create inlined source maps. 

https://github.com/mattdesl/test-electron-source-maps

**Comment by tengyifei** [comment]
I encountered the same problem with CSS source maps. Also the `Add folders to workspace` option is not working in Electron, ruling out the possibility of manually assigning a source map.

**Comment by paulcbetts** [comment]
Once I get the damn thing working, https://github.com/paulcbetts/electron-compile will make this much easier

**Comment by mattdesl** [comment]
In my case I'd actually like to keep the transpiling/etc in browserify and outside of Electron. See my use case here: 
https://github.com/Jam3/hihat
