### ISSUE TITLE
Webview preload script not surviving webview src change

### ISSUE THREAD

**Issue by frankhale** [atom/electron#1843]
I stated 0.27.2 in the issue topic but for me it broke after 0.23. I need a sanity check here. I'm doing a very basic ping/pong type IPC with my applications main window and a webview. This works perfectly fine for me on version 0.23.0 but breaks at 0.24.0 and all the way up to today with 0.27.2. I've looked at the dev tools for the webview and I can tell that my preload script is running but doing any IPC sends never makes it to the webview.

**Same code works fine in 0.23.0 and breaks in 0.24 -> 0.27.2.**

I'm doing exactly the same very basic IPC as listed in:

https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#ipc-message

```javascript
// In embedder page.
webview.addEventListener('ipc-message', function(event) {
  console.log(event.channel);
  // Prints "pong"
});
webview.send('ping');

.....

// In guest page.
var ipc = require('ipc');
ipc.on('ping', function() {
  ipc.sendToHost('pong');
})
```

Is anyone else having issues with IPC in webviews?

**Comment by frankhale** [comment]
I'll work on making a small reproducible example and link it here.

**Comment by paulcbetts** [comment]
This is working for us in the Slack app, but one thing we've always had to do is patch the `process` variable back in via `process.nextTick`

**Comment by frankhale** [comment]
Thanks for that! I was able to get a small sample running with a basic ping/pong. I think my problem is that when setting the src of the webview IPC doesn't respond. This is my theory at the moment, I'm going to try my little test app to see if IPC survives after changing src.

**Comment by frankhale** [comment]
Yep, after src is changed IPC stops working. Or rather the code that was set in my preload is no longer there to run.

**Comment by frankhale** [comment]
Here is a small example to demonstrate the behavior. 

https://github.com/frankhale/electron-webview-ipc-test

**Comment by frankhale** [comment]
The following issue may also be related: https://github.com/atom/electron/issues/1823

**Comment by frankhale** [comment]
I am not using nodeintegration in my particular case. The interesting bit is that changing src is blowing things up. I'm looking into the code now to see if I can see anything that may have changed with webview.

**Comment by frankhale** [comment]
Another possible related issue: https://github.com/atom/electron/issues/1820

**Comment by frankhale** [comment]
And another one (dang!) https://github.com/atom/electron/issues/1754

**Comment by frankhale** [comment]
Thank you!!

**Comment by steem** [comment]
@frankhale Have you tried the latest release binaries(electron v0.27.3)? I found that it preload attribute still doesn't work properly. 
Here are the steps:
1. Create a webview html element, the src is 'about:blank'. Then change the src to a url. It works.
2. Create a new webview html element again, the src is 'about:blank'. Then change the src to the url of step1. It doesn't work.
3. Create a new webview html element again, the src is 'about:blank'. Then change the src to a new url(not same with step1). It doesn't work.

Also, I have tried those steps:
1. Create a webview html element, the src is a url. It works.
2. Create a new webview html element, the src is same with step 1. It doesn't work.
3. Create a new webview html element, the src is not same with step 1. It doesn't work.

@zcbenz Please help to check the steps when you are available.

Thanks!

**Comment by steem** [comment]
@zcbenz After I tried more, I found that if you change the src to different site(in other words, different domain), it works. And then, if I change the src to the page in the site again, it doesn't work.

**Comment by frankhale** [comment]
@steem, I haven't tried 0.27.3 yet but I did compile from master and was using the fix. I have not seen any weird issues with preload with patch #1850 because I am only creating one webview and reusing it for my entire application life cycle. It seems to work fine for me in that particular case.

**Comment by steem** [comment]
@frankhale @zcbenz I have tried one webview today, still doesn't work after changing the src two times(note: the src is same). I also have tried reload method, it only works at the first time.
My test js code is very simple: 

```javascript
var site_count = 0;
function preload_test() {
    console.log('----------------: ' + site_count.toString());
    ++site_count;
}
setInterval(preload_test, 3000);

Using 'console-message' event to echo the message.

**Comment by zcbenz** [comment]
@steem Changing src to the same value will be ignored, if you want a refresh you should call `reload`.

**Comment by steem** [comment]
@zcbenz Yes, I use reload, but still doesn't work :(

**Comment by zcbenz** [comment]
Can you provide an example? Following code works for me:

/tmp/test.js:
```js
require('ipc').sendToHost('test');
```

In devtools:
```js
var w = new WebView;
w.setAttribute('preload', 'file:///tmp/test.js');
w.addEventListener('ipc-message', function(event) {
  console.log(event.channel);
});
w.src = 'http://google.com';
document.body.appendChild(w);
```

**Comment by steem** [comment]
@zcbenz Here is the sample code:

HTML:

```
<html>
    <head>
        <meta charset="utf-8">
        <title>Test</title>
    </head>
    <body>
      <input type="button" id="test_refresh" value="refresh"><br>
      <input type="button" id="test_change_src" value="change src">&nbsp;<input type="text" id="new_url" value=""><br>
      <script src="js/deps/jquery-2.0.3.min.js"></script>
      <script>
      function create_web_view (id, url) {
        $(document.body).append('<webview autosize="on" id="' + id + '" src="' + url + '"  preload="op/op_min.js" plugins></webview>');
      }
      create_web_view('test1', 'http://www.baidu.com');
      $('#test_change_src').click(function(){
        document.getElementById('test1').src = $('#new_url').val();
      });
      $('#test_refresh').click(function(){
        document.getElementById('test1').reload();
      });
      document.getElementById('test1').addEventListener('console-message', function(e) {
        console.log('webview message: ' + e.message);
      });
      </script>
    </body>
</html>
```

op_min.js

```
var site_count = 0;
function preload_test() {
    console.log('----------------: ' + site_count);
    ++site_count;
}
setInterval(preload_test, 3000);
```

If you click the refresh button, the op_min.js only works at the first two click.

**Comment by steem** [comment]
@zcbenz I debug the code and find that the it may be caused by v8 engine. The first call of reload will cause the AtomBrowserClient::AtomBrowserClient be called. But if you call reload again, AtomBrowserClient::AtomBrowserClient won't be called. WebContents::LoadURL will be called each time when calling reload.
The v8 code is libchromiumcontent, where can I get the code and build it?

**Comment by steem** [comment]
@zcbenz @frankhale Finally, I found that it's caused by the following line:
app.commandLine.appendSwitch('process-per-site');

After I delete it, it works. If not, after calling reload one time, it doesn't work. Even if you create a new webview, and initialize the src to any page of a website, it doesn't work after one time.

So, libchromiumcontent may not call AtomBrowserClient::AppendExtraCommandLineSwitches if in 'process-per-site' mode in some cases. Currently, I don't have time to debug libchromiumcontent. @zcbenz , if you are available, please help to check it.

Thanks!

**Comment by zcbenz** [comment]
@steem Thanks for debugging this! Sorry I didn't have time to look into it.

In Electron every page is forced to use its own process, which is necessary for the node integration support, so if you pass `process-per-site` to Chromium some pages will then be forced to share the same process, and node integration won't work for them.

**Comment by frozeman** [comment]
I'm on 0.26.0 and as soon as i change the src, or navigate to another domain, i loos the preloaded script.
Is this issue not yet in 0.26.0 resolved?

**Comment by steem** [comment]
@zcbenz Ok, I see.

Chromium process model won't create new process if the max process number is reached. Just worry about that whether the issue may come up when the max process number is reached.

**Comment by frozeman** [comment]
The problem still persists for me at 0.26.0.

**Comment by frozeman** [comment]
works on 0.28.0 :+1:

**Comment by mschnee** [comment]
This bug appears to have returned as of 0.31.2

Example project here: 
https://github.com/mschnee/electron-bug-example

**Comment by zcbenz** [comment]
@mschnee Which operating system are you using? And can you reproduce on 0.32.0?

**Comment by mschnee** [comment]
@zcbenz Verified as working in electron-prebuilt@0.32.1 on Windows 10, OSX 10.10, and Linux (gentoo x64, vanilla kernel 4.2)

Apologies for necro'ing a bug, looks like you beat me to it!
