### ISSUE TITLE
Way to override context menu in taskbar?

### ISSUE THREAD

**Issue by somebody32** [atom/electron#1845]
Hi!

Is there a way to override a context menu in taskbar for Windows? Or just to rename `Electron` to `My app name`?

![screenshot 2015-06-02 16 19 15](https://cloud.githubusercontent.com/assets/25742/7937987/5a66429c-0943-11e5-8394-5a3e0cd8583d.png)

Adding main menu to the app or adding `Tray` icon with a menu did not help

**Comment by vedatyilmaz** [comment]
+1

it open default Electron window..

**Comment by zcbenz** [comment]
There is a guide on this:
https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md

**Comment by somebody32** [comment]
@zcbenz I've read this guide a couple of times before opening this issue, but still have no idea how to remove/change `Electron` menu item from my screenshot.

I've tried adding global menu to app or adding Tray icon, but this makes no difference. Adding custom tasks does not solve the issue too. So, what is the right way to change this?

**Comment by vaughnroyko** [comment]
@zcbenz @somebody32 Was anything ever figured out for this? Still looking for a solution. 

https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md provides no insight.

**Comment by enlight** [comment]
Rebranding is mentioned at https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md#rebranding-with-downloaded-binaries

**Comment by alex1701c** [comment]
Is there a way to just remove this one entry?
