### ISSUE TITLE
Cookie headers are received but not shown in devtools when using 'http'

### ISSUE THREAD

**Issue by yoshuawuyts** [atom/electron#1852]
@zcbenz do you know if `electron` blocks the `Set-Cookie` header by default? Responses that carry this in the browser don't seem to have it in `electron`.

I read through the source, couldn't find any code that would point to that, but checking just in case this is true. Possibly related / of use to https://github.com/atom/electron/issues/1606.

**Comment by yoshuawuyts** [comment]
I've created a repro for this: https://github.com/yoshuawuyts/electron-cookie-issues-repro.

It appears `electron` is indeed blocking cookie related headers.

# electron blocks cookie headers by default
Using `OSX@10.10.2` and `electron@0.27.2` pulled in through `electron-prebuilt`.

## Steps to reproduce ([repro](https://github.com/yoshuawuyts/electron-cookie-issues-repro))
- setup electron to load an `index.html` that loads `client.js`
- perform an XHR request from `client.js` to a `server.js` that sets the `Set-Cookie` header

## Actual results
- no cookie headers are received

## Expected results
- cookie headers are received
- cookies are not stored ([`electron-cookies`](https://www.npmjs.com/package/electron-cookies) provides a workaround)

## Screenshots
### electron
![screen shot 2015-06-04 at 11 37 40](https://cloud.githubusercontent.com/assets/2467194/7981585/35cd1bb8-0ab0-11e5-8cce-79e0430bb578.png)

### chrome
![screen shot 2015-06-04 at 11 53 13](https://cloud.githubusercontent.com/assets/2467194/7981602/5751a2cc-0ab0-11e5-8a84-c151fd60157b.png)

**Comment by hokein** [comment]
Thanks for the detailed information. I can say that the `Set-Cookie` header is actually worked. You can view `Cookies` in `Resources` panel of dev-tool, then you will find the cookies.

I have no much idea about why dev-tools doesn't show the cookies header here, it might be a bug of dev-tools.

**Comment by yoshuawuyts** [comment]
@hokein I'm not seeing any cookies in there, both with `electron-cookies` enabled and disabled. 

![screen shot 2015-06-04 at 15 14 45](https://cloud.githubusercontent.com/assets/2467194/7984872/8722778a-0acc-11e5-836c-d7626661f91e.png)

**Comment by hokein** [comment]
Looks like you are loading the local file, are you sure you have sent the correct header?

In your reproduced repo, it actually works, see:

![image](https://cloud.githubusercontent.com/assets/2557445/7997583/0b97901e-0b62-11e5-8720-f9939819e9db.png)

**Comment by yoshuawuyts** [comment]
You were right, it was a header issue. Incidentally `window.fetch` doesn't support cookies so I had went with the `nets` module instead. The `cookie` headers not showing up in the request window is still a bug though, so I'll be updating the issue to only reflect that. Thanks for coming back to me so fast & helping me resolve my issues. :tada:

**Comment by yoshuawuyts** [comment]
Update: due to https://github.com/atom/electron/issues/1574 `nets` uses `request` under the hood, rather than `xhr`. When using `xhr` (e.g. `XMLHTTPRequest`) everything related to cookies is blocked and cannot be set. In the repro just require `xhr` instead:
```js
const nets = require('xhr')
```
