### ISSUE TITLE
dialog.showSaveDialog default filename for files that do not exist.

### ISSUE THREAD

**Issue by DavidVorick** [atom/electron#1855]
This is related to #1541 

I am using Linux 64bit, electron, version 0.26.1.

dialog.showSaveDialog cannot be passed a filename for a file that does not exist yet. This seems strange, as typically if you are saving/downloading a file using a file picker, it's because you don't have the file yet.

The call I was using:

```
var downloadPath = dialog.showSaveDialog({defaultPath: filename});
event.returnValue = downloadPath ? downloadPath : null;
```

**Comment by hokein** [comment]
It's a bug on Linux. The API can show default filename on Windows and OS X.

**Comment by DavidVorick** [comment]
Sorry if it's bad form to bump a closed issue, but I wanted to say thanks for getting to this so quickly. I've been really impressed with the development rate of Electron.
