### ISSUE TITLE
Link to Application distribution is 404

### ISSUE THREAD

**Issue by cfjedimaster** [atom/electron#1856]
On the quick start guide (http://electron.atom.io/docs/v0.27.0/tutorial/quick-start/), the link to Application distribution goes to a 404.

**Comment by hokein** [comment]
This is a issue on https://github.com/atom/electron.atom.io repo.

**Comment by kevinsawicki** [comment]
@jlord looks like the `Application distribution` link on that page goes to http://electron.atom.io/docs/v0.27.0/tutorial/quick-start/application-distribution.md instead of http://electron.atom.io/docs/v0.27.0/tutorial/application-distribution

**Comment by kevinsawicki** [comment]
Moving over to the site repository, https://github.com/atom/electron.atom.io/issues/37
