### ISSUE TITLE
Built-in address bar option

### ISSUE THREAD

**Issue by twolfson** [atom/electron#1862]
I recently wrote a wrapper app for Google Music via Electron. It works great except Google Music's website expects the user to be in a full-fledged browser with forward/back support to navigate between pages.

https://github.com/twolfson/google-music-electron

I was hoping that Electron would have built-in support as with `nw.js` (`toolbar` option in its manifest). However, when searching I could only find a single issue on the Disqus board that has fallen to deaf ears:

https://github.com/nwjs/nw.js/wiki/Manifest-format#toolbar

https://discuss.atom.io/t/is-it-possible-to-start-electron-with-an-address-bar/16393

To make sure this issue is more easily discovered by future me's, I am opening the issue in GitHub where the search is better integrated with the repo itself.

Would it be possible to provide an option to include the default browser address bar (e.g. forward/back/input box with HTTPS indicator and progress loading)?

**Comment by steelbrain** [comment]
I had thought of the same thing a few months ago, ended up creating https://github.com/steelbrain/Brauser

**Comment by twolfson** [comment]
Ah, they definitely would work as a starting point. It took me a bit of time to understand what it was/how I would use it. I imagine that I would use it similar to a boilerplate for my needs.

I feel that requiring `polymer` might be overkill for my needs. I have a feeling Chrome's navigation is all HTML/CSS (similar to how dev tools is all HTML/CSS) which is why I want feedback from the Electron team =/

**Comment by zcbenz** [comment]
You can use `<webview>` tag to simulate a browser in your app if you need an address bar. We don't have plan to implement this because it increases complexity a lot while benefits few people, most apps are pure JavaScript based and never do navigations so address bar is useless under most cases.

**Comment by Tribex** [comment]
Perhaps default_app could have a basic set of browser controls? (I'm entirely neutral on the idea of a toolbar.)

**Comment by twolfson** [comment]
@zcbenz Ah, k. Thank you for clarifying the current stance on the topic; I had a feeling that would be the case but wanted to make sure. Do you happen to know off hand if there is an address bar in Chromium? If so, can you link me to the code so I don't have to dig around for it?

**Comment by cuixiping** [comment]
You can use these apis to implement your Back/Forward functions:

[contents.canGoBack()](http://electron.atom.io/docs/api/web-contents/#contentscangoback)
[contents.goBack()](http://electron.atom.io/docs/api/web-contents/#contentsgoback)
[contents.canGoForward()](http://electron.atom.io/docs/api/web-contents/#contentscangoforward)
[contents.goForward()](http://electron.atom.io/docs/api/web-contents/#contentsgoforward)

**Comment by rolland-history** [comment]
@see https://www.electronjs.org/docs/api/browser-view
