### ISSUE TITLE
How to open new .html page from <a> tag

### ISSUE THREAD

**Issue by lhalver1** [atom/electron#1869]
I have an `<ul>` full of `<a>` tags and one of the tags is supposed to open a new .html page. What is the best way to do that in electron?

**Comment by steelbrain** [comment]
Please do explain. Your question was **very** confusing.

**Comment by zcbenz** [comment]
Probably the [new-window event](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-new-window).
