### ISSUE TITLE
BrowserWindow can't load url with `localhost`

### ISSUE THREAD

**Issue by hokein** [atom/electron#1870]
Currently, `BrowserWindow.loadUrl` can't handle `http://localhost:<port>` correctly(But `http://127.0.0.1:<port>` works fine). 

A screenshot:
![image](https://cloud.githubusercontent.com/assets/2557445/7997627/dd6a11e8-0b62-11e5-9974-70cc9115d98e.png)

**Comment by hokein** [comment]
I just figure out the reason. It's my network proxy program caused.

**Comment by rx4hvn** [comment]
@hokein how did you use that http:// instead of file:///

**Comment by Arnoldnuo** [comment]
@hokein I meet the same problem, but I don't have a network proxy program to cause this, can you tell me the detail of how you solve the problem.

**Comment by hokein** [comment]
@Arnoldnuo 
You could use [`--log-net-logpath`](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--log-net-logpath) command-line switch to see the details in your net trace.
