### ISSUE TITLE
dev-tools source maps not working 0.27.x

### ISSUE THREAD

**Issue by stumitchell** [atom/electron#1872]
Hi it seems that the chrome dev tools in 0.27.x do not see source maps 

I am programming with clojurescript and when I use the chrome dev-tools on in 0.26.1 I can see both the `.js` files and the `.cljs` files.

In 0.27.0 and 0.27.2 I only can see the `.js` files

**Comment by zcbenz** [comment]
This is a duplicate of #1842 and has been fixed, the fix will be shipped in next release.

**Comment by stumitchell** [comment]
Thx

**Comment by Dashed** [comment]
:+1:  Thanks @zcbenz!
