### ISSUE TITLE
native_window.h compile error.

### ISSUE THREAD

**Issue by thyrrestrup** [atom/electron#1875]
line 326 - only virtual member functions can be marked 'override'..
line 327 - only virtual member functions can be marked 'override'..
[link](https://github.com/atom/electron/blob/master/atom/browser/native_window.h#L326-L327)

**Comment by zcbenz** [comment]
The master branch should work now. It is usually recommended to build a specified tag instead of the master branch since the master branch is very likely to break building or have bugs.
