### ISSUE TITLE
Hiding the title bar

### ISSUE THREAD

**Issue by erusev** [atom/electron#1876]
We are building a text editor. The interface consists of a simple blank page. In order to make the interface even simpler, we would like for the title bar to disappear as soon users start typing (see https://ia.net/content/writer/features/writing-experience/mac.gif).

We were wondering if electron would allow us to do something like this.

**Comment by sprintr** [comment]
[Frameless Window](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md) can be used to remove the entire chrome of the window. So far it is not possible to remove it in the renderer process.

**Comment by sbruchmann** [comment]
I’m using a frameless window in combination with [titlebar](https://github.com/kapetan/titlebar) and hide the titlebar via CSS. Unfortunately, this works only for Yosemite as it is the only OS that is supported by `titlebar`.

Would love to see a native way.

**Comment by erusev** [comment]
Frameless Window seems to work great, thanks!

**Comment by hokein** [comment]
I close this issue since Frameless Window is a kind of solution.

**Comment by maddes** [comment]
This is not working, at least not on El Capitan (10.11.3). Neither the frameless window nor the [hidden alternative](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#alternatives-on-os-x)

[Here's a picture](http://stackoverflow.com/questions/35399378/how-can-i-remove-use-the-header-bar-with-photonkit/35399454#35399454) using a simple photonkit.com starter app.

**Comment by maddes** [comment]
Ups, my problem. I had two initialisation script on the Electron app.
