### ISSUE TITLE
Docs on Selenium/WebDriver do not mention specifying an 'app' directory

### ISSUE THREAD

**Issue by timruffles** [atom/electron#1877]
The [docs](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md) show you how to load external sites with Electron which seems of limited use.

Ideally you'd be able to load Electron with a specified app folder (e.g point the standalone Electron bin at an app you'd like to test) so you can functional test both the main and renderer processes.

**Comment by zcbenz** [comment]
I don't think you can use selenium to test the main process, it is designed to test the web pages.

**Comment by timruffles** [comment]
As I said *functional* test. Imagine you have a main process which exposes a method over `ipc`. If we could start Electron pointed at the `app` folder, it would start up the main process so we can test the renderer's (the 'web pages') interaction with the main process.

**Comment by zcbenz** [comment]
I got it now, you have to [put your app in Electron](https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md) to be able to use Selenium to test it. There should be a way to use Selenium without that, but I'm not familiar with Selenium.

**Comment by AlicanC** [comment]
Sadly, copying (syncing or whatever-ing) my application's source to a directory with Electron every time I change something is pretty lame.

I tried passing my source directory as an argument to Electron by using `desiredCapabilities.chromeOptions.args`:
```javascript
import assert from 'assert';
import webdriver from 'selenium-webdriver';
import electronPrebuilt from 'electron-prebuilt';
import path from 'path';
import webdriverio from 'webdriverio';

const options = {
  'host': 'localhost',
  'port': 9515,
  'desiredCapabilities': {
    'browserName': 'chrome',
    'chromeOptions': {
      'binary': electronPrebuilt,
      'args': [path.resolve('./src')]
    }
  }
};

const client = webdriverio.remote(options);
```

When you do this, what happens is not:
`electron.exe path/to/stuff`
but sadly is:
`electron.exe --path/to/stuff`
since whatever responsible for passing the arguments appends them with "--".

If Electron supported something like "--app=path/to/app", then we could make this work.

**Comment by timruffles** [comment]
Not sure if it works, but you could try symlinking. Then no manual copying required.

**Comment by AlicanC** [comment]
There are many possible workarounds. I'm looking for a real solution which looks like modifying `resources/default_app/main.js` to support `--app=path/to/app`.

The process could be made a lot more user friendly by making a very simple change on Electron.

**Comment by etiktin** [comment]
@AlicanC, you can open a PR that adds this to the default_app.

**Comment by janwiemers** [comment]
Hey there, just to let you know, I ran into the same problem so I created a pullrequest #3025

**Comment by AlicanC** [comment]
@janwiemers, thanks for the PR. I didn't really have the time for it.

**Comment by janwiemers** [comment]
Hey all this Issue is done with the merge of #3025

**Comment by Mingling94** [comment]
Hey all, can anyone see why my output doesn't get logged? I start chromedriver like the docs say and I execute the following file
`node test/test.js`
```js
const Path = require('path');
var webdriverio = require('webdriverio');
var childProcess = require('child_process');
var binPath = chromedriver.path;

// Start webdriverio
var client = webdriverio.remote({
	host: "localhost", // Use localhost as chrome driver server
	port: 9515,        // "9515" is the port opened by chrome driver.
	desiredCapabilities: {
		browserName: 'chrome',
		chromeOptions: {
			binary: Path.join(__dirname, '../node_modules/.bin/electron'), 
			args: ['app=' + Path.join(__dirname, '..')],
		}
	}
});

client
	.init().then(function() {
		console.log('reached');
	})
	.getTitle().then(function(title) {
		console.log('Title was: ' + title);
	})
	.end().then(function() {
		console.log('reached');
	});
```
