### ISSUE TITLE
Custom protocol doesn't set host, hostname and origin

### ISSUE THREAD

**Issue by frozeman** [atom/electron#1879]
Using a custom protocol handler the `window.location` object doesn't contain the `host`, `hostname` or `origin` and therefore they all share the same local storage.

Example
```js
// http://

document = {
  "origin": "http://localhost:3000",
  "hash": "",
  "search": "",
  "pathname": "/",
  "port": "3000",
  "hostname": "localhost",
  "host": "localhost:3000",
  "protocol": "http:",
  "href": "http://localhost:3000/"
}


// myprotocol://

document = {
  "origin": "myprotocol://",
  "hash": "",
  "search": "",
  "pathname": "//my.domain",
  "port": "",
  "hostname": "",
  "host": "",
  "protocol": "myprotocol:",
  "href": "myprotocol://my.domain"
}
```

This might be as it bases custom protocol handlers on the file protocol.
Is there a way to set the host to enforce separate local storages?

**Comment by frozeman** [comment]
Any comment? Its for us (ethereum.org) quite an important feature, as local storage is the only real way to store data client side and we would like to have our custom protocol handlers..

**Comment by steelbrain** [comment]
It doesn't set any cookies either.
cc @deepak1556

**Comment by deepak1556** [comment]
@frozeman i am running a custom protocol with a file job and `window.location.origin` does get set. A little more insight on how you are using the custom protocol would help, thanks.
![screen shot 2015-06-08 at 10 42 36 pm](https://cloud.githubusercontent.com/assets/964386/8040708/2babe0d2-0e30-11e5-97ff-409ddd797a91.png)

**Comment by frozeman** [comment]
Yes it sets the origin with the protocol but not the host name, so all hosts on the same protocol share the same local storage.

e.g. `library://my.lib` would share the same local storage as  `library://another.lib`

**Comment by frozeman** [comment]
Ps. i updated the example in the first comment, to show the differences

**Comment by deepak1556** [comment]
Yeah the host and port parameter being empty is because of the file protocol job. Would have been nice if embedders where allowed to override DOMStorage [identifier](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/dom_storage/dom_storage_area.cc&sq=package:chromium&l=78) method. Any reason to not use indexdb ?

**Comment by frozeman** [comment]
The main reason is that dapps ([ethereums](http://ethereum.org) decentralised apps) running in our custom browser "mist", will also be able to simple run in any other browser and therefore can only rely on local storage, and its important that every dapp has its own separate storage.

How do i access index db on a per page basis?

**Comment by frozeman** [comment]
IndexDB seems to use the same origin policy as local storage and therefore is no solution.

Any idea how to add the hostname to alter the origin of a custom protocol?

**Comment by deepak1556** [comment]
Actually the problem is the [url parser](https://code.google.com/p/chromium/codesearch#chromium/src/url/third_party/mozilla/url_parse.h&sq=package:chromium&type=cs&l=227&rcl=1433834947), standard schemes are treated in a different way to `file:` like schemes. So the fact hostname not set was not because of the protocol jobs. I am not sure how to fix that but we can probably implement our own DOMStorage for custom protocols, @zcbenz thoughts ?

**Comment by zcbenz** [comment]
Chrome has a concept of [standard scheme](https://code.google.com/p/chromium/codesearch#chromium/src/url/url_util.h&sq=package:chromium&type=cs&l=47), I believe this behavior is caused by custom protocol not treated as standard scheme.

> but we can probably implement our own DOMStorage for custom protocols

This doesn't sound like a decent solution to me.

**Comment by deepak1556** [comment]
Didnt know about registering custom schemes to the standard, will look into it. Thanks!

**Comment by frozeman** [comment]
Thanks for the other PR, can we now add async retrieval :)
