### ISSUE TITLE
Why don't you use gitter for this community?

### ISSUE THREAD

**Issue by LimeStreem** [atom/electron#1893]
Hello everyone contributing or interesting in this repository. :heart_eyes: 
I think it is better to make some of place to communicate about electron. It makes users contribute easier, and get user's feedback easier.

Thus, how about to use gitter?
https://gitter.im/

There is many famous repository using this service, for example, webpack,babel,and so on.

Thank you for reading! :laughing:

**Comment by steelbrain** [comment]
We have our own slack btw. and there's a room for electron there.
http://atom-slack.herokuapp.com

**Comment by LimeStreem** [comment]
oh,that good!
thank you!

**Comment by thomasjo** [comment]
FYI: The proper URL is https://atomio.slack.com/.
