### ISSUE TITLE
Failed to send message to ack remove remote endpoint

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#1898]
I'm getting this error when closing the main browser window or exit the application on OS X:

[28157:0607/230052:INFO:renderer_main.cc(200)] Renderer process started
[28157:0607/230059:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 2147483648, remote ID 2)

Something wrong with my machine or is this is issue with the latest release?

**Comment by tangrui** [comment]
I have the same problem when porting [electron-starter](https://github.com/atom/electron-starter) to my own project. This warning may be produced before "closed" event was emitted. What dose this mean, and do I need to care about it.

I'm using Electron 0.27.2.

Thank you!

**Comment by zcbenz** [comment]
It is a harmless warning printed by Chromium, you can [suppress the warnings](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md#--vlog_level) if you don't want to see them.
