### ISSUE TITLE
Electron and graceful-fs don't seem to work

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1903]
I am using Electron 0.27.1 on a Mac and notice that graceful-fs cannot be used to prevent EMFILE errors. 

To reproduce take belows application and change the folder in index.html to a folder with lots of javascript files. In my testing I needed at least 1000 files to cause issues. Run the application and I immediately get following output: Error EMFILE too many files open.

If I run the script bare with node.js or io.js I do not see the error so I assume Electrons way of patching the fs module for asar support is not compatible with graceful-fs way.

Any help how to correctly use graceful-fs is appreciated. 

index.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
    <script>
      var gracefulfs = require("graceful-fs");
      console.log("is graceful loaded: " + !!gracefulfs);

      var glob = require("glob");
      glob("/<path to lots of js files>/**/*.js", function(error, matches) {
        matches = matches.slice(0, 1000);
        matches.forEach(function(m) {
          gracefulfs.readFile(m, function(e, c) {
            if (e) {
              console.log(e);
            }
          });
        });
      });
      
      </script>
  </head>
  <body>
   
  </body>
</html>
```

package.json:
```json
{
  "name"    : "your-app",
  "version" : "0.1.0",
  "main"    : "main.js",
  "dependencies": {
    "glob": "*",
    "graceful-fs": "*"
  }
}
```

main.js:
```javascript
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when Electron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600, show: true});

  // and load the index.html of the app.
  mainWindow.loadUrl('file://' + __dirname + '/index.html');

  // Open the devtools.
  mainWindow.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});
```

**Comment by zcbenz** [comment]
I don't think `graceful-fs` can work in latest io.js, `graceful-fs` works by hooking `fs.open`, it worked in Node 0.10.x:
https://github.com/joyent/node/blob/v0.10.38/lib/fs.js#L207

but recent io.js releases calls `binding.open` directly in `readFile` so it doesn't work anymore:
https://github.com/nodejs/io.js/blob/v1.6.4/lib/fs.js#L246

I suggest reporting a bug to graceful-fs, or you can implement your own file reading pool, opening thousands of files at the same time seems pretty bad to me.

**Comment by bpasero** [comment]
Thanks for the explanation!

**Comment by bpasero** [comment]
@zcbenz I think this needs to reopen, I tried my sample on io.js and cannot reproduce the EMFILE issue. To reproduce take this code:

```javascript
var fs = require("fs");

var glob = require("glob");
glob("/<path to folder with many JS files>/**/*.js", function (error, matches) {
	counter = 0;
	console.log("matches: ", matches.length);
	matches.forEach(function (m) {
		fs.readFile(m, function (e, c) {
			if (e) {
				console.log(e);
			} else {
				console.log(counter++);
			}
		});
	});
});
```

```json
{
	"name": "name",
	"description": "description",
	"author": "author",
	"version": "1.0.0",
	"main": "pathToMain",
	"dependencies": {
		"glob": "*"
	}
}
```

Use io.js version 1.6.3 and run it. I can get to 8000 files without EMFILE error. When I try the same folder within Electron renderer, it quickly fails with EMFILE.

Interestingly in this example I don't even need graceful-fs. I am not sure why io.js behaves differently here though :-(. Any ideas?

**Comment by paulcbetts** [comment]
> Use io.js version 1.6.3 and run it. I can get to 8000 files without EMFILE error. When I try the same folder within Electron renderer, it quickly fails with EMFILE.

Electron is going to have more files open from start versus a command line app, so you're going to hit that limit way quicker. 

> opening thousands of files at the same time seems pretty bad to me.

This is still good advice - why leave all these files open?

**Comment by bpasero** [comment]
> Electron is going to have more files open from start versus a command line app, so you're going to hit that limit way quicker.

I see that, but being able to open 900 files in electron vs. 8000 files in io.js seems like a huge difference to me even if electron keeps files open.

> This is still good advice - why leave all these files open?

Well, the files are not left open, they are closed once readFile() is calling into the callback. There is no leak here and its arguable if the code is good or bad. At least it maximizes fs throughput by trying to read as many files in parallel as possible. If you look at libraries like glob, you will notice that all of them read the fs and open stats and directories in parallel up to as many files and folders you have. 

So, the only reason why it might be a bad idea is because of EMFILE and hence, thats why graceful-fs exists and is popular.

**Comment by paulcbetts** [comment]
> So, the only reason why it might be a bad idea is because of EMFILE and hence, thats why graceful-fs exists and is popular.

Hm, you're still opening 8000 files concurrently though - even if you can successfully do this, you'd probably get better performance if you batched these and issued N at a time. At the end of the day there's still only one filesystem / disk, and you've just hit it with 8000 requests at the same time.

**Comment by bpasero** [comment]
And then what is the right batch to avoid EMFILE?
Am 09.06.2015 8:45 nachm. schrieb "Paul Betts" <notifications@github.com>:

**Comment by zcbenz** [comment]
I believe Chromium has restricted the number of maximum opened files, so it reaches `EMFILE` much earlier than io.js. Even if we find a way to increase the number, your app will still see `EMFILE` when reading hundreds of thousands of files.

I think the solution is to monkey-patch `fs.readFile` to hang when `EMFILE` happens and continue when some `fs.readFile` ends, like [what graceful-fs did](https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js).

**Comment by bpasero** [comment]
> I believe Chromium has restricted the number of maximum opened files

Ok thats interesting. Would it be possible to lift this restriction, similar to how Electron lifts the storage quota?

**Comment by zcbenz** [comment]
> Would it be possible to lift this restriction, similar to how Electron lifts the storage quota?

It should be possible, but I'm not sure where to patch. Patching user code to handle `EMFILE` or fixing it in graceful-fs seems a much faster way.
