### ISSUE TITLE
Cannot build on Windows - cannot convert from 'const std::string' to 'base::FilePath'

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#1913]
Any thoughts on what might be driving this error and causing the build to fail? I installed the latest version of Visual Studio Community and tried running it from the VS command prompt as well.

	python script\build.py -c D

	ninja: Entering directory `out\D'
	[339/1062] CC obj\vendor\node\deps\openssl\openssl\crypto\dso\openssl.dso_win32.obj
	electron\vendor\node\deps\openssl\openssl\crypto\dso\dso_win32.c(289) : warning C4055: 'type cast' : from data pointer 'void *' to function pointer 'DSO_FUNC_TYPE'
	[723/1062] CC obj\vendor\node\deps\openssl\openssl\crypto\whrlpool\openssl.wp_block.obj
	electron\vendor\node\deps\openssl\openssl\crypto\whrlpool\wp_block.c(87) : warning C4164: '_rotl64' : intrinsic function not declared
	[918/1062] CXX obj\atom\common\crash_reporter\electron_lib.crash_reporter.obj
	FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\atom\common\crash_reporter\electron_lib.crash_reporter.obj.rsp /c ..\..\atom\common\crash_reporter\crash_reporter.cc /Foobj\atom\common\crash_reporter\electron_lib.crash_reporter.obj /Fdobj\electron_lib.cc.pdb
	electron\atom\common\crash_reporter\crash_reporter.cc(49) : error C2440: '<function-style-cast>' : cannot convert from 'const std::string' to 'base::FilePath'
	        No constructor could take the source type, or constructor overload resolution was ambiguous
	[918/1062] CXX obj\atom\common\electron_lib.platform_util_win.obj
	ninja: build stopped: subcommand failed.

**Comment by frankhale** [comment]
This is also logged here: https://github.com/atom/electron/issues/1910

You can try the fix that annotated there to get master to compile.

**Comment by kirkouimet** [comment]
Closing this issue as a duplicate:

**Comment by kirkouimet** [comment]
https://github.com/atom/electron/issues/1910
