### ISSUE TITLE
Ability to set color in terminal

### ISSUE THREAD

**Issue by tengyifei** [atom/electron#1917]
It would be nice to change the color of printed text in `console.log`. Currently the bash ASCII color escapes get printed as-is, and [Marak/colors.js](https://github.com/Marak/colors.js) does not work in renderer or main process.

**Comment by steelbrain** [comment]
Have you tried `console.log = require('console').log` and printing colors after that?

**Comment by tengyifei** [comment]
No luck :(
```
console.log('\\033[0;32m test \\033[0m');    // verbatim
console.log('test'.green);    // no color
```

**Comment by tengyifei** [comment]
Got it working with `\u001b` instead of the octal `\033'. Not sure why color.js does not work though.

**Comment by zcbenz** [comment]
> console.log('\\033[0;32m test \\033[0m');    // prints \033[0;32m test \033[0m

You should use `console.log('\033[0;32m test \033[0m')`, double backslashes will escape itself. 

I'm not sure why color.js doesn't work, you can probably report this to its issues. I'm closing this since ASCII control characters work as expected.

**Comment by tengyifei** [comment]
Forgot to mention that octal representations were deprecated and were triggering errors in the ES6 transpiler, hence unicode escapes.

**Comment by erossignon** [comment]
As a workaround, under windows, you can pipe the electron output stream with more . this will bring back colors. Although this is only useful if you start electron by hand for debugging for instance...
```
C:\myapp>electron . | more
```

**Comment by mceachen** [comment]
> erossignon commented on Jan 26
> As a workaround, under windows, you can pipe the electron output stream with `more`.

If you're using a bash windows shell (like from the git distribution), and you don't have `more`, try `cat`.

```sh
$ electron main.js | cat
```

**Comment by josselinbuils** [comment]
The [xpl/ansicolor](https://github.com/xpl/ansicolor) package seems to work well with electron.
