### ISSUE TITLE
Cannot compile on Windows when Electron is in a path with spaces

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#1919]
So yeah this has been crazy for me to track down - I tried to find where the path was being called to fix it but compilation is a complex beast and I can't seem to track down where to sanitize the path. Here is build output:

    C:\Users\Kirk Ouimet\Projects\electron>.\script\build.py
    ninja: Entering directory `out\R'
    [165/189] LINK_EMBED(DLL) node.dll
    FAILED: C:\Program Files (x86)\Python\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "C:\Program Files (x86)\Python\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.manifest" obj\vendor\node\node.node.dll.generated.manifest
    LINK : fatal error LNK1181: cannot open input file 'C:\Users\Kirk.obj'
    Traceback (most recent call last):
      File "gyp-win-tool", line 316, in <module>
        sys.exit(main(sys.argv[1:]))
      File "gyp-win-tool", line 29, in main
        exit_code = executor.Dispatch(args)
      File "gyp-win-tool", line 71, in Dispatch
        return getattr(self, method)(*args[1:])
      File "gyp-win-tool", line 169, in ExecLinkWithManifests
        subprocess.check_call(ldcmd + add_to_ld)
      File "C:\Program Files (x86)\Python\lib\subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'C:\Program Files (x86)\Python\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1181
    ninja: build stopped: subcommand failed.

I would really love to get this working, just need some help from someone who understands the compilation process to get this healed up.

This is my electron path:

`C:\Users\Kirk Ouimet\Projects\electron`

This is what is being passed into some call and breaking:

`LINK : fatal error LNK1181: cannot open input file 'C:\Users\Kirk.obj'`

**Comment by zcbenz** [comment]
Unable to reproduce anymore.

**Comment by anagas** [comment]
I have the same issue.

![electron](https://cloud.githubusercontent.com/assets/12841639/14422423/10b0f33c-ffd7-11e5-91fd-29cd982312e8.png)
