### ISSUE TITLE
Windows: Menu accelerator uses different font in some cases

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1924]
When you assign a F-XY key, the menu shows it in a weird font on windows. See the Alt+F3 below:

![image](https://cloud.githubusercontent.com/assets/900690/8077359/62e81d88-0f55-11e5-88ee-3eaa9581207b.png)

**Comment by zcbenz** [comment]
The rendering of menu is implemented on Chromium's side, so we are not able to fix this on Electron's side and I'm closing this issue as won't fix.
