### ISSUE TITLE
Mac: dropping file/folder onto dock does not add to process.argv

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1926]
I am trying to find out how to support the case that a user drops a file or folder into the dock icon of my electron app. I was hoping to find the path on the argv array of process to read it out, but its not here. I am also not getting an event through open-file (as outlined in https://github.com/atom/electron/blob/master/docs/api/app.md#event-open-file).

Note: things work fine once the app is running, in that case I am getting the open-file event. This is only an issue if the app is not running yet.

Since Atom allows to drop a folder into the dock icon to open the folder I am sure its somehwere. Can someone help me out here?

**Comment by zcbenz** [comment]
Two possibilities:

* `open-file` event is emitted before the `ready` event when you drag the file to dock to start the application.
* You didn't add the file type in `Info.plist`.

You can find how Atom handles it in `src/browser/main.coffee` under atom/atom repo.

**Comment by bpasero** [comment]
@zcbenz thanks, its actually the fact that open-file gets emitted very early in this case. I created https://github.com/atom/electron/pull/1953 to update the docs.
