### ISSUE TITLE
Loading additional .js files in Electron

### ISSUE THREAD

**Issue by Nanofus** [atom/electron#1928]
The documentation seems to be missing information on this.

I've added jQuery to my project as described [here](https://github.com/atom/electron/issues/254). It seems that to load additional .js scripts into a window you have to use `require` to get them, as loading Twitter Bootstrap in a `<script>` tag causes `Uncaught Error: Bootstrap's JavaScript requires jQuery` error, even though jQuery is loaded. How exactly do I do this?

Thanks in advance!

**Comment by zcbenz** [comment]
You should put the `<script>` tag after `require('jquery');`.
