### ISSUE TITLE
process.crash() equivalent to trigger "unresponsive" event

### ISSUE THREAD

**Issue by maxkueng** [atom/electron#1933]
Chromium provides some debug URLs listed under `chrome://chrome-urls/`. Some of them are `chrome://crash`, `chrome://kill` and `chrome://hang`.

"crash" and "kill" seem do be doing the same and in Electron we can trigger a crash using `process.crash()`. But for "hang" which makes Chromium freeze and pop-up the "Unresponsive" dialog there currently seems to be no method to trigger this.

It would be very useful for Electron apps that have to handle unresponsive windows if they could somehow purposely make the window unresponsive (so that it triggers the `unresponsive` event) in order to test the behavior. Maybe `process.hang()` or `process.unresponsive()`.

While I'm not very good at C++ I did some research and found that Chromium achieves this by doing

```c++
for (;;) {
  base::PlatformThread::Sleep(base::TimeDelta::FromSeconds(1));
}
```

[in render_frame_impl.cc](https://chromium.googlesource.com/chromium/src.git/+/master/content/renderer/render_frame_impl.cc) between lines 353 and 355.

Electron seems to register the `process.crash()` method [here](https://github.com/atom/electron/blob/71598e15bf0ca2fd8de338d864cc37776608c6c2/atom/common/api/atom_bindings.cc#L56). Maybe a `hang()` method could be added the same way?

**Comment by zcbenz** [comment]
> Electron seems to register the process.crash() method here. Maybe a hang() method could be added the same way?

Sounds good to me.
