### ISSUE TITLE
window position is changed after setContentSize 

### ISSUE THREAD

**Issue by KaeNote** [atom/electron#1934]
when i setContentSize ,then position is change
in version 23 is ok,and the newest version is wrong.

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by KaeNote** [comment]
win7 64bit
![20150616090039](https://cloud.githubusercontent.com/assets/2688187/8173859/771311ae-1406-11e5-8401-f37eef77b2b1.jpg)
