### ISSUE TITLE
Getting a screenshot with capturePage

### ISSUE THREAD

**Issue by anonrig** [atom/electron#1937]
Hello,

I am using Electron with Google Closure Library. I've the following code to get the current screenshot of the page. But the callback variable `data.toPng().toString('base64');` is always empty. I believe the output is filled with pipe. But couldn't make it work.

Appreciate a suggestion.
```
remote.getCurrentWindow().capturePage(function (data) {
                console.log(data);
                console.log(data.toPng().toString('base64'));
                document.dispatchEvent(new CustomEvent(signa.Connection.types.COMMAND_RESULT, {
                    detail: data.toDataUrl() + data.toPng().toString('base64')
                }));
            });
```

**Comment by zcbenz** [comment]
The v0.28.0 release should have this fixed.

**Comment by anonrig** [comment]
@zcbenz When the application is in backend, capturePage returns an empty buffer. It should throw something.
