### ISSUE TITLE
Release: Is Chrome 43 in 0.27.0 or 0.27.2?

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1938]
I am a bit puzzled what Chrome version is in 0.27.0. It says 43 in the release notes but then 0.27.2 has an entry "Fix wrong chrome version". Does this mean 0.27.0 ships with Chrome 42 although the release notes state otherwise?

**Comment by thomasjo** [comment]
43; https://github.com/atom/electron/issues/1808

**Comment by paulcbetts** [comment]
@bpasero The "Fix wrong chrome version" patch is just changing the reporting of the version, not the actual contents afaik. You definitely want to use 0.27.2 though, because 0.27.[0/1] had a lot of pretty bad problems

**Comment by chrisdias** [comment]
What is confusing to us is if we trace through the commits for 0.27.1:

·         Electron Shell Version: 0.27.1
o    https://github.com/atom/electron/tree/v0.27.1
·         Electron Shell consumes Brightray @8fba2a
o    Look in /vendor and then click on the brightray commit
o    https://github.com/atom/brightray/tree/8fba2a883552ad939a63250b552f467fa4f9bedb
·         BrightRay consumes libchromiumcontent @d5c126e
o    Look in /vendor and click on libchromium content commit
o    https://github.com/atom/libchromiumcontent/tree/d5c126e2d8fd181a94720c64b18196505b937041
·         Libchromiumcontent version file says chrome 42.0.2311.107
o    https://github.com/atom/libchromiumcontent/blob/d5c126e2d8fd181a94720c64b18196505b937041/VERSION
·         Therefore, Electron 0.27.1 consumes Chromium version: 42.0.2311.107
o    https://gsdview.appspot.com/chromium-browser-official/chromium-42.0.2311.107.tar.xz

We need to understand the exact version for our licensing files and to post to http://3rdpartysource.microsoft.com/.

Thanks,
Chris

**Comment by bpasero** [comment]
@paulcbetts we are currently on 0.27.1 and planned to ship our next update with that. I am curious about the actual issues you are talking about. Should we go for 0.27.3 even?

**Comment by paulcbetts** [comment]
@bpasero If your app works you can go with it, as I recall 0.27.0 was just completely busted (devtools segfaulted the app), and 0.27.1 had a broken WebView

**Comment by bpasero** [comment]
@paulcbetts got it. the devtools issue was the reason for us to update to 0.27.1. I noticed the webview changes but we are not using the web view at all in VS Code.

**Comment by zcbenz** [comment]
v0.27.1 actually ships Chrome43 but there was a bug that the version was not changed.

**Comment by bpasero** [comment]
Ok thanks!
