### ISSUE TITLE
Cannot find module './web-view/web-view-attributes' in 0.28.0 - Windows x64

### ISSUE THREAD

**Issue by frankhale** [atom/electron#1939]
In 0.28.0 there are a couple of new issues that show out of the box. You can see these simply by opening the default app and then opening Dev tools. The errors are detailing in the screenshot below:

![electron-0 28-cant-find-module](https://cloud.githubusercontent.com/assets/190154/8110540/e6720328-102a-11e5-873c-4cd193e75ecb.PNG)

**Comment by frankhale** [comment]
It looks like atom.asar is missing some code. The size of atom.asar is 111kb in 0.28 but is 123kb when I built master yesterday. Replacing atom.asar with a earlier copy resolves the issues for me.

**Comment by frankhale** [comment]
It looks like something happened in the build process for 0.28 and something happened to atom.asar. I just built 0.28 from master and all is well.

**Comment by paulcbetts** [comment]
Is this 32-bit or 64-bit Windows? No repro with the released OS X version

**Comment by frankhale** [comment]
Sorry I am on Win 64. Rebuilding from master solved the problem with atom.asar missing code.

**Comment by zcbenz** [comment]
Fixed in v0.28.1.
