### ISSUE TITLE
v0.28.0 - cannot find module ./web-view

### ISSUE THREAD

**Issue by jackal-scratch** [atom/electron#1940]
Trying out electron for the first time and downloaded the latest version 0.28 (win x64). I basically copy and pasted  the tutorial code from Quick Start (https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md) and was able to bring up a window. However I see the following error:
Uncaught Error: Cannot find module './web-view/web-view-attributes' (module.js:334)

I checked v0.27 and do not see this error.

**Comment by felicienfrancois** [comment]
Same here under windows, since v0.28

**Comment by felicienfrancois** [comment]
Duplicates #1939

**Comment by frankhale** [comment]
@jackal-scratch if you have the capability building Electron from master resolves the problem. Looks like something went awry when create_dist.py was ran causing atom.asar to either be corrupt or caused it to be missing some of the files.
