### ISSUE TITLE
Does Electron support Bluetooth?

### ISSUE THREAD

**Issue by gtzogana** [atom/electron#1943]
I've been trying to get bluetooth-serial-port to work with Electron with no success. I'm wondering if this is simply because the package isn't compatible with the runtime. Any insights?

**Comment by zcbenz** [comment]
I suggest reporting this to the module's repo if it doesn't work, the module doesn't need Electron or io.js to support Bluetooth to be used.

**Comment by philipgiuliani** [comment]
Hi @gtzogana i am also successfully using it in my project. Which problems do you have?

@zcbenz Chromes current versions have "Web Bluetooth" behind a flag. Its possible to enable it in electron?

**Comment by luan007** [comment]
Hi @philipgiuliani - seems using native NodeJS modules always work, though I'm still curious about the possibility about Web Bluetooth flag, which may eliminate one or many external modules

**Comment by barchard** [comment]
@luan007 likewise. some of the node module requirements for bluetooth are really demanding. especially for Windows. I'm still researching a way to do this. Web Bluetooth definitely looks promising/ideal

**Comment by amrish7** [comment]
@philipgiuliani Could you please add more information and code snippet on any changes that you had to do in order to get `bluetooth-serial-port` to work? I am trying to port my App to Electron and the bluetooth serial port is not working as expected. More information >> #7367

**Comment by himanshu21092** [comment]
Hi @amrish7, were you able to use bluetooth-serial-port successfully? I am going to start a project on electron which will have bluetooth support. Any help is appreciated. Thanks

**Comment by amrish7** [comment]
@himanshu21092 Yeah.. it did work when I last tested. It's again some 6 months back

**Comment by himanshu21092** [comment]
@amrish7 , did you do any workaround or it worked as mentioned in the docs?
