### ISSUE TITLE
Setting exit code

### ISSUE THREAD

**Issue by tengyifei** [atom/electron#1944]
Would be nice to have something like this:
```js
app.quit(1);    // exit with code 1
```

**Comment by zcbenz** [comment]
You can call `process.exit`.

**Comment by pushkin-** [comment]
@zcbenz So does `process.exit` basically do the same thing as `app.quit`? I thought `app.quit` would also go through Electron's closing logic whereas `process.exit` won't do that.

**Comment by zcbenz** [comment]
`app.quit` can not set exit code, `app.exit` can be used to quit smoothly with exit code. `process.exit` does not shutdown electron gracefully.

**Comment by s4m0r4m4** [comment]
Just ran across this description, super helpful - thanks!

**Comment by felipecrs** [comment]
Exit doesn't fire `before-quit`. Any other alternative?
