### ISSUE TITLE
Browser-Window will not POST form

### ISSUE THREAD

**Issue by timmickey** [atom/electron#1945]
If a browser-window page has a form  with method="post", the form is still sent as GET request. This seems to have been introduced in 0.27.3; still happens in 0.28.0. This does not happen in  0.27.1 or 0.27.2. This simplest way to reproduce is:

	var app = require('app')
	var BrowserWindow = require('browser-window')

	var mainWindow = null;

	app.on('window-all-closed', function() {
	    app.quit()
	});

	app.on('ready', function() {

	    mainWindow = new BrowserWindow({});

	    mainWindow.loadUrl('https://slack.com/signin')

	    mainWindow.openDevTools()

	});

I put the slack.com page in there, to prove that popular new sites do still do this. You cannot get past the signin page in 0.27.3+, but can in 0.27.2-

**Comment by bundyo** [comment]
I've also stumbled onto this one. Took me by surprise and currently downgraded to 0.27.2 in order to be able to login.

**Comment by brianmario** [comment]
Just noticed this too, as well as narrowing it down to the issue being introduced in 0.27.3. And for what it's worth it was with a completely different URL set in `mainWindow.loadUrl(...)`

**Comment by brianmario** [comment]
Thank you @zcbenz!
