### ISSUE TITLE
How to use accelerator keys

### ISSUE THREAD

**Issue by jannavarro** [atom/electron#1946]
I saw the guide for accelerator keys [here](https://github.com/atom/electron/blob/7d1f6dae6fee98d5b2b41550531b6712c1800666/docs/api/accelerator.md) but would you have some sample codes on how to implement accelerator keys? Do we just use the html 5's labelfor attribute but I'm sure there are other ways that are programatic.

**Comment by hokein** [comment]
You may search `Accelerator` in the repo to find all related code. https://github.com/atom/electron/search?p=1&q=Accelerator&utf8=%E2%9C%93

One of the major usage is in global-shortcut API, you can view the usage in https://github.com/atom/electron/blob/master/atom/browser/api/atom_api_global_shortcut.cc

**Comment by zcbenz** [comment]
The accelerators are used in `menu` and `global-shortcut` modules.
