### ISSUE TITLE
Making file associations to my app

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [atom/electron#1947]
Is there a way to set operating system file associations to an electron app? For example, how can I make all files with extension '.txt' be opened with my electron app?

**Comment by zcbenz** [comment]
You need to [register the file type in Windows registry](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144148(v=vs.85).aspx), it is usually done by the installer and is not very related to which application you want to assign to.
