### ISSUE TITLE
How to efficiently pass large array from main to render?

### ISSUE THREAD

**Issue by jgeurts** [atom/electron#1948]
I have an array with a size of roughly 8 million int values that I would like to pass from the main io.js layer to the browser layer. This array represents a 1080p image and I get roughly 30 images per second. I tried using ipc to send the array from io.js to chromium, but it seems to prefer sending a string rather than an array. Performance is a concern, so encoding the array to a base64 string to pass via ipc cuts down on the available performance.

Any thoughts on how I could transmit this data from the io.js side of things to the chromium side of things efficiently? I ultimately want to display these images in chrome to a canvas or img element, so that it appears there is a video streaming.

**Comment by maxkueng** [comment]
Could you start a TCP server in the browser process and consume it in the renderer process? If I understand you correctly you are trying to stream video / moving images generated in the browser to the renderer.

I haven't tried it out but there's a a thing called [BinaryJS](http://binaryjs.com/) that does binary streams. And there may be other possibilities in node to stream video over TCP.

Another way to communicate between browser and renderer is through globals. You can store an object in the browser `global.myObject = { whatever: true }` and access it in the renderer `myObject = remote.getGlobal('myObject')`.

**Comment by jgeurts** [comment]
I should be able to give BinaryJS a shot - I was hesitating because I was hoping ipc would alleviate the need. Maybe not though?

I'll try the globals options as well - I wasn't aware of that!

**Comment by zcbenz** [comment]
The array is serialized as JSON string when sending and deserialized with `JSON.parse`, so I think using `ipc` or `remote` to send a large image is a bad idea.

You should probably just do everything in renderer.

**Comment by jgeurts** [comment]
@zcbenz I can't do everything in renderer... The components I'm using to obtain that large array depend on some additional modules that are not compatible with renderer. Specifically, there was an issue with the process variable and expected properties.

**Comment by jgeurts** [comment]
If anyone comes back here, the [BinaryJS](http://binaryjs.com/) suggestion from @maxkueng worked wonderfully. Thanks @maxkueng for the heads up on that!

**Comment by sqwk** [comment]
@jgeurts Could you share your solution using BinaryJS? I am trying to draw a mediastream onto a canvas in another (second) window—your problem sounded similar.

**Comment by jgeurts** [comment]
@sqwk I ended up removing the binaryjs code in favor of using [MediaDevices.getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) from the frontend code. That said, the BinaryJS code looked something like:

    app.on('ready', function () {
      ...
      var binaryServer = BinaryServer({port:9000, chunkSize: 9999999999});
      var binaryClient;
      binaryServer.on('connection', function (client) {
        start = process.hrtime();
        console.log("binaryServer:connection");
        binaryClient = client;

        client.on('error', function (error) {
          console.log("binaryServer:error\n" + error);
        });
        client.on('drain', function () {
          console.log("binaryServer:drain");
        });
        client.on('close', function (code, message) {
          console.log("binaryServer:close\n" + code + "\n" + message);
        });
      });
      binaryServer.on('error', function (error) {
        console.log("binaryServer:error\n" + error);
      });
      binaryServer.on('drain', function () {
        console.log("binaryServer:drain");
      });
      binaryServer.on('close', function (code, message) {
        console.log("binaryServer:close\n" + code + "\n" + message);
      });
      ...
      someVideoInput.on('frame', function(data) {
        if (binaryClient) {
          try {
            binaryClient.send(compressedData);
          } catch (ex) {
            console.log(ex);
          }
        }

------
FE code:
html: `<canvas id="image" height="1080" width="1920" />`

javascript:

    var BinaryClient = window.require('binaryjs').BinaryClient;
    var binaryClient = new BinaryClient('ws://localhost:9000');
    var image = document.getElementById('image');

    binaryClient.on('stream', function (stream) {
      var parts = [];
      stream.on('data', function (data) {
        parts.push(data);
      });

      stream.on('end', function () {
        var array = new Uint8ClampedArray(parts[0]);
        var context = image.getContext('2d');
        // Assume image came through as 1920x1080
        context.putImageData(new ImageData(array, 1920, 1080), 0, 0);
      });
    });

**Comment by davidgilbertson** [comment]
@jgeurts I know it's been a while... but bow did you get MediaDevices.getUserMedia() working? I can get `navigator.webkitGetUserMedia` to work as per [this example](http://electron.atom.io/docs/api/desktop-capturer/) but not `navigator.mediaDevices.getUserMedia`.

**Comment by janakg** [comment]
Are there any new perspectives from the electron team for this use case in 2021?

**Comment by nornagon** [comment]
nope, but IPC got faster. https://gist.github.com/abc2246abd489a53e0a0747b38873251 shows that the end-to-end time for 8MB of data is about 25 ms. Additionally, that data will be pipelined, so e.g. sending 10x 8MB messages be faster than 250 ms if you don't wait for a round-trip. For example, here's a [modified benchmark](https://gist.github.com/b85f2dc54d570cdd3a7b115637aa1c3a) that suggests 10 8MB messages can be delivered in roughly 160 ms total, for 16ms each.

If you need higher throughput than this, your next avenue of investigation is probably shared memory of some sort, which isn't exposed by Electron, so a native module would be involved (and would require running unsandboxed renderers).
