### ISSUE TITLE
Manipulating browser window too closely in succession causes error

### ISSUE THREAD

**Issue by willbarrett** [atom/electron#1949]
On Ubuntu Linux, manipulating a single browser window too quickly in succession (e.g. <pre>browserWindow.setFullScreen(false); browserWindow.hide() </pre> causes this error:

```
ERROR:desktop_window_tree_host_x11.cc(1579)] Not implemented reached in void views::DesktopWindowTreeHostX11::MapWindow(ui::WindowShowState)
```

We noticed this as we have an event-driven system, so one call is not waiting for another to finish before calling the function. We're implementing a workaround, but this error tends to make the window visible if it is hidden.

**Comment by Ivshti** [comment]
@willbarrett shouldn't you call setFullScreen with a boolean instead of a string?

**Comment by willbarrett** [comment]
@Ivshti you're right, I should. The code is a paraphrase, not a copy. I've fixed the code in the issue. I'll see if I can mock up a demo app that will demonstrate the issue. Hopefully I'll get some time for that this afternoon.
