### ISSUE TITLE
Windows 10: Electron and Atom cannot properly be pinned to task bar

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1954]
- run latest Windows 10
- pin either electron or atom to the taskbar
- click it to open the app

=> you end up having 2 icons
=> somehow the app when started does not get associated to the pinned entry in the taskbar
=> it does not reproduce on Windows 8.x

I wonder if your change in https://github.com/atom/electron/commit/fb6c80d12ecbb99a481e1018a0d1d56c3fc4dce3 could have an impact here. Imho it is used to find out if an application belongs to the same process group or not: https://msdn.microsoft.com/en-us/library/windows/desktop/dd378422(v=vs.85).aspx

**Comment by paulcbetts** [comment]
So, this change shouldn't have any impact unless you're explicitly calling the method - the idea was that unless you called `SetAppUserModelId`, nothing would change. However, we've been noticing issues with this too, and one thing that I was wondering is that, do AppUserModelIDs get inherited? (i.e. if I set this in browser process, will renderer have the same ID?)

**Comment by bpasero** [comment]
I see, so we are not calling this method and I am not sure about Atom/Electron calling it. Thats an interesting theory about the child process getting another entry in the task bar. However when i was right clicking on this second task entry to check which command was running, it was actually the same as the pinned one.

**Comment by paulcbetts** [comment]
@bpasero Electron will end up calling it, but it has done so for at least a year or so. Another tricky bit is, that the Squirrel _shortcut_ we generate has its own AppID on Windows, in order to try to fix pinning. The reason I added that PR is so that we could make Electron's AppID follow along with the Squirrel one.

**Comment by paulcbetts** [comment]
Basically Pinning is a nightmarish feature that will continue to troll us forever

**Comment by zcbenz** [comment]
Calling `SetAppUserModelId` in renderer process might be able to fix this.

**Comment by bnb** [comment]
@zcbenz I'd really love to see this fixed, as it's driving me absolutely crazy.

**Comment by paulcbetts** [comment]
> Calling SetAppUserModelId in renderer process might be able to fix this

I was thinking about it too, basically we have to "fake" AppUserModel inheritance if it doesn't happen already.

**Comment by Keavon** [comment]
I am experiencing this with both Atom and an Electron app. Pretty unacceptable for a production app, so hopefully this can be figured out and fixed pretty quickly and it's not a limitation with Windows 10 itself.

**Comment by 18nleung** [comment]
+1, I just upgraded from Windows 8.1 to 10 and this has been happening.  Hope you guys figure out what's causing this - it's not that bothersome but the two icons look kinda funny sometimes.

**Comment by bnb** [comment]
It seems there's a fix [here](https://github.com/atom/electron/issues/2284). Can that be incorporated into Atom's next release?

**Comment by paulcbetts** [comment]
@bnb Already done :)

**Comment by DanielTamkin** [comment]
@paulcbetts Im getting the same bug and its nice to know this'll be fixed soon.

**Comment by zcbenz** [comment]
Does this still occur for Electron >= v0.30.2?

**Comment by bpasero** [comment]
@zcbenz yes, I just tried to pin the bare Electron 0.31.0 on Windows 10 and it reproduces.

**Comment by bpasero** [comment]
Btw I also tried with app.setAppUserModelId("Electron") and it does not seem to make a difference.

**Comment by paulcbetts** [comment]
@bpasero Do you have a shortcut and does that shortcut have an app user model ID already?

**Comment by bpasero** [comment]
@paulcbetts is there a way to find out what app user model ID windows is using when you pin an app from a shortcut? In my comment today I was just using the electron.exe as it comes from the GitHub releases page without shortcut and I just pinned it to the taskbar. However, in another scenario I was testing with VSCode where we indeed have a proper shortcut generated. I was hoping that the task bar pinning would not produce 2 entries if I programmatically set the ID to be the same as whatever the shortcut is using. But I could not find an ID to make it work....

**Comment by paulcbetts** [comment]
If you look at the command line parameters on a renderer process via Process Explorer you can see what Electron is using. Since you use Squirrel to install, you need to set it to `com.squirrel.PACKAGE_ID.YOUR_EXE_WITHOUT_DOT_EXE`, so for us it's `com.squirrel.slack.Slack`

**Comment by bpasero** [comment]
@paulcbetts indeed it works once I set it to "com.squirrel.code.Code". Any reason you guys don't close this bug and fix it on the Atom side by using the setAppUserModelId() call?

Out of curiosity, where is the com.squirrel name defined in Squirrel for the User App Id?

**Comment by paulcbetts** [comment]
@bpasero in Atom, this is already fixed but hasn't gone out yet since it relies on new Electron. Here's the PR that adds the user model ID stuff - https://github.com/Squirrel/Squirrel.Windows/pull/247

**Comment by bpasero** [comment]
@paulcbetts got it. I noticed one downside to calling setAppUserModelId(): My user tasks are no longer showing up when I right click on the task bar icon. I wonder if a pinned application needs to register its tasks differently, e.g. via the shortcut, instead of programmatically from within the application?

**Comment by paulcbetts** [comment]
Could you possibly have user tasks that were created before you made the `setAppUserModelId` change?

**Comment by bpasero** [comment]
@paulcbetts I tried both variants: first setting the user task and then the app id, and vice versa. In both scenarios, my task does not show up anymore. Once I dont set an app id, the task shows up.

**Comment by frankhale** [comment]
Looks like with the latest release of Atom 1.0.12 it can no longer be pinned to the desktop. It was pinned fine prior on two machines I use that I use. I know this issue is still open but is anyone else seeing this behavior?

**Comment by paulcbetts** [comment]
"Pinned to the Desktop"? What does this mean?

**Comment by frankhale** [comment]
Taskbar, LOL!

**Comment by paulcbetts** [comment]
This bug in Atom was an Atom bug, from the Electron side everything works correctly, reopen if someone finds that this isn't the case

**Comment by frankhale** [comment]
I didn't reopen or open this issue but was just using it as a sounding board since it was still open. Yeah pinning was fixed in Atom either in 1.0.13 or .14 at least it seems to be working now.

**Comment by p-bakker** [comment]
@paulcbetts Could you have a look at https://github.com/maxogden/electron-packager/issues/166 and determine if the 3rd bullet warrants reopening this case?

Dunno about the second bullet, if that is electron or electron-packager. The first bullet for sure is only the electron-packager

Basically I see duplicate icons on Electron and Windows exe's created with electron-packager with the latest version of electron (0.34.1 by now)

**Comment by paulcbetts** [comment]
@p-bakker Are you using Squirrel as your installer on Windows?

**Comment by p-bakker** [comment]
I'm using electron-packager which, to my understanding, uses Squirrel

**Comment by p-bakker** [comment]
Right..... I took the com.squirrel.myCompany.mycompany stuff from some comment on a case...

I see now that squirrel is only used when using the auto-updater functionality, which I'm not right now (want to, but for now I'd be happy to just get things working correctly without auto-updater functionality)

But, as I mentioned, I see the same duplicate icon thing when just running my app in electron (commandline 'electron .')

**Comment by paulcbetts** [comment]
@p-bakker Yep - because you set your app model ID to be something other than what the shortcut sets, you're seeing this bug. Remove this line and you shouldn't see it anymore.

**Comment by p-bakker** [comment]
I removed the app.setAppUserModelId(...); call: makes no difference

I've now also tested it just running electron, with the default app (which says: Welcome to Electron To run your app with Electron, execute the following command under your Console (or Terminal): ....) and I get the same double icon issue there

**Comment by p-bakker** [comment]
No idea if this is the case here, but it seems there's also a bug in Windows 10 that causes duplicate icons for pinned apps in the TaskBar. This issue will apparently be fixed in the next update to Windows 10: https://blogs.windows.com/windowsexperience/2015/10/12/announcing-windows-10-insider-preview-build-10565/

**Comment by p-bakker** [comment]
k, went through the exercise of setting up a VM with the Windows 10 Insider Preview build 10565, downloaded electron-v0.34.1-win32-x64.zip, extracted it and ran Electron, then pinned it: no duplicate icon!

To make sure I did the same procedure on my own machine running the currently released version of Windows 10: there I get duplicate icons.

So, pretty save to say this duplicate icon business is a Windows 10 bug and should be solved in the next Windows 10 update, which is expected to be released to the general public somewhere next month (nov '15).

So no need to reopen this case

**Comment by p-bakker** [comment]
Updated Windows 10 yesterday: the duplicate icon issue is gone now, so it was indeed a Windows 10 issue
