### ISSUE TITLE
Upgrade to chrome 43

### ISSUE THREAD

**Issue by bpmarinho** [atom/electron#1955]
This is the same as #1478 but I cannot reopen so I created a new one.

Chrome 43 fixes a huge problem affecting mouse usage on virtual box and is affecting atom after version 0.188.0. Next version had chrome 41 that showed the bug for the first time.

Here is the thread:
https://code.google.com/p/chromium/issues/detail?id=456222

Thank you,

Bruno

**Comment by bundyo** [comment]
What do you mean? Electron uses Chrome 43 since [0.27.0](https://github.com/atom/electron/releases/tag/v0.27.0).

**Comment by bpmarinho** [comment]
Sorry, my bad, should have checked this component instead of trying getting it from atom release notes.

Thanks,

Bruno

**Comment by bpmarinho** [comment]
Just installed atom and it's still the broken Chrome version.
So get the atom updated to Chrome 43 I need to log an issue on atom?

Thank you,

Bruno

**Comment by bundyo** [comment]
Yes, it is up to them to upgrade to a newer version of Electron.

**Comment by frankhale** [comment]
@bpmarinho, I don't think you need to log an issue on the Atom repo. I am quite sure they are keenly aware and tracking the direction of Electron. They have a lot of code that has to be tested so it's not surprising that they fall a little behind the Electron releases. Plus Atom 1.0 is imminent so I don't think they are going to adopt any new Electron releases just yet.

**Comment by bpmarinho** [comment]
Thanks for explain more. I open an issue on atom: atom/atom#7264
If 1.0 is eminent, this is a major problem to anyone using atom inside a VM in virtualbox.

**Comment by 50Wliu** [comment]
There is an open PR to upgrade Atom to Chrome 43: atom/atom#6877 (ignore how the title says Chrome 42; @zcbenz has already upgraded it to v43 in the PR itself).  This unfortunately won't be able to be merged until several crashes are fixed (such as a few in `node-spellchecker`).
