### ISSUE TITLE
Browser-Window node integration breaks after POST

### ISSUE THREAD

**Issue by timmickey** [atom/electron#1959]
Browser-Window node-integration breaks after POST. require / global are undefined in browser-window after a POST request. I've seen this behavior since I first used Electron - 0.26.0. Still happens in 0.28.1. Here is simple way to reproduce:

package.json
```
{
"name": "PostExample",
"version": "0.1.0",
"main": "main.js",
"description": "Post Loses Global"
}	
```

main.js
```
var app = require('app')
var BrowserWindow = require('browser-window')

var mainWindow = null;

app.on('window-all-closed', function() {
    app.quit()
});

app.on('ready', function() {

    mainWindow = new BrowserWindow({ 
        "node-integration": true,
    });

    mainWindow.loadUrl('file://' + __dirname + '/index.html')

    mainWindow.openDevTools()

});
```

index.html
```
<html>
 <script type="text/javascript">
    console.log(typeof global)
    try{
        var fs = require("fs");
    } catch(e){
        console.warn("ERROR", e)
    }
 </script>
<body>
 <h1>Posts to self</h1>
 <form action="" method="post">
    <input type="text" name="somevar" value="val" />
    <button type="submit">Submit to see Error</button>
 </form>
</body>
</html>
```

**Comment by deepak1556** [comment]
Yeah thats because we dont currently fork a new process for `POST` , which breaks the node integration. [This](https://github.com/atom/electron/blob/master/atom/renderer/atom_renderer_client.cc#L180) needs to be fixed.

**Comment by zcbenz** [comment]
Node integration relies on Chromium's browser-side-navigation feature, which doesn't support POST requests yet.

Related Chromium issue: https://code.google.com/p/chromium/issues/detail?id=475027

**Comment by lar248** [comment]
Is this fixed yet?

**Comment by karissa** [comment]
Looks like it

**Comment by viktorAndreevichMorozov** [comment]
1.2.6
Still/again not working.
