### ISSUE TITLE
Images from clipboard don't seem to support transparency on Win8.1

### ISSUE THREAD

**Issue by Nanofus** [atom/electron#1961]
I'm having trouble with writing transparent images from the clipboard into a file:

```
fs.writeFile('tempimage.png', clipboard.readImage().toPng(), function (err) {
            if (err)
                throw err;
            console.log('Save successful!');
        });
```

It says in NativeImage's documentation that it supports PNG transparency, however when I write a PNG image with transparency from the clipboard into a file with fs the transparent areas are turned white.

Any idea what could cause this?

**Comment by deepak1556** [comment]
Seems to work fine on OSX, what OS are you experiencing it on ?

**Comment by Nanofus** [comment]
Windows 8.1.

**Comment by zcbenz** [comment]
Seems like a Chromium bug.

**Comment by zcbenz** [comment]
Unable to reproduce on 0.36.2.

**Comment by gigadeplex** [comment]
I'm having this issue now on two windows computers...

**Comment by AramAnd** [comment]
I am having this issue on Window 10 and the Electron version is 8.2.5
