### ISSUE TITLE
Detect if input comes from Chrome Developer Tools?

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#1962]
In Node I can listen for input from stdin

			standardIn.resume();
			standardIn.on('data', function(key) {
				this.handleKey(key);
			}.bind(this));

Is there anyway for me to know if input is coming in from the Chrome web developer tools here?

![image](https://cloud.githubusercontent.com/assets/62191/8142442/6f48e282-1131-11e5-8ecf-a0ef42a82056.png)

This would be cool because I would be able to build some fun console interaction tools that would rely on knowing whether or not the input came from the dev tools console

**Comment by zcbenz** [comment]
There is no easy way to do that, the only way I can think of is to inject custom scripts to devtools by using `remote.getCurrentWindow().devToolsWebContents`.
