### ISSUE TITLE
Links with target="_blank" inside of <webview> tag do nothing, they should just navigate the webview to the page that was supposed to be opened in a new tab

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#1963]
When you have a webpage inside of a webview, <a> tags with <a target="_blank"> do nothing, as they are supposed to open in another tab.

Can this behavior be fixed by just navigating to the link inside of the webview without opening a new tab? Ideally I don't have to go through contents of the <webview> and strip all target="_blank" attributes on all links.

**Comment by netlovers** [comment]
Check out this:
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-new-window

**Comment by kirkouimet** [comment]
Yesss! Thanks @netlovers you are both wise and powerful

**Comment by andreigiura** [comment]
xcx

**Comment by bradydowling** [comment]
Looks like this method has since been removed (or the information for it has moved elsewhere. Is this still possible to hook into this event?

**Comment by enlight** [comment]
@bradydowling That event is now documented in the [`WebContents` doc](http://electron.atom.io/docs/api/web-contents/#event-new-window).

**Comment by alokmahor** [comment]
> I do it manually using webview events
> 
> ```
> webview.addEventListener('new-window', (e) => {
>   const url = e.url;
>   // update a variable used for webview src prop
> })
> ```

This does not work when `nativeWindowOpen: true` in webPreferences in parent window.

```javascript
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      webviewTag: true,
      nativeWindowOpen: true // This flag is not letting recieve new-window event from webview
    }
  })
```

**Comment by nornagon** [comment]
@alokmahor you need `allowpopups`.

**Comment by alokmahor** [comment]
> @alokmahor you need `allowpopups`.

If I add `allowpopups` in `<webview>` with `nativeWindowOpen: true` then electron app get crashed

**Comment by nornagon** [comment]
@alokmahor Please open a new issue with details and a small reproduction case!

**Comment by alokmahor** [comment]
> @alokmahor Please open a new issue with details and a small reproduction case!

Added new issue at [[Bug]: Electron app crash on clicking a link whose target is _blank in webview when nativeWindowOpen: true and allowpopups enabled on MacOS](https://github.com/electron/electron/issues/31127)
