### ISSUE TITLE
API to prevent page navigation (from DND, or keyboard or anything else)

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1965]
It is possible to drop a HTML file into an electron window and have it open. That is in all cases not what you want to happen when you write an Electron app. Can we have API that prevents page navigations from operations like drag and drop and even clicking a link within the app?

**Comment by Ivshti** [comment]
There is an API for that, it's the HTML5 Drag and Drop API.

http://www.w3schools.com/html/html5_draganddrop.asp

**Comment by bpasero** [comment]
I have updated the title to better reflect what I mean. Yes, its possible to do this from the renderer by catching the drop event, however there is other cases where the renderer can change where you have to manually interfere. For example, pressing the backspace key can sometimes cause a navigate-back. Also you need to install a click listener to prevent navigation. So you end up with 3 listeners to prevent the same thing. Having one API to prevent any changes in the page URL would solve all these cases imho.

If this API is not added then at least document all the workarounds one has to do to prevent browser behavior in that area.

**Comment by Ivshti** [comment]
It is documented in BrowserWindow documentation.

```
  win.on("will-navigate", function(e) { e.preventDefault() }); 
```

**Comment by bpasero** [comment]
@Ivshti that would be perfect, but it does not help for the drag and drop case.

**Comment by bpasero** [comment]
SORRY, I take it back, was not seeing its an event on the webcontents class. Works nicely!
