### ISSUE TITLE
Window transparency only works when the frame is hidden

### ISSUE THREAD

**Issue by jessefalzone** [atom/electron#1969]
I'm building Atom v0.209.0 with electron v0.28.1 on OS X 10.10.3.  I noticed that if I set `transparent: true` in the BrowerWindow options, only the frame is transparent (notice the close/minimize/maximize buttons in the upper left):
![screen shot 2015-06-14 at 10 34 16 am](https://cloud.githubusercontent.com/assets/2287437/8148973/1781553c-1282-11e5-9f72-5b65a1aec2be.png)

I'd expect the window to be transparent and the frame to be intact.  Is this possible on OS X?

Only when I set `frame: false` does the window allow transparency.
![screen shot 2015-06-14 at 10 22 34 am](https://cloud.githubusercontent.com/assets/2287437/8148985/bb932cb8-1282-11e5-8abf-bb362ef5b620.png)

Ideally I'd like to keep the frame but still change the opacity of the editor.

**Comment by zcbenz** [comment]
As stated in the document, transparent window only works without frame.
