### ISSUE TITLE
Base directory for `node_modules` with Node integration

### ISSUE THREAD

**Issue by mattdesl** [atom/electron#1971]
I'm trying to figure out how to configure the base directory for the Node-integrated `require()` statements in the browser process. My end goal is running Electron on regular Node.js sources that may require native modules (like fs or node-opencv). (The [gory details](https://gist.github.com/mattdesl/2bb568dc3a5d02121835).)

With the following, for example, after `npm install save-pixels --save`

```js
var save = require('save-pixels')
```

This works when I run `electron server.js` from the same directory. However, say I am running this from an entirely different folder with its own modules:

```
projects
    app/
        node_modules
        server.js
    my-module/
        node_modules
```

Trying to run `electron ../app/server.js` from the `my-module` folder still seems to look inside `app/node_modules` rather than the calling folder.

Thanks. :smile:

**Comment by zcbenz** [comment]
You can set `NODE_PATH` environment variable to override the default search paths.

Electron apps are mostly used as GUI apps, so current directory usually doesn't affect module search paths.

**Comment by mattdesl** [comment]
Thanks !
