### ISSUE TITLE
Best practice - how to use global shortcut but just contained to the focused BrowserWindow?

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#1972]
I love the API for global shortcuts - is it possible to somehow use a similar API to add shortcuts to a focused BrowserWindow?

**Comment by hokein** [comment]
Unfortunately, there is no API for this currently. The global-shortcut API will listen system key event even the BrowserWindow isn't focused.

**Comment by paulcbetts** [comment]
@kirkouimet Create a top-level menu item for it

**Comment by sindresorhus** [comment]
I think there should be an API for this. I've also had the need to create shortcuts just for the focused window, without having a menu for it.

**Comment by zcbenz** [comment]
This is a duplicate of #1334.

**Comment by niedzielski** [comment]
In my simple app, I created the accelerators I wanted via menu items but then call `BrowserWindow.setMenuBarVisibility(false);` to hide the whole menu bar.
