### ISSUE TITLE
electron cant start - NSURLErrorDomain

### ISSUE THREAD

**Issue by Zougi** [atom/electron#1973]
When I start electron with "$ electron" it does nothing.
When I start electron on my project with "$ electron ."
it says:
0615/102324:ERROR:http_transport_mac.mm(186)] Could not connect to the server. (NSURLErrorDomain -1004)

I'm on Mac OSX 10.8.5 and I installed electron with command line "$ npm install electron-prebuilt -g"
electron version: v0.27.2
npm version: 2.11.0
iosj version: v2.2.1

are prebuild binaries compatible with Mac OSX 10.8.5 ?

**Comment by zcbenz** [comment]
Can you download `electron-v0.28.1-darwin-x64.zip` from https://github.com/atom/electron/releases/tag/v0.28.1 and try double-clicking the extracted app?

**Comment by Zougi** [comment]
I downloaded this package, Electron.app launches =). If I do a "$ /Applications/Electron.app/Contents/MacOS/Electron .", my app starts! Thanks.

Also, I did a "$ npm install electron-prebuilt@0.28.1 -g", and got the same error. Am I the only one having problems with electron-prebuilt package?

**Comment by Zougi** [comment]
I believe the electron prebuilt package comes from the following repo: https://github.com/mafintosh/electron-prebuilt  I'll open the issue there and I thank you again for getting me started with electron zcbenz.
