### ISSUE TITLE
Control volume

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#1976]
Is it possible to have a input slider that can control the system volume?

e.g.

`<input id="Volume" name="Volume" type="range" min="0" max="100">`

I haven't been able to find anything in the documentation regarding this.

Thanks

**Comment by zcbenz** [comment]
You need to use some external programs or write a native node module to control system volume, there is no such APIs in Electron.

**Comment by warmhug** [comment]
I find electron's maximum volume is smaller than other native video players. This is very depressing. Every time I need to adjust the system volume to the maximum. But other native video players can enlarge the current volume.

**Comment by eroltoker** [comment]
@zcbenz has there been  any update to this since it was last discussed 2 years ago?  Is there still no way to access/detect/modify native audio volume?

**Comment by Imior** [comment]
We can use Node.js modules to control the system output volume, for example [loudness](https://www.npmjs.com/package/loudness).
