### ISSUE TITLE
List and control atom apps

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#1977]
We have a customer that wants us to build several Electron-powered apps for a games system running on Windows. We will have a main app that will house the menu and clicking on a menu item will launch the exe for that game chosen.

Is it possible to be able to send commands from one application to another? And list the applications open (say have a certain name). So that we can control them from one application.

**Comment by paulcbetts** [comment]
There's no built-in way to do this, I'd have a look at how other Desktop applications accomplish this task - one node.js-friendly way is to use named pipes on Windows

**Comment by iamdriz** [comment]
Can node.js access the task manager? And then I could list the apps.

All I'm wanting to do is be able to see which apps I have open. And then be able to switch to them via a menu if they are (or open it if not) and be able to close it.

**Comment by zcbenz** [comment]
You can use named pipe to communicate with other applications. For listing running apps I believe there are some command line utilities you can call and get output from.
