### ISSUE TITLE
Error ELIFECYCLE when using npm i electron-prebuilt --save-dev

### ISSUE THREAD

**Issue by Kep0a** [atom/electron#1978]
Total newbie to this stuff, I'm trying to install electron through command prompt to a folder, however when using that command it all goes well but ends with a bunch of errors, and deletes the node_modules folder. I've done some googling but a lot of answers were vague and the issue was resolved by reinstalling, which i've done on both of my computers (Windows 8.1) to no success.

I posted on over at npm/npm yesterday but got no response, any help is appreciated, thank you. [Here's the error log.](https://drive.google.com/file/d/0ByGR708ivvUuOU10bXJrLWRYVE0/view)

**Comment by zcbenz** [comment]
`electron-prebuilt` is no different to a normal module, so it should be related to configurations of your Windows machine. I suggest just downloading from [the releases page](https://github.com/atom/electron/releases) before you find out way to fix this.

**Comment by Kep0a** [comment]
That's what I was trying, I eventually figured out I cant use black slashes for whatever reason to enter the location of electron. Thanks for responding though @zcbenz to a newbie haha.
