### ISSUE TITLE
window focus/blur event on the app instance

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#1985]
I would be useful to have a focus/blur window event on the `app` instance. I can already subscribe to the focus/blur event on each window and act accordingly, but it would be a lot nicer to just be able to do:

```js
var app = require('app');

app.on('focused-window', function (focusedWindow) {
  doSomethingWithTheFocusedWindow(focusedWindow);
});
```

**Comment by paulcbetts** [comment]
:+1:

**Comment by davej** [comment]
Would an app `activate`/`deactivate` event make more sense (currently there is `activate-with-no-open-windows`)?

I tend to think that window focus/blur should be handled by the window and only the window. It's trivial to create this your own event on the app instance if needed (using the `remote` module) or just use vanilla IPC. Also there are things like the page visibility API, would those events be exposed on the app instance too? Seems like it could be a rabbit hole.

**Comment by jhuckaby** [comment]
Did we ever get app `activate` / `deactivate` events?  I see `activate` the [app docs](https://github.com/atom/electron/blob/master/docs/api/app.md), but it's only for OS X, and there is no `deactivate` event, as far as I can tell.

Specifically, I need to know when the _application_ itself is activated or deactivated, not at the window level.  Specifically, I need to hide all my `alwaysOnTop` windows on app deactivate, and show them again on app activate.  But I don't want to take any action if the user is just focusing / blurring windows within my app.

Thanks!
