### ISSUE TITLE
App immediately crashes

### ISSUE THREAD

**Issue by TPackard** [atom/electron#1986]
When I try to run the quickstart tutorial code on Electron (version 0.28.1 on Mac OSX Yosemite), it results in the following error:
![screen shot 2015-06-15 at 8 25 27 pm](https://cloud.githubusercontent.com/assets/5660066/8175288/01625dc0-139d-11e5-96a4-51f054e507fc.png)
It looks like the problem is in Electron itself, is there any fix?

**Comment by zcbenz** [comment]
Your `package.son` is invalid, we should have a better error message though.
