### ISSUE TITLE
Chinese font not working

### ISSUE THREAD

**Issue by RCyril** [atom/electron#1987]
Hi,

Chinese font not working in my app and all symbols are replaced by squares...
An Idea ? 

Thanks
Cyril

**Comment by zcbenz** [comment]
This is a duplicate of #1605.

Currently you have to choose a font in your CSS to work around it.

**Comment by tworry** [comment]
I've download NotoSansSC.otf,and put it in my app,but the Chinese font still not working while English characters is Noto Sans.how can I make it work?have 2 be woff?

**Comment by skelly2015** [comment]
I encountered with this same issue. Is this issue fixed in Electron or do we have to always use the workaround? I tried to use monospace font-family but it didn't work for me.

**Comment by mankeheaven** [comment]
4 years later, it's still not be resolved.
chinese font can not be rendered properly as rendered with browser.
