### ISSUE TITLE
Auto-updater: download progress?

### ISSUE THREAD

**Issue by pracucci** [atom/electron#1989]
Is there any way to get the auto-updater download progress (in any unit), so that we can display it while downloading?

**Comment by zcbenz** [comment]
The auto updater is a thin wrapper around [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac), you can request this feature there.

**Comment by joshuapinter** [comment]
Btw, you can't do this via autoUpdate so we ended up doing the download ourselves using @sindresorhus's brilliant https://github.com/sindresorhus/electron-dl and then just pointing autoUpdate's URL to the local temp directory.

![FileDownload - Mar-14-2019 22-43-07](https://user-images.githubusercontent.com/180819/54557569-1006ca00-4981-11e9-831f-d3e961f7d2e3.gif)

I wish this was built-in but doesn't look like that's gonna happen anytime soon so probably best to handle it yourself.
