### ISSUE TITLE
Notifications not appearing on OS X in Chrome 43

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1991]
Notifications should work on OS X but are a no-op:

```js
new Notification("Where am I?");
```

**Comment by ekonstantinidis** [comment]
@paulcbetts I'm using electron 0.27.2 and I thought notifications are working properly([example](https://github.com/ekonstantinidis/gitify/blob/master/src/js/stores/sound-notification.js#L27))? You can have a look at https://github.com/ekonstantinidis/gitify (will soon release a version that includes notifications - for now it's just in `master`)

**Comment by paulcbetts** [comment]
@ekonstantinidis I believe that they stopped working in the 0.28.x series

**Comment by ekonstantinidis** [comment]
@paulcbetts Oh ok! Was just about to jump to 0.28.x (before release) - will update and test to confirm the issue.

**Comment by paulcbetts** [comment]
NEVER MIND I AM AN IDIOT NOTHING TO SEE HERE
