### ISSUE TITLE
Documentation site out of date

### ISSUE THREAD

**Issue by johnmuhl** [atom/electron#1993]
http://electron.atom.io/docs/ does not list 0.28.x versions and /docs/latest goes to 0.27.0.

**Comment by zcbenz** [comment]
@jlord Can we add web hook for the releases event and update the documentation site automatically?

**Comment by jlord** [comment]
Right now it's just a manual script to run on `atom/electron.atom.io` when a new version comes out but making it automatic would be good :+1:
