### ISSUE TITLE
create-dist.py with rebranded electron

### ISSUE THREAD

**Issue by mcdermed** [atom/electron#1999]
Having an issue building a rebranded version of electron using the create-dist.py script.
There's no mention of using create-dist.py in the rebranding tutorial so this may be a new feature request for the script. 
https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md#rebranding-by-rebuilding-electron-from-source

Ideally we could use the `create-dist.py --target myapp` flag to use our custom branding.

```
GYP_DEFINES="project_name=myapp product_name=myApp"
$ ./script/build.py -t myapp
...
$ ./script/create-dist.py
...
ninja: Entering directory out/R
ninja: error: unknown target 'electron'
```

**Comment by zcbenz** [comment]
Now for rebanding you can just edit the `atom.gyp`, I'll update the documents.
