### ISSUE TITLE
Electron crashes with "Failed to send message to ack remove remote endpoint" while --debug-brk=5858

### ISSUE THREAD

**Issue by ChinmayPatel** [atom/electron#2000]
## Steps to Reproduce:
- create electron-start.js file
```
var app = require('app');
var BrowserWindow = require('browser-window');

app.on('ready', function(){
  var mainWindow = new BrowserWindow({
    width: 1400,
    height: 800,
  })
  mainWindow.loadUrl('file://' + __dirname + '/src/temp.index.html')
})
```

- Start the node inspector
```
node-inspector
```
it outputs

> Node Inspector v0.10.2
> Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.

- Run the app
```
electron ./app/electron-start.js --debug-brk=5858
```
It opens the app usual.

- Load the debugger page http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 in browser. 
The app will crash and print:

> [26098:0617/123027:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
> [26098:0617/123027:WARNING:channel.cc(549)] Failed to send message to ack remove remote > endpoint (local ID 2147483648, remote ID 2)
[26067:0617/123027:ERROR:channel.cc(300)] RawChannel read error (connection broken)

This happens every time I refresh the debugging page. Am I doing anything wrong here? What would be the reason behind it? How can we solve it?

**Comment by zcbenz** [comment]
You window automatically closes because it has been garbage collected, you can try:

```js
var mainWindow = null;
app.on('ready', function(){
  mainWindow = new BrowserWindow();
});
```

**Comment by ChinmayPatel** [comment]
Thanks @zcbenz for quick response. Your solution worked and solved the crashing issue.

However, it did not solve the debugging issue. I still cannot pause on the first line of JS execution. Any idea?

**Comment by TildaUser** [comment]
```javascript
var app = require('app')
var BrowserWindow = require('browser-window')
var mainWindow = null;

app.on('ready', function() {
  var mainWindow = new BrowserWindow({
    width: 600,
    height: 480
  })

  mainWindow.loadUrl('file://' + __dirname + '/public/index.html')
})
```

same problem
