### ISSUE TITLE
Communicate between apps

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2007]
If I have two Electron apps running, can I send messages between them?

**Comment by frankhale** [comment]
What about this? 

http://stackoverflow.com/questions/10213501/node-js-communicating-between-two-different-processes

https://github.com/joyent/node/wiki/modules#message-queue

https://github.com/substack/dnode

**Comment by maxkueng** [comment]
I'm with @frankhale on this. Electron apps can communicate with each other the same way any Node.js apps can communicate together.

Depending on whether your two apps are on the same host, the same network, or different networks you may choose different technologies.

**Comment by zcbenz** [comment]
The popular way is named pipe or file socket.

**Comment by iamdriz** [comment]
I'm struggling to understand this... basically if I have the following applications running:

~~~
Dashboard.exe
Game1.exe
Game2.exe
Game3.exe
~~~

And I fire an event inside Game3.exe, I want Dashboard.exe to react to this event.

According to the stackoverflow question shared by @frankhale http://stackoverflow.com/questions/10213501/node-js-communicating-between-two-different-processes

To listen and send messages across processes you can delcare it via the fork... e.g.

~~~
var fork = require('child_process').fork;
var example1 = fork(__dirname + '/example1.js');
~~~

The problem is... is that not assuming that I have launched the process from one of the other processes? Rather than both were called individually.

**Comment by iamdriz** [comment]
I'm going to look at giving this a try: https://github.com/weixiyen/messenger.js as it seems to do what I want... will report back here with results.

**Comment by iamdriz** [comment]
Boom! I can confirm that Messenger.js is exactly what I need! It doesn't matter who or when the apps were opened so long as they all listen on the same port they can communicate :)
