### ISSUE TITLE
Removing initial "Electron" from window title

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#2008]
After creating my app and deploying under /Contents/Resources/app/ I notice that the application window briefly displays "Electron" before changing to the `title` of my /app/index.html file.

Where can I override that initial display of "Electron"? I thought changing the `title` of  default_app/index.html would do the trick, but it doesn't seem to help.

**Comment by sbruchmann** [comment]
When you instantiate your main application window in the browser process, set the `title` property of the `BrowserWindow` to your desired value. For instance `let mainWindow = new BrowserWindow({ title: 'My Application' })`. Tip: Use [app.getName()](https://github.com/atom/electron/blob/master/docs/api/app.md#appgetname) here.
