### ISSUE TITLE
"Uncaught ReferenceError: require is not defined" in a Worker Process

### ISSUE THREAD

**Issue by mmacedoeu** [atom/electron#2013]
soapclient.js 

    var remote = require('remote');
    var soap = remote.require('soap');
    var url = 'http://www.w3schools.com/webservices/tempconvert.asmx?WSDL';

    self.addEventListener('message', function(e) {
  	    soap.createClient(url, function(err, client) {
          client.CelsiusToFahrenheit(e.data, function(err, result) {
      		    self.postMessage(result);
              console.log(result);
      });
 	});  
    }, false);

index.html

    <!doctype html>
    <html>
    	<head>
    		<meta charset="utf-8">
    		<title>Electron boilerplate</title>
    		<link rel="stylesheet" href="index.css">
    	</head>
    	<body>
        <script>
        	var soapworker = new Worker('soapclient.js');
    		soapworker.addEventListener('message', function(e) {
      			console.log('Worker said: ', e.data);
    		}, false);
    
        	soapworker.postMessage();
        	soapworker.postMessage(200);
        </script>	
    		<div class="container">
    			<header>
    				<h1>Electron boilerplate</h1>
        We are using io.js <script>document.write(process.version)</script>
        and Electron <script>document.write(process.versions['electron'])</script>.				
    			</header>
    			<section class="main"></section>
    			<footer></footer>
    		</div>
    	</body>
    </html>

**Comment by bengotow** [comment]
Hi @mmacedoeu — unfortunately you can't use Node in Web Workers. If you want to create a worker that has access to NodeJS, you can use https://nodejs.org/api/child_process.html to fork the node process.

**Comment by justinmchase** [comment]
@bengotow Do forked children support Transferrable Objects like Workers do?

**Comment by justinmchase** [comment]
Answer to my above question is no they don't.

Also, I just wanted to point it out for posterity but I think you can accomplish this by using the [remote](https://github.com/atom/electron/blob/master/docs/api/remote.md) api to create a hidden new window and do your work there. You won't be able to send transferrable objects still, but you will have access to the browser apis there and can use them in the hidden window (such as audio apis). You can communicate via ipc with that window.

**Comment by trusktr** [comment]
In case anyone stumbles here, it is now supported. Here's a minimal working example: https://github.com/trusktr/electron-web-worker-example.
