### ISSUE TITLE
Error when calling AutoUpdater.removeAllListeners()

### ISSUE THREAD

**Issue by bostondv** [atom/electron#2016]
When calling `AutoUpdater.removeAllListeners()` after `checkForUpdates()` has been called and error dialog appears

```
Uncaught Exception:
Error: Uncaught, unspecified "error" event.
    at EventEmitter.emit (events.js:143:13)
```

It does successfully cancel the auto update events though.

**Comment by zcbenz** [comment]
This behavior matches Node's documents:

> When an EventEmitter instance experiences an error, the typical action is to emit an 'error' event. Error events are treated as a special case in node. If there is no listener for it, then the default action is to print a stack trace and exit the program.
