### ISSUE TITLE
Closing dev tools on transparent window makes it unresponsive

### ISSUE THREAD

**Issue by steelbrain** [atom/electron#2022]
It works when I remove `transparent: true, frame: false`, but not when it's that.
Opening dev tools works, but as soon as you call the `closeDevTools` on the `BrowserWindow` it hangs.

**Comment by hokein** [comment]
Which OS do you use? I didn't reproduce it on OS X.

**Comment by zcbenz** [comment]
Closing unless there is more information provided.
