### ISSUE TITLE
How do I link a custom compiled libchromiumcontent with Electron?

### ISSUE THREAD

**Issue by frankhale** [atom/electron#2023]
I'm hesitant to post this here but there is little chatter in the #atom-shell IRC channel and I don't know if the Electron channel on discuss.atom.io would be the appropriate place for this. 

I have a need to patch libchromiumcontent and link it with Electron but I currently don't know how to do that. The build.py for Electron assumes I'm going to download a precompiled version. I've successfully compiled a custom libchromiumcontent and just need some pointers on how to take that and run build.py on Electron so that it links in my custom version. 

When I look at the libchromiumcontent module in the vendor folder in Brightray it doesn't contain all of the same files so I don't know if I can just dump in my compiled fork there. Is that how it'd be done?

I think once this development workflow is mentioned here it would be great to put this as an additional development document so that others wishing to do some hard core development or help out could easily reference it to get started.

**Comment by frankhale** [comment]
Actually I think I should just replace the libchromiumcontent module in the vendor folder of Brightray with the one I've compiled.

**Comment by frankhale** [comment]
Actually on second thought I don't think this is the way to do it. It seems it doesn't matter what is in the Brightray folder because bootstrapping Electron will just use what it downloads instead of using what I put there.

**Comment by frankhale** [comment]
This looks promising ->

```
electron\vendor\brightray\vendor\download\libchromiumcontent
```

rather than

```
electron\vendor\brightray\vendor\libchromiumcontent
```

Looks like doing a python script\create-dist.py is what I need to do in libchromiumcontent and then dump it in the first directory I listed above.

**Comment by hokein** [comment]
You can use the `script/create-dist.py` to make distributions for your custom libchromiumcontent, and unzip it to `electron/vendor/brightray/vendor/download/libchromiumcontent` dir.

> It seems it doesn't matter what is in the Brightray folder because bootstrapping Electron will just use what it downloads instead of using what I put there.

The `boostrap.py` script will checkout the libchromiumcontent version everytime it runs. So you need to disable the download part of code in `electron/vendor/brightray/vendor/libchromiumcontent/script/download`.

**Comment by frankhale** [comment]
Thank you! I'm doing a create-dist right now. I'll disable the download as well.

**Comment by frankhale** [comment]
Looks like I still have some stuff to learn. Even though I am able to compile libchromiumcontent from master I am not able to get it to link against Electron 0.28.2. I've tried multiple times. I'll try again tomorrow. I can get Electron 0.28.2 to build fine against the libchromiumcontent it's expecting and that it downloads but not with my hand compiled one. 

In the morning I'll delete all the code, clone it again and start over. Hopefully whatever is going wrong will work itself out.

**Comment by hokein** [comment]
@frankhale 
Instead of building the `master` branch of libchromiumcontent, you should build the `atom` branch, which is used in `Electron`.

**Comment by frankhale** [comment]
HAHA, I didn't even look at the branches. Thank you! I will definitely give this a shot in the morning. Hopefully my luck will be better. =)

**Comment by frankhale** [comment]
@hokein, this worked well for me. Thanks!

**Comment by frankhale** [comment]
Is it customary for me to write my libchromiumcontent patch, recompile, create dist, move dist to Electron's code, recompile Electron to test? Because that process is very time consuming. I'm okay with it but I want to make sure that I am not shooting myself in the foot.

**Comment by hokein** [comment]
I suppose you have to do it if you customize `libchromiumcontent`.

**Comment by frankhale** [comment]
No worries, just wanted to see if I was doing something really crazy.

**Comment by zcbenz** [comment]
There is a `-u` option in `bootstrap.py` that can be used to custom the location of libchromiumcontent. This is what I usually do:

```bash
$ cd /path/to/libchromiumcontent
$ ./script/create-dist
$ mkdir -p win/x64/thecommithashusedbyelectron
$ mv libchromiumcontent* win/x64/thecommithashusedbyelectron
$ cd /path/to/electron
$ ./script/bootstrap.py -v -u file:///path/to/libchromiumcontent/
```

If the bootstrap script fails you need to check if `thecommithashusedbyelectron` matches the one used by electron.

It sucks but since I rarely test electron with custom libchromiumcontent it works fine for me so far.
