### ISSUE TITLE
How to open two browser windows using separate context?

### ISSUE THREAD

**Issue by gajus** [atom/electron#2032]
I would like to open two windows that do not share session between them, e.g. I expect that using the following code opening github.com each window would be assigned different session IDs.

I would like to have some method to communicate between two windows.

```js
var app = require('app'),
    BrowserWindow = require('browser-window');

app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('ready', function () {
    var mainWindow;

    mainWindow = new BrowserWindow({width: 800, height: 600, frame: false, x: 100, y: 100, resizable: false});
    mainWindow.loadUrl('https://github.com/login');
    
    mainWindow.on('closed', function () {
        mainWindow = null;
    });
});

app.on('ready', function () {
    var mainWindow;

    mainWindow = new BrowserWindow({width: 800, height: 600, frame: false, x: 200, y: 200, resizable: false});
    mainWindow.loadUrl('https://github.com/login');
    
    mainWindow.on('closed', function () {
        mainWindow = null;
    });
});
```

**Comment by zcbenz** [comment]
It is currently tracked at #959.

**Comment by gajus** [comment]
@zcbenz I don't agree. While the title of the issue is somewhat relevant, the body of the issue is completely irrelevant:

> When I use a webview and log in to a website (let's say github) it appears the session/cookie information is lost after restarting the application. Is there a way to enable this on the webview?
