### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#2033]
I'm getting this error in Windows 8.1 when I run my app using the .exe:

![image](https://cloud.githubusercontent.com/assets/62191/8295010/838bebe2-18f5-11e5-97f4-2424238160f4.png)

When I run my app from the command line it works with no problem.

Any ideas on what could be causing the permissions issue or the best way on how I can debug it further?

**Comment by zcbenz** [comment]
You can set the devtools to catch uncaught exceptions and see the stack trace there.
<img width="912" alt="screen shot 2015-06-23 at 11 07 40 am" src="https://cloud.githubusercontent.com/assets/639601/8298194/56171102-1998-11e5-8cd7-f4fe7d448a52.png">

**Comment by kirkouimet** [comment]
@zcbenz thank you! So here is what I discovered using dev tools:

In Windows 8.1, this is my code causing the problem:

`process.stdout.write('hi')`

[Good] When I run electron from the command line, this code works without a problem and I see 'hi' in my command prompt.

[Bad] When I run a packaged version of my app by running the .exe I get this error:

`Uncaught Error: EPERM: operation not permitted, write`

I think this makes sense because there is no stdout to write to since there is no attached command prompt?

I inspected the `process.stdout` property to see if it had any properties I could use to conditionally call process.stdout based on whether or not there is a command prompt present. I couldn't find anything as `process.stdout` shows as being writable with no command prompt even though it throws the EPERM exception:

![image](https://cloud.githubusercontent.com/assets/62191/8310897/c8684e44-1987-11e5-98b7-4c94357fb2e5.png)

Any ideas on how I could go about solving this one? Would love to use this as a learning opportunity for me as well as to help improve Electron.

Thanks!

**Comment by zcbenz** [comment]
That's because on Windows a GUI program does not have console attached when it is not opened in console, which means you actually don't have stdout. So writing to stdout under this situation will throw the exception.

**Comment by kirkouimetsnapchat** [comment]
@zcbenz is there anyway for me to programmatically detect whether or not there is a console attached?

**Comment by zcbenz** [comment]
There should be some win32 API for this, but I think the best solution is to use console.log for logging, writing to stdout is quite tricky on Windows.

**Comment by kirkouimet** [comment]
My solution is pretty bad, but will do this for now until I learn more about win32 APIs for detecting if stdout is available to write to.

    try {
        stdout.write('my string');
    }
    catch(exception) {
        console.log(string);
    }

**Comment by ang3lx** [comment]
@kirkouimet i've this problem with sql.js that use stdout.
how can fix with your solution?

**Comment by kirkouimetsnapchat** [comment]
@ang3lx I think you are screwed unless you can somehow configure sql.js to use `console.log` instead of stdout.write. That is unless @zcbenz has any new ideas since we last talked

**Comment by kirkouimet** [comment]
@ang3lx I think you are screwed unless you can somehow configure sql.js to use console.log instead of stdout.write. That is unless @zcbenz has any new ideas since we last talked

**Comment by JimmyBoh** [comment]
I had this issue with the `Console` transport for `Winston`. The workaround was quite simple, don't enable the `stdout` transport when in production!

**Comment by jayralencar** [comment]
Hi, I solved it like this:
` process.stderr.write = console.error.bind(console); 
process.stdout.write = console.log.bind(console); //before requiring sql.js
var SQL = require('sql.js'); `
