### ISSUE TITLE
How to allow external packages to use original-fs

### ISSUE THREAD

**Issue by Gregg8** [atom/electron#2035]
Updated description in next comment...

**Comment by Gregg8** [comment]
Within Electron we are attempting to use a library (adm-zip) which uses `fs`. This library ends up using Electron's version of `fs`  and not `original-fs`.

But (for various reasons) that's a problem. We want adm-zip to get the `original-fs` version of `fs`. 

Is there any way to temporarily reinstate/rebind `fs` to `original-fs` when we call the library?


Further background: We're using adm-zip to unzip a file which contains a .asar file and the Electron `fs` fails on that file.

**Comment by zcbenz** [comment]
You can do it by monkey-patch:

```coffee
fs = require('fs')
originalFs = require('original-fs')
for name, method of originalFs
  fs[name] = method
```

**Comment by Gregg8** [comment]
That did the trick, many thanks.

**Comment by marwanhilmi** [comment]
Apologies to revive a closed issue, @zcbenz, I tried your suggestion but get an error:
`TypeError: Cannot assign to read only property 'F_OK' of #<Object>` when attempting to do `fs[name] = method`, am I missing something obvious?

If do a monkey-patch like this - what is a good practice to ensure you aren't breaking something else? Do you need to revert the monkey-patch after including the modules that need `original-fs`? For example, if I do something like:
```
// monkey patch fs
var rimraf = require('rimraf') // needs 'original-fs'
// then something else that requires Electron's fs happens, is it broken now?
// should I revert monkey patch now?
```

Any suggestions for best practice around this? This has definitely been problematic for me - I've been forking modules and adding `var fs = process.versions.electron ? require('original-fs') : require('fs')` which is obviously not ideal.

**Comment by Gregg8** [comment]
My project is in ClojureScript, not pure JS otherwise I would provide my source code, but what I do is patch just before the calls to my external lib then unpatch once they're done. Seems the safest thing to do.

**Comment by arnaudlamy** [comment]
> You can do it by monkey-patch:
> 
> ```coffee
> fs = require('fs')
> originalFs = require('original-fs')
> for name, method of originalFs
>   fs[name] = method
> ```

Hello, 

I'm facing the same issue and I'm a beginner. Can you help on how to apply your patch?


Thanks,
