### ISSUE TITLE
Possible to do find within a page? Cmd/Ctrl+F?

### ISSUE THREAD

**Issue by somebody32** [atom/electron#2037]
Hi!

Is it possible to do find within a page with highlighting, like you have in chrome when pressing cmd+f?

**Comment by zcbenz** [comment]
No it is not supported in Electron.

**Comment by steverandy** [comment]
@zcbenz can you provide some hints on how to implement find with highlighting on top of electron? Thanks.

**Comment by pfraze** [comment]
+1 this is something we could use

**Comment by pfraze** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/find appears to work

**Comment by mattwoodnyc** [comment]
@pfraze, @steverandy — given that electron can use regular events, you'd need to create your own *cmd+f* — http://unixpapa.com/js/key.html

**Comment by pfraze** [comment]
@mattwoodnyc yeah doing that now -- I just didnt know `window.find` was a native web api. That's all you need

**Comment by ArktekniK** [comment]
Just came across this and it appears that window.find always returns false ....

**Comment by hasusuf** [comment]
+1

**Comment by tenshis** [comment]
@pfrazee , any chance you could share the _cmd/ctrl+f_ command you built with the world?

**Comment by pfrazee** [comment]
@tenshis it's gotten pretty easy now with the electron apis http://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options

**Comment by cardwizard** [comment]
You can use jquery libraries like mark.js to do this.
