### ISSUE TITLE
Can't force-quit or command-tab Electron app in kiosk mode if run via AppleScript

### ISSUE THREAD

**Issue by cylinderStudio** [atom/electron#2040]
I have an Electron app (client-side JavaScript only, no nodejs)  where I set mainWindow this way:

``` mainWindow = new BrowserWindow({width: 800, height: 600, kiosk: true}); ```

I've been executing by putting the app folder in Electron.app/Contents/Resources/ and double-clicking Electron and it always works fine.

However, oddly enough, if I execute the application via an AppleScript that I have:

``` tell application "Electron" run ```

the app runs, but I can't get out of it or regain control of my Mac. I can't force-quit by trying command-option-escape, or bring up the menu bar by moving the mouse to the top of the screen, or use command-tab to tab through the list of applications. The only thing I'm able to do is press the power button to bring up the restart/shutdown/sleep menu and try and restart, and there, restart is cancelled by Electron.

Electron: v0.28.2-darwin-x64
Mac OS: v10.9.5

**Comment by zcbenz** [comment]
The kiosk mode of Electron disables menu and keyboard shortcuts for quitting, you should provide a way to quit in your app.

**Comment by cylinderStudio** [comment]
Given that it is a kiosk application (used by customers in a showroom), I can't provide a method on the screen for it to quit, or else customers will have the ability to stop the kiosk from running.

**Comment by zcbenz** [comment]
You can add a secret shortcut or some password for quitting, I think a real kiosk application should not be able to quit without the ways provided by the developers?

**Comment by cylinderStudio** [comment]
Well, we can agree to disagree. I build these touchscreen kiosk applications in many retail scenarios, and in almost every case, customers (and often kids) tap around on touchscreens looking for ways to mess up the application or in rare occasions, hack it somehow. So we typically do not afford away to quit a kiosk anywhere in the interface itself. Keyboards, mice and other input devices are not available to the customers in the touchscreen scenarios, only to us as the developers. So we quit the applications when necessary by force-quit via the keyboard, or in remote access/screen sharing.

At any rate, I found the workaround for me was to simply use fullscreen: true instead of kiosk: true, and that is fine for my purposes. Thanks for your response.
