### ISSUE TITLE
Calling javascript from an embedded swf file-- SecurityError 2060

### ISSUE THREAD

**Issue by leshow** [atom/electron#2041]
Has anyone had any success with this? I'm getting a Security Error 2060 when trying to call javascript from an embedded swf file, even with allowscriptaccess set to "always"

The swf file is local.
```
<script>
    var testMessage = function() { return 'working'; }
  </script>
```

the actionscript is making the call via:

```
ExternalInterface.call("testMessage");
```

html for the swf file:
```
    	<object id="myflash" width="550" height="400">
            <embed src="sample.swf"
            type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="500" height="400"></embed>
        	<param name="movie" value="sample.swf" />
        	<param name="bgcolor" value="#ffffff" />
        	<param name="height" value="550" />
        	<param name="width" value="400" />
        	<param name="quality" value="high" />
        	<param name="menu" value="false" />
        	<param name="allowscriptaccess" value="always" />
    	</object>
```

**Comment by simongregory** [comment]
I don't believe this is a bug with electron. Can you confirm you are trying to run your swf from the file system? You should see the same error if you run your html and swf in Chrome. 

Adobe's sandboxing docs are difficult to decipher as behaviour has evolved and there are differences between the flash players (i.e. Pepper), but if you use the 'Global Security Settings' in the [Settings Manager][] you can open the security sandbox up to allow access to specific directories on your filesystem.

In an electron app I got the `ExternalInterface.call` working by visiting the [Settings Manager][] using a `<webview>`.  

Clearly for this to function properly in a release of your app you'll have to work out how to do this programmatically. If there isn't a settings file (have a look through Adobe's docs) then there's a outside chance you can write the settings.sol (a binary format - basically asmf with different file headers). For me the file was here:
```
/Users/USER/Library/Application Support/ELECTRON-APP-NAME/Pepper Data/Shockwave Flash/WritableRoot/#SharedObjects/7BG6NDY2/macromedia.com/support/flashplayer/sys/settings.sol
```
However I doubt the '7BG6NDY2' in the path is predictable, it will be a security measure to force a visit to the [Settings Manager][].

An alternative would be to try running a web server locally and load the page in from there. 

[Settings Manager]: http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04a.html

**Comment by simongregory** [comment]
It's possible to use the [User Flash Player Trust directory](http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7c85.html#WSD2DCB535-92C6-49ff-8954-D8D5130404F1) to allow the trusted access you need.

Creating `/Users/USER/Library/Application Support/ELECTRON-APP-NAME/Pepper Data/Shockwave Flash/WritableRoot/#Security/FlashPlayerTrust/trust.cfg` with the following contents worked for me:

```
# Trust files in the following directories:

/Users/simon/code/nip/
```

Where nip is an electron project containing a copy of the prebuilt electron binary.

**Comment by leshow** [comment]
Thank you for responding, this is a great help.

I've been running my app with the electron-prebuilt binary so there isn't a Pepper/ directory in my project. How are you building your project so that the flash plugin is located within the project directory?

**Comment by leshow** [comment]
sorry, I misunderstood your second post.

is it possible to create the trust.cfg file programmatically with electron? I see you're on OSX, I'm not sure where the location of that file would be on linux, or if windows needing administrator privileges to alter C:\Windows\System32\Macromed\Flash\FlashPlayerTrust would affect attempting to add the file programmatically. I'll test on windows and see if I can find the correct directory under linux.

**Comment by leshow** [comment]
To anyone who encounters this issue, I've worked out the proper directory on windows as well:

```
C:\Users\USERNAME\AppData\Roaming\ELECTRON-APP-NAME\Pepper Data\Shockwave Flash\WritableRoot\
```
the following must be created in that directory:
```
\#Security\FlashPlayerTrust\
```
Along with a .cfg file (of any name) containing to path to the electron app folder/swf file location

I'll continue looking on linux and see where the correct location is there

**Comment by simongregory** [comment]
As I mentioned Adobe's docs on this are misleading. They were likely written before browser manufacturers started to tighten the security sandboxes. So you have to interpret them and go hunting. 

The Flash Pepper plugin (PPAPI) has a further restricted sandbox, by the looks of it the other Flash players can reach into a shared system location - this will be the paths you found in the linked docs.

If you browse through `/Users/USER/Library/Application Support/` and look for Chrome, Chromium, Electron, Atom Shell Default App, etc then if any of them have loaded the Flash player there'll be a `Pepper Data` directory in there. 

It looks like you've already discovered the windows location, you'll most likely find that using `app.getPath('appData')` gets you close on all OS's - details in the [electron app api docs](https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname). 

One thing to check would be that the Windows paths are consistent the different versions.

You should be successful creating the directories and the trust files programmatically with Electron, or an installer, as the permission level needed will the same to run the app.

**Comment by zcbenz** [comment]
I'm closing this since it is not a bug of electron, thanks guys for your detailed instructions!

**Comment by leshow** [comment]
For completeness:

app.getPath('appData') on linux is XDG_CONFIG_HOME, usually .config.

meaning the linux path for this is ~/.config/app-name/Pepper Data/Shockwave Flash/WritableRoot/#Security/FlashPlayerTrust/

adding the .cfg file with the exception there works, I've tested it. 

Thanks @simongregory for your help.

**Comment by MatheusRodrigues301** [comment]
Hi guys,

I'm trying load a flash into electron on ubuntu, but it isn't works.
I tried all the libpepflashplayer versions, but with no sucess.
Can someone help me ? On windows works well...

--main--
// Modules to control application life and create native browser window
const { app, BrowserWindow, ipcMain, dialog } = require('electron')
const path = require('path')
const url = require('url')

// Specify flash path, supposing it is placed in the same directory with main.js.
let pluginName
switch (process.platform) {
    case 'win32':
        pluginName = 'pepflashplayer64_32_0_0_192.dll'
        break
    case 'darwin':
        pluginName = 'PepperFlashPlayer.plugin'
        break
    case 'linux':
        pluginName = 'libpepflashplayer.so'
        break
}
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName))

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win

function createWindow() {
   win = new BrowserWindow({width: 800, height: 600, 
	webPreferences: {
            plugins: true,
            nodeIntegration: true
        }})
   win.loadURL('http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager09.html')
}

app.on('ready', createWindow)

**Comment by icerleer** [comment]
it's creat !!!!

**Comment by asoap** [comment]
I am ten years into the future, and I need to thank you past devs for figuring this out.  I would be lost and frustrated without you.
