### ISSUE TITLE
Port chrome.serial platform API?

### ISSUE THREAD

**Issue by tengyifei** [atom/electron#2042]
It would be nice to expose these functionalities in the Chrome Platform API. We are looking for ways to access the serial port in Electron and it's way too cumbersome to compile `node-serialport` for every platform and architecture and managing their precompiled binaries.

There is a similar issue in https://github.com/nwjs/nw.js/issues/518

**Comment by paulcbetts** [comment]
Sorry, Electron isn't planning to implement the Chrome packaged app API

**Comment by zcbenz** [comment]
Since node-serialport is already working well I don't think we will port the chrome.serial API since it is quite a lot of work.

**Comment by ddm** [comment]
I don't believe node-serialport actually works with Electron unfortunately.

**Comment by timfish** [comment]
This is why I finally went with NW.js. `node-serialport` was too unreliable and caused crashes on some machines and `chrome.serial` just works well on all platforms including chromebooks.
