### ISSUE TITLE
Bootstrapping script fails on Windows

### ISSUE THREAD

**Issue by marekdano** [atom/electron#2045]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--verbose' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose readDependencies loading dependencies from C:\electronjs\electron\package.json
5 verbose install where, deps [ 'C:\\electronjs\\electron',
5 verbose install   [ 'asar', 'coffee-script', 'coffeelint', 'request', 'runas' ] ]
6 verbose install where, peers [ 'C:\\electronjs\\electron', [] ]
7 verbose installManyTop reading for lifecycle C:\electronjs\electron\package.json
8 info preinstall electron@
9 verbose unsafe-perm in lifecycle true
10 verbose installManyTop reading scoped package data from C:\electronjs\electron\node_modules\asar\package.json
11 verbose installManyTop reading scoped package data from C:\electronjs\electron\node_modules\coffee-script\package.json
12 verbose installManyTop reading scoped package data from C:\electronjs\electron\node_modules\coffeelint\package.json
13 verbose installManyTop reading scoped package data from C:\electronjs\electron\node_modules\request\package.json
14 info package.json asar@0.5.0 No license field.
15 verbose readDependencies loading dependencies from C:\electronjs\electron\package.json
16 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\asar\package.json
17 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\coffee-script\package.json
18 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\coffeelint\package.json
19 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\request\package.json
20 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\asar\package.json
21 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\asar.cmd\package.json
22 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\cake\package.json
23 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\cake.cmd\package.json
24 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\coffee\package.json
25 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\coffee.cmd\package.json
26 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\coffeelint\package.json
27 verbose targetResolver reading package data from C:\electronjs\electron\node_modules\.bin\coffeelint.cmd\package.json
28 verbose already installed skipping coffee-script@^1.9.2 C:\electronjs\electron
29 verbose already installed skipping coffeelint@^1.9.4 C:\electronjs\electron
30 verbose already installed skipping request@* C:\electronjs\electron
31 silly cache add args [ 'runas@^2.0.0', null ]
32 verbose cache add spec runas@^2.0.0
33 silly cache add parsed spec { raw: 'runas@^2.0.0',
33 silly cache add   scope: null,
33 silly cache add   name: 'runas',
33 silly cache add   rawSpec: '^2.0.0',
33 silly cache add   spec: '>=2.0.0 <3.0.0',
33 silly cache add   type: 'range' }
34 silly addNamed runas@>=2.0.0 <3.0.0
35 verbose addNamed ">=2.0.0 <3.0.0" is a valid semver range for runas
36 silly addNameRange { name: 'runas', range: '>=2.0.0 <3.0.0', hasData: false }
37 silly mapToRegistry name runas
38 silly mapToRegistry using default registry
39 silly mapToRegistry registry https://registry.npmjs.org/
40 silly mapToRegistry uri https://registry.npmjs.org/runas
41 verbose addNameRange registry:https://registry.npmjs.org/runas not in flight; fetching
42 verbose already installed skipping asar@0.5.0 C:\electronjs\electron
43 verbose request uri https://registry.npmjs.org/runas
44 verbose request no auth needed
45 info attempt registry request try #1 at 11:47:27 AM
46 verbose request id 077fd49c87c71f19
47 verbose etag "235R4V7BPZIMDDM06FGCSMTGE"
48 http request GET https://registry.npmjs.org/runas
49 http 304 https://registry.npmjs.org/runas
50 silly get cb [ 304,
50 silly get   { date: 'Wed, 24 Jun 2015 10:47:34 GMT',
50 silly get     via: '1.1 varnish',
50 silly get     'cache-control': 'max-age=60',
50 silly get     etag: '"235R4V7BPZIMDDM06FGCSMTGE"',
50 silly get     age: '0',
50 silly get     connection: 'keep-alive',
50 silly get     'x-served-by': 'cache-lhr6324-LHR',
50 silly get     'x-cache': 'HIT',
50 silly get     'x-cache-hits': '1',
50 silly get     'x-timer': 'S1435142854.242147,VS0,VE89',
50 silly get     vary: 'Accept' } ]
51 verbose etag https://registry.npmjs.org/runas from cache
52 verbose get saving runas to C:\Users\Marek\AppData\Roaming\npm-cache\registry.npmjs.org\runas\.cache.json
53 silly addNameRange number 2 { name: 'runas', range: '>=2.0.0 <3.0.0', hasData: true }
54 silly addNameRange versions [ 'runas',
54 silly addNameRange   [ '0.1.0',
54 silly addNameRange     '0.2.0',
54 silly addNameRange     '0.3.0',
54 silly addNameRange     '0.4.0',
54 silly addNameRange     '0.5.0',
54 silly addNameRange     '0.5.1',
54 silly addNameRange     '0.5.2',
54 silly addNameRange     '0.5.3',
54 silly addNameRange     '0.5.4',
54 silly addNameRange     '1.0.0',
54 silly addNameRange     '1.0.1',
54 silly addNameRange     '1.1.0',
54 silly addNameRange     '2.0.0' ] ]
55 silly addNamed runas@2.0.0
56 verbose addNamed "2.0.0" is a plain semver version for runas
57 silly cache afterAdd runas@2.0.0
58 verbose afterAdd C:\Users\Marek\AppData\Roaming\npm-cache\runas\2.0.0\package\package.json not in flight; writing
59 verbose afterAdd C:\Users\Marek\AppData\Roaming\npm-cache\runas\2.0.0\package\package.json written
60 silly install resolved [ { main: './lib/runas.js',
60 silly install resolved     name: 'runas',
60 silly install resolved     version: '2.0.0',
60 silly install resolved     licenses: [ [Object] ],
60 silly install resolved     repository:
60 silly install resolved      { type: 'git',
60 silly install resolved        url: 'git+https://github.com/atom/node-runas.git' },
60 silly install resolved     bugs: { url: 'https://github.com/atom/node-runas/issues' },
60 silly install resolved     scripts:
60 silly install resolved      { prepublish: 'grunt coffee',
60 silly install resolved        test: 'node node_modules/jasmine-focused/bin/jasmine-focused --captureExceptions --coffee spec',
60 silly install resolved        install: 'node-gyp rebuild' },
60 silly install resolved     devDependencies:
60 silly install resolved      { 'jasmine-focused': '^1.0.5',
60 silly install resolved        grunt: '~0.4.1',
60 silly install resolved        'grunt-contrib-coffee': '~0.6.6',
60 silly install resolved        'grunt-cli': '~0.1.7',
60 silly install resolved        'grunt-shell': '~0.2.2',
60 silly install resolved        'coffee-script': '~1.6.2',
60 silly install resolved        'node-cpplint': '~0.1.5' },
60 silly install resolved     dependencies: { nan: 'https://atom.io/download/atom-shell/nan-1.6.1.tgz' },
60 silly install resolved     gypfile: true,
60 silly install resolved     gitHead: 'b4792701244cbeffb9cd90322c4e9ac7db7a5334',
60 silly install resolved     description: 'Run command synchronously with administrator privilege.',
60 silly install resolved     homepage: 'https://github.com/atom/node-runas',
60 silly install resolved     _id: 'runas@2.0.0',
60 silly install resolved     _shasum: '943d74dc6d250b90606721acde43347eb148efbb',
60 silly install resolved     _from: 'runas@>=2.0.0 <3.0.0',
60 silly install resolved     _npmVersion: '2.1.11',
60 silly install resolved     _nodeVersion: '0.10.33',
60 silly install resolved     _npmUser: { name: 'zcbenz', email: 'zcbenz@gmail.com' },
60 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
60 silly install resolved     dist:
60 silly install resolved      { shasum: '943d74dc6d250b90606721acde43347eb148efbb',
60 silly install resolved        tarball: 'http://registry.npmjs.org/runas/-/runas-2.0.0.tgz' },
60 silly install resolved     directories: {},
60 silly install resolved     _resolved: 'https://registry.npmjs.org/runas/-/runas-2.0.0.tgz',
60 silly install resolved     readme: 'ERROR: No README data found!' } ]
61 info install runas@2.0.0 into C:\electronjs\electron
62 info installOne runas@2.0.0
63 verbose installOne of runas to C:\electronjs\electron not in flight; installing
64 verbose lock using C:\Users\Marek\AppData\Roaming\npm-cache\_locks\runas-96b371f3c7afde56.lock for C:\electronjs\electron\node_modules\runas
65 silly install write writing runas 2.0.0 to C:\electronjs\electron\node_modules\runas
66 verbose unbuild node_modules\runas
67 silly gentlyRm C:\electronjs\electron\node_modules\runas is being purged from base C:\electronjs\electron
68 verbose gentlyRm don't care about contents; nuking C:\electronjs\electron\node_modules\runas
69 verbose tar unpack C:\Users\Marek\AppData\Roaming\npm-cache\runas\2.0.0\package.tgz
70 verbose tar unpacking to C:\electronjs\electron\node_modules\runas
71 silly gentlyRm C:\electronjs\electron\node_modules\runas is being purged
72 verbose gentlyRm don't care about contents; nuking C:\electronjs\electron\node_modules\runas
73 silly gunzTarPerm modes [ '777', '666' ]
74 silly gunzTarPerm extractEntry package.json
75 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
76 silly gunzTarPerm extractEntry README.md
77 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
78 silly gunzTarPerm extractEntry binding.gyp
79 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
80 silly gunzTarPerm extractEntry lib/runas.js
81 silly gunzTarPerm modified mode [ 'lib/runas.js', 420, 438 ]
82 silly gunzTarPerm extractEntry LICENSE.md
83 silly gunzTarPerm modified mode [ 'LICENSE.md', 420, 438 ]
84 silly gunzTarPerm extractEntry src/fork.cc
85 silly gunzTarPerm modified mode [ 'src/fork.cc', 420, 438 ]
86 silly gunzTarPerm extractEntry src/fork.h
87 silly gunzTarPerm modified mode [ 'src/fork.h', 420, 438 ]
88 silly gunzTarPerm extractEntry src/main.cc
89 silly gunzTarPerm modified mode [ 'src/main.cc', 420, 438 ]
90 silly gunzTarPerm extractEntry src/runas.h
91 silly gunzTarPerm modified mode [ 'src/runas.h', 420, 438 ]
92 silly gunzTarPerm extractEntry src/runas_darwin.cc
93 silly gunzTarPerm modified mode [ 'src/runas_darwin.cc', 420, 438 ]
94 silly gunzTarPerm extractEntry src/runas_posix.cc
95 silly gunzTarPerm modified mode [ 'src/runas_posix.cc', 420, 438 ]
96 silly gunzTarPerm extractEntry src/runas_win.cc
97 silly gunzTarPerm modified mode [ 'src/runas_win.cc', 420, 438 ]
98 verbose write writing to C:\electronjs\electron\node_modules\runas\package.json
99 info preinstall runas@2.0.0
100 verbose readDependencies loading dependencies from C:\electronjs\electron\node_modules\runas\package.json
101 silly prepareForInstallMany adding nan@https://atom.io/download/atom-shell/nan-1.6.1.tgz from runas dependencies
102 verbose readDependencies loading dependencies from C:\electronjs\electron\node_modules\runas\package.json
103 silly cache add args [ 'nan@https://atom.io/download/atom-shell/nan-1.6.1.tgz',
103 silly cache add   null ]
104 verbose cache add spec nan@https://atom.io/download/atom-shell/nan-1.6.1.tgz
105 silly cache add parsed spec { raw: 'nan@https://atom.io/download/atom-shell/nan-1.6.1.tgz',
105 silly cache add   scope: null,
105 silly cache add   name: 'nan',
105 silly cache add   rawSpec: 'https://atom.io/download/atom-shell/nan-1.6.1.tgz',
105 silly cache add   spec: 'https://atom.io/download/atom-shell/nan-1.6.1.tgz',
105 silly cache add   type: 'remote' }
106 silly mapToRegistry name nan@https://atom.io/download/atom-shell/nan-1.6.1.tgz
107 silly mapToRegistry using default registry
108 silly mapToRegistry registry https://registry.npmjs.org/
109 silly mapToRegistry uri https://registry.npmjs.org/nan@https://atom.io/download/atom-shell/nan-1.6.1.tgz
110 verbose addRemoteTarball https://atom.io/download/atom-shell/nan-1.6.1.tgz not in flight; adding
111 verbose addRemoteTarball [ 'https://atom.io/download/atom-shell/nan-1.6.1.tgz', null ]
112 info retry fetch attempt 1 at 11:47:28 AM
113 info attempt registry request try #1 at 11:47:28 AM
114 http fetch GET https://atom.io/download/atom-shell/nan-1.6.1.tgz
115 http fetch 200 https://atom.io/download/atom-shell/nan-1.6.1.tgz
116 silly fetchAndShaCheck shasum 7b6427390dfb63981622df987ed72c68dc3957c6
117 verbose addTmpTarball C:\Users\Marek\AppData\Local\Temp\npm-7132-51f152b1\atom.io\download\atom-shell\nan-1.6.1.tgz not in flight; adding
118 verbose addTmpTarball validating metadata from C:\Users\Marek\AppData\Local\Temp\npm-7132-51f152b1\atom.io\download\atom-shell\nan-1.6.1.tgz
119 verbose tar unpack C:\Users\Marek\AppData\Local\Temp\npm-7132-51f152b1\atom.io\download\atom-shell\nan-1.6.1.tgz
120 verbose tar unpacking to C:\Users\Marek\AppData\Local\Temp\npm-7132-51f152b1\unpack-e825d7c3dd4e
121 silly gentlyRm C:\Users\Marek\AppData\Local\Temp\npm-7132-51f152b1\unpack-e825d7c3dd4e is being purged
122 verbose gentlyRm don't care about contents; nuking C:\Users\Marek\AppData\Local\Temp\npm-7132-51f152b1\unpack-e825d7c3dd4e
123 silly gunzTarPerm modes [ '777', '666' ]
124 silly gunzTarPerm extractEntry package.json
125 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
126 silly gunzTarPerm extractEntry README.md
127 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
128 silly gunzTarPerm extractEntry include_dirs.js
129 silly gunzTarPerm modified mode [ 'include_dirs.js', 420, 438 ]
130 silly gunzTarPerm extractEntry nan.h
131 silly gunzTarPerm modified mode [ 'nan.h', 420, 438 ]
132 silly gunzTarPerm extractEntry appveyor.yml
133 silly gunzTarPerm modified mode [ 'appveyor.yml', 420, 438 ]
134 silly gunzTarPerm extractEntry LICENSE.md
135 silly gunzTarPerm modified mode [ 'LICENSE.md', 420, 438 ]
136 silly gunzTarPerm extractEntry CHANGELOG.md
137 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 420, 438 ]
138 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
139 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 420, 438 ]
140 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
141 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 420, 438 ]
142 silly gunzTarPerm extractEntry nan_new.h
143 silly gunzTarPerm modified mode [ 'nan_new.h', 420, 438 ]
144 silly gunzTarPerm extractEntry nan_string_bytes.h
145 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 420, 438 ]
146 silly gunzTarPerm extractEntry .dntrc
147 silly gunzTarPerm modified mode [ '.dntrc', 420, 438 ]
148 silly cache afterAdd nan@1.6.1
149 verbose afterAdd C:\Users\Marek\AppData\Roaming\npm-cache\nan\1.6.1\package\package.json not in flight; writing
150 verbose afterAdd C:\Users\Marek\AppData\Roaming\npm-cache\nan\1.6.1\package\package.json written
151 silly install resolved [ { name: 'nan',
151 silly install resolved     version: '1.6.1',
151 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
151 silly install resolved     main: 'include_dirs.js',
151 silly install resolved     repository: { type: 'git', url: 'git://github.com/rvagg/nan.git' },
151 silly install resolved     scripts:
151 silly install resolved      { test: 'tap --gc test/js/*-test.js',
151 silly install resolved        'rebuild-tests': 'pangyp rebuild --directory test' },
151 silly install resolved     contributors:
151 silly install resolved      [ [Object],
151 silly install resolved        [Object],
151 silly install resolved        [Object],
151 silly install resolved        [Object],
151 silly install resolved        [Object],
151 silly install resolved        [Object],
151 silly install resolved        [Object] ],
151 silly install resolved     devDependencies:
151 silly install resolved      { bindings: '~1.2.1',
151 silly install resolved        'node-gyp': '~1.0.2',
151 silly install resolved        pangyp: '~2.0.1',
151 silly install resolved        tap: '~0.5.0',
151 silly install resolved        xtend: '~4.0.0' },
151 silly install resolved     license: 'MIT',
151 silly install resolved     readme: 'Native Abstractions for ...
151 silly install resolved     readmeFilename: 'README.md',
151 silly install resolved     bugs: { url: 'https://github.com/rvagg/nan/issues' },
151 silly install resolved     homepage: 'https://github.com/rvagg/nan#readme',
151 silly install resolved     _id: 'nan@1.6.1',
151 silly install resolved     _shasum: '7b6427390dfb63981622df987ed72c68dc3957c6',
151 silly install resolved     _resolved: 'https://atom.io/download/atom-shell/nan-1.6.1.tgz',
151 silly install resolved     _from: 'https://atom.io/download/atom-shell/nan-1.6.1.tgz' } ]
152 info install nan@1.6.1 into C:\electronjs\electron\node_modules\runas
153 info installOne nan@1.6.1
154 verbose installOne of nan to C:\electronjs\electron\node_modules\runas not in flight; installing
155 verbose lock using C:\Users\Marek\AppData\Roaming\npm-cache\_locks\nan-05f058a08e7e0622.lock for C:\electronjs\electron\node_modules\runas\node_modules\nan
156 silly install write writing nan 1.6.1 to C:\electronjs\electron\node_modules\runas\node_modules\nan
157 verbose unbuild node_modules\runas\node_modules\nan
158 silly gentlyRm C:\electronjs\electron\node_modules\runas\node_modules\nan is being purged from base C:\electronjs\electron
159 verbose gentlyRm don't care about contents; nuking C:\electronjs\electron\node_modules\runas\node_modules\nan
160 verbose tar unpack C:\Users\Marek\AppData\Roaming\npm-cache\nan\1.6.1\package.tgz
161 verbose tar unpacking to C:\electronjs\electron\node_modules\runas\node_modules\nan
162 silly gentlyRm C:\electronjs\electron\node_modules\runas\node_modules\nan is being purged
163 verbose gentlyRm don't care about contents; nuking C:\electronjs\electron\node_modules\runas\node_modules\nan
164 silly gunzTarPerm modes [ '777', '666' ]
165 silly gunzTarPerm extractEntry package.json
166 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
167 silly gunzTarPerm extractEntry README.md
168 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
169 silly gunzTarPerm extractEntry include_dirs.js
170 silly gunzTarPerm modified mode [ 'include_dirs.js', 420, 438 ]
171 silly gunzTarPerm extractEntry nan.h
172 silly gunzTarPerm modified mode [ 'nan.h', 420, 438 ]
173 silly gunzTarPerm extractEntry appveyor.yml
174 silly gunzTarPerm modified mode [ 'appveyor.yml', 420, 438 ]
175 silly gunzTarPerm extractEntry LICENSE.md
176 silly gunzTarPerm modified mode [ 'LICENSE.md', 420, 438 ]
177 silly gunzTarPerm extractEntry CHANGELOG.md
178 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 420, 438 ]
179 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
180 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 420, 438 ]
181 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
182 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 420, 438 ]
183 silly gunzTarPerm extractEntry nan_new.h
184 silly gunzTarPerm modified mode [ 'nan_new.h', 420, 438 ]
185 silly gunzTarPerm extractEntry nan_string_bytes.h
186 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 420, 438 ]
187 silly gunzTarPerm extractEntry .dntrc
188 silly gunzTarPerm modified mode [ '.dntrc', 420, 438 ]
189 verbose write writing to C:\electronjs\electron\node_modules\runas\node_modules\nan\package.json
190 info preinstall nan@1.6.1
191 verbose readDependencies loading dependencies from C:\electronjs\electron\node_modules\runas\node_modules\nan\package.json
192 verbose readDependencies loading dependencies from C:\electronjs\electron\node_modules\runas\node_modules\nan\package.json
193 silly install resolved []
194 verbose about to build C:\electronjs\electron\node_modules\runas\node_modules\nan
195 info build C:\electronjs\electron\node_modules\runas\node_modules\nan
196 info linkStuff nan@1.6.1
197 silly linkStuff nan@1.6.1 has C:\electronjs\electron\node_modules\runas\node_modules as its parent node_modules
198 verbose linkBins nan@1.6.1
199 verbose linkMans nan@1.6.1
200 verbose rebuildBundles nan@1.6.1
201 info install nan@1.6.1
202 info postinstall nan@1.6.1
203 verbose unlock done using C:\Users\Marek\AppData\Roaming\npm-cache\_locks\nan-05f058a08e7e0622.lock for C:\electronjs\electron\node_modules\runas\node_modules\nan
204 verbose about to build C:\electronjs\electron\node_modules\runas
205 info build C:\electronjs\electron\node_modules\runas
206 info linkStuff runas@2.0.0
207 silly linkStuff runas@2.0.0 has C:\electronjs\electron\node_modules as its parent node_modules
208 verbose linkBins runas@2.0.0
209 verbose linkMans runas@2.0.0
210 verbose rebuildBundles runas@2.0.0
211 verbose rebuildBundles [ 'nan' ]
212 info install runas@2.0.0
213 verbose unsafe-perm in lifecycle true
214 info runas@2.0.0 Failed to exec install script
215 verbose unlock done using C:\Users\Marek\AppData\Roaming\npm-cache\_locks\runas-96b371f3c7afde56.lock for C:\electronjs\electron\node_modules\runas
216 verbose stack Error: runas@2.0.0 install: `node-gyp rebuild`
216 verbose stack Exit status 1
216 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
216 verbose stack     at EventEmitter.emit (events.js:110:17)
216 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
216 verbose stack     at ChildProcess.emit (events.js:110:17)
216 verbose stack     at maybeClose (child_process.js:1015:16)
216 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
217 verbose pkgid runas@2.0.0
218 verbose cwd C:\electronjs\electron
219 error Windows_NT 6.3.9600
220 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
221 error node v0.12.4
222 error npm  v2.10.1
223 error code ELIFECYCLE
224 error runas@2.0.0 install: `node-gyp rebuild`
224 error Exit status 1
225 error Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
225 error This is most likely a problem with the runas package,
225 error not with npm itself.
225 error Tell the author that this fails on your system:
225 error     node-gyp rebuild
225 error You can get their info via:
225 error     npm owner ls runas
225 error There is likely additional logging output above.
226 verbose exit [ 1, true ]
227 verbose unbuild node_modules\runas
228 info preuninstall runas@2.0.0
229 info uninstall runas@2.0.0
230 verbose unbuild rmStuff runas@2.0.0 from C:\electronjs\electron\node_modules
231 info postuninstall runas@2.0.0
232 silly gentlyRm C:\electronjs\electron\node_modules\runas is being purged from base C:\electronjs\electron
233 verbose gentlyRm don't care about contents; nuking C:\electronjs\electron\node_modules\runas
234 silly vacuum-fs purging C:\electronjs\electron\node_modules\runas
235 silly vacuum-fs quitting because other entries in C:\electronjs\electron\node_modules

**Comment by frankhale** [comment]
Looks like runas is failing to install. Can you try to install runas by itself and see if it fails?

```
npm install -g runas
```

Are you by chance using the Visual Studio command prompt to run bootstrap? If not, could you try it? I know there are other methods for building on Windows but for me it's worked well across multiple systems when I was having encountered various issues similar to this. I've noticed quite a lot of problems building node modules on Windows. It seems to be a source of much pain (at least it has been for me).

**Comment by zcbenz** [comment]
The `ELIFECYCLE` error usually means there is some trouble in your Windows development environment, one common solution is to reinstall Visual Studio.

Closing since it is actually an `npm` issue.
