### ISSUE TITLE
How to inject jquery into Browserwindow

### ISSUE THREAD

**Issue by fountainhead** [atom/electron#2048]
I am trying to replicated the selenium [example](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md#3-connect-to-chrome-driver) but using electron only.

I am wondering how to inject jQuery and then set the query to "nice cats" and printout the search results.
I need jQuery to be injected first and then set the query using `$("[name='q']")[0].value = "nice cats";`

I can open google using the below app.js code.

```js
var app = require('app')
var BrowserWindow = require('browser-window')
var ipc = require('ipc')

app.on('ready', function () {
  var mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });

  mainWindow.loadUrl('http://www.google.com');
  mainWindow.openDevTools();

  mainWindow.on('closed', function() {
    console.log("The page has been closed");
    mainWindow = null;
  });

  mainWindow.webContents.on('did-finish-load', function() {
    console.log(mainWindow.webContents.getUrl());
  });
});
```

I want to navigate to the next page using `$.click` and then print out the next results.

Can someone please help with this?

**Comment by frankhale** [comment]
I'd probably do it this way. Instead of loading Google in the mainWindow using loadUrl I'd instead create a basic HTML page that contains a webview. I'd then create a small JS file to load in the webview preload. This script would require jQuery like this:

```javascript
window.$ = window.jQuery = require('./bower_components/jquery/dist/jquery.min.js');
```

Then in that small script I'd do whatever other code you need to do in order to intercept and manipulate elements on the Google page.

At least that is what I am thinking off the top of my head. I'm sure there are other ways to do it.

**Comment by fountainhead** [comment]
That works. Thank you. :-)

**Comment by fountainhead** [comment]
Actually, I am still stuck on getting the elements of the page. How do I access them?

**Comment by frankhale** [comment]
I'll try to come up with an example. Give me a few minutes.

**Comment by frankhale** [comment]
Okay so disregard what I said above. It doesn't appear you can inject jQuery like that in a webview preload script. Try this, this works!

index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>jQuery injection into webview preload</title>
  </head>
  <body style="overflow:hidden;">
    <webview id="webview" preload="./manipulateGoogle.js" src="http://google.com" style="position:absolute;width:100%;height:100%;"></webview>
    <script>
      // need to have a script tag make webview work even if you don't plan to use it...
    </script>
  </body>
</html>
```

webview preload script (in this example name it manipulateGoogle.js)

```javascript
window.onload = function() {
    var script = document.createElement("script");
    script.src = "https://code.jquery.com/jquery-2.1.4.min.js";
    script.onload = script.onreadystatechange = function() {
      $(document).ready(function() {
        $("#lst-ib").val("Hello, World!");
      });
    };
    document.body.appendChild(script);
};
```

main.js

```javascript
var app = require('app');
var BrowserWindow = require('browser-window');
require('crash-reporter').start();

var mainWindow = null;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    resizable: true
  });

  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.focus();
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
```

Yay! It works! w00t!

![manipulategoogleusingjquery](https://cloud.githubusercontent.com/assets/190154/8346478/1d4c3526-1acb-11e5-9845-cb3223ded086.png)

**Comment by fountainhead** [comment]
@frankhale Thanks a ton! My head was spinning understanding what is available in which process!

Thank you! :-)

**Comment by frankhale** [comment]
You're welcome! Let me know if you have any other questions. I'll try to help out if I can!

**Comment by Deliaz** [comment]
**frankhale** thanks, great info. 
Is that possible in *manipulateGoogle.js* inject locally-stored scripts with relative path?

**Comment by frankhale** [comment]
Webviews are capable of injecting local scripts by using the preload tag (see above example). 

https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#preload

**Comment by Deliaz** [comment]
Thx, 
Is there any way to do this in the case of multiple scripts (without concatenation)?

**Comment by frankhale** [comment]
I guess you could load a script that in turn loads other scripts to get around only being able to pass one script to preload tag.

**Comment by Deliaz** [comment]
Yeah, I did so.
And it looks like I'm not able to use relative paths to scripts.

**Comment by frankhale** [comment]
Check that your paths are pointing to a correct location. I typically use __dirname and sometimes use ./ to build my relative paths.

http://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js

There are some Electron APIs to get various useful paths:

https://github.com/atom/electron/blob/master/docs/api/app.md#appgetapppath
https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname

There really shouldn't be any reason why a relative path would be a problem here. The preload tag has access to the node environment (at least initially if node integration is turned off). If you want to use node modules you'll need to make sure node integration remains on in the webview.

**Comment by frankhale** [comment]
You could start up a HTTP server to serve the scripts and avoid the issue with relative paths. Just add new script tags to the page in your preload script with the paths to the scripts you want.

**Comment by Deliaz** [comment]
**frankhale**, thanks, nice idea

**Comment by carlskii** [comment]
This is very helpful, however if the app navigates to a new page within the URL my rendered div disappears. Is there a way to make the JQuery `$("#lst-ib").val("Hello, World!");` call run after each page finishes loading ?

**Comment by carlskii** [comment]
Scratch the last comment - it actually works as is. It just got written to a different place in the page.

**Comment by carlskii** [comment]
OK one other issue I have here is that if I change the `manipulateGoogle.js` code to include a `console.out` like this: 

```
// injection technique borrowed from http://stackoverflow.com/questions/840240/injecting-jquery-into-a-page-fails-when-using-google-ajax-libraries-api
window.onload = function() {
    var script = document.createElement("script");
    script.src = "https://code.jquery.com/jquery-2.1.4.min.js";
    script.onload = script.onreadystatechange = function() {
      $(document).ready(function() {
        $("#lst-ib").val("Hello, World!");
        console.log("element inserted")
      });
    };
    document.body.appendChild(script);
};
```

Nothing gets written to the console log (dev tools) or the node.js console.

**Comment by frankhale** [comment]
You need to open the dev tools for the webview to see console log statements.

**Comment by carlskii** [comment]
I thought I did using the "view, toggle developer tools" then "view, reload" but it doesn't log anything.

**Comment by frankhale** [comment]
The webview has it's own instance of dev tools. Type this in the console of the main browser window dev tools:

This will open the dev tools for the webview.

```
var wv = document.getElementById("webview");
wv.openDevTools();
```

**Comment by frankhale** [comment]
@carlskii, are you able to see the console log statements in the webviews dev tools now?

**Comment by carlskii** [comment]
Yes thanks - that did the trick.

**Comment by frankhale** [comment]
:+1:

**Comment by carlskii** [comment]
Thanks for our help. I'm now able to add the following elements to my page. 

```
$("body").append('<div id="container">hello world</div>')

            $("#container").click(function() {
                console.log("Button Clicked");
                WebContents.goBack();
                console.log(webContents)
```

After reading the docs there seems to be a `WebContents.goBack()` method which should navigate backwards. Would you know if its possible to access this method from within the browser side or is it only available from the Node.js side of the fence ?

**Comment by frankhale** [comment]
If it's the browser window and you have node integration turned on you can get to it from both sides. Eg. if it's in main.js then you can use IPC to communicate from your browser side JS to the backend main.js code to call it. Or you can use the Remote API from your browser side code to grab the current BrowserWindow object and then call the method you need. If node integration is turned off you can do it via Socket IO (or similar technology) to communicate from the browser code to the main.js code in order to call the method.

Webview can be done in pretty much the same fashion, if node-integration is turned off wire up an event handler in your preload script so that it can be called from the code loading in the webview. If it's turned on do it like above (whatever you prefer).

There may be other ways to do it but this is just off the top of my head. If any of my info is wrong somebody please feel free to correct me.

**Comment by carlskii** [comment]
Thanks for this. 

Wow, Electron certainly seems to get complicated here. I previously used NW.js for some other projects. Are there any references/tutorials for that cover this bidirectional IPC configs ?

**Comment by frankhale** [comment]
So yeah, Electron has built in API to do IPC and the docs are here:

https://github.com/atom/electron/blob/master/docs/api/ipc-main.md
https://github.com/atom/electron/blob/master/docs/api/ipc-renderer.md

I've only briefly used the in-built IPC API so can't really comment much on it. I've also used Socket IO as a "IPC" mechanism and found it to work rather nicely. You could probably use other APIs to communicate back and forth but I haven't really explored it because Socket IO worked well for me in this regard.

**Comment by carlskii** [comment]
Thanks again @frankhale. 

Going back to your `manipulateGoogle.js` example. I'm not sure if I'm not understanding how it works properly. I'm able to inject JQuery and initially make some changes to my pages, however it seems that the changes are happening at the beginning of the page load rather than the end. i.e. I can initially see the changes that are made, but they are then overwritten as the rest of the page loads. 

I thought the `$(document).ready` should only fire once the page is fully loaded, but this doesn't appear to happening.

**Comment by frankhale** [comment]
(I haven't tried this but...) If you have control over the code that you are loading (eg you can edit it) why not set up a callback in your webview preload and then when your page gets done loading all it's ajax stuff then call the callback from the code loaded in the webview to notify it that your page is done doing everything so you can then manipulate it as needed from the webview preload script.

**Comment by carlskii** [comment]
Yeah, thats the problem, I don't have control of the code in the pages I'm loading.

**Comment by frankhale** [comment]
okay no problem, here is a possible work around. Maybe there is something you can look for in the page when you know the page may be finished loading and then trigger some code to manipulate the results. I'm thinking set up an interval to periodically do something and then remove the interval after some time or maybe even setup a timeout to run the manipulate code after a number of seconds have passed.

**Comment by TimNZ** [comment]
@frankhale You said you couldn't require jquery in a preload script
https://github.com/electron/electron/issues/2048#issuecomment-115092053

Why was that?  I'm doing this in 1.3.2 and it appears to work fine:

```
window.onload = function() {
    const {webFrame,remote} = require('electron')
    var appOptions = remote.getGlobal('app_options')
    let jq = require('jquery')
    jq(document).ready(() => {
        setInterval(() => {
            var a = jq('a[id=Dashboard]')
            if (a.length)
                a.text('Tim')

        })
    })
};
```

**Comment by MarshallOfSound** [comment]
@TimNZ That's because you are waiting for the window load event before `require` jQuery.  This means the `document` object is fully populated and the DOM is rendered.

You can't do what are you doing without the `onload` function

**Comment by dizawish** [comment]
Can by any chance confirm, that the above example of manipulation www.google.com still works?
Got up to the point of preloading the script, in which i put an alert(); and works fine. But i cant get the text swapping work with the jquery.
Thanx

**Comment by frankhale** [comment]
@dizawish I don't know what is going on now. I just tried the google manipulation code I wrote a long time ago and it fails in the preload script because window.onload never seems to be called or it's called before preload script loads now. This is different behavior to past Electron releases so I'm not really sure. Although I did manage to get it to work by refactoring my preload script a bit. I no longer rely on window.onload but instead use an interval to check the document.readystate and then inject jQuery, change the text in the google search input field and clear the interval. I've tested this against Electron 1.7.2.

The following repository has this code:

https://github.com/frankhale/electron-inject-jquery-webview-example

**Comment by michaelgv** [comment]
@frankhale @dizawish Electron has changed, it appears window.onload may not of been fired ever, however updating the script to something like this will fix it:

```javascript
document.addEventListener("DOMContentLoaded", function(event) {
	setTimeout(function() {
		alert(document.domain); // "google.com"
	},1000);
});
```

DOMContentLoaded is always fired, so listening for it is the best way to inject jQuery/do whatever you need to do here. I put it in a setTimeout for fun, however it's not necessary.

**Comment by frankhale** [comment]
Thank you so much @michaelgv for the pull request. I've merged it.

**Comment by michaelgv** [comment]
@frankhale np, another way to do it is with vanilla JS, or directly importing the jQuery library in your google.js file, vanilla way:

```javascript
document.addEventListener("DOMContentLoaded", function(event) {
	document.getElementById("lst-ib").value='Electron.js';
});
```

**Comment by AryaveerSR** [comment]
@frankhale  A Easy way to load HTML file is : window.loadFile('index.html') than that __dir or whatever

**Comment by fastcodeco** [comment]
> Okay so disregard what I said above. It doesn't appear you can inject jQuery like that in a webview preload script. Try this, this works!
> 
> index.html:
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <title>jQuery injection into webview preload</title>
>   </head>
>   <body style="overflow:hidden;">
>     <webview id="webview" preload="./manipulateGoogle.js" src="http://google.com" style="position:absolute;width:100%;height:100%;"></webview>
>     <script>
>       // need to have a script tag make webview work even if you don't plan to use it...
>     </script>
>   </body>
> </html>
> ```
> 
> webview preload script (in this example name it manipulateGoogle.js)
> 
> ```js
> // injection technique borrowed from http://stackoverflow.com/questions/840240/injecting-jquery-into-a-page-fails-when-using-google-ajax-libraries-api
> window.onload = function() {
>     var script = document.createElement("script");
>     script.src = "https://code.jquery.com/jquery-2.1.4.min.js";
>     script.onload = script.onreadystatechange = function() {
>       $(document).ready(function() {
>         $("#lst-ib").val("Hello, World!");
>       });
>     };
>     document.body.appendChild(script);
> };
> ```
> 
> main.js
> 
> ```js
> var app = require('app');
> var BrowserWindow = require('browser-window');
> require('crash-reporter').start();
> 
> var mainWindow = null;
> 
> app.on('window-all-closed', function() {
>   if (process.platform != 'darwin')
>     app.quit();
> });
> 
> app.on('ready', function() {
>   mainWindow = new BrowserWindow({
>     width: 1024,
>     height: 768,
>     resizable: true
>   });
> 
>   mainWindow.loadUrl('file://' + __dirname + '/index.html');
>   mainWindow.focus();
>   mainWindow.on('closed', function() {
>     mainWindow = null;
>   });
> });
> ```
> 
> Yay! It works! w00t!
> 
> ![manipulategoogleusingjquery](https://cloud.githubusercontent.com/assets/190154/8346478/1d4c3526-1acb-11e5-9845-cb3223ded086.png)

Tks it worked

**Comment by Novivy** [comment]
Note: You need to enable the webview tag for this to load

```
  webPreferences: {

            webviewTag: true
        
        },
```
