### ISSUE TITLE
How to increase electron max memory limit (--max_old_space_size)

### ISSUE THREAD

**Issue by bu2** [atom/electron#2056]
Is it possible to use the V8 option --max_old_space_size=N to increase the max memory limit of the electron process and its BrowserWindow subprocess ?

I tried different commands without success (I am on Mac OS X with node installed with Homebrew and electron installed with npm):

$ electron --max_old_space_size=4096 app/
$ node --max_old_space_size=4096 ~/.brew/bin/electron app/
...

(I also tried --max_old_space_size and --max-old-space-size).

I reach the limit around 1.5~1.7Go of memory when the following error occurs:
`[1765:0625/153220:ERROR:atom_bindings.cc(32)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

I am brute testing with following main.js program:

```
var output = [];
var count = 0;

while (true) {
  output.push(new Object());
  count++;

  if (count % 1000 == 0)
    console.log(process.memoryUsage());
}
```

Regards,

Bruno.

**Comment by zcbenz** [comment]
Does `--js-flags="--max_old_space_size=4096"` work for you?

**Comment by bu2** [comment]
Sorry but it does not work. I tried:
`electron --js-flags="--max_old_space_size=4096" app/`
and
`node --js-flags='"--max_old_space_size=4096" ~/.brew/bin/electron alpha/`

It work correctly for a pure nodejs program with following command:
`node --max_old_space_size=4096 alpha/main.js `

**Comment by bu2** [comment]
The option --js-flags="--max_old_space_size=4096" works on electron build from source following instructions: http://electron.atom.io/docs/v0.28.0/development/build-instructions-mac.

I run with following command:
`$ ~/lab/atom/electron/out/R/Electron.app/Contents/MacOS/Electron --js-flags="--max_old_space_size=4096" ./app/`

My config: 
macbook pro 13 early-2015
OS X 10.10.3

From my point of view, you can close this issue.

Thank you.

**Comment by zcbenz** [comment]
:+1:

**Comment by mgcrea** [comment]
Sorry to revive an old thread, but it looks like `--js-flags="--max_old_space_size=4096"` does not work anymore with latest electron, do you know if it got somehow replaced by another flag in latest electron?

**Comment by jrieken** [comment]
@zcbenz Can you comment on the differences how this flag behaves when having `ELECTRON_RUN_AS_NODE` set? It just seems to be ignored in that case? Given a script that just allocates memory (https://github.com/Microsoft/vscode/issues/28112#issuecomment-306558470) I can see the option nicely when running like this:

```
./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --js-flags="--max_old_space_size=2024" ~/Desktop/big.js
```

but when running it like so it is ignored 

```
 env ELECTRON_RUN_AS_NODE=true ./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --max_old_space_size=2024 ~/Desktop/big.js
```

Using the latter variant with nodejs (8.0.0) is working and shows the desired effect. What is different in electron?

**Comment by botezatumihaicatalin** [comment]
I got it to work like this by inserting this piece of code in Browser.js before **ready** event:

`// Increase max application memory (default is 1.8 Gb)
app.commandLine.appendSwitch('js-flags', '--max-old-space-size=4096')`

**Comment by Hadatko** [comment]
Hello could you address location of that file? I found several Browser.js

**Comment by hexianzhi** [comment]
In win10, electron 2.0.13, `app.commandLine.appendSwitch('js-flags', '--max-old-space-size=4096')` is not working.

but you can change `packge.json` 's scripts:
`{
  "scripts": {
    "start": "electron --js-flags=--max-old-space-size=500 . "
  }
}`

Or if you use  electron-vue, change the `dev-runner.js`:

`function startElectron () {
  var args = [
    // Add the line below
    "--js-flags=--max-old-space-size=500",
    '--inspect=5858',
    path.join(__dirname, '../dist/electron/main.js')
  ]
}`

**Comment by Hadatko** [comment]
Hi,
i am using this: "node_modules/.bin/electron --js-flags='--max-old-space-size=10192' ."

**Comment by Akash9773312** [comment]
Hi I am using electron 23.1.1 and I facing an Out Of Memory error can be please address me how can I resolve the same
