### ISSUE TITLE
Call java method from .jar

### ISSUE THREAD

**Issue by lhalver1** [atom/electron#2058]
How can I call a java method that is inside a class, and that class is part of a jar? The java code can not be in a web service or on a server, it must be client side only. For more I posted a stackoverflow question to go more in depth. 

See here: http://stackoverflow.com/questions/31055884/how-to-run-jar-methods-from-javascript/31056438#31056438

I am just checking to see if electron has any special tricks that might be able to help me out.

**Comment by mmastrac** [comment]
I'm working on a project that adds the ability to distribute end-user code in Java on top of Electron: https://github.com/orbitaljs

It works well on mac, but there are some platform bugs blocking it from working in Windows.

**Comment by zcbenz** [comment]
I'm closing this since NPAPI plugins support is going to be removed very soon by Chromium, and we won't fix any NPAPI related issues.
