### ISSUE TITLE
secure websocket (WSS://) connection stalling within electron

### ISSUE THREAD

**Issue by dte** [atom/electron#2059]
secure websocket connection over SSL works in Chrome but stalls in electron and eventually times out. A connection to the same server over a standard websocket works (ws://) in both electron as well as chrome. 

My hunch is a certificate issue from the server (perhaps it's not trusted?). If it is possible to turn off all certificate checking I can give that a go. 

Electron: 0.28.3
Operating System: OS X 10.10.3

![screen shot 2015-06-25 at 7 59 15 pm](https://cloud.githubusercontent.com/assets/585865/8368210/408cbb28-1b75-11e5-8bec-36e22f7510a7.png)

**Comment by dte** [comment]
possible relevant: https://github.com/atom/electron/issues/1450

**Comment by deepak1556** [comment]
> perhaps it's not trusted?

yup. Right now Electron defaults to first certificate from the store, . There is also a `select-certificate` event on [app](https://github.com/atom/electron/blob/master/docs/api/app.md#event-select-certificate) which can be used to pass PEM encoded data, will be available in next release.

>  If it is possible to turn off all certificate checking I can give that a go.

Nope cant be done.

**Comment by deepak1556** [comment]
> perhaps it's not trusted?

yup. Right now Electron defaults to first certificate from the store for self-signed certs, make sure its installed. There is also a `select-certificate` event on [app](https://github.com/atom/electron/blob/master/docs/api/app.md#event-select-certificate) which can be used to pass PEM encoded data, will be available in next release.

>  If it is possible to turn off all certificate checking I can give that a go.

Nope cant be done.

**Comment by zcbenz** [comment]
Does `--ignore-certificate-errors` work for you?

**Comment by dte** [comment]
Found the issue in the server-side websocket code. It didn't like an empty user-agent header string. Closing this as its not an electron issue.
