### ISSUE TITLE
Crash Reporter on Linux

### ISSUE THREAD

**Issue by hardchor** [atom/electron#2062]
Hi,

We're currently testing the crash reporter on Linux (Ubuntu 14.04 / Fedora 21):

```javascript
var app = require('app');
var crashReporter = require('crash-reporter');

crashReporter.start();

app.on('ready', function () {
    setTimeout(process.crash, 2000);
});
```

We get the following response
```bash
Failed to get crash dump id.
Report Id: 
```

**Comment by zcbenz** [comment]
This error means the crash reports collecting server is not working. When you call `crashReporter.start();` without parameters crash reports will be sent to the default server, which is not running for now because of my faults.

**Comment by hardchor** [comment]
Hi @zcbenz,

I've set it up to report to my own server, and I guess the response headers get dumped out, so this is what I'm (still) getting, even if the endpoint does consume the POSTed data and responds with a 200:

```http
  HTTP/1.1 200 OK
  Date: Fri, 26 Jun 2015 15:24:09 GMT
  Server: Apache
  X-Powered-By: PHP/5.5.8
  Access-Control-Allow-Origin: https://project.localhost
  Access-Control-Allow-Credentials: true
  Content-Length: 0
  Connection: close
  Content-Type: text/html; charset=UTF-8
Failed to get crash dump id.
Report Id: 
Illegal instruction (core dumped)
```

**Comment by zcbenz** [comment]
@hardchor Your server needs to send the ID back, the report ID is generated on server side.

**Comment by hardchor** [comment]
I see! That could probably go into the docs as well. Is it literally just a string with the ID as response?

**Comment by zcbenz** [comment]
@hardchor It can be an arbitrary ASCII string.
