### ISSUE TITLE
Perform async spell checking

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#2065]
I am using the spellchecking code from documentation.
```javascript
require('web-frame').setSpellCheckProvider("en-US", true, {
  spellCheck: function(text) {
    return !(require('spellchecker').isMisspelled(text));
  }
});
```

The electron API allows only synchronous operations and I want to use an async library to determine the spelling of words. How I can do that?

The ideal code should look like something like this:
```javascript
require('web-frame').setSpellCheckProvider("en-US", true, {
  spellCheck: function(text, done) {
    spellcheck(text, done);
  }
});
```

**Comment by erusev** [comment]
I'd also like to know that, thanks.

**Comment by zcbenz** [comment]
The spell checking interface of `blink` requires the spell check function to be asynchronous, so I'm afraid this is not possible unless `blink` changes its interface.
