### ISSUE TITLE
Access cookies from rendered javascript

### ISSUE THREAD

**Issue by Agrosis** [atom/electron#2070]
Currently I'm rendering webpack-generated react.js inside electron. I'm able to make XMLHttpRequests and it grabs the cookies successfully, but I'm having trouble actually getting the cookies themselves. I've opened Chrome's dev tools up and I see that cookies are stored in a local file?

How do i access this from node?

**Comment by hokein** [comment]
You can try the [WebContents.session.cookies](https://github.com/atom/electron/blob/master/docs/api/browser-window.md) APIs.

**Comment by Agrosis** [comment]
Yeah, cool, I set up a bridge with ipc and just used the webcontents api. Thanks!
