### ISSUE TITLE
app.setPath userData/appData Uncaught Exception on OS X (darwin)

### ISSUE THREAD

**Issue by vaughnroyko** [atom/electron#2071]
Using: `app.setPath("userData", path.join(process.cwd(), "save"));`

Causes the following error:

![image](https://cloud.githubusercontent.com/assets/2846662/8394501/66e4193a-1cef-11e5-9fd9-1ccaa177ddce.png)

Works as expected on Windows/Linux; creates the save folder in root/app directory.

**Version:** electron-v0.28.3-darwin-x64
**OS X:** 10.10.3 (Yosemite)

**Comment by hokein** [comment]
Can you provide more details? I couldn't reproduce it on OS X10.9 with v0.28.3.

**Comment by paulcbetts** [comment]
Where are you calling this method? You can only call it as _soon_ as your app starts up (i.e. before 'ready')

**Comment by vaughnroyko** [comment]
@hokein  Not sure what else information I can provide. Please let me know. Just as a test, I'm using the example files/config as found here: https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md

@paulcbetts The only thing I added was the following (before the ready):

    var path = require('path');
    app.setPath("userData", path.join(process.cwd(), "save"));

**Comment by vaughnroyko** [comment]
Some new information here. If I run Electron from the terminal directly, like so:

    /electron-v0.28.3-darwin-x64/Electron.app/Contents/MacOS/Electron /test

No error shows up anymore, and the path is saved to as expected. Maybe some kind of permissions issue?

**Comment by hokein** [comment]
The `process.cwd()` code has different behavior between launching from terminal and from `GUI`(double click icon), see
```
// Launching from terminal: <your app dirctory>/save
path.join(process.cwd(), "save")

// Launching from GUI: /save
path.join(process.cwd(), "save")
```

So you need to pass the `absolute` file path to make `Electron` launching from `GUI` works.
