### ISSUE TITLE
Electron to open some of the web will be wrong。

### ISSUE THREAD

**Issue by zg2013** [atom/electron#2072]
hello,
I use the electron to open up the part of the page to test, found in the use of chrome and nw.js no problem, but in the electron will be wrong.
Test site,：
http://www.bienvillecapital.com/
http://www.assemblyltd.com/
http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/scrollbar_themes_demo.html

window7 X64 / electron v0.28.3

My code：
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1100, height: 600});
  mainWindow.loadUrl('http://www.bienvillecapital.com/');
  mainWindow.openDevTools();
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
![1](https://cloud.githubusercontent.com/assets/5134292/8397035/1f8297ea-1df0-11e5-9f34-b799ced0bd11.png)
![2](https://cloud.githubusercontent.com/assets/5134292/8397038/24883f60-1df0-11e5-8abc-132d9ab58dd1.png)

My application is to open the user's arbitrary web pages by electron.
I think this should be the BUG of electron, or do I have code? Awaiting your reply, thank you very much.

**Comment by paulcbetts** [comment]
Disable node-integration or use a WebView tag with node-integration disabled

**Comment by zg2013** [comment]
Contact electron,Did not see clearly DOC.
Problem solving!
But I didn't use "node-integration" because I need some UI plugin in my app, maybe he doesn't support nodejs.
I use the "iframe", at least for the current problem.

Thanks to paulcbetts !!
