### ISSUE TITLE
Clarify dependencies

### ISSUE THREAD

**Issue by HitomiTenshi** [atom/electron#2075]
Is electron based on node.js or io.js?

Main page says node.js
![node.js](http://i.imgur.com/0mlcSSa.png)

README says io.js
![io.js](http://i.imgur.com/n6hFSwo.png)

**Comment by frankhale** [comment]
iojs

**Comment by HitomiTenshi** [comment]
Thanks, I never did real web development before so I wanted to know what to look at when I start developing my project with electron.
