### ISSUE TITLE
Cannot show insecure image in BrowserWindow

### ISSUE THREAD

**Issue by dataich** [atom/electron#2076]
I loaded secure website in BrowserWindow. The website has insecure image like 'http://example.com/image01.png'.
```js
mainWindow = new BrowserWindow({
 width: 800,
 height: 600
});

mainWindow.loadUrl("https://example.com");
```

Then the image can not be loaded and got following message in DevTools.

```
Mixed Content: The page at 'https://example.com' was loaded over HTTPS, but requested an insecure image 'http://example.com/image01.png'. This request has been blocked; the content must be served over HTTPS.
```

I tried 'web-security' and 'allow_displaying_insecure_content' but both options don't work.

```js
mainWindow = new BrowserWindow({
 width: 800,
 height: 600,
 'web-preferences': {
   'web-security': false
 }
});
```

```js
app.commandLine.appendSwitch('allow_displaying_insecure_content');
```

Is there any options about allowance insecure contents in BrowserWindow ?

**Comment by deepak1556** [comment]
`allow-displaying-insecure-content` is a webkit flag, and is turned off by [default](https://github.com/atom/electron/blob/master/atom/browser/atom_browser_client.cc#L149). Can add if @zcbenz approves. `web-security` option is to remove same origin policy btw.

**Comment by zcbenz** [comment]
> allow-displaying-insecure-content is a webkit flag, and is turned off by default. Can add if @zcbenz approves. web-security option is to remove same origin policy btw.

Add an `allow-displaying-insecure-content` option sounds good to me.

**Comment by paulcbetts** [comment]
> Add an allow-displaying-insecure-content option sounds good to me.

Is there any reason to not just turn this on when web-security is false? We're getting a ton of minutiae settings and I don't know of anyone who would want to enable this but not disable web security (i.e. why would you only want to _kind of_ disable web security).

**Comment by deepak1556** [comment]
> Is there any reason to not just turn this on when web-security is false?

yeah thats even better :+1:

**Comment by dataich** [comment]
Great, thanks!

**Comment by dataich** [comment]
I'm sorry i changed my mind...
I think there is no reason to not just turn `allow_displaying_insecure_content` on when `web-security` is false.
But how about opposite?
Sometimes I want `allow_displaying_insecure_content` is on without `web-security` is false.
