### ISSUE TITLE
How to set the chrome parameter

### ISSUE THREAD

**Issue by zg2013** [atom/electron#2078]
hello
I want to change the data-path chrome to my app directory. How to do?
For example, in nw.js, I can set up in package.json,
eg
"chromium-args": "--data-path='./data/data-path/'"
But I didn't find the package configuration method in electron.
Thank you very much!

**Comment by hokein** [comment]
You can use [`app.setPath`](https://github.com/atom/electron/blob/master/docs/api/app.md) API.
