### ISSUE TITLE
electron.atom.io docs do not match latest release

### ISSUE THREAD

**Issue by vinnyp** [atom/electron#2082]
Please update documentation to match latest release (v0.28.3).

[http://electron.atom.io](http://electron.atom.io) is pointing to [http://electron.atom.io/docs/v0.28.0/](http://electron.atom.io/docs/v0.28.0/). However, if you click on [Documentation Source](https://github.com/atom/electron/blob/master/docs/README.md), you'll get v0.28.3.

**Comment by johnmuhl** [comment]
See also https://github.com/atom/electron.atom.io/issues/51

**Comment by zcbenz** [comment]
Closing since there is already tracked at atom/electron.atom.io#51.
