### ISSUE TITLE
Open cmd.exe and pass arguments

### ISSUE THREAD

**Issue by lhalver1** [atom/electron#2084]
I can successfully open the command prompt

`var shell = require('shell');`
`var test = shell.openItem("cmd.exe");`

But is there a way I can pass it arguments, like `dir` or `exit`? Obviously I will be doing much more than that, but it's a start.

**Comment by carlosperate** [comment]
This is not really an issue, you should ask about it in the forum: https://discuss.atom.io/c/electron

**Comment by lhalver1** [comment]
Ok I will do that, thx

**Comment by lhalver1** [comment]
To whom it interests
I went with writing my own .bat file to open the cmd
`shell.openItem("customCMD.bat");`
and obviously I can do whatever I need to with the cmd in the batch file.
