### ISSUE TITLE
Documentation should indicate which parameters are optional/required and default values

### ISSUE THREAD

**Issue by mixmatch** [atom/electron#2088]
Current documentation does not clearly state if parameters are optional or required and their default values when not provided, e.g. 

Current:
>new BrowserWindow(options)
>options Object
>x Integer - Window's left offset to screen
>y Integer - Window's top offset to screen
>width Integer - Window's width
>height Integer - Window's height
>use-content-size Boolean - The width and height would be used as web page's size, which means the actual window's size will include window frame's size and be slightly larger.
>center Boolean - Show window in the center of the screen

>Creates a new BrowserWindow with native properties set by the options. Usually you only need to set the width and height, other properties will have decent default values.

Preferable [replace with actual defaults]:
>new BrowserWindow(options)
>Creates a new BrowserWindow with native properties set by the options. Usually you only need to set the width and height, other properties will have decent default values.
>options Object
>x Integer (optional) - Window's left offset to screen (default: [int/null])
>y Integer (optional) - Window's top offset to screen (default: [int/null])
>width Integer - Window's width
>height Integer - Window's height
>use-content-size Boolean (optional) - The width and height would be used as web page's size, which means the actual window's size will include window frame's size and be slightly larger. (default: [true/false])
>center Boolean (optional) - Show window in the center of the screen (default: [true/false])

**Comment by zcbenz** [comment]
Closing this since we are now adding `required` label in the documents, though it hasn't been done for all places.

For undocumented places, we can track them in new PRs.
