### ISSUE TITLE
showMessageBox() and showErrorBox() should use TaskDialog on Windows

### ISSUE THREAD

**Issue by vinnyp** [atom/electron#2090]
[TaskDialog()](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760540(v=vs.85).aspx) and [TaskDialogIndirect()](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760544(v=vs.85).aspx) were introduced in Windows Vista as new dialog APIs.

`TaskDialog()` was designed to be a `MessageBox()` and `ShellMessageBox()` replacement. 
`TaskDialogIndirect()` gives you more options to pass in to get [pretty rich dialogs with little effort](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760441(v=vs.85).aspx).

Please consider migrating over to these APIs.

`dialog.showMessageBox()` -> `TaskDialogIndirect()`. It will support the scenarios covered in the API. In fact, you'll save a lot of bug fixing and testing by just using this API instead of rolling your own dialog class. 

`dialog.showErrorBox()` -> `TaskDialog()`.

**Comment by paulcbetts** [comment]
@vinnyp Seems legit, can you send a PR to do it? Here's where you want to have a look:

https://github.com/atom/electron/blob/master/atom/browser/ui/message_box_views.cc#L386

**Comment by vinnyp** [comment]
@paulcbetts sure, I'll take a look.

**Comment by zcbenz** [comment]
Didn't know that API, it would be awesome to use native dialogs. I think we can also use GtkMessageDialog on Linux.

**Comment by vinnyp** [comment]
@zcbenz @paulcbetts before I dig into this, what versions of Windows are supported with Electron? I didn't see that mentioned anywhere. These dialog APIs work on Windows Vista+ and Windows Server 2008+. 

If Electron needs to work on older versions, I'll only do the mapping for those versions and above.

**Comment by paulcbetts** [comment]
@vinnyp >= Win7

**Comment by zcbenz** [comment]
@vinnyp If you haven't started, I would like to implement it myself, I have a plan to cleanup the dialog code so I don't want to cause too much troubles to you.

**Comment by vinnyp** [comment]
@zcbenz sure. It's taking me a while to ramp up on the system anyway :)  Can you include me in the PR?

A few things to call out:
- make sure you link to `comctrl32.lib` (I didn't see any references to it)
- you need to update the app manifest file to include [comctrl32 v6](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773175%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396), otherwise you'll get an error saying you're using the wrong version. 

**Side note:** if you're going to update the manifest file, you should also add that the app is [dpiaware](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) (go to the section called *Declaring DPI Awareness*). Otherwise make a separate PR for that.

**Comment by zcbenz** [comment]
@vinnyp Of course, thanks for sharing the information, it is very helpful!
