### ISSUE TITLE
Google Closure KeyboardHandler doesnt work

### ISSUE THREAD

**Issue by anonrig** [atom/electron#2096]
Hello,

I am using Google Closure in my web app and want to set keyboard shortcuts in the app using `goog.ui.KeyboardShortcutHandler`, you can find the demo from `https://github.com/google/closure-library/blob/master/closure/goog/demos/keyboardshortcuts.html`.

It doesn't get recognized in the Electron app but works in Web.

**Comment by zcbenz** [comment]
I cloned `closure-library` and the demo works well in Electron. Please provide more information of what "It doesn't get recognized " mean and I'll reopen if I can confirm.

**Comment by anonrig** [comment]
@zcbenz I've tested it on Linux but it still doesn't work.

**Comment by zcbenz** [comment]
Can you provide detailed steps to reproduce your problem and describe more about "doesn't work"?
