### ISSUE TITLE
Always on top doesn't always work

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2097]
If you have multiple Electron apps, and one of the apps has a window that is set to be always on top,  you can sometimes cause the other app windows to overlay the app containing the window that is set to be always on top. This can be caused by focusing the other app windows, Alt+Tab, or by opening another application switching focus to the new app.

None of the apps use fullscreen, kiosk or have their own always on top flags. But all are frameless and have their windows set to be transparent.

**Comment by iamdriz** [comment]
I did a little test with:

~~~
setInterval(function(){
		console.log( mainWindow.isAlwaysOnTop() );
	}, 1000);
~~~

and even when I have managed to cause another app window to overlay, the console still returns true... so electron thinks the window is still on top... any ideas?

**Comment by iamdriz** [comment]
This solves the issue:

~~~
setInterval(function(){
		mainWindow.setAlwaysOnTop(true);
	}, 1);
~~~

But shouldn't have to do this... and I'm sure it has performance issues.

**Comment by paulcbetts** [comment]
We've been hearing issues related to this too, where always-on-top doesn't always work

**Comment by zcbenz** [comment]
The `always-on-top` option is a hint to operating system or window manager that this window should be put above all non-topmost windows, and it is allowed to have top-most windows overlapping each other on most systems.

See also [How do I create a topmost window that is never covered by other topmost windows?](http://blogs.msdn.com/b/oldnewthing/archive/2011/03/10/10138969.aspx).

**Comment by paulcbetts** [comment]
We've definitely been hearing this happen with even non-topmost windows (i.e. topmost windows getting covered by Visual Studio or Excel). Could it be that if you `hide` a window and show it again, we forget to reset topmost flag?

**Comment by zcbenz** [comment]
The `IsAlwaysOnTop` method checks the `WS_EX_TOPMOST` flag, so if it returns true the topmost flag should be there:
https://code.google.com/p/chromium/codesearch#chromium/src/ui/views/win/hwnd_message_handler.cc&q=IsAlwaysOnTop&sq=package:chromium&type=cs&l=686

**Comment by iamdriz** [comment]
@zcbenz Why has this been closed? If it's still an unfixed issue.

**Comment by zcbenz** [comment]
@iamdriz As stated in my linked article, Windows can not guarantee a top-most window is always top-most.

**Comment by iamdriz** [comment]
@zcbenz So would the interval timer be the best way to ensure a window is always on top?

**Comment by Ciantic** [comment]
I had to periodically set my window always on top even in C# app.

But remember peeps, if you do interval make the time something reasonable like, `setInterval(function(){ mainWindow.setAlwaysOnTop(true);}, 10000);` 10 seconds... It does not go to wrong order very often.

**Comment by davidcoleman007** [comment]
is there an electron setting that can make an always-on-top window appear ABOVE a fullscreen app?  let's say that we launch some child process which goes into fs mode (real fs, not fs-windowed).  I know that windows is capable of still placing something over it, but is *electron* capable of asking windows to do this?

**Comment by camerondm9** [comment]
@davidcoleman007 Windows forces all other windows under a fullscreen window when it is initially shown, but if you make your window topmost after the fullscreen window is visible, it should end up on top of the fullscreen window, just like any other. I've done exactly this to overlay information on top of a live PowerPoint presentation. (If your window was already topmost, you may have to toggle it off and then on again to force yourself back to the top...)

**Comment by robsontenorio** [comment]
@camerondm9 could you share your code? how to detect any other screens are in fullscreen mode?

**Comment by camerondm9** [comment]
@robsontenorio My code doesn't detect fullscreen applications, it just detects if there is a window above it in the Z order that shouldn't be (based on the TopMost flag alone), and then forces itself back to the top. It checks every time it updates the overlay window (about 10 times a second). I'm not sure how this interacts with hardware-accelerated fullscreen, but for windowed fullscreen applications like PowerPoint it seems to work just fine. My code was written in C#, the core of it is like this:
```c#
if ((overlay != null) && overlay.Visible) {
	//Check if there is something over us...
	var cover = overlay.WindowAbove;
	while ((cover != null) && cover.TopMost) {
		cover = cover.WindowAbove;
	}
	if (cover != null) {
		//Quickly toggle topmost... (should force it back on top)
		overlay.TopMost = false;
		overlay.TopMost = true;
	}
}
```
WindowAbove corresponds to the Windows API function [GetWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633515(v=vs.85).aspx) with the GW_HWNDPREV flag
TopMost is set using [SetWindowPos](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633545(v=vs.85).aspx), and retrieved using [GetWindowLongPtr](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633585(v=vs.85).aspx)

**Comment by robsontenorio** [comment]
@camerondm9 thanks, for sharing :)

Ok, i do understand  the logic in C#. But i was looking for a Electron equivalent solution :(

**Comment by camerondm9** [comment]
@robsontenorio Even though Electron doesn't have built-in APIs for this, my understanding is that it would still be possible using something like the Node.js [fastcall](https://www.npmjs.com/package/fastcall) package to talk to the Window APIs directly. (You would have to make sure your app was running on Windows first)
It would be a fair bit of work though...
