### ISSUE TITLE
window.open should respect window.opener node-integration property

### ISSUE THREAD

**Issue by lele85** [atom/electron#2100]
I'm building an app that has an initial login/connect step in a classic website to retrive an oauth2 token. In order to work with classic web content login BrowserWindow is opened with:

```
"node-integration": false
```

All is working correctly except from Facebook Connect. Facebook redefines his own require on the website, disabling node-integration prevent conflicts but the setting is not passed down to opened window.

**Facebook js SDK internally calls a window.open and electron instantiate that window with node integration enabled no matter what.**

I think that the expected behavior is that **opened window** inherits **opener window** node integration property.

Any idea for a solution or a workaround is highly appreciated.

**Comment by zcbenz** [comment]
Sounds reasonable to me.

**Comment by lele85** [comment]
Digging deeper into the issue i discovered that this will only fix partially the issue because FB sdk uses window.opener shared state to manage communication between opened and opener window. It will be useful for sure in other scenarios. I'm watching #1865. Thank you for the effort @zcbenz!
