### ISSUE TITLE
API to set process priority

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#2101]
Every powerful desktop app platform requires an API to set the application priority for the OS.
One such use case is when using WebChimera.js, video playback might lack in performance in power-save mode even though WC.js itself is very optimized - the reason for this is that the OS downclocks the CPU, but adding priority for the process would solve the issue.

For windows, this is:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686219%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686277%28v=vs.85%29.aspx

For Unix-es this is the nice value.

**Comment by jaruba** [comment]
> Every powerful desktop app platform requires an API to set the application priority for the OS.

+1

**Comment by zcbenz** [comment]
It is only possible on Windows to set higher priority for current process, on POSIX systems you need to have root privilege to increase a process's priority.

**Comment by Ivshti** [comment]
UNIX systems generally don't need it. @jaruba will confirm, with WebChimera.js, which is currently the only acceptable solution for multi-codec video under electron / nw.js, it requires High process priority under Windows to play properly if the system is in power-save mode.

UNIX systems don't have this issue since they're smart enough to know when to upclock/downclock the processor - in the case of OS X / Linux.

**Comment by paulcbetts** [comment]
Setting process priority is generally a Bad Idea, and in fact, can actually make your app run slower because of priority inversion (i.e. high priority thread / process needs a lock, normal thread has it, but can't make process because high-priority process keeps hogging time)

**Comment by Ivshti** [comment]
That makes sense. 

As for the citation, @jaruba will explain.

**Comment by jaruba** [comment]
> As for the citation, @jaruba will explain

Player works fine in Electron when the laptop is plugged into a power source, but the entire app freezes / unfreezes constantly to an unwatchable / unusable state when I unplug the laptop.

> CPU downclocking is based on overall load, the process priority is only relative to other processes

This is undoubtedly true, setting ``High``priority to the chromium processes does make the video work as it should, but all other processes become laggy (including typing in a page from a chrome tab). Still, this only happens when the player is actually playing a video and truth be told, if your in power saving mode, you shouldn't try to play a video while doing something else anyway. :P

I can't imagine why this does not happen to VLC or WebChimera NPAPI Plugin but happens to a native implementation of WebChimera in Electron and NW.js. If there is a better way of giving the app more juice, I fail to see it, but I am sure that the proposed solution will work.

**Comment by jaruba** [comment]
I should also mention that my tests have been done on a pretty powerful laptop:

CPU: Intel i7-4500U
GPU: Nvidia Geforce 820M
RAM: 12GB

**Comment by Ivshti** [comment]
> I can't imagine why this does not happen to VLC or WebChimera NPAPI Plugin but happens to a native implementation of WebChimera for Electron and NW.js

webchimera.js has the overhead of doing an memcpy for a texture which cannot be avoided at the moment.

VLC and WebChimera use more efficient texture upload methods.

The reason for this is chromium's multi process architecture, which means WCjs runs in one process and the GPU interactions happen in another. When we call teximage2d, we write to shared mem and then we wait the GPU process to memcpy that into the GPU memory - blocking the whole process until it's done.

You can figure out why this is so bad for high res videos, and as we have found out, almost insignificant for regular res videos

**Comment by paulcbetts** [comment]
I think that if you want to do this, you should write a node module to do so, putting it in the core API will encourage people to do it, when in almost all cases it's a bad idea (particularly in the Chrome multi-process model where it's just begging for process inversion), _even_ if it happens to help in your particular case. If you use `node-ffi`, you don't even need to write C++ in order to call this Win32 API call.

**Comment by Ivshti** [comment]
The solution for this is already in the chromium code base, and it is called GpuMemoryBuffer - this is a framework that sets up shared mem in the GPU, which can be read by the renderer process (where WCjs is).

Unfortunately it is not exposed to the client side, but maybe we can have it exposed as an electron API - but we also need a lock/unlock system.

HTML5 video recently switched to using GpuMemoryBuffer.

There are plans for exposing this with semantics similar to EGLImage - WebGL dynamic texture extension, but TBH I don't think it will get implemented soon

**Comment by Ivshti** [comment]
@paulcbetts you're right, it would be safer to not implement it in core and even not do it in our case. We should shift our efforts into eliminating the memcpy that webchimera.js does instead of working around the issue.

**Comment by paulcbetts** [comment]
> you're right, it would be safer to not implement it in core and even not do it in our case. We should shift our efforts into eliminating the memcpy that webchimera.js does instead of working around the issue.

:+1: - This is definitely doable, I know you can toll-free convert node.js Buffers into Typed 8-bit arrays in C++ which I believe is what WebGL uses as its type for textures. You might have to write a bit of C++ code but if we can make this easier in Electron I'd definitely be into that PR

**Comment by Ivshti** [comment]
@paulcbetts we already do that at webchimera.js - it inits a Uint8Array and then directly renders video frames into its buffer without any copying - the mastermind behind it is the project creator - RSATom.

The point is, as I described in detail, what chrome does when calling texImage2d.

As I said, it writes the buffer into shared memory and then waits for the GPU process to copy it to GPU mem. 

In fact there are much better methods (PBOs, EGLImage) but inaccessible through what chromium provides with webgl.

**Comment by Ivshti** [comment]
@zcbenz you can close this because as @paulcbetts this can do more harm than good since chances are it will get misused.

**Comment by oxygen** [comment]
I have two use cases where it is needed to set the process priority for child processes (one of which requires suspending the child processes while on battery power). 

So if this ever gets reopened it would be great to control any child process, not just the nodejs backend and child GUIs.

**Comment by AustinDeric** [comment]
> Every powerful desktop app platform requires an API to set the application priority for the OS.

+1

> I'm closing this because as @paulcbetts this can do more harm than good since chances are it will get misused.

I think this is a concern of the linux nice system than it is with electron. electron should support linux's nice feature.
