### ISSUE TITLE
Send buffers over IPC

### ISSUE THREAD

**Issue by pfraze** [atom/electron#2104]
IPC doesn't seem to support sending Buffers; you have to serialize them to a string, or it will send an array of ints. This adds some overhead in messaging.

It would be nice to have that! Even better would be the zero-copy Transferables that workers have. We do image processing in the UI, so it's hard to avoid sending buffers to the main process.

**Comment by zcbenz** [comment]
Data sent through IPC are JSON encoded, and since Buffer is not part of JSON specification it is impossible to achieve this with our current architecture.

Using the `remote` module can pass Buffer to main process without manual conversion though.
