### ISSUE TITLE
Linux @ VirtualBox mouse problem

### ISSUE THREAD

**Issue by jadbox** [atom/electron#2106]
When using VirtualBox with a Linux client, Atom is unable to handle mouse input properly. Atom needs an update from Electron which is built upon Chrome 43.

Atom bug reference: https://github.com/atom/atom/issues/6306
Chrome issue report: https://code.google.com/p/chromium/issues/detail?id=456222

**Comment by steelbrain** [comment]
VMWare has an option to enable `Gaming Mouse Integration` that way it properly fires all the mouse move events instead of magically teleporting it there, is there a similar option for virtualbox?

**Comment by steelbrain** [comment]
__Note:__ VMWare also has a free VMWare Player, just in case you can't find that feature in VBox.

**Comment by zcbenz** [comment]
There is a PR to update Atom to use later Chrome: https://github.com/atom/atom/pull/6877.
