### ISSUE TITLE
Menu based event triggers don't get picked up in renderer process

### ISSUE THREAD

**Issue by krainboltgreene** [atom/electron#2110]
``` javascript
// renderer.js
const Remote = require("remote");
const IPC = Remote.require("ipc");
const PortalView = document.getElementById("view");

onload = function() {
  IPC.on("lowbrow-devtools-toggle", function() {
    if(PortalView.isDevToolsOpened()) {
      PortalView.closeDevTools();
    } else {
      PortalView.openDevTools();
    };
  });
}
```

```
// browser.js
menuItemWithAction("Toggle DevTools", [MODIFIER, "Alt", "I"], function(item, window) {
  window.webContents.send("lowbrow-devtools-toggle");
})
```

So with that setup let me explain what happens:

  1. `window.webContents()` returns the right WebContents object.
  2. The send returns `true`, so we know it's being "emitted"
  3. Nothing happens renderer side, not even `alert()` calls.

We've also tried it by hooking onto webcontents:

``` javascript
const Remote = require("remote");
const PortalView = document.getElementById("view");

onload = function() {
  Remote.getCurrentWebContents().on("lowbrow-devtools-toggle", function() {
    if(PortalView.isDevToolsOpened()) {
      PortalView.closeDevTools();
    } else {
      PortalView.openDevTools();
    };
  });
}
```

Interestingly even though either way failed to do anything, with the latter it at least showed up on the `_events` property of `window.webContents`. The `IPC` hook doesn't.

**Comment by zcbenz** [comment]
You should use `require('ipc')` instead of `remote.require('ipc')`.

**Comment by krainboltgreene** [comment]
Okay that works, however two things I want to mention:

  1. The difference should be clearly documented, as @travishartwell and I spent 4 hours trying to figure this bug out and it wasn't remotely obvious.
  2. Closing an issue before confirming the issue resolved is abrasive.
