### ISSUE TITLE
Request: chrome.webRequest.* API

### ISSUE THREAD

**Issue by steelbrain** [atom/electron#2115]
They're super-useful for headless video extraction from a page https://developer.chrome.com/extensions/webRequest
would be awesome to have them implemented in Electron.

**Comment by deepak1556** [comment]
Related https://github.com/atom/brightray/pull/119 wasnt sure of the design. `webContents.webRequest` would be better, we can proxy `chrome.*` if needed.

/cc @zcbenz  @hokein  @paulcbetts

**Comment by Tribex** [comment]
I too would find this incredibly useful.

**Comment by paulcbetts** [comment]
I'm not super excited about this, we have both protocol overrides and Service Workers, I don't know that we need a 3rd independent API for this, and we've already set a precedent that we're not implementing the Chrome packaged API

**Comment by steelbrain** [comment]
@paulcbetts Our protocol overrides aren't really complete, when we intercept the protocols it loses most of it's info like cookies, custom headers or post data too (maybe?).

**Comment by steelbrain** [comment]
Also, we don't have any concept of Async protocol interception or stuff.

**Comment by paulcbetts** [comment]
> Also, we don't have any concept of Async protocol interception or stuff.

We do now!

> Our protocol overrides aren't really complete, when we intercept the protocols it loses most of it's info like cookies, custom headers or post data too (maybe?).

So let's just fix the bug, instead of burning down the world and adding a new API

**Comment by steelbrain** [comment]
> We do now!

Sorry but I am unable to find it in the docs :) https://github.com/atom/electron/blob/master/docs/api/protocol.md

> So let's just fix the bug, instead of burning down the world and adding a new API

I agree that the existing protocol stuff is useful, but in our current API we would have to intercept protocols to know about the data flowing between them, You can't implement a download manager that automatically checks the headers of the requests and filters them based on that.

**Comment by Tribex** [comment]
@paulcbetts I haven't done any tests yet, but I have a hunch that protocol overrides won't work inside of a webview/iframe. I'll check ASAP. That's my primary use-case, and I'd like to be able to access *all* the information on the request, as @steelbrain said. If the current protocol system works with these, I'd be fine leaving this unimplemented. However, it does seem to be a weird way to monitor HTTP requests.

Something like webContents.on('request', callback(data)) would feel much more natural.

**Comment by alexindigo** [comment]
+1 `webview.on('request', callback)` and/or `webview.on('will-navigate', callback)` – with ability to cancel the whole thing.

**Comment by Tribex** [comment]
@alexindigo Yes, this would be a potential use case, and in-fact, one of the main reasons why I'd be interested in this. (For example, see https://github.com/Nateowami/BackLoader.) There would be no way to implement the meat of that Chrom(e/ium) extension in an electron-based program.

**Comment by Tribex** [comment]
@paulcbetts, @Tribex Initial tests seem to indicate that the protocol methods do handle requests inside a BrowserWindow, but I cannot get them to be redirected to the default handlers. Anything returned from the handler, null, undefined, or otherwise, causes a segfault.

**Comment by alexindigo** [comment]
My use case is to be able to show in webview pages from one domain (like my bank) and open other domains (if user ckicked links or other activity) in new window. But of course allowing original page to load external resources (CDN, analytics, ads).

**Comment by paulcbetts** [comment]
>  Initial tests seem to indicate that the protocol methods do handle requests inside a BrowserWindow, but I cannot get them to be redirected to the default handlers. Anything returned from the handler, null, undefined, or otherwise, causes a segfault.

So what I'm saying is not trying to assert that it works perfectly _now_, but that we should identify the reasons why it _doesn't_ work perfectly and fix them - I don't mean to say that these existing issues aren't legit

**Comment by Tribex** [comment]
@paulcbetts Yes, I understand that point, and it would probably be the best idea, but are you sure protocol handlers are the best way to implement features such as this? (Also, how do Service Workers factor in to this issue? Care to elaborate?)

Thanks!

**Comment by sulinixl** [comment]
This is a interesting issues, I have been searching some way to proxy all http/https request in the <webview> for a long time, it torment me.

By now, I found some possible way(They will be work in the future):
1. protocol: Doesn't work.
2. webRequest: Electron doesn't support chrome.* api, and the "webContents.webRequest" doesn't exists by now.
3. Service Worker: It need "https", if you want use it in "file", wait for https://github.com/atom/electron/pull/2852
4. Proxy: You can start one http proxy on PORT, and set the command argument "proxy-server", but it sames that you cann't proxy&intercept "https" request.
5. Webview#Event: Doesn't work.

If you are looking for some way to proxy http/https request, just stop here...

**Comment by Tribex** [comment]
Why doesn't protocol work?

**Comment by sulinixl** [comment]
@Tribex 
protocol's callback only provide url, method, referer and session, i can not get the params, headers, cookies(maybe in session), and i don't know how to proxy response, and lack of document......

If I wrong, please teach me how to proxy request use protocol. :laughing:

**Comment by Tribex** [comment]
Yes, I believe checking what's in session would be what's needed. I've toyed around with an earlier version of this, but haven't really tried to determine where everything is.
