### ISSUE TITLE
Scheme not registered on protocol intecept

### ISSUE THREAD

**Issue by steelbrain** [atom/electron#2116]
I get the scheme not registered error that we used to get before 0.26.1
this doesn't work
```js
app.on('ready', function() {
    var protocol = require('protocol');
    protocol.interceptProtocol('http', function(request) {
      console.log(request)
      return null
    });
});
```
this does
```js
app.on('ready', function() {
    var protocol = require('protocol');
    setImmediate(function(){
      protocol.interceptProtocol('http', function(request) {
        console.log(request)
        return null
      });
    })
});
```

**Comment by deepak1556** [comment]
`AtomURLRequestJobFactory` isnt set by the time `ready` event is triggered. I am really not sure if the fix should be to move the `ready` event after the `URLRequestContext` is created or add a new event `request-context-created` which clearly indicates when users can start using `protocol`module. @zcbenz thoguhts ?

**Comment by zcbenz** [comment]
Doesn't `protocol.registerProtocol('http')` throw `The scheme is already registered` error?

**Comment by deepak1556** [comment]
@zcbenz thats a typo in the issue , i believe @steelbrain refers to `protocol.interceptProtocol('http')` which shouldnt throw `scheme does not exist` on app `ready`.

**Comment by steelbrain** [comment]
@zcbenz that was a typo. Thanks for pointing out.

**Comment by zcbenz** [comment]
I'm merging this to #182, once the protocol APIs become pure async this will be solved.
