### ISSUE TITLE
No arrow functions despite harmony flag

### ISSUE THREAD

**Issue by keizom** [atom/electron#2118]
My main.js file contains this:

```
app.on('ready', function () {
  app.commandLine.appendSwitch('js-flags', '--harmony');
  // ...
});
```

Yet arrow functions are unrecognized. Let, const, and classes still work (with "use script").

Using Electron v0.29.1 on Gentoo Linux 2.2

**Comment by steelbrain** [comment]
How about
```js
var v8 = require('v8')
v8.setFlagsFromString('--harmony-arrow-functions')
```
https://iojs.org/api/v8.html#v8_setflagsfromstring_string

**Comment by steelbrain** [comment]
Also `--harmony` isn't supposed to turn on arrow functions see, https://iojs.org/en/es6.html

**Comment by keizom** [comment]
Unfortunately, passing neither `--harmony-arrow-functions` nor `--harmony_arrow_functions` into `v8.setFlagsFromString` is enabling arrow functions.

However, 
```
app.on('ready', function () {
  app.commandLine.appendSwitch('js-flags', '--harmony_arrow_functions');
  // ...
});
```
now solves the problem. I was not aware arrow functions was masked but now I know that an extra flag is required. Thanks!

**Comment by 0x80** [comment]
@keizom I've tried your solution but I still get this error when launching electron:

```
> DEBUG='app:*' HOT=1 NODE_ENV=development electron .

App threw an error when running [SyntaxError: /Users/me/MyApp/main.js:16
tingle.on('open', () => {
                   ^
Unexpected token )]
```

Am I missing something?

**Comment by keizom** [comment]
@0x80 the code I used enabled arrow functions in a renderer process. Perhaps there is a difference between enabling a renderer process and the main process (?). I do not know electron well enough to know if this is the case.

In the mean time, have you tried @steelbrain's method using `v8.setFlagsFromString`?

**Comment by 0x80** [comment]
@keizom The code in my renderer process runs through webpack and babel so that's not an issue I guess. I found my problem. You can only put ES6 code in a module that you then require. I was putting arrow functions right in the main.js file where also the v8.setFlagsFromString() calls were made. I don't think that's possible since the syntax will be interpreted/parsed before the flag settings have effect. Anyways it's working now! :+1:
