### ISSUE TITLE
Handling module paths?

### ISSUE THREAD

**Issue by grofit** [atom/electron#2120]
I posted this on Slack but got no response so just wanted to post in here.

Hey so I am fairly new to electron and I was wondering how I can set the base path for modules

grofit [9:46 AM]
as I was trying to bundle stuff, but that blows up because although lots of stuff is in the bundle when other modules need to reference stuff (as the module magic dance picks common JS not normal global scope) it falls over as it cannot find the module

grofit [9:47 AM]
I thought maybe it just embeds requirejs so I tried setting the require config path but it tells me require.config is not a function

grofit [9:47 AM]
so is there some *best practice* way to deal with lots of dependencies? and/or bundling

**Comment by steelbrain** [comment]
@grofit the way I handle it is requiring all the nodejs deps and then setting them to window
```
<script>
window.request = require('request')
</script>
```
and then add my own app's scripts like normal script tags and use nodejs in them
```
<script src="assets/js/main.js"></script>
```

**Comment by grofit** [comment]
I guess this rules bundling out then as you cannot really assign individually then, not that I need bundling it was just to cut down on the verbosity of the index includes.

That being said lets say I wanted to do as you have `window.$ = require("jquery")` and the jquery file lives within `./libs/jquery`, now I know I can prefix it with a route like this, but is there a way to just tell the `require` method where the default path to look for modules on the client is? as this is the crux of my question I think.

**Comment by steelbrain** [comment]
It's not really related to electron, search nodejs require path.

**Comment by grofit** [comment]
AH this is the answer then, I was expecting as it was running within the browser it would be using requirejs or some other browser based commonjs handler, but if it is running with nodejs as the resolving mechanism (for non `remote.require` calls then this gives me something to look at. Thanks.

**Comment by zcbenz** [comment]
Closing since this is not Electron related, I suggest asking about this on forums of Node.js, where you can get better answers.

**Comment by grofit** [comment]
Sure but I would also like to mention this issue would never have been raised if it were better documented within Electron somewhere that when in the browser domain it is using NodeJS as its CommonJS handler, I have seen a few issues where people are a bit confused why things like jquery is not loading in global scope when it is loaded via a script tag, and I was confused wondering why `require` was available but it was not using require js or any other normal browser dependency resolver.

So I would request someone adds a section in the documents even if its just a short paragraph explaining that the browser script resolution uses nodejs so all modules are loaded as common js packages and its up to the user to add global instances if required, so its recommended to install browser dependencies through npm. I mean its clear Electron uses NodeJS but I assume most people will think like I do assuming it controls some backend bit which is what `remote` is for, and the browser acts as a normal non module loading environment normally.

**Comment by steelbrain** [comment]
@grofit this is from the first paragraph of the main README of electron

> The Electron framework lets you write cross-platform desktop applications using JavaScript, HTML and CSS. It is based on io.js and Chromium and is used in the Atom editor.

:sweat_smile:

**Comment by thomasjo** [comment]
> So I would request someone adds a section in the documents

@grofit PRs are welcomed with :open_hands:

**Comment by grofit** [comment]
Yeah but that in no way really tells you that browser script resolutions are within the context of CommonJS modules, its not a massive thing, just something that trips you up without really noticing.

I am happy to write a blurb on the topic somewhere but I thought maybe 1 line somewhere on the main blurb would be enough.

**Comment by grofit** [comment]
Here is a proposed change which does add too much text but at least warns developers of what to expect when loading scripts:

https://github.com/atom/electron/commit/caa17fb9fb303f7fb9bf1ed84fb152806a311cda
