### ISSUE TITLE
Add ability to set the default_download_path

### ISSUE THREAD

**Issue by carlosperate** [atom/electron#2121]
More of a feature request than a bug. The new download manager delegate download directory points to the per-user application data directory. Could we edit this default location or change it to something more user friendly like the home/user directory?

**Comment by deepak1556** [comment]
if the `default_download_path` is set when should the file picker be prompted to select a new path ? or would it better if the download manager remembers the last selected path and uses it instead of another path api ?

**Comment by carlosperate** [comment]
> if the default_download_path is set when should the file picker be prompted to select a new path ? 

I'm not sure I understand this question, most likely due to my limited knowledge about how this feature works. I assumed the the `default_download_path` is the path shown on the file picker when it is opened (in this case to save the download file).

> would it better if the download manager remembers the last selected path and uses it instead of another path api ?

I quite like that feature, but it would still show the "per-user application data directory" on first launch and would prefer to have an api call to manually set it to a different path or to have it set to a different default (user home folder perhaps?).

Mostly I suggest this to not expose to the user the inner working of the application, as a packed electron app user might not quite understand why the "save file" prompt would suggest a "download" folder in within their `%APPDATA%` ,   `~/.config`, or `~/Library/Application Support` directory.

**Comment by deepak1556** [comment]
> Mostly I suggest this to not expose to the user the inner working of the application, as a packed electron app user might not quite understand why the "save file" prompt would suggest a "download" folder in within their %APPDATA% , ~/.config, or ~/Library/Application Support directory.

Ah cool, that cleared my doubt about this api. thanks!

> I assumed the the default_download_path is the path shown on the file picker when it is opened (in this case to save the download file)

yup, thats correct.
