### ISSUE TITLE
[v0.28.3-darwin-x64] Webview terminating, during History back.

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#2122]
Hello,

While experimenting with webview in electron, to check our app. We found that, when a webpage is fully loaded in Webview , navigate to any link and pressing "delete/backspace" would history.goBack() ( which is normal but., ) then upon navigating to any link would terminate.

generate "Render process started" & "terminate console logs"

Env : 
a. Mac OS x 0.10.4 and yosemite
b. v0.28.3 64 bit version of electron

Attached  reproducible sample & screens.
https://dl.dropboxusercontent.com/u/42787852/electron-app/Webview_terminating_history_navigation.zip

![screen shot 2015-07-03 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/3531949/8510400/9229b91a-22fd-11e5-9f91-72816f962b09.png)
![screen shot 2015-07-03 at 2 42 04 pm](https://cloud.githubusercontent.com/assets/3531949/8510401/92341248-22fd-11e5-8026-f44eeef2d393.png)

**Comment by steelbrain** [comment]
I think the history was implemented client sided, recently, which means that the renderer for a webview is terminated on each navigation event and respawned

**Comment by kamesh-a** [comment]
Note similar effect in "electron-v0.29.1-darwin-x64.zip" as well just in case we have tried to download the latest one to ensure bug is persistent.

**Comment by zcbenz** [comment]
Calling `delete/backspace` to going back currently messes up the history management, and it has caused many troubles. I was unable by finding out the exact call in Chromium to fix this, I'll try again today :(.

You can workaround it by hooking the `delete` key event for now.

**Comment by kamesh-a** [comment]
Thanks for working on this @zcbenz , i can do a hook on backspace/delete is this patch does that automatically , if so can you please point me to a rc release or something so we could give a try and confirm its does haul/terminate the webview :)

Have a good day !!!!!

**Comment by zcbenz** [comment]
You can try the v0.29.2 released just now.

**Comment by kamesh-a** [comment]
Thank you @zcbenz that was super quick. Will check that right away..

**Comment by kamesh-a** [comment]
Great, navigating history back is prevented, boolean fix works fine.

**Comment by oguzhancolak** [comment]
Thank you @zcbenz
