### ISSUE TITLE
require('crypto') on Renderer Process gives different object

### ISSUE THREAD

**Issue by mauris** [atom/electron#2129]
The `require('crypto')` on Renderer process gives a different object (and API) compared to on the Main process. The Renderer process gives the [DOM version of crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto), whereas the main process provides the actual NodeJS crypto package which I wanted.

My currently work around is to perform an IPC back to main process to access the NodeJS crypto library. Is this behaviour intended?

**Comment by zcbenz** [comment]
You should avoid using `var crypto = require('crypto')` under global scope, it will try to store to `window.crypto` which unfortunately can not be changed.

**Comment by mauris** [comment]
So the solution is to put the `require` statement within another inner scope? I'll give that a try. Many thanks for replying so quickly.

**Comment by zcbenz** [comment]
The simplest fix is to rename your variable to other than `crypto`, like `nodeCrypto = require('crypto')`.

**Comment by paulcbetts** [comment]
`screen` is another library that will troll you in this fashion

**Comment by francoislaberge** [comment]
@zcbenz What's the reasoning on this one? Why is this electron's behavior? I created a [debugger](https://www.npmjs.com/package/debugger) cli for node.js scripts using electron, and because of this you can't just run any arbitrary node.js app via including it into an electron page.

I worked around this by doing the following:
```js
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <title>Debugger</title>
</head>
<body>
    <script>
        /**
         * Ignore all this. This just includes the debugger target script
         */
        var ipc = require('ipc');
            src = ipc.sendSync('get-target-script');

        // We have to wrap the require in a scope to avoid issues like the following
        // where when trying to assign to certain named variables when in the global
        // scope it will be ignored because window.<variable-name> is read only.
        // See 'crypto' issue for example:
        // https://github.com/electron/electron/issues/2129
        (function(){
            require(src);
        })();
    </script>
</body>
</html>
```

Are there any obvious difference in the environments like this that I should be coding against? I find this much easier to use than using node-inspector. It's just
```bash
npm install -g debugger
debugger app.js
```

Thanks in advance!
Francois

**Comment by FruitJamUK** [comment]
@francoislaberge It's less Electron behaviour, and more a conflict between Chromium and Node behaviours, `window.crypto` exists in Chromium, unable to be over-written, so `crypto`'s just a namespace that can't be used in this instance.

At least you can call Node's `crypto` whatever you want, which seems like the most flexible solution. Maybe there could be better documentation of gotchas like this, but it beats taking away a Chromium feature people _could_ be expecting, when there's already a solution for Node `crypto` users.
