### ISSUE TITLE
X509 Verification error

### ISSUE THREAD

**Issue by matheusfaustino** [atom/electron#2135]
Hi, I'm making an app that uses a webview to render a URL with https and last week I started to get this error: 

    [21495:0706/094712:ERROR:cert_verify_proc_openssl.cc(231)] X509 Verification error unable to get local issuer certificate : 20 : 2 : 4

I really don't know what is wrong.
I'm using archLinux, electron v0.29.1 and node v0.12.5

Thanks for your attention

**Comment by zcbenz** [comment]
It had been fixed by #2128 and the fix will be included in next release.
