### ISSUE TITLE
v0.29.1 winx64 - taskbar menu gone

### ISSUE THREAD

**Issue by jackal-scratch** [atom/electron#2137]
Hi, I just updated from 0.27 to 0.29.1. In the prior version, when you right click on the app in the windows taskbar, a menu comes up with the option to close, pin, and open new. This seems to be gone in 0.29.1. 

Also, would anybody know if this task bar menu is customizable? Say i want to create a menu with the options maximize, minimize, close?

**Comment by zcbenz** [comment]
This sounds more likely a Windows bug to me, can you paste a screenshot?

> Also, would anybody know if this task bar menu is customizable? Say i want to create a menu with the options maximize, minimize, close?

You can find a a guide at https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#user-tasks-windows.

**Comment by jackal-scratch** [comment]
I'm not sure it's a bug with Windows, since if I switch back to 0.27.0, the menu will come back.
With 0.29.1, when i right click on the task in the task bar, nothing happens.


v0.27
![image](https://cloud.githubusercontent.com/assets/1057462/8547652/4717ad78-248e-11e5-9a8e-642e351199e9.png)

v0.29.1
![image](https://cloud.githubusercontent.com/assets/1057462/8547686/85df6942-248e-11e5-953a-5e8a36211479.png)

**Comment by carlosperate** [comment]
I'm using electron-prebuilt v0.29.1 and the right click on the taskbar works as expected on windows 8.1 x64.

**Comment by jackal-scratch** [comment]
Confirmed, it works on Windows 8. But not Windows 7.

**Comment by carlosperate** [comment]
Just tested it in a Windows 7 SP1 32 bit computer, and seems to be working fine there as well.

**Comment by LeMoussel** [comment]
Tested electron-v0.29.1-win32-x64 on 64 bit computer with Windows 7 SP1, working fine there as well.

**Comment by jackal-scratch** [comment]
I just updated to 0.29.2, looks like it's working fine for me again on Win 7. Will close. Thanks everybody.
