### ISSUE TITLE
getting Unmapped error reason: 268

### ISSUE THREAD

**Issue by bhargavrpatel** [atom/electron#2139]
Hello,

I am trying to send GET request to an Oauth server which returns a json containing token. Below, I have pasted my code. The output in the terminal is also posted in image form.

Note that while this doesn't affect my result, it is an error and not a warning.

```Javascript
function getToken(auth_code) {
  console.log("INSIDE GET TOKEN");
  let client_id = "1234";
  let client_secret = "aaaaaaaaaaaaa"; 
  let callback_uri = "https://localhost/callback";
  let url = `https://api.put.io/v2/oauth2/access_token?client_id=${client_id}&client_secret=${client_secret}&grant_type=authorization_code&redirect_uri=${callback_uri}&code=${auth_code}`;
  let request = require('superagent');

  request
    .get(url)
    .end(function (err, res) {
      console.log(res.text);  // Prints json as string with format: { "acess_token" : "ABCDEG" }
    });
}
```

### Output
![Image of Ouput](http://i.imgur.com/8FUr4Ml.png)

**Comment by zcbenz** [comment]
The #2128 should have fixed this, and it will be included in the next release.

**Comment by bhargavrpatel** [comment]
Thanks. Much respect
