### ISSUE TITLE
./scripts.build-dist on Linux fails with massive NSS symbol errors

### ISSUE THREAD

**Issue by capouch** [atom/electron#2143]
I have been regularly pulling from the master and building, including the dist target.

My latest attempt first failed with the libtinfo.so.5 error, which I found corrected yesterday in the documentation.   After fixing that, the D/R targets built just fine.

However, the dist target now fails, first with a slew of messages along these lines:
** snip **
/var/lib/jenkins/workspace/libchromiumcontent-linux/vendor/chromium/src/out/Release/../../net/third_party/nss/ssl/sslsock.c:2901: undefined reference to `PR_GetUniqueIdentity'
/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libcrssl.a(libssl.sslsock.o): In function `ssl_SetupIOMethods':
/var/lib/jenkins/workspace/libchromiumcontent-linux/vendor/chromium/src/out/Release/../../net/third_party/nss/ssl/sslsock.c:2859: undefined reference to `PR_GetDefaultIOMethods'
**

Re-running with -v, it ends like this:
** snip
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "./script/create-dist.py", line 213, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 85, in main
    force_build()
  File "./script/create-dist.py", line 107, in force_build
    execute([sys.executable, build, '-c', 'Release'])
  File "/usr/src/electron/script/lib/util.py", line 166, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/usr/src/electron/script/build.py', '-c', 'Release']' returned non-zero exit status 1

**Comment by zcbenz** [comment]
Sorry for the trouble, the master branch should work now.
