### ISSUE TITLE
PPAPi flash debug output

### ISSUE THREAD

**Issue by leshow** [atom/electron#2155]
electron version 29.2
testing on windows 8 and linux

I'm using code similar to this to set the flash player path

```
app.commandLine.appendSwitch('ppapi-flash-path', '/path/to/libpepflashplayer.dll');

// Specify flash version, for example, v17.0.0.169
app.commandLine.appendSwitch('ppapi-flash-version', '17.0.0.169');
```

rather than using the flash player included with chrome i've downloaded the debug version and used that [instead] (https://www.adobe.com/support/flashplayer/downloads.html) 

to confirm I have a working version of the debug player I replaced chromes libpepflashplayer.dll with the one installed from [here](https://fpdownload.macromedia.com/pub/flashplayer/updaters/18/flashplayer_18_ppapi_debug.exe)

then I restarted chrome and went [here](https://helpx.adobe.com/flash-player.html) and next to the version number I have (debug version) in red.

So in my electron app, I pointed ppapi-flash-path to this debug version and ran a swf that should generate some errors, however I don't see any errors in a pop-up or in the console.

How do you get the debug output from ppapi player?

**Comment by zcbenz** [comment]
How does the debug messages look like in Chrome? I think maybe we didn't have some debug interfaces implemented in Electron, having a screenshot should give us some clues on how to fix that.

**Comment by leshow** [comment]
I think I've solved this, it's another case of adobe having bad documentation; so I'll document things here.

You can create a file called mm.cfg in `app.getPath('appData') /electron-app/Pepper Data/Shockwave Flash/System/`

if you set the contents of that file to be: 
```
ErrorReportingEnable=1
TraceOutputFileEnable=1
```

when the application is run it will create a `flashlog.txt` file in `app.getPath('appData') /electron-app/Pepper Data/Shockwave Flash/WritableRoot/Logs/`

the contents of that file will be the debug/trace output from any swf file played by the pepper flash plugin.

**Comment by zcbenz** [comment]
Thanks for sharing that!

**Comment by jygao** [comment]
can i use the flash debugger in electron ?  i used the debug flash player ,but it won't pop-up error ,and i can not get the stack error info.

**Comment by jygao** [comment]
after some time ,when i had wrote some code to parse the flashlog.txt and popped up error tip in my app ,i found i haven't used the flash debugger version!
