### ISSUE TITLE
Unable to capture <Ctrl> + <Alt> + <Delete> key combination on Windows

### ISSUE THREAD

**Issue by toxickg** [atom/electron#2156]
I'm not able to capture `Ctrl`+`Alt`+`Delete` key combination using `global-shortcut` module in an app on Windows, while it works on Linux. Here's the shortcuts capturing code from the entry point script of the application:

```javascript
...
var globalShortcut = require('global-shortcut')
var shortcutsToCapture = ['Ctrl+Alt+Delete', 'Alt+F4', 'Ctrl+A']
...

app.on('ready', function () {

  captureShortcuts(shortcutsToCapture)
...
})

function captureShortcuts(shortcuts) {
  shortcuts.forEach(function (shortcut) {
    registerShortcutCapturing(shortcut)
  })
}

function registerShortcutCapturing(shortcut) {
  var result = globalShortcut.register(shortcut, function () {
    console.log('<' + shortcut + '> captured!')
  })

  if (!result) {
    console.log('<' + shortcut + '> registration failed!')
  }
}
```

Using `Control` instead of `Ctrl` key code doesn't make the difference, I always get the same message in the console: `<Ctrl+Alt+Delete> registration failed!`.

I tried it on Windows 7 (32-bit) with Electron version 0.28.3 and version 0.29.2. Once again, the same app successfully registers `Ctrl`+`Alt`+`Delete` combination capturing on Linux.

**Comment by paulcbetts** [comment]
Nobody can capture C-A-D on Windows, only the OS can do it.

**Comment by toxickg** [comment]
What I actually wanted to do is to disable `Ctrl`+`Alt`+`Delete` combination whatsoever, rather than capture it. I've discovered an alternative way to do that by tweaking the Windows registry.

@paulcbetts, thank you for the info!

**Comment by badlee** [comment]
My contribution http://www.northcode.com/blog/Securing-Windows-For-Use-As-A-Kiosk

**Comment by CharmyZ** [comment]
> What I actually wanted to do is to disable `Ctrl`+`Alt`+`Delete` combination whatsoever, rather than capture it. I've discovered an alternative way to do that by tweaking the Windows registry.
> 
> @paulcbetts, thank you for the info!

can i know how to disable Ctrl+Alt+Delete combination ？
