### ISSUE TITLE
Unable to move the cache

### ISSUE THREAD

**Issue by bhargavrpatel** [atom/electron#2157]
Hello, 

I am getting this error: 
![Unable to move Cache](http://i.imgur.com/6CRJYcS.png)

You may check code that causes this ![here](https://github.com/bhargavrpatel/viewput.io/blob/master/app/main.es6.js). When I uncomment line 45 to 47, I do not get the error.

**Comment by zcbenz** [comment]
The error means it failed to move a file while there is no error happened... not exactly understanding the reason but I think you can try removing `C:\...\viewputio` and do a restart of your computer.

Anyway this error can be safely ignored, so I'm closing this.

**Comment by rzfzr** [comment]
For somebody else finding this error, in my case it was due to having another app running in development at the same time...
```
[21560:0614/141906.583:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[21560:0614/141906.584:ERROR:cache_util.cc(145)] Unable to move cache folder C:\Users\capit\AppData\Roaming\Electron\GPUCache to C:\Users\capit\AppData\Roaming\Electron\old_GPUCache_000
[21560:0614/141906.584:ERROR:disk_cache.cc(196)] Unable to create cache
[21560:0614/141906.584:ERROR:shader_disk_cache.cc(613)] Shader Cache Creation failed: -2
C:\Users\capit\AppData\Roaming\npm\node_modules\electron\dist\electron.exe exited with signal SIGINT
PS C:\Users\capit\Desktop\GitGud\Test> electron .\dist\main.js
```

**Comment by ronyshaji** [comment]
> For somebody else finding this error, in my case it was due to having another app running in development at the same time...
> 
> ```
> [21560:0614/141906.583:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
> [21560:0614/141906.584:ERROR:cache_util.cc(145)] Unable to move cache folder C:\Users\capit\AppData\Roaming\Electron\GPUCache to C:\Users\capit\AppData\Roaming\Electron\old_GPUCache_000
> [21560:0614/141906.584:ERROR:disk_cache.cc(196)] Unable to create cache
> [21560:0614/141906.584:ERROR:shader_disk_cache.cc(613)] Shader Cache Creation failed: -2
> C:\Users\capit\AppData\Roaming\npm\node_modules\electron\dist\electron.exe exited with signal SIGINT
> PS C:\Users\capit\Desktop\GitGud\Test> electron .\dist\main.js
> ```

Did you solved the problem?

**Comment by joatansampaio** [comment]
> For somebody else finding this error, in my case it was due to having another app running in development at the same time...
> 
> ```
> [21560:0614/141906.583:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
> [21560:0614/141906.584:ERROR:cache_util.cc(145)] Unable to move cache folder C:\Users\capit\AppData\Roaming\Electron\GPUCache to C:\Users\capit\AppData\Roaming\Electron\old_GPUCache_000
> [21560:0614/141906.584:ERROR:disk_cache.cc(196)] Unable to create cache
> [21560:0614/141906.584:ERROR:shader_disk_cache.cc(613)] Shader Cache Creation failed: -2
> C:\Users\capit\AppData\Roaming\npm\node_modules\electron\dist\electron.exe exited with signal SIGINT
> PS C:\Users\capit\Desktop\GitGud\Test> electron .\dist\main.js
> ```

In other words, check out your open terminals and see if you haven't left another instance of the app opened.

**Comment by kimim** [comment]
Running multiple instances of an app with the same user-data directory isn't supported by Chrome, and thus isn't supported by Electron either. You'll need to use requestSingleInstanceLock, an in-memory session, or a separate data directory for each instance.

**Comment by sunjinbo321** [comment]
> Chrome 不支持使用同一个用户数据目录运行多个应用实例，因此 Electron 也不支持。您需要为每个实例使用 requestSingleInstanceLock、内存会话或单独的数据目录。

但是我想Electron 实现软件多开，第二次启动不能加载这个缓存会导致第二次启动比第一次启动慢4秒左右，请问有什么更好的解决方案嘛

**Comment by rzfzr** [comment]
@sunjinbo321 do you really need multiple instances? if not you can easily handle multiple windows instead.

**Comment by sunjinbo321** [comment]
> @sunjinbo321 do you really need multiple instances? if not you can easily handle multiple windows instead.



> @sunjinbo321 do you really need multiple instances? if not you can easily handle multiple windows instead.

**Comment by sunjinbo321** [comment]
> > @sunjinbo321 do you really need multiple instances? if not you can easily handle multiple windows instead.
> 
I did open multiple Windows, but because electron does not allow multiple processes to access idndexDB, the second start will take a while longer than the first start. I have solved it by using session isolation. But multiple processes still have problems with localstorage, and electron does not solve them. I really appreciate your reply

**Comment by SAKryukov** [comment]
I recently faced this problem on Windows. Solved it by manually removing VSCode cache, including GPU cache, and restarting Windows. Before restarting Windows, the problem persisted. The location of caches (there are several directories) depends on several factors (platform and type of installation). To locate it, run VSCode and enter the command (F1):

~~~text
Developer: Reveal User Data Folder
~~~

Look in this directory. If you delete it completely (or temporarily rename it), this is the way to reset everything to the factory defaults. This is safe, but it will require redoing all the settings. You can leave `extensions` as is, this is safe. But better remove parts of user data selectively, for example, the caches.

Still, this kind of glitch is still a problem. I don't know how to reproduce it from scratch.
