### ISSUE TITLE
looking for a document, required files

### ISSUE THREAD

**Issue by gaccettola** [atom/electron#2160]
I've successfully built electron from the sources on windows 8.1, 
Next I'd like to take only the files I need from \electron\out\R\ to work on an install package, but I don't see any documents on which files are required on windows.

Or am I doing this wrong?  I am only half guessing that \electron\out\R\ can be cleaned since I see .h files in there.  How do I clean \electron\out\R\?

Any help or a nod in a direction is appreciated.

**Comment by hokein** [comment]
You can use `script/create-dist.py` to create a package for your custom builds. A zip file that contains all dependent libraries will be generated.
