### ISSUE TITLE
Illegal instruction with Linux ARM

### ISSUE THREAD

**Issue by dustinblackman** [atom/electron#2162]
Currently getting `Illegal instruction` when using the new ARM build on a fresh Raspberry Pi B+ (1) with the latest Rasbian. No other output is given.

**Comment by carlosperate** [comment]
I believe the ARM version is compiled for the ARMv7 instruction set, and the B+ uses v6, so it'll be only compatible with the Pi 2.

**Comment by zcbenz** [comment]
The arm build is only available for ARMv7 machines, ARMv6 machines are not powerful enough to run latest Chromium smoothly so we won't have support for them.
