### ISSUE TITLE
Silent fail of render logic when calling ipc.sendSync

### ISSUE THREAD

**Issue by JavaScriptDude** [atom/electron#2163]
Given I have the following main.js:
```
 
var app = require('app');
var BrowserWindow = require('browser-window'); 
var ipc = require('ipc');

app.on('ready', function() {
  var mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.on('closed', function() {mainWindow = null;});
});


ipc.on('my-sync-ipc', function(event) {
  console.log('my-sync-ipc called');
});

ipc.on('my-async-ipc', function(event) {
  console.log('my-async-ipc called');
});
```

And the following index.html:
```
 <!DOCTYPE html>
<html>
  <head>
    <title>IPC Bug Test!</title>
  </head>
  <body>

    <script>

      var ipc = require('ipc');

      console.log("before my-async-ipc Call")
      ipc.send('my-async-ipc')
      console.log("after my-async-ipc Call")
		
      console.log("before my-sync-ipc Call")
      ipc.sendSync('my-sync-ipc')
      // Code stops here. No errors or messages.
      console.log("after my-sync-ipc Call")
		
    </script>
  </body>
</html>
```

After running I found the following console output:
```
before my-async-ipc Call
after my-async-ipc Call
before my-sync-ipc Call
```

The last line never fires. No errors or messages in the console or main process stdout.

My Electron version is 0.29.1. Platform: Linux

**Comment by zcbenz** [comment]
You have to set `returnValue` when handling synchronous messages:
https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md

Otherwise the web page would wait for responses forever.

**Comment by JavaScriptDude** [comment]
Understood. The documentation should be updated with a note that setting event.returnValue is a required step for sendSync. Its not intuitive to set event.returnValue=null or undefined.

**Comment by JavaScriptDude** [comment]
Is it possible to update the logic behind ipc.sendSync to have the setting of returnValue optional? I am sure that others will get burned by the same issue and silent fails are very nasty to hit for developers.

**Comment by JavaScriptDude** [comment]
Work around for others who hit this. Just set event.returnValue = null; in your IPC handler in the main process and the renderer code is then allowed to continue.
