### ISSUE TITLE
ES6 Promise doesn't work in 0.29.x

### ISSUE THREAD

**Issue by cnjon** [atom/electron#2165]
1.Promise doesn't work:
```javascript
mainWindow.webContents.on('did-finish-load',function(){
  	try{
	  	console.log(`${new Date()} : did-finish-load.`);

	  	console.log(`${new Date()} : Promise.`);
	  	Promise.resolve().then(function(){
	  		console.log(`${new Date()} : Promise.resolve.`);
	  	},function(){
	  		console.log(`${new Date()} : Promise.reject.`);
	  	});
	  	console.log(`${new Date()} : End Promise.`);
	}catch(ex){
		console.log(`${new Date()} : error : ${ex}.`);
	}
  });
```
I tried electron v0.28.1 and v0.28.3, it works fine.

2."--disable-gpu" doesn't work
```javascript
app.commandLine.appendSwitch('--disable-gpu');
```
In electron v0.28.1 and v0.28.3, it works fine too.

**Comment by zcbenz** [comment]
I tried to run

```js
        Promise.resolve().then(function(){
            console.log(`${new Date()} : Promise.resolve.`);
        },function(){
            console.log(`${new Date()} : Promise.reject.`);
        });
```

in Chrome's devtools, it prints:

 ```js
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
```

And in Electron it prints the exactly the same thing.

> 2."--disable-gpu" doesn't work

Can you open url `chrome://gpu` in your app and paste the result?

**Comment by cnjon** [comment]
1.
```javascript
mainWindow.webContents.on('did-finish-load',function(){
  	try{
	  	console.log(`did-finish-load.`);

	  	console.log(`Start Promise.`);
	  	Promise.resolve().then(function(){
	  		console.log(`Promise.resolve.`);
	  	},function(){
	  		console.log(`Promise.reject.`);
	  	});
	  	console.log(`End Promise.`);
	}catch(ex){
		console.log(`${new Date()} : error : ${ex}.`);
	}
  });
```
In v0.28.3,it prints:
![0 28 3](https://cloud.githubusercontent.com/assets/10810189/8613414/832f1d0c-2711-11e5-8694-eca7ff261f7b.png)
The same code,In v0.29.2,it prints:
![0 29 2](https://cloud.githubusercontent.com/assets/10810189/8613426/987da750-2711-11e5-8678-873e4e27b41a.png)

2.
```javascript
app.commandLine.appendSwitch('--disable-gpu');
```
In v0.28.3,it has 2 processes:
![0 28 3-gpu](https://cloud.githubusercontent.com/assets/10810189/8613582/280f8c0c-2713-11e5-89fa-b44b976a4eeb.png)
In v0.29.2,it has 3 processes:
![0 29 2-gpu](https://cloud.githubusercontent.com/assets/10810189/8613592/3f27d11a-2713-11e5-91d2-de347efb9828.png)

**Comment by zcbenz** [comment]
I downloaded the binaries from the Releases page and tested the x64 and ia32 binaries on a Windows 8.1 machine, and I can not reproduce what you said.

For the first problem, I tested by running this script:

```
    try{
        console.log(`${new Date()} : did-finish-load.`);

        console.log(`${new Date()} : Promise.`);
        Promise.resolve().then(function(){
            console.log(`${new Date()} : Promise.resolve.`);
        },function(){
            console.log(`${new Date()} : Promise.reject.`);
        });
        console.log(`${new Date()} : End Promise.`);
    }catch(ex){
        console.log(`${new Date()} : error : ${ex}.`);
    }
```

And this command

```
./electron-v0.29.2-win32-x64/electron.exe test.js
```

prints

```
[3068:0710/093107:INFO:CONSOLE(0)] did-finish-load.
[3068:0710/093107:INFO:CONSOLE(0)] Start Promise.
[3068:0710/093107:INFO:CONSOLE(0)] End Promise.
[3068:0710/093107:INFO:CONSOLE(0)] Promise.resolve.
```

For the second problem and I tested in this way:

```
./electron-v0.29.2-win32-x64/electron.exe --disable-gpu
```

And there is no GPU process.

Please provide reproducible example apps.

**Comment by LeMoussel** [comment]
Like @zcbenz , Tested on Windows 7 with  ia32 binaries (electron-v0.29.1-win32-ia32).
`electron-v0.29.1-win32-ia32\electron.exe --disable-gpu`
There is no GPU process, only 2  processes.

And with this code script
```javascript
var app = require('app');
app.commandLine.appendSwitch('--disable-gpu');
app.on('ready', function() {
  // Your code here
});
```
It has 2 processes.

**Comment by LeMoussel** [comment]
For the first problem I tested the @zcbenz script on Windows 7 with ia32 binaries (electron-v0.29.1-win32-ia32).
Print same result that @zcbenz script.

**Comment by cnjon** [comment]
I tested on Windows 7 x64, with ia32 binaries (electron-v0.29.2-win32-ia32) & x64 binaries (electron-v0.29.2-win32-x64),download from https://npm.taobao.org/mirrors/electron/0.29.2/
![sys](https://cloud.githubusercontent.com/assets/10810189/8632886/fa9de8b2-27e0-11e5-92d8-9bdf0d53b595.png)

I tested this code on another PC, print save result.

main.js:
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

app.on('window-all-closed', function() {
  app.quit();
});

app.commandLine.appendSwitch('--disable-gpu');
app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });
  mainWindow.webContents.on('did-finish-load',function(){
  	try{
	  	console.log(`did-finish-load.`);
	  	console.log(`Start Promise.`);
	  	Promise.resolve().then(function(){
	  		console.log(`Promise.resolve.`);
	  	},function(){
	  		console.log(`Promise.reject.`);
	  	});
	  	console.log(`End Promise.`);
	}catch(ex){
		console.log(`error : ${ex.message}.`);
	}
  });
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.focus();
});
```

I don't know why...

**Comment by NIM-Pro** [comment]
A similar problem.
Version: 0.29.2.
OS: Windows 7 x64.

Code:
``` js
function Message(text) {
    var win=createWindow('application://index.html')
    return new Promise(function(resolve,reject) {
        win.webContents.once('ipc-message', function(e, args) {
            console.log('ipc-message', args)
            if (args[0]==='resolve') {
                console.log('args[0]==="resolve" => true')
                resolve(args[1])
                //win.close()
            }
        })
    })
}

app.on('ready', function() {
    Message('azaza')
    .then(function(value) {
        console.log('Resolved',value)
    })
    .catch(function(e) {
        console.log(e.stack||e)
    })
})
```
Output:
```
[5216:0713/022619:INFO:CONSOLE(0)] ipc-message [ 'resolve', 'Work, please!' ]
[5216:0713/022619:INFO:CONSOLE(0)] args[0]==="resolve" => true

**Comment by cnjon** [comment]
@NIM-Pro But,it works fine in electron v0.28.x,just 0.29.x has this problem.

@zcbenz  help me,please!

**Comment by tengyifei** [comment]
Both 0.29.1 and 0.29.2 have this problem on OS X. Similar to @NIM-Pro 's suggestion, wrapping the promise with `setTimeout`, `setInterval`, or `process.nextTick` works around the issue. Heck it's even fixed when there is `console.log` statement preceding the `.then()` call, which I think also delays it into the next iteration of the event loop.

It seems that promises only malfunction when they are inside an event listener in the main process.
