### ISSUE TITLE
window.open() doesn't work with relative URLs

### ISSUE THREAD

**Issue by duanyao** [atom/electron#2166]
Suppose a local file `index.html` is loaded by electron which looks like

```
<!DOCTYPE html>
<meta charset="UTF-8" />
<button onclick="window.open('index.html')">test open</button>
```

Click "test open" button, a new window is opened, but `index.html` is not loaded in the new window (`about:blank` is loaded instead). `window.open()` seems only work with absolute URLs.

Tested with electron v0.29.2 linux 64bit.

**Comment by duanyao** [comment]
Hi @zcbenz, thanks for the quick fix. I know little about the internals of Electron and not sure what https://github.com/atom/electron/commit/260ec96edd9fad146ddbbf3be4abcf483d59c501 does exactly.

If an iframe's `window.open(url)` is called from its parent's JS context, which document will be used to resolve the relative `url`, the parent's or the child's? The correct answer is the the parent's. see https://bugzilla.mozilla.org/show_bug.cgi?id=1044950#c2
However I suspect your fix always takes the child's base URL to resolve the relative `url`.

**Comment by zcbenz** [comment]
@duanyao I didn't notice that, thanks for pointing it out. I'll have a fix for that.

**Comment by fgnass** [comment]
With the last change (the one that always uses `window.top.document` to resolve relative URLs) calling  `window.open()` from within an iframe no longer works. I currently see no easy fix to properly handle both cases, but I'd argue that the case where an iframe wants to open a URL relative to itself is much more common. Can we re-open the issue or should I file a new one?
