### ISSUE TITLE
asar.exe recognised as trojan by Avast antivirus

### ISSUE THREAD

**Issue by LukaszGrela** [atom/electron#2167]
Windows 8.1, Avast 2015.10.2.2218, asar.exe 0.10.38.0

Avast recognises this file as infected with Trojan Win32:Agent-AZHR[Trj]

I've sent this file to Avast for possible "false alarm".

**Comment by paulcbetts** [comment]
Can you report this as a false positive? This is more interesting than most of these bogus reports because it is recognizing an _actual_ virus and not just a heuristic. I wonder if Agent-AZHR is incorporating ASARs codebase somehow...

**Comment by LukaszGrela** [comment]
Yes, I've reported it, I've also tested the file with other AV's and it was fine.

**Comment by zcbenz** [comment]
Actually I think it is actually an virus, there is no `asar.exe` in Electron or the asar command line tool.

**Comment by LukaszGrela** [comment]
@zcbenz what is this then? https://github.com/atom/electron/commits?author=zcbenz
