### ISSUE TITLE
option to turn off sound when loading a BrowserWindow

### ISSUE THREAD

**Issue by matthewmueller** [atom/electron#2169]
If I do something like this:

```js
var win = new BrowserWindow({ show: false });
win.loadUrl('http://youtube.com')
```

It will immediately start playing an ad (or something). Is there a way to disable sound when you're not showing the window?

**Comment by deepak1556** [comment]
there is `setAudioMuted` api on [webContents](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#webcontentssetaudiomutedmuted)

**Comment by matthewmueller** [comment]
Gah. Thanks. Don't know how I missed that.
