### ISSUE TITLE
v0.29.0 error during bootstrap.py -v --target_arch=arm

### ISSUE THREAD

**Issue by bbarnett** [atom/electron#2173]
gyp verb content checksum node-v0.29.0.tar.gz 9b5c434f25d8fe043e01c732f5b2ab519feb93905d935655aea43acc486afdef
gyp verb extracted file from tarball src/tty_wrap.h
gyp verb extracted file from tarball src/udp_wrap.h
gyp verb extracted file from tarball src/util-inl.h
gyp verb extracted file from tarball src/util.h
gyp verb extracted file from tarball src/v8abbr.h
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`... 
gyp verb checksum url https://atom.io/download/atom-shell/v0.29.0/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v0.29.0/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v0.29.0/SHASUMS256.txt
gyp verb checksum data {"node-v0.29.0.tar.gz":"604f44ad1f61d123f5e9340fcfb02213ed012d8f29023f4fa27a61094b9c318d","iojs-v0.29.0.tar.gz":"fcf25ebda7bbca7e9ac17e525caf06a04c8180861b3e5042857e93e808a82716","node.lib":"d75c06df0abebdac567424218e8b818a91ea78114416217f309cbaf76c773103","x64/node.lib":"4f3b58e24b5decac6808c807ba0fd04f47f82ebeb254cd5cb151bcad97e33127","win-x86/iojs.lib":"d75c06df0abebdac567424218e8b818a91ea78114416217f309cbaf76c773103","win-x64/iojs.lib":"4f3b58e24b5decac6808c807ba0fd04f47f82ebeb254cd5cb151bcad97e33127"}
gyp verb download contents checksum {"node-v0.29.0.tar.gz":"9b5c434f25d8fe043e01c732f5b2ab519feb93905d935655aea43acc486afdef"}
gyp verb validating download checksum for node-v0.29.0.tar.gz (9b5c434f25d8fe043e01c732f5b2ab519feb93905d935655aea43acc486afdef == 604f44ad1f61d123f5e9340fcfb02213ed012d8f29023f4fa27a61094b9c318d)
gyp WARN install got an error, rolling back install
gyp verb command remove [ '0.29.0' ]
gyp verb remove using node-gyp dir: /home/bbarnett/.node-gyp
gyp verb remove removing target version: 0.29.0
gyp verb remove removing development files for version: 0.29.0
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.29.0.tar.gz local checksum 9b5c434f25d8fe043e01c732f5b2ab519feb93905d935655aea43acc486afdef not match remote 604f44ad1f61d123f5e9340fcfb02213ed012d8f29023f4fa27a61094b9c318d
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 3.16.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bbarnett/work/atom/electron/spec/node_modules/runas
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm verb unsafe-perm in lifecycle true
npm info runas@2.0.0 Failed to exec install script
npm verb unlock done using /home/bbarnett/.npm/_locks/runas-41170dad36323d0d.lock for /home/bbarnett/work/atom/electron/spec/node_modules/runas
npm verb stack Error: runas@2.0.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid runas@2.0.0
npm verb cwd /home/bbarnett/work/atom/electron/spec
npm ERR! Linux 3.16.0-43-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/runas
npm info preuninstall runas@2.0.0
npm info uninstall runas@2.0.0
npm verb unbuild rmStuff runas@2.0.0 from /home/bbarnett/work/atom/electron/spec/node_modules
npm info postuninstall runas@2.0.0
npm verb gentlyRm don't care about contents; nuking /home/bbarnett/work/atom/electron/spec/node_modules/runas

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bbarnett/work/atom/electron/spec/npm-debug.log

**Comment by zcbenz** [comment]
This had been fixed in v0.29.1:

> Changelog:
> 
> Fix native modules unable to be built with iojs < 2.3.1.
