### ISSUE TITLE
app.dock.hide() suppresses errors

### ISSUE THREAD

**Issue by matthewmueller** [atom/electron#2174]
Running:

```
$ electron runner.js
```

On **runner.js**: 

```js
var app = require('app');
app.on('ready', function() {
  console.log('ready!');
  aksjdflkasjdf()()
  console.log('got here? yah right.');
})
```

Yields:

![img](https://cldup.com/wa4x_dbRxD.png)

But if I have:

```js
var app = require('app');
app.dock.hide();
app.on('ready', function() {
  console.log('ready!');
  aksjdflkasjdf()()
  console.log('got here? yah right.');
})
```

Nothing happens. 

Also, would love to be able to ignore the window popping up, and just see the error in the console. Is that possible?

**Comment by deepak1556** [comment]
> Also, would love to be able to ignore the window popping up, and just see the error in the console. Is that possible?

doesnt `process.on('uncaughtException', callback)` help ?

**Comment by zcbenz** [comment]
This is because calling `app.dock.hide();` would turn your app into a background process, and when your app doesn't have focus OS X will not show your app's dialogs. This is by design in OS X so we won't be able to fix it.

A work-around is to call `app.focus()` for your app.
