### ISSUE TITLE
Error working with Flash Plugin in Windows

### ISSUE THREAD

**Issue by rjusher** [atom/electron#2176]
So I was trying to embed some videos in a electron app, but the following code works in linux and not in windows. In Windows it just says couldn't load plugin.

I am working on a Windows 8 64bits, with electron 0.29.2 and io.js 2.3.1
In Linux I am using a Ubuntu 14.04 LTS, electron 0.29.2 and io.js 2.3.1

Both the .dll and the .so files are in the same folder under application

```javascript
var app = require('app');
var BrowserWindow = require('browser-window');
var dialog = require('dialog')

require('crash-reporter').start();

var mainWindow = null;

app.on(
  'window-all-closed', function() {
    if(process.platform != 'darwim'){
      app.quit();
    }
  });

if(process.platform  == 'win32'){
  app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '/pepflashplayer.dll');
  app.commandLine.appendSwitch('ppapi-flash-version', '17.0.0.169');
} else if (process.platform == 'linux') {
  app.commandLine.appendSwitch('ppapi-flash-path', __dirname + '/libpepflashplayer.so');
  app.commandLine.appendSwitch('ppapi-flash-version', '17.0.0.169');
}

app.on('ready', function(){

	mainWindow = new BrowserWindow(
		{
			width:800,
			height:600,
			'web-preferences': {
				'plugins': true
			}
		});

	mainWindow.loadUrl('file://' + __dirname + '/index.html');
	mainWindow.openDevTools();

	mainWindow.on('closed', function(){
		mainWindow = null;
	});
});
```

**Comment by paulcbetts** [comment]
My psychic debugger says that you've got a different architecture Electron vs. your pepflashplayer.dll (i.e. 64-bit Flash and 32-bit Electron.exe or vice-versa)

**Comment by rjusher** [comment]
Thanks @paulcbetts:
I wiil lookup further into this.

**Comment by rjusher** [comment]
Your psychic debugger was absolutely right, it was a problem with the version of electron that I had downloaded, replaced it with the 32 bits .exe and it worked.

Just a last question how can I get the .dll for a 64 bit electron.

**Comment by rjusher** [comment]
Already found the dll thanks.

**Comment by rx4hvn** [comment]
@rjusher where did you find dll for 64 bits

**Comment by piecedigital** [comment]
How were you able to get the 64 bit version of Electron?

**Comment by rx4hvn** [comment]
@piecedigital check the link below
https://github.com/atom/electron/releases
