### ISSUE TITLE
El Capitan Open Window Dialog

### ISSUE THREAD

**Issue by wisesascha** [atom/electron#2178]
In OS X El Capitan it is impossible to use the open window when it is not bound to a window. This is a demo of the working version: http://gfycat.com/AggravatingHardAmmonite . This is a demo of it not working: http://gfycat.com/DeterminedUnkemptFeline . This also shows up in [Atom](https://github.com/atom/atom/issues/7811).

**Comment by zcbenz** [comment]
I don't know if we can fix it on Electron's side, I think we should just wait for El Capitan to be stable.

**Comment by thomasjo** [comment]
*Cross post from https://github.com/atom/atom/issues/7811*

---

I can reproduce the problems on 15A215h.
Here's a snippet of the relevant parts of the system log:
https://gist.github.com/thomasjo/7d5755428327361b8798

The part that stands out is
```
BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
```

I believe that is triggered when you launch the *Open* dialog. Hard to time exactly, but I get the same stuff dumped every time I provoke the problem.

**Comment by crazytyper** [comment]
I have narrowed it down to the following:

```javascript
var remote = require('remote');
var dialog = remote.require('dialog');
   
// dialog works as expected:
dialog.showOpenDialog(remote.getCurrentWindow(), { properties: [ 'openFile' ]});

// dialog will not close:
dialog.showOpenDialog({ properties: [ 'openFile' ]});
```

**Comment by RodrigoEspinosa** [comment]
The same issue is also happening for `showSaveDialog`, however @crazytyper solution where you specified the browser window, worked for that as well.

**Comment by zcbenz** [comment]
Fixed by el capitan beta 3

**Comment by adzymaniac** [comment]
Anyone have this problem with signed binary for mas submission?
I use electron-v0.34.0-mas-x64.zip and cannot open dialog after signin.
