### ISSUE TITLE
Arm cross compile still not working out of the box

### ISSUE THREAD

**Issue by bbarnett** [atom/electron#2181]
Making progress, v0.29.0 does not really support Arm cross compile, so by using v0.29.1, I've gotten the "bootstrap" to work, now when I run build.py, I get this:

bbarnett@baymax:~/work/atom/electron$ ./script/build.py
ninja: Entering directory `out/R'
[921/1017] SOLINK lib/libnode.so
FAILED: if [ ! -e lib/libnode.so -o ! -e lib/libnode.so.TOC ]; then /home/bbarnett/work/atom/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,noexecstack -Wl,--whole-archive  -Wl,--no-whole-archive -pthread -Wl,--whole-archive /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicui18n.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_base.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_external_snapshot.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libbase.a --sysroot=/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot -L/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -L/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -target arm-linux-gnueabihf -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.TOC; else /home/bbarnett/work/atom/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,noexecstack -Wl,--whole-archive  -Wl,--no-whole-archive -pthread -Wl,--whole-archive /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicui18n.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_base.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_external_snapshot.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a /home/bbarnett/work/atom/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libbase.a --sysroot=/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot -L/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -L/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/atom/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -target arm-linux-gnueabihf -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.tmp && if ! cmp -s lib/libnode.so.tmp lib/libnode.so.TOC; then mv lib/libnode.so.tmp lib/libnode.so.TOC ; fi; fi
/usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 i386linux elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[921/1017] CXX obj/atom/browser/electron_lib.web_view_manager.o
ninja: build stopped: subcommand failed.

Let me know if you need mor einformation.

**Comment by zcbenz** [comment]
You need to install cross compilation toolchains for arm, I have added the instructions in docs.
