### ISSUE TITLE
`global` object defined in webview

### ISSUE THREAD

**Issue by alexindigo** [atom/electron#2183]
Hi,

I noticed that `global` object defined in the webview (it's reference to the `window`, but) it's different from regular browser "environment" where `global` object is undefined. And many libraries (primary UMD-type ones) make decision on which branch of code to execute based on the existence of `global` object. Which would lead to breakage of the page loaded into webview, or at least would produce different experience for the end user.

I did try to add "userland" fix for the issue, but it yelled at me :)

Added `preload` script for webview

```
process.nextTick(function(){ global = undefined; });
```

Result:
![error](http://ia.gs/bvb7/Image%202015-07-10%20at%209.32.46%20AM.png)

**Comment by paulcbetts** [comment]
What you want is `delete global` instead

**Comment by paulcbetts** [comment]
> And many libraries (primary UMD-type ones) make decision on which branch of code to execute based on the existence of global object. 

You most likely need to patch these libraries, there are bunch of JS libs that make decisions that don't make sense to Electron. Send PRs!

**Comment by alexindigo** [comment]
If I do `delete global` I get same error, since it's used in that `init.js:86` and I can't get to that `asar` file to actually see what's going on there.

As for fixing all the libraries. It will be noble movement, but somewhat futile one. :)

All the browsers don't expose `global` object and only `window` one, I don't think webview should be purposively different from the thing it's trying to emulate.

Do you think there are benefits in existence of `global` object within webview?

Thank you.

**Comment by paulcbetts** [comment]
> As for fixing all the libraries. It will be noble movement, but somewhat futile one. :)

That's really the only way to do it though (or to fix UMD) - this isn't a single bug, it's a whole bunch of weird one-off wrong decisions that these libraries are making

> Do you think there are benefits in existence of global object within webview?

Do you have `node-integration` set to false? I could see an argument for that if this is the case

**Comment by alexindigo** [comment]
Yes, `node-integration` is false (or at least I assume it's the default, I don't mind to have explicit flag for that either). I do understand that `node-integration` makes it whole new story. :) My concern is emulating real browser as close as possible (no node or extra apis).

**Comment by jprichardson** [comment]
@alexanderneu correct me if I'm wrong, but don't most UMD libraries look for `module` and `module.exports`, and then `define`? If they can't find any of those, they just export to the function wrapper that passes in `window`?

**Comment by alexindigo** [comment]
@jprichardson While testing [global-define](https://www.npmjs.com/package/global-define) I bumped into many different implementations. Even within one project (third and forth dependency tiers). I don't remember all the names off hand, but I think it's safe to assume there will be as many implementations as there are the ways to achieve desired result.

And from where I stand, I don't see benefits in having `global` available in webview without node-integration. Please correct me if I'm wrong.

Thank you.

**Comment by jprichardson** [comment]
@alexindigo You have a point. I agree that `global` should not be available if `node-integration` is `false`.
