### ISSUE TITLE
Fullscreen transparent window is not transparent, distorted and non-functional.

### ISSUE THREAD

**Issue by ankitaggarwal011** [atom/electron#2184]
**Issues**
1. If fullscreen and transparent flags are both set to true, the fullscreen window displayed is completely white and not transparent. 
2. If the transparent flag is set to true and fullscreen flag is set to false, using specific allowed dimensions on the windows size (see #2170 ), a transparent window is displayed. Triggering this window to go fullscreen using F11 (Windows) key results in a distorted window with a portion transparent and a portion white. See image below.

![bug](https://cloud.githubusercontent.com/assets/4436850/8625372/ea60e506-275b-11e5-959a-795b78921b46.png)
**Configuration**
* System: Windows 7 (x64)
* Electron version: 0.29.1

**Steps to reproduce**
* For issue 1, Use this app configuration with default_app: 
```js
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 400,
    'auto-hide-menu-bar': true,
    'use-content-size': true,
    transparent: true,
    fullscreen:true,
    frame: false,
  });
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.focus();
});
```
* For issue 2, use this app configuration with default_app and go fullscreen (F11 on Windows):
```js
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 400,
    'auto-hide-menu-bar': true,
    'use-content-size': true,
    transparent: true,
    fullscreen:false,
    frame: false,
  });
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.focus();
});
```
Can anybody confirm this issue on other platforms (Linux, Mac)? @delvedor, are you facing this issue on your Windows system?
What do you think? @zcbenz

**Comment by delvedor** [comment]
I have this issue only on pc (Windows 7), the same code under Mac works.
The "funny" thing is that under a Virtualized Windows 7 (via Parallels) I have not this problem.

**Comment by paulcbetts** [comment]
Do you have Aero disabled? There are many many bugs with transparent windows when it is disabled

**Comment by delvedor** [comment]
@paulcbetts as I said in #2170:

In both Windows 7 machines I have DWM enabled and running (in fact, both are using aero).

**Comment by ankitaggarwal011** [comment]
@delvedor, I think this issue and issue #2170 are related to a common bug. Since both issues are happening on native windows installation, it is possible that it could be related to windows specific chromium issue.

**Comment by ankitaggarwal011** [comment]
I found something. Turns out it's related to the behavior of chromium with Windows. Check here, https://code.google.com/p/chromium/issues/detail?id=417947.

What do you think? @delvedor, @paulcbetts, @zcbenz

**Comment by zcbenz** [comment]
I'm merging this to #1690.
