### ISSUE TITLE
File Dialogs under Windows 8.1

### ISSUE THREAD

**Issue by yishn** [atom/electron#2188]
Electron v0.29.x on Windows 8.1: If you open a "open file dialog" or a "save file dialog", then Windows 8.1 thinks the app crashed when closing the main window. Below is the crash dialog. Sorry, it's in German... :grinning: Hope you get the gist.

![electron](https://cloud.githubusercontent.com/assets/9217349/8628329/51d2edba-2752-11e5-9915-76ed4b71bacf.png)

I can reproduce this by adding the following code in the first `<script>` tag of `default_app/index.html`:

```js
window.onload = function() {
  require('remote').require('dialog').showOpenDialog();
};
```

This issue doesn't occur when using Electron v0.28.x on Windows 8.1.

**Comment by TuckerWhitehouse** [comment]
I'm seeing this as well, Electron v0.29.2 on Windows 8.1. Was able to reproduce with the dialog call in the main script, as well as an ```<input type="file">``` on the page displayed.

**Comment by hokein** [comment]
Also confirmed it on Windows 7.

**Comment by hokein** [comment]
The crash stack trace:

![image](https://cloud.githubusercontent.com/assets/2557445/8631728/53bcaa3a-27b1-11e5-98fa-c0ebec188e1f.png)
