### ISSUE TITLE
Unable to Capture Screenshot of Electron on Mac OS X El Capitan

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [atom/electron#2189]
In build 10.11 Beta (15A216g) of Mac OS X El Capitan there is a Split View feature where the user can pin one windows to one side of the screen and another to the opposite, like on Windows 8. With all pinned windows it is possible to capture them together in a screenshot. However, in my experience, the Atom editor, Visual Studio Code and several apps I've made with Electron all suffer the same problem of not being capturable when in Split View mode. 
Below is a screen shot of Atom pinned on the right. It failse to capture the windows, instead returning a black area.
<img width="1280" alt="screen shot 2015-07-10 at 3 49 18 pm" src="https://cloud.githubusercontent.com/assets/1772622/8631033/d5a5202a-2722-11e5-816f-4befcb02204a.png">

Below is a wcreen shot of Visual Studio Code pinned in a Split View, one again it returned as a black region:
<img width="1280" alt="screen shot 2015-07-10 at 4 28 37 pm" src="https://cloud.githubusercontent.com/assets/1772622/8631000/4c79af32-2722-11e5-9142-3638586cef33.png">

And here is my app pinned in a Split View and returned as a black region:
<img width="1280" alt="screen shot 2015-07-10 at 4 03 33 pm" src="https://cloud.githubusercontent.com/assets/1772622/8631008/60615914-2722-11e5-9095-59bca20cfd0b.png">

By the way, here are two normal windows pinned side by side. A screen capture returns both:

<img width="1280" alt="screen shot 2015-07-10 at 4 15 36 pm" src="https://cloud.githubusercontent.com/assets/1772622/8631042/eb2d6632-2722-11e5-9f40-7a6770759fe1.png">

**Comment by zcbenz** [comment]
Unable to reproduce on 0.36.2.
