### ISSUE TITLE
Mac App Toolbar Menu

### ISSUE THREAD

**Issue by Chibaheit** [atom/electron#2192]
In 29.2, when I drag the app folder or use terminal to run the app, the menu show success
![image](https://cloud.githubusercontent.com/assets/6986642/8634228/c8485fd2-282b-11e5-946f-4e3b60ea485e.png)
But it can't appear when I move the app folder to Resources/
![image](https://cloud.githubusercontent.com/assets/6986642/8634233/081dcff2-282c-11e5-9491-924f499b802e.png)
To check the newly Electron  causes the issue, I do the same thing in 25.1. Everything seems well.

**Comment by zcbenz** [comment]
Recent Electron removed the default menu to keep consistent behaviors between all platforms, you have to use the menu API to create a menu for your app now.
