### ISSUE TITLE
Worker not stopped when navigator restart

### ISSUE THREAD

**Issue by SrMouraSilva** [atom/electron#2194]
I created some web workers, one new in a page load (location.reload()). Can't stop then! I haven't any reference :/

They're using much CPU

![sem titulo](https://cloud.githubusercontent.com/assets/5341804/8635941/505ada70-2819-11e5-9fc2-283eec770085.png)

**Comment by zcbenz** [comment]
Can you provide a reproducible example?

**Comment by SrMouraSilva** [comment]
I tried to reproduce the error again, but without success.
I also noticed that high consumption was due to "Enable continuous repainting page" option.

I believe that the particularity, can close.

Excuse me inconvenient: /
