### ISSUE TITLE
BrowserWindow.setSize() does not respect use-content-size

### ISSUE THREAD

**Issue by Osmose** [atom/electron#2196]
I'm using electron-prebuilt 0.29.2 on OS X 10.10.3.

When I open a BrowserWindow and pass `use-content-size` as an option, the width and height passed as options works as expected and set the content size rather than the entire window. However, when I then call `setSize()` on the window, it sets the window's size _including_ the titlebar rather than setting the content's height.

Perhaps it'd be best to have a separate `setContentSize` function that sets the window's content size?

Snips of the code I'm using:

```js
mainWindow = new BrowserWindow({
    width: baseWidth,
    height: baseHeight,
    'use-content-size': true,
});

mainWindow.setSize(baseWidth, 66);  
// Content height reported by the inspector is 44px due to 22px tall title bar.
```

**Comment by yishn** [comment]
There is such a function already, see [docs](
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowsetcontentsizewidth-height).

**Comment by Osmose** [comment]
Of course it'd just be something I missed in the docs. Bah. 

Thanks!
