### ISSUE TITLE
Starting Electron with multiple apps

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/electron#2199]
I have a setup whereby Electron ships with 2 apps - each of which are subdirectories (NOT asars) within resources

One is called 'app' - the other is called 'test'

if you call 'electron' it runs 'app' (as that's the default I assume?) - I also not that if 'app' isn't available, it calls 'default_app'?

I'd assumed if you called "electron test" it would run 'test' - but it doesn't.

Note: I'm 90% sure you could run alternate asar files at some point in the past - and thus MUST be a feature people would need?

**Comment by shrewdlogarithm** [comment]
As per my other issue on auto-updating 'asar' files - it's possible a change to how Electron looks for 'apps' could offer both an 'update' solution and/or a more flexible way of handling apps?

Right now I assume it looks for - in order

app\ directory
app.asar
default_app\ directory
(not sure if it looks for default_app.asar?)

One useful idea - make it look for app_update\ or app_update.asar and rename those before running them as app\ or app.asar - that's a built-in auto-update mechanism

Another approach is allow us to specific what to look for - e.g. "electron myapp" would look for myapp\ or myapp.asar

??

**Comment by zcbenz** [comment]
They are two ways of running apps:

* One is bundling your app inside Electron and Electron will always use your app when running.
* Another is to execute a clean Electron in command line and it will run the app specified as parameter.

The second way is implemented in default_app, if you bundle your app inside Electron you will lose this ability, but you can always reimplement in your app.

**Comment by shrewdlogarithm** [comment]
The whole "inside electron" thing is far from clear in the docs - I'm
guessing you mean 'inside electron' to be

electronbasedir/
  resources/
    app/ (or app.asar)

Wheras to run it as a command-line parameter (e.g. "electron myappname")
you'd make it

electronbasedir/
  myappname/ (or myappname.asar)

That's not really explained in the docs at-all at this point??

Also - it opens-up a can of worms with the way OSX apps are bundled??
