### ISSUE TITLE
app.commandLine.replaceSwitch?

### ISSUE THREAD

**Issue by jprichardson** [atom/electron#2202]
Would it be possible (does it even make sense?) to add `app.commandLine.replaceSwitch`? Like in the context of opening new browser windows? Since they're new Chromium processes it would seem to make sense. Maybe it make more sense to add the command line switches to `BrowserWindow`? 

Sorry, I'm not familiar with the internals, I just started digging around :)

**Comment by zcbenz** [comment]
All of the command line switches are read for only one time, so changing those switches doesn't make sense under most cases. What you want might be some new APIs, I suggest opening a new issue for what you actually want.
