### ISSUE TITLE
Crash when just dragging a firefox tab on Electron

### ISSUE THREAD

**Issue by KeitIG** [atom/electron#2204]
Hello,

Yeah, I know, this sounds crazy, but I've got a very strange bug on Linux (~~still haven't tried to reproduce it on Windows~~ works fine on Windows).

I was moving a Firefox tab from a monitor to the other, and when my dragging tab encoutered my Electron app (or the dev tools), my app just crashed with that error: 

```bash 
[14141:0713/155724:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D006EBD85E180000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
The program 'electron' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 11776 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)


```

![electronfirefoxcrash](https://cloud.githubusercontent.com/assets/1311607/8651357/802bb2e6-2978-11e5-942c-920344a9df2d.png)

![electronfirefoxcrash2](https://cloud.githubusercontent.com/assets/1311607/8651378/ae4d0008-2978-11e5-9ff6-cfd6206c6ade.png)

**Comment by zcbenz** [comment]
Refs https://github.com/atom/atom/issues/3593.

**Comment by BuZZ-dEE** [comment]
I can confirm this bug on AntergOS.

**Comment by SlimeQ** [comment]
confirmed on ubuntu 14.04 xfce

**Comment by frantic1048** [comment]
I can confirm this on Arch Linux.

**OS:** Linux 4.1.6-1-ARCH
**Desktop:** KDE
**Firefox:** Developer Edition 42.0a2 (2015-09-19)
**Electron version:** v0.33.0
**Electron package:** electron-prebuilt


```
[16700:0920/214623:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[16735:0920/214624:INFO:renderer_main.cc(200)] Renderer process started
[16726:0920/214634:ERROR:sync_control_vsync_provider.cc(60)] glXGetSyncValuesOML should not return TRUE with a media stream counter of 0.
The program 'electron' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 1228 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
   ```

**Comment by zcbenz** [comment]
After spending lots of hours trying to figure out why we have X Window System error in Electron while Chromium does not, I finally find out that Chromium is facing the same error, except that it simply prints the error and then ignore it. Good job Chromium.

**Comment by forivall** [comment]
I built electron and tested it here and can confirm that it's fixed :+1: Thanks!
