### ISSUE TITLE
Why CTRL+ALT+I to toggle dev tools?

### ISSUE THREAD

**Issue by Mingling94** [atom/electron#2205]
Shouldn't it be CTRL+SHIFT+I for Windows and Linux to reflect how one actually brings up devtools in Chrome?

Copied this issue from https://github.com/sindresorhus/electron-debug/issues/2 because I realized this was built into electron and I wasn't actually using the electron-debug package

**Comment by paulcbetts** [comment]
Yes, it should, Atom did this a long time ago and everyone copied it, this drives me crazy on the daily. /cc @zcbenz @kevinsawicki

**Comment by zcbenz** [comment]
I didn't use Chrome on Windows and Linux so I thought it was the one :smile_cat:, I'm :+1: on changing it to CTRL+SHIFT+I since it is the correct one.

**Comment by Mingling94** [comment]
Wow I'm psyched this made a difference ^_^
