### ISSUE TITLE
atom v>=1.0.1 non-compliant with C++11 mode; build FAILs if gcc CXXFLAGS includes "-std=c++11";

### ISSUE THREAD

**Issue by pgnd** [atom/electron#2212]
( Relocating from atom/atom, as "... That's more of an Electron concern. There's no C++ code in Atom, that's entirely Electron (and some native npm modules). " )

Building on 

    lsb_release -rd
        Description:    openSUSE 13.2 (Harlequin) (x86_64)
        Release:        13.2

with

    gcc --version
        gcc (SUSE Linux) 5.1.1 20150707 [gcc-5-branch revision 225501]
    node -v
        v0.12.6
    npm -v
        2.11.2

on 'release 1.0.0' branch

    git log | head
        commit 38745761e2b67d613d7104808a5c8f50b0abf474
        Author: Kevin Sawicki <kevin@github.com>
        Date:   Thu Jun 25 05:05:58 2015 -0500

            :arrow_up: pathwatcher@4.4.1

        commit c82b1022dc321b053256e860787ea825e0204eaa
        Merge: 6527400 3e1c18e
        Author: Kevin Sawicki <kevin@github.com>
        Date:   Wed Jun 24 17:05:29 2015 -0500
    ...
    script/build
        Node: v0.12.6
        npm: v2.11.2
        Installing build modules...
        Installing apm...
        child_process: customFds option is deprecated, use stdio instead.
        child_process: customFds option is deprecated, use stdio instead.
        child_process: customFds option is deprecated, use stdio instead.
        ...
        Done, without errors.

switching to 'master', build fails

    git log | head
        commit a13e0020796b323e3e6c85bfeb873dfb81e0a779
        Author: Nathan Sobo <nathan@github.com>
        Date:   Tue Jul 7 20:19:22 2015 -0500

            Use atom.getCurrentWindow()

        commit 4091fa9e78bb3b712fcdecdc349aba57ad7bfaed
        Merge: a6fdf12 a4d716c
        Author: Nathan Sobo <nathan@github.com>
        Date:   Tue Jul 7 19:26:04 2015 -0500
    ...
    script/build
        Node: v0.12.6
        npm: v2.11.2
        Installing build modules...
        In file included from ../deps/breakpad/src/common/linux/dump_symbols.cc:61:0:
        ../deps/breakpad/src/common/linux/dump_symbols.cc: In function ‘std::string {anonymous}::ReadDebugLink(const char*, size_t, bool, const string&, const std::vector<std::basic_string<char> >&)’:
        ../deps/breakpad/src/common/linux/eintr_wrapper.h:40:11: error: ‘typeof’ was not declared in this scope
           typeof(x) eintr_wrapper_result; \
                   ^
        ../deps/breakpad/src/common/linux/dump_symbols.cc:457:28: note: in expansion of macro ‘HANDLE_EINTR’
               ssize_t bytes_read = HANDLE_EINTR(read(debuglink_fd, &buf, kReadSize));
                                    ^
        ../deps/breakpad/src/common/linux/eintr_wrapper.h:42:5: error: ‘eintr_wrapper_result’ was not declared in this scope
             eintr_wrapper_result = (x); \
             ^
        ../deps/breakpad/src/common/linux/dump_symbols.cc:457:28: note: in expansion of macro ‘HANDLE_EINTR’
               ssize_t bytes_read = HANDLE_EINTR(read(debuglink_fd, &buf, kReadSize));
                                    ^
        ../deps/breakpad/src/common/linux/eintr_wrapper.h:43:12: error: ‘eintr_wrapper_result’ was not declared in this scope
           } while (eintr_wrapper_result == -1 && errno == EINTR); \
                    ^
        ../deps/breakpad/src/common/linux/dump_symbols.cc:457:28: note: in expansion of macro ‘HANDLE_EINTR’
               ssize_t bytes_read = HANDLE_EINTR(read(debuglink_fd, &buf, kReadSize));
                                    ^
        make: *** [Release/obj.target/dump_syms/deps/breakpad/src/common/linux/dump_symbols.o] Error 1
        gyp ERR! build error 
        gyp ERR! stack Error: `make` failed with exit code: 2
        gyp ERR! stack     at ChildProcess.onExit (/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
        gyp ERR! System Linux 4.1.1-1.ga46abf6-desktop
        gyp ERR! command "node" "/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
        gyp ERR! cwd /usr/local/src/atom/build/node_modules/minidump
        gyp ERR! node -v v0.12.6
        gyp ERR! node-gyp -v v2.0.1
        gyp ERR! not ok 
        npm ERR! Linux 4.1.1-1.ga46abf6-desktop
        npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "--userconfig=/usr/local/src/atom/build/.npmrc" "install" "--loglevel" "error"
        npm ERR! node v0.12.6
        npm ERR! npm  v2.11.2
        npm ERR! code ELIFECYCLE

        npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
        npm ERR! This is most likely a problem with the minidump package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node-gyp rebuild
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls minidump
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     /usr/local/src/atom/build/npm-debug.log

    cat /usr/local/src/atom/build/npm-debug.log
        ...
        32347 verbose linkBins grunt-atom-shell-installer@0.29.0
        32348 verbose linkMans grunt-atom-shell-installer@0.29.0
        32349 verbose rebuildBundles grunt-atom-shell-installer@0.29.0
        32350 verbose rebuildBundles [ '.bin', 'asar', 'underscore' ]
        32351 info install grunt-atom-shell-installer@0.29.0
        32352 info postinstall grunt-atom-shell-installer@0.29.0
        32353 verbose unlock done using /root/.atom/.npm/_locks/grunt-atom-shell-install-e0148a44dd181ee8.lock for /usr/local/src/atom/build/node_modules/grunt-atom-shell-installer
        32354 info minidump@0.9.0 Failed to exec install script
        32355 verbose unlock done using /root/.atom/.npm/_locks/minidump-7e19f8db7061fb7b.lock for /usr/local/src/atom/build/node_modules/minidump
        32356 verbose stack Error: minidump@0.9.0 install: `node-gyp rebuild`
        32356 verbose stack Exit status 1
        32356 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
        32356 verbose stack     at EventEmitter.emit (events.js:110:17)
        32356 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/lib/utils/spawn.js:24:14)
        32356 verbose stack     at ChildProcess.emit (events.js:110:17)
        32356 verbose stack     at maybeClose (child_process.js:1015:16)
        32356 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
        32357 verbose pkgid minidump@0.9.0
        32358 verbose cwd /usr/local/src/atom/build
        32359 error Linux 4.1.1-1.ga46abf6-desktop
        32360 error argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "--userconfig=/usr/local/src/atom/build/.npmrc" "install" "--loglevel" "error"
        32361 error node v0.12.6
        32362 error npm  v2.11.2
        32363 error code ELIFECYCLE
        32364 error minidump@0.9.0 install: `node-gyp rebuild`
        32364 error Exit status 1
        32365 error Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
        32365 error This is most likely a problem with the minidump package,
        32365 error not with npm itself.
        32365 error Tell the author that this fails on your system:
        32365 error     node-gyp rebuild
        32365 error You can get their info via:
        32365 error     npm owner ls minidump
        32365 error There is likely additional logging output above.
        32366 verbose exit [ 1, true ]
        32367 verbose unbuild node_modules/minidump
        32368 info preuninstall minidump@0.9.0
        32369 info uninstall minidump@0.9.0
        32370 verbose unbuild rmStuff minidump@0.9.0 from /usr/local/src/atom/build/node_modules
        32371 silly gentlyRm /usr/local/src/atom/build/node_modules/.bin/minidump_stackwalk is being gently removed
        32372 silly gentlyRm verifying /usr/local/src/atom/build is an npm working directory
        32373 silly gentlyRm containing path /usr/local/src/atom/build is under npm's control, in /usr/local/src/atom/build
        32374 silly gentlyRm deletion target /usr/local/src/atom/build/node_modules/.bin/minidump_stackwalk is under /usr/local/src/atom/build
        32375 verbose gentlyRm vacuuming from /usr/local/src/atom/build/node_modules/.bin/minidump_stackwalk up to /usr/local/src/atom/build
        32376 silly vacuum-fs removing /usr/local/src/atom/build/node_modules/.bin/minidump_stackwalk
        32377 silly vacuum-fs quitting because other entries in /usr/local/src/atom/build/node_modules/.bin
        32378 info postuninstall minidump@0.9.0
        32379 silly gentlyRm /usr/local/src/atom/build/node_modules/minidump is being purged from base /usr/local/src/atom/build
        32380 verbose gentlyRm don't care about contents; nuking /usr/local/src/atom/build/node_modules/minidump
        32381 silly vacuum-fs purging /usr/local/src/atom/build/node_modules/minidump
        32382 silly vacuum-fs quitting because other entries in /usr/local/src/atom/build/node_modules

**Comment by zcbenz** [comment]
I have moved this issue to https://github.com/atom/node-minidump/issues/9, but honestly I don't think anyone would care to fix it, adding `-std=c++11` in `CXXFLAGS` is a very bad idea for all C++ projects, even for those that do compile.
