### ISSUE TITLE
"Uncaught TypeError: dialog.showMessageBox is not a function"

### ISSUE THREAD

**Issue by loveencounterflow** [atom/electron#2213]
In my electron test app (built with v0.29.2 from https://github.com/atom/electron/releases) i have an `index.js` that opens a window:
```js
var app           = require( 'app' );
var BrowserWindow = require( 'browser-window' );
app.on( 'ready', function(){
  var main_window = new BrowserWindow({
    width:    1200,
    height:    800,
  });
  var url = 'file://' + __dirname + '/index.html';
  main_window.loadUrl( url );
  } );
```
and an `index.html` to issue an alert:
```html
<script>
  alert( 'helo' );
</script>
```
which however causes the following output to appear on the command line:
```
2738:0714/162825:INFO:CONSOLE(128)] "Uncaught TypeError: dialog.showMessageBox is not a function", 
source: [...]/Electron.app/Contents/Resources/atom.asar/renderer/lib/override.js (128)
```

unsurprisingly, this same error is reported when trying to use the global `alert` function from the devtools console.

perhaps related: when an error occurs inside the `ready` handler, e.g.
```js
app.on( 'ready', function(){ xxxxxxxxxxx; });
```
that error never gets correctly reported; instead, a failed attempt to call `showErrorBox` is displayed:
```
[...]/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/init.js:45
    return require('dialog').showErrorBox('A JavaScript error occured in the browser process', message);
                             ^
TypeError: require(...).showErrorBox is not a function
    at process.<anonymous> ([...]/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/init.js:45:30)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:219:26)
```
Almost the same occurs when the error happens outside the `ready` handler, but at least you get a single-line hint about what went wrong:
```
App threw an error when running [ReferenceError: xxx is not defined]
(rest as above)
```

**Comment by hokein** [comment]
You should not use a local variable `main_window ` to host the BrowserWindow in app `ready` event callback function, otherwise the `main_window` will get GCed. You need to keep a global reference of the `BrowserWindow` object.

**Comment by loveencounterflow** [comment]
thanks for the tip; i've since [updated my code](https://github.com/loveencounterflow/test-electron/blob/master/src/app.coffee#L46) and now use a module-level object to collect references to the windows. How can i tell one of those refs would be GC'ed? After all, whatever they're referring to is still existent as long as the window is on-screen, right?

Still, GC'ed or not, that doesn't really explain why `alert()` etc fail the way they do.

**Comment by hokein** [comment]
> How can i tell one of those refs would be GC'ed? After all, whatever they're referring to is still existent as long as the window is on-screen, right?

Maybe there is a way to detect it, however I don't know either. But I don't think detecting the browser window referring or not by on-screen is a good way. Because it depends on the GC collector running frequence, even the browser window will be there without reference in code.

> Still, GC'ed or not, that doesn't really explain why alert() etc fail the way they do.

Is the issue still here? I test your code on OS X, the `alert` API works well.

**Comment by loveencounterflow** [comment]
the issue definitely is still there as of https://github.com/loveencounterflow/test-electron/commit/0bb80695439979301e4b1246db4afa2e6a05f143

**Comment by hokein** [comment]
You should not invoke `alert` in main process(In your sample, it's your `app.coffee`). The `alert` API is only available in renderer process.

**Comment by loveencounterflow** [comment]
@hokein i think the call to `alert` happens from an HTML page being rendered, so it's definitely in the renderer process.

But, regardless, that is not the point.

The point is that when something goes wrong early on in the code, all that you get to see is the stack trace of

```js
 return require('dialog').showErrorBox('A JavaScript error occured in the browser process', message);
```
going wrong; this is a fault with the Electron code which expects `require('dialog').showErrorBox` to be a function at this point in time, which it is for some reason not. Now you can tell me all the time this is not the right time to display an error box, which may be right or not, but still the fact that Electron doesn't guard its call to `require('dialog').showErrorBox` means that i never get to see the *cause* of it trying to do so in the first place.

To put it bluntly, (1) there's an error in the app, (2) Electron tries to display it but (3) fails, and therefore (4) it get to see a stacktrace that tells me where Electron failed, but, importantly, not where the *app* failed. This should never happen.

**Comment by zcbenz** [comment]
@loveencounterflow Something has hijacked the `require('dialog')` call, can you print the result of `require.resolve('dialog')` in the main process?

**Comment by loveencounterflow** [comment]
I inserted 
```coffee
console.log require.resolve('dialog')
xxx
```
into `app.coffee`. Indeed, when cloning and building in `/tmp`, this seems to work (modulo https://github.com/mafintosh/electron-prebuilt/issues/44); it outputs:

```
/private/tmp/test-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js
App threw an error when running [ReferenceError: xxx is not defined]
```
plus there is a GUI dialog showing up that shows the stacktrace. So that's great.

However, when i do the same in my scratch folder which contains lots and lots of stuff i've tried out over time, then `dialog` is not loaded from the correct location; instead, `/Volumes/Storage/io/SCRATCH/node_modules/dialog/index.js` is shown. Closer inspection reveals that this is an incidental name clash with https://github.com/tomas/dialog. Running `npm uninstall dialog` does resolve the issue.

I'd venture that this should not happen, as you can never know what `node_modules` are present somewhere up in the directory tree. My guess is that `require('dialog');` is not specific enough and really should be `require('./dialog')` or similar.

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/atom/electron/issues/387.
