### ISSUE TITLE
How to control contents of `orderFrontStandardAboutPanel`

### ISSUE THREAD

**Issue by cpsubrian** [atom/electron#2219]
What controls the content of the 'orderFrontStandardAboutPanel' menu selector? I'd let to properly set the version and ideally add a copyright.

**Comment by zcbenz** [comment]
You need to edit `Info.plist` to edit some fields.

**Comment by nuthinking** [comment]
It would be nice if this could be easily done in Electron instead of through a complex build process in electron-packager.

**Comment by mb21** [comment]
see [`app.setAboutPanelOptions(options)`](https://electronjs.org/docs/all#appsetaboutpaneloptionsoptions-macos)

**Comment by akaustav** [comment]
The link posted by @mb21 is broken now. I believe here is the updated link: [`app.setAboutPanelOptions(options)`](https://electronjs.org/docs/all#appsetaboutpaneloptionsoptions-macos-linux)

**Comment by tomprogers** [comment]
My turn to update the link: [app.setAboutPanelOptions( options )](https://www.electronjs.org/docs/api/app#appsetaboutpaneloptionsoptions)
