### ISSUE TITLE
asar fs wrapper has problem with stating trailing slash on path

### ISSUE THREAD

**Issue by Keyang** [atom/electron#2222]
e.g.
origin-fs.lstat "/opt/file/dir/"  returns directory
wrapper-fs.lstat "/opt/file/dir/" returns false

however

wrapper-fs.lstat "/opt/file/dir" return directory.

it is small but better to keep the consistency to original fs design as it probablly breaks existing node modules.

~Keyang

**Comment by zcbenz** [comment]
Any test code? Following code works well:


```js
var fs = require('fs');
var originalFs = require('original-fs');
var assert = require('assert');

assert.deepEqual(fs.lstatSync('/tmp'), originalFs.lstatSync('/tmp'));
assert.deepEqual(fs.lstatSync('/tmp/'), originalFs.lstatSync('/tmp/'));
```

**Comment by Keyang** [comment]
Sorry for the confusion.
For direct filesystem access it is ok.
I mean the relative path within asar file
e.g.
app.asar has following structure
/data
/lib/cmd
/lib/cmd/a.js

the wrapped file system:
fs.lstat("app.asar/lib/cmd/",cb); //returns false / not found
fs.lstat("app.asar/lib/cmd",cb); //returns directory

the original filesystem always return directory no matter it is with or
without the trailing slash.

~Keyang
