### ISSUE TITLE
Disabling Content Security Policy when web-security is disabled

### ISSUE THREAD

**Issue by maxogden** [atom/electron#2223]
I have a use case where I open up a `browser-window`, load a site with a Content Security Policy that has a restrictive `connect-src` setting (for example `https://github.com/atom/electron`), and then I try and create a WebSocket connection to `ws://localhost:2000` where I have a local WebSocket server running.

The problem is that even with `web-security: false` the WebSocket fails with:

```
[15235:0714/135216:INFO:CONSOLE(0)] "Refused to connect to 'ws://localhost:2000/' because it violates the following Content Security Policy directive: "connect-src 'self' live.github.com wss://live.github.com uploads.github.com status.github.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com".
", source: https://github.com/atom/electron (0)
[15235:0714/135216:INFO:CONSOLE(4823)] "Uncaught SecurityError: Failed to construct 'WebSocket': Refused to connect to 'ws://localhost:2000/' because it violates the document's Content Security Policy.", source:  (4823)
```

Would it be possible to disable Content Security Policy checks when `web-security` is `false`?

**Comment by zcbenz** [comment]
Currently there is no perfect way to do that, Chromium doesn't provide a way to surprise the Content Security Policy. One trick is to hijack web requests and remove the Content Security Policy header, but if the page writes the Content Security Policy in the `meta` tag in HTML then there is no way to prevent that.

I think currently the best solution is to use node modules for WebSocket connections.

**Comment by maxogden** [comment]
@zcbenz Ah ok that is unfortunate, as it means I have no way to reliably establish two-way communication between a window and a browser process when loading an arbitrary URL, I wrote up an issue for that on my project here https://github.com/maxogden/electron-microscope/issues/4

**Comment by zcbenz** [comment]
#2375 has added a way to disable CSP for a certain scheme, turning the whole CSP down however is still possible since Chromium hard-coded the thing and didn't provide a switch.

I'm closing this since #2375 has provided a way to solve your original problem.
