### ISSUE TITLE
Error running `build.py`

### ISSUE THREAD

**Issue by hij1nx** [atom/electron#2224]
## Electron Version
`v0.29.2`

## OS
`Darwin hij1nx-2.local 14.3.0 Darwin Kernel Version 14.3.0`

## Steps to reproduce
```bash
./script/bootstrap.py -v # appears to be successful
./script/build.py

ninja: Entering directory `out/R'
ninja: error: '../../vendor/crashpad/util/macosx/usr/include/mach/exc.defs', needed by 'obj/vendor/crashpad/util/crashp
ad_util.gen/util/mach/exc.defs', missing and no known rule to make it
```

**Comment by hokein** [comment]
Could you try to remove `<electron-source-dir>/out` and re-boostrap the project via 

```
./script/bootstrap -v -d
./script/build -d
```

**Comment by hij1nx** [comment]
@hankbao `build.py: error: unrecognized arguments: -d`

**Comment by zcbenz** [comment]
@hij1nx It is a typo, I think he meant you should remove `out` and then build from scratch.

**Comment by hij1nx** [comment]
@zcbenz i figured, i tried without `-d` as well but the result is the same :(

**Comment by zcbenz** [comment]
Do you have Xcode installed? And what's its version?

**Comment by zcbenz** [comment]
Closing until there is more information provided.
