### ISSUE TITLE
Pass a packed JS file within an asar package to a spawned node child process

### ISSUE THREAD

**Issue by floydpink** [atom/electron#2226]
When trying to spawn a `child_process` that runs `node path/to/a/packed/file` I am getting `Cannot find module` error because the path is within `app.asar`

```
Error: Cannot find module 'C:\Program Files (x86)\my-app\resources\app.asar\bootstrap\daemon'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I understand this is because the unpatched node is trying to locate the `bootstrap/daemon` as a physical file.

Can someone who is more familiar with the [`asar` documentation/code](https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md) advise a workaround to this?

**Comment by zcbenz** [comment]
You can use child_process.fork to execute the script, the official Node binary can not read files in asar package.

**Comment by floydpink** [comment]
Thank you. 

I did try using fork in place of spawn, but fork does not allow specifying custom fds for the child's stdio. And this is important in what I am trying to do with the spawn/fork.

Is there some way fork can be used along with specifying stdio as well?

[This](https://github.com/swara-app/swara-server/blob/d188b2e49140a8d86c658d8a22f8e8a14d610792/mean-app/libs/spawnhelper.js#L55) is the instance where I am facing all of this problems. Thanks for your help.

**Comment by zcbenz** [comment]
You can put the script outside the asar package.

**Comment by floydpink** [comment]
I explored the options of keeping the script outside the asar package as well as trying to use `fork` instead of `spawn`. 

Keeping it outside the package will not work as the spawning script itself uses a lot of 
other modules and keeping all of them outside of the package kind of beats the point of a package.

And though fork seemed promising and did work in launching a child process, it seems to cause issues to Electron's Browser and/or Renderer processes - and a simple `mainWindow.loadUrl('http://localhost:3000/');` was not doing anything after using a fork.

Is there a way I can use the internal/embedded node to spawn a child process, so that it will read the module within the asar package?

**Comment by floydpink** [comment]
@zcbenz - Can you please reopen the issue so that someone else might be able to help resolve it?

**Comment by floydpink** [comment]
The suggestion from https://github.com/atom/electron/issues/1613#issuecomment-100146829 to add an environment variable of `{ATOM_SHELL_INTERNAL_RUN_AS_NODE : 0}` helped to successfully resolve the issue with using `fork`
