### ISSUE TITLE
Specifying base url tag in main html breaks asset loading

### ISSUE THREAD

**Issue by levint** [atom/electron#2227]
Adding the following tag in your html breaks loading of assets located within the application package.

`<base href="/" />`

For example, when you load the css like below:

`<link rel="stylesheet" href="assets/stylesheets/app.css">`

It would result to FILE NOT FOUND error displayed in the DevTools.

**Comment by zcbenz** [comment]
This behavior is expected in `file://` protocol, since the `/` in `file://` is the root of filesystem.

**Comment by kraiz** [comment]
For anybody coming along this issue, try this:
```
<base href="./" />
```
[Source](http://stackoverflow.com/questions/37265855/how-should-i-configure-the-base-href-for-angular-2-when-using-electron)

**Comment by Owchzzz** [comment]
Thnanks Kraiz

**Comment by mehmetkose** [comment]
it will doesn't work on web like site.com/sub/category/slug-page.html
