### ISSUE TITLE
Example Update JSON format is malformed in docs

### ISSUE THREAD

**Issue by mhkeller** [atom/electron#2228]
https://github.com/atom/electron/blob/master/docs/api/auto-updater.md#update-json-format

![screen shot 2015-07-15 at 00 58 18 am](https://cloud.githubusercontent.com/assets/498744/8691117/a44f4fce-2a8c-11e5-8c55-6498d095eef4.png)

The trailing comma after `pub_date` makes this invalid json.

**Comment by hokein** [comment]
Could you send a PR to fix it?

**Comment by zcbenz** [comment]
Closed by https://github.com/atom/electron/pull/2235.
