### ISSUE TITLE
Debugging script with Visual Studio Code

### ISSUE THREAD

**Issue by LeMoussel** [atom/electron#2229]
Does Electron run on Visual Studio Code ?
If yes, how to setup a simple environment where I can write  Electron script using Visual Studio Code ?

For example I with this Test.js script;

```javascript
var app = require('app');

process.on('uncaughtException', function(error) {
    console.error("ERROR Exception => " + error.stack);
})

app.on('ready', function() {
    console.log('ready!');
    aksjdflkasjdf(); // Caught Exception
})
```
But for Visual Studio Code there is an `launch.json` configuration file. But I don't say how to setup Visual Studio Code ready for Electron work.

**Comment by paulcbetts** [comment]
There is no way to attach the VS Code debugger to Electron at the moment afaik, you should request it as a feature

**Comment by LeMoussel** [comment]
NO, there is a way to configure Visual Studio Code to run Electron and attach the debugger in the same process.
* Stackoverflow Thread : [Debugging Electron-Atom script with Visual Studio Code](http://stackoverflow.com/questions/31429394/debugging-electron-atom-script-with-visual-studio-code)
* My Life for the Code blog (great article) : [A Better Way To Launch Electron from Visual Studio Code](http://www.mylifeforthecode.com/a-better-way-to-launch-electron-from-visual-studio-code/)
