### ISSUE TITLE
wrong shortcut being generated

### ISSUE THREAD

**Issue by praveenpuglia** [atom/electron#2233]
I wanted to create a shortcut for <kbd>Ctrl</kbd> + <kbd>K</kbd> + <kbd>B</kbd> via accelerator. 

#### Expected Behaviour
In the built menu, I should see `Ctrl+K+B` for shortcut and that should work.
#### Actual Behaviour
I see `Ctrl+K`. `B` is totally ignored.

In general, only the first letter is used for the shortcut. 

However, the behaviour with `Ctrl+Shift+*` or `Ctrl+Alt+*` is as expected.

**Comment by zcbenz** [comment]
It is not supported to set two key codes in one accelerator in Electron.

**Comment by praveenpuglia** [comment]
My bad, it's probably should be two separate commands like `Ctrl+K` & `Ctrl+B`.
