### ISSUE TITLE
Content is overflowing corner masking & shadow

### ISSUE THREAD

**Issue by aaronshekey** [atom/electron#2238]
I'm running the first El Capitan public beta. While corner rendering issues pre-date El Capitan, its exacerbated on this new beta.

Window content overflows the the border radius of an otherwise rounded border and shadow.

<img width="92" alt="corner" src="https://cloud.githubusercontent.com/assets/1369864/8713145/fffba40c-2b19-11e5-8323-0b8d98df78bd.png">

**Comment by aaronshekey** [comment]
Some additional screenshots taken on a 1x display when the content isn't overflowing:

### Native window (smooth, anti-aliased)
![native](https://cloud.githubusercontent.com/assets/1369864/8752895/f70faa00-2c7c-11e5-9842-86d4315d8dc0.png)

### Electron
![aliased](https://cloud.githubusercontent.com/assets/1369864/8752896/f98b8696-2c7c-11e5-8f41-5c58b96654b2.png)

**Comment by aaronshekey** [comment]
Here's a zoomed in version of each focusing on the same corner.

### Native
![screen shot 2015-07-17 at 12 16 40 pm](https://cloud.githubusercontent.com/assets/1369864/8753000/b62ab7b8-2c7d-11e5-9b25-6d740da82e9d.png)

### Electron
![screen shot 2015-07-17 at 12 16 30 pm](https://cloud.githubusercontent.com/assets/1369864/8753004/ba8a50de-2c7d-11e5-9896-0004bca7e7d5.png)

**Comment by husile** [comment]
Is it possibly related to [Chromium issue 396264](https://code.google.com/p/chromium/issues/detail?id=396264)? The solution there is compiling Chromium with 10.9 SDK, so people have to wait until Chromium drops 10.8 support. Currently libchromiumcontent is also compiled against 10.8 SDK.

**Comment by zcbenz** [comment]
The [corners](https://github.com/atom/electron/issues/517) [problem](https://github.com/atom/electron/pull/91) of window on Mac have haunted me since the first days of electron.

**Comment by zcbenz** [comment]
@husile That issue is the answer, thanks!
