### ISSUE TITLE
Tasks not being queued in order

### ISSUE THREAD

**Issue by jameslk** [atom/electron#2239]
It appears usage of the NodeJS API for asynchronous tasks are not being added to the browser task queue in the correct order when the NodeJS API is used within the browser frame. Here's a code sample that demonstrates the problem:

`test.html` (loaded within an ElectronJS `BrowserWindow`):
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<script>

function wait(seconds) {
	var until = new Date().getTime() + (seconds * 1000);
	while(new Date().getTime() < until) {};
}

var fs = require('fs');

// ----

console.log('1');

wait(1);

setTimeout(function() {
	console.log('3');
}, 0);

wait(1);

setTimeout(function() {
	console.log('4');
}, 0);

wait(1);

fs.readFile('./test.html', {encoding: 'utf-8'}, function(error, data) {
	console.log('5');
});

wait(1);

console.log('2');

</script>
</body>
</html>
```

When executed, I expect the output to be 1, 2, 3, 4, 5. Instead, it is 1, 2, 5, 3, 4. This appears to be related to the computation being performed from the calls to `wait`. When the calls to `wait` are taken out, it prints 1, 2, 3, 4, 5 as expected.

**Comment by frankhale** [comment]
hi @jameslk, I just ran your code against 0.29.2 on Windows and I got the expected results 1,2,3,4,5

Here is a screenshot:

![issue-2239](https://cloud.githubusercontent.com/assets/190154/8716200/fd5608b8-2b5b-11e5-9be8-dca28d1fae4d.PNG)

**Comment by jameslk** [comment]
@frankhale That's odd. The issue does seem to sometimes go away when the browser frame is refreshed.

I've tried it on 0.28.3, 0.29.0, 0.29.1, and 0.29.2 on OS X Yosemite.

Here's a screenshot of the issue:
<img width="469" alt="screen shot 2015-07-15 at 11 44 43 pm" src="https://cloud.githubusercontent.com/assets/774411/8716241/d9cced0e-2b4b-11e5-8f38-496c68772d64.png">

And the output from console:
```bash
$ node_modules/.bin/electron app.js 
[43698:0715/234410:INFO:renderer_main.cc(200)] Renderer process started
[43699:0715/234410:INFO:renderer_main.cc(200)] Renderer process started
[43696:0715/234410:INFO:CONSOLE(17)] "1", source: file:///Users/james/Desktop/test-electron-async/test.html (17)
[43696:0715/234414:INFO:CONSOLE(39)] "2", source: file:///Users/james/Desktop/test-electron-async/test.html (39)
[43696:0715/234414:INFO:CONSOLE(34)] "5", source: file:///Users/james/Desktop/test-electron-async/test.html (34)
[43696:0715/234414:INFO:CONSOLE(22)] "3", source: file:///Users/james/Desktop/test-electron-async/test.html (22)
[43696:0715/234414:INFO:CONSOLE(28)] "4", source: file:///Users/james/Desktop/test-electron-async/test.html (28)
```

This is the source running the browser window:
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = null;

app.on('window-all-closed', function() {
	app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 800, height: 600});

  mainWindow.loadUrl('file://' + __dirname + '/test.html');

  mainWindow.openDevTools();

  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
```

**Comment by frankhale** [comment]
I'm not trying to shoot you down, there may in fact be a problem, just trying to provide some more context here. I reloaded it 10 times (reload via F5 in dev tools) and all the times it printed the correct results on Windows using Electron 0.29.2. I only tested 0.29.2 on Windows, I can test Mac tomorrow.

**Comment by jameslk** [comment]
Actually, I just tested on a Windows VM and can confirm that it shows 1, 2, 3, 4, 5. So perhaps its a Mac-only issue. I'll try testing on a different Mac when I get a chance.

**Comment by frankhale** [comment]
Okay cool, I'll definitely test in the morning on my Mac to confirm your results.

**Comment by zcbenz** [comment]
In Electron the task queue of Node.js and the task queue of browser are independent, so there is no guarantee that tasks of setTimeout and Node.js APIs would run in sequence. Also the web standard never guarantees the sequence of setTimeout callbacks, so I think current behavior is fine.

**Comment by jameslk** [comment]
Unfortunately, this functionality caused a particularly nasty race condition for me that was pretty difficult to debug. I don't think how it currently works is what a developer would be expecting.

As a workaround, I will have to put NodeJS asynchronous API calls in `setTimeout`s to force the correct order of operation.
