### ISSUE TITLE
Use "sendSync" to cause browser-window.hide () error

### ISSUE THREAD

**Issue by zg2013** [atom/electron#2241]
@zcbenz  
I know you are very busy,Thank you for your patience.Thanks electron team, so I spent 2 hours after the investigation before the failure to write demo. now I again optimize the demo, has let you understand the trigger phenomenon. I guess the reason is hide () method to make the resources can not be loaded. 

Re description.
by  window7X64   electron-v0.29.2-win32-x64

demo: 
https://github.com/zg2013/app

Operation step 1 :
First step: <b>Don't hover to clock icon</b>,Then Click the Min icon to minimize to the system tray.
Second step: Click the system tray,Then Hover ‘Clock’ Icon.
Result: Icons do not appear.

Operation step 2 :
First step:  <b>hover to clock icon</b>,Then Click the Min icon to minimize to the system tray.
Second step: Click the system tray,Then Hover ‘Clock’ Icon.
Result: Icons do appear.

<b>Web in the use of ipc.sendSync communication, if the use of 'send()', it will be all normal</b>.
I was writing a problem? Should not use the "sendSync"?

Demonstration GIF
Normal：

![ok](https://cloud.githubusercontent.com/assets/5134292/8739507/2a242c08-2c6f-11e5-85bf-22634119cd29.gif)

Abnormal：
![bad](https://cloud.githubusercontent.com/assets/5134292/8739521/41119f04-2c6f-11e5-8225-221227f9498c.gif)

**Comment by zcbenz** [comment]
Please provide a demo app and use a screenshot to describe the problem.

**Comment by zg2013** [comment]
@zcbenz   Thank you. I wrote a demo. This problem can lead to other errors. For example, my JS is also wrong.

**Comment by zcbenz** [comment]
Sorry but without a _minimal_ demo I don't think anyone would have time to look into your code.

**Comment by zg2013** [comment]
@zcbenz   Thank you for your patience.I've updated the description.

**Comment by zcbenz** [comment]
@zg2013 The problem is you are sending a synchronous message to the main process but the main process doesn't send a reply, so the web page is blocked on waiting for a reply.

You can either use `ipc.send` in your page, or change your event handler in main process to `e.returnValue = win.hide();`.

**Comment by zg2013** [comment]
@zcbenz    I understand,  Thank you very much!
