### ISSUE TITLE
AJAX requests and Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by ArktekniK** [atom/electron#2245]
Our server expects a certain Origin header to match Access-Control-Allow-Origin for both our hosted application and our Electron app.

So far, I have not seen a way to set the Origin on the Browser-window object. Also, manually altering the Origin header as below will generate an error 'Refused to set unsafe header "Origin"'

````javascript
$.ajax({
        type: 'POST',
        url: req_url,
        data: data_value,
        dataType: 'json',
		beforeSend: function(xhr, settings) {
          xhr.setRequestHeader('Origin', req_origin);
        }
      }
````
We have also tried setting web-security settings on the browser-window
````javascript
"web-preferences" : {
    "web-security" : false
},
````
We are willing to fork Electron if this is a feature that is not wanted in the main branch, but I have been looking through source and not seen a way to work around this yet.

Is there a solution to this as I expect many users would come up against this problem

**Comment by jprichardson** [comment]
```js
"web-preferences" : {
    "web-security" : false
}
```

Should work. As a test, try making a request using a Node.js module in the `renderer`... say using something like [`request`](https://github.com/request/request).

**Comment by zcbenz** [comment]
I'm merging this to #2223, Chromium doesn't provide a good way to disable web requests security for now, the best choice is to use Node.js modules.

**Comment by jonluca** [comment]
This is a 3 year old issue but I wanted to say I had the same issue.

What I ended up doing was actually overwriting XMLHttpRequest with a custom one that used node in the back end, and didn't conform to spec by allowing all headers to be set and all HTTP methods to be used.

That library is [here](https://github.com/jonluca/node-xhr2-unsafe)

**Comment by emoji-king** [comment]
@jonluca How did you get this to work? I tried this with your library but I am still getting an error:

```
const XMLHttpRequest = require('xhr2-unsafe');
window.XMLHttpRequest = XMLHttpRequest;
```

**Comment by jonluca** [comment]
Are you using it with another front end library that uses it behind the scenes or are you invoking a `new XMLHttpRequest()` yourself? 

Try renaming it and using the renamed one, like 

```js
const XMLHttpRequestUnsafe = require('xhr2-unsafe');
window.XMLHttpRequestUnsafe = XMLHttpRequestUnsafe;
let xhr = new XMLHttpRequestUnsafe();
```

It's probably still defaulting to the Chrome XHR rather than the unsafe one.
