### ISSUE TITLE
Expose io.js cli from electron?

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2247]
Would it be possible to have a command line flag that allows to directly use io.js through electron.exe? My motivation is that we write Mocha tests and those should run against the same io.js version that Electron ships with. Since Electron includes io.js, being able to run mocha via the included io.js would be very cool.

**Comment by zcbenz** [comment]
You can set the `ATOM_SHELL_INTERNAL_RUN_AS_NODE` environment to `1` to make Electron run as node:

```bash
env ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 electron
```

**Comment by joaomoreno** [comment]
This is pretty cool!

**Comment by bpasero** [comment]
Nice, very cool to have this!
