### ISSUE TITLE
Maintain an aspect ratio for content within a window

### ISSUE THREAD

**Issue by mbarthelemy** [atom/electron#2252]
We had a need as a video player to enforce that our video content area, minus our controls, is 16:9 at all times. We added a function to BrowserWindow [maintainContentAspectRatio(aspectRatio, extraWidth, extraHeight)] to achieve this goal. It can be called multiple times if the developers needs change. The extra width and height are specified in pixels.

We're not wedded to the name of the particular function and we're currently missing an implementation to enforce the aspect ratio for Windows. The math in the windowWillResize:toSize: method in atom/browser/native_window_mac.mm should be easily adaptable to a Windows solution.

Pull Request: https://github.com/atom/electron/pull/2250
Related Issue: https://github.com/atom/electron/issues/1336

**Comment by zcbenz** [comment]
This API sounds good to me, I'm closing this since we already have #1336 tracking it.
