### ISSUE TITLE
How do I do ipc when creating a window via remote?

### ISSUE THREAD

**Issue by justinmchase** [atom/electron#2253]
I want to create a BrowserWindow in the renderer process via remote. I want to be able to talk with that window via IPC but I can't seem to figure it out. 

## index.js (renderer process)
```
var remote = require('remote')
var BrowserWindow = remote.require('browser-window'),
	ripc = remote.require('ipc')

var otherWindow = new BrowserWindow({show:false})
otherWindow.webContents.on('did-finish-load', function () {
	console.log('window loaded.') // this is called
})
ripc.on('example', function (event, msg) {
	console.log('example: ' + msg)
})
otherWindow.loadUrl('file://' + path.join(__dirname, '..', 'index.html'))
```

## index.html
```
<html>
<body>
  <script>
    var ipc = require('ipc')
    ipc.send('example', 'started')
  </script>
</body>
</html>
```

How can I send a message from the second window back to the other window?

**Comment by justinmchase** [comment]
Actually I figured it out. It does work like this but apparently this is bad:
```
'file://' + path.join(__dirname, '..', 'index.html')
```

It was creating a bad path and the index.html was just not being loaded at all. Once I got the right path it started working as expected, thanks.

**Comment by notbucai** [comment]
I am here when show:false packaged ipc cannot communicate, have you ever encountered it
