### ISSUE TITLE
Webview - How do I submit an event for the guest who is in the webview be heard by the electron?

### ISSUE THREAD

**Issue by candidosales** [atom/electron#2255]
How do I submit an event for the guest who is in the webview be heard by the electron?

**Comment by frankhale** [comment]
You can use IPC. In my app I use socket.io to achieve this.

**Comment by zcbenz** [comment]
There is an event of webview for that.

**Comment by candidosales** [comment]
I found the solution:

Webview --> Guest: webview.send();
Webview <-- Guest: ipc.sendToHost();
Webview --> Electron: ipc.send();
Webview <-- Electron: mainWindow.webContents.send();

Thanks =)
