### ISSUE TITLE
Documentation for how to package meteor applications

### ISSUE THREAD

**Issue by AlexFrazer** [atom/electron#2260]
Would be nice to see a streamlined way to package and distribute a meteor application. There doesn't seem to be any solid frameworks anywhere.

**Comment by sircharleswatson** [comment]
@AlexFrazer Have you seen this:
https://github.com/sircharleswatson/Electrometeor

**Comment by zcbenz** [comment]
Closing since there are excellent article plus example now, @sircharleswatson you can also add it to https://github.com/sindresorhus/awesome-electron.

**Comment by batjko** [comment]
Here is a very cool example video showcasing the ease with which you might run your Meteor app on Electron:
https://www.youtube.com/watch?v=1OpsJp1_OK4
