### ISSUE TITLE
BrowserWindow.(un)maximize() side-effect: hidden windows are shown

### ISSUE THREAD

**Issue by jorisvddonk** [atom/electron#2262]
Electron version: 0.30.0
OS: Windows 7 (DWM/Aero enabled/disabled doesn't seem to matter)

The BrowserWindow's `unmaximize` and `maximize` functions appear to have a side-effect: hidden windows will suddenly be shown. For `unmaximize`, the inner window content also doesn't get rendered correctly until the window is actually made visible via `show()` (see code/animated gif below). This side-effect doesn't appear to be documented, so I'm assuming that it's a bug.

Expected behaviour: window state is changed (maximized or minimized) but the window isn't shown until `show()` is called.

[sourcecode demonstrating the issue](https://gist.github.com/jorisvddonk/d951542592a2474d2aaa)

![animated gif demonstrating the issue](https://cloud.githubusercontent.com/assets/266543/8747444/683af5f2-2c93-11e5-9d48-15811548159d.gif)

**Comment by hokein** [comment]
> The BrowserWindow's unmaximize and maximize functions appear to have a side-effect: hidden windows will suddenly be shown. 

The `maximize` and `minimize` API behavior(a hidden window will be showed after the API called) here is expected, see #834. But after test,  the behavior is not consistent on three platforms, only work on Windows.

**Comment by zcbenz** [comment]
It is an expected behavior that maximizing a window also makes the window visible, because it can show a window in a certain state instead of showing it and then maximizing it.
