### ISSUE TITLE
Detached dev tools invisible

### ISSUE THREAD

**Issue by OlsonDev** [atom/electron#2263]
When I open my app, I have the dev tools open as well. The problem is they stopped showing up. Windows has an item on the taskbar for them but clicking it focuses "nothing". If I `Alt+Tab`, they show in the list of open windows like this:

![electron-dev-tools](https://cloud.githubusercontent.com/assets/308072/8750918/c1b4cbf4-2c6f-11e5-8cd4-aa202691d195.png)

I have no idea how to reproduce this, nor how to fix it. I tried changing my code to `mainWindow.openDevTools({ detach: false });` but they still open in a separate "window".

Windows 10 build TH1 10240, Electron v0.30.0.

**Comment by frankhale** [comment]
I've actually had this problem before as well. Dev tools showing on the task bar but you can't do anything with it. I had to shift right click on the task and select move to move it back onto the screen. It also has a very small size and will need to be resized again. I'm not sure how/why it happens but it definitely does on some occasions.

**Comment by OlsonDev** [comment]
That worked. I tried the context menu key on my keyboard to get to that menu but that didn't work, evidently because the context menu only shows `(empty)` as a disabled menu item. Now I know about Shift+Right click, which seems to be more consistent anyway. Thanks!

For those that come across this in the future, you have to use the arrow keys on the keyboard to attach the window to your cursor, then you can move it.

**Comment by zcbenz** [comment]
It seems that devtools window gets very small size sometimes, you can remove your app's data under `%USERPROFILE%` to clear the saved window size.

**Comment by Ivshti** [comment]
Also had this issue on Windows 8.
