### ISSUE TITLE
Registering for the ESC key on the document appears not to work.

### ISSUE THREAD

**Issue by EisenbergEffect** [atom/electron#2264]
Given the following code:

```
document.addEventListener('keypress', e => {
  console.log('keypress', e);
});
```

The event object will be logged to the console for alpha-numerics, enter, backspace, etc. but not for the **escape** key. I've double checked my code in a browser to ensure I haven't made a mistake and the escape key triggers correctly in that context, but does not in electron. Is there something electron-specific I should be doing to handle this? It does seem like a bug though as it will cause various JS libraries to function incorrectly. A specific example of that is a modal dialog library that wants to enable dialogs to be closed by pressing the escape key.

Operating System: OSX 10.10.4
Electron Version: 0.26.0

**Comment by paulcbetts** [comment]
> A specific example of that is a modal dialog library that wants to enable dialogs to be closed by pressing the escape key.

Not a solution, but to work around this, you can use the `dialog` tag which definitely handles the escape key

**Comment by zcbenz** [comment]
Chrome browser doesn't seems to handle it, so if you think it should you can create an issue in Chromium project.

I reproduced by:

1. Open Chrome 43
2. Open Google and open devtools
3. Run `document.addEventListener('keypress', function(e) {
  console.log('keypress', e);
});` in devtools
4. Press `ESC` and there is no output

**Comment by paulcbetts** [comment]
Afaik, `keypress` only captures key events that can be turned into strings, `keyup` seems to work:

```js
document.addEventListener('keyup', function(e) { console.log('keyup capture', e); }, true /* grab event on tunnel, not on bubble */);
```

**Comment by akashnimare** [comment]
@EisenbergEffect this works perfectly -

``` javascript
document.addEventListener('keydown', event => {
	if (event.key === 'Escape' || event.keyCode === 27) {
		window.close();
	}
});
```
