### ISSUE TITLE
When i disable close window - i can't quit in darwin

### ISSUE THREAD

**Issue by DsXack** [atom/electron#2265]
in browser-window script
```javascript
window.onbeforeunload = function (e) {
    return false;
};
```
in app script
```javascript
window.on('close', function () {
    window.hide();
});

app.on('activate-with-no-open-windows', function () {
    window.show();
});
```

it's good working for me: when i close window - window hide, when i click to app in dock – window is show. But i cant quit from app by CMD+Q

**Comment by DsXack** [comment]
I solved this with add this code:
```javascript
app.on('before-quit', function () {
   window.destroy();
});
```

**Comment by hokein** [comment]
Closing it since it has been solved.

**Comment by ialexryan** [comment]
window.destroy() should be avoided if possible; [this code](https://github.com/atom/electron/issues/444#issuecomment-76492576) might be a cleaner way to do what you're trying to do.
