### ISSUE TITLE
Cookies are purged after restart

### ISSUE THREAD

**Issue by jingweno** [atom/electron#2266]
When I open a browser window and log in a website (e.g., GitHub), the cookies are purged after restart. Is there a way to have the cookies persisted?

**Comment by hokein** [comment]
Can you provide your code here? 

The following code works well on OS X:

1. Login in GitHub website, and quit application.
2. Relaunch application, and my account still keeps login.

```
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    'auto-hide-menu-bar': true,
    'use-content-size': true,
  });

  mainWindow.loadUrl('https://github.com');
  mainWindow.focus();
});
```

**Comment by justinmchase** [comment]
@jingweno restart electron, or restart the OS?

**Comment by zcbenz** [comment]
Closing until there is more information provided.

**Comment by KynoYang** [comment]
I have the similar issue.
1, launch electron, cookie is set;
2, kill electron;
3, relaunch electron, cookie is gone.

The code works fine on MacOS and Windows, but fails on Ubuntu.
