### ISSUE TITLE
Screen API display object equality

### ISSUE THREAD

**Issue by OlsonDev** [atom/electron#2267]
```javascript
var screenHelper = require('screen');
var one = screenHelper.getAllDisplays();
var two = screenHelper.getAllDisplays();
var primary = screenHelper.getPrimaryDisplay();
var foundMatch = false;
var foundPrimaryInOne = false;
var foundPrimaryInTwo = false;
for (var a of one) {
    for (var b of two) {
        if (a == b) foundMatch = true;
        if (b == primary) foundPrimaryInTwo = true;
    }
    if (a == primary) foundPrimaryInOne = true;
}
console.log(foundMatch, foundPrimaryInOne, foundPrimaryInTwo); // => false false false
```

It sure would be nice if no `display-removed` or `display-metrics-changed` events have occurred between calls to `getAllDisplays()` that the values returned had equality.

Similarly, it would be nice if the primary display was in the array returned from `getAllDisplays()`.

I can work around this; just kinda tedious.

**Comment by zcbenz** [comment]
This would be a nice thing to have, but it seems that no one is interested in this, and it is quite hard to fix anyway since you can not override how JavaScript equals objects, so I'm just closing this.

However pull request to implement this is still welcomed.
