### ISSUE TITLE
Issue with menu selectors not working

### ISSUE THREAD

**Issue by grofit** [atom/electron#2268]
I am not quite sure if this should be raised here or on electron-prebuilt, but for some reason when I am trying to use what I think are the shorthand selectors for native actions, it blows up on me like so:

![Image of Error](https://dl.dropboxusercontent.com/u/98595151/ShareX/EMBERSOFT1/Error_2015-07-18_08-29-54.png)

I have gotten the latest version of the prebuilt, as I was following the basic tutorial then expanding from there, but every menu item I touch that has one of those native selectors on blows up with same error, here is an example of part of my menu:

```
label: 'Edit',
        submenu: [
            { label: "Undo", accelerator: "Command+Z", selector: "undo:" },
            { label: "Redo", accelerator: "Shift+Command+Z", selector: "redo:" },
            { type: "separator" },
            { label: 'Cut', accelerator: 'CommandOrControl+X', selector: "cut:" },
            { label: 'Copy', accelerator: 'CommandOrControl+C', selector: "copy:" },
            { label: 'Paste', accelerator: 'CommandOrControl+V', selector: "paste:" },
        ]
```

This is all applied using: (obviously the full menu not just the bit above)

```
var menu = Menu.buildFromTemplate(template);
        Menu.setApplicationMenu(menu);
```

The menu appears fine, but every time one of those with a selector is used it just throws the error, I also have the example:

```
{
        label: 'Quit',
        accelerator: 'Command+Q',
        selector: 'terminate:'
      },
```

And that also blows up when trying to use it, and that is in the menu docs... If this is not the right place to raise this, let me know and I will go take it to the pre-built one, but I assume the pre-built is just a gulp/(other build script) around these core files.

I am using Windows 8.1 pro for developing and testing.

**Comment by hokein** [comment]
The `selector` label is only on OS X, see https://github.com/atom/electron/blob/master/docs/api/menu.md#standard-menu-item-actions

**Comment by grofit** [comment]
ah ok, is there a way to achieve this functionality for windows/other OS? i dont mind if it is click delegates that go off and do something.

**Comment by carlosperate** [comment]
https://github.com/atom/electron/blob/master/docs/api/accelerator.md

**Comment by grofit** [comment]
I know how to do keyboard shortcuts, thats not the issue. I just want to know how I can copy paste etc via native commands.

**Comment by paulcbetts** [comment]
https://github.com/atom/electron/blob/652843f44769d59b59745ef69351d3ea4bd1e4c0/docs/api/browser-window.md#webcontentsundo

**Comment by grofit** [comment]
Awesome, thanks for that, the documentation is great when you can find the right bit to look at :)

**Comment by aaronfrost** [comment]
Unfortunately the link by @paulcbetts is gone. Would love to find the answer for this.
