### ISSUE TITLE
Sending keyboard events

### ISSUE THREAD

**Issue by matthewmueller** [atom/electron#2269]
Is it possible with the browser window to send a keyboard event? Something like: http://phantomjs.org/api/webpage/method/send-event.html

**Comment by zcbenz** [comment]
You can use `webContents.send` to send a message to the page, and in the page you can setup a script to listen to that message and trigger the keyboard event. If the page is out of your control you can use `preload` option of BrowserWindow to load your script.

**Comment by matthewmueller** [comment]
Yah, I guess the only downside with this is that we're stuck simulating keyboard events on the client-side. I haven't really found a reliable way of doing this (yet).

I don't know too much about the architecture of Electron, but the phantom implementation doesn't seem too bad (https://github.com/ariya/phantomjs/blob/63e06cb/src/webpage.cpp#L1015-L1123). Would you guys be interested in supporting this feature?

**Comment by kidwm** [comment]
electron v0.33.1 has added `sendInputEvent` method for WebContents and <webview> tag.

**Comment by fritx** [comment]
cool

**Comment by matthewmueller** [comment]
you guys are killing it. thanks!

**Comment by kidwm** [comment]
@zcbenz how to send "Backspace" and ''Enter" keys with `webContents.sendInputEvent`?

**Comment by brenca** [comment]
@kidwm Special character sending was a bit broken, so I sent a PR (#2998) to fix it. You can send a `Backspace` keystroke like this:
```javascript
browserWindow.webContents.sendInputEvent({
  type: "keyDown",
  keyCode: '\u0008'
});

browserWindow.webContents.sendInputEvent({
  type: "keyUp",
  keyCode: '\u0008'
});
```

**Comment by kidwm** [comment]
@brenca Thank you for awesome contribution!

**Comment by kidwm** [comment]
@brenca I've tried to send *RETURN* in 0.33.7 but failed:
```js
webview.sendInputEvent({
	type: 'keyDown',
	keyCode: '\u0013'
});
```
BTW, sending *Backspace* is working.
Did I do something wrong?

**Comment by kidwm** [comment]
@brenca Oh, I see, it's hex, so it should be '\u000d'

**Comment by ignjat** [comment]
Can't get it to work for keys using sendInputEvent and for me insertText is not an option. What should the keyCode be for a normal key, say 'a'?

**Comment by kidwm** [comment]
@ignjat just give it string
```js
sendInputEvent({
	type: 'char',
	keyCode: 'a'
})
```

**Comment by josephrocca** [comment]
So `type:'keyDown'` and `type:keyUp` can only be used for special characters? In the tests that I've done so far it's not possible to send regular characters with `keyUp/Down` which seems a bit strange but is in line with what @kidwm says above. Why is there this distinction between regular and "special" characters? If this is actually the case, then how to we know whether to send a unicode character with `char` vs. `keyUp` and `keyDown`? Thanks!

**Comment by lavasblog** [comment]
How can I send two at the same time?

**Comment by davismiculis** [comment]
I'm seeing lots of people having problems sending Enter/Return. So this is what worked for me:
```
webview.getWebContents().sendInputEvent({ type: 'char', keyCode: '\u000d', charCode: 13 })
```
