### ISSUE TITLE
How to get system language in main process?

### ISSUE THREAD

**Issue by plrthink** [atom/electron#2274]
How to get system language in main process? I want i18n my app's menu, so I think I should do i18n work in main process, but I can't find how to detect system-wide used language. How can I do this?

**Comment by tengyifei** [comment]
https://github.com/sindresorhus/os-locale

**Comment by plrthink** [comment]
@tengyifei This module doesn't help. When I change my system language to Chinese it still says 'en_US' in my electron app. Is it because its in electron's context?

**Comment by tengyifei** [comment]
What's your operating system? Can you try it in node?

**Comment by plrthink** [comment]
@tengyifei Yeah, you're right, I would do that shortly.

**Comment by zcbenz** [comment]
Closed with #2800.
