### ISSUE TITLE
Can not start app when there are chinese charactors in the app path

### ISSUE THREAD

**Issue by hmilyyang** [atom/electron#2275]
I am using 0.30.0 version in OS Windows 7. When I start a test app in a path with chinese charactors, it shows an error dialog says "Error:cannot find module 'd:/测试/test'". If i place the app in a path with all english charactors, it runs ok.
When I test the app with version 0.26.0, it runs ok with chinese charactors in path.

**Comment by hankbao** [comment]
Just encountered this problem.

**Comment by hokein** [comment]
I believe this is a bug of iojs,  and I filed on https://github.com/nodejs/io.js/issues/2236.

**Comment by hokein** [comment]
It should be fixed in #2474 by upgrading to iojs v3.1.0.

**Comment by hmilyyang** [comment]
Yes, I have tested the problem in Electron v0.31.0, and it is fixed. Thanks!

**Comment by hankbao** [comment]
Cool.
