### ISSUE TITLE
auto-updater failing with "Error: Uncaught, unspecified "error" event."

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#2276]
I tried using the `auto-updater` module under OS X but it fails with the follow error: `"Error: Uncaught, unspecified "error" event."`. The error is thrown when calling `.setFeedUrl` method:
```
autoUpdater.setFeedUrl('http://our-website.com/updates?version=' + version);
```

Our application is still not signed. However, I saw that when the reason for the error is the lack of code signing the error is different.

What could be the reason for the error?

**Comment by zcbenz** [comment]
You need to listen to the `error` event of `autoUpdater` to get detailed error message, Node.js's EventEmitter emits `uncaughtException` when there is no `error` listener while an error happens.

**Comment by astoilkov** [comment]
Thanks a lot!

**Comment by Soubkia** [comment]
I'm getting the same unspecified error. Could you be a little more specific about how to add a listener to autoUpdater? Referencing [this](https://nodejs.org/api/events.html) I tried:

```
var autoUpdater = require('auto-updater');
autoUpdater.addListener('uncaughtException', function(err) {
  console.log(err);
});
autoUpdater.setFeedUrl('https://github.com/atom/electron/releases/tag/v0.31.2');
```

**Comment by astoilkov** [comment]
This is not a Node.js object. You need to use the `.on` method the same way you treat all Electron objects that have events.

```
var autoUpdater = require('auto-updater');
autoUpdater.on("error", function(err) {
  console.log(err);
});
autoUpdater.setFeedUrl('https://github.com/atom/electron/releases/tag/v0.31.2');
```

**Comment by Soubkia** [comment]
Thanks for the response! It appears that prints out the same result:

```
[09:21:17] { preventDefault: [Function: preventDefault],
  sender: 
   EventEmitter {
     setFeedUrl: [Function: setFeedUrl],
     checkForUpdates: [Function: checkForUpdates],
     _quitAndInstall: [Function: _quitAndInstall],
     _events: { 'update-downloaded-raw': [Function], error: [Function] },
     _eventsCount: 2,
     quitAndInstall: [Function] } }
```

I'm not really sure what to make of this.

**Comment by youyudehexie** [comment]
@Soubkia 

```
var autoUpdater = require('auto-updater');
autoUpdater.on("error", function(err, msg) {
  console.log(msg); //print msg , you can find the cash reason.
});
autoUpdater.setFeedUrl('https://github.com/atom/electron/releases/tag/v0.31.2');
```
