### ISSUE TITLE
First boot of an electron application is very slow (Ubuntu-12.04-32bit)

### ISSUE THREAD

**Issue by conteit** [atom/electron#2278]
I've noticed that the first time I launch an electron application (after switching the PC on) boot time is very slow. The second time is faster. The third time is even faster and then the boot time becomes stable.

Why it happens? Is there something that I can do for optimizing bootstrap and let it always start as fast as it can?

Electron version: 0.28.2

**Comment by zcbenz** [comment]
It is a normal thing when you run big software on a slow machine, an Electron app is basically another Chromium browser. Following starts become faster because the operating system has done some caching work.

**Comment by dagguh** [comment]
I got a fast machine. Slack/Spotify are not "big software".
