### ISSUE TITLE
JQuery not loading successfully on multiple page requests

### ISSUE THREAD

**Issue by ahazelwood** [atom/electron#2279]
I'm having an issue where jquery can be loaded correctly the first time I need it in a preload script on a webview. However the second time jquery is referenced from an external page, the line to assign it via:

```javascript
  try {
        module.exports = null;
        if (typeof require === 'function') {
          alert('window: ' + window);
          alert('jquery: ' + window.jQuery);
          alert('export: ' + module.exports);
          if ( !window.jQuery ) {
            alert('before load');
            window.jQuery = require('./node_modules/jquery/dist/jquery.js');
            alert('after load');
            window.$ = window.jQuery;
            alert('after assignment');
         }
          alert('jquery: ' + window.jQuery);
        }
    } catch(e) {
        alert('failed load.');
        console.log(e);
    }
```

throws a Cannot read property createElement of undefined in the console at the assignment to window.jQuery from require, resulting in jQuery not getting loaded.

Error message on the console is:
```javascript
Guest page logged a message: TypeError: Cannot read property 'createElement' of undefined line: 40
```

Any additional thoughts on how to successfully load jquery on subsequent pages?

Thanks.

**Comment by zcbenz** [comment]
When the preload script is loaded the DOM might not be ready yet, so when jQuery is loaded there is probably no `document` object yet. You should delay the call until window is loaded.

**Comment by ahazelwood** [comment]
Please reopen this issue as the code sample above is the only way that I've been able to get any web page external or internal that reference jquery to run in a webview.  I've included a more complete example at:  https://github.com/ahazelwood/electron  along with a image of the error messages that you see at:  https://github.com/ahazelwood/electron/blob/master/DeveloperToolsSnapshot.png 

Thanks.

**Comment by frankhale** [comment]
@ahazelwood,

I just ran your code and all you need to do in order to get jQuery to load in your webview is to require it in your preload.js.

```
window.$ = window.jQuery = require('jquery');
```

![jquery-webview](https://cloud.githubusercontent.com/assets/190154/8802021/9729aa1a-2f8c-11e5-898e-4807a74a4099.PNG)

**Comment by ahazelwood** [comment]
Frank,
The problem is that on subsequent page loads, the same issue of jquery not registering appears.  Try clicking on multiple pages and you’ll see issues regarding jquery initializing.

Thanks.

**Comment by zcbenz** [comment]
@ahazelwood You should turn off node integration.

**Comment by frankhale** [comment]
Remove "nodeintegration disablewebsecurity" from your webview and you will no longer see issues about jQuery not being defined.

**Comment by ahazelwood** [comment]
Cool.  That fixed the issue.  In reading the documentation, I misread how the preload script works with the nodeintegration tag.  Maybe some clarification to this extent would be helpful in specifying that the preload script does have access to node APIs such as require and process.

Thanks.

**Comment by dude8** [comment]
i have the same problem:
if i load page.html, there are no problems, but if i navigate to other.html the same error appears.

```javascript
//preload.js
 "use strict";
console.log('called');
if(document)
    console.log("document!!!");
console.log(document);
window.$ = window.jQuery = require('jquery');
```

```javascript
//window settings
win = new BrowserWindow({
    width: width,
    height: height,
    resizable: false,
    maximizable: false,
    useContentSize: true,
    webPreferences: {
        preload:path.resolve('./preload.js')

    }
});
```

page.hml
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="other.html">link</a>
</body>
</html>
```

other.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
```
loading page.html:
![image](https://cloud.githubusercontent.com/assets/11646216/13106347/08565b9e-d568-11e5-9ce7-0d26c52996fa.png)


loading other.html:
![image](https://cloud.githubusercontent.com/assets/11646216/13106314/d918eebe-d567-11e5-9100-ef719c62c2ff.png)
