### ISSUE TITLE
After Rebuilding electron, windows still treats an app as electron

### ISSUE THREAD

**Issue by rjusher** [atom/electron#2284]
So I was building an electron app, for consulting various news aggregation sites, I created
one app for every site, and created a shortcut for quick access, after I had been using it for
some days I decided it was time to try rebranding the binaries ( https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md#rebranding-with-downloaded-binaries) for a better UX, I was hoping
to have a different icon for each news site. It worked for some time this way, but after
a while I wanted to pin every site to my taskbar, that was easy because I was able to pin a
shortcut but when I run the application it groups all the applications as one (an electron app).

They all behave like different instances of the same application, they do show the corresponding site but the executable is identified as "electron", so I tought the solution would be rebuilding electron following this guide:
https://github.com/atom/electron/blob/master/docs/development/build-instructions-windows.md,

I modified the atom.gyp file and the icon, and sure enough the executable was named correctly and the icon was what I expected, but windows keeps grouping the applications as the same.

When I look with ResEdit the executable underneath is still called electron.

Is there a solution for what I am trying to do, (I think so, because atom editor behaves like a different app).

**Comment by frankhale** [comment]
Possibly related to https://github.com/atom/electron/issues/1954

**Comment by rjusher** [comment]
@paulcbetts gave me the answer in the slack chat room, and I am posting it here.

The way to solve it is setting the AppUserModelId in the main process. Like the following code.

``` javascript
var app = require('app');
var BrowserWindow = require('browser-window');
var dialog = require('dialog')

require('crash-reporter').start();

var mainWindow = null;

app.on(
  'window-all-closed', function() {
    if(process.platform != 'darwin'){
      app.quit();
    }
  });

app.setAppUserModelId('<name-of-your-app-goes-here>')
app.on('ready', function(){

	mainWindow = new BrowserWindow({width:800,height:600,});
	mainWindow.loadUrl('file://' + __dirname + '/mainWindow/index.html');

	mainWindow.on('closed', function(){
		mainWindow = null;
	});
});

```

**Comment by frankhale** [comment]
Thanks @rjusher for posting this here!
