### ISSUE TITLE
How to inspect elements in the webview?

### ISSUE THREAD

**Issue by candidosales** [atom/electron#2285]
I need to inspect HTML elements, network requests, but does not show anything ... Can anyone help?

**Comment by frankhale** [comment]
You need to open the dev tools for the webview.

**Comment by paulcbetts** [comment]
If you've got the main Devtools open, highlight the WebView tag, hit ESC, then type `$0.openDevTools()`

**Comment by candidosales** [comment]
```javascript
var webview = document.getElementById("foo");
webview.addEventListener("dom-ready", function(){ webview.openDevTools(); });
```

Thank you! =)

**Comment by brandonros** [comment]
@candidosales Does this go in the typical main.js or the index.html? I get openDevTools undefined in index.html and document is not defined in main.js... :/

**Comment by kachkaev** [comment]
Without jQuery, assuming you have just one `webview` (or want to open the first one out of several):

```js
document.getElementsByTagName("webview")[0].openDevTools();
```

**Comment by lishoulong** [comment]
@paulcbetts, @frankhale , as you know the devtool for webview is detached from the main window. So how should I fixed the webview devtool in the main window and replace the main devtool.

Thanks.

**Comment by swati-maheshwari** [comment]
> ```js
> var webview = document.getElementById("foo");
> webview.addEventListener("dom-ready", function(){ webview.openDevTools(); });
> ```
> 
> Thank you! =)

i get error as document is undefined..where to keep this code?

**Comment by deadcoder0904** [comment]
@swati-maheshwari You are running it in `main.js` where `document` is `undefined`. You can run it in `renderer.js` after your DOM gets loaded to actually get the selector.

Also, you can put it in `index.html` just above `body` tag like:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Electron!</title>
  </head>
  <body>
    <div id="app"></div>
    <script>
      onload = () => {
        const webview = document.querySelector('webview')

        webview.addEventListener('dom-ready', () => {
          webview.openDevTools()
        })
      }
    </script>
  </body>
</html>
```

**Comment by padmakant-baloji** [comment]
> @paulcbetts, @frankhale , as you know the devtool for webview is detached from the main window. So how should I fixed the webview devtool in the main window and replace the main devtool.
> 
> Thanks.

Did you get any solution for this

**Comment by frankhale** [comment]
> Did you get any solution for this

Sorry, I never needed this functionality so have not tried to find a solution for it.
