### ISSUE TITLE
How to create a custom prototype to window Object of the Browser?

### ISSUE THREAD

**Issue by tommyZZM** [atom/electron#2291]
i want electron can have a global function whatever load any page? 
so i can use them in console.
how can i do this.

**Comment by frankhale** [comment]
One way is to do something like this in your main.js on app ready:

mainWindow.webContents.executeJavaScript("window.hello = function() { console.log('Hello, World!'); }");

Then you have access to that function from the page that loaded in your browser window. If you use a webview you can use it's preload script.

**Comment by tommyZZM** [comment]
thx,i find it.
