### ISSUE TITLE
No close button in message box with a parent window

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2293]
This is how an alert dialog looks like in v0.29.2 on Windows:
![alertonv29 2](https://cloud.githubusercontent.com/assets/4381579/8806437/617470d2-2fdf-11e5-9dbc-551774843521.png)

And this is how it looks like in v0.30.0:
![alertonv30](https://cloud.githubusercontent.com/assets/4381579/8806446/6664d870-2fdf-11e5-952f-0ade85c327f3.png)

In version v0.30.0 we moved to using native dialogs which explains the different look.

The issues with this are:

1. The new alert dialog no longer shows a close button (X). In most Windows apps, when you see a message box or a task dialog, it will have action buttons, but also the close button which is mapped to the default action (usually "Cancel" or "OK").

2. The default caption of the dialog is the executable name (e.g. "electron.exe"). I think it makes more sense to use "productName".

3. The style of the new dialogs is somewhat outdated (not "clean and flat" enough). In Windows 8, Microsoft added a `MessageDialog` API that replaces the `MessageBox` and `TaskDialog` APIs for modern apps (see examples at: https://msdn.microsoft.com/en-us/library/windows/apps/hh738363#appropriate_use). Electron is not a modern/metro app so it can't access the new dialogs (and they are not available in Windows 7), but maybe we can simulate them. The Windows Github app which is a regular desktop app, displays dialogs that use the new style. Is it possible to get Electron to use the same?

Here's how dialogs look like in Github for Windows:
![github_dialog example](https://cloud.githubusercontent.com/assets/4381579/8808377/e3475ba0-2fea-11e5-84d3-676902e8e910.png)

**Comment by paulcbetts** [comment]
> The Windows Github app which is a regular desktop app, displays dialogs that use the new style. Is it possible to get Electron to use the same?

GitHub for Windows implements this 100% custom, there's no built-in API to do this in Windows. However, you could implement this super easily using the `<dialog>` tag.

**Comment by etiktin** [comment]
I gave Github for Windows as an example of an app that decided to simulate the dialog style used by Windows store apps. It's not native, but in my opinion, it looks better than dialogs created using the taskdialog api or the older messagebox api.

Thanks for the tip about using the dialog tag for custom dialogs.

**Comment by zcbenz** [comment]
> The new alert dialog no longer shows a close button (X). In most Windows apps, when you see a message box or a task dialog, it will have action buttons, but also the close button which is mapped to the default action (usually "Cancel" or "OK").

The TaskDialog API removes the close button when the dialog has a parent window, I don't see a flag to bring it back.

> The default caption of the dialog is the executable name (e.g. "electron.exe"). I think it makes more sense to use "productName".

I'm :+1: on this.

> The style of the new dialogs is somewhat outdated (not "clean and flat" enough).

The `dialog` module is trying to be as native as possible, so if you want a more fashion dialog you should probably implement it yourself.

**Comment by etiktin** [comment]
> The TaskDialog API removes the close button when the dialog has a parent window, I don't see a flag to bring it back.

So maybe it's influenced by the styles of the parent.

According to Microsoft's [design guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742499(v=vs.85).aspx) for dialog boxes in desktop apps, there should always be a close button on the title bar:
> - Dialog boxes always have a Close button. Modeless dialogs can also have a Minimize button. Resizable dialogs can have a Maximize button.
- Don't disable the Close button. Having a Close button helps users stay in control by allowing them to close windows they don't want.
    - Exception: For progress dialogs, you may disable the Close button if the task must run to completion to achieve a valid state or prevent data loss.

They mention it again in:
> For modeless dialogs, use an explicit Close command button in the dialog to close the window. For both, use a Close button on the title bar to close the window.

That said, I did a Google image search for TaskDialog and it seems that in practice not everyone follows the guidelines (about half of the dialogs don't have a close button on the title bar).

Thanks for the quick response :smile:

**Comment by armoret** [comment]
`The default caption of the dialog is the executable name (e.g. "electron.exe"). I think it makes more sense to use "productName".`
+1, I agree.
(I'm using webview object and it changed here too.)

**Comment by etiktin** [comment]
@zcbenz, thanks for taking care of the title issue :)

What about the other issue regarding the missing close button:
> The new alert dialog no longer shows a close button (X). In most Windows apps, when you see a message box or a task dialog, it will have action buttons, but also the close button which is mapped to the default action (usually "Cancel" or "OK").

You stated in one of your comments that:
> The TaskDialog API removes the close button when the dialog has a parent window, I don't see a flag to bring it back.

But then I gave references from Microsoft official design guidelines that states that a task dialog must have a close button (see my previous comment). If the task dialog api doesn't have a flag to bring it up, then I guess it must be some style inherited from the parent.

**Comment by zcbenz** [comment]
> What about the other issue regarding the missing close button:

I forgot about that, I will keep this issue opened to track it.

**Comment by minhhd-works** [comment]
Hi,

How can I disable this close button in a message box sync for windows?
