### ISSUE TITLE
Main window goes blank/turns white after app runs for extended period (over 24 hours)

### ISSUE THREAD

**Issue by cylinderStudio** [atom/electron#2295]
I have a JavaScript application that I use as a kiosk, so it runs for extended periods of time (days, even weeks). 

When using NWJS as a wrapper, it ran the whole time without issue, but under Electron v0.30.0, the main window goes completely blank (turns white, which happens to be my CSS background color) after about 30 to 36 hours of run time. The window appears to still be open, the application is still running. The HTML is still available in the Elements tab of developer tools, and nothing is reported in the Console tab of developer tools. Running Mac OS X 10.9.5

**Comment by cylinderStudio** [comment]
I noticed that, post crash/rendering blank-out, when I look in the Sources tab of developer tools, the contents of the files listed in file:// are empty, where as they are populated with content when the app is running/displaying normally. (I'm deploying/running the app by putting the contents in the Electron.app/Contents/Resources/app folder.)

**Comment by zcbenz** [comment]
Should have been fixed in v0.31.0, please report back if it doesn't.
