### ISSUE TITLE
showOpenDialog displays inconsistent filtering behavior on OS X

### ISSUE THREAD

**Issue by tengyifei** [atom/electron#2296]
Electron converts string extensions to UTI before passing them to `setAllowedFileTypes` on OS X：
https://github.com/atom/electron/blob/02bdace366f38271b5c186412f42810ecb06e99e/atom/browser/ui/file_dialog_mac.mm#L33

Unfortunately, UTI has a tree-like hierarchy, implying that a filter on the parent type will also match all child types:
https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html#//apple_ref/doc/uid/TP40009259-SW1

For example, '.txt' maps to `public.plain-text`, a subtype of which is `public.source-code`. Specifying `extensions: ['txt']` will in addition allow the user to select things like *.c, *.cpp, *.js etc.

The output of this snippet is: `Swift.Unmanaged<ObjectiveC.CFString>(_value: public.plain-text)`
```swift
import Foundation
import MobileCoreServices

var uti = UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, "txt", nil);
print(uti!)
```

Another example is `.sh`, which maps to `public.shell-script`. Since `public.perl-script`, `public.python-script`, `public.ruby-script`... are all subtypes of `public.shell-script`, specifying `extensions: ['sh']` will also match `.py`, `.rb`, `.pl` ... :disappointed: 

Minimum code to reproduce:
```js
require('remote').require('dialog').showOpenDialog(null, { filters: [{ name: 'Text', extensions: ['txt'] }] });
```
Behavior on Windows and Linux: users can only select `.txt` files.
Behavior on OS X: users can select `.txt` files and all source code files and more.

Any idea why use UTI as opposed to passing the list of strings directly to `setAllowedFileTypes`?

**Comment by zcbenz** [comment]
This behavior was copied from Chromium:
https://code.google.com/p/chromium/codesearch#chromium/src/ui/shell_dialogs/select_file_dialog_mac.mm&sq=package:chromium&l=212
