### ISSUE TITLE
Network communications don't work when no internet connection

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2299]
I've been using the the Node-IPC module to do communications between Electron applications: https://github.com/RIAEvangelist/node-ipc/

But we've found that when the internet connection is dropped the communications are no longer sent and gives an error `Failed to read DnsConfig` (see the issue here: https://github.com/RIAEvangelist/node-ipc/issues/32).

After more testing we have found that this ONLY happens when using it inside Electron apps and not as standalone Node applications.

Any ideas on why this is occurring?

**Comment by zcbenz** [comment]
I tried the `example/TCPSocket/basic` of node-ipc, with no network connection I got follow error in iojs v2.2.1:

```
######
error:  { [Error: getaddrinfo ENOENT localhost:8000]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'localhost',
  host: 'localhost',
  port: 8000 }
connection closed world localhost -2 of false
disconnected from world
requested connection to  world localhost
Connecting client via TCP to localhost 8000
```

And follow error in Electron:

```
[2432:0723/032837:INFO:CONSOLE(60)] "

######
error:  { [Error: getaddrinfo ENOENT localhost:8000]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'localhost',
  host: 'localhost',
  port: 8000 }", source: C:\cygwin\home\zcbenz\codes\node-ipc\node-ipc.js (60)
[2432:0723/032837:INFO:CONSOLE(60)] "connection closed world localhost -5 of false", source: C:\cygwin\home\zcbenz\codes\node-ipc\node-ipc.js (60)
[2432:0723/032837:INFO:CONSOLE(60)] "disconnected from world", source: C:\cygwin\home\zcbenz\codes\node-ipc\node-ipc.js (60)
```

It is probably a bug of iojs, but since Electron is behaving exactly the same with iojs, I think it is fine to close this issue.

**Comment by iamdriz** [comment]
But it works fine outside of Electron regardless of network connection, so it only breaks when inside Electron.
