### ISSUE TITLE
webview.openDevTools() : "Unexpected token <", source: chrome-devtools://devtools/inspector.js (6459)

### ISSUE THREAD

**Issue by candidosales** [atom/electron#2304]
Trying to open the console webview and displays this error... Anyone can help me?

**Comment by zcbenz** [comment]
Can you provide some code that can reproduce this?

**Comment by candidosales** [comment]
The main files:

app/main.js
https://gist.github.com/candidosales/0381112ea350612a3261

app/index.html
https://gist.github.com/candidosales/b19dbdea0ae574cb8c3c

**Comment by hokein** [comment]
Hi, @candidosales 

Could you minimize your code here to make it as simple as possible? Your code look a little complex at first glance, which is not friendly to understand. thanks.

**Comment by candidosales** [comment]
Minimize ?!

I can explain what I'm doing.

Basically, the webview the site sends an event (screenshot) for the index.html then forwards the event to the electron, to run a command line to perform the screenshot and send mime and the image base64 created back linked to "screenshot.final" event.

Understood?

**Comment by deepak1556** [comment]
@candidosales i believe the response returned from the url you are posting to (`http://localhost:81/registro-chamadas/autenticacao?u=043250663&d=VIKSTARSP`) isnt a valid response, did you try hitting the url in other environments ? (curl, chrome etc) . I really dont think its a bug in `Electron`.

**Comment by zcbenz** [comment]
@candidosales No one cares if your app doesn't work, and the code your pasted apparently doesn't work so we can not even confirm if the bug exists.

I'll reopen if you can provide minimal example that works and reproduces the bug.
