### ISSUE TITLE
Electron is severely crashing Windows

### ISSUE THREAD

**Issue by nbst** [atom/electron#2305]
I have an application which I am running with Electron. As I am testing and debugging things, I start my application (electron.exe) and close it every so often (sometimes maybe once or twice per minute).

After a (seemingly random and definitely not related to code change) while, the following errors appear right when starting the application:

![image](https://cloud.githubusercontent.com/assets/5188344/8845287/f40aeea0-311d-11e5-9aa4-ad4040203796.png)

At this point, the application flashes one time when open but then runs normally.

Usually not very long after, starting the application results in the errors below:

![image](https://cloud.githubusercontent.com/assets/5188344/8845294/00edf004-311e-11e5-8b58-d95f4925692b.png)

At this point, the application is frozen for a few seconds when opening and then runs apparently slower than usual. As soon as this starts to happen, it is also impossible to open a browser page (tested Chrome and IE) - page remains blank and process seems to hang:

![image](https://cloud.githubusercontent.com/assets/5188344/8845298/108a8b1c-311e-11e5-9d54-b244566ea3d4.png)

The worst is that at this point, Windows will not shut down properly. Trying to sign out or shutdown results in a blue screen with the cursor stuck with the "loading" icon forever. The only solution from there is to force the computer to shut down by holding the power button. When doing this, I had about 50% chance of having Windows stuck in an infinite repair loop, with no other choice than to do a system restore.

So now I learned that I must reboot Windows as soon as those GL_INVALID_OPERATION happen...

Would that be an issue with my computer in particular (I am not able to test on another computer for another 2 weeks) or something with Electron?

Also, on a side note, maybe related or maybe not, sometimes the application seems to start 2 Renderer processes instead of 1 - at least the logs show the "Renderer process started" twice.

Thanks

**Comment by zcbenz** [comment]
I think there is some bug in Chromium's GPU acceleration or your GPU's driver, but honestly in either case we won't be able to fix it on Electron's side. I'm not sure if you wrote that app, but if so you can disable GPU acceleration to work around this, or you can wait for Electron to update to Chrome 44.

I'm closing this as won't fix, I'm sorry to see this but we really can not help with it.
