### ISSUE TITLE
Copy text from web view to clipboard on OSX via shortcut does not work

### ISSUE THREAD

**Issue by s-a** [atom/electron#2308]
Copy text from web view does work on Windows and Linux as expected. Select some text and press ```ctrl+c```.  
A user reported at https://github.com/s-a/iron-node/issues/13 that this does not work on OS X ```Command+c```. Well the behavior on Windows and Linux is like I wish. I can not image this should differ in Electron over platforms. Is it unexpected in Electron?

I am using electron 0.30.0

**Comment by s-a** [comment]
I am using Electron 0.30.0

**Comment by zcbenz** [comment]
On OS X you have to explicitly add menu items for Copy/Paste to make them work, like this:

```js
      {
        label: 'Cut',
        accelerator: 'Cmd+X',
        selector: 'cut:'
      },
      {
        label: 'Copy',
        accelerator: 'Cmd+C',
        selector: 'copy:'
      },
      {
        label: 'Paste',
        accelerator: 'Cmd+V',
        selector: 'paste:'
      },
      {
        label: 'Select All',
        accelerator: 'Cmd+A',
        selector: 'selectAll:'
      }
```
