### ISSUE TITLE
when I create shortcut on desktop there are some  the process into the windows taskmanager

### ISSUE THREAD

**Issue by huangxok** [atom/electron#2309]
when i create a shorcut,there is a issue that the electron  will be added into the process of windows task manager.
description:
I use the command-line to execute the --createshortcut
--squirrel-install
![issue1](https://cloud.githubusercontent.com/assets/7628834/8848463/1536f9ec-316a-11e5-904e-f1b5c8a505ac.png)
--createshortcut
![issue2](https://cloud.githubusercontent.com/assets/7628834/8848648/6b643752-316b-11e5-9023-c8b2bea5e18e.png)
exectue two steps
and then the desktop will create one file which is shortcut of the electrion ，also there are three
process in the windows task manager.
![issue3](https://cloud.githubusercontent.com/assets/7628834/8848621/4603d418-316b-11e5-80be-28631542455e.png)
I couldn't see the electron on desktop that is running.

environment:
electrion version:electron-v0.29.2-win32-ia32
node:1.4.28
os:win8.1

**Comment by zcbenz** [comment]
I think `--squirrel-install` and `--createshortcut` are not parts of electron? And [Process explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) should be able to give you more information of the processes.

**Comment by paulcbetts** [comment]
This might be #2312 in action

**Comment by huangxok** [comment]
thanks ,i dont describe it clearly.
