### ISSUE TITLE
Integrate KeyboardEvent.key code from upstream blink

### ISSUE THREAD

**Issue by pandrei** [atom/electron#2310]
Currently, in Atom, there is an issue with non-US keyboard layouts  caused by Blink. The issue, [Some non-US keyboard layouts not working #37] (https://github.com/atom/atom-keymap/issues/37),  along with other similar issues have a common source. KeyboardEvent.keyidentifier is not working correctly, does not support [Alt Graph](https://en.wikipedia.org/wiki/AltGr_key) and has the wrong values in some cases. <br>
In example, on a German keyboard the <b>#</b> is read as <b> \  </b> <br>

There is a fix for this in Chrome. A part of it is already in the trunk while the other is still waiting to be reviewed. <br>

<p align = "justify"> In order to get .key working and solve this issue, you have to follow these steps:</p>

* ideally use a new/upstream Blink checkout
* apply <a href=https://codereview.chromium.org/929053004> issue 929053004 </a>  
* apply   <a href=https://codereview.chromium.org/1146173006> issue 1146173006 </a>.  ( manually, if it doesn't auto apply)

This enables the .key and .code KeyboardEvent members, fixing the layout issues.

Tested on : 
Ubuntu 14.04 ( 3.16.0-30-generic # 40~14.04.1-Ubuntu SMP )
Chromium version : Version 46.0.2455.0 (64-bit)

Screenshot:

<img src=http://i.imgur.com/SD5x2yZ.png >

Please feel free to ask for any other additional information, if needed!

@nathansobo  @zcbenz

**Comment by nathansobo** [comment]
Thanks @pandrei. @zcbenz this was the patch I mentioned to you at Summit. I'm not sure about the effort involved in back-porting it to the current version of Electron, but if it's not too painful it would be really great to fix this issue for international users sooner rather than later. Thanks!

**Comment by zcbenz** [comment]
> ideally use a new/upstream Blink checkout

The blink commit is very tightly bound to the corresponding Chromium commit, there is no way to update the blink version in an old Chromium to the one of a newer Chromium.

If we really want this feature we should back port it into Chrome 43 and submit the patches to libchromiumcontent, you can find examples at https://github.com/atom/libchromiumcontent/tree/atom/patches.

**Comment by paulcbetts** [comment]
I don't know if backporting is a solution, but KeyboardEvent.key is _the_ solution for all of our shortcut woes, it will make life much, much easier for app developers once it lands

**Comment by zcbenz** [comment]
It is in Chrome 48, let's just wait for next Chrome upgrade.

**Comment by nathansobo** [comment]
@zcbenz Am I correct in my understanding that Chrome 48 only includes support for `KeyboardEvent.code`, meaning we'll still have to manually resolve this to keys in JS?

**Comment by zcbenz** [comment]
@nathansobo The `KeyboardEvent.key` is behind a runtime feature flag, we can even enable them in Chrome 47. I'll add options for them.

**Comment by nathansobo** [comment]
@zcbenz I talked to Rick Byers a couple months back, who heads up Chrome's input team, and he said there were still some issues resolving the `.key` property on Windows. I assume that's why it's behind a flag. I could be misinformed though.

**Comment by asantos3** [comment]
Can you enable this and ship it on the beta so at least non windows systems have atom-keymap#37 fixed?

**Comment by nathansobo** [comment]
@asantos3 Thanks for the heads-up. We're still on Electron 0.36.8. Once we upgrade to 0.37.x we'll try flipping the flags. I may do some experimentation next week.
