### ISSUE TITLE
console.log doesn't print UTF8 characters correctly in terminal

### ISSUE THREAD

**Issue by tommyZZM** [atom/electron#2311]
i find this problem while create a child process .

i find data from the child process after prase in to utf8 , some character(such as "μ" "你好" "の") not correct ..

```console
electron ./
```

then i try it in chromium like this

![default](https://cloud.githubusercontent.com/assets/6326007/8849968/a88cf6e0-3176-11e5-97c9-b9680fd61289.PNG)

what cause this problem? 

how can i fix this?

**Comment by zcbenz** [comment]
Which OS and terminal simulator are you using?

**Comment by tommyZZM** [comment]
reply@zcbenz : Windows 8.1

**Comment by zcbenz** [comment]
It seems that you are not using the system's "Command Prompt" to open Electron?

**Comment by tommyZZM** [comment]
reply@zcbenz: 
the terminial in the Intellij IDEA 14, but its the same in the " system's "Command Prompt""

![default](https://cloud.githubusercontent.com/assets/6326007/8868781/b8b50038-320e-11e5-9d22-4c0626167657.PNG)

**Comment by zcbenz** [comment]
The output of renderer process is no longer printed by default anymore.
