### ISSUE TITLE
app.quit() can't terminate electron.exe in 'ready' event handler without any window created

### ISSUE THREAD

**Issue by duanyao** [atom/electron#2312]
The minimal test case:

`package.json` :
```javascript
{
  "main": "quit-test.js",
  "name": "quit-test",
  "description": "quit-test",
  "version": "0.1.0"
}
```
`quit-test.js` : 
```javascript
var app = require('app');
app.on('ready', function () {
	console.log('ev:app ready');
	app.quit();
	console.log('after app.quit()');
});

app.on('quit', function () {
	console.log('ev:app quit');
});

app.on('will-quit', function () {
	console.log('ev:app will-quit');
});
```
Console output:
```
[804:0723/203017:INFO:CONSOLE(0)] ev:app ready
[804:0723/203017:INFO:CONSOLE(0)] ev:app will-quit
[804:0723/203017:INFO:CONSOLE(0)] ev:app quit
[804:0723/203017:INFO:CONSOLE(0)] after app.quit()
```
After the "quit" event, there are still two `electron.exe` process listed in Windows task manager, and I have to kill them forcibly.

Tested with electron-v0.30.0-win32-ia32 on Windows 7 64bit.

**Comment by paulcbetts** [comment]
I'm seeing this now too, but strangely an earlier version of our app doesn't have this problem

**Comment by danilosampaio** [comment]
Related: https://github.com/yeoman/yeoman-app/issues/73

**Comment by adilanchian** [comment]
Was this fixed? I'm having the same issue on Windows 7 running Electron 0.32.2 as well as Electron 0.34.1. I've tried two different code examples: 

  ```app.on('will-quit', function()
  {
    if (process.platform != 'darwin')
      app.quit();
  });```

as well as 

```app.on('windows-all-closed', function()
{
    if (process.platform != 'darwin')
      app.quit();
  });```

I have two open processes, close the window and I'm stuck with one. Thanks for your time!

-Alec

**Comment by ryhanson** [comment]
Running into the same issue with 0.34.x. Closing from terminal does not kill the app, I have to do an `app.quit()` from my tray menu in order to kill the process.

**Comment by adilanchian** [comment]
Hey @ryhanson,

Thanks for the post. Really awesome you were able to get that working. I actually had a weird behavior the other does running my app on Windows 7. After I packaged the app using electron-packager, I tried to run it on my Windows 7 machine. Everything worked well but I was still having that one process lingering around. Funny thing is when I closed the explorer window that the app was sitting in, the process disappeared. Basically the folder with that packaged app had a process identical to the ones used when you initiate the app. It was really weird but, I think that was the issue. Thanks again for the insight. 
-Alec

**Comment by alexandrubau** [comment]
Hey @ryhanson, I had exactly the same "problem". Thank you very much for your help.

**Comment by alexandrubau** [comment]
Just a small question: is better to reuse the same window rather than creating another one, right ?

**Comment by havenchyk** [comment]
The issue still here with `0.36.7`.

Looks like this is a solution, thanks, guys!
```
app.on('window-all-closed', app.quit);`
```

**Comment by julmot** [comment]
For me, the problem still exists with a [packed app](https://github.com/electron-userland/electron-packager), even when using `app.on('window-all-closed', app.quit);`. But, it works when the app isn't packed yet.

**Comment by paulshapiro** [comment]
Same here

**Comment by julmot** [comment]
@kevinsawicki Do you know the reason?

**Comment by kevinsawicki** [comment]
> Do you know the reason?

When you are running your app using something like `electron main.js` it is running a default app wrapper that registers a `window-all-closed` listener, https://github.com/electron/electron/blob/0caa35d33ca61a263f26f86f789a29a1d7ef5aa9/default_app/main.js#L40-L44

**Comment by julmot** [comment]
@kevinsawicki  No, I'm running a packaged app, nothing manually via console etc.

**Comment by kevinsawicki** [comment]
@julmot can you include a code snippet that is not working for you?

**Comment by reza7rm** [comment]
I am quite new to Electron and I have packaged my app using electron-builder however when I quit the app, the instances are running (3 each time I run), I wrote a bat to terminate them manually but that's silly having to clicking a bat file to taskkill the instances, here is my app main.js taken fromelectron template ,modified to have a splash:

[main.zip](https://github.com/electron/electron/files/975385/main.zip)
Any suggestion on how to solve the problem?

**Comment by Dairnon** [comment]
@reza7rm I second this, I'm having the same issue with anything I do with electron on win7, its been a pretty big problem for me to have to either restart every time (or painfully manually remove them) 

Do you happen to have a copy of the bat I could use for now?

**Comment by taviroquai** [comment]
Is this issue closed?

I have the same problem, can´t quit my application.
OS: Windows 8.1
Node: v6.10.3
Electron: v1.6.10

Reproducable with the initial post steps.

Thanks

**Comment by dwoodsDev** [comment]
I'm also still experiencing this behavior with a packaged electron app built with electron-builder@19.42.0 and running electron@1.6.15. The leftover processes are present on both Windows 7 and Windows 10.

Thank you.

**Comment by mangeshi** [comment]
someone please tell me how to resolve this issue.Leftover processes are still their app close

**Comment by Hedronmx** [comment]
I'm having the same problem 😮

**Comment by mengzhou44** [comment]
I 'm having the same problem.

**Comment by mangeshi** [comment]
I resolved it.particularly in my case app.quit() method was not getting called in window-all-closed event of app.Best possible solution is that you should write app.quit on first browser window object.lets say I have a login screen and dashboard screen, then my starting window should be login screen.

Rather than writing
 app.on('window-all-closed', () => { 
  app.quit();
 }) 

You should write this code
loginWindow.on('window-all-closed', () => { 
     app.quit();
  }) 


Hope it helps.
