### ISSUE TITLE
Focusing an element on initial load does not work (only when published)

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#2317]
Focusing an element is impossible on initial load when the application have been published. I have tried textarea and input with autofocus or programmatically calling `.focus()` and nothing works. When the application is using the electron installed globally on the system it works. It does not work when packaged into an `.app`.

I have isolated the issue and it is replicable using the provided code:

index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <textarea autofocus></textarea>
  </body>
</html>
```

main.js
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

app.on('ready', function () {
  var browserWindow = new BrowserWindow({

  });

  browserWindow.loadUrl('file://' + __dirname + '/index.html');
});
```

Steps to reproduce:
  1. Create an application with the code provided above (include also a package.json pointing to the main.js file)
  2. Download latest Electron 
  3. Place the application code into the `Electron.app/Contents/Resources/app` directory
  4. Run the application and see the textarea is not focused

Running the application using `electron .` in the application folder does focus the textarea correctly.

I am using Electron version 0.30.0. The issue could be replicated under Mac Mavericks and Yosemite (tested under those two don't know about the others).

Note: If you need a demo `.app` application I could upload one and provide a link.

**Comment by etiktin** [comment]
The issue you are describing doesn't reconstruct on Windows (at least using your example).

When you run the application using `electron .`, your app is actually loaded by the default_app. The default_app creates an environment that is different from the one you get when you publish the app. For example, the default_app registers shortcuts for opening the developer tools and for reloading, which are not available when you publish (unless you add them yourself). So my advice to you is to play with the code of the default_app (specifically `resources/default_app/main.js`) and that will probably lead to some insight.

**Comment by zcbenz** [comment]
It seems that this happens when you launch your app by double-clicking it from Finder, and the whole webview doesn't have initial focus unless you click the page.

**Comment by astoilkov** [comment]
Thank you. From what I understand you have created a `webContents.focus()` and `.tabTraverse(reverse:bool)` method. If that is correct do you plan to include this into the documentation?

**Comment by zcbenz** [comment]
I don't think those methods are needed outside Electron, so I have no plan to document them. However if there are requests of similar APIs I think it is fine to make them public by adding documents.

**Comment by amnet04** [comment]
Like zcbenz says, the problem is the focus on your window app you can solve this by adding   mainWindow.focus() in your create window method. 
.... And for some reason this not work if developer tools are active, close it and check it.
