### ISSUE TITLE
Changes to file were not saved to file system after ctrl+s in DevTools

### ISSUE THREAD

**Issue by s-a** [atom/electron#2322]
![image](https://cloud.githubusercontent.com/assets/1270662/8869774/3ad92d54-31e8-11e5-99ef-3f7511340666.png)

Is it possible to make this feature available within my Electron app?

I am using Electron 0.30.0

**Comment by deepak1556** [comment]
this is the default behaviour when the code is not mapped to workspace it will be saved in memory, to save the file when not mapped you need to choose save option from the dropdown menu for the file otherwise the best way is to use workspace option of devtools.

**Comment by s-a** [comment]
I mean that this behavior describes if I debug client code within chrome dev tools, but if I load files from filessystem should it not be mapped automaticly?

**Comment by s-a** [comment]
Is there a way to setup a workspace from within my electron app via API?

**Comment by paulcbetts** [comment]
> Is there a way to setup a workspace from within my electron app via API?

This would be super cool

**Comment by s-a** [comment]
It does not save the content even if I setup a workspace. 

![image](https://cloud.githubusercontent.com/assets/1270662/8870467/b558fd38-31ee-11e5-8e2c-8a4a3737aaf6.png)

As described at #2324 these settings are not saved permanent. Regarding to this a way via API would be perfect.

**Comment by deepak1556** [comment]
> It does not save the content even if I setup a workspace.

Thats weird, just test on linux and it works fine, but settings not persisted is a different issue as noted.

> Regarding to this a way via API would be perfect.

working on it.

**Comment by s-a** [comment]
I am on Windows 7

**Comment by s-a** [comment]
Just checked 0.30.2...  :+1: API works
Unfortunately the problem still exists on Windows :cry: .

**Comment by s-a** [comment]
This works! I was confused about a JavaScript file in memory enclosed by node module scope and the original JavaScript file

**Comment by mattdesl** [comment]
@s-a Did you manage to get local modifications working for in-memory scripts (i.e. that hit `debugger` statements) and have it bubble back to the local file? 

In my case I have two tabs now: the local file (modifications are working in it) and the in-memory wrapped file (modifications are just tinted red like in your first screen shot).

**Comment by s-a** [comment]
@mattdesl no this would be realy cool feature. May be there is a way to do it if we could hook into DevTools events.

**Comment by mattdesl** [comment]
@s-a Mabye you should re-open this?

It seems like it's only half way there. Local modifications work but aren't very useful yet with required files. :smile:

**Comment by s-a** [comment]
I suggest a feature request. This is different from the original issue.

**Comment by mattdesl** [comment]
@s-a Ok, I made a new issue:
https://github.com/atom/electron/issues/4185
