### ISSUE TITLE
Custom user settings in DevTools are not save permanent?

### ISSUE THREAD

**Issue by s-a** [atom/electron#2324]
When I press ```ctrl++``` devtools will zoom content. After restarting my Electron App it shows a "small" initial state content size. Zooming settings are not saved.

Is it possible to activate this feature in my app?

**Comment by deepak1556** [comment]
could you list the user settings that are not found to persist ? Have addressed the following though,

- zoom level preference
- workspace settings ( provided an api instead of saving preference)

**Comment by s-a** [comment]
Thats it so far reported in my issue tracker. Maybe there are others but that is all I have seen.

Regarding to the workspace the API is a much better way. Otherwise I would request an API to clear workspace settings :smile:
