### ISSUE TITLE
Embed a browser-window in a graphics engine

### ISSUE THREAD

**Issue by gerhardberger** [atom/electron#2326]
hi

is it possible, if I start a C++ 3D graphics engine through native addons in my app, to render a `browser-window` in it someway, that I created in my app?

thanks

**Comment by zcbenz** [comment]
No, currently there is no way to do that.

**Comment by paulcbetts** [comment]
With CEF, you could plausibly do this, have a look at the WPF control, it ends up effectively rendering to a bitmap which is then copied onto a WPF control. Perf sucks, but it would be super similar to your scenario

**Comment by gerhardberger** [comment]
Yeah, CEF was the original solution, but accessing iojs directly from them would be great, so the best solution would be to have browser-windows embedded.

**Comment by VinciShark** [comment]
@paulcbetts May I ask for a more detailed solution or a URL reference to where I can get start? THX

**Comment by frankhale** [comment]
@VinciShark if you want to go down the road of using CEF have a look at CEFSharp. There is a very detailed sample application.

https://github.com/cefsharp/CefSharp

**Comment by gerhardberger** [comment]
@VinciShark we added [offscreen rendering](http://electron.atom.io/docs/tutorial/offscreen-rendering/), that basically solves this problem. you create a 2D texture in your 3D scene and render the bitmaps you get on the `BrowserWindow`'s `'paint'` events onto it.

**Comment by VinciShark** [comment]
@gerhardberger The problem is my old program is using QT, and use graphic engine paint on QTWindow directly. It means I need not to get the frame bitmap. Do you mean I post the HWDN of offscreen rendering  browser window to the graphic engine, and than capture the bitmap and paint to other browser window?

**Comment by gerhardberger** [comment]
@VinciShark i don't exactly understand your use case, but you don't need the HWDN of the offscreen browser window, the [`'paint'`](http://electron.atom.io/docs/api/web-contents/#event-paint) event has the `image` parameter that is a `NativeImage` which has a [`getBitmap`](http://electron.atom.io/docs/api/native-image/#imagegetbitmap) method to get the bitmap representation of the browser window as a Buffer.
