### ISSUE TITLE
Question: How to compile native modules for electron with node-gyp on Windows?

### ISSUE THREAD

**Issue by s-a** [atom/electron#2330]
Regarding to this question http://stackoverflow.com/questions/31215400/nodejs-sync-cannot-find-fibers-binaries. I try to compile fibers for Electron v0.30.0 on windows.

I read 

 - https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-node-gyp-way
 - http://electron.atom.io/docs/v0.27.0/tutorial/using-native-node-modules/

And tried 

    git clone https://github.com/atom/electron.git --> to c:\git\electron

    C:\node-test\node_modules\fibers>set HOME=c:\git\electron\
    
    C:\node-test\node_modules\fibers>node-gyp configure node-gyp rebuild --target=0.30.0 --arch=x32 --dist-url=https://atom.io/download/atom-shell
    gyp info it worked if it ends with ok
    gyp info using node-gyp@2.0.1
    gyp info using node@0.12.6 | win32 | ia32
    gyp http GET https://atom.io/download/atom-shell/v0.30.0/node-v0.30.0.tar.gz
    gyp http 200 https://atom.io/download/atom-shell/v0.30.0/node-v0.30.0.tar.gz
    gyp http GET https://atom.io/download/atom-shell/v0.30.0/SHASUMS256.txt
    gyp http GET https://atom.io/download/atom-shell/v0.30.0/node.lib
    gyp http GET https://atom.io/download/atom-shell/v0.30.0/x64/node.lib
    gyp http 200 https://atom.io/download/atom-shell/v0.30.0/SHASUMS256.txt
    gyp http 200 https://atom.io/download/atom-shell/v0.30.0/x64/node.lib
    gyp http 200 https://atom.io/download/atom-shell/v0.30.0/node.lib
    gyp info spawn c:\python27\python.exe
    gyp info spawn args [ 'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   'node-gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'msvs',
    gyp info spawn args   '-G',
    gyp info spawn args   'msvs_version=auto',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\node-test\\node_modules\\fibers\\build\\config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'c:\\git\\electron\\.node-gyp\\0.30.0\\common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=c:\\git\\electron\\.node-gyp\\0.30.0',
    gyp info spawn args   '-Dmodule_root_dir=C:\\node-test\\node_modules\\fibers',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'C:\\node-test\\node_modules\\fibers\\build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp: node-gyp not found (cwd: C:\node-test\node_modules\fibers) while trying to load node-gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Stephan\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:355:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "node" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "node-gyp" "rebuild" "--target=0.30.0" "--arch=x32" "--dist-url=https://atom.io/download/atom-shell"
    gyp ERR! cwd C:\node-test\node_modules\fibers
    gyp ERR! node -v v0.12.6
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok

Can some one point me to what i am doing wrong here?

Using 
Microsoft Windows 7 Home Premium, 6.1.7601 Service Pack 1 Build 7601, X86-based PC

**Comment by s-a** [comment]
I successfully rebuild binaries by using wurde code from github repos.

**Comment by hankbao** [comment]
Hi, @s-a. Could you please share the link of wurde? Thanks.

**Comment by s-a** [comment]
So sorry, smart device autocomplete .... Wurde=fresh. Means I simply cloned for example fibers from github and compiled the code.

**Comment by bugparty** [comment]
the command you are using is incorrect
the command node-gyp configure and node-gyp rebuild should be in two line,like this
`node-gyp configure`
 `node-gyp rebuild --target=0.36.1 --arch=x32 --dist-url=https://atom.io/download/atom-shell`
since you are building from source, the target should be set to 0.36.1
I have update the tutorial,by the time https://github.com/atom/electron/pull/4726  hasn`t been accepted

https://github.com/bugparty/electron/blob/66e706721e03b44889e3565072307be12e315b62/docs/tutorial/using-native-node-modules.md

**Comment by TimelordUK** [comment]
I will shortly add binaries for electron, but I got this to work OK.

you are right, the standard node binaries will not load.

npm install msnodesqlv8
cd msnodesqlv8
node-gyp rebuild --target=1.3.2 --dist-url=https://atom.io/download/atom-shell
cp build/Release/sqlserverv8.node lib/bin

then run your electron app.
