### ISSUE TITLE
Cut, copy, paste not working in dialogs under Mac

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#2331]
Opening a dialog (for example save dialog) without providing the `browserWindow` object opens a dialog that does not support cut, copy, paste, select all commands.

```
dialog.showSaveDialog();
```

The issue could be replicated under Mac OS Maverics and Yosemite.

Note: Opening the dialog with `browserWindow` object provided works as expected.

**Comment by erusev** [comment]
I'd also like to see this fixed.

**Comment by astoilkov** [comment]
Any progress on that? We are close to releasing our [product](http://caret.io). It would be great if we don't bring this issue with it.

**Comment by astoilkov** [comment]
Hi @zcbenz,

Is there anything special that needs to be done in order for this to start working? I updated to 0.31.2 but the issue persists.

**Comment by zcbenz** [comment]
You need to specify the `role` attribute of menu item to make it work, an example can be found in the [Menu's document].
