### ISSUE TITLE
setResizable changes size of frameless window

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2333]
When using the setResizable API it causes the height of a frameless window to change. Something like this will reproduce it on Mac. I haven't been able to test it on other platforms so this could well be an OSX only issue...

```javascript
  var BrowserWindow = require('browser-window');
  var win = new BrowserWindow({
    resizable: false,
    frame: false
  });
  
  setInterval(function(){
    win.setResizable(!win.isResizable());
  }, 500);
```

Expected behavior is that calling this API would not cause the window dimensions or position to change.

**Note:** The 'resize' event is also triggered on the browser window.

**Comment by hokein** [comment]
Minimize to `setResizable()` API bug. Each time calling `setResizable(false)` in a frameless window, the height of the window will increase, and the increased number each time seems to be the height of title bar(about 22px).

A minimal sample:
```
var BrowserWindow = require('browser-window');
  var win = new BrowserWindow({
    frame: false
 });
win.setResizable(false);
win.setResizable(false);
```
