### ISSUE TITLE
Add 'alt-clicked' event to tray

### ISSUE THREAD

**Issue by jenslind** [atom/electron#2336]
Many applications (e.g. Dropbox) and native tools (Wifi, sound) in OS X menubar have another view/menu displayed when alt-clicking the tray icon.

**Comment by nishanths** [comment]
+1, I can pick this one up.

**Comment by matiasinsaurralde** [comment]
+1

**Comment by zcbenz** [comment]
Fixed by #2354 and #2369.

**Comment by jenslind** [comment]
Thanks!
