### ISSUE TITLE
Incorrect documentation for browser window options

### ISSUE THREAD

**Issue by mn4367** [atom/electron#2342]
The documentation for browser window options lacks proper indentation. Everything below `web-preferences` should be indented one level. Currently it looks like, for example, `text-areas-are-resizable` is a property of `options` while it is a property of `web-preferences`. The Markdown seems to be OK, but the [documentation](http://electron.atom.io/docs/v0.29.0/api/browser-window/) page isn't properly indented.

**Comment by hokein** [comment]
I move this to atom/electron.atom.io#59.
