### ISSUE TITLE
Label names of special menus 'Services', 'Windows' and 'Help' are hardcoded

### ISSUE THREAD

**Issue by mn4367** [atom/electron#2348]
The special menus on OS X are only handled properly if one uses the english names, the comment in the source [describes this as a hack](https://github.com/atom/electron/blob/master/atom/browser/ui/cocoa/atom_menu_controller.mm#L174). I made [another hack](https://github.com/mn4367/electron/commit/6de2fa61e24ee82b02ddb72c935a34e52f943f5c) ;-) which instead uses the 'sublabel'-property to detect those menus. `sublabel` seems to do nothing on OS X, so it's maybe a viable solution before a real localization mechanism is available for Electron.

If you like, I'll submit a PR.

**Comment by zcbenz** [comment]
The `sublabel` is used on Windows and Linux, so using it as solution doesn't sound a good idea to me, I think we need a new property for that.

**Comment by mn4367** [comment]
The modification I made is only in [code for OSX ](https://github.com/atom/electron/blob/master/atom/browser/ui/cocoa/atom_menu_controller.mm), so other platforms aren't affected. I have also documented this in the section for building menus on OS X, which already mentions those specal menus.

**Comment by mn4367** [comment]
Of course if you are using 'Windows' and 'Help' as a label (ther is no equivalent for 'Services' on Windows, for example) the this could be a problem, but in my opionion making a multi-platform app always involves creating appropriate menus for each platform separately.

**Comment by zcbenz** [comment]
The `sublabel` shows on Windows and Linux, so if you reuse the same menu on different platforms you will see `OSX_WINDOW_MENU` appearing on Windows and Linux. I agree with you that apps should create different menus for different platforms, but on Electron's side we have to ensure things work when user reuses one menu for all platforms.

Also I think though it is OK to use hacks in implementations, we should not make the API look like a hack.
