### ISSUE TITLE
memory leak in NativeImage.createFromPath()

### ISSUE THREAD

**Issue by kenan2002** [atom/electron#2353]
Run the code below and watch the memory status of Electron main process, you'll probably see rapid increase in memory usage. I have tested it on OS X.
```
var Tray = require('tray');
var app = require('app');
var path = require('path');

app.on('ready', function() {
    var tray = new Tray(path.join(__dirname, 'grass4.png'));
    tray.setPressedImage(path.join(__dirname, 'grass5.png'));

    setInterval(function() {
        tray.setImage(path.join(__dirname, 'grass4.png'));
        tray.setPressedImage(path.join(__dirname, 'grass5.png'));
    }, 10);
});
```

**Comment by hokein** [comment]
Which version are you using? v0.30.1?

**Comment by kenan2002** [comment]
@hokein    v0.29.2 and v0.30.1 both have the problem.

**Comment by hokein** [comment]
Reduce the code to `NativeImage.createFromPath`:

```
var NativeImage = require('native-image');

app.on('ready', function() {
  for (var i = 0; i < 1000; ++i) {
     var t = NativeImage.createFromPath('<path-image>.png');
     t = null;
  }
}
```

I can confirm that the destructor of [`NativeImage`](https://github.com/atom/electron/blob/02bdace366f38271b5c186412f42810ecb06e99e/atom/common/api/atom_api_native_image.cc#L130) will be invoked for each instance when JS garbage collector running GC.  But the memory will not release even after the `NativeImage` destructor. Also appears on Windows.

**Comment by kenan2002** [comment]
Is there any workaround?

**Comment by llhupp** [comment]
I'm still seeing a memory leak around `Tray.setImage()` on v0.33.2. Both of the following cause memory to stack up over time if called on a setInterval:
`Tray.setImage(NativeImage.createFromPath(somePath));`
`Tray.setImage(somePath);`

 I have a workaround where I make each of my NativeImages in memory up front and pass them to `setImage` when I need to.

**Comment by niftylettuce** [comment]
https://github.com/atom/electron/issues/3989
