### ISSUE TITLE
can i lock the mouse to the electron window?

### ISSUE THREAD

**Issue by tommyZZM** [atom/electron#2356]
keep the mouse moving inside the window area.

**Comment by zcbenz** [comment]
Currently there is no way to do this, locking mouse also requires acquiring privilege from operating system so I don't think we will ever implement it.

**Comment by tommyZZM** [comment]
thx

**Comment by tommyZZM** [comment]
hey,@zcbenz: can i use this
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

**Comment by tommyZZM** [comment]
thanks,@zcbenz: i success use the Pointer Lock API to lock the mouse!

it requires focus to the browser window.

its cool!

![default](https://cloud.githubusercontent.com/assets/6326007/8932151/bf63f968-356d-11e5-89ee-ed4d3accee29.PNG)
