### ISSUE TITLE
Tray Icon horizontally stretched

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2360]
Starting in version v0.30.1 the icon in the OSX tray appears stretched, this is not reproducible in v0.30.0. For example, our icon here is normally a square:

![image](https://cloud.githubusercontent.com/assets/380914/8913752/ce762c42-344f-11e5-8e08-ec62d21bb4d2.png)

The original icon is here for reference:

![taskbar-opaque-development-template 2x](https://cloud.githubusercontent.com/assets/380914/8913789/10523c46-3450-11e5-925f-de9e59144dfb.png)

**Comment by dataich** [comment]
+1

**Comment by randallm** [comment]
+1

**Comment by hokein** [comment]
It's caused by introducing the StatusItemView in v0.30.1. I will take a look on this.

**Comment by zcbenz** [comment]
@hokein Current implementation forces drawing image in 26px width, while the original implementation seems to draw the image as it is.
