### ISSUE TITLE
how to pass scroll events up from webview

### ISSUE THREAD

**Issue by Kilian** [atom/electron#2364]
I have an application in which I want to show three web pages next to each other, and I want to be able to scroll horizontally through them. This works great with three iframes, but not with webviews as those seems to capture all scroll events and don't pass them on to the application above.

I can not use an iframe due to x-frame origin access (it seems that 'disable-x-frame-options' from #573 no longer exists) so I must use a webview, but is it possible to pass the scroll events up from a webview similar to how it works in iframes?

**Comment by zcbenz** [comment]
In Chromium the webview is implemented as plugins and plugins will capture all events, so I'm afraid this is something that will never be solved.

But I think with #2115 implemented you should be able to remove `x-frame-options` headers and use iframe instead, so I'm merging this to #2115.

**Comment by frankhale** [comment]
I think this can be solved in much the same way I solved talking from webview to my main app. I'm using socket.io to communicate from my app to my webview. I use the preload script in the webview to hook into what it needs and then I just fire socket.io messages back and forth from webview to app, app to webview. I don't turn on node-integration for my webview so it's isolated, just wanted to make sure that is clear. 

I don't see why you couldn't do something similar to what I am doing and create an event handler for the scroll events and then just manually propagate them to your main app using some communication mechanism such as socket.io.

**Comment by kkruups** [comment]
There is always more than one way to skin a cat! :)
It is not elegant but it works just fine.

 You can do the following:

If you need to manipulate the DOM in your webview given a Scroll Event, then just add the and Scroll Event Listener for your webview to your webview's  preload script and add the handler (callback) to this Scroll Event Listener. 

```

example: inject.js (my preload script)
__my_preload_scriptAPI = {
   data: { url: "empty string"},
   getDoc: function(){
        return document
  },
  
addScrollEvtListenerWrapper:  function(){
     var myAPIObj = __my_preload_scriptAPI;
    doc = myAPIObj.getDoc()
   doc.addEventListener("scroll",  your_callback_goesHere )
 },

otherAPIHandlers: function(){}
}

Then in your main.js code just add a call 
  //get your webview
   wv =   document.getElementById("your-webview-id")
  
   //call your preload script handler 
   wv.executeJavaScript('addScrollEvtListenerWrapper()')

   
 

```
