### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by frozeman** [atom/electron#2366]
I have a context menu and on some actions i get an error "global is not defined" pointing to electrons code in `common/api/lib.callbacks-registry.js:35`:
```js
 CallbacksRegistry.prototype.apply = function() {
      var args, id, ref;
      id = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref = this.get(id)).apply.apply(ref, [global].concat(slice.call(args)));  // <-- THIS LINE
    };
```

The code is executed in a preloader filer, which is loaded as apreload script of a electron window.
The code, which creates the error is the following. The `Helpers.getWebview()` gets a webview DOM element.

```js
var currentMousePosition = {x: 0, y: 0};
var menu = new Menu();
// menu.append(new MenuItem({ type: 'separator' }));
menu.append(new MenuItem({ label: i18n.t('mist.rightClick.reload'), accelerator: 'Command+R', click: function() {
    var webview = Helpers.getWebview(LocalStore.get('selectedTab'));
    if(webview)
        webview.reloadIgnoringCache();
}}));
menu.append(new MenuItem({ label: i18n.t('mist.rightClick.openDevTools'), click: function() {
    var webview = Helpers.getWebview(LocalStore.get('selectedTab'));
    if(webview)
        webview.openDevTools();
}}));
menu.append(new MenuItem({ label: i18n.t('mist.rightClick.inspectElements'), click: function() {
    var webview = Helpers.getWebview(LocalStore.get('selectedTab'));
    if(webview)
        webview.inspectElement(currentMousePosition.x, currentMousePosition.y);
}}));


window.addEventListener('contextmenu', function (e) {
    e.preventDefault();

    // OPEN CONTEXT MENU over webviews
    if($('webview:hover')[0]) {
        currentMousePosition.x = e.layerX;
        currentMousePosition.y = e.layerY;
        menu.popup(remote.getCurrentWindow());
    }
}, false);
```

**Comment by alexindigo** [comment]
Try to enable `node-integration`.

**Comment by frozeman** [comment]
What if i don't want to enable node integration? ;) The preloader file has node integration, but the events are clickable also later, obviously when there is not node-integration anymore.

**Comment by alexindigo** [comment]
There is no `global` object defined in a regular browser, so after preload.js is done, everything node related is being cleaned up. Btw, care to elaborate why you're using `global` instead of `window` within webview?

**Comment by paulcbetts** [comment]
> Btw, care to elaborate why you're using global instead of window within webview?

This code is in Electron itself, @frozeman is not using `global` at all.

**Comment by alexindigo** [comment]
Should it be then changed to use `window`? Since before #2183 `global` was reference to `window` object anyway?
