### ISSUE TITLE
Backspace accelerator does not work

### ISSUE THREAD

**Issue by atdrago** [atom/electron#2371]
On Mac, using 'Backspace' alone as the Accelerator does not seem to work. The menu-item's click function never executes and the menu does not highlight. Partnering Backspace with any other modifier (such as 'Command+Backspace') does work.

**Comment by hokein** [comment]
It's a expected behavior. The Accelerator should be used with a `modifiers`: https://github.com/atom/electron/blob/master/docs/api/accelerator.md. Using `Backspace` key code alone will not work.

**Comment by atdrago** [comment]
If this is true, then why do `Up`, `Down`, `Left`, and `Right` work without modifiers? I'm sure there are others (`Esc`, `VolumeUp`, `VolumeDown`, etc) that would be expected to work without modifiers. Is `Backspace` an exception to the rule? If there are specific rules for which keys work with/without modifiers, this should be noted in accelerator documentation.

**Comment by wfsm** [comment]
But I think it's common to show del as hotkey, especially in OS X, del & fn+del are shown in different symbol.
