### ISSUE TITLE
Failure to redraw the title bar properly after using the snipping tool

### ISSUE THREAD

**Issue by joaomoreno** [atom/electron#2373]
From [VSCode issue 18247](https://code.visualstudio.com/Issues/Detail/18247):

> With the application maximised I started the Snipping Tool to get a screen shot. The tool started and I grabbed the area of screen. When I clicked on VSCode to bring it back into focus I noticed that the title bar did not return to the normal colour.
> I repeated this several times to make sure.
> The right most ~15% of the title bar does go back to blue, see attached.

![image](https://cloud.githubusercontent.com/assets/22350/8953948/81a0f476-35e2-11e5-8e9c-a020e0eb547e.png)

**Comment by paulcbetts** [comment]
Electron has a bucket full of paint invalidation rendering issues with DWM disabled on Win7 :(  Good news though, you can't turn off DWM in >= Win8!

**Comment by zcbenz** [comment]
I don't think anyone would be interested in this.
