### ISSUE TITLE
ASAR docs

### ISSUE THREAD

**Issue by timruffles** [atom/electron#2374]
While asar states it 'protects source code from users', that doesn't explain how it does, or what exactly you mean. I assume it actually means 'from easily modifying the source', but doesn't provide any real protection via obfuscation etc.

**Comment by YuriSolovyov** [comment]
yes, [asar](https://github.com/atom/asar) archives have pretty simple structure and can be read just fine

**Comment by timruffles** [comment]
I'm trying to reword the docs, but can't really come up with a reason to use it. ASAR gives you $SOME_BENEFIT at $SOME_COST? I have no idea from the docs.

**Comment by YuriSolovyov** [comment]
it also helps a bit with long paths on windows as well as some performance gain of modules require

**Comment by zcbenz** [comment]
Closed with #2376.
