### ISSUE TITLE
OS X Tray for 0.30.1 - emits clicked event even when ctx menu is shown / stretches icon

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#2378]
There are two issues related to the tray icon with Electron 0.30.1

1) the tray icon is stretched instead of fitted like the previous version
2) clicked event is emitted on tray even though ctx menu is also shown - unlike the previous versions

Maybe both are expected behaviours, but they do not make any sense - at all. It's obviously easier for developers when tray icons are fitted instead of stretched, and same goes to the click event.

**Comment by tommoor** [comment]
I believe these have been tackled: https://github.com/atom/electron/issues/2360

**Comment by hokein** [comment]
> 1) the tray icon is stretched instead of fitted like the previous version

It has been fixed in #2370.

> 2) clicked event is emitted on tray even though ctx menu is also shown 

Yes.  In the v0.30.1 previous version, the clicked event will be ignored when there is context menu in tray due to the limitation of implementation. In v0.30.1, we remove this limitation.

**Comment by zcbenz** [comment]
> 2) clicked event is emitted on tray even though ctx menu is also shown - unlike the previous versions

I'm :+1: on emitting the `clicked` event even when menu is shown, generally loosing the the limitation of the API always gives developers more powers, also it matches the behavior of the `right-clicked` event on Windows, which also emits the event while the menu is shown.

**Comment by Ivshti** [comment]
@zcbenz I know it's logical on some level, but the situation is that on Windows you can depend on the "clicked" event to do stuff like show/hide window, while on OS X behaviour is different and it shows menu.

From a user perspective, nobody is going to need the "clicked" event when the menu is shown. It makes absolutely no sense for no application.

Can we at least have a ".menuShown" property in the event or something? Or control over when the tray icon ctx menu shows? E.g. the only way to show it is listen to "clicked" and call a function like ev.showCtxMenu() ?

**Comment by zcbenz** [comment]
@Ivshti I'm down to not emitting `clicked` when there is menu showing, I agree it is not quite useful, and it is breaking current apps.

**Comment by hokein** [comment]
@zcbenz So:
* On OS X, the `clicked` event will not be emitted when a menu context is showing.
* On Windows, the `right-clicked` event will not be mitted when a menu context is showing.

Is that correct?

**Comment by zcbenz** [comment]
> On OS X, the clicked event will not be emitted when a menu context is showing.
> On Windows, the right-clicked event will not be mitted when a menu context is showing.

Yes.
