### ISSUE TITLE
tskill is not recognized as internal or external command when app is packaged

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2385]
I have the following code in an Electron application to kill a process by ID:

~~~
var exec = require('child_process').exec;
exec('tskill ' + theId, function(error, stdout, stderr) { });
~~~

Whereby theId is the process id.

If I run this app using `electron myapp` the command works fine.

But if I package the application up and then call this command, then I get an error that tskill is not recognized as internal or external command....

Any ideas why this would happen? Or how to solve it.

The full error I get from the `exec error` callback is:

~~~
exec error: Error: Command failed: C:\windows\system32\cmd.exe /s /c "tskill 6164"
'tskill' is not recognized as an internal or external command,
operable program or batch file.
~~~

Thanks

**Comment by iamdriz** [comment]
Is it because when an Electron application is packaged it runs commands differently than when testing with the electron prebuilt module?

**Comment by iamdriz** [comment]
I've managed to fix it with: `'taskkill /F /T /PID ' + theId` but it's interesting that `tskill` works in one environment but not in another.

**Comment by paulcbetts** [comment]
`tskill` isn't on my computer, maybe this isn't in %PATH% anymore?
