### ISSUE TITLE
Console (terminal) log output behavior is different to Node.js

### ISSUE THREAD

**Issue by s-a** [atom/electron#2390]
1. The output of spawned processes are written as ```Buffer```.  

```javascript
cmd = 'git clone --depth=1 ' + repoUrl + ' ' + dir;
console.log(cmd);
child_process.execSync(cmd);
```

2. Colors like implemented in https://www.npmjs.com/package/colors does not have any effect.

ref: https://github.com/s-a/iron-node/issues/30

**Comment by zcbenz** [comment]
> The output of spawned processes are written as Buffer.

Please describe more about what is the expected result, I don't quite understand what you meant.

> Colors like implemented in https://www.npmjs.com/package/colors does not have any effect.

I suggest reporting this to `colors`'s repo.

**Comment by s-a** [comment]
Sorry it is not about spawn. I changed to ```child_process.execSync``` because spawning behaves somehow weird like the process hangs... However I moved to exeSync and I call this code https://github.com/s-a/electron-recompile/blob/master/lib/recompiler.js#L52 from with in my electron app and this is the difference.

Node env:  
![image](https://cloud.githubusercontent.com/assets/1270662/9034131/9b3b4208-39cd-11e5-8307-7e3a4bbebcfd.png)

Electron env:  
![image](https://cloud.githubusercontent.com/assets/1270662/9033963/55cece52-39cc-11e5-93f8-5c670b88bb18.png)

**Comment by fritx** [comment]
:+1: for this

**Comment by etiktin** [comment]
#3056 adds Buffer support to `process.std*.write` and some other goodies.

**Comment by zcbenz** [comment]
:cool:
