### ISSUE TITLE
Flash control settings do not react on pressing when windowless mode is used

### ISSUE THREAD

**Issue by glschorn** [atom/electron#2392]
I'm using electron v0.30.2 on WIndows 8.1

I created an example [repository](https://github.com/glschorn/windowless-flash-electron) demonstrating the issue.

Steps to reproduce:

1. Run application
2. Right click on flash control
4. Popup menu appears with offset
3. Select settings
4. Try to click any radio button, close button, etc.

Result:
Nothing happens

When the [page](http://www.popup-killer-review.com/windowless-swf.htm) is opened with chrome it is possible to use settings.

**Comment by zcbenz** [comment]
Recent versions have fixed the problem of passing command from flash to Electron.
