### ISSUE TITLE
How to detect when openDevTools is ready?

### ISSUE THREAD

**Issue by s-a** [atom/electron#2393]
I use ```openDevTools``` and need an event when the devtools are ready to use. Does there exist a way to determine this?

**Comment by mattdesl** [comment]
See `devtools-opened` event on BrowserWindow:
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-devtools-opened

**Comment by s-a** [comment]
I have tried this but this event does not trigger for me.
```
require('remote').getCurrentWindow().on("devtools-opened", function(){
	debugger;
});
```

Anyway I fear that this will not work if the tools are already open and I press ctrl+r to reload. So what I need is an event when the debugger is ready to work. Does there exist a way? So far I am working with an ugly timeout waiting a second until debugger has loaded :/

**Comment by zcbenz** [comment]
@s-a You might put your code in the main process and use `executeJavaScript` to execute `debugger `.
