### ISSUE TITLE
Webviews don't load contents when BrowserWindow is created but not shown 

### ISSUE THREAD

**Issue by DanTup** [atom/electron#2399]
I recently started using [Slack](https://slack.com/) and was bugged by the window opening at startup. I mentioned this on twitter and a week later it was fixed.

However, the new version still shows up in the Taskbar at startup. If I open the window and click the X in the corner, it then minimises to the tray. It would be better if it just started in the tray (and not the taskbar) to match the behaviour when closing the window.

[@paulcbetts believes this is an Electron bug](https://twitter.com/paulcbetts/status/627530701613723648), so I thought it was worth posting here. If you believe this should work, an explanation of how might mean it can be fixed in Slack. If it's not clear what the bug is, then I hope @paulcbetts might be able to provide more details on the issue.

**Comment by paulcbetts** [comment]
To repro:

1. Create a window with a WebView
1. Load the URL but don't call `show` on the window
1. Even though parent page loads, WebViews don't get activated until they are visible

**Comment by mattdesl** [comment]
I noticed this when developing [hihat](https://github.com/Jam3/hihat), my current workaround is to show a browser window with size `{ width: 0, height: 0 }`.

**Comment by zcbenz** [comment]
Can not reproduce in v0.32.1 anymore, seems that it has been fixed by Chrome 44 or Chrome 45.
