### ISSUE TITLE
Copy and Paste on remote URL's not working

### ISSUE THREAD

**Issue by gillesdemey** [atom/electron#2402]
It seems that regular shortcuts like Copy (Cmd+C), Paste (Cmd+V) and Select All (Cmd+A) aren't working when loading an external URL in a browser window. Shortcuts like Quit (Cmd+Q) are working fine however.

It's a menu bar application that loads an external login screen to authenticate the user via oAuth. 

The weird part is that it works fine when I run the application locally using `electron .`, but when I build the application using `electron-packager` the copy and paste behaviour suddenly stops working (both were using the same Electron version in my tests).

I've tried disabling all globalShortcuts my application uses, but no luck.

Using the shortcuts works when using `electron .` on 0.30.x, but not on 0.26.x.
Both versions don't work when compiling the application.

I'm using Electron 0.30.2, tried with 0.26.0 and 0.26.2 as well.
OSX 10.10, haven't tried on Windows or Linux environments.

I'd appreciate any pointers on how to resolve this, maybe it's not a bug and I'm just missing something obvious.

**Comment by magicae** [comment]
I can reproduce if i packaged my app.

**Comment by ofZach** [comment]
can confirm that I also have this issue on packaged app with v0.30.1 / OSX / yosemite. 

if I run the app from the command line it works fine, but launching from the package cmd-c cmd-v cmd-a all doesn't work.

**Comment by ofZach** [comment]
also (in case this is helpful for debugging) if I run the app via electron at the command line, ie: 

Electron.app/Contents/MacOS/Electron appPath

cmd keys work when the "app" folder is not inside the same package as the electron executable I am calling.  If the app folder is in the same path as the executable those keys (cmd-c, cmd-v cmd-a) don't work.

**Comment by ofZach** [comment]
(side note, I seems to have solved this by adding a menu to my app which adds copy and paste options.  I do think it's strange that it works in one context and not another but at least with the menu everything is working well)

**Comment by gillesdemey** [comment]
I just tested this on windows, where it works as expected after packaging the app.

**Comment by tnrich** [comment]
Might this be related to #2308 ?

**Comment by zcbenz** [comment]
On OS X all applications have to own an application menu to make copy/paste shortcuts work, for apps that ran by electron-prebuilt, Electron will assign them a default menu, but for packaged apps, there is no default menu and you have to use the [Menu.setApplicationMenu](https://github.com/atom/electron/blob/master/docs/api/menu.md) API to create one.

**Comment by finnp** [comment]
There is a nice npm module called [electron-default-menu](http://npm.im/electron-default-menu) that can be used for this.

**Comment by siwalikm** [comment]
@gillesdemey were you finally able to resolve your issue?
