### ISSUE TITLE
addDevToolsExtension does not work in Electron v0.30.2

### ISSUE THREAD

**Issue by s-a** [atom/electron#2404]
Code to reproduce:
```javascript
	var dir = path.join(__dirname, "chrome-devtools-zerodarkmatrix-theme","theme-extension" );
	var ext = require('remote').require('browser-window').addDevToolsExtension(dir);
```

In electron: "0.26.1" it looks like this :+1: 

![image](https://cloud.githubusercontent.com/assets/1270662/9027707/1432165a-3960-11e5-8b80-45c6069b337f.png)

ref:https://github.com/s-a/iron-node/issues/28

**Comment by magicae** [comment]
v0.30.0 reproduced

**Comment by s-a** [comment]
@zcbenz does there exist a way to subscribe a notification if a new electron version was released?

**Comment by deepak1556** [comment]
@s-a you need to enable `Allow Custom UI themes` option in experiments panel of devtools for this extension to work.

**Comment by zcbenz** [comment]
> @zcbenz does there exist a way to subscribe a notification if a new electron version was released?

You can use RSS feed:
http://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases

**Comment by s-a** [comment]
@deepak1556 This is already activated.

@zcbenz ty :smile:

**Comment by deepak1556** [comment]
just tested on linux and works fine.

![screenshot from 2015-08-03 16-44-17](https://cloud.githubusercontent.com/assets/964386/9036405/f325cade-39fe-11e5-9c66-980dbe07d281.png)

**Comment by s-a** [comment]
Hmm nice to know that Linux is not affected :+1: @magicae What OS are you using? I am on Windows 7 here. Would be cool to know if it works on mac.

**Comment by magicae** [comment]
@s-a I use Linux and I can't add `React DevTool` to Electron devtool.

**Comment by deepak1556** [comment]
Really not sure this is a OS specific issue, only two things that can go wrong here would be path to extension might be incorrect or the custom experiments options isnt set before loading extension. @s-a could you try remote-debugging the devtools to see if extension is loaded ?

@magicae react devtools needs loading content scripts support in Electron.

**Comment by s-a** [comment]
@deepak1556 yes i am able to debug. But not far enough into electron to know how. Can you post me debugger expression I should check?

**Comment by s-a** [comment]
The fact my code works on v"0.26.1" indicates it is a timing problem then. 
I' ve tested this without success.
```javascript
	setTimeout(function() {
		debugger;
		var dir = path.join(__dirname, "chrome-devtools-zerodarkmatrix-theme","theme-extension" );
		var ext = require('remote').require('browser-window').addDevToolsExtension(dir);
		console.info("loaded dev-tools-extension", "chrome-devtools-zerodarkmatrix-theme", ext);
	}, 3000)

```

**Comment by magicae** [comment]
> @magicae react devtools needs loading content scripts support in Electron.

@deepak1556 is it supported now? I can't find it and can't load React DevTools...

**Comment by deepak1556** [comment]
@magicae nope. tracked here https://github.com/atom/electron/issues/915

@s-a you can check for the stack trace at `InspectorFrontEndAPI.addExtensions` in devtools.js.

**Comment by s-a** [comment]
@deepak1556  Sorry it does not stop at any break point i' ve placed. 

```javascript
app.commandLine.appendSwitch('remote-debugging-port', '9222')
```

 - Started my app
 - toggle breakpoints
- restarted my app

![image](https://cloud.githubusercontent.com/assets/1270662/9037926/5d62ab38-39f0-11e5-8fd8-799413ddbfe1.png)

**Comment by s-a** [comment]
@deepak1556 
puhhh i got it worked but cannot realy see anything here. 

![image](https://cloud.githubusercontent.com/assets/1270662/9038076/b946de00-39f1-11e5-83d5-031db047660c.png)


Have you any good line in mind for a breakpoint?

**Comment by s-a** [comment]
Just tested on Ubuntu Linux . For me ```addDevToolsExtension``` does ***not*** work there too.

**Comment by s-a** [comment]
@deepak1556 To be shure we talk about the same status i created a repo to reproduce at https://github.com/s-a/e-d-t-e-t

```bash
git clone https://github.com/s-a/e-d-t-e-t.git;
cd e-d-t-e-t;
npm install;
npm run dev;
```

**Comment by deepak1556** [comment]
@s-a thanks for the test case, these are the two things i had to change to make the extension work.

* Enable `Allow Custom UI themes` options
* load the page after `devtools-opened`

```
	mainWindow.on('devtools-opened', function() {
		mainWindow.loadUrl('file://' + __dirname + '/index.html');
	})
```

**Comment by s-a** [comment]
Unfortunately extension still does not work on my workstation. Additional I tried ```Restore defaults and reload``` 
![image](https://cloud.githubusercontent.com/assets/1270662/9055750/e7b34b7e-3a8d-11e5-8102-54fb6b9adabb.png)

Restarted the app re-checked ```Allow Custom UI themes``` and re-started again.
 Without success.

I will give it a try on Ubuntu today.  There I should have exactly the same environment conditions than you.

Updated test case code at https://github.com/s-a/e-d-t-e-t/commit/81900e8df0e9fd92d0f8a0df7d1d69ffcecff2d7

**Comment by s-a** [comment]
No success on Ubuntu

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
``` 

If I pass a wrong extension folder it throws an exception. 

What is your secret @deepak1556?  :imp:

**Comment by deepak1556** [comment]
@s-a was able to reproduce the issue, could try the following in your test demo and confirm the result.

* Run the test demo and enable the `Allow Custom Ui` option.
* Remove the extension and add (try in devtools console / in app run after devtools-opened with a delay).

The problem is when we load the registered extensions on devtools open [here](https://github.com/atom/electron/blob/master/atom/browser/lib/chrome-extension.coffee#L92), the experiments option isnt recognised by the time it loads and hence dont find the theme applied, a slight delay in loading the extension after devtools opened produces the desired result. I still havnt figured how devtools applies the experiments option.

**Comment by s-a** [comment]
I commented all code from app.js so that it is empty.

Then I executed this in the console after some seconds

```javascript
var path= require("path");
var dir = path.join(__dirname, "..", "chrome-devtools-zerodarkmatrix-theme","theme-extension" );
var ext = require('remote').require('browser-window').removeDevToolsExtension(dir);
console.log(ext);
setTimeout(function(){
ext = require('remote').require('browser-window').addDevToolsExtension(dir);
console.log(ext);}, 5000);
VM114:5 true
1
VM114:8 undefined
```

```removeDevToolsExtension``` returns true, while ```addDevToolsExtension``` returns undefined. :crying_cat_face:

**Comment by deepak1556** [comment]
`removeDevToolsExtension` uses the extension name from manifest not the path to the extension. It should be `removeDevToolsExtension("DevTools Theme: Zero Dark Matrix")`

**Comment by s-a** [comment]
Success!!! :scream_cat: :smile: :+1:

**Comment by s-a** [comment]
It simply works even without a timeout.

**Comment by Gouthamve** [comment]
I am getting a ENOENT error for react devtools. Its trying to open manifest.json which doesn't exist for react dev-tools

```
'/Users/goutham/github/bookworm/react-devtools/manifest.json'
Error: ENOENT: no such file or directory, open '/Users/goutham/github/bookworm/react-devtools/manifest.json'
```

**Comment by s-a** [comment]
@deepak1556 since v0.31.0 your work around does not work anymore :cry:

**Comment by s-a** [comment]
@deepak1556 seems that this is broken again in electron 0.36.0 ?

**Comment by s-a** [comment]
no it works! sorry i missed the option in allow custom ui
