### ISSUE TITLE
[request] Multiple `preload` scripts

### ISSUE THREAD

**Issue by mattdesl** [atom/electron#2406]
I am working on some low-level modules to help make CLI apps easier to write in Electron. Currently I am using the `preload` option to patch some things (like `process.argv` and `window.onerror`) to provide a nicer user experience. However, the end-user may want to attach their own `preload` scripts on top of this for their own specific needs.  

The easiest way I can think of is to make the `preload` option to BrowserWindow accept a `(String|Array)`. This way my low-level module can run its preload script before any of the end-users scripts. 

What do you think? I might be able to help PR this feature.

**Comment by zcbenz** [comment]
The `preload` script is simply implemented by calling `require('script/path')`, if you want to allow users to setup their own preload scripts, I think the best way is to just implement it by calling `require` in your preload script.

**Comment by mattdesl** [comment]
Thanks for the reply. :smile:

Is there a clean way of sending the paths (synchronously) to the `preload` script, without polluting the end-user's `ipc`?

**Comment by zcbenz** [comment]
You can save the paths in a global variable in the main process, and use the `remote` module to read them. Another way is to save the paths to some configuration file, and use `fs` to read it.
