### ISSUE TITLE
Add the ability to know in 'will-navigate', who initiated the navigation

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2413]
I think it would be helpful if the 'will-navigate' event, will contain information regarding who initiated the navigation. Some possible initiators that come to mind are: location change, form submit and drag and drop. Another option is to simply state if it was initiated internally (e.g. form submit) or externally (drag and drop).

One possible usage for this, is when you want to completely block drag and drop, but you don't want to block internal navigation (the HTML drag and drop API can also be used to do this, but if you don't control some of the resources, it's a problem).

Possible example usage:
```javascript
mainWindow.webContents.on('will-navigate', function (event, url) {
	if (event.isExternal) { // or: if (event.initiator = 'drag-and-drop')
		console.log('Preventing navigation to:', url);
		event.preventDefault();
	}
});
```

**Comment by zcbenz** [comment]
I'm closing this as won't fix, both Chromium and blink do not expose this information, if we want to implement this we have to do a very big refactor of blink, which is just too much work.
