### ISSUE TITLE
Content Tracing doesn't work as-documented

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#2416]
I'm trying to get content tracing working, but I keep getting TypeErrors - it appears that both parameters are expected to be strings via the Mate converters but the docs say `options` is a bitflag. Any ideas?

**Comment by deepak1556** [comment]
yup `TraceOptions` needs to be a comma-separated value from the list `record-until-full, record-continuously, enable-sampling, enable-systrace`. Need to update docs with the usage of those options as specified [here](https://chromium.googlesource.com/chromium/src/+/15f86fe47c852a07534d5293f1088445d76bee3e/base/trace_event/trace_options.h)

**Comment by paulcbetts** [comment]
Hm, closer now but it still doesn't work, now `stopTracing` doesn't actually call the callback or write out a file - here's what I've got:

```js
let tracing = null;
let tracingSession = new rx.SerialDisposable();

ipc.listen('tracing:start').subscribe(() => {
  logger.info('About to start recording!');
  tracing = tracing || require('content-tracing');
  
  tracing.startRecording('*', 'record-until-full,enable-sampling', () => {
    logger.info('Started recording!');   // Hits here!
    
    tracingSession.setDisposable(rx.Disposable.create(() => {
      logger.info('About to stop recording!');   // Hits here!
      tracing.stopRecording(null /* tried explicit path, empty str */, (path) => {
        // XXX: We never get here
        logger.info(`Content logging written to ${path}`); 
      });
    }));
  });
});
```
