### ISSUE TITLE
Disabling logs doesn't work when using "appendSwitch"

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2417]
If I run my electron app on the command line like this:
```cmd
electron.exe --v=-1
```
All logs are disabled.

However if I do it using `app.commandLine.appendSwitch('v', '-1');` before the app `ready` event (like the example at the bottom of the [documentation](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md) suggests), it doesn't work and I still get `console.log` and `console.warn` prints from the renderer (I also tried it with -1 instead of '-1' but it didn't change anything). 

Is any one else experiencing this? Is this only an issue with Windows?

I'm using Windows 8.1 64 bit and Electron v0.30.2

**Comment by mattdesl** [comment]
Yeah same. Here is my solution for the time being:
https://github.com/mattdesl/strip-chromium-logs

**Comment by cnjon** [comment]
"--disable-gpu" doesn't work too.

**Comment by etiktin** [comment]
@mattdesl thanks for the tip.
On what OS did you encounter this issue (trying to figure out if this happens only on Windows)?

/cc @deepak1556

**Comment by mattdesl** [comment]
I'm getting Chromium logs on OSX Yosemite.

**Comment by deepak1556** [comment]
Actually the proper way to disable chromium logging is to set the `logging_dest` to [LOG_NONE](https://code.google.com/p/chromium/codesearch#chromium/src/base/logging.h&sq=package:chromium&l=150&q=LOG_NONE) . @zcbenz can we set release mode logging to `LOG_NONE` [here](https://github.com/atom/electron/blob/master/atom/app/atom_main_delegate.cc#L42) before initialising the logger ? another option would be to check for `disable-logging` switch and set the appropriate `logging_dest` but i am not sure how to get swtich from app startup to presandbox state.

**Comment by preco21** [comment]
Same Issue

I'm using Windows 10 64 bit and Electron 0.31.0 (latest)
