### ISSUE TITLE
Tray balloons not showing up on Win7

### ISSUE THREAD

**Issue by bendulum** [atom/electron#2427]
```
    var Tray = require('tray');
    trayIcon = new Tray(iconPath);

    trayIcon.displayBalloon({
        icon: iconPath,
        title: 'fuuuu',
        content: 'more fuu'
    });

    trayIcon.on('balloon-show', function() {
        mainWindow.close();
    });
```

On Win7 this does not work although the icon shows up correctly in the tray. Attaching a context menu also worked. `displayBalloon` never does anything for me, the event also does not fire. `iconPath` is an absolute path to a png image. I see no error messages. I have Electron v0.30.2. 

What am I missing here? I took the code from here https://github.com/atom/electron/blob/master/docs/api/tray.md

**Comment by bendulum** [comment]
Same code is working now on a different machine (also Win7). Not sure what was at fault, and if this is an actual bug in electron...

**Comment by zcbenz** [comment]
Can you check your system notifications settings? I believe it is because the notification is disabled on your machine.

**Comment by bendulum** [comment]
I can confirm this works now. Thanks!
