### ISSUE TITLE
Where to handle ExternalInterface.call from swf?

### ISSUE THREAD

**Issue by sevengo8378** [atom/electron#2428]
I emebd swf using <webview> tag in index.html like this:
~~~html
    <script > 
        function testExternalCall(str) {
            console.log(str);
        } 
    </script>
    <webview id="swf" src="./asapp/out/Main.swf" style="display:inline-block; width:1024px; height:768px" 
        plugins="on" disablewebsecurity="on"></webview>
~~~

in actionscript make a call like this:
~~~actionscript
ExternalInterface.call("testExternalCall", "invoke from actionscript testExternalCall");
~~~

However， testExternalCall function in js is not triggered. Any suggestion?

**Comment by zcbenz** [comment]
You can check the solution in #2041.

**Comment by sevengo8378** [comment]
@zcbenz ,thanks for your reply.
Yesterday I have checked the #2041 thread, also i fixed the security issue.
If i embed html in webview tag, then put testExternalCall function in Main.html. It works well，function is triggered.
~~~html
<webview id="swf" src="./asapp/out/Main.html" style="display:inline-block; width:1024px; height:768px" 
        plugins="on" disablewebsecurity="on"></webview>
~~~
I don't know where to put testExternalCall function if directly set src=Main.swf. 
I have tried the preload attribute of webview tag. The result is js file is loaded, but function in js is still not triggered. 
~~~javascript
// alert is triggered
alert("swfBridge is loaded")

// this function is not triggered when ExternalInterface.call from actionscript
function testExternalCall(str) {
    console.log(str);
}
~~~

**Comment by zcbenz** [comment]
Maybe you can try `window.testExternalCall = function() {...}`, the preload script doesn't run in global scope.

**Comment by sevengo8378** [comment]
Still doesn't work.
Is the webview tag the only way to embed swf content? I try add these code in index.html, and cause a "Couldn't load plugin" error. It seems only webview tag has attribute plugins="on".
~~~html
<object id="swf" width="550" height="400">
        <embed src="./asapp/out/Main.swf"
        type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="1024" height="768"></embed>
        <param name="movie" value="sample.swf" />
        <param name="bgcolor" value="#ffffff" />
        <param name="height" value="768" />
        <param name="width" value="1024" />
        <param name="quality" value="high" />
        <param name="menu" value="false" />
        <param name="allowscriptaccess" value="always" />
    </object>
~~~

**Comment by sevengo8378** [comment]
Another question, can i use "ipc" module in webview embed html pages and communicate with index.html?

**Comment by zcbenz** [comment]
You have to load flash plugin to make flash work:
https://github.com/atom/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md

> Another question, can i use "ipc" module in webview embed html pages and communicate with index.html?

There is `ipc.sendToHost` API.
