### ISSUE TITLE
iojs 3.0.0 uses a different url for native addon headers (i think)

### ISSUE THREAD

**Issue by justinmchase** [atom/electron#2430]
When running `node-gyp` I am specifying the `--target` and `--dist-url` and this has been working fine for a while.

I just upgraded to iojs 3.0.0 and it appears to not work.
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@1.2.0 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.30.2/node-v0.30.2.tar.gz
...
```
Which worked. But after upgrading to 3.0.0 it appears to no longer work.
```
$ nvm install 3.0.0
$ nvm use 3.0.0
```

Results in the errors:
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v0.30.2/iojs-v0.30.2-headers.tar.gz
```

It appears that it is no looking for a `-headers.tar.gz` url, which atom seems to not be publishing. So my questions are:

A) Is the `-headers` version of the url supposed to work?
B) Which versions of node and node-gyp should I be using? 
C) What is the easiest way to tell what version of node I am supposed to be using for a given version of electron?

**Comment by justinmchase** [comment]
Btw, my build command looks something like this:
```
HOME=~/.electron-gyp node-gyp --target=0.30.2 x64 . --dist-url=https://atom.io/download/atom-shell configure build
```

**Comment by zcbenz** [comment]
It seems that io.js changed the filename of headers tarball (again!), I'll upload a copy of Electron's headers to the new location to make io.js happy.

Any version of npm and node-gyp except for the ones shipped by io.js v3.0.0 should work with Electron.

**Comment by zcbenz** [comment]
Refs https://github.com/nodejs/io.js/commit/e52f9636329dc5ecf3b6d79f8307e7817fff8e1e.
