### ISSUE TITLE
Fire an event on a drag & drop of an item to electron menubar

### ISSUE THREAD

**Issue by diasdavid** [atom/electron#2433]
Linking the issue open here https://github.com/maxogden/menubar/issues/3. Is there any elegant (possible would be fine as well) to enable drag & drop to electron's menu bar?

Thank you :)

**Comment by hokein** [comment]
Yes, Electron supports drag&drop feature since v0.30.1, see https://github.com/atom/electron/blob/master/docs/api/tray.md#event-drop-files

**Comment by diasdavid** [comment]
Thank you @hokein
