### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by flying-sheep** [atom/electron#2435]
Hi, sorry for opening a needless issue, but is there some form of planned release schedule?

Or do you simply release when certain features you’re interested in are there? Because I’m interested in #2383 and are wondering if i should wait for a release or not.

Thanks!

**Comment by zcbenz** [comment]
It is usually once a week, I'll probably publish a new release tomorrow.

**Comment by flying-sheep** [comment]
cool, thanks!
