### ISSUE TITLE
with multiple windows: unpredictable which dev tools window console.log() output goes to

### ISSUE THREAD

**Issue by freder** [atom/electron#2436]
hi,

I just started an electron project with multiple windows. 2 windows are created, and the dev tools are opened for both of them on creation.

when I adjust the size and position of the dev tools windows, electron seems to remember it, so the next time I start the program, they are in the same place.

however, `console` output of window number 1 does not always go to the left dev tools window. — sometimes it does, sometimes it doesn't.

![screen shot 2015-08-06 at 11 22 49](https://cloud.githubusercontent.com/assets/724844/9108450/70b761ca-3c2e-11e5-9d86-766a2a763dc3.png)

![screen shot 2015-08-06 at 11 22 22](https://cloud.githubusercontent.com/assets/724844/9108455/7708c2bc-3c2e-11e5-87bb-a1f0c09995ee.png)

is that a bug, or am I missing s.th. here?

**Comment by zcbenz** [comment]
Can not reproduce on 0.32.x anymore, please reopen if you still see it.

**Comment by freder** [comment]
still happens with `v0.33.0`

**Comment by zcbenz** [comment]
I think the console output actually goes into the correct window, it is just the window switched their positions. You can attach the devtools to the docked mode and see if the console output is in the correct window.

**Comment by freder** [comment]
when docked, everything is ok, indeed.
