### ISSUE TITLE
More than one process open

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2437]
If I build an Electron application and call it `bar.exe` then launch it.

![image](https://cloud.githubusercontent.com/assets/801252/9114023/8babc676-3c4f-11e5-9773-307e309846bf.png)
I see the application open the Task Manager three times... why is this?
When I close the application all three processes disappear (so they are related!)

**Comment by etiktin** [comment]
Yes. When you run Electron it will run 3 processes. That's because of Chromium's multi-process architecture. For more details see: https://www.chromium.org/developers/design-documents/multi-process-architecture

**Comment by iamdriz** [comment]
How do I know which process is the actual application?

**Comment by etiktin** [comment]
Look at their command line arguments. The first process with noting special in the command line is the main process. The others are renderers (notice the `--type` argument).

**Comment by iamdriz** [comment]
@etiktin What do you mean command line arguments? The command line isn't open. I'm just running the compiled exe.

Basically what I want to do is when I loop through the processes I can pick the correct process id for the main application and not the others.

**Comment by etiktin** [comment]
You can see it if you enable the "Command Line" column in the task manger details view (see details [here](http://www.winhelponline.com/blog/configure-task-manager-to-display-full-path-of-running-processes/)).

**Comment by iamdriz** [comment]
It seems that if you open another window in the same app that creates another process (so we'd have 4 processes now) but both windows still belong to one main process for the app. But the Window Title changes for this process to the new window that has been created.

**Comment by etiktin** [comment]
Yes, each additional window will run in a new process. It's stated in the Chromium's multi-process architecture link I posted before:
> In general, each new window or tab opens in a new process. The browser will spawn a new process and instruct it to create a single RenderView.

**Comment by priyatham-aps** [comment]
@etiktin 
Is this the case even when I have no windows open?
My application has only one tray icon and nothing else, and I still see three processes running.

**Comment by etiktin** [comment]
@priyatham-aps I guess so (I haven't used Electron for a while, but that's the basic architecture).

**Comment by M4kaveli** [comment]
hello @etiktin  thanks for your answer,
I have a question , i use request module to make http post requests
but i think this request will be sent three time due to three electron process
is possible?

**Comment by etiktin** [comment]
@M4kaveli it will be sent just once.
You can find details about the architecture at:
https://electronjs.org/docs/tutorial/application-architecture

**Comment by M4kaveli** [comment]
@etiktin 
Thanks,
So,
Maybe is due to setInterval ?
I use a request in setInterfal function and i have this problem...
Request sometime are sent more than once..
I don't know why so i asked about architecture.. 
My app  is like this : electron -> api -> electron web browser action -> api
exemple my api respond with  a string url and eletron navigate on this url.
any idea?

**Comment by M4kaveli** [comment]
I need to execute function every 10min so i use setinterval but i have problem with request sometime was executed more than once..

**Comment by etiktin** [comment]
@M4kaveli I suggest you open a new issue for you question, or try asking it on Electron's Slack channel.
In any case, I would probably start debugging it by making sure that the code you are running is being called from either the main process or the web page you load in the window, but not both (this could happen if you require the same code from both places etc.). One way to debug this, is to just write (append) to a file whenever your function is called, the result of https://github.com/jprichardson/is-electron-renderer/blob/master/index.js . If your code is being loaded from both places, you can refactor it or just protect the call with a test of isRenderer.

**Comment by M4kaveli** [comment]
@etiktin  Ok, thanks you and sorry for disturb !

**Comment by M4kaveli** [comment]
@etiktin  Hello, i founded the problem...
is this function :  win.webContents.on("did-finish-load", function () {

when page finish to load i call http request but the problem is when i click on website, the page refresh and enter again in "did-finish-load" so i have more than once request...

did you have any idea for this please? maybe one function same to did finish load but only for one time..

**Comment by etiktin** [comment]
@M4kaveli, I'm not familiar with your code. Maybe try to use a flag to block the second request. Something like:
```javascript
let requestSent = false;
win.webContents.on('did-finish-load', () => {
  if (!requestSent) {
    // Send the request
    ...
    requestSent = true;
})
```

**Comment by matteoannibali** [comment]
Hi, 
I need to run my electron processes as System in order to view and manage the Windows UAC messages for my Remote Desktop Application.

I use psexec -s but my processes run **WITH NO USER**

![image](https://user-images.githubusercontent.com/252208/41645385-236c6838-7471-11e8-8c44-e7c93813a4f7.png)

Maybe it's for Electron Architecture?

I try everything..it's possible to run Electron processes with System Privileges   :(

Thanks for you help....i'm near to give up.

**Comment by SwiTool** [comment]
> @M4kaveli, I'm not familiar with your code. Maybe try to use a flag to block the second request. Something like:
> 
> ```js
> let requestSent = false;
> win.webContents.on('did-finish-load', () => {
>   if (!requestSent) {
>     // Send the request
>     ...
>     requestSent = true;
> })
> ```

mhmm why not use `once` ?

```js
win.webContents.once('did-finish-load', () => {
    // Send the request
})
```

**Comment by o2genum** [comment]
Still not obvious why Electron opens 3 processes, not 2 (main and renderer). And it seems to open 2 processes per renderer.

This stackoverflow question provides a possible explanation:
https://stackoverflow.com/questions/52522026/what-are-these-extra-processes

Probably this should be covered in the docs.
