### ISSUE TITLE
Error: Call a callback of released render view

### ISSUE THREAD

**Issue by s-a** [atom/electron#2439]
![image](https://cloud.githubusercontent.com/assets/1270662/9119811/0b64ff9e-3c79-11e5-88d3-09b708175422.png)

Unfortunately I can not really reproduce it. I am experiencing this error using this code https://github.com/s-a/electron-toaster#usage then I refresh often via ```ctrl+r``` so that the code restarts.

How to catch this error? I mean if it is already released it must be save to process this exception as warning right?

Ref:https://github.com/s-a/iron-node/issues/31

**Comment by BakeRolls** [comment]
You should post it [here](https://github.com/s-a/electron-toaster/issues). Using IPC instead of remote could fix the issue.

**Comment by s-a** [comment]
@BakeRolls can you provide more details where I should use IPC?

**Comment by s-a** [comment]
Figured out this line https://github.com/atom/electron/blob/master/atom/browser/lib/rpc-server.coffee#L68 but how to catch this exception?

**Comment by BakeRolls** [comment]
@s-a If your main process waits for a message and would be responsible for creating the toast-window, it won't have to exec a callback of your renderer, wich can be uninitialized if you reloaded the app to fast. You would have to use your module from within your main process. See IPC [main process](https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md) and [renderer](https://github.com/atom/electron/blob/master/docs/api/ipc-renderer.md).

**Comment by s-a** [comment]
Thanks very much! Sounds promising.

**Comment by bengotow** [comment]
For anyone stumbling across this—I submitted https://github.com/atom/electron/pull/3103, which extends the error message to include the location of the released function.
