### ISSUE TITLE
Library not loaded: Mantle

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#2441]
Several of our users have complained that the Mac build does not work for them; while I'm trying tease out more detailed error reports, I was sent the following:

    Process: FooBar [2898]
    Path: /Applications/Foo Bar/FooBar.app/Contents/MacOS/FooBar
    Identifier: com.foo.foobar
    Version: ???
    Code Type: X86-64 (Native)
    Parent Process: ??? [1]
    Responsible: FooBar [2898]
    Date/Time: 2015-08-03 21:09:39.989 -0400
    OS Version: Mac OS X 10.10.4 (14E46)
    Report Version: 11
    Anonymous UUID: 09A4D490-19DA-B407-A9D0-719EFEF2E83C
    Time Awake Since Boot: 500 seconds
    Crashed Thread: 0
    Exception Type: EXC_BREAKPOINT (SIGTRAP)
    Exception Codes: 0x0000000000000002, 0x0000000000000000
    
    Application Specific Information:
    dyld: launch, loading dependent libraries
    
    Dyld Error Message:
    Library not loaded: @rpath/Mantle.framework/Mantle
    Referenced from: /Applications/Foo Bar/FooBar.app/Contents/MacOS/FooBar
    Reason: image not found
    
    Binary Images:
    0x7fff61dd9000 - 0x7fff61e0f837 dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld
    0x7fff891f1000 - 0x7fff893a1ff3 com.apple.QuartzCore (1.10 - 361.19) <F815B60E-75E3-3263-BE93-27A49882CF58> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff8e135000 - 0x7fff8e135fff com.apple.Carbon (154 - 157) <9BF51672-1684-3FDE-A561-FC59A2864EF8> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    
    Model: MacBook5,2, BootROM MB52.0088.B05, 2 processors, Intel Core 2 Duo, 2.13 GHz, 4 GB, SMC 1.38f5
    Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
    Memory Module: BANK 0/DIMM0, 2 GB, DDR2 SDRAM, 800 MHz, 0x7F7F7F7FB0000000, 0x4F435A324D38303032472020202020202020
    Memory Module: BANK 1/DIMM0, 2 GB, DDR2 SDRAM, 800 MHz, 0x7F7F7F7FB0000000, 0x4F435A324D38303032472020202020202020

(I swapped out the actual app name for "FooBar")

User states: "The Mac is an older one, circa 2010 or so, but it is running OS X Yosemite and the latest JVM."

Any idea why this user seems to have a problem finding Mantle (whatever that is)? Other users have no issues, and I can't imagine Electron has some hardware dependency. I just don't know where to start debugging this.

**Comment by zcbenz** [comment]
Can you ask the users to check if `YouApp.app/Contents/Frameworks` contain all necessary things? 

```bash
$ ls out/D/Electron.app/Contents/Frameworks/
Electron Framework.framework Mantle.framework
Electron Helper EH.app       ReactiveCocoa.framework
Electron Helper NP.app       Squirrel.framework
Electron Helper.app
```

Also your problem seems to be exactly the same with this one:
https://www.sencha.com/forum/showthread.php?303895-Works-perfectly-in-Windows-can-t-open-it-on-a-Mac&p=1111574

**Comment by Jmales** [comment]
What is the solution for this problem after all?

**Comment by artemv** [comment]
@Jmales I just had this issue on Mojave, fixed by removing spaces from `productName` in `electron-builder.json`. Before removing spaces it certainly worked on Capitan with the same name, but on Mojave I got this error lately:
```
Process:               My Desktop App [17691]
Path:                  /Applications/My Desktop App.app/Contents/MacOS/My Desktop App
Identifier:            com.electron.my-desktop-app
Version:               0.0.0-semantic-release (0.0.0-semantic-release)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           My Desktop App [17691]
User ID:               501

Date/Time:             2018-11-09 16:32:25.113 +0300
OS Version:            Mac OS X 10.14.1 (18B75)
Report Version:        12
Anonymous UUID:        E2AF8828-1EBE-0FFB-B42D-90B8663517BE

Time Awake Since Boot: 19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Mantle.framework/Mantle
  Referenced from: /Applications/My Desktop App.app/Contents/MacOS/My Desktop App
  Reason: image not found

Binary Images:
       0x10fa03000 -        0x10fa03ff7 +com.electron.my-desktop-app (0.0.0-semantic-release - 0.0.0-semantic-release) <F8DFE287-C6B4-3716-B3B3-CDF539205B40> /Applications/My Desktop App.app/Contents/MacOS/My Desktop App
       0x10fa09000 -        0x113cc0f17 +com.github.electron.framework (0) <3F98CCC6-1314-3F26-A9A0-8875072E18FA> /Applications/My Desktop App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x114248000 -        0x114263fff +com.github.Squirrel (1.0 - 1) <E4398068-33D3-3A00-9DBE-5ACC9B022501> /Applications/My Desktop App.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x114287000 -        0x1142eaff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/My Desktop App.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x114aff000 -        0x114b7d6a7  dyld (635.2) <1780094A-8FE2-3EAA-B4A3-C4CF14BC5196> /usr/lib/dyld
    0x7fff2ce88000 -     0x7fff2ce88fff  com.apple.Carbon (158 - 158) <BF1EC28F-CBA8-3B2F-B9FA-E583BC2D6C1F> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
```

**Comment by zztiswb116** [comment]
> but on Mojave I got this error lately

are you resolve this bug? how?

**Comment by artemv** [comment]
> > but on Mojave I got this error lately
> 
> are you resolve this bug? how?

fixed by removing spaces from productName in electron-builder.json like good old https://www.sencha.com/forum/showthread.php?303895-Works-perfectly-in-Windows-can-t-open-it-on-a-Mac&p=1111574 suggests.
