### ISSUE TITLE
Event when app is becoming active

### ISSUE THREAD

**Issue by ialexryan** [atom/electron#2444]
Steps to reproduce:
- hide or close all windows of your app.
- switch away from your app
- Cmd+Tab back to your app

Issue: the ["activate-with-no-open-windows" event](https://github.com/atom/electron/blob/master/docs/api/app.md#event-activate-with-no-open-windows) is only triggered if I return to the app by clicking on the dock icon, not by Cmd+Tab'ing.

**Comment by ialexryan** [comment]
This looks like it might be relevant: https://app.asana.com/0/15017329476852/26131671137841

**Comment by ialexryan** [comment]
This looks like it might be relevant: http://cocoadev.com/DifferentTypesOfAppActivation

**Comment by zcbenz** [comment]
This is expected since the term "activate" on OS X means the application is activated by clicking on the dock icon, what you want should be a new "active" or "focus" event that emitted when application is becoming active by Cmd+Tab or other means.

**Comment by zcbenz** [comment]
This has been fixed by adding the `activate` event.

**Comment by ialexryan** [comment]
Wait, sorry - how does that fix it? I just checked, and the `activate` event is not called when I Cmd+Tab to my application.

**Comment by loki951753** [comment]
> I just checked, and the activate event is not called when I Cmd+Tab to my application. 

same problem as @ialexryan

**Comment by moonwave99** [comment]
Had same problem, just checked what [Atom does](https://github.com/atom/atom/blob/master/src/browser/atom-application.coffee#L196).

**Comment by ialexryan** [comment]
Can this be reopened? My understanding is that my original issue still stands, although I'm no longer in a position to conveniently verify this with the latest Electron build.

**Comment by akashnimare** [comment]
@ialexryan It's there on latest build. Btw no application provide this feature. This issue exists even on telegram app (built on objective c). Same goes with chrome. So I guess this is standard behaviour (activate app only on click not on cmd+tab).

**Comment by chriswhong** [comment]
Hello, for anyone who stumbles across this, I was also seeing that the `activate` event only fired when switching back to my app by clicking on the dock, and did not fire when using `Cmd-Tab`.  

I wanted my electron to open its only window when the user brings the app back to the foreground.  I noticed that github desktop uses this approach, and it worked for me.  You have to use `Menu.sendActionToFirstResponder`:

```
      mainWindow.on('close', (e) => {
        if (!forceQuit) {
          e.preventDefault()
          Menu.sendActionToFirstResponder('hide:')
        }
      })
```
Where `forceQuit` is true if they are actually quitting the app, not just closing the window.

**Comment by emcmanus** [comment]
As explained above, the `activate` event works correctly. You're not supposed to "launch" applications from the app switcher.

There are two ways to fix the UX.

1. Exit the process when all windows are closed:
```
app.on('window-all-closed', () => {
  app.quit()
});
```

2. Or, if you'd like to keep the main thread running, even though no windows are visible:

```
// Hide our icon from the MacOS app switcher when there is no window to show.
app.on('browser-window-created', () => {
  app.dock.show(); // Show in app switcher
});
app.on('window-all-closed', () => {
  app.dock.hide(); // Hide from app switcher
});
app.on('activate', () => {
  // User has clicked the dock icon. Do whatever you need to, to create and/or show your main window.
});
```
