### ISSUE TITLE
referrer-header won't get setted on href

### ISSUE THREAD

**Issue by drmonty** [atom/electron#2445]
Here is a small example:

#### package.json

```
{
    "name": "example",
    "version":  "1",
    "main": "main.js"
}
```

#### main.js

```
var app = require('app');
var BrowserWindow = require('browser-window');
var mainWindow = null;
app.on('window-all-closed', function() {
    app.quit();
});
app.on('ready', function() {
    mainWindow = new BrowserWindow({width: 1280, height: 1024, "node-integration": false });
    mainWindow.loadUrl('http://127.0.0.1/index.php');
    mainWindow.openDevTools({ detach: true });
    mainWindow.on('closed', function() {
        mainWindow = null;
    });
});
```

#### index.php

```
<?php
error_log(array_key_exists('HTTP_REFERER', $_SERVER) ? "YES" : "NO");
echo
'<html>
    <body>
        <a href="/index.php">click</a>
    </body>
</html>';
```

(a http-server with php ability is up and running on port 80 and references a `/index.php` request to the above defined index.php).

#### start electron (if you are in the same directory, where you added your package.json / main.js)

```
electron .
```

If you click with electron on this link, the referrer-header won't get setted (as in your logs, there will only `NO`s get logged for every request.

Is there a way, to restore the original behavior of an webbrowser, which will always set the referrer header (if won't set some sort of attribute to prevent the default behavior to the link)?

Thanks!

**Comment by drmonty** [comment]
An even more minimal example:

main.js

```
var app = require('app');
var BrowserWindow = require('browser-window');
var mainWindow = null;
app.on('window-all-closed', function() {
    app.quit();
});
app.on('ready', function() {
    mainWindow = new BrowserWindow({width: 800, height: 600, "node-integration": false });
    mainWindow.loadUrl('http://www.whatismyreferer.com/');
    mainWindow.openDevTools({ detach: true });
    mainWindow.on('closed', function() {
        mainWindow = null;
    });
});
```

Click on the link. Expected is the following response:

```
Your referer:

http://www.whatismyreferer.com/
```

I receive:

```
Your referer:

No referer / Hidden
```

**Comment by drmonty** [comment]
hmm... If I change the Request from GET to POST, the referer get's finally transmitted.

A workaround would look like this:
Modify `index.php` from my first commit to the following:

#### index.php

```
<?php
error_log(array_key_exists('HTTP_REFERER', $_SERVER) ? "YES" : "NO");
echo
'<html>
    <head>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.11.3.min.js"></script>

        <script>
            $(document).click(function(event) {
                var href = $(event.target).attr("href");

                if (href != undefined)
                {
                    event.preventDefault();
                    $("<form action=\'" + href + "\' method=\'POST\'></form>").submit();
                }
            });
        </script>
    </head>
    <body>
        <p>HTTP_REFERER: ' . (array_key_exists('HTTP_REFERER', $_SERVER) ? "YES: " . $_SERVER['HTTP_REFERER'] : "NO") .'</p>
        <a href="/index.php'">click</a>
    </body>
</html>';
```

Electron will display this after clicking on the link:

```
HTTP_REFERER: YES: http://localhost/index.php

click
```

HTTP-Serverlog will also response with `YES`s.

@zcbenz is this the normal procedure to receive the referer?

**Comment by zcbenz** [comment]
> @zcbenz is this the normal procedure to receive the referer?

It is a bug that referrer is not set, the way link navigates in Electron is different from Chromium browser because we need to restart renderer process for every navigation, and I forgot to set the referrer.

**Comment by drmonty** [comment]
@zcbenz thanks for digging into this :smile:. hope it get's fixed soon.

**Comment by drmonty** [comment]
Thanks @deepak1556 and @zcbenz

**Comment by eyyubovkamran** [comment]
The bug still exists. Electron v1.2.0
