### ISSUE TITLE
Can't extract tarball or zip if it contains an asar archive

### ISSUE THREAD

**Issue by dustinblackman** [atom/electron#2446]
On Electron 0.30.2 (OSX 10.10.3) there seems to be an issue when extracting archives that contain .asar archives (created with [asar](https://github.com/atom/asar) 0.7.2). This happens when trying to extract tarballs with [node-tar](https://github.com/npm/node-tar) or [tar-fs](https://github.com/mafintosh/tar-fs), or zip files with [yauzl](https://github.com/thejoshwolfe/yauzl). If I was to run the exact some code outside of electron with iojs 2.3.1, then it works like a charm.

Here's a trace that winston sends out whenever it happens using yauzl. This will happen with both the original atom.asar archive, and my own app.asar. Also tried with just the electron releases to make sure it wasn't an issue with my own archives.

https://gist.github.com/dustinblackman/e1163128c3d6fd883af6

If curios on the code, the WIP of it is found here. https://github.com/dustinblackman/Championify/blob/dev/lib/zipz.coffee

EDIT:

Example code that'll get the same error but with tar-fs.

```coffeescript
zlib = require 'zlib'
tar = require 'tar-fs'
fs = require 'fs'

fs.createReadStream('./my-electron-app.tar.gz')
  .pipe(zlib.Gunzip())
  .pipe(tar.extract('./extract'))
```

**Comment by Eusebius1920** [comment]
+1

**Comment by mugifly** [comment]
+1

**Comment by Eusebius1920** [comment]
For a workaround (in case of tars) see #1658!
