### ISSUE TITLE
Accesskey Support

### ISSUE THREAD

**Issue by kjlaw89** [atom/electron#2448]
I've looked around for this, but haven't been able to find any results. Is it possible to use "accesskey" within electron? My application has a few instances of accesskey which work in the browser when pressing Alt+[key], but do not work in Electron.

**Comment by zcbenz** [comment]
Can you provide an example? And which operating system are you using? The http://dmauro.github.io/Keypress/ example seems to handle Alt+Key successfully in Electron.

**Comment by zcbenz** [comment]
Closing until there is more information provided.

**Comment by pushkin-** [comment]
If you point your webview to https://jsfiddle.net/z9buaych/, hitting Alt+C will not trigger the button.
