### ISSUE TITLE
Error when creating an audio context in electron

### ISSUE THREAD

**Issue by justinmchase** [atom/electron#2449]
In version `0.30.3` I'm getting an error on windows x64:

```
new AudioContext();
```
produces this error:
```
[29436:0807/150714:ERROR:audio_low_latency_output_win.cc(181)] Bailing out due to non-perfect timing.  Buffer size of 480 is not an even divisor of 1056
```

It appears to be coming from this file:
http://src.chromium.org/svn/trunk/src/media/audio/win/audio_low_latency_output_win.cc

Am I doing something wrong, does anyone have a hint for me?

**Comment by zcbenz** [comment]
Fixed in 0.31.0 as a result of Chrome 44 upgrade.
