### ISSUE TITLE
Resize webview will lead to crash in v0.30.3

### ISSUE THREAD

**Issue by jwu** [atom/electron#2450]
When I open a page that includes a webview, and resize it, it will crash.

To reproduce this:

1. create a browser window
2. add a webview in it:

```html
<html>
    <head>
        <title>Fireball-x Editor</title>
    </head>

    <body>
        <webview id="view" src="webview/index.html"
            nodeintegration
            disablewebsecurity
            autosize="on"
        ></webview>
    </body>
</html>
```

3. Keep resizing the window  by mouse

It will crash afterward.

I test this on Mac OSX with Electron v0.30.3. It is ok when I switch to v0.30.2

**Comment by frankhale** [comment]
I can confirm this with my app. My app's functionality relies heavily on webview and resizing the app crashes it using Electron 0.30.3.

**Comment by magicae** [comment]
Comfirm this with my app also.

**Comment by subwaymatch** [comment]
Confirm with my app also. 
It only occurs when 'src' attribute for the webview tag is set. 

**Case 1:** No 'src' attribute set (doesn't crash)
```html
<webview id="wv"></webview>
```

**Case 2:** 'src' attribute set (crashes)
```html
<webview id="wv" src="http://www.github.com"></webview>
```

**Case 3:** 'src' attribute set via Javascript (crashes)
```html
<webview id="wv"></webview>
```
```javascript
document.getElementById("wv").src = "http://www.google.com";
```

**Comment by frankhale** [comment]
Thank you @zcbenz, 0.30.4 fixes this issue!!!
