### ISSUE TITLE
`new BrowserWindow` event?

### ISSUE THREAD

**Issue by yan-foto** [atom/electron#2455]
I've been studying the source code and couldn't find a convenient event to find out if a new `BrowserWindow` is created *except* the [`browser-window-focus`](https://github.com/atom/electron/blob/master/atom/browser/api/lib/browser-window.coffee#L46), which is semantically different from a hypothetical `new-browser-window` event.

I could also use `BrowserWindow.getAllWindows()` to poll regularly and find out if any `BrowserWindow` has been created. But this doesn't sound like a good idea :worried:! 

Are there any events that I am missing at the moment? If not I would request it as a feature.

**Comment by hokein** [comment]
There is a `new-window` event in [`WebContents`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-new-window). Does it feed on your need? Usually developers create the BrowserWindow via `new BrowserWindow({option})`, you can probably hook it by yourself.

**Comment by yan-foto** [comment]
That event is an instance event, so I must at first have access to an instance of `WebContent` to be able to listen for the event. What I need is an app-wide notification upon creation of `BrowserWindow`s. You know what I mean?

**Comment by kevinsawicki** [comment]
> I've been studying the source code and couldn't find a convenient event to find out if a new BrowserWindow

There isn't an event for this available from the app module. But you could fire a custom event on the `app` whenever this occurs since your app itself is the one creating the browser windows

**Comment by yan-foto** [comment]
> since your app itself is the one creating the browser windows

that premise is not correct in my case. I am developing [a module](https://github.com/yan-foto/electron-reload) which refreshes the contents of `BrowserWindow` upon any change in source files. The idea is to require this module and let the rest be done automatically. I prefer to avoid asking users (of the module) to emit an event everytime they create a `BrowserWindow`. Does it make sense or am I missing something here?

**Comment by kevinsawicki** [comment]
> Does it make sense or am I missing something here?

Yeah, I see what you are saying, you can't currently monitor browser window creation from a library that isn't responsible for creating them.
