### ISSUE TITLE
Can't download prebuilt binaries

### ISSUE THREAD

**Issue by armaseg** [atom/electron#2466]
I'm trying to download prebuilt binaries for Windows (ia32 and x64) and everytime I try I get 
<code>ECONNRESET</code> or 
<code>Error: GET https://github.com/atom/electron/releases/download/v0.30.3/electron-v0.30.3-win32-ia32.zip returned 503</code>

I'm trying to do this directly downloading from Chrome and using 

<code>electron-packager ./ FooBar --platform=win32 --arch=ia32 --version=0.30.3</code>
<code>electron-packager ./ FooBar --platform=win32 --arch=ia32 --version=0.30.2</code>
<code>electron-packager ./ FooBar --platform=win32 --arch=ia32 --version=0.30.1</code>

**Comment by zcbenz** [comment]
AWS S3 is down for now, unfortunately there is nothing we can do except for waiting for S3 to recover.
https://news.ycombinator.com/item?id=10033172
