### ISSUE TITLE
Provide an option to bypass the 5MB application local storage limitation (for AppCache, IndexedDB etc.)

### ISSUE THREAD

**Issue by bvahdat** [atom/electron#2471]
Maybe something similar to the [`unlimitedStorage`](https://developer.chrome.com/apps/offline_storage#unlimited) option of Chrome Apps.

**Comment by deepak1556** [comment]
Electron doesnt impose the limit, it has already been patched in [libchromiumcontent](https://github.com/atom/libchromiumcontent/blob/atom/patches/dom_storage_map.patch) .

**Comment by bvahdat** [comment]
That's indeed true, thanks!
