### ISSUE TITLE
"Gtk: cannot open display" error when running from background app

### ISSUE THREAD

**Issue by fatihky** [atom/electron#2472]
Hi! I have added my electron program as a service on ubuntu. When I try to start it, it is not starting. I am disabled window creation. Applicaton does not create ui windows. But error continues. I am getting this error:
```
[11141:0811/004011:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[11141:0811/004011:ERROR:browser_main_loop.cc(219)] Gtk: cannot open display: 
[11143:0100/000000:ERROR:zygote_linux.cc(588)] write: Broken pipe
```

Note: I am on Elementary OS 64 Bits. For faster tests, I have created new simple service which tries to running my app and writes output to file. Small service's source code:
```js
require ('shelljs/global');
var log4js = require('log4js');
var logger;
log4js.loadAppender('file');
log4js.addAppender(log4js.appenders.file('/home/fatih/app.log'), 'file');

logger = log4js.getLogger('file');

function run_app() {
  exec ('/home/fatih/my-app/releases/my-app-linux-x64/my-app', function (code, output) {
    logger.debug ('real app exited with code:', code, output.substring(0, 400));
    //if (code !== 0)
    //  setTimeout(run_app, 3000);
  });
}

setInterval(function () {
  logger.debug ('ping');
}, 20000);

run_app();
```

I have compiled it to native with jxcore and I added it as a service. If I start this program from command line, it is working. But if I run this app as a service, my app is not starting.

Also, I have tried this: http://www.thegeekstuff.com/2010/06/xhost-cannot-open-display/ But it is not worked for me(I only run `xhost +` command from command line).

**Comment by zcbenz** [comment]
On Linux services are running without X session attached, and since Electron requires X11 to run, this is not something that can be fixed.

The only way is to make your app automatically run after the user has login, which is also how all other GUI applications do.

**Comment by srhyne** [comment]
@zcbenz thank you for your help with this. I'm using [Electron Screenshot Service]( https://github.com/FWeinb/electron-screenshot-service). And I have this same problem. Would you be to give a little more clarification to your statement?

`The only way is to make your app automatically run after the user has login, which is also how all other GUI applications do.`

Thank you in advance.

**Comment by srhyne** [comment]
@fatihky did you figure this out?

**Comment by zcbenz** [comment]
@srhyne http://standards.freedesktop.org/autostart-spec/autostart-spec-latest.html

**Comment by fatihky** [comment]
@srhyne yep. I added [app name].desktop file to ~/.config/autostart directory.

**Comment by srhyne** [comment]
Thank you @zcbenz and @fatihky
