### ISSUE TITLE
Atom/Electron Truck Factor

### ISSUE THREAD

**Issue by gavelino** [atom/electron#2478]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Atom/Electron** and obtained a value of **1**.

The developer responsible for this TF is:

Cheng Zhao - author of 98% of the files 

To validate our results, we would like to ask **Atom/Electron** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Atom/Electron**?

(b) Do you agree that **Atom/Electron** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Atom/Electron** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by kevinsawicki** [comment]
> (a) Do you agree that the listed developer is the main developer of Atom/Electron?

Yes

> (b) Do you agree that Atom/Electron will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

Yes

> (c) Does Atom/Electron have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Yes, we are actively looking to grow the team, both by hiring and by expanding the number of active maintainers on the project. We are also working to improve the documentation and the way issues are triaged.

Hope this helps, closing this out.

**Comment by gavelino** [comment]
Thank you.
