### ISSUE TITLE
How to catch errors occured in the main process?

### ISSUE THREAD

**Issue by s-a** [atom/electron#2479]
I d like to get details about exception via full stack trace. Devtools shows no error.

![image](https://cloud.githubusercontent.com/assets/1270662/9210044/32820072-407a-11e5-9cba-98e6a49d3c97.png)

ref:https://github.com/s-a/iron-node/issues/38

**Comment by bengotow** [comment]
Hi @s-a - you can bind node-inspector to the main process the same way you would a normal nodejs process: https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md. If you pass `--debug-brk`, you can connect node-inspector and then break on the exception.

**Comment by s-a** [comment]
Ty for fast response. I require only scripts in webview. I wonder it crashes the main process. Does electron use bcrypt? Tried to check package json but there are only a few dev dependencies. Do you know where  I can find a dependency list of electron (prebuilt)? I suspect a version conflict... Will try your tip tomorrow.

**Comment by s-a** [comment]
@bengotow  This is not possible in this case because I require the Meteor run-time libs in my project. In this case it returns ```--debug: unknown option.```. 

Would be new nice if main process errors could be written to 
 - DevTools console or
 - terminal console or
 - file system or
 - OS event system log

What do you think?

**Comment by etiktin** [comment]
To to catch errors that occure in the main process you can use:
```javascript
process.on('uncaughtException', function (error) {
    // Handle the error
}
```
When you set a listener for `uncaughtException`, Electron no longer outputs the error dialog from your first post. In the handler body, you can do what ever you want (output to console, show a custom error message etc.). You can also try to use `WebContents.executeJavaScript` and output an error message in the renderer side (if you use console.error, you should be able to see it in devtools). Keep in mind that when you get an `uncaughtException` the usual recommendation is to output an error and exit since the process is in unknown state, so trying to execute some code on the renderer side might fail.

You mentioned you're trying to load meteor app using Electron. Does meteor even works over io.js (last I checked it only worked with specific node.js versions)?

**Comment by s-a** [comment]
@etiktin 
Hi, I already tried ```uncaughtException``` event handler in the main process ```index.js```. Without success. 

Yes I try to make it work. I recompiled all native modules against current Electron. No plan if its  possible but I already started a Meteor hello world app. Now I try the next step (example todo app) and I stumble on ```bcrypt``` which was also compiled successful. 

Cannot figure out what tries to load bcrypt from where :smiley:   

I overwrote require and put a break-point there to get informed over any require attempt. In this case the debugger does not stop. So I suspect the require comes from any internal compiled Electron code, but not sure about this and I have no more Ideas at this point.

**Comment by etiktin** [comment]
It's weird that `uncaughtException` didn't work for you. Maybe you can try the following:
In your main script, only register the `uncaughtException` handler and set a timer to require the rest of your code.

Regarding meteor, I think it will be easier to first try and get meteor to work with the io.js version that electron uses. After you get it working with io.js, move the code to electron.

**Comment by s-a** [comment]
It is more weird that the exception is caused by a require statement from within webview code. So if I understand electron right this could not be a main process exception. Right?
I agree this would be easier. I like the pain :)
I do not require meteor code from main process.

**Comment by etiktin** [comment]
I'm not sure. If you try to require something that doesn't exists in the renderer, do you get an `uncaughtException` in the main process?
For example:
```javascript
var remote = require('remote');
var foo = remote.require('a/b/c/d/foo');
```
If you do get the exception, then it seems all node integration works through the main process. Maybe the issue you see with loading bcrypt is too low-level and `uncaughtException` can't catch it (you can see if that's the case by trying to load meteor in io.js, if `uncaughtException` won't catch it there, then it's not catchable).

**Comment by s-a** [comment]
This will not throw exception in main process.

![image](https://cloud.githubusercontent.com/assets/1270662/9229636/61a1607e-411e-11e5-9632-6b5f94e83860.png)

I do not use ```remote.require``` I am working with ```require``` from renderer. And I overwrote ```require``` as follows : https://github.com/s-a/iron-node/blob/f419dc896d3f0cea91761ea9ff43fb9038ebaed6/app/require.js
It fixes the path for native modules respecting current v8 version. 

The error occurs while it tries to load the wrong binary version because the code which caused the exception does not use my require version.

Maybe this happens because bcrypt was required by another native module which does not know my ```require``` command?

In detail this is what i am trying here https://github.com/s-a/iron-node/blob/f419dc896d3f0cea91761ea9ff43fb9038ebaed6/docs/METEOR.md

**Comment by etiktin** [comment]
@s-a, why did you close this issue? Did you figure out how to catch the error? If not then I suggest you leave it open for some feedback from the project maintainers (it might help future answer seekers).

Did you hear about [Electrometeor](https://github.com/sircharleswatson/Electrometeor)? They claim that they got meteor working on Electron. Maybe you can try to load bcrypt using their project and see what happens.

**Comment by s-a** [comment]
I do not want to create unnecessary noise. I wrote to the author of ElectroMeteor. Maybe he will answer. I updated to meteor 1.1.0.4 and the error is historie. Now it cannot find module ```kexec``` . I feel that success is near :smile:

**Comment by etiktin** [comment]
Good luck :+1:

**Comment by s-a** [comment]
After I upgraded the meteor project packages the error occurs again :crying_cat_face:

**Comment by zcbenz** [comment]
Can you provide a demo? The dialog you see is actually created in `uncaughtException` handler.

And for the error, I believe it is because you didn't follow [the right way](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) to install modules.

**Comment by s-a** [comment]
> I believe it is because you didn't follow the right way to install modules.

Yes this is what I am trying to do here. But I need more details about the exception to see what going on there.  

I have registered the ```uncaughtException``` event like this. But the code will not reached in this exception case. 
```javascript
var error = function(error) {
        debugger;
	console.error(error);
	var msg = {
		/*type : "error",
		title : "Uncaught Exception",
		buttons:["ok", "close"],*/
		width : 400
	};

	switch (typeof error) {
		case "object":
			msg.title = "Uncaught Exception: " + error.code;
			msg.message = error.message;
			break;
		case "string":
			msg.message = error;
			break;
	}
	msg.detail = "Please check the console log for more details.";

	ipc.send('electron-toaster-message', msg);
}

process.on('uncaughtException', error);
```


> Can you provide a demo?

This is not trivial. I tried this with ```meteor create --example todos``` example app. 


Steps to reproduce: 
 - ```npm install iron-node -g```
 - https://github.com/s-a/iron-node/blob/master/docs/METEOR.md
You nee to [setup meteor environment](https://github.com/s-a/iron-node/blob/master/docs/METEOR-DEBUG-BUILD.md#setup-metor-environment) before start the project.

The recompiling of native modules is non destructive. The build script will create a new folder for each binary handled by require function of my Electron app.

**Comment by zcbenz** [comment]
You need to setup `uncaughtException` handler in the main process since the exception happens there.

**Comment by s-a** [comment]
This is what @etiktin already mentioned. I ' ve tried that before.

**Comment by zcbenz** [comment]
Your `uncaughtException` handler is installed in the renderer process, that's why it doesn't work.

**Comment by s-a** [comment]
The code is not active in repository. I retried this again 30 minutes before.  My Handler should write a file to filesystem but it does not trigger.

**Comment by zcbenz** [comment]
That's because you are listening to the `uncaughtException` in the wrong process. In your case you should do it in `index.js` instead of `app.js`.

**Comment by s-a** [comment]
That is what I have tried.

**Comment by zcbenz** [comment]
Hmm from [your WIKI](https://github.com/s-a/iron-node/blob/master/docs/METEOR.md) you are using Electron as a replacement of upstream Node to run meteor, so the dialog you see doesn't come from your app, instead it comes from Meteor, if you want to catch that you have to modify Meteor's source code.

And for the error you see, I think it is because the troubling module is placed under `packages` folder instead of `node_modules`, so `npm` and `node-gyp` won't be able to find it.

**Comment by daniellmb** [comment]
Attaching to `process` wasn't enough for me. I also needed to hook into the error dialog to make sure I caught everything.

```js
 electron.dialog.showErrorBox = (title, content) => {
  console.log(`${title}\n${content}`);
 });
```

**Comment by tripower** [comment]
if I run my app with "npm run start" I can handle the exception with
`process.on('uncaughtException', function (err) {`
but after packaging and run the EXE with ASAR 
the code of uncaughtException will never be reached??
inside I have tried console.log, winston.log, process.exit ...
nohting happen

any ideas to get this working?

![electron starter with NO dll](https://github.com/electron/electron/assets/25051422/a5a575c1-4733-41e9-98ba-cdd1e1baa548)
