### ISSUE TITLE
Input type File HTML5

### ISSUE THREAD

**Issue by evillasr** [atom/electron#2480]
If I tray to use a input type="file" as normally on html5  it returns me C:\fakepath\ and then just the last part of the directory. 
In this case I will use File, like it's on the DOM (drag and drop) 
But I hope somebody tell me if there's a sollution or what could I try.

**Comment by hokein** [comment]
The result `C:\fakepath\` returned by `Input type File` is expected. If you want to get the selected file path, you should use the `dialog` module(https://github.com/atom/electron/blob/master/docs/api/dialog.md).

**Comment by seanzer** [comment]
check the ev.target.files property
