### ISSUE TITLE
Memory not to be recovered. Using CSS3 filter or SVG feGaussianBlur 

### ISSUE THREAD

**Issue by zg2013** [atom/electron#2482]
simulation IOS .
The chrome does not appear to be the case.
Frequent  add / remove   -webkit-filter:blur(3px), On multiple DOM nodes.
Memory is maintained at a very high level, and will not take the initiative to release.
 
use electron v0.30.4
![20150812155618](https://cloud.githubusercontent.com/assets/5134292/9219069/b539e116-410a-11e5-99e1-390623db16ab.png)

If I did something wrong, I would give a suggestion, thank you.

**Comment by zcbenz** [comment]
Can you provide a demo, or some code snippet that can run in both Chrome and Electron?

**Comment by zcbenz** [comment]
Closing until there is more information provided.
