### ISSUE TITLE
navigator.language always return "en-US"?

### ISSUE THREAD

**Issue by pracucci** [atom/electron#2484]
I'm running an Electron app on OSX 10.9.5 and I switched my system language to Italian (English is the secondary language). Then I relaunched the Electron app, and `navigator.language` still returns `en-US`.

I saw that was a patch applied to master last year, that should fix `navigator.language` so I'm wondering if I'm missing something or it's a bug. Does it work to your?

![screen shot 2015-08-12 at 10 16 12](https://cloud.githubusercontent.com/assets/1701904/9219492/8732fa02-40db-11e5-9f7c-d072a4cf9308.png)

**Comment by OlsonDev** [comment]
I just tried it on Windows 10. It returned `en-US` after I set it as `es-419` as the default (aka Spanish as spoken in the Latin America/Caribbean). Then I logged out of Windows, logged back in, reran it. Electron stated `es-419`.

Did you try signing out then back in?

**Comment by pracucci** [comment]
I found the root cause of the issue, thanks to @hongrich help on Slack's #electron channel. In order to make `navigator.language` (and generally, language detection) working in Electron on Mac, the `Resources` directory should contain a `<lang>.lproj` empty directory for each supported language. Since the directory is empty and git doesn't track empty dirs, I actually lost it when importing our project (including Electron pre-built binaries) to git.

**Comment by Luigiradicati** [comment]
Ciao @pracucci, do the .lproj dirs exist only in the built pkg or there's a way to have them also in the dev env? In other words, is there the possibility to have `navigator.language` return the correct value also when I'm coding or I must build a package to see the result? And does `getLocale()` have the same dependency on .lproj dirs?

**Comment by pracucci** [comment]
Ciao @Luigiradicati I'm not into Electron-based apps development anymore and I honestly don't remember it. Maybe @lele85 knows it?

**Comment by zerofront** [comment]
what' s the use of these empty .lproj directories? Is there any references?
