### ISSUE TITLE
Global shortcuts with more than one non modifier

### ISSUE THREAD

**Issue by diasdavid** [atom/electron#2486]
I'm not sure if possible/desired, but is there a way to create a global shortcut with more than one 'non modifier' key? Like: `cmd+i+p`?
 
The behaviour that I'm observing with:

```JavaScript
var ret = globalShortcut.register('ctrl+i+d', function () {
  console.log('ctrl+i+d is pressed')
})
```

Is that electron ignores the `i` and fires the callback on `ctrl+d`

**Comment by OlsonDev** [comment]
Not currently possible, see #2233.

**Comment by diasdavid** [comment]
Thank you @OlsonDev
