### ISSUE TITLE
Error on quit

### ISSUE THREAD

**Issue by frozeman** [atom/electron#2488]
If i quit the application using `cmd+Q` sometimes i get the following error:

```
[30224:0813/105526:WARNING:proxy_message_pipe_endpoint.cc(50)] Failed to write enqueue message to channel
[30224:0813/105526:WARNING:channel.cc(315)] RawChannel write error
module.js:336
    throw err;
          ^
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at process.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/init.js:45:12)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:219:26)
```

The main problem is that, when the app is killed with an error, chromium doesnt write the changes of the localstorage to disk and therefor loose them!

**Comment by frozeman** [comment]
Seems to be related to https://github.com/atom/electron/issues/1685

**Comment by etiktin** [comment]
From the stack trace it seems that closing the app caused an exception which was caught by electron's default `uncaughtException` handler. Then the handler tried to show and error dialog, but it failed to require the `dialog` module.
It will be interesting to know why it failed to load the `dialog` module, but for the time being you might be able to circumvent it. If you set you'r own handler for `uncaughtException`, the default handler won't try to show the error message, so if you're not going to show it in your handler, the exit should proceed successfully. Another thing you might want to try, is to require the dialog module in your main process. Once you require it, it should be cached, so the next time it's requested it should be served from the cache, which might solve the issue as well.

**Comment by zcbenz** [comment]
Can you paste following code in your main process script and see if it shows dialog correctly?

```js
require('dialog').showErrorBox('test', 'test');
```

**Comment by frozeman** [comment]
I tried you code and the error didn't seem to happen, so yes it was showing the dialog.
I'm currently was on 0.30.4 and i think i was on an older version where the error occurred.

I'm currently doing the following in quit to prevent the error:
```js
var killedSockets = false;
app.on('before-quit', function(event){
    if(!killedSockets)
        event.preventDefault();

    // CLEAR open IPC sockets to geth
    _.each(global.sockets, function(socket){
        if(socket) {
            console.log('Closing Socket ', socket.id);
            socket.destroy();
        }
    });

    // delay quit, so the sockets can close
    setTimeout(function(){
        killedSockets = true;
        app.quit();
    }, 500);
});
```

**Comment by zcbenz** [comment]
So does it occur on recent versions?

**Comment by frozeman** [comment]
It did not so far, but i also now have that workaround, which prevented it.

I will post when i get it again.

**Comment by zcbenz** [comment]
Cool, so I'm closing this until we get some new information.

**Comment by bengotow** [comment]
Hey folks—I think I've narrowed this down based on a Mailspring bug report. It looks like this happens if you synchronously call `app.quit()` from the main script of your app. (Which we're doing in the scenario linked above, when `makeSingleInstance` returns `true`, indicating another version of the app is already running.
