### ISSUE TITLE
Control OS Windows

### ISSUE THREAD

**Issue by vertangelx** [atom/electron#2489]
Is it possible for an electron app to manipulate the windows of OSX? For example, can an electron app minimize Chrome or drive Firefox to open http://www.google.com?

**Comment by etiktin** [comment]
Well, you can do that with node.js, so yes, it should work in Electron. Take a look at [RobotJS](https://www.npmjs.com/package/robotjs).

**Comment by hokein** [comment]
You can probably do it via third-party nodejs module(like RobotJS mentioned by @etiktin) or write a node addon.
