### ISSUE TITLE
Mac App Store

### ISSUE THREAD

**Issue by tanx** [atom/electron#249]
first of all thanks for open sourcing atom(-shell). It looks very interesting.

We currently have a chrome packaged app in the chrome web store and were looking at using node-webkit to package the app for the mac app store. Is this possible with atom-shell as well? I ask this because this was an issue for node-webkit at first, since it used private mac os apis:
https://github.com/rogerwang/node-webkit/issues/936

Thanks

**Comment by thewebdreamer** [comment]
@mstade & @zcbenz I was curious, has any progress been made?

**Comment by mstade** [comment]
Not by me I'm afraid, I had to move abroad shortly after the last conversation took place and so that took up my time and I unfortunately never got back to this. I don't think I will anytime soon either, sorry.

**Comment by callumlocke** [comment]
No update since January... has there been any progress on Mac App Store compatibility?

**Comment by alexzhang2015** [comment]
@tanx  Does the  email client (https://whiteout.io) with atom electron upload to mac app store successfully?

**Comment by tanx** [comment]
> @tanx Does the email client (https://whiteout.io) with atom electron upload to mac app store successfully?

We haven't gotten around to the Mac App yet. Using Chrome Apps on all desktop platforms.

**Comment by scottdraves** [comment]
:+1:

**Comment by tschundeee** [comment]
Hi friends just for reference: 

I am member of MacGap2:
https://macgapproject.github.io/

With MacGap2 you can bring your web based stuff into the app store as it is a very lightweight html container app.

I also wrote https://github.com/tschundeee/maverix as a OSX UI Bootstrap + Angular Starting Point that can be used together with macgap. So give it a try. Feedback is always welcome :)

**Comment by paulcbetts** [comment]
@tschundeee Can you delete this comment? It's not helpful or appropriate.

**Comment by callumlocke** [comment]
@paulcbetts I know what you mean, it feels spammy, but in this case I think it's relevant. The subscribers for this issue are looking for an AppStore-compatible way of building JS-based desktop apps, so his comment is both helpful and appropriate IMO. It just also happens to be self-promotional :)

**Comment by wisesascha** [comment]
Hey All. I believe I have successfully patched Electron. I'm going to release the binaries if my app is accepted onto the store.

**Comment by Jonty** [comment]
@wisesascha That's incredible news! Please push your patches somewhere so others can use/fix them.

**Comment by paulcbetts** [comment]
@wisesascha That's awesome! We can work with you to get those patches into mainline

**Comment by tschundeee** [comment]
Okay after reading my post I admit that it might sound a bit self-promotional but I just wanted to help people that want to get their web based stuff onto the app store now.
As both projects are MIT licensed and free to use I don't have a bad conscience about telling the world about them.

**Comment by callumlocke** [comment]
@tschundeee I don't think you should have a bad conscience about it at all! I will be checking out MacGap2 because I need something that works now. (But also hopeful about this news from @wisesascha.)

**Comment by tschundeee** [comment]
MacGap is supersmall because it makes use of the webkit version that ships with osx where electron bundles the blink engine. If you want to go multi-platform electron or https://github.com/nwjs/nw.js/ is the way. But if you are specifically targeting OS X => MacGap gets you really small app sizes (below 1mb) and comes as a real xcode project.

**Comment by paulcbetts** [comment]
@tschundeee Seriously. Stop.

**Comment by wisesascha** [comment]
https://github.com/wisesascha/libchromiumcontent/tree/atom-MAS This is the branch. I have added a patch that is highly based on https://github.com/alexeyst/node-webkit-macappstore . There are small changes that are not totally MAS support based they are more for making it compile on OS X El Capitan.

**Comment by zcbenz** [comment]
@wisesascha This is AWESOME! When your application succeeded to pass MAS's auditing I'll import your patch and provide an official build for it.

**Comment by unindented** [comment]
@wisesascha Any news on your app auditing?

**Comment by zcbenz** [comment]
Related: https://github.com/nwjs/chromium.src/commit/749a457884d0a8b775cc3ec2dc9243b604dd50c7.

**Comment by engelgabriel** [comment]
@wisesascha please give us some great news!!! :)
We need it for https://github.com/RocketChat/Rocket.Chat.Electron/issues/19

**Comment by wisesascha** [comment]
The truth is it keeps getting rejected for crashpad related issues. I have
resubmitted it for the 3 time. I will put in the latest patch when its
passes

**Comment by hankbao** [comment]
@wisesascha Good luck.

**Comment by maximeaubaret** [comment]
@wisesascha Bon Chance.

**Comment by engelgabriel** [comment]
@wisesascha boa sorte!

**Comment by zcbenz** [comment]
@wisesascha If crashpad is the only remaining issue, I think we can simply disable it in the Mac App Store build. In final release we will provide two builds for OS X, one is normal build, and the other is the build that with some MAS violating code disabled.

**Comment by paulcbetts** [comment]
@zcbenz Could we compile Crashpad as a library and delay-load it? That way it'd be easy to create the MAS version in `electron-packager` et al by reaching into the bundle and deleting the library. Creating separate builds will complicate the ecosystem more

**Comment by hokein** [comment]
Actually, the `crashpad_handler` is a sperated binary in `Electron.app/Contents/Frameworks/Electron Framework.framework/Resources`.

**Comment by zcbenz** [comment]
@paulcbetts Enabling MAS also removes some other features, from my understanding of https://github.com/nwjs/chromium.src/commit/749a457884d0a8b775cc3ec2dc9243b604dd50c7, it disables video capturing and makes the app not aware of DNS changes. Also https://github.com/nwjs/blink/commit/27b680078f32e59d6aabcbd63747e164997d3dd2 makes the input tag look less native.

@hokein `crashpad_handler` is only one part of the crash reporter, Electron still links to `vendor/crashpad/client/client.gyp:crashpad_client`.

**Comment by hokein** [comment]
@zcbenz  Thanks for pointing out. The only part in Electron that depends on `crashpad_client` and `crashpad_handler` is the `crash-reporter` API, we probably disable this API in MAS.

**Comment by Nax** [comment]
@wisesascha  Any update on this ?

**Comment by jarek-foksa** [comment]
Would it be technically possible to integrate Mac App Store in-app purchases too? Would such feature be accepted in the official branch?

**Comment by wisesascha** [comment]
My app got approved. The patch in my repo is up to date. There is one issue though. I had to patch crashpad in the electron repo but Im not sure the best way to publish those changes.

**Comment by hankbao** [comment]
Great :+1:

**Comment by wisesascha** [comment]
I just wanted to let everyone here know that I have created a guide on how to get your app on to the Mac App Store. Hopefully its useful to some of you. http://www.saschawise.com/blog/2015/08/12/electron-for-the-mac-app-store.html

**Comment by engelgabriel** [comment]
We :heart: @wisesascha :wink:

**Comment by scottdraves** [comment]
:heavy_plus_sign: :heavy_plus_sign:

**Comment by paulcbetts** [comment]
@wisesascha This is amazing, thank you so much for the hard work and the writeup!

**Comment by engelgabriel** [comment]
Hi @zcbenz and @paulcbetts,

Should we try to replicate what @wisesascha did in our applications? Or will you re-implement what he did in same shape or form back into the main repository so all the Electron apps would be able to safely submit to the Mac App Store?

Thanks all for the great work!

**Comment by frankhale** [comment]
As a side note to this, has anyone attempted to put an Electron based app in the Windows app store?

**Comment by paulcbetts** [comment]
@frankhale Only Modern™™™ apps can go in the Windows app store until Project Centennial ships. Desktop apps in the store right now are effectively just a marketing page, hitting the "Install" button just takes you to a 3rd party site

**Comment by paulcbetts** [comment]
> Or will you re-implement what he did in same shape or form back into the main repository so all the Electron apps would be able to safely submit to the Mac App Store?

There will probably be a 2nd version of Electron OS X posted for future releases that is MAS compatible

**Comment by frankhale** [comment]
Thanks @paulcbetts!

**Comment by behrangsa** [comment]
@paulcbetts any ETAs for the MAS compatible version of Electron?

**Comment by herrmannplatz** [comment]
Was checking @wisesascha approach. But its seems like that with [Version 0.31.0](https://github.com/atom/electron/releases/tag/v0.31.0) this no longer works, since ffmpeg lib is no longer shipped with the app. Any ideas to how to solve this?

**Comment by wisesascha** [comment]
I'll look into fixing this, but my first guess is that you have to modify
some of the gyp files to no longer include ffmpeg.

**Comment by herrmannplatz** [comment]
I looks like that one issue is that ffmpeg is using QTKit. Isnt it possible to create a patch that compile ffmpeg without using QTKit like mentioned [here](http://stackoverflow.com/questions/26652950/remove-qtkit-dependency)?

**Comment by zcbenz** [comment]
@wisesascha How much time did the "processing" step take for you in iTunes Connect? I have waited for hours and I'm now wondering whether it is going to last forever.

**Comment by herrmannplatz** [comment]
@zcbenz I used the Application Loader App. And it took a couple of minutes to upload to itunes connect. Before i managed to upload i run into a couple of issues that where already detected by the application uploader.

**Comment by herrmannplatz** [comment]
any updates?

**Comment by behrangsa** [comment]
@herrmannplatz See https://github.com/atom/electron/pull/2920

**Comment by herrmannplatz** [comment]
I know. The question was related to the upload experiment.

**Comment by scottdraves** [comment]
:dolphin: :dolphin:

**Comment by holgersindbaek** [comment]
I know if might be a little off topic, but I need to do in app purchases in mu Electron app for the Mac App Store. It doesn't seem like anyone has figured out how to do that yet, so I've created a post on Stackoverflow with a 300 reputation points worth of bounty. If you think you can get more specific with how you'd do in app purchases, please let me know in there:

https://stackoverflow.com/questions/46753835/implementing-in-app-purchase-in-an-electron-app-for-the-mac-app-store
