### ISSUE TITLE
Issue finding node module in renderer window process

### ISSUE THREAD

**Issue by aackerman** [atom/electron#2494]
I'm running into an issue where on reload of a window *somewhat rarely* the renderer window is not able to resolve a node module and my application is unable to continue running.

This is using a build folder, not an `asar` file.

Is it possible there are race conditions involved with this code path?
```
Uncaught Error: Cannot find module 'winston'
Module._resolveFilename @ module.js:332
Module._load @ module.js:282
Module.require @ module.js:361
require @ module.js:380
(anonymous function) @ main.js:29702
```

```
process.versions
{
  "http_parser": "2.5.0",
  "node": "2.2.1",
  "v8": "4.3.61.21",
  "uv": "1.5.0",
  "zlib": "1.2.8",
  "ares": "1.10.1-DEV",
  "modules": "44",
  "openssl": "1.0.2a",
  "electron": "0.28.1",
  "atom-shell": "0.28.1",
  "chrome": "43.0.2357.65"
}
```

![screen shot 2015-08-13 at 9 54 07 am](https://cloud.githubusercontent.com/assets/786640/9253036/6a9fdf74-41a1-11e5-8136-5374446cd91d.png)

**Comment by bpasero** [comment]
Not sure if related, but fyi with io.js 2.2.0 you get this when you require on Windows with a path that contains unicode characters: https://github.com/nodejs/node/issues/2236

**Comment by aackerman** [comment]
@bpasero thanks for the info, but yes that is likely unrelated.

I haven't a found a way to create a reduced test case, but I have selenium/capybara testing failures related to this that can reproduce this issue somewhat consistently, maybe 30% of the time when the tests are run in a loop.

**Comment by kevinsawicki** [comment]
Are you able to log out `require('module').globalPaths` when the issue happens?

**Comment by aackerman** [comment]
I should be able to, this error is caught by `uncaughtException` callbacks so I'll try that in the morning and comment back midday tomorrow.

**Comment by aackerman** [comment]
The global paths appear to be the expected paths. In this case app is symlinked to my build directory, I wouldn't expect that to be a problem.

```
/Users/aaron.ackerman/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/lib/node
/Users/aaron.ackerman/Electron.app/Contents/Resources/atom.asar/renderer/api/lib
/Users/aaron.ackerman/Electron.app/Contents/Resources/app
/Users/aaron.ackerman/Electron.app/Contents/Resources/app.asar
/Users/aaron.ackerman/Electron.app/Contents/Resources/atom.asar/common/api/lib
```

I think I have some great info here to begin debugging this problem, I've got two screenshots, the first is a scenario where the module is able to be required with 22 resolved lookup paths.

![screen shot 2015-08-18 at 8 14 20 am](https://cloud.githubusercontent.com/assets/786640/9330821/562a023e-4581-11e5-82b2-15f6ce12dbb7.png)

The second screenshot here, where the module was not able to be required, the app was only able to find 14 lookup paths. To try to reproduce the problem I added a breakpoint to `module.js` and used a bare `require('winston')` from the devtools console. Same end result, but I hope that doesn't skew the output.

![screen shot 2015-08-18 at 8 12 58 am](https://cloud.githubusercontent.com/assets/786640/9330829/6bc25b64-4581-11e5-826d-e1b0d65abfc6.png)

In the failure case the parent module is coming the `atom.asar`. In the case where it works, the parent module is the application's `index.html` file.

**Comment by aackerman** [comment]
@kevinsawicki do you happen to know where I might go from here to try to figure out why the second screenshot error case is possible?

**Comment by kevinsawicki** [comment]
> do you happen to know where I might go from here to try to figure out why the second screenshot error case is possible?

I'm not sure, @zcbenz or others might have some ideas.

Are you able to reproduce this issue on electron 0.30+? I wonder if it may be an asar issue that has already been fixed.

**Comment by vikbez** [comment]
I'm having this issue on windows when I load the application over network.
paths like: "\\SERVER\stuff\app\resources\app\node_modules"

**Comment by zcbenz** [comment]
It is an old bug that has already been fixed, please report back if you are still able to reproduce it on 0.30+.

**Comment by aackerman** [comment]
Would you mind pointing me toward the PR that fixes this issue so I can understand what's happening here?

**Comment by zcbenz** [comment]
It was fixed months ago, basically it was caused because the javascript context sometimes is created earlier than the page and Electron failed to add module search paths for the page's location.

**Comment by mnichols** [comment]
I just ran into this with Electron v0.30.6 on OSX 10.10.3. 
Here is what I ran from my project root : `./node_modules/.bin/electron .`

Here are the results of 
```js
// inside index.html
require('module').globalPaths.forEach(console.log.bind(console))
```

It looks like my apps `node_modules` folder isnt in the module paths in the renderer process? I would expect to see: `/Users/mnichols/dev/pqls/apps/agent-ui/node_modules` somewhere in there. 

```
[38631:0831/171832:INFO:CONSOLE(18)] "/Users/mnichols/dev/pqls/apps/agent-ui/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/lib/node", source: file:///Users/mnichols/dev/pqls/apps/agent-ui/signIn.html (18)
[38631:0831/171832:INFO:CONSOLE(18)] "/Users/mnichols/dev/pqls/apps/agent-ui/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib", source: file:///Users/mnichols/dev/pqls/apps/agent-ui/signIn.html (18)
[38631:0831/171832:INFO:CONSOLE(18)] "/Users/mnichols/dev/pqls/apps/agent-ui/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/app", source: file:///Users/mnichols/dev/pqls/apps/agent-ui/signIn.html (18)
[38631:0831/171832:INFO:CONSOLE(18)] "/Users/mnichols/dev/pqls/apps/agent-ui/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/app.asar", source: file:///Users/mnichols/dev/pqls/apps/agent-ui/signIn.html (18)
[38631:0831/171832:INFO:CONSOLE(18)] "/Users/mnichols/dev/pqls/apps/agent-ui/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/common/api/lib", source: file:///Users/mnichols/dev/pqls/apps/agent-ui/signIn.html (18)
[38631:0831/171832:INFO:CONSOLE(336)] "Uncaught Error: Cannot find module 'package.version'", source: module.js (336)
```

Am I doing something incorrectly?

**Comment by npenin** [comment]
I do have the same issue. I guess my global paths are wrong, but don't know what to do against that :
```
require('module').globalPaths
["/home/pi/mediacenter/node_modules/electron-prebuilt/dist/resources/atom.asar/common/api/lib", "/home/pi/mediacenter/node_modules/electron-prebuilt/dist/resources/atom.asar/renderer/api/lib"]
```

Any clue ?
