### ISSUE TITLE
Access/edit resources of external webpages from main process?

### ISSUE THREAD

**Issue by Malaz27** [atom/electron#2496]
I have my app loading webpages within electron itself, using the shell module is not an option for what i want the app to do. I want to edit/insert code into the HTML of these webpages from the main process, is this at all possible, and if so how? I tried accessing the document as s-a did [here](https://github.com/atom/electron/issues/2425), but both `mainWindow.document` and `mainWindow.webContents.document` were apparently undefined.

**Comment by etiktin** [comment]
You could do it with a `preload` script or with `WebContents.executeJavaScript`.

**Comment by kevinsawicki** [comment]
Here are some links to the docs that @etiktin mentioned:

Executing JavaScript from the main process: https://github.com/atom/electron/blob/master/docs/api/browser-window.md#webcontentsexecutejavascriptcode-usergesture

Using a `preload` file when creating a new `BrowserWindow`: https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

Closing this out.
