### ISSUE TITLE
Extending electron - Adding an Xcode Project as a library

### ISSUE THREAD

**Issue by mattotodd** [atom/electron#2497]
I have added a git submodule as a dependency to electron, but I am having a hard time trying to get it added to the build path.

I can import from the library by specifying the path directly:

    #include "vendor/foo_library/FooLibrary/FooInterface.h"

but all relative paths from the initial imported file do not work for the library.

How can I add this lib to my electron build?  I dont seem to see any specific docs for such a thing.

Does it help at all that my library has an FooLibrary.xcodeproject folder?

**Comment by mattotodd** [comment]
Was able to build past the import steps by adding my lib folder to the `include_dirs` of the lectron_lib,  but now the Electron Framework POSTBUILD step throws:

    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_FooSettings", referenced from:
          objc-class-ref in libelectron_lib.a(electron_lib.platform_util_mac.o)
    ld: symbol(s) not found for architecture x86_64

**Comment by paulcbetts** [comment]
If you want to extend Electron, an easier way would be to create a node.js module that includes your Framework via static linking

**Comment by mattotodd** [comment]
Thanks for the reply @paulcbetts  I'd rather not modify electron if I don't have to

I guess I was thinking since electron was taking care of using the correct mac/windows related code for each platform,  that would be the place for me to add my code.

If I were to write a node module that used static linking, and needed to use it with both windows and mac versions of electron (the existing library I am trying to link to is written in objective-c for mac, c++ for windows),  would I be making the distinction to use the correct platform library in my javascript code,  or would I have to build a version of the node module for each platform?

**Comment by paulcbetts** [comment]
> or would I have to build a version of the node module for each platform?

You usually do this via setting up your Gyp file in your native module to include the right native code per-platform. Since native node modules usually get rebuilt from source via `npm rebuild` (then later, electron-rebuild), the appropriate section of your Gyp file will get run

**Comment by mattotodd** [comment]
ok,  I notice the node docs on addons are explicitly about linking to c++ code.  Can this be done with objective-c code ?

**Comment by mattotodd** [comment]
ok @paulcbetts been banging my head against this for a while now, and i suspect that the reason I am having trouble with the addon is that it can't be written in objective-c code, or at least when I go to use any mac CoreFoundation (like NSString)  it throws an error.   Do you know, can you only write a node.js addon in pure c++ code.  Can I not take advantage of any mac specific framework? I realize you may not know the answer to this.

If so, I may need to go back to forking electron, where I can use objective-c code (just having trouble linking my library)

**Comment by paulcbetts** [comment]
> Do you know, can you only write a node.js addon in pure c++ code. Can I not take advantage of any mac specific framework? I realize you may not know the answer to this.

You should use Objective-C++ (i.e. C++ classes + you can call Objective-C), the extension is `.mm`

**Comment by gabriel** [comment]
Are there any examples somewhere of packaging a mac framework as a native node module for use in the Electron app?

**Comment by mralexgray** [comment]
+1 @gabriel re: wanting some concrete examples.

**Comment by hello-chenchen** [comment]
https://github.com/zoom/zoom-macsdk-electron
maybe this project can provide some ideas.
