### ISSUE TITLE
Build fails when MSVS 2015 is installed but not '2013.

### ISSUE THREAD

**Issue by teleclimber** [atom/electron#2499]
The build docs for Windows [1] mention the need for MSVS 2013, but points to a page that downloads 2015. As a result the naive developer (ahem, me) might assume 2015 works just as well as 2013 to build Electron on Windows. My experience indicates otherwise. [2]

Either the docs should be updated to point to MSVS 2013, or there is apparently a bug in the build system when using '2015.

[1] http://electron.atom.io/docs/v0.30.0/development/build-instructions-windows/
[2] https://discuss.atom.io/t/build-on-windows-could-not-locate-visual-studio-error/19888

**Comment by fredvb** [comment]
Sorry to append to this issue, but I've been also encountering issues with MSVS 2015, will try to downgrade to 2013 and see. 
But on another node, I've been wondering on what version of Node.js (or io.js) I should be when attempting to build module that require to be rebuilt with node-gyp (I assume those are native modules). 

It would be nice if the windows releases gave information on what version of Node was used. I might be blind, maybe it's straight in my face.

**Comment by paulcbetts** [comment]
You can't use VS2015, you need to use VS2013. If you've got both installed, set the `GYP_MSVS_VERSION` environment variable to `2013`

**Comment by fredvb** [comment]
Thanks, seems like this can be done via this command, if I understand well: npm config set msvs_version 2013 --global

Regarding the Node version, what version of Node is used to build the latest Electron release v0.30.4 ?

**Comment by paulcbetts** [comment]
@fredvb You should set up `electron-rebuild` if you're going to use native modules, then you can use whatever system version of node.js you want.

**Comment by fredvb** [comment]
Installing VS2013 Express did the job.

**Comment by zcbenz** [comment]
Closing since #2503 has made the requirement of compiler clearer.
