### ISSUE TITLE
[mac] provide a way to handle/prevent pinch zoom

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2500]
With an electron app on Mac I can use the trackpad to pinch zoom into the application either by tapping with 2 fingers or pinch zoom. I could not find a way to disable this behavior (I was hoping for some meta tag I could use to control this behavior in Chrome itself, but it did not work: http://stackoverflow.com/questions/11689353/disable-pinch-zoom-on-mobile-web).

Ideally in Electron I have API to disable this behavior or control what it should do.

**Comment by tomashanacek** [comment]
:+1:

**Comment by ricodang** [comment]
![1f44d](https://cloud.githubusercontent.com/assets/12050858/9305007/ff65b8dc-44ed-11e5-9a6a-db40e19c4363.png)

**Comment by markadrake** [comment]
I agree.

An issue with Windows too. The meta tag for viewport seems to only take effect for mobile devices, and [this solution did not work for me](http://stackoverflow.com/questions/29929411/disable-pinch-zoom-in-webkit-or-electron) either.

**Comment by tomashanacek** [comment]
Hi this works for me:

```
window.addEventListener('mousewheel', function(e) {
  if (e.ctrlKey) {
    e.preventDefault();
  }
});
```

**Comment by markadrake** [comment]
You're exactly right - my app hadn't updated until just recently. The JS above does work.

**Comment by zcbenz** [comment]
[blink::WebView::zoomLimitsChanged](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/public/web/WebView.h&sq=package:chromium&rcl=1440301189&l=208&type=cs) seems to be able to disable this.

**Comment by bpasero** [comment]
@zcbenz when I look at the arguments of the renderer, I can see --enable-pinch and --enable-pinch-virtual-viewport. Maybe those have an impact too?

**Comment by zcbenz** [comment]
@bpasero That looks quite suspicious, I'll take a look, thanks!

**Comment by carlosperate** [comment]
Is there a way to prevent this from the main process side, instead of the renderer process?

**Comment by zcbenz** [comment]
Chromium doesn't expose API on main process side, I think it is probably because all the rendering is done in renderer process.
