### ISSUE TITLE
Using `fs` in a webview preload script throws a `process is undefined` error

### ISSUE THREAD

**Issue by mart-jansink** [atom/electron#2502]
Using a `webview` tag such as `<webview src="http://controlled.server.com" preload="preload.js" allowtransparency="on"></webview>` with `preload.js` containing the minimum working example:

```
var fs = require("fs");
fs.createReadStream( "/tmp/foo" );
```

results in `Uncaught ReferenceError: process is not defined`. As far as I can tell, the `fs` module uses the `stream` module and both modules contain references to the `process` global variable even though they don't `require` the `process` module themselves and therefore can't access the variable anymore after it's cleaned up.

Is there some way to remedy this? I'd rather avoid enabling `node-integration`, even though the `webview`'s source URL is hardcoded and completely under my control..

**Comment by zcbenz** [comment]
Currently you have to add the `process` object back to `global` to work around this:

```js
var process = global.process;
process.once('loaded', function() {
  window.process = process;
});
```

I will figure out a better solution to make `process` and other things available in node modules while not polluting the global scope.
