### ISSUE TITLE
(Win64) Electron crashes after writing a file (piped from an HTTP request) when packed (asar)

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/electron#2507]
I have an app which uses http.get to pull a file from the web - writing it via pipe to an fs.createwritestream

It works 100% AOK in an unpacked app - if I pack the app (asar) it still works (e.g. the file is read/written OK) however Electron crashes when you quit/exit ("Electron has stopped working") dialog - no other errors or clues (app does exit when closed from the dialog)

This is version 0.29.2 - I can't use 0.30.x due to the tray icon bug (my app only exists as a tray icon - so without one, it doesn't exist!!)

Note: the file it's writing is in the same directory as the asar file - that may be part of the problem?

If there are ways I can get more information/debugging - crash files I can find - please let me know.

**Comment by zcbenz** [comment]
Can you have a try of v0.30.5/v0.31.0? They have the tray bug fixed.

**Comment by shrewdlogarithm** [comment]
First quick test suggests the crash no longer happens as of 0.30.6 (I
didn't try 0.31.0 or 0.30.5 yet) - so that's a good thing!

**Comment by zcbenz** [comment]
Good to hear that.
