### ISSUE TITLE
Accessing full uri from custom protocol

### ISSUE THREAD

**Issue by kevlened** [atom/electron#2514]
Electron v0.30.4
OSX 10.10.4

I'm trying to create a link to my app using a custom protocol like `myapp://somedata`. The electron-packager [supports custom protocol registration on Macs](https://github.com/maxogden/electron-packager/commit/18871061d52068804125425943e47fd088979ed5). Safari successfully opens my app using the custom protocol, but how can I inspect `somedata` when my app opens?

It appears [node-webkit passes the uri using argv](https://github.com/nwjs/nw.js/pull/1769#issuecomment-70824265).

I looked at [the protocol api](https://github.com/atom/electron/blob/master/docs/api/protocol.md), although it only seems relevant for links within my app, not on a system-wide scale.

**Comment by kevinsawicki** [comment]
Have you tried the `open-url` event?

```js
require('app').on('open-url', function(event, urlToOpen) {
   event.preventDefault();
   console.log(urlToOpen);
});
```

https://github.com/atom/electron/blob/master/docs/api/app.md#event-open-url

**Comment by kevlened** [comment]
That's exactly what I needed. Thanks!

**Comment by daniellizik** [comment]
`open-url` doesn't seem to fire in 2.0.16
