### ISSUE TITLE
Installation error on Ubuntu 15.04 using npm pre-built

### ISSUE THREAD

**Issue by nethack42** [atom/electron#2516]
When trying to install electron using "npm install electron-prebuilt -g" the installation fails since the nodejs binary is called "nodejs" instead of "node". 

As a workaround one can create a symlink: 
```bash
ln -s /usr/bin/nodejs /usr/local/bin/node
```

This error occurs on Ubuntu 15.04 but should be reproducible with every Ubuntu/Debian version.

```bash
npm ERR! electron-prebuilt@0.30.4 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
...
npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
```

**Comment by Tribex** [comment]
15.10 or 15.04? O_o
15.10 isn't going to be officially released for another two months.

**Comment by nethack42** [comment]
Sorry, I meant 15.04.
Updated the issue description.

**Comment by zcbenz** [comment]
I suggest always using the official tarball of Node instead of the one bundled by Ubuntu, many Node modules (including _all_ native Node modules) assumes the existence of `node` command in their install script, so even we fixed this in electron-prebuilt you are gonna see this error soon after you start to write a Electron app.

I'm closing this as won't fix.

**Comment by DaVince** [comment]
That is really weird, thanks for making me aware. I'll do that.

That makes me think... Possibly something to include in the install instructions on the page?

**Comment by z3ntu** [comment]
I have the same issue on Ubuntu 15.04 myself. PLEASE add a note to the website for users that are affected by this...

> The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

**Comment by etiktin** [comment]
@z3ntu, if you have the time, you can add the note yourself by creating a PR (see details [here](https://help.github.com/articles/editing-files-in-another-user-s-repository/)).
