### ISSUE TITLE
Can't exit html5 fullscreen by keyboard

### ISSUE THREAD

**Issue by duanyao** [atom/electron#2517]
In most browsers, users can exit html5 fullscreen by pressing 'ESC' key, however Electron can't. I suggest Electron to also do this by default.

**Comment by hokein** [comment]
This behavior is aligned with Chrome's. In Chrome browser, user presses `F11` to enter the full screen and represses `F11` to exit(The `Esc` key makes no sense).

**Comment by duanyao** [comment]
No, I'm talking about html5 fullscreen, not F11-fullscreen. Chrome also exit html5 fullscreen via `Esc`.

**Comment by hokein** [comment]
Oops...I misunderstand it.

**Comment by qgustavor** [comment]
Is possible to add a option to restore old behavior?
