### ISSUE TITLE
Allow customization of default dialogs

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2522]
I think it would be cool if we allowed customization of default dialogs (alert, confirm and prompt), by registering a handler. So for example if I want my alerts to have a custom title and icon, I could do something like this:
```javascript
mainWindow.onAlert = function (msg) {
    var dialog = remote.require('dialog');
    dialog.showMessageBox(
        mainWindow,
        {
            type: 'none',
            icon: './alert.png',
            title: 'Foobar',
            message: msg,
            buttons: ['Click me'],
            noLink: true
        }
    );
}
```

You could even translate the title, labels etc. (see #2518 for a related issue).

If we will have support for default "confirm navigation" dialog (see #2481), it will be great if we can customize that too.

The handlers should probably always use `dialog.showMessageBox`, because these dialogs are supposed to be modal and synchronous. So maybe it would make more sense for the handlers to just return the options parameter for `dialog.showMessageBox`. For example:
```javascript
mainWindow.onAlert = function (msg) {
	return {
            type: 'none',
            icon: './alert.png',
            title: 'Foobar',
            message: msg,
            buttons: ['Click me'],
            noLink: true
    };
}
```

To be fair, you could accomplish some of these stuff by hooking the methods or using custom methods. That said, I think it's pretty common to want to customize them and Electron as a framework for building applications should expose an API for that.

What do you think?

**Comment by duanyao** [comment]
I think it is even better to be able to intercept dialogs globally, so you don't have to change every site that creates `BrowserWindow`:

app.on('dialog-alert', function(ev) {
  //...
});

**Comment by etiktin** [comment]
Some users are running multi-apps through a single app. They basically just open new windows for each app from a single master process (see for example #2415 and #2438). So I think it's better to leave the configuration on the `BrowserWindow` which will give the option to configure the look differently per window (e.g. they can set different dialog title per window). If you want to set the same options for all windows, you could still do that by wrapping the window creation with code to set up the options.

The more I think about it, I don't see a reason to treat this like setting an event handler. We just want to allow customization of the modal dialog, which means the options used to create it. So maybe something like this will be better:
```javascript
mainWindow.alertDialogOptions = {
	type: 'none',
	icon: './alert.png',
	title: 'Foobar',
	buttons: ['Click me'],
	noLink: true
};
```
When an alert is called, the modal dialog creation code, will check if the developer supplied an options object and if so it will customize the dialog according to it and then display it.
This approach seems simpler and cleaner to me.

**Comment by duanyao** [comment]
There are requirements other than just changing the look and feel of dialogs, e.g.:

* Block dialogs from all or some pages, according to user's setting.

* Fill authentication dialogs with saved usernames/passwords.

Additionally, one may want to set the title/icon of dialogs according to the title/favicon of the web page that triggered it.

I think the event handler approach provides all the flexibility. We may add properties such as `browserWindow` (maybe `window` too for iframes) to the event object, so that developer can get all context info about the dialog to be shown.

**Comment by zcbenz** [comment]
For overriding the `alert` box you can simply do it in [preload](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) script:

```js
window.alert = ...;
```

That's also how we implemented `alert` in Electron:
https://github.com/atom/electron/blob/master/atom/renderer/lib/override.coffee#L78-L88

**Comment by alexindigo** [comment]
There is one difference between native and custom `alert` – custom one is not blocking, although it's better UX in most cases, might be a problem for some.

**Comment by etiktin** [comment]
@alexindigo, what do you mean when you say that custom `alert` doesn't block?
If you implement it using `dialog.showMessageBox()`, just don't provide a callback and the call will be synchronous/blocking. For `alert` it doesn't matter that match, but `confirm` must be synchronous because you need to return the result to the caller.

**Comment by alexindigo** [comment]
@etiktin Hey, sorry for the confusion, I missed that part completely. Thank you for the clarification.

**Comment by duanyao** [comment]
@zcbenz  preload script looks awesome, but how about browsing contexts that are not created by `new BrowserWindow(...)`, e.g. `window.open(), <a target="_blank">, <iframe>`, etc.?

**Comment by zcbenz** [comment]
@duanyao Good question, I can't find a existing way to solve that. One possible solution is allow setting preload script for the whole session, so ever page created for the session will load the preload script:

```js
var session = xxxx.createSession({preload: '/script.js'});
var window = new BrowserWindow({session: session});
```

How does it sound?

**Comment by duanyao** [comment]
Session may work.

Another (more general) solution is "browsing context life circle events", so you can inject different scripts to different pages, at different loading states (e.g. before parsing HTML, ondomcontentloaded, or onload). One example is [Geckofx](https://bitbucket.org/geckofx/geckofx-33.0/src/3e2c6436b414984328d4e3cbee6dedf5f09a9e9d/GeckoFxTest/Main.cs?at=default#Main.cs-355), it has `Navigating`, `Navigated`, `DocumentCompleted`, `CreateWindow` events, and you can retrieval the URL and call `EvaluateScript()` to inject scripts in the handlers.

I noticed that Electron class `WebContents` has `did-start-loading`, 'did-frame-finish-load', 'new-window' events and `executeJavaScript()`, seems potentially being able to achive this purpose?

**Comment by zcbenz** [comment]
> I noticed that Electron class WebContents has did-start-loading, did-frame-finish-load, new-window events and executeJavaScript(), seems potentially being able to achive this purpose?

We still need to add all those events to `Session` though, otherwise we can still not handle pages opened by `window.open`.

**Comment by duanyao** [comment]
>otherwise we can still not handle pages opened by window.open.

Doesn't `new-window` event report windows created by `window.open`?

**Comment by etiktin** [comment]
Currently there's no support for `alert` and `confirm` in iframes. The `preload` script for `Sessions` sounds like a good solution for customizing the dialogs, but I think we also need a default preload (kind of like what override.coffee does for the parent window).

Will this work even when `websecurity` is set to true and the child window(s) belongs to a different origin?

**Comment by zcbenz** [comment]
> Will this work even when websecurity is set to true and the child window(s) belongs to a different origin?

Yeah preload script is loaded regardless of web security, and child windows always have the same session.
