### ISSUE TITLE
Native menus large on high DPI Linux

### ISSUE THREAD

**Issue by niedzielski** [atom/electron#2523]
electron-v0.30.4-linux-x64.zip
Linux Mint 17.2

Menus are twice (or larger?) the size they should be. This includes the context menu in dev tools which occupies a very large area but I wasn't able to capture a shot of it.

![2015-08-18-19-43-27-483930021](https://cloud.githubusercontent.com/assets/1071806/9347056/e7fd4d8c-45e1-11e5-92b3-d3f23d229140.png)

I know there's been a ton of discussion about high DPI support. I apologize if this bug is a duplicate.

**Comment by niedzielski** [comment]
Just to be clear, it's not an overstatement to say that this makes most menus completely unusable. For example, in Atom I'm able to see a small portion of the first menu tier but all submenus opened are literally unnavigable.

**Comment by paulcbetts** [comment]
We're seeing this too on certain distros

**Comment by niedzielski** [comment]
I was able to capture a slightly more descriptive screenshot in Atom. The first tier of menus is almost unusable the second pops open but can't seem to hold anything.

![2015-08-31-10-47-48-854446950](https://cloud.githubusercontent.com/assets/1071806/9584389/23b6781c-4fce-11e5-9941-995f7c4339e9.png)

**Comment by zhulik** [comment]
I have the same issue, ArchLinux, Plasma desktop

**Comment by niedzielski** [comment]
If I set Gnome scaling to 1x (`gsettings set org.gnome.desktop.interface scaling-factor 1`), the native menus are properly sized but everything else is half sized. I wonder if this has to do with the way Linux Mint Cinnamon specifically handles interface scaling. Many other distros have half sized scrollbars and window decorations, even when setting Gnome scaling to 2x. Mint doesn't and I think that might be causing a problem with Electron.

**Comment by razvanz** [comment]
Same here on Arch Linux with Cinnamon/Gnome. I set gnome `scaling-factor 2` and the context menus are huge compared with non-electron apps. Mostly inconvenient when using Atom, the same case applies on the slack app (which is also build with electron).
