### ISSUE TITLE
Registering a global keyboard shortcut doesn't work if there's already a predefined global registration available on a given OS for a given accelerator.

### ISSUE THREAD

**Issue by bvahdat** [atom/electron#2527]
Given the [documentation code snippet](https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md#global-shortcut) if I try to register any global keyboard shortcut for the accelerator `F9` through `F12` on `OS X Yosemite 10.10.5` then my given `callback` will be not invoked on the key press as the given accelerator has got an already predefined shorcut-binding on `OS X`. But coding the same for, let's say `F8`, would work as `F8` has no predefined shortcut-binding before the app starts. Also interestingly [`globalShortcut.register()`](https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md#globalshortcutregisteraccelerator-callback) returns `true` in both cases, no matter if for `F8` (which works) or `F9` ... `F12` (which doesn't works). I've verified the same behaviour on `MS-Windows 7 & 8.1` as well.

Side note: For testing on `OS-X` I first did the 2-steps setup by [this article](https://support.apple.com/kb/PH13982?locale=en_US) as otherwise you can't verify the behaviour.

**Comment by zcbenz** [comment]
The normal APIs on each platform to register global hotkeys do not allow overriding other application's registered hotkeys (especially those used by the operating system), this is to reduce surprises to users and give your system peace (imaging apps scrambling for hotkeys).

Of course there are many ways to rob the hotkeys from other apps and even the operating system, but it makes us look like virus, and is bad anyway, so we are not going to do that.

**Comment by bvahdat** [comment]
Thanks for your feedback!

I do completely agree on this with you. Exactly because of the reasons you mentioned and also to avoid newbies like me to fall into this trap `globalShortcut.register()` should better throw an error in such cases instead of returning `true`. Don’t you think so?

**Comment by bvahdat** [comment]
Simply put, the API behaviour together with the current documentation made me to assume this should work.

**Comment by zcbenz** [comment]
Some platform's APIs do not consider hotkey taken as an error, we are just returning what we get from system APIs.
