### ISSUE TITLE
Ability to set app as default

### ISSUE THREAD

**Issue by marcus433** [atom/electron#2528]
If possible I believe it would be useful to allow electron developers to use LSSetDefaultHandlerForURLScheme to allow their app to be set as default for a given protocol. For example set the default email app for mailto:// etc.

**Comment by etiktin** [comment]
It seems there's some support for it at least for OS X. See #36.

**Comment by zcbenz** [comment]
I suggest writing a native module for this, it is independent from Electron's APIs and we can not add API for every platform feature.
