### ISSUE TITLE
Floating apps

### ISSUE THREAD

**Issue by sharedmit** [atom/electron#2530]
Is there a way to develop an app like spotlight using electron? 
Apps that float.
![spotlightsuggestionsyosemite](https://cloud.githubusercontent.com/assets/1515815/9377922/dea8abb0-4725-11e5-9acb-4e1b577be40c.jpg)

**Comment by jlord** [comment]
Do you mean positioning the application the center of the screen? Yep! :sparkles: 

- Here is `BrowserWindow.setPosition(x, y)` in the [Electron docs](http://electron.atom.io/docs/v0.30.0/api/browser-window/#browserwindow-setposition-x-y).
- Here is a module on npm to help, [`electron-positioner`](https://www.npmjs.com/package/electron-positioner).

**Comment by sharedmit** [comment]
Yep! that and you know no menu bar or toolbar, or is that the default in electron ?

**Comment by sharedmit** [comment]
And I also I think that one is for a browser.

**Comment by LeMoussel** [comment]
For no menu bar you can set `Menu.setApplicationMenu(null)`. Here is `Menu.setApplicationMenu(menu)`in the [Electron Docs](http://electron.atom.io/docs/v0.30.0/api/menu/#class-method-menu-setapplicationmenu-menu).

**Comment by sharedmit** [comment]
Thank you both @jlord & @LeMoussel !
