### ISSUE TITLE
Cannot see console log from webview

### ISSUE THREAD

**Issue by petrfelzmann** [atom/electron#2531]
_Electron v0.30.1 + Windows 8.1_
Let main window load such web page:
```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <webview src="webview.html"></webview>
</body>
</html>
```
The included webview.html can be:
```html
<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <script>
        console.log('foobar');
    </script>
</head>
<body>
    <p>Webview content</p>
</body>
</html>
```
When run this example I cannot see the 'foobar' message in dev tools' console window. It truly downgrade the debugging possibilities.

![webview-console](https://cloud.githubusercontent.com/assets/12231141/9378521/7135d1e6-4722-11e5-90e3-e2d0703a8119.png)

**Comment by petrfelzmann** [comment]
There is need to register [console-message](http://electron.atom.io/docs/v0.30.0/api/web-view-tag/#console-message) event, [thx to appelgriebsch](https://discuss.atom.io/t/cannot-see-console-log-from-webview/19974/3)! I'm closing the issue.

**Comment by arve0** [comment]
Link to current documentation: https://electron.atom.io/docs/api/webview-tag/#event-console-message
