### ISSUE TITLE
Memory not to be recovered. Using CSS3 filter or SVG feGaussianBlur

### ISSUE THREAD

**Issue by zg2013** [atom/electron#2534]
simulation IOS .
The chrome does not appear to be the case.
Frequent add / remove -webkit-filter:blur(3px), On multiple DOM nodes.
Memory is maintained at a very high level, and will not take the initiative to release.

use electron v0.30.4

If I did something wrong, I would give a suggestion, thank you.

![b539e116-410a-11e5-99e1-390623db16ab](https://cloud.githubusercontent.com/assets/5134292/9382151/9334d44c-4770-11e5-90e7-69c98e775661.png)

**Comment by zcbenz** [comment]
You already reported it at #2482.
