### ISSUE TITLE
[OSX] "Uncaught Error: ENOENT: no such file or directory, lstat '/index.js'", source: ATOM_SHELL_ASAR.js (118)

### ISSUE THREAD

**Issue by sebastianmenge** [atom/electron#2536]
hey everyone, 

i'm getting this error after starting the electron process.
using electron 0.30.4

"Uncaught Error: ENOENT: no such file or directory, lstat '/index.js'", source: ATOM_SHELL_ASAR.js (118)

i narrowed it down a bit already.
this warning shows up when building the app with webpack and target set to "atom"
a problem with the ndarray-fill package

WARNING in ../~/ndarray-fill/~/cwise/~/static-module/~/falafel/~/acorn/dist/acorn.js 
Critical dependencies:
1:478-485 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. 
Try to require the original source to get better results.
@ ../~/ndarray-fill/~/cwise/~/static-module/~/falafel/~/acorn/dist/acorn.js 1:478-485

if i dont require ndarray-fill anywhere the error in electron goes away but the app itself of course crashes here and there cause i need ndarray-fill in different places.

any ideas?

**Comment by zcbenz** [comment]
Can you provide a small demo app?

**Comment by zcbenz** [comment]
Closing until there is more information provided.
