### ISSUE TITLE
Local prebuilt binary vs global inconsistencies

### ISSUE THREAD

**Issue by Auxolust** [atom/electron#2539]
There appears to be an inconsistency in how electron apps are run between the local prebuilt binaries and the globally installed prebuilts. If I use 

    "%~dp0/node_modules/.bin/electron.cmd" .

Then everything works correctly, however if I use the global command via the electron-prebuilts 

    electron . 

Then the renderer side cannot require properly. I'm assuming this has to do with the current working directory. I don' believe it is an electron-prebuilt issue so much as an issue with the directory in which the executing electron.exe resides, but I could be wrong. Is there a way rather than using the locally installed prebuilt-electron package installed, or without packaging the app fully as an asar that I can get the equivalent to the local run that allows the renderer to require correctly?

**Comment by zcbenz** [comment]
Can you give a demo app that can show the problem?

**Comment by Auxolust** [comment]
```js
var app = require('app'),
    BrowserWindow = require('browser-window'),
    crashReporter = require('crash-reporter'),
    express = require('express');
var expressApp = express(),
    mainWindow = null,
    port = 8080;
crashReporter.start();

function retryServer()
{
    expressApp.listen(port, serverSuccessful)
        .on('error', retryServer);
}

function serverSuccessful()
{
    mainWindow = new BrowserWindow(
    {
        width: '800',
        height: '600',
        center: true,
        frame: false,
        'dark-theme': true,
        type: 'desktop',
        "node-integration": true,
        'web-preferences':
        {
            'allow-displaying-insecure-content': true,
            'allow-running-insecure-content': true
        }
    });
    mainWindow.loadUrl('http:localhost:' + port);
    mainWindow.on('closed', function()
    {
        mainWindow = null;
    });
}
app.on('window-all-closed', function()
{
    if (process.platform != 'darwin')
    {
        app.quit();
    }
});
app.on('ready', function()
{
    //..Load routes
    expressApp.listen(port, serverSuccessful)
        .on('error', retryServer);
});
```

You now cannot require in the render process if you use global electron, but you can if you use the local electron

**Comment by zcbenz** [comment]
You are loading a page with `http` protocol so Electron is not able to add your page's location to module search paths, because Node's module system only works for filesystems.

When you run a local Electron, the module system will automatically add its location to module search paths, which I think happens to include your page's location. The best way to fix this is to use preload script to add your page's location to module search paths:


```js
// preload.js
require('module').globalPaths.push(__dirname + '/node_modules');
```

**Comment by Auxolust** [comment]
Much appreciated , thank you.

**Comment by Auxolust** [comment]
Actually for anyone checking this thread later,you cannot use

require('module').globalPaths.push(__dirname + '/node_modules');

as this then messes up the require for electron modules, you need to use
the injected module object that already exists in the window context, so

module.paths.push(__dirname+'/node_modules');

**Comment by hermwong** [comment]
I'm running into this issue when I try to run my Electron app on Windows. The Electron app executes perfectly fine on OSX.

On Windows my Electron app isn't able to find the `gaze` node module which I've included in my [`index.html`](https://github.com/phonegap/phonegap-app-desktop/blob/0.2.0/www/index.html#L19) file.
