### ISSUE TITLE
Return NULL/undefined from api

### ISSUE THREAD

**Issue by mattotodd** [atom/electron#2540]
Say I have extended electron to have a new api endpoint with the following signature (example code):

    base::string16 LoadPlatformValue(const base::string16& identifier){
      wchar_t* value = GetValue(identifier);
      if(value == nullptr){
  	    // not set return empty string
  	    return base::string16(L"");;
      }
      return base::string16(value);
    }

Currently if value returns a null pointer, I return an empty string, because if i return the nullptr or NULL, electron just hangs and does not spit out an error, or return a value (running on the js side)

Is it possible to return null or undefined in this case?  Or is empty string my only option?

**Comment by deepak1556** [comment]
> Is it possible to return null or undefined in this case? Or is empty string my only option?

You can always modify/add converters to return desired v8 value, If you would like to return null or undefined for empty `base::string16`, can change your converter [here](https://github.com/atom/electron/blob/master/atom/common/native_mate_converters/string16_converter.h) to do so.

```
    if (val.empty())
      return v8::Null(isolate);
```

**Comment by zcbenz** [comment]
You can return `v8::Local<v8::Value>` directly in your function.
