### ISSUE TITLE
Make a frameless still moveable?

### ISSUE THREAD

**Issue by Somiac** [atom/electron#2541]
How can I make a frameless window still draggable so you can move it around the screen? And is there a way to select a specific element in the application to make it moveable? (for example my own designed taskbar)

**Comment by frankhale** [comment]
Have a look here:

https://github.com/atom/electron/blob/4e94e0c82f332b668241d8306f7359222c3dd760/docs/api/frameless-window-ko.md#draggable-region

**Comment by Somiac** [comment]
Electron is so beautiful, will this effect clicking on action items within the region?

**Comment by frankhale** [comment]
Mark those items as non draggable like this:

NOTE: This is mentioned in the doc I linked above.

```css
button {
  -webkit-app-region: no-drag;
}
```

**Comment by Somiac** [comment]
Thanks

**Comment by SaroarShahan** [comment]
> Mark those items as non draggable like this:
> 
> NOTE: This is mentioned in the doc I linked above.
> 
> ```css
> button {
>   -webkit-app-region: no-drag;
> }
> ```

Thanks a lot dude!
