### ISSUE TITLE
How do I change the name of the electron window?

### ISSUE THREAD

**Issue by Somiac** [atom/electron#2543]
At first tried changing just the menu,

```
    <script>
		var remote = require('remote');
		var Menu = remote.require('menu');
		var template = [
		  {
		    label: 'My App',
		    submenu: [
		      {
		        label: 'About my app',
		        selector: 'orderFrontStandardAboutPanel:'
		      },
		      {
		        type: 'separator'
		      },
		    ]
		  },
		];
		menu = Menu.buildFromTemplate(template);
		Menu.setApplicationMenu(menu);
	</script>
```

But the menu still shows "Electron". Also how do I change the entire app name to my app name? package.json has my app name, not sure where else to set this?

On a side note if I could get pointed in the right direction on changing the app icon.

I'm on OS X, and installed electron local to my working directory if that makes any difference.
Thanks!

**Comment by etiktin** [comment]
To change the default window title you can set the title option when creating the browser window (see details at https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions). If the htmls you are loading include a title tag, then that will change the title. You can prevent that by listening to 'page-title-updated' event and calling event.preventDefault() (see detsils at https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-page-title-updated).

There are details about rebranding in the docs. The simple way to achive this is to use the electron-packager node module. See https://www.npmjs.com/package/electron-packager).

**Comment by Somiac** [comment]
I had just tried the title option as shown below, and still nothing. (I don't have the title tag in my html page)

```
  mainWindow = new BrowserWindow({
    width: 300, 
    height: 500,
    title: "My App",
    frame: false,
    resizable: false,
    transparent: true,
  });
```

**Comment by etiktin** [comment]
It works for me on Windows. Maybe in OS X you have to change it in the plist. You can try the rebranding details for OS X. See https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md#os-x .

**Comment by Somiac** [comment]
Yup, tried that as well, doesn't seem to be working.. :/

**Comment by etiktin** [comment]
Did you try electron-packager?

**Comment by Somiac** [comment]
Not yet, still developing - just expected you could do all of this before packaging everything together.

**Comment by zcbenz** [comment]
Closing this since @etiktin has listed every related documents.

**Comment by Akshay-Thakare** [comment]
@Somiac you should set the title in the webpage. It will get reflected in the app title bar.

```
<!DOCTYPE html>
<html>
<head lang="en">
    <title>INSERT_TITLE_HERE</title>
```

**Comment by ScarletFloppy** [comment]
This should do the trick (at least it did for me (only tested on windows so far)):

`mainWindow.setTitle(require('./package.json').name);`

**Comment by hcano91** [comment]
@Akshay-Thakare 's is the right one.

**Comment by MattLangleyUK** [comment]
I appreciate this is old, but I had the same issue and the answers here didn't quite work.

**Comment by EddieOne** [comment]
The first answer isn't clear enough. Here's the secret sauce. :+1: :+1:

```
mainWindow.on('page-title-updated', function(e) {
  e.preventDefault()
});
```

**Comment by SwiTool** [comment]
> The first answer isn't clear enough. Here's the secret sauce. 👍 👍
> 
> ```
> mainWindow.on('page-title-updated', function(e) {
>   e.preventDefault()
> });
> ```

Yea I don't know why the title was updated, because I removed everything from the electron-webpack config, but still, by putting your code it works great.
Btw, it's not "how to change the window title" but "how to prevent the window title to be changed"

**Comment by roembol2000** [comment]
On macOS you should use an empty item at the beginning. here's how to do it:
`if(process.platform == 'darwin'){
    menuTemplate.unshift({});
}`

**Comment by NaClYen** [comment]
If use `loadURL()` to load page context that `BrowserWindow` will ignore the `title` property.

This is my solution:
```
mainWindow = new BrowserWindow({ ... });

const setWinTitle = () => {
  if (mainWindow) mainWindow.title = `my-app-${app.getVersion()}`;
  return true;
};

mainWindow
  .loadURL(`file://${__dirname}/index.html`)
  .then(setWinTitle)
  .catch((e) => console.error(e));
```

**Comment by preto89** [comment]
**Theres actually 3 places where Electron gets the app name**

> I would advice changing all to the same name instead of using just one, other systems might not get the name from the same one place.


1. manifest.json
```
{
  "short_name": "My App Name",
  "name": "Create React App Sample",
  "icons": [],
  "start_url": ".",
  "display": "standalone",
  "theme_color": "#ffffff",
  "background_color": "#ffffff"
}
```

2. electron.js
```
mainWindow = new BrowserWindow({ 
   title: "My App Name",
   width: 800,
   height: 800,
   minWidth: 800,
   minHeight: 800,
   backgroundColor: 'black',
});
```
3. index.html
```
<html lang="en">
   <head>
     <meta name="viewport" content="width=device-width, initial-scale=1" />
     <title>My App Name</title>
   </head>
   <body>
     <div id="root"></div>
   </body>
</html>
```

**Comment by renepardon** [comment]
> The first answer isn't clear enough. Here's the secret sauce. 👍 👍
> 
> ```
> mainWindow.on('page-title-updated', function(e) {
>   e.preventDefault()
> });
> ```

In combination with setTitle or the title attribute it works perfectly! So you can choose your weapon :)

**Comment by nguyentruongtoan1309** [comment]
> The first answer isn't clear enough. Here's the secret sauce. 👍 👍
> 
> ```
> mainWindow.on('page-title-updated', function(e) {
>   e.preventDefault()
> });
> ```

Now, let use app.on replace for mainWindow.on, this work for me

**Comment by K3yr0nym0us** [comment]
adding to the question...
Is it possible to change the title that the alerts show?
instead of saying "electron" say the name of the app?
![Screenshot 2023-03-08 195106](https://user-images.githubusercontent.com/99368098/223869366-f3b955a4-2dd3-401a-99ba-c8e6c84c5084.png)

**Comment by daviskoko** [comment]
Setting an empty label on the first menu item should fix it
`// Import the menu template from Angular
  const { template } = require('./menu-template');
  template.unshift({label: ''});`
