### ISSUE TITLE
Screen capture API is not working as expected

### ISSUE THREAD

**Issue by preco21** [atom/electron#2548]
I'm using [captureScreen](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowcapturepagerect-callback) API in renderer process.

But if API called before WebContents `did-finish-load` or `did-stop-loading` events, it's just make empty image. (I check only page with include image)

index.js:
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

var mainWindow = null;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {    
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    'use-content-size': true
  });
  
  mainWindow.setMenu(null);
  mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.focus();
});
```

index.html:
```javascript
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <img src="test.png">
        <script src="b.js"></script>
    </body>
</html>
```

b.js:
```javascript
var remote = require('remote');
var fs = require('fs');

var currentWebContents = remote.getCurrentWebContents();
var currentWindow = remote.getCurrentWindow();

/* NOT WORKING
window.addEventListener('load', function() {
    capturePage();
});

document.addEventListener('DOMContentLoaded', function() {
    capturePage();
});
*/

currentWebContents.on('did-finish-load', function() {
    capturePage();
});


function capturePage() {
    currentWindow.capturePage(function(image) {
        var buf = image.toPng();
        
        fs.writeFile('s.png', buf, function(err) {
          console.log(err);
        });
    });
}
```

It's bug? or expected(normal)?

**Comment by hokein** [comment]
I think this behavior is expected. 

Indeed, the API implementation relies on the `WebContents`, so you need to wait WebContents finishing all the loading stuff.

I think the `capturePage` API causes some misunderstood on developers, it'd be better to move it to `BrowserWindow.WebContents` space while keeping compatibility, @zcbenz how about your idea here?

**Comment by zcbenz** [comment]
The capturePage API can only capture the page after it has done loading, it is a limitation of Chromium so we won't fix it, we should probably make it in the documents though.

> I think the capturePage API causes some misunderstood on developers, it'd be better to move it to BrowserWindow.WebContents space while keeping compatibility, @zcbenz how about your idea here?

I'm :+1: on this, there are some other methods need to be moved too.
