### ISSUE TITLE
document.execCommand('insertText', text) not work

### ISSUE THREAD

**Issue by fritx** [atom/electron#2551]
I'm doing editor stuff
Both of `insertText` `insertHTML` won't work
All it performs is a `delete`
However, `selectAll` `cut` `copy` works
Any guys could help me out? :smiley: 
Neither of OSX 10.10 and Win 7 would work

**Comment by dkfiresky** [comment]
Maybe this can help:

```js
var remote = require('remote');
remote.getCurrentWebContents().copy();
remote.getCurrentWebContents().paste();
```

http://electron.atom.io/docs/v0.30.0/api/browser-window/#webcontents-copy
http://electron.atom.io/docs/v0.30.0/api/browser-window/#webcontents-paste

**Comment by fritx** [comment]
@dkfiresky looks like [WebContents.replace(text)](http://electron.atom.io/docs/v0.30.0/api/browser-window/#webcontents-replace-text), i'll try soon

**Comment by fritx** [comment]
oops i'm sorry.. it should be `document.execCommand('insertText', false, text)` instead
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by nafees55** [comment]
> oops i'm sorry.. it should be `document.execCommand('insertText', false, text)` instead
> https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

it's working.
