### ISSUE TITLE
[OSX] Frameless, not-resizable window has wrong size

### ISSUE THREAD

**Issue by kasoki** [atom/electron#2552]
When you try to create a frameless and not-resizable window with a specific size, Electron won't open it with the specified size (It's a bit bigger).

Example:

app.js

    var app = require('app');
    var BrowserWindow = require('browser-window')

    var win = null;

    app.on('window-all-closed', function() {
        app.quit();
    });

    app.on('ready', function() {
        win = new BrowserWindow({
            frame: false,
            resizable: false,
            width: 1024,
            height: 600
        });

        // and load the index.html of the app.
        win.loadUrl('file://' + __dirname + '/index.html');

        win.on('closed', function() {
            win = null;
        });
    });

index.html

    <!doctype html>
    <style>
        body {
            background-color: yellow;
        }

        .test {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 1024px;
            height: 600px;

            background-color: pink;
        }
    </style>

    <div class="test">

    </div>

The window should be completely pink but as you can see in this screenshot the background also appears: ![wrong size](https://monosnap.com/file/ZkjsewrEIR5fVKix0RJsEHVbyYkHCl.png)

According to document.documentElement.clientHeight the current height is 622px.

I'm running this on OS X 10.10.4 and Electron v0.30.4

**Comment by photonstorm** [comment]
Just to say that I see this happen on Windows too (Electron v0.30.4) only in this case I get vertical and horizontal scroll bars appearing. It happens regardless if I have set `resizeable` or `auto-hide-menu-bar` - it seems to be getting some extra padding from somewhere not in the html file.

**Comment by sircharleswatson** [comment]
I'm noticing this as well. if I make a 100x100 window, it definitely comes up as a rectangle rather than a square.

**Comment by hokein** [comment]
If we remove `resizable` field in creating `BrowserWindow`, it works as expected.

**Comment by leshow** [comment]
also getting this bug on mac, I have a hack workaround while this is getting fixed:

- set resize: true
- in main.js/index.js:
```javascript
mainWindow.on('resize', function(e) {
e.preventDefault();
mainWindow.setContentSize(origW, origH);
});
```

it's a dirty hack I'd prefer not to do, hopefully this bug is fixed soon.

**Comment by smebberson** [comment]
I'm also getting this bug...
