### ISSUE TITLE
[OSX] Strange constraint error

### ISSUE THREAD

**Issue by ducky427** [atom/electron#2555]
Hi,
I am using Electron v0.30.5 on Mac OSX 10.10.5. 

I have a complex electron app and on one page, on a button press, a dialog window is launched. When that happens, I get the following in the terminal from where the app is launched. The app itself doesn't crash. But this warning is printed:

```
2015-08-22 00:00:36.149 Electron[97698:1317067] Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7f93028f3e30 h=--& v=--& V:[FI_TBrowserBackgroundView:0x7f93006b80b0(0)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f93028d3770 h=-&- v=-&- V:|-(0)-[FI_TListScrollView:0x7f9305027b90]   (Names: '|':FI_TBrowserBackgroundView:0x7f93006b80b0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f93028d3720 h=-&- v=-&- V:[FI_TListScrollView:0x7f9305027b90]-(0)-|   (Names: '|':FI_TBrowserBackgroundView:0x7f93006b80b0 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f93028f5080 h=-&- v=-&- V:[NSClipView:0x7f93005955c0]-(15)-|   (Names: '|':FI_TListScrollView:0x7f9305027b90 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f93028f5030 h=-&- v=-&- V:|-(0)-[NSClipView:0x7f93005955c0]   (Names: '|':FI_TListScrollView:0x7f9305027b90 )>"
)

Will attempt to recover by breaking constraint
<NSAutoresizingMaskLayoutConstraint:0x7f93028f5080 h=-&- v=-&- V:[NSClipView:0x7f93005955c0]-(15)-|   (Names: '|':FI_TListScrollView:0x7f9305027b90 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
```

I am coming back to this project after a while and the strange thing is I don't remember seeing this warning a while back. Could it be that updating to OS X 10.10.5, which was released on 13th August, has caused this issue?

Thanks!

**Comment by zcbenz** [comment]
What's the type of the dialog? Is it a open dialog, save dialog, or a message box? And can you reproduce this reliably?

**Comment by ducky427** [comment]
I can reproduce this reliably from within my app. Its an open dialog.

**Comment by zcbenz** [comment]
I think it is a bug of OS X 10.10:
https://www.google.com/search?client=safari&rls=en&q=Unable+to+simultaneously+satisfy+constraints&ie=UTF-8&oe=UTF-8#q=%22Unable+to+simultaneously+satisfy+constraints%22+FI_TBrowserBackgroundView+FI_TListScrollView&start=0

**Comment by ducky427** [comment]
I've managed to create a minimal example which reproduces this issue in this [gist](https://gist.github.com/ducky427/684650e33b519775a298).

All I did was take the example in the [Quick Start Guide](https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md) and add a menu with a menu item which opened a open dialog.

**Comment by zcbenz** [comment]
I tried that example on 10.10.5 but can not reproduce, it seems to be machine-dependent.

**Comment by ducky427** [comment]
bummer. thanks!

**Comment by ducky427** [comment]
I don't have these issues on the latest OS X 10.11 GM.
