### ISSUE TITLE
[OSX] Loading bounce?

### ISSUE THREAD

**Issue by wisesascha** [atom/electron#2560]
We currently have an API for bouncing the dock in an informational event, but it would great to let user know that the app is still loading and not just broken.

**Comment by jlord** [comment]
Do you mean to use the icon bounce in place of a loading spinner?

**Comment by aackerman** [comment]
This already exists, https://github.com/atom/electron/blob/master/docs/api/app.md#appdockbouncetype

**Comment by zcbenz** [comment]
Any screenshot that can show what you want?

**Comment by wisesascha** [comment]
This is an example. The icon only stops bouncing once the window has loaded fully. http://d.pr/i/1dAQZ

**Comment by zcbenz** [comment]
You can pass "critical" to `dock.bounce`.
