### ISSUE TITLE
Electron doesn't work on OSX when unzipped on windows and copied to Mac.

### ISSUE THREAD

**Issue by s-oram** [atom/electron#2561]
Electron doesn't work on OSX when unzipped on windows and copied to Mac. 

#### Steps to reproduce

1) Download electron-v0.31.0-darwin-x64.zip from https://github.com/atom/electron/releases
2) Unzip on Windows 7.
3) Copy files to OSX. Version 10.9.5
4) Attempt to open the default Electron application. **ERROR**
 App doesn't open and error message is shown. 

```
Process:         Electron [400]
Path:            /Volumes/*/Electron.app/Contents/MacOS/Electron
Identifier:      com.github.electron
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [150]
Responsible:     Electron [400]
User ID:         501

Date/Time:       2015-08-23 13:05:21.552 +1000
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  73F8EA31-601A-B94A-5D65-330F6D8889EA

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Volumes/*/Electron.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Volumes/OSX Share/electron-v0.31.0-darwin-x64 - Copy/Electron.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

Binary Images:
    0x7fff6c43b000 -     0x7fff6c46e817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld

Model: Macmini5,1, BootROM MM51.0077.B10, 2 processors, Intel Core i5, 2.3 GHz, 16 GB, SMC 1.76f0
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 512 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1333 MHz, 0x8502, 0x505341333847313333333253000000000000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1333 MHz, 0x8502, 0x505341333847313333333253000000000000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 4.2.7f3 14616, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: TOSHIBA MK5065GSXF, 500.11 GB
USB Device: Hub
USB Device: Cruzer Facet
USB Device: IR Receiver
USB Device: Hub
USB Device: USB Optical Mouse
USB Device: USB Keyboard
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
FireWire Device: SAFFIRE_PRO_24, Focusrite, Up to 400 Mb/sec
Thunderbolt Bus: Mac mini, Apple Inc., 22.2
```

I'm not the first to run into this problem. https://discuss.atom.io/t/dont-work-with-mac-osx-10-9-2/6019/6

### Another related problem.

1) Download electron-v0.31.0-darwin-x64.zip from https://github.com/atom/electron/releases
2) Unzip on OSX using the default Archive utility. 
3) Run default Electron app. It works as expected. 
4) Copy files to Windows.
5) Make a copy of the those files on Windows.
6) Copy the new files back to OSX. 
7) Attempt to run the default Electron app. **ERROR** Same error message as above.

After copying the Electron files on Windows, some files have different sizes. (Checked using Beyond Compare).

Original 0 bytes.
Copied 61,432,200 bytes.
` Electron.app/Contents/Frameworks/Electron Framework.frameword/Electron Framework`

Original 0 bytes.
Copied 4,096 bytes.
` Electron.app/Contents/Frameworks/Electron Framework.frameword/Resources`

![2015-08-23_13h22_46](https://cloud.githubusercontent.com/assets/1150429/9426796/07ea035e-499a-11e5-95e8-2e59dd9a4041.png)

**Comment by paulcbetts** [comment]
Win7 doesn't respect symlinks in zip files so it won't work.

**Comment by s-oram** [comment]
Thanks Paul. Are there any known workarounds?

**Comment by paulcbetts** [comment]
> Are there any known workarounds? 

Don't do that :)

> Is this noted in the documentation anywhere?

No, but this is true with most (all?) OS X Applications, this is not unique to Electron

**Comment by s-oram** [comment]
> Don't do that :)

Fair enough. :) 

> No, but this is true with most (all?) OS X Applications, this is not unique to Electron

I'm very new to working with OS X. Probably another dumb question: My OS X application runs independently of Electron. Would it be reasonable for my application to re-create the symlinks before starting Electron?

**Comment by paulcbetts** [comment]
> My OS X application runs independently of Electron.

I'm not sure what you mean by this, can you explain?

**Comment by s-oram** [comment]
My application is split into two parts. A backend HTTP server with no GUI and a frontend Electron app that works as a client. The user starts the backend server, then the backend launches the frontend automatically. I've split the application up this way because I wanted to use Go for the backend. I would've built the GUI with Go as well but couldn't find a mature crossplatform GUI library I liked the look of. 

Would it be feasible for the backend server to recreate any required symlinks before launch the Electron based GUI?

**Comment by Jmales** [comment]
s-oran, I'm having the same problem as you when building an Electron App for MacOS 10.10.
Did you manage to solve this?

**Comment by s-oram** [comment]
Hi Jmales, Sorry for the slow reply. I didn't end up fixing it. I moved away from using Electron for the time being. It's possible recreating the symbolic links on OSX as part of the install step would side-step the problem.

**Comment by jadedResearcher** [comment]
I'm running into this too, is there any fix at all? Is there just no way to make a mac application on a windows machine?

**Comment by brenca** [comment]
Since this is an OS limitation, I don't think there is (or going to be) a fix/workaround.

**Comment by nornagon** [comment]
Theoretically it would be possible to do this by creating the zip file from in-memory data rather than off the filesystem. See e.g. https://github.com/archiverjs/node-compress-commons/pull/23 which adds symlink support to `compress-commons`. That'd be a fairly involved task though.
