### ISSUE TITLE
Support `index.js` module resolution

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#2567]
According to the Node.js [module resolution](https://nodejs.org/api/modules.html#modules_folders_as_modules) I should be able to have `index.js` file and not need to specify a `main` field in package.json:

> If there is no package.json file present in the directory, then node will attempt to load an index.js or index.node file out of that directory.

I use this convention in all my node modules, but it doesn't seem to work with Electron.

The app entry file is named `index.js` and if I have the following in  `package.json`:

```
{
  "main": "index.js"
}
```

...it works, but if I remove the `main` field I get the following error message in a (non-asar) packaged OS X app:

<img width="532" alt="screen shot 2015-08-24 at 13 56 50" src="https://cloud.githubusercontent.com/assets/170270/9434654/3782cd68-4a6b-11e5-9a39-dc03b61e1108.png">

-

To package the app I just took the default Electron app and put a `app` folder in the `Resources` folder and added `index.js` and the above `package.json` file, according to the [Application distribution](http://electron.atom.io/docs/v0.31.0/tutorial/application-distribution/#application-distribution) docs.

-

Electron 0.31.0. OS X 10.10.5.

**Comment by hokein** [comment]
From my point, it's not related to node's require mechanism, instead, this is more like a way of Electron startup. The `package.json` tells your app details(e.g. name, version) and the entry js file location(in `main` field).

**Comment by sindresorhus** [comment]
@hokein Electron is using package.json and should follow the convention. I don't see any downside in supporting this. I personally find `index.js` much clearer as I can see the entry point of the app when browsing the filesystem instead of having to open `package.json` and look at the `main` field.

**Comment by hokein** [comment]
Oh, I have some misunderstandings on it. It sounds reasonable.
