### ISSUE TITLE
Getting Started Question

### ISSUE THREAD

**Issue by mindware** [atom/electron#2572]
The Getting Started guide suggests that once electron-prebuilt is installed globally, one can simply cd into the desired directory and execute the following and the application should start: 

electron . 

The issue im finding is that on my OSX Yosemite installation, doing so results in 'Error opening app', 'Cannot find module <PATH to app>'. If I simply do:

electron main.js 

It runs. Am I missing something? Thanks in advance.

**Comment by etiktin** [comment]
Do you have a package.json in that directory?
Does it have a `main` key pointing to main.js?

**Comment by zcbenz** [comment]
The [forum](https://discuss.atom.io/c/electron) is a better place for questions.

**Comment by mindware** [comment]
Thanks. That was the issue, @etiktin. Fixed.

**Comment by etiktin** [comment]
You're welcome :)
