### ISSUE TITLE
Windows 10: app.setUserTasks not working

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2573]
I am using Electron 0.31.0 and set a simple user task to the standard electron app like this:

```javascript
app.setUserTasks([
	{
		title: "New Window",
		program: 'C:\\Program Files (x86)\\Sublime Text 3\\sublime_text.exe'
	}
]);
```

While I see the sublime icon showing up in the task bar, it does not open on click.

**Comment by paulatbipsync** [comment]
We are also seeing this problem
On Windows 7 the task functions as expected
