### ISSUE TITLE
Memory leak calling native methods

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2575]
For us this shows up with the getCursorScreenPoint method as we poll it to find when the users mouse position is at the edge of the screen. However every time the method is called it leaks a non-insignificant amount of memory.

I've put together a demo here: https://github.com/speak/electron-bug-demos/tree/get-cursor-screen-point-memory-leak - simply run the app and watch the memory usage shoot up. This is what the usage in timeline looks like:

![image](https://cloud.githubusercontent.com/assets/380914/9453499/6a7e2a22-4a80-11e5-8141-d5cb4a4b2206.png)

The core code is simply:

```javascript
this.interval = setInterval(function(){
  var screen = require('screen');
  var point = screen.getCursorScreenPoint();
  console.log(point.x, point.y);
}, 10);
```

Hopefully someone can point out something stupid I'm doing - I'd prefer that to this being a real bug :wink:

**Comment by OlsonDev** [comment]
Just curious, does it still leak if you move the `var screen = require('screen')` before the `setInterval` call?

**Comment by tommoor** [comment]
@OlsonDev yes, same pattern of upwards memory usage. However for some reason if you require screen immediately then the getCursorScreenPoint method doesn't exist so you'd need to change it to something like:

```
setTimeout(function(){
  var screen = require('screen');
  
  setInterval(function(){
    var point = screen.getCursorScreenPoint();
    console.log(point.x, point.y);
  }, 10);
}, 1000);
```

**Comment by paulcbetts** [comment]
@tommoor You're getting trolled by `window.screen`, try calling it `atomScreen`

**Comment by OlsonDev** [comment]
AFAICT, he's not getting trolled by `window.screen`. Inside the function passed to `setTimeout`, he's creating a local called `screen` that doesn't bleed to `window`.

**Comment by thesbros** [comment]
@OlsonDev I believe @paulcbetts is talking about this part:
> However for some reason if you require screen immediately then the getCursorScreenPoint method doesn't exist

**Comment by OlsonDev** [comment]
Sure, I guess I assumed @tommoor was even still within some sort of closure considering he was doing `this.interval = ` ... rarely do I see people use `this` when they mean `window` or `global`.

**Comment by thesbros** [comment]
Can confirm on Arch Linux, Electron v0.31.0 with the original post's code or the following code:
```js
var atomScreen = require("screen");
setInterval(function()
{
	var point = atomScreen.getCursorScreenPoint();
	console.log(point.x, point.y);
}, 10);
```

Ran both for about ~5 minutes, each increased by about 1-2MB every second. Perhaps it has something to do with calling the method inside of an interval?

**Comment by tommoor** [comment]
@thesbros personally - I think it's holding onto a reference of the closure everytime that the remote method is called. In one of my memory heaps I saw many references to handleApiCall but not sure if that's a clue or red-herring..

**Comment by tommoor** [comment]
One last note, the same code running in the main process in an interval does not continuously raise memory usage in the same way so there is most likely something in the RPC methods that is leaky, although I haven't tested all of the different API's it could many / them all.

**Comment by zcbenz** [comment]
`require('screen')` in renderer process is equivalent to `require('remote').require('screen')`, so a faster way to reproduce this is:

```js
var w = require("remote").getCurrentWindow();
for (var i = 0; i < 50000; ++i)
  w.getBounds();
```

I can confirm JS heap is increasing, but by snapshotting the JS heap everything looks normal, it says there is nothing taking so much memory. So I tracked the destructors of the C++ objects, since every object tracked by `remote` has a corresponding C++ object tracking its lifetime, I can easily track whether those objects have been destroyed. And the results showed that every object returned by `remote` has been successfully garbaged collected.

So I'm wondering whether the way we track remote objects has prevented V8 from collecting memory from heap, because when `remote` module returns normal data that its lifetime is not tracked, the memory usage is quite normal:

```js
var w = require("remote").getCurrentWindow();
for (var i = 0; i < 50000; ++i)
  w.getSize();
```

**Comment by tommoor** [comment]
Thanks @zcbenz :smile: - any chance of a 0.30.7?

**Comment by zcbenz** [comment]
> any chance of a 0.30.7?

Unlikely, the patch is too big, backporting is not very easy.
