### ISSUE TITLE
OS X: Clicking tray icon quickly several times causes context menu to stop opening

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#2580]
I noticed that on OS X, clicking the tray icon quickly several times sometimes does not open the context menu. One can then continue clicking the icon, and the highlight and pressed image will toggle, but no tray menu will show at all, except the pressed image is shown when there is no highlight (and vice versa).

I did not attach any click listeners.

Here is a screenshot taken of the tray icon after clicking several times, the icon is highlighted but no context menu is shown, and the pressed image is not used as it should be. It remains in this state even after clicking elsewhere and focusing another application in the OS.

![image](https://cloud.githubusercontent.com/assets/413206/9461223/262ecbfa-4b0d-11e5-9ff0-56b8987842f3.png)

**Comment by jorangreef** [comment]
Other native tray icons toggle the context menu correctly, even after many successive clicks.

**Comment by hokein** [comment]
> clicking the tray icon quickly several times sometimes does not open the context menu. 

If clicking the tray icon too quickly, it will be regarded as `double-click` event, which explains why the context menu is not shown. I think it cannot be fixed due to the limitation of current implementation.

> Here is a screenshot taken of the tray icon after clicking several times, the icon is highlighted but no context menu is shown, and the pressed image is not used as it should be. It remains in this state even after clicking elsewhere and focusing another application in the OS.

Which OS X version are you using? I could not reproduce it on OS X 10.10.4, even I clicked the tray icon many times.

**Comment by jorangreef** [comment]
Thanks for your help @hokein.

> If clicking the tray icon too quickly, it will be regarded as double-click event, which explains why the context menu is not shown. I think it cannot be fixed due to the limitation of current implementation.

It would be great if Electron could then still keep the highlight and pressed icon in sync. That is, if a double-click event happens, the icon should not be highlighted and should not display the pressed icon.

I am using OS X 10.10.5. I just need to click the tray icon very quickly a few times to reproduce it easily.

**Comment by jorangreef** [comment]
Just to add, sometimes when I reproduce it, the pressed icon and highlight is shown, but without the context menu. Here is another screenshot:

![image](https://cloud.githubusercontent.com/assets/413206/9463547/8a3ffed8-4b1d-11e5-9352-6ca9be565c35.png)

**Comment by jorangreef** [comment]
Here is another screenshot, where clicking the tray icon again after the previous screenshot, causes the menu to show, but now the pressed image is not used as should be the case (should be a white plus).

![image](https://cloud.githubusercontent.com/assets/413206/9465657/bc38f780-4b2e-11e5-84df-2e5f6a3b950c.png)

**Comment by jorangreef** [comment]
Here it is again in another state, this time not pressed but highlighted.

**Comment by jorangreef** [comment]
Clicking again, and now the menu shows with highlight and correct pressed image:

![image](https://cloud.githubusercontent.com/assets/413206/9465680/01cc9c34-4b2f-11e5-80a3-3f8655a177c4.png)

**Comment by jorangreef** [comment]
Thanks @zcbenz and @hokein!
