### ISSUE TITLE
Textarea placeholder rendering bug

### ISSUE THREAD

**Issue by MichaelOstermann** [atom/electron#2581]
First of all, thank you a lot for this tool, it's been awesome so far! :)

I noticed a little bug regarding textarea placeholders, they always stay visible for me on focus. I also tried removing all CSS that I had, to see if something there was causing the bug, but with no success. I have nothing else that modifies properties of the textarea element.

![screen shot 2015-08-25 at 10 14 51 2](https://cloud.githubusercontent.com/assets/7288490/9462186/3b62f080-4b14-11e5-97c9-827d819c7bc5.png)

If anybody else has this issue, you can circumvent this with something like:

```css
textarea:focus::-webkit-input-placeholder {
    opacity: 0;
}
```

**Electron version:** 0.31.0
**OS:** OS X Yosemite 10.10.2

**Comment by zcbenz** [comment]
Can you give a full html page? You probably want to try if you can reproduce it in Chrome 44.

**Comment by MichaelOstermann** [comment]
It works fine in all browsers including Chrome 44, as for the full html page, you can literally just write a single `<textarea placeholder="example"></textarea>` in the index.html provided by you and the bug can be observed there!

**Comment by OlsonDev** [comment]
Windows 10, fresh download of 0.31.0, modified default app:

![textarea placeholder rendering bug](https://cloud.githubusercontent.com/assets/308072/9471366/8d817354-4b15-11e5-9405-f9e83fb3da74.gif)

**Comment by MichaelOstermann** [comment]
Originally I received this bug report from another mac user, tried it out myself and was able to reproduce, I've just tried it now again on a third mac and it works there - the 2 macs where this bug happened are Macbook Pro Retina models, on an iMac it works - sorry if I was supposed to add that info at the beginning :)

**Comment by zcbenz** [comment]
Can you provide a full html page that we can test? At least your screenshot is not a simple `<textarea placeholder="example"></textarea>`.

**Comment by MichaelOstermann** [comment]
Sure, here's the result of a styled textarea and a raw one, this is what I got on the two tested Retina models:

![screenflow](https://cloud.githubusercontent.com/assets/7288490/9488421/43d665be-4bda-11e5-9a68-f0aa3136b786.gif)

And my html for this was:

```html
<html>
<head>
  <title>Electron</title>
  <style>
    body {
        background-color: #ECF2F5;
    }
    textarea.styled {
        -webkit-appearance: none;
        border: 1px solid #ced5d9;
        color: #454a4c;
        padding: 10px;
        text-rendering: optimizeLegibility;
        box-sizing: border-box;
        line-height: 1.4;
        resize: none;
    }
    textarea.styled:focus {
        outline: none;
        border-color: #00aaff;
    }
    </style>
</head>
<body>
  <textarea class="styled" placeholder="example placeholder"></textarea>
  <br>
  <textarea placeholder="example placeholder"></textarea>
</body>
</html>
```

**Comment by zcbenz** [comment]
Hmm I can not reproduce on my machine, seems to be a machine-dependent bug.

**Comment by MichaelOstermann** [comment]
Did you try it on a non-retina? It worked for me on a non-retina machine yesterday

**Comment by zcbenz** [comment]
No, I can not find a non-retina machine. But I'm not sure I can fix it even if I can reproduce it, the rendering code is on Chromium's side and it is really hard to find out the cause.

**Comment by OlsonDev** [comment]
I tried it on a rMBP and could not reproduce, placeholders behaved properly. Unfortunately, the non-Retina MBP I found couldn't be upgraded past OS X 1.6.8 because it sports a Core 2 Duo. Electron requires OS X 10.8.

**Comment by MichaelOstermann** [comment]
Then it's probably not worth it to make a deeper investigation since this can be easily fixed with css - perhaps you could do a section in the docs for possible minor issues like this one?

**Comment by zcbenz** [comment]
Does it still occur on >= v0.32.x?

**Comment by MichaelOstermann** [comment]
I checked on 0.32.0 and 0.33.0, the bug does not occur in both versions anymore!

**Comment by zcbenz** [comment]
:sparkles:
