### ISSUE TITLE
Windows: running electron.exe with invalid app results in left over gpu process

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2583]
- download electron 0.31.0
- rename default_app to default_app2
- run electron.exe

=> you get a nice dialog telling that the app is invalid

Open process explorer to find the electron.exe process still around together with the gpu proces.

=> should terminate the app once you dismiss the dialog.

**Comment by iamdriz** [comment]
I've also noticed this when Electron applications crash or throw exception errors.

**Comment by iamdriz** [comment]
This issue also prevents the application from being open again until you manually close those leftover processes.

**Comment by iamdriz** [comment]
@zcbenz What if the app unexpectedly quits or has an error that doesn't throw the invalid app error? The process is still left in these scenarios.
