### ISSUE TITLE
OS X: Max Files Limit

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#2584]
I updated my system-wide max files limit on OS X via a plist in Library/LaunchDaemons to be 10240, and have confirmed this using `launchctl limit`.

But I found Electron is still getting EMFILE at around 1024 descriptors.

I think this behavior is inherited from Chrome, which is blindly setting its own limit, probably with the intention of increasing the very low usual 256 limit on Mac OS X, but now actually getting something less than the system limit.

Would it be possible to increase it to 10240 or provide a function to change the ulimit on OS X or Linux? I would not like to have to bundle a native add-on with Electron to do this, and Node.js does not yet provide access to the posix methods for changing ulimit.

**Comment by etiktin** [comment]
There's a module that mitigates the issue called [graceful-fs](https://www.npmjs.com/package/graceful-fs).

**Comment by deepak1556** [comment]
@jorangreef Is an api really required for this or does `graceful-fs` solves your issue ?

**Comment by jorangreef** [comment]
No, my use-case is a hash table database which needs to have more than 1000+ files open by design at times until compaction catches up. I think there is actually an outstanding issue with graceful-fs and Electron in any event.

The best would be for Electron to just set it to MAX(system limit, 1024).

**Comment by etiktin** [comment]
The issue with graceful-fs not working on io.js was resolved a couple of months ago, so it should work with Electron.
If you try to open lots of files together, but you let them close once you read them, then graceful-fs could solve the issue for you. If you need to keep all of them open at the same time, then it won't work for you. You could also just test it and see if it solves the issue for you.

In any case it seems that @deepak1556, is adding an API to change the limit.

**Comment by jorangreef** [comment]
Thanks @deepak1556 and @etiktin yes, I need to keep them all open at the same time. It's only in the presence of sustained writes and then the number of open file descriptors drops.
