### ISSUE TITLE
os.release reports incorrect version in Windows 10

### ISSUE THREAD

**Issue by mnemotiv** [atom/electron#2586]
electron v0.31.0

follow these to resolve:
https://github.com/nodejs/node/pull/2332
https://github.com/nodejs/node/pull/2347

**Comment by mnemotiv** [comment]
Seems like already done by: https://github.com/atom/node/commit/07a88b0c8b0ae678d4eac365716d23678d63fa64

But still an existing issue regarding by (workaround ideas): https://github.com/joyent/node/issues/25896

**Comment by mnemotiv** [comment]
Workaround:
```
var osRelease = function() {
  if(process.platform !== 'win32') {
    return os.release();
  }
  
  var matchVersion = child_process.execSync('ver.exe', { encoding: 'utf8', timeout: 10000 }).match(/([\d-.])+/g);
  
  return matchVersion[matchVersion.length - 1];
};

**Comment by zcbenz** [comment]
@mnemotiv We are not using Node's manifest file in Electron, I think that's why it is reporting wrong version here. I'll port that patch and thanks for finding the fixes!
