### ISSUE TITLE
Strange behavior when retrieve the position (X,Y) of an HTML element

### ISSUE THREAD

**Issue by LeMoussel** [atom/electron#2587]
OS : Win 7
Electron : 0.30.4 

In main process, main.js file is like this 
```javascript
app.on('ready', function() {
    var preloadJS = __dirname + '/preload.js'
    mainWindow = new BrowserWindow({width: 800, height: 600, preload: preloadJS});
    
    // Hide the menu bar, but allow it to be brought up by pressing `alt`.
    mainWindow.setMenuBarVisibility(false);
    mainWindow.setAutoHideMenuBar(true);
  
    mainWindow.openDevTools();

    mainWindow.loadUrl('http://www.actuino.fr')

    mainWindow.webContents.on('did-finish-load', function() {
       mainWindow.webContents.executeJavaScript('Test()')
    });
  
    mainWindow.on('closed', function() {
       mainWindow = null;
    });
});
```
In rendered process, preloadJS.js file, is like this 
```javascript
function getOffset( el ) {
    var _x = 0;
    var _y = 0;
    while( el && !isNaN( el.offsetLeft ) && !isNaN( el.offsetTop ) ) {
        _x += el.offsetLeft - el.scrollLeft;
        _y += el.offsetTop - el.scrollTop;
        el = el.offsetParent;
    }
    return { top: _y, left: _x };
};
    
Test = function() {
    for (var i=0; i<document.links.length; i++) {
        var coords = getOffset(document.links[i]);
        console.log(document.links[i].href + ' top:' + coords.top + ' left:' + coords.left);
    }
};
```
When running main.js, some links have top and left values positioned to 0.
If I copy preloadJS.js code in Electron console, when I execute Test() function  all links have top and left set to some values (but not 0)

I don't see why some links have top and left values set to 0 when running script?

**Comment by zcbenz** [comment]
What if you put this in your preload script?

```js
window.onload = function() { Test(); }

**Comment by LeMoussel** [comment]
Same results. Some links have top and left values positioned to 0.

`[6200:0826/084044:INFO:CONSOLE(16)] "005b – Programmer un USBASP sous Arduino => http://www.actuino.fr/tutos/usbasp/005b-programmer-usbasp", source: C:\Electron\Test\PreLoad\preload.js (16)
[6200:0826/084044:INFO:CONSOLE(17)] "    coords =>  top:0 left:0", source: C:\Electron\Test\PreLoad\preload.js (17)`

In console Electron windows, run `Test()`, obtain this result 
![electron](https://cloud.githubusercontent.com/assets/1816573/9487180/98014d4e-4bcf-11e5-8bf7-ea392a473d3c.png)

**Comment by zcbenz** [comment]
What if you put that code in your page? Like in the script tag in `<head>`.

**Comment by LeMoussel** [comment]
I'm not the page owner, I can't modify it.

But in Electron windows, if i click on 'Accueil', this page is reloaded, `Test()` function is re-executed and all links have top and left set to some values (not 0). Bizarre, bizarre .....

**Comment by zcbenz** [comment]
On some pages the positions of elements are modified after page is loaded, a common way in web pages is to wait for page to get loaded and then use JavaScript to dynamically position the elements to certain positions, so by the time `Test()` is executed the elements may do have 0 positions. And due to the nature of browser cache, whether the elements may have been positioned when `Text()` is called is really uncertain.

Since we can't really be certain it is a bug of Election, and in most cases it is not because rendering of page is on Chromium's side, I'm closing this.

**Comment by LeMoussel** [comment]
Hummm ... I'm not sure. Strange ....
I wait 10 sec with window `setTimeout()` method before to call `Test()` and some links have 0 positions.

**Comment by LeMoussel** [comment]
If use [<webview>](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md) like this code, this seems correct. Links elements have positions.

**main.js**
```javascript
var app = require('app');
var BrowserWindow = require('browser-window'); 

var mainWindow = null;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1200, height: 800});
  mainWindow.loadUrl(__dirname + '/index.html');
  mainWindow.on('closed', function() { mainWindow = null; });
});
```
**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="index.js"></script>
  </head>
  <body>   
  </body>
</html>
```
**index.js**
```javascript
document.addEventListener("DOMContentLoaded", function() {
	var webview = document.createElement('webview');
	webview.addEventListener('did-finish-load', onWebViewLoaded);
    webview.addEventListener("dom-ready", function(){ webview.openDevTools(); });
    webview.addEventListener('console-message', function(e) { console.log(e.message); });
	webview.src = 'http://www.actuino.fr/';
    webview.preload = './preload.js';
	document.body.appendChild(webview);
});

function onWebViewLoaded() {
	console.log('onWebViewLoaded');
    var webview = document.getElementsByTagName('webview')[0];
    webview.executeJavaScript('Test()');
}
```
**preload.js**
```javascript
function getOffset( el ) {
    var _x = 0;
    var _y = 0;
    while( el && !isNaN( el.offsetLeft ) && !isNaN( el.offsetTop ) ) {
        _x += el.offsetLeft - el.scrollLeft;
        _y += el.offsetTop - el.scrollTop;
        el = el.offsetParent;
    }
    return { top: _y, left: _x };
};
    
window.Test = function Test() {
    for (var i=0; i<document.links.length; i++) {
        var coords = getOffset(document.links[i]);
        console.log(document.links[i].text + ' => ' + document.links[i].href)
        console.log('    coords => ' + ' top:' + coords.top + ' left:' + coords.left);    
    }
};
```
