### ISSUE TITLE
404 when trying to install v0.31.0 via electron-prebuilt

### ISSUE THREAD

**Issue by smoak** [atom/electron#2590]
Trying to install electron via the electron-prebuilt package, but it seems there aren't any downloadable releases for 0.31.0:

```bash
 npm install electron-prebuilt -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.31.0 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.31.0-darwin-x64.zip
Error: GET https://github.com/atom/electron/releases/download/v0.31.0/electron-v0.31.0-darwin-x64.zip returned 404

/usr/local/lib/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: GET https://github.com/atom/electron/releases/download/v0.31.0/electron-v0.31.0-darwin-x64.zip returned 404
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
```

Notice this line here: Error: GET https://github.com/atom/electron/releases/download/v0.31.0/electron-v0.31.0-darwin-x64.zip returned 404

And when you view the electron releases in github (https://github.com/atom/electron/releases) there isn't a Downloads section for v0.31.0

**Comment by smoak** [comment]
I can successfully install v0.30.5 (via `npm install electron-prebuilt@0.30.5 -g`)

**Comment by conordickinson** [comment]
Happening to me too, it was working this morning though. Seems like the files got removed or something.

**Comment by stewartpark** [comment]
I'm having this error, too. After I've changed everything to adopt 0.31.0... (registerProtocol and all)

:'(

**Comment by zcbenz** [comment]
Somehow the release became a draft, maybe a cat walked on someone's keyboard? Anyway I clicked the publish button and things are working now.

**Comment by stewartpark** [comment]
Thanks, @zcbenz :)
