### ISSUE TITLE
Paste into input field doesn't work after packaging up app

### ISSUE THREAD

**Issue by stursby** [atom/electron#2591]
Working on an App locally (using `electron .`) and pasting `Cmd+V` (on Mac) works as expected. However, after running `electron-packager` ... nothing happens when I paste. For reference, I'm pasting into a simple `<input type="text">`.

**Comment by robertfirespotter** [comment]
When you run `electron .` you're running your app with electron's default menu items and accelerators built in. When you run it as a package, you'll need to add them yourself into your main process. 

See https://github.com/atom/electron/blob/master/atom/browser/default_app/main.js as an example.

**Comment by stursby** [comment]
Got it, thanks @robertfirespotter. Also, somebody shared this article on the Atom/Electron Slack channel - http://www.pracucci.com/atom-electron-enable-copy-and-paste.html.

**Comment by JLarky** [comment]
@robertfirespotter your link seem to be broken, I have found this package though https://www.npmjs.com/package/electron-default-menu

**Comment by Aathi** [comment]
Grate solution
https://github.com/onmyway133/blog/issues/67

**Comment by edwinbustamanterodriguez** [comment]
> Here is a pure JS solution which just works for Ctrl+V or CMD+V and doesn't require the addition of a menu
> 
> ```
> const { clipboard } = require('electron')
> const keyCodes = {
> 	V: 86,
> }
> 
> 
> document.onkeydown = function(event){
> 	let toReturn = true
> 	if(event.ctrlKey || event.metaKey){  // detect ctrl or cmd
> 		if(event.which == keyCodes.V){
> 			document.activeElement.value += clipboard.readText()
> 			document.activeElement.dispatchEvent(new Event('input'))
> 			toReturn = false
> 		}
> 	}
> 
> 	return toReturn
> }
> ```

to use on various inputs.
<input class="form-control ml-2" id="port" type="text" [(ngModel)]="port"  (input)="changePort($event)" (focusin)="focusPort()">


 focusPort() {
    const context = this.contextMain;
    document.onkeydown = function (event) {
      let toReturn = true;
      if (event.ctrlKey || event.metaKey) {  // detect ctrl or cmd
        if (event.which == keyCodes.V) {
          console.log(clipboard.readText());
          context.port = clipboard.readText();
          context.ref.detectChanges();
          toReturn = false;
        }
      }
      return toReturn;
    };
  }
