### ISSUE TITLE
Make Electron OS X app package more robust

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#2592]
According to https://github.com/atom/electron/issues/2561 unzipping or copying an OS X Electron app to Windows and then copying back to OS X will break the symlinks used for the OS X and Linux app packages.

It would be great if Electron did not use symlinks in the app package, this would make the app package more robust when transported via different media, network drives etc. and would also simplify auto-updating.

**Comment by paulcbetts** [comment]
Any OS X application with a Framework is going to have the same problem, this isn't really a scenario that we should really care about, that's just How OS X Works.

**Comment by jorangreef** [comment]
Is it really impossible to package a framework without a symlink?

**Comment by zcbenz** [comment]
The only way to do that is to copy all the files to where the symbol link should be, and it would increase the package size by about a few hundreds MBs. It is clearly not something we want to do.
