### ISSUE TITLE
Load flash plugin

### ISSUE THREAD

**Issue by mikart143** [atom/electron#2597]
Hello everybody,
I have problem with implementation of flash in my app. I am trying to use twitch player. I added to my program web-preferneces and I copied pepper flash plugin from chrome to my folder and twitch player still displaing : Couldn't load plugin. I can't resolve this problem, please help me  !!

![image](https://cloud.githubusercontent.com/assets/4084564/9491231/cff1dd36-4bed-11e5-8e7a-e596ca7ca808.png)

index.html 

http://pastebin.com/LD4yb8aA

**Comment by hokein** [comment]
@mikart143, please kindly see the sample: https://github.com/hokein/electron-sample-apps/tree/master/pepper-flash-plugin

**Comment by mikart143** [comment]
Ok thanks but how can i check which version of electron/pepper i have ? Where can i download other bit version one of them ?

**Comment by zcbenz** [comment]
You can find the version of flash plugin in `chrome:://plugins`, and the [forum](https://discuss.atom.io/category/electron) is probably a better place for asking questions.
