### ISSUE TITLE
Fullscreen errors on OS X

### ISSUE THREAD

**Issue by apexskier** [atom/electron#2599]
When trying to activate fullscreen, an error message appears in the terminal and the app briefly "flashes", but doesn't change size at all. This happens any way I've tried to activate fullscreen (from renderer thread using remote, from main thread, from clicking on the fullscreen window button, from the OS X view menu, using a frameless window, using a non-frameless window). Minimizing and maximizing/unmaximizing the window works.

OS X 10.10.5, Electron 0.31.0

The terminal output looks like this:
```
2015-08-26 10:27:31.332 Electron[57665:4665300] Message error: Connection invalid
2015-08-26 10:27:31.401 Electron[57665:4665300] ___createFullScreenMessageConnection_block_invoke: Fullscreen message error: Connection invalid
```

**Comment by zcbenz** [comment]
Are you using `screen` or `tmux`? If so, please read this:
https://github.com/atom/electron/issues/916#issuecomment-68567844

**Comment by apexskier** [comment]
Yep, that's it. Thanks!
