### ISSUE TITLE
[0.30.x] Mac BrowserWindow.capturePage is Failing during app hidden/background state

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#2610]
Hello,

We are using capturePage feature of browserWindow to get the app screen shot for our feedback mechanism in app. while writing the code, we found an issue, bw.capturePage returns NativeImage.

[mac] when app in hidden/background NativeImage.isEmpty() is always true, i.e, image is empty
[windows it works fine]

Sample App:
https://github.com/kamesh-a/electron-samples/tree/master/CaptureImage

Env : 
Mac OS x 0.10.9 & 0.10.10 
Electron engine 0.30.6 ... to 0.30.x all versions exhibit this.

Interesting thing, 0.30.6 process.tick and setInterval works smooth when app is hidden/background, when compared to other engines < 0.30.6

Thank you guys for all your work on this environment.

**Comment by kamesh-a** [comment]
0.31.0 also exhibits the same effect, but ticks are pretty much slower when 0.30.6. Still some native modules are not working in 0.31.0

ex : spellchecker, grunt-asar

will this be fixed and released in 0.30.x versions until 0.31.x becomes compatible

**Comment by zcbenz** [comment]
I can confirm this bug, but it is inside Chromium's rendering code, we can probably work around it by making Chromium think the page is visible when capturing image.

**Comment by appelgriebsch** [comment]
Got a workaround:
* get displaySize and create window off-screen
* capture page and close off-screen window

```javascript
var localScreen = require('screen');
var display = localScreen.getPrimaryDisplay().workAreaSize;
_width = display.width;
_height = display.height;

if (_window === null) {
  _window = new browserWindow({
    x: display.width,
    y: display.height,
    width: display.width,
    height: display.height,
    resizable: false,
    'skip-taskbar': true,
     show: true,
     'enable-larger-than-screen': true
  });
```

**Comment by davej** [comment]
@appelgriebsch Thanks for the workaround! It caused my main app UI to lose focus, so I used `showInactive` instead.

```javascript
function(width, height) {
  var localScreen = require('screen');
  var display = localScreen.getPrimaryDisplay().workAreaSize;

  var win = new BrowserWindow({
    x: display.width,
    y: display.height,
    width: width,
    height: height,
    show: false,
    frame: false,
    'enable-larger-than-screen': true
  });

  win.showInactive();
}
```

I've noticed that it's a **lot** more laggy than the previous behaviour on older versions of Election (i.e.. capturing a hidden window). Hopefully, a more performant patch can be landed to Electron.

**Comment by zcbenz** [comment]
Unable to reproduce in 0.36.2 anymore.
