### ISSUE TITLE
Tray icon is not created if electron new app is moved

### ISSUE THREAD

**Issue by armaseg** [atom/electron#2615]
This is an extension of ticket #2468 

Tray icon is correctly created on Windows 7 once the app is executed using the standard command:
<code>electron .</code>

Also, executing electron-packager works:
<code>
electron-packager ./dist/ myApp --platform=win32 --arch=x64 --version=0.30.5 --asar --overwrite  --icon=./myImage.ico --app-bundle-id=myApp  --helper-bundle-id=myApp --version-string.CompanyName=myCompany --version-string.ProductName=myApp --version-string.FileDescription=myApp --version-string.OriginalFilename=myApp
</code>

But, If I move the new app folder myApp-win32-x64 to another place in my disk and execute myApp.exe it won't work anymore. I tryed with v0.30.5 and v0.30.6

Then, I downladed v0.30.5 and v0.30.6 Prebuilt binaries and placed the app.asar that electron-packager created and it didn't work either. I did the same test with v0.30.1 and it worked.

![electronv0306](https://cloud.githubusercontent.com/assets/1028859/9527289/c667ea96-4cb3-11e5-8413-932607ce4600.JPG)

**Comment by paulatbipsync** [comment]
We are seeing this problem also
It's a terrible workaround but for the time being on windows we are calling:
`app.setName( 'APPNAME' + Math.random( 1, 1000 ) );`
On startup, this seems to allow tray icons to be created reliably

**Comment by hankbao** [comment]
Same problem here on Windows 7. Tray works on Windows 10.

**Comment by kasoki** [comment]
@hankbao doesn't work for me on Windows 10 either, @paulatbipsync hack helped though.

**Comment by Pettor** [comment]
I am experiencing the same problem on Windows 10.

**Comment by zcbenz** [comment]
Fixed by #2882.

**Comment by paulcbetts** [comment]
> Not really sure how to do the "Once that information is removed, you can move the binary file to a new location and reregister it with a new GUID" part as of yet and its not explained."

Yeah, as far as I can tell, you can't remove GUIDs by any means, though I could be wrong
