### ISSUE TITLE
Chrome urls support

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2618]
What [chrome urls](http://www.stugon.com/complete-list-of-allchrome-urls-purposes/) are supported in Electron?

`chrome://gpu` works, but I tried some others and noting else seems to work.

**Comment by deepak1556** [comment]
which url are you interested in ? `chrome://serviceworker-internals`, `chrome://webrtc-*` `chrome://tracing` can be used.

**Comment by etiktin** [comment]
Thanks @deepak1556 :)
I was just wondering what is available and didn't find any reference to it in Electron's code. Where did you find it?

**Comment by deepak1556** [comment]
https://github.com/atom/brightray/pull/95

**Comment by zcbenz** [comment]
Not every `chrome://` url is supported, usually only the ones belong to the content module are.

**Comment by hokein** [comment]
Not every `chrome://` urls are supported in Electron.

Basicly, only the ones that has no dependency on Chromium browser' resources are supported. The other ones which relies on Chromium browser related part are not supported, e.g. `chrome://extensions`, `chrome://apps`, `chrome://history`.

The only way to test it is trying to load the chrome urls in Electron to see whether it works.

**Comment by etiktin** [comment]
Thanks :)
