### ISSUE TITLE
getTitle() returns "" for frameless window

### ISSUE THREAD

**Issue by apexskier** [atom/electron#2620]
This is happening for me on commit 195be931a4f28e1acfb4fa7da5c6fb3a9c9855e7. Simply removing the frame: false from the BrowserWindow options makes getTitle() return the correct title.

**Comment by zcbenz** [comment]
`BrowserWindow.getTitle()` returns window's title, and frameless window doesn't have a title (it used to but then gets removed later), what you want should be `WebContents.getTitle` which returns page's title.
