### ISSUE TITLE
Potential Security Issues with web pages loaded in browserwindows

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/electron#2621]
I have a prototype Electron app which allows users to share custom web-pages which can be loaded into browserwindows (mainly to enable 'remembering' size/position and to run borderless)

I've had a quick think and I can't imagine any security risks in doing this (unlike node-webkit which would give page authors open access to Node and thus to the local filesystem etc??) but I thought I'd ask if anyone was aware of any risks in allowing users to share webpages which are opened within an Electron app/browserwindow/renderer process??

Note: Obviously they have access to the main process via remote/IPC so they can access/change global variables, call global functions and send other IPC messages, but so long as none of those have any malicious potential, I can't think of anything else?

**Comment by zcbenz** [comment]
Electron doesn't require users' permission for geolocation API or WebRTC, so a third party web page can access any resources that allowed by HTML5 API.
