### ISSUE TITLE
[0.31.0] failed to start electron with --debug=5858

### ISSUE THREAD

**Issue by jwu** [atom/electron#2622]
I try to start electron with `--debug` command as the document told me to do: https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md

This works before 0.31.0. It failed by reporting the following information:

```bash
./bin/electron/Electron.app/Contents/MacOS/Electron --debug=5858 ./
Segmentation fault: 11
```

**Comment by zcbenz** [comment]
It has been fixed by #2608 and will be released soon.
