### ISSUE TITLE
bundled with 0.12.x timeline?

### ISSUE THREAD

**Issue by RIAEvangelist** [atom/electron#2624]
when will electron be bundled with 0.12.x?

the documentation states that electron is still using the unstable version 0.11.13

thanks.

**Comment by RIAEvangelist** [comment]
please label as question

**Comment by etiktin** [comment]
Are you talking about the node version?
Electron uses io.js (a fork of node). The version used in Electron v0.31.0 is io.js v3.1.0.
This information is available in the [releases page](https://github.com/atom/electron/releases).

**Comment by thomasjo** [comment]
The incorrect documentation in question is https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md. At least that's the only reference to Node.js bundling mentioned in conjunction with version information.

And as @etiktin has mentioned, Electron is currently shipping with io.js v3.1.0.

**Comment by RIAEvangelist** [comment]
OK, this also propagates to the web site.
