### ISSUE TITLE
How do I make the app render bigger (scale x2 or something)?

### ISSUE THREAD

**Issue by trusktr** [atom/electron#2625]
Electron is tiny on my Linux Desktop (the window with the white border is Neovim-e, running in Electron, but it's tiny:

![screenshot from 2015-08-27 23-47-01](https://cloud.githubusercontent.com/assets/297678/9540767/0046f690-4d17-11e5-965c-b46f1df62694.png)

Is there some way to make the browser window render twice as big (or an arbitrary value)?

**Comment by Tribex** [comment]
@trusktr I wonder if you could use `transform: scale(2.0);` on the body/html element's css?

**Comment by zcbenz** [comment]
Electron reads the `text-scaling-factor` setting of `org.gnome.desktop.interface` to get the DPI, you can set it to a proper value to make Electron work correctly. Also you can use the [web-frame](https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframesetzoomfactorfactor) module to set page's scale factor.

**Comment by trusktr** [comment]
@Tribex `transform: scale(2)` doesn't work because it scales everything and the window stays small, plus the GTK menus are still small, and the developer tools are still tiny. The overall app should be scaled with the Desktop's scaling.

@zcbenz If I change `text-scaling-factor` from 1 to 2, my desktop fonts will be extremely huge. Everything in the background of my screenshot is at x1 font-scale. Gnome already scales the whole desktop x2 for retina, but only electron is not scaled. Does it need to read some other setting other than `text-scaling-factor` perhaps?

**Comment by trusktr** [comment]
@zcbenz How do we get web-frame? I'm getting

```
Error: Cannot find module 'web-frame'
```

in the launcher:

```coffee
# launcher.coffee
# entry point of the app
# Copyright (c) 2015 Lu Wang <coolwanglu@gmail.com>

app = require 'app'
BrowserWindow = require 'browser-window'

webFrame = require 'web-frame'
console.log 'web-frame?'
console.log webFrame # ERROR

process.on 'uncaughtException', (error={}) ->
  console.log error.message  if error.message?
  console.log error.stack  if error.stack?

app.on 'window-all-closed', -> app.quit()

win = null
app.on 'ready', ->
  win = new BrowserWindow width: 800, height: 600
  win.loadUrl 'file://' + __dirname + '/nvim.html'
```

**Comment by trusktr** [comment]
I don't use CoffeeScript, but [neovim-e](https://github.com/coolwanglu/neovim-e) is written in coffee.

**Comment by Tribex** [comment]
@trusktr The `web-frame` module is only accessible from the renderer process. Try using it from nvim.html.

**Comment by trusktr** [comment]
@Tribex How might I do that? `window.webFrame` is undefined.

**Comment by Tribex** [comment]
@trusktr

Here's a skeleton `nvim.html`:

```html
<!DOCTYPE html>
<html>
<head>
    <script>
        var webFrame = require('web-frame');
        webFrame.setZoomFactor(2);
    </script>
</head>
<body>
    <p>Paragraph Element which should now be rescaled</p>
</body>
</html>
```

**Comment by trusktr** [comment]
@Tribex That worked! 

How would we make this work on all Desktops (Linux Desktops, OS X, and Windows)?

**Comment by Tribex** [comment]
@trusktr Not sure, never used electron on a platform other than Linux or a high-DPI screen.
