### ISSUE TITLE
Inversed sequence of finding up node_modules after packaging?

### ISSUE THREAD

**Issue by fritx** [atom/electron#2626]
The normal sequence of finding up node_modules in node.js, should be 'from inner to outer', which is resonable - modularity, local first..
However, It's weird that I found the direction got inversed in a packaged electron app, which suprised me and of course wasted lots of my time.
And the bug is dangerous cause the production environment can be out of control.
I'm happy to find such a bug of electron though..
(Windows 7 x64 & electron v0.31.0)

```
- dev/
  - node_modules/   ## for random reasons it just exists
    - sqlite3/   ## instead of this
  - xxxapp/
    - node_modules/
      - sqlite3/   ## this should be picked up
    - main.js   ## call require('sqlite3')
  - xxxapp-released/
    - electron.exe   ## the same
```

**Comment by zcbenz** [comment]
Can you paste the value of `module.paths`?

**Comment by fritx** [comment]
![](http://channel.fritx.me/media/a2440363c680ba96e7a8282136586cf5.jpg)

(This time I'm on Windows10..) in main.js, seems alright..
But in index.html, the order of `module.paths` seems really bad:

![](http://channel.fritx.me/media/fcac5e8aa5cff237147e40cf173095b7.jpg)

```plain
- test/
  - hijack-demo/
    - hijack-app/
      - app/
        - node_modules/
        - main.js
        - index.html
```

**Comment by zcbenz** [comment]
This is part of how Node's module system works, it will add all paths up to the root of filesystem to module search paths. We should probably constrain the module search paths to inside of the app.

**Comment by fritx** [comment]
@zcbenz yeah i guess it is how io.js or node.js do it :+1: we should just constrain it.
