### ISSUE TITLE
Printing fails with more than 3 pages on Windows

### ISSUE THREAD

**Issue by Purii** [atom/electron#2627]
I'm not able to print out a document with more than three pages on Windows. Debian looks fine.

- System: Windows 7 32-Bit and 64-Bit
- Electron versions: `0.31.1` and `0.30.6`
- Kind of app: Simple `BrowserWindow` to load a website

By using `PDFCreator` the print queue stops at page 3/3, even if there are more pages. I can't recognize any error message.
Printing through a physical printer doesn't display anything and the printer keeps silent.
The size of the document doesn't seem to be a problem, since it happens with both text-only and pictures-only.

Could someone test this please, to exclude a problem with the client?

**Comment by hokein** [comment]
Could you paste your `code` here? Someone has meet the same issue before, you can read in #805 comments.

**Comment by Purii** [comment]
I use mainly this [example code](https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md).
```JavaScript
.....
app.on('ready', function() {
// Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 1000,
    'min-width': process.platform === 'win32' ? 400 : 700,
    'min-height': process.platform === 'win32' ? 260 : 500,
    title: 'HelloPrinter',
    icon: './assets/icon.png',
    'auto-hide-menu-bar': true,
    'node-integration': false
  });

  // and load the index.html of the app.
  //mainWindow.loadUrl('file://' + __dirname + '/index.html');
  mainWindow.loadUrl('http://localhost');
  mainWindow.setMenu(null);
  // Open the devtools.
  mainWindow.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});
....
```

The apache on localhost serves a page which needs more than three pages to print out. To trigger the print out, I'm just using `window.print()`:
```php
<?php
for($i=0;$i<250;$i++) {
  ?>
  <span>Hello!</span>
  <br>
  <?php
  }
?>
<a href="#" onClick="window.print()">Print!</a>

```

**Comment by hokein** [comment]
I can confirm it on Windows, it should be a bug. Right now you can use `printToPDF` API as a workaround.
