### ISSUE TITLE
Add support for WinAPI's CreateMutex

### ISSUE THREAD

**Issue by joaomoreno** [atom/electron#2629]
[`CreateMutex`](https://msdn.microsoft.com/en-us/library/ms682411.aspx) allows me to create a system-wide mutex that parallel executions of my application, as well as other applications, can use to determine whether my application is currently running.

It is specifically used in [Inno Setup](http://www.jrsoftware.org/ishelp/index.php?topic=setup_appmutex) as a mechanism to know whether an application is currently running or not.

It would be nice to have this via some API, but a simple declarative approach would suffice. All I'm interested in is having such mutex exist throughout my application's lifecycle.

**Comment by zcbenz** [comment]
I suggest writing a native module for it, we can not just add API for every single API. Another choice is to use node-ffi to call win32 APIs directly.

And for your purpose, using named pipe is another popular way, and it doesn't require adding new API.

**Comment by joaomoreno** [comment]
Fair enough, good point!
