### ISSUE TITLE
Silent print does nothing on Linux (Tested on Ubuntu 14.04)

### ISSUE THREAD

**Issue by pulkit110** [atom/electron#2630]
Printing a `webview` with `silent` set to `true` does nothing on Linux (works fine on OSX). When `silent` is set to `false`, it brings up the print dialog and works fine. 

There is a default printer configured and using `lpr` from the command line without specifying any printer works fine too.

Sample code: 

```javascript
var printWebView = $('<webview/>', {
  src: 'http://google.com'
}).css({visibility: 'hidden'});
printWebView[0].addEventListener('dom-ready', function () {
  printWebView[0].print({silent: true});
});
printWebView.appendTo('body');
```

**Comment by hokein** [comment]
Could you try to listen to the `did-finish-load` event instead of `dom-ready` ?

**Comment by pulkit110** [comment]
@hokein It doesn't work with `did-finish-load` either.

**Comment by zcbenz** [comment]
Unable to reproduce in 0.36.2.

**Comment by fxckdead** [comment]
@zcbenz @hokein  i just faced the same issue in Ubuntu 14.04 with versions 0.36.2, 0.36.12 and 0.37.

In Windows and OSX it works, but only in linux it doesn't print in silent mode.

**Comment by MyungireJ** [comment]
Hey guys, is there any one who has found solution for this for linux  ?  I still can't print when silent mode is true.

**Comment by Kymy** [comment]
Hey, somebody has found a solution ?

**Comment by willswire** [comment]
still an issue!

**Comment by ufocruz** [comment]
still an issue!
