### ISSUE TITLE
Preload CSS

### ISSUE THREAD

**Issue by kylebrowning** [atom/electron#2632]
Is there a way to preload a CSS file for all pages that get clicked on?

I am getting flickering everytime it loads a page in the BrowserWindow.

**Comment by fritx** [comment]
+1
I want a css get fixed before the page

**Comment by denistsoi** [comment]
Check out a js preloader (or caching your assets before rendering)
http://www.createjs.com/preloadjs
(this should get closed as it's not related to Electron)

You may also review how [Menubar](https://github.com/maxogden/menubar) does things.
