### ISSUE TITLE
Unable to focus input in new window until user has interacted with the window

### ISSUE THREAD

**Issue by aackerman** [atom/electron#2636]
I have a situation in my application where I want to open a new window and focus an input.

I can't seem to do any focusing of elements on the page until the user has interacted with the window and in the webpage `document.hasFocus()` continues to be `false` until the user interacts with the window.

Is this a known limitation or is there another way to accomplish this task?

Calling focus on the browser window instance or setting the alwaysOnTop flag did not solve this issue.

**Comment by zcbenz** [comment]
Which version of Electron are you using? And what's your operating system? It sounds to be an old bug.

**Comment by aackerman** [comment]
I was using 0.28.1 and OSX 10.10. I'll try with a newer version.

On Saturday, August 29, 2015, Cheng Zhao <notifications@github.com> wrote:

> Which version of Electron are you using? And what's your operating system?
> It sounds to be an old bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/electron/issues/2636#issuecomment-135960109>.
>


-- 
Aaron Ackerman
theron17@gmail.com

**Comment by zcbenz** [comment]
v0.30.1 included the fix.
