### ISSUE TITLE
Exposing app.hide to pass focus to the previously-active application

### ISSUE THREAD

**Issue by holmesal** [atom/electron#2640]
I'm on OSX, implementing a frameless overlay designed to be opened on top of other applications.

The problem is that when I hide my BrowserWindow, my application still has focus. This is a little infuriating if you're opening an overlay on top of an app like terminal, because when you close the overlay you need to also click the screen for your keyboard inputs to be registered.

It seems that this could be achieved (on OSX at least) with [[NSApplication hide]](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/index.html#//apple_ref/occ/instm/NSApplication/hide:). Would it be possible to add support for this to the `app` api?

**Comment by zcbenz** [comment]
Actually `app.hide` is calling `[NSApplication hide]`, you can use `app.dock.hide` to avoid your app being focused on.

**Comment by holmesal** [comment]
As far as I can tell, there is no `app.hide` method - only `browserWindow.hide`.

Am I missing this somewhere? It doesn't seem to be in the docs, and I get `app.hide is not defined` when attempting to call it. I'm on `v0.31.1`.

Reformulating in case I wasn't clear:
* Open Finder
* Open my app on top of Finder
   * At this point, the finder window has lost focus, but the osx menubar still says "Finder".
* Call `browserWindow.hide()` on my only browserwindow.
   * At this point, my application is invisible but *still seems to be in the foreground* becase:
      * The underlying finder window hasn't regained focus
      * It is still responding to keyboard shortcuts - pressing `ctrl+q` will quit my app and return focus to Finder

So in my original question, I was hoping there was a way for me to hide *my entire `app`*, not just my `browserwindow`.

**Comment by holmesal** [comment]
I found that executing the "hide" command from the menu produces the desired result, though of course it's super-hacky.
```
menu = Menu.getApplicationMenu()
appMenu = menu.items[0].submenu
hideMenuItem = appMenu.items[4]
appMenu.delegate.executeCommand hideMenuItem.commandId
```
So I guess my question becomes - is there a way to do this directly via the `app` api?

**Comment by zcbenz** [comment]
Sorry I thought `app.hide` was implemented, you can use `Menu.sendActionToFirstResponder` to implement that:

```js
Menu.sendActionToFirstResponder('hide:');
```

**Comment by holmesal** [comment]
Ah! Good to know, thanks :+1:

**Comment by afficiona** [comment]
@zcbenz Thank you. Worked like a charm for me. :)
