### ISSUE TITLE
setting webview.src to unreachable url doesn't emit 'did-fail-load' event.

### ISSUE THREAD

**Issue by ssreekanth** [atom/electron#2646]
When I'm trying to load a url in webview, it doesn't fire 'did-fail-load' when that url is unreachable or the webserver itself is down. however, when i reload the webview, it fires 'did-fail-load' after some timeout.

Is it a known issue that it doesn't emit 'did-fail-load' event for the first time, but does it when called webview.reload() ? Or should i be having listener for the some other type of event?

**Comment by zcbenz** [comment]
In latest electron I'm not able to reproduce, seems that it gets fixed by some other commits.

**Comment by gabssnake** [comment]
Maybe solved by merge #1242? See issue #1105 for similar symptom.
