### ISSUE TITLE
Main process crashes when require('ws')

### ISSUE THREAD

**Issue by Quramy** [atom/electron#2648]
I create an electron app which uses WebSocket, and I use [ws@0.8.0](https://www.npmjs.com/package/ws) .

Yesterday, I update dependency of `electron-prebuilt` from v0.30.6 to v.0.31.0 , so my main process crashes when `require('ws')`.

I wrote example of this issue(sample repository is [Quramy/electron-ws](https://github.com/Quramy/electron-ws):

```js
'use strict';

// If comment out the following line, app starts up nomally and logs 'ready' in consle.
// And old with electron-prebuilt(v.0.30.6) this issue isn't occurred.
var ws = require('ws');

require('app').on('ready', function () {
  console.log('ready');
});
```

With v0.31.0, the electron process closed and there is no error in my console.

How do I fix this issue ?

I use:

- OS: OS X 10.9.5
- electron-prebuilt: v0.31.0
- ws: v0.8.0

**Comment by etiktin** [comment]
Did you rebuild your modules using [electron-rebuild](https://github.com/electronjs/electron-rebuild) (`ws` uses `node-gyp` for itself or for it's dependencies)?

**Comment by Quramy** [comment]
I tried `nvm iojs-v3.1.0` and re-install `ws`, so this issue get fixed.
Thanks.

**Comment by etiktin** [comment]
You're welcome. Glad it worked.
