### ISSUE TITLE
Set as default app top open file type

### ISSUE THREAD

**Issue by RIAEvangelist** [atom/electron#2651]
Short of building a custom binary which the installer informs the system that the app is intended to open certain file types,

is it possible for electron to register an app as a default program to open certain file types?

Building my first electron app now to compare to NW.js. [electron video player](https://github.com/RIAEvangelist/electron-video-player) seemed like a good place to start for a first app.

**Comment by zcbenz** [comment]
I suggest writing a Node.js module for this, it is independent from Electron's APIs and we can not add API for every platform feature.

**Comment by RIAEvangelist** [comment]
Wasn't sure if this was something supported or not. Thought it was worth asking as it seemed pretty basic. Default app to open .txt or .mp4 etc.

Thanks for feedback.

**Comment by simonmeusel** [comment]
For all of you, who are searching for a solution, have a look at https://www.electron.build . More specifically search for `fileAssociations` [here](https://www.electron.build/configuration/configuration).
