### ISSUE TITLE
webview with ipc-message not working on guest page

### ISSUE THREAD

**Issue by alexandrkazah** [atom/electron#2653]
I'm trying to use ipc module in guest page with this code
// In guest page.
function sendCallBack() {
require('ipc').sendToHost('pong');
}

so in my embedder I have code similar to:
"webview src="http://my_guest_page.html" nodeintegration></webview"

But webview is crashing and not loading. Here is log message i get from webview log: "Uncaught ReferenceError: bowser is not defined"

Any help would be much appreciated.

**Comment by zcbenz** [comment]
Can you provide a reproducible demo app?

**Comment by alexandrkazah** [comment]
How/where I can post my test project code?

**Comment by frankhale** [comment]
@alexandrkazah, here on Github or as a Gist https://gist.github.com/

**Comment by alexandrkazah** [comment]
I have played more with my project and found out that my setup on the guest page is preventing this. So my test project I done works but my development setup is not due to some configuration on guest web application. Thanks anyway for your time guys.
