### ISSUE TITLE
Problem including frontend libs like jQuery in `<script>`tag

### ISSUE THREAD

**Issue by fritx** [atom/electron#2659]
```js
var $ = require('jquery')  // this is okay, but..
```

```html
<script src="jquery.js"></script>
<script> // jQuery is not defined </script>
```

I noticed that in [jquery/src/intro.js](https://github.com/jquery/jquery/blob/master/src%2Fintro.js#L17), once `module.exports` is detected, jQuery assumes that is node.js, etc, and is being exported...

In [nw.js (formerly node-webkit)](https://github.com/nwjs/nw.js), there was no problem probably because in this case - `<script>` tag, nw.js didn't expose any `module.exports`, so it goes the browser way.

I think `require` is the better way to work, but while migrating from nw.js, we just want to make as few changes as possible..

- The common intro/outro wrapper of most the frontend libs should to be improved? (to be more accurate)
- Maybe electron should not expose `module.exports` in `<script>`tags, just like nw.js does? (seems it also makes no sense to be `require`d?)

I'm not sure.. Any idea?

**Comment by zcbenz** [comment]
If you want to load a pure web environment, you should turn off node integration and use preload script to load your custom code. Hiding `module.exports` is a big breaking change so no matter whether it is good or not we won't do it.

On using jQuery itself, there are already many discussions on it (like https://github.com/atom/electron/issues/2048).

**Comment by fritx** [comment]
Thanks! :smile:
