### ISSUE TITLE
question : where to promote electron apps

### ISSUE THREAD

**Issue by RIAEvangelist** [atom/electron#2660]
I have been using nw.js for a while now, but decided to give electron a shot this weekend. @MaybeRex and I decided to throw together a quick project to check out the work flow from dev to release/build an [electron based video player](](https://github.com/RIAEvangelist/electron-video-player)). The separation of responsibilities electron provides is quite nice and reminiscent of Chrome OS apps in a way.

[If you want to try it download from the release page](https://github.com/RIAEvangelist/electron-video-player/releases).

__What is the best way or location to promote or get electron apps infront of the public?__ Chrome OS (and all other platforms with chrome) have the Chrome Web Store and mobile devices have their stores, but I do not know of any popular locations to promote free or sell commercial desktop apps which have popularity.

If we were to go through the process of submitting to the Mac, Windows, and Ubuntu stores independently it seems that there would be some headaches involved, especially with windows apps...

**Comment by Tribex** [comment]
It would be interesting/fun to write a cross-platform app store in Electron, then use it to promote electron apps. (Which would not need to bundle the electron runtime due to the presence of it in the app store itself.)

Extra points for basing it on npm or a fork of it. (Such as apm)

**Comment by RIAEvangelist** [comment]
@Tribex thanks for sharing that list. pretty cool.

I have been thinking that I might just have to build a store as well since there is really nothing I have been able to find. [Gum Road](https://gumroad.com/) is a nice site to handle sales, but it's not a store, and you can't search it. So you still have to find ways to get your app in front of as many people as possible.

The nice thing about a store is that the people there are already looking for an app, so it increases your chance of getting installs being it free or paid.

**Comment by Tribex** [comment]
@RIAEvangelist If you do happen to start building a store, I'd be happy to contribute from time to time, when possible. :)

Hosting would be tricky though.

**Comment by RIAEvangelist** [comment]
I already have a few servers, so all we would need to do is come up with the right domain name.

**Comment by Tribex** [comment]
@RIAEvangelist Ah, okay then. Keep me posted!  I don't think Apple (or Windows?) allows third-party app stores on it's app store though, so it would have to be distributed via another method.

**Comment by RIAEvangelist** [comment]
Distributing a store will be easier than distributing an app I believe. The demographic for distributing a single app is limited to that apps functionality.

While a store on the other hand has the benefit of containing many apps thus creating a much larger demographic that may be interested.

ie. you might not be interested in buying an oven mit, but you might be interested in buying something from a store that also sells oven mits.

**Comment by RIAEvangelist** [comment]
Maybe I'll start building a store that is based on integrating with [Gum Road](https://gumroad.com/) maybe. This way we don't have to worry about PCI compliance and other sorts of financial things.

This seems good since I am not interested in making money off the project, just providing a place where other people can distribute or sell their apps.

**Comment by Tribex** [comment]
Hmm, does GunRoad have an API? It also doesn't really seem oriented toward programs. More toward arts and such. However, if it will work for ya, then I suppose it's fine. :3

**Comment by zcbenz** [comment]
Promoting electron apps is the same with promoting apps written with other frameworks, different platforms have their own way of promoting apps. On OS X there is app store, on Windows there are various third party app markets, and for games you can submit to Steam store.

In future we may have our own app store when #673 is done, but it will be years later.

**Comment by lakinmohapatra** [comment]
We are waiting for electron app store

**Comment by gtamas** [comment]
Yeah what's up with this?

**Comment by gtamas** [comment]
Any plans?

**Comment by gtamas** [comment]
What's up?
