### ISSUE TITLE
Will electron provides latest v8 with develop branch of node.js? 

### ISSUE THREAD

**Issue by Kimura1** [atom/electron#2663]
As you can see, iojs and node.js will be integrate.
According to new node.js, major version up (include v8 update) is carried out every six months.

https://github.com/nodejs/node/issues/2577
> It is a little sparse on information, but the LTS working group ( https://github.com/nodejs/LTS ) is ensuring every year will have a LTS release. These are going to be the most stable for production use, however there will be many more releases, with major releases every 6 months. It is a bit easier to read from : https://twitter.com/rvagg/status/635605780780093440

However, I want to use new v8 on electron more earlier.

Will you provide binary of unstable electron?

**Comment by zcbenz** [comment]
We always use the V8 shipped by stable release of Chrome, it is usually the latest stable one and under most cases it is also the one used by latest io.js/node.js.
