### ISSUE TITLE
[FEATURE REQUEST] A way to know if the OSX dock icon is visible

### ISSUE THREAD

**Issue by aackerman** [atom/electron#2667]
I'm interested in having a way to know if the osx dock icon is visible or not. The use case is for application testing where I want to test that when all windows aside from a window associated with a tray icon are closed the dock icon is closed.

I'm unable to find a way to do that right now, I looked through the [source](https://github.com/atom/electron/blob/master/atom/browser/browser_mac.mm) and a method to do this doesn't exist and I wasn't able to come up with a clear way to do this after a few cursory google searches. I don't have the ObjC expertise to contribute myself.

**Comment by zcbenz** [comment]
The dock icon is always visible unless your app quits or you explicitly calls `dock.hide` to hide it. So if your app is still running and you didn't call `dock.hide`, then your dock icon is visible.
