### ISSUE TITLE
Event when dock is clicked whilst windows are open

### ISSUE THREAD

**Issue by tommoor** [atom/electron#2671]
In relation to #194 - it would be great to have an `activate` event triggered when the dock icon is clicked so that we can appropriately hide/show windows for example.

**Comment by lipis** [comment]
+1

**Comment by tommoor** [comment]
Guessing we'd just add the event in here https://github.com/atom/electron/blob/master/atom/browser/mac/atom_application_delegate.mm#L56 @zcbenz - any chance of slipping something into the next release? :wink:
