### ISSUE TITLE
Support two-finger swipe navigation

### ISSUE THREAD

**Issue by jacwright** [atom/electron#2683]
OSX supports various gestures with the trackpad. One of the most useful of these is the two-finger swipe which allows you to navigate forward and backward in web apps. This could be very useful for electron apps.

**Comment by ssreekanth** [comment]
See #1486 for some details.

**Comment by paulcbetts** [comment]
I don't think you should really have the concept of back and forward in a desktop app, nor should we enable it, since for the majority of desktop apps, devs will have to do work to disable this or else users will write in, "I two finger swipe back and get a white screen, wat"

**Comment by carlosperate** [comment]
Completely agree with @paulcbetts.

**Comment by jacwright** [comment]
I also agree with @paulcbetts. It should be something available for use, but not turned on by default. Browsers use it, and browser-like apps could use it (a photo app to swipe through photos for e.g.), but not code editors and many other types of desktop apps.

This feature was created by Apple for desktop apps. Web apps don't use it. Browser's (which are desktop apps that access the internet) do. Desktop image apps use it. There may be other types of applications that could use it.

In addition, apps that are built for the web but work offline in a desktop app could provide a consistent experience in and out of the browser if this feature was enabled.

Closing out since this is covered by #1486. I was searching for swipe and should have expended the issue search for gestures.

**Comment by brennanMKE** [comment]
I use back and forward in IDEs all the time. Xcode and VS Code support it. I have VS Code configured on my Mac to use cmd-+ and cmd-- to go forward and back but with Xcode I can simply swipe right and left on the trackpad build into the MacBook. It is much more natural. And since VS Code does not support tabs it is even more important to be able to quickly navigate through the code.

This is not just a web-browser feature. Many applications could use this feature.

**Comment by hph** [comment]
The referenced issue has been closed as well. It would be very helpful to support this in conjunction with `<webview>`.

**Comment by ccorcos** [comment]
@paulcbetts swipe back doesn't have to actually trigger `history.back()`. But the gesture can definitely be useful. If the feature is there, it would be nice if it were exposed!

**Comment by philfreo** [comment]
@jacwright Since the broader issue you referenced didn't go anywhere and was closed, perhaps this narrower use case issue (ability to detect 2-finger swipe gestures) could be reopened? 

In particular, I was surprised to see a [3-finger swipe event supported already](https://electronjs.org/docs/api/browser-window#event-swipe-macos). Chrome & Safari are two desktop apps that both support 2-finger swipes. It'd be great if Electron did too.

(This would allow userland support for "2-finger swipe for back/forward navigation" as well as other use cases).

**Comment by tzarebczan** [comment]
+1 on this one...would love to have it in our LBRY Electron app!

**Comment by warpdesign** [comment]
@philfreo I am also surprised Electron natively supports 3-fingers swipe under macOS and not 2-fingers swipe.

Especially knowing that 3-fingers swipe is usually already mapped to the change of workspace under macOS and so not really suitable for use inside any application.

**Comment by Xylobol** [comment]
Also in support. I'd love to see this on Windows in particular.

**Comment by raphaelschaad** [comment]
It feels that this should be an Electron API. `BrowserWindow` already supports [`Event: 'swipe'`](https://www.electronjs.org/docs/api/browser-window#event-swipe-macos) for 3-finger gestures. A nice API choice would be to simply expose the number of touches (=fingers) as int on the existing API.

As of now, it is an odd design choice to support 3 but not 2-finger swipes in userland because 3-finger swipe is commonly used as an OS-level gesture (e.g. navigating between fullscreen apps), and 2-finger swipe is commonly used as an app gesture to navigate back/forward (e.g. browsers, code editors).

I disagree with @anaisbetts on all points:
> I don't think you should really have the concept of back and forward in a desktop app
I think this is a design choice the app designer should make. Apple (e.g. Calendar.app) and Google (e.g. Chrome), for example, have decided that it is a good concept for desktop apps.

nor should we enable it, since for the majority of desktop apps, devs will have to do work to disable this or else users will write in, "I two finger swipe back and get a white screen, wat"
I appreciate this point because from an implementation point of view, you were thinking about this as a default on `BrowserWindow` navigation behavior. But it doesn't have to be that way. If you look at how Electron implements `[Event: 'swipe']`, there will be no work for devs, or user complaints, whatsoever. It will be opt-in and extending an existing API.

Is anyone reading this familiar with who implemented the 3-finger gesture? There might have been technical limitations to implement my suggested approach that I'm unaware of. Happy to help.

**Comment by anaisbetts** [comment]
To be clear, I am totally for Electron apps being able to easily listen to all kinds of swipe events - what I am not against is the *default* of mapping any swipe action to navigation. 

Developers who *do* want this behavior can trivially implement it, please don't hoist disabling this onto every developer and adding *yet another* way for Electron apps to land on a white screen

**Comment by raphaelschaad** [comment]
Great!

**Comment by raphaelschaad** [comment]
Quick bump on this. @thread: who would be a good person to provide some guidance on where to start? Happy to commit time from my end to get this in -- but have no clue where to start. Thanks in advance!

**Comment by jorilallo** [comment]
We also have received requests for two fingers swipes for our application as users expect more parity with browsers/native apps. Would be excited to see this as opt-it implementation in Electron

**Comment by gaodeng** [comment]
any news?

**Comment by samuelmaddock** [comment]
The Chromium implementation of this behavior on macOS is available in [chrome_render_widget_host_view_mac_history_swiper.mm](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/renderer_host/chrome_render_widget_host_view_mac_history_swiper.mm)

If it can be brought into Electron, we could introduce a simple `BrowserWindow` constructor option for `enableHistorySwipe` which would default to `false`.

**Comment by Brian-Bartels** [comment]
Any update on this? I see this as quite valuable

**Comment by maccman** [comment]
I agree - this would be super valuable.

**Comment by Dovizu** [comment]
One of the great ways to prove Apple wrong is to make Electron-wrapped apps as good as native apps are at supporting native design patterns. 

Two-finger swipe is nearly universal on Mac. Can we prioritize this?

**Comment by alexb148** [comment]
Adding my voice to say I'd also love to see this as an option

**Comment by moritzWa** [comment]
Is there any way I can vote for the prioritization of this or put up a bounty. This would be great for our desktop app. I use this pretty heavily in the browser and this is basically the only feature that is missing from the electron/desktop app.

**Comment by Eneris** [comment]
There is a way...

Two-finger swipe is handled as mouse `wheel` event.
Custom detection (FE in preload script) is possible. But... there is a catch:

WheelEvent is missing `phase` and `momentumPhase` properties and `momentum` phase events are not fired which are needed to properly detect when swipe ends. This needs to be patched in Chromium source.

One of those places is here: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/input/mouse_wheel_event_manager.cc;l=77?q=mouse_wheel_event_manager.cc&ss=chromium

**Comment by GoldinGuy** [comment]
@Eneris Can you share the pre-load script? Have there been any updates on this?

**Comment by Eneris** [comment]
> @Eneris Can you share the pre-load script? Have there been any updates on this?

```ts

enum Gesture {
    UNKNOWN = 0,
    ZOOM,
    SCALE,
    SWIPE,
    SCROLL,
}

const enum Phase {
    // No phase information is avaiable.
    kPhaseNone = 0,
    // This wheel event is the beginning of a scrolling sequence.
    kPhaseBegan = 1 << 0,
    // Shows that scrolling is ongoing but the scroll delta for this wheel event
    // is zero.
    kPhaseStationary = 1 << 1,
    // Shows that a scroll is ongoing and the scroll delta for this wheel event
    // is non-zero.
    kPhaseChanged = 1 << 2,
    // This wheel event is the last event of a scrolling sequence.
    kPhaseEnded = 1 << 3,
    // A wheel event with phase cancelled shows that the scrolling sequence is
    // cancelled.
    kPhaseCancelled = 1 << 4,
    // A wheel event with phase may begin shows that a scrolling sequence may
    // start.
    kPhaseMayBegin = 1 << 5,
    // A wheel event with momentum phase blocked shows that a scrolling sequence
    // will not be followed by a momentum fling. This should only ever be set on
    // the momentum phase of an event.
    kPhaseBlocked = 1 << 6,
}

interface GestureWheelEvent extends WheelEvent {
    phase: Phase
    momentumPhase: Phase
}

type EventNames = (
    | 'gesture-started'
    | 'gesture-detected'
    | 'gesture-in-progress'
    | 'gesture-ended'
)

interface EventData {
    gestureType: Gesture
    sumVertical: number // Horizontal
    sumHorizontal: number // Vertical
    eventCount: number
    ctrlKey: boolean
    handle: boolean
}

export class GestureDetector {
    events = new EventTarget()
    gestureData: EventData = null
    // gestureData = null
    waitForAnotherStart = true

    addEventListener(eventName: EventNames, listener: (event: CustomEvent<EventData>) => void): void {
        this.events.addEventListener(eventName, listener)
    }

    removeEventListener(eventName: EventNames, listener: (event: CustomEvent<EventData>) => void): void {
        this.events.removeEventListener(eventName, listener)
    }

    constructor() {
        this.resetGestureData()

        window.addEventListener('wheel', this.handleWheelEvent.bind(this), { passive: true })
    }

    resetGestureData() {
        this.gestureData = {
            gestureType: Gesture.UNKNOWN,
            ctrlKey: false,
            sumVertical: 0,
            sumHorizontal: 0,
            eventCount: 0,
            handle: false,
        }
    }

    // handleEventStart(ctrlKey) {
    handleEventStart(ctrlKey: boolean) {
        this.resetGestureData()
        this.gestureData.ctrlKey = ctrlKey
        this.waitForAnotherStart = false
        this.events.dispatchEvent(new CustomEvent<EventData>('gesture-started'))
    }

    handleEventDetected() {
        this.events.dispatchEvent(new CustomEvent<EventData>('gesture-detected', { detail: this.gestureData }))
    }

    handleEventProgress() {
        this.events.dispatchEvent(new CustomEvent<EventData>('gesture-in-progress', { detail: this.gestureData }))
    }

    handleEventEnded(shouldHandle: boolean) {
        this.waitForAnotherStart = true
        this.gestureData.handle = shouldHandle

        const event = new CustomEvent<EventData>('gesture-ended', { detail: this.gestureData })

        this.events.dispatchEvent(event)
        this.gestureData = null
    }

    handleEventCancel() {
        this.handleEventEnded(false)
    }

    handleEventFinished() {
        this.handleEventEnded(true)
    }

    detectEventType() {
        const absVertical = Math.abs(this.gestureData?.sumVertical)
        const absHorizontal = Math.abs(this.gestureData?.sumHorizontal)

        if (this.gestureData.ctrlKey && absVertical && !absHorizontal) {
            /**
             * TODO: Find a way to separate wheel+ctr and two-finder-pinch.
             * They are as far as I know identical in many ways
             */

            return Gesture.SCALE
        }

        if (absVertical * 2 < absHorizontal) {
            return Gesture.SWIPE
        }

        if (absHorizontal * 2 < absVertical) {
            return Gesture.SCROLL
        }

        return Gesture.UNKNOWN
    }

    handleWheelEvent({
        phase, momentumPhase,
        deltaX, deltaY,
        ctrlKey,
    // }) {
    }: GestureWheelEvent) {
        if (phase === Phase.kPhaseBegan) { // Gesture begining
            return this.handleEventStart(ctrlKey)
        }

        if (this.waitForAnotherStart) return // Ignore events

        if (phase === Phase.kPhaseCancelled) {
            return this.handleEventCancel()
        }

        /**
         * When momentum movement starts, it delays the regular phase end until the momentum ends
         * In this case, we consider momentum start phase as regulas phase end
         */
        if (phase === Phase.kPhaseEnded || momentumPhase === Phase.kPhaseBegan) { // Gesture ended
            return this.handleEventFinished()
        }

        // After this point, ignore all phases other than kPhaseChanged
        if (phase !== Phase.kPhaseChanged && momentumPhase !== Phase.kPhaseChanged) return

        // No momentum events allowed after this point
        if (momentumPhase !== Phase.kPhaseNone) return

        if (phase === Phase.kPhaseChanged || phase === Phase.kPhaseStationary) {
            // Invert numbers to have more graph-like X/Y movements
            this.gestureData.sumVertical -= deltaY
            this.gestureData.sumHorizontal -= deltaX
            this.gestureData.eventCount++

            const detectedEventType = this.detectEventType()

            // Detect EventType type
            if (this.gestureData.gestureType === Gesture.UNKNOWN) {
                if (detectedEventType !== Gesture.UNKNOWN) {
                    this.gestureData.gestureType = detectedEventType
                    this.handleEventDetected()
                // Detect conditions to cancel gestures
                } else if (this.gestureData.gestureType !== detectedEventType) {
                    // TODO: Here is the point where Win and Mac behaviour diverge
                    // Win: Continues detecting type gesture ends
                    // Mac: Stops detecting once script changes the detection result
                    // Pick what you want here :)

                    // return this.handleEventCancel()
                }
            }

            // Gesture identified and is in progress
            if (this.gestureData.gestureType !== Gesture.UNKNOWN) {
                return this.handleEventProgress()
            }

            return
        }

        throw new Error(`Unknown phase configuration ${JSON.stringify({ phase, momentumPhase })}`)
    }
}
```

**Comment by oskarblom** [comment]
Any way this could have some priority?

**Comment by iamEvanYT** [comment]
Bump. Anyone can make a PR for this? It would be very useful.

**Comment by wesleydarnell** [comment]
FYI passerbys, for Windows:
Back navigation in Windows can be enabled at the windows level in advanced gestures for 3/4 finger swiping to trigger "Backwards navigation". To support this in electron handle the app-command events.

```
browserWindow.on("app-command", (event, cmd) => {
      if (cmd === "browser-backward") {
        if (browserWindow.webContents.navigationHistory.canGoBack()) {
          browserWindow.webContents.navigationHistory.goBack();
        }
      } else if (cmd === "browser-forward") {
        if (browserWindow.webContents.navigationHistory.canGoForward()) {
          browserWindow.webContents.navigationHistory.goForward();
        }
      }
    });
```

**Comment by MatteoGauthier** [comment]
Can't we make use of the `TouchpadOverscrollHistoryNavigation` chromium flag ?

**Comment by quinn-linear** [comment]
11 years later… 👋 would be great to support

**Comment by alexb148** [comment]
This works for me:

```
const myWindow = new BrowserWindow();
myWindow.on('swipe', (event, direction) => {
  if (direction === 'left') {
    myWindow.webContents.goBack();
  } else if (direction === 'right') {
    myWindow.webContents.goForward();
  }
});
```

**Comment by daguej** [comment]
@alexb148 That doesn't really work generally.  The `swipe` event is only fired on Mac, only when using 3 fingers (not 2), and only if System Settings > Trackpad > More Gestures > Swipe between pages is set to "Swipe with two or three fingers", which is *not* the default.  Most users will not have this set.

This is [documented here](https://www.electronjs.org/docs/latest/api/base-window#event-swipe-macos).

**Comment by stasberkov** [comment]
I believe "Swipe with two or three fingers" is on by default, using "2 fingers".
