### ISSUE TITLE
Electron ipc module interaction with debugger is broken

### ISSUE THREAD

**Issue by akrieger** [atom/electron#2691]
tl;dr pausing in debugger in renderer context does not prevent additional ipc calls from invoking callbacks.

Pause the debugger inside an ipc message handler, after a console.log statement. Have the main process continue to send messages via ipc. Note in the debugger console that the log statement continues to execute despite being paused at a statement in the same function. I believe this breaks the fundamental singlethreaded assumption about javascript by allowing what appear to be multiple executions of the same code in the same context.

#### main.js
```javascript
'use strict';

var app = require('app');
var BrowserWindow = require('browser-window');
var ipc = require('ipc');
var path = require('path');
var url = require('url');

class Application {

  constructor() {
    this.setupIpc();
    this.setupWindow();
  }

  setupIpc() {
    ipc.on('hello', function(event) {
      var ping = function() {
        event.sender.send('ping', 'pong');
        setTimeout(ping, 1000);
      };
      setTimeout(ping, 1000);
    });
  }

  setupWindow() {
    this.window = new BrowserWindow({
      'auto-hide-menu-bar': true,
      width:  1024,
      height: 768,
      'min-width': 1024,
      'min-height': 768,
      resizable: true,
      frame: true,
      title: 'Test ipc app'
    });

    this.window.on('closed', function() {
      this.window = null;
    });

    this.window.openDevTools();

    this.window.loadUrl(url.format({
      protocol: 'file',
      pathname: path.resolve(__dirname, 'index.html'),
      slashes: true
    }));
  }

}

app.on('ready', function() {
  global.application = new Application();
});
```

#### index.html
```javascript
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>Test ipc app</title>
  </head>
  <body>
    <div>
      Test.
      <script type='text/javascript'>
        var ipc = require('ipc');
        ipc.on('ping', function(pong) {
          console.log('got ' + pong);
          if (1 === 1) { // Break here.
          }
        });
        ipc.send('hello', 'world');
      </script>
    </div>
  </body>
</html>
```

**Comment by akrieger** [comment]
I believe that in *practice* this does not cause problems with the app, only a debugger interaction. However, it does make actively debugging an Electron app very difficult because we cannot deterministically step through the execution of multiple sequential ipc events, since only the first one is paused and the rest continue through unhindered.

**Comment by zcbenz** [comment]
I'm merging this to #1966 since it is the same kind of bug.
