### ISSUE TITLE
Where is app.terminate()?

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2697]
I no longer see it in the docs. Was it deprecated? I think it is valuable to have a way to quit the app without invoking unload handlers for all windows.

**Comment by bpasero** [comment]
I just found out about https://github.com/atom/electron/issues/1624. Is the right way still then to call process.exit()?

**Comment by etiktin** [comment]
Yes. I'm using it and it seems to work as expected.

**Comment by tommoor** [comment]
You shouldn't use terminate as you'll get odd behaviour, such as not persisting local storage.

**Comment by zcbenz** [comment]
`app.terminate` was removed and now mapped to `app.quit`, because too many users used it instead of `app.quit` and complained local storage was not persisted.

You should just use `process.exit`, it can do the same thing, and is much more flexible.

**Comment by bpasero** [comment]
Makes sense, thanks!
