### ISSUE TITLE
XMLHttpRequest status code is 0 for "file:///" URLs

### ISSUE THREAD

**Issue by AlicanC** [atom/electron#2701]
Using version 0.30.4, this simple use case of `XMLHttpRequest` fails because `request.status` is always `0` for `file:///` URLs:

```javascript
var request = new XMLHttpRequest();

request.open('GET', 'file:///path/to/a/file.txt', true);

request.onload = function () {

  /*
    "request.responseText" is here and contains correct data,
    but since "request.status" is "0", this will fail
  */

  if (request.status >= 200 && request.status < 400) {
    // Success
  } else {
    // Fail
  }

};

request.send();
```

**Comment by AlicanC** [comment]
I guess this is the expected behavior, but for the sake of compatibility with third-party code, HTTP status codes could be returned for `file` protocol.

**Comment by zcbenz** [comment]
I can confirm the same behavior on Google Chrome, so I suggest reporting this to Chromium project, we are not going to change the standard behavior of browser in Electron. Or you can probably use a custom protocol, or some node modules to get different behaviors.
