### ISSUE TITLE
[question] protocol.InterceptHttpProtocol 

### ISSUE THREAD

**Issue by frankhale** [atom/electron#2702]
Here is what I want to do but this just goes into an infinite loop.

```js
 protocol.interceptHttpProtocol('https', function(request, callback) {
   callback({ 'url' : request.url, 'referrer' : 'https://myreferrergoeshere' });
 });
```

So I tried this but again this will infinite loop because I have no way of knowing when the callback will be finished.:

```js
function interceptHttpsProtocolAndSetReferrer() {
  protocol.interceptHttpProtocol('https', function(request, callback) {
    protocol.uninterceptProtocol('https', function() {
      callback({ 'url' : request.url, 'referrer' : 'https://myreferrergoeshere' });

      interceptHttpsProtocolAndSetReferrer();
    });
  });
}
```

I tried using a timeout, but that is a bit janky. I just want to override the referrer for **all** navigations using https. Is there a way I can accomplish this with the protocol module?

**Comment by frankhale** [comment]
This is question is probably a moot point because it doesn't seem like you can override the referrer using protocol.interceptHttpProtocol for navigations inside an iframe. The interception works but the referrer doesn't get set. Perhaps the iframe sets the referrer back to being empty?

**Comment by zcbenz** [comment]
You can set `session` to `null` to send the request in a new context to solve the infinite loop:

```js
callback({ 'url' : request.url, 'referrer' : 'https://myreferrergoeshere', 'session': null });
```

Currently we don't have a better way to modify a request before #2115 is implemented.
