### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by hhammoud01** [atom/electron#2707]
Hey all,
I'm just wondering whether electron supports deeplinking for OSX.

If it is the case, how do we do that ?

thank you very much,
regards,
Hussein.

**Comment by zcbenz** [comment]
What's deeplinking?

**Comment by hhammoud01** [comment]
when ur on an iphone and u enter in your browser a youtube link, it opens the youtube application if you have it installed.
Same goes for many other applications.
Many other examples are stated in the related wikipedia pages https://en.wikipedia.org/wiki/Deep_linking and https://en.wikipedia.org/wiki/Mobile_deep_linking (for example http://en.wikipedia.org/wiki/Deep_linking#Example is a deep link)

**Comment by zcbenz** [comment]
There is no deep linking on desktop systems, the closest thing is `shell.openExternal`.

**Comment by MichaelOstermann** [comment]
There is something like that, when you open for example `macappstores://itunes.apple.com/us/app/xcode/id497799835?mt=12` in the browser (has to be opened via a user action like a click, not possible programmatically/typing in the url bar) it will actually open the mac appstore and show the page for xcode, [here's](http://fredandrandall.com/blog/2011/07/30/how-to-launch-your-macios-app-with-a-custom-url/) an article describing how to do that!

**Comment by bbnnt** [comment]
@MichaelOstermann  in there a way to declare a `macappstores://` scheme in elecron  ?

**Comment by VojtechBartos** [comment]
There is definitely deep linking on Mac OS X and it works in same way as on iOS

@bbnnt @hhammoud01 i haven't found way how you can do it directly via electron, but its definitely doable during packaging via [electron-packager](https://github.com/maxogden/electron-packager) via `protocols` attribute

```js
import packager from 'electron-packager'

const options = {
    dir: './'
    version: '0.34.1', // electron version
    platform: 'darwin',
    arch: 'x64',
    'app-version': packageJson.version,
    protocols: [
      {
        name: 'NameOfYourApp',
        schemes: ['nameofyourapp']
      }
    ]
  };

  packager(options, err => {
     if (err) throw err;
  });
```

**Comment by Ondross** [comment]
You can setup deep-linking (a protocol with parameters) in your app code, using `app.setAsDefaultProtocolClient()`

See: http://electron.atom.io/docs/all/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows

**Comment by oikonomopo** [comment]
[From mine similar Q/A at SO][1]:
It's about opening app and pass parameters with deep linking using Electron for both platforms (macOS/win32).
![alt text](https://raw.githubusercontent.com/oikonomopo/electron-deep-linking-osx/master/electron-deeplinking-osx-example.gif)

----------

> Minimal electron project with deep linking capabilities in macOS/win32 platforms (Single Instance Application) ['electron-deep-linking-mac-win' on GitHub][2].


----------

`package.json`:

    {
      "name": "electron-deeplinking-macos-win32",
      "version": "0.0.1",
      "description": "Minimal Electron application with deep inking (macOS/win32)",
      "main": "main.js",
      "scripts": {
        "start": "electron .",
        "pack": "build --dir",
        "dist": "build"
      },
      "repository": "https://github.com/oikonomopo/electron-deep-linking-osx",
      "author": "oikonomopo",
      "license": "CC0-1.0",
      "devDependencies": {
        "electron": "1.6.6",
        "electron-builder": "17.1.2"
      },
      "build": {
        "appId": "oikonomopo.electron-deeplinking-macos-win32",
        "protocols": {
          "name": "electron-deep-linking",
          "schemes": ["myapp"]
        },
        "mac": {
          "category": "public.app-category.Reference"
        },
        "win": {
        }
      }
    }


----------

 `main.js`:

    const {app, BrowserWindow} = require('electron')
    // Module with utilities for working with file and directory paths.
    const path = require('path')
    // Module with utilities for URL resolution and parsing.
    const url = require('url')
    
    // Keep a global reference of the window object, if you don't, the window will
    // be closed automatically when the JavaScript object is garbage collected.
    let mainWindow
    
    // Deep linked url
    let deeplinkingUrl
    
    // Force Single Instance Application
    const shouldQuit = app.makeSingleInstance((argv, workingDirectory) => {
      // Someone tried to run a second instance, we should focus our window.
    
      // Protocol handler for win32
      // argv: An array of the second instance’s (command line / deep linked) arguments
      if (process.platform == 'win32') {
        // Keep only command line / deep linked arguments
        deeplinkingUrl = argv.slice(1)
      }
      logEverywhere("app.makeSingleInstance# " + deeplinkingUrl)
    
      if (win) {
        if (win.isMinimized()) win.restore()
            win.focus()
      }
    })
    if (shouldQuit) {
        app.quit()
        return
    }
    
    function createWindow () {
      // Create the browser window.
      mainWindow = new BrowserWindow({width: 800, height: 600})
    
      // and load the index.html of the app.
      mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true
      }))
    
      // Open the DevTools.
      mainWindow.webContents.openDevTools()
    
      // Protocol handler for win32
      if (process.platform == 'win32') {
        // Keep only command line / deep linked arguments
        deeplinkingUrl = process.argv.slice(1)
      }
      logEverywhere("createWindow# " + deeplinkingUrl)
    
      // Emitted when the window is closed.
      mainWindow.on('closed', function () {
        // Dereference the window object, usually you would store windows
        // in an array if your app supports multi windows, this is the time
        // when you should delete the corresponding element.
        mainWindow = null
      })
    }
    
    // This method will be called when Electron has finished
    // initialization and is ready to create browser windows.
    // Some APIs can only be used after this event occurs.
    app.on('ready', createWindow)
    
    // Quit when all windows are closed.
    app.on('window-all-closed', function () {
      // On OS X it is common for applications and their menu bar
      // to stay active until the user quits explicitly with Cmd + Q
      if (process.platform !== 'darwin') {
        app.quit()
      }
    })
    
    app.on('activate', function () {
      // On OS X it's common to re-create a window in the app when the
      // dock icon is clicked and there are no other windows open.
      if (mainWindow === null) {
        createWindow()
      }
    })
    
    // Define custom protocol handler. Deep linking works on packaged versions of the application!
    app.setAsDefaultProtocolClient('myapp')
    
    // Protocol handler for osx
    app.on('open-url', function (event, url) {
      event.preventDefault()
      deeplinkingUrl = url
      logEverywhere("open-url# " + deeplinkingUrl)
    })
    
    // Log both at dev console and at running node console instance
    function logEverywhere(s) {
        console.log(s)
        if (mainWindow && mainWindow.webContents) {
            mainWindow.webContents.executeJavaScript(`console.log("${s}")`)
        }
    }

main.js code description:

 - At `let deeplinkingUrl` we keep the provided url.

 - At macOS platform this is captured at [`'open-url'` event][3], we set it with `deeplinkingUrl = url`! (See `// Protocol handler for osx`)

 -  At win32 platform this is saved at [`process.argv`][4] together with other arguments. To get only the provided url, `deeplinkingUrl = argv.slice(1)`.  (See `// Protocol handler for win32`)

 -  As [@Aurélien Nicolas][5] mentions, at [`app.makeSingleInstance` method][6] we check in which platform we are and we set `deeplinkingUrl` accordingly! If we are at win32 platform, the url is located at `argv` variable from callback, else at macOS should have already been set at `'open-url'` event! (See `// Force Single Instance Application`)


  [1]: https://stackoverflow.com/questions/43912119/open-app-and-pass-parameters-with-deep-linking-using-electron-macos
  [2]: https://github.com/oikonomopo/electron-deep-linking-mac-win
  [3]: https://electron.atom.io/docs/api/app/#event-open-url-macos
  [4]: https://nodejs.org/api/process.html#process_process_argv
  [5]: https://stackoverflow.com/questions/38458857/electron-url-scheme-open-url-event#answer-39297057
  [6]: https://electron.atom.io/docs/api/app/#appmakesingleinstancecallback

**Comment by ppianist** [comment]
It's not working on Windows.
I'm getting this error from the above sample project.

![image](https://user-images.githubusercontent.com/42444925/100995644-ea32a780-350c-11eb-85c8-61f20f3dcfc1.png)

**Comment by asparamancer** [comment]
@ppianist it only works in a packaged app, it looks like you're running from terminal

**Comment by p32929** [comment]
Any way to make it work in dev?
