### ISSUE TITLE
Windows: Shell.moveItemToTrash() fails for drives created with subst

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2715]
- create a drive using the subst command on a folder (https://technet.microsoft.com/en-us/library/bb491006.aspx)
- call Shell.moveItemToTrash() with a path from that drive

=> the file does not end up in the trash 
=> the return value from Shell.moveItemToTrash() does not indicate this failure

**Comment by zcbenz** [comment]
Electron is calling `SHFileOperation` to remove the file, not sure if it is a limitation of the API or we need to pass some flags.

**Comment by zcbenz** [comment]
Fixed by #3337.
