### ISSUE TITLE
changing menu label at runtime ?

### ISSUE THREAD

**Issue by rogergl** [atom/electron#2717]
Is it possible to change a menu label at runtime ?

Right now I'm doing this:

var menu = Menu.getApplicationMenu();
menu.items[1].submenu.items[2].visible = true;
menu.items[1].submenu.items[2].label = "123";

This makes the menu visible but does not change the label.

**Comment by zcbenz** [comment]
Currently you have to call the `setApplicationMenu` again to apply the changes, I'm merging this to #528.

**Comment by meowlab** [comment]
Hi @zcbenz 
Even call `setApplicationMenu` again also doesn't work.
For example:
```javascript

var app = require('electron').app,
    Menu = require('electron').Menu,
    BrowserWindow = require('electron').BrowserWindow;

var mainWindow = null;

app.on('ready', function() {
  mainWindow = new BrowserWindow({ width: 600, height: 400 })
  var m = Menu.buildFromTemplate([{
    label: 'test',
    submenu: [{label: 'test-test'}]
  }, {
    label: 'hello',
    submenu: [{label: 'hello-test'}]
  }]);

  m.items[1].submenu.items[0].label = 'hello-hello';
  console.log(m.items[1].submenu);

  mainWindow.setMenu(m);
  Menu.setApplicationMenu(m);
});

```
In console you can see label is changed to 'hello-hello', but the menu shown is still 'hello-test'
Is it by design?

Thanks

**Comment by zcbenz** [comment]
@meowlab The label attribute can not be changed dynamically, you have to create a new `Menu` object with `Menu.buildFromTemplate`.

**Comment by soulreaper02** [comment]
You can push or unshift menu items based on your need. For example
if (process.env.NODE_ENV !== 'production') {
    mainMenuTemplate.push({
        label: 'Dev Tools',
        submenu: [{
            label: 'Open Debbuger',
            accelerator: process.platform == 'darwin' ? 'Command+I' : 'Ctrl+I',
            click(item, focusedWindow) {
                focusedWindow.toggleDevTools();
            }
        }, {
            role: 'reload'
        }]
    })
}

**Comment by ltfschoen** [comment]
Thanks for your help, I was able to implement it this way https://github.com/paritytech/fether/pull/415

**Comment by abhimatta999** [comment]
> Currently you have to call the `setApplicationMenu` again to apply the changes, I'm merging this to #528.

have to call 'setApplicationMenu' from  renderer or from main.?
