### ISSUE TITLE
document.onmousemove causes momery leak

### ISSUE THREAD

**Issue by xuanhun** [atom/electron#2720]
the code is so simple:

    <body>
    <script>
        document.onmousemove = function () {
      
        };
    </script>
    </body>
when started:
![20150906](https://cloud.githubusercontent.com/assets/2384516/9702408/1ff42fb6-548e-11e5-9493-24d693391fa0.png)

When moving the mouse on document , memory has been growing up.
![20150906120152](https://cloud.githubusercontent.com/assets/2384516/9702437/7c7776b6-548f-11e5-8733-f92bbb6f9cca.png)

**Comment by zcbenz** [comment]
Lots of things in Chromium are lazy-initialized, so the memory increase from 8M to 37M is because of initialization of mouse handling code, not memory leak. And 37M is a quite normal number for web page.
