### ISSUE TITLE
[question] registerUrlSchemeAsBypassingCsp for <webview>

### ISSUE THREAD

**Issue by TasukuUno** [atom/electron#2724]
I want to do xhr request from webview to main process by custom protocol url. If in renderer process html (not in webview), I can allow only my protocol with `webFrame.registerUrlSchemeAsBypassingCsp()`. But is there any way to do it in webview? or I have to set `disablewebsecurity`?

**Comment by zcbenz** [comment]
You can call it in the preload script of webview.
