### ISSUE TITLE
[0.32.0] Session is not persistent in Electron

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#2735]
Hello, 
While running our test cases, we found that session is not persistent in app. When we close the  app, session is some how getting cleared. so Next time when we load the app. Our auth page is shown.

based on this , i have created a sample "gmail" demo. Which exhibits the same thing.

Working Electron Engine versions : <= 0.30.3
Defective Electron Engine versions : > 0.30.3

```
https://github.com/kamesh-a/electron-samples/tree/master/sessionNotPersistent
```

Please take a look, Let us know if needed any info. We would be glad to help.

**Comment by kamesh-a** [comment]
Tested with 0.32.0, Same result,
Steps:
a. Login in gmail after successful login.
b. close the app
c. restart the app.

Expected behavior :  landing into mailbox, without asking to user info.
current behavior : Asks user info everytime when we start the app.

Tested in  Mac OS and Windows

**Comment by deepak1556** [comment]
Unable to reproduce on linux, the test app works fine.

**Comment by kamesh-a** [comment]
@deepak1556 We have not tested it on linux, We don't have development env in linux. Basically we create app only for MAC OS X yosemite and mavericks and windows 7,8,10

**Comment by kamesh-a** [comment]
Thanks @zcbenz so it will store disk, not keep in memory. Is there any way i could test this. I assume only way now it download the code and build it or you have pre-test build before release.

Once a again Great work by Electron team and community.

**Comment by kamesh-a** [comment]
@zcbenz Thank you for fixing, @deepak1556 I can confirm that, our test sample was working fine in linux, I setup Ubuntu 64bit box. But our primary targets are mac & win for now. thanks for your reply.

Really appreciate all your works.  I would love to dive in test the build. Is there any way i could do it. I guess i have to compile the atom project to get updated build. If there is any test build please point it to me. we would be glad to test it.

Thanks again.

**Comment by zcbenz** [comment]
I'm cutting a new release soon because of a regression in v0.32.0.

**Comment by kamesh-a** [comment]
Okay :+1:
