### ISSUE TITLE
Default menu bar in new opened page

### ISSUE THREAD

**Issue by Daaru00** [atom/electron#2736]
It's possible to disable default menu bar in new page? 
If I open a new page (e.g social login page) the menu bar is set with edit, view, window, help, how I can remove that? In the main windows I used:
```
mainWindow.setMenu(null);
```
but in external page I can't do this.

**Comment by zcbenz** [comment]
The default menu will gone after you packaged your app into Electron, you can also use follow trick to remove the default menu too:

```js
setImmediate(function() {
  app.setApplicationMenu(null);
});
```

**Comment by Daaru00** [comment]
Sorry, I do not have try to pack it.
thank you!
