### ISSUE TITLE
Best pratices to dev a new app

### ISSUE THREAD

**Issue by jonatasfreitasv** [atom/electron#2737]
I am beginning to develop an open-source desktop app.

I'm wondering which stack to use for development.

What is best for the electron and that will attract more contributors?
Coffeescript? Typescript? Native JS?
Angularjs? React? Backbone?

And for unit testing ? Karma with Jasmine? NodeUnit?

**Comment by carlosperate** [comment]
This is the kind of question that belong to the forum, not to the issue tracker: https://discuss.atom.io/c/electron

**Comment by jonatasfreitasv** [comment]
Nice !!! I did not know of the existence of this tool.
