### ISSUE TITLE
New window communication on main thread

### ISSUE THREAD

**Issue by zackarychapple** [atom/electron#2738]
As per https://discuss.atom.io/t/how-can-i-open-a-panel-in-a-new-window/20635 there is a need to be able to break out packages to a new windows and still have them be able to communicate on the same thread as the main window.  This is particularly useful when working on multiple monitors.

**Comment by paulcbetts** [comment]
@zackarychapple This is more of an Atom thing - Electron will never run multiple windows in the same process, so the Atom team needs to come up with a new abstraction for talking between windows more easily

**Comment by zackarychapple** [comment]
@paulcbetts how does electron communicate between windows? I'm surprised that Kitematic or someone else is not requesting the same thing.

**Comment by zcbenz** [comment]
In Electron each window has its own ID, so as long as you know the ID of target window you can use messages to arbitrary window with `ipc` module. In your case you can return the ID of new window to the window that created it, and in the new window you can also pass the ID of the window that created it, this way the two windows can easily communicate with each other.

But as @paulcbetts said, it needs an abstraction in Atom to make the whole thing easier, there are also [a few modules](https://www.npmjs.com/search?q=electron+ipc) provided some wrappers.
