### ISSUE TITLE
Google social login not work

### ISSUE THREAD

**Issue by Daaru00** [atom/electron#2739]
Google social login with plusone.js client not work, signin callback is not fired when login is completed in other window.

this is my code (tested with simple webpage)
```javascript 
<body>
    <span id="signinButton">
      <span
        class="g-signin"
        data-callback="signinCallback"
        data-clientid="MYCLIENTID.apps.googleusercontent.com"
        data-cookiepolicy="none"
        data-requestvisibleactions="http://schemas.google.com/AddActivity"
        data-scope="https://www.googleapis.com/auth/plus.login https://www.google.com/analytics/feeds/ https://mail.google.com/mail/feed/atom/ https://www.google.com/calendar/feeds/"
        data-accesstype="offline" data-approvalprompt="force">
      </span>
    </span>


    <script type="text/javascript">

        // This function will attempt to remove a cookie from all paths.
        var pathBits = location.pathname.split('/');
        var pathCurrent = ' path=';

        // do a simple pathless delete first.
        document.cookie = name + '=; expires=Thu, 01-Jan-1970 00:00:01 GMT;';

        for (var i = 0; i < pathBits.length; i++) {
            pathCurrent += ((pathCurrent.substr(-1) != '/') ? '/' : '') + pathBits[i];
            document.cookie = name + '=; expires=Thu, 01-Jan-1970 00:00:01 GMT;' + pathCurrent + ';';
        }

        (function () {
            var po = document.createElement('script');
            po.type = 'text/javascript';
            po.async = true;
            po.src = 'https://apis.google.com/js/client:plusone.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(po, s);
        })();

        function signinCallback(authResult) { // this is not fired
            console.log(authResult);
        }
    </script>
</body>
```

**Comment by Daaru00** [comment]
neither add callback in global scope
```javascript
    (function () {
            var po = document.createElement('script');
            po.type = 'text/javascript';
            po.async = true;
            po.src = 'https://apis.google.com/js/client:plusone.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(po, s);

            function signinCallback(authResult) { // this is not fired
                console.log(authResult);
            }
        })();
```
or force adding it in window object

```javascript
    (function () {
            var po = document.createElement('script');
            po.type = 'text/javascript';
            po.async = true;
            po.src = 'https://apis.google.com/js/client:plusone.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(po, s);

            window["signinCallback"] = function(authResult) { // this is not fired
                console.log(authResult);
            }
        })();
```
Google client library can reach the callback because it not fire error "Callback function named "signinCallback" not found" (it fired if I remove the function declaration).

so how can I implement Google social login?

**Comment by zcbenz** [comment]
How are you running the page? I got `Invalid parameter value for origin: Missing authority: file://` error when clicking the button.

**Comment by Daaru00** [comment]
Yes, but I serve the login page with nodejs express server (deactivated when the user is logged). 
so, ```localhost``` is a valid origin

**Comment by zcbenz** [comment]
I now get `Error: invalid_client`, I understand if you don't want to expose your real client ID, but can you maybe provide a temporary one? Otherwise it would be very hard to look into this issue.

**Comment by Daaru00** [comment]
No problem,
I activated a test client:
Client ID: 
`904967667397-aqkeevit7nm68vj97cc2a64c2pm8ndqd.apps.googleusercontent.com`
Authorized JavaScript origins (pay attention to use 2323 port in express server): 
`http://localhost:2323`

**Comment by zcbenz** [comment]
Which version of Electron are you using? v0.31.2 fixed a similar issue before.

**Comment by Daaru00** [comment]
I used exactly v0.31.2 on Linux OS

**Comment by zcbenz** [comment]
The google login is using `window.opener.document` to call the callback in parent window, which Electron doesn't support for now, I'm merging this to #1865.

**Comment by harishankarjoshi** [comment]
you can use this code
first install "electron-google-oauth" pachage by npm
npm install --save electron-google-oauth

than implement this code.

const electronGoogleOauth = require('electron-google-oauth');
            const browserWindowParams = {
                'use-content-size': true,
                center: true,
                show: true,
                resizable: false,
                'always-on-top': true,
                'standard-window': true,
                'auto-hide-menu-bar': true,
                'node-integration': false
            };

            const googleOauth = electronGoogleOauth(browserWindowParams);

            (async() => {

                // retrieve  authorization code only 
                const authCode = await googleOauth.getAuthorizationCode(
                    ['https://www.google.com/m8/feeds'],
                    'client_key.apps.googleusercontent.com',
                    'secret',
                    'urn:ietf:wg:oauth:2.0:oob'
                );
                console.dir(authCode);

                // retrieve access token and refresh token 
                const result = await googleOauth.getAccessToken(
                    ['https://www.google.com/m8/feeds'],
                    'client_key.apps.googleusercontent.com',
                    'secret',
                    'urn:ietf:wg:oauth:2.0:oob'
                );
                console.dir(result);

            })();
