### ISSUE TITLE
Overlay scrollbars on top of all content

### ISSUE THREAD

**Issue by carlosperate** [atom/electron#2740]
I'm testing this using v0.31.2-32bit on Windows 8.1 64 bit.

This might be a bug in the chrome engine, I'm not sure, but the overlay-scrollbars stay on top of any content:

![scrollbars](https://cloud.githubusercontent.com/assets/4189262/9747054/43ad2fb6-5673-11e5-87a3-d70be93c8fe0.png)

Also, it would be quite useful if the scrollbar changed from a dark overlay to a light one if the background colour itself is dark (or having a thin white border would also work great). As it is really hard to tell there is another scrollbar on the bottom right corner.

**Comment by zcbenz** [comment]
I'm not sure whether it is a bug of your HTML or Chrome engine, but I suggest dumping your page into an independent HTML page and testing it in different browsers, and then report it to Chromium's issues tracker. Electron renders the page exactly the same with Chrome browser, so even if it is a bug of Chrome browser we are not able to fix it on our side.

**Comment by carlosperate** [comment]
Just tested in chrome 45.0.2454.85 and canary 47.0.2505.0 setting the `chrome://flags` and experienced the same issue, so I'll try to create a minimum example and report it to the Chromium tracker.

One thing I've noticed though is that Chrome does indeed have a lighter border around the overlay scrollbars (and they are slightly thicker) making them more visible, is there any way to force electron to do the same?

![scroll](https://cloud.githubusercontent.com/assets/4189262/9779534/796b2336-5774-11e5-82d1-3eadaacccbc8.png)

**Comment by zcbenz** [comment]
> One thing I've noticed though is that Chrome does indeed have a lighter border around the overlay scrollbars (and they are slightly thicker) making them more visible, is there any way to force electron to do the same?

Is it a new behavior in Chrome 47? The drawing of scrollbars should be the same in Electron v0.32.x and Chrome 45.

**Comment by carlosperate** [comment]
No, both 45.0.2454.85 (32 bit) and 47.0.2505.0 (64 bit) have the same scrollbars. I'm also using electron 0.32.1, so it should have the v45 engine.

This might be a very long shot, but could it be that Chrome detects the touch screen in my laptop and increases the scrollbars for touch, and somehow electron does not?

**Comment by carlosperate** [comment]
>This might be a very long shot, but could it be that Chrome detects the touch screen in my laptop and increases the scrollbars for touch, and somehow electron does not?

Nope, just found a flag to disable touch support in Chrome and the scrollbars are still rendered larger and with the lighter border.
