### ISSUE TITLE
Debugging: wrong place to pause on first line

### ISSUE THREAD

**Issue by 3y3** [atom/electron#2741]
If electron started with `--debug-brk` flag. He pauses on line
```
// Hello, and welcome to hacking node.js!
```
This is a first executable line of `node/src/node.js` and this is wrong place for pausing.

Do you want an extended information here? Or current description is enough?

**Comment by zcbenz** [comment]
I thought it was the right place to pause, but it seems that Node.js pauses on the first line of user's script? We should do the same in Electron then.

**Comment by TayNelson** [comment]
I'd really like this to be fixed. I currently can't get `debug-brk` working with any of the debuggers which I have tried.

Looking at Node.js' [`/src/node.cc`](https://github.com/nodejs/node/blob/2e6ece44e176f70a9c5c03879f4c98b912c7afbd/src/node.cc#L3928-L3938):

```cc
// Start debug agent when argv has --debug
if (instance_data->use_debug_agent())
  StartDebug(env, debug_wait_connect);

LoadEnvironment(env);

env->set_trace_sync_io(trace_sync_io);

// Enable debugger
if (instance_data->use_debug_agent())
  EnableDebug(env);
```

[`LoadEnvironment`](https://github.com/nodejs/node/blob/2e6ece44e176f70a9c5c03879f4c98b912c7afbd/src/node.cc#L2967) will load [`/src/node.js`](https://github.com/nodejs/node/blob/master/src/node.js), and call its top-level function, passing the `process` object:

```cc
Local<Value> arg = env->process_object();
f->Call(global, 1, &arg);
```

It appears that they are only enabling the debug agent after the environment has been loaded. Perhaps this is what causes Node.js to *not* break as early as Electron.
