### ISSUE TITLE
`node-integration` doesn't work with `window.open` on 0.32.0

### ISSUE THREAD

**Issue by dataich** [atom/electron#2742]
Following code could disable node-integration on 0.31.2.

```js
window.open('http://example.com', 'example', 'node-integration=0');
```

After upgraded electron version to 0.32.0, `node-integration` parameter doesn't work with `window.open`.

**Comment by zcbenz** [comment]
It is a bug that if it doesn't work, though `node-integration` has been moved to `web-preferences` we are still keeping backward-compatitibily.

**Comment by dataich** [comment]
Thanks @zcbenz !
