### ISSUE TITLE
Loading app in with http protocol instead of file

### ISSUE THREAD

**Issue by macchie** [atom/electron#2758]
Hi everyone, is there any way to start a webserver along with the electron app? I couldnt find any tutorial that explained this.. basically all i need to do is to use google analytics api with oauth authentication, localhost is fine as a javascript origin for google, but file:// is not.. any idea on how to implement this? A simple gulp/grunt server launch would be enough ;)

**Comment by frankhale** [comment]
As a matter of fact I was looking into this today and decided to hack together a solution. I'll post the sample to Github when I get home.

**Comment by frankhale** [comment]
Here is what I came up with earlier today. 

https://github.com/frankhale/electron-with-express

**Comment by zcbenz** [comment]
@frankhale It looks awesome!

For future questions, I suggest asking in the [forum](https://discuss.atom.io/c/electron).

**Comment by macchie** [comment]
i finally managed to do it before you posted your solution but i will take a look of course :) thanks a lot, ill post my own solution too of course!

**Comment by frankhale** [comment]
Awesome I'd love to see it!

**Comment by macchie** [comment]
@frankhale Enjoy!

https://github.com/macchie/electron_plus_http

**Comment by macchie** [comment]
It currently includes a simple ionic/angular app ;)

**Comment by frankhale** [comment]
Thanks I'll have a look!

**Comment by jagadeeshkoka** [comment]
Hey guys,  your links are broken would you mind to post it again?
