### ISSUE TITLE
Mac OS X 10.8.5 and reliance on "en.lproj"

### ISSUE THREAD

**Issue by smebberson** [atom/electron#2759]
I've found that on Mac OS X 10.8.5, Electron requires the "en.lproj" folder that comes with the default build of Electron. If you delete that folder, it fails to load with a `Segmentation Fault: 11` error.

This doesn't occur on anything newer than 10.8.5. I have a hunch, although untested, that it also causes Electron to not load on 10.7.5.

To recreate:

- download the latest release from https://github.com/atom/electron/releases
- find the `Electron.app` file, and right-click and choose "Show Package Contents"
- navigate to `Contents/Resources`
- either delete or rename `en.lproj`

If you try starting, you should see that it errors. As a side point, you can delete any other `.lproj` folder.

Thanks,
Scott.

**Comment by zcbenz** [comment]
The `*.lproj` files are required by Electron and Chromium for certain things to work, and we don't guarantee Electron would work if you remove them.

**Comment by smebberson** [comment]
Okay, that's fair enough. Seems like it's an omission from the documenetation at http://electron.atom.io/docs/v0.32.0/tutorial/application-distribution/ perhaps?
