### ISSUE TITLE
shell.openItem() blocks execution until external application exits

### ISSUE THREAD

**Issue by jsayol** [atom/electron#2761]
**Electron version**: tried 0.30.4 and 0.32.1, both affected
**OS**: Xubuntu 15.04

When opening a file through an external application via shell.openItem() the script's execution in halted until shell.openItem() returns, which happens when the external application exits (or is manually closed).

**Comment by zcbenz** [comment]
I can not find a case that `openItem` is blocking, can you provide an example?

**Comment by jsayol** [comment]
I created a small project to reproduce it. Just clone it and run it:

```
$ git clone https://github.com/jsayol/electron-openitem-test.git
$ cd electron-openitem-test
$ npm start
```

I ran some tests and, apparently, it doesn't always block. If the external app is already open before launching shell.openItem() then the script execution continues as normal. For example, opening the text file while my text editor (medit) is already open simply creates a new tab and electron goes on as expected, but it blocks if electron has to launch the text editor.

I don't have any other system other than my Xubuntu to test this right now so It *might* only happen on XFCE, I don't know. Let me know if you can reproduce the problem with this example.

**Comment by jsayol** [comment]
As a side note, I'm on an extremely slow internet connection right now and I didn't have the time to test this with the latest electron version (seriously, it would have taken over an hour to download) so I went with the one I already had installed, 0.32.1.

You might want to tweak package.json and test this with other versions to see if it affects the behavior at all.

**Comment by zcbenz** [comment]
Can you run this command under terminal and see if it blocks?

```bash
$ xdg-open ./test.mp4
```

**Comment by jsayol** [comment]
Dammit, it does. I should have checked that myself first, sorry for wasting your time.
