### ISSUE TITLE
WebGL not working on Windows Embedded Sp1

### ISSUE THREAD

**Issue by jorgericardograca** [atom/electron#2763]
Hi all,

I have an issue with Electron v0.32.2 x64 build that Chromium does not have in Windows Embedded Standard:
![electronopenglissue](https://cloud.githubusercontent.com/assets/14205438/9814090/27050d0e-5883-11e5-9fc3-d513273e1115.png)

I am trying to open get.webgl.org in electron but it cannot initialize the egl. Any ideas?

**Comment by zcbenz** [comment]
Can you try if WebGL works in Chrome 45?

**Comment by jorgericardograca** [comment]
![electronopenglissue](https://cloud.githubusercontent.com/assets/14205438/9816565/a99d3f7c-5895-11e5-9e66-b6886f46ca24.png)

v45 as requested the exact same.

**Comment by jorgericardograca** [comment]
This is my builds fault, the prebuilt exe works fine. Any idea on what could cause this?
