### ISSUE TITLE
Not necessary escape in Dialog

### ISSUE THREAD

**Issue by KiYugadgeter** [atom/electron#2766]
When I invoked dialog.showSaveDialog from main process with ipc, There is a not necessary escape in replacing dialog like attached picture.
![2015-09-10 23 30 52](https://cloud.githubusercontent.com/assets/7894040/9831139/d2926df8-5985-11e5-9f05-9e8c5f57fc16.png)

**Comment by zcbenz** [comment]
This is weird, are you using El Capitan?

**Comment by Kimura1** [comment]
I using OS X 10.10.5 (Yosemite)
I don't know this bug causes from which version.

**Comment by zcbenz** [comment]
Unable to reproduce in 0.36.2 anymore.
