### ISSUE TITLE
[windows] starting crash reporter from renderer blocks for 1-2s

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2769]
This happens with 0.32.2, I did not happen with 0.27.3. We start the crash reporter from the renderer as part of our startup and I can see with 0.32.2 that this seems to block the renderer process for 1-2 seconds. This results in the entire UI being blocked and not doing anything for this period.

Did anything change in this area that could cause this? Our workaround for now is to not start the crash reporter from the renderer.

**Comment by bpasero** [comment]
Btw I think it also blocks from the main side.

**Comment by bpasero** [comment]
@zcbenz could it be that electron is now waiting until the crash reporter is up and running and before it did not? I see two commits that might have an impact: https://github.com/atom/electron/commit/db58048077f604f46814a7e5dff3d87a1fd7e3f3 and https://github.com/atom/electron/commit/c872b1a770c49df662fded29005ab760ed2dfe0c

**Comment by zcbenz** [comment]
It seems very likely.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
@zcbenz I am a bit puzzled, I see this again with 0.34.1 but have no clue what changed in this one week.

**Comment by zcbenz** [comment]
@bpasero Can you try running the crash service process first:

```js
set ATOM_SHELL_INTERNAL_CRASH_SERVICE=1
electron.exe --v=1 --application-name=AppName --reporter-url=somewhere
```

and then try whether the `crashReporter.start()` blocks?

(`AppName` has to match your app's name.)

**Comment by bpasero** [comment]
@zcbenz at my Windows at home I cannot reproduce the delay with the crash reporter anymore so maybe I did something wrong at work. I will check this out again next week from Work to see if its an issue on my end and let you know!

**Comment by bpasero** [comment]
Nevermind I think this was a red herring.
