### ISSUE TITLE
window.open(url) does not respect { show: false }

### ISSUE THREAD

**Issue by matthewmueller** [atom/electron#2771]
If we initialize a browser window with `{ show: false }`, but the browser window runs JS code that opens a javascript window, then a new browser window will open, regardless of `{ show: false }`

Here's an example:

```js
var app = require('app')
var BrowserWindow = require('browser-window');

app.on('ready', function() {
  win = new BrowserWindow({ show: false });
  win.webContents.loadUrl('http://output.jsbin.com/cekonip/1');
  win.webContents.once('did-finish-load', function() {
    console.log('loaded!');
  })
})
```

The jsbin runs the following code:

```js
window.open('http://google.com')
```

**Comment by zcbenz** [comment]
The Web standard says nothing about how should `window.open` behave when the window is hidden, but I think it is quite reasonable for the child window to inherit parent window's properties.

**Comment by matthewmueller** [comment]
+1 that sounds like a great default.

**Comment by bchr02** [comment]
+1 I agree

**Comment by mike-thompson-day8** [comment]
+1 -  this has become important for us
