### ISSUE TITLE
64bit crash right after start up on windws 8

### ISSUE THREAD

**Issue by kuno** [atom/electron#2775]
We build a app based on electron, the 32bit version works well. But the 64bit version crash on windows 8 right after it was started up.

Even the 'clean' version electron which download from https://github.com/atom/electron/releases (tested version on `0.29.2` and `0.32.2`) can not start.

Here is the message came from the command line

![electron](https://cloud.githubusercontent.com/assets/161327/9846847/9454cc4c-5b07-11e5-9e36-186ec379114e.PNG)

In some ways, it looks like  this issue https://github.com/mapbox/mapbox-studio/issues/1190

Those are all I know.

**Comment by zcbenz** [comment]
Do you have Visual Studio installed? If you have then what's the version of it?

**Comment by kuno** [comment]
We  dont have a completed installation of VS, but have this:
![installation](https://cloud.githubusercontent.com/assets/161327/9867152/fde107da-5b9c-11e5-9078-02d76672d29f.PNG)

**Comment by zcbenz** [comment]
Can Chrome run on your machine?

**Comment by kuno** [comment]
@zcbenz 

Yes, both 32bit and 64bit version of chrome running without problems.

**Comment by zcbenz** [comment]
Do you have any anti-virus program running? And if you have can you try turning them off?

**Comment by kuno** [comment]
No there are not anti-virus program, and I'd also turned off the windows defender.

**Comment by zcbenz** [comment]
I'm afraid the only way to get more information is to use windbg to get a full stack trace on your machine, instructions can be found at https://github.com/atom/electron/issues/3208.
