### ISSUE TITLE
Window with minimum size will stop rendering when the window is moved

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#2779]
Hello,
We found an issue, when render-er is getting completely stalled, when we move the app position after loading the contents. Issues arises due to two properties when we tried to include in BrowserWindow.
( Note :  we are not sure what other props exhibit this behavior )
```
"min-height", "min-width" in BrowserWindow
```
Steps to reproduce :

1. Load the app.
2. Let it load the "< any URL>" and complete it.
3. now, move the window to any position, app is hanged up until we do a manual resize.
4. Manual resize, restores the state, back

```
sample app : https://github.com/kamesh-a/electron-samples/tree/master/RenderStalls
```

Works fine in Engines :  <= 0.31.x
Defective behaviour found in :  0.32.x

Please let us know , if you need any info regarding, it we would be glad to help.

**Comment by kamesh-a** [comment]
I forgot to mention, this issue is WINDOWS specific. Mac works fine with the latest engine 0.32.x

win 7, 8 and 10

**Comment by smebberson** [comment]
My users are also experiencing this...

**Comment by smebberson** [comment]
@zcbenz, do you see this getting some attention anytime soon?

**Comment by smebberson** [comment]
@zcbenz, in fact, I just ran a test with 0.33.9 and the issue seems to have disappeared. @kamesh-a, can you confirm?

**Comment by kamesh-a** [comment]
@zcbenz and @smebberson i have checked the same test sample with 0.33.9 and 0.34.x version of electron. It seems to work fine. We can close this card.
