### ISSUE TITLE
How to get linux distro?

### ISSUE THREAD

**Issue by sergiovilar** [atom/electron#2780]
Hello, 

there's a way to get the current linux distro that the Electron app is running?

Thank  you!

**Comment by paulcbetts** [comment]
Nope. There's no way to do this even in native Linux code, nobody can agree in the Linux world on even something this simple.

**Comment by frankhale** [comment]
Can't you shell out and call uname -a and get the output of that? Assuming
it's installed.

**Comment by paulcbetts** [comment]
`uname -a` usually works, but it doesn't tell you the distro info, just the kernel info

**Comment by zcbenz** [comment]
There are [lots of ways](http://www.cyberciti.biz/faq/find-linux-distribution-name-version-number/) to get it, but it took efforts to work out a method that works for all distributions.

You can follow the guides and implement a node module for it, I don't see a reason to have an API in Electron for it.

**Comment by cstayyab** [comment]
You can use node module [`lsb-release` ](https://www.npmjs.com/package/lsb-release) to find out your required information.
