### ISSUE TITLE
BrowserWindow 'title-bar-style': 'hidden-inset' option causes crash on OS X 10.9

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#2790]
From: https://github.com/atom/electron/pull/2776#discussion_r39516678

```js
const win = new BrowserWindow({
		'width': 800,
		'height': 600,
		'title-bar-style': 'hidden-inset'
});
```

This throws on OS X 10.9 with Electron 0.32.3.

![image](https://cloud.githubusercontent.com/assets/170270/9879233/a92dd8e0-5bf0-11e5-870a-a3fbc3656243.png)

**Comment by ssreekanth** [comment]
I see the issue on OS X 10.10.5 too.

**Comment by jaanus** [comment]
This is strange. I now reviewed and tested the Chromium implementation of `IsOSYosemiteOrLater` and it looks correct. It should guard against that method running. @sindresorhus and @ssreekanth what does `uname -r` (from command line) return on your Yosemite system?

**Comment by ssreekanth** [comment]
```
$ uname -r
14.5.0
```

**Comment by jaanus** [comment]
@ssreekanth so what exactly do you see on your 10.10.5 Yosemite machine? These APIs should be available there.

**Comment by jaanus** [comment]
About the comment made by @zcbenz …

> Can you create a new issue for this? I'm wondering if it is caused by me setting `MACOSX_DEPLOYMENT_TARGET` to `10.10`.

I’m now looking at `vendor/brightray/vendor/download/libchromiumcontent/src/base/mac_util.h` which says…

    // When the deployment target is set, the code produced cannot run on earlier
    // OS releases. That enables some of the IsOS* family to be implemented as
    // constant-value inline functions. The MAC_OS_X_VERSION_MIN_REQUIRED macro
    // contains the value of the deployment target.

And the inlined function is…

    #if defined(MAC_OS_X_VERSION_10_10) && \
        MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_10
    #define BASE_MAC_MAC_UTIL_H_INLINED_GE_10_10
    inline bool IsOSYosemiteOrLater() { return true; }
    #endif

I’m not sure how to set a deployment target for building this project, but it appears that if this inlined function were to be used, it would produce incorrect results when code built on Yosemite is run on pre-Yosemite.

**Comment by vdemedes** [comment]
@jaanus Running `uname -r` on Mavericks returns: `13.4.0`.

**Comment by sindresorhus** [comment]
@jaanus I just published my [app](https://github.com/sindresorhus/caprine0 if you need a testcase.
