### ISSUE TITLE
min/max dimensions not bound to content when using "use-content-size" flag

### ISSUE THREAD

**Issue by ToadKing** [atom/electron#2792]
When making a window with the "use-content-size" flag set, the "min-\*" and "max-\*" are still calculated with the full window size, not the content size. It would make sense for the "min-\*" and "max-\*" to match "width" and "height" in this case.

**Comment by etiktin** [comment]
On what OS did you notice this?

**Comment by ToadKing** [comment]
On second look it appears this is a side effect of my app working around the bug in #1806. Sorry about that.
