### ISSUE TITLE
Setting BrowserWindow's fullscreen option to 'false' doesn't actually hide the fullscreen button.

### ISSUE THREAD

**Issue by ssreekanth** [atom/electron#2793]
```md
Per documentation:

`fullscreen` Boolean - Whether the window should show in fullscreen. When set to `false` the fullscreen button will also be hidden on OS X.
```

However, fullscreen button is still visible but disabled (i.e. greyed out) on OS X.
![screen shot 2015-09-15 at 12 16 03 pm](https://cloud.githubusercontent.com/assets/1380334/9887737/0ec315b2-5ba6-11e5-8cd0-c8e1c1f453f8.png)

**Comment by zcbenz** [comment]
The behavior is different on different versions of OS X, what we did is to tell OS X to hide the button, but how it is hidden is out of our control. We probably need to change the docs to "hidden or disabled".
