### ISSUE TITLE
Global protocol handlers.

### ISSUE THREAD

**Issue by justinmchase** [atom/electron#2795]
I would like to have a url on my website such as `foo://my/protocol/handler` and when its clicked on in a web browser, have it handled by my electron app. I know its possible to do this in windows at least.

I know there is the `protocol` api, but it doesn't seem to respond to global protocol urls. Is that true? Is there a way to make it do that?

Also, I just wanted to add that the documentation for `protocol.registerStandardSchemes` doesn't seem to explain what it does or what its for and I'm not sure I understand it. Any explanation here would be much appreciated :)

**Comment by zcbenz** [comment]
You need to modify Windows registry to achieve that:
https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx

The `protocol` module only works for the URL requests inside Electron.

**Comment by justinmchase** [comment]
Got it @zcbenz, thanks.
