### ISSUE TITLE
Unable to debug dynamically required modules

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#2804]
I have an application where I require some modules dynamically like this:

```
// this code is executed after the document.body have loaded

this.loadModule(name);

loadModule: function () {
  return require('./myModules/' + name);
}
```

However, doing this breaks the debugging experience. Sometimes the debugger stops but even then the file is empty(blank only title shows the file name) and can't be debugged.

**Comment by zcbenz** [comment]
Where did you set the breakpoint? And which file shows empty?

**Comment by astoilkov** [comment]
The breakpoint is inside the module that's dynamically loaded via the `loadModule` function. I will try and isolate a scenario and send you an entire application.

**Comment by zcbenz** [comment]
Closing until more information is provided.
