### ISSUE TITLE
How to start a "most bottom" window?

### ISSUE THREAD

**Issue by IonicaBizau** [atom/electron#2805]
I want to make an Electron window to be *always* under the others windows–aka *most bottom*–how can I do this with Electron?

Also, would like to know if it's possible to hide it when pressing <kbd>Alt</kbd> + <kbd>Tab</kbd>. :balloon:

**Comment by IonicaBizau** [comment]
Hmm, there is an [`always-on-top`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions) option, but there is no `always-on-bottom`.

**Comment by Tribex** [comment]
On Linux/X11 systems, you can set the window type to `desktop,` which will accomplish what you want. However, I know of no method to do this for other platforms.

**Comment by zcbenz** [comment]
This is quite platform-dependent, and as @Tribex said this is only possible on X11 systems.

**Comment by IonicaBizau** [comment]
@Tribex @zcbenz Oh, yeah! Exactly what I needed. I'm running Ubuntu and my app will anyway run on Linux. Thank you! :cake:

**Comment by IonicaBizau** [comment]
@Tribex @zcbenz When there are two  windows like this, if I click the first one which was opened, it comes in the front (on top of the second one)–is it possible to keep it in the bottom always?

**Comment by Tribex** [comment]
@IonicaBizau Hmm, never run into this dilemma before. No clue. :(

**Comment by IonicaBizau** [comment]
@Tribex Hmm, then can we reopen this?

**Comment by Tribex** [comment]
@zcbenz Request for re-open. :3

**Comment by zcbenz** [comment]
You can't have two bottom-most windows at the same time, you can read [this article](http://blogs.msdn.com/b/oldnewthing/archive/2011/03/10/10138969.aspx) for some ideas, though it talks about top-most windows on Windows, the logic applies to all platforms.

**Comment by IonicaBizau** [comment]
@zcbenz Thanks–when I will have a working thingy I will let you know :smile:

**Comment by IonicaBizau** [comment]
I ended by having two `desktop` apps and using [inter-process communication](https://github.com/IonicaBizau/node-messager): if I want to keep A in the bottom (always), I catch the `focus` event of A and send an event to B which focuses the B window. Not sure if this is the best way, but it's working. :tada:

**Comment by dudeofawesome** [comment]
@IonicaBizau It looks like the `type` option on `BrowserWindow` might be what you're looking for. If you set it to `'desktop'` on OS X (and linux too, I believe), then the window will be attached to the desktop

> The desktop type places the window at the desktop background window level (kCGDesktopWindowLevel - 1). Note that desktop window will not receive focus, keyboard or mouse events, but you can use globalShortcut to receive input sparingly.

**Comment by IonicaBizau** [comment]
@dudeofawesome True, but if you have two windows like this, the first one can be activated and will overlap the second one.

**Comment by Adam-Morris** [comment]
@Tribex How would I set the `type` of the window to `desktop`?

**Comment by Adam-Morris** [comment]
For future reference:

Bottom-most windows are **only** supported on OS X and Linux (not Windows) or any other X11-based systems. To set the window to always be on the desktop (bottom-most window) set the BrowserWindow object as so:

 `window = new BrowserWindow({
		type: 'desktop'
	})`

**Comment by armaldio** [comment]
Hello, 

I had the same problem and on Windows desktop type doesn't work so I end up writing a native c++ addon.
Here is the link: https://github.com/armaldio/electron-bottom-most

Feel free to test/improve it.

**Comment by JimmyBoh** [comment]
@Armaldio Does your library continuously move it on the bottom or just move it to the bottom once?

**Comment by Armaldio** [comment]
It will always be the window with the lowest z-index possible.
I guess that if you have two windows that are bottom most, the last one created and put to the bottom is under the previous one. 
To sum up, it's the exact same behavior as top-most window but to the bottom

**Comment by JimmyBoh** [comment]
@Armaldio Hmm, I see. I'll have to play around with your library, it looks promising!
