### ISSUE TITLE
Have Chromium run in separate background process

### ISSUE THREAD

**Issue by natew** [atom/electron#2806]
This is half a question of feasibility and apologies if already discussed. I notice two things always brought up. With Atom, it's the slow startup time. With Electron, the weight it adds to any app you deploy with it.

Would it be possible to have Electron work in a two part manner, where the "runner" process is installed and can be set to run on startup, and then apps can be deployed without Chromium, just the JavaScript bundles, allowing them to be both much smaller and have potentially much faster startup times after first start? Does not Chrome already isolate processes as well so security would be ok? Just curious about this mostly.

**Comment by etiktin** [comment]
A run-time approach like you are suggesting is discussed at #673.

**Comment by zcbenz** [comment]
I'm merging this to #673.
