### ISSUE TITLE
module http or request stops on middle of transfers 0.32.3

### ISSUE THREAD

**Issue by MikeGCV** [atom/electron#2809]
When transferring a file using the http module get method, on 0.32.3 windows x64, the transfer doesn't finish, mostly on big files.
In 0.32.2 no problem

**Comment by zcbenz** [comment]
Can you provide an example?

**Comment by MikeGCV** [comment]
As i was making an example of this issue, i saw that 0.33.0 was released. Testes the same code against 0.33.0 and no problem. Very strange. Well, seems solved.

**Comment by MikeGCV** [comment]
The problem has returned, i don't understand, in 0.32.2 this code:

var _fs = require('fs');
var request = require('request');
 
var _file = _fs.createWriteStream(path + '/' + file, { bufferSize: 64 * 1024 });
            var cur = 0;
            var req = request({
                method: 'GET',
                uri: _app.serverIP + '/resources/files/' + file
            });

            req.on('response', function ( data ) {
                console.log(data.statusCode);
                console.log( data.headers[ 'content-length' ] );

                req.pipe(_file);
                _file.on('finish', function() {
                    _file.close(resolve);
                    _file = null;
                });
            });

            req.on('data', function (chunk) {
                //console.log(chunk.length);
                cur += chunk.length;
                console.log((100.0 * cur / total).toFixed(0));
            });

            req.on('error', function(err){
                _fs.unlink(path + '/' + file);
                reject(err);
            });

            req.on('end', function() {
                req = null;
            });

In 0.32.3 and 0.33 gives me this error on big files: ESOCKETTIMEDOUT. This is executed in the renderer process.

Thanks

**Comment by MikeGCV** [comment]
Same error happening in the main process, no errors on 0.32.2. This is in windows.

**Comment by MikeGCV** [comment]
Just tested in Linux, same error on 0.33

**Comment by zcbenz** [comment]
It is hard to determine since you are sending a request to your own server, can you try if following example works?

```js
var req = require('request')('https://github.com');
var file = require('fs').createWriteStream(process.env.USERPROFILE + '/Desktop/test.html');
req.on('response', function() {
  req.pipe(file);
});
```

Also if you are creating a server inside Electron you have to paste a full example, otherwise it would be impossible to debug this since the cause is very likely to be in other parts of your code.

**Comment by MikeGCV** [comment]
It's an external server, i've been doing some tests, it's very strange, your code works perfectly, but not for big files, i will be doing more tests tomorrow

**Comment by MikeGCV** [comment]
Ok, here's my scripts, nothing interfering, this is on 0.33.1 windows 8.1.

main.js loaded in the renderer

    window.addEventListener('DOMContentLoaded', function () {
        'use strict';

        var req = require('request')  ('http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4');
        var file = require('fs').createWriteStream(__dirname + '/testing.mp4');

        req.on('response', function() {
            console.log('Transfer start');
            req.pipe(file);
        });

        req.on('end', function(){
             console.log('Transfer end');
        });
    });

app.js for the main process:

    'use strict';
    const app = require('app');
    const BrowserWindow = require('browser-window');

    let mainWindow;

    function onClosed() {
	mainWindow = null;
    }

    function createMainWindow() {
	const win = new BrowserWindow({
		width: 600,
		height: 400
	});

	win.loadUrl(`file://${__dirname}/index.html`);
	win.on('closed', onClosed);
	win.webContents.on('dom-ready', function(){
		win.openDevTools({detach: true});
	});
	return win;
    }

    app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
    });

    app.on('activate-with-no-open-windows', () => {
	if (!mainWindow) {
		mainWindow = createMainWindow();
	}
    });

    app.on('ready', () => {
	mainWindow = createMainWindow();
    });

Many times, the download fails with timeouts or RangeError: length out of bounds. 
In version 0.32.2 this never happens

**Comment by zcbenz** [comment]
Thanks for the test case, it seems that the length of Buffer becomes zero sometimes.

**Comment by Akgupta11** [comment]
i am getting an error of ESOCKETTIMEDOUT and ETIMEDOUT in case of blynk app for using google voice assistant to operate my command as turning ON the LED and turning OFF the LED. it will be so helpful i get any help related to this issue. Anyone of can share the solution for this error
