### ISSUE TITLE
Disable app when not active

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2820]
On OS X if an application is not at the fore-front then it doesn't use memory so that if you have multiple applications running it doesn't hog all the memory when you are not using them. I'm not sure if Windows has a similar feature, but in any case I'm not sure if it would work for Electron apps.

I have built a suite of games/apps in Electron that a user can run concurrently and all have lots of fancy CSS, JavaScript and Videos playing. This causes the CPU/GPU to get hammered if the user has lots of them running.

Is it possible to have an Electron app stop running if the user isn't interacting with the application?

The only idea I could think of was to unload the webview on blur then reload the application webpage on focus again... but this isn't really pausing the app! Any ideas? Or could this be a possible enhancement in Electron?

**Comment by zcbenz** [comment]
There is no magic to pause everything automatically, Chromium took the way of destroying background tabs to reduce memory usages, which is very similar to your unloading/reloading webview.

On Windows and Linux the traditional way is to pause the loops when window is blurred, but you have to do it yourself.

I'm closing this since we can not provide a builtin solution.

**Comment by iamdriz** [comment]
@zcbenz Because the background tab discard from memory feature is part of Chromium, will it be coming into Electron?

**Comment by zcbenz** [comment]
@iamdriz Chromium implemented it by destroying the tab when it is not visited for sometime, and then reload it when you open it, you can implement the logic yourself.

**Comment by paulcbetts** [comment]
> Chromium implemented it by destroying the tab when it is not visited for sometime, and then reload it when you open it

Can someone do this solely with the given Electron API though? I have to imagine that Chromium doesn't lose things like scroll state or the JS context when the page is blown away then reloaded, no? I'm :+1: on letting developers control policy but we should give them the tools to do so

**Comment by zcbenz** [comment]
Preserving JS context is different in Electron from Chromium since we allow native calls, I think keeping the state of a page in Electron is basically the same difficult with doing that for a native app.

**Comment by iamdriz** [comment]
@zcbenz

Is this what you mean:

~~~
var mainWindow;

mainWindow.loadUrl('index.html');

mainWindow.on('blur', function(){
    mainWindow.loadUrl('blank.html');
});
mainWindow.on('focus', function(){
    mainWindow.loadUrl('index.html');
});
~~~

**Comment by zcbenz** [comment]
@iamdriz Exactly.

**Comment by paulcbetts** [comment]
> I think keeping the state of a page in Electron is basically the same difficult with doing that for a native app.

Legit
