### ISSUE TITLE
MIDI access cannot be init first time unless reload

### ISSUE THREAD

**Issue by wildfiremedia** [atom/electron#2821]
Critical fix need for this issue on Windows, tested on 8/8.1 that can't properly initial midi port the first time Electron is run, it could only properly initialize after reload the page using remote.getCurrentWindow().reload()

All of these error have been tested exhaustively and conclude it's a bug.

```
var midi = null;  // global MIDIAccess object
var output = null;

function echoMIDIMessage( event ) {
  if (output) {
    output.send( event.data, event.timestamp );
  }
}

function onMIDISuccess( midiAccess ) {
  console.log( "MIDI ready!" );
//  var input = midiAccess.inputs.entries.next();
 // if (input)
 //   input.onmidimessage = echoMIDIMessage;
  output = midiAccess.outputs.values().next().value;
  if (!output)
    console.log("Uh oh! Couldn't get i/o ports.");
}

function onMIDIFailure(msg) {
  console.log( "Failed to get MIDI access - " + msg );
}

navigator.requestMIDIAccess().then( onMIDISuccess, onMIDIFailure );
```

**Comment by zcbenz** [comment]
Which version of Electron are you using? I got following output but I think it is because I don't have MIDI devices:

```
MIDI ready!
Uh oh! Couldn't get i/o ports.
```

Also can you try if it works in Chrome?

**Comment by wildfiremedia** [comment]
I tried on latest Electron and Google  chrome web browser with the same
issue that tell me either V8 or W8.x have issue. I tried W7 early this year
was fine. Note, I didn't have any firewalls or antivirus installed.

You can install any supported Virtual Midi e.g. LoopBe1, the output api
from webmidi wil show blank results, if we load the page, the device will
appear. There is no race conditions from user end, I assume there might be
a bug at the V8 implementation.

**Comment by zcbenz** [comment]
If it doesn't work in Chrome browser you should report it to Chromium's issues tracker instead, we are not able to fix it on Electron's side.

**Comment by proyb2** [comment]
Updated Electron with Nodejs 4.1.1 works now.
