### ISSUE TITLE
Process priority when application is minimized on dock or not focused

### ISSUE THREAD

**Issue by lele85** [atom/electron#2822]
I'm developing a CPU intensive application with electron and i'm experiencing some issue with process priority. We have a native module written in C doing signal processing (low level) and we broadcast live streaming over a socket. When application window is visible everything goes smooth but when is not focused (or worse minimized on dock) it looks like process is running at extremely low priority (native lib buffers are not able to be processed in real time). The strange fact is that this behaviour was introduced somewhere between electron 0.26.1 (firts version we used) and 0.31.1 (next version bump we adopted). Between these two version we have a leap of chromium from 42 to 44.

Anyone has any idea about this issue?

To be clear even in 0.26.1 i had experienced something similar but it wasn't so bad to compromise application functionality

**Comment by zcbenz** [comment]
Can you try preventing app suspension with [power-save-blocker module](https://github.com/atom/electron/blob/master/docs/api/power-save-blocker.md)?

**Comment by lele85** [comment]
Tried, sadly it doesn't solve the issue.

**Comment by zcbenz** [comment]
Does it help if you set `page-visibility` to `true`?

**Comment by pracucci** [comment]
@zcbenz unfortunately setting `page-visibility` to `true` doesn't help

**Comment by zcbenz** [comment]
I can confirm from source code that renderer process's priority has been lowered after the page is hidden, and luckily there is a `--disable-renderer-backgrounding` flag to disable that, can you have a try?

**Comment by lele85** [comment]
`--disable-renderer-backgrounding` seems to solve the issue. Thank you very much!
