### ISSUE TITLE
debugging main thread per instruction causes electron to crash

### ISSUE THREAD

**Issue by cdaringe** [atom/electron#2824]
Hi all.  Here are the steps and some supporting info:

```bash
cdieringer@Snapper-osx:~/node/coinstac$ node-inspector -v
Node Inspector v0.12.3
cdieringer@Snapper-osx:~/node/coinstac$ electron -v
v0.30.6
cdieringer@Snapper-osx:~/node/coinstac$ node-inspector
Node Inspector v0.12.3
Visit http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 to start debugging.
```

in a new terminal
```bash
cdieringer@Snapper-osx:~/node/coinstac$ electron --debug .
Debugger listening on port 5858
```

The electron window opens.  In a browser, opening http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858 triggers causes `'Electron unexpectedly quit'`.  I've attached the [failure output here](https://gist.github.com/cdaringe/ca19088a1bb68a855a34).

Let me know if i can provide anything more.  Thanks,

Chris

**Comment by zcbenz** [comment]
The `--debug` flag was broken in v0.30.6, you should update to >= v0.31.1 to get the fix.
