### ISSUE TITLE
Can't get node submodule "7888f607ce74cc100ceb78f3af258a55ee2f62c4"

### ISSUE THREAD

**Issue by richmonkey** [atom/electron#2828]
Run python script\bootstrap.py -v.
But "7888f607ce74cc100ceb78f3af258a55ee2f62c4" commit id is't exist.

**Comment by zcbenz** [comment]
Which branch are you checking out?

**Comment by richmonkey** [comment]
Master branch . commit id is b4e836bf2ee20d4675f548c70754cf12db8fb7c8

**Comment by richmonkey** [comment]
-7888f607ce74cc100ceb78f3af258a55ee2f62c4 vendor/node

**Comment by zcbenz** [comment]
Thanks for reporting it, seems that I didn't tag that commit in the repo, it should work now.
