### ISSUE TITLE
Configurable invoking action for tray context menu

### ISSUE THREAD

**Issue by jasisk** [atom/electron#2830]
I'm not sure what the API would look like, nor am I confident how this would work cross-platform, however the current implementation of the tray context menu is [force-bound to the primary click action](https://github.com/atom/electron/blob/e4a7352b6299a03a42f545cfec1c45dde60bac41/atom/browser/ui/tray_icon_cocoa.mm#L210-L216) (at least on Mac).

Would rather the ability to perform a different primary action on click but display the context menu on right click.

Would it be possible and make sense to expose this kind of configuration? Perhaps exposing the underlying mechanisms (menu + positioning? Not a native dev so `¯\_(ツ)_/¯`) to recreate a tray context menu without `setContextMenu`?

**Comment by zcbenz** [comment]
There is a [Tray.popUpContextMenu](http://electron.atom.io/docs/v0.33.0/api/tray/#tray-popupcontextmenu-position-os-x-windows) API for this purpose.

**Comment by jasisk** [comment]
Indeed, however by merely using `setContextMenu`, [the primary click action is no longer configurable](https://github.com/atom/electron/blob/e4a7352b6299a03a42f545cfec1c45dde60bac41/atom/browser/ui/tray_icon_cocoa.mm#L210-L216):
``` objc
- (void)mouseUp:(NSEvent*)event {
  // ... snip ...
  // Show menu when single clicked on the icon.
  if (event.clickCount == 1 && menuController_)
    [statusItem_ popUpStatusItemMenu:[menuController_ menu]];

  // Don't emit click events when menu is showing.
  if (menuController_)
    return;
  // ... snip ...
}
```

**Comment by zcbenz** [comment]
Ah I didn't realize that, we should probably add an option to change the behavior.

**Comment by jtburke** [comment]
:+1: I would also like this. Particularly useful for menu bar apps. Some apps in the wild that use this non-standard mac: Bartender, Boom.

I feel it should be **very** explicit that you want this behaviour and the default behaviour should be as it is already.

**Comment by ssreekanth** [comment]
+1

**Comment by uargh** [comment]
+1

**Comment by rdickert** [comment]
@zcbenz It appears this issue should not have been closed (?) - at least, I can't get control of the tray context menu in the way described by @jasisk. Was it classified as a "won't fix", or perhaps is there a way to achieve this result that I'm not getting? The exact behavior I'd like to set up is:  

* left click: `show()` the main window.
* right click: open the context menu.

I can get this behavior on windows (which normally uses the right click for the context menu) but not on mac. On mac, the context menu pops up on left click regardless, and click events do not seem to trigger at all.

**Comment by prietoguy** [comment]
I am experiencing the same issue. Is the click event being triggered on a mac? (OSX 10.11.5)

**Comment by zcbenz** [comment]
@rdickert Don't call `setContextMenu` if you don't want the default behaviors of context menu.

**Comment by jaredtibs** [comment]
I am also experiencing this issue at the moment? I have an app entirely accessible through a tray icon, and want to enable 'quite' functionality through a right click only. Is there a way to do this now? 

Setting the context menu on the `right-click` event causes all click events to open the context menu... from what I can tell.

**Comment by aeris-alex** [comment]
> I am also experiencing this issue at the moment. I have an app entirely accessible through a tray icon, and want to enable 'quit' functionality through a right click only. Is there a way to do this now?
> 
> Setting the context menu on the `right-click` event causes all click events to open the context menu.

This might be two years old and a closed issue but this comes up as a top google result. So here is your solution.

`const contextMenu = Menu.buildFromTemplate([
        { label: 'Quit', type: 'radio', role: 'quit' }
    ])

    tray.on('right-click', function(event) {
        tray.popUpContextMenu(contextMenu)
    });`
