### ISSUE TITLE
Update electron app or remove it

### ISSUE THREAD

**Issue by satomusic** [atom/electron#2832]
Hey world,

I'm a noob at all of this programming and I'm having trouble finding my answer on the web. I've looked and looked but can't find anything that makes sense.

Feel free to move this post or delete if I'm causing any trouble. Or please point me in the direction of a post that would explain my questions.

I just want to learn how to update electron and learn further, how to use it. If not, how do I delete it.

I am funning Yosemite 10.10.5 on a Mac. Thanks.

**Comment by zcbenz** [comment]
You can find where to ask for help in the [Community section of Readme](https://github.com/atom/electron#community).
