### ISSUE TITLE
GetCurrentWindow in BrowserWindow X effecting BrowserWindow Y

### ISSUE THREAD

**Issue by grofit** [atom/electron#2839]
So I have a main window which starts when the app begins, then you can load many more windows from each window.

Anyway the problem comes in, if I was to call `remote.getCurrentWindow().toggleDevTools()` on window Y, the dev tools would appear on window X.

There seems to be very little information on how to handle multiple first class windows, so could anyone let me know how the best way to handle each windows scope?

(I have thought about trying to keep track of the browser window instances somewhere, or just having ipc events on windows but cannot find out much about if IPC is isolated to window/renderer or are global)

Any info around this area would be great.

**Comment by zcbenz** [comment]
Can you provide a full example? This is related to where and how you call `remote.getCurrentWindow`, and we didn't see similar issues in Atom which uses Electron and creates multiple windows.

**Comment by grofit** [comment]
Here is a overly simplified example of what is happening, it also shows another issue I run into where it deletes the window context of another window.

![Example Issue](https://dl.dropboxusercontent.com/u/98595151/ShareX/EMBERSOFT1/15/09/2015-09-21_08-57-44.gif)

Here is the example file if you want it:

https://dl.dropboxusercontent.com/u/98595151/menu-test.rar

**Comment by zcbenz** [comment]
You are creating a new application menu in your second window, so the callback of "Toggle DevTools" is ran in the second window even though you click it in the first window.

You should either only set menu for current window in each page, or set the menu in the main process. And the latter way is preferred under most cases.

**Comment by grofit** [comment]
Sorry to be a simpleton but what do you mean exactly? I need each window to have a menu and function as its own application, so are you saying that if I set it once in the main application then never set it again it will carry over or something?

A brief code example of how to best handle this scenario would be very much appreciated.

**Comment by zcbenz** [comment]
`setApplicationMenu` is equivalent to call `setMenu` for every window on Windows, in your case you can call `remote.getCurrentWindow().setMenu` instead of `setApplicationMenu` to fix it.

**Comment by grofit** [comment]
Thanks, will give this a try.

**Comment by etiktin** [comment]
@zcbenz, according to the [docs](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetmenumenu-os-x) `setMenu` is only available on OS X, is that incorrect?

**Comment by grofit** [comment]
It did seem to work for me, and I am on windows.

**Comment by zcbenz** [comment]
> @zcbenz, according to the docs setMenu is only available on OS X, is that incorrect?

We made a mistake there, it is actually not available on OS X.

**Comment by grofit** [comment]
So if `setMenu` doesnt work on OS X what is the desired approach in that environment to achieve the same thing?

**Comment by etiktin** [comment]
I reckon you can replace the application menu when ever a window comes into focus.

**Comment by grofit** [comment]
ok so do set application window every time the window is selected?

**Comment by etiktin** [comment]
Yes. I would probably just hold menu objects on the browser window that uses it, so when you get a `browser-window-focus` app event you just call `Menu.setApplicationMenu(window.mainMenu)`.
If you encounter some performance issues, you can optimize the code to switch menus only when needed, so if your window lost focus because the user opened another app, coming back to the same window, won't switch the menu (you can do this easily by keeping track of the window id).
