### ISSUE TITLE
ctrl+<key> get very strange keyCode from keyPress event

### ISSUE THREAD

**Issue by frantic1048** [atom/electron#2842]
when press single ctrl combine key, There are very strange keyCode from **keyPress** event.

suck like:

| real key pressed | keyCode returned by keyPress event|
| ---: | :--- |
| ctrl+j | 10 (Enter key)|
| ctrl+d | 4 |
| ctrl+l | 12 |
| ctrl+t | 20 (CapsLock)|
| ctrl+r | 18 (Alt) |
| ...... | ...... |

I think they are strange enough （´＿｀）

I write a minimal sample app print out the `keyPress` event and `keyDown` event.( **Note:** only **keyPress** event with **ctrl+`<key>`** reproduces this issue)

**Kernel:** Linux 4.1.6-1-ARCH
**OS:** Arch Linux (2015-09-19)
**Electron version:** v0.33.0
**Electron package:** electron-prebuilt
**Operation:** press any **ctrl+`<key>`** on window

**Minimal Sample:**

I used `setMenu(null)` to enable more ctrl combine keys. It does not affect on reproducing.

index.html

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<pre id="keylog"></pre>
<script type="text/javascript">
var keyLog = document.querySelector('#keylog');
function viewKey(ev){
  return `    keyIdentifier:${ev.keyIdentifier}\n` +
         `    keyCode:${ev.keyCode} ("${String.fromCharCode(ev.keyCode)}")\n` +
         `    charCode:${ev.charCode} ("${String.fromCharCode(ev.charCode)}")\n`;
}
window.addEventListener('keypress', function(ev){
  keylog.innerHTML = `keypress\n` +
                      viewKey(ev) +
                      keylog.innerHTML;
});
window.addEventListener('keydown', function(ev){
  keylog.innerHTML = `keydown\n` +
                      viewKey(ev) +
                      keylog.innerHTML;
});
</script>
</body>
</html>
```

app.js

```javascript
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var win = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when atom-shell has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
  // Create the browser window.
  win = new BrowserWindow({
      title: 'strange keypress event keycode'
  });

  // disable default elctron menu.
  win.setMenu(null);

  // and load the index.html of the app.
  win.loadUrl('file://' + __dirname + '/index.html');

  // Emitted when the window is closed.
  win.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null;
  });
});
```

package.json

```json
{
  "name": "test",
  "version": "0.0.0",
  "main": "app.js",
  "dependencies": {
    "electron-prebuilt": "^0.32.3"
  }
}
```

**Comment by OlsonDev** [comment]
`keyCode` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode).

**Comment by frantic1048** [comment]
@OlsonDev : The new keyIdentifier behaves same as keyCode, they both appears such strange result in keyPress. My demo also print out keyIdentifier for comparing.

**Comment by zcbenz** [comment]
I opened your page in Chrome 45 and I can reproduce the exact same result, I'm not sure about what should be the expected result, but since Electron has the same behavior with Chrome 45, I suggest reporting this to [Chromium issues tracker](https://crbug.com).

**Comment by frantic1048** [comment]
@zcbenz Thanks for your guiding. I'll try to confirm further about this issue, and consider reporting to [Chromium issues tracker](https://crbug.com/).
