### ISSUE TITLE
Open links in same window

### ISSUE THREAD

**Issue by akashnimare** [atom/electron#2843]
app.on('ready', function () {
	Menu.setApplicationMenu(appMenu);
	mainWindow = createMainWindow();
	const page = mainWindow.webContents;
	page.on('new-window', function (e, url) {
		window.open(url,'_self',false)
	});
});

I am not able to open the links(which has attr target=_blank) in same window.
Any idea where I am going wrong?

**Comment by zcbenz** [comment]
You can call `mainWindow.loadUrl`.

**Comment by jdsimcoe** [comment]
@zcbenz @akashnimare I'm trying this in an Electron app to open external URLs in the same window and can't get it to work:

```
webView = document.createElement('webview');

webView.addEventListener('new-window', function (e) {
        this.loadUrl(e.url);
    });
```

I'm trying to get a [Nativefier](https://www.npmjs.com/package/nativefier) instance to open external links in the same window.

**Comment by jdsimcoe** [comment]
@zcbenz @akashnimare Nevermind... this worked:

```js
webView.addEventListener('new-window', function (e) {
        webView.src = e.url;
    });
```
