### ISSUE TITLE
Cookies required error upon first login facebook (Atom-Electron application)

### ISSUE THREAD

**Issue by hhammoud01** [atom/electron#2848]
I am building an application using Atom/Electron Library and I have a facebook login button for this application. It is working fine. However, upon the user's first login (in Facebook's popup window), an error shows (cookie are required please enable them in your browser to log in). 

I checked electron's documentation and nothing seems to be a workaround for this problems. Any help/ideas are much appreciated. 
Thank you.

**Comment by hhammoud01** [comment]
When I open devtools I get the follow sequence of errors (upon login).
And I also notice that cookies are cleared once I log in.

Uncaught ReferenceError: __d is not defined(anonymous function) @ HEHg7hgYkh_.js:34
module.js:336 Uncaught Error: Cannot find module 'TimeSlice'Module._resolveFilename @ module.js:336Module._load @ module.js:286Module.require @ module.js:365require @ module.js:384(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:8
login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:9 Uncaught ReferenceError: requireLazy is not defined(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:9
login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:11 Uncaught ReferenceError: requireLazy is not defined(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:11
module.js:336 Uncaught Error: Cannot find module 'TimeSlice'Module._resolveFilename @ module.js:336Module._load @ module.js:286Module.require @ module.js:365require @ module.js:384(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:12
module.js:336 Uncaught Error: Cannot find module 'BigPipe'Module._resolveFilename @ module.js:336Module._load @ module.js:286Module.require @ module.js:365require @ module.js:384(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:16
login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:17 Uncaught TypeError: Cannot read property 'beforePageletArrive' of undefined(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:17
module.js:336 Uncaught Error: Cannot find module 'TimeSlice'Module._resolveFilename @ module.js:336Module._load @ module.js:286Module.require @ module.js:365require @ module.js:384(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:18
login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:18 Uncaught TypeError: Cannot read property 'beforePageletArrive' of undefined(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:18
module.js:336 Uncaught Error: Cannot find module 'TimeSlice'Module._resolveFilename @ module.js:336Module._load @ module.js:286Module.require @ module.js:365require @ module.js:384(anonymous function) @ login.php?login_attempt=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_ur…:19
Navigated to https://www.facebook.com/login.php?login_attempt=1&next=https%3A%2F%2Fwww.f…6response_type%3Dtoken%26client_id%3D299953330100883%26ret%3Dlogin&lwv=100

**Comment by zcbenz** [comment]
You need to turn off node integration in your window, otherwise Facebook login may not work sometimes.  

A better solution is to only turn off node integration in the popup window, currently you have to hook `window.open` to do that, a more decent solution is tracked at #2823.

**Comment by hhammoud01** [comment]
Before trying the solution in #2823, I tried opening the window with node-integration: false and still did not work :/ 
Any suggestions ?

**Comment by zcbenz** [comment]
Can you provide a small demo app that can reproduce the problem?

**Comment by PauloLira** [comment]
+1

**Comment by bierzorutas** [comment]
+1
