### ISSUE TITLE
Unable to use https through proxy

### ISSUE THREAD

**Issue by gnattu** [atom/electron#2849]
Electron 0.32 updated to Chrome 45, and Chrome 45 makes SSL connection more strict, which prohibits https connection through some http proxy that does't support SSL. The output in terminal showed like this
<pre>
[5823:0919/212509:ERROR:ssl_client_socket_openssl.cc(1060)] handshake failed; returned -1, SSL error code 1, net_error -100
</pre>
The app worked properly on Electron 0.31, is it possible to let the app access resources without https anyway?
What's more, for chrome, this terminal command works:
<pre>
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ssl-version-max=tls1
</pre>
but it doesn't works on electron

**Comment by zcbenz** [comment]
I think we can implement `--ssl-version-max` flag in Electron to fix this, Chrome did that by implementing a custom [SSLConfigService](https://code.google.com/p/chromium/codesearch#chromium/src/net/ssl/ssl_config_service.h&sq=package:chromium&type=cs&rcl=1442762901&l=23).
