### ISSUE TITLE
How to debug electron c++ source codes?

### ISSUE THREAD

**Issue by minggo** [atom/electron#2850]
Is there anybody know how to debug electron source code? I created a [ticket here](https://discuss.atom.io/t/how-to-debug-electron/20966) too.

**Comment by minggo** [comment]
I use the command to set a breakpoint like this:

`/atom/browser/api/atom_api_app.cc`

Then there is error message like this:

`Breakpoint 14: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.`

**Comment by minggo** [comment]
I built Electron with debug mode `./script/build.py -c D`, so i think the app includes debug information. Am i wrong?

**Comment by zcbenz** [comment]
I suggest poking [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) for help since there many Chromium developers there can help on how to debug Chrome and apps that built upon Chromium. There is also a chromium-dev Slack channel averrable.
