### ISSUE TITLE
Loading java sourcemap breaks code mirror syntax highlight

### ISSUE THREAD

**Issue by kyrisu** [atom/electron#2851]
I'm packaging GWT app into Electron container, but when I want to debug it and load the sourcemaps I get:

```
[1437:0921/143457:ERROR:CONSOLE(25)] "Empty response arrived for script 'chrome-devtools://devtools/bundled/cm_modes_module.js'", source: chrome-devtools://devtools/bundled/inspector.js (25)
[1437:0921/143457:ERROR:CONSOLE(0)] "Uncaught (in promise) Could not instantiate: WebInspector.DefaultCodeMirrorMimeMode", source: chrome-devtools://devtools/bundled/inspector.html?can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (0)
```

Which efectively disables the syntax highlight. Everything works ok in the recent version of chrome.

Any tips how I could troubleshoot are greatly appreciated

**Comment by zcbenz** [comment]
Can you provide a small demo app that uses source maps?

**Comment by kyrisu** [comment]
Do you have access to tomcat server? 

If yes - I can provide sample GWT project (and electron project) with instructions how to run codeserver (which is providing java sourcemaps).

**Comment by zcbenz** [comment]
No, I'll probably try to setup a simple app when I have time in future.

**Comment by ducky427** [comment]
I can also reproduce this issue using ClojureScript. I can probably create a simple app for this.

**Comment by ducky427** [comment]
I've got an app folder [here](https://www.dropbox.com/s/s9p9p3hun408hzb/app.zip?dl=0). To reproduce using Electron v0.33.0 on OS X:

1) Launch the app using Electron through terminal. I did: `Electron.app/Contents/MacOS/Electron app`.
2) Open DevTools using the Debug Menu [if not already open].
3) Goto Sources tab and open `file:// .... js/p/out/cljs/core.cljs`.

I noticed the error in the terminal.

Hope this helps.

**Comment by ducky427** [comment]
Could it be that some files are missing from [atom/libchromiumcontent's create-dist](https://github.com/atom/libchromiumcontent/blob/master/script/create-dist#L108) script? I found that the CodeMirror files are in `vendor/chromium/src/third_party/WebKit/Source/devtools/front-end/cm_modes` folder of `libchromiumcontent` repo.

**Comment by ducky427** [comment]
Thanks a lot. Electron `v0.33.4` does fix this for me.

Reallly grateful for this project. :+1:
