### ISSUE TITLE
Node-Webkit manifest format support

### ISSUE THREAD

**Issue by cloady** [atom/electron#2857]
Hi, guys.

I use electron & node-webkit to create desktop apps.

* Node-webkit has more clear and powerful manifest format than electron.
* Electron might to have same (and more scalable) manifest format as in node-webkit.
* Electorn might be compatible with nw.js manifest format.

In nw.js format we can declare **window** and **window properties** in package.json. It's very usable and i would like that the Electron also can create window without launcher *.js file provided.

We could provide "*.js" and "*.html" file with the ```main``` decaration. And get ```node-main``` property for js launcher also.

For example:

{
     "main": "index.html",   // when specified HTML we SHOULD create new BrowserWindow
     "window": {
         // Here is window PROPERTIES to create browserWindow.
      },
      "node-main": "index.js" // javascript application launcher (starts after "main").
}

Now this my feature request to listen your opinion. I would like to help to create this functionality.

**Comment by paulcbetts** [comment]
I'm not sure why someone would want to do that, but you should create a node.js module that will parse nw.js manifests and run them, I don't think this needs to be built into Electron (and tbh I question its utility)

**Comment by zcbenz** [comment]
We may support using `html` file for `main` field, since it is useful for simple apps and is very easy to implement, but supporting full node-webkit manifesto format is impossible because the [underlying architecture is completely different](http://electron.atom.io/docs/v0.33.0/development/atom-shell-vs-node-webkit/).

**Comment by cloady** [comment]
> We may support using html file for main field

I think this will be enough
