### ISSUE TITLE
Build error on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by torokze** [atom/electron#2858]
Hi,

Freshly cloned repo failed to build.

Mac OS X 10.10.5
Xcode 5.1.1

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

I would send this to the maintainers of the runas package.
I have a log file but I don't know how to embed into this message.

Zolee

**Comment by zcbenz** [comment]
The `ELIFECYCLE` error means there is an error happened with your toolchain, solutions include:

* Reinstall Node.js and npm
* Update to a newer Xcode
* Use an old Node.js (like 0.12.0) if current one is too new
