### ISSUE TITLE
Most links are not working in 0.33.0

### ISSUE THREAD

**Issue by paul321** [atom/electron#2859]
Hi

For some reason, links with css, cursor: pointer are not showing the hand cursor, and if users click on that element it doesn't do anything, this was working in 0.32.2

Links located in drag zone that have no-drag css property on, sometimes work, sometimes don't

Thank you

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by paul321** [comment]
Windows and Osx you can see this bug in the app called Microstockr, after
you login there is a hamburger menu, after clicking 1-2 times on it. This
was working fine in previous versions

**Comment by zcbenz** [comment]
Can you work out a minimal example? Even we can download the app and login, it is unlikely for any of us to debug into the app to check what's wrong.

**Comment by paul321** [comment]
We think it's from css property translateX using pixels as unit instead of
percent that is causing links to behave like a normal text until users
click them few times :)

**Comment by zcbenz** [comment]
So we can close this?

**Comment by paul321** [comment]
Yes i think you can, this is a chrome bug i guess
