### ISSUE TITLE
Build electron on windows 7 and vs2013

### ISSUE THREAD

**Issue by richmonkey** [atom/electron#2865]
I used the master branch code, and the latest commit id is "01a3bf58817f191aa98b816e8132238ec5accb22".

Run python script/build, Then i got:
d:\share\electron\vendor\brightray\vendor\download\libchromiumcontent\src\base\b
ind_internal.h(82) : fatal error C1001: 编译器中发生内部错误。
(编译器文件“msc1.cpp”，第 1325 行)
 要解决此问题，请尝试简化或更改上面所列位置附近的程序。
请选择 Visual C++
“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
        d:\share\electron\vendor\brightray\vendor\download\libchromiumcontent\sr
c\base\bind.h(91): 参见对正在编译的类 模板 实例化“base::internal::HasNonConstRe
ferenceParam<BoundRunType>”的引用
        d:\share\electron\vendor\brightray\vendor\download\libchromiumcontent\sr
c\base\timer\timer.h(225): 参见对正在编译的函数 模板 实例化“base::Callback<void
 (void)> base::Bind<void(__cdecl base::trace_event::TraceMemoryController::* )(v
oid),base::internal::UnretainedWrapper<Receiver>>(Functor,const base::internal::
UnretainedWrapper<Receiver> &)”的引用
        with
        [
            Receiver=base::trace_event::TraceMemoryController
,            Functor=void (__cdecl base::trace_event::TraceMemoryController::* )
(void)
        ]
        d:\share\electron\vendor\brightray\vendor\download\libchromiumcontent\sr
c\base\timer\timer.h(223): 编译类 模板 成员函数“void base::BaseTimerMethodPoint
er<Receiver,true>::Start(const tracked_objects::Location &,base::TimeDelta,Recei
ver *,void (__cdecl base::trace_event::TraceMemoryController::* )(void))”时
        with
        [
            Receiver=base::trace_event::TraceMemoryController
        ]
        d:\share\electron\vendor\brightray\vendor\download\libchromiumcontent\sr
c\base\timer\timer.h(237): 参见对正在编译的类 模板 实例化“base::BaseTimerMethod
Pointer<Receiver,true>”的引用
        with
        [
            Receiver=base::trace_event::TraceMemoryController
        ]
        d:\share\electron\vendor\brightray\vendor\download\libchromiumcontent\sr
c\base\trace_event\trace_event_memory.h(76): 参见对正在编译的类 模板 实例化“bas
e::RepeatingTimer<base::trace_event::TraceMemoryController>”的引用
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\cl.exe 中有内部
编译器错误。  将会提示您以后向 Microsoft 发送错误报告。
“C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\cl.exe”中的
内部编译器错误
    请选择 Visual C++
“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息
ninja: build stopped: subcommand failed.

**Comment by zcbenz** [comment]
Have you installed Update 4?
