### ISSUE TITLE
Main content area not accessible on Windows

### ISSUE THREAD

**Issue by BrendanMcK** [atom/electron#2872]
Curious if there's been any work or investigation done on Accessibility of Electron? I've tried out a few Electron-based apps, and am finding that there's some basic accessibility on Mac - but mostly nothing on Windows.

Chromium does seem to have built-in accessibility support, but for some reason it's not getting enabled on Windows. I'm hoping there's just a switch or build option that got missed somewhere.

Some notes:
* On Mac, VoiceOver can track focus and traverse items, but doesn't do heading navigation as it can do in Safari or Chrome
* On Windows, the menu bar and menu items do support some accessibility (can track focus and get item under mouse pointer), but the main content area is exposed as a single opaque box. I tested with both NVDA and the Inspect.exe windows accessibility tool.
* As a reference, Chrome and Chromium both are accessible on Windows; though need to start NVDA first (or use --force-renderer-accessibility flag) since they only enable accessibility support conditionally on startup.
* When using Atom, NVDA appears to read out the names of tabs as they are clicked - but what's actually happening here is that clicking tabs also changes the window title, and NVDA is just reading that change.

FYI @felixrieseberg

**Comment by zcbenz** [comment]
We didn't do anything on accessibility except for making TTS work on OS X, the `--force-renderer-accessibility` flag should also work in Electron, though I haven't tried.

**Comment by BrendanMcK** [comment]
Looks like --force-renderer-accessibility does cause some of the accessibility support to be enabled, but still lots missing. I tried it on VSCode, Atom and Slack, with varying degrees of success:

* Events don't work; seeing error messages in console "browser_accessibility_manager_win.cc: Not firing AX event because of no reoot_delegate or hwnd." The inspect tool can determine the HTML element under the mouse pointer and traverse the item tree, but neither it nor NVDA track keyboard focus.

* The apps can end up taking a bit longer to start up; atom goes from warm start of ~8 sec on this slow VM to about 20s. ISTR that Chromium's accessibility support does have some perf cost, which is why it's off by default, so might just be hitting that.

* NVDA doesn't work; likely related to the events issue, but NVDA navigation commands (eg. 'h' to move to next header) don't work either.

Next step may be to investigate why focus and other events aren't being sent. Once that and other issues are addressed, ideal situation is that Electron would detect presence of a screenreader (eg. using the windows SystemParameterInfo(SPI_GETSCREENREADER) flag, or some other means), so that passing in the --force-renderer-accessibility flag shouldn't be needed -- but we likely don't want to enable that until the other issues are addressed.

**Comment by paulcbetts** [comment]
Super into helping out on this soon, we've got someone starting at Slack soon who will be focused on working on Electron, and improving our accessibility story is a priority for our app

**Comment by felixrieseberg** [comment]
Yo @paulcbetts, Kevin Sawicki's peeps and some of our devs are gettig together early November to work on this (and other stuff). Want to hop by? If so, I'd send you deets!

**Comment by paulcbetts** [comment]
@felixrieseberg Please do!

**Comment by ryanmolden** [comment]
This should be fixed with commit 4ce840d

**Comment by zcbenz** [comment]
@ryanmolden :+1:
