### ISSUE TITLE
Control network speed programmatically

### ISSUE THREAD

**Issue by mastayoda** [atom/electron#2874]
Is there a way to control the network speed in the DevTools emulation programmatically? I know that I can access and set the device emulation through webContents.enableDeviceEmulation, but I can't find anything to set the bandwidth throttling to 3G, 4G or other speeds... I'm trying to automatically test an app in headless servers and it will be great if I can simulate several networks speeds among the clients.

-Thanks

**Comment by zcbenz** [comment]
There is no such API for now, but it looks good to me to add one.

**Comment by deepak1556** [comment]
Currently our devtools doesnt throttle network in emulation mode, we need to implement it before exposing an api.

**Comment by mastayoda** [comment]
Thanks so much for the quick response. In an era of real time applications, this will be a killer feature to have :+1:  looking forward to the next releases.
