### ISSUE TITLE
Using grpc 0.11.1, got Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by ThreeSZO** [atom/electron#2876]
I`m using grpc 0.11.1 in my project, grpc was built with nodejs 4.1.0, electron version 0.33.0, but I can`t get it work, it always got this error.
![c45dd381-bc69-43eb-895e-97a9807b168e](https://cloud.githubusercontent.com/assets/5828111/10040294/ce8d7826-620c-11e5-9494-45d5cdf25005.png)

**Comment by zcbenz** [comment]
Please follow the [Using Native Node Modules](http://electron.atom.io/docs/v0.33.0/tutorial/using-native-node-modules/) guide to build native modules.

**Comment by vilic** [comment]
@zcbenz Hi I am facing the same issue even after running `electron-rebuild` with `-p`:

```text
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Projects\electron-serial\node_modules\serialport\build\Release\node-v47-win32-x64\serialport.node
```

I am on Windows 10 10586 with Node.js 5.7.1, any idea?

**Comment by ZombieHippie** [comment]
Also experiencing this issue, I have tried configuring every thing I could think of with this one using https://github.com/electron/electron-rebuild on Windows 10

**Comment by paulcbetts** [comment]
Serialport uses node-pre-gyp which is broken on Electron until recently

**Comment by vilic** [comment]
I solved this issue by using script and manually calling build, install header and fix.

**Comment by BoOdya** [comment]
Hello!
How did you solve the issue couse I have the same one? node v6.3.0, grpc v1.0.0, electron v.1.3.5

**Comment by classLfz** [comment]
@vilic Hello! Could you get some more details ? I have the same problom which confuses me. Please.

**Comment by classLfz** [comment]
Well, I fix this issue by [`The npm way`](https://github.com/electron/electron/blob/f403950503eb82bcfa230b13a909572beff75fc0/docs/tutorial/using-native-node-modules.md#the-npm-way) in the electron docs:
```sh
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.33.1
export npm_config_arch=x64
export npm_config_runtime=electron
HOME=~/.electron-gyp npm install <module-name>
```
notice:
- the `npm_config_target` is the project's electron used version;
- `<module-name>` is the native node module that you want to install.
