### ISSUE TITLE
Tray 'clicked' event fires but popUpContextMenu does not work if app has just started up and has focus

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#2880]
I use the tray's clicked event to call popUpContextMenu and pop up the tray menu.

This does not work however on Windows 10 if the app is launched and then the tray is clicked (without the app losing focus or clicking anywhere else in Windows in between).

To reproduce:

1. A simple Electron app which uses 'clicked' to call popUpContextMenu.
2. Launch the app by searching for it on Windows 10 using Search (type name of app then hit enter to launch). This launches the app so that it has focus. Do not click anywhere else.
3. Click the tray icon.
4. The 'clicked' event will fire but calling popUpContextMenu will have no effect.
5. Clicking on the desktop or somewhere else and then clicking on the tray icon will open the context menu.

N.B. I found that launching the app by double-clicking on it from the Start menu does not reproduce the bug. You need to launch it in a way so that it has focus.

It is as if the tray's context menu is invisibly open when the app is launched with focus. As soon as the app loses focus the tray's context menu is closed and then it can be opened using popUpContextMenu.

I run into this several times a day.

**Comment by zcbenz** [comment]
I'm unable to reproduce in 0.36.2.

**Comment by jorangreef** [comment]
Thanks, just checked again, and can confirm it's no longer reproducible in 0.36.2.
