### ISSUE TITLE
Share storage between apps

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#2881]
I have two electron applications that both need to access some stored data. For example temporary access tokens, etc. In the browser world I use `sessionStorage` or `localStorage`. However it seems that each Electron app has its own storage that each other cannot access.

Is there a way to store something that can then be accessed by either application? I'm looked at NodeJS global variables e.g. `GLOBAL.storage = 'TEST';` but that isn't accessible in different apps either. And using `module.exports` and `require` isn't suitable either as the variable needs to be dynamic (unless you can update a variable value pulled from a require and have its new value accessible in other apps automatically).

So the only idea I can think of is to write/read to/from a file using the `fs` module and then delete it on app quit. Or connect to a database like mongo db. Although I'd like to avoid this if possible.

**Comment by etiktin** [comment]
Using files without a synchronization mechanism or locks, could lead to race conditions and data corruption. This might not be an issue, depending on access patterns and the type of data, but I think you would be better off using some caching or ipc modules from npm. For example:
- [node-shared-cache](https://www.npmjs.com/package/node-shared-cache)
- [node-ipc](https://www.npmjs.com/package/node-ipc)

**Comment by iamdriz** [comment]
I use node-ipc for some other communications between my apps, but in this particular case I want to have the variable accessible somewhere. i.e. make a request to get it. If I use IPC I'd have to send the variable to all the apps that need it and then store it locally for each application. Hence why the global text file feels easier to manage. It's literally going to be one word I'm storing and nothing else.

**Comment by sindresorhus** [comment]
Sounds like [configstore](https://github.com/yeoman/configstore) would be enough for your use-case.

**Comment by zcbenz** [comment]
Sharing data between apps is a general programming topic, not an Electron specific issue, so I'm closing this.

For storing access token, there is node-keytar module.

**Comment by iamdriz** [comment]
@zcbenz Thanks for that module. Looks awesome. But isn't the keychain used for storing actual account details like a database does, rather than temporary session data?
