### ISSUE TITLE
Download libchromiumcontent.zip and libchromiumcontent_static.zip is slow

### ISSUE THREAD

**Issue by minggo** [atom/electron#2884]
I am in China, the speed to download libchromiumcontent.zip and libchromiumcontent_static.zip is time cost. So could add a China mirror for these two libraries?

**Comment by hokein** [comment]
@minggo There is a qiniu mirror for libchromiumcontent, see https://github.com/hokein/libchromiumcontent-qiniu-mirror.

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
@hokein
I found the mirror can not work now.
