### ISSUE TITLE
Does electron integrate jQuery? What about zeptoJS, underscoreJS and others?

### ISSUE THREAD

**Issue by pampang** [atom/electron#2888]
I am curious about the integration of Electron.
Is jQuery integrated by Electron? (It ALL begins with the "$", I can use it in console even if it was a blank page run by Electron.)
And IF SO, what about other frameworks, such as zeptoJS, underscoreJS or what else?
If have one, PLS tell me!!!

**Comment by OlsonDev** [comment]
No, none of those are integrated. I'm not sure what you mean by `It ALL begins with the "$"` but the `$` you can use in the console on a blank window is [available in Chrome](https://developer.chrome.com/devtools/docs/commandline-api#selector) as well.

A better place for questions like this is the [forum](https://discuss.atom.io/c/electron), by the way.

**Comment by pampang** [comment]
Thanks for OlsonDev, thanks a ton.
My problem is below: 
![example](https://cloud.githubusercontent.com/assets/13509115/10091510/dfaa970c-636e-11e5-9ae4-e501423938d1.png)


While in a "hello world" page, I can still use "$" in console while open it in electron.
The main code of this page is like the code in: 
http://electron.atom.io/docs/v0.33.0/tutorial/quick-start/

**Comment by pampang** [comment]
reopen

**Comment by OlsonDev** [comment]
I don't understand what the "problem" is. `$` exists just like I said it would -- this is the same behavior in Chrome and Electron. Even Firefox makes `$` available and it has similar semantics. It's just a variable (assigned a function), available only in the context of the console. The link I included documents it. Here it is again: https://developer.chrome.com/devtools/docs/commandline-api#selector

You can prove it's not jQuery by checking out other properties on it. For example, `$.fn` doesn't exist; nor does `$.fn.jquery` (which would typically give you the version of jQuery as a string).

**Comment by pampang** [comment]
OH! I totally got it!
Thanks a ton, really!
