### ISSUE TITLE
title-bar-style doesn't work !?

### ISSUE THREAD

**Issue by fourtwentyone** [atom/electron#2893]
It seems the 'title-bar-style' feature doesn't work, or maybe I misunderstood how this work but here is my workflow : 

Electron v0.30.7
Mac Osx 10.10.5

Main.js source :
```
var app = require('app'); 
var BrowserWindow = require('browser-window'); 

require('crash-reporter').start();

app.on('window-all-closed', function() {

  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', function() {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    'title-bar-style': 'hidden'
  });

  win.loadUrl('file://' + __dirname + '/index.html');

  win.on('closed', function() {
    win = null;
  });

  win.show();
});
```

This doesn't change anything and same for ``` 'hidden-inset' ```, but ``` frame : false ``` work fine

**Comment by johnmuhl** [comment]
`title-bar-style` is not available in the 0.30.x releases. https://github.com/atom/electron/releases/tag/v0.32.3
