### ISSUE TITLE
Profiler in WebView tag's DevTools has draw issues

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#2896]
To repro:

1. Create a WebView tag
1. Call `openDevTools` on it
1. Go to the Profiler tab, take a perf trace with JS Profile / Memory / Paint enabled
1. Toggle Frames View (http://cl.ly/image/2i072v1Q1i01/Slack_Corp__-_Slack_2015-09-24_12-28-14.png) then toggle it back

![](http://cl.ly/image/2e3O1N3J1L1D/Developer_Tools_-_httpstinyspeck.slack.commessagessf_2015-09-24_12-28-48.png)

**Comment by paulcbetts** [comment]
It seems as if this is isolated to guest views, the BrowserWindow's DevTools works properly

**Comment by deepak1556** [comment]
Did you happen to do a right click in the flamechart view before toggling ? currently context menu is broken in webview devtools https://github.com/atom/electron/issues/1456 . I couldnt reproduce the issue without performing the context menu action in the flamechart view.

**Comment by paulcbetts** [comment]
@deepak1556 That's entirely possible that this is the bug I'm hitting
