### ISSUE TITLE
Show window as desktop on OS X

### ISSUE THREAD

**Issue by matthewmueller** [atom/electron#2899]
Is there a way to create windows that live on the desktop below the files? Something along the lines of: 

![img](http://projects.tynsoe.org/en/geektool/shots/shot47.jpg)

---

Looks like this is a good place to start: https://github.com/balthamos/geektool-3/blob/ac91b2d03c4f6002b007695f5b0ce73514eb291f/NerdTool/classes/CGSPrivate.h

---

If it's not possible, is there a plugin system available for native code? Thanks!

**Comment by Tribex** [comment]
On Linux, yes. I wrote a web wallpaper app awhile back. On other platforms, not yet, AFAIK.

**Comment by zcbenz** [comment]
Since `Geektool` already succeeded to do this I guess the answer is yes on OS X, but it seems to be hard work to port this thing to Electron. For using native code in Electron, you can checkout Node.js native modules, but for now we don't have a way to get native handles of windows created by Electron.

**Comment by matthewmueller** [comment]
Cool thanks for your response! To be fair, I wouldn't think this should be in core or anything. Mostly just the ability to create a plugin to enhance the window would be pretty sweet.

**Comment by p-e-w** [comment]
:+1: This is an *amazing* idea (not just on OS X of course, but on other platforms as well!).

Imagine the possibilities: Node-powered dynamic wallpapers that reflect system stats, online feeds etc., and are as easy to layout and style as a web page. Conky with its arcane configuration language would instantly become superfluous. It could also do wonders for screensavers (WebGL!).

I do think this is useful and common enough to warrant inclusion in core Electron. Basically what's needed is a "desktop" flag that puts the window in the background, makes it full screen (not covering launchers of course) and disables all user input on it by default.

@Tribex: Do you mean you have done so already with Electron on Linux? Could you share what was necessary to set this up?

**Comment by Tribex** [comment]
@p-e-w All that's required for doing so on Linux is adding `type: 'desktop'` to the window options. Input is not disabled though.

**Comment by sindresorhus** [comment]
Looks like it should be pretty easy to achieve on OS X too: http://stackoverflow.com/a/4987525/64949

**Comment by zcbenz** [comment]
Fixed with #3509.

**Comment by matthewmueller** [comment]
woo hoo!

**Comment by chinchang** [comment]
super!

**Comment by JGMathematica** [comment]
are there any way to implement this on windows?
