### ISSUE TITLE
List of shared lib Electron is dependent on

### ISSUE THREAD

**Issue by louy2** [atom/electron#2901]
- libgtk2
- libgconf2
- libnss3
- libasound

The above list is what electron reports are missing when I was running it from a Ubuntu server without GUI built-in. After installing them I was able to run it and direct the view to my VcXsrv on the Windows host via SSH.

In addition to the above I also installed `xdg-utils` to eliminate an error message during running.

Any other stuff I should pay attention to in this development setup?

**Comment by zcbenz** [comment]
You can find a list in [Build Instructions (Linux)](http://electron.atom.io/docs/v0.33.0/development/build-instructions-linux/).
