### ISSUE TITLE
Remove storage limitation of WebSQL

### ISSUE THREAD

**Issue by paul321** [atom/electron#2903]
Hi

I'm getting the following error: "there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space", when i try to use websql, this happens when the database reaches around 10 mb and the indexeddb around 500+ mb

Is this a limitation in Electon that can be changed?

I'm opening the db with the following line:
openDatabase(self.database, '', self.database, 500 * 1024 * 1024 || 0)

Also the app's data directory is 1.5gb and free space is 15.5 gb it there any limitation of 10% from the free space?

Thank you

**Comment by zcbenz** [comment]
Which version of Electron are you using?

**Comment by paul321** [comment]
0.33.0
