### ISSUE TITLE
Resolving promise causes renderer to crash.

### ISSUE THREAD

**Issue by jprichardson** [atom/electron#2906]
This is an odd one... 

The chromium renderer process crashes when a promise is resolved in a specific set of conditions. However, it seems pretty deterministic (occurring approx 90% of the time). It does not happen on every promise resolution, but it does happen at the exact same spot in my code. This project is currently closed source or I'd post a link. Also, to make matters worse, I'm unable to distill the code into a reproducible sample to cause a crash - but I'm still working on one.

The chromium renderer crashes when using `require('babel-core/register')` in conjunction with https://www.npmjs.com/package/node-fetch. The snippet looks something like:

```js
let res = await fetch(`${site}`, { headers: httpHeaders })

// when it crashes, 90% of the time (literally), it happens here:
// a try/catch block does not help
let body = await res.text()
```

This behavior started causing a crash in Electron version **0.32.3**.

**Works**:

- `0.30.4`
- `0.31.2`
- `0.32.0`
- `0.32.1`
- `0.32.2`

**Crashes**:

- `0.32.3`
- `0.33.1`

What's weird is that it crashes on a patch version change. Was there any **major change between `0.32.2` and `0.32.3`?**

The message in the crash report provides little detail. I can post it if you think it'd help. I understand that I haven't posted much to help diagnose the issue other than the change in versions. But is there any advice that can be given that I can use to try to track down what's causing the crash?

Thanks in advance for your help.

**Comment by paulcbetts** [comment]
This doesn't change your problem, but Chrome 43+ has Fetch built into the DOM API, you don't need to bring it i via node.js

**Comment by jprichardson** [comment]
> This doesn't change your problem, but Chrome 43+ has Fetch built into the DOM API, you don't need to bring it i via node.js

This is correct. But if I don't want to adhere to the SOP (same origin policy) i.e. site does not support CORs, then I must use the Node `fetch` since it doesn't need to adhere to SOP.

**Comment by sindresorhus** [comment]
> Was there any major change between 0.32.2 and 0.32.3?

You could just check yourself: https://github.com/atom/electron/compare/v0.32.2...v0.32.3

> But if I don't want to adhere to the SOP (same origin policy) i.e. site does not support CORs

Turn it off then? `{'web-security': false}` http://electron.atom.io/docs/v0.33.0/api/browser-window/

**Comment by zcbenz** [comment]
Can you try v0.33.2? There were some weird bugs around `Buffer` introduced by `0.32.3`.

**Comment by jprichardson** [comment]
> Can you try v0.33.2? There were some weird bugs around Buffer introduced by 0.32.3

It works, thanks!

> You could just check yourself: v0.32.2...v0.32.3

Thanks, I didn't remember how to do a version comparison. This will definitely come in handy.

> Turn it off then? {'web-security': false} http://electron.atom.io/docs/v0.33.0/api/browser-window/

I was aware of `web-security`, but I didn't actually stop and consider that it would solve the SOP issue. Thanks for pointing this out.

On a side note, when I switched to the browser `fetch`, it did work in the versions that were broken. So presumably it was a `Buffer` issue.

Thanks everyone for chiming in with thoughts and suggestions!
