### ISSUE TITLE
Passing userAgent to loadURL

### ISSUE THREAD

**Issue by startupfoundry** [atom/electron#2908]
Hello,

I'm trying to pass userAgent to loadUrl (http://electron.atom.io/docs/v0.28.0/api/browser-window/#webcontents-loadurl-url-options), but I'm having trouble getting it to work. I've attached the code below.

````mainWindow.loadUrl('https://google.com',[userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"]);````

This code doesn't throw any errors, but doesn't seem to have an effect on setting the User Agent. My web app uses agent sniffing to know what webRTC implementation to load. If I open up web inspector and spoof a Chrome User Agent my app works perfectly.

Am I missing something obvious? Thanks for your help

**Comment by johnmuhl** [comment]
The options object should look like `{ userAgent: "Mozilla/5.0…" }`. Brackets in the documentation mean the argument is optional not that it should be an array :)

**Comment by startupfoundry** [comment]
@johnmuhl , thanks for comment. I really appreciated your help. I've adjusted my code to be:

````mainWindow.loadUrl('http://whatsmyuseragent.com/',{ userAgent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"});````

It shows the correct useragent in testing, but the app still doesn't load unless I emulate a different user string from the web inspector. It's really strange, but probably something on my end that's unrelated to electron.

**Comment by goddyZhao** [comment]
btw, what is the default user agent pattern? I see it has something like `xxxxx appName/appVersion xxxx`, I just wonder whether does the `appVersion` come from? It doesn't seem to be the `version` property in package.json

**Comment by goddyZhao** [comment]
sorry, the `appVersion` is from `version` in `package.json`.
