### ISSUE TITLE
Native node modules fail to load in Windows on x64 v0.33.2 due to linker/dll errors

### ISSUE THREAD

**Issue by akrieger** [atom/electron#2909]
I'm trying to write a native node module. It used to work with older versions of electron (v0.2x.x days). I haven't touched it in a little while, and I'm trying to revamp it for electron v0.33.2. I get two different failure modes depending on circumstance.

I am compiling the module following the instructions on the wiki page, using Git Bash from the Git for Windows distribution. node v4.1.0, npm 3.3.4, node-gyp v3.0.3, Visual Studio 2013 Update 5 CTP 3.
```
HOME=~/.electron-gyp node-gyp rebuild --target=0.33.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```

I've observed the following:
electron-prebuilt x64 v0.33.2: Segmentation fault.
locally compiled debug electron x64 @ c0528c5049dc42ab191367b0a463274f72f46818 : The native module simply fails to load. Enabling the right flags (http://ofekshilon.com/2013/06/22/entry-point-not-found-and-other-dll-loading-problems/) and debugging in Visual Studio gives this output:

```
3c1c:1898 @ 77103875 - LdrLoadDll - ENTER: DLL name: C:\path\to\native\module.node
3c1c:1898 @ 77103875 - LdrpLoadDllInternal - ENTER: DLL name: C:\path\to\native\module.node
3c1c:1898 @ 77103875 - LdrpResolveDllName - ENTER: DLL name: C:\path\to\native\module.node
3c1c:1898 @ 77103875 - LdrpResolveDllName - RETURN: Status: 0x00000000
3c1c:1898 @ 77103875 - LdrpMapViewOfSection - ENTER: DLL name: C:\path\to\native\module.node
'electron.exe' (Win32): Loaded 'C:\path\to\native\module.node'. Symbols loaded.
3c1c:1898 @ 77103890 - LdrpMapViewOfSection - RETURN: Status: 0x00000000
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlInitializeCriticalSection" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlLeaveCriticalSection" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlEnterCriticalSection" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlDeleteCriticalSection" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "TpSetWait" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "TpReleaseCleanupGroup" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "TpWaitForWait" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "TpReleaseCleanupGroupMembers" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "TpWaitForWork" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "TpPostWork" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlReAllocateHeap" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlEncodePointer" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlDecodePointer" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlAllocateHeap" by name
3c1c:1898 @ 77103890 - LdrpGetProcedureAddress - INFO: Locating procedure "RtlSizeHeap" by name
3c1c:1898 @ 77103890 - LdrpNameToOrdinal - WARNING: Procedure "?GetCurrent@Isolate@v8@@SAPEAV12@XZ" could not be located in DLL at base 0x00007FF811100000.
3c1c:1898 @ 77103890 - LdrpReportError - ERROR: Locating export "?GetCurrent@Isolate@v8@@SAPEAV12@XZ" for DLL "C:\path\to\native\module.node" failed with status: 0xc0000139.
First-chance exception at 0x00007FF8467D2ED0 (ntdll.dll) in electron.exe: 0xC0000139: Entry Point Not Found.
3c1c:1898 @ 77103890 - LdrpGenericExceptionFilter - ERROR: Function LdrpSnapModule raised exception 0xc0000139
	Exception record: .exr 000000D015DFC330
	Context record: .cxr 000000D015DFBE40
3c1c:1898 @ 77103890 - LdrpProcessWork - ERROR: Unable to load DLL: "C:\path\to\native\module.node", Parent Module: "(null)", Status: 0xc0000139
'electron.exe' (Win32): Unloaded 'C:\path\to\native\module.node'
3c1c:1898 @ 77103890 - LdrpLoadDllInternal - RETURN: Status: 0xc0000139
3c1c:1898 @ 77103890 - LdrLoadDll - RETURN: Status: 0xc0000139
[15388:0925/151851:INFO:CONSOLE(0)] App threw an error when running [Error: The specified procedure could not be found.
C:\path\to\native\module.node]
```

**Comment by zcbenz** [comment]
Can you try whether the module works for Node v4.1?

**Comment by akrieger** [comment]
Yes, the same module compiles and executes correctly with Node v4.1.

**Comment by zcbenz** [comment]
Does other native module like `runas` work for you?

**Comment by akrieger** [comment]
When I install `runas` via the #2 method described in 'using native node modules' (setting a variety of environment variables before calling npm install), it loads fine.

Looking at those instructions further, I tried added a --runtime=electron flag to the node-gyp command line for my module. That appeared to change the error case somewhat. electron now seems to just exit immediately, silently, with code 0. However, debugging over RDP is tiresome and slow, so I will have to report back tomorrow.

I will note that using the download version of runas with my debug version of electron still results in the same dll error, so maybe the issue there is a mismatch between Release version of a module and Debug build of electron? Regardless, I still didn't seem able to make electron-prebuilt run correctly with my locally built new module. It seems to just exit immediately.

**Comment by zcbenz** [comment]
The debug version of Electron can not run native modules on Windows, you can find more details in https://github.com/atom/electron/issues/2558#issuecomment-134492155.

To debug the problem in Release build, you can pass the ` --renderer-startup-dialog` parameter when running the default app:

```bash
$ electron  --renderer-startup-dialog your-app
```

and then you can open Visual Studio and attach to the process by "Debug" => "Attach to Process".

**Comment by akrieger** [comment]
Ok, running Release electron shows no issues.

Strangely, after reverting my changes to confirm the problem, there no longer appeared to be an issue. I can no longer reproduce the segmentation fault in 0.33.2. Sigh. And everything was reproducing so consistently before.

If I run into similar issues I'll try to get a consistent repro in as clean of a scenario as I can. Maybe all of the fiddling I did resulted in purging some bad cached state or build artifact or header file somewhere which resulted in everything working later.

**Comment by akrieger** [comment]
Thank you for the advice with running electron with --renderer-startup-dialog to attach to it with visual studio, that will be a great help in the future!

**Comment by paulcbetts** [comment]
With WinDbg, I usually use the commands to debug Electron, which sets up debugging all child processes, then disables breaking in when processes are created/destroyed:

```
.childdbg 1
sxd cpr
sxd ebp
sxd ibp
```
