### ISSUE TITLE
beginFrameSubscription frame is not ARGB

### ISSUE THREAD

**Issue by brenca** [atom/electron#2919]
I've done some tests while I was looking for the FrameSubscription API and in all my examples, the frame always turned out to be BGRA not ARGB. I might be doing something wrong since the function that converts from YUV to RGB states that the data will be ARGB 32, but even when I put the raw frame data to a canvas, I need to change the order of the bytes in the buffer to get the right colors.

**Comment by zcbenz** [comment]
That function is quite old and not used by Chromium for some time, so it is possible that the underlying data of the frame has changed while that function stayed untouched. Maybe we can just change the docs to say it is returning BGRA?

**Comment by brenca** [comment]
I've done some research - this might have to do something with machine endianness.
https://www.chromium.org/developers/design-documents/graphics-and-skia
https://en.wikipedia.org/wiki/RGBA_color_space

**Comment by zcbenz** [comment]
> We could state this in the documentation, I guess.

The research is awesome! Can you create a pull request to document them?

**Comment by brenca** [comment]
Sure thing!
