### ISSUE TITLE
'will-download' event not fired when Webview has unique session

### ISSUE THREAD

**Issue by kjlaw89** [atom/electron#2924]
This is an issue I stumbled upon once I started implementing the recent changes for the will-download event. If you set a unique partition value on the _webview_, the will-download event will no longer fire for it. Is it possible to make the will-download event a global one, or is there possibly a way to expose the session that's associated with each _webview_ so that we could attach a separate 'will-download' event to it?

**Comment by zcbenz** [comment]
We need a way to return the session for the partition, I'm merging this to #959.

Maybe we can add a new `session` module and use `session.fromPartition` to return the `Session` object from partition string.
