### ISSUE TITLE
Crash when use node-sqlite3 in electron but do't crash when use node-sqlite3 in node.

### ISSUE THREAD

**Issue by richmonkey** [atom/electron#2925]
First npm install sqlite3.
Then compile sqlite with electron's v8:
HOME=~/.electron-gyp node-gyp rebuild --module_name=node_sqlite3 --module_path=../lib/binding/node-v44-darwin-x64 --target=0.30.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell

The code "https://gist.github.com/richmonkey/f83c19542248ad08dbfa" will crash
But "https://gist.github.com/richmonkey/d1c49c0c601a6151f223" will not crash

crash dump:
#
# Fatal error in ../../v8/src/global-handles.cc, line 238
# Check failed: object_ != nullptr.
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::GlobalHandles::MakeWeak(v8::internal::Object**, void*, void (*)(v8::WeakCallbackInfo<void> const&), v8::WeakCallbackType)
 3: Nan::ObjectWrap::Unref()
 4: node_sqlite3::Statement::Finalize(node_sqlite3::Statement::Baton*)
 5: node_sqlite3::Statement::Process()
 6: node_sqlite3::Statement::Work_AfterRun(uv_work_s*)
 7: uv_queue_work
 8: uv__work_done
 9: uv__async_start
10: uv__async_init
11: uv__io_poll
12: uv_run
13: atom::NodeBindings::UvRunOnce()
14: base::internal::RunnableAdapter<void (atom::NodeBindings::*)()>::Run(atom::NodeBindings*)
15: base::internal::InvokeHelper<true, void, base::internal::RunnableAdapter<void (atom::NodeBindings::*)()>, base::internal::TypeList<base::WeakPtr<atom::NodeBindings> const&> >::MakeItSo(base::internal::RunnableAdapter<void (atom::NodeBindings::*)()>, base::WeakPtr<atom::NodeBindings> const&)
16: base::internal::Invoker<IndexSequence<0ul>, base::internal::BindState<base::internal::RunnableAdapter<void (atom::NodeBindings::*)()>, void (atom::NodeBindings*), base::internal::TypeList<base::WeakPtr<atom::NodeBindings> > >, base::internal::TypeList<base::internal::UnwrapTraits<base::WeakPtr<atom::NodeBindings> > >, base::internal::InvokeHelper<true, void, base::internal::RunnableAdapter<void (atom::NodeBindings::*)()>, base::internal::TypeList<base::WeakPtr<atom::NodeBindings> const&> >, void ()>::Run(base::internal::BindStateBase*)
17: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
18: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
19: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
20: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
21: __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
22: __CFRunLoopDoSources0
23: __CFRunLoopRun
24: CFRunLoopRunSpecific
25: RunCurrentEventLoopInMode
26: ReceiveNextEventCommon
27: _BlockUntilNextEventMatchingListInModeWithFilter
28: _DPSNextEvent
29: -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:]
30: -[NSApplication run]
31: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
32: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
33: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
34: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
35: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
36: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
37: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
38: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
39: base::internal::DstRangeRelationToSrcRangeImpl<int, long, (base::internal::IntegerRepresentation)1, (base::internal::IntegerRepresentation)1, (base::internal::NumericRangeRepresentation)0>::Check(long)
40: AtomMain
41: main
42: start

**Comment by richmonkey** [comment]
node version:v0.12.7
electron version:v0.30.2
osx version:10.10.4

**Comment by etiktin** [comment]
This seems related to #1182. Check it out, there are tips there on how to solve this.

**Comment by richmonkey** [comment]
My question is different with https://github.com/atom/electron/issues/1182. 
I can compile and run my sqlite code.
Some code crashed when use electron but it did't crash when use node

**Comment by richmonkey** [comment]
When use electron, i can't keep db as global variable for open db just one time.

**Comment by zcbenz** [comment]
Can you try whether it works in the latest v0.33.3 release?

**Comment by richmonkey** [comment]
Got "https://github.com/mapbox/node-sqlite3" master branch, and still use electron v0.30.2, the issue disappear
