### ISSUE TITLE
How do I copy/cut/paste on Windows from a menu?

### ISSUE THREAD

**Issue by lipis** [atom/electron#2932]
So I have the following for my Edit menu that works on OS X:
```js
var editTemplate = {
  label: 'Edit',
  submenu: [
    {label: 'Undo', accelerator: 'CmdOrCtrl+Z', selector: 'undo:'}, 
    {label: 'Redo', accelerator: 'Shift+CmdOrCtrl+Z', selector: 'redo:'}, 
    {label: 'Cut', accelerator: 'CmdOrCtrl+X', selector: 'cut:'}, 
    {label: 'Copy', accelerator: 'CmdOrCtrl+C', selector: 'copy:'}, 
    {label: 'Paste', accelerator: 'CmdOrCtrl+V', selector: 'paste:'}, 
    {label: 'Delete', selector: 'delete:'}, 
    {label: 'Select All', accelerator: 'CmdOrCtrl+A', selector: 'selectAll:'}
  ]
}
```

But throws an error on Windows:
![screen shot 2015-09-29 at 13 25 43](https://cloud.githubusercontent.com/assets/125676/10162758/aa191e32-66ad-11e5-9d79-f9d84a010b84.png)

What should I do for Windows?

**Comment by johnsusi** [comment]
Try adding *role* to your submenus

`{label: 'Copy', accelerator: 'CmdOrCtrl+C', role: 'copy'}`

http://electron.atom.io/docs/v0.33.0/api/menu/

**Comment by lipis** [comment]
@johnsusi it worked for `undo, redo, copy, cut, paste` but not for `delete` and `selectAll`.. any idea?

**Comment by lipis** [comment]
And now they are disabled on OS X.

<img width="231" alt="screen shot 2015-09-29 at 14 53 06" src="https://cloud.githubusercontent.com/assets/125676/10164442/d234950c-66b9-11e5-88ac-4761b1eadb15.png">

**Comment by lipis** [comment]
Also it would be nice to document that somewhere:

- https://github.com/atom/electron/blob/master/docs/api/menu.md
- https://github.com/atom/electron/blob/master/docs/api/menu-item.md

**Comment by lipis** [comment]
Nevemind.. found it: https://github.com/atom/electron/blob/master/docs/api/menu-item.md
