### ISSUE TITLE
What would be an efficient way to send buffer data from main to renderer?

### ISSUE THREAD

**Issue by 0x80** [atom/electron#2936]
webContents.send() uses strings. In my application I want to send about 512 bytes of data (arriving in Buffer) at about 60fps from the main process to a renderer process. What would be an efficient way without converting it to and from strings?

**Comment by zcbenz** [comment]
The most reliable way for this is to use [shared memory](http://blog.varunajayasiri.com/shared-memory-with-nodejs), though it is not easy to find a solid implementation for Node.js.

**Comment by 0x80** [comment]
I think shared memory is overkill for this amount of data, especially if there is no solid Node implementation. If there is no way to do binary IPC in Electron I think I will go for something like Redis pub/sub.
