### ISSUE TITLE
Save web page into filesystem, like ctrl+s's Chrome

### ISSUE THREAD

**Issue by zg2013** [atom/electron#2937]
hello
I hope to do offline download page, at present, I climb to download, but not too good. I think if electron can get the cache, so if you add a download excuse should be icing on the cake.
Thank you, hoping to add this API.

![20150930112634](https://cloud.githubusercontent.com/assets/5134292/10183765/2d05e614-6766-11e5-98f5-b1d705e3e2d0.png)

**Comment by subwaymatch** [comment]
+1 for this feature

**Comment by appelgriebsch** [comment]
+1 from here as well... would be even nicer to save it as an "archive" (ASAR ?)

**Comment by akashnimare** [comment]
@zcbenz So basically we want to add the feature like ctrl+s'chrome.

**Comment by dkfiresky** [comment]
Why does this should be implemented in electron, if it's possible to write an application which will detect online/offline state and manage it's behavior?

**Comment by subwaymatch** [comment]
@dkfiresky I don't think detecting online/offline state and handling it is the issue here. The feature discussed here is basically "Save As" in Chrome. Saving website (for offline viewing) is a pretty tricky feature to implement.

**Comment by dkfiresky** [comment]
@subwaymatch you may want to use [node-website-scraper](https://github.com/s0ph1e/node-website-scraper) package instead of requesting new feature from Electron.

**Comment by zg2013** [comment]
@dkfiresky  
If you're standing in a browser's perspective, and viewing the API electron, you'll feel you should not be missing a "As Save" method.( Including "getTitle", "goBack", "openDevTools", "page-favicon-updated", .... If you think, these are not supposed to be.)
Such as access to the web, if the use of node-website-scraper] "save as", you need to request a web site again, and [node-website-scraper] is not good, such as the inability to obtain accurate favtion.ico, but electron [Event:'page-favicon-updated'] can get to, the two are distinct. I am currently using [node-website-scraper], because it is not stable, so I hope to be able to provide electron to provide native methods, rather than the unstable spider[node-website-scraper ].

**Comment by zg2013** [comment]
@dkfiresky
You're right. 
"ctrl+s",It is not the best way to use the web crawler.

**Comment by subwaymatch** [comment]
@dkfiresky Using a scraper will save a re-requested version of the user's current view, and is not same as saving the rendered view (in cache). The feature requested by @zg2013 and others seems to require access to Chromium's disk cache, which is not currently available.

**Comment by dkfiresky** [comment]
@zg2013 I think there are two major options:
- implement online/offline state detection in your app, so it will still display user some data etc.
- use website scraper to retrieve remote website data and store/display it as it would be the application

@subwaymatch I will reference the docs: [app.getPath(name)](http://electron.atom.io/docs/v0.33.0/api/app/#app-getpath-name)
> - appData Per-user application data directory, which by default points to:
> %APPDATA% on Windows
> $XDG_CONFIG_HOME or ~/.config on Linux
> ~/Library/Application Support on OS X
>
> - cache Per-user application cache directory, which by default points to:
> %APPDATA% on Windows (which doesn't have a universal cache location)
> $XDG_CACHE_HOME or ~/.cache on Linux
> ~/Library/Caches on OS X
>
> - userCache The directory for placing your app's caches, by default it is the cache directory appended with your app's name.

All the paths are available to you, so you can grab any cached resource.

**Comment by etiktin** [comment]
I think the problem with the scraper module is mostly with dynamic pages. The node module won't automatically use the cookies from Electron (the implication of this is that session id or tokens won't be sent to the server), not to mention state/data stored in local storage etc. 
For most stateless static pages, it should work.

**Comment by zg2013** [comment]
@dkfiresky 
I think it's a very bad way to use a reptile.
Because in the complex network circumstances (such as the content of the web site is JS), the crawler is unable to obtain the content of the site accurately. While Chrome is more accurate. After testing, [node-website-scraper] is really unable to obtain accurate. In addition, if the electron already has all the data in the site (in debug mode has been able to see the picture CSS JS and HTML even if it is off the network state), then why again use the crawler to get? Chrome should not use the crawler to complete the ctrl+s.

**Comment by dkfiresky** [comment]
@zg2013 you can't obtain files from electron cache directories?

**Comment by fritx** [comment]
niubility

**Comment by zg2013** [comment]
@zcbenz  thank you !

**Comment by subwaymatch** [comment]
@zcbenz Thank you! +1

**Comment by Nashorn** [comment]
Bottom line, we need a way to save the rendered page to disk.
