### ISSUE TITLE
question: Menubar with long string inside

### ISSUE THREAD

**Issue by iamstarkov** [atom/electron#2938]
Is it possible to create this kind of menubar with text inside?
![screen shot 2015-09-30 at 10 15 09](https://cloud.githubusercontent.com/assets/559321/10187951/2bc758f0-675c-11e5-940f-801cd39db7cf.png)

**Comment by zcbenz** [comment]
[Tray.setTitle(title)](http://electron.atom.io/docs/v0.33.0/api/tray/#tray-settitle-title-os-x) can achieve this.

**Comment by iamstarkov** [comment]
Thanks
