### ISSUE TITLE
Mac: "Services" menu stopped being pupulated with v0.31.2

### ISSUE THREAD

**Issue by naoboo** [atom/electron#2943]
In main.js I have the following to use the services function of OS X.

```javascript
app.on('ready', function() {

  // ...
  
  var template = [
    {
      label: 'MyApp',
      submenu: [

        //...

        {
          label: 'Services',
          submenu: []
        },
        // ...
```

Up to v0.31.1 the Services menu was populated as follows:

<img width="754" alt="v0 31 1" src="https://cloud.githubusercontent.com/assets/2261416/10197061/e105faee-6763-11e5-8067-fca2ee772da8.png">

But, starting with v0.31.2, I cannot get the same result:

<img width="413" alt="v0 31 2" src="https://cloud.githubusercontent.com/assets/2261416/10197148/3b5f3226-6764-11e5-8f30-c109f67a866e.png">

I am wondering if this is a bug or if I am not doing things that I am supposed to do.

Mac OS X: 10.10.5

**Comment by robertfirespotter** [comment]
There was a recent change to add a "role" attribute to menu items. For services you need to add role: 'services' to that menu. 

Here's the commit https://github.com/atom/electron/commit/6bce5b560bc04b9caa720bb89a73f3096a0ac120

**Comment by naoboo** [comment]
Changed the relevant part as follows:

```javascript
{
  label: 'Services',
  role: 'services',
  submenu: []
},
```

The Services menu works fine now (for v0.31.2 as well as the latest version, v0.33.3).  Thanks!!

**Comment by zcbenz** [comment]
Since v0.33.3 it is required to specify `role` attribute to mark a menu as "Services" menu, this change is to make it possible to make menu localization possible.
