### ISSUE TITLE
Can't load fb-flo extension

### ISSUE THREAD

**Issue by FliiFe** [atom/electron#2944]
In devtools, when adding the extension, it just returns "fb-flo", and nothing more.
```javascript
require('remote').require('browser-window').addDevToolsExtension('path_to_dir');
```
FB-Flo support would be great as it can help debugging apps without reload.

**Comment by zcbenz** [comment]
Currently we have to implement some chrome APIs to be able to load certain extensions, I'm merging this to #915.
