### ISSUE TITLE
BrowserWindow height and min-height options vary based on title bar

### ISSUE THREAD

**Issue by benmkramer** [atom/electron#2945]
Electron v0.33.1 on Mac OS X 10.10.5

The `height` and `min-height` options for BrowserWindow appear to be behaving inconsistently, in that `min-height` appears to take into account the size of the title bar.

To see this happen, use the following app code.  Once open, attempt to resize slightly using the bottom corner, and notice that the window snaps its height to be slightly larger than it was initially, despite the `height` and `min-height` both being initialized to `400`.

```js
var app = require('app');
var BrowserWindow = require('browser-window');
app.on('ready', function () {
  var win = new BrowserWindow({
    height: 400,
    width: 400,
    'min-height': 400
  });
  win.show();
});
```

**Comment by zcbenz** [comment]
I'm merging this to #1806.

**Comment by etiktin** [comment]
@benmkramer, thanks for the test case :)

**Comment by smebberson** [comment]
Seeing as though #1806 has been merged, but only fixes Windows. Should this be reopened?
