### ISSUE TITLE
On Ubuntu, shortcuts with "alt" don't register with global-shortcut

### ISSUE THREAD

**Issue by mkozakov** [atom/electron#2946]
<code>gsc.register('shift+t', function() {console.log("shortcut used")});</code>
<code>gsc.register('alt+t', function() {console.log("shortcut used")});</code>

With this code, the shift+T shortcut gets recognized, but the "Alt+T" shortcut is not. According to my tests, shortcuts with "alt" work on OSX and Windows, but not Ubuntu.

This shortcut works, by the way: <code>'ctrl+alt+g'</code>

**Comment by zcbenz** [comment]
I'm unable to reproduce on Ubuntu with GNOME 3 environment, I think this is caused by the `Alt+T` global shortcut already taken by the desktop environment or another app in your system.
