### ISSUE TITLE
Not possible to change the label of menu item after it's created

### ISSUE THREAD

**Issue by lipis** [atom/electron#2954]
I'm trying something like this:
```
menu = Menu.buildFromTemplate(menuTemplate)
menu.items[4].submenu.items[0].label = 'Foo'
```

But it doesn't seem to work.. is there any way to change the label?

**Comment by zcbenz** [comment]
I'm merging this to #528.

**Comment by etiktin** [comment]
If you want to a change a label in a menu, you could as a workaround, keep a reference to the menu template, modify it, rebuild it and set the updated menu.

**Comment by lipis** [comment]
@etiktin That makes sense.. (at least for now) thanks

**Comment by BenjaminVanRyseghem** [comment]
I try to change the label of a menu item while the menu is open
(basically a clock as menu item).

Any idea how to do that? Because rebuilding the menu also closes it :confused:
