### ISSUE TITLE
Very high loading times on OSX El Capitan

### ISSUE THREAD

**Issue by paul321** [atom/electron#2955]
Hi

Just updated to El Capitan and Electron 0.33.3 it's extremely slow in loading apps with large numbers of files, this was not happening in version 0.33.0 as you can see in the  video below, sometimes it's even failing and reports timeout 

https://youtu.be/HSMjGPyX8wI

**Comment by zcbenz** [comment]
Can you narrow down from which version of Electron this problem starts to happen? And does it happen for v0.33.4?

**Comment by paul321** [comment]
It seams that 0.33.4 is ok, i think you can close it now, btw i tested it
on 2 machines

**Comment by zcbenz** [comment]
:cool:
