### ISSUE TITLE
npm install error: Cannot find module 'process-nextick-args' / Installing wrong version

### ISSUE THREAD

**Issue by stevenmwade** [atom/electron#2958]
Reinstalling electon-prebuilt because npm wouldn't update it and the reinstall came with this nifty error:
`Cannot find module 'process-nextick-args'`

It seems like it is not installing any of it's own modules. It also isn't installing the latest version on another computer, only version 0.25.3.

**Comment by paulcbetts** [comment]
You probably want the electron-prebuilt repo, which isn't this one: https://github.com/mafintosh/electron-prebuilt
