### ISSUE TITLE
copy / paste / select don't work on darwin x64 packaged application

### ISSUE THREAD

**Issue by kmsheng** [atom/electron#2959]
I follow https://github.com/atom/electron/issues/2308 and add menu items but still don't work
https://github.com/karmapa/ketaka-lite/commit/dd33a3e19b563826bf953fbafd1df27fd159c932

Menu blinks when I press `command + c` but words aren't copied.
I'm using electron 0.30.4, electron-packager 5.0.2
OSX Yosemite 10.10.5 (14F27)

**Comment by kmsheng** [comment]
Adding selector property works on osx platform but fails on windows ( saying Menu.sendActionToFirstResponder is not a function )

**Comment by zcbenz** [comment]
The `role` property of MenuItem is only available after v0.31.2.

**Comment by kmsheng** [comment]
Thanks, confirmed.
