### ISSUE TITLE
Issue with lodash.isPlainObject and object from different renderers

### ISSUE THREAD

**Issue by ALF-er** [atom/electron#2966]
Hello.

I have issue with passing plain object from Renderer process to the function from Main process. Particularly with checking it on "plainess" =) 

Here is repo to reproduce https://github.com/ALF-er/different-contexts-isPlainObject-test/ just `npm install`, `npm start`.

It'll start `electron-prebuilt` with Main Process target script `mainprocess.js`. There is defined `global.store` with single method `dispatch` which use `lodash.isPlainObject` to determine is parameter `action` plain. Also it will "dispatch" plain-object-action with type `ACTION_FROM_THE_SAME_GLOBAL_CONTEXT` which will be recognized as plain (Look at Terminal, Powershell, console etc. for output):
```
{ type: 'ACTION_FROM_THE_SAME_GLOBAL_CONTEXT' } true
```
Then it will spawn one window with `rendererprocess.html` and `rendererprocess.js` as Renderer. It'll get store from main process via `remote.getGlobal("store")` and call its `dispatch` function with plain-object-action `{ type: "ACTION_FROM_ANOTHER_GLOBAL_CONTEXT" }` but in console we will see
```
{ type: 'ACTION_FROM_ANOTHER_GLOBAL_CONTEXT' } false
```

As we found out, passed object will be transformed in something not so "plain" and check `action.prototype.constructor instanceof action.prototype.constructor` will fail. 

Any suggestions how to get exactly passed object?

OS: Windows 10
Electron: 0.33.3

Related discussion https://github.com/rackt/redux/issues/830

PS: Sorry for my English =| And thank you in advance

**Comment by zcbenz** [comment]
The object returned by `remote` module is not the original object, it is a proxy object that routes the calls to methods and properties to the main process and sends the result back, so operations that rely on object equivalence like `instanceof` won't work for it.

**Comment by jdalton** [comment]
@zcbenz  can you point to the area in the source that creates the proxy object (just curious).

**Comment by jdalton** [comment]
I think I [found it](https://github.com/atom/electron/blob/master/atom/renderer/api/lib/remote.coffee).

If you want to keep it seen as a plain object you could always make the remote object's `[[Prototype]]` value `null` as if it were created by `Object.create(null)`.

**Comment by jdalton** [comment]
Actually that throws an error:
>
[20476:1003/112136:WARNING:dns_config_service_posix.cc(146)] dns_config has unhandled options!
[TypeError: Cannot read property 'constructor' of null]
[20476:1003/112136:INFO:CONSOLE(41)] "Uncaught TypeError: Cannot read property 'name' of undefined", source: /Users/jdalton/Projects/different-contexts-isPlainObject-test/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js (41)
