### ISSUE TITLE
Issue with using selenium and webdriver doc

### ISSUE THREAD

**Issue by ErikBean** [atom/electron#2968]
Took hours to solve this problem, the documentation on this page for running chromedriver dos not work on a windows machine:
(https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md)
It suggests starting chromedriver with the command `chromedriver --url-base=/wd/hub --port=9515`
But on windows, it needs to be started without the root slash on the url-base: `chromedriver --url-base=wd/hub --port=9515` otherwise chromedriver returns a 400 Bad Request with `RuntimeError: unhandled request` for all requests. 
Removing the root slash from url-base made everything work as it says in the tutorial 
Thanks,
-Erik

**Comment by zcbenz** [comment]
Thanks for bringing this up, I'll update the documents.
