### ISSUE TITLE
JSON.parse throwing error

### ISSUE THREAD

**Issue by stevenmwade** [atom/electron#2969]
Trying to read a file and JSON.parse is throwing an electron error (only on some computers):

`data = JSON.parse(fs.readFileSync(dataFilePath, 'utf-8'));`

No error without JSON.parse. Also no error on other computer.

    Uncaught Exception:
    SyntaxError: Unexpected token ,
        at Object.parse (native)

**Comment by zcbenz** [comment]
Apparently the content of `dataFilePath` is not a valid JSON string, you can debug it by printing the file out.

**Comment by stevenmwade** [comment]
@zcbenz You're right. It looked like everything was kosher, but apparently there are different kinds of quotation marks. Not sure how that happened. Sorry for the timesuck.
