### ISSUE TITLE
--ppapi-flash-path failed to recognize path with unicode characters

### ISSUE THREAD

**Issue by KochiyaOcean** [atom/electron#2981]
All versions of Electron have this issue. The path is garbled so that the program couldn't access resource correctly.

![d6 j f 7lgp0mlb ncndlb7](https://cloud.githubusercontent.com/assets/8194131/10267440/7591b962-6ac7-11e5-8e16-b062c3216e05.png)
![uvnb __ lh9rbw0 yawro5](https://cloud.githubusercontent.com/assets/8194131/10267443/7bb7464a-6ac7-11e5-8eba-f48cdebfe8bd.png)

**Comment by zcbenz** [comment]
Seems that `--ppapi-flash-path` failed to recognize path with unicode characters.
