### ISSUE TITLE
`setImmediate` is `undefined` in the preload script when `node-integration` is false

### ISSUE THREAD

**Issue by antoinepairet** [atom/electron#2984]
Summary: When `node-integration` is set to false, `setImmediate` is `undefined` in the preload script. 

I am using a using:
 * a `preload` script
 * `node-integration: false`
 * At some point in the `preload` script I am making HTPP requests (using the `request` module).

Each time I perform such a request, I got an error because `setImmediate` is `undefined`. `setImmediate` is used in the file `_tls_wrap.js` [see line 340] (https://github.com/nodejs/node/blob/master/lib/_tls_wrap.js#L340).

In the [tests](https://github.com/atom/electron/blob/a6b7dd22e8f1fed48c16af307ff222114d7c8ba8/spec/webview-spec.coffee#L87), it is explicitly tested that `[typeof process, typeof setImmediate, typeof global].join(' ')` is evaluated to `'object undefined object'`.

Why is `setImmediate` undefined in the preload script?
What solution/workaround exists for this use case ?

Thanks in advance.

**Comment by felicienfrancois** [comment]
https://developer.mozilla.org/en/docs/Web/API/Window/setImmediate
> Note: This method is not expected to become standard, and is only implemented by recent builds of Internet Explorer and Node.js 0.10+. It meets resistance both from Gecko (Firefox) and Webkit (Google/Apple).

setImmediate is not implemented in Chromium/Chrome and may never be implemented. For now, the only solution is to use `setTimeout`

**Comment by etiktin** [comment]
As a workaround, you might be able to use the [setImmediate.js](https://github.com/YuzuJS/setImmediate) polyfill at the start of your preload script.

**Comment by antoinepairet** [comment]
@felicienfrancois Thanks for your reply. It's not about having `setImmediate` defined in Chrome/Chromium. Let me try to explain it again.
As far as I understand it, having `node-integration = false` should not affect the preloaded script (we can still use `require`, `process` is defined etc.). However, making HTTPS calls in the preloaded script with `setImmediate` undefined will throw errors due to `_tls_wrap.js` relying on `setImmediate`.
I do not understand why `setImmediate` should be undefined while `process` etc. are OK.

@etiktin Thanks for the hint. Sadly, `require('setimmediate');` at the beginning of my preload script does not fix the issue. [It returns directly](https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js#L5)

**Comment by etiktin** [comment]
If it returns it means that `global.setImmediate` is defined, but you said in the OP that it's `undefined` in the preload script.

**Comment by antoinepairet** [comment]
@etiktin See this minimum example:

Main script:
````js
mainWindow = new BrowserWindow({
    'web-preferences': {
        'node-integration': false,
        preload: path.join(__dirname, './preload.js')
    }
});
````

preload.js:
````js
var request = require('request');
var fs = require('fs');

console.log(typeof setImmediate); // <---- function

window.doRequest = function doRequest() {
	fs.readFile('myBigFile', function (err, dataBuffer) {

        console.log(typeof setImmediate); // <---- undefined

	    request({ method: 'PUT', uri: 'https://myURL.com', body: dataBuffer });  // <---- Error thrown
	});
}
````

The function `doRequest` is triggered from a button in the markup.

The error that is thrown is:
````
Uncaught ReferenceError: setImmediate is not defined(anonymous function) 
    @ _tls_wrap.js:340emitOne 
    @ events.js:82emit 
    @ events.js:169(anonymous function) 
    @ net.js:469
````

**Comment by etiktin** [comment]
See #2866.

I think you might be able to fake it using something like this (just as a workaround):
```javascript
window.setImmediate = global.setImmediate = setTimeout;
window.clearImmediate = global.clearImmediate = clearTimeout;
```

**Comment by antoinepairet** [comment]
@etiktin Good catch, thanks.

Unfortunately, your suggestion does not work. (btw, note that it should be adapted with argument manipulation since `setTimeout` and `setImmediate` do not have the same signature:
````
var immediateID = setImmediate(func, [param1, param2, ...]);
var timeoutID = window.setTimeout(func, [delay, param1, param2, ...]);
````

**Comment by zcbenz** [comment]
By the time the preload script is executed the `setImmediate` function is still available, but once the web page started to load, the Node's globals are removed, including `setImmediate`. So you will get the undefined error when you try to use `setImmediate` after the first tick of message loop.

The solution is to bring the `setImmediate` back immediately after Electron removes the symbols:

```js
process.once('loaded', function() {
  global.setImmediate = setImmediate;
});
```

**Comment by antoinepairet** [comment]
@zcbenz Thanks for your explanation.

To make it work, I had to adapt your code sample to:
````js
var _setImmediate = setImmediate;
process.once('loaded', function() {
  global.setImmediate = _setImmediate;
});
````
and add it at the beginning of the preload script.
Thanks a lot.

**Comment by anthonysubramani** [comment]
@antoinepairet Thank you. It still works.

**Comment by GramThanos** [comment]
@antoinepairet 's solution based on @zcbenz 's code, works just fine. Thank you :D
