### ISSUE TITLE
Windows issue: 0.33.5 - window becomes white on calling win.hide()

### ISSUE THREAD

**Issue by Ivshti** [atom/electron#2990]
When calling ``BrowserWindow`` .hide(), the window becomes white under Windows 10 and 8.1 (haven't tested on anything else) with Electron 0.33.5.

The window then does not hide, simply remains white forever.

**Comment by zcbenz** [comment]
Oops, I removed a wrong line in https://github.com/atom/electron/pull/2950, will revert that.

**Comment by Ivshti** [comment]
Thanks! Awesome & quick work

**Comment by fasterthanlime** [comment]
:star2: Was wonder if I was doing something wrong :) Thanks for fixing it so quickly! :shipit:
