### ISSUE TITLE
Preload script not found when packaged with asar

### ISSUE THREAD

**Issue by antoinepairet** [atom/electron#3000]
Preload script is not found after having packaged the application with asar.

The following code works perfectly outside of an asar archive. However it breaks after packaging the app. The preload script is not loaded. I suspect a path issue.
````js
var windowOptions = {
    'web-preferences': {
        preload: path.join(__dirname, 'dsRenderer.js')
    }
};

new BrowserWindow(windowOptions);
````

Electron 0.33.4, Win 7.
Bonus question: Should an error be thrown when a preload is requested and it is not found?
Thanks in advance

**Comment by nasht00** [comment]
What was the solution? I have the same issue.


    mainWindow = new BrowserWindow({width: 1500, height: 1024, 'web-preferences': {'preload': path.resolve(__dirname, 'badgeNotifications.js')}});

**Comment by sarabsandhu** [comment]
I am having the same issue. Please share some information on resolving this issue. thank you.
