### ISSUE TITLE
jqLite & jQuery : dot replaced by comma in css value

### ISSUE THREAD

**Issue by Kilhog** [atom/electron#3001]
Since version 0.32.0 when I do something like that :
```
angular.element(document.querySelector('#something')).css('height', '0.5px');
```
or
```
$('#plop').css('transition', 'all 0.5s linear');
```
The result in the DOM is `height: 0,5px` or `transition: all 0,5s linear`

If you want to reproduce the bug is pretty simple :
```
<body>
	<div id="plop"></div>
	<script>
		var $ = require('./dist/js/jquery.min.js');
		$( document ).ready(function() {
			$('#plop').css('transition', 'all 0.5s linear');
		})
	</script>
</body>
```
I use the prebuilt osx

**Comment by zcbenz** [comment]
This behavior follows Chrome 45, I suggest posting this to [Chromium's issues](https://crbug.com) if it is a bug.

**Comment by Kilhog** [comment]
I just noticed, when you do ```open ./node_modules/electron-prebuilt/dist/Electron.app``` you have the bug up here, but when you do  ```open -b com.github.electron ./node_modules/electron-prebuilt/dist/Electron.app``` I d'ont have the bug. I don't understand ><
