### ISSUE TITLE
rendering fails on transparent html background

### ISSUE THREAD

**Issue by destan** [atom/electron#3004]
When a BrowserWindow created with following options:

```
var windowOptions = {
    width: mainWindowState.width,
    height: mainWindowState.height,
    transparent: true
  }
```

and the loaded html has transparent background, screen refresh fails.

![out_1444123431](https://cloud.githubusercontent.com/assets/442813/10304895/96e8a31e-6c25-11e5-8124-1d07a3ffb089.gif)

```
Ubuntu 14.04.3 LTS 
electron v0.31.2
node v4.1.1
```

**Comment by zcbenz** [comment]
Can you try whether Electron v0.33.x has this problem?

**Comment by destan** [comment]
@zcbenz `v0.33.6` is broken as well. Note that this only occurs when `transparent: true` is passed in options.

**Comment by destan** [comment]
@zcbenz I see you tag the issue as `more-information-needed`. What information do you need? Maybe I can help.

**Comment by zcbenz** [comment]
Unable to reproduce in 0.36.2 any more.
