### ISSUE TITLE
Is it possible somehow to subscribe to an event when a notification pops up from the BrowserWindow?

### ISSUE THREAD

**Issue by lipis** [atom/electron#3006]
I'm trying to integrate the [node-notifier](https://github.com/mikaelbr/node-notifier) for Windows support and I'm wondering if there is a way to subscribe to an event when a system notifications appears, to be able to get some information from it like, title, content and image. Is that doable?

Until this will be magically solved: https://github.com/atom/electron/issues/262

**Comment by zcbenz** [comment]
You have to either hack node-notifier, or write a native module for that, this is out of Electron's scope.
