### ISSUE TITLE
How to paste specified data in element?

### ISSUE THREAD

**Issue by fritx** [atom/electron#3007]
For now I have to deal with the real `clipboard`, and focus on it and `execCommand('paste')`
Here is my weird code: https://github.com/fritx/wxbot/blob/dev/preload.js#L233-L254
Is there any way to paste data directly? Thanks!

**Comment by zcbenz** [comment]
You can probably call `webContents.paste`, or send a fake `paste` event to the DOM element directly.

**Comment by fritx** [comment]
- `webContents.paste` still has to work with the real `clipboard`
- I've also tried dispatch a fake `paste` event but it wouldn't truly paste things accroding to http://www.w3.org/TR/clipboard-apis/#clipboard-event-interfaces

What I need is to emulate a user paste behavior, is it possible?

**Comment by zcbenz** [comment]
I'm afraid the only way to do that is to access the real clipboard, even Chromium's tests also do so:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/editing/pasteboard/data-transfer-items.html

**Comment by fritx** [comment]
Oh I see! What a pity.. Thanks for your time!
I should probably keep that code...
