### ISSUE TITLE
[OSX] [Tray] drop-files is not fired when dragging from the dock 

### ISSUE THREAD

**Issue by Dignifiedquire** [atom/electron#3008]
When dragging files from folders in the dock onto the tray icon there is no `drop-files` event fired. When dragging from the desktop or the Finder the event is fired. 
The OS does indicate that it should be possible, as it shows the green plus button to indicate a drop target when dragging the file.

*OS:* `OS X 10.11`
*Electron:* `0.33.6`

**Comment by zcbenz** [comment]
There is [`open-file` event](http://electron.atom.io/docs/v0.33.0/api/app/#event-39-open-file-39).

**Comment by Dignifiedquire** [comment]
I'm sorry, but I don't think `open-file` is the correct event. I'm not talking about dropping the file onto the dock, I'm talking about dragging a file from a dock folder onto the OS X tray. See below for a demonstration:

Start: 
![screen shot 2015-10-06 at 16 12 48](https://cloud.githubusercontent.com/assets/790842/10311007/24d946d2-6c45-11e5-8777-45c5ab354fb9.png)

End:

![screen shot 2015-10-06 at 16 13 47](https://cloud.githubusercontent.com/assets/790842/10311041/4ed351b2-6c45-11e5-913d-8966f19b94d8.png)

**Comment by hokein** [comment]
I couldn't reproduce it on OS X 10.10.4. The `drop-files` event is fired.

**Comment by nishanths** [comment]
@hokein I can reproduce in OS X 10.11.2. `drop-files` is not fired for files dropped from the Dock onto a Tray icon. I believe this has been a long standing Apple issue referenced here:

* http://stackoverflow.com/q/9534543/3309046
* http://openradar.appspot.com/radar?id=1745403

Submitted a fix.

**Comment by ektavarshney** [comment]
I am still facing this issue in macOS Big Sur 11.2 1. drop-files event is not fired for files dropped from the Dock onto a Tray icon.
