### ISSUE TITLE
Is it possible to get the OS's version?

### ISSUE THREAD

**Issue by lipis** [atom/electron#3012]
We can easily get the `process.platform` but it looks like there is nothing regarding the version of the OS. It would be nice to distinguish between 10.10 or 10.11 on OS X, or Windows 7, 8, etc..

**Comment by felicienfrancois** [comment]
[require('os').release()](https://nodejs.org/api/os.html#os_os_release)

**Comment by hokein** [comment]
I'm closing it since @felicienfrancois  has provided a solution for this.

**Comment by lipis** [comment]
:+1:

**Comment by chrtz** [comment]
This isn't really a solution, as it shows (in the case of macOS) just the unix version.
f.g. 16.7.0 for macOS 10.12.6

**Comment by megahertz** [comment]
@chrtz 
You can use [this table](https://en.wikipedia.org/wiki/Darwin_(operating_system)#Release_history) to detect actual macOS version.

Another options:
 - read /System/Library/CoreServices/SystemVersion.plist
 - exec `sw_vers`

**Comment by Christilut** [comment]
`require('os').release()` doesn't always return the right result on Windows.

On my Windows 10 Pro N machine it returns `10.0.18362` which is correct but on another Windows 10 machine (Home edition I think) it returns `6.2.9200` which is Windows Server 2012 or Windows 8.

**Comment by vitor251093** [comment]
Complementing @megahertz message, in macOS, you can use that to achieve what you want expect from `require('os').release()`

```
child_process.execSync("sw_vers -productVersion").toString().trim()
```

I'm not sure if `trim()` is actually required, but I've inserted it there just in case. Shouldn't that issue be reopened, considering that the macOS "regular" version is one people would use the most? 

Another function could be added to `os`, like `.productVersion()` (based in the sw_vers argument), and `.release()` could be renamed to `.buildVersion()` to decrease confusion (also based in a sw_vers argument).

**Comment by louisencontre** [comment]
> `require('os').release()` doesn't always return the right result on Windows.
> 
> On my Windows 10 Pro N machine it returns `10.0.18362` which is correct but on another Windows 10 machine (Home edition I think) it returns `6.2.9200` which is Windows Server 2012 or Windows 8.

Hey @Christilut 
Is this issue still occurring today? We need to prevent our users for using the auto-update feature if users are on Windows 8, Windows 7 and Vista so we have to develop a way to figure this out. That false positive you are talking about is a bit scary for us. 🙏

**Comment by andymartinwork** [comment]
Here's what electron uses to get the version on windows: https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw

"Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases."

**Comment by andymartinwork** [comment]
I checked the manifest of apps produced with electron-builder and it appears the correct manifest is present in the exe file. So hopefully this is good enough to trust to stop the auto-updater.

**Comment by fanhefeng** [comment]
It seems like the  `os.release()` returns the Kernel Version but I want the System Version.

**Comment by sime** [comment]
`os.version()` seems to be useful on macOS. You can match the darwin version (e.g. `xnu-11215*`on Wikipedia: https://en.wikipedia.org/wiki/MacOS_Sequoia
