### ISSUE TITLE
How to listen on clipboard data changed?

### ISSUE THREAD

**Issue by blan4** [atom/electron#3013]
Hello.
I can't find any documentation about how to register a listener on the clipboard changes. So when i put something in the clipboard via cmd+c i'm hope that some event could be fired.
So is it lacking of the documentation on API, or this feature hasn't been added yet?
Thanks.
(For example, QT has the signal http://doc.qt.io/qt-5/qclipboard.html#changed)

**Comment by hokein** [comment]
It hasn't been implemented. There is a issue #2280 tracking it already. So I merge this to #2280.
