### ISSUE TITLE
Quick Start Guide Fails

### ISSUE THREAD

**Issue by audrummer15** [atom/electron#3018]
The quick start guide does not work for starting a sample app with electron. I get the following screen

<img width="556" alt="screen shot 2015-10-06 at 10 34 29 pm" src="https://cloud.githubusercontent.com/assets/1392689/10328454/71ec3864-6c7a-11e5-818a-c60675f87dd0.png">

**Comment by hokein** [comment]
I see you are running the command `electron .`. Do you put sample app under the current directory?

**Comment by audrummer15** [comment]
Yes, the sample app indicated in the quick start guide is in the cwd

**Comment by hokein** [comment]
Could you paste the code of sample app here? The invalid-app error indicates that there is a module not found in the sample or some required files(e.g. `package.json`) are missing.

**Comment by zcbenz** [comment]
Closing until more information is provided.
