### ISSUE TITLE
.isAlwaysOnTop(true); does not bring window to top on windows nor does it stay.

### ISSUE THREAD

**Issue by ResourceHog** [atom/electron#3019]
app.on('ready',function(){
	mainWindow = new BrowserWindow({width: 800, height:600});
	mainWindow.isAlwaysOnTop(true);
        ...
});

The application is only on top when explicitly clicked on.

**Comment by skreborn** [comment]
As far as I'm concerned, `.isAlwaysOnTop()` is used to query this propery. To set it, use `.setAlwaysOnTop(state)`.

**Comment by OlsonDev** [comment]
Not only `as far as [you're] concerned`, but the docs state it [pretty clearly](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag) as well: use `mainWindow.setAlwaysOnTop(true)`.
