### ISSUE TITLE
Load jade with win.jade('file.jade', locals);

### ISSUE THREAD

**Issue by franciscop** [atom/electron#3023]
Is it possible to add a method to the `browser-window` instance that allows for loading a file from jade and pass some locals?

I've implemented it in my local file in the following way:

```js
var BrowserWindow = require('browser-window');

// Extend BrowserWindow to allow jade parsing (maybe better loadJade())
BrowserWindow.prototype.jade = require('../window-jade');

window = new BrowserWindow({ width: 400, height: 500 });

// Several ways to include it, absolute or relative, and with extension or without:
// - `print` or `print.jade`
window.jade('print', { a: "Some text" });
```

I implemented it in `../window-jade.js` in this case, that looks like this:

```js
// Load from a jade file and pass some variables to it
var jade = require('jade');

module.exports = function(file, locals){

  // Making `.jade` optional
  file = file.split('.').pop() == 'jade' ? file : file + '.jade';

  // Render the .jade from file. Future: make the full path optional
  var html = jade.renderFile(process.cwd() + '/' + file, locals);

  // Make use of the native `loadUrl` as seen in https://github.com/atom/electron/issues/968
  this.loadUrl('data:text/html,' + encodeURIComponent(html));
};
```

However [the source for `browser-window` seems to be all in .C](https://github.com/atom/electron/tree/2ef66cb6608a326c4627df4115db992caf336d57/atom/browser). Is there a place for something like this inside Atom? Or should I publish it as a separated npm module and just require it?

**Comment by etiktin** [comment]
Not everyone needs it, so I think it makes more sense to publish it as a module ("electron-jade"). As a rule of thumb, if something can be implemented as a module, it should be a module instead of adding it to core.

**Comment by zcbenz** [comment]
An easier way to achieve that is to use [protocol API](http://electron.atom.io/docs/v0.33.0/api/protocol/).

**Comment by franciscop** [comment]
@etiktin that makes perfect sense, thank you .
@zcbenz there's a big problem with that, the fact that we cannot pass variables to `.loadUrl()` makes it difficult to work that around [as we are discussing here](https://github.com/yan-foto/electron-jade/issues/9). But that solution I'm proposing also carries a different set of problems that have to be balanced. Thanks for pointing to the right place to search for more information though, I was a bit lost.
