### ISSUE TITLE
window.print callback?

### ISSUE THREAD

**Issue by kress95** [atom/electron#3028]
I'm trying to close a window after calling the print function, it's a 'headless window' just used for printing, but the print function won't accept a callback like the pdf printing function (that would let me know when printing is done).

I needed it because trying to close the window just after calling the function is breaking my app.

**Comment by CKing** [comment]
Normal Webbrowsers don't have a callback as well. Adding one would break compatibility IMO. 

But in Chrome I am calling window.close in a settimeout after 10ms. This way the print window is displayed and then, after the print window is closed, the dummy window gets closed.
