### ISSUE TITLE
Pixelated scrollbar on Macbook Retina (OS X)

### ISSUE THREAD

**Issue by evgenyzinoviev** [atom/electron#3029]
I'm creating an app with Electron and I found that scrollbars on retina displays are pixelated (like non-retina).
![](https://i.imgur.com/jyfiDPV.png)
Left is Electron; right is how it should look like.

**Comment by zcbenz** [comment]
I can reproduce this same thing in Chrome browser, you can probably report it to [Chromium's issues list](https://crbug.com). I'm closing this since it is a bug of Chromium, and we are not able to fix it in Electron.

**Comment by jakedowns** [comment]
didn't seem to be on chromium's issue list, so I submitted it: https://code.google.com/p/chromium/issues/detail?id=577347&thanks=577347&ts=1452719344

**Comment by evgenyzinoviev** [comment]
https://code.google.com/p/chromium/issues/detail?id=531257
It is already fixed in latest chromium versions.

**Comment by jakedowns** [comment]
derp. thanks
