### ISSUE TITLE
HTTP request's "Accept-Language" header doesn't list system's locale

### ISSUE THREAD

**Issue by webarchymeta** [atom/electron#3034]
We are developing a single page app using electron (version 0.33.4) on Windows 7 64 bit. It retrieves data and web contents from a remote server using `jQuery` ajax calls. It was found that the `Accept-Language` header in ajax requests sent to the server is always `en-US, en`. It seems that electron should set the default Language of the browser window to what the underlying OS is using, shouldn't it? Or is there an API that can be used to set the Language?

**Comment by zcbenz** [comment]
What's the value of `navigator.language` on your machine?

**Comment by webarchymeta** [comment]
The value of navigator.language is 'zh-CN' in my case and the property of navigator.languages is not initialized in the original electron environment, I set it to ['zh-CN'] as well, but jQuery still does not use that for some reasons.

**Comment by swapnil0545** [comment]
We are using the Accept-Language Request headers and then setting the app localization accordingly.
We get the required header property in chrome browser but I don't see this in electrons dev tool. I am using electron "v.3.1.6".
@zcbenz
