### ISSUE TITLE
Electron 0.33.6 electron arm build fails again... :-(

### ISSUE THREAD

**Issue by bbarnett** [atom/electron#3035]
Updated to commit 59b43a6571c8ca88c2c67d83325824f8e858611e

Followed the instructions for a linux cross compile arm build.

This fixed my earlier issue (thanks): #3016

bbarnett@bighero:~/work/electron$ ./script/build.py
ninja: Entering directory `out/R'
[921/1038] SOLINK lib/libnode.so
FAILED: if [ ! -e lib/libnode.so -o ! -e lib/libnode.so.TOC ]; then /home/bbarnett/work/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,noexecstack -Wl,--whole-archive  -Wl,--no-whole-archive -pthread -Wl,--whole-archive /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_external_snapshot.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicui18n.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_base.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libbase.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a --sysroot=/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot -L/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -L/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -target arm-linux-gnueabihf -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.TOC; else /home/bbarnett/work/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,noexecstack -Wl,--whole-archive  -Wl,--no-whole-archive -pthread -Wl,--whole-archive /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_external_snapshot.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicui18n.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_base.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libbase.a /home/bbarnett/work/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a --sysroot=/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot -L/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -L/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/bbarnett/work/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -target arm-linux-gnueabihf -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.tmp && if ! cmp -s lib/libnode.so.tmp lib/libnode.so.TOC; then mv lib/libnode.so.tmp lib/libnode.so.TOC ; fi; fi
/usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 i386linux elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[921/1038] ACTION compile_coffee: comp...offee_e42ad8b794496e05f38fce7e796ecf89
ninja: build stopped: subcommand failed.

**Comment by zcbenz** [comment]
> /usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
> Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 i386linux elf_l1om elf_k1om i386pep i386pe
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

From the error message you didn't install a cross compiler on your machine, you can follow [the guide](http://electron.atom.io/docs/v0.33.0/development/build-instructions-linux/#cross-compilation) to install the necessary dependencies.
