### ISSUE TITLE
In Mac OS X El Capitan, the "Enter Full Screen" menu item appears by itself

### ISSUE THREAD

**Issue by bengotow** [atom/electron#3038]
On Mac OS X El Capitan, a menu item titled "Enter Full Screen" is automagically being added to the application's "View" menu. This item is not present in earlier version of Mac OS X.

You can see this bug in Atom—on El Capitan, Atom's "Toggle Full Screen" option is shown in the View menu, and a mysterious extra "Enter Full Screen" item is listed at the bottom. Both of them actually do work.

I like the idea proposed in https://github.com/atom/electron/issues/2811 of having the full screen mode handled automatically, but this behavior needs to be consistent across platforms and OS versions.

**Comment by zcbenz** [comment]
It seems that EI Capitan added the menu item automatically, I couldn't find any documentation mentioning this behavior, and there doesn't seem to have a way to remove it. I would consider it a bug of OS X and wait for Apple to fix it.

Refs https://crbug.com/538872.

**Comment by lipis** [comment]
Not with the View menu, but something similar is happening with the Edit menu..

<img width="230" alt="screen shot 2015-10-09 at 09 44 20" src="https://cloud.githubusercontent.com/assets/125676/10388448/5976a7e6-6e6a-11e5-88d3-ebc50c6f45be.png">

The last two items were not added by me. (That was happening with Yosemite as well)

**Comment by mn4367** [comment]
Until this is fixed it's possible to tweak the menu label text for *Edit* and *View* so that no unwanted additional entries are made. In my case I just added '\u200C' to the view menu label text. This is the zero width non-joiner character which is invisible, so the menu item will look the same as without the character. This worked for me on OS X El Capitan.

**Comment by paulcbetts** [comment]
> It seems that EI Capitan added the menu item automatically, I couldn't find any documentation mentioning this behavior, and there doesn't seem to have a way to remove it

Confirmed, we had the same :trollface: happen to the Slack Mac app (not Electron-based)

**Comment by jasongrlicky** [comment]
Hey there! The only documentation for this I could find was in the [OS X 10.11 AppKit Release Notes](https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/) - look under the "Full Screen Menu Item" section. From this mention, it seems like the code to remove the menu item would be to add the following to the Electron App Delegate:

```objectivec
- (void)applicationWillFinishLaunching:(nonnull NSNotification *)notification {
    [[NSUserDefaults standardUserDefaults] setBool:NO forKey:@"NSFullScreenMenuItemEverywhere"];
}
```
Hope this helps!

**Comment by zcbenz** [comment]
@jasongrlicky It does fix the problem, thanks a lot! I'll create a pull request for it.
