### ISSUE TITLE
Cannot find module 'original-fs'

### ISSUE THREAD

**Issue by apigarage** [atom/electron#3039]
When I `require 'original-fs` in my script, it errors out saying `Cannot find module 'original-fs'`. I'm using 0.33.6 version of electron-prebuilt. 

Are there any special configuration for using original-fs?

**Comment by zcbenz** [comment]
This is weird, can you provide a sample app?

**Comment by ChinmayPatel** [comment]
oops. I was doing it wrong. Just realized that my "npm start" was firing up a `gulp` command instead of `electron` command. As soon as I ran the script inside the electron context, it started working. 

Apologies.
