### ISSUE TITLE
BrowserWindow - `fullscreen: false` option doesn't work on El Capitan

### ISSUE THREAD

**Issue by KevinMartin** [atom/electron#3042]
Code:
```js
const window = new BrowserWindow({
	width: 800,
	height: 500,
	fullscreen: false,
	transparent: true,
	'title-bar-style': 'hidden-inset',
	'node-integration': true
});
```

Correctly on Yosemite, the green window titlebar button only had the "+" plus to expand the window to fit the screen.

After upgrading to El Capitan today, I am able to both go fullscreen and use the new split screen feature.

**Comment by KevinMartin** [comment]
Any updates/comments on this?

**Comment by DoWhileGeek** [comment]
+1 I'm having this issue as well.

**Comment by leftstick** [comment]
The same issue as mine
