### ISSUE TITLE
Allow bundling of Asar and Electron executable

### ISSUE THREAD

**Issue by medemi68** [atom/electron#3045]
I was wondering if it would be possible to add support for bundling the .asar file with the executable (so that an executable can be distributed).

This would make it possible to hide the source code. (Which is needed to make any commercial application)

On windows you could use the copy command (similar to nw.js' implementation) (there are similar commands for both linux and osx):

          copy /B electron.exe+app.asar app.exe

Either that, or create a way so that users CANNOT extract the asar file (perhaps an extractable=false option?).

I'd still prefer the first method and remove the resources folder entirely.

**Comment by zcbenz** [comment]
Appending the `.asar` file to the binary doesn't hide the source code, people can very easily extract the file out. If you don't want your file visible under the `resources`, you can hide your real code by concatenating the binary with your app, and then write a simple app that extract the `.asar` file from the binary and then execute it.
