### ISSUE TITLE
file:// = http request never send out

### ISSUE THREAD

**Issue by EricTsangX** [atom/electron#3047]
Hey guys,
I found if the browser-window load with file://xxxxx/index.html, my http request can never send out, however, the browser-window.loadUrl(http://xxxxxxx) works. Any idea?

http request code from (http://davidwalsh.name/nodejs-http-request)
```javascript
        var http = require("http");
        http.get({
            host: 'personatestuser.org',
            path: '/email'
        }, function(response) {
            // Continuously update stream with data
            var body = '';
            response.on('data', function(d) {
                body += d;
            });
            response.on('end', function() {

                // Data reception is done, do whatever with it!
                var parsed = JSON.parse(body);
                resolve({
                    email: parsed.email,
                    password: parsed.pass
                });
            });
        });
```

**Comment by dkfiresky** [comment]
@EricTsangX does the `resolve` function was defined before the `http.get` call?

**Comment by EricTsangX** [comment]
Yes, I am using native es6 promise. I tried to use console.log and found the callback is not triggered.
Devtools- network also report nothing

**Comment by dkfiresky** [comment]
@EricTsangX I've made the same call and `http.get` request was made, successfully triggering the callback.
You might want to check your code for any issues.

**Comment by EricTsangX** [comment]
Thanks. I found the problem. I am using co+generator to deal with callback hell, but it seems it only work with "http://", cannot use with "file://", weird...

**Comment by EricTsangX** [comment]
Thanks. I changed to use jQuery ajax, it works now. It seems NodeJS http request cannot work in Chromium?

**Comment by dkfiresky** [comment]
If you want to retrieve file contents by accessing it via `file://` protocol, you might want to look at
[protocol](http://electron.atom.io/docs/v0.33.0/api/protocol/) module.

`HTTP` module works fine. As I already told, your snippet above works fine and the callback successfully triggered with the received JSON.

**Comment by zcbenz** [comment]
The requests sent from `http` module are not recorded in devtools because Node.js uses its own networking instead of Chromium's.
