### ISSUE TITLE
Menus are corrupt in v0.33.6

### ISSUE THREAD

**Issue by EhsaanF** [atom/electron#3050]
I upgraded my Electron to v0.33.6 today, but now I have menus rendering problem:
![menu](https://cloud.githubusercontent.com/assets/2109385/10394868/b5f3d8b8-6ea6-11e5-8ef7-084f01d9f554.gif)

As you can see, hovering a top level menu, causes render problems. Sometimes it even makes the whole program unresponsible. Also shortcut keys for menu items (those are starting with Ctrl/Cmd) aren't showing.

How can I fix it? Should I downgrade?

**Comment by etiktin** [comment]
Please provide the OS name and version.
Try running Electron without providing an application, so you'll see the default app. Click on ALT to show the window menu. Does it also display the same issue?

**Comment by EhsaanF** [comment]
Windows 10 x64 Pro version
No, default app is OK.

**Comment by zcbenz** [comment]
Can you provide a sample app that can reproduce this problem?

**Comment by EhsaanF** [comment]
@zcbenz On the path that Electron has rendering problems, all apps (including default app) have the problem. But as I said when I extract the Electron anywhere else, everything is OK.

**Comment by zcbenz** [comment]
Cool, I'm closing this issue then.
