### ISSUE TITLE
Pop-in Window on Fullscreen

### ISSUE THREAD

**Issue by KevinMartin** [atom/electron#3051]
Hi,

While playing around with Apple Mail in Fullscreen, I tried creating a new email, and while expecting the new compose window to shoot me out of Fullscreen, the compose window popped in instead.

It also worked perfectly in El Capitans split-screen mode.

Would something like that be possible with Electron?

<img width="1440" alt="screen shot 2015-10-09 at 10 02 11 am" src="https://cloud.githubusercontent.com/assets/510957/10395895/62654738-6e6d-11e5-8a8d-93c12b728963.png">
<img width="1440" alt="screen shot 2015-10-09 at 10 02 16 am" src="https://cloud.githubusercontent.com/assets/510957/10395894/626477b8-6e6d-11e5-962f-db57bb82bbe7.png">

**Comment by zcbenz** [comment]
Currently you can only use HTML to simulate it, I'm merging this to #323.
