### ISSUE TITLE
Cross compiling electron 0.33.6 How to point to my own local build tools

### ISSUE THREAD

**Issue by bbarnett** [atom/electron#3052]
Is there a way for me to use my own cross compiler that I built with buildroot, or cross-tool-ng to cross compile the electron code? How do I point the electron build at my "local" cross compiler?

**Comment by zcbenz** [comment]
You have to modify the `toolchain.gypi` to suit your environment, but you also have to compile a custom build of [libchromiumcontent](https://github.com/atom/libchromiumcontent/tree/atom) too.

Also the compilation environment for cross-compiling Electron and Chromium is extremely complicated, it would be quite hard to switch to your own toolchains.

**Comment by bbarnett** [comment]
Thanks, but obviously, the tools allow you to cross compile with the Ubuntu ARM toolchain, so while the compilation environment is "extremely complicated", it's clearly set up somewhere.Thanks for the pointer to toolchain.gypi; how is the toolchain set for libchromiumcontent? It must also be compiled with the Ubuntu ARM toolchain, or am I missing something?
-blair

**Comment by zcbenz** [comment]
You can start from [build instructions of Chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md), libchromiumcontent is basically a custom build of Chromium with lots of helpers scripts to avoid the headache of setting up everything.

**Comment by bbarnett** [comment]
Thanks, Cheng! I'll see what I can do...
-blair
