### ISSUE TITLE
Modal browserWindow

### ISSUE THREAD

**Issue by EhsaanF** [atom/electron#3053]
Is there any feature to create browserWindow that is a modal of another browserWindow?

I'm trying to make a settings window that is a modal of mainWindow. This is my code:
```javascript
{
					label: 'Settings',
					role: 'settings',
					click: function( item, focusedWindow ) {
						settingsWindow = new browserWindow( {
							width: 		640,
							heght: 		480,
							resizable: 	false,
							'skip-taskbar': true
						} );
						settingsWindow.loadUrl( 'file://' + __dirname + '/views/settings.html' );
						settingsWindow.openDevTools();

						settingsWindow.on( 'closed', function() {
							settingsWindow = null;
						} );
					}
				},
```

**Comment by etiktin** [comment]
Modal dialogs in web applications are usually implemented using divs or iframes. So if the native frame/border is not mandatory for you, you should check it out. For example, here's a [Bootstap example](http://getbootstrap.com/javascript/#live-demo).

**Comment by KevinMartin** [comment]
@EhsaanF, something like: #3051?

**Comment by EhsaanF** [comment]
@etiktin I know, but I want to make it like natives like Windows native applications.
@KevinMartin I don't know, never had a Mac :smile: look at regular settings dialogs.

**Comment by KevinMartin** [comment]
Can you post a screenshot of an app that does it so we can get an idea of what you're looking for? It could be the same thing as my issue, just a different platform...

**Comment by EhsaanF** [comment]
![focus](https://cloud.githubusercontent.com/assets/2109385/10402047/b8d0edd6-6ecf-11e5-8825-f6579e69ca7e.gif)

As you can see, when a modal window is open, you can't focus on its parent.

**Comment by MichaelOstermann** [comment]
You could just create another BrowserWindow instance and use the `always-on-top` option. You can communicate between those two Windows with [ipc](https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md), as well as listen to any [Events](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#events) they trigger!

**Comment by EhsaanF** [comment]
Good idea but it's not that I want. I think Electron doesn't support modal
windows at all.

**Comment by zcbenz** [comment]
I'm merging this to #323.

**Comment by sourceskyboxer** [comment]
Check new version issue #323 I have written long post with after my problem.
