### ISSUE TITLE
Error logs when not using --enable-logging

### ISSUE THREAD

**Issue by etiktin** [atom/electron#3058]
When not using `--enable-logging` we shouldn't see any internal logs, including `ERROR` logs. The only output should be from calls to `console.*` or `process.std*.write` from the browser process.
The reason is that the error logs are not really informative. For example on Linux a lot of users (maybe all) get the SUID sandbox message (see screenshot at #1482). It seems pointless to show this info to app users, and developers can run with `--enable-logging` to see it.

/Last remaining task from #3032.

**Comment by deepak1556** [comment]
You can use `logging::SetMinLogLevel` to achieve this, set it to a value higher than the severity listed when the flag is not provided.

**Comment by etiktin** [comment]
Are you sure that will prevent all logs?
In #3032, Chen said we'll probably need to patch Chromium to achieve that.

**Comment by deepak1556** [comment]
Yeah tested on linux with `logging::SetMinLogLevel(4)`, disables all logs. Do try it out.

**Comment by etiktin** [comment]
You're right, it works. I added it to #3060. Thanks!
