### ISSUE TITLE
WebContents event 'devtools-closed' not firing with 0.32.1 (windows)

### ISSUE THREAD

**Issue by kress95** [atom/electron#3063]
WebContents event 'devtools-closed' is not firing with electron-prebuilt 0.32.1 on windows.
(didn't tested with other platforms)

I'm trying to open a hidden window with just the devtools visible (everything ok up to this point), to see only the logs from `loca` mocha reporter when running `npm test`, but the `devtools-closed` never fires so my hidden window never closes.

**Comment by zcbenz** [comment]
Can you try the latest release? We had some fixes for devtools events in recent versions.

**Comment by kress95** [comment]
When calling openDevTools with `{detach: true}` the `devtools-closed` is firing without actually closing it, but it's no issue for me since I can ignore the first call.

I checked it with `isDevToolsOpened` and it's really closed (I think the detatch option closes it in order to put it in a separate window) but no issue with that so far, closing :3
