### ISSUE TITLE
So all the windows options with "-" throw errors .... 

### ISSUE THREAD

**Issue by AdamKyle** [atom/electron#3066]
So take the concept of:

```js
  ouathWindow = new BrowserWindow({
    width: 640,
    height: 480,
    always-on-top: true
  });
```
throws errors, why? because doing something like:

```js
var object = {always-on-top: ture}
```

> Uncaught SyntaxError: Unexpected token -(…)

the token, incase its not obvious is the `-` 

Am I doing this wrong?

**Comment by thomasjo** [comment]
You have to wrap the hyphen separated options with quotes, i.e. change your example code to this

```js
ouathWindow = new BrowserWindow({
  width: 640,
  height: 480,
  'always-on-top': true
});
```

It's very unfortunate a choice was made to use hyphens instead of underscores, or perhaps better yet, camelCasing. But that's the way it is, and it's unlikely it will ever change sadly.
