### ISSUE TITLE
What Chromium and Node versions does Electron use?

### ISSUE THREAD

**Issue by callumlocke** [atom/electron#3068]
Sorry if I'm missing it, but I can't find this info.

**Comment by zcbenz** [comment]
You can check it in `process.versions`.

**Comment by charandas** [comment]
@zcbenz thanks for the info. The key in the `process.versions` object is called `chrome`, not `chromium`.  Is that just an oversight?

Apart from that, do you know if we can custom select chromium versions, or can use a more beta version such as canary?

**Comment by CapOM** [comment]
process.version prints the nodejs version.
process.versions['chrome'] prints the chromium version.

One version of electron gives you one version of https://github.com/electron/libchromiumcontent (this one https://github.com/electron/electron/tree/master/vendor).
And one version of electron/libchromiumcontent gives you one version of Chromium:  https://github.com/electron/libchromiumcontent/blob/master/VERSION
