### ISSUE TITLE
Start Electron applications programmatically

### ISSUE THREAD

**Issue by IonicaBizau** [atom/electron#3069]
Currently I'm using the `npm start` script to start Electron apps:

```sh
electron my-app.js --enable-transparent-visuals --disable-gpu
```

But is it possible to start Electron apps programmatically? Is there anything better than spawning the processes?

```js
var Spawn = require("child_process").spawn;

var pr = Spawn("electron", ["my-app.js", "--enable-transparent-visuals", ...], { cwd: ... });
// do something with this process
```

I imagine something like this:

```js
Electron("path/to/my-app.js", {
    "enable-transparent-visuals": true
  , "disable-cpu": true
});
```

**Comment by zcbenz** [comment]
Spawning a new process is exactly the right way to go.

**Comment by IonicaBizau** [comment]
@zcbenz Actually I saw that even the Electron CLI app spawns another process. I built [`electroner`](https://github.com/IonicaBizau/electroner) to simplify the things a little bit. :grin:
