### ISSUE TITLE
sendInputEvent with RETURN does not trigger form submit

### ISSUE THREAD

**Issue by kidwm** [atom/electron#3072]
```js
webview.sendInputEvent({
	type: 'keyDown',
	keyCode: '\u000d'
});
webview.sendInputEvent({
	type: 'keyUp',
	keyCode: '\u000d'
});
```
and this is my testing form.html in webview
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>FORM TESTING</title>
    </head>
    <body>
		<form>
			<input type="text" />
		</form>
    </body>
</html>
```
Or have I mistaken something?

**Comment by zcbenz** [comment]
Maybe it is because the `input` doesn't have focus?

**Comment by kidwm** [comment]
@zcbenz I've tried manually clicking in the input textfield to make it focused, still no triggering.

**Comment by brenca** [comment]
Looks like for some reason the form sending is triggered on a keypress event - send a 
``` JavaScript
webview.sendInputEvent({
    type: 'char',
    keyCode: '\u000d'
});
```
after the `keyUp`, and it will work. (Tested on v33.7)

**Comment by kidwm** [comment]
@brenca Thank you! it works.
now my code snippet turns into:
```js
if (code == BACKSPACE) target.sendInputEvent({
	type: 'keyDown',
	keyCode: code
});
target.sendInputEvent({
	type: code == BACKSPACE ? 'keyUp' : 'char',
	keyCode: code
});
```
Maybe we should add this info to docs?

**Comment by zcbenz** [comment]
I'm closing this since it has been solved.

**Comment by brenca** [comment]
@kidwm Any time :) I don't think this is *that* closely related to the API, but I'm thinking about making a set of example snippets where I gather and list these behaviours as we discover them.
