### ISSUE TITLE
Override Electron Logging

### ISSUE THREAD

**Issue by kurisubrooks** [atom/electron#3074]
Is there any way to override Electron's logging system? I've got a module that logs console output to a file, but it must be called with a function. How could I apply this to Electron, to get it to use this module?

Example of Electron Console output (as called from web renderer):
```
[4448:1013/172627:INFO:CONSOLE(38)] "[%] [13/10/2015 5:26:26pm] Program Started", source: /Users/Kurisu/Dropbox/Code/GitHub/eew/client/node_modules/lumios-toolkit/src/index.js (38)
```

Example of standard console output:
```
[%] [13/10/2015 5:26:26pm] Program Started
```

Example of logging function:
```
logger.debug('Program Started');
```

**Comment by kurisubrooks** [comment]
I've tried to override it by changing `stdout`, but alas, no result.
```
process.stdout.write = function(input) {
    tools.debug(input);
};
```

**Comment by zcbenz** [comment]
This has been solved on master branch, and the fix will be included in next release.
