### ISSUE TITLE
[15184:1014/091258:ERROR:ipc_channel_win.cc(435)] pipe error: 232

### ISSUE THREAD

**Issue by tommyZZM** [atom/electron#3078]
just update v0.33.7

show this error in terminal while close the electron window.
````
[15184:1014/091258:ERROR:ipc_channel_win.cc(435)] pipe error: 232
````
seems not cause anything?

any the other terminal log not works anymore
![capcture](https://cloud.githubusercontent.com/assets/6326007/10472705/07243dba-7256-11e5-916b-541dc687bf0f.PNG)

operating system:Windows10

**Comment by zcbenz** [comment]
It is actually a harmless warning from Chromium, we have disabled such warnings in #3056 and the fix will be included in next release.
