### ISSUE TITLE
Is it possible to capture an incoming desktop notification event in OS X?

### ISSUE THREAD

**Issue by IdanAdar** [atom/electron#3081]
Is it possible to capture an incoming desktop notification event in OS X?

The reason is this: a desktop app based on Electron that loads a remote URL.
The website that is loaded displays desktop notifications.

The end goal is to display a dock badge to notify that a notification arrived, and to dismiss it once the app came to view.

**Comment by zcbenz** [comment]
You can override the `Notification` function in `preload` script to do whatever you want when a notification shows.

**Comment by IdanAdar** [comment]
What is the "preload script"? I do not see it in my project structure.

I have:
- icons
- main.js
package.json

**Comment by zcbenz** [comment]
There is a `preload` attribute in `web-preferences` option:
http://electron.atom.io/docs/v0.33.0/api/browser-window/#new-browserwindow-options

**Comment by IdanAdar** [comment]
Hmm... no joy. Is there anything in particular to do in my case?

`app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1500, height: 1024, "web-preferences": {preload: "/custom.js" }});

mainWindow.loadUrl('https://mail.notes.na.collabserv.com/verse');
...
...`

**Comment by zcbenz** [comment]
As documented:

> the path of preload script has to be absolute path.

**Comment by IdanAdar** [comment]
loadUrl is a remote URL (a website), whereas custom.js is a local file (next to main.js), so what are you referring to in "absolute URL"?

**Comment by etiktin** [comment]
It means it needs to be the absolute *file* path. For example `c:\foo\preload.js` on Windows, or `/foo/preload.js` on POSIX. You can use node.js built-in `path` module to resolve a relative path to a full path.

**Comment by nasht00** [comment]
Well I obviously would not want to hardcore a path specific to my machine.
Can you give an example?
It's pretty basic, say I have a file called custom.js at the root of my electron app.
The same level as my main.js.

How would I refer to this file? So it would work for everyone.

**Comment by sbruchmann** [comment]
@nasht00 You are looking for `path.resolve(__dirname, 'custom.js')`. See [docs](https://nodejs.org/docs/latest/api/path.html#path_path_resolve_from_to).

**Comment by nasht00** [comment]
Thank you, that was it!

**Comment by IdanAdar** [comment]
Thank you sbruchmann.

Just to clarify the original intent of this issue: the remote URL that is loaded outputs desktop notifications in OS X. We would like to capture these in order to add a badge to the Electron-based app.

zcbenz suggested to override the Notification function in a preloaded script.
Does this mean to actually create our own instance of Notification() per https://developer.mozilla.org/en/docs/Web/API/notification?

**Comment by IdanAdar** [comment]
Solved by using this: https://github.com/atom/electron/issues/1803

**Comment by nasht00** [comment]
@sbruchmann 
Everything was working fine, until we used `electron-packager` and now the preload does not load at all.

**Comment by akashnimare** [comment]
@IdanAdar How did you override the native notifications?

**Comment by quanglam2807** [comment]
@IdanAdar I have similar question with @akashnimare. Please help.
