### ISSUE TITLE
Chromium PDF renderer for my own Electron

### ISSUE THREAD

**Issue by EhsaanF** [atom/electron#3085]
I searched a lot for how to display PDF documents in Electron, the solution was to use PDF.js, but unfortunately PDF.js doesn't support my language (Persian) and has issues.

The only way I see now is to use Chromium PDF renderer. I know that would make Electron heavy, but I want to know how can I add it to my own Electron?

Also I want to know that what is "pdf.dll" in Electron root?

**Comment by etiktin** [comment]
When you say that pdf.js doesn't support your language do you mean the actual text is rendered incorrectly or that the UI (toolbar) is not translated?

pdf.dll is currently used for printing to pdf and for regular printing on Windows.

**Comment by EhsaanF** [comment]
The whole document renders incorrectly.

**Comment by etiktin** [comment]
I suggest you also open an issue in the pdf.js repo.

**Comment by hokein** [comment]
Electron doesn't support viewing PDF right since the PDF plugin in Chromium has a heavy dependency on Chrome extension component which is not easy to migrate to Electron.

You can submit the issue in `pdf.js` repo as @etiktin mentioned above. 
I'm closing this issue as won't fix.

**Comment by paulcbetts** [comment]
This would be a good Google SoC project, @zcbenz, we should get Electron into that

**Comment by hokein** [comment]
@paulcbetts 
:clap: It is a nice potential GSoC project.

**Comment by EhsaanF** [comment]
I know, but PDF.js doesn't support anything I want, PDFs those I want to view through Electron are so heavy and takes long time to render with PDF.js. I just wanted to know how can I add Chroumium PDF render engine to Electron? Can you help me how?
