### ISSUE TITLE
Controlling the input that a webview is requesting

### ISSUE THREAD

**Issue by ozsay** [atom/electron#3086]
Hi,

I have a similar scenario to the following:

index.html

    <html>
    <body>
    	<webview src="guest.html"></webview>
    </body>
    </html>

guest.html

    <html>
    <head>
    	<script src="script.js"></script>
    </head>
    <body>
    </body>
    </html>

Usually, when the app runs, the webview requests `script.js` with `file://` protocol to the path `file://script.js` (sort of).

I want to be able to tell the webview to load a different script instead of `script.js`.

The premise is that i don't want to change the contents of the directory that contains `guest.html` and `script.js` (so I can't change `script.js` or `guest.html`).

One way to solve this issue is using a http server in electron back-end to serve the files. Then I can tell the server to serve a diffrent script to the url `http://localhost/script.js` (of course `index.html`'s webview is changed to http protocol).

Is it possible somehow to accomplish this without using a http server?

And on the same topic:

A similar scenario is that guest.html is served by another http server that electron doesn't control.
Is it possible to do the same?

Thanks in advance,
Oz

**Comment by paulcbetts** [comment]
@ozsay The highly invasive way to do this is to register a custom Protocol using the protocol API over the file protocol. Here's a similar example: https://github.com/electronjs/electron-compile/blob/master/src/protocol-hook-44.js

**Comment by zcbenz** [comment]
This is a desired though in-convinient behavior of `file://` protocol, changing it might have unexpected results, and since there is a perfect solution, I'm closing this.

**Comment by ozsay** [comment]
The more I discover electron, it keeps getting better and better..

Thanks!

**Comment by ozsay** [comment]
@zcbenz I tried to do that using `protocol` and I had difficult time to understand why it was not working.

Finally I looked at the example here http://electron.atom.io/docs/v0.33.0/api/protocol/ and saw that `path.normalize` is used. After adding this to my code, it worked.

Maybe you should mention that paths must be normalized in the method description.

Thanks anyways
