### ISSUE TITLE
Using a certificate in electron

### ISSUE THREAD

**Issue by dannysamuel** [atom/electron#3088]
Hi,

I am trying to use a certificate in electron but wasn't sure how to do that. Is there a way to set the certificate up?

Thanks

**Comment by etiktin** [comment]
Maybe this sample app will help: https://github.com/hokein/electron-sample-apps/tree/master/client-certificate

**Comment by hokein** [comment]
Closing it since the link provided by @etiktin gives a solution.

**Comment by dannysamuel** [comment]
Thanks @etiktin
