### ISSUE TITLE
webview tag's event callback arguments not correct

### ISSUE THREAD

**Issue by johnsmith0209** [atom/electron#3090]
I've found that in the callback function of webview tag's event('did-get-response-details'), arguments are not the same as the one in webContents. There should be six arguments, but i only get one(event).
My OS is OSX 10.10.4, and electron is electron-prebuild 0.33.6.

HTML code is:
```javascript
<webview id="wv" src="https://discuss.atom.io/" style="display:inline-block; width:1000px; height:900px;"></webview>
<script>
var webview = document.getElementById('wv');
webview.addEventListener('did-get-response-details', function () {
  console.log('get-reponse-detail', arguments);
});
</script>
```
Here is the console msg:
![pic](http://ww2.sinaimg.cn/bmiddle/7319494cjw1ex1ykphpxyj20vw0ecq61.jpg)

Am I using it right? Thanks a lot!!

**Comment by zcbenz** [comment]
The way `<webview>` handles event follows the custom of DOM, so you need to get the parameters from the `event` Object:

```js
webview.addEventListener('did-get-response-details', function (event) {
  console.log('get-reponse-detail', event.status, event.newUrl);
});
```

**Comment by johnsmith0209** [comment]
Thanks al lot!!
