### ISSUE TITLE
Reliability of Offline API

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron#3091]
I am experimenting with an Electron app that makes use of the Offline API. I use the approach described in the electron docs to the inform the main process about the connectivity status.

What I experienced was that whenever the user's machine (Mac OS X and Win 8/10) goes to sleep, I can not rely on the offline/online event being fired. The events are fired most of the time when the machine goes to sleep and recovers. But especially on longer sleeping period the events are not fired. I guess its related to the fact that the machine goes to hibernate at some point.

Don't know if this is the right place to report, cause it might be related to chromium or OS limitations.

I am using electron 0.33.3

**Comment by zcbenz** [comment]
The implementation of offline/online events in Electron is exactly the same with upstream Chromium, I suggest reporting to [Chromium's issues list](https://crbug.com) instead, since we are not able to solve it on Electron's side.

**Comment by paulcbetts** [comment]
Offline in Chromium means, "100% of the network adapters were removed / are disabled" - it's not at all a reliable check for reachability. If you get `offline` you definitely know the network *won't* work, but getting the `online` event is simply a hint that you _might_ be back online
