### ISSUE TITLE
include 3rd party binaries 

### ISSUE THREAD

**Issue by tobsn** [atom/electron#3093]
I want to convert some image formats within the app - is there any way to include the imagemagick binary into the build? possible for x/dar/win?

**Comment by zcbenz** [comment]
You can write a Node.js module for this purpose.

**Comment by tobsn** [comment]
there are node modules for this but they all leverage the imagemagick binary

**Comment by jlord** [comment]
@tobsn You can build and include imagemagick within your Electron app. You can then use it in your app with node.

For example, in this project of mine I include Portable Git by dropping the entire thing into my project:

- https://github.com/jlord/git-it-electron/tree/master/assets/PortableGit

And then I use it within my Electron app by pointing to it's path:

- https://github.com/jlord/git-it-electron/blob/master/lib/spawn-git.js#L11

**Comment by tobsn** [comment]
thank you for this awesome answer Jessica! :D

**Comment by antoniobrandao** [comment]
@jlord why is it in your example git invoked differently for win23 and the rest? win32 seems to use that winGit variable but in the "else" it seems it is expecting "git" to be in the PATH (?). 

And why the " '"' + "'"'s in the win32 command?

**Comment by jlord** [comment]
> but in the "else" it seems it is expecting "git" to be in the PATH

@antoniobrandao that's because it is on the PATH in OS X and Linux. Windows is different so the Portable Git in this project only ships with and is used in the Windows version.

**Comment by kinoli** [comment]
How would you install imagemagick cli into a folder?
