### ISSUE TITLE
[request] Tray hover event

### ISSUE THREAD

**Issue by renarsvilnis** [atom/electron#3094]
Creating feature request for adding a hover event for [Tray](https://github.com/atom/electron/blob/master/docs/api/tray.md). Is it something that has already been discussed (*couldn't find in the search at least*) and rejected or are there platform limitations?

**Use case**
Change (*or [animate](https://twitter.com/RenarsVilnis/status/654638564328767488)*) icon when files are going get drag-n-dropped onto the tray to display reaction instead of the current behavior of changing the appearance of the cursor.

**Comment by nishanths** [comment]
+1 I can pick this up

**Comment by zhengw060024** [comment]
Is there any event to track mouse on tray？

**Comment by Jc-L** [comment]
See https://github.com/electron/electron/pull/9760 and commit https://github.com/electron/electron/commit/e44f6555036c9e45d0c40e4aa425888fe04be311 adding `mouse-enter` and `mouse-leave` events.

**Comment by hovancik** [comment]
Too bad it's for Mac only
