### ISSUE TITLE
Changing webview src causes pipe error 109 and Electron extinig

### ISSUE THREAD

**Issue by EhsaanF** [atom/electron#3096]
I tried to change src attribute of a webview with push of a button in JavaScript, but it causes pipe error 109 and Electron suddenly exits (without any alert or crash report)

```javascript
$( 'body' ).on( 'click', '.sub-parts li a', function() {
		var pdf_path = $( this ).data( 'pdf' );
		if ( ! pdf_path || typeof pdf_path == 'undefined' )
			return;

		$( '#start-cover' ).hide();
		$( '#viewer' ).show();
		console.log( 'http://localhost:8999/web/viewer.html#' + pdf_path );
		document.getElementById( 'viewer' ).setAttribute( 'src', 'http://localhost:8999/web/viewer.html#' + pdf_path );
	} );
```

It's OK when I execute the same code from DevTools console.

**Comment by zcbenz** [comment]
Can you provide a full example?

**Comment by EhsaanF** [comment]
What do you mean from a full example? I sent my JavaScript code and this is my `<webview>` element:
```html
<webview id="viewer" src="http://localhost:8999/web/viewer.html#/api-test.pdf" style="display: none;"></webview>
```

Should I provide the whole app here?

**Comment by zcbenz** [comment]
A reproducible __minimum__ example would be appreciated, it is really hard to see what's wrong from your code, it is using webview to display PDF file on a local server, and also uses jQuery and involves user action, any factor could be the source of the bug.

**Comment by EhsaanF** [comment]
1- I create a web-server in port 8999 for PDF.js and PDF files.
```javascript
	var serve = serveStatic( __dirname + '/public' );
	var server = http.createServer( function( req, res ) {
		var done = finalhandler( req, res );
		serve( req, res, done );
	} );
	try {
		server.listen( 8999 );
	} catch( e ) {
		require( 'dialog' ).showErrorBox( 'پورت مشغول!', 'پورت 8999 مشغول است! برنامه را ببندید و دوباره امتحان کنید.' );
		app.quit();
	}
```

Server works well.

2- I have a `<webview>` tag to display PDF.js renderer. (PDF.js renderer is the same on used in PDF.js demo)
```html
<webview id="viewer" src="http://localhost:8999/web/viewer.html#/api-test.pdf" style="display: none;"></webview>
```

3- I have a dynamic list of PDFs (currently it's static) marked up like this:
```html
					<ul class="table-of-contents">
						<li>ادبیات فارسی (2)</li>
						<ul class="sub-parts">
							<li><a href="#" data-pdf="/api-test.pdf">درس 1 تا 6</a></li>
							<li><a href="#" data-pdf="/api-flynet.pdf">درس 7 تا 14</a></li>
							<li><a href="#">درس 14 تا 21</a></li>
						</ul>

						<li>کتاب دو</li>
						<ul class="sub-parts">
							<li><a href="#">بخش دو</a></li>
						</ul>
					</ul>
```
Each item that has `data-pdf` attribute should load the PDF in `http://localhost:8999/web/viewer.html#{FILE}` ({FILE} is the `data-pdf` value)

4- jQuery captures links to load PDFs and then changes the `<webview>` src attribute to mentioned URL.
```javascript
	$( 'body' ).on( 'click', '.sub-parts li a', function() {
		var pdf_path = $( this ).data( 'pdf' );
		if ( ! pdf_path || typeof pdf_path == 'undefined' )
			return;

		$( '#start-cover' ).hide();
		$( '#viewer' ).show();
		console.log( 'http://localhost:8999/web/viewer.html#' + pdf_path );
		try {
			document.querySelector( '#viewer' ).setAttribute( 'src', 'http://localhost:8999/web/viewer.html#' + pdf_path );
		} catch( e ) {
			console.log( e );
		}
	} );
```
I wonder why the same code works correctly when I type it in DevTools console.

**Comment by EhsaanF** [comment]
I found out how to solve the problem by just putting a simple timeout to load the URL.
```javascript
		setTimeout( function() {
			webview.setAttribute( 'src', 'http://localhost:8999/web/viewer.html#' + pdf_path );
		}, 20 );
```

As explained [here](http://answers.awesomium.com/questions/212/application-crashing.html) for Awesomium too, looks like it's a Chromium bug, not Electron or Awesomium themselves.

@zcbenz Thanks for spending time on my problem.

**Comment by candidosales** [comment]
Thank you! =D
