### ISSUE TITLE
[Windows] Is it possible to run only one instance of the app?

### ISSUE THREAD

**Issue by lipis** [atom/electron#3098]
If the user is going to start the app again it should active the current instance if it's already running.

**Comment by kurisubrooks** [comment]
On OS X, it already does this. 
I'm not sure if there's much you could do backend for this.

**Comment by lipis** [comment]
It looks like it's already here: #648

**Comment by lipis** [comment]
https://github.com/mnichols/monogamous/issues/2

**Comment by M4kaveli** [comment]
Hello, with build portable app.makeSingleInstance doesn't work..
Any idea?

**Comment by akashnimare** [comment]
@M4kaveli it should work. How are you using it?
```

const isAlreadyRunning = app.makeSingleInstance(() => {
	if (mainWindow) {
		if (mainWindow.isMinimized()) {
			mainWindow.restore();
		}

		mainWindow.show();
	}
});

if (isAlreadyRunning) {
	return app.quit();
}
```

**Comment by M4kaveli** [comment]
@akashnimare  Hello thanks for your reply,
I tried this code on createWindow function this work fine but when i do a portable build this not work...
same with app.relaunch()

**Comment by M4kaveli** [comment]
i tried only like this : const isAlreadyRunning = app.makeSingleInstance(() => {});

and work fine :)

Any idea for app.relaunch sir ?

**Comment by xalc** [comment]
@M4kaveli  any idea for portable apps? How to start a single decompress for portable App?
