### ISSUE TITLE
Since electron>=0.33.7 not been able to run via xvfb

### ISSUE THREAD

**Issue by FWeinb** [atom/electron#3099]
I am using electron on travis but since electron>=0.33.7 it is not possible to start electron on a headless machine  with just xvfb. 

I get the following errors:
```sh
[5420:1015/174606:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Xlib:  extension "RANDR" missing on display ":99.0".
Xlib:  extension "RANDR" missing on display ":99.0".
[5436:1015/174606:ERROR:sandbox_linux.cc(345)] InitializeSandbox() called with multiple threads in process gpu-process
[5420:1015/174606:ERROR:browser_gpu_channel_host_factory.cc(133)] Failed to create channel.
```

**Comment by zcbenz** [comment]
We have been running atom and electron's specs on Travis and thing seem to work, you can find our settings at:
https://github.com/atom/electron/blob/master/.travis.yml
https://github.com/atom/electron/blob/master/script/cibuild

But there is also a Chromium bug on running 32bit binary on 64bit kernel that looks similar to this one:
https://code.google.com/p/chromium/issues/detail?id=527209

**Comment by FWeinb** [comment]
I am using the new container based build system on travis, might that be a reason?
[Here](https://travis-ci.org/FWeinb/FWeinb/electron-screenshot-app/builds/85579625) is the full log of the failing task. I am just starting [this](https://github.com/FWeinb/electron-screenshot-app/blob/fix-linux/app.js) file via electron.

**Comment by FWeinb** [comment]
Just tried to run 0.34.0 and everything looks good again.

**Comment by rhysd** [comment]
@zcbenz 

I'm currently having the same issue with Electron v1.3.3.  But other app doesn't reproduce this bug.  I think there is another root cause for this.
