### ISSUE TITLE
feature request: privilege elevate

### ISSUE THREAD

**Issue by zh99998** [atom/electron#3104]
for a desktop application, sometimes we access system function and need privilege elevate. 
and windows, linux, and OSX are all provided a GUI way to elevate. 

unfortunately, elevate in GUI is too complex for a cross-platform script application. there is no cross-platform way to do it. i have to depends on many platform-related modules for such a fucking thing. and there still many problem. and some other things like communication or control is much more difficult. 

this is one of "The hard parts" for javascript desktop application.

if there is an build-in function like:
elevate(external_program) and elevate(javascript_function)

things be much more better.

**Comment by zcbenz** [comment]
We have an node module for this: https://github.com/atom/node-runas.

In Electron we usually add new built-in modules only when 1) it is very necessary, 2) or it is already in Chromium.
