### ISSUE TITLE
Electron App Freezes on minimize to dock on OSX

### ISSUE THREAD

**Issue by ex3ndr** [atom/electron#3106]
It seems that app became almost freezed and it is unable to check websocket connection to load updates.

Same behaviour was when chrome slows down background tabs by setting minimal setTimeout time to 1 s or something. This could be fixed with web worker that implements "setTimeout" emulation. This hack doesn't work in Electron.

Any workaround?

**Comment by zcbenz** [comment]
The renderer process lowers it priority when it is not active, you can try the solutions in #2822.
