### ISSUE TITLE
Problems symbolizing windows crash dumps.

### ISSUE THREAD

**Issue by lele85** [atom/electron#3110]
Hi, we are building a product on electron and actually we are not able to symbolize correctly crash dumps on windows.

I will explain the process i'm using to decode it, giving you an example with default electron prebuilt release.

I've added this snippet in `index.html`:
  https://gist.github.com/lele85/11fb7d8c5a76a348e261

I've got this node server running on localhost that is collecting dumps:

   https://gist.github.com/lele85/fd785705a4a83b2bccef

When i launch app crash reporter is configured then `process.crash()` is called. Server script correctly collects `.dmp` file. With this crash dump i'm using `minidump_stackwalk.exe` from your repo ( https://github.com/atom/chromium-breakpad/blob/master/dump_syms.exe ) to decode `.dmp` against correct symbols. I'm doing this step in cygwin shell (`@32 bit`) because it looks like the tool was compiled in this evironment:

    minidump_stackwalk.exe ./dumps/crash.dmp ./electron.breakpad.syms > stacktrace.txt

I'm using windows 8.1 `@64bit`, using electron prebuilt `v0.33.9`, symbols, cygwin shell `@32bit`. In the resulting stacktrace i can't find any reference to `process.crash()` i only have some references to crashpad itself that's puzzling me.

Here you can find dump file and resulting decoded stacktrace: https://www.dropbox.com/s/0owojrtrx95o2e2/crash.zip?dl=0

Any help on that is appreciated. Thanks for the work you are doing with Electron. It's a great piece of software. :)

**Comment by zcbenz** [comment]
You probably have to run `minidump_stackwalk` on POSIX systems, the prebuilt `minidump_stackwalk.exe` binary has never been seriously tested, so there is no guarantee that it can work. And I think no one is actually using `minidump_stackwalk.exe` on Windows.

I symbolized the dump file on OS X and the result is good:

```
Operating system: Windows NT
                  6.3.9600 
CPU: x86
     GenuineIntel family 6 model 61 stepping 4
     2 CPUs

Crash reason:  EXCEPTION_ACCESS_VIOLATION_WRITE
Crash address: 0x0
Assertion: Unknown assertion type 0x00000000
Process uptime: 0 seconds

Thread 0 (crashed)
 0  electron.exe!atom::`anonymous namespace'::Crash() [atom_bindings.cc : 28 + 0x0]
    eip = 0x00ac90d2   esp = 0x007fe9d0   ebp = 0x007feac4   ebx = 0x00000000
    esi = 0x03e2c860   edi = 0x007feb14   eax = 0x07cb8be0   ecx = 0x007feaac
    edx = 0x07cb8be0   efl = 0x00010202
    Found by: given as instruction pointer in context
 1  electron.exe!mate::internal::Dispatcher<void >::DispatchToCallback(v8::FunctionC
allbackInfo<v8::Value> const &) [function_template.h : 236 + 0x16]
    eip = 0x00ac93df   esp = 0x007fe9d4   ebp = 0x007feac4
    Found by: call frame info
 2  node.dll!v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCall
backInfo<v8::Value> const &)) [arguments.cc : 33 + 0x6]
    eip = 0x6d38f7ee   esp = 0x007feacc   ebp = 0x007feaf8
    Found by: call frame info
...
```
