### ISSUE TITLE
MenuBar Template Icon Greys Out

### ISSUE THREAD

**Issue by adilanchian** [atom/electron#3112]
I have set a menubar icon in my app running on Mac OS and Electron v0.32.2 and it looks great but, I am having an issue with when it is clicked. On a black menubar it turns grey instead of staying white. I have double checked to make sure the alpha is correct and it is. Not sure if this is something that has been encountered before? Here are some screen shots of the issue : 

<img width="225" alt="screen shot 2015-10-16 at 11 02 19 am" src="https://cloud.githubusercontent.com/assets/13204620/10545194/75f7fcb8-73f5-11e5-9962-6757843563ff.png">

<img width="232" alt="screen shot 2015-10-16 at 11 02 30 am" src="https://cloud.githubusercontent.com/assets/13204620/10545201/7a63afb8-73f5-11e5-90bf-e2f6518bb402.png">

Thanks for the help in advance!

**Comment by kurisubrooks** [comment]
This is an issue with OS X itself. It does this with other tray icons as i've noticed. The way to work around this is by setting an `Tray.setPressed(image)`, specifically choosing an image to replace the static one when the tray icon has been pressed.

**Comment by adilanchian** [comment]
Hey kurisubrooks,

Thanks for the reply. I'm going to try that out but I appreciate the help!

-Alec
