### ISSUE TITLE
Atom + Linux clipboard character limitation (4000 characters)

### ISSUE THREAD

**Issue by jliverman** [atom/electron#3116]
FYI I opened a discussion topic on the Atom forum about this here:

https://discuss.atom.io/t/linux-clipboard-character-limitation-4000-characters/21746

I have 2 files:

- filename "works" has 4000 characters
- filename "no_work" has 4001 characters

> [jliverman@centosvbox ~]$ wc -c works
> 4000 works

> [jliverman@centosvbox ~]$ wc -c no_work
> 4001 no_work

If I copy the "works" file content to the Linux X11 clipboard using the "xsel -b" command and attempt to paste it into a document I have opened in Atom/Electron using Control+V (this is Atom 1.0.19 + Electron 34 on CentOS 7.1 with xorg 1.15 and GNOME 3.8.4; see below) it works as expected.

    [jliverman@centosvbox ~]$ xsel -b < works
    [jliverman@centosvbox ~]$

However, if I do the same with the "no_work" file then Atom/Electron appears to freeze for several seconds. Atom/Electron eventually unfreezes but nothing is pasted into the open document.

    [jliverman@centosvbox ~]$ xsel -b < no_work
    [jliverman@centosvbox ~]$

This happens regardless of clipboard content (e.g. it can be a single line of "Lorem Ipsum"-style content). This behavior does NOT occur with other editors like gedit (Control+V), ScITE (Control+V), gvim ("+ register), etc.

So is the problem in Atom/Electron or is the problem in X11 or GTK? I've searched the Atom & Electron (Github) forums and Google for answers related to any 4000-character limitation in X11, GTK, the ICCCM, etc. and have found nothing... So any help is greatly appreciated.

    [jliverman@centosvbox ~]$ apm -v
    apm  1.0.5
    npm  2.13.3
    node 0.10.40
    python 2.7.5
    git 1.8.3.1

    [jliverman@centosvbox ~]$ uname -a
    Linux vboxjl2076 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    [jliverman@centosvbox ~]$ cat /etc/centos-release
    CentOS Linux release 7.1.1503 (Core) 

    [jliverman@centosvbox ~]$ X -version

    X.Org X Server 1.15.0
    Release Date: 2013-12-27
    X Protocol Version 11, Revision 0
    Build Operating System:  2.6.32-220.17.1.el6.x86_64 
    Current Operating System: Linux vboxjl2076 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64
    Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-229.14.1.el7.x86_64 root=UUID=d1079f78-f24d-4084-be8b-466bbdfed0f2 ro vconsole.keymap=us crashkernel=auto
    vconsole.font=latarcyrheb-sun16 rhgb quiet LANG=en_US.UTF-8
    Build Date: 10 April 2015  11:44:42AM
    Build ID: xorg-x11-server 1.15.0-33.el7_1 
    Current version of pixman: 0.32.4
            Before reporting problems, check http://wiki.x.org
            to make sure that you have the latest version.

    [jliverman@centosvbox ~]$ gnome-shell --version
    GNOME Shell 3.8.4

**Comment by zcbenz** [comment]
Can you try whether Chromium has this problem?

**Comment by jliverman** [comment]
I installed Google Chrome Version 46.0.2490.71 (64-bit) from Google's YUM repo and then created a small test web page (in a local file called paste_test.html) containing the following HTML:

    <!DOCTYPE html>
    <html>
      <body>
        <textarea rows="50" cols="100"></textarea>
      </body>
    </html>

I then loaded the page (paste_test.html) using Google Chrome and attempted to paste the content of the "works" file (4000 characters) into the textarea element using "xsel -b < works" followed by Control+V. This worked as expected.

However, when I did the same for the "no_work" file (4001 characters) using "xsel -b < no_work" followed by Control+V I got what appeared to be the same behavior as the Atom editor i.e. the Google Chrome tab appeared to freeze for several seconds. After this freeze was finished the page seemed to return to normal and nothing had been placed into the textarea control (confirmed by checking the textarea's "value" property).

I imagine this confirms it is an issue with Electron versus Atom (assuming it was either/or; I understand this may still be a problem with X11, GTK, etc.)?

**Comment by jliverman** [comment]
Out of curiosity I started Google Chrome using the command-line and observed that it threw a "Gdk: shmget failed ... (No space left on device)" error to STDERR when the errant paste was performed:

    [jliverman@centosvbox ~]$ google-chrome-stable paste_test.html
    pci id for fd 14: 80ee:beef, driver (null)
    libGL error: core dri or dri2 extension not found
    libGL error: failed to load driver: vboxvideo
    [28402:28402:1019/175249:ERROR:sandbox_linux.cc(338)] InitializeSandbox() called with multiple threads in process gpu-process
    [28238:28238:1019/175345:ERROR:browser_main_loop.cc(243)] Gdk: shmget failed: error 28 (No space left on device)
    [jliverman@centosvbox ~]$ 

Please note that all of the other errors are present even with normal (working) operation. Also note that I am using CentOS inside of VirtualBox (version 4.3.28 r100309); I'm not sure if that matters or not. Lastly, Atom doesn't seem to place anything on STDOUT/STDERR when started from the command-line so I got nothing from it for the good or bad (errant) paste operations.

Does this point to an issue in GTK (as Gdk may be the GIMP Drawing Kit)?

**Comment by zcbenz** [comment]
Electron shares the same clipboard with Chromium, I suggest reporting it to [Chromium's issues list](https://code.google.com/p/chromium/issues/list) since it is an upstream bug.

**Comment by jliverman** [comment]
It seems the Chromium issue tracker already had a thread opened for this issue: https://code.google.com/p/chromium/issues/detail?id=515401

It also seems that it has been reproduced/validated by one of the Chromium devs. I added my 2 cents to the thread just in case it makes tracking down the issue any easier. 

Thanks!

**Comment by ebiggers** [comment]
I posted an update on the chromium issue linked above.  The issue actually appears to be caused by a bug in the 'xsel' program.

**Comment by jliverman** [comment]
I have replaced my use of the xsel program with xclip and find the behavior is as expected. So I agree with ebiggers in saying that the bug is in xsel, not Electron/Chromium. Thus I feel that this issue can be closed.

My hat's off to you, ebiggers! I can only hope to be as much of a BEAST as you one day!! Great job!!!
