### ISSUE TITLE
[webContents.savePage] Is not perfect, download the file can not reach chorme 'ctrl+s'

### ISSUE THREAD

**Issue by zg2013** [atom/electron#3121]
The method appears to be very imperfect, the data is missing, and it is not normal.

Contrast test, url is 'www.baidu.com'
The [webContents.savePage] effect of elentron is:
![ele](https://cloud.githubusercontent.com/assets/5134292/10556807/e9212750-74c2-11e5-9ab7-acf2e09950f3.png)

Chrome is:
![chrome2](https://cloud.githubusercontent.com/assets/5134292/10556809/fa9d1ce6-74c2-11e5-8db0-2f9f7bb3a366.png)

Web page and can not be offline Preview

**Comment by hokein** [comment]
Could you load `http://baidu.com` in Electron and open the `Sources` panel in `DevTools` to find recheck all the external resources? From the images, seems that the url is loaded with a baidu acount in Chrome while it isn't in electron. 

The reason why web pages don't be previewed correctly is a wrong saving directory of the external resources, which is a bug of Electron.

**Comment by appelgriebsch** [comment]
Additionally I noticed that it will not save the content of an embedded webview... :(

**Comment by zcbenz** [comment]
I believe this has been fixed by #3128.
