### ISSUE TITLE
Window Title set to Electron when running on Windows

### ISSUE THREAD

**Issue by sleman** [atom/electron#3122]
Title looks fine when building for Mac. However after building for Windows, the window title shows: Electron instead of html title.

Tried the following:
* Set using `browserwindow.setTitle()`.
* Set using index.html `<title>` tag.

Strange thing is if browser window loses focus then regains focus, the title magically changes once the window is visible again.

**Comment by zcbenz** [comment]
Can you provide an example app? I'm unable to reproduce this.

**Comment by sleman** [comment]
I'll try to create a new project I can share when I get a chance. This person is having the same issue: http://stackoverflow.com/questions/31882538/window-title-not-showing-correctly-electron

**Comment by sleman** [comment]
Issue occuring with plain project started with get started instructions
https://www.dropbox.com/s/a7gh6xsyx2ug7qa/electron.zip?dl=0

**Comment by zcbenz** [comment]
Do you have DWM closed on your machine? Seems that the titlebar failed to repaint.

**Comment by zcbenz** [comment]
Refs #1821.

**Comment by sleman** [comment]
I believe so. I only saw the issue when using Remote Desktop. If a fix is not easy, why not change the default window title bar from `Electron` to be empty? This would be much better for end users rather than confuse them with the Electron name.

**Comment by zcbenz** [comment]
I'm merging this to #1821. To set default title, you can set the `title` option of `BrowserWindow`.
