### ISSUE TITLE
Unable to prevent default when using require("remote")

### ISSUE THREAD

**Issue by NStal** [atom/electron#3123]
Platform:Linux/Ubuntu 15.04
Electron:v0.34.0

KeyEvent of `HTMLInputElement` can't be `preventDefault`ed, when I call preventDefault after a call to require("remote").require("shell").openExternal("...")

I can put remote things in setTimeout(...,0), so not a big problem, but do cost me sometimes to find it out. I'm migrating my webapp to Electron.

**Comment by zcbenz** [comment]
Can you provide an example?

**Comment by zcbenz** [comment]
Closing until more information is provided.
