### ISSUE TITLE
ShowWindow working in node but not in electron

### ISSUE THREAD

**Issue by antoinepairet** [atom/electron#3124]
I am trying to interact with another software on Windows. At some point, I need to show the other program. It works perfectly when done via node. It does not when done via electron. Since I use `node-ffi` I first reported the issue there https://github.com/node-ffi/node-ffi/issues/255. 
As Nathan suggests, could it related to the way electron interacts with the windows event loop?

I am consuming a DLL through `node-ffi` both via `node` and `electron`. The DLL allows to control another program. All functions but one work great. There is one function that is not working using electron while it works using nodejs. When that particular function is called from a terminal using node it works. However, when called from an electron app, it does not work. No error is thrown. The return code is 0 = everything is OK.

How can I debug this issue?

The goal of that function is to bring the UI of the other program to the top. It takes an integer as argument and returns a short:

````js
var dll = ffi.LoadLibrary('myDLL', {
    // ...
    DxSetWindowPlacement: ['short', ['int']]
});

dll.DxSetWindowPlacement(1); // works in nodejs, not in electron
````

The corresponding C header file contains:

````c
#ifdef WINDOWS
extern "C" short WINAPI DxSetWindowPlacement (
    UINT uShowCmd
    );
#else
// ...
````

In the end, the DLL will call the `ShowWindow` function: [see MSDN doc](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx)
MS doc says:
>As noted in the discussion of the nCmdShow parameter, the nCmdShow value is ignored in the first call to ShowWindow if the program that launched the application specifies startup information in the structure. In this case, ShowWindow uses the information specified in the STARTUPINFO structure to show the window. On subsequent calls, the application must call ShowWindow with nCmdShow set to SW_SHOWDEFAULT to use the startup information provided by the program that launched the application. This behavior is designed for the following situations ...

Calling the function twice or more does not have an impact. I also tried different values without success.

How can I tackle this issue? Let me know if I can provide more information.

Thanks in advance for your help!

**Comment by zcbenz** [comment]
It is probably because Electron is a multi-process GUI program, Windows has secrets rules of on showing/focusing window and it says nothing in the error message. #2867 is another example.

I'm afraid there is nothing we can do on this, and it is very likely only someone from Microsoft in Windows team can answer this.
