### ISSUE TITLE
openDevTools seems not to be documented

### ISSUE THREAD

**Issue by IonicaBizau** [atom/electron#3125]
I expected to see it in the [Browser Window docs](https://github.com/atom/electron/blob/c7d9352972ff5c90733a3ce0eb3add86fd101905/docs/api/browser-window.md). :thought_balloon:

**Comment by hokein** [comment]
The `openDevTools` API has been moved to [`webContents`](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsopendevtoolsoptions) from `browserWindow`. The `BrowserWindow.openDevTools` is a deprecated API we prefer developers to use `win.webContents.openDevTools` instead.
