### ISSUE TITLE
Is it possible to set negative coordinates for windows?

### ISSUE THREAD

**Issue by IonicaBizau** [atom/electron#3126]
I tried `mainWindow.setPosition(20, -35)` but it doesn't become *invisible* (out of the user's view). :smile:
Is it a bug or a feature?

Is it possible to set negative coordinates for windows?

**Comment by paulcbetts** [comment]
Window coordinates are always relative to the primary monitor so it is indeed quite possible to have negative positions. If you want to hide the window, just call `hide`

**Comment by zcbenz** [comment]
Some platforms forbid windows to be moved out of screen by default, you can probably have a try of `enable-larger-than-screen` option, which removes that limitation.

**Comment by IonicaBizau** [comment]
@paulcbetts I already used `hide`, but I would like to make an animation moving the window out of the screen.

@zcbenz I tried that, but I see no change. I can move the windows out of the screen manually, but how can I would like to do that programatically. I the past I created [BAT](https://github.com/IonicaBizau/bat)–a platform similar to Electron (of course, not so powerful! :joy:). I tried moving the window using `setWindowPosition(-200, -200)` and it alsmot worked, but only vertically (the top side went out of the visible area).

[Here](https://github.com/IonicaBizau/bat/blob/345fb73dad3f3b5eea81d36e4cb6a50b282b4028/source/main.cpp#L186-L197) is the snippet that moves the window. :thought_balloon:

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by IonicaBizau** [comment]
@zcbenz Ubuntu 15.10, with default Unity desktop.

**Comment by IonicaBizau** [comment]
@zcbenz `getPosition` returns negative coordinates–which may explain why [the tests are passing](https://github.com/atom/electron/blob/0d9e0a38c015142666d144a6199401af6dd1054d/spec/api-browser-window-spec.coffee#L187-L191).

**Comment by zcbenz** [comment]
On Linux this totally depends on which window manager you use, some allows moving the window to anywhere you want, and some forces the window to be inside the screen, Electron just asks the window manager to move the window to a specific position,

**Comment by IonicaBizau** [comment]
> On Linux this totally depends on which window manager you use

@zcbenz Good point! :sparkles: Tried it on open-box and it works even without `enable-larger-than-screen`. Thanks! :cake:
