### ISSUE TITLE
[Documentation - broken anchor link in browser-window.md (?)]

### ISSUE THREAD

**Issue by learningjs** [atom/electron#3127]
:memo:

In [browser-window](http://electron.atom.io/docs/v0.33.0/api/browser-window) doc, the instance method [win.close()](http://electron.atom.io/docs/v0.33.0/api/browser-window/#win-close) links to the [Event: 'close'](http://electron.atom.io/docs/v0.33.0/api/browser-window/#event-39-close-39), but looks like the link is [broken](http://electron.atom.io/docs/v0.33.0/api/browser-window/#event-close).

I'd like to send a pull request to fix it, but I am not sure what would be the right solution.

Can someone give me a hint?

**Comment by hokein** [comment]
It's likely a issue of [`electron.atom.io`](https://github.com/atom/electron.atom.io).

\cc @jlord

**Comment by jlord** [comment]
Yep, this is an issue with the website. Closing here and opening over there.
