### ISSUE TITLE
Tray Disappears after v0.34 update

### ISSUE THREAD

**Issue by kurisubrooks** [atom/electron#3130]
As of the 0.34 update, the tray icon seems to disappear after about a minute.
I've looked around with past issues to see if I could find anything similar, and I found #822. 
I tested with the fix mentioned in that issue, and to my surprise the tray icon now stayed for around 2 minutes, but still disappeared after time.

This seems to have only started occurring as of the 0.34 update, as my syntax has not changed from when I was using 0.33.8.

**Comment by zcbenz** [comment]
Can you provide an sample app?

**Comment by kurisubrooks** [comment]
Here is my current syntax:

```
var BrowserWindow = require('browser-window');
var app = require('app');
var Menu = require('menu');
var Tray = require('tray');

app.on('ready', function() {
	var appIcon, contextMenu;
	if (process.platform == 'darwin') {
		appIcon = new Tray(path.join(__dirname, 'resources', 'IconTemplate.png'));
		appIcon.setPressedImage(path.join(__dirname, 'resources', 'IconPressed.png'));
	} else appIcon = new Tray(path.join(__dirname, 'resources', 'IconWindows.ico'));
	if (settings.dev_mode) contextMenu = Menu.buildFromTemplate(dev_template);
	else contextMenu = Menu.buildFromTemplate(nodev_template);

	appIcon.setToolTip('EEW');
	appIcon.setContextMenu(contextMenu);

	var nodev_template = [
		{label: locale[lang].about,click: function(){}},
		{type: 'separator'},
		{label: locale[lang].help,click: function(){open('http://lumios.xyz/support.html');}},
		{label: locale[lang].settings,click: function(){electron.newSettings();}},
		{type: 'separator'},
		{label: locale[lang].contribute,click: function(){open('https://github.com/lumios/eew');}},
		{label: locale[lang].bug,click: function(){open('https://github.com/lumios/eew/issues');}},
		{label: locale[lang].updates,click: function(){}},
		{type: 'separator'},
		{label: locale[lang].quit,click: function(){logger.debug('Closed via Tray Menu');process.exit(0);}}
	];
});
```

Both templates are defined, but i've only included one for the sake of the example, as it's rather lengthy. Please let me know if you need all the defined variables.

**Comment by kurisubrooks** [comment]
If you would like to see my full syntax, please check here: 

https://github.com/lumios/shake/blob/master/src/index.js
https://github.com/lumios/shake/blob/master/src/electron.js

**Comment by zcbenz** [comment]
Your `appIcon` was garbage collected, try:

```js
var appIcon = null;
app.on('ready', function(){
```

**Comment by kurisubrooks** [comment]
This seems to have worked! Thanks so much.
Strange, it only happened in v0.34 however.
Thanks again!
