### ISSUE TITLE
Is it possible to add a 'contextmenu' event to web contents API?

### ISSUE THREAD

**Issue by meowlab** [atom/electron#3135]
Under the present circumstances, if we use `browserWindow.loadUrl('www.google.com')` to load a website (not a website I can control and cannot use `require('ipc')` since there was a conflict), it has no way to control or enable the website's context menu, all right click to webpage will be ignored.

If we add `contextmenu` event to web contents API, it will provide a way to trigger self-defined menu without any support in render side, although it's not as good as a 'native browser' context menu, but it at least work.

Any ideas? Thanks!

**Comment by zcbenz** [comment]
You can use `preload` script to do hack the `contextmenu` event in arbitrary page, see the `preload` option of `web-preferences`:
http://electron.atom.io/docs/v0.33.0/api/browser-window/#new-browserwindow-options

usually we don't add every DOM event to browser side unless there is a strong reason.

**Comment by meowlab** [comment]
Thanks for help! I missed it

**Comment by meowlab** [comment]
Hi @zcbenz , sorry to bother again
I just tried use `preload` in the `web-preferences` and set a hook on `contextmenu` event successfully.

But I found there was no way to use things like `require`, if I invoke `require` in `preload`, electron will tell me
```javascript
[37421:1019/195457:INFO:CONSOLE(96)] "Unable to load preload script /Users/******/web-hook.js", source: /Users/*******/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/init.js (96)
```

The more wired thing is: if my `preload` is something like:
```javascript
console.log("meow");
var bw = require('browser-window');
````
In console electron will tell me 
```
[37421:1019/195457:INFO:CONSOLE(17)] "meow", source: /Users/******/web-hook.js (17)
[37421:1019/195457:INFO:CONSOLE(96)] "Unable to load preload script /Users/******/web-hook.js", source: /Users/*******/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/init.js (96)
```
The script seems both load successfully and not, like a Schrodinger's cat :P

Since the description of `preload` in document is so simple, I don't know whether it's by design or not, any ideas? Thanks!

PS:`console.log(require)` in `preload` gives me that:
```javascript
[37346:1019/195340:INFO:CONSOLE(20)] "function require(path) {
    return self.require(path);
  }", source: /Users/******/web-hook.js (20)
```
Seems not a undefined-require issue.

**Comment by MichaelOstermann** [comment]
Instead of doing `var bw = require('browser-window')`, you need to do this:

```javascript
var remote = require('remote');
var bw = remote.require('browser-window');
```

See the [remote docs](https://github.com/atom/electron/blob/master/docs/api/remote.md) for more information on this! :)

**Comment by meowlab** [comment]
@MichaelOstermann 
It works! Thanks!
I just imagine preload is running on main process because it can access node require all time :)

**Comment by kamesh-a** [comment]
Hope this helps. 
```
https://github.com/kamesh-a/electron-samples/tree/master/DynamicContextMenu
```
But still i am struggling to find a way to write dynamic context menu to load suggestions.

**Comment by meowlab** [comment]
@kamesh-a Thanks~
