### ISSUE TITLE
When HTML Imports and <webview> used together, sometimes it will cause page pending.

### ISSUE THREAD

**Issue by jwu** [atom/electron#3137]
## desc:

I've been met this problem for several months. It is very hard to reproduce it in previous version. But since v0.33.4 (and a cool thing is v0.33.3 will not meet this issue), it become 100% to reproduce the problem.

The issue relates with HTML import and webview, when they work together, a webview `ipc.sendSync` function will happen to insert into the HTML import request, and eventually it will block the HTML imports, which make the page stun there.

## example code:

To help Electron team easily locate the problem, I create a repo for this issue: https://github.com/jwu/electron-html-import-pending, you can follow the README to run the app, it also shows how to reproduce it.

If things go right, we will see a window like this:

![screen shot 2015-10-19 at 6 48 42 pm](https://cloud.githubusercontent.com/assets/174891/10575865/0920ce72-7692-11e5-9c67-80e88db8a95a.png)

But if a pending happens, it will give you a blank white window like this:

![screen shot 2015-10-19 at 6 49 25 pm](https://cloud.githubusercontent.com/assets/174891/10575884/21b32930-7692-11e5-84ca-bfdee99ee8fa.png)

Note, in this time, if the dev-tools opened (open by default), go to the Network session, and you will see a pending item remains in it. Plus the call stack is as strange as what I describe --- a syncing ipc after an event emitter:

![screen shot 2015-10-19 at 6 50 24 pm](https://cloud.githubusercontent.com/assets/174891/10575980/a2843630-7692-11e5-95d0-b4b4daf3f7fc.png)

## test environment:

 - System: Mac OSX
 - Electron ver: v0.34.0. It starts quite easy to reproduce it since v0.33.4. versions below it including v0.33.3 is hard to reproduce in simple case, but the problem already there, and I can only reproduce it in complicated code.

Hope the sample code and the information can help you locate the problem.

**Comment by zcbenz** [comment]
This should have been fixed by #3833.

**Comment by jwu** [comment]
Hi @zcbenz ,

I test this in Electron v0.36.2, and it works! Thank you very much.

Regards,
Wu
