### ISSUE TITLE
Feature request - Find/Search content in Webview Tag

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#3138]
Hello,

Is there any property existing to accomplish this in webview tag in electron, I couldn't find the replacement. Do point me in the direction , if i am missing something here.
```
<webview>.find(string searchText, FindOptions options, function callback)

```

**Comment by subwaymatch** [comment]
+1 for this feature!

**Comment by neelj** [comment]
+1

**Comment by kamesh-a** [comment]
Any luck on this, Implementing a search functionality inside app is crucial. Please let us know is there by any chance this can be landed in stable builds sometime soon.

currently we are tying to inject script and highlight the words , which is overkill to scan entire document plus if there is any iframe it wont pass through due to CSP.

Having this "webview.find", implemented would be useful for many applications.

Thanks.

**Comment by kamesh-a** [comment]
@deepak1556  awesome thanks for the PR. eager to test the build.
