### ISSUE TITLE
Problems resizing the app on HDPi displays on Windows.

### ISSUE THREAD

**Issue by lipis** [atom/electron#3140]
Does anyone else have issues with it?

**Comment by Yserz** [comment]
Yes, it looks like the apps size and positioning is not respecting the scaling option in windows.

**Comment by zcbenz** [comment]
Can you describe what problems you saw?

**Comment by lipis** [comment]
@Yserz can you share the screenshots?!

**Comment by Yserz** [comment]
![resize](https://cloud.githubusercontent.com/assets/1138344/10583602/20abbc4a-768e-11e5-95c0-ba2174e5ffba.png)

STR:
1 Set scaling setting in windows 10 to e.g. 175%
2 Start an electron app which works with screen resolution etc.

Actual:
App starts, app should resize to a given value but hangs

Expected:
App resizes to the given value

**Comment by lipis** [comment]
In normal conditions the loading circle would be in the middle.. and this is not a CSS issue.. 

(not sure how to describe it better)

**Comment by zcbenz** [comment]
Can you provide an example app? I'm running Windows under HIDPI and the default app looks good.

Also is it a Windows 10 specific problem?

**Comment by Yserz** [comment]
The problem is only when the app resizes itself. It works properly when the size is changed by user interaction. I can't test it on win 8.

**Comment by zcbenz** [comment]
It is probably related to how you changed window size, an reproducible example would be very helpful on this.

**Comment by lipis** [comment]
There was strange combination of setting the minimum and maximum width of the window that was causing it.. so lets close it for now and if something else we'll report back. Thanks @zcbenz
