### ISSUE TITLE
'will-download' event does not leave waiting for response state

### ISSUE THREAD

**Issue by adilanchian** [atom/electron#3142]
I'm using the will-download event, in Electron 0.34.0, to get the mimeType "application/pdf" from a site where the pdf is sent from a server. Once I hit the pdf URL I grab the url and use webContents.executeJavaScript, with JQuery, to run code to replace the src of an iFrame so I can display the PDF inline. This method has worked up to Electron v0.32.2 but every version after that I get stuck with this will-download issue. Here is some code to better explain the process I've taken to get to where I am. Any insight on this matter would be great. Thanks in advance!

```
  spWindow.webContents.session.on('will-download', function(event, item, webContents)
     {
         if(item.getMimeType() == 'application/pdf')
        {
          console.log("Is Loading? : "+webContents.isLoading());
          event.preventDefault();
          console.log("Waiting For Response? : "+webContents.isWaitingForResponse());
          console.log(webContents.getUrl());

          // webContents.stop() does not seem to function in this instance
          webContents.stop();
          
          // Never reaches 'did-finish-load'
          webContents.on('did-finish-load', function()
          {
            var jsToRun = "$('iframe').attr('src', 'url_from_server');";
            console.log("Injecting : "+jsToRun);
            spWindow.webContents.executeJavaScript(jsToRun);
            console.log("Waiting For Response? : "+webContents.isWaitingForResponse());
          });
        }
      });
```

Output for this Code : 
```
Is Loading? : true
Waiting For Response? : true
*Loads PDF URL*
```

Thanks again for the help!

**Comment by hokein** [comment]
The `did-finish-load` event will not be emitted when the `webContents` loads a `pdf` url. I test it in v0.32.2 and v0.34.0. You may try:

```
spWindow.webContents.session.on('will-download', function(event, item, webContents) {
  if(item.getMimeType() == 'application/pdf') {
    console.log("Is Loading? : "+webContents.isLoading());
    event.preventDefault();
    console.log("Waiting For Response? : "+webContents.isWaitingForResponse());
    console.log(item.getUrl());
    webContents.stop();
    item.on('done', function(e, state) {
      console.log(state); // should be cancelled
      var jsToRun = "$('iframe').attr('src', 'url_from_server');";
      console.log("Injecting : "+jsToRun);
      spWindow.webContents.executeJavaScript(jsToRun);
      console.log("Waiting For Response? : "+webContents.isWaitingForResponse());
    });
  }
});
```

**Comment by adilanchian** [comment]
Hey hokein,

Thank you for the reply! So basically you added an event on item to see if it is done? I guess that will give me a heads up if the webContents.stop() works. Thanks again for your time and I will be testing this out with updates to come.

-Alec

**Comment by adilanchian** [comment]
Just implemented this code now. So the webContents.stop() does show the 'cancelled' state which is good but it still holds true for Waiting For Response after trying to run the JS inside the frame. I have been thinking that this implementation is probably not the most efficient but, it would be great to know what I'm doing wrong here. Thanks !

**Comment by hokein** [comment]
@adilanchian Oh, I see your purpose. You should use `did-stop-loading` event:
```
spWindow.webContents.session.on('will-download', function(event, item, webContents) {
  if(item.getMimeType() == 'application/pdf') {
    console.log("Is Loading? : "+webContents.isLoading());
    event.preventDefault();
    console.log("Waiting For Response? : "+webContents.isWaitingForResponse());
    console.log(item.getUrl());
    webContents.stop();
    webContents.on('did-stop-loading', function() {
      console.log(webContents.isWaitingForResponse()); // should be false
      var jsToRun = "$('iframe').attr('src', 'url_from_server');";
      console.log("Injecting : "+jsToRun);
      spWindow.webContents.executeJavaScript(jsToRun);
      console.log("Waiting For Response? : "+webContents.isWaitingForResponse());
    });
  }
});
```

**Comment by adilanchian** [comment]
@hokein @zcbenz

My issue was solved through @hokein example. Sorry about not updating sooner. Thank you for all your help!
