### ISSUE TITLE
OS X 'Smart Zoom' is enabled on OS X

### ISSUE THREAD

**Issue by ashgti** [atom/electron#3143]
This might be intentional, but I just noticed that 'Smart Zoom' on OS X is enabled. I haven't seen anywhere that says this should be supported. I'm mostly filing this because I couldn't find confirmation one way or another that this should work. 

If this is the intended behavior, the please ignore. 

![atom-smart-zoom](https://cloud.githubusercontent.com/assets/22535/10585609/ea25d5fc-764c-11e5-8b66-35fdd7f7e93e.gif)

**Comment by nathansobo** [comment]
No, this isn't intentional. We've disabled pinch to zoom on the latest beta release, and we should disable this as well. Thanks for the report.

**Comment by nathansobo** [comment]
This issue was moved to atom/atom#9216
