### ISSUE TITLE
Badges for app icons in Windows taskbar?

### ISSUE THREAD

**Issue by johnthedebs** [atom/electron#3148]
I'm working on porting an app from NW.js to Electron, and realized badges aren't available on Windows in Electron (which might be a deal-breaker in this case).

Is there some way to implement badges myself (ideally in JS), or is there a plan to add this feature at some point?

Thanks!

**Comment by paulcbetts** [comment]
What do you mean by badges? Maybe https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetoverlayiconoverlay-description-windows-7 is what you want?

**Comment by johnthedebs** [comment]
I mean OS X-style badges, ie a small red ovally overlay with some text in it.

That `setOverlayIcon` method will allow me to do what I'm looking for, thanks for pointing it out!

If there's wider interest I'd love to see a solution similar to NW.js's `setBadgeLabel` method that works across platforms and generates the image on-the-fly for Windows support, but `setOverlayIcon` is enough that I can roll my own.

**Comment by paulcbetts** [comment]
@johnthedebs Interesting, can you show a screenshot as to what that looks like on Windows?

**Comment by johnthedebs** [comment]
Sure, here you go:

![screen shot 2015-10-20 at 1 46 38 pm](https://cloud.githubusercontent.com/assets/97469/10616032/0bd3a7d0-7731-11e5-8f3c-563aa295a9cd.png)

**Comment by paulcbetts** [comment]
Oh yeah, this is just the Overlay Icon, but they draw the overlay for you

**Comment by johnthedebs** [comment]
Here's a solution that may be useful to others: https://gist.github.com/johnthedebs/c22a04fcd08e598e69b8

Closing this issue now, since it's resolved as far as I'm concerned.

**Comment by JSONValidator** [comment]
How can I create canvas in the main process? 
'document is not defined'

**Comment by enlight** [comment]
@JSONValidator You don't, the code posted by @johnthedebs is supposed to run in a renderer process.

**Comment by michaelpeterlee** [comment]
To implement @johnthedebs solution, you must re-require electron.remote in setBadge().

**Comment by michaelpeterlee** [comment]
@JSONValidator use IPC similar to code here: https://github.com/electron/electron/issues/7325

**Comment by viktor-shmigol** [comment]
I've created plugin for it. https://github.com/viktor-shmigol/electron-windows-badge
