### ISSUE TITLE
How to show file content in new window?

### ISSUE THREAD

**Issue by erguotou520** [atom/electron#3154]
I send a message in render process which tell the main process to open a new window and show the file.
```javascript
ipc.send('open.file', file_path)
```
In the main process, the code is like
```javascript
ipc.on('open.file', function (event, file_path) {
  var win = createWindow();
  // win.show();
  win.webContents.send('opened.file', file_path)
})
```
and the html has the listener
```javascript
ipc.on('opened.file', function(data) {
  console.log(1);
})
```
But when I open a file, the code in the listener doesn`t affect and there's no log out. How can I resolve this?

**Comment by erguotou520** [comment]
I change the way to achieve this by using `electron-window`. I pass a arg to the new window. But how can I resolve it using this way?

**Comment by etiktin** [comment]
So you have a window (let's call it win1) and you want it to ask the browser process to create a new window (let's call it win2). Then you want the browser process to notify win2 that it was created (notice you're sending the message to the window you just created). Did you mean to send it to win1 instead?
Did you try sending the message after the window finished loading?

**Comment by zcbenz** [comment]
Closing since this is neither a feature request or bug report.

**Comment by erguotou520** [comment]
@etiktin 
I send the callback in the `did-finish-load` event, it works.
```javascript
win.webContents.on('did-finish-load', function () {
  win.webContents.send('opened.file', args);
})
```

@zcbenz
Sorry for that. I should go to the [Discuss](https://discuss.atom.io/c/electron)
