### ISSUE TITLE
Provide zoom methods for <webview>

### ISSUE THREAD

**Issue by PalmerAL** [atom/electron#3161]
Electron 0.34.0, OS X 10.11.0.

webview.zoomIn(), webview.zoomOut() and webview.resetZoom() should exist.

From #940, it appeared that these were implemented, but they don't actually work.

**Comment by zcbenz** [comment]
The zoom methods are available in [web-frame](http://electron.atom.io/docs/v0.33.0/api/web-frame/#webframe) module.

**Comment by PalmerAL** [comment]
That doesn't solve my issue. I want to zoom the contents of the ``<webview>``` only, but not zoom the content outside the webview. web-frame zooms the entire window, including things not in the webview.

**Comment by zcbenz** [comment]
You need to use `web-frame` module in the page inside `<webview>`.

**Comment by PalmerAL** [comment]
Thanks!

**Comment by KevinGrandon** [comment]
@PalmerAL - Did you get this working? I need something similar, but haven't been able to figure out how to implement this.

Having a zoom method on webview would really help.

**Comment by PalmerAL** [comment]
I got this to work using the ```ipc``` module. I added this code inside of the webview's ```preload``` script (http://electron.atom.io/docs/v0.35.0/api/web-view-tag/#preload):

```
var electron = require("electron");
var ipc = electron.ipcRenderer;
var webFrame = electron.webFrame;

var _browser_zoomLevel = 0;
var _browser_maxZoom = 9;
var _browser_minZoom = -8;

ipc.on("zoomIn", function () {
	if (_browser_maxZoom > _browser_zoomLevel) {
		_browser_zoomLevel += 1;
	}
	webFrame.setZoomLevel(_browser_zoomLevel);
});


ipc.on("zoomOut", function () {
	if (_browser_minZoom < _browser_zoomLevel) {
		_browser_zoomLevel -= 1;
	}
	webFrame.setZoomLevel(_browser_zoomLevel);
});


ipc.on("zoomReset", function () {
	_browser_zoomLevel = 0;
	webFrame.setZoomLevel(_browser_zoomLevel);
});

```

Then, I can send IPC messages to the webview:

```
webview.send("zoomIn");
webview.send("zoomOut");
webview.send("zoomReset");
```

**Comment by KevinGrandon** [comment]
Thanks for posting the code, that's really useful!

**Comment by pomegrn8** [comment]
Ditto - thanks!
