### ISSUE TITLE
Tray menu HTML?

### ISSUE THREAD

**Issue by CyrisXD** [atom/electron#3167]
Is https://github.com/atom/electron/issues/752 still the workaround method to have 'Rich" tray menus? 

Or has Electron since been updated with a method, I can't find documentation? 
I've noticed PopKey was built with Electron and has quite a nifty tray menu. 

<img width="385" alt="screen shot 2015-10-21 at 11 18 40 pm" src="https://cloud.githubusercontent.com/assets/3248638/10633865/3777d23e-784a-11e5-8ebf-abcda6df1612.png">

**Comment by zcbenz** [comment]
Yeah I believe it is just showing a transparent window.
