### ISSUE TITLE
Providing a Service for Mac OSX

### ISSUE THREAD

**Issue by bhazzard** [atom/electron#3171]
I was unable to sign up for the Electron forums, so I apologize if this isn't the appropriate venue for a question.

I'm trying to provide a system level context menu item when a user right clicks on a file in Mac OSX Finder that will execute code in my Electron App.

This is usually achieved by providing a "Service". But Apple's documentation https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/SysServices/Articles/providing.html#//apple_ref/doc/uid/20000853-98551, only provides information on how to provide a service by writing Objective-C or Cocoa stuff (a world I'm not familiar with). Apparently it is also possible to implement a service with AppleScript or an Automator workflow.

My question is, has anybody else solved this? Is it currently possible to provide services to Mac OSX from an Electron App?

**Comment by zcbenz** [comment]
Electron didn't provide related APIs, you probably have to write a native Node.js module, or patch Electron achieve that.

**Comment by bhazzard** [comment]
This seems like it would be a fairly common desire, do you think it would be worth a pull request to electron or a separate module library if it is possible to do it in a cross platform way?

**Comment by zcbenz** [comment]
I would accept a pull request to add support for Service if it works fine in Electron, it doesn't have to be cross-platform, we already have lots of platform-dependent APIs.
