### ISSUE TITLE
Requesting a chromium upgrade

### ISSUE THREAD

**Issue by charandas** [atom/electron#3174]
Hi there,

I am using electron for a kiosk app with touch gestures. It's working out great as I have more control of the renderer process than just a browser.

Scrolling seems to break on some divs for me, though. This is nothing new: I am seeing vertical pan-to-scroll break with the stable Chrome too.

A fix has however landed in chromium as of 08/31. Can I request it be upgraded to that commit?

See more info here: https://code.google.com/p/chromium/issues/detail?id=417345

**Comment by zcbenz** [comment]
We usually upgrade Chrome to a new version when it enters stable channel.

**Comment by charandas** [comment]
@zcbenz can I create an electron build locally that uses a chromium unstable commit?

I noticed something to do with S3 credentials in the build config. Those, I don't have but it would be nice for users to be able to build.

**Comment by zcbenz** [comment]
Upgrading Chromium usually involves lots of changes in Electron's code, unless you are familiar with Electron and Chromium's development, I would say it is impossible.
