### ISSUE TITLE
Specify a PAC file URL to session.setProxy(config, callback)

### ISSUE THREAD

**Issue by romaincointepas** [atom/electron#3176]
https://github.com/atom/electron/blob/master/docs/api/session.md#sessionsetproxyconfig-callback
Same as the switch `--proxy-pac-url=http://www.example.com/proxy.pac` but for a session.

I also have some questions regarding the proxy behavior (I couldn't find clear documentation on it).

Question 1: Can this setProxy be used multiple times after the session has "started"?
- Load http://www.google.com with a http://www.example.com/proxy1.pac.
- call session.setProxy and specify a new http://www.example.com/proxy2.pac
- Load http://www.google.com, this time it should use http://www.example.com/proxy2.pac

Question 2: Could a proxy (config or PAC URL) be specified for a webview and not the entire Browser window?

**Comment by deepak1556** [comment]
> Question 1: Can this setProxy be used multiple times after the session has "started"?

Yes, calling `setproxy` will reset the proxy service with the config provided.

> Question 2: Could a proxy (config or PAC URL) be specified for a webview and not the entire Browser window?

Yes, you can use the partition attribute of `webview` to isolate its request context from the browser window and use `setProxy` as usual.

**Comment by romaincointepas** [comment]
Ok, thanks for the quick answers! Looking forward to the PAC URL support then.

**Comment by romaincointepas** [comment]
@deepak1556 I apologize for commenting on a closed issue but that seems like a follow up.

How would you exactly use setProxy on a webview (I'm trying to use setProxy from the page embedding the webview)? I can't seem to get the session object for that webview from outside (<webview>.session is undefined).
PS: that webview has a persistent partition.

**Comment by deepak1556** [comment]
You can use `require('remote').getCurrentWebContents().session` in your `webview` page.

**Comment by romaincointepas** [comment]
Ok, that's what I thought. Any plan for adding access to the webview webContents from outside that webview?

The idea here is that I'm trying to set the proxy before loading a specific URL into the webview (I'm loading a remote website that needs to be proxied). I'm not sure how to achieve that (as preload will still be executed after the webview URL has been fetched).

Right now the only solution would be to load a dummy blank page, the script in `preload` would execute and change the proxy settings, then I would load the real URL.

Do you see a better way to achieve this?

Thanks!

**Comment by deepak1556** [comment]
hmm expose `webview.setProxy` would be a better option.

/cc @zcbenz

**Comment by zcbenz** [comment]
Having `webview.setProxy` sounds good to me, it is a bit more work though, since currently `setProxy` is a session wide operation.

**Comment by romaincointepas** [comment]
@zcbenz as this issue is closed, should I open a new one specific to the `webview.setProxy` enhancement?

**Comment by myfrndjk** [comment]
@ romaincointepas 
Could you please share the sample code to set proxy dynamically ?.
I have a same use case but dont know how to reset that
