### ISSUE TITLE
window.innerWIdth seems to be reported incorrectly

### ISSUE THREAD

**Issue by Tyriar** [atom/electron#3182]
Discovered in https://github.com/atom/electron/issues/2952

`window.innerWidth` seems to be reporting as 3 pixels short of the actual value.

WIndows 10 with electron v0.34.0

![windows_10](https://cloud.githubusercontent.com/assets/2193314/10680000/dd88e4c0-78d0-11e5-9de8-81153449aab7.png)

Ubuntu 15.04 with electron v0.34.0

![ubuntu_15 04](https://cloud.githubusercontent.com/assets/2193314/10680010/f125d7e0-78d0-11e5-9f43-d4b9cdc226a1.png)

**Comment by zcbenz** [comment]
The 3px is actually taken by the devtools, when you dock the devtools vertically it will reserve 3px of space to use as resizing handle.

You can see it by setting background color to black:
<img width="912" alt="screen shot 2015-10-23 at 10 06 43 am" src="https://cloud.githubusercontent.com/assets/639601/10682885/e99fa256-796d-11e5-9de9-44e35ee49363.png">
