### ISSUE TITLE
Use system spellchecker

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#3189]
From: https://github.com/sindresorhus/caprine/issues/14

-

All native apps on OS X gets spellchecking in text boxes (NSTextView) for free.

I know I could use [webFrame.setSpellCheckProvider](http://electron.atom.io/docs/v0.34.0/api/web-frame/#webframe-setspellcheckprovider-language-autocorrectword-provider), but then I would have to hard-code a language, add boilerplate code, use a node module.

Why can't I just define that I want spellchecking as an option and have it use the system one?

**Comment by paulcbetts** [comment]
Neither Windows 7 or Linux have spellchecking built-in, you have to implement it yourself

**Comment by sindresorhus** [comment]
OS X users are used to having spellchecking in text boxes by default. It would be very non-native not having that. If other OSes doesn't provide it built-in, users won't expect it there either. According to [node-spellchecker](https://github.com/atom/node-spellchecker) there's a spellcheck API in Windows 8.

**Comment by zcbenz** [comment]
The `blink` engine doesn't use `NSTextView`, it just renders everything itself, so there is no way to use the system spellchecker.

**Comment by sindresorhus** [comment]
Ok, but Chrome has spellchecking cross-platform, so why not expose that?

**Comment by bfred-it** [comment]
I'm not too sure, on OSX I can use the system's spellchssecker just fine in Chrome.
<img width="535" alt="OS X Native spellchecker" src="https://cloud.githubusercontent.com/assets/1402241/10709751/ba335a7c-79ee-11e5-8ba8-ffd25beaf7b7.png">

**Comment by paulcbetts** [comment]
@bfred-it Not 100% sure on this, but that is actually using a Google web service as the spellchecker, which is why Chrome has it everywhere

**Comment by sindresorhus** [comment]
@paulcbetts You can disable that in the Chrome settings and it still works.

<img width="306" alt="screen shot 2015-10-25 at 00 05 11" src="https://cloud.githubusercontent.com/assets/170270/10711645/167f0296-7aac-11e5-9a16-4cda7257161d.png">

**Comment by bfred-it** [comment]
@paulcbetts no that's the system's UI 

<img width="446" alt="OS X Spellchecker in TextEdit" src="https://cloud.githubusercontent.com/assets/1402241/10714870/c46fd4b8-7abe-11e5-9b3f-cb1c27704498.png">

**Comment by zcbenz** [comment]
Chrome just uses OS X's spelling check API (or hunspell on other platforms) and then shows a custom context menu, you can implement the exact same thing with `menu` and `node-spellchecker` modules.

The "spelling and grammar" dialog, is also a system dialog, but we don't have a way to show it in Electron app yet, I have split the problem in following issues:
* https://github.com/atom/electron/issues/3211
* https://github.com/atom/electron/issues/3210

Chrome has worked hard to make things feel native, we can expose everything in Electron, but it needs some no-easy work.

**Comment by ylluminate** [comment]
This is a pretty important feature. Is it just too hard to implement for anyone / everyone right now?

**Comment by Mte90** [comment]
Any hope? this feature is blocking to many appliations based on electron

**Comment by davidmoore-io** [comment]
+1 on Mte90's comment. It's expected behaviour in OS X apps, and I know a whole load of electron apps (Rambox etc) are keen for this to work.

**Comment by kopurando** [comment]
moreover, native OSX apps can enable autocorrect, which works pretty well these days. Whatever based on Chrome, however, only spell checks. In fast-typing scenarios it is useless sometimes. And almost everything is in Chrome these days. Electron just intensifies the situation.
This issue has been travelling around bug trackers for 4-5 years now, and still no solution? This sounds so backwards in 2017. Even dumbphones are way ahead of desktops on this matter!

**Comment by sferoze** [comment]
@kopurando I know, all I want is spellcheck to work in my electron app, and every few weeks I come back to this issue to see if I can get it to work and nothing... Most solutions are too complicated or too buggy to implement. 

I wish there was just a boolean or something to set in electron to use native spellcheck... 

Ahh... any luck on your side?

**Comment by NiklasBr** [comment]
Any news on this?

**Comment by wesleytodd** [comment]
Any update on this?  I am hoping to use Beaker Browser as my primary browser, but the lack of a spell checker is the only blocking feature.  I don't mean to add to the noise, but squeaky wheel something or other....

**Comment by tgy** [comment]
Shouldn't this issue be re-opened? Not having spell checking is extremely annoying indeed.

**Comment by MarshallOfSound** [comment]
This is implemented in Electron 8.

See https://github.com/electron/electron/pull/20692

**Comment by Syed-Umair** [comment]
@MarshallOfSound , I think it would be great if we could have documentation on how use this spellchecker for webviews.
