### ISSUE TITLE
Sails web socket problem ? sails.io.js

### ISSUE THREAD

**Issue by jaumard** [atom/electron#3190]
I'm trying to use Sails.js with Electron, everything is working fine on Chrome or other navigators.
But on Electron I have `Uncaught TypeError: Cannot read property 'get' of undefined`

It come from the web sockets io.socket or io.sails are not defined under electron. 

Is there any known limitation about this ?  All javascript files are loaded correctly. 
Sails use socket.io under the hood under a `sails.io.js`file.

**Comment by jaumard** [comment]
Disabling node integration fix the problem ! 

```
mainWindow = new BrowserWindow({
		width              : 1200,
		height             : 900,
		"node-integration" : false
	});
```

**Comment by HaiderMalik12** [comment]
I also want to use sails js with electron. Could you provide me some boilerplate code for sails and electron integration ?
