### ISSUE TITLE
Linux: require('auto-updater') throws

### ISSUE THREAD

**Issue by bpasero** [atom/electron#3194]
This is a regression from how it worked before, I could require the auto-updater module on Linux and it would not throw. With 0.34.1 I see the following error right from the require call:

Error: auto-udpater is not implemented on this platform

**Comment by paulcbetts** [comment]
Don't do that then

**Comment by bpasero** [comment]
So why was it possible in the first place then if not functional?

**Comment by bpasero** [comment]
Seems a bit harsh to throw from a require call and the previous way was a nice no-op impl. But the workaround is to not require it. I still preferred the way it worked before.

**Comment by bpasero** [comment]
Thanks!
