### ISSUE TITLE
Store a database locally

### ISSUE THREAD

**Issue by sergiuwd** [atom/electron#3195]
Hello! I am developing an app that needs to be run even if there's no internet connection. I am currently getting the data from an online MySQL database. What I want to do is to find a way to store the database locally, so if I restart the app and there's no internet connection, it will run with the last known data. Is there any way I can do it?

**Comment by tevfik6** [comment]
I'm new in this Electron-NodeJS world and I'm not sure it would be best practice to do. The simplest way would be writing to a file as JSON. When you query your sql in MySQL write the results to a file then work on that file.

**Comment by sergiuwd** [comment]
GREAT idea! I tried it and worked like a charm. It's true, it's not that good if you work with lots of data, but I'll only have 100 - 150 entries into the database.

**Comment by etiktin** [comment]
You could use WebSQL to store and query the data locally

**Comment by ali** [comment]
There's a few other solutions to this problem:

* [LocalStorage][]
* [IndexedDB][]
  * [localForage] and [Dexie.js][] are a simple wrappers for IndexedDB.
* [level.js][] and the [LevelUP][] bindings. This is probably heavier than what you're looking for.

I'd probably choose IndexedDB over reading/writing 100+ rows to a JSON file, especially if that data set was going to get larger.


Misc:

* Treehouse has a good article about [creating a todo app with IndexedDB](http://blog.teamtreehouse.com/create-your-own-to-do-app-with-html5-and-indexeddb).
* [Quip solved this problem in their app][quip] by writing data locally to LevelDB, and then syncing LevelDB with their server.
* The [Dive In To HTML5 article on localstorage][dive] is a good resource for learning more about the web storage APIs and localstorage.

[LocalStorage]: https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage
[IndexedDB]: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
[dive]: http://diveintohtml5.info/storage.html
[quip]: https://medium.com/@btaylor/react-with-c-building-the-quip-mac-and-windows-apps-c63155c1531b#.tfuzzps3t
[LevelDB]: https://github.com/google/leveldb
[LevelUP]: https://github.com/Level/levelup
[localForage]: https://mozilla.github.io/localForage/
[Dexie.js]: http://www.dexie.org/
[level.js]: https://github.com/maxogden/level.js

**Comment by Targun** [comment]
Is there a maximum size an IndexedDB database can be with electron?

**Comment by iamtekeste** [comment]
@Targun check this issue for the answer about IndexedDB limit #4550

**Comment by ShivkAgg** [comment]
How can I insert & fetch data from database using electron...?

**Comment by ykadosh** [comment]
If you are looking for a persistent data storage solution, check out [electron-json-storage](https://github.com/jviotti/electron-json-storage)

**Comment by afshinm** [comment]
@ykadosh I have used the https://github.com/jviotti/electron-json-storage and it's not a good solution for production since it doesn't support file locking so if perform several write transaction at the same time, the storage file will break.

I'm going to use IndexedDB.

**Comment by ykadosh** [comment]
@afshinm wow, that's a serious flaw. I wonder why it's doing that since internally it is based on `app.getPath('userData')`.

**Comment by baconface** [comment]
For anyone reading don't forget about [SQLite](https://www.npmjs.com/package/sqlite3). You will need to rebuild it for Electron though. [Here are instructions](http://verysimple.com/2015/05/30/using-node_sqlite3-with-electron/) to get it to build.

**Comment by afshinm** [comment]
I don't really know the reason @ykadosh but this is what happened to me in a real project at work. I would prefer using LocalForage and it seems working well with Electron.

**Comment by zeke** [comment]
Another interesting option: https://github.com/blahah/yunodb

**Comment by afshinm** [comment]
Ok, just switched to LocalForage and works fairly good.

I think the problem with json storage is:

```
Note that it is unsafe to use fs.write multiple times on the same file without waiting for the callback. For this scenario, fs.createWriteStream is strongly recommended.
```
https://nodejs.org/api/fs.html#fs_fs_write_fd_buffer_offset_length_position_callback

and also: 
https://github.com/jviotti/electron-json-storage/blob/master/lib/storage.js#L119

**Comment by zeke** [comment]
`localForage` is such a great project name.

Another thing for persisting a JSON object to disk: https://github.com/sindresorhus/electron-config

**Comment by EmadAdly** [comment]
Also can take a look at this package It's promising.

`https://github.com/pouchdb/pouchdb`

**Comment by b4dnewz** [comment]
this https://github.com/louischatriot/nedb also seems cool and is 100% JavaScript, no binary dependency

**Comment by sergiuwd** [comment]
Hi guys! As you see, this was posted 2 years ago. Since then, I have been working on many cordova/electron projects. The best approaches I have found are NeDB, IndexedDB, SQLite and LocalStorage. Use them wisely!

**Comment by P0oOOOo0YA** [comment]
This a common question, so let me share my view. I vote for `SQLite` all the way it is simply the best option available today. It is fast minimal reliable and there are many ORMs available for it in many languages including javaScript. Being a native module you have to compile it using `electron-builder` and then you can use pack it with your application.

**Comment by harshil-darji** [comment]
> Hi guys! As you see, this was posted 2 years ago. Since then, I have been working on many cordova/electron projects. The best approaches I have found are NeDB, IndexedDB, SQLite and LocalStorage. Use them wisely!

Hello. I was thinking about using [Electron Store](https://github.com/sindresorhus/electron-store) for my application. How is it as an option over other approaches you mentioned?
