### ISSUE TITLE
Loading URL from <webview> tag bulkier than using mainWindow.loadUrl() and jQuery problem

### ISSUE THREAD

**Issue by tevfik6** [atom/electron#3196]
Hello, 

I really liked Electron and I have a really good opportunity to learn NodeJS while building something. 
I'm working on simple projects just to learn. Yesterday I came to a point where I need to read some html elements or delegate some of events on a url loaded in the window. 

The best way I thought, injecting jQuery and implementing with that. It seems like i have three options;

- iframe
- `<webview>` tag
- using loadUrl, loading the url from mainWindow.loadUrl

My App is already using the mainWindow.loadUrl method. Using this way there is no way to inject jQuery and run some jQuery code i guess. I've noticed [webContents.executeJavaScript(code[, userGesture])] (https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsexecutejavascriptcode-usergesture) but with this function i could not inject jQuery even though i disable all security settings in webContets of mainWindow. 

Then I decided to use `<webview>` tag. First thing i notice resizing the window has a huge rendering difference then loading url without webview tag. It worked bulky. I stopped using it.

The only option left is iframe. I was thinking to stay in the node js side rather than going to html side. 
You might say you can also right NodeJS codes in html/javascript side but unfortunately not, the link I'm trying to load requires me to disable nodejs in the window where i load the link. 

So, as a summary; I don't know do we have specific reason not to have it but it would be great to have webContents.injectJSLibrary. 
Or do we have any other way where I can load the jQuery and run jQuery codes on a website i loaded using loadUrl method not with iframe or `<webview>` tag.

Thanks in advance for any comment!

Tev.

**Comment by tevfik6** [comment]
I was digging more, it seems like reading from file works okay.
```js 
var jQueryLib = Fs.readFileSync(__dirname+"/jquery-2.1.4.min.js", 'utf8');
mainWindow.webContents.executeJavaScript(jQueryLib)
```

**Comment by zcbenz** [comment]
Usually the recommended way to inject third party code is to use the `preload` script.

In future you should seek help from [the Community](https://github.com/atom/electron#community), the issues list is for bug reports and feature requests.
