### ISSUE TITLE
OS X sandbox and dialog

### ISSUE THREAD

**Issue by luin** [atom/electron#3197]
Just read the [Mac App Store Submission Guide](https://github.com/atom/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md), and it's awesome to be able to submit an electron app to the Mac App Store.

Since the resources which can be accessed by a sandboxed app are strictly limited, if my app want to access files inside users' home directory, do I just need to use `dialog.showOpenDialog` to ask the users select the files and then read them? If so, if I want to read these file again later (may be the next time the app is started), do I need show the dialog again or just read them directly since I've read them before?

**Comment by herrmannplatz** [comment]
Regarding the sandboxing, I think you need to add the following entitlement key `com.apple.security.files.user-selected.read-only` to your parent.plist. See [Apple Docs](https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html)

**Comment by zcbenz** [comment]
I suggest seeking help from the [Community](https://github.com/atom/electron#community), the issues list is for bug reports and feature requests.

Regarding your question, I think it is more suitable to ask in some generic Apple developer forums.
