### ISSUE TITLE
Window.onfocus not triggering on click on drag element

### ISSUE THREAD

**Issue by gsouf** [atom/electron#3202]
When an element has the following style: 

```css
-webkit-app-region: drag;
```
Then the following wont trigger when we click on the element:

```js
window.onfocus = function(){
};
```

Please note that the following will work:

```js
require('remote').getCurrentWindow().on("focus", function(){
}):
```

**Comment by gsouf** [comment]
After a few additional tests the following wont trigger:

```js
    $(".drag-element").click(function(){
    });
```
but the following will trigger:

```js
    $(".drag-element").hover(function(){
    });
```

**Comment by gsouf** [comment]
Found the issue already repported for click events: https://github.com/atom/electron/issues/1354

But this issue is not about clicking. It's about focusing when we drag

**Comment by zcbenz** [comment]
Unable to reproduce in 0.36.2 anymore.
