### ISSUE TITLE
__dirname points to wrong folder when executed from remote webpage with 'electron .'

### ISSUE THREAD

**Issue by romaincointepas** [atom/electron#3204]
1. `main.js` is loading a remote page `http://www.example.com/page.html` into a `BrowserWindow` with `note-integration: true`.
2. `page.html` loads `/static/myscript.js` (also a remote script).
3. Inside `myscript.js`, I console.log `__dirname`
4. When running my app by doing `electron .` (I use `electron-prebuilt`), __dirname points to `node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib`, which does not contain any of my app files (they are in `app/`).

The remote `page.html` embeds a `<webview>` with a preload script that is NOT remote (same folder as `main.js`, let's call it `preload-script.js`) so I need a way to get the absolute path for `preload-script.js` to provide to `preload` (or get the absolute path of the `app/` folder and append `/preload-script.js`).

Thanks!

**Comment by romaincointepas** [comment]
Ok, closing my own issue and putting this as reference:

From the renderer process (remote webpage), instead of `__dirname`, use [`app.getAppPath()`](http://electron.atom.io/docs/latest/api/app/#app-getapppath).
```coffeescript
remote = require 'remote'
app = remote.require('app')
console.log app.getAppPath()
```

**Comment by thinklinux** [comment]
I think this should be added to the documentation. Is very unclear there. I had exactly the same use case and I lost couple of hours until I finally found that issue. I should add that in order for that code to work I had to execute `electron app-folder/` no `electron main.js`.

**Comment by lingz** [comment]
Can confirm what @thinklinux said, you need to run it on a folder, in which electron will find the `package.json`, or `index.js` file

**Comment by dhill2522** [comment]
I realize this has been closed for a while, but here is a simple update to the solution from @romaincointepas. `app = remote.require('app')` no longer works in Electron 2 (not sure when this changed). Instead `app` is actually a property of `remote` so you can get the path with the following instead:
```js
const { remote } = window.require('electron')
console.log('My path:', remote.app.getAppPath())
```
