### ISSUE TITLE
BrowserWindow app switcher icon is pixelated

### ISSUE THREAD

**Issue by niedzielski** [atom/electron#3206]
### Versions
electron-prebuilt v0.34.0
Linux Mint Cinnamon v17.2 Rafaela (high DPI screen)

### Issue
Setting the icon in BrowserWindow gives a perfect taskbar icon but a pixelated application switcher icon. I've tried using only a high resolution icon but this makes both the taskbar and application switcher icon pixelated.

![2015-10-25-133924_2880x1800_scrot](https://cloud.githubusercontent.com/assets/1071806/10717464/06253fc4-7b1e-11e5-95ae-ad525d4680f3.png)

![2015-10-25-133643_2880x1800_scrot](https://cloud.githubusercontent.com/assets/1071806/10717449/c4e8baf4-7b1d-11e5-8011-c53dc788429f.png)

### Repro
1. Clone the repo, install dependencies, and launch the app. The delta is [minimal](https://github.com/atom/electron-quick-start/compare/master...niedzielski:bug/pixelated-browserwindow-icon).
    ```
git clone https://github.com/niedzielski/electron-quick-start.git -b bug/pixelated-browserwindow-icon;
npm install;
npm start
```
1. Press &lt;alt+tab&gt;.

**Comment by etiktin** [comment]
Did you try adding high resolution images like mentioned [here](https://github.com/atom/electron/blob/master/docs/api/native-image.md#high-resolution-image)?

**Comment by zcbenz** [comment]
You can find the answer in https://github.com/atom/electron/issues/468#issuecomment-48555401.
