### ISSUE TITLE
Update auto-updater docs for windows

### ISSUE THREAD

**Issue by michaelzoidl** [atom/electron#3214]
Since the `auto-updater` function is also [supported](https://github.com/atom/electron/pull/1984) on the windows platform we should update the docs:
https://github.com/atom/electron/blob/master/docs/api/auto-updater.md

**Comment by zcbenz** [comment]
The latest document has already been updated with auto-updater on Windows :)

**Comment by michaelzoidl** [comment]
oh well... -_- forgot to take a look... sorry
