### ISSUE TITLE
Windows: setting save dialog path without extension adds .*.* to file name

### ISSUE THREAD

**Issue by bpasero** [atom/electron#3216]
- electron 0.34.1
- save dialog options are a defaultPath to a file without extension (e.g. c:\Users\bpasero\ticino-playground\makefile1)
- open the dialog
=> windows presents the file with extra .*.* (e.g. makefile1.*.*)

![image](https://cloud.githubusercontent.com/assets/900690/10724998/0e43ee2a-7bc9-11e5-8121-7e0b9c4400e0.png)

**Comment by zcbenz** [comment]
Fixed with #3240.
