### ISSUE TITLE
Get OS window handle ID

### ISSUE THREAD

**Issue by omrilitov** [atom/electron#3219]
There doesn't seem to be a way to get the id provided by the OS for the window. For example, on Windows there is a window hwnd and it can be used on some win api to manipulate the window.
Is there any known way of doing that?

**Comment by zcbenz** [comment]
There is no data type in JavaScript can represent a native handle, we can probably add an API to return a `v8::External` or `node::Buffer` which contains an external pointer to the handle of native window, and then users can receive the handle by writing a native module.

**Comment by omrilitov** [comment]
It looks fair to say GetAcceleratedWidget() in native_window_views.cc returns the window handle on the windows part.
Is there a known equivalent in osx/linux?

**Comment by zcbenz** [comment]
`GetAcceleratedWidget()` also works on Linux. On OS X it should be the `window_` member of `NativeWindowMac`.

**Comment by omrilitov** [comment]
Will start working on a pull request :+1: 
v8 is not my strongest part, from your experience, is there a preference between v8::External and node:buffer?

**Comment by zcbenz** [comment]
node-ffi uses `node::Buffer` to store external pointers, it also used `v8::External` and `v8::Object` in the past, so I guess `node::Buffer` works the best.

**Comment by skreborn** [comment]
Any updates on this? I am actually in the need of this feature. Thanks!

**Comment by omrilitov** [comment]
Unsigend integer would not suffice as explained here https://github.com/atom/electron/pull/3256#issuecomment-152005215.
Stroring the pointer in a buffer is a pattern already being used in the pull request mentioned above.
I actually started working on the pull request which should have been simple, but encountered unexpected problems.
I had some difficulties finding time to keep working on it, but I will soon.
@skreborn You are more then welcome to help with it if you'd like :smile:

**Comment by skreborn** [comment]
@omrilitov Okay, fair point about the inability to guarantee V8's inner workings, so a `Buffer` might just be the better choice. I would love to help out, although right now I have no idea how to do that.

Also, doesn't `GetAcceleratedWidget` work on all platforms? If not, why not? Haven't had the time to check out the code regarding this. The type of value it returns (`AcceleratedWidget`) is defined for most (if not all) supported platforms.

**Comment by omrilitov** [comment]
It does work on all platforms, I actually don't know how to explain the weird behavior.
If you want you can start by looking at the last commit in my fork https://github.com/omrilitov/electron, the basics are there.
Hopefully in the next days I'll find some time to work on it.

**Comment by omrilitov** [comment]
Added in https://github.com/atom/electron/pull/4023
