### ISSUE TITLE
Is it possible to get the size of text, apps and other items on Windows (dpi)?

### ISSUE THREAD

**Issue by lipis** [atom/electron#3220]
I have issues when I'm using the min/max window size when the settings are not set to 100%.. so one solution would be to get that number and adjust the sizes accordingly..
![screen shot 2015-10-26 at 15 44 58](https://cloud.githubusercontent.com/assets/125676/10732092/addc4b74-7bf8-11e5-9dad-bd2155f0cacb.png)

(Or maybe it should be solved in the core Electron somehow)

**Comment by paulcbetts** [comment]
`window.devicePixelRatio * 100`
