### ISSUE TITLE
Controlling DevTools

### ISSUE THREAD

**Issue by francoislaberge** [atom/electron#3221]
Hi,

Is there anyway to configure/set DevTools properties, such as navigating to the console, or setting which device it's emulating. etc.

**Comment by zcbenz** [comment]
You can call the `DevToolsAPI` in the WebContents of devtools to control it:

```js
myWindow.devToolsWebContents.executeJavaScript('DevToolsAPI.showConsole()')
```

However devtools doesn't provide an API for everything and there is no documentation on it, you can probably seek help from the `#chrome-devtools` IRC channel or chromium-dev mailing list.

**Comment by francoislaberge** [comment]
Awesome, thanks. Will check that out.
