### ISSUE TITLE
Seems like page-visibility option on BrowserWindow is broken

### ISSUE THREAD

**Issue by nathansobo** [atom/electron#3225]
In Electron `0.34.0`, it doesn't seem like my `page-visibility` setting is being honored. I'm using it [here](https://github.com/atom/atom/blob/6495f1a5314320cbc6d9a5936aab24e507e2d21d/src/browser/atom-window.coffee#L34) to ensure test windows continue running tests even if they're in the background. It was working, but now it doesn't seem to be.

**Comment by zcbenz** [comment]
It seems that from Chrome 45 setting `page-visibility` doesn't prevent performance throttling any more, can you try using the `--disable-renderer-backgrounding` command line switch?

```js
app.commandLine.appendSwitch("disable-renderer-backgrounding");
```

Refs #2822.

**Comment by nathansobo** [comment]
Is this something that can be done for just a test window or is it application-wide?

**Comment by zcbenz** [comment]
This flag is application-wide, you can append it before creating the test window so normal users won't be affected, but the windows created after that will still be affected though.

From the source code the only way to prevent only one window being put into background is to keep playing audio in the page.

**Comment by nathansobo** [comment]
One more question... is it possible to only append a flag for a single window's render process?

**Comment by zcbenz** [comment]
Yeah it is possible for renderer process, but `--disable-renderer-backgrounding` is read in the main process.

Playing audio is not a so bad option though, it can be done by creating an empty audio on the fly.

**Comment by nathansobo** [comment]
:zap: Tried the audio hack. Seems to work. Thanks a ton for that idea!

**Comment by nathansobo** [comment]
I'm still getting timeout failures on CI where animation frames aren't firing. Am I doing the sound thing wrong? I thought it was preventing throttling locally but maybe I was mistaken: https://github.com/atom/atom/pull/9485/files

**Comment by zcbenz** [comment]
It seems that Chrome had [a bug](https://code.google.com/p/chromium/issues/detail?id=491895) that it doesn't update the background information immediately when audio starts/stops, and it got fixed very recently, I think we are hitting this bug. The `--disable-renderer-backgrounding` switch seems to be our only option.

**Comment by nathansobo** [comment]
I'm actually seeing that it's working locally. Running audio as I did in the above PR causes tests to complete in the background locally. I am seeing 20 second animation frames on CI regardless of the throtlling settings, either with the flag or the audio hack. For now I just increased the timeout, but it would be nice to know why these frames are taking so long.

**Comment by nathansobo** [comment]
@zcbenz Can you reference me to the relevant location in the Chromium source so I can open an issue on the Chromium bug tracker. After talking to some developers at the Chrome Dev Summit it seems like this is something they care about correcting.

**Comment by zcbenz** [comment]
The code that determines whether to lower the priority of renderer process is located at: https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/renderer_host/render_process_host_impl.cc&sq=package:chromium&type=cs&l=2369

And the `page-visibility` option is implemented at:
https://github.com/atom/electron/blob/master/atom/renderer/atom_renderer_client.cc#L207-L218

I'm not sure from when it stops working in Chromium.

**Comment by zenorocha** [comment]
Thanks for sharing your solution @zcbenz!
