### ISSUE TITLE
BrowserWindow fullscreen and show

### ISSUE THREAD

**Issue by EladBezalel** [atom/electron#3228]
Electron 0.34.1
Windows 10

When creating a new window with parameters `show: false` and `fullscreen: true`
the window still showing

``` js
var window = new BrowserWindow({
  show: false,
  fullscreen: true
});
```

**Comment by zcbenz** [comment]
The `fullscreen: true` property means showing the window in fullscreen state, which conflicts with the `show: false`. I don't think there is a correct behavior when two conflicting properties are used together.

**Comment by EladBezalel** [comment]
@zcbenz the initial thought was creating a window that will be in fullscreen mode but i will decide when to show it or not..

**Comment by meetDeveloper** [comment]
@zcbenz I am also same problem, is there any way I can store how I want my window to be, and then when I use window.show(), it should show.
