### ISSUE TITLE
[IPC] Adding and removing listeners from a remote EventEmitter

### ISSUE THREAD

**Issue by ide** [atom/electron#3229]
I'm using the `auto-updater` module, which exports an EventEmitter instance. Because I want to easily display the update status in the UI, I import it with `require('remote').require('auto-updater')` in the renderer process.

The issue I've run into is that the remote module/IPC interface doesn't seem to track the identities of functions passed to it. That is, this code doesn't actually remove the listener:
```js
autoUpdater.on('checking-for-update', listener);
autoUpdater.removeListener('checking-for-update', listener);
```

So presumably the internals of `remote` or the IPC layer should save the listeners as keys of a Map/WeakMap that are mapped to callback IDs. When the same local function is passed to multiple remote method calls, the remote side should know that it's the same function.

**Comment by etiktin** [comment]
I think when you pass objects using remote, they are cloned, so when you try to remove the handler your not actually removing the correct instance (the cloned instance).
As a work around, you can use `autoUpdater.removeAllListeners('checking-for-update')`, but that will work correctly only if the listeners list contains just your handler copy.
