### ISSUE TITLE
Windows: app.addRecentDocument(path) does not work with folders

### ISSUE THREAD

**Issue by bpasero** [atom/electron#3237]
This might be expected, but I wonder if it would be possible to also support folders in the recent documents list. When I right click on the Windows explorer I get a list of folders, so I think it is supported in general.

**Comment by zcbenz** [comment]
I think you have to register your app as handler of folders:
http://electron.atom.io/docs/v0.33.0/tutorial/desktop-environment-integration/#windows-notes
