### ISSUE TITLE
visual studio 2015 support

### ISSUE THREAD

**Issue by alittletina** [atom/electron#3239]
hello!

according to the instructions, you need visual studio 2013 to build electron.

what's blocking us from building with visual studio 2015? i'm writing some code for electron, but they use c++14 features not supported in vs2013.

thank you!

**Comment by zcbenz** [comment]
Currently Chromium is compiled with VS 2013, and we use the same compiler to compile Electron to avoid potential problems.

You can track the progress of moving to VS 2015 at https://code.google.com/p/chromium/issues/detail?id=440500.
