### ISSUE TITLE
Allow browser-window to use express.js middleware

### ISSUE THREAD

**Issue by alexgleason** [atom/electron#3242]
Here's an example of the type of thing I'm wanting:

```javascript
var app = require('app');
var BrowserWindow = require('browser-window');
var serveStatic = require('serve-static');
var mainWindow = null;
app.on('ready', function() {
  mainWindow = new BrowserWindow();

  // The important bit
  mainWindow.use(serveStatic(__dirname + '/public'));
  mainWindow.loadReq('/index.html');


});
```

This would enable developers to do any sort of arbitrary routing or processing on requested files, which is very powerful.

For example, I would like to use [Harp](http://github.com/sintaxi/harp) to avoid having to compile sass/jade/coffeescript as well as avoiding build tools like grunt/gulp. I could have something like this:

**index.jade**:
```jade
doctype html
html(lang="en")
  head
    link(href='app.css', rel='stylesheet')
  body
    h1 Hello world.
```

**app.scss**:
```scss
$mycolor: blue;
body { background-color: $mycolor; }
```

**main.js** (Electron entrypoint):
```js
...
  var harp = require("harp");
  mainWindow.use(harp.mount(__dirname));
  mainWindow.loadReq('/index');
...
```

Harp's middleware would take the `/index` request, process it to render and serve `index.jade` as HTML, then mainWindow would load the resulting HTML inside of the web contents.

Now, I *know* that you could just create an express server inside the Electron app and use `mainWindow.loadUrl('http://localhost:7894/index')`, but I want to avoid opening a port on the user's computer just to do this. I don't even want a server to start, I just want Electron to be able to run requests through some middleware functions.

What do you think?

Thanks!

**Comment by paulcbetts** [comment]
Maybe use https://github.com/electronjs/electron-compile instead?

**Comment by zcbenz** [comment]
There were some discussions on it:
https://github.com/atom/electron/issues?q=is%3Aissue+jade+is%3Aclosed

**Comment by paulcbetts** [comment]
fwiw I would also take a PR to electron-compile to support Jade!

**Comment by alexgleason** [comment]
Thanks for the tip! I was searching with the wrong keywords before.

If anyone finds this thread in the future, there seems to be a way to accomplish what I'm wanting with the [protocol API](http://electron.atom.io/docs/v0.33.0/api/protocol/).

**Comment by baikon** [comment]
@alexgleason, it's been a couple months since this issue was closed but have you found a solution for this? I'm also interested in avoiding opening a port on a user's computer via express. If you've used the protocol API, could you provide an example on how it was accomplished?

**Comment by greggman** [comment]
I'm not sure why you need/want to do this from a browser window. In any case though here's an app that's running express from the browser process and turning it on/off from the browser window. It would be easy to extend to run multiple servers (one for each browser window)

https://github.com/greggman/servez
