### ISSUE TITLE
[OSX] /deep/ combinator is deprecated. 

### ISSUE THREAD

**Issue by Stickymaddness** [atom/electron#3248]
Hi,

I've just started taking a look at Electron, and installed the electron command globally. I followed the quickstart guide, when I run the hello world app the console opens with:

```
/deep/ combinator is deprecated. 
See https://www.chromestatus.com/features/6750456638341120 for more details.
```

The link details html /deep/ being deprecated in chrome 45+, but from what I can tell electron injects the following style when you create a new app:

```
<style type="text/css">html /deep/ * { min-width: 0; min-height: 0; }</style>
```

I've also tried creating a new test app with electron as a development dependency but the same issue occurs.

**Comment by zcbenz** [comment]
Electron shouldn't inject any style into your app, where did you find that style tag?

**Comment by ducky427** [comment]
I can reproduce this issue by calling the `mainWindow.openDevTools()` method inside `app.on('ready'...`. If I comment `openDevTools`, the warning disappears.

**Comment by Stickymaddness** [comment]
It displays in the inspector which opens as soon as I run the app:

<img width="636" alt="screen shot 2015-10-28 at 11 37 23 am" src="https://cloud.githubusercontent.com/assets/6553902/10784772/9b813d92-7d68-11e5-8348-40c3139c175c.png">

My index.html is as per the quickstart guide.

**Comment by Stickymaddness** [comment]
I actually didn't notice that `mainWindow.openDevTools()` is called on startup, and thought it was due to the warning. 

Commenting it out at least hides the error, just a bit disconcerting to see the warning when starting out with a hello world.

**Comment by zcbenz** [comment]
Seems that it is added by devtools:
https://code.google.com/p/chromium/issues/detail?id=500074
https://code.google.com/p/chromium/issues/detail?id=498405

**Comment by Stickymaddness** [comment]
That's a bit ironic. Thanks for the fast response!

**Comment by k5e** [comment]
This is not restricted to OSX. I have seen it today on Windows 10 and on Ubuntu Linux 15.10.
Both time a fresh install of electron (via npm).

**Comment by brenca** [comment]
+1 I've seen this on Windows 10 too.

**Comment by MajorBreakfast** [comment]
+1 This is a nasty bug. I just spent an hour figuring out why polymer's `<paper-item>` is less tall when I set `Polymer.dom = 'shadow'`. Turns out that it has nothing to do with polymer and everything to do with this bug o.O

**Comment by sergiandreplace** [comment]
Repro in Ubuntu 14.04 with Chrome Version 46.0.2490.86

**Comment by sashahilton00** [comment]
+1 to the pile. This bug sucks. It has had me searching my code for ages, only to stumble across this thread, and realise my time has been wasted. Particularly frustrating that it only occurs when devtools is open :angry:

**Comment by zcbenz** [comment]
Unable to reproduce in 0.36.2 anymore, Chrome 47 seems to have fixed the problem.
