### ISSUE TITLE
3rd party pepper plugins are not supported

### ISSUE THREAD

**Issue by AArnott** [atom/electron#3252]
Repro steps:

1. git clone https://github.com/AArnott/PPApiForDotNet
1. cd PPApiForDotNet\src
1. msbuild /p:platform=x86
1. electron electron-quick-start
1. In the trivial electron app you see an "Insert plugin" button. Click it.
1. I see a useless "Couldn't load plugin" error where my plugin should be on the electron rendered surface.

The electron app is straight from [electron-quick-start](https://github.com/atom/electron-quick-start), with the plugin added.
The plugin itself is straight from the [PPAPI C++ sample](https://code.google.com/p/ppapi/source/browse/trunk/examples/stub/stub.cc) that is "This is the simplest possible C++ Pepper plugin that does nothing.". 

![image](https://cloud.githubusercontent.com/assets/3548/10795318/67da3500-7d56-11e5-80c3-fbdf20a776a2.png)

Clues:

1. I see that a [AddPepperPlugins](https://github.com/atom/electron/blob/6d20d37101f6db3579452df2a63d6a257a1f881b/atom/app/atom_content_client.cc#L99) method is defined, but I can't find a single caller of this method. @deepak1556  added this method in https://github.com/atom/electron/pull/1558 and did not add any callers (that I can see).
1. [The prescribed technique](https://github.com/atom/electron/issues/912#issuecomment-116794390) for telling electron about the plugin: `app.commandLine.appendSwitch('register-pepper-plugins', ppapiPath + ';application/x-ppapi-helloworld');` uses the `register-pepper-plugins` switch which [does not appear _anywhere_](https://github.com/atom/electron/search?utf8=%E2%9C%93&q=register-pepper-plugins) in the electron code base.
1. Although @rewiredpictures also [noticed the lack of the support for the switch](https://github.com/atom/electron/issues/912#issuecomment-116762298) mentioned above, @deepak1556 alleged that [he tested and confirmed that support is actually there](https://github.com/atom/electron/issues/912#issuecomment-116794390).

**Comment by deepak1556** [comment]
> I see that a AddPepperPlugins method is defined, but I can't find a single caller of this method. @deepak1556 added this method in #1558 and did not add any callers (that I can see).

Its called by the [content layer](I see that a AddPepperPlugins method is defined, but I can't find a single caller of this method. @deepak1556 added this method in #1558 and did not add any callers (that I can see).) and it is also responsible for handling the switch `register-pepper-plugins`

@AArnott in your application example dont add `file://` prefix to the plugin path.

**Comment by AArnott** [comment]
@deepak1556 I've tried with and without the `file://` scheme. It doesn't work either way.
Your 'content layer' link is broken. can you fix so I can research it?

**Comment by AArnott** [comment]
Well, some time after removing the `file://` scheme, it started working. That can't have been the only issue because I've removed that in the past and it still didn't work, but evidently that was one of the last things to reapply. It works [now](https://github.com/AArnott/PPApiForDotNet/tree/ff509e03605eb3bf536fe8a4a4c03d1ee7bb9526). Thanks.

**Comment by deepak1556** [comment]
heres the link https://code.google.com/p/chromium/codesearch#chromium/src/content/common/pepper_plugin_list.cc&sq=package:chromium&l=144&rcl=1446060510

**Comment by rmsmith** [comment]
Hello!

I am also seeing the same "Couldn't load plugin" message on Windows 7, with Electron 0.35.4, Chrome 45.0.2454.85.  I am able to load the exact same pepper plugin .dll in Chrome Canary (49.0.2587.0) on the same pc so I think that the plugin .dll is okay.  Additionally, I have no troubles loading the plugin in Electron on OSX as a .so.  So, there does appear to be a Windows-specific problem here.

Note that in order to get the plugin loading smoothly in Chrome Canary I had to open `chrome://plugins` while the app was running and check the `Always allowed to run` flag.  I don't know if that has any significance but I thought it was worth mentioning.

Thanks for any help you can provide!  And please let me know if it is better to open a new issue rather than to comment here (I wasn't sure).

**Comment by deepak1556** [comment]
@rmsmith not sure but might be related to plugin policy. Better to open a separate issue, also would it be possible to provide a sample app that can reproduce the issue ? thanks!
