### ISSUE TITLE
Native modules - build instructions for node-gyp on windows.

### ISSUE THREAD

**Issue by bgSosh** [atom/electron#3253]
Looks like the current node-gyp build instructions on [this page](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) only cover linux.  

Is there a working equivalent of the `HOME=~/.electron-gyp` bit for windows?

**Comment by paulcbetts** [comment]
Use `electron-rebuild`, it will handle this all for you

**Comment by bgSosh** [comment]
Thanks, but doesn't that only work with npm modules?  The module I'm trying to build ([greenworks](https://github.com/greenheartgames/greenworks), isn't offered as an npm package, only as source.

**Comment by paulcbetts** [comment]
Wow, weird. Well, if you take that file and copy-paste it into your node_modules folder verbatim, it should still work

**Comment by bgSosh** [comment]
Ok, I'll give it a go. Thanks for your help.

**Comment by bgSosh** [comment]
That didn't seem to work unfortunately.  It seems to have built nslog.node, but ignored greenworks.

**Comment by paulcbetts** [comment]
`npm link` it in maybe? Or just publish it on `npm` under your own name - https://docs.npmjs.com/getting-started/scoped-packages

**Comment by etiktin** [comment]
node-gyp downloads the relevant node (in this case Electron's node) headers to a folder under process.env.HOME (if it doesn't exist, it falls back to process.env.USERPROFILE). So I would expect the code to work even if you skip the set and start the command from the node-gyp part.
If you do want to set a specific home for Electron's headers, call the following command before executing node-gyp:
`set HOME=C:\Dev\.electron-gyp`

**Comment by hokein** [comment]
If you use the native windows terminal, you need to set the `HOME` environment as @etiktin  stated:

```
set HOME=C:\Dev\.electron-gyp 
node-gyp rebuild --target=<0.29.2 or other versions> --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
Or you can use a linux-like terminal like cygwin to run the command.
