### ISSUE TITLE
Get application path using Electron-Boilerplate

### ISSUE THREAD

**Issue by sergiuwd** [atom/electron#3257]
Hi!
I need to find the app's location (like <i>C:/Program Files/App</i>) and set it to a variable. None of the  <i>app.getPath(name)</i>  associated directories won't return that.
I am generating some JSON files within the application and I want them to be located inside the app's folder. Any idea about how I can find it?

NOTE: I am compiling the app using electron-boilerplate.

**Comment by jlord** [comment]
What is `app.getAppPath()` returning then?

**Comment by sergiuwd** [comment]
<i>C:\Program Files (x86)\App\resources\app.asar</i>

**Comment by paulcbetts** [comment]
Give this a go:

```js
import path from 'path';
console.log(path.basename(process.execPath));
```
