### ISSUE TITLE
Add video and audio codecs

### ISSUE THREAD

**Issue by RHNorskov** [atom/electron#3259]
I am looking for a way to playback videos with ac3 audio, and xvid videos.

**Comment by zcbenz** [comment]
You have to do a custom build libchromiumcontent with custom `ffmpeg_branding`, currently we just use the chrome browser's setting since it is well tested. You can find more at https://github.com/atom/electron/issues/1595.

**Comment by RHNorskov** [comment]
Ok, it looks like none of the existing `ffmpeg_branding` brands support ac3, and looking at `vendor\chromium\src\third_party\ffmpeg\build_ffmpeg.py` line 493 it looks like i need to add some parameters to the ffmpeg build

    # Google Chrome & ChromeOS specific configuration.
    configure_flags['Chrome'].extend([
        '--enable-decoder=aac,h264,mp3',
        '--enable-demuxer=aac,mp3,mov',
        '--enable-parser=aac,h264,mpegaudio',
    ])

How is this done? Do I make a patch in `patches\third_party\ffmpeg`? Or am I on the completely wrong track?

**Comment by amilajack** [comment]
What is the modern way of doing this? This issue seems pretty old so I'm sure things have changed.
