### ISSUE TITLE
webview self close tag

### ISSUE THREAD

**Issue by kidwm** [atom/electron#3260]
It seems that:
```html
<webview src="https://www.github.com/" />
<hr />
```
would rendered into this:
```html
<webview src="https://www.github.com/">
<hr />
</webview>
```
So why could not use self close tag with webview?

**Comment by paulcbetts** [comment]
Making webview a void element would require patching Blink, which is Not Worth It

**Comment by zcbenz** [comment]
This is a decision made by Chromium, I suggest discussing this on [Chromium's issues list](https://crbug.com) or the chromium-dev mailing list.
