### ISSUE TITLE
Crash on Windows 2008 SP2

### ISSUE THREAD

**Issue by ex3ndr** [atom/electron#3263]
Unable to find `SetCurrentProcessExplicitAppUserModelID` in `SHELL32.dll` on Windows 2008 SP2. According to docs, this method appears only in Windows 2008 R2

**Comment by paulcbetts** [comment]
Yep, Windows Vista and the Server equivalent are not supported, sorry!

**Comment by ex3ndr** [comment]
I believe that there are very small change related to tray in your code as 0.34 works well.
