### ISSUE TITLE
PowerSaveBlocker not preventing suspend

### ISSUE THREAD

**Issue by zackify** [atom/electron#3264]
```js
var id = powerSaveBlocker.start('prevent-app-suspension')
require('power-monitor').on('suspend', function() {
    ajaxRequest().then(function(response){
    console.log('out due to computer sleep')
    powerSaveBlocker.stop(id)
  })
})
```
I'm blocking power save yet my ajax request still doesn't get through until after the computer resumes. I even checked if the powerSaveBlocker is running and it is.

**Comment by zcbenz** [comment]
`prevent-app-suspension` only prevents your app to be suspended by system when it is running in background, it doesn't make your app run even when the system sleeps.

**Comment by zackify** [comment]
Is there no way to prevent sleep long enough to make an Ajax request?
