### ISSUE TITLE
Select element does not respect font on OS X el capitan

### ISSUE THREAD

**Issue by isidorn** [atom/electron#3267]
Electron starter app.
Add a select element to the index.html :
```
 <select class="select"=""><option value="<BadFont>">&lt;BadFont&gt;</option></select>
```
Add a font to the element, for instance
```
	font-family: "Segoe UI","SFUIText-Light", "HelveticaNeue-Light", sans-serif, "Droid Sans Fallback";
```
Notice that the font **does not get picked up**. Now change the background color of the select element to any color, e.g white. Notice that the font now gets picked up.

I only see this on OS X el capitan.

**Comment by sindresorhus** [comment]
Does it work on Chrome? Sounds like a Chrome issue.

**Comment by isidorn** [comment]
Just checked, and it is a chrome issue.
I submitted https://code.google.com/p/chromium/issues/detail?id=549492

**Comment by zcbenz** [comment]
Thanks for reporting the Chromium issue, I'm closing this then.
