### ISSUE TITLE
node-postgres doesn't work with Electron

### ISSUE THREAD

**Issue by pengux** [atom/electron#3269]
Is there a different in ABI for Electron and Node that prevents using node-postgres? For example, I get the error `net.Stream is not a function` and I suppose it's because Electron doesn't implement that?

**Comment by zcbenz** [comment]
Electron just uses Node, so you should have everything needed to run a node module. I suggest reporting this to node-postgres instead since it is unlikely for any of us to look into source code of node-postgres.

**Comment by pengux** [comment]
For those who find this issue: node-postgres needs to run in the main process for it to work.

**Comment by MRGabriel100** [comment]
how do i configure it ?
