### ISSUE TITLE
Feature Request - WebVR

### ISSUE THREAD

**Issue by justinmchase** [atom/electron#3271]
http://webvr.info/

I believe there are chrome branches with webvr api's in them. It would be really cool if they could be pulled into electron somehow. It would be an incredibly light weight way to make and deliver VR apps.

**Comment by zcbenz** [comment]
Currently we only use the stable versions of Chrome, if you want to try experimental features you have to do a custom build of libchromiumcontent and turn on corresponding build flags yourself.

**Comment by lwansbrough** [comment]
@justinmchase did you end up trying this out?

**Comment by justinmchase** [comment]
@lwansbrough No, but this is still on my radar. I haven't taken the time to figure out how to build electron or get custom libchromiumcontent builds, but if you had some idea how I would be interested in trying still!

**Comment by lwansbrough** [comment]
Cool, I may try to find some time to talk a look at this.

**Comment by lwansbrough** [comment]
Bit of a brain dump here but this is sort of an overview of the process from what I've gathered:

- [Building Electron with a custom `libchromiumcontent`](https://github.com/atom/electron/issues/2023)
- [Chromium with WebVR source branch](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr)
- [libchromiumcontent source](https://github.com/atom/libchromiumcontent)

So with this, I think you'd want to pull down the Chromium source, reference is in the build of libchromiumcontent and then reference your custom libchromiumcontent in your custom build of Electron.

**Comment by paulcbetts** [comment]
@lwansbrough tbh I'd hold on - it's going to be Really Hard to try to fix all the build changes of 3+ versions of Chromium, it's not just a simple "change version, rebuild, tada" process

**Comment by lwansbrough** [comment]
@paulcbetts What if I'm not interested in running the latest Chromium, and just want to work from the VR version that was created a few months ago? I doubt things have changed so significantly that Electron wouldn't work on it? Thoughts?

**Comment by lwansbrough** [comment]
Oh sorry I see what you're saying. Well the VR stuff isn't actually that huge of a change. I could probably merge the VR stuff into the latest version of chrome without too much of a hassle?

**Comment by paulcbetts** [comment]
@lwansbrough You could give it a try I guess! I just wanted to warn you that it might Not Be A Joy

**Comment by lwansbrough** [comment]
Fair, thanks for the heads up! I'll update here if I make any progress.

**Comment by HMUDesign** [comment]
@lwansbrough Are you still pursuing this?

**Comment by lwansbrough** [comment]
@HMUDesign Waiting for the WebVR spec to stabilize.

**Comment by justinmchase** [comment]
I tried it again the other day but had trouble getting electron to build. Problems with python and xcode sdk setup on my machine, someday I'll get it to work!

**Comment by jcarpenter** [comment]
Plan is to land WebVR in Chrome 54, FYI. Paging @toji

**Comment by toji** [comment]
Yes, hoping to land it in 54. In the meantime a lot of the underlying code should actually be in place in M52 (current dev) so it won't be too long before the patch delta shrinks considerably.

**Comment by lwansbrough** [comment]
Great news. What's the ETA on Chrome 54?

**Comment by toji** [comment]
Oct. 18th

**Comment by lwansbrough** [comment]
@toji Cheers, thanks!

**Comment by justinmchase** [comment]
Thanks for the followup! I'm looking forward to trying it out.

**Comment by grigorkh** [comment]
@justinmchase @lwansbrough are you still pursuing this? Do you have any news regarding this issue?

**Comment by jcarpenter** [comment]
Hi folks, just an FYI that we're now targeting Chrome 55 for WebVR API 1.0,
with a stable release date of Dec 6, per
https://www.chromium.org/developers/calendar

**Comment by paulcbetts** [comment]
@jcarpenter What's the release where this is available in experimental (i.e. can be enabled with chrome:flags?)

**Comment by cvan** [comment]
@paulcbetts:

Per @toji's https://webvr.info/get-chrome/ page:

> In order to enable access to the WebVR APIs in these builds you must turn on the "Enable WebVR" flag in about:flags or launch from the command line with --enable-webvr

**Comment by cvan** [comment]
Forgive my ignorance, but I'm curious: is it possible for the Electron team to cherrypick the WebVR changeset (and permit the flag to be enabled) without having to wait for WebVR to hit release channel (Chrome 55, as @jcarpenter mentions [above](https://github.com/electron/electron/issues/3271#issuecomment-242952641)).

From my naïve poking around of Electron and its dependencies, it seems to be an elaborate process to merge and uplift changes from Chromium proper to Electron's Chromium source. Is there any (clever) way to get around that? If not – and I definitely won't expect any precise date – but what do y'all think is roughly the timeframe WebVR (in whichever form, its current experimental form in @toji's Chromium builds or the upcoming stable/upstream builds) will be available to consume from Electron?

**Comment by marklundin** [comment]
It is possible to build electron with a specific version of Chrome, therefore you can target @toji's WebVR build

**Comment by marklundin** [comment]
But it's not.an entirely easy process

**Comment by fmoo** [comment]
Has anyone heard any updates about WebVR support in Chrome/PC?

Last week, Chromium [announced WebVR](https://blog.chromium.org/2016/12/introducing-webvr-api-in-chrome-for.html) will be in Chrome 56 for Android.

That said, there haven't been any new experimental builds of chromium pushed to [webvr.info](https://webvr.info/get-chrome/) since October.  Does anyone know when we might hope to see this available in windows or osx builds?

**Comment by MikeHuntington** [comment]
I'm also interested in any update on this. I'm new to Electron so I'm not totally familiar with the process.

**Comment by jcarpenter** [comment]
The priority for the Google WebVR team is Android at the moment, but we're
keen to implement WebVR API for desktop in 2017 (timelines TBD).

**Comment by etiennepinchon** [comment]
Any updates?

**Comment by fmoo** [comment]
@etiennepinchon - According to my notes, desktop WebVR support made it into Chromium @ v57.  Current stable build of Chrome is 59.  Electron is currently built on Chromium 56

**Comment by xinaesthete** [comment]
@fmoo @etiennepinchon I think you'll find that all the added in v57 was some fairly empty placeholder APIs, nothing to really allow you to do VR work.  We're still stuck with very specific builds for actually doing anything with the hardware etc.

**Comment by etiennepinchon** [comment]
@fmoo @xinaesthete Thank you guys for the updates! Haha I had some hope but those empty placeholders are somehow killing any hope.. 😆 
Hopefully we will get to play with webVR in an official build of chrome before the end of this year!
Firefox is still leading when it comes to webVR 🥇

**Comment by cvan** [comment]
@etiennepinchon Check out https://github.com/mozilla/qbrt, which is maintained by @mykmelez. I think you'd be able to do much of what you want for Hologram with qbrt. Let me know how it goes, and feel free to ping me directly (from [GitHub](https://github.com/cvan) comments, [Twitter](https://twitter.com/cvanw), or [email](mailto:cvan@mozilla.com)).

**Comment by etiennepinchon** [comment]
@cvan I tried to send you a mail but you probably did not receive it :(
Would it work with electron, I am not really sure it would.. ?

**Comment by xinaesthete** [comment]
Canary now supports WebVR. I guess it'll be a little while before it makes it to stable and Electron, but it's progress.

**Comment by amireldor** [comment]
Hey, any updates on this? Is this the place to follow up?

**Comment by stephanedemotte** [comment]
Chrome support webvr in experimental feature, how to activate it ?
```
webPreferences: {
      experimentalFeatures: true
    }
```
don't work :/
