### ISSUE TITLE
Electron[0.34.2] - Crash Reporter at startup crashes BrowserWindow

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#3276]
Hello,

Crash reporter module is not working properly in 0.34.x and have few questions on that.
We have embedded crash reported to start on a browser window. When ever we start app in 0.34.x it crashes instantly. Behavior is fine 0.33.x

Ex: 
```
https://github.com/kamesh-a/electron-samples/tree/master/CrashReporter

```

a. Do we need to start crash reporter on all browser window?
b. Starting crash reporter in main background Daemon JS won't collect all crashed in BrowserWindow?

Testing Environment
Electron :  0.34.1 32bit
OS :  windows 8.1 64 bit

**Comment by zcbenz** [comment]
Hmm I am unable to reproduce with 32bit binary on my machine, can you try building Electron locally and then use Visual Studio or Windbg to debug it?

Also does it crash with 64bit binary? And does v0.33.9 crash for you?

**Comment by kamesh-a** [comment]
sure @zcbenz , I am working on it to set windbg
