### ISSUE TITLE
Sending an object reference from host to a webview script

### ISSUE THREAD

**Issue by eric-naguras** [atom/electron#3277]
I made an app that is using preloaded scripts in a webview.
Something like:
`<webview  preload="./js/somescript.js" src="http://somewebsite" plugins></webview>` 

In the host process I use a Winston logger with some special transports and other options.
I would like to use that same logger instance in the webview script.
My question is: 'How do I send the winston instance to the already running webview script'?

When I use:
`webview.send('message', {type: 'hello', logger: 'hi'});`

the message and containing object gets sent but when I try to send the winston object it fails with 

`webview.send('message', {type: 'hello', logger: winston});`
`Uncaught TypeError: Cannot read property 'name' of undefined`

The winston object exists at the time I send the ipc message.

Is there a solution for this?

I would hate to include winston and all config settings in the webview script because my app has about a dozen webviews with accompanying scripts.

**Comment by zcbenz** [comment]
It is probably a bug if sending the object fails, can you provide an example?

**Comment by eric-naguras** [comment]
Sure I can, But give me some time to prepare it.
I will get back on this tomorrow.
I just thought there might be a better way to do this.

I love Electron, it makes programming fun. :-)

**Comment by eric-naguras** [comment]
@zcbenz here is a link to a repo that reproduces the error.
`git@github.com:eric-naguras/ipcTest.git`
`https://github.com/eric-naguras/ipcTest`

Thank you so much for looking into this.
It will give the error in the host process, not in the webview.

**Comment by zcbenz** [comment]
The `ipc` module sends the objects by serializing them into JSON, so methods of objects are not sent.

**Comment by eric-naguras** [comment]
Ok, Thank you. I'll find another way by sending log messages to the host process.

**Comment by coelhoadler** [comment]
Hello @eric-naguras, did you found any solution to sending an object?

**Comment by eric-naguras** [comment]
@coelhoadler you can send data but not objects with their methods included.

**Comment by coelhoadler** [comment]
Thank you for reply @eric-naguras
