### ISSUE TITLE
robotjs with electron

### ISSUE THREAD

**Issue by slifin** [atom/electron#3286]
I'm trying to use [robotjs](https://github.com/octalmage/robotjs) with electron but keep getting "Module did not self register"

I've installed electron to a dir then installed robotjs with npm install robotjs 

I understand I need new headers or something so I've been following this documentation:
https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

the top command "The Easy Way", doesn't appear to work on windows, it will error with:
'.' is not recognized as an internal or external command

I think the documentation needs updating to make this more obvious, and finally is it possible for windows users to use this easy method?

**Comment by paulcbetts** [comment]
Try:

```
.\node_modules\.bin\electron-rebuild.cmd
```

**Comment by slifin** [comment]
that did the trick, thank you
