### ISSUE TITLE
0.34.1 and 0.34.2 releases on Github but not electron.atom.io

### ISSUE THREAD

**Issue by fasterthanlime** [atom/electron#3289]
0.34.1 and 0.34.2 show up as [Github releases](https://github.com/atom/electron/releases) but not [on the official site](http://electron.atom.io/releases.html) — as a result, we're stuck with 0.34.0 because [grunt-electron](https://github.com/sindresorhus/grunt-electron) cannot download anything newer.

I'm not familiar with your release process, but is it possible a few steps were omitted for the last two? Thanks!

**Comment by fasterthanlime** [comment]
edit: Pretty sure my grunt-electron troubles have nothing to do with releases being listed on electron.atom.io, my bad.

**Comment by jlord** [comment]
@fasterthanlime No worries! Just for brevity's sake we only put the major releases on the website.

**Comment by fasterthanlime** [comment]
Makes sense, thanks for the clarification!

(For the record, grunt-electron downloads the latest electron releases no problem, my problem *did* indeed lie elsewhere)
