### ISSUE TITLE
Sync a folder

### ISSUE THREAD

**Issue by sergiuwd** [atom/electron#3296]
I am uploading some images and storing them inside a directory using a PHP script. Now I'm stuck at a point: I need to find a way to sync the online directory with a local directory, so I can use the images even if the app I'm creating with Electron is offline.
Note: the server that stores the images is a regular online host for my website
Is there any module that can do that? Or... do you have any idea about how I can do it?

**Comment by etiktin** [comment]
If you just want caching in case you're offline, you might want to check out Service Worker:
https://ponyfoo.com/articles/serviceworker-revolution
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

If you still want to be able to download all the files, the simplest hackish way, will probably be to add a php page that dynamicly creates `img` tags for all your images. Then you can use [`webContents.savePage`](https://ponyfoo.com/articles/serviceworker-revolution
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) to save the page and all of it's assets (in this case the images).

**Comment by sergiuwd** [comment]
Hi, @etiktin! Thanks for your answer! I think your idea is better than mine. I was thinking about creating an archive of all existing images each time I upload a new image, then download it and extract it locally when the app syncs.
But I will try your idea, because it seems better to me.
I really need to download the images, because I want to be sure that the app will run ok no matter what will happen.
