### ISSUE TITLE
Calling app.setAppUserModelId breaks app.setUserTasks

### ISSUE THREAD

**Issue by miniak** [atom/electron#3297]
When I call `app.setAppUserModelId` with a custom app identifier, `app.setUserTasks` no longer works at all.

`app.setAppUserModelId` calls the `SetCurrentProcessExplicitAppUserModelID`.
`app.setUserTasks` calls `ICustomDestinationList::SetAppID`, but this value seems to be empty, unless set by this piece of code, which is invoked from `app.setName`:
```
void Browser::SetAppUserModelID(const std::string& name) {
  app_user_model_id_ = base::string16(L"electron.app.");
  app_user_model_id_ += base::UTF8ToUTF16(name);
  SetCurrentProcessExplicitAppUserModelID(app_user_model_id_.c_str());
}
```
I guess that `app_user_model_id_` should be set by `app.setAppUserModelId`

**Comment by zcbenz** [comment]
Good catch, I believe this is the cause of #2573.
