### ISSUE TITLE
Pnacl Support

### ISSUE THREAD

**Issue by francoislaberge** [atom/electron#3300]
Does anyone understand what it would entail to use pnacl and electron? It might be helpful for some high performance front end stuff I'm exploring.

**Comment by zcbenz** [comment]
There is too much work needed to be done to add pnacl support in Electron, and we don't have any plan for it now. You can find some discussions at #835.

**Comment by deepak1556** [comment]
If you are not looking for the security provided by native client , then you can just compile and load them as pepper plugins using `register-pepper-plugins`

**Comment by francoislaberge** [comment]
@zcbenz Thanks for the clean answer.

@deepak1556 Yeah, security and was curious if it would make C/C++ more convenient to use as you don't have to recompile for every change in v8 headers and such

**Comment by paulcbetts** [comment]
@deepak1556 Do Pepper plugins like Flash not run under a sandbox in Electron?

**Comment by deepak1556** [comment]
Nope, we treat them as trusted and are run in separate unsandboxed plugin process.

**Comment by timofonic** [comment]
Would there be some kind of automated way to compile them? I want the mosh client, among other stuff.

I would like Atom become a new and better Emacs. I would even like to use it as a window manager, maybe I'm crazy...

**Comment by minggo** [comment]
> Nope, we treat them as trusted and are run in separate unsandboxed plugin process.

Does it mean we can use fread and frite to access local files directly in pepper plugin?

**Comment by minggo** [comment]
Ok, i succeed to access local file via `<iostream>`. 

@deepak1556 @zcbenz 
I just want to make sure that pepper plugin will not be run in sandbox in future? Because i need to access local file directly.

Thanks.

**Comment by deepak1556** [comment]
@minggo by default pepper plugins loaded from browser commandline run out of process and trusted, if you want them to run in-process you need to force it with flag `ppapi-in-process`

**Comment by minggo** [comment]
@deepak1556 Thanks for explaining.

**Comment by GnorTech** [comment]
@francoislaberge and all: NW.js has NaCl support; you could consider it: http://nwjs.io

**Comment by LukasBombach** [comment]
So am I mistaken or do Pepper Plugins run on NPAPI? Because those are being phased out of Chrome and not supported or will not be supported anymore on Electron right? Basically that means no more native plugins that do any rendering the the front end or am I mistaken?

**Comment by paulcbetts** [comment]
@LukasBombach Pepper plugins are the replacement for NPAPI, and they are supported by Chrome (and aren't being phased out)

**Comment by LukasBombach** [comment]
Ah I see, I confused those with FireBreath Plugins. Who comes up with all these names  😕
