### ISSUE TITLE
a problem about `webContens`

### ISSUE THREAD

**Issue by yibuyisheng** [atom/electron#3301]
Hi, I have met a problem about `webContents`.

In the main process, I write this code to create a custom dialog:

```js
var dlg = new BrowserWindow({width: 400, height: 400});
dlg.webContents.once('readytoreceiveparams', function () {
  console.log('start emit');
  dlg.webContents.emit('params', 'some params');
  console.log('end emit');
});

dlg.loadUrl(...);
```

In the renderer process, the code is:

```js
var webContents = remote. getCurrentWebContents();
webContents.emit('readytoreceiveparams');
webContents.once('params', function (params) {
  console.log(params);
});
```

The main process can receive the `readytoreceiveparams` message, and print `start emit` and `end emit`. But the renderer process can not receive the `params` message.

The environment:

> The version of electron-prebuilt: 0.34.2.
My OS: OS X EI Capitan 10.11.1.

Wait for your help, thanks.

**Comment by yibuyisheng** [comment]
When I change the renderer code to this:

```js
var webContents = remote. getCurrentWebContents();
webContents.once('params', function (params) {
  console.log(params);
});
webContents.emit('readytoreceiveparams');
```

It works. But It is also prove the truth that the message sending between renderer process and main process is synchronous, and it's really strange, isn't it?

**Comment by zcbenz** [comment]
Calling methods of objects returned by `remote` module is synchronous, e.g. the `webContents.emit('readytoreceiveparams'); `. You should use `ipc` module explicitly if you want to send messages asynchronously.
