### ISSUE TITLE
Duplicated icon when pinning to the taskbar

### ISSUE THREAD

**Issue by iiegor** [atom/electron#3303]
I know there is a similar issue (https://github.com/atom/electron/issues/1954) but it is related with Squirrel.Windows and Windows 10. This problem is also on Windows 7 and **Squirrel.Windows** shouldn't be needed for pinning an application.

![img](https://i.gyazo.com/6be848aabc8b098ad8273a0cd267046b.gif)

* ``app.setAppUserModelId('electron.app.AppName')`` doesn't make any difference.
* This is happening when I drag (as in the gif above) the .exe to the taskbar and then I try to run it. If I execute the app first and then pin the running instance, the pinned app will work correctly.

**Comment by zcbenz** [comment]
Are you dragging the actual `exe` file or the shortcut file?

**Comment by iiegor** [comment]
I'm dragging the ``exe`` of my packaged application to the taskbar.

**Comment by iiegor** [comment]
Thanks!
