### ISSUE TITLE
What's the correct format for the icon in Tray on OS X?

### ISSUE THREAD

**Issue by lipis** [atom/electron#3304]
So when I'm using the `16x16.png` I'm getting this result:
<img width="119" alt="screen shot 2015-11-02 at 15 56 52" src="https://cloud.githubusercontent.com/assets/125676/10884856/8d149b12-817a-11e5-9130-bef20719566c.png">

and with `32x32.png` this one..
<img width="134" alt="screen shot 2015-11-02 at 15 57 30" src="https://cloud.githubusercontent.com/assets/125676/10884858/8f0d7650-817a-11e5-8162-cb3a37acc969.png">

Is there any way to make it nice and sharp and use the `x2` version?

**Comment by bmathews** [comment]
https://github.com/atom/electron/blob/master/docs/api/native-image.md#high-resolution-image
