### ISSUE TITLE
Distorted canvas rendering

### ISSUE THREAD

**Issue by snawbel** [atom/electron#3312]
I have an app displaying a mapboxgl canvas on an iMac 27" screen in portrait mode. Looks good i Chrome but in my Electron App the canvas distorts when resizing the window height beyond a certain number of pixels. 

~~I see the same problem with http://alteredqualia.com/three/examples/webgl_terrain_dynamic.html and suspect it exists for other webgl/canvas sites.~~

So, until I can reproduce this with a more general example, it could be an issue with mapboxgl. Still I'm curious as to the different behaviour in Chrome vs Electron.

Screenshot 2880x5120px (converted to PNG8 for file size)
![distorted_canvas_screenshot_png8](https://cloud.githubusercontent.com/assets/554578/10906847/1c894752-8225-11e5-9c4a-40c66df7ab7d.png)

**Comment by zcbenz** [comment]
Can it be related to the version of Chrome? Electron is still using Chrome 45 for now.

**Comment by snawbel** [comment]
Yes, I get the same error on Chrome 45. Thanks for pointing me in the right direction!

So... that begs the question; when do you think Electron will be updated to Chrome 46? :)

**Comment by zcbenz** [comment]
> So... that begs the question; when do you think Electron will be updated to Chrome 46? :)

It is currently blocked by the upgrading of our internal build machines, which is also put aside because the server guys are busy doing another big thing. A safe guess is to wait for another month, by then maybe we will skip Chrome 46 and upgrade to Chrome 47 instead.

**Comment by herrmannplatz** [comment]
Since Chrome 47 is out, whats the plan when to upgrade?

**Comment by zcbenz** [comment]
Fixed by #3714.
