### ISSUE TITLE
Access elements inside webview

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#3315]
I have an application that needs to work on a touch screen (runs on Windows 7) and I have built a custom keyboard using jQuery for the screen.

The keyboard appears when a user clicks an input element. And to access certain elements such as inputs in an iframe I use:
~~~
$('iframe').contents().on('click', 'input, textarea', function(e){ showKeyboard(); });
~~~

Note, I run the src of the iframe through a PHP proxy to get around the security issues with accessing the elements of cross domain iframe.

However when using the webview tag, I can't access dom elements inside the webview...

Is it possible to do this? I can't use the executeJavascript method as I need to listen for when a user clicks an input inside the webview that calls the code in the parent, rather than fire JS code into the frame.

**Comment by zcbenz** [comment]
Currently there is no way to access DOM elements of webview directly, I'm merging this to #2425.

In your case you can probably use `ipc` module to send messages instead.

**Comment by iamdriz** [comment]
@zcbenz How would I use IPC to communicate with a webview that is showing a webpage I don't control? For example the bbc website.

**Comment by zcbenz** [comment]
@iamdriz You can setup IPC in the `preload` script.

**Comment by iamdriz** [comment]
Can you show an example of how I can do this? Append the JS code I would need to the webview guest page. Thanks.

**Comment by iamdriz** [comment]
@zcbenz Can you show an example of how I can do this? Append the JS code I would need to the webview guest page. Thanks.

**Comment by iamdriz** [comment]
@zcbenz What I have tried so far is:

~~~
// preload.js

var ipc = require('ipc');

function live (eventType, elementQuerySelector, cb) {
    document.addEventListener(eventType, function (event) {

        var qs = document.querySelectorAll(elementQuerySelector);

        if (qs) {
            var el = event.target, index = -1;
            while (el && ((index = Array.prototype.indexOf.call(qs, el)) === -1)) {
                el = el.parentElement;
            }

            if (index > -1) {
                cb.call(el, event);
            }
        }
    });
}

live("click", "input[type=text]", function (event) {
	ipc.send('showKeyboard', event);
});
~~~

Then in the page that contains the webview I have:

~~~
ipc.on('showKeyboard', function(event){
	console.log(event);
});
~~~

But it never seems to bubble back up when I click inputs in the bbc website...

**Comment by iamdriz** [comment]
@zcbenz Okay I spent a few hours with this last night and got the preload script to work and fire events back up to the main process via IPC. However when I console log out the event I don't get what I passed back....

For example I get:

![image](https://cloud.githubusercontent.com/assets/801252/10965377/77cb1250-83a4-11e5-8da8-1e10dafadccc.png)

But this is what is inside my preload.js file:
~~~
var ipc = require('ipc');

function live (eventType, elementQuerySelector, cb) {
    document.addEventListener(eventType, function (event) {

        var qs = document.querySelectorAll(elementQuerySelector);

        if (qs) {
            var el = event.target, index = -1;
            while (el && ((index = Array.prototype.indexOf.call(qs, el)) === -1)) {
                el = el.parentElement;
            }

            if (index > -1) {
                cb.call(el, event);
            }
        }
    });
}

live("click", "input[type=text]", function (event) {
    
	ipc.send('showKeyboard', event);
	
});

ipc.send('showKeyboard', 'hello cameron');
~~~

I don't see the data for either ipc send command when I do:
~~~
ipc.on('showKeyboard', function(data){
	console.log(data);
});
~~~

**Comment by iamdriz** [comment]
@zcbenz How feasible is it to get accessible dom elements in webview though? As the IPC route isn't really working for me. My previous code worked fine with iframe, but then I lost all the other niceties of the webview such as the history and loading events and separate process.

**Comment by iamdriz** [comment]
To clarify why the IPC route isn't working for me:

In the preload.js file applied to the webview I have:
~~~
var ipc = require('ipc');
document.addEventListener('click', function(event) {
	   ipc.send('showKeyboard', event);
});
~~~

Then on the main process I have:
~~~
ipc.on('showKeyboard', function(event, arg){
	mainWindow.webContents.send('showKeyboard', arg);
});
~~~

Then in the renderer page that contains the webview I have:
~~~
ipc.on('showKeyboard', function(data){
	console.log(data);
});
~~~

The console.log is:
~~~
Object {}
~~~

So for some reason the object is blank when I get it back from the click event in the webview.

**Comment by iamdriz** [comment]
@zcbenz Any ideas on what the issue is that means that DOM events don't travel back up the IPC from the webview like shown in my example?

**Comment by etiktin** [comment]
The event is probably not cloned properly in ipc. What information from the event object does main.js and the renderer need? Try to take what ever you need from the event and pass just that information in a simple object (stringify it if needed).

**Comment by iamdriz** [comment]
That's the thing though. It doesn't send anything up regarding the event from the Dom. I'm sending it just as is but nothing is returned.

**Comment by etiktin** [comment]
You mean that in the webview itself, when click is fired, the event is an empty object?

**Comment by iamdriz** [comment]
Yeah. So it seems the events in webview are not accessible...

**Comment by iamdriz** [comment]
@etiktin @zcbenz Have you been able to re-create this? Thanks again.

**Comment by MissCuriosity** [comment]
@zcbenz Would you please share a demo about how to communicate with webview in electron?I have already tried a lot of ways,but failed

**Comment by bahmandamia6982** [comment]
![gta_v_icon_v1_by_andonovmarko-d8jgaxi](https://user-images.githubusercontent.com/5371898/36872080-4e7233c8-1db9-11e8-9583-cd01fa09c905.png)
