### ISSUE TITLE
Webview URL incorrect after navigation

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#3316]
If I have a webview like:
~~~
<webview id="foo" src="http://www.bbc.co.uk/"></webview>
~~~
And then click a link inside the webview on the BBC website and say for example visit the sport section so in affect navigating to `http://www.bbc.co.uk/sport` and then run this code:
~~~
var webview = document.getElementById("foo");
var url = webview.getUrl();
~~~

The url is still `http://www.bbc.co.uk/` instead of being: `http://www.bbc.co.uk/sport`

Why doesn't the `getUrl()` method return the current url of the view rather than what was in the src originally? The same issue happens if I call the `goBack` and `goForward` methods, the getUrl still returns the original url instead of the new url that is being displayed.

**Comment by zcbenz** [comment]
I'm unable to reproduce this, which version of Electron are you using?

**Comment by iamdriz** [comment]
@zcbenz Updated to v0.34.2 and seems to be working now. Thanks.
