### ISSUE TITLE
Certificate pinning

### ISSUE THREAD

**Issue by andrewrothman** [atom/electron#3318]
I'd like to be able to carry a communication over a TLS secured connection, but I'd like to be able to verify the certificate myself, or optionally allow the user to mark the certificate as trusted. Is this a possible addition?

I'm using electron prebuilt 0.34.2.

**Comment by zcbenz** [comment]
Currently we don't have an API for that, however if you just need to setup an connection instead of showing a page, you can probably find some Node.js modules.

**Comment by zcbenz** [comment]
I'm merging this to #3330.

**Comment by nkt** [comment]
Hey everyone, we created tiny library, [electron-ssl-pinning](https://github.com/dialogs/electron-ssl-pinning). It helps to prevent MITM in your electron applications.

**Comment by KaKi87** [comment]
Hello @nkt, what happened to this repo ? Thanks

**Comment by pateljoel** [comment]
@nkt Any update here? 

Seems like this is the only library for SSL pinning and I assumed this should be in electron...
