### ISSUE TITLE
Website mentions npm run

### ISSUE THREAD

**Issue by MajorBreakfast** [atom/electron#3320]
http://electron.atom.io/ mentions `npm install && npm run`, but `npm run` is not a thing :) Should be changed to `npm start`.

**Comment by johnmuhl** [comment]
Duplicate of https://github.com/atom/electron-quick-start/issues/5

**Comment by jlord** [comment]
My bad, wrong npm script in my head. Closing here and fixing on the website 👍 Thanks!

**Comment by jlord** [comment]
🔗 https://github.com/atom/electron.atom.io/commit/ca6866da2ff700a07c5735843740d989ca293e10
