### ISSUE TITLE
Pinch zoom stop working in 0.34.2

### ISSUE THREAD

**Issue by tomashanacek** [atom/electron#3321]

**Comment by neilcampbell** [comment]
I just noticed something that may be related to this issue and explain what is happening.

We are disabling the pinch to zoom feature using window.require('web-frame').setZoomLevelLimits(1, 1); from the renderer process, however recently it has stopped working (and pinch to zoom is enabled again).

It appears that window.require (in the renderer process) is no longer available when node-integration is false.

Removing the node-integration config setting fixes it, as the default is true.

Is this an issue or is it correct behaviour for window.require to not be available when node-integration is false?

**Comment by zcbenz** [comment]
> Is this an issue or is it correct behaviour for window.require to not be available when node-integration is false?

It is an expected behavior, you can put your code in `preload` script which always has access to `require`.

For the original issue, I'm not able to reproduce, the easiest way to test whether it is a bug of Electron is to try it in the default app, which works at least on OS X 10.10

**Comment by tomashanacek** [comment]
I'm testing it on OS X El Capitan 10.11.1 (15B42). In version 0.34.1 pinch zoom works. In 0.34.2 not.
see https://www.dropbox.com/s/bt5cj8uev3s7boa/pinch-zoom.mov?dl=0

**Comment by zcbenz** [comment]
0.34.2 is linked with OS X 11.11 SDK, while 0.34.1 is linked with 10.10 SDK, I'm wondering whether it is related to this.

**Comment by neilcampbell** [comment]
Awesome thanks! @zcbenz

**Comment by zcbenz** [comment]
Electron 0.35.3 is now linked with OS X 10.10 SDK.
