### ISSUE TITLE
Getting a "Could not get code signature" error after signing app and verifying

### ISSUE THREAD

**Issue by seanchen1991** [atom/electron#3322]
I followed Marco Pracucci's blog on code signing Electron apps, which can be found [here](http://www.pracucci.com/atom-electron-signing-mac-app.html). After signing my app, I run `codesign --verify -vvvv Application.app` and `spctl -a -vvvv Application.app`. Both output exactly what they're supposed to. 

Then when I run `npm start`, which starts Electron, I get the error. There seems to be nothing wrong with my code signing procedure. Am I starting the app incorrectly?

**Comment by zcbenz** [comment]
I think you need to sign every library included in Electron, an example can be found at http://electron.atom.io/docs/v0.34.0/tutorial/mac-app-store-submission-guide/#sign-your-app.

**Comment by seanchen1991** [comment]
Thanks for the tip. Unfortunately it didn't solve my problem. :( 
I've signed every library included in Electron and am still getting the exact same error.

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/atom/electron#community), you can also search old issues since there were some similar issues and solutions.
