### ISSUE TITLE
not trigger 'maximize' event when click 'maximize' button

### ISSUE THREAD

**Issue by CharellKing** [atom/electron#3325]
I create a 'browser-window'; it not trigger 'maximize' event when I click 'maximize' button; To my surprised, these events('closed', 'minimize' etc) are ok.

this's my test code on max os x:

var main_window = new BrowserWindow({'accept-first-mouse': true, 'min-width': 500, 'min-height': 200, icon: tray_icon_path, 'title-bar-style': 'hidden', 'fullscreen': 'true'});
main_window.loadUrl(`file://${__dirname}/index.html`);

main_window.on('maximize', function() {
    console.log('maximize');
    main_window.maximize();
});

**Comment by zcbenz** [comment]
Which version of OS X are you using? From 10.10 the maximize button is changed to fullscreen button.

**Comment by moscartong** [comment]
OS X no longer has "maximize" window, only fullscreen. I think you should use enter/leave-full-screen event.

**Comment by CharellKing** [comment]
@zcbenz OS X EI Caption 10.11.1

**Comment by CharellKing** [comment]
@moscartong  'enter-full-screen' doesn't works. when i click the maximize button; the window only shakes


    main_window.on('enter-full-screen', function() {
        console.log('enter-full-screen');
    });

**Comment by CharellKing** [comment]
'enter-full-screen' and 'maximize' both does't work

**Comment by moscartong** [comment]
I try the quick start demo with OSX EI Caption 10.11.1:
1. git clone https://github.com/atom/electron-quick-start
2. npm install
3. add the following code to main.js:

```
mainWindow.on('maximize', function() {
    console.log('maximized!');
});
mainWindow.on('unmaximize', function() {
    console.log('unmaximized!');
});
mainWindow.on('enter-full-screen', function() {
    console.log('entered full screen');
});
mainWindow.on('leave-full-screen', function() {
    console.log('leaved full screen');
});
```

then run "npm start" and click the fullscreen button to enter full screen, then leave it, console output:

<img width="800" alt="hello_world__and_electron-quick-start_ _electron_helper_ _npm_term_program_apple_terminal_term_xterm-256color_ _139x43_and_browser_window" src="https://github-cloud.s3.amazonaws.com/assets%2F165961%2F10958096%2Fc94a4942-83a5-11e5-9105-bdef256d3938.png">

So the enter/leave-full-screen event seems work just fine.

**Comment by zcbenz** [comment]
> @moscartong 'enter-full-screen' doesn't works. when i click the maximize button; the window only shakes

If the window shakes then you probably made it unrealizable or disabled fullscreen.

**Comment by moscartong** [comment]
@zcbenz Oh, miss that xD

**Comment by CharellKing** [comment]
I try the quick start demo; when i click the full screen, the window only shacks;
@moscartong  what does it miss???

**Comment by CharellKing** [comment]
how to solve it
