### ISSUE TITLE
Mouse wheel doesn't scroll the window on Mac with external mouse

### ISSUE THREAD

**Issue by frozeman** [atom/electron#3327]
When one connects an external mouse, the content is not scrollable via the mouse wheel.

This works with the touchpad and the mac magic mouse though! Any other standard computer mouse seems to not work.

Deactivating any BrowserWindow option, doesn't seem to make a difference.

System: Macbook Pro OSX 10.11

**Comment by zcbenz** [comment]
What's the version of Electron are you using?

**Comment by frozeman** [comment]
v0.34.0

**Comment by zcbenz** [comment]
I'm unable to reproduce on OS X 10.10, does it only happen for your app, or for all web pages opened in Electron?

**Comment by frozeman** [comment]
Ok with the standard electron app it work. I will investigate whats the difference

**Comment by frozeman** [comment]
Ok i figured it out.
I added this snippet to disable the pinch zoom gesture:
```js
document.addEventListener('mousewheel', function(e) {
    if(e.deltaY % 1 !== 0) {
        e.preventDefault();
    }
});
```

For some reason, it works well with the magic mouse scrolling, but not with standard mouses. I think i have to improve the snippet.

Is there a way to disable the zoom on mac for the window?

**Comment by zcbenz** [comment]
You can use `require('web-frame').setZoomLevelLimits(1, 1)`.

**Comment by frozeman** [comment]
Perfect thanks! This should be an option of the browser window IMO
