### ISSUE TITLE
Possible to validate each certificate via an API

### ISSUE THREAD

**Issue by steelbrain** [atom/electron#3330]
It would be nice to have an API where we can intercept all the certificate validations and approve them manually. I need this for an app of mine and is a blocker.

**Comment by andrewrothman** [comment]
I'm also wondering how to do the same thing. I just stumbled across [forge](https://github.com/digitalbazaar/forge). Maybe it's helpful? I don't have time to take a look at it later but I'll drop it here for now

**Comment by zcbenz** [comment]
Reopening this because of #3469.
