### ISSUE TITLE
Remote debug browser view

### ISSUE THREAD

**Issue by kevinsimper** [atom/electron#3331]
There is a method for remote debug the main process, but there is not information on how to remote debug the browser view.

There is a old issue https://github.com/atom/electron/issues/554 which is closed and it is linking to an old page that gives a 404.

I am trying to remote debug the browser window, because I want to try to use the react-devTools that does not work inside electron #3313

**Comment by etiktin** [comment]
You can remote debug by using the `--remote-debugging-port=8315` command line argument. Then you can access the remote devtools interface on http://localhost:8315 (you can change 8315 to any other port).
That said, you still won't be able to use react-devtools (devtools extensions you install in your local Chrome are not available in remote debug).

**Comment by kevinsimper** [comment]
Hi @etiktin, thanks for your answer

I know there is remote debug for the main process, but how for the browser windows that you start with `new BrowserWindow()`

**Comment by etiktin** [comment]
The `remote-debugging-port` is for debugging renderers and not the main process. Try it out, it works.

**Comment by kevinsimper** [comment]
Yes, I can see it now and I got confused because I could not see the page that i have `.loadUrl`, but I think have found the `iframe` now that i used to show my page.

But what can i do from this remote debug window of useful things? 

I successful deleted the iframe in the remote debugger but nothing happend.

**Comment by etiktin** [comment]
It supports, pretty much anything you could do in normal devtools, so you can add elements, set breakpoints, profile etc. That said, the experience and performance is not as good as the normal devtools, so I suggest using it only when it makes sense. Example scenarios:
- Debugging an Electron app that was packaged for distribution
- Debugging an Electron app running on another machine in your network
- Debugging a devtools extension (see #2835)

**Comment by kevinsimper** [comment]
I just put in a `console.log('test')` in my `index.html` but I don't see it in the remote debug. What am i missing? Just for test I can't either access anything from the file that i called `new BrowserWindow()` in.

**Comment by etiktin** [comment]
I just tested it again with v0.34.2 32 bit on Windows 8.1 64 bit and it works fine for me with both file urls and remote urls.
Every `console.log` call is printed in the remote devtools console tab.

When you go to http://localhost:8315 , you should see a list of all available targets. If you select a specific window, you won't see the code that created it because it happened outside of that renderer scope. To debug that code, you'll need to go and debug the parent target (if it's on the browser side, you'll need to debug it in the manner described in the docs).

If you have the local Electron devtools open as well, close it, since that blocks you from debugging it in remote devtools.

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by octref** [comment]
@kevinsimper I wrote a blog post just on this topic: http://code.matsu.io/1

**Comment by myst729** [comment]
Is there a way to load devtool extension in the remote debug window?

For instance, I'm working on a electron app, in which vue.js is adopted. So I'd like to load vue-devtools in the remote-debug window just like developing vue web apps.

**Comment by trusktr** [comment]
Thanks @etiktin! Your hint allowed me to figure out how to connect [Puppeteer](https://developers.google.com/web/tools/puppeteer/) to my Electron window from within my Electron main process code.

I put the code sample in the forums: [[SOLVED] Control/automate an Electron application with Puppeteer?](https://discuss.atom.io/t/solved-control-automate-an-electron-application-with-puppeteer/64126/8)

**Comment by etiktin** [comment]
@trusktr you're welcome 😀
