### ISSUE TITLE
BrowserWindow.webContents: Improve will-navigate event for HTML5 History API

### ISSUE THREAD

**Issue by KevinMartin** [atom/electron#3334]
Feature Request:

The `will-navigate` event does not trigger on `pushState` or `replaceState` which is a critical feature of many HTML5-based apps.

It would be great to also have `will-navigate` trigger or have a new event to support the History api.

**Comment by zcbenz** [comment]
It is possible to get events when an in-page navigation happens, but there is no way to prevent that, and it would probably require a big patch in Chromium to achieve this.

So I suggest just overriding `pushState` in `preload` script.

**Comment by KevinMartin** [comment]
@zcbenz, my app is using angular, so I just send an IPC message at the moment when navigation occurs. I'm not really interested in preventing navigation though...

I tried `will-navigate`, but it does not trigger it with `pushState`...

**Comment by zcbenz** [comment]
@KevinMartin You can use `navigation-entry-commited` event for now, which is not public yet, the parameters are `(event, url, inPage, replaceEntry)`.
