### ISSUE TITLE
Window resize causes an input field go unresponsive

### ISSUE THREAD

**Issue by isikfsc** [atom/electron#3339]
When I resize the app screen horizontally the input filed does not work, I cannot type with my keyboard.
I can only start being able to input something by typing again if I just hit return. This causes a blank input and a html element with the input field. If there was any sequence of letters I have typed before hitting return the last letter is shown on the preceding line instead of whole other letters. Resizing vertically does the same effect of yielding the only last letter typed from the last sequence of letter typed.

I have tested my program in the Chromium, Chrome, and Safari, all on mac., and all works normally without this issue.

I experience this issue only with electron.
OS X 10.10.4 Yosemite.
electron-v0.34.1-darwin-x64.
electron-v0.34.2-darwin-x64.

[repository](https://github.com/isikfsc/onyx) of the sample game app with all files for the app/ dir of Electron.app

**Comment by samueleaton** [comment]
So it works in chrome and safari but not in electron? Or it works in nothing?

**Comment by isikfsc** [comment]
Sorry for incomplete description above.
I have tried it on the Chromium, Chrome, and Safari, all on mac, and all  works just fine without the above mentioned issue.
The above issue only happens in Electron.

**Comment by samueleaton** [comment]
Which version of OS X and which version of Electron?

**Comment by isikfsc** [comment]
OS X 10.10.4 Yosemite
electron-v0.34.1-darwin-x64
By the way, I can send the entire app by some preferred means to have you better experience what I have just tried to describe.

**Comment by isikfsc** [comment]
I have updated my original comment with a detail about this issue I have forgotten first, and with some of the subsequent comments of mine.

**Comment by zcbenz** [comment]
Can you paste a minimal example in gist or somewhere else?

**Comment by isikfsc** [comment]
I have created an example [repository](https://github.com/isikfsc/onyx.git) with the entire files for the app directory to be put under the Resources dir of an Electron.app.
play.html is the entry point for the game both in browser and in the main electron process to load inside a Browser window. then this rendered html page loads the game scripts with script tags.
index.html is just a website for the game.

**Comment by zcbenz** [comment]
I can reproduce the same bug on Chrome 45, and it has been fixed by Chrome 46. So currently you have to wait until we [upgrade Electron to use Chrome 46](https://github.com/atom/electron/issues/3312#issuecomment-153632338).

**Comment by isikfsc** [comment]
by the way how can I check which version of Electron uses which version of chrome(or chromium?).

**Comment by etiktin** [comment]
You can check it by printing out the value of `process.versions['chrome']` ([docs](https://github.com/atom/electron/blob/cd2f924db8fd7363d191988b77ad6fa0073f9abf/docs/api/process.md)).

**Comment by zcbenz** [comment]
Fixed by #3714.
