### ISSUE TITLE
Trouble with steam-overlay in electron (since v0.32.0)

### ISSUE THREAD

**Issue by bgSosh** [atom/electron#3340]
We're using the [greenworks](https://github.com/greenheartgames/greenworks) module to facilitate interaction with the steam api in our application.  Some steam-api operations cause a steam ui overlay to appear on the screen.   However, there appears to be an issue using it with electron - either A: [win7] the overlay appears, but it is not possible to interact with it via keyboard or mouse (input seems to be directed to the BrowserWindow, behind the overlay), or B: [win8/10] The overlay does not appear at all.

This was apparently working in electron prior to 0.32.0 (and is working in nwjs).  To help trying to figure out what's wrong, does anyone know:
 - What change between v0.31.2 and v0.32.0 might be responsible for the breakage?
 - What differences between nwjs and electron might account for the difference in behaviour?
 - Any other insights?

Thank you for any help.  Here's some info from valve on the overlay, in case it's relevant:

> The game doesn't need to do anything to have the overlay work, it automatically hooks in for any      game launched via Steam. For development, when running your game in a debugger for example, the      overlay is loaded when you call SteamAPI_Init(). You'll need to make sure to call SteamAPI_Init() before      you initialize the OpenGL/D3D device, otherwise it won't be able to hook in. The overlay works with games that use OpenGL, or DirectX 7, 8, 9 or 10. Input has to be win32 or DirectInput. The Steam overlay will not show over software-rasterized games. 

Here's an [open issue on the greenworks repo](https://github.com/greenheartgames/greenworks/issues/50), which relates to this.

[Extra info:  We are using 32bit binaries]

**Comment by zcbenz** [comment]
0.32.0 upgraded Chrome version to 45, which is very likely the reason of the breakage. nw.js 0.12 is still using an quite old Chrome version, I think that's why it still works.

It is really hard to figure out why this is broken or how to fix it since I'm not familiar with Steam API, a good start is probably to investigate the changes between Chrome 44 and 45.

I'm closing this since we don't have resources investigating this and there is no support on it.
