### ISSUE TITLE
Enable inspecting the devtools window

### ISSUE THREAD

**Issue by kmalakoff** [atom/electron#3345]
I used Chrome as my primary development platform so when I switch to Electron, my muscle memory for bringing the Developer Tools to the foreground is `alt+cmd+I` (Mac OSX). 

In Electron, `alt+cmd+I` toggles the Developer Tools instead of bringing them to the foreground which means that I can lose my breakpoint position, debugging information and have to regenerate my test case. This loss of debugging state has happens to me many times everyday and causes wasted effort.

Could `alt+cmd+I` be remapped to match Chrome's foreground functionality instead changing it to toggle in Electron?

**Comment by zcbenz** [comment]
That's weird, `alt+cmd+I` is toggling devtools on my machine, and I can verify from Chrome's source code:
https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/devtools/devtools_window.cc&sq=package:chromium&type=cs&l=427

**Comment by kmalakoff** [comment]
Thank you for the quick response!

I'm not sure if it is a platform-specific thing. Is the code you are referencing to Linux-specific or cross-platform? It looks like there are multiple functions to open the devtools...is the version you found definitely what is called by the menu bar shortcut for Chrome or just an API?

This is what I see on Chrome ("Developer Tools"):

![chrome](https://cloud.githubusercontent.com/assets/756520/10988263/aee73eee-83ef-11e5-9cd9-c455d6bf73af.png)

In Chrome, when I press the shortcut once, it brings up the dev tools, if I press it again, it brings up the dev tools on the dev tools (turtles all the way down!). It uses the currently opened tab / window for choosing what to launch in the dev tools. If it is in the background, it comes to the foreground.

-----------------
This is what I see on Electron ("Toggle Developer Tools"):

![electron](https://cloud.githubusercontent.com/assets/756520/10988264/aee79d08-83ef-11e5-8be6-eb0e2cf8e0e0.png)

In Electron, when I press the shortcut once, it brings up the dev tools, if I press it again, it brings closes the dev tools window and I lose all of my debugging information. If it is in the background, it doesn't bring the window to the foreground and closes it regardless of if it is on top or hidden away.
-----------------

That's why the Chrome version (I'm using) is better since if I can't see the devtools, they appear in the foreground without me having to check if they are already open or not. This is to me a much better solution than me pressing the shortcut, finding out that the window was behind Electron and I just lost my debugging information!

I'e been looking through the source code, but it's my first time to look at this. We need to chase the menu option constant: https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/toolbar/app_menu_model.h&l=56 to see what is called...

**Comment by zcbenz** [comment]
I think I found the difference now, I was using docked devtools while you were using it undocked.

Chrome seems to use different behaviors for undocked devtools.

**Comment by kmalakoff** [comment]
Yeah, I prefer and tend to use an undocked window. That must be it...different API call for docked and undocked cases. 

This change will be much appreciated! Thank you.

**Comment by zcbenz** [comment]
I'm merging this to #2835.
