### ISSUE TITLE
Is it possible to make a multi-window app use less resources?

### ISSUE THREAD

**Issue by magicae** [atom/electron#3351]
Electron uses `BrowserWindow` to create a new window. It means a new render process which taking up ~100MB memory will be created. An application managing multiple windows will take up lots of resources because of this. Any ideas or improvements about it? Thanks!

**Comment by zcbenz** [comment]
No, I'm afraid this is the price you have to pay for using Chromium.

If you really want to save resources for showing simple windows, you can write a native module to create native windows instead.

**Comment by paulcbetts** [comment]
The math isn't completely accurate if you're just looking at Task Manager, because a lot of that memory will be shared between the processes, but @zcbenz is also right that Chromium ain't cheap

**Comment by magicae** [comment]
OK, I see. Thanks!
