### ISSUE TITLE
how do you make a patch to libchromium content

### ISSUE THREAD

**Issue by RHNorskov** [atom/electron#3353]
I want to make some changes chromium src files in libchromiumcontent, how do I make my own patch file?

**Comment by nishanths** [comment]
Perhaps this is what you are looking for? https://github.com/atom/libchromiumcontent

**Comment by hokein** [comment]
We use [atom/libchromiumcontent](https://github.com/atom/libchromiumcontent) to maintain the patch to Chromium. If you need to customize libchromiumcontent, you need to build, and package it on local machine manually. Currently electron doesn't support the custom libchromiumcontent build #3310.

**Comment by RHNorskov** [comment]
Maybe I didnt explain right. I have cloned atom/libchromiumcontent. And I have made some changes to `\vendor\chromium\src\third_party\ffmpeg\chromium\scripts\build_ffmpeg.py` I want to know how I can make a patch file, like there is plenty of in `\patches` already.

**Comment by hokein** [comment]
Use `git diff` to generate the patch file. The practice likes:

```
cd path-to-libchromiumcontent/vendor/chromium/src
git init
git add .
git commit -m "chrome v45"
// modify the src file
// git diff the src file 
```

**Comment by RHNorskov** [comment]
Exactly what I need, thank you very much!
