### ISSUE TITLE
require broken when using custom URL scheme

### ISSUE THREAD

**Issue by miniak** [atom/electron#3361]
I have registered an "app:" URL scheme, which only allows access to files inside of the electron app.
However `require('jquery')` like calls are broken in JavaScript code loaded using the "app:" scheme.

```
const protocol = require('protocol');
const ERR_ACCESS_DENIED = -10;

protocol.interceptFileProtocol('file', function(request, callback) {
    callback(ERR_ACCESS_DENIED);
});

protocol.registerFileProtocol('app', function(request, callback) {
    var parts = url.parse(request.url);
    callback(path.join(__dirname, parts.pathname));
});

aboutDialog = new BrowserWindow(...);
aboutDialog.loadUrl('app:///about-dialog/index.html');
```

Doing this works fine:
```
const protocol = require('protocol');

protocol.interceptFileProtocol('file', function(request, callback) {
    var parts = url.parse(request.url);
    callback(path.join(__dirname, parts.pathname));
});

aboutDialog = new BrowserWindow(...);
aboutDialog.loadUrl('file:///about-dialog/index.html');
```

**Comment by miniak** [comment]
I can see a difference in `Module._load`:
`parent.paths = []` when loaded using "app:"
`parent.paths = ["/about-dialog/node_modules", "node_modules"]` when loaded using "file:"

**Comment by miniak** [comment]
This workaround works:
`require(path.join(app.getAppPath(), 'node_modules/jquery'))`

**Comment by zcbenz** [comment]
This behavior is intended, for more you can see https://github.com/atom/electron/issues/2539#issuecomment-135247877.
