### ISSUE TITLE
Prevent the close of the window

### ISSUE THREAD

**Issue by n457** [atom/electron#3362]
Hi everybody,
I'm using Electron 0.34.3 for Linux x64.

I'm trying to prevent the close of the window.

The fragment of code below doesn't work, the code is executed and the window closes immedialely.
```javascript
  currentWindow.on('close', function (event) {
    event.preventDefault();
    // Some code.
  });
```
The official documentation for [BrowserWindow](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-close) says :
![capture d ecran_2015-11-07_13-36-45](https://cloud.githubusercontent.com/assets/11824581/11015192/bca35732-8554-11e5-9040-7f0dee038d13.png)
So, It's maybe a bug ?

But this fragment of code work, like [the doc says](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-close) :
```javascript
  window.addEventListener('beforeunload', function (event) {
    var answer = confirm('Do you want to quit ?');
    event.returnValue = answer;
  });
```

**Comment by zcbenz** [comment]
Have you put the code in main process? The callback [is called asynchronously](http://electron.atom.io/docs/v0.34.0/api/remote/#passing-callbacks-to-the-main-process) if you do that in renderer process.

**Comment by n457** [comment]
Oh OK I see, I put the code in renderer process. I'm exactly in this case (example from [the link you put](http://electron.atom.io/docs/v0.34.0/api/remote/#passing-callbacks-to-the-main-process)) :
```javascript
var remote = require('remote');
remote.getCurrentWindow().on('close', function() {
  // blabla...
});
```
So it's not a bug. I'll stick with `window.addEventListener('beforeunload')` since it's more convinient for me.
Thank you very much for your help :)
You can close the subject, unless you have something to add :)

**Comment by ThibaultJanBeyer** [comment]
Here is how you can prevent the closing:

after lots of tryals I came up with a solution:

```javascript
// Prevent Closing when work is running
window.onbeforeunload = (e) => {
  var answer = confirm('Do you really want to close the application?');
  e.returnValue = answer;  // this will *prevent* the closing no matter what value is passed
  if(answer) { win.destroy(); }  // this will close the app
};
```

Found in [docs](https://electron.atom.io/docs/api/browser-window/#event-close)

**Comment by nbcnc** [comment]
Here's another way to do it.  

Set a flag indicating whether the window should be closed immediately.

    const delayClose = true;

    window.onbeforeunload = (e) => {
       if (delayClose) {
        callSomeFunctionWithPromises().then(() => {
          delayClose = false;
          // call the window.close event another time, after setting delayClose to 'false'
          window.close();
        });
        // prevents closing the window immediately
        e.returnValue = true;
      } else {
        // 'someundefinedvalue' is literally a variable name I made up that's not defined anywhere
        // returning an undefined variable is all that's necessary to let the window close normally
        e.returnValue = someundefinedvalue; 
      }
    });

**Comment by tsuriga** [comment]
I couldn't get the above one to close the window, but combining the two above yielded success:

```js
window.addEventListener('beforeunload', (e) => {
  callSomeFunctionThatReturnsAPromise()
    .then(() => {
      remote.getCurrentWindow().destroy(); // 'remote' being electron.remote here
    });

  // prevent the window from closing immediately
  e.returnValue = true;
});
```

**Comment by dovk** [comment]
This might be acceptable for some as it worked for me

**Comment by dovk** [comment]
This might not be in keeping with the times but I wanted to nip it in the bud so I added in the renderer:
```
const keys = { "F1": false, "F2": false, "F3": false, "F4": false, "F5": false, "F6": false, "F7": false, "F8": false, "F9": false, "F10": false, "F11": false, "F12": false, "F13": false, "F14": false, "F15": false, "F16": false, "F17": false, "F18": false, "F19": false, "F20": false, "F21": false, "F22": false, "F23": false, "F24": false, "PrintScreen": false, "ScrollLock": false, "Pause": false, "Tab": false, "CapsLock": false, "Shift": false, "Control": false, "Meta": false, "Alt": false, "ContextMenu": false, "ArrowLeft": false, "ArrowRight": false, "ArrowUp": false, "ArrowDown": false, "Enter": false, "Backspace": false, "Clear": false, "NumLock": false, "Insert": false, "Home": false, "PageUp": false, "PageDown": false, "End": false, "Delete": false }
document.addEventListener('keydown', function (event) {
  if (event.defaultPrevented) {
    return
  }
  return checkKey(event)
})
function checkKey(event) { // block keyboard events such as alt-f4 which could close the window
  let key = event.key || event.keyCode;
  let val = parseInt(key, 10);
  if (typeof val == 'number' ||
    keys[key] == false ||
    event.altKey ||
    event.ctrlKey ||
    event.shiftKey ||
    event.metaKey ||
    event.repeat) {
    event.preventDefault()
    return false
  }
}
```
There are some other things I mention [here ](https://github.com/dovk/electron-security-example#electron-security-and-other-issues) that may be useful to someone else
