### ISSUE TITLE
`remote` module drops custom error properties

### ISSUE THREAD

**Issue by lukasbestle** [atom/electron#3364]
**Information about my setup**

- Electron v0.34.2
- OS X

**What I'm trying to do**

I need to transfer an `Error` object from the main process to the renderer process. Actually it's an object that inherits from `Error` (simplified to the important stuff):

```javascript
var util = require('util');

var AppError = function(message) {
  // Set another property
  this.code = 'whatever';
  
  // Initialize the Error
  Error.call(this, this.message);
  
  // Capture stack trace
  if(Error.captureStackTrace) {
    Error.captureStackTrace(this, AppError);
  }
};

util.inherits(AppError, Error);
```

**What I expect to happen**

The `remote` module copies over all properties of the object to the renderer process.

**What actually happens**

Only the `message` property is available in the renderer process. All other properties (including `name`) are discarded. So I'm basically left with a standard JavaScript `Error` again.

**Reason for this bug**

The fix for #3089 was that errors are recreated using `new Error(meta.message)`. This is also the reason why it won't copy over other attributes.

---

Is there anything you can do about that? Thank you in advance.

**Comment by zcbenz** [comment]
Can you try v0.34.3? I believe it was fixed by #3291.

**Comment by lukasbestle** [comment]
Thanks for your reply.

v0.34.3 partly fixed the issue. Custom properties and the stack are copied over (\o/ BTW), but the `name` property isn't.

**Comment by lukasbestle** [comment]
Awesome, thanks!
