### ISSUE TITLE
Undo/redo support?

### ISSUE THREAD

**Issue by christiangenco** [atom/electron#3365]
I notice in [electron/atom/browser/api/lib/menu-item.coffee](https://github.com/atom/electron/blob/master/atom/browser/api/lib/menu-item.coffee) and in other places in the codebase that there are references to the `undo` and `redo` menu items under Edit.

How do I provide a function to be called when these menu items are selected (or the shortcut is pressed)?

**Comment by dkfiresky** [comment]
@christiangenco checkout [menu](http://electron.atom.io/docs/v0.34.0/api/menu/) and [menu-item](http://electron.atom.io/docs/v0.34.0/api/menu-item/) packages.

**Comment by zcbenz** [comment]
Under the hood it is calling `webContents.undo()`.
http://electron.atom.io/docs/v0.34.0/api/web-contents/#webcontents-undo

**Comment by rgbkrk** [comment]
Is there any way to access the event for roles like undo/redo so that we can have a custom undo/redo stack?
