### ISSUE TITLE
How to split a view into pieces

### ISSUE THREAD

**Issue by 14307130040** [atom/electron#3366]
Like the layouts and pieces in Rails, I want a method to reuse the code. Currently the webview tag can only display a whole html page; hence I should always write duplicated html header tags and so on. Sharing on the global javascript objects among them directly (since they may in the same page it's redundant to have another scheme handle the sharing problem) could also save a lot of codes. Or is there any way to customize an html tag so that I can implement what I need.

**Comment by zcbenz** [comment]
Electron doesn't provide this, you have to use a template engine yourself, you can find some discussions at https://github.com/atom/electron/issues?q=is%3Aissue+jade+is%3Aclosed.
