### ISSUE TITLE
Should the application menu be created in render process?

### ISSUE THREAD

**Issue by erguotou520** [atom/electron#3369]
### System info:
```
apm  1.0.5
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.3.2
os OSX
```
2. My app's repository [electron-markdown](https://github.com/erguotou520/electron-markdown)
3. In `master` branch, I create the menu in the render process(/src/menu.js) following the electron guide. It works fine. But when I close all the windows(not click 'Quit') and click `File -> new` again, it gives me the released callback error.
![mydown](https://cloud.githubusercontent.com/assets/7945757/11019578/95ce0648-863a-11e5-8a22-49b3e9c77664.gif)

![image](https://cloud.githubusercontent.com/assets/7945757/11019484/6b242d3c-8635-11e5-807e-857300b235be.png)
In the click handler, I just send a ipc message. How to fix this problem?
4. In `menu-future` branch, I move the `menu.js` to main process. But it don't work. No menu shows. What's going on?

![image](https://cloud.githubusercontent.com/assets/7945757/11019498/dbc8a2fc-8635-11e5-896a-f207911e919f.png)

**Comment by ozsay** [comment]
Each window that you create overrides the application menu (the app has 1 menu). When you close a window, the app keeps a reference to that window because the menu was created there. When another window tries to open a new window, the app looks for the window that created the menu, But it was closed.

the `menu-future` branch works fine for me.

**Comment by erguotou520** [comment]
@ozsay If that is true, how can I fix it(After close all window and click a menuitem)?
And the `menu-future` branch just show me a menu: `Electron->Quit`, nothing more.

![image](https://cloud.githubusercontent.com/assets/7945757/11020546/4358cae2-865d-11e5-99d8-611ca4eaaa34.png)

**Comment by ozsay** [comment]
I think the right approach is to set the application menu in the main process (like in `menu-future` branch).

The menu is fine for me in `menu-future` branch, I can open new windows and display the help, open...

I'm using windows 7 (electron 0.33.9)

**Comment by erguotou520** [comment]
@ozsay I build this in Windows10, the menu is OK, but not OK in Mac. What's going on?

**Comment by ozsay** [comment]
I don't know, I don't have a mac :(
Try to update electron to the last version or wait for a mac user to look into it.

**Comment by erguotou520** [comment]
I have uninstalled `Electron` and reinstall it, update to the last, clean the apm/npm cache, but nothing works...

**Comment by zcbenz** [comment]
When creating the application menu in renderer process, the click handlers of menu items are also in the renderer process, so once you closed the window that created the menu, the click handler is also gone too. You can find more abound this at:
http://electron.atom.io/docs/v0.34.0/api/remote/#passing-callbacks-to-the-main-process
