### ISSUE TITLE
Is there any way to get Electron version ?

### ISSUE THREAD

**Issue by lealife** [atom/electron#3371]
Like app.getElectronVersion() ?

**Comment by zcbenz** [comment]
http://electron.atom.io/docs/v0.34.0/api/process/

**Comment by kirkstrobeck** [comment]
^ http://electron.atom.io/docs/all/#processversionselectron

**Comment by baconface** [comment]
To be fair the old link also indicates `process.versions.electron`.

**Comment by JohannBlake** [comment]
I'm using electron 1.6.11 and the cursor doesn't change to a pointer using css. Was this fixed?
