### ISSUE TITLE
ipc server and client

### ISSUE THREAD

**Issue by wormen** [atom/electron#3381]
tell me how to use the IPC module to transmit data to the server and back again ...

**Comment by zcbenz** [comment]
Please seek help from [the community](https://github.com/atom/electron#community).

**Comment by wormen** [comment]
I read it, as it turned out, I have a problem in the transmission of data, and that if the module is connected without a server, it just does not work, I get an error of this kind

`
Uncaught TypeError: Cannot read property 'on' of undefined
`

`
Uncaught TypeError: Cannot read property 'send' of undefined
`

**Comment by chadcampbell** [comment]
I just updated an Electron app that was running version 0.34.0. Once I updated the app to version 0.36.4, I began experiencing this issue as well.
