### ISSUE TITLE
got error: ipc.send is not a function

### ISSUE THREAD

**Issue by AoDev** [atom/electron#3386]
Hello, 
I am trying to use ipc to forward a globalShortcut event for a media key.
But I get `ipc.send is not a function.`

* OS: OSX Maverick
* Electron: 0.31.1

This code will make it easier to understand:

```js
// MAIN process
var ipc = require('ipc')
var globalShortcut = require('global-shortcut')
...
  globalShortcut.register('MediaPlayPause', function () {
    ipc.send('playPause', 'togglePause')
  })
```

```js
// WINDOW process
var ipc = window.require('ipc')
...
ipc.on('playPause', function () {
  console.log('playPause pressed')
})
```

If I `console.log(ipc)` I get:

```
EventEmitter {
  domain: null,
  _events:
   { ATOM_BROWSER_REQUIRE: [Function],
     ATOM_BROWSER_GLOBAL: [Function],
     ATOM_BROWSER_CURRENT_WINDOW: [Function],
     ATOM_BROWSER_CURRENT_WEB_CONTENTS: [Function],
     ATOM_BROWSER_CONSTRUCTOR: [Function],
     ATOM_BROWSER_FUNCTION_CALL: [Function],
     ATOM_BROWSER_MEMBER_CONSTRUCTOR: [Function],
     ATOM_BROWSER_MEMBER_CALL: [Function],
     ATOM_BROWSER_MEMBER_SET: [Function],
     ATOM_BROWSER_MEMBER_GET: [Function],
     ATOM_BROWSER_DEREFERENCE: [Function],
     ATOM_BROWSER_GUEST_WEB_CONTENTS: [Function],
     ATOM_SHELL_NAVIGATION_CONTROLLER: [Function],
     ATOM_SHELL_SYNC_NAVIGATION_CONTROLLER: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_CREATE_GUEST: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_ATTACH_GUEST: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_DESTROY_GUEST: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_SET_SIZE: [Function],
     ATOM_SHELL_GUEST_VIEW_MANAGER_SET_ALLOW_TRANSPARENCY: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_OPEN: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_CLOSE: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_METHOD: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_POSTMESSAGE: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_OPENER_POSTMESSAGE: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_WEB_CONTENTS_METHOD: [Function],
     ATOM_SHELL_GUEST_WINDOW_MANAGER_GET_GUEST_ID: [Function] },
  _eventsCount: 26,
  _maxListeners: undefined }
```

Not sure what I am doing wrong.

**Comment by AoDev** [comment]
Note: I have tried with current latest electron version: 0.34.3. Same problem.

**Comment by dkfiresky** [comment]
@AoDev

>### [IPC Renderer](http://electron.atom.io/docs/v0.34.0/api/ipc-renderer/)
> Note: If you want to make use of modules in the main process from the renderer process, you might consider using the [remote](http://electron.atom.io/docs/v0.34.0/api/remote/) module.

So this code:

```js
// WINDOW process
var ipc = window.require('ipc')
```

should be replaced with this:

```js
// WINDOW process
var remote = require('remote')
var ipc = remote.require('ipc')
```

**Comment by AoDev** [comment]
@dkfiresky I found a solution. I mistakenly thought that the ipc module could be used to send events from main process to a renderer process. Instead, one must use the `webContents.send` method.

Regarding your code, all examples in the documentation show that `ipc` is required without the remote module.

In the end I had to do this:

```js
// MAIN process
var globalShortcut = require('global-shortcut')
win = new BrowserWindow({ width: 960, height: 600 })
...
  globalShortcut.register('MediaPlayPause', function () {
    win.webContents.send('playPause')
  })
```

```js
// WINDOW process
var ipc = window.require('ipc')
...
ipc.on('playPause', function () {
  console.log('playPause pressed')
})
```

But I still don't understand why "`ipc.send` is not a function".
Thank you for helping.

**Comment by paulcbetts** [comment]
@AoDev Where would it send to?

**Comment by AoDev** [comment]
Like I said, I didn't see that it could not be used to send messages from the main process to the renderer process. Missed this part: "It is also possible to send messages from the main process to the renderer process, see WebContents.send for more information."

I thought the IPC module was some kind of API to an event bus where events can be emitted both by the main process and the renderer process. So to answer your question @paulcbetts , I thought I could emit an event from the main process with `ipc.send` and listen to it from the renderer process with `ipc.on` and wouldn't need another module for that.

There are multiple examples like here http://electron.atom.io/docs/v0.34.0/api/ipc-main-process/
where there is `ipc.send`.

**Comment by justinmchase** [comment]
@AoDev There is exactly 1 main process, and potentially many render processes. When you're in the main process you can't just do `ipc.send` because it can't know which window you want to send to. So instead you must specify which window you want to send your message to by using `win.webContents.send` or in the ipc event handler there is a `event.sender` which you can also send messages back to.

But that's why there is no send on the ipc module in the main process. Arguably it could be:
```
ipc.send = function (w, m, a) {
  w.webContents.send(m, a);
};

ipc.send(browserWindow, 'message', args);
```

But that is somewhat redundant.

**Comment by skhameneh** [comment]
Suggestion: Make invoking ipc.send() from main process throw an informative error.

**Comment by AoDev** [comment]
@justinmchase I thought that it would be a global thing, that any process from any window could subscribe to if needed, so no need to say to who goes the message, but more like "this happened" anyone is welcome to listen and do anything with it.
For example in my app, I am listening to a global keypressed event. The OS is not sending the message to a particular app, it's the app that decides to listen to this event and do something.

**Comment by AoDev** [comment]
@skhameneh Good idea : )

**Comment by justinmchase** [comment]
I think we've almost got a pull request worthy feature here :) how about this (psuedo code):

```
function send(message, args, /*optional*/targetWin) {
  if (!app.isReady) throw new Error('You must wait for the app ready event.');

  var targets;
  if (targetWin) {
    targets = [targetWin];
  } else {
    targets = BrowserWindow.getAllWindows();
  }

  if (!targets || !targets.length) 
    throw new Error('A browser window must be present to send a message from the main process.');

  targets.forEach(function (target) {
    target.webContents.send(message, args);
  });
}

module.exports = {
  ...,
  send: send
};
```

**Comment by paulcbetts** [comment]
I'm not very +1 on this because it's not consistent - in a renderer, `ipc.send` sends to a single place. In the browser, `ipc.send` sends to some renderers (Browser Windows) but not others (WebView tags), and is multicast.

I'm into the `targetWin` property though, and having it just be another way to call `target.webContents.send`

**Comment by AoDev** [comment]
Hi, although it was not my intention to turn this into a feature request, all of you have given interesting ideas.

As a developer (who did not read the docs well enough, hence this issue), I wish I had a simple stream of events that can be used by all windows and the main process. Whether it is ipc or another module, I wish I could simply do:

```js
// listen from windows (renderer) or main process
var mainStream = require('main-stream')
mainStream.on('someEvent', function(event) {
  doSomething(event)
})
```

```js
// emit from windows (renderer) or main process
var payload = 'some data'
var mainStream = require('main-stream')
mainStream.emit('someEvent', payload)
```
I think it's quite simple, especially to synchronise multiple windows if necessary.

Regarding `ipc.send` in the main process, whether it ends up being there (with `targetWin` property) or not, I wish I had at least a descriptive error message like @skhameneh said :)

**Comment by zcbenz** [comment]
On master branch we have renamed the `ipc` module to `ipcRenderer` and `ipcMain`, so hopefully users won't be surprised `ipc.send` is in renderer process but not in main process anymore.

**Comment by HoverBaum** [comment]
This just threw me off big time. Also had the `ipc.send is not a function` error.

So I googled around and found that there was now this `ipcMain` thing. Required that and still the same error. Really confused me because I thought to myself 'well now I am using the thing to send from the main process, hell I am even sure it is the main process'. Only after reading through this did I realize how it works.

I mean it makes perfect sense that the main process catering to many rendering processes need to know which one to send to. But it still seems that there could be a better error message here.

**Comment by samuelcesc** [comment]
Really an issue. Still throws the same error.

Would be really glad if this issue can be fixed.

**Comment by MarshallOfSound** [comment]
I don't see how this is an issue.

You are trying to call a function that doesn't exist, and can't be implemented?

**Comment by meetDeveloper** [comment]
@MarshallOfSound Not having Informative error message was an issue.
