### ISSUE TITLE
--proxy-server switch also affects websocket requests

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#3390]
[From the documentation](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md#--proxy-serveraddressport):
The --proxy-server switch should only affects HTTP and HTTPS requests.

According to my tests, it also affects ws (i.e websocket) and wss (i.e secure websocket) requests.

This should be either fixed or the documentation updated.

**Comment by zcbenz** [comment]
That's because WebSocket protocol is based on HTTP protocol, I'll update the documents.

**Comment by felicienfrancois** [comment]
I suspected it but it may be a useful precision as not all proxy servers handle websocket
