### ISSUE TITLE
Setting the app name

### ISSUE THREAD

**Issue by johnRivs** [atom/electron#3391]
According to the docs, I should also add the `productName` key to the app's `package.json`. At some point during the execution of `./node_modules/.bin/electron main.js`, the following code is executed:
```js
// Override app name and version.
var packagePath = path.resolve(option.file);
var packageJsonPath = path.join(packagePath, 'package.json');
if (fs.existsSync(packageJsonPath)) {
  var packageJson = JSON.parse(fs.readFileSync(packageJsonPath));
  if (packageJson.version)
    app.setVersion(packageJson.version);
  if (packageJson.productName)
    app.setName(packageJson.productName);
  else if (packageJson.name)
    app.setName(packageJson.name);
  app.setPath('userData', path.join(app.getPath('appData'), app.getName()));
  app.setPath('userCache', path.join(app.getPath('cache'), app.getName()));
  app.setAppPath(packagePath);
}

// Run the app.
require('module')._load(packagePath, module, true);
```
Ideally, this is what should be executed: `app.setName(packageJson.productName);`. Unfortunately, it doesn't, because `packageJsonPath` equals `C:\foo\my-app\main.js\package.json` instead of `C:\foo\my-app\package.json`.

I tried using `app.setName()` at the start of `main.js`. I can retrieve the value correctly from the renderer process, but it seems like it doesn't really change it, because `app.getPath(userData)` returns `Electron` as the app name (which is what Electron finds in `.\node_modules\electron-prebuilt\dist\resources\default_app\package.json`).

**Comment by etiktin** [comment]
Are you talking about the window title you see when you hover over your app in the taskbar? If so, then what you're looking for is actually the `title` key passed to the BrowserWindow constructor. You might also want to listen to the `page-title-updated` event to prevent title change.

**Comment by johnRivs** [comment]
I'm talking about the name of the app, the thing Electron looks for in package.json, the productName key. Electron uses the name for the folder in %APPDATA%.

https://github.com/atom/electron/blob/master/docs/api/app.md#appgetname

https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by etiktin** [comment]
Does it work correctly when you package your app for distribution (put your files under resources\app and run electron.exe)?

**Comment by etiktin** [comment]
OK. I got it, you are running it wrong. Instead of `./node_modules/.bin/electron main.js` you should have passed `./node_modules/.bin/electron .`. When you use the default app you should pass it the path to your app folder, not to the main file.

**Comment by johnRivs** [comment]
Ohh, forgot about that. Has to be it. I don't know why I decided to run the command using main.js. Will try later.

Thanks!
