### ISSUE TITLE
webview's `reloadIgnoringCache` doesn't appear to be ignoring cache

### ISSUE THREAD

**Issue by johnthedebs** [atom/electron#3393]
I have a site in a webview which I'm reloading with the `reloadIgnoringCache` method, and after the reload I see a bunch of `304` responses in the webviews devtools. I've tried calling the method on both the webview itself and the host window with the same results.

I could be misunderstanding what the method is supposed to do, but my expectation was that it wouldn't attempt to use the cached response for any requests, like when the `Disable cache` check box is checked in the dev tools window.

I'm using Electron version 0.34.3 on OS X 10.11.1.

**Comment by zcbenz** [comment]
Currently `reloadIgnoringCache` is mapped to `loadUrl` since we need to force restarting renderer process, I'm merging this to #1360.

**Comment by xmsz** [comment]
any update?
