### ISSUE TITLE
Content tracing seems to not work at all

### ISSUE THREAD

**Issue by justinmchase** [atom/electron#3394]
The drop dead simplest thing I could think of and it just gives me the same error no matter what I do:

```
var util = require('util');
var app = require('app');

var contentTracing;

app.on('ready', function () {

	contentTracing = require('content-tracing');
	contentTracing.startRecording('*', contentTracing.DEFAULT_OPTIONS, function () {

		console.log('tracing started.');
		contentTracing.stopRecording(null, function (path) {
			console.log('Tracing Data: ', path);
		})

	})
})
```

The call to `startRecording` is throwing an error:

<img width="420" alt="screen shot 2015-11-10 at 4 12 51 pm" src="https://cloud.githubusercontent.com/assets/10974/11077479/0279539c-87c6-11e5-9cb7-f2cf45756409.png">

**Comment by zcbenz** [comment]
The API of `contentTracing.startRecording` has changed but we forgot to update the example, you can reference the documents of `contentTracing.startRecording` on how to use it.

**Comment by justinmchase** [comment]
Which documents are you referring to? I was looking at the api docs in the wiki here, this was my result.

**Comment by zcbenz** [comment]
You can find detailed documents under the "Methods" section:
http://electron.atom.io/docs/v0.34.0/api/content-tracing/#contenttracing-startrecording-options-callback

**Comment by justinmchase** [comment]
oh I see! I was looking right at that and didn't notice that there was an extra parameter in the example. Thanks I'll try it again.

**Comment by blakef** [comment]
I've updated the example, and it still generates the same error:

```javascript
var util = require('util');
var app = require('app');

var contentTracing;

app.on('ready', function () {

    contentTracing = require('content-tracing');
    var args = {
        categoryFilter: '*',
        traceOptions: 'record-until-full'
    };
    contentTracing.startRecording(args, function () {

        console.log('tracing started.');
        contentTracing.stopRecording(null, function (path) {
            console.log('Tracing Data: ', path);
        });

    });
});
```

Running on `"electron-prebuilt": "^0.34.3"`
