### ISSUE TITLE
Recursive copy of directory with fs-plus fails if directory includes asar file

### ISSUE THREAD

**Issue by raelyard** [atom/electron#3395]
With the patching of fs done by electron, recursively copying a directory (via fs-plus copySync) with a .asar archive in it results in the patched asar-aware fs recognizing the archive as such, and copying to a directory, essentially unpacking it.  The created directory has the name of the file being unpacked (something.asar).  When it then recurses into the contents of the archive and tries to copy them into the newly created directory, the patched openSync implementation tries to create the file in an archive in the destination location - but the destination is a directory, not an asar archive.  It fails with "Error: Invalid package".  The invalid package here is that desitnation copy location is a directory and not a package, but is named such that openSync expects it to be an archive.

I'm not sure what to expect is the right thing for this to do here.

Might be same problem as #2446

**Comment by zcbenz** [comment]
I'm merging this to #2446 since they are the same kind of bug, for now you have to use the workaround in #2035.
