### ISSUE TITLE
Windows: Screen display-metrics-changed event not triggered

### ISSUE THREAD

**Issue by pierrefourgeaud** [atom/electron#3403]
On Windows (haven't tried on other platforms) the event 'display-metrics-changed' is not triggered when I change the resolution of my screen.

electron: 0.34.3
simple laptop, with no external screen.

**Comment by raleksandar** [comment]
This is related to #3075 I believe.

**Comment by pierrefourgeaud** [comment]
Yes and actually I noticed also that not only I don't get the event but the values are not updated if I query the display bounds and workArea...

**Comment by zcbenz** [comment]
I'm merging this to #3075.
