### ISSUE TITLE
win.loadUrl() causes app to come to front

### ISSUE THREAD

**Issue by andre-gois** [atom/electron#3405]
Mac osx (didn't test in other systems).

Calling win.loadUrl() causes electron app to come to front of other apps.
In my use case I followed the example in the Online/Offline Event Detection guide, calling different urls depending on online/offline status.

The problem is every time the status changes this causes the app to come to front.

Can this be prevented?

**Comment by zcbenz** [comment]
Can you provide a full example?

**Comment by andre-gois** [comment]
of course:

on my main js file:
```
ipc.on('online-status-changed', function(event, status) {
        if (status == 'offline') {
            mainWindow.loadUrl('file://' + __dirname + '/html/no-connection.html');
            rebuildMenu(false);
        } else {
            mainWindow.loadUrl('file://' + __dirname + '/html/index.html');
        }
    });
```
and in both index.html and no-connection.html scripts:
```
var alertOnlineStatus = function() {
	ipc.send('online-status-changed', navigator.onLine ? 'online' : 'offline');
};

window.addEventListener('online',  alertOnlineStatus);
window.addEventListener('offline',  alertOnlineStatus);
```

Every time I turn the internet on or off the app jumps to the foreground.

**Comment by zcbenz** [comment]
The problem is very likely in other places, like in the `no-connection.html ` file.

**Comment by andre-gois** [comment]
You are right, thank you and sorry.
