### ISSUE TITLE
Automatic updates for mac?

### ISSUE THREAD

**Issue by Janneman84** [atom/electron#3407]
Would anyone care to explain how to make automatic updates for mac work? All information I can find is some theoretical blabla and some websites pointing at each other for more info. Nowhere any actual begin to end no-skipping-steps explanation with examples can be found (so frustrating). If I'm wrong please let me know.

I know I have to do something with auto-updater and Squirrel.mac, and npm? I did manage to make automatic updates work for Windows though, and I'd like to make it work similarly for mac.

**Comment by zcbenz** [comment]
For a real-world example, you can check how Atom uses it:
https://github.com/atom/atom/blob/master/src/browser/auto-update-manager.coffee

If you still have more questions, I suggest seeking help from [the community](https://github.com/atom/electron#community)
