### ISSUE TITLE
`<webview>` transparency not working

### ISSUE THREAD

**Issue by Triztian** [atom/electron#3408]
I've tried to use webviews that are transparent to no avail. It seems that in theory the transparency is supported (at least by looking at the source code). Here are is what I've tried:

 * webview with the `allowtransparency` attribute, with the loaded contents having `<html style="background-color: transparent">` and `<body style="background-color: transparent">`
 * `<webview style="background-color: transparent" ....>`
 * Using the following css rules: `webview::shadow object { background-color: transparent }`
 * Applied this patch and recompiled: https://gist.github.com/40b04b677a05aeb0f7f7
 * Applying the following patch: https://gist.github.com/Triztian/f59279d9b0172812b938

Before submitting the issue I started a discussion on the discuss page for electron:
https://discuss.atom.io/t/stacked-webview-transparencies/22464/7

Is the webview transparency something that is supported?

**Comment by zcbenz** [comment]
The webview is implemented as a browser plugin, which unfortunately has an opaque background. This issue is currently tracked at #1397, the only solution is to patch the Chromium code and it is a quite hard to find the right place to patch.
