### ISSUE TITLE
electron+ipc (development mode)

### ISSUE THREAD

**Issue by wormen** [atom/electron#3414]
I write an application using the IPC module and observe the following situation ... that when debugging, it is either not working or not to send data

for debugging, I use the following method
It sets global `electron-prebuilt` and to launch applications using the BAT file with the contents `electron %cd%`

but if the application pack, then everything works fine

tell me how to work better with the IPC module in step debugging, to avoid packaging the application every time you change any code

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/atom/electron#community), the issues list is only for bug reports and feature requests.
