### ISSUE TITLE
printtoPDF not a function 

### ISSUE THREAD

**Issue by nicksmetBagaar** [atom/electron#3429]
Hello,

I want to use the printtoPDF function from teh browser window but It always throws an error that the function isn't found.

This is in the main.js -> in my view i trigger an event 'generate-pdf' that should create and store the pdf.

Now the bizar thing is that it works when i run it locally with npm start, but as soon as I build it, it starts to fail.

     ipc.on('generate-pdf', function(event, arg){
          mainWindow.printToPDF({}, function(error, data) {
           fs.writeFile('/Users/nsmet/Desktop/test.pdf', data, function(error,data) {
              if(error){

              }
               mainWindow.webContents.send('pdf-done',error + ' pdf');
           })
       })
    });

Creating the window in ready
    mainWindow = new BrowserWindow({width: 800, height: 600});

    mainWindow.loadUrl('file://' + __dirname + '/../views/index.html');

    //mainWindow.webContents.openDevTools();

    mainWindow.on('closed', function () {
        mainWindow = null;
    });

**Comment by etiktin** [comment]
Can you paste the error message and error stack?
What Electron version and OS are you using?

**Comment by nicksmetBagaar** [comment]
version : v0.29.2

This is the error : 

Uncaught Exception:
TypeError: mainWindow.printToPDF is not a function
    at EventEmitter.<anonymous> (/Users/nsmet/Documents/projects/stc-electron/dist/osx/Siemens Train Configurator-darwin-x64/Siemens Train Configurator.app/Contents/Resources/app/js/main.js:71:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
    at EventEmitter.<anonymous> (/Users/nsmet/Documents/projects/stc-electron/dist/osx/Siemens Train Configurator-darwin-x64/Siemens Train Configurator.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:84:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)

**Comment by etiktin** [comment]
Can you print the typeof of mainWindow?
Does it work if you call it on mainWindow.webContents?

It's an old version of Electron, does it work for you with v0.34.x?

**Comment by nicksmetBagaar** [comment]
Hmm, I double checked and I'm getting 2 electron versions. In the console I'm getting 0.29.2 and if I print it out in my views it is 0.34.3. 

@etiktin I tried both suggestions, neither of them work.

**Comment by nicksmetBagaar** [comment]
Ok, When using the electron-packager the electron version was set to 0.25.3. In that version printtopdf didn't exist. So updating the version to 0.34.3 did the trick. 

"build:osx": "npm run clean:osx && electron-packager ./app \"Some Name\" --out=dist/osx --platform=darwin --arch=x64 --version=0.34.3 --icon=assets/osx/loopline.icns",

**Comment by zcbenz** [comment]
The easiest way to check the version of Electron is `process.versions.electron`.
