### ISSUE TITLE
no way to bypass/modify CSP (Content Security Policy) to allow unsafe-eval

### ISSUE THREAD

**Issue by maxogden** [atom/electron#3430]
E.g. if you load `https://github.com/atom/electron` (which has a restrictive CSP) in a `browser-window` and try to run `eval` it raises the following error:

"Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com"."

I had these settings on my `browser-window`:

```
  "webPreferences":  {
      "webSecurity": false,
      "allowRunningInsecureContent": true,
      "allowDisplayingInsecureContent": true
  }
```

Would be nice if there was a way to either modify the CSP in general or specifically override the `unsafe-eval` directive

**Comment by etiktin** [comment]
FYI according to the docs setting `webSecurity` to false will set `allowRunningInsecureContent` and `allowDisplayingInsecureContent` to true for you.

**Comment by zcbenz** [comment]
You can use `webFrame.registerUrlSchemeAsBypassingCsp`:
http://electron.atom.io/docs/v0.34.0/api/web-frame/#webframe-registerurlschemeasbypassingcsp-scheme

**Comment by mattiasarro** [comment]
@zcbenz Do you happen to know how/where to add this configuration in Atom? I'd like to load some external HTML/JS files in my [Hydrogen](https://github.com/nteract/hydrogen) result box.

**Comment by milos-popovic** [comment]
Hi @zcbenz @mattiasarro 
I have the same use case (adding scripts to Hydrogen results). Have you found any solutions?

**Comment by mattiasarro** [comment]
I haven't. I'd need to go through Atom docs and source code to see how Atom uses Electron, which might take more time than I currently have. I'm wondering if a workaround could be saving the external scripts and loading it locally, which maybe wouldn't trigger the security exception.

Any help (e.g. which source files to look into) would be much appreciated. This could be a really useful feature (e.g. embedding TensorBoard and other interactive visualizations directly into a Hydrogen results box).

**Comment by milos-popovic** [comment]
Hi, I did try to load the scripts from local files, and it worked for loading jQuery by adding a <script> tag, but then I've tried loading rest of the libraries from local using jQuery.getScript, but this failed again. Haven't tried yet to use the basic method (the one I've used to load jQuery) to load everything else.

**Comment by lejafar** [comment]
@mattiasarro @milos-popovic I stumbled upon this issue with the same, any Ideas how to make this work? @lgeiger do you have idea what the best approach would be to bypass the CSP when using external js libraries to produce rich hydrogen output with `display(Javascript("..."))` ?

**Comment by milos-popovic** [comment]
@lejafar unfortunately, I can't help as I quit trying in the end
