### ISSUE TITLE
bad browser window docs

### ISSUE THREAD

**Issue by terrysahaidak** [atom/electron#3431]
Is there any notice that options object's properties of BrowserWindow should looks like `'web-preferences'` instead `webPreferences`?

Example:

This is doesn't work
```js
const win = new BrowserWindow({
    width: 1050,
    height: 550,
    webPreferences: {
      webSecurity: false
    }
}
```

This works perfect
```js
const win = new BrowserWindow({
    width: 1050,
    height: 550,
    'web-preferences': {
      'web-security': false
    }
}
```

I've spend about 2 hour to get it working, because i didn't know i should write `'web-preferences'`.

**Comment by johnmuhl** [comment]
The docs on GitHub track the master branch (which is unreleased). Use http://electron.atom.io/docs/ (or select the appropriate tag on GH) to access documentation for released versions.

**Comment by terrysahaidak** [comment]
Oh, i did not know it and used master branch docs for alwayse.
Thank you for explanation.
