### ISSUE TITLE
Trigger download without window navigation

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#3433]
Is there an easier way to trigger the `will-download` event (say, from a renderer process) than doing a window navigation? We noticed in the [spec](https://github.com/atom/electron/blob/master/spec/api-session-spec.coffee#L94) that that is how the event is tested.

In our scenario, we have a window that is hosting embedded content, and it's the embedded content that requests some resource to be downloaded. We'd like to avoid modifying the links in the embedded content, and we can't navigate the host window.

**Comment by zcbenz** [comment]
You can use `will-navigate` event to catch the navigation, and then start downloading in the window by executing JavaScript.

**Comment by zcbenz** [comment]
After some discussion, we think the solution is to add a new API like `session.downloadURL`.

**Comment by paulcbetts** [comment]
This would be :gem: :heart_eyes_cat: for us!
