### ISSUE TITLE
Rename ATOM_SHELL_INTERNAL_RUN_AS_NODE

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron#3434]
Just wanted to queue up an issue for possibly renaming this environment variable to `ELECTRON_INTERNAL_RUN_AS_NODE` (or something else) as part of the Electron 1.0 API.

Also, @zcbenz do you think this is something that should be documented as part of the public API?

**Comment by zcbenz** [comment]
I'm :+1: on this, users are already using it anyway.
