### ISSUE TITLE
window.focus does not trigger if window is hidden

### ISSUE THREAD

**Issue by tevfik6** [atom/electron#3435]
Hi, 

Title explains the situation, I've searched and could not find any issue related to this. 

I'm on a mac and using on notification click event, calling window.focus(). This works perfect only if the window is visible.

If i hide `mainWindow.hide()`, focus event never triggered. I kinda wanted to hack it by handleing from 
```
mainWindow.on('focus', function(event){
mainWindow.show()
});
```
But it sees like focus event does not trigger at all. 

I'm not sure this behaviour is expected or not, but i would like to get the focus even in any case so that i can show the window and focus.

**Comment by etiktin** [comment]
You can emit the event yourself. For example:
`mainWindow.emit('focus')`

**Comment by tevfik6** [comment]
Thank you for your comment @etiktin but the project doesn't have nodejs from client side. Because it is actually a website. So, technically javascript focus should work on this or my assumption is wrong.

**Comment by zcbenz** [comment]
A hidden window can not be focused.

> but the project doesn't have nodejs from client side. Because it is actually a website.

You can use `preload` script to load a custom script for arbitrary website.
