### ISSUE TITLE
Can't debug version above 0.30.8 on WebStorm or VSCode using remote debugger

### ISSUE THREAD

**Issue by PauloLeal** [atom/electron#3436]
It keeps connecting but never connects. It happens on OSX and Linux. I can`t test on Windows.

**Comment by PauloLeal** [comment]
Its to debug the main proccess

**Comment by zcbenz** [comment]
I'm merging this to #3378.

**Comment by PauloLeal** [comment]
I disagree because I can debug v34 with node inspector

**Comment by PauloLeal** [comment]
at least on mac...
