### ISSUE TITLE
Unable to load https url via. loadUrl

### ISSUE THREAD

**Issue by kaarebs** [atom/electron#3437]
mainWindow.loadUrl(som https url) fails :(

When i load my dev app at http://localhost:4000 I have no problems -> everything works!

But when i change the url to https://our.production.env.com I get these error:

[5931:1114/161056:ERROR:nss_ocsp.cc(613)] No URLRequestContext for NSS HTTP handler. host: crt.ssl.com
[5931:1114/161056:ERROR:cert_verify_proc_nss.cc(922)] CERT_PKIXVerifyCert for xxx.xxx.com failed err=-8179

node : v0.12.7
electron: v0.31.0
3.16.0-53-generic #72~14.04.1-Ubuntu, x86_64 x86_64 x86_64 GNU/Linux

My dev team using OSX have the same versions of node and electron - everything works fine here, so I guess it is a linux problem.

**Comment by deepak1556** [comment]
Thats because of not following up on incomplete certificate chains on linux, it was fixed sometime back https://github.com/atom/brightray/pull/156 . I suggest upgrading your electron version on linux to v0.34.x.

**Comment by kaarebs** [comment]
Ohh.. Thanks a lot :) - now auto updater fails - så I will compile from master branch now - that issue has been fixed here :)
