### ISSUE TITLE
Merging efforts with others to get one great powerful and multiplatform webapp framework?

### ISSUE THREAD

**Issue by timofonic** [atom/electron#3438]
Hello.

What about merging efforts between Electron, Adobe's [Crosstalk Project](https://crosswalk-project.org), [NW.js](http://nwjs.io), [JX Core](https://github.com/jxcore/jxcore) and others?

I think this would benefit all involved parties with a stronger framework that can be available for more platforms, developers would find a more optimized and portable environment too. The merging process would be painful, but the result would be a lot better. "No pain, no gain".

I'm sure it would require a massive PR and legal effort, because Adobe is secretive about their involved programmers (for example). But the result would be very positive if results in an Open Governed project with the parties agreeing on the terms and merging efforts.

FOSS can do bigger and better things by managing the division of bigger tasks into smaller ones by more workforce, instead dividing in the efforts and competing all the time. It makes sense from economical and social reasons, this is wasted time that can be used to do things better and to improve lots of other projects much needed to get improved too. It's really hard to find good programmers. 

What do you people think?

It's time to change and make stronger projects, other toxic business models are reacting to weakness in the FOSS community and there's need to fix it.

Please consider it.

Kind regards.

**Comment by zcbenz** [comment]
Merging different projects is extremely hard and most times impossible because each one has its own architecture, it is not like getting a [Devastator](http://tfwiki.net/wiki/Devastator_(G1)) from Scrapper, Hook, Bonecrusher and Long Haul.

Also I don't know a single project that succeeded because of merging other projects, otherwise we would just merge FreeBSD/OpenBSD/NetBSD/Linux to get a much more awesome operating system than OS X and Windows.

**Comment by timofonic** [comment]
I would merge all BSDs. Currently DragonFly BSD is trying to get the best of the BSD world and has a very interesting file system, too. I would love certain BSD code to be merged with GPL code, but there are license issues.

So the main issue is about license...

On the other hand, this can be done progressively with certain projects one by one in a benevolent borg way (to make a scifi comparison too, let's get nerdy!).

**Comment by krytarowski** [comment]
Minix merged with NetBSD, and the process of merging is ongoing with the goal of custom core kernel and the rest from NetBSD (including networking, device drivers, bootloaders etc).
