### ISSUE TITLE
Add webContents.evaluateJavascript

### ISSUE THREAD

**Issue by n1k0** [atom/electron#3440]
I'm trying to retrieve a value computed against the DOM of an opened page in a browser window. I've found [webContents.evaluateJavascript](https://github.com/atom/electron/blob/fe214e08068a36e4f98febecd62b31011de474af/docs/api/web-contents.md#webcontentsexecutejavascriptcode-usergesture), but it seems it doesn't return any value:

```js
var browserWindow = new BrowserWindow({width: 800, height: 600});
browserWindow.loadUrl(someUrl);
browserWindow.webContents.on('did-finish-load', () => {
  console.log(webContents.executeJavaScript('document.body.textContent')); // undefined
});
```

Note that using `alert` demonstrates the property exists and contain something in my case:

```js
webContents.on('did-finish-load', () => {
  // shows an alert with body text
  webContents.executeJavaScript(`alert(document.body.textContent)`); 
});
```

Maybe it should return the computed value? Or maybe we could add a new `evaluateJavascript` method, like [the one in Phantom](http://phantomjs.org/api/webpage/method/evaluate.html), so we could retrieve values from the opened page context:

```js
browserWindow.webContents.on('did-finish-load', () => {
  console.log(webContents.evaluateJavaScript(function() {
    return document.body.textContent;
  }));
});
```

What do you think?

**Comment by etiktin** [comment]
You can do it today using ipc. Send the code you want to evaluate to the renderer using ipc, eval it in the renderer and send the result back using ipc.

**Comment by n1k0** [comment]
> You can do it today using ipc. Send the code you want to evaluate to the renderer using ipc, eval it in the renderer and send the result back using ipc.

That sounds like what I'm after, thanks. Do you have by chance pointers to the right documentation bits, ideally some code examples?

**Comment by etiktin** [comment]
See ipc example here: https://github.com/atom/electron/blob/v0.34.3/docs/api/ipc-main-process.md#sending-messages

Consider putting the renderer ipc and eval code in a preload script so it will work even if you disable node integration (see details here: https://github.com/atom/electron/blob/v0.34.3/docs/api/browser-window.md#new-browserwindowoptions).

**Comment by n1k0** [comment]
Perfect, thank you. I'm closing this.

**Comment by leegee** [comment]
Is it possible to do this without nodeintegration? Should I open a new ticket...?
