### ISSUE TITLE
Auto-updater broken as of 0.34.3: NSURLSession/NSURLConnection HTTP load failed

### ISSUE THREAD

**Issue by mkscrg** [atom/electron#3442]
Minimal repro here: <https://gist.github.com/mkscrg/d56227f2b6a3a430a17d>

`auto-updater` fails immediately after the `update-available` with this error:

```
2015-11-14 18:45:14.807 Electron[2750:121917] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
auto-updater error: An SSL error has occurred and a secure connection to the server cannot be made.: (null)
```

In my limited tests, I could hit this issue with **Electron >= 0.34.2 && OS X >= 10.11**. Dropping to 0.34.1 and/or 10.10 seemed to avoid it.

**Comment by mkscrg** [comment]
Possible workaround: apparently some SSL certs break `auto-updater` and some don't. All of our `wagonhq.com` certs seem to work fine.

I tried serving the update files different ways and found:

- Amazon's content certs break `auto-updater`. This includes
    - `s3.amazonaws.com`
    - `*.s3.amazonaws.com`
    - `*.cloudfront.net`
- Our "normal" SSL certs seem to work fine. For example [`*.wagonhq.com`](https://www.wagonhq.com/), which is a Comodo wildcard cert. I'm not sure what distinguishes this from Amazon's certs.
- A simple self-signed cert breaks `auto-updater`. ([Made like this.](https://devcenter.heroku.com/articles/ssl-certificate-self))

**Comment by joshaber** [comment]
Correct. This is because of App Transport Security, new in iOS 9 and OS X 10.11.

Unfortunately in classic Apple fashion there's very little documentation about it. It looks like the best they have is documentation of the plist keys: https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40016240

You'll need to either setup your update server with a cert that App Transport Security will accept, or add an exception to your app.

**Comment by mkscrg** [comment]
@joshaber is it odd that we ran into this issue as of 0.34.2? We got around it by using an ATS-friendly cert, but I was surprised to find this breakage in an Electron point release.

**Comment by joshaber** [comment]
Hmm that is a bit surprising. I'd have thought it'd be dependent on the SDK you're linking against, but perhaps it's using the SDK Squirrel was built against instead.

**Comment by joshaber** [comment]
Is it possible you changed the SDK your app is building against?

**Comment by zcbenz** [comment]
From 0.34.2 the Electron build switched to use OS X 10.11 SDK because of an issue of our internal CI machine, that should be the root problem of this. @joshaber I'm cc-ing you in that issue.

**Comment by joshaber** [comment]
@zcbenz I wonder if Electron should include an ATS exception by default so that we can undo this breakage. Maybe even `NSAllowsArbitraryLoads` and let users turn it back on if they want it?

**Comment by zcbenz** [comment]
@joshaber I'm :+1: on adding `NSAllowsArbitraryLoads` by default, but many apps are creating their own Plist files, so it will not really fix this.

**Comment by paulcbetts** [comment]
It'd be :cool: :up: if Apple would yanno, specify why correctly-validating certificates don't work

**Comment by joshaber** [comment]
>It'd be :cool: :up: if Apple would yanno, specify why correctly-validating certificates don't work

FWIW, `nscurl --ats-diagnostics URL` will usually give you more info.
