### ISSUE TITLE
Found A bug with menu

### ISSUE THREAD

**Issue by McFarts** [atom/electron#3445]
IF you do
```
mainWindow.setMenu(null); // Remove top Menu
```

to remove the top menu

You cannot do CTRL+R to refresh the app anymore, UNLESS you have the dev console open and have your mouse active inside of it.

Intended or bug?

Edit: BTW W7 PRO 64 BIT & Latest version of Electron ~

**Comment by jean-emmanuel** [comment]
It seems perfectly normal since the window's keyboard shortcuts are defined in the top menu (ctrl+r for refresh is just a default value). The dev panel has its own shortcuts that can override them though (see settings>shortcuts in the panel).

**Comment by McFarts** [comment]
Yeah, but when the top menu bar is showing your mouse doesn't need to be active over it for the ctrl+r to work, your mouse can be anywhere on the screen and the ctrl+r works fine.

However, when that top menu is gone and u have the dev console up, your **mouse has to be** active in the dev console  area for a ctrl+r or f5 to work.  But, when the top menu is there your mouse does not have to be active over it to work, doesn't seem right

**Comment by jean-emmanuel** [comment]
The dev console's shortcuts should only be active when it's opened, since they are related to dev things. Having ctrl+r being assigned to the same action in the rendered document and in the dev console is a coincidence. 
If you want ctrl+r to work always the same way, you will have to declare a  [global shortcut](http://electron.atom.io/docs/v0.34.0/api/global-shortcut/)

```
var globalShortcut = require('global-shortcut');

app.on('ready', function() {
  var ret = globalShortcut.register('ctrl+r', function() {
    if (window.isFocused()) window.reload()
  });

});

app.on('will-quit', function() {
  globalShortcut.unregisterAll();
});
```

**Comment by sindresorhus** [comment]
You might want to check out [electron-debug](https://github.com/sindresorhus/electron-debug).

**Comment by McFarts** [comment]
@jean-emmanuel  Oh good idea.

@sindresorhus  Thank you, I guess not really a bug, just thought the mouse being active over the console was weird to enable refresh.

I will close for now I guess Thank you guys!
