### ISSUE TITLE
Forked Electron process using eslint crashes

### ISSUE THREAD

**Issue by aknuds1** [atom/electron#3446]
After using `child_process.fork` to spawn a thread and requiring `eslint` module from it, the child process crashes with the following on it's stderr:

    VM685:2 (6644,0x10b23f310) malloc: *** error for object 0x7fb3b3450cb0: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug

I believe it crashes in an `eval` performed by `eslint` while linting, Please tell me how I can debug this further.

**Comment by zcbenz** [comment]
It had been fixed in v0.34.1.
