### ISSUE TITLE
Electron packaged app dependencies? Openbox fails

### ISSUE THREAD

**Issue by Prezto** [atom/electron#3447]
All seems to work fine on an ubuntu gnome system and also on lubuntu. I also tested full desktops and on all the program just works.

When i use an ubuntu server image with only an openbox-session all seems to fail and i get the error message below. I made this for a sort of "kiosk" idea. Maybe i am doing something wrong or does Electron require certain packages to be installed?

Note : This is a packaged electron app with version 0.34.3.
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/opt/arcadia/resources/atom.asar/browser/lib/init.js:115:7)
    at Object.<anonymous> (/opt/arcadia/resources/atom.asar/browser/lib/init.js:127:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3
```

**Comment by zcbenz** [comment]
Does chromium-browser work on it?

**Comment by tymat** [comment]
Chromium works just fine in my setup but I get the same issue.

**Comment by Prezto** [comment]
I forgot this issue. My apologies. I do remember it had to do with system dependencies and not with electron. I will try to check for you which packages you need.

Verzonden met mijn Windows Phone
________________________________
Van: Anthony Eufemio<mailto:notifications@github.com>
Verzonden: ‎2/‎5/‎2016 2:05 PM
Aan: atom/electron<mailto:electron@noreply.github.com>
CC: Dany Henriquez<mailto:dany.henriquez@outlook.com>
Onderwerp: Re: [electron] Electron packaged app dependencies? Openbox fails (#3447)

Chromium works just fine in my setup but I get the same issue.

---

**Comment by tymat** [comment]
Please see this https://github.com/ethereum/mist/issues/142

Happens in electron-prebuilt on OS X El Capitan
