### ISSUE TITLE
Licence cannot legally be MIT, it must be GPL

### ISSUE THREAD

**Issue by still-dreaming-1** [atom/electron#3449]
I am not a lawyer, and I am only trying to make an informed decision about whether to use electron for my own project. Please correct me of any mistakes.
According to this website http://tangiblejs.com/posts/nw-js-electron-compared, electron statically links to the ffmpeg library which is GPL. Based on some research, it seems to me electron is not allowed to have an MIT license, it must have a GPL license. I believe GPL licensed code can contain MIT licensed code, but not the other way around. If that is true, it would seem all projects using electron must also have a GPL licence if they are distributing their applications. It seems nw.js avoids this problem by requiring users to manually link to the ffmpeg library. What do you all think about this?

**Comment by zcbenz** [comment]
Only a small part of ffmpeg are GPL-licensed, and Chromium/Electron is compiled with the non-GPL ones, you can read ffmpeg's LICENSE.md for more:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/ffmpeg/LICENSE.md&sq=package:chromium&type=cs

If you still have more questions, I suggest bringing it up on Chromium's [issues list](https://crbug.com), Electron's license is compatible with Chromium's one, and I believe Google's lawyers have solved the license problems perfectly.
