### ISSUE TITLE
Subscribing to Frames in C++

### ISSUE THREAD

**Issue by KenPowers** [atom/electron#3452]
I would like to subscribe to frames in an Electron app and send them through [this particular API implemented in C++ (PDF warning)](http://www.goodshooter.com/ahigh/Blackmagic%20Decklink%20SDK.pdf). My original idea was to implement a native Node addon and have a C++ function handle the frame data. I got something working where a C++ function is called for every frame ~~but it crashes when I iterate through the buffer data (see below)~~.

So ~~while it would be nice to get that working (see code below),~~ I was thinking about my use-case and I was wondering if I could avoid the use of node buffers altogether since I don't have to use the data at all from JavaScript land. I was looking at the implementations of [`WebContents::BeginFrameSubscription`](https://github.com/atom/electron/blob/52f1431bde557e083f74af368aed5c08b9ae76f1/atom/browser/api/atom_api_web_contents.cc#L944-L952) and [`FrameSubscriber::OnFrameDelivered`](https://github.com/atom/electron/blob/e5e4749eb3c592667922f87c1105981db9dd84f7/atom/browser/api/frame_subscriber.cc#L36-L62) and had a few questions:

1. Let's say I pass a JavaScript instance of `WebContents` in to a native C++ function. How do I go about calling `GetRenderWidgetHostView()` so I can then call `BeginFrameSubscription()`?
1. Is there documentation anywhere on how to implement a `FrameSubscriber` in C++? Yes, I can read the code but it's been a while since I've really done serious C++.

~~As for what I had previously gotten working, I've never really done native node development before and I'm not too familiar with V8 internals. So this is an excerpt from my attempt at cobbling together various examples I've found across the internet:~~

```c++
#include <nan.h>

const int NUM_CHANNELS = 4;

void ProcessPixels(const Nan::FunctionCallbackInfo<v8::Value>& info) {
  unsigned long bufferLength = node::Buffer::Length(info[0]);
  unsigned char *bufferData = (unsigned char *)node::Buffer::Data(info[0]);
  unsigned long len = 0;
  for (unsigned long i = 0; i < bufferLength; i += NUM_CHANNELS) {
    for (int j = 0; j < NUM_CHANNELS; j++) {
      // Do something with the following
      // bufferData[i + j]; // Crashes when `i + j == 4435`
    }
  }
}

void Init(v8::Local<v8::Object> exports, v8::Local<v8::Object> module) {
  Nan::SetMethod(module, "exports", ProcessPixels);
}

NODE_MODULE(frames, Init)
```

~~The above crashes *consistently* when `i + j` is `4435` with `SIGSEGV`. So yeah, segfault. What I don't understand is *why?*... I also tried `unit8_t *` instead of `unsigned char *`, same result.~~

**Comment by KenPowers** [comment]
Okay, ignore the code "not working." I was using `i` in the inner loop when I meant to use `j`. Stupid stupid stupid mistake.

I'm still interested in my initial question though. Bypassing the usage of node `Buffer`s and whatnot.

**Comment by zcbenz** [comment]
You can use `v8::Object::GetAlignedPointerFromInternalField` to get the native class pointer from the `webContents` object, but it would be very hard to call the right methods of it because Node doesn't know the headers of Electron, and the C++ interface is not exported.

**Comment by KenPowers** [comment]
So maybe a custom build of Electron with my own code added to `WebContents`? I could add a patch to the build process.

**Comment by IsaiahJTurner** [comment]
@knpwrs What did you end up doing here?

**Comment by knpwrs** [comment]
I wound up rendering what I wanted to render outside of Electron.
