### ISSUE TITLE
URL pointing to / not given right file:// translation

### ISSUE THREAD

**Issue by bitwombat** [atom/electron#3455]
# Description

I'm seeing that an `img` URL like:
`<img src="./theme/images/videoTitle_16x9.jpg" />`

Is accessed correctly by electron (Chromium?) as:
`file:///home/me/electron_bug/theme/images/videoTitle_16x9.jpg`

However, if it's referring to root (note no leading '.'):
`<img src="/theme/images/videoTitle_16x9.jpg" />`

Then no translation happens and it points to:
`file:///theme/images/videoTitle_16x9.jpg`
...which is, of course, not on disk and 404's.

While my testcase seems simple, this is actually a huge problem for me as my app has 100s of URLs like this.

# How to reproduce
* Download and extract [this zip file](https://www.dropbox.com/s/jwikwvbar5mquil/electron_bug.zip?dl=0)
* Run electron
    $ cd electron_bug
    $ electron .
* Inspect the two image elements

**Comment by zcbenz** [comment]
This behavior is intended for `file://` protocol, and you can observe the same behavior in Chromium. The solution is to either keep using relative urls, or to use custom protocol.
