### ISSUE TITLE
Webview events are not accessible via IPC

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#3466]
I posted an issue about accessing DOM elements inside the webview: https://github.com/atom/electron/issues/3315#issuecomment-156403512 to which apparently you cannot do yet, so the only solution is to use IPC.

However I have found an issue whereby events are not accessible.

To re-create this:

In the **preload.js** file applied to the webview I have:
~~~
var ipc = require('ipc');
document.addEventListener('click', function(event) {
	   ipc.send('sendEvent', 'simple text');
	   ipc.send('sendEvent', event);
});
~~~

Then on the main process **main.js** I have:
~~~
ipc.on('sendEvent', function(event, arg){
	mainWindow.webContents.send('sendEvent', arg);
});
~~~

Then in the renderer page that contains the webview I have:
~~~
ipc.on('sendEvent', function(data){
	console.log(data);
});
~~~

The console.log is:
~~~
'simple text'
Object {}
~~~

So for some reason the object is blank when I get it back from the click event in the webview.

But if I send back simple text then I see that fine. Just not events from the click.

**Comment by zcbenz** [comment]
The JavaScript objects passed to `ipc.send` are serialized to JSON when sending messages.

Also if you are communicating between the webview and host page, there is more easy to do that:
http://electron.atom.io/docs/v0.34.0/api/web-view-tag/#event-39-ipc-message-39

**Comment by iamdriz** [comment]
@zcbenz I'm not sure what you mean... Are you saying they are destroyed? Because I can't decode them or anything, the Object is empty from what I can see.

**Comment by zcbenz** [comment]
Many DOM objects can not be serialized into JSON, and you will get an empty object if you do so.

**Comment by iamdriz** [comment]
@zcbenz So how do I get around this? As I need to get access to dom elements or there events in a webview. Thanks.

**Comment by zcbenz** [comment]
You can just pass the attributes you need.

**Comment by iamdriz** [comment]
@zcbenz I tried that: `event.target.tagname` but even that is blank. It's as though anything to do with events isn't available inside the webview.

**Comment by Sjael** [comment]
Is there no fix for this? And how would I specify what DOM elements I'd need in that case?

**Comment by Sjael** [comment]
@zcbenz How would we pass the attributes needed? I'm wanting to access DOM elements as well, but I'm trying to .clone() them and access them on the renderer. Is this possible?

**Comment by coelhoadler** [comment]
I've the same problem within pass an object for ipc =/
