### ISSUE TITLE
Just tried to run electron 0.35.0, ipcMain missing?

### ISSUE THREAD

**Issue by frozeman** [atom/electron#3467]
I get the error that the module `ipcMain` doesn't exist, when using `const ipc = require('ipcMain');` in the main.js file.

**Comment by zcbenz** [comment]
You have to use `require('electron').ipcMain`, the `require('ipc-main')` also works but is deprecated.

**Comment by frozeman** [comment]
Thanks a lot, just looked at the release page, but better put that there ;)
