### ISSUE TITLE
Problem with current protocol implementation

### ISSUE THREAD

**Issue by ssboisen** [atom/electron#3468]
Hi,

Ever since the protocol implementation was changed in v0.31.0 (see [here](https://github.com/atom/electron/compare/v0.30.8...v0.31.0) for all changes) it's no longer possible to do proper url rewriting and resource loading in Electron, a feature that is very useful and even necessary in some cases.

Previously you could intercept the file scheme and then return a type of job depending on where you wanted the actual content to be loaded from. This is however no longer possible since you now have a intercepter for each type of job and it's not possible to intercept a scheme more than once.

I suggest going back to the original concept with a single interceptor-api but with seperat job-type objects while keeping the async behaviour, so a usage similar to this:

```
protocol.interceptProtocol('file', function (request, callback) {
  var url = request.url.substr(7);
  if (/^fonts.googleapis.com.*/.test(url)) {
    callback(new protocol.RequestHttpJob({ url: 'https://' + url }));
  } else if (/^\/api\/.*/.test(url)) {
    callback(new protocol.RequestHttpJob({ url: 'https://mydomain.com' + url })); 
  } else {
    callback(new protocol.RequestFileJob(path.join(__dirname, 'static', url));
  }
});
```

Alternatively instead of using the callback each of the job-types could be a promise so they could just be returned (like the previous api except the promises part).

Is this something you would considering fixing or are there good reasons why it was changed? I'dd be happy to supply a pull-request if that would speed up the process.

**Comment by zcbenz** [comment]
I love the original protocol design, but it is against the design of Chromium's network stack and has many bugs and limitations, you can find more about the decision in #2475.

**Comment by ssboisen** [comment]
That is unfortunate! I guess the only way to get around this now then is by using ```protocol.interceptHttpProtocol`` with an integrated web server that acts as a sorta proxy for a local file and a remote one.
