### ISSUE TITLE
Notification with icon crashes electron on Windows

### ISSUE THREAD

**Issue by raleksandar** [atom/electron#3470]
Following example causes electron v0.35.0 to crash on Windows 10:

````js
new Notification('Title', {
    body: 'Notification with icon',
    icon: 'file:///D:/temp/electron/test.png',
});
````
File exists in that path. I have also tried using normal file path (not URI) but it still crashes.
Only without icon property set it will show notification (and not crash an app).

**Comment by zcbenz** [comment]
It has been fixed by https://github.com/atom/brightray/pull/175, the fix will be included in next release.

**Comment by raleksandar** [comment]
Great, thanks on quick reply! :)
