### ISSUE TITLE
how to let the main window out of focus automatically

### ISSUE THREAD

**Issue by YangjunZ** [atom/electron#3472]
I want to develop a desktop app by electron. A global shortcut has been registered to show and focus the main window. And another global shortcut has been registered to hide the main window and recover the focus to application which has used previously. 
For the first shortcut, it is easy to do this. But for the second one, I have not found any method in electron API to main window out of focus automatically. 
Despite the main window has been hidden, the window of previous application can not get the focus.
Can anyone help me ?

**Comment by zcbenz** [comment]
Electron doesn't interact with windows created by other applications, so the only way to do what you want precisely is to write a native Node module.

However on Windows and Linux, when you hide a window the previous window should regain the focus automatically, and on OS X you should be able to achieve the same effect by [hiding the app](https://github.com/atom/electron/issues/2640):

```javascript
Menu.sendActionToFirstResponder('hide:');
```

**Comment by YangjunZ** [comment]
Thanks for your comments. 
But I have found that a window can be focused through it has been hidden on windows.
This led to the previous window can not regain the focus automatically. 
Here are my codes:

```javascript
function initShortcut() {
    globalShortcut.register('alt + shift + x', function() {
        showHideSwitch();
    });
}

function showHideSwitch() {
    if (mainWin.isFocused() && mainWin.isVisible()) {
        // mainWin.emit('blur');
        mainWin.hide();
        //after that case, the mainWin is not visible, but it's focused.
    } else {
        mainWin.show();
        mainWin.webContents.send('focus-on-input');
    }
}
```

**Comment by wearhere** [comment]
@zcbenz when you write

> However on Windows… when you hide a window the previous window should regain the focus automatically

I do not find this to be the case. Here is a video illustrating my situation:

http://cl.ly/2F0I1r2b2a13

1. You can see that before clicking on the "compose" tray item, the Explorer window has the focus (as indicated by the "X" menu bar button being red).
2. When the "compose" window closes, focus does not revert to the Explorer window.

Here is another video where I hide the main window when the compose window closes, just to be sure, and focus still does not revert to the Explorer window:

http://cl.ly/2E1c0R19471J

**Comment by YangjunZ** [comment]
Hi @wearhere, I have the same problem too. 
It is annoying that a window can be focused through it has been hidden on windows, except app quit.

If we can discard focus to system, this problem can be solved. There are some hints in source code of electron shows below :
``` C
//atom/browser/native_window.h
virtual void Focus(bool focus) = 0;

...

//atom/browser/native_window_views.cc
void NativeWindowViews::Focus(bool focus) {
  if (focus)
    window_->Activate();
  else
    window_->Deactivate();
}

...

//description in BrowserWindow API
win.focus()
Focus on the window.

```
But electron API has not method to set focus false. Maybe we need dive more deeper.

**Comment by PAB-me-uk** [comment]
@zcbenz

Can this be reopened as its clearly not fixed and is affecting downstream projects.

See https://github.com/tinytacoteam/zazu/issues/185

**Comment by Slapbox** [comment]
I am also finding this to be a serious user experience problem.

**Comment by jakobvogel** [comment]
Hi! I came across the same problem and found two workarounds that work on Windows:

1. [RobotJS](http://robotjs.io) can be used to simulate [alt]+[tab]. Unfortunately, this brings up the app switching dialog for a short time.
2. Windows apparently defocuses the app once the last visible window is closed. Consequently, after hiding the relevant window, one can open an auxiliary window (in my case: transparent, frameless, 1x1 pixels in a screen corner), and close it again immediately. This is invisible to the user but leads windows to pass focus to another app.

I would also prefer a proper solution (like `app.defocus()`), but in lack of it, the second option works well for us (so far).

**Comment by ttrepka** [comment]
@jakobvogel's second option seems to work great on Windows!

Here's a piece of code (and a full [Electron Fiddle Gist](https://gist.github.com/ttrepka/aace7f4c53a6bc98b6fdedac5ee39576) to play with), I thought it could be helpful for others:
```
function winReturnFocus() {
  const dummyTransparentWindow = new BrowserWindow({
    width: 1,
    height: 1,
    x: -100,
    y: -100,
    transparent: true,
    frame: false,
  });
  dummyTransparentWindow.close();
}

mainWindow.on('hide', () => {
  if (process.platform === 'win32') {
    winReturnFocus();
  }
})
```
I still think this should be reopened and fixed in Electron, though.

**Comment by avalanche1** [comment]
Please open this issue!

**Comment by avalanche1** [comment]
By the way, guys, this is not a Win-only problem - the same is true for macOS

**Comment by Slapbox** [comment]
This is working properly for us now. I think if you're having issues, you may need to try `win.blur()` to actively return focus to the window which previously had it.

**Comment by anis00723** [comment]
@avalanche1 it actually hides the app 😞

**Comment by sachinsrinivas12** [comment]
I'm building a notifier application, checkWindowIsMinized is called every time I get a new notification,

My else if condition isn't working.

I need to show the app and it should be focused for the user. Can you help me fix this piece of code?
  ipcMain.on('checkWindowIsMinized', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) {
        mainWindow.restore()
      } else if (!mainWindow.isFocused()) {
        mainWindow.webContents.focus()
      }
    }
  })

**Comment by HawtinZeng** [comment]
Just use `browserWindow.blur();`, it works in Electron@31.1.0

**Comment by nianyi778** [comment]
> By the way, guys, this is not a Win-only problem - the same is true for macOS顺便说一句，伙计们，这不是一个只有 Win 的问题 - macOS 也是如此

Now it has not been repaired, I do not know how to solve it

**Comment by yPhil-gh** [comment]
> By the way, guys, this is not a Win-only problem - the same is true for macOS

Linux (Ubuntu 24.04 here) too.
