### ISSUE TITLE
Maximize not working properly...

### ISSUE THREAD

**Issue by sapioit** [atom/electron#3480]
Oh, so I am working on [this project](https://github.com/sapioit/Colliderr) and I am trying to have the FullScreen working properly... but this is what I get...

If you do know a workaround, please do tell me about it!

## Normal (not maximized nor fullscreen)

![image](https://cloud.githubusercontent.com/assets/3173159/11228488/82aa8548-8d95-11e5-8cab-90678ae8950c.png)

## Maximized (space around the html of the BrowserWindow)

![image](https://cloud.githubusercontent.com/assets/3173159/11228503/9ee6d108-8d95-11e5-877d-dc16274f4db6.png)

## Full Screen (no transparency where it should be)

![image](https://cloud.githubusercontent.com/assets/3173159/11228508/a942b11c-8d95-11e5-9059-02bf7fb603a4.png)

**Comment by zcbenz** [comment]
I'm merging this to #1690.
