### ISSUE TITLE
Memory Leak Event Emitters: when using evaluate

### ISSUE THREAD

**Issue by bollywood-coder** [atom/electron#3481]
Hi Nightmare Team

I know there has been an issue submitted 3 weeks ago:
https://github.com/atom/electron/issues/3244

However, I want to contribute to this issue that nightmare's evaluate function could be the potential source of this problem..

1. Test
--------
// with evaluate -> Memory Leak after the 10nth loop
function *start() {
  var nightmare = new Nightmare({ show: true });
  for (var i = 0; i < links.length; i++) {
    var title = yield nightmare.goto(links[i]).evaluate(_extractTitle);
    console.log(links[i], title);
  }
  yield nightmare.end();
}

2. Test
--------
// no evaluate -> everything runs fine!
function *start() {
  var nightmare = new Nightmare({ show: true });
  for (var i = 0; i < links.length; i++) {
    var title = yield nightmare.goto(links[i]);
    console.log(links[i], title);
  }
  yield nightmare.end();
}

Node version: 4.2.2
Nightmare version: 2.14.7

I hope I could contribute to this issue to help you to fix it more faster.
Screenshot of the full code and output included!

Question: Do you guys work on this issue already?

Cheers
R.

![issue](https://cloud.githubusercontent.com/assets/10127605/11228490/c228cd3a-8d84-11e5-9053-594bf00a9c98.JPG)

**Comment by paulcbetts** [comment]
This is a nightmare issue, please file it on the appropriate repo
