### ISSUE TITLE
child_process.execSync causes error: write EBADF

### ISSUE THREAD

**Issue by davej** [atom/electron#3482]
Seeing this issue in the renderer process (works fine in main process) of 0.34.3 on Yosemite. `child_process.exec` is fine, only `execSync` fails.

To recreate in the renderer, just do:
```js
require('child_process').execSync('echo $PATH');
```

The error backtrace:
```
events.js:141 Uncaught Error: write EBADF
exports._errnoException @ util.js:837
exports._exceptionWithHostPort @ util.js:860
afterWrite @ net.js:760
```
<img width="912" alt="screen shot 2015-11-17 at 22 54 28" src="https://cloud.githubusercontent.com/assets/26971/11227494/31dcee1a-8d7e-11e5-86b1-d7db990bb692.png">

Possibly related to: https://github.com/atom/electron/issues/1471

**Comment by zcbenz** [comment]
I'm unable to reproduce it, but I think I can guess out the cause. Can you run this code in renderer and then test whether `execSync` works?

```javascript
```

**Comment by davej** [comment]
It is still causing the same error.

```js
> process.stdout._write = function(_, _, callback) {
    process.nextTick(function() {
      callback(0);
    });
  }
> require('child_process').execSync('echo $PATH');
events.js:141 Uncaught Error: write EBADF
```

**Comment by zcbenz** [comment]
Does the error happen if you call `require('child_process').execSync('echo $PATH', {stdio: 'ignore'});`?

**Comment by davej** [comment]
No.

**Comment by davej** [comment]
@zcbenz After a bit of digging, I realised that it is specific to my app. I've managed to track down a reproducible error scenario, it's very very strange!

In main/browser:
```js
var foo = console;
```

In renderer:
```js
require('child_process').execSync('echo $PATH');
```

Here's a repo that you can clone to reproduce it: https://github.com/davej/electron-execSync-test

**Comment by davej** [comment]
Tested the repo in my last comment on a different machine machine running OS X 10.11 and also tested on Windows 7.

Results are:

* Windows 7: **OK**
* OS X 10.10 (Yosemite): **Error**
* OS X 10.11 (El Capitan):  **Error**

This seems to suggest that the bug is OS X specific but not machine dependent.

**Comment by lgodard** [comment]
Hi
i experience same behaviour on Win7

in a js
const console = require('console');
...
console.log('my dummy message');

this line issues an error
 Uncaught Error: EBADF: bad file descriptor, write

if i remove the const console, everything is fine

feel free to ask if precision needed

Laurent

**Comment by etiktin** [comment]
@lgodard, the console object is a part of the global object so it's always available and you don't  need to require it. The require will always fail, unless you npm install some module called console, so just remove that line.

**Comment by davej** [comment]
It may fail but it shouldn't fail with a bad file descriptor message.

**Comment by etiktin** [comment]
I agree it should be `Error: Cannot find module 'console'` or in this case `TypeError: Identifier 'console' has already been declared`. The point of my comment was that you shouldn't require console, not about the error thrown.

**Comment by davej** [comment]
You're probably correct, it's not impossible that `console` is a module though. It may shim `console` features or dump the logs to file/db. Anyway, I'm gone horribly off-topic! :-)

**Comment by lgodard** [comment]
Hi,
Thanks a lot for your responses

I agree that console.log() works and displays outputs in DevTools window

But, at least on linux, using require('console') redirects the output in the console where npm start has been launched. It allows to track all the output messages at once (no external module installed)

My point is, it is working for linux but fails on win7 with the "Uncaught Error: EBADF: bad file descriptor, write" message so i can't rely on developping multiplateform

Thanks again

Laurent
