### ISSUE TITLE
Codesigning latest Electron release fails Gatekeeper

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#3489]
I have an automated build system to package up and codesign my Electron app (Ronomon.app) and then run it through spctl to verify Gatekeeper acceptance.

It's been working fine with Electron v0.30.4.

Switching to Electron v0.35.0 today gave spctl errors that I couldn't fix (by changing frameworks to be signed etc.). These are the signing commands I use and the resulting error:

```
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Electron Framework.framework/Libraries/libnode.dylib"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Electron Framework.framework/Electron Framework"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Electron Framework.framework"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Mantle.framework/Mantle"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Mantle.framework"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/ReactiveCocoa.framework/ReactiveCocoa"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/ReactiveCocoa.framework"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Ronomon Helper.app"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Ronomon Helper EH.app"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Ronomon Helper NP.app"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Squirrel.framework/Resources/ShipIt"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Squirrel.framework/Squirrel"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app/Contents/Frameworks/Squirrel.framework"
codesign --deep --force --sign "Developer ID Application: ..." "Ronomon.app"

spctl --ignore-cache --no-cache --verbose=4 --assess --type execute "Ronomon.app"
Ronomon.app: rejected
source=no usable signature
```

I switched back again to Electron v0.30.4 and `spctl` accepts the signature. Using codesign to verify both also passes, but spctl is what OS X will use when the app is downloaded by the end-user.

Any help would be much appreciated. I know Apple added some more symlink checks to spctl recently.

**Comment by zcbenz** [comment]
Can you try the ways in http://jbavari.github.io/blog/2015/08/14/codesigning-electron-applications/? It seems that you also need to sign some symbol-linked directories.

**Comment by jorangreef** [comment]
Thanks @zcbenz, I was trying to sign the frameworks via `versions/current` instead of via `versions/a`.

I modified the script there and got it to work. The `export CODESIGN_ALLOCATE` there was not necessary.

Here is a reduced and simple script which works and does the minimum of signing (without signing things twice):

https://gist.github.com/jorangreef/27e708c67b7e6746a98a

It's a few seconds quicker and passes Gatekeeper. Hope this helps anyone else, and thanks again for the pointers.
