### ISSUE TITLE
Flickery dock icon animation when launched with app.dock.hide()

### ISSUE THREAD

**Issue by detj** [atom/electron#3498]
I'm building a tray app on OSX and don't need the dock icon to show at all. The first line of the main file is

```
app.dock.hide();
```

But, when launched with `electron-prebuilt`

```
$ electron .
```

dock icon launches for a brief moment and then disappears, animating the dock all the way which will not go unnoticed. Here is a gif of the behavior.

![flickery dock icon animation](http://zippy.gfycat.com/JadedRewardingGrizzlybear.gif)

I also tried this, but the same behavior exists

```
app.on('will-finish-launching', function() {
  app.dock.hide();
});
```

Maybe I'm not calling the `app.dock.hide()` method at the right place? Is it possible to configure this through `package.json` so that the when it launches it doesn't show the dock icon at all?

_electron v0.35.0_

**Comment by zcbenz** [comment]
On OS X  you can add `LSUIElement` to Info.plist to hide the dock icon by default, but currently it will crash the app. I'm merging this to #1369.

**Comment by lucasbento** [comment]
@detj: did you find a way to fix this?

**Comment by detj** [comment]
@lucasbento I have to try with a newer version of Electron and see. As far as I know, it is possible to specify certain plist values in `package.json` now which should solve the issue.
