### ISSUE TITLE
[0.35.0] "Will-Download" event is not Firing

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#3511]
Hello,

We have download intercept code to show UI and route it to the folder when download completes,
Our code was failing in 0.35.0, on digging further into it, we can see that event is not firing in 0.35.

Env Info :
- Electron 0.35.0 64bit mac build
- Electron 0.35.0 32bit windows build

Works fine in 0.34.x Builds of Electron.

Thanks.

**Comment by kamesh-a** [comment]
One more we have to notice , If user changes the directory path, while download dialog pops up, application have no clue whether " download path / filename  " has been changed.

Showing the item in folder is not possible.

**Comment by zcbenz** [comment]
Can you provide an example? The test case of `will-download` seems to be passing.

**Comment by kamesh-a** [comment]
Sure i will provide a test case in couple mins

**Comment by kamesh-a** [comment]
https://github.com/kamesh-a/electron-samples/tree/master/willDownload

Works fine  in :0.34.x
Fails in 0.35.x

Plus deprecated api, reporter is issues an max call stack trace...
<img width="1005" alt="electron_deprecated_reporter_max_call_stack" src="https://cloud.githubusercontent.com/assets/3531949/11332520/5e9a213a-91ec-11e5-9150-c85072c3782d.png">


(electron) loadUrl is deprecated. Use loadURL instead.
(electron) hasUserGesture property is deprecated. Use hasUserGesture method instead.
(electron) hasUserGesture property is deprecated. Use hasUserGesture method instead.
(electron) hasUserGesture property is deprecated. Use hasUserGesture method instead.
(electron) hasUserGesture property is deprecated. Use hasUserGesture method instead.
(electron) hasUserGesture property is deprecated. Use hasUserGesture method instead.

Thanks.

**Comment by kamesh-a** [comment]
Fix, works fine. Thank you @zcbenz
