### ISSUE TITLE
Executing a script as a child_process.exec inside an asar archive

### ISSUE THREAD

**Issue by jviotti** [atom/electron#3512]
I have [this module](https://github.com/resin-io/drivelist) that executes scripts (vbscript, sh) that live within the module directory to perform it's work. Given that the scripts are not nodejs modules, using `child_process.fork` doesn't seems to be an option.

Is there a way to make `child_process.exec` or `child_process.spawn` automatically read the contents of `app.asar`, given the [following paragraph in Electron's documentation](http://electron.atom.io/docs/v0.35.0/tutorial/application-packaging/#node-api)?

> With special patches in Electron, Node APIs like fs.readFile and require treat asar archives as virtual directories, and the files in it as normal files in the filesystem.

I have the following ideas but feel that this could be solved in a much easier way:

1. Make the module detect if trying to execute a file inside an `*.asar` and copy it to another location with outside the archive `fs` (assume this one does work on `asar`) and call from there.

2. Save the scripts as text and write to a temporary file when the module starts and call from there.

I would appreciate any insight on this!

**Comment by zcbenz** [comment]
We do support executing script in asar archive with `child_process.execFile`, and it is implemented exactly by copying the file out.

However `exec` and `spawn` are different stories because they accept `command` instead of `file`, and the commands are executed under shell. There is no reliable way to determine whether a `command` uses a file in asar archive, and even if we do, we can not be sure whether we can replace the path in `command` without side effects.

So I think the only solution is to use `execFile` in your module.

**Comment by jviotti** [comment]
@zcbenz Thanks for the information, will try `execFile`.

**Comment by jviotti** [comment]
@zcbenz I've tried using `execFile` in my module. The script seems to be found, however I get an `EACCES`:

```
Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.exports.execFile (child_process.js:153:15)
    at Object.module.(anonymous function) [as execFile] (ATOM_SHELL_ASAR.js:178:18)
    at Object.exports.run (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/node_modules/drivelist/build/scripts.js:21:24)
    at Object.exports.list (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/node_modules/drivelist/build/drivelist.js:16:18)
    at Object.tryCatcher (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as listAsync] (eval at <anonymous> (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Object.exports.listRemovable (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/lib/src/drives.js:46:20)
    at callFunction (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:176:18)
    at EventEmitter.<anonymous> (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:272:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:95:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

Are executable permissions conserved the packaging to an `asar`?

I've found the following issues: https://github.com/atom/asar/issues/27 about preserving permissions when unpacking, and given that you say `execFile` is implemented by copying the file out (extracting), the permissions should be kept.

**Comment by jviotti** [comment]
I've tried executing the script as `execFile('sh', [ 'path/to/script.sh' ])` which throws a different error:

```
Error: Command failed: sh /Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/node_modules/drivelist/scripts/darwin.sh
sh: /Users/jviotti/Projects/resin/herostratus/release/Herostratus-darwin-x64/Herostratus.app/Contents/Resources/app.asar/node_modules/drivelist/scripts/darwin.sh: Not a directory

    at ChildProcess.exithandler (child_process.js:209:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:764:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by jviotti** [comment]
My guess is that `execFile` only attempts to read the file argument from the `asar`, so passing the script path as an argument doesn't work.

**Comment by jviotti** [comment]
@zcbenz I've tried running `fs.chmod()` on the script right before calling it with `execFile` however this function doesn't seems to be patched to work with `asar`, since I get `ENOTDIR` errors again.

**Comment by jviotti** [comment]
I suspect the issue should be fixed by setting execution permissions on the new path where the patched `execFile` extracts the original script here: https://github.com/atom/electron/blob/master/atom/common/lib/asar.coffee#L105.

I have no idea how to test my app with a modified Electron to give it a try though.

**Comment by zcbenz** [comment]
Yeah it is because the execution permission bit is not added when the file is copied out, I'll fix it on Electron's side.

**Comment by jviotti** [comment]
@zcbenz Cool, thank you very much!

**Comment by EragonJ** [comment]
I think I hit the same problem when using trying to pack my application as `asar`. I think the most confusing part is `ENOTDIR` error because for devs, what electron did in the background like what @jviotti said at https://github.com/atom/electron/issues/3512#issuecomment-158847339 is quite a black box.

I have been struggled for a while and had no idea about to fix the problem even if I did check the manual (https://github.com/atom/electron/blob/master/docs/tutorial/application-packaging.md#adding-unpacked-files-in-asar-archive) for several times. If possible, can @zcbenz add few lines (just few lines !) in that document about this magic when you are trying to give it a patch? It would be helpful for devs to know how to do further debugging and testing when hitting any bug related to this in the future :smiley: 

Thanks ++

**Comment by jviotti** [comment]
@EragonJ

I've been playing more with it and I'm in the process of sending a pull request for it, which gave some insight about how to test these kinds of issues:

- Follow the [build instructions](https://github.com/atom/electron/tree/master/docs/development) appropriate to your operating system.
- Build the debug target: `./script/build.py -c D`, so you can find an `electron` binary in `out/D/electron`.
- Package your app as an `asar` with `asar pack path/to/myapp app.asar` (I'm my case I created a dummy app that uses `execFile` to run a script inside the app directory).
- Run the `asar` package with the compiled electron: `./out/D/electron path/to/app.asar`.

Hope it helps!

**Comment by EragonJ** [comment]
@jviotti cool thanks !! I'll give it a try ! :+1:

**Comment by oleiba** [comment]
Hi, I tried using `execFile` in the context of executing a node script (such that is referenced from `npm start`):
```js
  var modulePath = path.join(__dirname, 'node_modules/my-module')
  var moduleEntry = require(path.join(modulePath, 'package.json')).main
  var scriptPath = path.join(modulePath, moduleEntry)
  var t = cp.execFile('node', [scriptPath])
```
Does not seem to work. Not in asar mode, this scripts succeeds and launches the server found at my-module, and in asar mode (packaged app) it doesn't.
Any help will be appreciated.

**Comment by alexis1990** [comment]
Do you find a solution ? I have this error : /bin/sh npm: command not found. It is my path : ./node_modules/.bin/electron .

**Comment by oleiba** [comment]
@alexis1990 I worked around this issue by using `fork` rather than `execFile('node', ...)`:
```js
 var t = cp.fork(modulePath, [], {stdio: ['ignore', 'ignore', process.stderr, 'ipc']})
```

**Comment by ayizhi** [comment]
I use pm2 api and solve this problem in this way
https://github.com/electron/electron/issues/9459#issuecomment-772317790

**Comment by mhkeller** [comment]
For anyone finding this, an alternate solution, if you don't mind them being unpackaged, is to put the executables in [`extraResources`](https://www.electron.build/configuration/contents.html#extraresources) in your electron-builder config. This will put them in your app's resources folder, not in the asar. You can get the path to the resources folder with `process.resourcesPath`.

**Comment by TiagoSilvaPereira** [comment]
> For anyone finding this, a possible alternative solution is to put the executables in [`extraResources`](https://www.electron.build/configuration/contents.html#extraresources) in your electron-builder config. This will put them in your app's resources folder, not in the asar. You can get the path to the resources folder with `process.resourcesPath`.
> 
> A possible downside is they're a little easier to find if they aren't in the asar but it's not like it's hard to unpackage an asar anyway...

Thanks, this exactly what I was looking for
