### ISSUE TITLE
Render Process crashes when delivering Notification with Image on Windows 10

### ISSUE THREAD

**Issue by kurisubrooks** [atom/electron#3516]
Triggering a notification with a custom icon crashes the render process (with no error, it just closes).

```
new Notification("test", 
    title: "Content-Image Notification",
    body: "Short message plus a custom content image",
    icon: path.join(__dirname, 'icon.png')
);
```

Tested on Windows 10, using Electron v0.35.0. Used the [notifications sample app](https://github.com/hokein/electron-sample-apps/tree/master/notifications).

**Comment by zcbenz** [comment]
It has been fixed by atom/brightray#175, the fix will be included in next release.
