### ISSUE TITLE
fs of browser process miss ReadStream class

### ISSUE THREAD

**Issue by ivankarpey** [atom/electron#3518]
I'm using node.js 5.0 and this code perfectly valid in node:
`var fs = require('fs');`
`var a = fs.ReadStream`

It will assign `fs.ReadStream` class to `a`, however if type this in electron's browser process `a` will be `undefined`. Becuase of this issue it's not possible to use `fs-extra` module with electron.

**Comment by zcbenz** [comment]
I'm unable to reproduce, which version of Electron are you using?

**Comment by ivankarpey** [comment]
was a problem caused by using browserify. Not electron fault.
