### ISSUE TITLE
Passing userAgent to loadUrl

### ISSUE THREAD

**Issue by bitwombat** [atom/electron#3523]
Almost identical to [this issue](https://github.com/atom/electron/issues/2908), but the solution isn't working for me with v0.34.2.

    mainWindow.loadUrl('file://' + __dirname + '/index.html', { userAgent: 'MyAgent/1.1'} );

Is this the way to do it so that always and everywhere in my app the code will see a userAgent of "MyAgent/1.1"?

Like the original, I have legacy code that's using the user agent to decide whether to show video using HTML5 or Flash (and I'm trying to tell it to send me HTML5).

I've got a js alert on the page to echo back my user agent, and the above code is not having an effect.

**Comment by zcbenz** [comment]
You should use `webContents.setUserAgent` if you want the user agent to persist between navigations.

**Comment by bitwombat** [comment]
That's not working.  Like this?

    mainWindow.loadUrl('file://' + __dirname + '/index.html');
      
    var userAgent = "Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25";

    mainWindow.webContents.setUserAgent(userAgent);

By "not working", I mean I run electron, bring up dev tools, and from the console, I inspect navigator.userAgent.  

My main.js attached.
[main.js.txt](https://github.com/atom/electron/files/45380/main.js.txt)

**Comment by bitwombat** [comment]
I'm creating a new issue for this since I'm thinking it might not get seen since it was closed.

**Comment by zcbenz** [comment]
`setUserAgent` has to be called before loading the URL.

**Comment by bitwombat** [comment]
Yep, tried that too.  I'm thinking this has to do with a NEW window being opened by a link...

**Comment by zcbenz** [comment]
without actual example no one can figure out what's wrong

**Comment by bitwombat** [comment]
Sure enough, inspecting navigator.userAgent shows it's correct in the main window, but doesn't get inherited by a new window generated with:

    <a href="../../../content/activity/01/activity.html" onclick="uf.content.openActivity(this.getAttribute('href')); return false;">Play</a>

Where "openActivity" does a:

    this.openActivity=function(n){
        return window.open(n,"_blank","menubar=no,location=no,toolbar=no,resizable=yes,scrollbars=yes,status=no,width=800,height=680")
    }

**Comment by zcbenz** [comment]
`webContents.setUserAgent` only sets user agent for current page, I have created #3602 for this.
