### ISSUE TITLE
docs about servers side support for auto updating a windows build

### ISSUE THREAD

**Issue by plrthink** [atom/electron#3525]
The doc about 'auto-updater' module says 

>The server-side setup is also different from OS X. You can read the documents of Squirrel.Windows to get more details.'

But I can't find that at Squirrel.Windows'  documents. 

Where I can find the info about that?

**Comment by enahum** [comment]
Does anyone have an example for a server side implementation for Squirrel.Windows? I cannot seem to find it, I managed to get the RELEASES file to establish that there is an update available, but thats all, no way to download nor install the update.

Any help here will be appreciated.

**Comment by dkfiresky** [comment]
I think they wanted you to read/visit [this link](https://github.com/squirrel/squirrel.windows)

**Comment by enahum** [comment]
@dkfiresky, already read it. couldn't find any info about a server side implementation for hosting the updates, as @plrthink says no docs in that link about how it works.

I found out that when checking for updates it makes a request to the `updater.setFeedURL` and appends a `RELEASES?id=APPNAME&localVersion=1.0.2&arch=amd64` at the end.

If there's no update the `update-not-available` event is fired, but when there is an update the download is not triggered as in Squirrel.Mac

**Comment by dkfiresky** [comment]
The `update` is only fired when you reply with `200 OK` and following json:
> ```js
> {
>    "url": "http://mycompany.com/myapp/releases/myrelease",
>    "name": "My Release Name",
>    "notes": "Theses are some release notes innit",
>    "pub_date": "2013-09-18T12:29:53+01:00",
>}
>```

Ref: https://github.com/Squirrel/Squirrel.Mac#update-json-format

I assume it's the same with Squirrel.Windows.

**Comment by plrthink** [comment]
@dkfiresky So, does it means the server side setup for auto update windows builds is same as ways for OS X except that we are supposed to add a config file as [this](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/hosting-releases-on-iis.md) says?

There is no pcs available to me right now, so I would try that tomorrow. But I think the doc is so misunderstanding if it's true...

**Comment by enahum** [comment]
I really don't think so, cause the only way it detects that theres is an update available is by downloading the RELEASES file.

My Squirrel.Mac implementation works flawless but this one I cannot seem to understand.

**Comment by enahum** [comment]
Ok folks, got it working!!!!

This is the way it works at least for me:

* use [grunt-electron-installer](https://github.com/atom/grunt-electron-installer) to generate the installer
* In your electron app set the updater URL with setFeedURL (it has to be a valid URL with SSL)

I have suppor for both mac & windows updates.. my URL is `https://mycompany.com/update/:app/:platform/:version` then in the server I have two routes for this

1. /update/:app/:platform/:version -> This one is for Mac updates and returns `204` or  `200` status code with the Squirrel.Mac json update format
2. /update/:app/:platform/:version/releases -> This one is for Windows updates and downloads the latest RELEASES file (be aware that the RELEASES file have to have only one line per version  one for the `full` and one for the `delta`)

After that the URL for the Mac downloads is set in the json update format in the url property, but the `Squirrel.Windows` way of doing it is by making a `GET` Request to the same URL as in the setFeedURL  of the updater meaning that is something like this /update/:app/:platform/:version/filename.nupkg.

Serve the file in that URL and you're set.

**Comment by plrthink** [comment]
@enahum nice! It would be great if you can show a example here or create a gist.

**Comment by plrthink** [comment]
@enahum A few questiones here: 

1.For windows builds, does electron (or Squirrel.Windows) automatically decide whether there is a update available based on the latest RELEASES file? Since unlike that on mac, which you can decide if there is a update or not by making different response, on windows it just download the latest RELEASES file. 

2.Does electron (or Squirrel.Windows) automatically request the update (the .nupkg) file or you should manually request that?

**Comment by enahum** [comment]
@plrthink 

1. For windows build, Squirrel.Windows will decide automatically if there is an update based on the RELEASES file it downloads, it will make a comparison with the RELEASES file that you already have with the installed app. That means that when checking for updates you have to send the RELEASES file to the electron app.

2. When the RELEASES file have a newer version than that installed by the user it will automatically request the newest .nupkg found in the RELEASES file (it could be the full version or the delta version).

Hope it helps

**Comment by plrthink** [comment]
@enahum Yeah, that make sense for me. An additional question. How to generate a delta .nupkg file?

**Comment by enahum** [comment]
the [grunt-electron-installer](https://github.com/atom/grunt-electron-installer) creates it all by itself if you don't delete your previous builds of the installer.

Cheers!!

**Comment by plrthink** [comment]
Oh, got it, thank for answering questions.

**Comment by plrthink** [comment]
@enahum @dkfiresky After digging Squirrel.Windows, I find this:

1. At this [line](https://github.com/Squirrel/Squirrel.Windows/blob/237cf945e492d1fcad678eb5522fe3565db4960e/src/Squirrel/UpdateManager.CheckForUpdates.cs#L51), Squirrel.Windows fetch a remote RELEASES file.

2. And this [file](https://github.com/Squirrel/Squirrel.Windows/blob/237cf945e492d1fcad678eb5522fe3565db4960e/src/Squirrel/UpdateManager.DownloadReleases.cs) is response for downloads .nupkg files.

**Comment by enahum** [comment]
I haven't been able to run the app with the squirrel events getting triggered, I even modified the rcedit project to include SquirrelAwareApp=1.

Anyone have had successfully made this work?

**Comment by plrthink** [comment]
@enahum Did you say it work?

**Comment by plrthink** [comment]
Could anyone of electron team update the docs about this section and explain how it works? May be it's easy for a windows developer to understand but it's not  for a js developer without any existing knowledge about windows development.

**Comment by zcbenz** [comment]
I suggest bringing this up in [issues list of Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows/issues), you should be able to get much better answers there, and the documents on auto-updater in Electron just links to there.

**Comment by evgenyzinoviev** [comment]
Hey guys, can I use auto-updater on windows without using grunt-electron-installer (I want to use Inno Setup for creating the installer).

**Comment by enahum** [comment]
@evgenyzinoviev I haven´t tried but it shouldn't be a Problem, and if you include the binaries from Squirrel.Windows you should have support for the auto-updater feature, Its only a wild guess. Give it a try and let us know if it works.

Cheers.

**Comment by paulcbetts** [comment]
> Could anyone of electron team update the docs about this section and explain how it works? May be it's easy for a windows developer to understand but it's not for a js developer without any existing knowledge about windows development.

Squirrel.Windows, I totally agree with this sentiment, it's been on my TODO list to make this _much_ easier / less confusing. Sorry that right now it's kind of Black Magic. 

> (I want to use Inno Setup for creating the installer)?

auto-updater specifically works with Squirrel.Windows, if you use Inno Setup you're on your own

**Comment by evgenyzinoviev** [comment]
okay then, I ported osx auto-updater to windows and it seems to work: https://github.com/evgenyzinoviev/electron-windows-updater

**Comment by plrthink** [comment]
@paulcbetts :+1:

**Comment by mzmousa** [comment]
@paulcbetts any news on updated docs?
