### ISSUE TITLE
Is electron have page cache settings like nwjs?

### ISSUE THREAD

**Issue by webpatch** [atom/electron#3526]
I have tested the same html page in electron and mwjs.  When i use the "location.reload()" js script to reload the page, it seens that nwjs have  page cache, it rerender page very fast ,but the electron looks like do a full reload without page cache ?

**Comment by webpatch** [comment]
the test page is just a normal static html file without any js or css.

**Comment by zcbenz** [comment]
Electron forces restarting renderer process for every navigation and reload, that's probably why the page seems to render slower.
