### ISSUE TITLE
Windows7, 8: Renderer process crashes when loading large images

### ISSUE THREAD

**Issue by kmsheng** [atom/electron#3527]
Hi there!
Consider the following codes and <a href="https://github.com/karmapa/ketaka-lite/tree/master/files/ctd-551/images">image files</a>, it happens when I click the button frequently.
Each image is around 4000 x 5000 in dimensions (~1000kb)

I tested the same code in latest chromium browser, it didn't crash.
So I don't know if this is related to electron or chromium's issue?
Did you guys experience this before ?
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title></title>
    <style type="text/css">
      #btn {
        position: absolute;
        width: 200px;
        height: 100px;
        top: 50%;
        left: 50%;
      }
    </style>
  </head>
  <body>
    <img id="img" width="1024" height=768"" alt="" />
    <button id="btn">button</button>
    <script>
        var img = document.getElementById('img');
        var btn = document.getElementById('btn');
        var index = 551;

        btn.onclick = function() {
        if (index >= 600) {
            index = 551;
        }
          img.src = 'images/CTD-' + (index++) + '.jpg';
        }
    </script>
  </body>
</html>
```

**Comment by bengotow** [comment]
We've gotten reports of this happening in N1: https://github.com/nylas/N1/issues/415. Definitely seems to be an Electron issue. I'll see if we can create a small test app to reproduce.

**Comment by zcbenz** [comment]
I'm unable to reproduce in 0.36.2 anymore, it seems that Chrome 47 has fixed this crash.
