### ISSUE TITLE
libchromium downloaded over http

### ISSUE THREAD

**Issue by gabriel** [atom/electron#3532]
https://github.com/atom/electron/blob/master/script/lib/config.py#L10

Should you change that from http to https?

**Comment by paulcbetts** [comment]
afaik it's intentionally HTTP because the latter causes problems for people in China (yes, I know this is Not Ideal)

**Comment by zcbenz** [comment]
Some python distributions do not recognize S3's certificate and refuses to download from the HTTPS url, and people kept opening issues because of it, using HTTP url solved the headache.

If you cares for security, you can just override the `LIBCHROMIUMCONTENT_MIRROR` environment variable.

**Comment by gabriel** [comment]
In this case maybe there should be a sha check to make sure it's not modified after download? 

Or maybe another solution might be to host it from github or another mirror?
