### ISSUE TITLE
Disable scrollbar on webview

### ISSUE THREAD

**Issue by dangan-ronpa** [atom/electron#3534]
Seems there's no way to disable scrollbar before dom-ready.
This makes the UI a little ugly.

Another thing will improve UX is page zoom settings before page loaded.

**Comment by zcbenz** [comment]
I suggest bringing this up in [Chromium's issues list](https://crbug.com), since we need Chromium to implement it before we can add the feature, and if Chromium team doesn't want to add it, there will be no way for us to work on it anyway.

**Comment by mnicic** [comment]
Register "dom-ready" event on a webview element
Then, implement function to insert a CSS styles, something like:
myWebView.insertCSS('html,body{ overflow: hidden !important; }');

**Comment by nana-yaw** [comment]
> myWebView.insertCSS('html,body{ overflow: hidden !important; }');

Solves it. In my case I just opened a **style** tag and pasted `html,body{ overflow: hidden !important; }` and it worked like a charm. Thanks @mnicic.
