### ISSUE TITLE
webContents.addWorkSpace() crashes the app

### ISSUE THREAD

**Issue by niedzielski** [atom/electron#3536]
### Versions
electron-prebuilt v0.34.0
Ubuntu 15.10 (high DPI screen)

### Issue
Calling webContents.addWorkSpace() crashes the app.

### Example
I just added one line to the electron-quick-start example:

    mainWindow = new BrowserWindow({width: 800, height: 600});
    mainWindow.webContents.addWorkSpace(__dirname); // Crashes after adding this line.

https://github.com/atom/electron-quick-start/compare/master...niedzielski:bug/add-work-space

**Comment by deepak1556** [comment]
Must be used after devtools creation.

```
    mainWindow.webContents.on('devtools-opened', function() {
        mainWindow.webContents.addWorkSpace(__dirname)
   })
```

@zcbenz should the api be made part of `mainWindow.devToolsWebContents` instead ?

**Comment by niedzielski** [comment]
@deepak1556, thank you. That works perfectly. devToolsWebContents was a point of confusion.
