### ISSUE TITLE
Set HTTP referer header with jQuery

### ISSUE THREAD

**Issue by suminb** [atom/electron#3539]
This might sound like a stupid question, but would it be possible to manually set the HTTP referer header via jQuery? What I'm trying to do is something like this:

    $.ajax({
      url: 'http://localhost:8080',
      headers: {
        'Referer': 'http://non-local-host'
      },
      data: {},
      type: 'POST',
      success: function(response) { console.log(response); }
    });

Then I get this error message:

    Refused to set unsafe header "Referer"

The origin of this error message is somewhere in the middle of the jQuery code.

    // Set headers
    for ( i in headers ) {
      xhr.setRequestHeader( i, headers[ i ] );
    }

I assumed this is happening because of the security policy of WebKit, so I tried to disable the `web-security` option but it did not make any difference.

    mainWindow = new BrowserWindow({
      width: 800, height: 600,
      'web-preferences': {'web-security': false}
    });

Any help would be greatly appreciated.

**Comment by zcbenz** [comment]
It is explicitly disallowed by [W3C standard](http://www.w3.org/TR/XMLHttpRequest/#dom-xmlhttprequest-setrequestheader), I suggest using Node's `http` module for this.
