### ISSUE TITLE
Event to listen when window is set to fullscreen

### ISSUE THREAD

**Issue by krolow** [atom/electron#3540]
Hey guys

Is there any listener for fullscreen event?

I'd like that my app react when user set it to fullscreen, basically i'd like to hide the main menu when it is set to fullscreen, there is a way for listen such a thing?

By the way i was unsure if i should ask it here, but i could not found any IRC/or/CHAT link in readme to guide users to ask questions there... if it exists perhaps it would be good to have it in readme!

**Comment by etiktin** [comment]
The fullscreen events are documented here:
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-enter-full-screen

Ways to interact with the community are mentioned here:
https://github.com/atom/electron/blob/master/README.md#community

**Comment by krolow** [comment]
thx @etiktin
