### ISSUE TITLE
"Hide others" not enabled on os x

### ISSUE THREAD

**Issue by bnolan** [atom/electron#3543]
On OS X, the hide others menu option is disabled, and so is the keyboard shortcut.

<img width="238" alt="screen shot 2015-11-22 at 1 17 29 pm" src="https://cloud.githubusercontent.com/assets/17499/11321873/6f9e9258-911b-11e5-8735-a37c3248d51e.png">

**Comment by zcbenz** [comment]
Fixed by #3549.
