### ISSUE TITLE
Add enterSplitView() and exitSplitView() methods

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#3545]
In El Capitan holding the green(plus) button enters the new split view mode. We have custom title bar in our application and we need `enterSplitView()` and `exitSplitView()` methods in order to enable the same functionality.

**Comment by bengotow** [comment]
Hey @astoilkov — I looked into this for our app. We do the same thing and users have noticed we don't support split view.

Unfortunately, entering split screen mode is interactive—if you press and hold on the green "fullscreen" dot in the window, you enter a mode where you can drag the window to the left and right to choose which side it should land on. There does not seem to be a public API in Mac OS X to invoke this interaction manually.

**Comment by astoilkov** [comment]
Thanks for the info @bengotow. I hope they introduce an API so we could make our custom title bars work. If you have any additional information regarding this can you contact me via email on: `antonio.stoilkov@gmail.com`.

Thanks!

**Comment by zcbenz** [comment]
I'm closing this since this is impossible without a public API, but I'm happy to reopen it once there is a new API in the new SDK.
