### ISSUE TITLE
Cannot read package.json bug with filesizeq

### ISSUE THREAD

**Issue by wildfiremedia** [atom/electron#3546]
Lost hours due to strange bug with different filesize, the files in "bug" folder which package.json with 1 byte less does work on any Electron version. Could you make it compatible or at least prompt for an error why it didn't read?

https://img42.com/4uEqE+

https://www.dropbox.com/s/gwfszwlbm2kcgxr/app.zip?dl=0

Mac OS X 11.10.x

**Comment by bengotow** [comment]
Hi @wildfiremedia — it looks like your package.json file in "bug" contains "pretty" quotes, which aren't valid in JSON:

![image](https://cloud.githubusercontent.com/assets/1037212/11329965/06a15eec-9158-11e5-93b5-6309cfbac101.png)

When I remove those it reads the file and runs fine.
