### ISSUE TITLE
How can I fetch the requests at start in a page?

### ISSUE THREAD

**Issue by huangruichang** [atom/electron#3551]
I am working at a network speed measuring tool with electron. But I can not find out which event can help me to fetch the requests when they start in a page. Please help :crying_cat_face:

**Comment by zcbenz** [comment]
We have some basic events like `did-get-response-details`:
http://electron.atom.io/docs/v0.35.0/api/web-contents/

For advanced things, you have to wait for #2115.

**Comment by huangruichang** [comment]
@zcbenz cool, thanks a lot. :+1:
