### ISSUE TITLE
While using `0.35.1` on `osx`, the window always display behind all the other apps

### ISSUE THREAD

**Issue by leftstick** [atom/electron#3553]
While download the newest version `0.35.1` of `electron-prebuilt`, i found my app always display behind all the other apps.

And cannot be brought to front.

Doesn't anyone knows what happened? The thing is when i rollback to `0.35.0`, everything is fine.

**Comment by bengotow** [comment]
Hey @leftstick — 0.35.1 added support for the "desktop" window type on Mac OS X in addition to Linux, which displays the window as the user's desktop background. Maybe you're creating a BrowserWindow with `type: desktop`? I can't reproduce the issue with the default "Welcome to Electron"  app.

**Comment by leftstick** [comment]
hi @bengotow , yes i am creating `BrowserWindow` with `type: desktop`, my options which passed into `BrowserWindow` is as following:

```
var startupOpts = {
    useContentSize: true,
    center: true,
    resizable: process.env.NODE_ENV === 'dev',
    alwaysOnTop: false,
    fullscreen: false,
    skipTaskbar: true,
    kiosk: false,
    title: '',
    icon: null,
    show: true,
    frame: true,
    disableAutoHideCursor: false,
    autoHideMenuBar: false,
    type: 'desktop',
    titleBarStyle: 'default'
};
```

BTW, the config options works perfect with `0.35.0`, i am wondering why?

**Comment by bengotow** [comment]
In 0.35.0, "desktop" was only a recognized option on Linux. Mac OS X support for that option was added in 0.35.1. So in 0.35.0, it was probably only creating the wrong behavior on Linux.

You can safely remove the desktop type and everything should be fine.

**Comment by leftstick** [comment]
Thanks very much!
But i still have no idea what `desktop` is suppose to do?

**Comment by bengotow** [comment]
Hi @leftstick — this is what the `desktop` option is for: https://github.com/atom/electron/issues/2899

**Comment by leftstick** [comment]
Got it, thanks very much
