### ISSUE TITLE
BrowserWindow doesn’t show an https page unless the ignore-certificate-errors Chromium cmd switch is used

### ISSUE THREAD

**Issue by davidsupan** [atom/electron#3555]
I'm working on a very simple Electron application to load up a secure website which asks for a certificate for login.
**mainWindow.loadURL(url);**
However, the Electron application window is blank unless I use the *ignore-certificate-errors* command line switch for Chromium, whereas it works perfectly fine in Chrome.
**app.commandLine.appendSwitch("ignore-certificate-errors");**
Is there a was to see why it doesn't do anything without the switch?

**Comment by deepak1556** [comment]
you can use `log-net-log` switch to get a trace of network events and load it up in `chrome://net-internals` to see whats' happening under the hood.

**Comment by zcbenz** [comment]
How does a website ask for a certificate for login? Is there an existing website can be used as example?

**Comment by mbilker** [comment]
startssl.com is an example. They give you a S/MIME certificate and the user uses that to authenticate to StartSSL.

**Comment by zcbenz** [comment]
Electron's support for client certificate is not complete for now, I'm merging this to #1956.

**Comment by davidsupan** [comment]
I run the website locally for testing purposes and it works fine in a standalone browser.
When I open the regular http version of the website in Electron, I can clearly see all the events and loading times for scripts in the Network tab of Dev Tools. The https version only asks for the certificate and then nothing happens, the window is blank and nothing is seen in the Network tab.

**Comment by deepak1556** [comment]
@davidsupan i get client cert auth error in chromium, i believe you have the client certificate installed in your system. You can use the `select-client-certificate` event on `app` to provide the right certificate as response in your case, by default we choose the first certificate from the cert store.

**Comment by davidsupan** [comment]
There is only 1 client certificate in the cert store, as reported by the select-client-certificate event. (list.length equals 1)
