### ISSUE TITLE
Ability to disable unresponsive dialog?

### ISSUE THREAD

**Issue by Gregg8** [atom/electron#3557]
We have an application with long-running processes which may not yield to the system in time to avoid the unresponsive js dialog.

I know we can chunk processes and all that, but we really want to disable that dialog or set the trigger time to a very large number.

There is a Chromium arg called `--disable-hang-monitor` which will do this but the page of supported switches...

https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md

...does not support it.

Would be grateful if this switch could be added to the list. 

Otherwise, is there any other way to avoid that dialog (apart from chunking)?

**Comment by zcbenz** [comment]
The unresponsive dialog doesn't show by default, if your app is based on Atom you can look into `atom-window.coffee`.

**Comment by Gregg8** [comment]
Thanks for the info :-)
