### ISSUE TITLE
Add more security related attributes to webview

### ISSUE THREAD

**Issue by lloeki** [atom/electron#3558]
Allowing images but not scripts is a significant security improvement when embedding apps in `webview` elements.

There is apparently a [code-level possibility of controlling this](https://github.com/atom/electron/blob/c2197d8a05cd3fe280d7542ba60d41dcd0b5cfc2/atom/browser/web_contents_preferences.cc#L159), but being exposed as a set of prefs, it currently applies only to `BrowserWindow` and is not exposed as an attribute of the `webview` element at all.

Proposals:

- make the `disablewebsecurity` able to handle non-truth values such as `script` and `display`

or

- add new tag(s) to selectively allow `display` and/or `run` of insecure resources

Dependency on https://github.com/lloeki/matterfront/pull/41

**Comment by zcbenz** [comment]
I'm merging this to #2749.
