### ISSUE TITLE
[OS X] Custom Sheets

### ISSUE THREAD

**Issue by usandfriends** [atom/electron#3560]
Hi, I would like to create a custom [sheet](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Sheets/Concepts/AboutSheets.html). Currently, I am using a small BrowserWindow as a makeshift sheet, but I was wondering if there is any support for custom sheets?

**Comment by zcbenz** [comment]
I'm merging this to #323.

**Comment by usandfriends** [comment]
@zcbenz Similar, just note that:
+ Native OS X sheets drop down from the application's top bar and cannot be repositioned or resized while dialogs can be spawned anywhere and can be moved to other desktops and resized at will.
+ Sheets do not have a top bar while dialogs do.
+ The window the sheet was spawned in becomes inaccessible until the sheet is dismissed (similar to a Javascript alert/prompt) while dialogs are spawned independent of any window.
