### ISSUE TITLE
Regression: calling dialog. showOpenDialog through remote, passing callback

### ISSUE THREAD

**Issue by bengotow** [atom/electron#3565]
Hey folks—in Electron `0.34.3`, it was possible to do this:

```
  showOpenDialog: (options, callback) ->
    dialog = remote.require('dialog')
    dialog.showOpenDialog(@getCurrentWindow(), options, callback)
```

However, in `0.35.1`, the open dialog appears and the `callback` is run, but user interaction with the BrowserWindow fails in really strange way after you're finished selecting files. You can type into the selected text input and scroll, but you can't click anything on the page. As far as I can tell, it's permanently borked.

On the other hand, using the synchronous version of showOpenDialog works just fine. This code does not exhibit the problem:

```
  showOpenDialog: (options, callback) ->
    dialog = remote.require('dialog')
    callback(dialog.showOpenDialog(@getCurrentWindow(), options))
```

I know that passing callbacks through `remote` is "bad", but I feel like something else may be the issue here?

**Comment by rprichard** [comment]
I'm also hitting this bug.  Here's a [standalone test case](https://gist.github.com/rprichard/76697d6c47a3b265e444).  (Instructions are in the Electron BrowserWindow.)  v0.35.0 is good; v0.35.1 is bad.  It appears that when `showOpenDialog` is invoked remotely with a callback, it never returns, and then `window.setInterval` callbacks stop firing.  Calling `showOpenDialog` from the main process instead works fine.

**Comment by rprichard** [comment]
I tried replacing the remote `Dialog.showOpenDialog` call with a call to an exported browser function, i.e.:
```
        require("remote").getGlobal("showOpenDialog")(undefined, function() {
            setText("DDD");
        });
```
Then, in the browser process:
```
global.showOpenDialog = require("dialog").showOpenDialog;
```
The problem still manifests.  *However*, if I instead define `global.showOpenDialog` like so, the problem is fixed:
```
global.showOpenDialog = function(title, cb) {
    require("dialog").showOpenDialog(title, cb);
}
```

**Comment by rprichard** [comment]
It's a problem with @bengotow's recent change:  https://github.com/atom/electron/commit/1022179a1ff78c9622538ec150517ffcedffb78c#diff-5f99379ee6d769b3577d79bb4388cae2R107.  It's missing a `typeof`.  I'll submit a PR.

**Comment by rprichard** [comment]
I submitted https://github.com/atom/electron/pull/3573.

**Comment by rprichard** [comment]
Also, it's possible for the `showOpenDialog` call to hang still, even with my fix.  There's no guarantee that the callback function that `callFunction` appends to the call arguments will actually be called, and if it isn't, then `event.returnValue` is never set.  e.g. extra arguments:

```
Dialog.showOpenDialog(null, {title: 'TEST'}, function() {}, "dummy");
```

It's not immediately obvious to me how to prevent this from happening.  Better argument validation somewhere, I'd guess.

**Comment by bengotow** [comment]
Oh wow — caused the regression myself... 😞 Thanks for triaging and submitting the fix @rprichard.
