### ISSUE TITLE
Electron 0.35.0+ built with Mac OS X 10.11 SDK, cannot autoupdate over http [!!]

### ISSUE THREAD

**Issue by bengotow** [atom/electron#3566]
Hey folks—was talking with @emellum about this today on the Atom slack channel and verified it with an N1 update this evening. The auto-updater module in Electron 0.35.1 fails to download updates from `http` URLs on Mac OS X. 

I think this is most likely because the latest releases have been built against the new Mac OS X 10.11 SDK, and Mac OS X is expecting it to have a Transport Security Policy in the info.plist file. I actually didn't know they'd done this on Mac OS X—I've only seen this error message when building against iOS 9. 

I'm looking to see if we can resolve this issue for N1 users by simply serving up an `https` url (we use S3), but it may pose a very serious problem for users who can't make that switch.

![screen shot 2015-11-23 at 11 06 45 pm](https://cloud.githubusercontent.com/assets/1037212/11360183/0259ece8-9237-11e5-83fc-2c9fe4467356.png)

**Comment by zcbenz** [comment]
Yeah it is caused by 10.11 SDK, I'll try to link Electron with 10.10 SDK in next release.

**Comment by bengotow** [comment]
Switching the update URL in the server response to `https` resolves this problem—I think it's only the Squirrel Helper that is being built against 10.11.

**Comment by zcbenz** [comment]
Electron 0.35.3 is now linked with OS X 10.10 SDK.
