### ISSUE TITLE
AngularJS: Showing weird behaviour _only_ in prebuilt Electron

### ISSUE THREAD

**Issue by maxrimue** [atom/electron#3569]
I wrote a little Angular app to play around with Angular Material a bit. I then wanted to use the `.html` + `.js` file inside an Electron app. 

However, as I noticed, Angular for some reason doesn't really work in Electron, but only in Electron. If I try the _exact_ same script (same link to dependencies, etc.) in Firefox, Chrome, or Safari, it works just as expected. I also posted the script online on StackOverflow, with getting an answer that the Angular Code was not containing any mistakes. 

If I, however, open the code in Electron (0.35.1 on OS X El Capitan), the script shows weird behaviour and finally 'crashes' (onclick events break). Down below, I have two videos showing the difference between how it is supposed to work (in Chrome 46) and how it doesn't in Electron:

(I wasn't able to create `.gif`s of `.mov`s without getting a new App Store card or sacrificing length, so I hope Google Drive is okay)
 
https://drive.google.com/file/d/0B3S33WrzEUwMV3ladTFkc1RIYWc (Chrome 46, working correctly)

https://drive.google.com/open?id=0B3S33WrzEUwMZnREdHJiUE0wV1k (Electron 0.35.1, not working correctly)

As I said, both Chrome and Electron run the exact same code, but the result is different. The Angular code also proved to be all right. Thanks.

**Comment by ozsay** [comment]
Can you provide the code so i reproduce the issue ?

**Comment by maxrimue** [comment]
Sure,
[this plunker](http://plnkr.co/edit/rGHAS3Qk69161m12l3Mb?p=info) contains the Angular and HTML code, the code for starting the Electron app is (`index.js`):
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');
var mainWindow = null;

app.on('window-all-closed', function() {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 700, height: 400, 'min-width': 700, 'min-height': 400});
  mainWindow.loadURL('file://' + __dirname + '/index.html');
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});
```
The plunker already contains all necessary dependencies (Angular, Angular Animate, Angular Aria, and Angular Material), so if you want to try the code with Electron, make sure to use a `package.json` like this (for letting npm install the dependencies):
```json
{
  "name": "someapp",
  "version": "1.0.0",
  "description": "",
  "main": "lib/index.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron-prebuilt": "0.x.x"
  },
  "dependencies": {
    "angular": "1.4.8",
    "angular-animate": "1.4.8",
    "angular-aria": "1.4.8",
    "angular-material": "0.11.x"
  }
}
```
Running `npm start` should do it.

**Comment by maxrimue** [comment]
I just noticed that for some reason, this problem only occurs with the prebuilt version of Electron. I used [electron-packager]() for building an `.app` (OS X), and inside this application, it works just fine. Only when I run the app with the prebuilt executable (as shown above in the `package.json`), this weird behaviour occurs.

**Comment by ozsay** [comment]
The dialog is closed fine for me.

electron prebuilt (0.35.1)
Win 7 64bit

**Comment by maxrimue** [comment]
I've just tried it again with the prebuilts of 0.35.0 and 0.34.4 again, both behave just as 0.35.1 did.

**Comment by ozsay** [comment]
On Ubuntu 15.10 it also works fine. I don't have a mac so I can't test it on OSX.

**Comment by maxrimue** [comment]
I've just tried it on another Mac, there it worked, too. So it seems like this is only a problem on my system, but I have still no idea why...

**Comment by zcbenz** [comment]
I suggest reporting this to https://github.com/mafintosh/electron-prebuilt since it is more like an issue there.
