### ISSUE TITLE
Clicking a notification when window is hidden using browserWindow.hide() will not show the window

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#3575]
On OS X, if you hide a window with Cmd+H, get a notification, and click it, the window will be shown. However, if you hide it using browserWindow.hide(), the app will be activated, but the window will not be shown. I think it should be consistent here and show the window in that case too.

-

Electron 0.35.0. OS X 10.11.1.

**Comment by bengotow** [comment]
On Mac OS X, applications can be hidden and windows can be hidden. In the first case (`Cmd-H`), the entire application is hidden, which isn't the same as hiding all of the windows of the application. Clicking the notification un-hides the application and brings it to the foreground (it should show your app in the menu bar), but doesn't do anything to the windows.

Mac OS X doesn't require that applications have any open windows, so it's totally up to you to listen for the app to be activated and show the window you want to ensure is visible if it's been hidden. I think in Mac OS X's `NSWindowController`, you can specify that your app should "Show on Activate", but it's an opt-in thing.

I think it's probably best for this to be implemented by listening for the `activate` event and showing the app's main window. Our app has several windows hidden most of the time, and we wouldn't want them to show automatically when it was brought to the foreground.

**Comment by zcbenz** [comment]
Closing this because we are just following OS X's default behavior, and thanks @bengotow for the explanation.

**Comment by sindresorhus** [comment]
Thanks for the explanation @bengotow. Makes sense.

I'm surprised there is no easy way to have a notification triggered by a window show the window. Right now I have to do this and proxy the notification event through to the main process and handle it there: https://github.com/sindresorhus/caprine/blob/8106f5060b259833111a6b7c69ed761a39f7408a/browser.js#L23-L36

@zcbenz Would you be open to adding a `notification-click` event to the browser window webContents?
