### ISSUE TITLE
Can't trigger Notification.onClick event

### ISSUE THREAD

**Issue by phamdaniel** [atom/electron#3576]
https://developer.mozilla.org/en-US/docs/Web/API/Notification/onclick
We can set the value from the browser window, but the event is never triggered. 
It is possible to work around this by decorating the Notification but it would be much easier to call the API.

```
Notification.onClick = function() {
    ipc.send('notification-click');
};
```

**Comment by zcbenz** [comment]
Please report following informations:

* The version of Electron
* Which OS you are using
* Some code snippet that can reproduce this

**Comment by phamdaniel** [comment]
My bad, it was being overridden.
