### ISSUE TITLE
Is there a way to ping IP address for electron?

### ISSUE THREAD

**Issue by ahgan84** [atom/electron#3582]
HI guys, currently developing a app which display a server's website using electron. I'm using the below line in my main process to show the server web page:

    mainWindow.loadUrl('http://192.168.1.20:2000')

Is there a way to know whether the ip address to the server is correct? I want to show an error message if the ip is wrong. Is there a ping function for electron?

For Winform C#, we have the below code to ping:

            System.Net.IPAddress address = System.Net.IPAddress.Parse("192.168.1.20"); 
            Ping pingSender = new Ping ();
            PingReply reply = pingSender.Send (address);
            if (reply.Status == IPStatus.Success)
            {
                Console.WriteLine("Correct IP!!!");
            }
            else 
            {
                label3.Text = "Cannot find server...";
            }

Is there a similar code in electron?
Currently if the server ip is wrong, it just show a blank white page.

**Comment by v12** [comment]
Have a look at [net-ping](https://www.npmjs.com/package/net-ping) package.

**Comment by etiktin** [comment]
You can create the window with `show` set to false and then listen to the `dom-ready` and `did-fail-load` events.
If you get the `did-fail-load` with a matching url, the server is not available and you should show the error message. If you get `dom-ready` the server is available and you should show the page. Details are in the webContens and BrowserWindow docs.

**Comment by zcbenz** [comment]
Closing since

**Comment by ahgan84** [comment]
@etiktin, I tried your method. When I want to simulate cannot connect to server which mean the ip is wrong, I get both "dom-ready" and "did-fail-load" message. How come?

**Comment by etiktin** [comment]
@ahgan84 aren't you getting `did-fail-load` first and only then `dom-ready`? If so, then on `did-fail-load`, you can remove the `dom-ready` listener so the window won't show. Show the error message, close the window and exit.

If that's not the case (for some reason you get the ready event before the fail event), then you can throw `did-get-response-details` into the mix and show the window only if you get `httpResponseCode` 200 for your url (if you need to support redirects, you'll need to update your url to the `newURL`).

**Comment by ahgan84** [comment]
I see. Then if I receive "did-fail-load", how do I do retry to load the webpage again?

**Comment by etiktin** [comment]
Just load the url again (e.g. `mainWindow.loadURL('http://example.com')`).

**Comment by ahgan84** [comment]
The is it that i have to do a for loop whereby i keep retry loading the page until the page is loaded?

**Comment by etiktin** [comment]
Don't loop. Just use a tries counter. Each time you try to load again, inc the tries. When tries get to your max tries and you get "did-fail-load", exit (show the error message only once you reach max tries).
