### ISSUE TITLE
autoUpdater.quitAndInstall() does not quit immediately

### ISSUE THREAD

**Issue by mariokostelac** [atom/electron#3583]
I have a code like:
```
autoUpdater.on('update-downloaded', notifyUserAboutUpdate);
```
and

```
function notifyUserAboutUpdate() {
  let buttons = ['Sure, get me a new version!', 'Nah, I\'m good, I can wait.'];
  let options = {
    type: 'question',
    message: 'Hey, new version of app is downloaded! Do you want to restart it now and get the newest version?',
    cancelId: -1,
    buttons,
  };

  dialog.showMessageBox(window, options, function(response) {
    if (response == 0) {
      autoUpdater.quitAndInstall();
    }
  });
}
```

Hitting "sure" button does not trigger immediate quit and reinstallation and that's kind of annoying. To clarify things more, `window` variable that is sent to dialog method is a window where I render the webapp. Am I attaching wrong window?
What would be possible cases why `quitAndInstall()` does not run immediately?
After I click "sure" and close the app itself, it restarts actually and updates itself.
Going with "no" button does not restart the app on app close.

**Comment by zcbenz** [comment]
`quitAndInstall` will close all windows first and then _try_ to quit, so it will not quit if there is any code in your code preventing that.

**Comment by seancolyer** [comment]
FYI in case anyone comes across this, try removing `window` from your dialog command:

```js
dialog.showMessageBox(options, function(response) {
```

It can block and cause this odd behavior.

**Comment by eladams** [comment]
@seancolyer thanks for the tip 👍 worked for me!

**Comment by salomvary** [comment]
If you want to keep the `window` option (because you want the dialog to be shown as a sheet on macOS) you will have to use this workaround:

```js
  dialog.showMessageBox(window, options, function(response) {
    if (response == 0) {
      setTimeout(() => autoUpdater.quitAndInstall(), 1);
    }
  });

**Comment by develar** [comment]
If you use electron-updater — https://github.com/electron-userland/electron-builder/issues/1604#issuecomment-306709572
