### ISSUE TITLE
better doc on auto-updater

### ISSUE THREAD

**Issue by aaronfrost** [atom/electron#3585]
I can see that it uses Squirrel.Mac, and I can read what the server needs to do. However, once the thing sees that there is an update available... where will it fetch the updated assets from? And what format do those assets need to be in?

Also, I have heard that you are re-vamping the auto-updater. I would love to see more doc on that.

**Comment by zcbenz** [comment]
I suggest bringing this up in [issues list of Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac), you should be able to get much better answers there, and the documents on auto-updater in Electron just links to there.
