### ISSUE TITLE
mac app store submission error

### ISSUE THREAD

**Issue by plrthink** [atom/electron#3591]
I am following the [Mac App Store Submission Guide](http://electron.atom.io/docs/latest/tutorial/mac-app-store-submission-guide/) to prepare my app to mac app store. Everything works great but after successfully uploading it, I received an email which tells me something wrong with uploaded bundle. And here's message:

> Invalid Signature - The nested app bundle Electron Framework at path MockingBot.app/Contents/Frameworks/Electron Framework.framework has following signing error(s): a sealed resource is missing or invalid . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

> Invalid Signature - The nested app bundle Squirrel at path MockingBot.app/Contents/Frameworks/Squirrel.framework has following signing error(s): a sealed resource is missing or invalid . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

> Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.

It seems like it fails to code signing, but I checked that with `pkgutil --check-signature` and the result says it has been signed.  

And I'm using `electron-v0.35.1-mas-x64` as my prebuilt.

**Comment by zcbenz** [comment]
That error means what you uploaded doesn't match the signature, it is very likely some data gets corrupted when you uploaded the bundle.

**Comment by plrthink** [comment]
Oh, after double checking that I'm actually using `electron-v0.35.1-darwin-x64` not `electron-v0.35.1-mas-x64` as pre-built bundle.

**Comment by imyuvii** [comment]
@plrthink Does it solve the issue ? I am facing the same

**Comment by plrthink** [comment]
@imyuvii Yeah, I was not using the mas version of electron so it was not validated by mac app store.

**Comment by azer** [comment]
I'm also facing this problem and haven't figured out a way to solve the problem. How do you choose mas build? 

I'm building using electron-packager and specified platform as `mas` but it did not work.

**Comment by imyuvii** [comment]
@plrthink did MAS build work ? I've tried it but application doesn't work after installing.

**Comment by imyuvii** [comment]
@azer 
`electron-packager` . '<your application name>' --platform=mas --arch=x64 --icon=icon/icon.icns --ignore=node_modules/* --out=/Users/imyuvii/nodeapps/number-game/build`

**Comment by WANGNEWMAN** [comment]
What Happen
