### ISSUE TITLE
Callback after menu item role property takes effect

### ISSUE THREAD

**Issue by kmsheng** [atom/electron#3592]
Hi, there !

I was wondering if there's a callback for role property.

The situation is a little awkward because I need to manually triggering selecting all text when my CodeMirror instance is focused and "Select All" menu item on application menu is clicked.
https://github.com/karmapa/ketaka-lite/blob/master/main/services/MenuConfig.js#L38

I tried adding click function on it but it doesn't work. Any help would be appreciated : |

**Comment by zcbenz** [comment]
No current there is no way to do that, but you can just call `webContents.selectAll()` method in the `click` handler, most `role`s have corresponding APIs.

**Comment by kmsheng** [comment]
Got it. Thanks
