### ISSUE TITLE
Com objects: MainProcess and RendererProcess not initialized in the same way

### ISSUE THREAD

**Issue by DerekDomino** [atom/electron#3593]
I'm loading a DLL with ref-ffi which itself interacts with Windows COM. It raises an error or not ("CoInitialize not called") depending on whether my script is run with electron-prebuilt in command line or from the Main process, Renderer process or node 4.2.1.

Here is a summary:
 * electron-prebuilt in command line: Error
 * Main process (my script is injected in background.js): No Error
 * Renderer process (script is injected in preload.js): Error
 * node v4.2.1: Error

After reading MSDN documentation it seems that CoInitialize (or CoInitializeEx) must be called for each each thread interacting with the COM library. 

I then guess that COM initialization is different in the above situations.

How can we call CoInitializeEx for the Renderer process?

**Comment by zcbenz** [comment]
Electron only initializes COM in main process after the `ready` event, if you want to initialize COM at the time you want, you have to write a native module to do it yourself.
