### ISSUE TITLE
minimum and maximum window size does not work

### ISSUE THREAD

**Issue by RX14** [atom/electron#3597]
Using electron 0.35.1 and arch linux with a tiling window manager, setting the `BrowserWindow` `minWidth`, `maxWidth`, `minHeight`, `maxHeight` properties seems to happen after the window is initialized, meaning they do not take effect.

See i3/i3#2086.

App code:
```js
const electron = require("electron");
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

var mainWindow = null;

app.on("ready", function() {
    mainWindow = new BrowserWindow({
        width: 1184,
        height: 804,
        minWidth: 1184,
        minHeight: 804,
        maxWidth: 1184,
        maxHeight: 804,

        useContentSize: true,
        center: true,
        resizable: false,
        fullscreen: false,
        frame: false,

        show: false
    });

    mainWindow.loadURL("file://" + __dirname + "/src/main.html");
    mainWindow.show();

    mainWindow.on("closed", function() {
        mainWindow = null;
    })
});
```

With this code I expected the window to float as per [here](https://github.com/i3/i3/blob/next/src/manage.c#L376-L379) in my window manager's source code, however it does not. `xprop` reports the minimum and maximum window sizes set.

**Comment by zcbenz** [comment]
On Linux, setting maximize/minimum size conflicts with the `resizable` option, you have to use only one of them. To make your window float, you may want to use the `type` option.

**Comment by RX14** [comment]
Which is the correct type for a window that wants to always float and not be resizable float yet is a "normal" desktop application?

There doesn't seem to be much docs on exactly the side effects for each winow type.

**Comment by zcbenz** [comment]
The `type` is mapped to `_NET_WM_WINDOW_TYPE`, you can find details at [freedesktop.org specifications](http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html), how the window actually looks like would depend on the implementation of window manager you use.
