### ISSUE TITLE
GlobalShortcut works with Ctrl+MediaKey but not just MediaKey

### ISSUE THREAD

**Issue by niedzielski** [atom/electron#3600]
### Versions
electron-prebuilt v0.35.1
Ubuntu 15.10 (high DPI screen)

### Issue
globalShortcut.register fails to bind just `MediaPlayPause`. The other media keys fail to bind too. `A` and `Ctrl+MediaPlayPause` both bind and function properly.

### Example
Something like this fails:
```
...
app.on('ready', function() {
  var globalShortcut = electron.globalShortcut;
  globalShortcut.register('MediaPlayPause', callback);
...
```

Full example here: https://github.com/atom/electron-quick-start/compare/master...niedzielski:bug/media-key-shortcut

**Comment by zcbenz** [comment]
That's because the desktop environment you use has already taken the control of media keys, you need to turn off related settings of the DE.
