### ISSUE TITLE
A window can be focused through it has been hidden on windows

### ISSUE THREAD

**Issue by YangjunZ** [atom/electron#3601]
I have found that a window can be focused through it has been hidden on windows.
This led to the previous window can not regain the focus automatically. 
Here are my codes:

```javascript
function initShortcut() {
    globalShortcut.register('alt + shift + x', function() {
        showHideSwitch();
    });
}

function showHideSwitch() {
    if (mainWin.isFocused() && mainWin.isVisible()) {
        // mainWin.emit('blur');
        mainWin.hide();
        //after that case, the mainWin is not visible, but it's focused.
    } else {
        mainWin.show();
        mainWin.webContents.send('focus-on-input');
    }
}
```
When I input 'alt+shift+x', the main window will show or hide. But when the mainWin  were hidden by shortcut, it will keep up the focus.

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by zcbenz** [comment]
On Windows a hidden window can also be focused, it is a bit weird though.

In your case I think the simplest fix is to check `isVisible` first:

```javascript
if (mainWin.isVisible() && mainWin.isFocused())
```
