### ISSUE TITLE
tray: svg or pdf image

### ISSUE THREAD

**Issue by jorangreef** [atom/electron#3605]
Is it possible to use an SVG or PDF as a tray icon on OS X?

**Comment by Desuvader** [comment]
Don't think so.
See https://github.com/atom/electron/blob/master/docs/api/native-image.md

**Comment by zcbenz** [comment]
It is possible since they can renderered in HTML and then captured as image anyway, but it would very difficult to get an efficient solution because SVG and PDF are document types under the hood.

I'm closing this as won't fix.
