### ISSUE TITLE
Kiosk functionality

### ISSUE THREAD

**Issue by superfunkminister** [atom/electron#3607]
I'm building a Kiosk application for use at public events where I don't want the user to be able to interact with the operating system. Things like properly hiding the menubar https://github.com/atom/electron/issues/1415 on a Mac, or overriding edge swiping on Windows tablets would be really useful. Is allowing Electron to be used in such a way on the roadmap at all?

**Comment by zcbenz** [comment]
There are kiosk APIs, though there are [a few issues reported](https://github.com/atom/electron/issues/1054).
