### ISSUE TITLE
Disable zooming (both pinch zoom and smart zoom [mac])

### ISSUE THREAD

**Issue by rerdos** [atom/electron#3609]
Does anyone have a working solution to disable all kinds of zooming in electron v0.35.0? (including pinch zoom and smart zoom (on mac))

**Comment by Kilhog** [comment]
In main.js : ```app.commandLine.appendSwitch('--enable-viewport-meta', 'true');```
and in index.html ```<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />```
😉

**Comment by carlosperate** [comment]
You can set a fixed zoom level: https://github.com/atom/electron/pull/2612
https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframesetzoomlevellimitsminimumlevel-maximumlevel

**Comment by rerdos** [comment]
I tried those, but they didn't work. I tried this one (from the entry point `index.js`):
`var webFrame = require('electron').webFrame;`
`webFrame.setZoomLevelLimits(1, 1);`
and I got this:
`Uncaught Exception: TypeError: Cannot read property 'setZoomLevelLimits' of undefined`.
When I run those lines from the console, it works and every form of zooming is disabled.
If I try it from anywhere else in the app I got: `Module not found: Error: Cannot resolve module 'electron'`.

Could anyone specify where should I put those lines?

**Comment by carlosperate** [comment]
You need to execute that from the renderer process.

**Comment by rerdos** [comment]
Works!
`require('web-frame').setZoomLevelLimits(1, 1);`
Executed from main.js (the one which is included in the .html file).

**Comment by bridiver** [comment]
I think the name of the method name is confusing and misleading because it doesn't actually control the zoom level limits, it controls the page scale limits. Zoom increases or decreases the size of elements on the page. Page scale changes the size of the viewport and doesn't distort the page layout like zoom can. `setDefaultPageScaleLimits` does indeed control the limits for pinching, but those are not the zoom limits. To control the zoom limits you have to call `zoomLimitsChanged`

**Comment by AlekzZz** [comment]
i could not find "setDefaultPageScaleLimits" nor "zoomLimitsChanged", where to set those? previous suggestion didn't work, i can still zoom in / out using cmd+(+/-)

**Comment by pronebird** [comment]
Still can zoom with hotkeys. What's up with that?

**Comment by fandy** [comment]
@pronebird I disabled hotkey zooming with `webFrame.setZoomLevelLimits(1, 1)`, but am unable to disable pinch zooming on trackpad. Is anyone working on a fix for this?

**Comment by Vamoss** [comment]
var app = require('electron')
    app.commandLine.appendSwitch('disable-pinch');

Solution found by mixing these two links:

1 - https://github.com/electron/electron/issues/8793#issuecomment-289791853

2 - https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

**Comment by jeffbcross** [comment]
As far as I can tell, `disable-pinch` is no longer a supported flag, at least on desktop

**Comment by dharamgoyal** [comment]
> ```
> var app = require('electron')
> app.commandLine.appendSwitch('disable-pinch');
> ```
> Solution found by mixing these two links:
> 
> 1 - [#8793 (comment)](https://github.com/electron/electron/issues/8793#issuecomment-289791853)
> 
> 2 - https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

This solution has fixed the issue for me.

**Comment by ozooner** [comment]
Can confirm, disable-pinch worked also for me on electron v2

**Comment by SuperKirik** [comment]
'disable-pinch' doesn't work anymore,

webFrame in render process:
`var webFrame = require('electron').webFrame
`

also doesn't work if you follow electron secure guideline (because webFrame couldn't be accessed):
```
    webPreferences: {
      preload: `${__dirname}/preload.js`,
      nodeIntegration: false,
      contextIsolation: true,
      }
```

Setting 'zoom settings' in the main process like this:
```
  const { webContents } = mainWindow;
  webContents.setZoomFactor(1);
  webContents.setVisualZoomLevelLimits(1, 1);
  webContents.setLayoutZoomLevelLimits(0, 0);
```
do not work for me as well.

**Comment by SuperKirik** [comment]
the only thing the helps is disabling concrete shortcuts like here in Render process
https://github.com/electron/electron/issues/8793#issuecomment-648307765

Or smth like this in Main process
```
app.on('browser-window-focus', () => {
  globalShortcut.register('CommandOrControl+=', () => {
     logger.debug('Shortcut Disabled');
  });
});
app.on('browser-window-blur', () => {
  globalShortcut.unregister('CommandOrControl+=');
});
```

**Comment by ozooner** [comment]
@SuperKirik Which electron version?
