### ISSUE TITLE
vsync control

### ISSUE THREAD

**Issue by joeblew99** [atom/electron#3611]
Use case:
I am using Electron in Kiosk mode, and using webGL. 
The UX has been designed so the user never has to scroll, as per best practices for a kiosk app. I bring this up, because it means that it opens up the opportunity to turn vsync off, so the the GPU can do work inbetween vertical scans of the monitor.

So, does electron allow the ability to toggle Vsync ?

also this is neat trick to test it
http://www.vsynctester.com/manual.html

**Comment by zcbenz** [comment]
No Electron doesn't provide such abilities, the closest thing is the `--disable-gpu-vsync` command line switch which is provided by Chromium.

I suggest bringing this up in [Chromium's issues list](https://crbug.com).
