### ISSUE TITLE
Misspelled string in source

### ISSUE THREAD

**Issue by lukewestby** [atom/electron#3613]
Hi all,

I noticed a misspelling here for the string `"rotaion"`:

https://github.com/atom/electron/blob/e5e4749eb3c592667922f87c1105981db9dd84f7/atom/browser/api/atom_api_screen.cc#L44

Not sure if it's causing bugs, but wanted to bring it up.

**Comment by etiktin** [comment]
Yep, it's a bug. According to [screen.md](https://github.com/atom/electron/blob/3a5160f79968998ef214eb1d81c00993b0737637/docs/api/screen.md#event-display-metrics-changed) it should be `"rotation"`.

Care to open a PR to fix it?

**Comment by lukewestby** [comment]
Surely! #3621
