### ISSUE TITLE
Cursor doesn't change to pointer in topbar

### ISSUE THREAD

**Issue by Kilhog** [atom/electron#3619]
When attempting to hover over the icons in the topbar the cursor doesn't change to a pointer as it should. Only with frameless window, with frame window It works well.
As you can see in the gif, the "hitbox" of the topbar still seem to exist.

![sans titre](https://cloud.githubusercontent.com/assets/4045682/11457772/d4e1ab1e-96b1-11e5-8c5d-39e09cbd4d5a.gif)
Electron 0.35.2 & OSX

**Comment by zcbenz** [comment]
I'm merging this to #3009.

**Comment by laura-chacon** [comment]
> When attempting to hover over the icons in the topbar the cursor doesn't change to a pointer as it should. Only with frameless window, with frame window It works well.
> As you can see in the gif, the "hitbox" of the topbar still seem to exist.
> 
> ![sans titre](https://cloud.githubusercontent.com/assets/4045682/11457772/d4e1ab1e-96b1-11e5-8c5d-39e09cbd4d5a.gif)
> Electron 0.35.2 & OSX

Me and @ancodeUDW experienced the same issue. 
There are some news about it? 
Thank you
