### ISSUE TITLE
32-bit Audio Decoding

### ISSUE THREAD

**Issue by bleib1dj** [atom/electron#3620]
Electron Version: 0.35.0+ (All Electron versions seem to be affected as this is an underlying Chromium bug)
Chromium Trackers:
* [Chromium Issue](https://code.google.com/p/chromium/issues/detail?id=557170&can=5&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified)
* [Chromium Resolution](https://codereview.chromium.org/1422113002)

This issue occurs when you are attempting to decode an audio file that has a 32-bit sample rate in an electron app. As the issue logged in Chromium points out this could be tested using http://wavesurfer-js.org/ with the files listed in the project (github doesn't support wav file upload, sorry).

**Comment by bleib1dj** [comment]
This issue is resolved with commit [ad33ab7a20ddede811d0562c45a267a1b06c1ed6](https://chromium.googlesource.com/chromium/src/+/ad33ab7a20ddede811d0562c45a267a1b06c1ed6) and I noticed #3610 requests a chromium update schedule. I don't know if jumping to v49 would be in the cards but while the team works towards a stable v49 release is there a way I could either build electron with the canary chrome build, or assist in getting the necessary components in place to support v49?

**Comment by paulcbetts** [comment]
@bleib1dj Jumping to Chromium v49 is going to be very difficult, you might have to wait, or handle audio decoding in your own node.js native module (or even in JS via compiling an Emscripten module) and convert it to a format that Chromium v45 can grok

**Comment by bleib1dj** [comment]
Alright cool, thanks for the heads up @paulcbetts.

**Comment by zcbenz** [comment]
For new features that available in test channels of Chrome, you have to wait until it becomes a stable release and later Electron updates to it. Updating the Chrome version in Electron requires a lot of work, so we only do it for stable releases.
