### ISSUE TITLE
Error “env: node: No such file or directory” with child_process.spawn in only .app (distribution file)

### ISSUE THREAD

**Issue by ledinhphuong** [atom/electron#3627]
I get an “env: node: No such file or directory” error when i try to run my node module in child process from main process:
```js
this._process = spawn(`path/to/node_modules/.bin/my_file`, args)
```
I tried with options = `{env: process.env}` for spawn but it still didn't work. Also, I tried to workaround with `asar = true/false`.

My environment:
>Mac OSX 10.11
>electron v0.35.0

**Comment by zcbenz** [comment]
Using `spawn` is the same with running `path/to/node_modules/.bin/my_file` in shell, I think it is because you don't have a global Node installed.

**Comment by ledinhphuong** [comment]
@zcbenz: That's mean I cannot use the nodejs packaged inside Electron, right?

**Comment by DavidWells** [comment]
It is recommended to use `exec` over `spawn`? I'm running into this same issue

Thanks! =)

**Comment by tonyyls** [comment]
I meet this issue as well,  any solutions?

**Comment by joshwcomeau** [comment]
Having this issue as well; when `env` is specified as an argument for `childProcess.spawn`, no command succeeds (even builtin ones like `which`).

More info in this SO question: https://stackoverflow.com/questions/50661717/childprocess-spawn-fails-when-env-is-specified

**Comment by mathieudutour** [comment]
The solution is to use `window.process.env` instead  of `process.env` because webpack will inject a stub for `process.env`.

So it would look like:

```js
spawn(`path/to/node_modules/.bin/my_file`, args, {
  env: {
    ...window.process.env, // contains PATH which is needed to find the commands
    MY_VAR: true
  }
})
```

**Comment by D4uS1** [comment]
I know its a little bit late, but in my case i used the [process.execPath](https://nodejs.org/api/process.html#process_process_execpath) attribute to tell the spawn method to take the electron node process. 

I passed the file to open as first argument and it worked.
I am new to electron and do not know if this is a good choice, but i think you have to do something like:

```
const child_process = require('child_process');

const child = child_process.spawn(process.execPath, ['path/to/node_modules/.bin/my_file', ...args], {
	env: {
		ELECTRON_RUN_AS_NODE: 1
	}
})
```

Please also note that if you use asar, you need to exclude binaries out of the asar package and target those excluded binaries.
Usually electron-builder (for instance) does this automaticly. If you want to use a binary that was excluded from the asar package, you can use the _getAppPath()_ method from electron and replace the _app.asar_ part with _app.asar.unpacked_. e.g:

```
const child_process = require('child_process');
const path = require("path");
const { app } = require("electron");

const pathToBinary =  path.join(app.getAppPath().replace('app.asar', 'app.asar.unpacked'),
      'path/to/node_modules/.bin/my_file')

const child = child_process.spawn(process.execPath, [pathToBinary, ...args], {
	env: {
		ELECTRON_RUN_AS_NODE: 1
	}
})
```
