### ISSUE TITLE
Calling a function in javascript from main process before closing the app.

### ISSUE THREAD

**Issue by ahgan84** [atom/electron#3629]
Hi guys, I have trouble calling a function in javascript from the main process. What I want to do is to check some variable first before the app close. I have the below code in my main process:

    app.on('ready', function(){
	var mainWindow = new BrowserWindow({
		width:680,
		height:705
	})

    mainWindow.loadUrl('http://192.168.1.20')
	
    mainWindow.on('closed', function() {
    mainWindow = null;
      });
    
    mainWindow.on('close', function() {
      console.log('I do not want to be closed');
        mainWindow.webContents.executeJavaScript("testing();");
    });

I want to run a testing() function in javascript before user close the button:

          testing = function(){
          // my checking function
      };

But I can't get the testing() function running, any idea how to solve?

**Comment by zcbenz** [comment]
Without full code I have to assume `testing` is a local function.

Also the [beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) event should work better for your purpose.

**Comment by ahgan84** [comment]
My testing() function is running on the server side javascript, which is the where my url goes. Not a local one. Any difference if it ia a server side or locally?

**Comment by zcbenz** [comment]
`executeJavaScript` executes the code in the web page.

**Comment by ahgan84** [comment]
I have found the solution by using window.onbeforeunload on the javascript of my webpage. Thanks!

**Comment by dontcry2013** [comment]
Just for anyone curious about how to do it to save some time.
## Open the index.js/jsx and add the following
```
window.onbeforeunload = () => {
  // Do housekeeping before leaving;
  localStorage.clear();
};
```
