### ISSUE TITLE
Prevent a Menu from closing + Trigger opening of a Menu

### ISSUE THREAD

**Issue by n457** [atom/electron#3637]
[ Electron 0.35.0 x64 Linux ]

Hi,

I have **2 questions** about **Electron native menus** and I can't find aswers neither in the doc, nor in the issues section of the project :

- Is there any way to **prevent a Menu from closing** ?

For example, when the user click on an **MenuItem**, it can be very useful in case of a **Menu composed of several MenuItem checkboxes** to prevent the Menu from closing : the user **doesn't have to open the menu again** to check another checkbox.

- Is there any way to **trigger the opening of a Menu** (in JS) ? (not as a context menu via Menu.popup())

Thanks for your time.

**Comment by bengotow** [comment]
Hi @n457 — I'm not sure about Linux, but on Mac OS X you can't select a menu item without the menu closing. It's just the way menus are implemented by the system. Similarly, there is no way to programmatically open a menu in the menu bar. You can open contextual menus, but not menus in the menu bar. On Mac OS X, apps that /really/ want to do this can achieve it using crazy Accessibility APIs, but it's very unusual.

So... no on both counts. Sorry!

**Comment by zcbenz** [comment]
On Linux we have two implementations for menu: one is for distributions with global application menu bar support, one is for traditional window menu bar. It is impossible to do both of your questions for the first one, so the answer is no.

**Comment by n457** [comment]
Ok !
