### ISSUE TITLE
Hardware acceleration doesn't work in Flash plugin

### ISSUE THREAD

**Issue by fredvb** [atom/electron#3639]
On Windows (don't know about other OS's) (Tried with many releases of Electron)

When loading a Flash based video player in Electron, it seems to consume more GPU and Memory in the gpu-process and the pappi process respectively compared to Chromium.

I've tried to compare the flags passed to the pappi and gpu-process in chromium in an attempt to make them the most alike possible. So I've came up with those commandLine switches:
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, 'plugins', 'pepflashplayer19.dll')); // Used the latest pepperflash player i could find.
app.commandLine.appendSwitch('ppapi-flash-version', '19.0.0.245');
app.commandLine.appendSwitch('ppapi-flash-args', 'enable_hw_video_decode=1');
Only the last switch was new for Electron (found it from how Chromium opens it's pappi process)

Just as a sake of comparison, when playing the video in fullscreen in Electron, the gpu-process consumes about 17-18% of my GPU, while on Chromium (and Chrome) the GPU seems to stay around 4%. 

On another note, the pappi process seems to not be able to clean it's memory as nicely as on Chromium, I can't really describe it, but it just seems to get better garbage collected in Chromium as the video plays. 

Regarding the renderer process and the pappi process, they seem to consume also more CPU than in Chromium.

All this using a simple hosted video play to which I win.loadURL to in Electron, and simply open the same URL in Chromium, for the sake of comparison. 

I've been using Process Explorer to find out the GPU usage of the applications.

This ticket is basically to see if anyone has encountered this difference and found a solution to this. Are there maybe other switches that could maybe make Electron consume less GPU ? Or is there a reason this is happening in Electron vs Chromium ?

In my Electron application, I'll have to play some videos for hours at the time and a good memory garbage collection and GPU usage sure would helps considering that it'll often run on Intel CPU+CPU chips. (in my case, 17% of is a breeze for my top of the line video card, but that same 17% would translate to a higher % on CPU+GPU chips.)

Any ideas would be appreciated. Feel free to ask for more details.

**Comment by fredvb** [comment]
After more investigation. If I disable Hardware Acceleration within the Flash Player Settings (by right-clicking on the Flash element and unchecking the option), the error doesn't appear. In this case, the hardware acceleration is disabled and the GPU/CPU usage of Electron is the same as described above. Thus I conclude that Flash hardware acceleration doesn't seem to work the way I've got it setup.
Am I missing some file or a flag that might enable hardware acceleration in Flash ?

**Comment by fredvb** [comment]
Probably related, if I go see a video on youtube that uses HTML5 video (dash, thus h264) I get this error message (while the video still plays, probably in software mode, and this is the HTML 5 Youtube player): 
ERROR:gpu_video_decode_accelerator.cc(280)] HW video decode not available for profile 12

So, I'm guessing this issue doesn't only affect Flash, but also any video decoding that attempts to access hardware acceleration.

**Comment by fredvb** [comment]
I don't seem to see this whole problem on 0.30.4 . The GPU is at around 4-5% (same as on Chromium) and CPU is also very low.

**Comment by zcbenz** [comment]
It is probably a bug of Chrome 45.

**Comment by fredvb** [comment]
"Hardware acceleration doesn't work in Flash plugin", it does the same error when viewing an HTML5 video on Youtube.

**Comment by fredvb** [comment]
I'll attempt at finding the latest version on which it works as expected.

**Comment by fredvb** [comment]
0.31.2 is the last version that seems to be good.
0.30.8 is good too.
0.32.0 is where it starts with the bug up to 0.35.2. (Thus Chrome 45 as you mentioned)

**Comment by fredvb** [comment]
If you need me to test this issue when you get a chance to upgrade the Chrome version and attempt at picking the right release of Chrome, I'll be happy to see what I can do to test it.

**Comment by zcbenz** [comment]
Can you try whether 0.36.2 works?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by fredvb** [comment]
It seems like it's working great on 0.36.2 and 0.36.3.
Thanks.
