### ISSUE TITLE
How to send data to an renderer and then get a return value?

### ISSUE THREAD

**Issue by ppoo24** [atom/electron#3642]
See there is only one way about communication with two Renderer Process: `webContents.send`, now i can use `webContents.send` to send data from Window A(in preload.js) to Window B, And then i tried to return something from B:
```js
// FILE: preload.js of Window A
var cts = require('remote').require('myapp').lib('window-manager').getWebContents('pusher'); //here is just getting the webContents of Window B
window.setInterval(function () {
	console.log('------[return value]', cts.send('doTest', { 't1': 'test send:' + Date.now() }, 132)); //here will always got `true`
}, 1000);

//HERE try to hold the response data
var ipc = require('electron').ipcRenderer;
ipc.on('test-back', function () {
	console.log('-----got response data', arguments);
});
```
```js
//FILE: Window B
<script>
var ipc = require('electron').ipcRenderer;
ipc.on('doTest', function (e) {
	console.log('-------[PusherWin]Got messages', arguments);
	e.sender.send('test-back', {'test': 'test'}, 'test back'); //Here will not take effect
});
</script>
```
you will see success while sending to B, but can not get response data from B.
So is a way to get `callback` from `webContents.send` ? or only way to use the main process as a proxy ?

**Comment by zcbenz** [comment]
In Window B, `e.sender.send` will send the message to the main process instead of Window A. You can setup a listener in the main process and the route the message to Window A.

**Comment by dublinus** [comment]
For some reason, when I do this, in "Window B", it seems I can only accept one argument in the `on` method:

    var ipc = require('ipc');
	ipc.on('imported-projects', function(projects) {
		for(var key in projects)
			addProject(projects[key]);
	});

I don't know why, but this works. Every reference I've seen online shows that the "message" (`projects` in my case) should be the second argument, and the first should be the event, but if I do it that way, the second argument is `null`. How do I get the event, in order to send an event back to the parent window?

**Comment by ppoo24** [comment]
@dublinus Why not use `var ipc = require('electron').ipcRenderer;`

**Comment by dublinus** [comment]
I always see "Cannot find module 'electron'" when I try that. I'm not sure if maybe my electron installation is causing this, but I don't think I did anything differently.

**Comment by evgenyzinoviev** [comment]
@dublinus try to update Electron version.
