### ISSUE TITLE
will-navigate e.preventDefault() does not work when called from devTools

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#3644]
Clicking `Cmd+R` under Mac when devTools is focused triggers opening a new tab in Chrome. This happens regardless of the fact I have `e.preventDefault()` in my `will-navigate` event which fires correctly. The main problem is that devTools no longer stops on breakpoints.

I have global handler for `Cmd+R` in the app which reloads the app which is not captured when devTools is focused which is causing me a lot of wasted time.

**Comment by zcbenz** [comment]
I don't actually understand what you are trying to do, can you provide an example?

**Comment by astoilkov** [comment]
Ok. This could be fixed in the newest electron. I will test the scenario with the latest version and get back to you:
  1. Subscribe to `will-navigate` event and call `e.preventDefault()`
  2. Launch the app and open `devTools`
  3. Hit `Cmd+R` when `devTools` is focused - this will cause opening new tab in chrome

We are using Electron version `0.31.2`.

**Comment by astoilkov** [comment]
Ok. This is fixed in the latest Electron release. Sorry for bothering.
