### ISSUE TITLE
Kiosk mode not working on linux

### ISSUE THREAD

**Issue by omnidan** [atom/electron#3646]
In [DWM](http://dwm.suckless.org/) the kiosk mode does not seem to work, it's even possible to open the devtools.

I just tested it and devtools as well as pressing the Alt key and exiting fullscreen mode **works** on xfce too when kiosk mode is on.

**Comment by zcbenz** [comment]
On Linux the kiosk mode is just an alias to fullscreen mode, most desktop environments doesn't provide support for kiosk mode, and you have to hack your operating system to achieve it [like this](http://thepcspy.com/read/building-a-kiosk-computer-ubuntu-1404-chrome/).
