### ISSUE TITLE
How can I bypass the "An attempt was made to bypass the security policy of the user agent" error?

### ISSUE THREAD

**Issue by OLmitch** [atom/electron#3651]
I'm sorry for posting a "how-to" question in the issue section, but I'm not sure who I should contact or how else I can figure out this issue. I'm also a beginner, so this may be a very dumb question.

We've been building an automated browser testing tool using Electron and the browserstack-webdriver, and the whole dang thing is pretty much done, as we built the Electron UI and the BrowserStack automated testing scripts separately (we tested BrowserStack scripts via the command line).

Alas, when we tried to combine Electron with our BrowserStack code, we ran into an error that says:

*Uncaught SecurityError: An attempt was made to bypass the security policy of the user agent.*

From what little information I have been able to find about this issue, it looks like registerUrlSchemeAsBypassingCSP is possibly a way to work around the CSP of Chromium, but unfortunately I am having no luck getting it to work.

This is the code I'm trying to use:

```
var electron = window && window.require('electron');
var webFrame = electron.webFrame;
webFrame.registerUrlSchemeAsBypassingCSP('http://hub.browserstack.com/wd/hub');

var driver = new webdriver.Builder().
  usingServer('http://hub.browserstack.com/wd/hub').
  withCapabilities(capabilities).
  build();
```

The SecurityError is thrown when the function .build() is run. Am I passing in the wrong "scheme" into the registerUrlSchemeAsBypassingCSP function? Or am I just totally on the wrong track thinking registerUrlSchemeAsBypassingCSP can get us around this issue?

I've also tried turning off webSecurity:

```
  var mainWindow = new BrowserWindow({
    width: 580,
    height: 700,
    show: true,
    "webPreferences":  {
        "webSecurity": false,
        "allowRunningInsecureContent": true,
        "allowDisplayingInsecureContent": true
    }
  });
```

But the SecurityError continues.

We've been singing the praises of what a joy Electron is to work with, and now I'm worried we've hit some limitation that will render all our work the past three weeks useless. Any information would be greatly appreciated. Thank you!

**Comment by OLmitch** [comment]
Doh...after more research I learned the "scheme" is what I typically think of as a "protocol".

So http, https, file, mailto, data, etc. are schemes. I think I already tried http as the scheme but it still gave the same error. I'll give it another try a few hours from now.

**Comment by zcbenz** [comment]
You might also want to see how [spectron](https://github.com/kevinsawicki/spectron) or [nightmarejs](http://www.nightmarejs.org) works.

Also `webFrame.registerUrlSchemeAsBypassingCSP` only works for current page, e.g. the page that uses `webdriver`, while as far as I know `webdriver` will load the page in a different window.

**Comment by OLmitch** [comment]
Thank you very much for the insight. I've looked through those programs for over an hour now, but unfortunately I am in over my head at the moment and haven't made a breakthrough.

Basically browserstack-webdriver is Selenium, except modified to enable remote testing with Browserstack. I am wondering, do you know if Electron *can possibly* work with this browserstack-webdriver package? Or is there a reason that Electron *definitely can not* work with browserstack-webdriver?

[This is the most basic example script that browserstack-webdriver provides](https://www.browserstack.com/automate/node#getting-started). It works immediately when we run it from the CLI, but fails with the *Uncaught SecurityError: An attempt was made to bypass the security policy of the user agent.* when we try and run it after clicking a button in the mainWindow of our Electron app.

Any additional insight or advice would be appreciated. Thanks again!

**Comment by zcbenz** [comment]
If `browserstack-webdriver` works with Node then it should work in Electron, I'm wondering whether it is doing something special when it found it ran under a browser-like environment.

You can probably try whether the same code would work in Node, Electron's main process, and Electron's renderer process.

**Comment by OLmitch** [comment]
Thank you @zcbenz! I ran the same code through ipc in the app.js (Electron's main process, I believe?), and the app is successfully communicating with Browserstack :)
