### ISSUE TITLE
`window.open()` does not respect width and height parameters

### ISSUE THREAD

**Issue by chanpory** [atom/electron#3652]
According to the `window.open` function documentation [here](https://github.com/atom/electron/blob/master/docs/api/window-open.md), I should be able to override inherited options by passing in a features string. This does not seem to work as expected.

For example, running `window.open("https://github.com", "", "width=800, height=800");` does not cause the size of the new window to be 800 x 800px. It still inherits the size of the parent window.

Any suggestions here?

**Comment by wearhere** [comment]
+1

**Comment by zcbenz** [comment]
Which version of Electron are you using?

**Comment by chanpory** [comment]
0.35

**Comment by chanpory** [comment]
@zcbenz @wearhere Here is a fork of `electron-quick-start` which demonstrates the unexpected `window.open()` behavior.

https://github.com/chanpory/electron-quick-start/tree/window-open

**Comment by wearhere** [comment]
I've located the cause: `when key not in child` [here](https://github.com/atom/electron/blob/52f1431bde557e083f74af368aed5c08b9ae76f1/atom/browser/lib/guest-window-manager.coffee#L8) expects _child_ to be an array, not an object:

```coffee
mergeOptions = (child, parent) ->
  for own key, value of parent when key not in child
    if typeof value is 'object'
      child[key] = mergeOptions {}, value
    else
      child[key] = value
  child

mergeOptionsFixed = (child, parent) ->
  for own key, value of parent when key not in Object.keys child
    if typeof value is 'object'
      child[key] = mergeOptions {}, value
    else
      child[key] = value
  child

console.log 'before', mergeOptions {width:200}, {width:100}     // prints "before Object {width: 100}"
console.log 'after', mergeOptionsFixed {width:200}, {width:100} // prints "after Object {width: 200}"
```
