### ISSUE TITLE
Got "bundle format is ambiguous" when signing the code

### ISSUE THREAD

**Issue by mecee** [atom/electron#3655]
I followed the [Mac App Store Submission Guide](https://github.com/atom/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md) to sign my code but got several errors:

```
sign/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework: bundle format is ambiguous (could be app or framework)
sign/Electron.app/Contents/Frameworks/Electron Framework.framework/: bundle format is ambiguous (could be app or framework)
sign/Electron.app: code object is not signed at all
```

The signing script is exactly the same as the one in the guide:

```shell
codesign --deep -fs "$APP_KEY" --entitlements child.plist "$FRAMEWORKS_PATH/Electron Framework.framework/Libraries/libnode.dylib"
codesign --deep -fs "$APP_KEY" --entitlements child.plist "$FRAMEWORKS_PATH/Electron Framework.framework/Electron Framework"
codesign --deep -fs "$APP_KEY" --entitlements child.plist "$FRAMEWORKS_PATH/Electron Framework.framework/"
codesign --deep -fs "$APP_KEY" --entitlements child.plist "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign --deep -fs "$APP_KEY" --entitlements child.plist "$FRAMEWORKS_PATH/$APP Helper EH.app/"
codesign --deep -fs "$APP_KEY" --entitlements child.plist "$FRAMEWORKS_PATH/$APP Helper NP.app/"
codesign  -fs "$APP_KEY" --entitlements parent.plist "$APP_PATH"

```

I did some searching and found out the errors are similar with #720. However the solution provided by @reggi didn't do the trick. 

My OS X version is 10.11, and I have tried Electron v0.35.2 and v0.34.2 (downloading from the [releases page](https://github.com/atom/electron/releases), electron-v0.35.2-mas-x64.zip and electron-v0.34.2-mas-x64.zip), both of which showed the same error.

**Comment by zcbenz** [comment]
The signing tool seems to behave differently on different versions of OS X, you can also try this script:
https://gist.github.com/jorangreef/27e708c67b7e6746a98a
