### ISSUE TITLE
remote.process.argv has an extra arg in osx when opening file with app from Finder

### ISSUE THREAD

**Issue by cldwalker** [atom/electron#3657]
When opening my Electron app in osx by opening it with a file from Finder, `remote.process.argv` has an additional arg e.g. `["/Users/me/code/repo/LightTable/builds/lighttable-0.8.0-alpha-mac/LightTable.app/Contents/MacOS/Electron" "-psn_0_12340164"]`. This additional arg appears to be [an apple event](http://stackoverflow.com/a/8542947). This additional arg makes process.argv unreliable/unusable for opening files from the commandline. Have you seen this before and is this expected behavior?

I'm seeing this for OSX 10.10.4 for Electron 0.31.1 and 0.34.5

**Comment by 25512345** [comment]
Are you want open electron app with a file?

**Comment by zcbenz** [comment]
This argument is appended by Finder and there is no way to tell Finder not to do it, usually people are just [removing the argument starts with `-psn`](https://github.com/search?q=%22-psn%22&type=Code&utf8=✓).

**Comment by cldwalker** [comment]
@zcbenz Good to know. Thanks!
