### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by alanhoff** [atom/electron#366]
Is there a way to cross/compile atom-shell for ARM based computers?

**Comment by surdu** [comment]
+1

**Comment by surdu** [comment]
I see node-webkit is already on this (nwjs/nw.js#193). 

Could't the forces be united in order to port all the required dependencies to arm ? If I understood correctly, both this and nw share the same core, and the porting problem lays mainly in the core part, right ?

**Comment by jonathanjibo** [comment]
There are so many applications for supporting ARM builds.
+1+1+1+1

**Comment by Qard** [comment]
:+1: I also want this.

**Comment by mib4fun** [comment]
+1 !

jean-vincent KASSI
+22503487790
http://www.viadeo.com/fr/profile/jean-vincent.kassi


On Tue, Apr 28, 2015 at 12:33 AM, Stephen Belanger <notifications@github.com

**Comment by DavidVorick** [comment]
+1

**Comment by ozooner** [comment]
+1

**Comment by paulcbetts** [comment]
Please stop :+1:ing if you have nothing else to contribute to the conversation.

**Comment by zcbenz** [comment]
Anyone interested in contributing to ARM build might start from this branch of libchromiumcontent: https://github.com/atom/libchromiumcontent/pull/138.
