### ISSUE TITLE
webview.src doesn't work before body.onload

### ISSUE THREAD

**Issue by mkscrg** [atom/electron#3667]
Minimal repro: https://gist.github.com/mkscrg/a8748a986c3040b58d65

This creates a `webview` but doesn't correctly set the `src` attribute:

```html
<body>
  <script>
var loadWebview = function() {
var webview = document.createElement('webview');
webview.id = 'splash';
webview.style.height = '100%';
webview.style.width = '100%';
webview.src = 'webview.html';
document.body.appendChild(webview);
};
loadWebview();
  </script>
</body>
```

Workarounds include:

- calling the function after full page load, e.g. `<body onload="loadWebview()">`
- including the `webview` tag (and `src` attribute) explicitly in HTML

**Comment by xywz** [comment]
`webview` doesn't have any of its attributes until `document.readyState == 'interactive'`. This means `src`, `preload`, `getURL`, etc. will all be `undefined`, and if set, their values will be overwritten.
