### ISSUE TITLE
On Windows, is it possible to prevent electron.exe from detaching?

### ISSUE THREAD

**Issue by eudoxia0** [atom/electron#3668]
I have a project that provides an interface to Electron through stdio-based IPC. The problem is, on Windows, the `electron.exe` runs in the background after printing some initial text.

I've tried `SET ELECTRON_ENABLE_LOGGING=YES`, which according to [this forum post][post] and [this file][file] should keep the process on the terminal listening for input, but it didn't work. So, my question is, is possible to keep the process running in the foreground?

Related issue for cross-referencing purposes: https://github.com/ceramic/ceramic/issues/25

For reference, I tested this on version 0.35.2 of Electron.

[post]: https://discuss.atom.io/t/foreground-option-does-nothing/16478
[file]: https://raw.githubusercontent.com/atom/atom/ae09d687a0c194b6adefb8eb9450c8d5689716d0/resources/win/atom.cmd

**Comment by paulcbetts** [comment]
No, this is the frustrating duality of Win32 app personalities - you can _either_ be a GUI app or a console app, not both. You need to wrap the process in an app that will wait until the PID exits

**Comment by eudoxia0** [comment]
Thanks for the quick reply. I'll try to find some way around this.
