### ISSUE TITLE
Remove the default crash reporting URL

### ISSUE THREAD

**Issue by benogle** [atom/electron#3673]
Currently, the crash report URL points to our atom crash report server, and people are using the default. IMO, what we should do is:

* Remove the [default](https://github.com/atom/electron/blob/4252c17db08694df4b0994aef0768c467054f448/atom/common/api/lib/crash-reporter.coffee#L23) URL
* Write docs on how to set up your own crash report server
  * @zcbenz is our server open source?
* When no default is specified, we could log a warning somewhere?

**Comment by paulcbetts** [comment]
I mean let's face it, when there's an Electron crash, I want @zcbenz to fix it anyways :P  :trolleybus: :trolleybus:

**Comment by benogle** [comment]
Lololololol. There's too many tho
