### ISSUE TITLE
What is the right way of calling node.js modules from inside iframe?

### ISSUE THREAD

**Issue by ValeryEliseev** [atom/electron#3675]
Question:
What is the right way of calling node.js modules from inside iframe?

The core of the problem:
In our big browser-oriented web-application we use "dhtmlx" javascript library, wich draws its own "windows" on the main page using iframe, thus imitating MDI interface. Every such a window is a separate html page, with its own purpose.
We are going to create an Electron-based application having more features than the browser-based one. We need to call node.js modules both from the main page (which is loaded in Electron) and from the pages that reside in several iframes located on the main page.
We can't use webview, because iframes are being created dynamically by a third-party library.
Simple call to "require" from the page loaded into iframe doesn't work.

Let's use a simple "default_app"-based example from Electron distribution to demonstrate the problem.

First we create a two-lines file "node-call.js" in "resources/default_app" folder:

os = require('os');
document.write(os.type());

Next we create another one-line file "iframe-content.html" in the same folder:

&lt;html&gt;&lt;script src='node-call.js'&gt;&lt;/script&gt;&lt;/html&gt;

Then we add 2 lines into "default_app/index.html" file just before the closing &lt;/body&gt; tag:

&lt;script src='node-call.js'&gt;&lt;/script&gt;
&lt;iframe src='iframe-content.html'&gt;&lt;iframe&gt;

Let's start Electron. First output of document.write works, so we see our OS type on the main page. The second output from inside iframe doesn't work. We see an error in console:

Uncaught ReferenceError: require is not defined

So, node.js is not available by default inside iframe. Unfortunately, we didn't find a way to activate it in the manual. If there is such a way, please, tell us.

One can suppose it was designed this way in sake of security. However, if we alter "node-call.js" by adding a "top" to "require"

os = top.require('os');

both calls work fine. Hence, either the reason is not a security concern, or developers didn't take into account that one could call modules through "top".

Anyway it is bad because either the thing that should work does not, or works one that should not.
This means that the possibility of the call through a "top" could be blocked in next releases. Or we do something wrong.
Please help us!

**Comment by zcbenz** [comment]
The node integration in iframe is removed as a part of #1044, you can find the technical reasons there.
