### ISSUE TITLE
process terminated when require zmq 

### ISSUE THREAD

**Issue by gtaranas** [atom/electron#3678]
I have read [Using native Node modules](http://electron.atom.io/docs/v0.31.0/tutorial/using-native-node-modules/) 

in my dev machine zmq module works fine, but when i m trying to run it (after building with electron-packager) in virtual machine (win 7, 64bit same as my dev machine) process terminated without errors.

**Comment by zcbenz** [comment]
I suggest posting this to zmq's issues list for a better idea, it is just impossible for us to debug every native module that doesn't work, and if it is a bug of Electron, we will fix it.
