### ISSUE TITLE
webview does not load without script tag

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron#3679]
Using a `<webview>` tag on Electron 0.35.2 without having a `<script>` tag in the parent HTML seems to cause the webview to never load the page.

### Does not load

This has no `<script>` tags and the webview never loads.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <webview src="http://yahoo.com" autosize="on" minwidth="500" minheight="500"></webview>
  </body>
</html>
```

<img width="801" alt="screen shot 2015-12-03 at 8 28 46 am" src="https://cloud.githubusercontent.com/assets/671378/11566570/e6312d84-9997-11e5-8e81-8c3daa351f9c.png">

### Loads

Same example above except an empty `<script>` tag in the `<head>` and the webview loads.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script>
    </script>
  </head>
  <body>
    <webview src="http://yahoo.com" autosize="on" minwidth="500" minheight="500"></webview>
  </body>
</html>
```

<img width="802" alt="screen shot 2015-12-03 at 8 29 20 am" src="https://cloud.githubusercontent.com/assets/671378/11566594/fda2048e-9997-11e5-8d3b-6194d5c021b0.png">

**Comment by xywz** [comment]
Duplicate of #1117.

**Comment by kevinsawicki** [comment]
Thanks so much @xywz, closing this out.
