### ISSUE TITLE
Electron distributable size increased with 12.7MB between v0.31.2 and v0.35.2

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#3681]
Electron size increased with 12.7MB between v0.31.2 and v0.35.2. I was wondering about the reason behind this decision? Electron is already quite big and it makes me sad to see its size increase so dramatically.

**Comment by zcbenz** [comment]
It is the result of Chrome 45 upgrade, Chrome is getting bigger everyday and we don't have a choice but to follow.

**Comment by astoilkov** [comment]
Do you have an idea about what might be the reason behind this dramatic increase in size in the Chrome 45 upgrade? Thanks.

**Comment by zcbenz** [comment]
It could be some shiny new feature, I have no idea. Also Electron keeps adding components from Chromium project, which can also affect binary sizes, like the pepper plugin support.

**Comment by bpasero** [comment]
One thing that would be cool eventually is to make pieces optional. E.g there is a pdf.dll with > 10 MB of size that you likely only need if you want printing. I

**Comment by erusev** [comment]
@bpasero Exactly, I wonder if there something that we could do to somehow promote this idea.

**Comment by erusev** [comment]
@zcbenz 

Could things like this pepper plugin support be implemented in a way that would allow developers excluding them from builds?

**Comment by carlosperate** [comment]
> One thing that would be cool eventually is to make pieces optional. E.g there is a pdf.dll with > 10 MB of size that you likely only need if you want printing. 

+1

**Comment by mib4fun** [comment]
@zcbenz is it possible to have things optionals ? 
So we can use only core electron for projects

**Comment by astoilkov** [comment]
I think this is becoming a discussion. @zcbenz Do you think you could reopen the issue and maybe discuss options on how this could be achieved?

**Comment by zcbenz** [comment]
Yeah it is possible to disable certain parts of Electron by adding flags to `gyp` files and compilation switches to source code files, but every flag added will double the work we need to do. Currently we need to make sure Electron works for 7 different platforms, after adding 2 flags, the number would become 28.

If anyone is willing to send a pull request to add a build flag to disable certain features, and keeps __maintaining__ it after each Chrome version update, I would be very happy to merge, but for now we just don't have enough resources for it.

**Comment by erusev** [comment]
@zcbenz Thanks for commenting on this, I appreciate it.
