### ISSUE TITLE
Retry loading a webpage when failed.

### ISSUE THREAD

**Issue by ahgan84** [atom/electron#3689]
Below is my code:

    var app = require('app');
    var ipc = require('ipc');
    var BrowserWindow = require('browser-window');
    var settings = require('./settings');

    var mainWindow = null;

    app.on('window-all-closed', function() {
      if (process.platform != 'darwin') {
        app.quit();
      }
    });

    app.on('ready', function(){
	    var mainWindow = new BrowserWindow({
		    fullscreen: true,
		    autoHideMenuBar: true
	    })
  
         mainWindow.loadUrl('file://' + __dirname + '/index.html') // FIRST WEBPAGE
	
        mainWindow.on('closed', function() {
        mainWindow = null;
        
      });

        ipc.on('redirect', function(){
            mainWindow.loadUrl('http://192.168.1.10/page2')  // SECOND WEBPAGE

            mainWindow.webContents.on("did-fail-load", function() {
                console.log("did-fail-load");

                mainWindow.loadUrl('file://' + __dirname + '/index.html');   
     // REDIRECT TO FIRST WEBPAGE AGAIN
            });

        });

I will first go into the first webpage, then after it received a command "redirect" from the javascript using ipc module, it will redirect to a second webpage. But I need to check whether or not the second webpage can be connected. If it cannot be connected (did-fail-load), it will go to the first webpage again. And the cycles goes on. 

I use the console.log("did-fail-load") to check whether or not it had failed to connect to the second page. But I found out that it had duplicated call. The first time it fail to connect to second webpage, there is one console.log("did-fail-load"), when it retry the second time, there is two console.log("did-fail-load") appear, and the 3rd time it retry, there is three console.log("did-fail-load") appear. Is it that it some how got duplicated calls on mainWindow?

**Comment by asherkin** [comment]
You're registering a new did-fail-load handler every time your redirect handler is called, so they keep piling up each time.

**Comment by ahgan84** [comment]
@asherkin, then what is the best way to do retry until the page is loaded? In my case, retry until the server is up.

**Comment by ahgan84** [comment]
@asherkin, then is it that i cannot always call my redirect function? Then instead of redirect to first page where eventually the redirect function will be called again, i retry load the second page over and over again?

**Comment by asherkin** [comment]
You just need to move the `did-fail-load` handler registration out of the `redirect` handler.

**Comment by ahgan84** [comment]
@asherkin, ok... I have tried your method by putting the did-fail-load out of the redirect handler. 

Yes! It really will do retry loading the second page if it did-fail-load until it can connected to the webpage.

But got one small problem is that the app sometimes will crash after 2 times of did-fail-load, sometimes after 10 times... I think it's random times. I don't know it is a concern or not. I'm using 'npm start' to start my app. The error log when it crashes is below:

     0 info it worked if it ends with ok
     1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
     1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
     1 verbose cli   'start' ]
     2 info using npm@2.11.3
     3 info using node@v0.12.7
     4 verbose run-script [ 'prestart', 'start', 'poststart' ]
     5 info prestart electron-packager-myq-io-amd@1.0.0
     6 info start electron-packager-myq-io-amd@1.0.0
     7 verbose unsafe-perm in lifecycle true
     8 info electron-packager-myq-io-amd@1.0.0 Failed to exec start script
     9 verbose stack Error: electron-packager-myq-io-amd@1.0.0 start: `electron .`
     9 verbose stack Exit status 3221225477
     9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
     9 verbose stack     at EventEmitter.emit (events.js:110:17)
     9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
     9 verbose stack     at ChildProcess.emit (events.js:110:17)
     9 verbose stack     at maybeClose (child_process.js:1015:16)
     9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
     10 verbose pkgid electron-packager-myq-io-amd@1.0.0
     11 verbose cwd C:\Work\Project 2015\electron-packager-myq-io-amd
     12 error Windows_NT 6.3.9600
     13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
     14 error node v0.12.7
     15 error npm  v2.11.3
     16 error code ELIFECYCLE
     17 error electron-packager-myq-io-amd@1.0.0 start: `electron .`
     17 error Exit status 3221225477
     18 error Failed at the electron-packager-myq-io-amd@1.0.0 start script 'electron .'.
     18 error This is most likely a problem with the electron-packager-myq-io-amd package,
     18 error not with npm itself.
     18 error Tell the author that this fails on your system:
     18 error     electron .
     18 error You can get their info via:
     18 error     npm owner ls electron-packager-myq-io-amd
     18 error There is likely additional logging output above.
     19 verbose exit [ 1, true ]

Below is the code after the modification:

    var app = require('app');
    var ipc = require('ipc');
    var BrowserWindow = require('browser-window');
    var settings = require('./settings');

    var mainWindow = null;

    app.on('window-all-closed', function() {
      if (process.platform != 'darwin') {
        app.quit();
      }
    });

    app.on('ready', function(){
        var mainWindow = new BrowserWindow({
            fullscreen: true,
            autoHideMenuBar: true
        })

     mainWindow.loadUrl('file://' + __dirname + '/index.html') // FIRST WEBPAGE
         mainWindow.on('closed', function() {
         mainWindow = null;

      });

     mainWindow.webContents.on("did-fail-load", function() {
         console.log("did-fail-load");
         mainWindow.loadUrl('file://' + __dirname + '/index.html');   
     // REDIRECT TO FIRST WEBPAGE AGAIN
     });

    ipc.on('redirect', function(){
        mainWindow.loadUrl('http://192.168.1.10/page2')  // SECOND WEBPAGE
    });

I have not tried the actual exe app after compiling using electon-packager. I'll try that.

**Comment by ahgan84** [comment]
@asherkin, the actual exe will crash too. How come crashes happen. Anything wrong with my app?

**Comment by asherkin** [comment]
Is your Electron version up-to-date? v0.35.3 fixed a crash that could occur when using loadURL inside `did-fail-load`.

**Comment by ahgan84** [comment]
Oh.. i notice that the latest version of electron only been released two days ago... then i think my electron version is an old one. I installed my version about a month ago. Let me check first, @asherkin.

**Comment by zcbenz** [comment]
Closing since it is likely an already fixed bug.
