### ISSUE TITLE
Animate browser window resizing.

### ISSUE THREAD

**Issue by pilwon** [atom/electron#369]
It would be great to add an option to `BrowserWindow.setContentSize(width, height)` to animate the browser window resizing:

    BrowserWindow.setContentSize(width, height, animate)
                            or
    BrowserWindow.setContentSize(width, height, {animate})

**Comment by flysonic10** [comment]
+1

**Comment by atdrago** [comment]
+1

**Comment by mondo989** [comment]
This would be great!

**Comment by yukine201** [comment]
+1

**Comment by petel** [comment]
+1

**Comment by evgenyzinoviev** [comment]
This is done for OS X, see #4112.

**Comment by zcbenz** [comment]
Only OS X  has native animate resizing, I think implementing this on OS X is enough to close this.

**Comment by my-lalex** [comment]
I made a quick hack for that:https://gist.github.com/my-lalex/f81352ad69fba206b84e59341fc469ed
I didn't tested it on other platform than macOS, but it should work...
