### ISSUE TITLE
No console output in windows git bash

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#3692]
Its very common for windows users to use git bash to get a decent command window.

It seems that running electron from it does not generate any output. I've read through #3056 and cannot see this raised anywhere. I've set ELECTRON_ENABLE_LOGGING and it makes the cmd window add logging but does not effect git bash.

![image](https://cloud.githubusercontent.com/assets/309321/11590780/9385699e-9a8a-11e5-8a67-15590879717c.png)

**Comment by paulcbetts** [comment]
What happens if you use `electron.exe --enable-logging`

**Comment by lukeapage** [comment]
i tried that - no effect. but also that doesn't appear documented - the
chrome flags page doesn't say you can use those  flags on the electron exe
- can you?

**Comment by zcbenz** [comment]
Can you try setting the `ELECTRON_NO_ATTACH_CONSOLE` env?

**Comment by lukeapage** [comment]
@zcbenz awesome that fixes the issue. Is this a bug or just something that needs documenting?

**Comment by zcbenz** [comment]
Electron attaches to the console automatically, it is mainly to make the default Window console happy and caused troubles for third party terminals.

Currently we have whitelisted cygwin from this, I'll add git bash too.

**Comment by lukeapage** [comment]
thankyou
