### ISSUE TITLE
Electron crash with webview and screen reader (VoiceOver, JAWS, and NVDA)

### ISSUE THREAD

**Issue by yohaia** [atom/electron#3696]
I've used Electron version 0.35.2 on windows 8.1 64 bit.

When i've activated JAWS on the application,
It seems that the accessibility tree is exposed well to the system, 
Screen reader were able to read it (I've tested JAWS).

But,
When I try to load webview with URL, 
When JAWS is still active, electron is immediately crashed.

**Comment by zcbenz** [comment]
Seems to be related to 4ce840d.

**Comment by zcbenz** [comment]
Fixed with #4009.

**Comment by yohaia** [comment]
Now the behavior is (version 0.36.2) it wont crash, but JAWS read "embed object" and not the webview content text, then just the action like "TAB", anything else is ignored.

**Comment by rameshc-clarion** [comment]
Kindly guide me JAWS works with Electron app or not ? 
I checked on linux with Screen reader of linux but any content in electron app was not readable by screen reader.
