### ISSUE TITLE
Require fails when using ChromeDriver and HTTP url

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron#3699]
Requires seems to fail (sometimes intermittently) when using ChromeDriver to launch an app that uses an HTTP URL. This only seems to be an issue with `http://` urls, `file://` urls do not exhibit this behavior.

To reproduce:

- Clone https://gist.github.com/kevinsawicki/a7f87097a8edcdfb43b7
- Run `npm install`
- Run `chromedriver --url-base=wd/hub --port=9515`
- Run `./run.sh` to see it launch normally
- Run `./test.sh` to see if fail to launch when run via ChromeDriver

The failure looks like:

<img width="641" alt="screen shot 2015-12-04 at 2 15 53 pm" src="https://cloud.githubusercontent.com/assets/671378/11602756/8ef2d860-9a91-11e5-919a-cfd43e161681.png">

The sample project uses `webdriverio` to launch the app.

The `index.html` is really simple and just does a `require` after the document is ready.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="text/javascript">
      function requireElectron() {
        try {
          require('electron')
          document.write('require(\'electron\') succeeded')
        } catch (error) {
          document.write('require(\'electron\') failed')
          document.write('<pre>' + error.stack + '</pre>')
        }
      }
    </script>
  </head>
  <body onload="requireElectron()">
  </body>
</html>
```

/cc @mkscrg

**Comment by zcbenz** [comment]
After some debugging I think I have found the cause. In Electron the asar archive objects are destroyed when `unload` event is fired, somehow the `unload` event is fired before the page is loading and destroyed the the asar archive object that includes all built-in modules.

**Comment by justintaft** [comment]
+1 please fix

**Comment by justintaft** [comment]
Hm, did some more debugging. I can confirm what zcbenz is saying.

```Destroy``` in atom_api_asar.cc is being called, which deconstructs the archive.
Later on when require is called ,```Stat`` in atom_api_asar.cc is called. Since the  ```archive_``` address is now null (0x00), Stat returns false.

I added some LOG statements to electron's source code to find this out.

The below is a big cryptic, sorry..
```
 []67788:1230/103843:ERROR:atom_api_asar.cc(55)] atom_api_asar STAT archive renderer/lib/web-view/web-view.js 0x7fa088cd5150 0x7fa088ccffe0
 []67788:1230/103843:ERROR:archive.cc(203)] Statting THIS PATH, FD 0x7fa088ccffe0 renderer/lib/web-view/web-view.js , 31
 []67788:1230/103843:ERROR:atom_api_asar.cc(55)] atom_api_asar STAT archive  0x7fa088cd5150 0x7fa088ccffe0
*[]67788:1230/103843:ERROR:archive.cc(203)] Statting THIS PATH, FD 0x7fa088ccffe0  , 31
*[]67788:1230/103843:ERROR:atom_api_asar.cc(105)] atom_api_asar DESTROYING ARCHIVE0x7fa088cd5150 0x7fa088ccffe0
*[]67788:1230/103843:ERROR:archive.cc(133)] Archive is deconstructing! THIS FD0x7fa088ccffe0 31
*[]67780:1230/103844:INFO:CONSOLE(21081)] "Got to require", source: file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js (21081)
 []67780:1230/103844:INFO:CONSOLE(21082)] "1451500724137", source: file:///Users/justintaft/programming/LightTable/deploy/core/node_modules/lighttable/bootstrap.js (21082)
*[]67788:1230/103844:ERROR:atom_api_asar.cc(55)] atom_api_asar STAT archive common/api/lib 0x7fa088cd5150 0x0
*[]67788:1230/103844:ERROR:atom_api_asar.cc(55)] atom_api_asar STAT archive renderer/api/lib 0x7fa088cd5150 0x0
*[]67788:1230/103844:ERROR:atom_api_asar.cc(55)] atom_api_asar STAT archive renderer/api/lib/exports 0x7fa088cd5150 0x0
 []67780:1230/103844:INFO:CONSOLE(338)] "Uncaught Error: Cannot find module 'clipboard'", source: module.js (338)
 []67780:1230/103844:INFO:CONSOLE(36)] "TypeError: Cannot read property 'init' of undefined", source: file:///Users/justintaft/programming/LightTable/deploy/core/LightTable.html?id=1 (36)
 []67780:1230/103844:INFO:CONSOLE(37)] "TypeError: Cannot read property 'init' of undefined
     at HTMLScriptElement.script.onload (file:///Users/justintaft/programming/LightTable/deploy/core/LightTable.html?id=1:34:28)", source: file:///Users/justintaft/programming/LightTable/deploy/core/LightTable.html?id=1 (37)
```
