### ISSUE TITLE
"/chromium" appended to appData and userData directories

### ISSUE THREAD

**Issue by johnmuhl** [atom/electron#3709]
- Electron 0.35.0-4
- Ubuntu 15.10

`app.getPath('appData')` and `app.getPath('userData')` have `/chromium` appended. Electron versions < 0.35 do not have this issue.

Output below is from the electron-quick-start app with

``` javascript
console.log(process.versions.electron)
console.log(process.env.XDG_CONFIG_HOME)
console.log(app.getPath('appData'))
console.log(app.getPath('userData'))
```

added to `main.js`

```
0.35.4
undefined
/home/jm/.config/chromium
/home/jm/.config/chromium/Electron
```

```
0.34.5
undefined
/home/jm/.config
/home/jm/.config/Electron
```

**Comment by paulcbetts** [comment]
This is pretty bad if we're moving the userData folder and losing settings

**Comment by bpasero** [comment]
We also hit this but for us the fix is not included in 0.35.5 and this would force us to jump to 0.36 with Chrome and node.js updates.

Is there any way we can fix this path in our code or is appPath set too early to adjust?

**Comment by bpasero** [comment]
@zcbenz ping

**Comment by zcbenz** [comment]
@bpasero I think the only way to fix this is to cherry pick the commit, I'll publish a 0.35.6 release for this later.

**Comment by bpasero** [comment]
:+1: thanks

**Comment by bpasero** [comment]
@zcbenz does https://github.com/atom/electron/pull/4052 impact the 0.35.6 release and how?

**Comment by zcbenz** [comment]
@bpasero #4052 doesn't have actual impacts, it is for preventing future bugs.

**Comment by bpasero** [comment]
Ok great
