### ISSUE TITLE
Unexpected behaviour of `textarea`

### ISSUE THREAD

**Issue by gordomium** [atom/electron#3710]
- OSX 10.11.1
- Electron 0.34.5

Auto select blanks at current line in `textarea` after closing menubar. Chrome has no such behaviour.

![bug](https://cloud.githubusercontent.com/assets/4279066/11618074/334131b4-9cd1-11e5-9083-fe3cdde74d23.gif)

**Comment by zcbenz** [comment]
This is caused by how context menu is implemented in Electron (by sending sync messages from renderer process), I'm merging this to #3210.
