### ISSUE TITLE
Illegal layout on Ubuntu

### ISSUE THREAD

**Issue by gordomium** [atom/electron#3713]
- Ubuntu 14.04.3
- Electron 0.35.4

Layout breaks after lost focus on the window.

![bug](https://cloud.githubusercontent.com/assets/4279066/11624229/55afa1c2-9d0d-11e5-9963-51fc0986c3c5.gif)

**Comment by zcbenz** [comment]
Chromium on Linux doesn't work well with certain virtual machines, and unfortunately Electron inherited this bug.

I'm closing this as won't fix.
