### ISSUE TITLE
Support HTTP/2.0 in webview

### ISSUE THREAD

**Issue by diracdeltas** [atom/electron#3720]
Loading https://http2.akamai.com/ in an Electron webview indicates that it doesn't support HTTP/2.0 :(. I confirmed using Wireshark that the TLS ClientHello sent by Electron doesn't contain the ALPN extension at all.

HTTP/2.0 has large performance improvements and is widely supported in modern browsers (http://caniuse.com/http2).

Electron Version: 0.35.1 
OS: OSX 10.11

**Comment by paulcbetts** [comment]
Looks like this is broken erry'where, even in Chrome 47 - probably need to fix something in Brightray to get it working

**Comment by diracdeltas** [comment]
> Looks like this is broken erry'where, even in Chrome 47 - probably need to fix something in Brightray to get it working

you mean Electron with Chrome 47? HTTP/2 works fine in Chrome 47 itself.

**Comment by paulcbetts** [comment]
@diracdeltas Yeah, I have a locally built copy of #3714
