### ISSUE TITLE
webview 'did-get-redirect-request' not firing for <meta> redirects

### ISSUE THREAD

**Issue by diracdeltas** [atom/electron#3723]
I expected 'did-get-redirect-request' to fire for `<meta>` redirects (https://en.wikipedia.org/wiki/Meta_refresh) but it didn't. Test case: https://zyan.scripts.mit.edu.

Electron Version: 0.35.1 
OS: OSX 10.11

**Comment by xywz** [comment]
`'did-get-redirect-request'` is only for when a redirect is received while requesting a resource. `'will-navigate'` is for when a user or the page wants to start navigation.

**Comment by diracdeltas** [comment]
I guess that also makes sense. It turns out that `load-commit` is good enough for my use case. Closing.
