### ISSUE TITLE
Renewing OS X codesign certificates

### ISSUE THREAD

**Issue by Rokt33r** [atom/electron#3728]
I noticed I'd been signing my electron app with an **old iOS** certificates which will be expired soon.
To fix it, I created a new certificates again. But I got error like below when I trying to update my app.

```
[Error: Code signature at URL file:///Users/dickchoi/Library/Application%20Support/com.maisin.boost.ShipIt/update.jc5WYHU/Boost.app/ did not pass validation: code failed to satisfy specified code requirement(s)]
```

What should I do?

**Comment by zcbenz** [comment]
I suggest asking about this in https://github.com/Squirrel/Squirrel.Mac/issues, the developers there should be able to give you much better answers.

**Comment by jamesopti** [comment]
@Rokt33r - Did you ever find a solution to this?

The same thing is happening to me.

Any help would be awesome!
