### ISSUE TITLE
Dialogs are not centered in dwm

### ISSUE THREAD

**Issue by omnidan** [atom/electron#3730]
In gnome, the dialog windows are centered, in [dwm](http://dwm.suckless.org/) they are not.

`zenity` and other dialog windows are centered in both, dwm and gnome. So there must be something electron dialogs do differently.

**Comment by zcbenz** [comment]
Are the dialogs in Chromium browser centered?

**Comment by omnidan** [comment]
@zcbenz if you mean the javascript `alert()` box, yes it is, but it uses the special chrome alert, not the system alert:

![https://i.imgur.com/R4LcBZ2.png](https://i.imgur.com/R4LcBZ2.png)

**Comment by zcbenz** [comment]
@omnidan How about other dialogs like the save file dialog?

**Comment by omnidan** [comment]
@zcbenz The save file dialog is not centered either.

**Comment by zcbenz** [comment]
It is a bug of Chromium then, I suggest reporting this to either [Chromium's issues list](https://crbug.com) or the dwm team, what we can do in Electron is to wait for either project to fix the problem.

**Comment by zcbenz** [comment]
Closing since this is either a bug of Chromium or dwm, and there is nothing we can do in Electron.
