### ISSUE TITLE
hashchange events are not captured as history entries

### ISSUE THREAD

**Issue by brian-mann** [atom/electron#3737]
While researching an attempted work-around for #3734 I realized that Electron does not capture `hashchange` events from the renderer. A hashchange event will always cause a browser to insert a new record into its history entries.

I checked through the source and found that both the `will-navigate` and `navigation-entry-commited` events are not fired on any kind of `hashchange`.

Because this is incorrect, the following methods are faulty:

- `webContents.canGoBack()`
- `webContents.canGoForward()`
- `webContents.canGoToOffset(offset)`
- `webContents.goBack()`
- `webContents.goForward()`
- `webContents.goToIndex(index)`
- `webContents.goToOffset(offset)`

**Comment by svileng** [comment]
I'm experiencing the same issue — I have an Angular web app that uses hash-based routing, and `will-navigate` does not fire on page changes.

**Comment by zcbenz** [comment]
I believe #3875 has fixed this.

For capturing in-page navigation event, a `did-navigate-in-page` event has been added and will be included in next release.

**Comment by blackChef** [comment]
@zcbenz  `webContents.goBack()` does not trigger `did-navigate-in-page`.  When you go back from `a.com/#foo` to `a.com/#bar`, you can see `webContents.getActiveIndex()` changes. but `webContents.getURL()` remains same.
