### ISSUE TITLE
BUG, when using q's defer.reject from the remote module

### ISSUE THREAD

**Issue by ppoo24** [atom/electron#3740]
Leave these codes in a browser window:
~~~js
var q = require('remote').require('q');
q().then(function () {
	var defer = q.defer();
	setTimeout(function () {
		defer.reject(new Error('Test throw error'));
	}, 100);
	return defer.promise;
})
.catch(function (e) { console.dir(e); });
~~~
and we will catch this Error object (see it in DevTool):
![image](https://cloud.githubusercontent.com/assets/1631659/11676252/b1aecb88-9e6b-11e5-9e48-c84f94d28b9e.png)
but what we want should be like this:
![image](https://cloud.githubusercontent.com/assets/1631659/11676376/b2b6ef0a-9e6c-11e5-8a37-f10692b97b18.png)
so i tried to dig in, put a breakpoint at this line `defer.reject(new Error('Test throw error'));`, found electron is using a wrap for remote calls, and it will run to below:
![image](https://cloud.githubusercontent.com/assets/1631659/11676553/3f4f9632-9e6e-11e5-9241-0e7f907cb9a2.png)
as Error object, the for-in statement can not get its property.
May solve this ? tks

**Comment by zcbenz** [comment]
The `remote` modules do not work well with Promise types, it is not designed for general PRC purpose anyway. The only solution is to use the ES6 `Promise` class, which is supported by `remote`.

**Comment by ppoo24** [comment]
tks!
