### ISSUE TITLE
Build fails with clang library error

### ISSUE THREAD

**Issue by capouch** [atom/electron#3741]
I regularly build Electron from the github sources.

Just now, after syncing and running the bootstrap script, the build fails:

** snip ** 
ninja: Entering directory `out/D'
[2/1038] CC obj/vendor/node/deps/openssl/openssl/ssl/openssl.ssl_cert.o
FAILED: /home/brianc/electron/vendor/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/vendor/node/deps/openssl/openssl/ssl/openssl.ssl_cert.o.d -DPURIFY -D_REENTRANT -DOPENSSL_NO_SSL2 -DOPENSSL_NO_SSL3 -DOPENSSL_NO_HEARTBEATS '-DENGINESDIR="/dev/null"' -DTERMIOS '-DOPENSSLDIR="/etc/ssl"' -DL_ENDIAN -DOPENSSL_NO_ASM -DDSO_DLFCN -DHAVE_DLFCN_H -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DTOOLKIT_VIEWS -DUSE_AURA -DUSE_X11 -DUSE_NSS_CERTS -DUSE_NSS -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUG -DCOMPONENT_BUILD -DGURL_DLL -DSKIA_DLL -DUSING_V8_SHARED -DWEBKIT_DLL -I../../vendor/node/deps/openssl -I../../vendor/node/deps/openssl/openssl -I../../vendor/node/deps/openssl/openssl/crypto -I../../vendor/node/deps/openssl/openssl/crypto/asn1 -I../../vendor/node/deps/openssl/openssl/crypto/evp -I../../vendor/node/deps/openssl/openssl/crypto/md2 -I../../vendor/node/deps/openssl/openssl/crypto/modes -I../../vendor/node/deps/openssl/openssl/crypto/store -I../../vendor/node/deps/openssl/openssl/include -Wno-missing-field-initializers -Wno-parentheses-equality -Wno-unused-function -Wno-sometimes-uninitialized -Wno-pointer-sign -Wno-string-plus-int -Wno-unused-variable -Wno-unused-value -Wno-deprecated-declarations -Wno-return-type -Wno-shift-negative-value -fPIC -fvisibility=hidden -m64 -march=x86-64   -c ../../vendor/node/deps/openssl/openssl/ssl/ssl_cert.c -o obj/vendor/node/deps/openssl/openssl/ssl/openssl.ssl_cert.o
/home/brianc/electron/vendor/llvm-build/Release+Asserts/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
[2/1038] CC obj/vendor/node/deps/http_parser/http_parser.http_parser.o
FAILED: /home/brianc/electron/vendor/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/vendor/node/deps/http_parser/http_parser.http_parser.o.d -DHTTP_PARSER_STRICT=0 -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DTOOLKIT_VIEWS -DUSE_AURA -DUSE_X11 -DUSE_NSS_CERTS -DUSE_NSS -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUG -DCOMPONENT_BUILD -DGURL_DLL -DSKIA_DLL -DUSING_V8_SHARED -DWEBKIT_DLL -I../../vendor/node/deps/http_parser -Wno-parentheses-equality -Wno-unused-function -Wno-sometimes-uninitialized -Wno-pointer-sign -Wno-string-plus-int -Wno-unused-variable -Wno-unused-value -Wno-deprecated-declarations -Wno-return-type -Wno-shift-negative-value -fPIC -m64 -march=x86-64   -c ../../vendor/node/deps/http_parser/http_parser.c -o obj/vendor/node/deps/http_parser/http_parser.http_parser.o
/home/brianc/electron/vendor/llvm-build/Release+Asserts/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.

**Comment by capouch** [comment]
Fix is to symlink libncurses.so.5 to be seen as libtinfo.so.5

**Comment by zcbenz** [comment]
Currently we only support building on certain Linux distributions, for other distributions you have to solve any build problem yourself.

For this issue, you can find the solution in docs:
http://electron.atom.io/docs/v0.35.0/development/build-instructions-linux/#troubleshooting

**Comment by evgeniyzinoviev** [comment]
Just a tip for gentoo users: you must enable `tinfo` use flag for `ncurses` package for this to work.
