### ISSUE TITLE
Unable to choose the font weight

### ISSUE THREAD

**Issue by torarvid** [atom/electron#3744]
Whether I'm using Atom or Visual Studio Code, I generally prefer using "Light" fonts. For instance, in Sublime Text, I can choose `Source Code Pro light` as my font face in the prefs, and it will understand that it should use the font name `Source Code Pro` and the weight `Light`. (On my Mac, it lists weights like Light, Medium, Regular, Bold, etc...)

Maybe this is possible to do in Electron based editors, but I don't know how to do it..

(Apologies if this issue is filed in the wrong place, and should go in the Atom/VSCode repos instead)

**Comment by raleksandar** [comment]
I use all range of font weights in my Electron app so it's definitely something you should ask about on Atom/VSCode repos

**Comment by Jack-CHS-PWD** [comment]
Having this exact issue.

In an existing electron app, I imported the exact code (js/css/html) from <https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight> (the example in the middle of the webpage with a slide bar to adjust font-weight dynamically.)

In Electron, however, it only displays two font weights when the slider is dragged:
* normal: [1-599]
* bold: [600-1000]

Moreover, when making a fresh clone of the "Electron Quick Start" template and adding the same code, the font weight will instead only display three font weights: 
* slim: [1-549]
* normal: [550-799]
* bold: [800-1000]

Neither of these results seem to represent proper functionality of this feature (a smoothly transitioning displayed font weight), but it's even stranger that the results are different on the separate applications despite using identical imports for the js/css

Using node.js 12.8.1, Chromium 78.0.3904.130, and Electron 7.1.7
