### ISSUE TITLE
MAS submission sandbox error - Contents/MacOS/MyApp

### ISSUE THREAD

**Issue by hauran** [atom/electron#3746]
Im getting this error when i try to submit to MAS -  

ERROR ITMS-90296: "App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "com.MyApp.pkg/Payload/MyApp.app/Contents/MacOS/MyApp" )]"

added that file to the script described here: http://electron.atom.io/docs/v0.35.0/tutorial/mac-app-store-submission-guide/ but get the error "Contents/MacOS/MyApp: bundle format unrecognized, invalid, or unsuitable", so that doesn't seem to do anything.

any ideas on how to sandbox Contents/MacOS/MyApp?

**Comment by herrmannplatz** [comment]
Could be either missing or wrong bundle identifiers.

**Comment by zcbenz** [comment]
The signing tool seems to behave differently on different versions of OS X, you can also try this script:
https://gist.github.com/jorangreef/27e708c67b7e6746a98a
