### ISSUE TITLE
Icons and Menu missing on ubuntu VM

### ISSUE THREAD

**Issue by xhallix** [atom/electron#3756]
I wrote an app which runs fine on windows, but when I tested it on linux I'm getting trouble with the menubar.
There are two cases:
1. app is blazing fast but has no menu bar
2. app is horrible slow but has a menu bar
I dont know how to invoke both cases, they seems to occur randomly

Is this a know issue?

I'm running Ubuntu 14.04.3 LTS in VMware.
Electron is install locally.

Thanks

**Comment by zcbenz** [comment]
Chromium on Linux is known to work poorly in certain virtual machines, and unfortunately Electron inherited this bug. I suggest reporting this to [Chromium's issues list](https://crbug.com) instead, there is nothing we can do in Electron.

**Comment by xhallix** [comment]
thanks for the quick reply :) I'll raise it on the issue list later on
