### ISSUE TITLE
Use SemVer - Bump to 1.0 or publish a roadmap for 1.0

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#3757]
Electron is currently 0.x meaning

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Is this true? if so, is there a roadmap of changes before initial development will finish?

Or is it that you haven't got around to bumping to 1.0 ?

**Comment by kevinsawicki** [comment]
>  is there a roadmap of changes before initial development will finish?

Not sure if you've seen this yet but 1.0 API changes have been documented initially at http://blog.atom.io/2015/11/17/electron-api-changes.html

**Comment by lukeapage** [comment]
awesome, I didn't see that..
