### ISSUE TITLE
Is it possible to launch a .bat file from an electron html file?

### ISSUE THREAD

**Issue by jpmi1** [atom/electron#3763]
Trying to launch an application .exe once a button is pressed on the .html file in the app folder. I need to pass in two variables that I collected earlier and was planning on doing this by creating a bat file and running it on the press of the button any help would be appreciated.

**Comment by kevinsawicki** [comment]
You might want to take a look at the following links for answers:

* http://stackoverflow.com/questions/22678933/run-a-windows-batch-file-from-node-js
* http://stackoverflow.com/questions/21557461/execute-a-batch-file-from-nodejs
* https://nodejs.org/api/child_process.html

It is possible and requires using the node `child_process` module.

I'm going to close this out.

**Comment by GrumpyCrouton** [comment]
Is this still possible to do? I tried with the above sources and could not get this to work. I also posted a question on StackOverflow, but views on that are very slowly trickling in and I thought I would try my luck here: https://stackoverflow.com/questions/49906156/run-batch-file-from-electron-main-thread
