### ISSUE TITLE
Events when links are clicked in `webview`

### ISSUE THREAD

**Issue by jingweno** [atom/electron#3772]
I want to implement the cases that when any link is clicked in a `webview`, it's opened in the default browser. But `webview` only has the [`new-window` event](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#event-new-window) which is fired only when new window is opened  (e.g., with `_target`). I wonder how do I support the case for links that don't open a new window?

**Comment by jingweno** [comment]
It seems https://github.com/atom/electron/issues/852 had similar problems

**Comment by jingweno** [comment]
My electron version is `v0.35.4`.

**Comment by xywz** [comment]
Duplicate of #1378?

**Comment by zcbenz** [comment]
I'm merging this to #1378, @xywz thanks for noticing this!
