### ISSUE TITLE
Loading ClojureScript sourcemaps breaks code mirror syntax highlighting (possible regression?)

### ISSUE THREAD

**Issue by ducky427** [atom/electron#3773]
I think there has been a regression in Electron v0.36.0. There was a similar issue #2851 which had addressed it. 

Now the errors are:

```
96858:1211/090227:ERROR:CONSOLE(0)] "XMLHttpRequest cannot load https://chrome-devtools-frontend.appspot.com/serve_file/@2d637ddb1c5ed38b794d9c2c00f0379868892bc8/cm_modes_module.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-devtools://devtools' is therefore not allowed access. The response had HTTP status code 404.", source: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@2d637ddb1c5ed38b794d9c2c00f0379868892bc8/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (0)
[96858:1211/090227:ERROR:CONSOLE(25)] "Empty response arrived for script 'https://chrome-devtools-frontend.appspot.com/serve_file/@2d637ddb1c5ed38b794d9c2c00f0379868892bc8/cm_modes_module.js'", source: chrome-devtools://devtools/bundled/inspector.js (25)
[96858:1211/090227:ERROR:CONSOLE(0)] "Uncaught (in promise) Could not instantiate: WebInspector.DefaultCodeMirrorMimeMode", source: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@2d637ddb1c5ed38b794d9c2c00f0379868892bc8/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (0)
```

**Comment by deepak1556** [comment]
Seems like a bug with chromium was able to reproduce the issue on v46.0.2490.86 (64-bit)..

**Comment by ducky427** [comment]
I've tried the same experiment with Chrome 47.0.2526.80 and Chromium 49.0.2589.0 on OSX and it works. So it could be something specific to Chromium 46.

@deepak1556, where can I find Chromium 46?

Thanks!

**Comment by deepak1556** [comment]
Oh it works with 47? cool. Thanks for confirming.

**Comment by deepak1556** [comment]
Found the issue, the current webkit revision value used in our [remoteBase url](https://github.com/atom/brightray/blob/master/browser/inspectable_web_contents_impl.cc#L109-L114) doesnt seem to be a path that exists on gae, tried with the latest value from [chromium](https://code.google.com/p/chromium/codesearch#chromium/src/build/util/LASTCHANGE.blink&sq=package:chromium) and it works. So this might be a blocker util next chromium upgrade, can we hardcode the webkit revision value for devtools remoteBase url until then @zcbenz ?

**Comment by zcbenz** [comment]
@deepak1556 Hardcoding the webkit revision doesn't seems a decent solution to me, and using a remote file not matching the correct revision is very easy to break things. I think we should find out why the revision value is wrong.

**Comment by darrrk** [comment]
:+1: 
I lose syntax highlight for *.coffee files
Please remove "ClojureScript" word from issue title, this problem more wider.

**Comment by zcbenz** [comment]
Fixed with https://github.com/zcbenz/chromium-source-tarball/commit/4682f0df3dd740ff468b2f0df9d515aeaae8fc20.

**Comment by ducky427** [comment]
Thanks!
