### ISSUE TITLE
Uncaught exception in main process after reloading

### ISSUE THREAD

**Issue by DerNivel** [atom/electron#3778]
This code causes an uncaught exception when focusing the (detached) Developer Tools after reloading the page:

```javascript
import classnames from 'classnames';
import { remote } from 'electron';

const mainWindow = remote.getCurrentWindow();

mainWindow.on('blur', () => document.body.className = classnames('unfocused'));
mainWindow.on('focus', () => document.body.className = classnames('focused'));
```

The stack trace:
```
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (bootstrap.js:12:12.
    at BrowserWindow.ret (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\rpc-server.js:149:21)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
    at Object.module.exports.showErrorBox (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\dialog.js:157:35)
    at process.<anonymous> (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\init.js:62:19)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
    at Object.module.exports.showErrorBox (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\dialog.js:157:35)
    at process.<anonymous> (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\init.js:62:19)
```

**Comment by DerNivel** [comment]
Oh sorry. I'm dumb. I don't release the callbacks before/after reloading.

**Comment by astoilkov** [comment]
Hey @DerNivel,

Can you share what is the code that helped you release these callbacks after reloading? I am having the same problem but can't figure it out.

**Comment by DerNivel** [comment]
Method 1: Don't use events with the remote module (use the ipc module for that)
Method 2: Release the callbacks on app startup. Example:
```javascript
remote.getCurrentWindow().removeAllListeners(); // put this as first line in your code of the renderer-process
```

**Comment by astoilkov** [comment]
Thanks a lot for the information. This really helped in resolving this issue.

How did you find out these things on your own?

**Comment by DerNivel** [comment]
I noticed that the crash is caused because Electron tries to call callbacks that are not in runtime anymore. I looked for a method which deletes the association with these callbacks and found `removeAllListeners()` in the documentation.

**Comment by DerNivel** [comment]
Oh sorry. `removeAllListeners()` is not documented. Then I have no idea where I found that.

**Comment by serjN** [comment]
@levrik, I used "Method 2: Release the callbacks on app startup", but it doesn't work.

**Comment by levrik** [comment]
@serjN did you import the `remote` module?

**Comment by serjN** [comment]
@levrik in my render process
```
var electron = require(electron);
electron.remote.getCurrentWindow().removeAllListeners();
```

**Comment by levrik** [comment]
@serjN There are missing quotation marks around `electron` inside the `require` statement

**Comment by serjN** [comment]
@levrik  It's pseudo code, problem not in quotation marks.

**Comment by levrik** [comment]
@serjN Did you get any error or warning?

**Comment by serjN** [comment]
On render process no (function electron.remote.getCurrentWindow().removeAllListeners() executed without errors), on main process "Uncaught Exception: Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here."

Steps to reproduce:
0)Have this code on page
```
var electron = require('electron');
electron.remote.getCurrentWindow().removeAllListeners();
```
1) From page throw nodejs library restify send request with callback in render process
2) Stop request on web server
3) Reload page
4) Release request on web server 
5) See  error: "On render process no, on main process Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here."

**Comment by levrik** [comment]
@serjN I think this it not related to this issue.

**Comment by serjN** [comment]
@levrik I understood, I supposed that electron.remote.getCurrentWindow().removeAllListeners() removed all listeners for render process, bit it's not truth. Thanks.

**Comment by levrik** [comment]
@serjN `removeAllListeners` removes all event listeners which are attached to the window directly.

**Comment by danyadev** [comment]
(for those who want to solve the problem)
in renderer process
code: 
`getCurrentWindow().on('blur', titlebarBlur);`
`getCurrentWindow().on('focus', titlebarFocus);`
`getCurrentWindow().on('maximize', maxOrRes);`
`getCurrentWindow().on('restore', maxOrRes);`
fix: (add)
`window.addEventListener('beforeunload', ()=>{`
  `getCurrentWindow().removeListener('blur', titlebarBlur);`
  `getCurrentWindow().removeListener('focus', titlebarFocus);`
  `getCurrentWindow().removeListener('maximize', maxOrRes);`
  `getCurrentWindow().removeListener('restore', maxOrRes);`
`});`
