### ISSUE TITLE
allowNTLMCredentialsForAllDomains causes the application to terminate.

### ISSUE THREAD

**Issue by ruanbarcellos** [atom/electron#3779]
Since the electron v0.34.1 version, when this feature was launched, I'm trying to use it in Windows 10, but causes the application to terminate.

No error message is shown

**Comment by paulcbetts** [comment]
Are you perhaps calling this API before `ready` has fired?

**Comment by paulcbetts** [comment]
Assuming this is the case, please reopen if not.

**Comment by ruanbarcellos** [comment]
I'm sorry, I forgot to answer .. Yes this was the case, thank you.
