### ISSUE TITLE
[0.36.0] Commandline Switch is failing

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#3780]
Hello,

First of all great work on bringing " chrome 47" to electron and bringing other necessary features like "Desktop capture", Was eager to test the build bcoz chrome has lot of fixes 

Command-line switch failed so unable to use debugging tool in browser. sample snippet is provided
we use it to debug our apps in chrome browser.
```
var app = require('app'); // Module to control application life.
app.commandLine.appendSwitch('remote-debugging-port', '9222');

```

Thanks.

**Comment by deepak1556** [comment]
commandline switches work fine, its most likely the `IDR_CONTENT_SHELL_DEVTOOLS_DISCOVERY_PAGE` value must have changed. You can still use remote debugging, In your chrome browser visit `http://localhost:9222/json` and find the `webSocketDebuggerUrl` and visit `chrome-devtools://devtools/bundled/inspector.html?ws=<webSocketDebuggerUrl>`

**Comment by kamesh-a** [comment]
@deepak1556 thanks i didn't see the json. i thought devtools websocket didnt work. closing the card
thanks.
