### ISSUE TITLE
[0.36.0] reading large files failed

### ISSUE THREAD

**Issue by appelgriebsch** [atom/electron#3781]
When trying to read in files into an Electron application (pdf documents, stored in local PouchDB (leveldb)) using the File object I will experience a crash of the application with the latest version of the Electron runtime (0.36.0). Using an earlier version of it works pretty well with the same file though...

On the command line I see the following "crash dump" before the application quits unexpectedly:

[10084:10156:1211/152921:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=http://54.249.141.255:1127/post --app
lication-name=inspect.demonstrator --v=1]
[10084:10156:1211/152921:VERBOSE1:crash_service.cc(142)] window handle is 00000000001806CE
[10084:10156:1211/152921:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\inspect.demonstrator Crash Service
dumps at C:\Users\ANDREA~1.GER\AppData\Local\Temp\inspect.demonstrator Crashes
[10084:10156:1211/152921:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\ANDREA~1.GER\AppData\Local\Temp\inspect.demonstrator Crashes
\crash_checkpoint.txt
server is http://54.249.141.255:1127/post
maximum 128 reports/day
reporter is electron-crash-service
[10084:10156:1211/152921:ERROR:crash_service.cc(301)] could not start dumper

<--- Last few GCs --->

   22189 ms: Mark-sweep 35.2 (68.1) -> 27.1 (69.1) MB, 13.6 / 0 ms (+ 37.0 ms in 13 steps since start of marking, biggest step 6.0 ms) [idle
 notification: finalize incremental] [GC in old space requested].
   22841 ms: Mark-sweep 28.4 (69.1) -> 26.8 (68.1) MB, 12.6 / 0 ms (+ 38.0 ms in 14 steps since start of marking, biggest step 7.0 ms) [idle
 notification: finalize incremental] [GC in old space requested].
   25786 ms: Scavenge 28.6 (69.1) -> 27.8 (69.1) MB, 0.7 / 0 ms [idle task: scavenge].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000D410A628E1 <String[7]: file://>
    1: /* anonymous */(aka /* anonymous */) [G:\inspect-demonstrator\app\modules\library\services\LibraryDataService.js:43] [pc=0000038E6906
6D07] (this=0000036D33A04189 <undefined>,doc=00000013CB052231 <an Uint8Array with map 000000C3B0513E01>)
    2: /* anonymous */(aka /* anonymous */) [G:\inspect-demonstrator\app\modules\library\services\LibraryDataService.js:45] [pc=0000038E6906
6...

**Comment by zcbenz** [comment]
I'm merging this to #3786.
