### ISSUE TITLE
[Win32] Transparent icons are having a blue background on Windows Notifications.

### ISSUE THREAD

**Issue by lipis** [atom/electron#3782]
![screen shot 2015-12-11 at 15 46 14](https://cloud.githubusercontent.com/assets/125676/11746411/5ce26db2-a01e-11e5-9628-7100ed751f54.png)

**Comment by paulcbetts** [comment]
@lipis This isn't a bug, this is your Accent Color from Windows

**Comment by lipis** [comment]
I was just expecting to be black as the rest of the notification.. so in order to fix it we need to have a squared icon I guess..
