### ISSUE TITLE
WebView Missing Equivalent of 'devtools-opened' / 'devtools-closed'

### ISSUE THREAD

**Issue by francoislaberge** [atom/electron#3783]
The WebView element has a matching [openDevTools](http://electron.atom.io/docs/v0.35.0/api/web-view-tag/#lt-webview-gt-opendevtools), [closeDevTools](http://electron.atom.io/docs/v0.35.0/api/web-view-tag/#lt-webview-gt-closedevtools), and [isDevToolsClosed](http://electron.atom.io/docs/v0.35.0/api/web-view-tag/#lt-webview-gt-isdevtoolsopened) that WebContents has. But it does not generate the ```devtools-opened``` and ```devtools-closed``` events that WebContents has.

I know I could use polling to get around this, but was hoping maybe I was missing the correct way to detect when the user close the devtools of a webview that I opened. I'm working on a debugger workflow and want to restore the shown/hidden state of the debugger.

Thanks in advance,
Francois

**Comment by bridiver** [comment]
don't forget devtools-focused
