### ISSUE TITLE
Use asap command within electron

### ISSUE THREAD

**Issue by younes200** [atom/electron#3784]
I'm trying to create a asar package within an electron application. 
I tried first to use `asar` function  `asar.createPackageWithOptions` but it failed. I guess `asar` package is using the patched version of `fs`. Next, I tried to use asar from command ligne  :
```
execFile("./node_modules/asar/bin/asar", ['pack', src, dest], function (error, stdout, stderr) {
    if (error) return console.error(error);
    console.log(stderr);
});
```
But it fail with :
```
Uncaught Exception:
TypeError: Error processing argument -1.
    at TypeError (native)
    at Object.module.exports.showErrorBox (/Users/
```
My electron application is not using `--asar` package for deployment.
Any idea how to fix it ?
Thanks in advance.
/Y

**Comment by zcbenz** [comment]
`execFile` usually won't throw an uncaught exception, the error is very likely to come from other parts of your code.

**Comment by younes200** [comment]
Here is example for the issue : https://github.com/younes200/electron-asar-test
Please not that the error occurred only when running the application as packaged (.app or .exe) not with `electron .`

**Comment by zcbenz** [comment]
I think I have found the problem, `execFile` will copy the file out of asar archive before executing it, and since only one file is copied out, the execution will fail. The solution is to either put the `asar` npm module out of the `asar` archive, or just use the `asar.createPackageWithOptions` API, you can set  `process.noAsar` to `true` to force using the original `fs` module.

**Comment by younes200** [comment]
Thanks @zcbenz for the `process.noAsar` tips ;) Should I put back the `process.noAsar` to `true` after calling the `asar.createPackageWithOptions` ?

**Comment by zcbenz** [comment]
Yeah you should set it back once the work is done, Electron's builtin modules are inside an asar archive so you may still need asar support in other parts of your code.
