### ISSUE TITLE
after package,in mac osx, the shortcut key cannot work,like command+c,command+v

### ISSUE THREAD

**Issue by wyjieying** [atom/electron#3787]
after package,in mac osx, the shortcut key cannot work,like command+c,command+v,why?
if use command line to run project, shortcut key can work, but ,after package , it cannot work?

**Comment by zenorocha** [comment]
Hey @wyjieying, you might want to check the [menu class](https://github.com/atom/electron/blob/master/docs/api/menu.md).

**Comment by zcbenz** [comment]
The packaged app doesn't have default menu which provides key shortcuts, you have to create an application menu yourself.

**Comment by wyjieying** [comment]
const electronLocalshortcut = require('electron-localshortcut');
add this code can solve the problem!, i don't know  why

**Comment by petrfelzmann** [comment]
On Windows the Ctrl+V command works, but on OSX the Cmd+V doesn't work. Seems to me as bug on OSX.

**Comment by vikas-cis** [comment]
There is still a bug on OSX Cmd/Ctrl+V doesn't work, Is anyone get it to resolve ?

**Comment by Golosay** [comment]
That's because the Edit menu item is removed by default.
Add it to electron index.ts

```
const appMenuBarMenuTemplate: (MenuItemConstructorOptions | MenuItem)[] = [
  { role: process.platform === 'darwin' ? 'appMenu' : 'fileMenu' },
  { role: 'editMenu' }, // Add this menu
];
```
