### ISSUE TITLE
visibilitychange event not being triggered

### ISSUE THREAD

**Issue by zenorocha** [atom/electron#3788]
I've been trying to use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) however the `visibilitychange` event is not being triggered. 

I understand that Electron's `pageVisibility` option forces either visible or hidden states but is there a way to listen for the true window visibility changes?

P.S.: Here's a small snippet and an [electron-quick-start fork](https://github.com/zenorocha/electron-quick-start/blob/master/index.html) if you guys wanna do some testing.

```js
document.addEventListener("visibilitychange", function() {
  console.log( document.visibilityState );
});
```

**Comment by DerNivel** [comment]
Take a look at these events: https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-blur

**Comment by chrisyip** [comment]
In my app, `visibilitychange` event can be triggered, but the behavior is strange:

When window minimized or maximized, `document.hidden` is always `true`.

Tested on `0.34.5`.

**Comment by hfcorriez** [comment]
+1

**Comment by gordomium** [comment]
+1

**Comment by gordomium** [comment]
And in my app, `document.hidden` is always `false`.

both `0.34.5` on `OSX`.

**Comment by zenorocha** [comment]
Hey @chrisyip,

Could you share a snippet that demonstrates `visibilitychange` being used in your app?

**Comment by chrisyip** [comment]
@zenorocha

```
document.addEventListener('visibilitychange', function () {
  // code goes here
}, false)
```

Thought the third parameter, `useCapture`, is marked `optional` in MDN's document, but in my experience, you'd better pass it explicitly. Otherwise, event might not be triggered.

**Comment by paulcbetts** [comment]
Sorry for the silly question, but why would you use this API in Electron? What are you trying to accomplish

**Comment by zenorocha** [comment]
That's alright @paulcbetts. I'm building some sort of TweetDeck for GitHub (http://devspace.io) and the reason why I use this API is to stop pooling data whenever the page is not visible and fetch new data whenever the webpage is visible again.

**Comment by DerNivel** [comment]
@zenorocha Then use the `blur` and `focus` events of the `BrowserWindow`.

**Comment by zenorocha** [comment]
Yes @DerNivel, that's an option. But I'm trying to reuse the same codebase from desktop and web apps.

**Comment by chrisyip** [comment]
@patrickdet @zenorocha @DerNivel I'm trying to reuse the same codebase from desktop and web apps too.

`blur` event doesn't work perfectly (don't know if it's a bug yet), so I'm trying to use `visibilitychange` event to figure out the perfect way.

**Comment by paulcbetts** [comment]
I think @DerNivel's got the right idea here - if you want to reuse the web codebase, you can artificially raise `visibilitychanged` yourself on blur/focus

**Comment by arusakov** [comment]
Electron 0.36.7
Mac OS X 10.11.3

```document.hidden``` alway true, when I switch between desktops.
