### ISSUE TITLE
100% CPU after wakeup from suspend, Linux

### ISSUE THREAD

**Issue by ninja-** [atom/electron#3793]
lsof:
```
electron 25432 ninja   21u  unix 0xffff8803ba988700      0t0 1431093 type=STREAM -> 0xffff8803ba988e00[Xorg,27058,@/tmp/.X11-unix/X0]
electron 25432 ninja   27u  unix 0xffff88030f8fe580      0t0 1428081 type=STREAM -> 0xffff88030f8fa300[Xorg,27058,@/tmp/.X11-unix/X0]
```

strace(repeats forever):
```
poll([{fd=21, events=POLLIN}, {fd=22, events=POLLIN}, {fd=27, events=POLLIN}, {fd=28, events=POLLIN}], 4, 4294967295) = 1 ([{fd=28, revents=POLLIN}])
recvmsg(27, 0x7ffd90aa93c0, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(21, 0x7ffd90aa9380, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(27, 0x7ffd90aa9390, 0)          = -1 EAGAIN (Resource temporarily unavailable)
```

This will happen for every electron app in my tests after waking up from suspend

OS: Arch Linux kernel 4.2.5-1-ARCH
Electron: latest prebuilt from npm repository

**Comment by zcbenz** [comment]
Regarding "latest prebuilt from npm repository", is it 0.36.0? And for "every electron app", did you mean apps like VS Code and Atom?

**Comment by ninja-** [comment]
@zcbenz yes the version I tested with was 0.36.0. The apps that were independently causing this problems were Rocket.Chat Desktop and Matterfront (slack-like chat apps). Atom didn't seem to have this problem though.

**Comment by paulcbetts** [comment]
We've never heard of this afaik

**Comment by zcbenz** [comment]
Since Atom doesn't have the problem, and I have to assume it is the app's code that caused the 100% CPU usage. I suggest reporting this to each app's repo instead.
