### ISSUE TITLE
pepper plugin does not load on Windows

### ISSUE THREAD

**Issue by rmsmith** [atom/electron#3794]
Hello,

I am trying to load a pepper plugin and receiving a "Couldn't load plugin" message on Windows 7, with Electron 0.35.4, Chrome 45.0.2454.85.  I am able to load the exact same plugin .dll in Chrome Canary on the same pc.   Additionally, I have no trouble loading the plugin in Electron on OSX as a .so, so there appears to be a Windows-specific problem.

As requested by @deepak1556 in #3252 I am opening a new issue here with a minimal sample app (attached).  The sample contains a prebuilt plugin in `win/Release/hello.dll` because setting up the build can be a bit tricky.  However, I have included the `Makefile` should you wish to build it again; it uses the `nacl_sdk` (`make` from `nacl_sdk` must be on your `%PATH%`) and VS2013 (`cl.exe` from VS2013 must be on your `%PATH%`).

If the plugin is successfully loaded you will see "hello from plugin" printed to the javascript console.

Please let me know if there are any further details I can provide to assist with debugging this issue. 

Thank you!

[pepper.zip](https://github.com/atom/electron/files/60184/pepper.zip)

**Comment by paulcbetts** [comment]
My psychic debugger is saying that your plugin and Chrome are 64-bit and your Electron is 32-bit or vice-versa

**Comment by rmsmith** [comment]
@paulcbetts I should have mentioned that this is a 32-bit .dll running in 32-bit Electron; my Chrome Canary version is also 32-bit.

One other tidbit regarding Chrome Canary is that I had to go into `chrome://plugins` and check a checkbox that says "Always allowed to run" in order for the plugin to smoothly load.  That checkbox won't appear until you have a page running that attempts to load the plugin, but once checked it will persist for future loads.  I don't know if this is relevant to Electron but I thought it was worth mentioning.

**Comment by zcbenz** [comment]
You need to use the plugin from the Chrome version that matches the one used by Electron, e.g. Chrome 45 instead of Chrome Canary.

**Comment by rmsmith** [comment]
@zcbenz I don't understand why you have closed this issue.  I have built the pepper plugin with the `pepper_45` version of the `nacl_sdk` and I am using Electron with Chrome 45.  The fact that I can load my plugin in Chrome Canary is simply provided as  evidence that the plugin .dll is properly built.

Does anyone have a working 3rd party pepper plugin that they are using with Electron on Windows?

**Comment by zcbenz** [comment]
@rmsmith Sorry I thought you were trying to use the Flash plugin, currently I don't think we have a way to load third party pepper plugins except for Flash, we should definitely add one though.

**Comment by rmsmith** [comment]
@zcbenz support for 3rd party pepper plugins was recently added by @deepak1556 (see #1558) and I can confirm that it _does_ work on OSX.  The problem seems to be on Windows only.

**Comment by rmsmith** [comment]
Today I was able to figure out my problem and load the plugin on Windows.  The problem was with the plugin path on Windows.  All of the example code that I have seen on this subject has shown code similar to the attached example:

```
var path = require('path');
app.commandLine.appendSwitch('register-pepper-plugins', path.join(__dirname,'win/Release/hello.dll;application/x-hello'));
```

The above call to `path.join` yields:

```
D:\github\electron-quick-start\win\Release\hello.dll;application\x-hello
```

The above string does not represent a Windows path, which was the problem.  If I build my own path string literal then the plugin successfully loads:

```
D:/github/electron-quick-start/win/Release/hello.dll;application/x-hello
```

Being new to `node.js` this behavior of the `path` module was not obvious to me.  It would probably be good to have a correct example somewhere for others to avoid this pitfall :)

I will close this issue since the plugin loading is working now :)  Sorry for the noise.

Thanks!

**Comment by sleepcooper** [comment]
@rmsmith  
 hello rmsmith :  
    I have a  problem with your plugin. use the word (chrome --register-pepper-plugins="E:/Demo/pepper/win/Release/hello.dll;application/x-hello" ) to regist the plugin and in chrome plugins I saw hello.dll. then in local html file I write the word:
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello</title>
  </head>
  <script>
	var obj = document.getElementById('hello');
	alert(obj);
  </script>
  <body>        
    <embed width="200px" height="200px"
        id="hello"
        type="application/x-hello"/>
  </body>
</html>

I received a tip that the website don't support the plugin and the variable object is null
I don't know what's problem, can you help me?

thanks

**Comment by rmsmith** [comment]
@sleepcooper which version of Chrome are you using?  As far as I know this will not work in the Stable channel of Chrome, it works only in the Chrome Canary channel or in things like Electron.

If you are in Chrome Canary (32-bit build for Windows) then be sure to check the checkbox that says "Always allowed to run" in `chrome://plugins` and then try to re-launch Canary.

Hope that helps,

**Comment by rmsmith** [comment]
@sleepcooper also I just noticed that you have quotation marks around "embed" in your html.  That is probably why your variable `obj` is null.  Try removing those quotes :)

**Comment by sleepcooper** [comment]
@rmsmith  I changed chrome version in the Chrome Canary version(32-bit build for Windows) ,  and set "Always allowed to run". but still has the problem that the website don't support the plugin and the variable object is null , should I set some option in chrome:// flags
embed label has quotation in order to show my html content

**Comment by rmsmith** [comment]
@sleepcooper my test of the plugin in Chrome Canary was as a Chrome App, not a web page, so perhaps that accounts for the difference.  My tests in Chrome Canary were only for debugging purposes so that I could get things working in Electron.  If you want to target Chrome web pages I'd recommend using Native Client or Emscripten, which are both designed for that use case.  The `Makefile` in my sample plugin can also produce a `.pexe` file (Portable Native Client executable) with some minor modifications.  Hope that helps,

**Comment by sleepcooper** [comment]
@rmsmith Thank you reply . we want to use plugin in cef frame.  I choose load dll file and use ppapi mode. but when i start,  ran into a problem that dll plugin don't load successful.

**Comment by sleepcooper** [comment]
@rmsmith  
If I change your code, how to built a dll file on windows os

thanks

**Comment by rmsmith** [comment]
@sleepcooper I built the example plugin `dll` using `make` from the `nacl_sdk` and Visual Studio 2013, however I did not use the `vs_addin`.  If you put `cl.exe` from VS 2013 on your %PATH% that is all you need to build with `make` from the `nacl_sdk` (it is convenient to also put `make` from `nacl_sdk/pepper_45/tools/` on your %PATH%).  I hard-coded some paths to VS 2013 in the Makefile for this sample plugin, so you should check that those match your system.  Once all of this is setup, it should be as simple as typing `make TOOLCHAIN=win` on the command line.

Hope that helps,

**Comment by minggo** [comment]
@rmsmith Is there any example about how to build a .so with pepper SDK?

**Comment by rmsmith** [comment]
@minggo the example plugin in this issue can build a .so.  More examples can be found in the Native Client SDK and their documentation and forums are a better place to ask questions on the topic.

**Comment by minggo** [comment]
@rmsmith Thanks for your answer. I just download the SDK, and run `make`, all are generate `.pexe` or `.nexe` files. And i found you said you can generate `.so`, so i ask you here.

PS: can electron load `.pexe` file?

**Comment by rmsmith** [comment]
@minggo on OSX you would run `make TOOLCHAIN=mac` on the command line, for example.  Check that `mac` and/or `linux` are in the Makefile's `VALID_TOOLCHAINS`.

Electron will not load a `.pexe` or `.nexe` (those require Native Client which is not included) but only a `.so` or `.dll` (trusted Pepper Plugin).

**Comment by minggo** [comment]
@rmsmith  Thanks.
