### ISSUE TITLE
Feature request: Kiosk mode and kiosk printing support

### ISSUE THREAD

**Issue by neerajcse** [atom/electron#3806]
Chromium already has flags which allow skipping the print preview and also allows automatic selection of default printer for printing [(see kiosk and kiosk-printing)]. 

It would be a great addition to Electron if these switches can be integrated into the [chromium switches api].

I would be glad to contribute to the code for this if this feature ends up being a low-priority thing.

[(see kiosk and kiosk-printing)]: http://peter.sh/experiments/chromium-command-line-switches/
[chromium switches api]:https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md

**Comment by zcbenz** [comment]
For kiosk mode we have `kiosk` option in `BrowserWindow`, for kiosk printing there is `silent` option for the `BrowerWindow.print` API.

**Comment by ivaninja** [comment]
Is it possible to add that feature, to create all prints like silent

**Comment by Wexoo** [comment]
`kiosk` in `BrowserWindow` is a great working alternative. But for me it's also not the same to set `silent` for the `print()` function and just setting the global print settings to silent / kiosk-printing. Especially for wrapping an existing web app for a desktop version, it would be very useful to be able to pass the chrome flag `--kiosk-printing` instead for global silent prints.
