### ISSUE TITLE
http://atom-slack.herokuapp.com does not work anymore

### ISSUE THREAD

**Issue by brian-mann** [atom/electron#3807]
Is there another way to get an invite to the slack channel?

**Comment by kevinsawicki** [comment]
It is back up, thanks for reporting this.

**Comment by refack** [comment]
https://atom-slack.herokuapp.com/ is 503ing ATM

![image](https://user-images.githubusercontent.com/96947/49687794-4ad1aa00-fad6-11e8-949c-b325d1e261ea.png)

**Comment by BinaryMuse** [comment]
@refack This is back up and running

**Comment by refack** [comment]
> This is back up and running

Thank you. Can confirm it works for me.

**Comment by cjl248** [comment]
http://slack-chat.herokuapp.com/slack  currently not working again. See screenshot.
<img width="542" alt="Screen Shot 2019-07-04 at 7 01 44 PM" src="https://user-images.githubusercontent.com/10910899/60689712-562f5d00-9e8e-11e9-8e6a-4b7bb3c03554.png">
