### ISSUE TITLE
quitAndUpdate + makeSingleInstance

### ISSUE THREAD

**Issue by fasterthanlime** [atom/electron#3813]
electron 0.35.4, Windows 8.1 64-bit, using the auto-updater, this gif shows a call to `auto_updater.quitAndUpdate()` after an update was fully downloaded:

![quitandupdate](https://cloud.githubusercontent.com/assets/7998310/11799398/05e736ce-a2d4-11e5-9d78-16ca7b50cc58.gif)

It seems the window gets closed, and almost instantly, the app gets the `activate` event (presumably because auto-updater tries to launch another instance?), hence, the update is not actually 'applied'.

When quitting manually the app and launching it again, the new version is active.

I know about #539 but not convinced it's a dupe — I'm not asking for a separate `app.restart()` API that works under any circumstances, just for auto-update to work (which assumes Squirrel.Windows presence, so we can potentially rely on `Update.exe` to relaunch us after we're done shutting down).

**Comment by fasterthanlime** [comment]
Nothing that @paulcbetts described almost the situation we're seeing:

> This is actually something that might be useful given the addition of the makeSingleInstance API, since the straightforward way that bwin provides doesn't work then (since if you lose the race, you'll just signal yourself then proceed to exit)

Presumably we're catching/preventDefaulting some events that would otherwise lead us to quit after being signaled.

One can reproduce the GIF above by:

  * Downloading a itch v0.8.1's `itchSetup.exe`, installing as usual
  * Hitting 'Help -> Check for updates'
  * Waiting for Squirrel.Windows to figure out there's an update, download and apply it
  * Clicking on `Click to restart & apply update!`

**Comment by paulcbetts** [comment]
@fasterthanlime the `--processStart` flag of update.exe was designed to solve this, it'll wait for its parent to exit, then respawn the latest version

**Comment by zcbenz** [comment]
> @fasterthanlime the --processStart flag of update.exe was designed to solve this, it'll wait for its parent to exit, then respawn the latest version, we should wire this into autoUpdate

I think the autoUpdater in Electron is already using it?

**Comment by raleksandar** [comment]
I have no problems using `autoUpdater.quitAndInstall()` together with `app.makeSingleInstance()` on both OSX and WIndows.

My code in `main.js` is something like this:

```js
require('./updater.js');

const shouldQuit = app.makeSingleInstance((argv) => {
    // argument processing
    if (mainWindow) {
        focus(mainWindow); // focus() will restore window if necessary and then focus() it
    } else {
        init();
    }
});

if (shouldQuit) {
    app.quit();
}

app.on('ready', init);
app.on('activate', () => {
    if (mainWindow) {
        focus(mainWindow);
    } else {
        init();
    }
});
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

function init() {
    // load html, setup everything...
}
```

Excerpt from `update.js`:
```js
if (process.platform === 'win32') {
    // process Squirrel events and app.quit() if necessary
}

// ...

const buttons = ['Restart and update', 'Not now'];

if (process.platform === 'darwin') {
    buttons.reverse();
}

const cancelId = buttons.indexOf('Not now');

autoUpdater.on('update-downloaded', (e, releaseNotes, releaseName) => {
    dialog.showMessageBox({
        message: 'A new version of is available!',
        noLink: true,
        buttons,
        cancelId,
    }, (choice) => {
        if (choice !== cancelId) {
            autoUpdater.quitAndInstall();
        }
    });
});
```

**Comment by fasterthanlime** [comment]
> I think the autoUpdater in Electron is already using it?

Yep:

  * https://github.com/atom/electron/blob/fbb8e61958c8950455883e2a4ae12088ba030a12/atom/browser/api/lib/auto-updater/auto-updater-win.coffee#L8
  * https://github.com/atom/electron/blob/fbb8e61958c8950455883e2a4ae12088ba030a12/atom/browser/api/lib/auto-updater/squirrel-update-win.coffee#L40

@raleksandar that's with electron 0.35.4 or higher ?

I'm pretty sure our app loads too much before determining if it needs to quit or not, I'm going to fix that and see if that fixes it.

**Comment by raleksandar** [comment]
@fasterthanlime That's on 0.35.4 and 0.36.0, sorry for not mentioning that previously

**Comment by raleksandar** [comment]
btw, @fasterthanlime you should definitely check for Squirrel arguments as soon as possible.I have `require('./update.js');` as first line in my main.js and in update.js I first check for arguments from Update.exe:

```js
const path = require('path');
const spawn = require('child_process').spawn;
const minimist = require('minimist');

const exeName = path.basename(process.execPath);

function squirrel(args) {
    try {

        const child = spawn(
            path.resolve(path.dirname(process.execPath), '..', 'Update.exe'),
            args, {
                detached: true,
            }
        );

        child.on('close', () => app.quit());

    } catch (e) {
    }
}

const args = minimist(process.argv);

if (args['squirrel-install'] || args['squirrel-updated']) {
    squirrel(['--createShortcut', exeName]);
} else if (args['squirrel-uninstall']) {
    squirrel(['--removeShortcut', exeName]);
} else if (args['squirrel-obsolete']) {
    app.quit();
}

// rest of update related code (attaching listeners on autoUpdater, etc)

```

**Comment by fasterthanlime** [comment]
You can tag this with 'user error' :) Here's what happened:

  * quitAndUpdate() called Update.exe
  * ...which signalled our app
  * ...which emitted the 'before-quit' event (which we ignored)
  * and then started closing windows. since our app has a tray icon, we preventDefault() close unless we know we're quitting (and I didn't quite understand the `before-quit` event until now)
  * as a result, the app never quit

Thanks all for the assistance (and wonderful pieces of software), hopefully my mistake will be useful to others who google their way through it :)

**Comment by bluetidepro** [comment]
@fasterthanlime How did you fix it then with your workflow you mentioned above? I'm running into the same issue...

**Comment by fasterthanlime** [comment]
@bluetidepro the main issue was that I was ignoring before-quit

I'm still experiencing the problem on OSX, but I'm also preventDefault-ing `window-all-closed` there, so it might have something to do with it.

**Comment by havenchyk** [comment]
@raleksandar I have the similar code to yours and my app cannot be started after `autoUpdater.quitAndInstall()`  on windows. Are you sure, it's working for you? I use makeSingleInstance as well.

**Comment by Darkzarich** [comment]
I had a similar issue, inspected every single post I found about this issue and hope it will help someone:

Electron documentation states this:
>  If application quit was initiated by autoUpdater.quitAndInstall(), then before-quit is emitted after emitting close event on all windows and closing them.

I had tray icon set for my app and `.preventDefault()` for window's `close` event. `autoUpdater.quitAndInstall()` tried to close all the windows and then `window-all-closed` even would fire and close the app but due to preventing default behavior it wasn't happening so the app wasn't quitting for update and then `app.requestSingleInstanceLock()` logic was preventing running another instance.

This is what I did after realizing what `before-quit` does when it's update that caused it:

```js
app.on('before-quit', () => {
  process.exit();
})
```
