### ISSUE TITLE
electron occasionally freezes (from crash) in headless browser testing

### ISSUE THREAD

**Issue by kaizhu256** [atom/electron#3820]
i've replaced phantomjs with electron @ v0.35.4 for my headless browser-tests.  it will occasionally crash (about 10% of time), when running an intentionally faulty browser script, to test failure-cases in my testing library.

here's the line where it fails on travis-ci (i have a separate detached process that will kill electron after 60 seconds):
https://travis-ci.org/kaizhu256/node-utility2/jobs/96600773#L728
![image](https://cloud.githubusercontent.com/assets/280571/11811467/a44d9834-a370-11e5-8342-a2fec67cc2da.png)

and here is the webpage with intentionally faulty javascript (throws an uncaught error) that will freeze electron
https://hrku01-utility2-beta.herokuapp.com/test/script-only.html?modeTest=consoleLogResult&modeTestCase=testCase_testRun_failure&timeExit=9999999999

![image](https://cloud.githubusercontent.com/assets/280571/11811253/772f2184-a36f-11e5-9e0d-a2e39e9c2efe.png)

i create a new BrowserWindow for the testpage, so it has no access to native nodejs features.
here is my headless browser test subroutine:
https://github.com/kaizhu256/node-utility2/blob/702c054f71094e5d37290bd681e6c829ecaffd58/index.js#L110

sorry i can't give more info about the cause of the bug.  i can't open the web inspector with recent releases of electron

P.S. electron @ v0.36.0 is unusable.  it always freezes, when running the error-script.
the 10% failure rate occurs when i enable istanbul-code-coverage on browser-side.
if i run tests without code-coverage, the freeze-failure drops to ~1%

**Comment by brian-mann** [comment]
I believe this is exactly what I am experiencing with #3803. I also have nodejs features disabled. Mine also hangs on version `0.35.4.` and `0.36.0`

**Comment by zcbenz** [comment]
@kaizhu256 Are you able to work out a test case for Electron?

**Comment by zcbenz** [comment]
Closing until more information is provided.
