### ISSUE TITLE
0.36.0 is not MAS compatible

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron#3823]
Guess this is related to the Chromium update. 

According to Apple:
"The app includes ': xpc_mach_send_get_right' from the framework '/usr/lib/libSystem.B.dylib'."

**Comment by raleksandar** [comment]
From v0.36.0 there is [a electron-v0.36.0-mas-x64 build](https://github.com/atom/electron/releases/tag/v0.36.0) have you been using that one?

**Comment by zcbenz** [comment]
This call [was added](https://chromium.googlesource.com/chromium/src/+/e624db4ce20b2f0f327c7436cf140867351487a0%5E%21/#F0) in Chrome 47, Chrome is also using other [xpc_ APIs](https://code.google.com/p/chromium/codesearch#chromium/src/sandbox/mac/xpc_private_stubs.sig&sq=package:chromium&type=cs) in older versions, not sure why they were not warned.

Anyway I'll try to remove all the `xpc_` calls.

**Comment by herrmannplatz** [comment]
Thanks for the fast response.

**Comment by herrmannplatz** [comment]
No complains, thanks again.

**Comment by JamyGolden** [comment]
I got rejected for this same issue and submitted the [electron-v0.36.7-mas-x64 build](https://github.com/atom/electron/releases/tag/v0.36.7). Hasn't this been resolved yet?
