### ISSUE TITLE
iframe spoof top level

### ISSUE THREAD

**Issue by rdbell** [atom/electron#3824]
node-webkit lets you give iframes the nwfaketop attribute. Documents loaded in these iframes don't know that they're in iframes. (window == window.top) returns as true.

Does electron have similar functionality? I'm trying to migrate my app from nw to electron right now.

**Comment by rdbell** [comment]
I may switch to using <webview> instead, because it seems to spoof toplevel by default, but I'd still like to know if this is possible with iframes.

**Comment by zcbenz** [comment]
No, we used to have a few options for controlling `iframe`, but they had been removed once the `<webview>` supported was added.
