### ISSUE TITLE
Opening devtools while in text input element writing "î" on french keyboards

### ISSUE THREAD

**Issue by whoisthecoon** [atom/electron#3828]
Here's the problem:

Opening devtools using the keyboard shortcut (`cmd` + `alt` + `i`) on a french AZERTY keyboard on OS X Yosemite happens to write an "î" (`alt` + `i` on french keyboard) if focus is on any text-input element (textarea, input, atom editor).
Spotted on Atom 1.3.1 (Electron v0.34.3).

I hope I provided enough information.

Thanks for the good work!

**Comment by zcbenz** [comment]
It has been fixed in Electron 0.36.0 and will be included in Atom once Atom updates the electron version.
