### ISSUE TITLE
cors mode for external domains in service worker

### ISSUE THREAD

**Issue by somebody32** [atom/electron#3831]
There is a strange problem when loading fonts from google in service worker:
Electron adds `credentials: 'include'` to fetch call, while Chrome 47 and Canary do `credentials: omit`.

As a result, request fails in Electron with CORS-violation error. I did an ugly workaround in a service worker:

```javascript
if (/fonts\.gstatic\.com/.test(url.host)) {
  request = new Request(request, {credentials: 'omit'});
}
```

But maybe there is a cleaner solution?

Full code to reproduce:

```html
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&subset=latin,cyrillic-ext,latin-ext,cyrillic" rel="prefetch stylesheet" type="text/css">
```

Service worker:

```javascript
self.addEventListener('fetch', fetcher);

function fetcher(event) {
  event.respondWith(fetch(event.request));
}
```

**Comment by somebody32** [comment]
Investigated more that case:

Initial request to google fonts is the same, but then there is a redirect wich differs in `credentials` field:

In chrome 47 and canary it is `omit`, but in electron it is `include`

**Comment by somebody32** [comment]
Updated the issue with new details and workaround

**Comment by zcbenz** [comment]
Can you provide a full example? It would makes it much easier for us to look into this.

**Comment by somebody32** [comment]
@zcbenz will be glad too:

**main.js for electron**:
```javascript
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

app.on('ready', function() {
  const mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL('http://localhost:8123');
});
```

You will need a simple server to serve static assets, SW is not working with `file:` scheme.
If you have ruby, you can do one-liner like that: `ruby -run -ehttpd . -p8123`

**index.html**

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&subset=latin,cyrillic-ext,latin-ext,cyrillic" rel="prefetch stylesheet" type="text/css">
  </head>
  <body>
    <h1>electron</h1>
  </body>
  <style>
    h1 {font-family: "Open Sans", Times, sans-serif;}
  </style>
  <script type="text/javascript">
    navigator.serviceWorker.register('sw.js').then(function(registration) {
      console.log('Registration succeeded.');
    }).catch(function(error) {
      console.log('Registration failed with ' + error);
    });
  </script>
</html>
```

**sw.js**
```javascript
self.addEventListener('fetch', fetcher);

function fetcher(event) {
  console.log('fetch from SW')
  event.respondWith(fetch(event.request));
}
```

If you run app once and then restart it (to register SW and then allow it to work), you should see something like this:
![screenshot 2015-12-17 13 58 49](https://cloud.githubusercontent.com/assets/25742/11870264/5abe9b4e-a4c6-11e5-95cb-0fa294a4a8ba.png)

But in plain Chrome 47 everything works. Hope that helps!
