### ISSUE TITLE
UAC elevation results in three electron instances when application is on `resources/app`

### ISSUE THREAD

**Issue by jviotti** [atom/electron#3834]
I'm facing a weird issue on Windows 10. I have an application that needs administration permissions. At startup, it checks for such permissions and they are not met, prompts for elevation using https://github.com/tehsenaus/windosu and re runs the application.

So far so good, however when downloading an electron zip and placing the application inside `resources/app`, for some reason my application is elevated three times.

I've built a small gist that reproduces the error: https://gist.github.com/jviotti/9cf7dc566c7e8766de91

First, run it with `electron-prebuilt` as follows:

```sh
$ npm install
$ npm start
```

The app is elevated and a single instance is shown.

![capture](https://cloud.githubusercontent.com/assets/2192773/11844506/8467e09a-a3e5-11e5-8807-dcc025d530d0.PNG)

Now download a zip from the releases page (you can download `0.33.9` which is the same version the gist installs with `electron-prebuilt`): https://github.com/atom/electron/releases/tag/v0.33.9, place the content of the gist in `resources/app` and run `electron.exe`. The application is elevated three times:

![capture1](https://cloud.githubusercontent.com/assets/2192773/11844872/6bfd5b1e-a3e7-11e5-8c6a-0c894a6f9b86.PNG)

### Things I've tried

- Various electron versions. The bug happens everywhere.
- Explicitly passing `resources/app` to the `electron.exe` binary from the zip.
- Explicitly passing `resources/app/index.js`.
- Debugging `windosu`. The module only executes the command passed to it exactly once, yet three instances appear.
- Download another `0.33.9` zip, place it in another directory and call `resources/app` from the original zip with the binary from the other zip. The issue still appears.
- Move my app outside `resources/app` can call it with the `electron.exe` binary from the zip. The issue still happens.
- Call my app inside `resources/app` with the `cli.js` script of an `electron-prebuilt` installation in another directory. It works fine.
- Call my app inside `resources/app` with the `dist/electron.exe` binary contained in `electron-prebuilt`. It works fine. 

Do you have any clues about what's going on?

**Comment by jviotti** [comment]
I get the following error when running the gist with `v0.36.0`:

![capture3](https://cloud.githubusercontent.com/assets/2192773/11847854/cd259b32-a3f5-11e5-8529-2a330a4a4776.PNG)

**Comment by zcbenz** [comment]
We can't debug every node module that doesn't work well with Electron, especially for ones like `windosu` that include lots of code. You can probably report this to the module's repo, and I'll reopen this once they found out which part of Electron doesn't work correctly.
