### ISSUE TITLE
Transparent window with transparent video ghosting since 0.36

### ISSUE THREAD

**Issue by diimdeep** [atom/electron#3836]
El Capitan
0.36.0

https://github.com/diimdeep/electron_transparent_video_ghosting

![test](https://cloud.githubusercontent.com/assets/485713/11855486/a99fd086-a45b-11e5-8ac4-04c65df258a9.gif)

**Comment by maxogden** [comment]
looks cooler imo

**Comment by zcbenz** [comment]
I suggest reporting this to Chromium's issues list instead, since this is completely controlled by Chromium's rendering code. I'm closing this since there is nothing we can do in Electron.

**Comment by diimdeep** [comment]
I'm not sure it is 100% Chromium because I observe this bug in simple BrowserWindow without extra options in latest 1.3.2 while Chromium rendering is ok.

Can someone check if they seeing same?
Just clone https://github.com/diimdeep/electron_transparent_video_ghosting and `npm install && grunt start` it will run 1.3.2 


`npm install && grunt exec:package_mac132 exec:package_mac35 exec:package_mac36`

You can check that 

- in 0.35.4 rendering is ok either in simple window or transparent

![0 35 4](https://cloud.githubusercontent.com/assets/485713/17462446/f175aa1c-5cb5-11e6-9fa6-b758218e4866.gif)

- in 0.36 transparent with glitch

![0 36 0](https://cloud.githubusercontent.com/assets/485713/17462447/fab47f40-5cb5-11e6-9523-4aebf31d1113.gif)

- in 1.3.2 both with glitches but little different.

![1 3 2](https://cloud.githubusercontent.com/assets/485713/17462448/05487a92-5cb6-11e6-92a5-a97a1a73b066.gif)

**Comment by diimdeep** [comment]
In nw.js same issue so this is Chromium after all..

**Comment by diimdeep** [comment]
But nw.js renders transparent webm in opaque window without glithes

**Comment by diimdeep** [comment]
nw.js is actually draws transparent window almost perfect.

**Comment by zcbenz** [comment]
You might want to try disabling hardware acceleration.

**Comment by diimdeep** [comment]
I tried, drawing is ok in opaque, in transparent still ghosting. And too slow.
