### ISSUE TITLE
main process use angularjs app report an error

### ISSUE THREAD

**Issue by mwylaoma** [atom/electron#3842]
Error : Uncaught AssertionError: path must be a string assert.js:89

**Comment by zcbenz** [comment]
Please include a reproducible example and information of Electron's version and which OS you are using.

I'll reopen when more information is provided.

**Comment by mwylaoma** [comment]
OK.The Electron's version is v0.36.0, OS is windows 10.
Here is the example : 
Main Process 
    appAll.on('ready', function () {
    mainWindow = new BrowserWindow({width: 1600, height: 1080/*, frame: false, fullscreen: true*/});
    mainWindow.loadURL("http://ip/test.html");
    mainWindow.on('closed', function () {
        mainWindow = null;
    });
});

test.html in remote server :
<html>
    <body>
           <div>
                <script type="text/javascript" scr="/lib/requirejs/require.js"></script>
           </div>
           <script type="text/javascript">
               require(['require','../require.config'],function (require,config){
                   .........
               }
           </script>
    </body>
</html>

**Comment by zcbenz** [comment]
`requirejs`  conflicts with Electron's `require` function, you can turn off `nodeIntegration` to work around this. Also https://github.com/yuki-takei/electron-angular-boilerplate provides a good guide.

**Comment by mwylaoma** [comment]
Do you mean this ?
```javascript

  <script>
    System.import('less');
    System.import('app');
  </script>

```

But if I do this,my project require.config 

```javascript
define({
    baseUrl: 'app',
    // Here paths are set relative to `/source` folder
    paths: {
        "domReady": "b/requirejs-domReady/domReady",
        "jquery": "b/jquery/dist/jquery",
        "jqueryui": "b/jquery-ui/jquery-ui",
    .....
```

must change,and the project struct will change a lot.

### Can use other ways to resolve the conflict?

**Comment by djangosdk** [comment]
From http://stackoverflow.com/questions/18867489/uncaught-assertionerror-path-must-be-a-string-error-in-require-js 

Looks like the new version of RequireJS has a function called: ```requirejs()``` in addition to ```require()``` to avoid conflicts with ```node's require()```
