### ISSUE TITLE
app.getLocale() always returns "" since v0.36.0 on Windows

### ISSUE THREAD

**Issue by meowlab** [atom/electron#3843]
Only Windows has this issue and I can confirm v0.35.4 is fine

**Comment by zcbenz** [comment]
I can not reproduce with the default app of v0.36.0. Can you check whether the `locales` folder exists along the binary files?

**Comment by meowlab** [comment]
Opps...
Yes the zero-byte files were filtered when decompress
When I add it, `app.getLocale()` came back
Thanks!

**Comment by havenchyk** [comment]
@zcbenz I haven't this folder along the binary files, but is it possible to get the locale in the development mode?
