### ISSUE TITLE
Electron based applications on Windows 10: There is always a console window opened

### ISSUE THREAD

**Issue by webarchymeta** [atom/electron#3846]
We have an application based on Electron (0.36.0) which runs fine on Windows 7. However when it is run on a Windows 10 machine, there is always a blank console window opened in addition to the application. Anyway to fix this problem?

**Comment by zcbenz** [comment]
Does this happen for older versions of Electron?

**Comment by webarchymeta** [comment]
yes, but I am not sure which version it was since it was uninstalled before installing the new one

**Comment by zcbenz** [comment]
Does the default app of Electron shows the console window?

**Comment by webarchymeta** [comment]
no, the default app behave normally, but when I use electron to run my own app, it appears. An ideas???

**Comment by zcbenz** [comment]
It is very likely some node modules used by your app are creating the console window.

**Comment by webarchymeta** [comment]
Oh, please don't close it that fast. The fact that the console window does not appear in any other cases (Windows 7, 8.1, Linux) indicate that Electron in itself has something not properly handled, am I right? Besides the main window, we do not use other visual module ...

**Comment by zcbenz** [comment]
You are probably right, but you need to provide a reproducible example.

**Comment by webarchymeta** [comment]
It appears that it's the
```
app.commandLine.appendSwitch('enable-logging');
```
line that is causing the problem. After removing the line, the console window disappears ...

However, this still seems to be at least an inconsistency in behavior
