### ISSUE TITLE
shell.openExternal not working when url contains pipe character

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron#3850]
I experienced, that when using an unescaped url that contains a pipe character shell.openExternal will not open this link. I am running electron v0.36.0 on OS X El Capitan.

For example google is making use of them (http://translate.google.com/translate?u=heise.de&hl=en&langpair=auto|en&tbb=1&ie=UTF-8)

#3849 solved this for me

**Comment by zcbenz** [comment]
Fixed by #3849.
