### ISSUE TITLE
session[.defaultSession].webRequest undefined

### ISSUE THREAD

**Issue by OlsonDev** [atom/electron#3852]
I've been reading over [session docs](https://github.com/atom/electron/blob/master/docs/api/session.md) and I can't seem to access `webRequest`; it's `undefined` no matter where I try to get it from. What am I doing wrong?

In the console:
![image](https://cloud.githubusercontent.com/assets/308072/11878632/b08ebe64-a4bc-11e5-91fd-783154cdf0ec.png)

In the main process:
```javascript
setTimeout(function() {
    console.log('webRequest?', !!mainWindow.webContents.session.defaultSession.webRequest);
}, 5000);
```
![image](https://cloud.githubusercontent.com/assets/308072/11878712/0393ba7e-a4bd-11e5-8698-074a64613182.png)

**Comment by deepak1556** [comment]
It is not yet been made available, wait for the next release.
