### ISSUE TITLE
method to get serialized remote object

### ISSUE THREAD

**Issue by cdaringe** [atom/electron#3856]
hi all:

i use `remote` to use an API within my main process.  i generally use that API simply to get raw data.  however, the returned object is a remote object (as clearly documented), riddled with getter/setters/etc to sync-get-send via IPC.  is there a way to get a serialized version of the remote object with ease?

thanks!

**Comment by cdaringe** [comment]
I forgot to add, JSON.stringify produces a max call stack, which _perhaps_ is expected.

```js
api = require('remote').require('/path/to/api/services/index.js');
setDataz = function(err, result) { JSON.stringify(result); } // kaaaboooom!!
api.bots.list(setDataz)
```

**Comment by cdaringe** [comment]
you know... i think i have a cycle.  brb

**Comment by cdaringe** [comment]
so the main process would have to `decycle`.  what if we detected if the call was coming from remote and decycled prior to passing?

**Comment by zcbenz** [comment]
You can use the `ipcRenderer` module to send raw data.
