### ISSUE TITLE
[question] ffmpeg codecs

### ISSUE THREAD

**Issue by smolleyes** [atom/electron#3857]
hi

what about ffmpeg codecs support in electron ? what s the supported codecs list please? and can we build a custom version with more codecs (if needed) :) ?

thanks

**Comment by zcbenz** [comment]
We are using the same codecs with the Chrome browser, the build flags of ffmpeg can be found at:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/ffmpeg/chromium/config/Chrome/win/x64/config.h&sq=package:chromium

It is possible to build with more codecs by modifying the build flags, but you need to hack into Chromium's source code yourself.

More information can be found at https://www.chromium.org/audio-video.
