### ISSUE TITLE
`remote.Menu` is undefinied

### ISSUE THREAD

**Issue by DerNivel** [atom/electron#3858]
Don't know if it's reported already but `require('electron').remote.Menu` returns `undefinied`.

Electron 0.35.4

**Comment by DerNivel** [comment]
Sorry. My mistake. Closing it.

**Comment by maronin** [comment]
What did you do to fix it? I am having the same problem

**Comment by DerNivel** [comment]
Sorry, I don't know anymore how I fixed it.
