### ISSUE TITLE
Notification icon is missing after packaging with ASAR on Windows 10

### ISSUE THREAD

**Issue by Rokt33r** [atom/electron#3866]
I'm using electron v0.35.4 and Windows10

<img width="457" alt="no-icon" src="https://cloud.githubusercontent.com/assets/5865853/11911250/76a7a0de-a652-11e5-99b4-2593c325f94f.png">

But, It works before packaging.

**Comment by paulcbetts** [comment]
This is a bug but if you want to work around it, set that icon to be as part of the unpacked part of the ASAR archive, then replace "app.asar" in the path with "app.asar.unpacked"

**Comment by Rokt33r** [comment]
Thanks you! I'll give a shot.

**Comment by debchy** [comment]
Snooze can't access app.asar file. So transfer the logo image to resource folder while the program first run. 
`
        let logoFile=path.join( __dirname, 'images','logo.png');
        let destinationFile=path.join(process.resourcesPath,'logo.png');
        var exists = fs.existsSync(destinationFile);
        if(!exists){
            fs.createReadStream(logoFile).pipe(fs.createWriteStream(destinationFile));
        }`
then in notification use that resource path.
`function sendNotification(title,message) {
    let applicationIconNewMessage=__dirname+"/images/new-message.png";
    if (electronBrowserWindow.isMinimized() || !electronBrowserWindow.isFocused()) {
        notifier.notify({
            title: title, message: message.substring(0, 25) + (message.length > 25 ? " .." : ""),
            wait: true, timeout: 4, icon: path.join( process.resourcesPath,'logo.png')
        });
        electronBrowserWindow.setOverlayIcon(applicationIconNewMessage, "new message");
    }
}`
