### ISSUE TITLE
[Critical Security Issue] Prevent iframe accessing his parent

### ISSUE THREAD

**Issue by ClementNerma** [atom/electron#3868]
I left Node-WebKit since a few month to use Electron because it's more adapted to my projects.
But, I've discovered a security issue in the iframe management :

We have two files, app.html and iframe.html.
In app.html, i put this code :

```html
<iframe src="iframe.html"></iframe>
```

And in iframe.html, this one :

```html
<script type="text/javascript">
    console.log(require);
</script>
```

This cause an error because I didn't allow iframe to use Node.js features.
But, if I write this :

```html
console.log(window.top.require);
```

It works ! I can use fs module, or even get process object for window.top.process !

Is there a way to fix that or can you fix that on Electron ?
Thanks by advance.

**Comment by paulcbetts** [comment]
You should use the `webview` tag to do this, which lets you disable node-integration

**Comment by ClementNerma** [comment]
When I use the `webview` tag the page never load... I've taken the example of the documentation 
```html
<webview id="foo" src="https://www.github.com/" style="display:inline-block; width:640px; height:480px"></webview>
```
But the page never load ;-(
I'm using the win32-x64 version.

**Comment by ClementNerma** [comment]
When I put this code in the `frame.html` file (using the `webview` tag) :
```html
<script type="text/javascript">
    console.log('hello');
</script>
```
Nothing happens...

**Comment by zcbenz** [comment]
If you are not using an ancient version of Electron, then you are probably encountering #1117.

For questions on using the webview, you can seek help from https://github.com/atom/electron#community.

**Comment by ClementNerma** [comment]
I'm using the latest version of Electron. I can use JavaScript in the two files, but my problem is I want to pass an object from `main.html` to `frame.html`. But because there isn't the `contentWindow` variable on the `webview` tag, how can I do it ?
