### ISSUE TITLE
Long filename problem with Windows

### ISSUE THREAD

**Issue by mulderp** [atom/electron#3870]
Hi,

just wanted to understand better how/if Electron apps can be packaged "smarter" to work in a Windows environment. (I don't like Windows, but some PCs in offices and labs use that unfortunately).

The example I tried was similar to https://gist.github.com/jedthehumanoid/a7f8278e0a37d259adca

Where I integrate some node modules for the serial port. After packaging and installing the binary, I saw quite a number of problems related to long filenames.

Feel free to close this issue, since it might lead to a discussion on a meta-level.

Thanks in any case!

**Comment by zcbenz** [comment]
It has been a long time headache for Node.js apps on Windows (https://github.com/nodejs/node-v0.x-archive/issues/6960), in Electron you can [package your app into asar archive](http://electron.atom.io/docs/v0.36.0/tutorial/application-packaging/) to work around it.
