### ISSUE TITLE
Access PKCS11 Certificate

### ISSUE THREAD

**Issue by chameleonbr** [atom/electron#3874]
Is there any way to access digital certificates by electron, sign something, using the PKCS11 on Electron? If not, would like to make a suggestion, Chrome works fine with certificates, it would be interesting to have the possibility too.

Thank you.

**Comment by zcbenz** [comment]
For using the system install client certificate, there is [select-client-certificate event](http://electron.atom.io/docs/v0.36.0/api/app/#event-39-select-client-certificate-39), for using a custom client certificate, there is [an issue](https://github.com/atom/electron/issues/1956) tracking it.

**Comment by abdalahshaban** [comment]
how can use select-client-certificate
