### ISSUE TITLE
ipc: I fail to use "require" from my .js files

### ISSUE THREAD

**Issue by dertuxmalwieder** [atom/electron#3876]
I'm currently building a small desktop application with Electron. My `index.html` contains a `<a href="#">` tag which should open an "About" window when being clicked.

The relevant part of my `index.html`:

    <html>
        <head>
        
        <script type="text/javascript" src="./assets/js/windowfuncs.js"></script>
        </head>
        <body>
            <a href="#" id="about">About this app</a>
        </body>
    </html>

`windowfuncs.js`:

    var ipc = window.require("ipc");
    $("#about").on("click",function() {
        ipc.sendChannel('openAboutWindow','About');
    });

Error in the dev tools: `require` is unknown.

I don't get it.

**Comment by paulcbetts** [comment]
Did you create the BrowserWindow with `nodeIntegration: false`?

**Comment by dertuxmalwieder** [comment]
Yes, for jQuery reasons.

**Comment by paulcbetts** [comment]
Yeah, so `require` doesn't work - load jQuery like this:

```
<script>window.$ = require('./path/to/jQuery')</script>
```

**Comment by dertuxmalwieder** [comment]
Hmm, OK. That seems to work, thanks.

(But it still does not react to the $.click event...)
