### ISSUE TITLE
HTML 5 Canvas Converter?

### ISSUE THREAD

**Issue by McFarts** [atom/electron#3879]
Was wondering if we use html 5 canvas inside atom that it can be converted to use openGL instead.

I'm creating an action rpg game similar to treasurearena and I need to access video memory (opengl) or whatever instead of using html 5 canvas, it's too slow.

The problem is I want to do everything in `Javascript`, it's my favorite language.

**Comment by zcbenz** [comment]
I don't know the answer, I suggest seeking help from the [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) mailing list.
