### ISSUE TITLE
Invalid documentation on IPC module

### ISSUE THREAD

**Issue by katacarbix** [atom/electron#3883]
I coped code from the documentation and ran it, and my console says:

    (electron) ipc module is deprecated. Use require("electron").ipcRenderer instead.

Please fix this in `electron/docs/api/ipc-main-process.md`.

**Comment by enlight** [comment]
I don't know where you copied the code from, but https://github.com/atom/electron/docs/api/ipc-main-process.md doesn't exist.

**Comment by zcbenz** [comment]
You should view the documentation that matches the version of Electron you use.

**Comment by katacarbix** [comment]
Oops, sorry. I was viewing it in the wrong branch. No wonder my code was wonky.
