### ISSUE TITLE
Audio stop playing when using dialog.showOpenDialog()

### ISSUE THREAD

**Issue by KeitIG** [atom/electron#3887]
Hello,

I have a classic 
```
var audio = new Audio('pathtofile.mp3');
audio.play();
```

and when I open a dialog, for example: 
``` javascript
var folders = dialog.showOpenDialog({ properties: ['openDirectory', 'multiSelections']});
```

the `audio` stop playing, and when I close the dialog, the audio resumes.

I think it was introduced with 0.36.1, any guess on it ?

**Comment by astoilkov** [comment]
When you don't specify callback to the `showOpenDialog` function it becomes a synchronous call. If you want for the music to continue playing you should probably go with `showOpenDialog(options. callback)` and provide it with second parameter callback function. This makes the call async.

**Comment by KeitIG** [comment]
Yes indeed, thanks for pointing it, I didn't see there was a change here, thanks a lot.
