### ISSUE TITLE
mac 0.36.1 shell.openExternal encode #

### ISSUE THREAD

**Issue by lin-chao** [atom/electron#3891]
os: mac
version: 0.36.1 

shell.openExternal("https://github.com#123")

when open browser , the url be encode like this:

https://github.com/%23123

test code is here:

```
"use strict"
const app = require('electron').app
const BrowserWindow = require('electron').BrowserWindow
const shell = require('electron').shell

app.on('window-all-closed', function() {
  app.quit()
})

app.on('ready', function() {

  shell.openExternal("https://github.com#123")

})
```

this code in 0.36.0 or win 0.36.1 is ok
open browser and url is https://github.com#123

**Comment by zcbenz** [comment]
This bug is caused by #3849.
