### ISSUE TITLE
No docs for versions like 0.35.1, 0.35.2 on atom.io

### ISSUE THREAD

**Issue by DerNivel** [atom/electron#3894]
Why there are no docs for this versions on atom.io
Often new APIs are added in theses versions but you can't find the documentation on atom.io

**Comment by zcbenz** [comment]
The documents are currently updated manually so they are a bit outdated, we will solve this once we implemented https://github.com/atom/electron.atom.io/issues/51.

**Comment by DerNivel** [comment]
Ah ok. Thanks for the information.
