### ISSUE TITLE
Add a way to force flushing localStorage

### ISSUE THREAD

**Issue by bpasero** [atom/electron#3895]
I am often seeing that the state in localStorage is not flushed to disk when Electron crashes abnormally. It would be nice if Electron could expose API to force a flush to disk of the storage state so that applications can periodically make sure all state is persisted.

**Comment by deepak1556** [comment]
Does [`enable-aggressive-domstorage-flushing`](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/content_switches.cc&sq=package:chromium&l=936&rcl=1450974613) help ? It changes the default domstorage commits duration to 1s. Other available way would be to expose `StoragePartition::Flush` which flushes pending commits available in the default duration to disk and also less IO expensive compared to the former.

**Comment by hadar111** [comment]
Have the same problem .. @deepak1556 how do you use 'enable-aggressive-domstorage-flushing' ?
I tried to run 
app.commandLine.appendSwitch('--enable-aggressive-domstorage-flushing’);
and 
app.commandLine.appendSwitch('enable-aggressive-domstorage-flushing’);
without success..

the localstorage data only commited to disk when the application is closed properly.

**Comment by bpasero** [comment]
Somehow I missed your comment @deepak1556. I second the question from @hadar111. I think having an explicit method to flush local storage to disk would be ideal.

**Comment by hadar111** [comment]
@bpasero did you tried it (method to flush local storage to disk) ?

**Comment by bpasero** [comment]
No I did not as it does not (yet) seem to be exposed in the JS API.

**Comment by bpasero** [comment]
Amazing, thanks so much!

**Comment by hadar111** [comment]
Thanks !
