### ISSUE TITLE
Failed to register SW

### ISSUE THREAD

**Issue by havenchyk** [atom/electron#3897]
When I'm trying to register service worker, it fails with following message

> Failed to register a ServiceWorker: No URL is associated with the caller's document.

Electron 36.0, ubuntu 14.04

Here is what I'm trying to do
```js
require('web-frame').registerURLSchemeAsPrivileged('file');

navigator.serviceWorker.register('my-worker.js', {scope: './'}).then((registration) => {
    console.log('Registration succeeded.');
}).catch(function(error) {
    console.log('Registration failed with ' + error);
});
```

Am I doing something wrong?

**Comment by havenchyk** [comment]
Is there any thoughts, guys?

**Comment by zcbenz** [comment]
Can you provide a full example?

**Comment by havenchyk** [comment]
Heh, can't reproduce. Maybe I had an old version of `electron-prebuilt` and didn't update it. Thanks!
