### ISSUE TITLE
Adding item to file system context menu on installation

### ISSUE THREAD

**Issue by rkpatel33** [atom/electron#3899]
How does Atom accomplish adding an 'Open with Atom' item to the context menu? Can this be done with the installer packager, or does it need some other customization?

![image](https://cloud.githubusercontent.com/assets/3799489/11964481/12c5890c-a8bc-11e5-8f13-9f5477e7d4d6.png)

**Comment by zcbenz** [comment]
You can find related code at https://github.com/atom/atom/blob/8fb4e887df800438b2deeb23a2c23004b9ff358a/src/browser/squirrel-update.coffee.
