### ISSUE TITLE
Dialogs showMessageBox and showSaveDialog blocks each other

### ISSUE THREAD

**Issue by anovi** [atom/electron#3901]
Hello. I use autoUpdater module in my app. I was saving file by showSaveDialog when message about update had appeared. It turned out that i could not submit neither of the dialogs. Even by keyboard.

![alsdfjalsdkjf_md__](https://cloud.githubusercontent.com/assets/3472054/11967480/39d35df0-a914-11e5-9cb7-30c45f0bd26f.png)

**Comment by zcbenz** [comment]
You should pass callbacks to the dialog APIs to turn them into asynchronous mode.
