### ISSUE TITLE
path.join not working in main process, yosemite, electron-prebuilt 0.35.2

### ISSUE THREAD

**Issue by BenjaminVerble** [atom/electron#3906]
OS: Yosemite 10.10.5
electron-prebuilt@0.35.2

- using path.join is not working in this case. only returns the result of pathPrefix variable, omitting the final argument to path.join
- regular string concatenation produces the correct results (was avoiding this b/c it is not cross-platform according to my understanding)

contents of get-user-save-location.js, required by main process

```
'use-strict'
const path = require('path')
const dialog = require('electron').dialog

module.exports = function (cb) {
    dialog.showOpenDialog({
        properties: ['openDirectory'],
        title: 'please select a directory...hint: dropbox, g-drive, etc.'
    }, path => {
        if (path) {
            const pathPrefix = path[0]
            const dbPath = path.join(__dirname, pathPrefix, 'app_db')
            cb(dbPath)
        } else {
            const pathError = new Error()
            pathError.message = 'proplem making this path'
            throw pathError
        }
    })
}
```

**Comment by paulcbetts** [comment]
![](http://cl.ly/3n2j041D342W/path.join_not_working_in_main_process_yosemite_electron-prebuilt_0.35.2__Issue_3906__atomelectron_2015-12-23_16-05-01.png)

**Comment by BenjaminVerble** [comment]
whoops. thank you
