### ISSUE TITLE
Documentation is unclear about when "unresponsive" event fires

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#3917]
I experimented with the unresponsive event today. However, I can't seem to successfully trigger it. I tried to simulate application hanging using an infinite loop but without success.

Can you clarify why the event is not being triggered? Then I could add more information to the documentation.

```js
// I tried executing this code after hitting Enter in our app
while (true) {}
```

```js
browserWindow.on('unresponsive', function () {
  require('dialog').showMessageBox({
    type: 'info',
    message: 'Reload window?',
    buttons: ['Cancel', 'Reload']
  });
});
```

**Comment by zcbenz** [comment]
We basically emit the event when Chromium tells us the window is unresponsive, there is no documentation on when it would be emitted:
https://code.google.com/p/chromium/codesearch#chromium/src/content/public/browser/web_contents_delegate.h&sq=package:chromium&type=cs&l=316
