### ISSUE TITLE
sending keyboard events serially

### ISSUE THREAD

**Issue by matthewmueller** [atom/electron#3930]
It appears that `sendInputEvent` (https://github.com/atom/electron/issues/2269) is an asynchronous event. This is causing problems if you'd like to type more than one character into a text box (see https://github.com/segmentio/nightmare/issues/414 for more information).

Is there anyway to execute these events serially or provide a callback or something when the input event has finished?

**Comment by zcbenz** [comment]
Chromium doesn't seem to provide related APIs.

**Comment by matthewmueller** [comment]
@zcbenz yikes, do you have any idea how we could send a word? as it stands, we can only send individual characters and those characters are not guaranteed to be in the proper order. this seems like it highly limits the usefulness of sendEvent :-/

**Comment by matthewmueller** [comment]
@zcbenz yesssss! thank you!!

**Comment by matthewmueller** [comment]
Hey @zcbenz, does this actually trigger keyboard events (keydown, keypress, keyup)?

**Comment by zcbenz** [comment]
@matthewmueller No it won't trigger keyboard events, only `textInput` event will be triggered, it works like pasting or dragging text into the window.
