### ISSUE TITLE
Mac: app.clearRecentDocuments() does not seem to have any effect

### ISSUE THREAD

**Issue by bpasero** [atom/electron#3932]
I am trying to clear the recent documents list that you see when you right click on an application in the dock. Calling this method, this list is not changed at all. I am on 10.11.

**Comment by bpasero** [comment]
@nishanths has this been verified? I am not able to clear the list of recent files and folders when calling `app.clearRecentDocuments()` in our bundled VS Code version, it does work though when we run "out of sources". I wonder if there is some extra requirement in application bundles to make this work properly?

This is with Electron 0.37.5.

**Comment by starriv** [comment]
Seems to have been repaired for a long time, but why is there an atom problem?

<img width="144" alt="qq20170321-182813 2x" src="https://cloud.githubusercontent.com/assets/7098001/24143291/31cf9ae0-0e64-11e7-953b-e36629c9c0a8.png">
