### ISSUE TITLE
HTML5 Canvas - Rendering Problems (Chart.js)

### ISSUE THREAD

**Issue by Bratkartoffl** [atom/electron#3935]
The current Chromium: 47.0.2526.73 Version causes problems while rendering charts within the html5 canvas element.
Does anyone have a workaround for this problem?

Please see this post for better illustration:
https://code.google.com/p/chromium/issues/detail?id=567308&q=status%3Aunconfirmed&sort=-id&colspec=ID%20Stars%20Area%20Feature%20Status%20Summary%20Modified%20OS

**Comment by zcbenz** [comment]
No we don't have a workaround for this, the only thing we can do is to wait for Chrome to fix the bug.
