### ISSUE TITLE
Instantly exits on Windows

### ISSUE THREAD

**Issue by snuggles08** [atom/electron#3937]
I get the error code 3221225620. Is it because my main file is inside a directory junction?

**Comment by zcbenz** [comment]
This error means `INTEGER_DIVIDE_BY_ZERO`, can you provide following information?

* The version of Electron and Windows.
* Does the default app work?
* Does your app work if you move it outside directory junction?

**Comment by zcbenz** [comment]
Closing until more information is provided.
