### ISSUE TITLE
remote fs.utimes fails with error.

### ISSUE THREAD

**Issue by brendon-gonzalez** [atom/electron#3939]
Below is an error I get after attempting to run `fs.utimes()` on a file. I am currently using version 0.36.2 on OSX 10.11.1.

<img width="550" alt="screen shot 2015-12-28 at 3 56 55 pm" src="https://cloud.githubusercontent.com/assets/2855044/12025323/aff72ab4-ad7b-11e5-8d00-c5c723c38d1a.png">
=====
Below is the code I ran just using the quick start [repo](https://github.com/atom/electron-quick-start).

__In index.html__
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <script>
    var remote = require('electron').remote;
    var fs = remote.require('fs');
    var path = '/Users/foo/bar.txt';
    var path = fs.readFileSync(path).toString();
    // To verify that remote fs works
    console.log(path);
    // Fails during the utimes call with the above error.
    fs.utimes(path, new Date(), new Date(), function (e, r) {
      console.log(e, r);
    });
  </script>
  <body>
  </body>
</html>
```
=====
Now, I could be doing something wrong here, but we came across this bug when we tried to upgrade from 0.33.6 to the latest version. We were using `utimes` just fine before where we were copying a file from point a to point b and had to set the times on the file after the copy had completed.

**Comment by zcbenz** [comment]
This is because for now `Date` is not supported when passing arguments to a remote function, I don't know why it doesn't throw error in 0.33.6.

To work around it, you can pass  a numberable string like `'123456789'`.
