### ISSUE TITLE
menuItem accelerator not working

### ISSUE THREAD

**Issue by djahma** [atom/electron#3940]
setting an accelerator on a menuitem does not launch the click function associated with that menuitem when adding a menuitem with Menu.append(menuitem).

**Comment by zcbenz** [comment]
Can you provide an example?

**Comment by djahma** [comment]
Here is code ran in the main process. The 'mip' var is path to some file on disk. And the 'lastmenu' object is the menuitem where I branch in the new **f** menuitem.
```
var txt = fs.readFileSync(mip,'utf8');
var f = eval(txt)
f = new MenuItem(f)
lastmenu.append(f)
```
And here is content of 'mip' file:
```
(function(){
   var o = {
      label: 'Console',
      accelerator: 'ctrl+j',
      click: function(item, focusedWindow) {
         console.log("Just do something")
      }
   }
   return o
})()
```
The menu gets updated fine and shows the **Console** label as well as its accelerator. Clicking that **Console** Menuitem does execute the click function. However, using the accelerator does nothing.

**Comment by zcbenz** [comment]
I'm not able to reproduce in a bare app, it should be something else in your code caused the problem, can you work out an example app?

**Comment by djahma** [comment]
I've actually found a way around that glitch, after `append(menuitem)` I call `Menu.setApplicationMenu(topmenu)` and the accelerator works. Therefore, I don't think that's a bug, but just an inconsistency. Anyway, here is a working example: https://copy.com/k7G1zrNjXsqSI6W1

There are 4 files you'd have to download into the same folder as the electron binary, and then :
`$ ./electron ./test.js` to launch the inconsistency demo.

Under **File** menu, you'll see a **Console** menuitem that's being added after the original items. That **Console** menu is displayed, and clicking it does trigger its click function. However, its accelerator does not work.
Now, in *test.js* file, if you uncomment the `Menu.setApplicationMenu(tmpmenu)` line, the accelerator will work.

I believe the `submenu.append()` function should set the accelerator too if it already show the menuitem...or not show anything until the Menu.setApplicationMenu() is called for a consistent behavior?

(apologies for the dirty code, I quickly pulled bits and pieces to get a working example)

**Comment by zcbenz** [comment]
The application menu and window menu objects in Electron can not be dynamically changed, this is because the menu object is only a model, not the actual native menu. So you have to call `Menu.setApplicationMenu` again when you added/removed items in the menu.

This design inherits from Chromium, the good part is menus can be easily reused between different parts of UI elements, but the bad part is it can not be dynamically changed.

**Comment by abhimatta999** [comment]
Can anyone help me out with creating new menu from renderer?
