### ISSUE TITLE
Adjacent main menu items require two clicks to close

### ISSUE THREAD

**Issue by joshas** [atom/electron#3951]
In native Windows applications when I open menu, move cursor to adjacent menu item and click - menu that is open closes.
In Electron it requires two clicks to close menu, e.g. click on menu item, move cursor to next one (note that focus still stays on first one), click - this moves focus to current menu item and one more click 
closes menu.
![menu](https://cloud.githubusercontent.com/assets/79141/12040513/44d961aa-ae72-11e5-857b-fd10b0c04041.png)

Windows 7, 64-bit
Electron 0.36.2

On a side note, menu works correctly on Xubuntu, although menu item still stays focused:
![menu-xubuntu](https://cloud.githubusercontent.com/assets/79141/12040582/fa218984-ae72-11e5-9fb4-3892aac27454.png)

**Comment by zcbenz** [comment]
I'm merging this to #3964.
