### ISSUE TITLE
ipcRenderer.send/ipcMain.on remove functions from parameters ?

### ISSUE THREAD

**Issue by KeitIG** [atom/electron#3963]
Hi !

I'm trying to get a context menu that does not block the renderer process, and I'm using `ipcMain` and `ipcRenderer` to achieve that.
Attach files by dragging & dropping,  Sélect. fichiers selecting them, or pasting from the clipboard.
Submit new issue

Here's my code:

``` javascript
var template = [
   {
       label : 'Add to queue',
       click : function() {
           console.log('add to queue');
       }
   },
   {
       label : 'Play next',
       click : function() {
           console.log('play next');
       }
   }
];

ipcRenderer.send('contextMenu', template);

```

and in my main process:
```javascript
ipcMain.on('contextMenu', function(event, template) {

    var contextMenu = Menu.buildFromTemplate(template);
    contextMenu.popup(mainWindow);
});
```

The menu appears fine but when I click on a `MenuItem`, nothing happens, and in fact, the `click` key is not even here anymore (was removed from the object). I tried to send functions as arguments directly, it's the same: they become `undefined` in the main process.

Is it the default behavior ?

(reproduced it on Ubuntu 14.04 and Windows 10, with Electron 0.36.2 and 0.35.2)

**Comment by DerNivel** [comment]
See here: #3923

**Comment by KeitIG** [comment]
Damn, so I have to find another way. Thanks.
