### ISSUE TITLE
Vue.js devtools extension not working

### ISSUE THREAD

**Issue by levani** [atom/electron#3966]
I'm trying to install `Vue.js devtools` but the tab is not appearing. I cloned the github repository https://github.com/vuejs/vue-devtools and run the followng commands from app console:

~~~
const BrowserWindow = require('electron').remote.BrowserWindow;
BrowserWindow.addDevToolsExtension('/Users/LM/Documents/extensions/vue-devtools/shells/chrome');
~~~

no errors are printed in console but the vue tab isn't appearing.

I'm using electron 0.36 and vue-devtools 1.0.5.

**Comment by zcbenz** [comment]
Vue.js devtools extension basically works the same way with React devtools extension, I'm merging this to #915.
