### ISSUE TITLE
Override `window.open` inheritance.

### ISSUE THREAD

**Issue by jamen** [atom/electron#3971]
I'm developing an application that uses SoundCloud's JavaScript SDK.  This SDK calls `window.open` internally with no way to alter the _`features`_ being passed in.

This is troublesome because `window.open` is being called from a window that had `show: false` during initialization, but was later unhidden, so the window created with `window.open` is actually still hidden (with now way to access it because it was created internally by SoundCloud).

Since this is an Electron addition, I would like to see a way to disable this inheritance or alter the options it's inheriting.

**Comment by DerNivel** [comment]
Just override `window.open`.

An example (not tested, but should work): 
```javascript
var originalWindowOpen = window.open;
window.open = function openWindow(url, frameName) {
    return originalWindowOpen(url, frameName, 'FEATURES_STRING');
}
```

**Comment by jamen** [comment]
Thanks, that's a nice workaround.
