### ISSUE TITLE
Main process doesn't print uncaught exceptions to console anymore

### ISSUE THREAD

**Issue by alvin-777** [atom/electron#3973]
Instead it prints a bunch of "undefined"s:
![image](https://cloud.githubusercontent.com/assets/13615512/12070396/ed266a86-b0bd-11e5-8f30-f3c33c303dd9.png)
This is very inconvenient when having unknown issues with our apps. 

Not sure since which version this problem occurred (probably v0.36.0), because I didn't even realise what those "undefined"s are until recently...

**Comment by zcbenz** [comment]
It is probably because you are catching `uncaughtException` in your app.

**Comment by alvin-777** [comment]
At the end I found than it was the colors js we use failed for some reason.
Thanks for your hint!
