### ISSUE TITLE
Is Electron adding "Origin: file://" to my outbound request? If yes how do I prevent this?

### ISSUE THREAD

**Issue by dukedougal** [atom/electron#3976]
The server that I am talking to is refusing to respond because the request from Electron contains a header with "Origin: file://"  I have no control over the target server so the only thing I can address is the client side (hopefully).

Is Electron adding this header?  How do I stop it? Hopefully something can be done because if not then it's not possible to talk to Amazon Web Services from electron which would be problematic.

thanks

**Comment by zcbenz** [comment]
I don't think Electron is adding this header, can you provide an example that reproduce the problem?

**Comment by karissa** [comment]
Have you tried using the `protocol` handlers? https://github.com/atom/electron/blob/master/docs/api/protocol.md

**Comment by zcbenz** [comment]
Closing until more information is provided.
