### ISSUE TITLE
Building for arm fails with due to misplaced -lrt argument

### ISSUE THREAD

**Issue by Juul** [atom/electron#3977]
During "ninja -C out/D electron":

```
undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Re-running the failed command with -lrt added at the end of the command succeeds. Note that -lrt is already part of the failed command but not at the end where it should be.

I'm not familiar with ninja. Anyone able to provide a fix?

**Comment by zcbenz** [comment]
You probably need to upgrade your toolchain version.

We have only tested cross compilation on Ubuntu 12.04 and 14.04, for other distributions you are largely on your own.

**Comment by Juul** [comment]
This is on Lubuntu 14.04. I should have specified.
