### ISSUE TITLE
process.stdout.write in iron-node

### ISSUE THREAD

**Issue by willhoag** [atom/electron#3979]
`process.stdout.write` in [iron-node](https://github.com/s-a/iron-node/) doesn't write to it's console.

```js
process.stdout.write("doesn't work")
console.log('works')
```
dependencies running on OSX 10.11.1
```
├─┬ iron-node@2.0.3
│ ├── commander@2.9.0
│ ├── electron-prebuilt@0.36.2
│ ├── electron-recompile@1.0.16
│ ├── electron-toaster@2.0.1
│ ├── markdown@0.5.0
│ ├── nmp@1.0.3
│ ├── open@0.0.5
│ ├── package.js@1.1.3
│ └── semver@5.1.0
```
My experience is limited with the inner workings of both *electron* and *iron-node*. Posting on behalf of @s-a per request https://github.com/s-a/iron-node/issues/30#issuecomment-168405636

**Comment by zcbenz** [comment]
`process.stdout.write` behaves exactly as the name says, writing output to stdout, not console. If you want to change the behavior, you can do:

```js
process.stdout.write = console.log
```

**Comment by etiktin** [comment]
I think you'll need to use
```js
process.stdout.write = console.log.bind(console);
```
Since the log method must be executed on the console object.
