### ISSUE TITLE
allowDisplayingInsecureContent not working in webview

### ISSUE THREAD

**Issue by lin-chao** [atom/electron#3982]
create a BrowserWindow with options: 
```
{
  ....
  "webPreferences": {
    "allowDisplayingInsecureContent": true
  }
  ....
}
```

i find a webview in this BrowserWindow , allowDisplayingInsecureContent not working.

is this a bug?

thank you~

**Comment by zcbenz** [comment]
Webview doesn't use `BrowserWindow`'s options, you have to set it separately for webview.

However for now we do not support setting allowDisplayingInsecureContent for webview, this is tracked at #2749.

**Comment by zhangalex** [comment]
@lin-chao  Just use allowRunningInsecureContent instead.

`  mainWindow = new BrowserWindow({
    autoHideMenuBar: true,
    webPreferences: {
      webSecurity: false,
      allowRunningInsecureContent: true
    }
  })`
