### ISSUE TITLE
Question: Possible to use a specific node version instead of build in shipped one?

### ISSUE THREAD

**Issue by s-a** [atom/electron#3984]
Hi,
I have a wide range of users reporting problems with different native modules they use with my electron application. I guess it is specificly changed and compiled for electron but might it be possible to define an external node version installed on the target machine to run in electron instead the default shipped one? 
If not, is it possible to compile the electron-prebuilt module against a specified node version?

**Comment by paulcbetts** [comment]
Nope, sorry. You need to rebuild the modules, read in the native module rebuild guide
