### ISSUE TITLE
IPC arguments not being sent from webContents.send

### ISSUE THREAD

**Issue by johnthedebs** [atom/electron#3985]
I'm sending a message (from a menu click callback) like so:

    focusedWindow.webContents.send("message", "zoom-in");

and listening for it in a preload script on a `webview`:

    var electron = require("electron");
    var ipc = electron.ipcRenderer;

    ipc.on("message", function(e, arg) {
        console.log("MESSAGE", e, arg);
    });

What happens:
When the menu item is triggered, the callback executes and logs "MESSAGE", the event object, and another object that also has a `sender` attribute but that's otherwise different than the event object.

Expected behavior:
When the menu item is triggered, the callback executes and logs "MESSAGE", the event object, and the second argument that I passed to `webContents.send`.

I'm running Electron 0.36.2 and OS X 10.11.2.

**Comment by zcbenz** [comment]
I'm unable to reproduce, it is probably the other parts of your code caused this problem. Can you provide a full example?

**Comment by johnthedebs** [comment]
Hey, I took a fresh look at this today and you're right that it was my other code. I was listening for the event in the renderer process and then sending it off again to the webview. I missed that code when upgrading; sorry for the distraction!
