### ISSUE TITLE
Fatal V8 error when debugging JavaScript

### ISSUE THREAD

**Issue by paul321** [atom/electron#3988]
Hi
When i'm trying to debug, it fails with the following message and after that i need to restart Electron, if i try it again it will fail at same point, self it's undefined and if i go step by step it happens

self.options.loading--;

<code>
 Fatal error in y:\jenkins\workspace\libchromiumcontent-win\vendor\chromium\src\v8\src\debug\debug.cc, line 511
 Check failed: !it.done() && (it.frame()->fp() == thread_local_.last_fp_).
</code>

**Comment by zcbenz** [comment]
I think it is a bug of V8, it would be great if you can work out a test case that can reproduce the problem in Chrome browser.

Refs https://github.com/nodejs/node/issues/3253.

**Comment by zcbenz** [comment]
Closing since it is a bug of V8 and there is nothing we can do with it in Electron.
