### ISSUE TITLE
Document `var tray = null` usage in tray.md

### ISSUE THREAD

**Issue by niftylettuce** [atom/electron#3990]
Per <https://github.com/atom/electron/issues/822> we should make it note "Does your app icon disappear after a minute?  Please make sure to define `var tray = null` and then once your app is ready `tray = new Tray(icon)` in order to prevent garbage collection and your tray disappearing.

**Comment by zcbenz** [comment]
It is just basic JavaScript, I'll add an FAQ chapter in the docs in future.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management
