### ISSUE TITLE
Something weird is going on with IPC since 0.35.x

### ISSUE THREAD

**Issue by bpasero** [atom/electron#4005]
I am seeing an issue both with 0.35.5 as well as latest 0.36.x when doing IPC communication between the browser side and the render side from a close event of a Window. 

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <script>
        var ipc = require("ipc");
        ipc.on("onClose", function(event, channel) {
            ipc.send(channel.channel);
        });
    </script>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node <script>document.write(process.versions.node)</script>,
    Chrome <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.
  </body>
</html>
````

**main.js**
```javascript
'use strict';

const app = require('app');
const ipc = require('ipc');
const BrowserWindow = require('browser-window');

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function () {
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform != 'darwin') {
        app.quit();
    }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.on('ready', function () {
    // Create the browser window.
    mainWindow = new BrowserWindow({ width: 800, height: 600 });

    mainWindow.on('close', function (event) {
        event.preventDefault();

        const channel = Date.now() + '';
        ipc.once(channel, function () {
            console.log('GOT IT')
        });

        mainWindow.webContents.send('onClose', { channel: channel });
    });

    // and load the index.html of the app.
    mainWindow.loadUrl('file://' + __dirname + '/index.html');

    // Emitted when the window is closed.
    mainWindow.on('closed', function () {
        // Dereference the window object, usually you would store windows
        // in an array if your app supports multi windows, this is the time
        // when you should delete the corresponding element.
        mainWindow = null;
    });
});
```

The sequence goes as follows:
* close the window
* this will trigger `close` event for the window on the browser side
* we `preventDefault()` to stop closing from happening and IPC a message to the window renderer side
* renderer receives this message and responds back
* the browser side does not print `GOT IT` so the message is lost

Interestingly this works when using the new `require("electron")` syntax (e.g. `require("electron").ipcMain` and `require("electron").ipcRenderer`

I think this is an issue when one of the IPCs or both use the classic import. For some weird reason I cannot get the new import to work in VSCode in this situation but I am hoping that the bug is the same as reported here.

**Comment by bpasero** [comment]
@zcbenz nevermind I think the issue on my end is that since 0.35 there is a new event object being send as first argument for "ipc.on" if you are on the renderer side. I think previously this was not the case.

**Comment by bpasero** [comment]
Still, it seems to me that require("ipc") and require("electron").ipcRenderer differ in this aspect and so the adoption is not just a replacement of the import. I think this should be made clearer.

**Comment by zcbenz** [comment]
In [the API changes blog post](http://blog.atom.io/2015/11/17/electron-api-changes.html) you can find guides on moving to APIs, including the `ipcRenderer` thing. We have remove all usages of `ipc` module in current docs, so for new comers will be no surprises.

**Comment by bpasero** [comment]
Thanks for the link.
