### ISSUE TITLE
[Question] interceptHttpProtocol leading to infinite loop

### ISSUE THREAD

**Issue by py09mb** [atom/electron#4008]
Trying to set up an interceptor to modify a websocket request. Leads to an infinite loop with the console.log being called continuously.

The most basic code snippet:

    function socketInterceptor (req, done) {
        console.log('Socket Request: ', req);
        return done(req);
    }

    protocol.interceptHttpProtocol('wss', socketInterceptor);

According to #2702 have also tried setting the session to null but this just closes the electron app after the first request has been intercepted.

    function socketInterceptor (req, done) {
        console.log('Socket Request: ', req);
        return done({
            url: req.url,
            method: req.method,
            referer: req.referer,
            session: null     
        });      
    }

    protocol.interceptHttpProtocol('wss', socketInterceptor);

Hopefully someone can point me in the correct direction, thanks :)

**Comment by zcbenz** [comment]
If you simply want to record or modify the requests, the `webRequest` API would be much better choice.

**Comment by py09mb** [comment]
Thanks for the response. Had a look at the webRequest API in the Session module but seems I can only cancel a request and redirect to another URL which breaks the websocket handshake.  I was looking to modify the url of the request before it was made which I thought was the function of the interceptor on Protocol, but I guess I was mistaken. 

I figured out another workaround in my project by overriding a function that builds up the websocket outside of electron so will close this if there is no actual issue. Thanks again!
