### ISSUE TITLE
BrowserWindow's `setOverlayIcon` method failing

### ISSUE THREAD

**Issue by johnthedebs** [atom/electron#4011]
BrowserWindow's `setOverlayIcon` method is failing for me with:

    Uncaught Error: Could not call remote function `setOverlayIcon`. Check that the function signature is correct. Underlying error: Error processing argument -1.

![screen shot 2016-01-06 at 3 47 32 pm](https://cloud.githubusercontent.com/assets/97469/12154342/eabdfa7a-b48c-11e5-91b8-24046562af41.png)

I'm on Windows 10, and ran into this issue with Electron versions 0.35.5 and 0.36.2. This API was working as expected with Electron v0.34.3.

To reproduce, run the quickstart app and paste the following into the devtools console:

    const electron = require("electron");
    const NativeImage = electron.nativeImage;
    var win = electron.remote.getCurrentWindow();
    win.setOverlayIcon(NativeImage.createEmpty(), "");

In case it makes a difference, I'm running a packaged app using `electron-prebuilt`.

**Comment by paulcbetts** [comment]
You can't pass NativeImages across remote boundaries since they're not serializable. Gotta set the overlay icon on the browser side.

**Comment by tborychowski** [comment]
Hi,
I'm having the same issue and cannot seem to find the answer.
I'm adding the overlay icon in the browser.
