### ISSUE TITLE
On Linux, hiding and showing a browserWindow removes the Application menu

### ISSUE THREAD

**Issue by bengotow** [atom/electron#4012]
This was reported by an N1 user earlier today (https://github.com/nylas/N1/issues/911). If you attach an application menu in your main process:
```js
  menu = Menu.buildFromTemplate(application_menu);
  Menu.setApplicationMenu(menu);
```

And then from a BrowserWindow, call `remote.getCurrentWindow().hide()`, followed by `show()`, the application menu does not re-appear when the window is shown. It seems that the menu is permanently gone.

Here's a small app that reproduces the issue:

[missingmenus.tar.gz](https://github.com/atom/electron/files/80393/missingmenus.tar.gz)

**Comment by leethomas** [comment]
Sounds like this https://github.com/atom/electron/issues/3869

I'll see if I can fix tonight

**Comment by steelbrain** [comment]
Bump

**Comment by steelbrain** [comment]
Thanks @zcbenz!

**Comment by akashnimare** [comment]
@bengotow not related but do you know any api which can tell if the system wakes up from hibernation? `powermonitor` 'resume' api does not work in that case 😞
