### ISSUE TITLE
Accessing elements inside Webview not working

### ISSUE THREAD

**Issue by xasos** [atom/electron#4013]
I'm trying to programmatically click on ID tags on a webpage. When I normally run the `.click()` function in jQuery in the website in chrome, the clicking works. However, in Electron this same code doesn't work - I suspect because the DOM changes on the Electron window. jQuery works with changing text on Google's homepage, but not on this site.

Here's the application I'm currently trying with: https://github.com/xasos/overcast-desktop
Electron: 0.36.0
OS: Mac OS X 10.11

**Comment by xasos** [comment]
I'm trying to programmatically click on ID tags on a webpage. When I normally run the `.click()` function in jQuery in the website in chrome, the clicking works. However, in Electron this same code doesn't work - I suspect because the DOM changes on the Electron window. jQuery works with changing text on Google's homepage, but not on this site.

Here's the application I'm currently trying with: https://github.com/xasos/overcast-desktop
Electron: 0.36.0
OS: Mac OS X 10.11

**Comment by zcbenz** [comment]
I'm merging this to #2425. For now you can call `executeJavaScript` API to execute code in webview.
