### ISSUE TITLE
libchromiumcontent-static

### ISSUE THREAD

**Issue by Sumxx** [atom/electron#4015]
Can you provide a download resource of China? 
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/osx/x64/0fbded6cf3d9244389db05f0c022e474a06ad32a/libchromiumcontent-static.zip 
Over the wall to download speed is too slow！fuck wall！

**Comment by zcbenz** [comment]
You can try https://github.com/hokein/libchromiumcontent-qiniu-mirror, I don't know whether it is still maintained though.
