### ISSUE TITLE
[v0.36.2 mac] require('electron').app undefined

### ISSUE THREAD

**Issue by hialan** [atom/electron#4017]
`require('electron').app` not work but `require('app')` is okay.
Just tried https://github.com/atom/electron-quick-start , and also got same error. 

seems require('electron').* all missing. 

change code to this: 
```
'use strict';

const electron = require('electron');
// Module to control application life.
const app = electron.app;

console.log(app);

// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow;
```
got following result: 
```
$ npm start

> electron-quick-start@1.0.0 start /Users/hialanMacAir/Work/electron-quick-start
> electron main.js

undefined
App threw an error when running [TypeError: Cannot read property 'on' of undefined]
```

**Comment by zcbenz** [comment]
You must have the npm `electron` module somewhere in your system, which overrides the builtin electron module. You can find out the path of it by logging out `require.resolve('electron')`.

**Comment by hialan** [comment]
Still the same...

$ npm install electron --save
electron@0.4.1 node_modules/electron
└── drip@1.1.0 (tea-concat@0.1.0)

```
'use strict';

const electron = require('electron');
// Module to control application life.
const app = electron.app;

console.log(app);
console.log( require.resolve('electron') );

// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow;
```
result

```
$ npm start

> electron-quick-start@1.0.0 start /Users/hialanMacAir/Work/electron-quick-start
> electron main.js

undefined
/Users/hialanMacAir/Work/electron-quick-start/node_modules/electron/index.js
App threw an error when running [TypeError: Cannot read property 'on' of undefined]
```

**Comment by hialan** [comment]
Sorry, my fault. 
I installed electron in my global path. 
After remove it then it going fine. 
Thanks.

**Comment by robin-drexler** [comment]
I get the same error. The electron module is installed in the project folder I started `electron .` in and not in some other global path.
I checked using `require.resolve('electron')`.
Or did what exactly did you mean by `builtin electron module`? @zcbenz 

Thanks in advance. :)

**Comment by maxfarseer** [comment]
I have same issue with menu example (app is undefined), from: http://electron.atom.io/docs/v0.36.5/api/menu/
Can anybody give me quick example on current version: 1 page application with custom menubar ?

**Comment by hialan** [comment]
Do not install node-electron ( https://www.npmjs.com/package/electron ) which is belong to another project. Just remove it and it will work. 

`npm remove electron`  (for local)
`npm remove electron -g`  (for global)

**Comment by btelintelo** [comment]
Thank you hialan.  This solved my problem.

**Comment by ericwgreene** [comment]
Hi maxfarseer, you can access the "app" using require("electron").remote.app.  Using the example you referenced:
```
{
  label: "Quit",
  accelerator: "Command+Q",
  click: function() {
    require("electron").remote.app.quit();
  }
}
```

**Comment by ackmanx** [comment]
For others that don't remember installing electron from npm...

IntelliJ was giving me a warning on `require('electron')` saying the module wasn't in my `package.json`, nor was it installed. Not knowing any better, I used IntelliJ's quickfix suggestions to get the warning to go away.

This installed it to my project's `node_modules `directory in a folder `electron`. After doing hialan's suggestion to remove locally, the problem was gone.

For reference, resolving electron without a problem shows the module installed in `electron-prebuilt`.

`/Users/varr/Dropbox/Code/Projects/Electron Explorer/src/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/exports/electron.js`

**Comment by yeganehaym** [comment]
what is require('app') and why removed?

i am using require('electron') but i have some old project that using require('app') in it and i got error

how to enable this feature?

**Comment by enlight** [comment]
> what is require('app') and why removed?

These modules are no longer available directly via `require` in order to prevent name collisions with other third party modules as discussed in #387.

> i am using require('electron') but i have some old project that using require('app') in it and i got error
> 
> how to enable this feature?

Electron v0.35.0 started issuing deprecation warnings about `require('app')`, and Electron v1.0.0 removed the ability to `require('app')` completely, so if you don't want to update your old code downgrade to the last release before v1.0.0.

**Comment by Pablodotnet** [comment]
I don't understand how this fix removing electron locally and globally can work, so how we are going to use "npm start" or run the app after this? :S I'm having this issue.

**Comment by enlight** [comment]
@Pablodotnet this doesn't really have anything to do with installing electron locally or globally. But if you install Electron locally you can start your app with `npm start` changing/adding the `start` NPM script to your `package.json` and set it to run `electron .` or `electron path/to/main.js`, e.g.

```
"scripts": {
  "start": "electron ."
}
```

**Comment by Pablodotnet** [comment]
Yes I know that, that's how I'm running the app and I have electron installed there in my app folder with npm install electron. But you are saying the error I'm having of the 'on' issue solves removing locally and globally so doing that, the script will not run because electron isnt installed neither globally and locally

**Comment by enlight** [comment]
> But you are saying the error I'm having of the 'on' issue

I have no idea what issue you're talking about, or what it has to do with this particular issue.

**Comment by Pablodotnet** [comment]
Im sorry if I didn't explain well the first time, I'm having the same problem as hialan was having, 

`App threw an error when running [TypeError: Cannot read property 'on' of undefined]`

When running npm start, the console in the electron app keeps giving me that error.

**Comment by enlight** [comment]
@Pablodotnet I suggest posting your issue in https://discuss.atom.io/c/electron along with the full error information.

**Comment by jrop** [comment]
I'm sorry to revive this, but I am having this issue on Mac OSX Sierra as well.

Here's my environment:

* no global electron installed (only local, via the `electron` package)

package.json
```js
...
"main": "index.js",
"devDependencies": {
    "electron": "^1.4.6"
}
...
```
index.js
```js
console.log(require('electron'))
```

Then I run:
```sh
$ ./node_modules/.bin/electron index.js
.../node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
```

What is the solution to resolve this?

**Comment by johnking** [comment]
I played electron long time ago and it worked very well. But I had the issue today - 2016 Nov 19!

I simply cloned `electron-quick-start` and `npm install && npm run start`, but I got errors:
```
app.on('ready', createWindow)
   ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/johnking/workshop/electron/electron-quick-start/main.js:40:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
...
```

I am using the latest electron version: electron@1.4.7

I googled the solutions and tried all kinds of workarounds but could not figure it out.

1. I tried to delete and reinstall the electron folder under node_modules
1. I tried to remove the globally installed electron module
1. I also tried logs:
```
console.log(require.resolve('electron'))
console.log(require('electron'))
```
but it did not give me much useful information.
```
/Users/johnking/workshop/electron/electron-quick-start/node_modules/electron/index.js

/Users/johnking/workshop/electron/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
```

thanks for any suggestions and help 

-John

**Comment by johnking** [comment]
I also tried delete the whole node_modules and reinstall it, the issue does not go away.

**Comment by jrop** [comment]
@johnking are you invoking electron from within tmux by any chance?

**Comment by hellosaumil** [comment]
@maxfarseer 

try, writing 

[const electron = require('electron')
var remote = require('electron').remote
const app = remote.app
](url)

 in [rederer.js](url)

**Comment by arcanosam** [comment]
I'm using nodejs 7.4.0 and electron 1.6.11

I use  require('electron').remote.app and works

thanks.

**Comment by jinfagang** [comment]
Still says app is not defined, I just place a tiny script below html:
```
<script>
    const {remote} = require('electron').remote;
    const app = remote.app;
    console.log(app.getVersion());
    document.getElementById('msg').innerHTML = remote.getGlobal('sharedObj').msg;

</script>
```
It says app is not defined. Any one knows what this means?

**Comment by enlight** [comment]
@jinfagang `const {remote} = require('electron').remote` is the equivalent of `const remote = require('electron').remote.remote`, you need to use `const {remote} = require('electron')`.

**Comment by jinfagang** [comment]
Waoh, Very Thanks Point this Out!!!!

**Comment by radiaph** [comment]
As of today (late Aug 2017), I find that `electron.app`works from the main process, but not from a renderer process, and `electron.remote.app` works from a renderer process, but not from the main process.  For example:

```
const electron = require('electron');
const app = (process.type === 'renderer') ? electron.remote.app : electron.app;
```

**Comment by RepComm** [comment]
I'm in VSCode 1.19.3, Node.js 8.9.3, and Electron 1.7.12.
I have the error "electron.app" is undefined. I was in the main process.

My launch.json had regular node js configurations:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/main.js"
        }
    ]
}
```

I switched that to Node js: Electron Main configuration:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Electron Main",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "program": "${workspaceFolder}/main.js",
            "protocol": "inspector"
        }
    ]
}
```

And I didn't have to change my code. I was running a slightly modified version of the example project. This fixed my problem.

**Comment by rip3rs** [comment]
I for some reason had this issue several times.

doing: `../node_modules/electron/dist/Electron.app/Contents/MacOS/Electron .` on the terminal it works

but... doing `node server.js` it did not work

but doing what @soware did it fixed the issue doing:
```
"scripts": {
"start": "electron ."
},
```

I believe that it's the path that node chooses that is the problem.
I don't believe it is an electron bug.

**Comment by trusktr** [comment]
Out of nowhere today, I started having this problem. No idea why. The only thing I changed in the last days has been type definitions, lint configs, and some dependency versions. I'm investigating...

**Comment by trusktr** [comment]
Okay, this is weird. I have this code in `src/index.js`:

```ts
import Electron = require('electron')
console.log(' >>>>>>>>>> ', Electron, ' <<<<<<<<< ')
console.log(' >>>>>>>>>> ', typeof Electron, ' <<<<<<<<< ')
```

When I run `npm start` which runs `electron src/index.js`, the output is this:

```
 >>>>>>>>>>  /Users/trusktr/src/test-project/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron  <<<<<<<<<
 >>>>>>>>>>  string  <<<<<<<<<
```

The type of the import is a `string`, containing the path to Electron. This is strange...

**Comment by MarshallOfSound** [comment]
@trusktr Sounds like you're running `node src/index.js` instead of `electron src/index.js`

Either that or the `ELECTRON_RUN_AS_NODE` env var is set 🤔

**Comment by trusktr** [comment]
Okay, well, I just took at look at `node_modules/electron/index.js`, and it contains this:

```js
var fs = require('fs')
var path = require('path')

var pathFile = path.join(__dirname, 'path.txt')

function getElectronPath () {
  if (fs.existsSync(pathFile)) {
    var executablePath = fs.readFileSync(pathFile, 'utf-8')
    if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
      return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath)
    }
    return path.join(__dirname, 'dist', executablePath)
  } else {
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  }
}

module.exports = getElectronPath()
```

So, um..... Why is it returning a string? Where are the APIs?

**Comment by trusktr** [comment]
Yeah, `ELECTRON_RUN_AS_NODE` is set. How'd that get set? 🤔

**Comment by trusktr** [comment]
I'm running a terminal inside of Atom editor. Is that why maybe?

**Comment by trusktr** [comment]
Note for anyone stumbling: The [`Termination`](https://atom.io/packages/termination) terminal plugin for Atom does not have this problem (does not set `ELECTRON_RUN_AS_NODE` in your env).

**Comment by abritabroad** [comment]
OMG, this issue! 
I ran into this because I was launching PowerShell from Visual Studio Code via an extension (CodeShell).
It was setting ELECTRON_RUN_AS_NODE.
I ended up removing it in my powershell profile with `Remove-Item env:ELECTRON_RUN_AS_NODE`

**Comment by kingmodus** [comment]
@trusktr
