### ISSUE TITLE
Real Kiosk Mode

### ISSUE THREAD

**Issue by sergiuwd** [atom/electron#4019]
I have developed a desktop app using Electron and I have to install it on 12 Windows 8.1 Tablets. The app is a virtual food menu and I need to prevent the users from getting out of the app. The problem is that Windows 8.1 has Charms Bars and it displays the menu over the app when I drag from the right edge. From there, they can get out of the app and go to the desktop. How can I prevent that? Is there a real kiosk mode for Electron? Or... do you have any solution?

Note:
http://www.askvg.com/how-to-disable-hot-corners-charms-bar-and-app-switch-list-in-windows-8-1/ - NOT WORKING
http://www.askvg.com/how-to-disable-charms-bar-hint-in-windows-8/ - NOT WORKING

**Comment by zcbenz** [comment]
Windows doesn't provide API for kiosk mode, so it is impossible for us to implement real kiosk mode in Electron.

But it is possible to set arbitrary program as kiosk mode on Windows, following links should be able to give you some ideas.
https://github.com/nwjs/nw.js/issues/3318#issuecomment-89281703
https://technet.microsoft.com/en-us/library/mt219051(v=vs.85).aspx

**Comment by syedhassaanahmed** [comment]
As @zcbenz pointed out above, I've [created a Kiosk demo](https://github.com/syedhassaanahmed/kiosk-demo-electron) which uses Shell Launcher to enable the app as custom shell.

**Comment by NoedeMora** [comment]
@syedhassaanahmed I downloaded your Kiosk demo for me is impossible to run and install and see how the app run. I need run an app in windows 10 without notifications windows on the right side of the screen. When i run my app and sweep from the right side of the screen appears windows 10 and the people go inside of them. Can you help with this? thanks in advance.

**Comment by syedhassaanahmed** [comment]
Hi @NoedeMora What part of the app is impossible to run and install? Can you please post the error or a detailed description. The app itself won't disable windows notification, you'd either have to do it in Windows settings or enforce it via an MDM solution ([Intune](https://docs.microsoft.com/en-us/intune/device-restrictions-windows-10) for example).

Another option is to build a [UWP app](https://docs.microsoft.com/en-us/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access#span-idappendix1uwpextensionspanspan-idappendix1uwpextensionspanspan-idappendix1uwpextensionspanappendix-1-uwp-extension) which works as a true kiosk app.

**Comment by NoedeMora** [comment]
@syedhassaanahmed sorry for the delay to response here, i run your electron in another computer with the care of your Readme instructions and now go fine.
Yes i search for something to run an electron app above of windows 10 to work in real kiosk. I try to search more info about UWP app. Thanks
