### ISSUE TITLE
Shell.openExternal parses hashtag which creates wrong url

### ISSUE THREAD

**Issue by bimusiek** [atom/electron#4022]
So, I am trying to open url with `shell.openExternal`.

Url looks like `https://myaccount.google.com/security#connectedapps`, however it is evaluated to `https://myaccount.google.com/security%23connectedapps` which returns 404 obviously.

How can I make it work? Is there any option to escape special chars to not escape them in shell? 

Cheers, Mike.

**Comment by zcbenz** [comment]
This was an old bug that had already been fixed in 0.36.2.

**Comment by denji** [comment]
Atom Beta 1.5.0 is trying to access myaccount.google.com, google.com, productforums.google.com
