### ISSUE TITLE
remote disregards properties defined when using Object.defineProperty

### ISSUE THREAD

**Issue by cdaringe** [atom/electron#4024]
hello!

Suppose I have simple object, `app = {};`.  Let's say that it is exported by `app.js`.

```js
var app = require('./app.js');
Object.defineProperty(
    app,
    'core',
    {
        get: function() {
            return require('coinstac-core').get();
        },
        set: function() { } // blah
    }
);
```

later if i `require('remote').require('./app.js')`, `app.core` is _undefined_.  However, if I modify the above to simply be

```js
var app = require('./app.js');
app.core = require('coinstac-core').get();
```

then `core` is exposed remotely, as expected.

I hope it was clear!  Thanks :)

**Comment by zcbenz** [comment]
The property needs to be `enumerable`.

**Comment by cdaringe** [comment]
Thanks @zcbenz, you rock
