### ISSUE TITLE
BrowserWindow.webContent.session.webRequest.on__ methods only work with defaultSession

### ISSUE THREAD

**Issue by christoth** [atom/electron#4036]
BrowserWindow.webContent.session.webRequest.on__ methods only work with defaultSession.

The webRequest lifecycle event listeners do not fire if registered to a session created with Session.fromPartition() and then assigned to the browserWindow.webContents.session.

e.g. (doesn't work)
var mainSession = require('electron').session.fromPartition('000');
mainWindow.webContents.session = mainSession;

Using 0.36.3 on Win7x64.

**Comment by zcbenz** [comment]
Changing the `session` property won't change a `webContents`'s session, you should set the `session` property when creating window.

**Comment by deepak1556** [comment]
@zcbenz would it make sense to provide a `setSession` api on webContents ? Since we allow creation of a session, we can allow to set that session ?

```
const newSession = session.fromPartition('test');
webContents.setSession(newSession)
// use session related apis..
```

**Comment by zcbenz** [comment]
@deepak1556 I don't think it is possible to change BrowserContext of an existing WebContents?

**Comment by deepak1556** [comment]
`NavigationController` allows us to change the browsercontext.

**Comment by christoth** [comment]
@zcbenz Thanks, I missed the relationship between the BrowserWindow webPreferences.partition and the webContents session.  Would it make sense to rename the property sessionPartition?

**Comment by zcbenz** [comment]
@deepak1556 There is no code in Chromium using that API, and I'm concerned about some lifetime problems, I'm not confident with using it.

@christoth `partition` is a already widely used name, renaming it to `sessionPartition` doesn't seem a good idea to me. Actually there is a `session` property of `webPreferences` that accepts a Session object, but I forgot to mention it in docs, I'll update the docs.
