### ISSUE TITLE
Attemting to call a function in a renderer process that has been closed or released while call app.exit

### ISSUE THREAD

**Issue by s-a** [atom/electron#4039]
Steps to reproduce:  

    
    var notify = function (msg) {
    	try{
    		Notification.requestPermission();
    		var notification = new Notification(msg.title, { body: msg.text, icon: '../logo/icon.png' });
    		console.log(notification);
    	} catch(e){
    		console.error(e);
    	}
    }

    notify({title:"hello", text:"world"});

Then click on the notifier to close the toast and call ```app.exit();```

    // I call this code from menu click or via Ctrl+w shortcut. tried but cannot catch it
    var app = remote.require("app");
    submenu: [
    	{
    		label: 'Exit',
    		click: function() {
    			try{
    				app.exit(0);
    			}catch(e){}
    		},
    		accelerator: 'Control+w'
    	}
    ]
        

![image](https://cloud.githubusercontent.com/assets/1270662/12217975/3cbede12-b711-11e5-94f5-b493d010a165.png)

**Comment by s-a** [comment]
using electron 0.36.3 on windows 10

**Comment by zcbenz** [comment]
Can you provide a reproducible example? The information you provided doesn't seem to be related with the error.

**Comment by s-a** [comment]
Yes you are right . just tried to reproduce. This hast obiiously nothing to do with the notification. This happens in general after ctrl+r in dev tools.

    git clone https://github.com/s-a/iron-node.git
    cd iron-node
    npm install
    
    // safe as notify.js
    var notify = function (msg) {
        try{
            Notification.requestPermission();
            var notification = new Notification(msg.title, { body: msg.text, icon: '../logo/icon.png' });
            console.log(notification);
        } catch(e){
            console.error(e);
        }
    }
    
    notify({title:"hello", text:"world"});
    
    // start in dev mode
    node_modules/.bin/electron ./app ../test/notify.js
    
    // focus devtools and use ctrl+r to reload
    // ctrl+w to exit.

**Comment by s-a** [comment]
I am wondering that alt+f4 works as expected. Is there something simillar I could use to close my electron application via API ?

**Comment by zcbenz** [comment]
When creating the application menu in renderer process, the click handlers of menu items are also in the renderer process, so once you closed or reloaded the window that created the menu, the click handler is also gone too. You can find more abound this at:
http://electron.atom.io/docs/v0.36.0/api/remote/#passing-callbacks-to-the-main-process

Alt+F4 works because the close command comes from the operating system, not from the menu.
