### ISSUE TITLE
Notifications doc: says only Windows supports `icon`

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4040]
http://electron.atom.io/docs/v0.36.0/tutorial/desktop-environment-integration/#windows says only Windows supports passing an image but OS X does too it seems. I would update the doc but I have no idea if Linux supports it, could someone confirm?

**Comment by zcbenz** [comment]
Actually all platforms support `icon`, but on Windows there was a limitation that `icon` can only be `file:` protocol. But this limitation was not true anymore in recent versions, I'll update the docs so it is up-to-date and not confusing.

**Comment by zcbenz** [comment]
Closed with 33b7b77.

**Comment by adam-lynch** [comment]
Thanks!
