### ISSUE TITLE
problem when use browserify

### ISSUE THREAD

**Issue by wendy0402** [atom/electron#4041]
Hi, I dunno If this is still issue since I already find the workaround. However want to tell it to help others solve this problem.
so I try to use electron and for the client side use browserify. However when I want to use module for Renderer Process using this(I assume it's like in your docs):
```
var ipcRenderer = require('electron'). ipcRenderer;
```
and browserify it, then it will raise error `cannot find module electron` since electron is not included in my `package.json`. However this is a built-in modules so of course no need to put it in package.json.

my workaround for this is as follow:
```
var ipcRenderer = window.require('electron'). ipcRenderer;
```

I hope it can be documented in your docs, so no other guys have this same problem :smile:

**Comment by zcbenz** [comment]
browserify uses its own version of `require`, which doesn't work with Electron's built-in modules.

**Comment by xywz** [comment]
Use `browserify --ignore-missing`.

**Comment by MaxGfeller** [comment]
If that is still an issue, here is how i solved it: http://maxgfeller.com/blog/2016/08/30/electron-browserify/
