### ISSUE TITLE
Transparent BrowserWindow & maximize method wrong behavior

### ISSUE THREAD

**Issue by yohaia** [atom/electron#4043]
I am using 0.36.2 on windows 8.1,
when trying to create my on title bar with action (frame = false), 
I saw that when using the maximize function ignore windows task bar size (my window go under it).
when try to re-size it back, the move it some where and again maximize, the window is off the screen.

When transparent flag is false/not set, everything working fine.

**Comment by zcbenz** [comment]
This is unfortunately impossible to fix, to show transparent window correctly we have to remove the `WS_THICKFRAME` and `WS_CAPTION` styles from the window, which then resulted in the problem you saw. For more about the technical background, you can read https://github.com/atom/electron/issues/734#issuecomment-169332056.

**Comment by Gaubee** [comment]
Is there a way to reset  transparent as false ? 
If can do it, then maximize can work.
But I still can not find the API.

**Comment by Dixeran** [comment]
There is a workaround. I create a frameless but not transparent window called `foo` with property `show: false`. When I need to maximize the main window (the transparent one), I do it like this:
```js
foo.maximize(); // this will make it show, and maximized like normal window
main.setBounds(foo.getBounds()); // this will let the transparent window size to the current bound
foo.hide(); // hide the auxiliary window
```
