### ISSUE TITLE
Crash on Windows in 0.36.3

### ISSUE THREAD

**Issue by flexpaper** [atom/electron#4049]
Please see dump below:

Operating system: Windows NT
                  10.0.10586 
CPU: amd64
     family 6 model 69 stepping 1
     4 CPUs

Crash reason:  EXCEPTION_ACCESS_VIOLATION
Crash address: 0x0

Thread 0 (crashed)
 0  ntdll.dll + 0xa5934
    rip = 0xf1ea5934   rsp = 0x4f2fda58   rbp = 0x00003184

Thread 1
 0  ntdll.dll + 0xa84f4
    rip = 0xf1ea84f4   rsp = 0x4f3ff368   rbp = 0x00000000

Thread 2
 0  ntdll.dll + 0xa84f4
    rip = 0xf1ea84f4   rsp = 0x4f4ffa38   rbp = 0x00000000

Thread 3
 0  ntdll.dll + 0xa84f4
    rip = 0xf1ea84f4   rsp = 0x4f5ff408   rbp = 0x00000000

Thread 4
 0  ntdll.dll + 0xa4f04
    rip = 0xf1ea4f04   rsp = 0x4f6ff6b8   rbp = 0x4f6ff820

Thread 5
 0  ntdll.dll + 0xa84f4
    rip = 0xf1ea84f4   rsp = 0x4f7ffae8   rbp = 0x00000000

Thread 6
 0  ntdll.dll + 0xa84f4
    rip = 0xf1ea84f4   rsp = 0x4f8ff4e8   rbp = 0x00000000

Thread 7
 0  ntdll.dll + 0xa84f4
    rip = 0xf1ea84f4   rsp = 0x4f9ffa78   rbp = 0x00000000

Thread 8
 0  ntdll.dll + 0xa4f04
    rip = 0xf1ea4f04   rsp = 0x4fbffc58   rbp = 0x4fbffd10

Loaded modules:
0x7ff644250000 - 0x7ff6489a9fff  electron.exe  0.36.3.0  (main)
0x7ffabc270000 - 0x7ffabce51fff  node.dll  5.1.1.0
0x7ffac2870000 - 0x7ffac295efff  msvcr120.dll  12.0.21005.1
0x7ffac2960000 - 0x7ffac2a05fff  msvcp120.dll  12.0.21005.1
0x7ffacf5b0000 - 0x7ffacf5bbfff  davhlpr.dll  10.0.10586.0
0x7ffad0110000 - 0x7ffad02c7fff  urlmon.dll  11.0.10586.17
0x7ffad7160000 - 0x7ffad71c9fff  oleacc.dll  7.2.10586.0
0x7ffad9cc0000 - 0x7ffad9f4dfff  wininet.dll  11.0.10586.17
0x7ffadea20000 - 0x7ffadeaa7fff  AudioSes.dll  10.0.10586.11
0x7ffadfb60000 - 0x7ffadfb69fff  version.dll  10.0.10586.0
0x7ffae0200000 - 0x7ffae020bfff  secur32.dll  10.0.10586.0
0x7ffae0800000 - 0x7ffae0a73fff  comctl32.dll  6.10.10586.0
0x7ffae15a0000 - 0x7ffae172bfff  dbghelp.dll  10.0.10586.0
0x7ffae20e0000 - 0x7ffae2163fff  winspool.drv  10.0.10586.11
0x7ffae2be0000 - 0x7ffae2e3ffff  DWrite.dll  10.0.10586.0
0x7ffae4d40000 - 0x7ffae4d54fff  wshbth.dll  10.0.10586.0
0x7ffae5430000 - 0x7ffae5447fff  usp10.dll  10.0.10586.0
0x7ffae7cc0000 - 0x7ffae8042fff  iertutil.dll  11.0.10586.35
0x7ffae9090000 - 0x7ffae9131fff  dxgi.dll  10.0.10586.0
0x7ffae9140000 - 0x7ffae93e7fff  d3d11.dll  10.0.10586.17
0x7ffae9900000 - 0x7ffae996ffff  MMDevAPI.dll  10.0.10586.0
0x7ffae9cc0000 - 0x7ffae9cd9fff  pnrpnsp.dll  10.0.10586.0
0x7ffae9e20000 - 0x7ffae9e2cfff  winrnr.dll  10.0.10586.0
0x7ffae9e30000 - 0x7ffae9e45fff  NapiNSP.dll  10.0.10586.0
0x7ffaea180000 - 0x7ffaea195fff  dhcpcsvc6.DLL  10.0.10586.0
0x7ffaea6b0000 - 0x7ffaea6c9fff  dhcpcsvc.dll  10.0.10586.0
0x7ffaea840000 - 0x7ffaea861fff  dwmapi.dll  10.0.10586.0
0x7ffaea870000 - 0x7ffaea8a7fff  IPHLPAPI.DLL  10.0.10586.0
0x7ffaea970000 - 0x7ffaeaaa5fff  WinTypes.dll  10.0.10586.0
0x7ffaeadc0000 - 0x7ffaeadd5fff  wkscli.dll  10.0.10586.0
0x7ffaeae20000 - 0x7ffaeaee7fff  winhttp.dll  10.0.10586.0
0x7ffaebd30000 - 0x7ffaebd47fff  nlaapi.dll  10.0.10586.0
0x7ffaec400000 - 0x7ffaec412fff  wtsapi32.dll  10.0.10586.0
0x7ffaec420000 - 0x7ffaec5a5fff  propsys.dll  7.0.10586.0
0x7ffaec9e0000 - 0x7ffaeca0bfff  WINMMBASE.dll  10.0.10586.0
0x7ffaeca40000 - 0x7ffaeca62fff  winmm.dll  10.0.10586.0
0x7ffaecda0000 - 0x7ffaece35fff  uxtheme.dll  10.0.10586.0
0x7ffaece40000 - 0x7ffaecee9fff  dnsapi.dll  10.0.10586.0
0x7ffaecef0000 - 0x7ffaecf16fff  devobj.dll  10.0.10586.0
0x7ffaed1a0000 - 0x7ffaed1d1fff  fwbase.dll  10.0.10586.0
0x7ffaed830000 - 0x7ffaed83bfff  netutils.dll  10.0.10586.0
0x7ffaedb80000 - 0x7ffaedb9efff  userenv.dll  10.0.10586.0
0x7ffaedcf0000 - 0x7ffaedd4bfff  mswsock.dll  10.0.10586.0
0x7ffaee090000 - 0x7ffaee0bcfff  sspicli.dll  10.0.10586.0
0x7ffaee340000 - 0x7ffaee34afff  CRYPTBASE.DLL  10.0.10586.0
0x7ffaee350000 - 0x7ffaee378fff  bcrypt.dll  10.0.10586.0
0x7ffaee420000 - 0x7ffaee42efff  kernel.appcore.dll  10.0.10586.0
0x7ffaee430000 - 0x7ffaee43ffff  msasn1.dll  10.0.10586.0
0x7ffaee440000 - 0x7ffaee48afff  powrprof.dll  10.0.10586.0
0x7ffaee490000 - 0x7ffaee4a3fff  profapi.dll  10.0.10586.0
0x7ffaee4b0000 - 0x7ffaeeaf3fff  windows.storage.dll  10.0.10586.0
0x7ffaeeb00000 - 0x7ffaeeb16fff  netapi32.dll  10.0.10586.0
0x7ffaeeb20000 - 0x7ffaeeba5fff  FirewallAPI.dll  10.0.10586.0
0x7ffaeec60000 - 0x7ffaeecc9fff  bcryptPrimitives.dll  10.0.10586.0
0x7ffaeecd0000 - 0x7ffaeed84fff  SHCore.dll  10.0.10586.0
0x7ffaeed90000 - 0x7ffaeef56fff  crypt32.dll  10.0.10586.0
0x7ffaeef60000 - 0x7ffaef147fff  KERNELBASE.dll  10.0.10586.0
0x7ffaef150000 - 0x7ffaef192fff  cfgmgr32.dll  10.0.10586.0
0x7ffaef200000 - 0x7ffaef207fff  psapi.dll  10.0.10586.0
0x7ffaef2c0000 - 0x7ffaef380fff  oleaut32.dll  10.0.10586.0
0x7ffaef7c0000 - 0x7ffaef85cfff  msvcrt.dll  7.0.10586.0
0x7ffaef860000 - 0x7ffaef9b9fff  msctf.dll  10.0.10586.0
0x7ffaef9c0000 - 0x7ffaef9c7fff  nsi.dll  10.0.10586.0
0x7ffaefa30000 - 0x7ffaefb4bfff  rpcrt4.dll  10.0.10586.0
0x7ffaefbc0000 - 0x7ffaefbfafff  imm32.dll  10.0.10586.0
0x7ffaefc00000 - 0x7ffaefd85fff  gdi32.dll  10.0.10586.0
0x7ffaeffc0000 - 0x7ffaf0102fff  ole32.dll  10.0.10586.0
0x7ffaf0110000 - 0x7ffaf01b6fff  advapi32.dll  10.0.10586.0
0x7ffaf01c0000 - 0x7ffaf0315fff  user32.dll  10.0.10586.20
0x7ffaf0320000 - 0x7ffaf042afff  comdlg32.dll  10.0.10586.0
0x7ffaf0430000 - 0x7ffaf06acfff  combase.dll  10.0.10586.0
0x7ffaf06b0000 - 0x7ffaf1c0efff  shell32.dll  10.0.10586.11
0x7ffaf1c10000 - 0x7ffaf1cbcfff  kernel32.dll  10.0.10586.0
0x7ffaf1cc0000 - 0x7ffaf1d1afff  sechost.dll  10.0.10586.0
0x7ffaf1d20000 - 0x7ffaf1d71fff  shlwapi.dll  10.0.10586.0
0x7ffaf1d80000 - 0x7ffaf1deafff  ws2_32.dll  10.0.10586.0
0x7ffaf1e00000 - 0x7ffaf1fc0fff  ntdll.dll  10.0.10586.20

**Comment by zcbenz** [comment]
Can you provide the dump file? You should be able to find it under `C:\Users\USERNAME\AppData\Local\Temp\APPNAME Crashes`. It is impossible to see what has happened from an unsymbolized report.

**Comment by zcbenz** [comment]
Closing until more information is provided.
