### ISSUE TITLE
Fail to customize notifications in Windows 10 Build 10586

### ISSUE THREAD

**Issue by taroxd** [atom/electron#4053]
I ran the scripts below:
```javascript
new Notification('A Title');
```

As the screenshot shows, however, `electron` does not show up in the `Show notifications from these apps` on Windows 10 Build 10586, while it does on Windows 10 Build 10240.
Therefore, I cannot disable the notification from electron, and neither can I change any settings about the notification.

![qq 20160111120856](https://cloud.githubusercontent.com/assets/6070540/12226819/f5fd9bc4-b85c-11e5-9b5c-0f6d00a37dc0.png)

**Comment by zcbenz** [comment]
Can you try setting Application User Model ID, and add a shortcut of your app in start menu?

**Comment by taroxd** [comment]
I tried with the following code:
```javascript
app.setAppUserModelId('poi');
```

Add I added a shortcut linked to `C:\Users\taroxd\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\electron.exe D:\poi`.

But it did not work. Have I done something wrong? Do I have to copy a clone of electron to run my app, instead of using the globally installed electron?

**Comment by zcbenz** [comment]
On Windows 8 to show notification for your app, you have to package your app as an independent app and install it in `%ProgramFiles%`, and then add a shortcut for it in start menu. I think Windows 10 is making things closer with Windows 8.

Anyway the change is on Windows's side, there is nothing we can do except for following exactly [what Microsoft's docs requires](https://msdn.microsoft.com/library/windows/apps/windows.ui.notifications.toastnotificationmanager.aspx).

**Comment by paulcbetts** [comment]
Hm, Slack isn't installed in Program Files and it's still in this list as of Win10 11082. We do set the app model ID in the shortcut though.
