### ISSUE TITLE
WebdriverIO + WebdriverCSS Screenshot failure

### ISSUE THREAD

**Issue by sebastianmenge** [atom/electron#4059]
hey everyone,

was setting up testing for my electron app with WebdriverIO and chromedriver as described in the readme and it worked perfectly fine.
Then i tried to use WebdriverCSS to do CSS regression testing with screenshots, which works totally fine, if i try to run it in a normal chrome browser.
But im getting the following error from chromedriver logs when running it in electron:

MacOSX 10.11.2 (El Capitan)
Electron 0.35.1

```
5802.755][DEBUG]: DevTools request: http://127.0.0.1:12135/json
[5802.757][DEBUG]: DevTools response: [ {
   "description": "",
   "id": "E2ADA59A-7B17-4A5D-A4F5-5E66E9CCC55B",
   "title": "App",
   "type": "page",
   "url": "http://localhost:8080/"
} ]

[5802.861][INFO]: RESPONSE GetWindowSize unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: content shell=)
[5802.861][INFO]: COMMAND Quit {

}
[5802.913][INFO]: RESPONSE Quit
[5802.913][DEBUG]: Log type 'driver' lost 467 entries on destruction
[5802.914][DEBUG]: Log type 'browser' lost 14 entries on destruction
```

Was wondering if this might be due to the non Supported "Background Pages" feature in electron or is there simply no automation extension in the electron chromium browser?

**Comment by zcbenz** [comment]
WebdriverCSS is using chrome extension's background script API, which is not supported by Electron for now.

I'm merging this to #915 since the root cause is same.

**Comment by kevinkir** [comment]
@zcbenz, I see the at #915 is closed, but I am still getting this error when trying to take screenshots from electron-chromedriver. Should this be re-opened?
