### ISSUE TITLE
Takes 20+ seconds to Load Electron on Win 7 SP1

### ISSUE THREAD

**Issue by SkaterDad** [atom/electron#4060]
While trying to use Visual Studio Code on my work computer, I experienced very long load times.  Here is a link to the [Issue I opened on the VSCode repo](https://github.com/Microsoft/vscode/issues/1855) which contains more details.

As part of my troubleshooting, I tried running Electron by itself and experience 20 second loading times.  I tried several versions from [mafintosh/electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and get the same result.

Attached are the CPU profiles captured from VS Code when doing a window reload.  If there are ways to capture the profiles while launching Electron, I'd be happy to do that.

[CPU-20160108T102601.zip](https://github.com/atom/electron/files/85843/CPU-20160108T102601.zip)

*System Specs*
 * Windows 7 Enterprise SP1
 * Intel i5-4590, 8GB RAM, Samsung 950Pro SSD
 * On a corporate network which forces us to use Symantec Endpoint.  I don't believe Symantec is the cause because VSCode launched quickly on our servers which also run Symantec.  This problem seems exclusive to our Win 7 machines.

**Comment by zcbenz** [comment]
From the CPU profile, most time were spent on `ChildProcess.spawn` and `ipc.sendSync`, e.g. creating child process and sending IPC messages. The only explanation I can find is the anti-virus program.

<img width="598" alt="screen shot 2016-01-12 at 9 56 11 am" src="https://cloud.githubusercontent.com/assets/639601/12252489/c1e32708-b912-11e5-97f7-1594aa0dff74.png">

**Comment by SkaterDad** [comment]
As much as I dislike Symantec Endpoint, I don't believe it is the cause.  It's processes show no significant CPU or disk utilization during the startup of Electron or VS Code according to profiles I recorded with Windows Performance Recorder.

This is backed up by our Win Server 2008 machines having no issues with Electron, despite having Endpoint with the same definitions installed.

**Comment by mattdell** [comment]
I am having a very similar issue. Can we reopen this?

**Comment by beaugunderson** [comment]
I'm also having this issue.
