### ISSUE TITLE
Not working in renderer process: on("will-download", ... item.setSavePath(...); ...)

### ISSUE THREAD

**Issue by markus-sommer** [atom/electron#4061]
Hello,

[`DownloadItem.setSavePath()`](http://electron.atom.io/docs/all/#downloaditem) is supposed to prevent the save dialog, which is exactly what I need. However, this doesn't work in a renderer process. The save dialog still appears. In fact, the `"will-download"` event handler is called *after* the save dialog appeared and had been closed. The code was contracted for this issue:
```js
require("electron").remote.getCurrentWebContents().session.on("will-download",
        function(event, item, webContents) {
    item.setSavePath(`C:\\Path\\${item.getFilename()}`);
});
```
Although, *this does work* in allowing you to cancel requests:
```js
require("electron").remote.getCurrentWebContents().session.webRequest.onBeforeRequest(
        function(...) { ... });
```
Also, `DownloadItem.setSavePath()` in the main process works as expected. It prevents the save dialog:
```js
let window = new require("electron").BrowserWindow();
...
window.webContents.session.on("will-download", function(event, item, webContents) {
    item.setSavePath(`C:\\Path\\${item.getFilename()}`);
});
```
Further, having a `"will-download"` event handler function in both processes basically works, because you can successfully use the `DownloadItem` in the renderer process to print the download status every second.

---

Unfortunately, I couldn't think of a workaround. I don't think there's any possibility to call a function of the renderer process from the main process synchronously and get a result which, then, could be used for `setSavePath()` to be called from the main process. Is there still some way to get the `setSavePath()` logic into the renderer process while this bug persists?

**Comment by zcbenz** [comment]
This behavior is intended, you can find more about it at:
http://electron.atom.io/docs/v0.36.0/api/remote/#passing-callbacks-to-the-main-process

And unfortunately there is no way to fix this for now, the download API exposed by Chromium is synchronous, unless we did a big refactor of related Chromium code, we have to live with it.

**Comment by markus-sommer** [comment]
Okay, thanks for the information!
