### ISSUE TITLE
Flash content protected with Adobe Access DRM not playable under Windows

### ISSUE THREAD

**Issue by eugirdor** [atom/electron#4063]
Flash videos that use DRM will play in Electron under Mac, but not Windows.  On Windows, Flash returns error 3364, which appears to be due to Flash not getting a "Device ID" from the browser when it requests one. https://forums.adobe.com/thread/1938250?start=0&tstart=0

I am able to play DRM videos in nw.js on both platforms (using the NPAPI Flash Player).

The issue seems to be referenced here: https://code.google.com/p/chromium/issues/detail?id=568249

The interesting comment is  # 6 in the Chromium bug report.

```
I assume you have enable_rlz=1 in your build?
```

I do not know much about Chromium's source, but it looks like all the code associated with generating a "Device ID" is wrapped in a `#if defined(ENABLE_RLZ)`.

I am assuming Electron's Chromium build does not have this flag enabled.  I am not sure how to verify that or how to go about enabling the flag if that is indeed the case.

Any help is much appreciated.

**Comment by eugirdor** [comment]
If you create an Electron build with Flash enabled in it, it is easy to test the issue by having the app load up the URL referenced in the Chromium bug report: http://drmtest2.adobe.com:8080/SVP/SampleVideoPlayer_FP.html

Loading the video http://drmtest2.adobe.com:8080/Content/anonymous.f4v will work on Mac and give a DRM error on Windows.

**Comment by zcbenz** [comment]
We don't have enable_rlz enabled in libchromiumcontent, that should be the problem. I'll try enabling it.

**Comment by kingio** [comment]
Sorry for reopening this issue but i'm not sure if this are the steps to set enable_rlz = 1 when building electron:
1. `git clone https://github.com/electron/electron.git`
2. Edit https://github.com/electron/electron/blob/master/script/build-libchromiumcontent.py#L34 adding a `'-enable_rlz 1'`:
`execute_stdout([sys.executable, build, '-R', '-enable_rlz 1','-t', args.target_arch])`
3. Build electron having `--build_libchromiumcontent` set:
`./script/bootstrap.py -v --build_libchromiumcontent`

¿Can you guys confirm this?
