### ISSUE TITLE
remote module don't work with ES6 class methods

### ISSUE THREAD

**Issue by jiaz** [atom/electron#4066]
ES6 classes treat member functions as non-enumerable in the instantiated class. However remote currently only works with enumerable properties, which means I have to use the old school prototype style to define classes for remote use. I find it a little bit inconvenient.

Here is an example:

in main process
```js
class ClientSocket {
    connect() {
        //..
    }
}
app.clientSocket = new ClientSocket();
```

in render process
```js
const clientSocket = remote.app.clientSocket;
clientSocket.connect() // this doesn't work because connect() is not enumerable.
```

I mostly write new code in ES6 style and I'd like to keep my code style consistent. Is there any way to enable remote for ES6 class?

**Comment by zcbenz** [comment]
It is quite a surprise to me that ES6 class methods are not enumerable.

**Comment by parro-it** [comment]
Taken from Dr. Axel Rauschmayer words: [Prototype methods Foo.prototype.* are writable and configurable, but not enumerable.](http://www.2ality.com/2015/02/es6-classes-final.html)

**Comment by jiaz** [comment]
@zcbenz Yeah, it's a surprise to me too. For now I can just use prototypes or reconfigure the properties. However to me it seems that it's necessary to provide some long term solution for this since eventually people will start using ES6 syntax and class is a nice feature to group functionalities.

One idea, is that possible to also include those non-enumerable own properties that are functions?
There is a stackoverflow answer here demonstrate some similar ideas:
http://stackoverflow.com/questions/31054910/get-functions-of-a-class

However I think this does need some consideration and discussion.

**Comment by Robbilie** [comment]
I just wrote a whole stack of classes, put them into my main js file and was stuck for hours trying to find out why there were no methods on the classes when getting them with remote.require

i would love to be able to use the syntax instead of rewriting all the classes, is there a way to bypass this issue or any plans for the next release to include such functionality?
