### ISSUE TITLE
OS X: dialog.showMessageBox: icon option does nothing

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4073]
I've tried both passing the result of `nativeImage.createFromPath('/Users/adam/Desktop/x.png')` and just the string path as the `icon` but it's still just the Electron icon;

<img width="435" alt="screen shot 2016-01-12 at 23 39 49" src="https://cloud.githubusercontent.com/assets/1427241/12280473/065a0c94-b986-11e5-81f0-4cd15dea10c4.png">

**Comment by adam-lynch** [comment]
@zcbenz I see you added the bug label but could you confirm if the two things I tried would be ok if there wasn't a bug? I mean: if it was working, could I pass a string or the result of `nativeImage.createFromPath(filePath)`? Thanks.

**Comment by zcbenz** [comment]
It is a bug that the `icon` option doesn't work on OS X. Passing image's path as string or the `NativeImage` instance should both work.

**Comment by adam-lynch** [comment]
:+1:
