### ISSUE TITLE
dialog.showMessageBox: `cancelId` clarification

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4074]
Sorry for all the issues, doing a bit of research into the APIs :). So, `cancelId` has this description:

>`cancelId` Integer - The value will be returned when user cancels the dialog instead of clicking the buttons of the dialog. By default it is the index of the buttons that have "cancel" or "no" as label, or 0 if there is no such buttons. On OS X and Windows the index of "Cancel" button will always be used as cancelId, not matter whether it is already specified.

If you don't have a `cancel` or `no` button and `0` is used, will the callback be called with `1` if your first button is clicked, `2` if the second is clicked, and so on?

Also, about this bit:

>On OS X and Windows the index of "Cancel" button will always be used as cancelId, not matter whether it is already specified.

What happens if there is no `Cancel` button?

**Comment by zcbenz** [comment]
> If you don't have a cancel or no button and 0 is used, will the callback be called with 1 if your first button is clicked, 2 if the second is clicked, and so on?

The callback will be called with button's index when button is clicked, so 0 for 1st button. 

> What happens if there is no Cancel button?

Then it would follow the `cancelId`.

[The community](https://github.com/atom/electron#community) is usually a better place for this kind of questions, and the best way is to try it yourself.

**Comment by adam-lynch** [comment]
>The callback will be called with button's index when button is clicked, so 0 for 1st button.

So you can't tell if they clicked the button or cancelled then?

>The community is usually a better place for this kind of questions, and the best way is to try it yourself.

Ok thanks, noted. I felt like this was verging on bug territory so I put it here. Like what I'm saying above about not knowing if a button was clicked or if it was cancelled. Thanks
