### ISSUE TITLE
Module version mismatch when using webFrame.setSpellCheckProvider example.

### ISSUE THREAD

**Issue by jeremy-dimasuay** [atom/electron#4077]
[Electron webFrame docs]:https://github.com/atom/electron/blob/master/docs/api/web-frame.md
[Electron quickstart project]:https://github.com/atom/electron-quick-start

Apologies in advance if this is an issue in the spellchecker project.

The [Electron webFrame docs] have the following example for using this plugin:

```
webFrame.setSpellCheckProvider("en-US", true, {
  spellCheck: function(text) {
    return !(require('spellchecker').isMisspelled(text));
  }
});
```

Using this example results in the following error: 
```
App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
```

Additionally I was able to reproduce on the [Electron quickstart project] after cloning the project:
```
npm install --save spellchecker
npm install && npm start
```

Thanks for any assistance in advance.

**Comment by zcbenz** [comment]
Native modules have to be compiled against Electron's headers.
http://electron.atom.io/docs/v0.36.0/tutorial/using-native-node-modules/
