### ISSUE TITLE
Dialog: showErrorBox or entire API can be called before ready?

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4078]
>This API can be called safely before the ready event the app module emits, it is usually used to report errors in early stage of startup. If called before the app readyevent on Linux, the message will be emitted to stderr, and no GUI dialog will appear.

This at the end after the `showErrorBox` summary. Does it apply to the whole API? I know it says "API" but just want to be safe.

**Comment by zcbenz** [comment]
Only showErrorBox can be called before the ready event.

**Comment by adam-lynch** [comment]
:+1:
