### ISSUE TITLE
undefined ipcRenderer

### ISSUE THREAD

**Issue by gsantome** [atom/electron#4081]
Good morning guys, yesterday I updated the version of electron and now I'm having a lot of problems. I got the latest version of electron-prebuilt and electron and this is my problem

```javascript
var ipc = require('electron').ipcRenderer;
console.log(ipc);
```
the console.log print undefined...

I have no idea whats going on...

```javascript
"electron-prebuilt": "^0.36.3"
"electron": "^0.4.1"
```

Thanks

**Comment by jean-emmanuel** [comment]
https://github.com/atom/electron/issues/3577#issuecomment-159578340

```require('ipc-renderer')```

**Comment by parro-it** [comment]
on #3661 @zcbenz said: 

> require('electron').ipcRenderer  is the correct one

**Comment by parro-it** [comment]
If the snippet you paste is from your package.json, you probably depend on [paradox electron module](https://www.npmjs.com/package/electron) for mistake. This module has nothing to do with electron platform. You only need  electron-prebuilt dependency.

Maybe your problem is due to the fact that you get this module when you `require('electron')` you get paradox module instead of Electron builtin. Try remove it

**Comment by zcbenz** [comment]
The npm `electron` module conflicts with electron's built-in module, if you want to use the npm module you have to use `require('ipc-renderer')` instead of `require('electron').ipcRenderer`.

**Comment by gsantome** [comment]
@zcbenz why the documentation haven't got that information? 

Thanks for your help

**Comment by gsantome** [comment]
@zcbenz and @parro-it I remove electron-prebuilt and now I'm using just electron npm module, but when I'm trying to run require('ipc-renderer') I'm getting 
```
Cannot resolve module 'ipc-renderer'
```
could someone help me?

**Comment by parro-it** [comment]
You should keep `electron-prebuilt` module: it contains electron platform binaries you want to use to start your app. These binaries contains the prebuilt  `ipc-renderer` module you want to use.
You should instead remove `electron` module you found on npm: it has nothing to do with electron platform, it's just a case of [homonymy that is causing confusion](https://github.com/logicalparadox/electron/issues/10)
I suggest you to start with a boilarplate. You'll find a list of them on [awesome-electron](https://github.com/sindresorhus/awesome-electron) repo.

**Comment by gsantome** [comment]
@parro-it I found the problem... Im using web pack and this is the configuration that i need to add

```javascript
//webpack.config.js

        plugins: [
		new webpack.ExternalsPlugin('commonjs', [
			'desktop-capturer',
			'electron',
			'ipc',
			'ipc-renderer',
			'native-image',
			'remote',
			'web-frame',
			'clipboard',
			'crash-reporter',
			'screen',
			'shell'
		])
         ]
```

thanks for your help

**Comment by parro-it** [comment]
YW

**Comment by FelikZ** [comment]
@parro-it 

> Note As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-prebuilt name is deprecated, and will only be published until the end of 2016.

https://www.npmjs.com/package/electron

**Comment by oliveirafhm** [comment]
This error also catch me, and I **solved** it changing the constructor of BrowserWindow (in the main process) as follows:

`let mainWindow = new BrowserWindow({
    width: 600,
    height: 400,
    webPreferences: {
        nodeIntegration: true
    }
  });`

Mac OS X 10.11.6
Node v12.12
"electron": "^7.1.1"

**Comment by NathanHawks** [comment]
@oliveirafhm your fix worked for me as well.

**Comment by rishabbhattacharyya** [comment]
> @parro-it I found the problem... Im using web pack and this is the configuration that i need to add
> 
> ```js
> //webpack.config.js
> 
>         plugins: [
>         new webpack.ExternalsPlugin('commonjs', [
>             'desktop-capturer',
>             'electron',
>             'ipc',
>             'ipc-renderer',
>             'native-image',
>             'remote',
>             'web-frame',
>             'clipboard',
>             'crash-reporter',
>             'screen',
>             'shell'
>         ])
>          ]
> ```
> 
> thanks for your help

it worked for me, thanks
