### ISSUE TITLE
Focus stuck in Electron applications on raw X session

### ISSUE THREAD

**Issue by Terminus-IMRC** [atom/electron#4083]
Hello.

Normally, on a raw X session (i.e. without window managers), a window under the mouse cursor becomes active:
![1](https://cloud.githubusercontent.com/assets/4298265/12291256/8f5ecf90-ba29-11e5-852c-8a5ef21c8332.gif)

However, electron applications don't allow other windows to focus on even if the mouse cursor is over the other windows:
![2](https://cloud.githubusercontent.com/assets/4298265/12291310/c2ac42ec-ba29-11e5-85e9-f23f826f0738.gif)

I ran this application https://gist.github.com/Terminus-IMRC/aca2b09186e8ab7ae3e3 in the movie above.
And I used Electron v0.36.3 on Linux.

This behavior is inconvenient.
Why is this occurring and could you fix this?

Thanks in advance for your answers.

Regards,
Terminus-IMRC.

**Comment by zcbenz** [comment]
Does the Chromium browser work as expected?

**Comment by Terminus-IMRC** [comment]
No. Chromium has the same problem.
So, is this a Chromium issue?

**Comment by zcbenz** [comment]
Yeah Electron uses the same code with Chromium on drawing the window, reporting this to [Chromium's issues list](https://crbug.com) would be a better choice, since we are not able to fix this on Electron's side.

**Comment by Terminus-IMRC** [comment]
Thanks!
