### ISSUE TITLE
Pm2 startup causes electron app to be launched maximized not fullscreened

### ISSUE THREAD

**Issue by MassambaDiouf** [atom/electron#4085]
https://github.com/MassambaDiouf/Electron-FullScreen-HelloWorld

In Ubuntu 14.04 LTS:

When using Pm2 to launch an electron app at startup, the app will be maximized (panel will still be visible) not fullscreened. However if the pm2 process is deleted and relaunched it will then be fullscreened. I believe this is a problem with electron and Ubuntu, a link to a public repository has been added above that replicates the error.

**Comment by zcbenz** [comment]
On Linux if you want to make an GUI app run on startup, you have to follow your desktop environment's specification, such as [Desktop Application Autostart Specification](https://developer.gnome.org/autostart-spec/).

If you use other ways like pm2 to do that, there would be no guarantee that the app would start after the desktop environment gets ready, which results in the problem you saw.

**Comment by MassambaDiouf** [comment]
Thank you for your prompt reply, a true life saver.
