### ISSUE TITLE
ipc.send is not a function

### ISSUE THREAD

**Issue by joselevelsup** [atom/electron#4087]
So I have been using Electron and Angular to make a software for myself. When I use the ipc module to send a message, I get an error that says <code>ipc.send is not a function</code>. Can someone please help? 
 
In app.js for Main Process:
````javascript 
 ipc.on('open-new-window', function(){
    var newWindow = new windowPart({
        width: 1280,
        height: 700,
        resizable: true,
        show: false
    });
    newWindow.loadUrl('file://' + __dirname + '/www/windows/newWindow.html');
    newWindow.maximize();
    newWindow.on('closed', function(){
        newWindow = null;
    });    
});
````

In index.js for the Renderer Process:
````javascript
$scope.openWindow = function(){
       ipc.send('open-new-window');
   };
````

In the index.html:
````html
 <button type="button" class="btn btn-default btn-block" ng-click="openWindow();"><i class="glyphicon glyphicon-folder-open"></i> Open a new Window</button>
````

**Comment by zcbenz** [comment]
It seems that you are importing the ipc module in the wrong way, but since you didn't show other parts of the code, it is impossible to tell. Also the [community](https://github.com/atom/electron#community) is a better place for this kind of questions.

**Comment by joselevelsup** [comment]
I use <code> require </code> to load in the ipc module.
