### ISSUE TITLE
new IPC Modules

### ISSUE THREAD

**Issue by gsantome** [atom/electron#4093]
I already build an app with electron (http://getgala.me) and thanks god i didn't updated the latest version of electron... Now I'm building another app with the latest version but now ipc documentation sucks... in another issue someone told me we need to user require('ipc-renderer') but didn't work... and require('electron').ipcRenderer didn't work too... so i have no idea whats going on and how to solve it...

Thanks!

**Comment by gsantome** [comment]
another problem here is when we use WebPack, I think it's the same problem with Broserify... if I tried to require ipc-renderer of course its failing because don't find that module... but if I remove that line and I added a debugger... then require('ipc-renderer') in the console works fine.

**Comment by gsantome** [comment]
I solve this problem... it will be nice to put this inside the documentation

```javascript
//webpack.config.js

        plugins: [
		new webpack.ExternalsPlugin('commonjs', [
			'desktop-capturer',
			'electron',
			'ipc',
			'ipc-renderer',
			'native-image',
			'remote',
			'web-frame',
			'clipboard',
			'crash-reporter',
			'screen',
			'shell'
		])
         ]

**Comment by L-A** [comment]
The page you're looking for is http://electron.atom.io/docs/v0.36.0/api/ipc-main/.

For your main process:
```javascript
const ipcMain = require('electron').ipcMain;
```

For your renderer(s):
```javascript
const ipcRenderer = require('electron').ipcRenderer;
```

Also note that callbacks on both sides now receive the event as their first argument, so it's possible that you have to change handlers like this:

```javascript
ipcRenderer.on('simple-message', foo(bar)) // bar is an event
```
into this instead:
```javascript
ipcRenderer.on('simple-message', foo(event, bar)) // bar is your data
```

**Comment by zcbenz** [comment]
There is a blog post on migrating to the new APIs:
http://blog.atom.io/2015/11/17/electron-api-changes.html

**Comment by gsantome** [comment]
@L-A thanks for you reply... but what you are saying don't work if you use web pack for example... and the blog that @zcbenz is saying its exactly the same problem... don't work for web pack... I think web pack is one of the most popular tool for UI development so will be nice to have that documentation too.

Thanks again... i solve my problem with what i commented before

**Comment by L-A** [comment]
> but what you are saying don't work if you use web pack for example...

@gsantome I use Webpack to package with no issues. See [Electron React Boilerplate](https://github.com/chentsulin/electron-react-boilerplate) for a ready-to-use example where Webpack handles 0.36.2.
