### ISSUE TITLE
enableDeviceEmulation mobile screenSize viewSize

### ISSUE THREAD

**Issue by thisconnect** [atom/electron#4099]
I try to open a browser and take a screenshot, that works nicely. But exploring the dev tools does mess things up for me. I tired to openDevTools / enableDeviceEmulation on different events, but that has no effect as far as I can tell.

Neither of the enableDeviceEmulation params seem to have any effect for me. The dev tools are opening in a new window regardless of `detach` and the browser always chanages to 360 x 640, instead of my specified width and height.

Another effect is that if I manually change something in the dev tools interface, it will keep this setting next time I try, it is somehow cached. I am probably doing something wrong, I am stuck, help! :)

using electron-prebuilt 0.36.3 testing with `electron test.js`

```javascript
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

console.log('electron', process.versions.electron);
console.log('type', process.type);
console.log('node', process.versions.node);
console.log('chrome', process.versions.chrome);

app.on('ready', function(){

  const win = new BrowserWindow({
    width: 480,
    height: 640,
    webPreferences: {
      nodeIntegration: false,
      javascript: true
    }
  });
  // win.setBounds(options)

  const webContents = win.webContents;

  webContents.openDevTools({
    detach: false
  });
  // webContents.disableDeviceEmulation();
  webContents.on('devtools-opened', function(){
    console.log('devtools-opened');
  });

  webContents.enableDeviceEmulation({
    screenPosition: 'mobile',
    screenSize: { width: 480, height: 640 },
    deviceScaleFactor: 0,
    viewPosition: { x: 0, y: 0 },
    viewSize: { width: 480, height: 640 },
    fitToView: false,
    offset: { x: 0, y: 0 }
  });

  webContents.loadURL('https://www.google.com', {
    'extraHeaders' : 'pragma: no-cache\n'
  });

  webContents.on('dom-ready', function(){
    console.log('dom ready');
  });

  webContents.on('crashed', function(){
    console.log('crashed');
  });

  webContents.on('did-stop-loading', function(){
    console.log('did-stop-loading');
  });

  webContents.on('did-finish-load', function(){
    console.log('did-finish-load');
  });

});

app.on('window-all-closed', function () {
  // On OS X keep app open until Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

```

**Comment by zcbenz** [comment]
You should call `enableDeviceEmulation` after the page gets loaded.

I don't see any problem with window's size.

For the devtools problem, when `detach` is false the devtools will show with user's preference, so if you want it attached you should manually do it in devtools.

> Another effect is that if I manually change something in the dev tools interface, it will keep this setting next time I try, it is somehow cached.

This is expected behavior.

Also the [community](https://github.com/atom/electron#community) is a better place for this kind of questions.

**Comment by thisconnect** [comment]
I did not ser thr communit section thanks.

The problem about the size is that in my example 480x640 is defined wich is fine until the devtools open. After devtools opened the page shrinks inside the window to 360 x 640

**Comment by thisconnect** [comment]
https://discuss.atom.io/t/parameters-in-webcontents-enabledeviceemulation-have-no-effect/24550
