### ISSUE TITLE
Add webview.loadURL

### ISSUE THREAD

**Issue by christoth** [atom/electron#4101]
Could you please expose the extraHeaders option from WebContents.loadURL as a WebView attribute?
It would also be great to have access to loadURL on WebView as a method (like BrowserWindow).
Thanks

**Comment by zcbenz** [comment]
Adding `loadURL` to webview looks good to me. However adding `extraHeaders` attribute seems unnecessary, you can use the [webRequest](https://github.com/atom/electron/blob/master/docs/api/session.md#seswebrequest) API.

**Comment by christoth** [comment]
loadURL on webview would be great.

**Comment by CharlieHess** [comment]
@zcbenz is it as simple as this? https://github.com/atom/electron/pull/4186

**Comment by zcbenz** [comment]
yep.

**Comment by rishibhargava** [comment]
having some trouble with this API. If I dont have the src attribute in the webview to start with, then the loadURL gives an error - 

=================
<webview id='mainwebview' style="display:none;border:none;width:100vw;height:100vh;padding:0;margin:0"></webview>

function updateWebviewURL(u) {
          var webv = document.getElementById('mainwebview');
          if (webv) {
            webv.loadURL(u);
            webv.style.display = 'block';
          }
      };

================

Uncaught TypeError: Cannot read property 'loadURL' of undefined
node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:410

using electron-prebuilt version 0.36.7

Anyone else seen this scenario?

**Comment by azain** [comment]
Yeah, I am having the same issue! The documentation states that you should use the dom-ready event first:
```
webview.addEventListener("dom-ready", function() {
  webview.openDevTools();
});
```
But trying to use .loadURL inside this event's callback will trigger the dom-ready event again once it's loaded, which calls the .loadURL!!

**Comment by rishibhargava** [comment]
Yes this is indeed how it works. I dealt with this by just checking whether this is the initial load or not.

Rishi Bhargava
408-905-8344
Demisto.com<http://www.demisto.com/>

**Comment by azain** [comment]
Sure, me too. But I think that there should be a closer look into this, or not. It's just a bit weird.

**Comment by manuelro** [comment]
I'm having the exact same issue with 'webview.loadURL()', if I use it inside the 'dom-ready' handler it will fire the event again, and therefore create a URL loading bucle. Is this the intended behaviour?

**Comment by FlameOfIgnis** [comment]
I was having the same issue with the page below:
```html
<webview id="app" preload="./preload.js" style="width:100%; height:100%">
</webview>

<script>
ipcRenderer.on('load-url', (events,url)=>{
    webview.loadURL(url)
})
</script>
```

This will give the following error:
```
Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.WebViewElement.getWebContentsId (web-view-impl.ts:223)
    at HTMLElement.loadURL (web-view-impl.ts:266)
    at EventEmitter.<anonymous> (index.html:8)
    at EventEmitter.emit (events.js:210)
    at Object.onMessage (init.ts:50)
```

# Solution (More of a workaround)
Turns out this is caused by no source tag in webview. A quick workaround is just adding a dummy source to the initial webview

```html
<webview id="app" preload="./preload.js" src=false style="width:100%; height:100%"></webview>
```

**Comment by Slapbox** [comment]
@FlameOfIgnis unfortunately that didn't work for me, same error message.

**Comment by Slapbox** [comment]
This is like pulling teeth. I thought I could fix this issue in 10-15 minutes, but it's now the second hour with no end in sight. We really have to load a site just to call `loadURL`?

**Comment by kunfan96** [comment]
I use innerHtml,
```
const url = 'Your website'
document.body.innerHTML= `<webview style="height:100%" src="${url}" disablewebsecurity id="wv"></webview>`
```

**Comment by Slapbox** [comment]
It's highly inadvisable to use `disablewebsecurity`.
