### ISSUE TITLE
Segmentation fault without crash dump while viewing menu

### ISSUE THREAD

**Issue by ladenberger** [atom/electron#4103]
Sometimes I get an segmentation fault without crash dump when viewing the submenus of my menu items in the top menu bar. 

It is hard to reproduce this error since it happens sporadically. But I think a minimal electron application could help to reproduce this error: Create a minimal electron application with two menu items that have also submenus (with e.g. two submenu items). Click on both menu items alternately as long as the application crashes. 

I use electron v0.36.3.

**Comment by kevinsawicki** [comment]
@ladenberger What platform are you seeing this on? Or multiple platforms?

**Comment by ladenberger** [comment]
I am running electron on Linux-x64.

**Comment by zcbenz** [comment]
Can you try whether v0.36.2 has the problem? There was a menu bar change could be related.

And can you set the `ELECTRON_ENABLE_STACK_DUMPING` environment variable to `1` and then reproduce the crash? The stack trace would be printed in terminal and can be helpful.

```bash
env ELECTRON_ENABLE_STACK_DUMPING=1 electron ...
```

**Comment by ladenberger** [comment]
I just tried v0.36.2 and it seems that in this version everything works well.

Back to v0.36.3 - same problem. Here is the stack trace:

Received signal 11 SEGV_MAPERR 000000000009
#0 0x000001c8701b <unknown>
#1 0x7f7e626de340 <unknown>
#2 0x000002fc5850 <unknown>
#3 0x0000030e9bb3 atom::MenuDelegate::SwitchToSiblingMenu()
#4 0x000001c883e3 <unknown>
#5 0x000001ca3a4b <unknown>
#6 0x000001ca3d59 <unknown>
#7 0x000001ca3f3d <unknown>
#8 0x000001c7d2fa <unknown>
#9 0x7f7e5e4b9e04 g_main_context_dispatch
#10 0x7f7e5e4ba048 <unknown>
#11 0x7f7e5e4ba0ec g_main_context_iteration
#12 0x000001c7d1d6 <unknown>
#13 0x000001cb7140 <unknown>
#14 0x000002401e6b <unknown>
#15 0x000002401db0 <unknown>
#16 0x000002404ecd <unknown>
#17 0x0000023fd163 <unknown>
#18 0x0000010cb431 <unknown>
#19 0x0000010ca310 <unknown>
#20 0x00000304d5cc main
#21 0x7f7e5c54dec5 __libc_start_main
#22 0x000000532549 <unknown>
  r8: 0000000000000000  r9: 0000000000000001 r10: 0000000016a30282 r11: 0000000000000000
 r12: 00000000041cb0da r13: 00007ffc8ffbcd60 r14: 00000000033506f8 r15: 000012f97b2f5f60
  di: 0000000000000001  si: 000012f97b480800  bp: 00000000041cb0a8  bx: 000012f97b480800
  dx: 00007f7e63d69d70  ax: 00007ffc8ffbca98  cx: 00000000030e9ba0  sp: 00007ffc8ffbcad8
  ip: 0000000002fc5850 efl: 0000000000010202 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000009
[end of stack trace]

**Comment by zcbenz** [comment]
@ladenberger Thanks for testing old versions and pasting the stack trace, it is enough for fixing the crash.

**Comment by ladenberger** [comment]
@zcbenz perfect :smiley:
