### ISSUE TITLE
Question: way to store password

### ISSUE THREAD

**Issue by havenchyk** [atom/electron#4108]
Hi, sorry for the question here, but on forum there is no correct answer for me.

I'd like to store password for some time somewhere in the electron. The options that I found are
 - node-keytar
 - cookies

Maybe webcontents.session will also be helpful here.

Could anyone from electron team suggest any way to implement password storing functionality?
Thanks in advance.

**Comment by kevinsawicki** [comment]
[Atom](https://github.com/atom/atom) uses (and developed) keytar and it has worked well and is cross-platform.

I'd recommend using that for things you'd typically store in the keychain on Mac OS X.

Going to close this out, hope this helps.
