### ISSUE TITLE
Add onServerResponseData to webRequest

### ISSUE THREAD

**Issue by StickyCube** [atom/electron#4120]
Would there be any scope for adding an api for looking at server response data?

Something like:
```
session.webRequest.onServerResponseData(filter, (data, done) => {
  checkData(data);
  return done(data);
});
```

or perhaps a stream?
```
session.webRequest.onServerResponseData(filter, (istream, ostream) => {
  istream.pipe(spyStream).pipe(ostream);
});
```

cheers

**Comment by zcbenz** [comment]
The API provided by Chromium only allows us to modify the headers, if we want to add this API we need Chromium to provide related interface first. You can probably suggest adding this API to `chrome.webRequest` in [Chromium's issues list](https://crbug.com), once it is added there we can port it to Electron.

Or you can just use the `protocol` module to try to similar things.
