### ISSUE TITLE
Remote debugging not working on OS X

### ISSUE THREAD

**Issue by darrrk** [atom/electron#4125]
I do all actions, which described in master branch doc: https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md

But when I try to use node-inspector, error throws in it console:
```
Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.7.0/node-v47-darwin-x64/debug.node'
```
And electron process infinitely busy until I close tab with node-inspector

OS | Electron version
------------ | -------------
OS X 10.11.2 | 0.36.4 in process and node-inspector runtime

**Comment by darrrk** [comment]
@lukeapage, maybe it not tested in OS X?..

**Comment by lukeapage** [comment]
I wasn't able to test on mac os no. 

That path is for a global install of node inspector - are you definitely running node-inspector with electron (its looking for a node build, not an electron build - could also be that node pre gyp in the electrons app path isn't patched)  and did you recompile v8-debug in the global paths.. In my tests I install node inspector locally (it should still work but maybe there is a local/global mismatch?) 

I think its unlikely something is very windows specific but its possible mac os needs something extra or slightly different.

**Comment by darrrk** [comment]
Thanks. I do all anew, but install deps locally (besides node-pre-gyp, local node-pre-gyp can't patch, strangely...)
node-inspector run without errors and even show some js
But it not working :(
No show sourcemaps files, REPL not working, can't catch breakpoint, e.t.c.
Unfortunately.

**Comment by zcbenz** [comment]
You have to follow the guide exactly, e.g. you have to install the node-pre-gyp locally in node-inspector's repo, it needs to override the original one used by node-inspector.

**Comment by darrrk** [comment]
Ok, I install node-pre-gyp locally too and follow the guide exactly now, but it now working again and simptoms like this:

> No show sourcemaps files, REPL not working, can't catch breakpoint, e.t.c.
