### ISSUE TITLE
encoding issues with Main Proces

### ISSUE THREAD

**Issue by buildcold** [atom/electron#4128]
i tried  change win7 console's encoding,use utf-8 with ```chcp 65001``` as @zcbenz  said.
[link to 4114!](https://github.com/atom/electron/issues/4114)
http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500

use cmd:
```node main.js ``` the characters it's display well;

but with ```electron .```    the characters show 口口口口口

just as image show below

main.js

```
console.log('这是中文')；
```
![123](https://cloud.githubusercontent.com/assets/4065930/12369615/eff4d454-bc35-11e5-841e-bc2aa53809d6.png)

**Comment by zcbenz** [comment]
This seems to be related to your system's language, on Windows with English language, setting `chcp 65001` makes Node.js crash with `Error: write EIO`, while Electron still prints garbage text.

So I think this is completely an issue of Windows and it is impossible to be fixed. However if you are able to fix the problem, a pull request would be welcomed.

**Comment by staristic** [comment]
@kabledev 
It works. Your solution resolved all issues cause by encoding in my project. At least in dev env.
I just worry about that if built exe can work on PC of customers.
