### ISSUE TITLE
Problem with install.js 

### ISSUE THREAD

**Issue by naveenjafer** [atom/electron#4136]
[npm-debug.txt](https://github.com/atom/electron/files/93236/npm-debug.txt)
The log file on running the commmand " sudo npm install -g electron-prebuilt" is

/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

    electron-prebuilt@0.36.4 postinstall /usr/local/lib/node_modules/electron-prebuilt
    node install.js

/usr/local/lib/node_modules/electron-prebuilt/install.js:22
throw err
^

Error: end of central directory record signature not found
at /usr/local/lib/node_modules/electron-prebuilt/node_modules/yauzl/index.js:167:14
at /usr/local/lib/node_modules/electron-prebuilt/node_modules/yauzl/index.js:473:5
at /usr/local/lib/node_modules/electron-prebuilt/node_modules/fd-slicer/index.js:32:7
at FSReqWrap.wrapper as oncomplete
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "electron-prebuilt"
npm ERR! node v5.4.1
npm ERR! npm v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.4 postinstall: node install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.4 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node install.js
npm ERR! You can get their info via:
npm ERR! npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/naveen/npm-debug.log

**Comment by DerNivel** [comment]
I think you should report this issue on the `electron-prebuilt` repository.

**Comment by etiktin** [comment]
The electron-prebuilt repository is the correct destination for this issue. That said, the error you are getting means that `yauzl` couldn't validate the zip file.

**Comment by naveenjafer** [comment]
Thank you everybody. Got it fixed from there.

**Comment by lgfaler** [comment]
@naveenjafer How did you fix this?  I'm having the same issue.

**Comment by naveenjafer** [comment]
@Igfaler https://github.com/electron-userland/electron-prebuilt/issues/69#issuecomment-164636460 The comment by Judy worked.
