### ISSUE TITLE
Electron keeps crashing on ipc calls

### ISSUE THREAD

**Issue by Akshay-Thakare** [atom/electron#4140]
If you see the error file's it says that there is a SIGSEGV, SIGABRT & SIGTRAP. How to fix this?

The below code in render process never gets executed. It crashes the process. The same occurs when i try async calls.

//Render process code

```
function processResult(callback) {
    try {
        var result = ipcRenderer.sendSync('create-file', './database/userList.db');
        console.log(result);
    } catch(err){
        console.log(err);
    }
}
```

// Main process code
```
ipcMain.on('create-file', function (event, arg) {
    console.log('creating file');
    event.returnValue = true;
});
```

Here's the crash report link
[1] https://github.com/Akshay-Thakare/electron_errors/blob/master/error1.txt
[2] https://github.com/Akshay-Thakare/electron_errors/blob/master/error2.txt
[3] https://github.com/Akshay-Thakare/electron_errors/blob/master/error3.txt
[4] https://github.com/Akshay-Thakare/electron_errors/blob/master/error4.txt

**Comment by Akshay-Thakare** [comment]
It seems like there is a stack problem somewhere up in the code as even async calls are crashing.

**Comment by zcbenz** [comment]
The crash is very likely to be caused by other parts of your code, can you provide an reproducible example app?

**Comment by Akshay-Thakare** [comment]
I found the issue. I was executing a child process and it so happens that the call to that process was a sendSync which due to some still unknown reason was getting executed twice thus leading to a memory leak. I used a flag to limit it to a single execution for now (bad hack). 

Sorry for the trouble. And I had send you a mail yesterday regarding making modification's to chrome src please have a look at the same.

Thanks
