### ISSUE TITLE
webContents.downloadURL saves to userData folder by default

### ISSUE THREAD

**Issue by diracdeltas** [atom/electron#4141]
On OS X, webContents.downloadURL saves to [userData]/Downloads instead of ~/Downloads by default

Electron 0.36.3

**Comment by deepak1556** [comment]
Not sure if this is a bug, If neither `session.setDownloadPath` or `downloadItem.setSavePath` in `will-download` event is set. It will default to `Downloads` in respective app folder or the last saved download directory.

**Comment by zcbenz** [comment]
`~/Downloads` seems to be a better location for default download dir.
