### ISSUE TITLE
Fullscreen mode works only for production builds

### ISSUE THREAD

**Issue by svileng** [atom/electron#4144]
I'm using `electron-packager@5.1.1` and `electron-prebuilt@0.36.4`, and fullscreen mode in OSX works only when I run the app using the build executable. When I run it with `./node_modules/.bin/electron .` clicking on the fullscreen green icon causes the contents of the app to flicker for a second, but the size of the actual window doesn't change.

**Comment by zcbenz** [comment]
Can you provide an example app?

**Comment by zcbenz** [comment]
Closing until more information is provided.
