### ISSUE TITLE
Black video frames in Chrome / Electron

### ISSUE THREAD

**Issue by paul321** [atom/electron#4149]
Hi

I'm trying to load video tags in latest Electron (same behavior in Chrome) and it's showing black frames, here is a screenshot and a html file that can be tested in Chrome / Electron

![videos](https://cloud.githubusercontent.com/assets/555502/12397325/304146ce-be15-11e5-9b98-38c83535a858.jpg)

```html
<video>
    <source src="http://vid.123rf.com/preview/ruchos/ruchos1508/ruchos150800067.mp4">
</video>

<video style="object-fit: cover;">
    <source src="http://vid.123rf.com/preview/ruchos/ruchos1508/ruchos150800067.mp4">
</video>

<video style="object-fit: cover;">
    <source src="http://vid.123rf.com/preview/ruchos/ruchos1508/ruchos150800067.mp4">
</video>

<video style="object-fit: cover;">
    <source src="http://vid.123rf.com/preview/ruchos/ruchos1508/ruchos150800067.mp4">
</video>
```
Here is the video url, it playing only black background, if you forward it, the video will play correctly
http://vid.123rf.com/preview/ruchos/ruchos1508/ruchos150800067.mp4

**Comment by zcbenz** [comment]
Since it is the same behavior in Chrome, I suggest reporting this to [Chromium's issues list]. The media code is inside Chromium so it is impossible for us to fix this on Electron's side.
