### ISSUE TITLE
Support backgroundColor for (transparent) window on OSX

### ISSUE THREAD

**Issue by gabriel** [atom/electron#4154]
On OSX, setting `transparent: true` gives you a transparent window without a shadow.

On NSWindow using a `[NSColor clearColor]` for background color prevents a shadow from appearing at all (since it uses the background color to generate a shadow, the shadow is clear).
In fact, on [this line](https://github.com/atom/electron/blob/master/atom/browser/native_window_mac.mm#L421) if you removed setHasShadow call it would still not have a shadow since the background is clear.

In order to support a shadow on a transparent window you need to be able to set a non-clear NSWindow background color. For example at [atom/browser/native_window_mac.mm](https://github.com/atom/electron/blob/master/atom/browser/native_window_mac.mm#L421)

```objc
if (transparent()) {
    [window_ setOpaque:NO];
    [window_ setBackgroundColor:[NSColor colorWithCalibratedRed:1.0 green:1.0 blue:1.0 alpha:0.1]];
  }
```

it would have a somewhat blended window with a drop shadow.

Currently backgroundColor is only supported for linux and windows but we could also support for mac as well?

Alternatively I could add a transparentBackgroundColor attribute which would only set the background color if the window was transparent (and support an alpha channel).

If I added support for something like this in a PR, is this something you might consider merging in?

Thanks!

**Comment by zcbenz** [comment]
I think we can just use the `backgroundColor` attribute for it, I'm merging this to #861 since background color thing is tracked there.

Pull request is welcomed, to implement this you need to fill the code of `NativeWindowMac::SetBackgroundColor`.
