### ISSUE TITLE
[Mac] Referencing an unavailable resource in protocol.registerHttpProtocol causes a crash

### ISSUE THREAD

**Issue by bhuga** [atom/electron#4155]
In my main process, I have code like this:

```javasript
   var httpHandler = function(protocol) {
    return function(request, callback) {
      var url = request.url.split("://", 2)[1]
      url = protocol + "://" + url
      return callback( {url: url} );
    }
  }

  electron.protocol.registerHttpProtocol('haxs', httpHandler("https"))
  electron.protocol.registerHttpProtocol('hax', httpHandler("http"))
```

and in my browserWindow, I'm running this:

```javascript
  var hostRequire = require;  // node is disabled in the window, so we're scoping this to the closure with preload
  webFrame = hostRequire('electron').webFrame;
  webFrame.registerURLSchemeAsBypassingCSP("hax")
  webFrame.registerURLSchemeAsBypassingCSP("haxs")
  webFrame.registerURLSchemeAsSecure("hax")
  webFrame.registerURLSchemeAsSecure("haxs")
```

This does what I want, injecting a URL and bypassing CSP, for an accessible url. If I reference `haxs://example.com/foo.js`, in the dom, and it's available, it works. But If I reference something that doesn't exist, such as a bad hostname, or `hax://localhost:3000` while a local server is not running, Electron crashes. Am I perhaps not handling errors correctly? I'm trying to copy https://github.com/atom/electron/blob/master/docs/api/protocol.md#protocolregisterhttpprotocolscheme-handler-completion pretty straightforwardly. I have posted a gist of the crash log: 

https://gist.github.com/bhuga/38b73a5d42b2d68b7cea

The complete files with relevant context are https://github.com/bhuga/hackable-slack-client/blob/master/app/main.js and https://github.com/bhuga/hackable-slack-client/blob/master/app/expose-window-apis.js

**Comment by zcbenz** [comment]
Which version of Electron are you using? In v0.36.3 we fixed a similar crash.

**Comment by bhuga** [comment]
> Which version of Electron are you using? In v0.36.3 we fixed a similar crash.

I'm a version behind. I'll update and re-test. Thanks!

**Comment by bhuga** [comment]
`0.36.3` took care of it. Thanks for the help!
