### ISSUE TITLE
Question about win.destroy()

### ISSUE THREAD

**Issue by evgenyzinoviev** [atom/electron#4159]
The BrowserWindow doc has this note on `destroy` method:
`You should only use this method when the renderer process (web page) has crashed.`
I have an app with multiple windows and sometimes I want to force-close some of them. Does that note mean that `destroy()` is something dangerous with bad effects?

**Comment by zcbenz** [comment]
Calling `destroy()` is safe, it is very widely used in Electron's tests to make sure windows are force closed.

I'll update the docs, it is a bit out of date.
