### ISSUE TITLE
require('electron').webFrame undefined

### ISSUE THREAD

**Issue by issya** [atom/electron#4167]
When I try to use webFrame per the documentation it returns undefined.

    var webFrame = require('electron').webFrame;

**Comment by zcbenz** [comment]
You have the npm `electron` module installed either locally or globally, which overrides the `electron` built-in module.

**Comment by niftylettuce** [comment]
What does that even mean @zcbenz?  Why are you closing it if @issya hasn't reported that his issue is fixed?  I have the same issue here.  I believe there's something wrong here.

**Comment by niftylettuce** [comment]
For example, you can do `require('electron').BrowserWindow`, or `require('electron').Tray` just fine.  I don't have a globally installed version of `electron`, and as far as I know, you need to install it locally in your NPM dir... hence `npm install --save electron` -- otherwise what would it even require?  Please re-open this issue.

**Comment by issya** [comment]
I still have this issue. electron-prebuilt was installed globally. Now I only have the latest version of electron-prebuilt in my local node_modules and it still does not work. I saw that the FAQ states that you could have this problem if electron is installed locally or globally. It has to be installed in one or the other for electron to function at all.

**Comment by zcbenz** [comment]
@niftylettuce `webFrame` is a renderer process module, you can not use it in main process.

@issya Can you paste the result of `require.resolve('electron')`?

**Comment by issya** [comment]
```
Uncaught Exception:
TypeError: require(...).executeJavaScript is not a function
    at resetDB (/Users/*****/test/app/js/electron.js:34:25)
    at template.submenu.click (/Users/****/test/app/js/electron.js:84:50)
    at MenuItem.click (/Users/****/test/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:69:18)
    at Function.delegate.executeCommand (/Users/****/test/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:128:69)
```

**Comment by matthewmueller** [comment]
:thumbsup: i'm running into this issue as well. it's in the render process, not the main process.

**Comment by matthewmueller** [comment]
woops, looks like i'm in the main process haha
