### ISSUE TITLE
Disable Windows Toaster Notification Sound

### ISSUE THREAD

**Issue by rdcvnh** [atom/electron#4169]
Now that Windows toaster notification is working out of the box in Electron, when you fire it through the Notification API, it always plays the default Windows 10 notification chime.

According to the Notification API (https://developer.mozilla.org/en/docs/Web/API/notification), it is possible to set the "sound" or "silent" property in the notification's options. Could this also be implemented for Electron so no sound is played when a notification is displayed? Just for reference, nwjs does not play any sound on new notification.

Thanks in advance

**Comment by felixrieseberg** [comment]
This might be possible - I'll check it out.

**Comment by felixrieseberg** [comment]
Yup, got it - should probably make it into one of the next releases.

**Comment by rdcvnh** [comment]
Awesome, thank you!
