### ISSUE TITLE
Attempting to a specific project folder in Atom and VSCode adds the home directory instead

### ISSUE THREAD

**Issue by Tyriar** [atom/electron#4171]
Two cases have been reported for Atom/VSCode, both running Ubuntu 12.04. This issue was originally reported in https://github.com/atom/atom/issues/9320 and https://github.com/Microsoft/vscode/issues/2115

**Steps to reproduce:**

1. Create a directory `~/test-dir`
2. Launch `atom --safe`
3. File > Add Project Folder
4. Navigate to ~/test-dir and add it

**Expected:**

`~/test-dir` is added as a project folder

**Actual:**

`~` is added as a project folder

**Notes:**

- I've experienced this problem on both Atom 1.0.8 and 1.0.19, but only on my work PC (Ubuntu 12.04).
- I have had to resort to using [project-manager](https://atom.io/packages/project-manager) to handle all project folders on my work PC which handles project folders just fine
- Repeating steps 2-3 seems to attempt to re-add `~` (which does nothing)

**Comment by zcbenz** [comment]
This is not the first issue on this, [previous one](https://github.com/atom/electron/issues/1212) was closed as won't fix. I'm reopening the original issue since the request for it seems to be popular, and there is no harm doing that anyway.
