### ISSUE TITLE
--enable-precise-memory-info?

### ISSUE THREAD

**Issue by demian85** [atom/electron#4173]
Is there an easy way to support this command line switch? I need it to monitor memory consumption while running a UI test inside a webview.
I see it's not [documented](http://electron.atom.io/docs/v0.36.0/api/chrome-command-line-switches/), but its supported by Chromium.

**Comment by deepak1556** [comment]
you can use `blinkFeatures` option to enable for `browserwindow`. Have created a PR to support `webview`.

```
new BrowserWindow({
  'webPreferences': {
    'blinkFeatures': 'PreciseMemoryInfo'
  }
})

<webview blinkfeatures="PreciseMemoryInfo"></webview>
```
