### ISSUE TITLE
Different behavior between environment (Windows vs MacOS X) of app:before-quit event and no alternative to the mainWindows 'close' event

### ISSUE THREAD

**Issue by alexandrev** [atom/electron#4183]
Hi, 

On the Kitematic project we are using the atom/electron API to do some communication between the components and we are facing environment issues on Windows when we need to receive an event on app:before-quit. The event is sent but it seem it is not send at the same time on Windows and on MacOS X because on MacOS X system we receive the event but on Windows we don't.

We found a "workaround" but we want to work on a specific solution for this problem. You can see all the details of the issue here: https://github.com/docker/kitematic/issues/1369 and https://github.com/docker/kitematic/pull/1394

Thanks

**Comment by zcbenz** [comment]
Can you make a sample app that can demonstrate the problem? We are not familiar with kitematic's codebase.

**Comment by alexandrev** [comment]
Ok, I will work on this, but it is going to be difficult because the multienvironment and event synchronization issues. I'll keep you posted. Thx @zcbenz

**Comment by zcbenz** [comment]
Closing until more information is provided.
