### ISSUE TITLE
OSX System Preferences Keyboard Shortcuts mapped to Option key aren't captured

### ISSUE THREAD

**Issue by Rosey** [atom/electron#4184]
Electron Version: 0.35.0
OSX 10.11.12

Also tested on Atom 1.4.0, not sure what version of Electron it's using.

Steps to reproduce:

- Open System Preferences -> Keyboard -> Shortcuts -> App Shortcuts
- Set up a shortcut for a menu item that uses the option/alt key
<img width="418" alt="screen shot 2016-01-21 at 11 50 24 am" src="https://cloud.githubusercontent.com/assets/1326431/12492471/3c3d0cac-c035-11e5-83bb-d8f3eac0db25.png">
<img width="220" alt="screen shot 2016-01-21 at 11 51 06 am" src="https://cloud.githubusercontent.com/assets/1326431/12492484/4676f52a-c035-11e5-9ff2-374449e40d84.png">
- The shortcut is then reflected in the menu (yay)
- The shortcut doesn't work unless you actually have the menu open
- With other shortcuts, e.g. shortcuts that use the command or control key, it works properly when the menu is closed.

**Comment by jlord** [comment]
Thanks for awesome repro steps! 

I gave it a try and found the same issue you found when trying with Atom. Atom isn't on the latest Electron so I gave it a try with an app using the latest, `v0.36.4`, and was able to have the shortcut work as expected. 

Would you be able to try with the latest version?

**Comment by Rosey** [comment]
Eek, how embarrassing. You're right, it's fixed in the latest version, just tried it out. I did try skimming the release notes between 0.35.0 and 0.36.4 to see if there was any mention of that kind of bug fix before I opened this issue, but I might have missed it. :blush: 

Thanks for the quick reply!

**Comment by jlord** [comment]
No worries, glad it's sorted now!
