### ISSUE TITLE
Local modifications for required scripts with workspaces

### ISSUE THREAD

**Issue by mattdesl** [atom/electron#4185]
It is possible to add workspaces to the DevTools panel, but they are not very useful when you `require()` scripts with Node. You can add a breakpoint to sources in the workspace folder, but they will not get picked up by the debugger since Node's require will wrap them with a closure and runs a new script in memory. This also means local modifications to the in-memory script won't modify the local file system.

Here is a screen shot. Both `test.js` tabs point to the same file (right click -> "Copy Link" provides same URL). However, the one on the right is served in-memory (no modifications possible), and the left is from file system (modifications possible).

<img width="308" alt="screen shot 2016-01-21 at 3 23 31 pm" src="https://cloud.githubusercontent.com/assets/1383811/12493455/0f699c68-c053-11e5-9bd1-978b09f47097.png">

Any ideas how we can resolve this so that breakpoints + local modifications work the same way whether it's required or from file system?

I can put together a test case if necessary.

**Comment by zcbenz** [comment]
The scripts loaded by `require` are different from the ones loaded by `<script>` tag, Node did some modifications to them so the script loaded into page is not the same with the one on filesystem anymore. If we want to implement this we have to tell devtools which parts of the script are modified, and let it save to the original file without the modifications, which is not possible with the design of the workspace of devtools, so I'm closing this as won't fix.

**Comment by mattdesl** [comment]
Thanks for the quick reply! I'm overloading Module/require in my app to add source maps and custom require() resolve, do you think anything like that (user land changes, not core electron) would be possible to fix this in the future?

**Comment by zcbenz** [comment]
I'm not sure, we probably have to modify Node's module code to make it work, the key is to make modules compiled like normal web JS files, which can be very hard.
