### ISSUE TITLE
CSS Cursor attribute in Top area doesn't work.(OSX, Frameless window)

### ISSUE THREAD

**Issue by Rokt33r** [atom/electron#4187]
Although I set `cursor: pointer` to all tab buttons, the top area where titlebar was located still show default cursor.

Please watch the video.
https://www.youtube.com/watch?v=bTCijr-KE3Q&feature=youtu.be

> Same condition of #4151.

**Comment by zcbenz** [comment]
This is a duplicate of #3009.

**Comment by Rokt33r** [comment]
I don't think it is duplicated.
I applied `frame: false` not `titleBarStyle: 'hidden-inset`.

**Comment by zcbenz** [comment]
I thought you were using `titleBarStyle`, for normal frameless window all HTML things won't work in the draggable region, because the OS captures all mouse events to make draggable regions work.
