### ISSUE TITLE
How I can debug electron in Windows?

### ISSUE THREAD

**Issue by bernex** [atom/electron#4195]
I can't debug it.

How I can debug electron in Windows?

**Comment by jlord** [comment]
Here's documentation on [debugging in the main process](http://electron.atom.io/docs/v0.36.4/tutorial/debugging-main-process/). Console logging is also useful :sparkles:

**Comment by zcbenz** [comment]
If you want to debug Electron itself, any native debugger would work.

**Comment by bernex** [comment]
No.

I build: python script\build.py -c D

And run: no have api-ms-win-core-winrt-l1-1-0.dll

![image](https://cloud.githubusercontent.com/assets/4822771/12529848/95a39546-c1d8-11e5-89d8-fa8199215ae7.png)

**Comment by zcbenz** [comment]
You need to follow the docs to install all prerequisites: http://electron.atom.io/docs/v0.36.5/development/build-instructions-windows/

**Comment by LartSimZ** [comment]
I get the same issue. I have all prerequisites installed. I'm trying to build the 64-bit Debug  version of Electron under Windows 7 with VS 2013 Update 5 toolchain.
I wonder why WinRT DLLs are referenced as delay loaded in the electron.ninja generated file for the Windows AMD64 platform. What's your view ?

**Comment by naiduv** [comment]
same issue.. 
![image](https://cloud.githubusercontent.com/assets/675835/13379584/67af62ba-ddf7-11e5-8f37-bee1c06eba4d.png)

**Comment by naiduv** [comment]
I had to search my registry for the dll.
1. regedit in cmd
2. search for the dll using find
3. copy to the out/d directory

obviously this is a temporary fix

**Comment by ficristo** [comment]
I have the same problem. For now I've copied the relevant dll...

**Comment by evgeniyzinoviev** [comment]
I have the same problem on Windows 7 and here is what I did..
I have created the .bat file that adds a folder that contains required dlls to the PA

**Comment by evgeniyzinoviev** [comment]
I have the same problem on Windows 7 and here is what I did..
I have created the .bat file that adds a folder that contains required dlls to the PATH variable and then runs electron:
```
setlocal
set PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\NETCoreSDK\Microsoft.NETCore.Windows.ApiSets-x64\1.0.0\runtimes\win7-x64\native\
e:\path\to\electron\out\D\electron.exe .
```
