### ISSUE TITLE
When calling autoUpdater.quitAndInstall() it would be nice to be able to pass some state to the new instance

### ISSUE THREAD

**Issue by f0zi** [atom/electron#4197]
In my case I'd like to pass a URL to the new instance, but something more generic would probably make more sense:

- a JS object (JSON?)
- a set of command line parameters
- maybe just the guarantee that set environment variables will be inherited (explicitly in the docs)
- something else?

Right now I'm creating a temporary file. I don't think this is a good solution, this file will be picked up at the "next start", whatever that will be. I'm also relying on the fact that deleting that file will succeed.

Note: On the Mac I'm using the 'open-url' event. That is, the app that is about to restart was opened from a protocol handler. While the parameters would work for me just fine (and in fact would be required on Windows), being able to trigger that on the new instance would be nice as well.

Thanks

**Comment by zcbenz** [comment]
The autoUpdater libraries (https://github.com/Squirrel/Squirrel.Mac and https://github.com/Squirrel/Squirrel.Windows) used by Electron do not support passing state to new instance, I suggest reposting this to their repos and once they added support for this we can add corresponding APIs in Electron.

Also I think using a temporary file is not a bad idea though, many programs are using this pattern.

**Comment by f0zi** [comment]
Thanks, I did, looks like it's already supported: https://github.com/Squirrel/Squirrel.Windows/issues/573
