### ISSUE TITLE
When it is safe to use WebView.Send()?

### ISSUE THREAD

**Issue by yinghuitan** [atom/electron#4199]
Our application(Nuclide) is hosting WebView in its DOM like below:

const webviewNode = ((document.createElement('webview'): any): WebviewElement);
webviewNode.src = this._getUrl();
webviewNode.nodeintegration = true;
webviewNode.disablewebsecurity = true;
webviewNode.classList.add('native-key-bindings'); // required to pass through certain key events
webviewNode.classList.add('nuclide-debugger-webview');
const controlBarNode = React.findDOMNode(this.refs.controlBar);
controlBarNode.parentNode.insertBefore(webviewNode, controlBarNode.nextSibling);

After this, I am trying to send some data to the code running inside WebView via IPC:
webviewNode.send('command', 'UpdateSettings', data);

However, electron will throw exception at line "(ref = internal.webContents)[m].apply(ref, args);":

"TypeError: Cannot read property 'send' of undefined at webview.send (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:290:44) at [object Object].componentDidMount (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide/debugger/atom/lib/DebuggerInspector.js:70:17) at r.a.notifyAll (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:12:7127) at r.f.close (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:15:4173) at r.o.closeAll (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:16:2085) at r.o.perform (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:16:1531) at o.perform (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:16:1448) at o.v.perform (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:15:15261) at Object.D [as flushBatchedUpdates] (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:15:15430) at r.o.closeAll (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:16:2085) at r.o.perform (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:16:1531) at Object.d.batchedUpdates (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:14:8520) at Object.s [as enqueueUpdate] (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:15:14475) at r (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:15:12114) at Object.c.enqueueSetState (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:15:12975) at [object Object].r.setState (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/react/dist/react-with-addons.min.js:13:12567) at [object Object]._updateStateFromStore (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide/debugger/atom/lib/DebuggerControllerView.js:108:12) at emitNone (events.js:72:20) at EventEmitter.emit (events.js:166:7) at DebuggerStore._handlePayload (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide/debugger/atom/lib/DebuggerStore.js:122:26) at Dispatcher.$Dispatcher_invokeCallback (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/flux/lib/Dispatcher.js:220:35) at Dispatcher.dispatch (/Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/node_modules/flux/lib/Dispatcher.js:195:14) at /Users/jeffreytan/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide/debugger/atom/lib/DebuggerActions.js:84:27 at process._tickDomainCallback (node.js:411:9) "

If I step under debugger, this exception does not throw. Also, I can see (ref = internal.webContents) contains valid object. So this seems to be a race condition. 

Question:
1. When do I know it is safe to call WebView.send()?
2. I want to pass some data from our host process to the WebView process at very early stage. Is using IPC the best approach? 

Thanks!

**Comment by zcbenz** [comment]
The webview element must be loaded before using the methods.

Example:

```js
webview.addEventListener("dom-ready", function() {
  webview.openDevTools();
});
```

Depending on what you want to do, `preload` script can be used to load data on early stage.

**Comment by BloodShura** [comment]
Isn't there any event that happens **before** the DOM is ready, where `webView#send` is available?

I need to execute a script after the `preload` script is executed, but before the DOM starts rendering.

If that isn't possible... then, is there any way I can pass parameters to the `preload` script? I need to customize its contents and, [according to the docs](https://electronjs.org/docs/api/webview-tag#preload), the `preload` script path must have `file://` protocol, so I can't load it and pre-process it with the customized parameters...
