### ISSUE TITLE
Disabling RTC

### ISSUE THREAD

**Issue by aakilfernandes** [atom/electron#4200]
I'm working on an app with privacy considerations and I'd like to disable WebRTC. Any thoughts on how I might do that?

**Comment by zcbenz** [comment]
I'm merging this to #4200.

**Comment by paulcbetts** [comment]
@zcbenz Typo? Merging to its own bug?

**Comment by zcbenz** [comment]
Oops, it should be #4174.

**Comment by aakilfernandes** [comment]
@zcbenz I read the linked issue, I don't see the connection. linked issue has to do with webviews, this is regarding webrtc

**Comment by zcbenz** [comment]
@aakilfernandes webview is a WebContents under the hood, once we have a way to control permission of webrtc in webview it would be possible to do the same for WebContents.

**Comment by aakilfernandes** [comment]
Got it thanks

**Comment by diracdeltas** [comment]
https://github.com/atom/electron/issues/4174 is closed now, but webrtc still cannot be disabled entirely. ex: visiting https://diafygi.github.io/webrtc-ips/ reveals internal IP address without firing a permission request. so i don't know if @aakilfernandes's original request has been addressed.

**Comment by phil-r** [comment]
Any progress on this issue? I still can't find any way to disable webrtc
