### ISSUE TITLE
non-persistent webview partition writing URLs to cache?

### ISSUE THREAD

**Issue by diracdeltas** [atom/electron#4203]
The webview documentation says "if there is no persist: prefix, the page will use an in-memory session." However, grepping in the `appData` folder shows URLs from a non-persistent session in `Cache/data_1` and `Cache/data_3`. See https://github.com/brave/browser-laptop/issues/138#issuecomment-172965631 for exact repro steps.

Electron 0.36.3
OS X 10.11

**Comment by deepak1556** [comment]
Unable to reproduce, tested with the following app.

```
// main.js
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
const session = electron.session;
const path = require('path')

var win = null;

app.on("ready", function() {
    win = new BrowserWindow();

    win.webContents.loadURL('file://' + path.join(__dirname, 'index.html'));
    win.openDevTools();
})
```

```
<!--index.html-->
<webview src="http://savecrypto.org" partition="test"></webview>

```

Could you provide a sample app that reproduces the issue ? Moreover if a webview partition persisted, the data will be present under `<appdata>/Partitions/<partition_name>/`

**Comment by diracdeltas** [comment]
This is the example app: https://github.com/brave/browser-laptop. Once you have it running (npm install, npm run-watch, npm start), try the steps at https://github.com/brave/browser-laptop/issues/138#issuecomment-172965631 to repro.

**Comment by zcbenz** [comment]
@diracdeltas From the original issue, the cache shows under `~/Library/Application Support/Brave/Cache`, which means the cache is from the default session instead of the in memory partition. @deepak1556 also verifies in memory partition does not write cache to filesystem. If you think this is a bug of Electron, you should provide a test case, we don't have time to debug your app.

**Comment by diracdeltas** [comment]
thanks for the tips, figured out the problem on our end
