### ISSUE TITLE
[doc] browser-window.md: Descriptions for type, titleBarStyle and webPreferences are misaligned

### ISSUE THREAD

**Issue by princejwesley** [atom/electron#4209]
![image](https://cloud.githubusercontent.com/assets/1622515/12532969/58130800-c247-11e5-958e-9370101818b1.png)

**Comment by zcbenz** [comment]
I don't get it, they seem aligned to me.

**Comment by princejwesley** [comment]
@zcbenz it make sense now. I was expecting option descriptions nested under respective options.
