### ISSUE TITLE
Is it possible to show keyboard shortcuts in a MenuItem?

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#4212]
Couldn't find this in the API, `sublabel` cane close but did not do the trick.

![image](https://cloud.githubusercontent.com/assets/62191/12533825/d68ad23e-c1f3-11e5-8138-e4b7dd0f766b.png)

**Comment by xywz** [comment]
Use `accelerator`. See https://github.com/atom/electron/blob/master/docs/api/menu-item.md and https://github.com/atom/electron/blob/master/docs/api/accelerator.md.

**Comment by kirkouimet** [comment]
Thanks! Will there be any conflict if I already have an `onkeyup` event listening for keyboard shortcuts that use the same key combination as the accelerator?

**Comment by zcbenz** [comment]
The accelerators of menu will only be handled when the keyboard shortcut is not captured by JavaScript.

**Comment by karimhossenbux** [comment]
Would `CmdOrCtrl+,` works for CMD + ; ?
On my Spanish keyboard I have on the same key `,` and `;` but I need to put `,` to get the correct shortcut behaviour.
