### ISSUE TITLE
question: require('app') vs. require('electron').app?

### ISSUE THREAD

**Issue by bcherny** [atom/electron#4213]
the former works for me, but i see the latter (which evals to undefined) in all the official docs. what's the blessed way to get an app instance?

**Comment by enlight** [comment]
If you're on v0.35 or later you should use `require('electron').app`, if you're on an earlier version use `require('app')`. If you are on v0.35+ and `require('electron').app` doesn't work double check you didn't accidentally install the `electron` module (which has nothing to do with Electron shell).

BTW, questions should go to the [community](https://github.com/atom/electron#community), issues are for bugs/features.

**Comment by bcherny** [comment]
that's the exact issue. thanks!

bummer that electron can't just be called "electron".
