### ISSUE TITLE
Is possible to catch parameters which has been sent by post request via website (in webview)? [v0.36.3]

### ISSUE THREAD

**Issue by cybri0nix** [atom/electron#4214]

**Comment by deepak1556** [comment]
you can get `uploadData` from `protocol.interceptHttpProtocol`. `session.webRequest` api currently doesnt provide `uploadData`, @zcbenz can we add it ?

**Comment by zcbenz** [comment]
> session.webRequest api currently doesnt provide uploadData, @zcbenz can we add it ?

Sounds a good idea to me.

**Comment by cybri0nix** [comment]
@deepak1556 @zcbenz Very very cool! How long should I wait? Thanks!

**Comment by RussBaz** [comment]
details.uploadData[0].bytes.toString() does not escape '&' (ampersand) symbol, therefore making it barely parseable if not impossible to parse. Do I need to parse bytes somehow differently or is it a bug in uploadData?

Thank you.

**Comment by deepak1556** [comment]
@RussBaz doesnt node `querystring` module help ?
