### ISSUE TITLE
Cannot access piped stdin in main process 

### ISSUE THREAD

**Issue by s-a** [atom/electron#4218]
I succesfuly got access to ```stdin``` data at 
https://github.com/s-a/iron-node/blob/e844eac23fb8a0f7f2285dab9318ab3a4fe2fc78/bin/run.js#L17

But having trouble to access ```stdin``` at the ```main process``` module.
https://github.com/s-a/iron-node/blob/e844eac23fb8a0f7f2285dab9318ab3a4fe2fc78/app/index.js#L11

I Created a test script at https://github.com/s-a/iron-node/blob/e844eac23fb8a0f7f2285dab9318ab3a4fe2fc78/package.json#L16 ```pipe-test```

Well I tried a few variants and feel that this could be an electron bug on windows (not tried other OS s)

Ref.: https://github.com/s-a/iron-node/issues/78

**Comment by zcbenz** [comment]
On Windows only console programs can have stdin, but Electron is a GUI program.

To support this we have to either provide a build of Electron that is compiled as console program, like [what Node.js does](https://github.com/nodejs/node/blob/master/common.gypi#L150-L168), or you can work around this in your app by saving stdin into a file and then pass it to Electron.

Adding a new build would put lots of burden on our maintenance, so unless there are strong requests to add it, we won't do that.

**Comment by stelcheck** [comment]
Thanks for the reply. For what its worth, I ended making a REPL using named pipe, and having a parent Node.js process both start my Electron app and connect through it using the net library. Works like a charm.

**Comment by ccoenen** [comment]
@stelcheck is there any source available where I could take a peek? I have a very similar problem in a pet project which I would like to use on windows.

**Comment by stelcheck** [comment]
@ccoenen https://gist.github.com/stelcheck/a0c798ff31df5f2c0e5d72513948dcf1

It's pretty simple, just an IPC connection through a socket file, a REPL server on the electron side. I use the console script to start the electron app for convenience.

**Comment by Slapbox** [comment]
@zcbenz is there any appetite for supporting this? I'd really like to integrate with Chrome's "Native Messaging" but right now it seems like there's no way to do that without a go-between application and manually configuring a secure channel between `electron` and the go-between application.

**Comment by jml674** [comment]
Same here, there is a need for stdin for chrome native apps.

**Comment by organy110** [comment]
> On Windows only console programs can have stdin, but Electron is a GUI program.
> 
> To support this we have to either provide a build of Electron that is compiled as console program, like [what Node.js does](https://github.com/nodejs/node/blob/master/common.gypi#L150-L168), or you can work around this in your app by saving stdin into a file and then pass it to Electron.
> 
> Adding a new build would put lots of burden on our maintenance, so unless there are strong requests to add it, we won't do that.

That's not true. In WPF framework, Swing framework and more, stdio is supported even though they were all developed for web apps.

**Comment by giladnavot** [comment]
> Well I tried a few variants and feel that this could be an electron bug on windows (not tried other OS s)

Any news on that?
I am trying to implement A CLI using Electron and I need to get user input.
Currently not working on windows 10 with Electron 8.0.0 

(Electron main process) Not working on Windows:

```
var readline = require('readline');
var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  rl.question('Question: ', (question) => {
    console.log(question)
    rl.close();
});
```

**Comment by Slapbox** [comment]
@giladnavot I spent literally a month on this. I'm no expert, but this seems to me to be _impossible_ on Windows. Your only option is a native Node application bridge via IPC as far as I'm aware, or a non-Node solution.

**Comment by talmobi** [comment]
@Slapbox same conclusion. Can't seem to access stdin at all on Windows from Electron. Works fine on mac/ubunutu.

**Comment by skinner2401** [comment]
@zcbenz Is there any chance this could be revisited? I am asking as I know the build infra has come a long way, since the original answer in early 2016. Build is now synchronized with chromium nightly, and having forward/backward fix ports with bots, etc. Is it something the build infra team would be willing to tackle now that there have been many enhancements?

This would be a very useful feature for securely passing information from any parent to an electron child process on windows.

**Comment by The-MAZZTer** [comment]
It is certainly deceptive to have the process.stdin object available but broken. It should be removed if it is not functional.

**Comment by projektorius96** [comment]
> @zcbenz Is there any chance this could be revisited? I am asking as I know the build infra has come a long way, since the original answer in early 2016. Build is now synchronized with chromium nightly, and having forward/backward fix ports with bots, etc. Is it something the build infra team would be willing to tackle now that there have been many enhancements?
> 
> This would be a very useful feature for securely passing information from any parent to an electron child process on windows.

Is it still relevant for Windows 10/11 users today ?
