### ISSUE TITLE
Path of LICENSES.chromium.html may be wrong

### ISSUE THREAD

**Issue by minggo** [atom/electron#4220]
Path of `LICENSES.chromium.html` is needed by `script/create-dist.py` [like this](https://github.com/atom/electron/blob/master/script/create-dist.py#L130), but the path may be error if libchromiumcontent.zip is not downloaded and extracted by `script/bootstrap.py`.

**Comment by zcbenz** [comment]
We only support one way of building Electron, which is the one documented by "Build Instructions", if you use other ways you are on your own. (But we accept PRs that add/fix other ways of building.)

**Comment by minggo** [comment]
But bootstrap.py supports passing `libcc_shared_library_path`, `libcc_static_library_path` and `libcc_source_path`.

**Comment by zcbenz** [comment]
Those parameters were contributed by third parties, they are not officially maintained.
