### ISSUE TITLE
Is it possible to have Electron as a subview in a more complex view hierarchy?

### ISSUE THREAD

**Issue by zsszatmari** [atom/electron#4222]
Hi!

  I cannot seem to find this in the documentation. Is it possible to - instead of creating it's dedicated window, but with as little hackery as possible - embed Electron as a subview in a view hierarchy? Under OS X, one would get an NSView *, under Windows, one would perhaps specify parent's HWND when creating as child window.
  Thank You!

**Comment by zcbenz** [comment]
No currently it is impossible to embed Electron in other applications, Electron's architecture doesn't allow that.
