### ISSUE TITLE
IPC nulling out multiple references of the same object

### ISSUE THREAD

**Issue by bmathews** [atom/electron#4224]
This seemed to have started recently, but I'm not sure which version of electron exactly. I've reproduced it on 0.36.4 and 0.36.5.

When sending an object over ipc from the main process, additional references to the same object end up being null. The first 'instance' of that property on `state` makes it to the client, but any additional references end up null.

```javascript
  const state = {}
  const object = { 'prop': 1 }

  state.firstReference = object
  state.brokenReference = object // brokenReference ends up null on the client

  win.webContents.on('did-finish-load', function() {
    console.log('sending state', state)
    win.webContents.send('update', state)
  });
```

Here's a repo that reproduces this:
https://github.com/bmathews/electron-ipc-bug

**Comment by xywz** [comment]
Duplicate of #3598.

**Comment by bmathews** [comment]
@xywz ugh, thanks!

**Comment by ajwhite** [comment]
I really feel like this is a bug, but #3598 got closed saying this behavior was intentional. I feel like these issues should remain open for contributors to take a look at and potentially provide a good solution.
