### ISSUE TITLE
Electon binary crashes with "igh"

### ISSUE THREAD

**Issue by alexose** [atom/electron#4226]
I'm trying to run Electron under Debian Wheezy, and the binary simply exists with "igh" regardless of arguments:

    $ electron
    igh
    $

Yeah, I don't know either.

This happens on both electron-prebuilt and my own compiled binary.  Any ideas?

My uname -a outputs the following:

    Linux box 4.3.0-0.bpo.1-amd64 #1 SMP Debian 4.3.3-7~bpo8+1 (2016-01-19) x86_64 GNU/Linux

**Comment by zcbenz** [comment]
Are you using the 64bit binary? Can you try whether the 32bit binary would crash with the same error?

Also can you try setting `ELECTRON_ENABLE_STACK_DUMPING` env and see if there is any stack trace printed?

```bash
$ export ELECTRON_ENABLE_STACK_DUMPING=1
$ electron
```

**Comment by alexose** [comment]
The 32bit binary crashes with this error:

    ./electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

```ELECTRON_ENABLE_STACK_DUMPING``` yields nothing :(

**Comment by zcbenz** [comment]
It seems that the 64bit binary seems to include instructions that your processor doesn't recognize, I don't know why it could happen, but the only solution is to recompile Electron for your Linux distribution and processor type.

I'm merging this to #259.
