### ISSUE TITLE
Quick Start has a menu, that isn't in code?

### ISSUE THREAD

**Issue by FelixINX** [atom/electron#4227]
Hi,

I am asking this weird question, but on my computer, I don't found any menu script with Electron Quick Start.
I have start [a repo](https://github.com/FelixINX/electron-quickstart) where I have put my code, and if you searched "menu", you find this.

> We couldn’t find any code matching 'menu'

I am using, Windows 10, node 5.1.1, Chrome 47.0.2526.110, and Electron 0.36.5.

Thank you

**Comment by OlsonDev** [comment]
You're likely using the [default app](https://github.com/atom/electron/blob/master/atom/browser/default_app). Check out its [main.js](https://github.com/atom/electron/blob/master/atom/browser/default_app/main.js); it builds the defaultl menu there. On your own computer, you'll find it in `electron-v0.36.5-win32-x64.zip\resources\default_app` or if you're using `npm install electron-prebuilt`, you'll find it in `node_modules/electron-prebuilt/dist/resources/default_app`.

**Comment by zcbenz** [comment]
The default app creates a default menu for your app, once your app is packaged, the default menu will be gone.

**Comment by FelixINX** [comment]
@OlsonDev I am not talking about the default app, but the quickstart app

https://github.com/atom/electron-quick-start

![](http://i.imgur.com/fSfd1XM.png)

@zcbenz You're right, when packaged, the menu isn't there. Thanks.

**Comment by OlsonDev** [comment]
`electron-quick-start` uses the default app (until packaged), hence me stating you're likely using the default app. :-)

**Comment by FelixINX** [comment]
@OlsonDev thats more clear now. Thank you!

**Comment by MartinMa** [comment]
To be honest, I find this very confusing. Would it hurt to put a comment about this on `main.js`. Maybe above `function createWindow ()` or something?
