### ISSUE TITLE
Modifiers don't work on the Media Accelerators

### ISSUE THREAD

**Issue by MathijsvVelde** [atom/electron#4232]
I'm trying to listen to the media accelerators (VolumeXX, MediaXX) with modifiers on Yosemite with global-shortcut in the latest Electron (0.36.5) but all the accelerators triggered like no modifiers were used. Tried them on a minimal workable example too, with the same effect.

**Comment by zcbenz** [comment]
The global shortcuts will only work when they are not taken by other applications, on OS X  the media keys are preserved by OS X itself, so there is no way to register global shortcuts for them.

**Comment by MathijsvVelde** [comment]
Sorry to say, but you're wrong...
I'm already using `MediaNextTrack`, `MediaPreviousTrack` and `MediaPlayPause` without modifier successfully.

The volume controls without the modifiers work aswell, but I don't want to overrule the system volume controls.

I want to use the modifiers with the volume controls, so i can set the app and the system volume, (e.g.: `Ctrl+VolumeXX` for the app and `VolumeXX` are still available for the system volume controls)

**Comment by zcbenz** [comment]
Sorry I didn't notice you were using modifiers.

It is interesting that on EL Capitan, registering media key with modifiers has completely no effect.

**Comment by zcbenz** [comment]
After some experiments I think this is a limitation of OS X, I'll add documentation for it.

**Comment by MathijsvVelde** [comment]
Okay, thanks anyway :+1:
