### ISSUE TITLE
Custom protocol doesn't execute javascripts? 

### ISSUE THREAD

**Issue by frozeman** [atom/electron#4238]
After trying for a few hours now and experimenting with many different ways to "rewrite" a custom protocol to a http call, i'm posting here my findings.

When creating a custom protocol it seems to load linked stylesheets and javascript files, but seem to not execute them properly on some occasions.

I created the following test repro: https://github.com/frozeman/electron-curstom-protocol-realtive-urls-repro

Debugging process:

1. i tried to load a simple html side from a local server and rewrote `myprot://interface` -> `http://localhost/index.html` using `protocol.registerHttpProtocol('myprot', ....)`. This works!
2. i tried to load a more complex js application and it *doesn't seem to run all the javascript*, even though they are loaded and i can inspect them vial the debug console. (It also doesn't show any errors in the console)
![screen shot 2016-01-26 at 16 24 37](https://cloud.githubusercontent.com/assets/232662/12584767/50e0064c-c449-11e5-943c-e2d227526809.png)
   - I tried to run the same (meteor) application using the `--production` flag, which will concatenate and minify all the js and css into 2 single files and the app runs!
![screen shot 2016-01-26 at 16 22 42](https://cloud.githubusercontent.com/assets/232662/12584698/1015bbfc-c449-11e5-9d33-7c229e9a8f96.png)
3. I thought it may be meteor, so i tried a few other js applications, and rewrote to http://todomvc.com/examples/react/ etc. Some seem to run, others show the HTML, but the js also seems only half executed or doesn't run at all.
4. So i thought it maybe the custom protocol, which the js frameworks may not like, so i used `protocol.interceptHttpProtocol('http', ...)`, and only rewrote `http://interface` -> `http://localhost:3000`
   - This also doesn't work and shows the exact same behaviour as with a registered custom protocol. Apps with less requests work, others don't.

### Conclusion:

It seems like that applications with large requests, or with a lot will not fully process the loaded javascript files and seem to fail silently.
It doesn't seem to be a problem of the loaded js frameworks, or the custom URL used, as rewriting `http://interface` -> `http://localhost:3000` has the same negative results.

If there is a way that i can help to debug this, i'm more than happy to do so.

### Running the repro
https://github.com/frozeman/electron-curstom-protocol-realtive-urls-repro

To run the repro, you need to have meteor installed. If not install meteor as follows:

     curl https://install.meteor.com/ | sh

Then start the test app by running:

    $ cd repro/myapp
    $ meteor --production

In another terminal start the electron app:

    $ cd repro/
    $ electron .

**To test the difference, run then the meteor app without the `--production` flag and then restart electron.**

You may need to increase the number after the `?` in line 77 of the `main.js`, to prevent caching.

**Comment by zcbenz** [comment]
By turning off node integration (which you should otherwise meteor is not supposed to work correctly), I can see following error:

```
WebSocket connection to 'ws://interface/sockjs/674/gjoxbu7w/websocket' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

So it seems that you also need to interpret `ws://`.

Also if you only want to redirect the URL, the `session.webRequest` API is a much better choice.

**Comment by frozeman** [comment]
I turned of node-integration, and it didn't make a difference. The web socket error is not important for Meteors frontend to work, its just tries to connect to a server, and as the example with the `production` flag shows, it works.

This issue still seems to be valid to me

**Comment by zcbenz** [comment]
Yeah I tried the demo, but I'm not familiar with how meteor works. We can not debug into thousand lines of meteor's code for a particular problem.

**Comment by frozeman** [comment]
Is there a debug flags for electron, which i can use to help you guys debug this issue?

I don't think it has anything to do with the particular framework loaded, but rather with the amount of requests, or something similar. I assume a race condition somewhere when serving and executing the files over a custom protocol.

**Comment by frozeman** [comment]
Especially, when i use `protocol.interceptHttpProtocol('http', ...)` to simply rewrite `http://interface -> http://localhost:3000`, it should work exactly the same, as on a normal website, as i only alter the domain.

Though the behaviour is exactly the same as when using a custom protocol.

The meteor applications work fine, when requested directly.

**Comment by deepak1556** [comment]
Aside from the `ws` error, the number of requests with and without the interception are different. Not sure whats causing the requests to be halted, nothing weird shows up with `log-net-log`.

**Comment by deepak1556** [comment]
The todomvc application listed in the original post works fine with interception.

**Comment by frozeman** [comment]
@deepak1556 nice that you're here, hopefully you can help me get to the bottom of this issue :)

I just simplified the whole [repro](https://github.com/frozeman/electron-curstom-protocol-realtive-urls-repro) a lot more, so basically the only difference is now that i switch out the protocol, i leave everything as is:
```js
  protocol.registerHttpProtocol('mist', function(request, callback) {
      request.url = request.url.replace('mist:','http:');

      console.log(request.url);
      callback(request);

  }, function (error) {
    if (error)
      console.error('Failed to register protocol', error)
  });
```

Simply switching from `http://` to `mist://`, will make the app not work. So the only difference here is that i either use a custom protocol or not.
```js
mainWindow.loadURL('mist://localhost:3000/?2324'); // change to http://localhost:3000/ as reference
```

Also adding:
```js
protocol.registerStandardSchemes(['mist']);
```
Doesn't make it a standard protocol with a proper `location.origin`.

I tried rewriting the websocket URL `ws://` and i could do this successfully [see here](https://github.com/frozeman/electron-curstom-protocol-realtive-urls-repro/blob/master/backup.js#L2-L10) (though `//:myurls` won't get the domain appended, see https://github.com/atom/electron/issues/1747).   
It didn't make any difference and still doesn't work!  
I also know form test with meteor apps as static files, that the web socket connection doesn't matter (I'm the creator of [meteor-build-client](https://github.com/frozeman/meteor-build-client)).
Running the meteor app with `--production`, where it concatenates all files, the app works! Though there are more complex meteor apps, which even don't run, if i concatenate them... its surely a strange issue!

Besides this web socket connection failure, there is also no other issue i could debug..

Can i try anything to debug this further? I really need custom protocols to work like standard HTTP.

**Comment by arolson101** [comment]
I'm seeing this also.  In my protocol handler I print the request passed in and I get:
```
{ method: 'GET', referrer: '', url: 'app://' }
{ method: 'GET', referrer: '', url: 'app://' }
```
but if I change the scripts from ```<script src="vendor.js"></script>``` to ```<script src="app://vendor.js"></script>``` then I see the correct script response but the wrong .map request:
```
{ method: 'GET', referrer: '', url: 'app://vendor.js' }
{ method: 'GET',
  referrer: '',
  url: 'app://vendor.js/vendor.js.map' }
```

**Comment by frozeman** [comment]
I figured by adding a `/` on the end of loaded url, it works, but this still doesn't solve the issue i posted here..

**Comment by frozeman** [comment]
@zcbenz can you please re-open that issue, as it certainly is one and unsolved, so we can keep track of it?

I will get back to this very soon and hope to get more insight.

**Comment by hodgman** [comment]
I'm struggling with this same issue. Simply making a custom protocol that loads http files, makes javascript fail to execute properly. Was this issue resolved somehow?

**Comment by gpetrov** [comment]
I'm also getting this issue, trying to use custom app protocol to load the app to solve the file protocol origin problems as described in https://github.com/electron/electron/issues/19789

But fail because javascript includes can't be loaded.

Are we missing something @zcbenz and @MarshallOfSound ?
