### ISSUE TITLE
Better to load application from server or from local?

### ISSUE THREAD

**Issue by dukedougal** [atom/electron#4239]
I am developing an Electron application.

My understanding is that Electron can either load my HTML and JavaScript application code either from the locally installed files when someone downloads and installs my Electron app, or the other choice is that I can get Electron to load the application from a web server.

Are there pros and cons to either approach?

The downside that I see of running everything locally from the installed package is that whenever I change my application the user will need to download an update, whereas if I run it from a web server I can change the code any time.

I wonder also if major Electron applications like Visual Studio Code and GitHub Atom load their application files locally or from web server.

**Comment by sbruchmann** [comment]
What’s the point of running a desktop client that loads a web page? I already have multiple web browsers on my system…

**Comment by dukedougal** [comment]
>> What’s the point of running a desktop client that loads a web page? I already have multiple web browsers on my system…

The desktop client has different capabilities to a web browser.

My main questions are:

If I update my application code, then presumably the end user needs to download an update, along with all the Electron binaries?

Do Atom and Visual Studio Code load their application from the installed package files or from a web server?

**Comment by DerNivel** [comment]
Atom and Visual Studio Code load their application from the installed package files. It would be bad to load from a web server since then your application only works online.

**Comment by dukedougal** [comment]
>> It would be bad to load from a web server since then your application only works online.

Is that the only reason it would be bad?  What if I am perfectly happy that my application only works online - any other downsides or problems?

**Comment by DerNivel** [comment]
I think it's not really safe to load remote code.
And if you would load your app from a server you should load a minimal app locally to check for an internet connection to inform the user!

**Comment by dukedougal** [comment]
>> I think it's not really safe to load remote code which has access to the file system.

The application package has to be downloaded from the Internet which is no different to remote code.

**Comment by DerNivel** [comment]
I think there is a difference.

**Comment by lee-dohm** [comment]
This kind of discussion, where there isn't a concrete answer, is best on [Discuss, the official Atom (and Electron!) forum](https://discuss.atom.io).

In general, Electron is a framework that is designed to allow you to use web technologies to build desktop applications. This tends to point towards applications architected like Atom, where the code for the application and all of its packages is installed and executed locally even if data is obtained via network connections. I'm sure there are situations where different trade-offs might well be useful. This is just the main focus of the current design.
