### ISSUE TITLE
Any word on using Chakra engine?

### ISSUE THREAD

**Issue by Janneman84** [atom/electron#4240]
I was wondering if the new Node Chakra engine will make its way to Electron. Any word on this?

For example this would make it possible to use [node-uwp](https://github.com/Microsoft/node-uwp), which allows you to use Universal Windows Platform APIs in Node.js, like Bluetooth. It would be really nice if I could use BLE in a Windows Electron app :).

**Comment by zcbenz** [comment]
If Chromium switches to use Chakra engine, we will follow.
