### ISSUE TITLE
Can't change taskbar application name

### ISSUE THREAD

**Issue by mcaballeropinto** [atom/electron#4241]
We are using Electron V0.34.1 for our app and we found an issue we don't know how to solve yet. Our app shows Electron as its name in Windows taskbar when you do right click on it, the app shows the right title while it is running, is only the context menu that appears after right clicking on it what is showing the wrong name. Screenshot for reference:

<img width="306" alt="screen shot 2016-01-20 at 10 00 56 am" src="https://cloud.githubusercontent.com/assets/2819038/12600396/45689784-c44e-11e5-98dd-34d14a50c137.png">

We have tried everything we could:

* Added a title to the window and the HTML document.
* Renamed the .exe file.
* Set an appName. In fact if we do app.getName() we get the right name.
* Edited the the version-string resource of our .exe. We use electron-packager v5.2.1 for generating the exe and editing the resources.
* Added productName property to package.json file.
* Called app.setAppUserModelId('com.microsoft.storageexplorer'); in main process

Is there any other way I can't find to achieve this?

Thank you very much for your time!

**Comment by paulcbetts** [comment]
If you set an App User Model ID, this name is usually the name of your shortcut, as long as that shortcut _also_ has the same model ID in it (by default, it probably won't). Here's the code in Squirrel that does this:

https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/ShellFile.cs#L873

**Comment by zcbenz** [comment]
The exe file also has some meta information inside, including the app's name, you can use something like [ResEdit](http://www.resedit.net) to edit them.

It is recommended to use existing [packaging tools](http://electron.atom.io/docs/v0.36.5/tutorial/application-distribution/#packaging-tools) instead of manually packaging, so you don't have to take care this kind of problems.

**Comment by mcaballeropinto** [comment]
@paulcbetts Thanks for the tip! We don't use squirrel right now, but we will take your info in count then.

@zcbenz As I explained, we are already modifying those resources and we use the recommended packaging tools already. In fact, looking at it using ResEdit there is no electron anywhere.

Thanks guys for your help, any other suggestions? 

IMHO I don't think this issue is resolved unless I used the wrong channel to ask the questions, sorry if that is the case.

**Comment by zcbenz** [comment]
@mcaballeropinto I tend to close the issue if it is proved to work on other Electron apps. Using this issue as an example, at least Atom and Slack do not have the problem, and non of other Electron apps has reported similar issue before, so I think it is safe to assume the problem is on your side.

Have you installed your app into Program Files? And is there any other shortcut link pointing to your app? The rule for deciding the icon and name of a program on taskbar is not transparent, but generally Windows will try to use the information from exe files and shortcut links that have the same app user model ID, and you can right click on the task menu to find out the file that decides the name of the item.

<img width="306" alt="screen shot 2016-01-28 at 11 36 08 am" src="https://cloud.githubusercontent.com/assets/639601/12634317/6539458e-c5b3-11e5-8e5f-d6bf07b5583a.png">
<img width="380" alt="screen shot 2016-01-28 at 11 36 18 am" src="https://cloud.githubusercontent.com/assets/639601/12634322/6a28a198-c5b3-11e5-8b7c-128d833f3fbc.png">

**Comment by mcaballeropinto** [comment]
@zcbenz Thanks for clarifying! I am not running the app from any shortcut, is that the only way to show the right name in the taskbar? I am just running the generated EXE file by electron packager. Here is a similar screenshot of yours:

<img width="264" alt="screen shot 2016-01-28 at 10 37 44 am" src="https://cloud.githubusercontent.com/assets/2819038/12654934/515e0b10-c5ab-11e5-8db9-232dd02ed8f9.png">

And here is the details tab of the EXE file, as you can see there is no Electron reference:

![screen shot 2016-01-28 at 10 39 18 am](https://cloud.githubusercontent.com/assets/2819038/12654955/667bfe80-c5ab-11e5-80e7-8296abd751e4.png)

**Comment by paulcbetts** [comment]
Oh! Do you have a different Electron app installed? Because Electron sets the App ID, it gets joined with _other_ Electron apps that have the same AppID

**Comment by mcaballeropinto** [comment]
@paulcbetts That may be the case, I have been running other electron apps in the same machine. How do you set an AppID properly? Isn't that what I am doing with the line: app.setAppUserModelId('com.microsoft.storageexplorer');?

BTW, than you guys for your help!

**Comment by paulcbetts** [comment]
@mcaballeropinto Yep, that's right - just make sure to call that pretty early (i.e. right after `ready`)

**Comment by mcaballeropinto** [comment]
That did the trick! I wasn't executing setAppUserModelId method at the right time, it has to be executed right after the app ready event is thrown.

Thanks guys!

**Comment by iiegor** [comment]
Hello, I'm getting a similar issue with the latest electron version (v0.36.7) on windows 7 and 10 but unlike the author of this issue the app name is still "Electron" even with the app user model id set after//before the app ``ready`` event. I use ``electron-packager`` and all parameters like productName, ... etc are set (See the build script: [sindresorhus/caprine/package.json#L27](https://github.com/sindresorhus/caprine/blob/master/package.json#L27)), the unique difference I see here is that I don't use Squirrel.

**Comment by asethwright** [comment]
@iiegor Just wanted to let you know what worked for me. I was not using Squirrel to test my application either and could never get the taskbar name to modify correctly. This was occuring even after I had set all of the proper options for windows (like ProductName, etc). Windows 10 seems to remember the name of the taskbar item based on where your application folder is located in Program Files. Once I changed the name of the folder containing my .exe, Windows allowed me to pin to taskbar with the correct name.

Just a note: I also right clicked and did "Pin to Start" but I'm not sure if that made a difference. Hope this helps you out.

**Comment by iiegor** [comment]
@asethwright thanks for the information but unafortunately I just checked that and still doesn't works :confused:. Since I'm not the only one having this problem, I think this must be re-opened.

**Comment by loziobiz** [comment]
Same problem here! App packaged with electron-packager@7.0.1 but not bundled with squirrel. None of previous tips did the trick.

**Comment by arlenyan** [comment]
I examined explorer.exe using procmon and found it was reading a rogue start menu shortcut here:

"C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\Electron.lnk"

It must've been written there somewhere along the way during development. Anyway, I deleted that file and now everything works perfectly.

**Comment by JonMarbach** [comment]
@zcbenz Please don't link to resedit.net. The installers there are infected with malware... I know because I've been trying to clean up my machine after following your link above. (See https://github.com/electron/electron/issues/4357 as well)

**Comment by jorangreef** [comment]
I have a version of ResEdit from 2015. I scanned it today with ClamAV and it was clean. I see that Chrome now blocks the download page for resedit.net (I wanted to scan the newer binaries there).

Do you know when the trojan was introduced into ResEdit? Any alternative you would recommend?

**Comment by JonMarbach** [comment]
@jorangreef According to this, the  downloads have been infected on and off over the past few years:
https://www.mywot.com/en/forum/51496-resedit-net-gone-rogue

There probably is a safe version available from somewhere else, but I haven't searched yet.

**Comment by jorangreef** [comment]
Thanks @JonMarbach

**Comment by jdfwarrior** [comment]
I'm having the same issue using 1.4.3. I tried app.setAppUserModelId() and it doesn't seem to make a difference. 

I'm using electron-packager, everything seems to work right EXCEPT.. the text in the context menu when you right click the taskbar icon, the tooltip for the taskbar icon, and the text when you pin the app to the start menu

Any other thoughts suggestions? 
`app.on( 'ready', () => app.setAppUserModelId( 'com.our.organization' ) )`

This is how I'm setting it and this is one of the first lines after the requires at the top of my index.js for Electron.

**Comment by nikolovp** [comment]
I have the same issue with Electron v3.0.2.

`app.setName` and `app.setAppUserModelId` do not seem to help.

I believe Windows somehow caches the app name and details based on the executable's path, If I move the app to a different place I get the correct app tittle.

Btw, I do not have a shortcut for the app and I do not need one because of the way the app gets executed.
