### ISSUE TITLE
Cannot find module 'xxxxxx'

### ISSUE THREAD

**Issue by doowb** [atom/electron#4243]
Versions:
 - Electron 0.36.5
 - node 5.1.1
 - OSX 10.9.5 x64

I started off with the example app and was able to open a file and require in a module like `jquery` inside the renderer process fine.

I want to dynamically create my html files, so I start an express server in the main process and request the files through `.loadURL('http://localhost:8080');`.

This serves up the file, but then I started getting the `Cannot find module 'jquery'` error. I tried some of the other suggested and even tried another module from my `node_modules` but nothing was working.

I was able to use `protocol.interceptStringProtocol('file', handler)` to proxy `file://` requests through to the server and that was working when I ran the project locally by doing `electron .`.

Once I package up the project and try to run the app, I'm getting the `Cannot find module 'jquery'` error again. I've verified the `node_modules` exist in `Contents/Resources/app` inside the package.

Below is a screen shot of the app devtools open with the error and the `globalPaths` output. I'm not sure how to debug this or where to look next.

![image](https://cloud.githubusercontent.com/assets/995160/12602347/afb39756-c476-11e5-8ee6-6eb8c02e6081.png)

**Comment by zcbenz** [comment]
If you installed jQuery from npm, you can just call `require('jquery')`.

**Comment by doowb** [comment]
> tried another module from my node_modules but nothing was working

It's not just `jquery` and I did try `require('jquery')`. That's the second `Cannot find module 'jquery'` in the screenshot.

It's not finding anything I have in my `node_modules`.

**Comment by zcbenz** [comment]
I just noticed you were loading a remote page with `http://` protocol, in this case `require` won't be able to find local modules because there is no way to know current file system's path from a http page.

Usually [the community](https://github.com/atom/electron#community) is a better place for this kind of questions.

**Comment by doowb** [comment]
Thanks, I didn't notice the slack community when I was looking for answers, I'll check that out.

**Comment by gnail** [comment]
@zcbenz what about adding the main process' search path to the renderer? If I do the following I can `require('jquery')` with no problems:
````
require('electron').remote.process.mainModule.paths.forEach(function(path) {
    require('module').globalPaths.push(path);
});
````
What would be the downside of doing this?

**Comment by rohmanhm** [comment]
Hi @doowb have you solved this problem?

**Comment by rohmanhm** [comment]
Today I've got the same error.
https://stackoverflow.com/questions/51215282/electron-cannot-find-module-on-production-build

But the error only occurs on production build
![image](https://user-images.githubusercontent.com/7524911/42393484-b7bba898-8180-11e8-9370-a96d24f6c171.png)

Any suggestion will be helpful
