### ISSUE TITLE
How to find out if the app is running inside electron or not?

### ISSUE THREAD

**Issue by jheuing** [atom/electron#4248]
Hello,

if I have an angular app, I would like to develop and possibly run it in the browser as well. How can I differenciate if it's running inside electron and add a menu and such, or if not?

Thanks, Jan-Hendrik

**Comment by enlight** [comment]
You can just check if `process.versions.electron` is set.

This is not an issue, please ask questions in https://discuss.atom.io/c/electron or http://atom-slack.herokuapp.com/

**Comment by jheuing** [comment]
Wow, that was quick. Thanks for the answer...

I'll look at the other two places next time, thanks for mentioning it.

**Comment by svileng** [comment]
@jheuing You can inject JavaScript from Electron, and set a global variable for your app on `window`, which will be present only when Electron is running it. Check the `webPreferences` `preload` option on `BrowserWindow`: http://electron.atom.io/docs/v0.36.5/api/browser-window

**Comment by ericsoco** [comment]
https://github.com/electron/electron/issues/2288
