### ISSUE TITLE
autoUpdater error

### ISSUE THREAD

**Issue by wialy** [atom/electron#4250]
Hi,

I'm using electron updateUpdater module on OSX and get an error:
```
The file “update.sqLsfsW” couldn’t be saved in the folder “com.electron.displayagent.ShipIt”.
```

Do you know how can I get more information about what's wrong?

**Comment by zcbenz** [comment]
Under the hood the autoUpdater uses the Squirrel library, I suggest reporting this to [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac/issues) instead.
