### ISSUE TITLE
WidevineCDM - requestMediaKeySystemAccess failing

### ISSUE THREAD

**Issue by Chids-gs** [atom/electron#4252]
I'm using the latest electron version(v0.36.5) . Whenever I am trying to playback a Widevine encrypted MPEG Dash content, I'm getting an error when i invoke navigator.requestMediaKeySystemAccess() with the first argument being 'com.widevine.alpha' . I tried with almost all MPEG dash that is available online (http://www.dash-player.com/demo/drm-test-area/, DashJS Test streams), but facing the same issue.

Unencrypted MPEG Dash content plays fine in electron
 
The same content(widevine enabled) plays fine in Chrome.

Also, I have tried to re-install my Widevine Plugin and still the issue exists

**Comment by zcbenz** [comment]
Can you paste the details of the error from http://www.dash-player.com/demo/drm-test-area?

Also please make sure:
* Both `widevinecdm` and `widevinecdmadapter` files are copied.
* The pass of `widevinecdmadapter` is passed to `widevine-cdm-path`.
* The arch of plugin matches Electron.

You can also find some common problems in #2085.

**Comment by Chids-gs** [comment]
have attached the screenshot of the error I am getting.
![screenshot](https://cloud.githubusercontent.com/assets/6661161/12636458/1cae5b9c-c5b3-11e5-992e-d2eb03d4490a.jpg)

I did cross check if widevine plugins are loaded using navigator.plugins
![pluginsloaded](https://cloud.githubusercontent.com/assets/6661161/12636559/dffd8fc8-c5b3-11e5-8e6b-7ac45550e722.PNG)

**Comment by Chids-gs** [comment]
Sorry for the inconvenience. Issue was with my main.js. created a new app and it is working fine.

Thanks for the swift reply!
