### ISSUE TITLE
 Popup does not come up or gain focus on linux 

### ISSUE THREAD

**Issue by MarcoPolo** [atom/electron#4254]
To Repro off this [fork of electron-quick-start](https://github.com/MarcoPolo/electron-quick-start/tree/popup-not-focused-linux) and [relevant code](https://github.com/MarcoPolo/electron-quick-start/compare/master...MarcoPolo:popup-not-focused-linux?expand=1)

1. inside terminal: `npm start`
2. press the `Popup new window in 5s` button
3. switch back to terminal.
4. fail to see popup take focus

What should happen:
Step 4 should have the popup take focus and accept input. (Does this on osx correctly)

(Tested with ubuntu 14.04 on unity and Gnome Shell)

Quick screen gif:

![popup-linux](https://cloud.githubusercontent.com/assets/594035/12626534/f899a344-c4ed-11e5-97f7-18d6d4998899.gif)

Another interesting thing is that it pops up correctly if only the desktop has focus (not the terminal like above)

![popup-linux-focused](https://cloud.githubusercontent.com/assets/594035/12626545/0e8b369a-c4ee-11e5-871c-9bd8e529bd20.gif)

**Comment by zcbenz** [comment]
There are two ways to focus a window on Linux:
* send `_NET_ACTIVE_WINDOW` to window manager to request for focus;
* or call `XSetInputFocus` to tell X11 to force focusing the window.

In Electron we are using the first solution, and so is GTK+. Then the window manager is responsible for deciding how to focus the window, in your case, the window manager decides that your popup window should not take focus when another app is having the focus.

It is possible to just force focusing the window, but it would be a possible annoyance to users, and may be against the desktop environment's settings, resulting bugs like https://crbug.com/318937.

So I'm closing this as won't fix.
