### ISSUE TITLE
Error: Module did not self-register only on specific pages

### ISSUE THREAD

**Issue by aggregatejeff** [atom/electron#4255]
On specific pages (google's oauth screen, for example), the spellchecker module for a webview is failing to load (and causing issues). I'm using electron 0.36.5, with spellchecker loaded as part of a preload script. It works without an issue, except when the webview navigates to, as an example: https://accounts.google.com/o/oauth2/auth?access_type=offline.......

To replicate, create a webview with the spellchecker module in a preload script
go to gmail in the webview
click on your user
click on add account
submit necessary information
Error in the console should say "Error: module did not self register" and then any typing that triggers spellchecker will target disconnect / black out the webview.

I'm stumped as to why this is. Any help would be greatly appreciated.

**Comment by paulcbetts** [comment]
I suspect that this is a dupe of #4025

**Comment by aggregatejeff** [comment]
hrm. Almost certainly. I'll close this out.
