### ISSUE TITLE
NativeImage does not scale down

### ISSUE THREAD

**Issue by bahmutov** [atom/electron#4256]
Hi, 

I am capturing window screenshot on high resolution screen, which creates a NativeImage 2x as large as needed. For example, for window content 1000x1200 I get back the image with size 2000x2400. This could be explained by devicePixelRatio being 2 on my Mac.

I can save the image just fine
```js
window.capturePage(function (image) {
  var buffer = image.toPng()
  fs.writeFileSync('./image.png', buffer, 0)
});
```

I am trying to scale down the image using the following code
```js
const pngData = image.toPng();
const smallImage = NativeImage.createFromBuffer(pngData, 2);
console.log('scaled image size', smallImage.getSize())
fs.writeFileSync('./image.png', smallImage.toPng(), 0)
```

The file is written to disk, but it is empty.
Is there something that prevents proper scaling down of the NativeImage?

**Comment by zcbenz** [comment]
The scale factor of an image does not change the image itself, it is only an hint for systems that support high-DPI.

Electron doesn't provide any API for manipulating images, you have to use third party Node modules or manipulate Canvas instead.
