### ISSUE TITLE
How can I test the crashReporter? Is it possible to crash Electron somehow on demand?

### ISSUE THREAD

**Issue by lipis** [atom/electron#4259]
In particular I'm interested in doing that on Electron for Windows.

I'm trying to use the [crashReporter](https://github.com/atom/electron/blob/master/docs/api/crash-reporter.md) but I can't crash the app on demand to debug it :) We had couple of crashes and it looks like the `POST` request is not going through, or I'm doing something wrong.

Here is the `<form>` that handles the `POST` requests: https://electron-crash-reporter.appspot.com/5649391675244544/create/

You can use the following from the command line to submit a crash and it should return with a simple `200` if everything went well.. It works for me when I'm testing it manually.. but maybe I missed something somewhere.

```bash
echo 'Hello, world!' > crash.log
curl --form ver=ver \
  --form platform=platform \
  --form process_type=process_type \
  --form guid=guid \
  --form _version=_version \
  --form _productName=_productName \
  --form prod=prod \
  --form _companyName=_companyName \
  --form upload_file_minidump=@crash.log \
  https://electron-crash-reporter.appspot.com/5649391675244544/create/
```

**Comment by robertfirespotter** [comment]
The spec makes a call to "process.crash()" Maybe that will work?

https://github.com/atom/electron/blob/master/spec/fixtures/api/crash.html

**Comment by zcbenz** [comment]
The test case for crashReporter can help you there:
https://github.com/atom/electron/blob/master/spec/api-crash-reporter-spec.js

**Comment by lipis** [comment]
thanks all guys..
