### ISSUE TITLE
using Electron instead of phantomjs

### ISSUE THREAD

**Issue by lasryaric** [atom/electron#4262]
I see in the doc [electron vs nw.js](https://github.com/atom/electron/blob/master/docs/development/atom-shell-vs-node-webkit.md) that Electron can be a replacement of Phantomjs:
>  Electron's APIs are lower level so you can use it for browser testing in place of PhantomJS.

I am writing a desktop application that needs to go browse a few website to collect some data (PDF bills).
I tried 2 things in order to automate a BrowserWindow instance and have it navigate the website(s) by inputing the credentials, clicking on link etc, but I quickly met blockers.

# solution 1

use a preload script and communicate via ipcMain messages. The preload script handle the message and click on the buttons and inputs the data in the input fields via javascript.

**The problem is that the preload code is not available after navigating from one page to another.**

# solution 2
using BrowserWindow.webContents.executeJavascript("code") I send the code to click and input the data but in order to get a feedback from the browser, I am using:

```javascript
function clientClick(cssSelector) {
	const ipcRenderer = require('electron').ipcRenderer;
	
	var domElemement = document.querySelectorAll(cssSelector)

	console.log('clientClick: ', cssSelector)
	if (!domElemement || domElemement.length == 0) {
		callback(new Error("dom element not found for css selector: "+ cssSelector));

		return ;
	}

	domElemement[0].click();
	
	ipcRenderer.send('doneExecuting');
	
}
```

on `github.com` for example, the line  `const ipcRenderer = require('electron').ipcRenderer;` throws an error because Github has its own `require()` function exposed in the browser.

Here is the error thrown:
```
Uncaught Error: Could not find module electronn @ frameworks-9ee55ceaf87fc34dc86334249fef6cbece88e815478e0fbe81642d57ed0fff89.js:1clientClick @ VM102:2(anonymous function) @ VM102:17electron.ipcRenderer.on @ /Users/ariclasry/dev/hellobill/electron-quick-start/node_modules/electron-prebuilt/dist/Electron.ap…:45emitThree @ events.js:97emit @ events.js:175
```

**What is the best solution to use Electron as PhantomJS?** 

I know that nightmarejs is doing something similar so I will start looking at the source code right now.

**Comment by lasryaric** [comment]
after looking at nightmarejs source code, I understand that in the preload script you can attach your code to the window object, which will persist across page change.

```javascript
// preload.js
window.__hellobill = {};
window.__hellobill.ipc = require('electron').ipcRenderer;
window.__hellobill.runLoop = __hellobillLoop;
```

```javascript
//main.js

mainWindow.webContents.on('did-finish-load', function() {
 mainWindow.webContents.executeJavaScript("__hellobill.runLoop()");
});
```

**Comment by jlord** [comment]
@lasryaric Electron isn't a direct replacement of PhantomJS but can be used to build something similar to that. I'll clear up that documentation :soon: 

Looking at others like nightmarejs will hopefully get you on the right path. You might also find [maxogden/electron-microscope](https://github.com/maxogden/electron-microscope) useful :microscope:
