### ISSUE TITLE
Fatal error on exit electron app

### ISSUE THREAD

**Issue by s-a** [atom/electron#4266]
[7136:0129/081452:FATAL:scoped_handle.cc(44)] Check failed: false.
    Backtrace:
            (No symbol) [0x00C8D517]
            (No symbol) [0x00C87A57]
            (No symbol) [0x00CBAEBF]
            (No symbol) [0x00CBAF01]
            (No symbol) [0x00CB100B]
            (No symbol) [0x00CB0A0B]
            (No symbol) [0x00C33318]
            (No symbol) [0x00C334E7]
            (No symbol) [0x00BDEF65]
            (No symbol) [0x00BDF273]
            v8::TypeSwitch::match [0x5A01A96E+651326]
            v8::Locker::IsLocked [0x59F09D1C+804588]
            v8::Locker::IsLocked [0x59F0C9CD+816029]

Steps to reproduce

    $ npm install -g iron-node;
    $ iron-node;
    #press Ctrl+w

Just tried to reproduce but this happens only in distributed version.

Windows 10 . Electron 0.36.5.

ref.: https://github.com/s-a/iron-node/issues/86

**Comment by felicienfrancois** [comment]
I also get a renderer crash when quitting my app, on windows 10 with electron 0.36.6 (0.36.5 was working well)
```
[8320:0129/150532:FATAL:scoped_handle.cc(44)] Check failed: false.
Backtrace:
        (No symbol) [0x00007FF6F09FE401]
        (No symbol) [0x00007FF6F09F787C]
        (No symbol) [0x00007FF6F0A38569]
        (No symbol) [0x00007FF6F0A2C2AB]
        (No symbol) [0x00007FF6F0A2BA7E]
        (No symbol) [0x00007FF6F0980819]
        (No symbol) [0x00007FF6F0980ABC]
        (No symbol) [0x00007FF6F090991B]
        (No symbol) [0x00007FF6F0909D3F]
        v8::TypeSwitch::match [0x00007FF9513BBA2B+727259]
        v8::Locker::IsLocked [0x00007FF95126D7B7+1036007]
        v8::Locker::IsLocked [0x00007FF95126CB52+1032834]
        (No symbol) [0x0000003D7EE08B1F]
```
