### ISSUE TITLE
os.platform() returns 'browser', which isn't an OS

### ISSUE THREAD

**Issue by timruffles** [atom/electron#4270]
`os.platform()` should return the [operating system](https://nodejs.org/api/os.html#os_os_platform). It has just started to return 'browser'. 'browser' isn't an OS.

It's not very to break/change node APIs! :)

**Comment by sbruchmann** [comment]
Which operating system and version of electron are you using? I could not reproduce this on OS X `10.11.3` and electron `0.36.6`.

**Comment by timruffles** [comment]
Sorry! False alarm, this is `browserify`'s doings. :blush:

**Comment by wangfpp** [comment]
@timruffles  how dou you resolve this problme?

**Comment by McCaulay** [comment]
@wangfpp I fixed this by setting NodeIntegration to true in [Vue CLI Plugin Electron Builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration). May not be the same in your case but if anyone else stumbles on this and is using it, this may be the solution.
