### ISSUE TITLE
Throw launch-time error on OS X 10.8.x and update docs

### ISSUE THREAD

**Issue by merkg** [atom/electron#4273]
It appears that Electron no longer supports 10.8.x; see:
https://github.com/atom/electron/issues/3530
> zcbenz commented on Nov 23, 2015
> Yeah, I think we used to support 10.8, but at some time we broke that and no one complained.

However, the documentation still says that 10.8 is supported:
http://electron.atom.io/docs/v0.36.5/tutorial/supported-platforms/
> the minimum OS X version supported is OS X 10.8.

and it continues to cause confusion for those trying to run on 10.8; a small sampling of cases:
https://github.com/Microsoft/vscode/issues/296
https://github.com/Microsoft/vscode/issues/1207
https://github.com/PancakeBot/PancakePainter/issues/47

If 10.8 is no longer supported, the runtime should trigger a meaningful launch-time error rather than crashing, presumably by updating the min supported OS key so that the OS will simply refuse to launch the app and inform the user as to why.

The documentation should also be updated to reflect the actual minimum requirement of OS X 10.9.

**Comment by lukeadams** [comment]
Seems similar to atom/atom#1598 (They patched it in Atom but not Electron).
The issue you linked has a good point https://github.com/atom/electron/issues/3530#issuecomment-158876952: Chrome dropped support for 10.8 anyways. I think it's safe to bump.

**Comment by ddlsmurf** [comment]
Ok so I'm maybe the only one, but anyone know which is the latest commit to work on 10.8 ?
