### ISSUE TITLE
Failed to load resources: net::ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by juturu** [atom/electron#4280]
In Electron v0.36.0 on MAC, loading web app with big set of javascript files and assets is causing chromium to hit "Failed to load resources: net::ERR_INSUFFICIENT_RESOURCES" error while loading javascript files. 

This issue is happening randomly and only on MAC. I don't see this issue on windows for the same app. Any ideas?

**Comment by zcbenz** [comment]
There is a default limitation on how many files you can open on POSIX systems, you can call `process.setFdLimit` to change it:

```js
process.setFdLimit(8192);
```

**Comment by juturu** [comment]
Thanks @zcbenz

**Comment by tiagorangel2011** [comment]
This happened to me on Windows 11, wonder why.
