### ISSUE TITLE
ERROR:archive.cc(143)] FILE_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by bpasero** [atom/electron#4282]
I am getting this in the console when I start VS Code with Electron 0.36.7 on Windows 10. Not much more info than that and it does not seem to cause issues, but wanted to report it.

**Comment by zcbenz** [comment]
This is a debugging message, I'll remove it for non-errors.

**Comment by theIYD** [comment]
@zcbenz I have been facing a sentry alert for this as well on Electron 30.0.8. 

Below is the timeline of events: 

```
Exception - This event
04:14:48.000 AM
Error: FILE_ERROR_NOT_FOUND

04:14:48.005 AM
app.browser-window-focus

04:14:48.005 AM
window.focus

04:14:47.922 AM
window.show

04:14:47.904 AM
app.browser-window-created

04:14:47.904 AM
app.web-contents-created

04:14:47.876 AM
app.browser-window-created

04:14:47.873 AM
app.web-contents-created

04:14:47.732 AM
app.session-created

04:14:47.712 AM
app.ready

04:14:47.709 AM
app.will-finish-launching
```
