### ISSUE TITLE
onBeforeSendHeaders: Can't add custom headers

### ISSUE THREAD

**Issue by romaincointepas** [atom/electron#4283]
The following code doesn't add the `X-Test` headers to all requests from the session.

```
session.defaultSession.webRequest.onBeforeSendHeaders(function(details, callback) {
  details.requestHeaders['X-Test'] = "Hello";
  callback({cancel: false, requestHeaders: details.requestHeaders});
});
```

It seems like at the moment, this approach can only modify the currently available headers (Accept, Accept-Encoding, Accept-Language, Upgrade-Insecure-Requests and User-Agent).

This will work and modify the User-Agent header:

```
session.defaultSession.webRequest.onBeforeSendHeaders(function(details, callback) {
  details.requestHeaders['User-Agent'] = "New UA";
  callback({cancel: false, requestHeaders: details.requestHeaders});
});
```

*Using Electron 0.36.7*

**Comment by deepak1556** [comment]
It does send the headers,
![screenshot](https://cloud.githubusercontent.com/assets/964386/12696157/c4ced398-c788-11e5-8189-02cddb7e33c8.jpg)
 verified headers being sent using `log-net-log` for the same code.

**Comment by zcbenz** [comment]
Are you using the API in renderer process? If so that's because the `remote` module doesn't support adding property to remote objects.

**Comment by romaincointepas** [comment]
@zcbenz Yes that's it! I didn't think about that.

Closing the issue!

**Comment by bahmutov** [comment]
Can I ask how to add a custom header for a webview then?
```js
const webview = document.createElement('webview')
webview.setAttribute('id', 'app')
webview.setAttribute('src', base)
webview.setAttribute('httpreferrer', base)
// one started loading
const session = webview.getWebContents().session
session.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
    details.requestHeaders['X-Test'] = 'test'
    callback({cancel: false, requestHeaders: details.requestHeaders})
})
```
the new header is not sent :(

**Comment by CliffReimers** [comment]
> Can I ask how to add a custom header for a webview then?
> 
> ```js
> const webview = document.createElement('webview')
> webview.setAttribute('id', 'app')
> webview.setAttribute('src', base)
> webview.setAttribute('httpreferrer', base)
> // one started loading
> const session = webview.getWebContents().session
> session.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
>     details.requestHeaders['X-Test'] = 'test'
>     callback({cancel: false, requestHeaders: details.requestHeaders})
> })
> ```
> 
> the new header is not sent :(

```js
session.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
     const requestHeaders = {...details.requestHeaders, ...{
          ['X-Test']: 'test'
    }};
     callback({cancel: false, requestHeaders})
})
```

**Comment by sadeghtanha2018** [comment]
please don't send to me

you made me 😰

در دوشنبه ۲۶ نوامبر ۲۰۱۸،‏ ۱۵:۳۴ David Reimers <notifications@github.com
نوشت:

**Comment by lishoulong** [comment]
https://github.com/electron/electron/issues/4283#issuecomment-177381736

@zcbenz , as you say in this reply, in the render process, the remote module can not add property for the remote object.
In my case, I use the browserWindow.webContents.session.webRequest.onBeforeSendHeaders([],function(details, fn) {}).
The logic come into my onBeforeSendHeaders callback, but my change to the details.requestHeaders alse not work.
