### ISSUE TITLE
[.\node_modules\.bin\electron-rebuild.cmd ] window has a problem

### ISSUE THREAD

**Issue by code1031** [atom/electron#4284]
.\node_modules\.bin\electron-rebuild.cmd      ( electron version 0.36.7)
executing result:
Unable to find electron-prebuilt's version number, either install it or specify
an explicit version

**Comment by etiktin** [comment]
This issue is with electron-rebuild so it's probably better if you open it there https://github.com/electronjs/electron-rebuild .

**Comment by code1031** [comment]
![image](https://cloud.githubusercontent.com/assets/15321237/12699537/e20ed4c8-c7f9-11e5-9d98-c7a4b5f5a9ea.png)

**Comment by code1031** [comment]
![image](https://cloud.githubusercontent.com/assets/15321237/12699542/fe0d75c6-c7f9-11e5-8f32-cf0fee4f7d38.png)

**Comment by paulcbetts** [comment]
@code1031 This is node-pre-gyp continuing to not work

**Comment by code1031** [comment]
@paulcbetts thanks a lot ,how to solve the problem?

**Comment by enlight** [comment]
- Run [electron-rebuild](https://github.com/electronjs/electron-rebuild) with the `pre-gyp-fix` option.
- Patch `node-pre-gyp`, you can do that by installing the branch from [PR 187](https://github.com/mapbox/node-pre-gyp/pull/187) locally.
- Monkey-patch `node-pre-gyp` at runtime using https://github.com/enlight/electron-node-pre-gyp-fix

**Comment by code1031** [comment]
I am sorry,I couldn't understand，I can concretely how to do ?

**Comment by code1031** [comment]
tried many times ,only to find 
![image](https://cloud.githubusercontent.com/assets/15321237/12709934/e483ea02-c8eb-11e5-8bb1-cea9fe5605f8.png)

**Comment by code1031** [comment]
![image](https://cloud.githubusercontent.com/assets/15321237/12710320/58b32ce0-c8f0-11e5-9bfe-22d53c5431d4.png)
