### ISSUE TITLE
Lots of errors printed when running 0.36.7 in Ubuntu 15 from Parallels

### ISSUE THREAD

**Issue by bpasero** [atom/electron#4285]
Running with Electron 0.36.7 on Ubuntu 15 in Parallels from my Mac, I am seeing a lot of the following logged as errors to the console:

```
ERROR:gles2_cmd_decoder.cc(2124)] [.RenderWorker-0xe10a7b6b9a0]GL ERROR :GL_INVALID_OPERATION : GLES2DecoderImpl::DoReleaseTexImage2DCHROMIUM: <- error from previous GL command
```

Any clues what this could be?

**Comment by zcbenz** [comment]
This is a bug of the OpenGL implementation of Parallels, they didn't implement some OpenGL command on Ubuntu while the command was used in Chrome 47.

I think it is safe to ignore this error.
