### ISSUE TITLE
Custom scrollbars creating equally sized empty gaps

### ISSUE THREAD

**Issue by scholtzm** [atom/electron#4294]
I have been experiencing issues with my app after styling scrollbars via `::-webkit-scrollbar`. To narrow down the issue, I have created small test case and here are the screenshots:

`index.html` directly opened in Chrome, everything looks correct:
![screen shot 2016-01-31 at 22 47 03](https://cloud.githubusercontent.com/assets/2640934/12705302/0f772382-c86f-11e5-9ca7-f07b40cbf04f.png)

`index.html` opened via Electron, no extra code, just one `BrowserWindow`:
(notice the gap on the right)
![screen shot 2016-01-31 at 22 51 34](https://cloud.githubusercontent.com/assets/2640934/12705303/35bb0f90-c86f-11e5-8454-9f8ffa636353.png)

to make it a bit more obvious I resized the scrollbars to `20px` (both `width` and `height`):
(this time I notice there's actually another gap at the bottom too)
![screen shot 2016-01-31 at 22 52 54](https://cloud.githubusercontent.com/assets/2640934/12705306/4867d5ec-c86f-11e5-9616-001b73224521.png)

after resizing the `BrowserWindow` just very slightly:
(the gap on the left bottom disappears)
![screen shot 2016-01-31 at 22 53 04](https://cloud.githubusercontent.com/assets/2640934/12705320/90c2d1d4-c86f-11e5-8c4f-6c1f4660d0d1.png)

I haven't been able to reproduce any of the issues in regular Chrome browser. Removing scrollbar styles from the style sheet removes these issues completely.

Tested on OSX 10.11.3 with Electron v0.36.7. Same thing happening on Windows 8.1.

**Comment by zcbenz** [comment]
Were you testing the code in Chrome 48? Electron is still using Chrome 47 so can you test whether the code works in Chrome 47? I would like to verify whether it is a bug of Electron or Chrome 47.

**Comment by scholtzm** [comment]
Yep, tested with `Version 48.0.2564.97 (64-bit)`.

I will have to figure out how to get hold of v47 and I'll report back.

**Comment by scholtzm** [comment]
@zcbenz 

Dammit Google! :grinning: 

(v48 and v47 respectively)
![darn](https://cloud.githubusercontent.com/assets/2640934/12726418/c0a1715a-c917-11e5-8895-647f5db40d61.png)

Hopefully Electron with v48 will be released soon. In the meanwhile, I will have to disable custom scrollbars or downgrade to lower version.
