### ISSUE TITLE
API for checking whether Dark Mode is enabled on OS X

### ISSUE THREAD

**Issue by sindresorhus** [atom/electron#4300]
http://www.macworld.co.uk/how-to/mac-software/turn-on-yosemites-dark-mode-on-mac-3534690/

Dark Mode was introduced in OS X 10.10.

I'm thinking a method `app.isDarkMode()` and a `app.on('dark-mode')` event.

This is useful so you have the ability to make your app dark when Dark Mode is enabled.

For the method you could use:

```objective-c
NSString *mode = CFBridgingRelease(CFPreferencesCopyValue((CFStringRef)@"AppleInterfaceStyle", kCFPreferencesAnyApplication, kCFPreferencesCurrentUser, kCFPreferencesCurrentHost));
```

And for the event, there's:

```objective-c
[[NSDistributedNotificationCenter defaultCenter] addObserver:self selector:@selector(darkModeChanged:) name:@"AppleInterfaceThemeChangedNotification" object:nil];

-(void)darkModeChanged:(NSNotification *)notif {
    NSLog(@"Dark mode changed");
}
```

-

Similar to https://github.com/atom/electron/issues/1861, but this is IMHO a separate, and more actionable and focused request.

**Comment by zcbenz** [comment]
Closed with #4646.
