### ISSUE TITLE
autoUpdater error on first run (windows)

### ISSUE THREAD

**Issue by zh99998** [atom/electron#4306]
first run after install (opened by installer automatically), autoUpdater may trigger an error
```
Couldn't acquire lock, is another instance running
```

screenshot: http://postimg.org/image/j8zi7lz8z/

and this time app can't update.

close app and run it again everything will be ok.

**Comment by paulcbetts** [comment]
Are you sure you're trying to do this in `--squirrel-firstrun`? If you're doing this in `--squirrel-installed` then this is by-design. If it's the former, you probably just need to wait a second or three to let Squirrel exit

**Comment by zh99998** [comment]
i'm not handle --squirrel-firstrun since it's not documented in https://github.com/atom/grunt-electron-installer.

in --squirrel-installed, i only created desktop icon, not trying update.

I'll try to handle --squirrel-firstrun in my code.

**Comment by zh99998** [comment]
yes it works , my code is:
```
    if (process.argv[1] == '--squirrel-firstrun') {
        setTimeout(()=> {
            autoUpdater.checkForUpdates();
        }, 3000)
    } else {
        autoUpdater.checkForUpdates();
    }
```

but just wait for 3 seconds is not graceful, since we don't know when will it finish.

it's better to check squirrel process running in checkForUpdates internally.

or at least, document it in autoUpdater.

**Comment by zcbenz** [comment]
I'm closing this since it is a by design in [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows).

**Comment by paulcbetts** [comment]
I'll try to rig this so it at least doesn't fail when you check for updates immediately after first run
