### ISSUE TITLE
Question: Possible to access some DevTools functions?

### ISSUE THREAD

**Issue by s-a** [atom/electron#4310]
Googled a while to find a way to access some devtools functions programmatically like ```revealInNavigator(filename)``` ```openSourceCodeView(filename)``` ```setBreakpoint(filename, linenumber)``` without success.  

Do we have some functions like that available in Electron ?

![image](https://cloud.githubusercontent.com/assets/1270662/12729241/0bc4cd5e-c926-11e5-8b4c-26e9b4f5cc80.png)

**Comment by deepak1556** [comment]
Run the following under devToolsWebContents context and you can refer to [InspectorFrontEndHostAPI.js](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/host/InspectorFrontendHostAPI.js) for the declaration.

```javascript
devToolsWebContents.executeJavaScript("DevToolsAPI.revealSourceLine(['some url'])")
```

`revealInNavigator` use `DevToolsAPI.revealSourceLine`
`openSourceCodeView` use `DevToolsAPI.showPanel` // not yet available
and you can use rdp with `webcontents.debugger` api for instrumentation purpose.

**Comment by s-a** [comment]
@deepak1556 thanks for the quick reply, Just tried from devtools debugger console.```require("remote").getCurrentWindow().webContents.executeJavaScript("DevToolsAPI.revealSourceLine(['c:\git\test\index.js'])")```

This Throws ```DevToolsAPI is not defined``` Ihave also tried to access ```InspectorFrontendHostAPI``` any idea what i am doing wrong?

**Comment by deepak1556** [comment]
you need to run them under `devToolsWebContents` context.

```
require("remote").getCurrentWindow().devToolsWebContents.executeJavaScript()
```

**Comment by s-a** [comment]
Tried ```revealSourceLine``` yesterday but nothing happens. No exception also. Will try debugger API this weekend.

**Comment by deepak1556** [comment]
Make sure that url passed to `revealSourceLine` is something the devtools is aware of.
