### ISSUE TITLE
0.36.7 fatal error on .close() .destroy() (on windows 10)

### ISSUE THREAD

**Issue by odubuc** [atom/electron#4311]
I'm using Windows 10 and version 0.36.7

when using `.close()` or `.destroy()` on a  `BrowserWindow` or by closing the windows manually in the UI

I get this error
```
[14576:0201/150158:FATAL:scoped_handle.cc(44)] Check failed: false.
Backtrace:
        (No symbol) [0x00007FF7BBB8E401]
        (No symbol) [0x00007FF7BBB8787C]
        (No symbol) [0x00007FF7BBBC8569]
        (No symbol) [0x00007FF7BBBBC2AB]
        (No symbol) [0x00007FF7BBBBBA7E]
        (No symbol) [0x00007FF7BBB10819]
        (No symbol) [0x00007FF7BBB10ABC]
        (No symbol) [0x00007FF7BBA9991B]
        (No symbol) [0x00007FF7BBA99D3F]
        v8::TypeSwitch::match [0x00007FFB96E6BA2B+727259]
        v8::Locker::IsLocked [0x00007FFB96D1D7B7+1036007]
        v8::Locker::IsLocked [0x00007FFB96D1CB52+1032834]
        (No symbol) [0x0000033F2D408B1F]
```

I think I found a similar issue "closed" [here](https://github.com/atom/electron/issues/4127) 
so if I'm just too quick and the fix isn't available yet I'll simply wait.
Thank you.

**Comment by zcbenz** [comment]
Are you sure you are using 0.36.7?

**Comment by odubuc** [comment]
You were right, I has it installed globally in another project folder... 
I just tested it by creating 1000 document and closing them.
No problem anymore. 
Thank you for your time and sorry for this silly mistake :)
