### ISSUE TITLE
PDF Links for Fragment Identifiers are not generated

### ISSUE THREAD

**Issue by caleblloyd** [atom/electron#4313]
Links with fragment identifiers (like #id-of-heading) do not show up as links in PDFs generated from Electron.

Using electron-pdf with Electron 0.36.7, I get the PDF:
https://caleblloyd.com/downloads/pdf/electron.pdf
Links in the Table of Contents do not work.

Using the latest Chromium, I get:
https://caleblloyd.com/downloads/pdf/chromium.pdf
Links in the Table of Contents work properly.

Command in electron-pdf was:

    electron-pdf http://www.sec.gov/Archives/edgar/data/789019/000119312516441821/d15167d10q.htm electron.pdf

**Comment by zcbenz** [comment]
Chrome 48 has switched to use pdfium for PDF generating, so we will get this fixed in Electron once we [upgrade to Chrome 48](https://github.com/atom/libchromiumcontent/pull/175).

**Comment by danburzo** [comment]
We've also had this problem. Seems that the printer generates bad Destination references for the links, writing just the fragment identifier in a link without creating a reference with that identifier in the dictionary. 

We've managed to go around this limitation by post-processing the PDF with Apache PDFBox in Java, but there are also Python libraries that can help, e.g. [PyPDF2](https://pythonhosted.org/PyPDF2/Destination.html). 

The idea is to iterate through all the annotations, identify the broken ones, and set the correct destinations.

But yes, we're very much looking forward to that pull request being merged :-D
