### ISSUE TITLE
Avoid ESC-key quits fullscreen

### ISSUE THREAD

**Issue by jhovgaard** [atom/electron#4316]
I have a fullscreen switch on my app. I'm switching between fullscreen using:
`webkitRequestFullscreen()` and `webkitExitFullscreen()`. 

However when pressing the escape key fullscreen gets switched off.

I understand the purpose of this functionality in the browser, but is it possible to avoid the behavior in Electron?

Thanks!

**Comment by zcbenz** [comment]
You can use the `BrowserWindow.setFullScreen` API if you don't want the browser-like behavior.

**Comment by jhovgaard** [comment]
@zcbenz Thanks for your quick answer! Is it possible to access the API directly from the browser, or?

**Comment by zcbenz** [comment]
Yeah you can use the `remote` module.

**Comment by jhovgaard** [comment]
Got it. Thanks a lot!

**Comment by AuWiMo** [comment]
I found kiosk mode to be a solution 
https://stackoverflow.com/questions/64709288/preventing-a-user-from-exiting-full-screen-mode-to-window-mode-in-electron
