### ISSUE TITLE
Global shortcut register 'super+space' on Windows returns false

### ISSUE THREAD

**Issue by jbasinger** [atom/electron#4319]
I'm trying to make an app where the main window pops up by hitting window_key+space, but registering that key combination with global shortcuts returns false.

Here is a sample app gist reproducing the error
https://gist.github.com/jbasinger/6f09d502f813e3d7fb0b

**Comment by zcbenz** [comment]
Global shortcuts can only work when the shortcut has not been taken by other applications, in your case `Super + Space` is a reserved shortcut by Windows, so there is no way for other app to register it.
