### ISSUE TITLE
can i launch a window with special URL like chrome://inspect/

### ISSUE THREAD

**Issue by lin-chao** [atom/electron#4321]
can i launch a window with special specail URL like chrome://inspect/#devices ?

i find i can launch a window with "chrome://serviceworker-internals"

but i cannot  launch a window with  chrome://inspect/ or  chrome://flags/

thank you~

**Comment by zcbenz** [comment]
Only certain `chrome://` URLs are supported in Electron, to support others we have to port corresponding code from Chromium (sometimes the work can be huge).
