### ISSUE TITLE
Ignore focus

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#4323]
Is it possible to ignore a users click on the window and prevent its focus?

I have an application that launches another application and while it's loading, I show a splash/loading screen on the first application. But if the user gets bored and clicks on the first application it will cause the newly opened application to appear below as the last command to the OS was to focus the first application.

I've seen `win.setIgnoreMouseEvents(ignore)` in the docs, but that is OS X only and we are running this application on Windows 7. Pointer events and JS prevent default are also no good as the user has already interacted and focused the application window to fire them.

**Comment by zcbenz** [comment]
I'm merging this to #2864.
