### ISSUE TITLE
Is it possile to have different menus for each window

### ISSUE THREAD

**Issue by grandtiger** [atom/electron#4327]
Question: if an Electron app has multiple windows, can each window has a different menu? I tried the following with different templates on different windows, but the last one that get set override the first one. Please let me know what I did wrong, or if this is not possible right now. Thanks a lot!

```
var menu = Menu.buildFromTemplate(template);
Menu.setApplicationMenu(menu);
```

**Comment by enlight** [comment]
According to the docs, yes it's possible to set a menu for each BrowserWindow, but only on Windows or Linux: https://github.com/atom/electron/blob/v0.36.7/docs/api/browser-window.md#winsetmenumenu-linux-windows

**Comment by grandtiger** [comment]
@enlight Thanks for the link! I am on windows and I have managed to get it to work.

**Comment by kevinsawicki** [comment]
Closing this out, thanks @enlight for providing the answer and link :+1:

**Comment by axelrindle** [comment]
Is there any way to get this to work on OSX, without having to create a menu with HTML?

**Comment by sethlu** [comment]
@axelrindle The application menu is shared between all browser views of the app on macOS. I think it is possible instead to switch between different application menus for the windows?

**Comment by alexsan134** [comment]
Its possible:

In Renderer or Main Proccess make two functions with menus templates like this:

main menu:
`function createMenu(){
    var menu = Menu.buildFromTemplate([
    {
        //your menu items
    }
   ])
    Menu.setApplicationMenu(menu);
}`
second menu:
`function createMenuwin(){
    var menu = Menu.buildFromTemplate([
    {
        //your menu items
    }
   ])
    Menu.setApplicationMenu(menu);
}`

when you call the second window : Example open an image:

`function openIMG(path){
    win = new BrowserWindow({  
        width: 800, 
        height: 550,
       frame: true, 
       backgroundColor : "rgba(0,0,0,0)",
        vibrancy: 'medium-light',
    });
    win.loadFile(path);
    createMenuwin();
    win.on('close', () =>{
        `createMenu();`
    })
}`

when the second window is open create an app menu with
`createmenuwin()`

when the second window is closed call the event:
`win.on('close', () =>{})`

inside the close event of the second window , call:
`createMenu();`

**Comment by axelrindle** [comment]
@alexsan134 Thanks, I will try this 👍 😄

**Comment by mauris** [comment]
I think it might be better to run `Menu.setApplicationMenu` in the `focus` event of `BrowserWindow`.

**Comment by PkAIR** [comment]
Can agree with @mauris - you should check also focus for a window cuz when you have two windows opened side by side both of them will have menu for the later opened. Tested on manjaro linux.

**Comment by Timmmm** [comment]
This is the code we use:
