### ISSUE TITLE
Error executing execSync "EPERM: operation not permitted, write"

### ISSUE THREAD

**Issue by mapaiva** [atom/electron#4328]
Hi guys,

I'm making a electron app and had this problem :disappointed:. The error is throwed after execute a call for `child_process.execSync`. When I run electron from the command line, this code works without  problem.
I've tested it on others platform and on linux and mac works nicely.

I already saw the #2033 and #3266 but nothing resolutive for there.

I'm on **Windows 10 x64** and using the Electron version **0.36.4**.

That's the command I try to execute.
![capturar](https://cloud.githubusercontent.com/assets/8807694/12754145/42634f08-c9b1-11e5-80b3-bc122bff7539.PNG)

That's the response
![capturar2](https://cloud.githubusercontent.com/assets/8807694/12754183/66f265d4-c9b1-11e5-8501-a8930cc9c35a.PNG)

Any ideas what it can be? Any workarounds or solutions?

Thanks
Matheus

**Comment by kevinsawicki** [comment]
@mapaiva are you able to provide a reduced test application that demonstrates this behavior?

**Comment by mapaiva** [comment]
@kevinsawicki Of course.

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by soichih** [comment]
I am hit by a very similar problem on Windows 10 + electron 1.0.1 and 1.0.2 (I haven't tried 1.1.0 because it currently does not work with Windows 10).

As part of my electron app, I am using electron-sudo.exec which eventually calls child_process.execSync().  This function then run following which causes the exception.
```
 if (inheritStderr)
    process.stderr.write(ret.stderr);
```

Here is the full call stack.
```
fs.js:706 Uncaught Error: EPERM: operation not permitted, write
fs.writeSync	@	fs.js:706
SyncWriteStream.write	@	fs.js:2064
execSync	@	child_process.js:519
writeTempBatchFile	@	E:\kdinstall-win32-x64\resources\app\node_modules\electron-sudo\index.js:12
attempt	@	E:\kdinstall-win32-x64\resources\app\node_modules\electron-sudo\index.js:89
exec	@	E:\kdinstall-win32-x64\resources\app\node_modules\electron-sudo\index.js:206
AppComponent.install	@	app.component.ts:355
```

More detailed version info..
```
ares:"1.10.1-DEV"
atom-shell:"1.0.1"
chrome:"49.0.2623.75"
electron:"1.0.1"
http_parser:"2.6.2"
modules:"47"
node:"5.10.0"
openssl:"1.0.2g"
uv:"1.8.0"
v8:"4.9.385.28"
zlib:"1.2.8"
```
