### ISSUE TITLE
Opening an external url with IE

### ISSUE THREAD

**Issue by gj1118** [atom/electron#4334]
Hi, 
I am facing a issue wherein i have to open an external link in IE only. The thing is the external link does not work with other other browsers. Is there a way this can be implemented. Please suggest. 

thanks and regards
gagan

**Comment by baconface** [comment]
Easy peasy.
```javascript
var exec = require('child_process').exec;
exec('start "" "iexplore" "http://google.com/"');
```

**Comment by gj1118** [comment]
@baconface You are the man sir.. Here is a :+1: thumbs for you :)
