### ISSUE TITLE
Tray error: Uncaught Exception: TypeError: Error processing argument -1.

### ISSUE THREAD

**Issue by onetwopunch** [atom/electron#4335]
Following the docs at http://electron.atom.io/docs/v0.36.5/api/tray/ I have the following code:

```
'use strict';

const electron = require('electron');

const app = electron.app;
const Menu = electron.Menu;
const MenuItem = electron.MenuItem;
const Tray = electron.Tray;
const path = require('path');

let tray, menu, quit;

app.on('ready', function() {
  tray = new Tray(path.join(__dirname, 'icon.png'));
  menu = new Menu();
  quit = new MenuItem({
    label: "Quit",
    click: app.quit
  });
  menu.append(quit);
  tray.setToolTip('This is my application.');
  tray.setContextMenu(menu);
})
```

When I run `npm start` I get the error `Uncaught Exception: TypeError: Error processing argument -1.` at the line that instantiates `Tray`. Not sure what this error means or why I got it.

**Comment by kevinsawicki** [comment]
Are you sure the `icon.png` exists at that path? `new Tray` will throw an error when the path is invalid.

**Comment by onetwopunch** [comment]
@kevinsawicki So I literally just got it working with this code:

    let image = nativeImage.createFromPath(path.join(__dirname, 'img', 'icon.png'))
    tray = new Tray( image );

**Comment by onetwopunch** [comment]
@kevinsawicki I also took a look at the source and if I'm not mistaken, it looks like the API [here](https://github.com/atom/electron/blob/f3645c66619ce0eeadbed94440158412e1072f39/atom/browser/api/atom_api_tray.h#L41) is instantiating with a native image object and not a string. Am I mistaken in this? Or is that an inconsistency in the docs?

**Comment by kevinsawicki** [comment]
> is instantiating with a native image object and not a string. Am I mistaken in this? Or is that an inconsistency in the docs?

I think many times string are automatically converted to native images and this is one such case.

See http://electron.atom.io/docs/v0.36.5/api/native-image/#nativeimage for more details.

**Comment by onetwopunch** [comment]
@kevinsawicki Yeah I read that too, but that doesn't really explain to me why passing in a nativeImage type fixed the issue?

**Comment by kevinsawicki** [comment]
> Yeah I read that too, but that doesn't really explain to me why passing in a nativeImage type fixed the issue?

In your first example you had a path of `path.join(__dirname, 'icon.png')` but in your second example (where it worked) you have a path of `path.join(__dirname, 'img', 'icon.png')`, I just want to confirm that you used a valid path when you passed the string into `new Tray` API.

**Comment by onetwopunch** [comment]
@kevinsawicki Oh yeah sorry they were both valid paths, I just moved the image before the second example

**Comment by kevinsawicki** [comment]
@onetwopunch can you create a gist or repo with your failing example and with the image and code?

**Comment by onetwopunch** [comment]
@kevinsawicki Yup, here's the commit that fixed it in my repo https://github.com/onetwopunch/gitify/commit/8f9b05f7656beb149c89af7d26cdf77c6a75ef15

**Comment by kevinsawicki** [comment]
Very strange, I could get your example working with a string argument to `new Tray` with other images, but not that one in your repo.

This one worked for me:

![test](https://cloud.githubusercontent.com/assets/671378/12802085/311c7450-ca96-11e5-8691-bddbfe59139b.png)

**Comment by onetwopunch** [comment]
@kevinsawicki oh weird it must have been something wonky with that image. I just pulled it off the internets as a placeholder but now that I added a png that I bought, its working fine with the string. Maybe it has to do with some mac `xattr` issue ¯\_(ツ)_/¯

**Comment by deepak1556** [comment]
There is no problem with the image converter taking a path string  value, it is most likely caused by image being unable to decode by the converter. The reason it succeeded with using nativeimage directly because , the converter will just obtain a handle to the native class and the image representation will be empty for corrupt image, wont throw any conversion type error for it. Would be helpful to debug if you could provide the image you were trying to set, couldn't find on the repo you linked. Thanks!

**Comment by onetwopunch** [comment]
@deepak1556 I actually was able to figure out that the image was converted from a `.ico` to `.png` which is why the encoding was likely messed up. The image should still be there in earlier commits.
