### ISSUE TITLE
is this a bug? 

### ISSUE THREAD

**Issue by CarlosRen** [atom/electron#4340]
![image](https://cloud.githubusercontent.com/assets/6012322/12772350/8038511a-ca6b-11e5-8ea6-f225686b3a25.png)
why?

**Comment by xywz** [comment]
Duplicate of #254.

**Comment by kevinsawicki** [comment]
Thanks @xywz for pointing to that other issue, closing this out.

**Comment by CarlosRen** [comment]
I didn't used jquery in electron . This error happened in `mainwindow.load(mywebsite)` and the page is normal in browser (chrome)
![image](https://cloud.githubusercontent.com/assets/6012322/12774836/9b71fd7e-ca83-11e5-9c3c-6f2ced799af1.png)

**Comment by plrthink** [comment]
@CarlosRen You doesn't use jQuery in your electron app  but your website does. The issue #254 explain why this occurs in detail. In short,  you should either set `nodeIntegration ` to `false` when create a `BrowserWindow ` instance or use something like webpack to bundle javascript file used in your website.

**Comment by CarlosRen** [comment]
@plrthink thanks, it's my fault, i didn't finish the reading
