### ISSUE TITLE
Warn for invalid URL

### ISSUE THREAD

**Issue by Darkle** [atom/electron#4342]
Hi, I'm not exactly sure if this is a bug, but after reading [this article](https://samsaffron.com/archive/2012/06/07/testing-3-million-hyperlinks-lessons-learned), I tried the nonsense url mentioned in the comments `http://nonsense:port/yay` with loadUrl and while it didn't crash electron, none of the regular browserWindow or webContent events seemed to be emitted. 

If you use a url that isn't available e.g. `http://lszfief78nwfo8dosz8nfeosz8jeosz8t.com`, you get the regular did-start-loading, did-fail-load etc. emitted, but there's no error or events emitted for `http://nonsense:port/yay`

I've created a temp repo to try it out: https://github.com/Darkle/loadUrlTest

(sorry for the unspecific issue title, I didn't know what else to call it)

**Comment by deepak1556** [comment]
`http://nonsense:port/yay' isnt a valid url, hence chromium will not load it. This is not an issue, it works as expected.

**Comment by Darkle** [comment]
Sure, I get that it cant load it, but I thought it was weird that no events were fired. I'd like it to fail in a way that I could hook into (e.g. 'did-fail-load') - but at the moment, nothing happens - no events seem to be triggered, it just does nothing.

**Comment by deepak1556** [comment]
Those events are fired only after the url loads (either success or failure), in this case an invalid url isnt loaded, hence they dont fire. Maybe we can make electron throw an error for invalid url ?

**Comment by Darkle** [comment]
Yeah that'd be great.
