### ISSUE TITLE
How to get the current os user 

### ISSUE THREAD

**Issue by gj1118** [atom/electron#4343]
Hi , Is there a way I can get the current logged in domain user in electron , please ? 

Thanks and Regards
gagan

**Comment by felicienfrancois** [comment]
There are nodejs modules for that, for example [userid](https://www.npmjs.com/package/userid)

**Comment by plrthink** [comment]
[`process.platform`](https://nodejs.org/api/process.html#process_process_platform) should works.

**Comment by gj1118** [comment]
thanks @felicienfrancois .. Since I am on windows going ahead with username .

**Comment by mbuchner** [comment]
let username = process.env.username || process.env.user;

**Comment by Slapbox** [comment]
Does `process.env.USERNAME` populate before the user logs in on Windows?

**Comment by barbalex** [comment]
The username module is not meant to be used in electron and does not seem to work correctly under all circumstances: https://github.com/sindresorhus/username/issues/27#issuecomment-1404545925

**Comment by Slapbox** [comment]
@barbalex I don't understand the relevance of that issue to this one besides where you say that `process.env.USERNAME` doesn't appear to work in a packaged application.

**Comment by barbalex** [comment]
> @barbalex I don't understand the relevance of that issue to this one besides where you say that `process.env.USERNAME` doesn't appear to work in a packaged application.

The username module itself does not work in a packaged application. In the issue the author says he does not indend to support electron. And the username module was mentioned as a solution. 

What works for me in a packaged app:

```
const os = require('os')
const userName = process.env.username ?? process.env.user ?? os?.userInfo?.()?.username
```
...because `os?.userInfo?.()?.username` seems to work.

**Comment by Slapbox** [comment]
> the username module was mentioned as a solution.

Ah I see.

> To do this I need to explicitely install os as a npm dependency.

That should not be necessary - at least, not in the `main` process.

**Comment by barbalex** [comment]
Meanwhile I am (still) getting the correct user in dev mode. But in production (when running the build project), the user returned is always `SYSTEM`.

Somehow this keeps changing every few electron-versions or windows-updates.

After spending quite some time experimenting I have found a roundabout way to get the correct user inside main > index.js.
The basic idea is that there is a powershell command that works:

```js
const spawn = require('child_process').spawn

function executePowershell(command) {
  return new Promise((resolve) => {
    const powershell = spawn('powershell.exe', [command])
    powershell.stdout.on('data', (data) => {
      resolve(data.toString())
    })
  })
}


  // PROBLEM:
  // multiple ways to get username
  // but on installed version most return 'SYSTEM'
  // Only thing that seems to work is powershell
  // returns on my dev pc: 'PC_ALEX\\alexa\r\n'
  const usernameFromPS = await executePowershell(
    '[System.Security.Principal.WindowsIdentity]::GetCurrent().Name',
  )
  const indexOfBackslash = usernameFromPS.indexOf('\\')
  const usernameWithoutDomain = usernameFromPS.slice(indexOfBackslash + 1)
  const usernameFromPsSanitized = usernameWithoutDomain.replace(/\r\n/g, '') // 'alexa'
  const userName =
    usernameFromPsSanitized ??
    process.env.username ??
    process.env.user ??
    os?.userInfo?.()?.username
```

Hope this helps others.
