### ISSUE TITLE
unminimize doesn't work during drag operation on window

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#4345]
I am trying to replicate titlebar functionality in a frameless window in order to remove the borders on the window.

When a frameless window is maximised, I am awaiting a mousedown on the titlebar and starting a drag operation. On the first mouse move I am unmaximising the window, but it has no effect.

e.g. browser side

```
$('#titlebar').on('mousedown', function() {
   ipcRenderer.send('startdrag');
});
```

main thread

```
ipcMain.on('startdrag', (event, offset) => {
    log.debug('starting window drag');

    if (leftMouseDown) {

        const browserWindow = BrowserWindow.getFocusedWindow(); //BrowserWindow.fromWebContents(event.sender);

        function onDrag(x, y) {

            const winX = x - offset.x;
            const winY = y - offset.y;

            if (browserWindow.isMaximized()) {
                log.debug('maximised during drag - unmaximize');
                browserWindow.unmaximize();
            }

            browserWindow.setPosition(winX, winY);
        }

        function onUp() {
            mouse.removeListener('left-up', onUp);
            mouse.removeListener('left-drag', onDrag);
            log.debug('browser window drag finish');
        }

        mouse.on('left-drag', onDrag);
        mouse.on('left-up', onUp);
    }
});
```

but it seems that
a)
```
browserWindow.unmaximize();
```
has no effect (it doesn't change the size)

b)
The window frame is shown when dragging (I guess it should be reproducible by maximising a frameless window and then dragging?)
e.g. maximise and set position programmatically
![image](https://cloud.githubusercontent.com/assets/309321/12775967/5d31de20-ca52-11e5-8b91-12640d6a044c.png)
then manually resize.. gone!
![image](https://cloud.githubusercontent.com/assets/309321/12775981/7922ded6-ca52-11e5-856d-fee238d8dbbc.png)

I can work-around the problem by doing
```
browserWindow.setSize(100, 100);
```
instead of 
```
browserWindow.unmaximize();
```

and of course I can make that solution a bit better by remembering the size before maximising.. but I guess I shouldn't have to?

**Comment by lukeapage** [comment]
In fact its weirder than I thought - setting the size to 100,100 actually causes the size to restore to the previous size (and not 100,100 at all)

**Comment by lukeapage** [comment]
Sorry this is on windows, haven't tried on mac

**Comment by DerNivel** [comment]
Why you are not using `-webkit-app-region: drag`?
https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region

**Comment by lukeapage** [comment]
As per - https://www.npmjs.com/package/electron-drag

Does css auto restore when dragging maximised then?

**Comment by DerNivel** [comment]
When `-webkit-app-region: drag` is set on an DOM element, it behaves like a normal titlebar.
That means double click maximizes the windows, if maximized and you start dragging the titlebar it restores and is movable.

**Comment by zcbenz** [comment]
I'm merging this to #3614 since they are caused by the same reason.
