### ISSUE TITLE
closing a frameless window animates the blue frame

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#4347]
when you do `window.close` within a frameless window, in windows, you see the blue frame re-appear as the window animates to close..

Only a minor issue but it would be good if it stayed hidden.

**Comment by lukeapage** [comment]
doing it a few more times, you actually see
first
a) the content disappears and becomes transparent
b) the blue frame appears
c) the blue frame animates from large to small..

**Comment by lukeapage** [comment]
hrmm I wonder if this is a result of this PR:
https://github.com/atom/electron/pull/800/files

**Comment by lukeapage** [comment]
Doesnt seem to happen if transparency is set

**Comment by zcbenz** [comment]
This is a limitation of Windows, you can find more about this in https://github.com/atom/electron/issues/734#issuecomment-169332056.
