### ISSUE TITLE
loadURL for webview gives exception

### ISSUE THREAD

**Issue by rishibhargava** [atom/electron#4348]
I am having some trouble with this API (<webview>.loadURL. If I dont have the src attribute in the webview to start with, then the loadURL gives an error -

My code - 

function updateWebviewURL(u) {
var webv = document.getElementById('mainwebview');
if (webv) {
webv.loadURL(u);
webv.style.display = 'block';
}
};

Uncaught TypeError: Cannot read property 'loadURL' of undefined
node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:410

using electron-prebuilt version 0.36.7

Anyone else seen this scenario?

**Comment by kevinsawicki** [comment]
This is the expected behavior if the `dom-ready` event has not been fired yet on the web view.

From the docs, http://electron.atom.io/docs/v0.36.5/api/web-view-tag/#methods

> Note: The webview element must be loaded before using the methods.

> Example

> ```js
> webview.addEventListener("dom-ready", function() {
>     webview.openDevTools();
> });

Has the `dom-ready` event fired on your webview before you called `loadURL`? You need to set the `src` attribute for the `dom-ready` event to fire I believe.

**Comment by rishibhargava** [comment]
ok got it. Thanks for clarification.
