### ISSUE TITLE
record and replay user input?

### ISSUE THREAD

**Issue by gbaumgart** [atom/electron#4351]
l am investigating the possibilities to abuse electron for real unit tests. the record part i can solve my self but not the replay. Where i have to start digging for sending mouse and keyboard events to the browser window via Javascript? I am ok with C++ and the CEF and just need a pointer. Thank you!

**Comment by felixrieseberg** [comment]
You can just use ChromeDriver. Kevin wrote thttps://github.com/kevinsawicki/electron-chromedriver which will allow you to do exactly what you want. 

I believe this solves your problem, so I'll close this issue for now - otherwise, I'd recommend asking for help in the Slack channel (https://atom-slack.herokuapp.com/).

**Comment by gbaumgart** [comment]
Hi, thank you but how does this allows to write BrowserWindow.emit(new Event{args}) in order to create mouse & keyboard events ? I checked all files in 'chrome driver' (really don't know what it is).

After going through all C headers and sources in atom/electron, I also can't find anything close to it, except the EventEmitter class. 

Would you bother to tell me how chromedriver does this?

**Comment by gbaumgart** [comment]
ah, I see now. This is about selenium. No, its not what I want.

**Comment by felixrieseberg** [comment]
Well... ChromeDriver the primary tool used to do fake user input to Chrome. It is in fact [the standard](https://www.w3.org/TR/webdriver/).

**Comment by gbaumgart** [comment]
i understand, but it requires too much other stuff like selenium and it assumes I am running ordinary test units (which i don't want). 

I want to replay user-actions this at any time on existing applications, from within my electron application. You still think chrome-driver will do that for me?

**Comment by gbaumgart** [comment]
Can you please re-open the issue. Its not solved. I would like to extend BrowserWindow for sendKeys/sendMouse. Sorry i mentioned 'test-units' which may have lead you to answer it with a Selenium-Tool. 

Thank you.

**Comment by felixrieseberg** [comment]
First of all, I think you're mixing up unit tests and integration tests. You clearly don't want unit tests. You don't need user input for unit tests.

If you want to programmatically click/enter things in a `BrowserWindow`, use its `webContents` property - there's a `executeJavaScriptCode` method that will allow you to do exactly what you want. [Inject some JS](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsexecutejavascriptcode-usergesture) and having it click and enter things to your hearts content.

Sounds good?

**Comment by gbaumgart** [comment]
yeah, you're right about the test stuff.

This sounds good, for sending keyboard events, I would write:

$(function() {
    var e = $.Event('keypress');
    e.which = 65; // Character 'A'
    $('window').trigger(e);
});

but how I would send mouse events? 

$(function() {
    var e = $.Event('move');//or click
    .....
    $('window').trigger(e);
});

This would work? I guess I would have to create a fake mouse-pointer to make it real but if it really would, I am ok with that.

Sorry bothering on this but really thank you, being that patient with me.

**Comment by kevinsawicki** [comment]
> but how I would send mouse events?

You can simulate mouse events withs something like the following:

```js
var mouseMove = new MouseEvent('mousemove', {
  view: window,
  bubbles: true,
  clientX: 256
});
document.body.dispatchEvent(mouseMove);
```

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

I'm going to close this out. If you need more help or want to discuss this further, I'd recommend posting a thread over on the message forum, https://discuss.atom.io/c/electron

**Comment by brenca** [comment]
Or you can use webContents.sendInputEvent (https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentssendinputeventevent)?

**Comment by gbaumgart** [comment]
jeez, that was not my day. sendInputEvent does the job! 

thank you all! very much appreciated!

**Comment by kevinsawicki** [comment]
@brenca thanks so much for mentioning that API :+1:

**Comment by brenca** [comment]
I'm glad I could help :)
