### ISSUE TITLE
Webview tag can't prevent default on will-download

### ISSUE THREAD

**Issue by Thomas101** [atom/electron#4352]
Hi,

I've found that if you subscribe to the will-download event from a webview you're not able to prevent default, or set the save path to suppress the default file dialog behavior. Both calls succeed but don't seem to have any effect. If you log the calls out to the console, they calls come up after the file picker dialog, so I suspect it's getting run after the default behaviour

```js
const partition = 'persist:abc'
const ses = session.fromPartition(partition)
ses.on('will-download', (evt, item) => {
  evt.preventDefault()
  item.setSavePath('/test.txt')
})

const webview = document.createElement('webview')
webview.setAttribute('partition', partition)
```

**Comment by kevinsawicki** [comment]
@Thomas101 are you listening to the `will-download` event from the render process or the main process?

I'm able to reproduce it when listening from the render process but it does seem to work correctly when done from the main process

**Comment by Thomas101** [comment]
It was in the renderer process, I'll change it to the main process. Thanks!

**Comment by leohxj** [comment]
in main process, listen to `will-download` event could prevent the default download.
