### ISSUE TITLE
ResEdit should be removed from documentation.

### ISSUE THREAD

**Issue by g33kco** [atom/electron#4357]
The resedit (http://www.resedit.net/) link you have on (http://electron.atom.io/docs/v0.36.5/tutorial/application-distribution/) should be removed as both downloads are packed with trojan viruses inside of the installer. They hide InstallManager.exe in the temp folder and attempt to run it which in turn unleashes hell.

**Comment by paulcbetts** [comment]
@g33kco Agree, can you send a PR to remove it from the docs?

**Comment by g33kco** [comment]
When I get time unless someone else beats me to it.

**Comment by felixrieseberg** [comment]
Dang, thanks for the information. I'll get on that right away.

**Comment by g33kco** [comment]
I use resource hacker, but thought I'd give resedit a try. After that experience I'll stick with what I know works. =o)

Thanks,
Mark Lewis
CEO
G33K Co, LLC
mark@g33kco.com
307.840.4594

**Comment by kevinsawicki** [comment]
@g33kco thanks for opening this, the docs have been updated and the site pages no longer contain the links.

**Comment by jorangreef** [comment]
I have a version of ResEdit from 2015. I scanned it today with ClamAV and it was clean. I see that Chrome now blocks the download page for resedit.net (I wanted to scan the newer binaries there).

Does anyone know when the trojan was introduced into ResEdit (and by who/how)? Any alternative you would recommend?
