### ISSUE TITLE
bootstrap failed on Windows if checkout by commit 9ffe502fb1f3aa801ca7800ef69a50ff0ee72fbc

### ISSUE THREAD

**Issue by ArktekniK** [atom/electron#4360]
@zcbenz This is possibly a similar issue to #3736   ??

Bootstrap output

C:\Git\rstarkey\electron>script\bootstrap.py -v
Running in verbose mode
git submodule sync
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/brightray'
Synchronizing submodule url for 'vendor/crashpad'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/native_mate'
Synchronizing submodule url for 'vendor/node'
Synchronizing submodule url for 'vendor/requests'
git submodule update --init --recursive
Submodule path 'vendor/brightray': checked out 'be00b1d551a977612bfe74979bdbfdec5e8c748f'
Submodule path 'vendor/brightray/vendor/libchromiumcontent': checked out 'd0192f9809a2eec42f66f51b0f85e38e08a2dc8e'
Submodule path 'vendor/native_mate': checked out 'a3dcf8ced663e974ac94ad5e50a1d25a43995a9d'
fatal: reference is not a tree: 3b044608ee51ca001dabe944cade6e64f46b0724
Unable to checkout '3b044608ee51ca001dabe944cade6e64f46b0724' in submodule path 'vendor/node'
None
Traceback (most recent call last):
  File "C:\Git\rstarkey\electron\script\bootstrap.py", line 210, in <module>
    sys.exit(main())
  File "C:\Git\rstarkey\electron\script\bootstrap.py", line 39, in main
    update_submodules()
  File "C:\Git\rstarkey\electron\script\bootstrap.py", line 95, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\Git\rstarkey\electron\script\lib\util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1

**Comment by zcbenz** [comment]
It seems that I forgot to tag the node repo, it should work now.
