### ISSUE TITLE
`remote.require` doesn't work with bundling, but is needed for tools like `electron-localshortcut`

### ISSUE THREAD

**Issue by mitchhentges** [atom/electron#4365]
Hello, and thanks for the neat-o framework!

I'm using [`electron-localshortcut`](https://github.com/parro-it/electron-localshortcut) in an app for assigning key shortcuts. It needs to run in the main (non-render) process, so I import it as so:

`remote.require('electron-localshortcut')`

However, once I `browserify` my fears away, `remote.require` can't find `electron-localshortcut` because it's looking on the filesystem, not using the module-bundler's `require` method.

I keep hearing that "hey, naw, it's OK, we don't need module bundlers anymore, it's the future", but I don't want things like `gulp` and other unused-at-runtime libraries being included in my Electron app. It increases the size from 50MB to ~200MB, which isn't that cool. That's why I'm using `browserify` in 2016.

Thanks again!

**Comment by kevinsawicki** [comment]
> I'm using electron-localshortcut in an app for assigning key shortcuts. It needs to run in the main (non-render) process, so I import it as so

Have you tried requiring it in the main process using a plain old `require('electron-localshortcut')`?

**Comment by enlight** [comment]
If `browserify` strips out unused dependencies unless it sees them required then you need to configure it to not throw away `electron-localshortcut` during bundling probably with the `--require` / `-r` [option](https://github.com/substack/node-browserify#usage).

**Comment by mitchhentges** [comment]
I can verify that the dependency _is_ added into the bundle by browserify. I can test this as follows:
```
var launcher = require('browser-launcher2'); //Browserify parses this require, adds to bundle
var remoteLauncher = remote.require('browser-launcher2'); //Fails, it's not on the local filesystem

**Comment by enlight** [comment]
Ah silly me, in order for Browserify to load modules from a bundle it would have to provide it's own `require()`, but it won't be able to hijack `remote.require()`. So you'll have to require it in the main process instead and expose the API via IPC.

**Comment by mitchhentges** [comment]
Is it a possibility that `remote.require()` can check the local instance (e.g. browserify's) of `require` before failing?

**Comment by enlight** [comment]
`remote.require()` calls `process.mainModule.require()` in the main process, you could perhaps monkey-patch `process.mainModule.require()` to call Browserify's `require` if the default implementation fails to load the requested module.

**Comment by mitchhentges** [comment]
Hmm.
I did some research into the `ipc` modules, and [solved my issue using that](https://github.com/james-proxy/james/pull/116).
Considering that I'm one of the few people having this problem, I'll refrain from monkey-patching. Thanks for the direction :)

**Comment by parro-it** [comment]
My 2c here are that we must solve the issue by making browserify (and webpack I guess) aware of remote.require, maybe by developing a plugin...
