### ISSUE TITLE
BrowserWindow.getNativeWindowHandle() doesn't give a valid HWND on Windows

### ISSUE THREAD

**Issue by LartSimZ** [atom/electron#4369]
Hi,
I'm using BrowserWindow.getNativeWindowHandle() API (introduced in #4023) as I need to reparent the Chromium window in our application. But it seems that the buffer returned does not contain any valid HWND (I checked with MS tool Spy++). I did a test using the same code than getNativeWindowHandle() and I found that using node::Buffer::New() is wrong as I could not get back the initial value. However, this is working when using node::Buffer::Copy(). I think the same change should be done in the ToBuffer() method used by getNativeWindowHandle()'s implementation. The NodeJS states that node::Buffer::Copy() is doing a copy of source data which is better in this case.

**Comment by LartSimZ** [comment]
Proposed pull request #4398

**Comment by zcbenz** [comment]
Fixed by #4398.
