### ISSUE TITLE
What does `autoCorrectWord` do? (as passed to `webFrame.setSpellCheckProvider`)

### ISSUE THREAD

**Issue by wearhere** [atom/electron#4371]
[The documentation](https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider) for `webFrame.setSpellCheckProvider` does not say.

Looking at [the code](https://github.com/atom/electron/blob/master/atom/renderer/api/atom_api_spell_check_client.cc#L190), it seems that it is meant to automatically correct swapped-letters misspellings like "wiht" (to "with"), except that in my testing it does not do that.

**Comment by aggregatejeff** [comment]
if autoCorrectWord is set to true it should automatically correct the misspelled word with the first suggestion returned by the spellcheck module. There could be multiple reasons it's not doing that (no matches, module not returning suggestions, etc.).

**Comment by wearhere** [comment]
> if autoCorrectWord is set to true it should automatically correct the misspelled word with _the first suggestion returned by the spellcheck module_.

What do you mean? The spell-check provider (the third argument to `setSpellCheckProvider`) does not return suggestions, but rather a Boolean "this text is/isn't spelled correctly".

**Comment by zcbenz** [comment]
> Looking at the code, it seems that it is meant to automatically correct swapped-letters misspellings like "wiht" (to "with"), except that in my testing it does not do that.

As quoted in the code:

```
    // Make decision: if only one swap produced a valid word, then we want to
    // return it. If we found two or more, we don't do autocorrection.
```

**Comment by Aluxian** [comment]
@zcbenz The code you quoted is no longer there: https://github.com/atom/electron/blob/master/atom/renderer/api/atom_api_spell_check_client.cc

It was removed by this commit: https://github.com/atom/electron/commit/5fae63a2f5d030ddb49d032bab7c50cc25d20d05

What's the behaviour now? It's not doing anything anymore, is it? I typed `acceptabel` (which has only one correction – `acceptable`) and it didn't autocorrect it.
