### ISSUE TITLE
filesystem usage inside .app

### ISSUE THREAD

**Issue by cumajkeee** [atom/electron#4373]
Is it possible to have access to files/directories in read-write mode inside .app which is in Application folder?

Now receive Uncaught Exception: Error: EROFS: read-only file system, open /path/to/...

Thanks in advance.

**Comment by kevinsawicki** [comment]
You should be able to do this. I tried locally and was able to write files into the root `.app` folder using the regular `fs` Node APIs.

I thought `EROFS` implied that you were on a read-only file system so in this case, are you sure you can write anything to the filesystem regardless of path?

**Comment by cumajkeee** [comment]
Without package application - yes, but if I make installer and install it as usual app (moving .app in OSX Application folder) - no.

**Comment by kevinsawicki** [comment]
> Does asar usage can affect this?

I don't think it does.

Can you share a code example or sample app that is failing for you with the `EROFS` error?

**Comment by paulcbetts** [comment]
You can't do this anyways - even if you succeed, doing this will break your app's code signature

**Comment by JohannBlake** [comment]
I had problems with this too. On my MacOS I installed the app into the Downloads directory and gave it permission to run. This didn't help. Only after I installed the app into the Applications folder did it work.

**Comment by wandersonsousa** [comment]
If anyone its facing this same issue, try to search for relative paths in your application when trying to save files, for example. on windows this will be ok `fs.saveFile("storage/file.txt")` but when do the same on mac you may have some permission problems, so its better to do something like this 
`
import { join, dirname } from "path";
import { fileURLToPath } from "url";
const __dirname = dirname(fileURLToPath(import.meta.url));
const file = join(__dirname, "storage/file.txt");
`
