### ISSUE TITLE
Focusing secondary windows

### ISSUE THREAD

**Issue by iamdriz** [atom/electron#4376]
In my application I have dual screen setup and we have built a custom task switcher (as the Windows UI is locked out) that allows a user to focus running applications.

When running the application I have the following processes in the Windows Task Manager:

![image](https://cloud.githubusercontent.com/assets/801252/12850843/c49b2986-cc1e-11e5-8d39-96b97f58483a.png)

Process ID `7900` is the main app and window and `17512` is the second window and the other two processes being the background processes for the main application.

If I run the following in the command prompt: `wscript Focus.vbs 17512`

And the contents of the Focus.vbs is:

~~~
set objShell = WScript.CreateObject("WScript.Shell")
objShell.AppActivate WScript.Arguments.Item(0)
~~~

It doesn't bring the second window to focus! But if I run the above code with `7900` (the first window), then it brings that window to focus fine. I've also noticed that the second window title is null in the task manager.

So it seems that this 4th process is not actually the second window but a background process for it. Is this correct?

Is there a way to get the actual process id for the second window that can be focused? Or will we have to listen to focus of the main window then bring all other windows to focus as well.

**Comment by zcbenz** [comment]
All windows are created in the main process, the renderer process is only responsible for drawing the page, there are also a few other background processes none of them creates windows.

**Comment by baconface** [comment]
If your windows have unique titles you can access them via VBScript using ```objShell.AppActivate "Window Title"```.

If your background process is spawned in Electron keep your window management within Electron and JavaScript and use the [BrowserWindow API](https://github.com/atom/electron/blob/master/docs/api/browser-window.md) as it supports multiple windows and screens and focus is as easy as [win.focus()](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winfocus).
