### ISSUE TITLE
What dependencies should I add to my .deb and .rpm packages?

### ISSUE THREAD

**Issue by Aluxian** [atom/electron#4377]
I read in the docs that I need `libappindicator1` for the tray icon on Linux, should I add that in my deb/rpm dependencies for every distro (I have just one for every distro)? What other packages should I add as dependencies? Which should I add for deb and which for rpm?

Also, on Elementary OS, my app asked for `canberra-gtk-module`, although it worked without it too. Should I add [those from atom](https://github.com/atom/atom/blob/master/resources/linux/debian/control.in) (without git and python which I probably don't need)?

Or should I tell my users to install `libappindicator1` and others if they need them (and not enforce them as dependencies)?

Thanks!

**Comment by paulcbetts** [comment]
Here's what we use at Slack (which might not quite be right, but it's a good start):

gconf2, gconf-service, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libxtst6, libnss3, python, gvfs-bin, xdg-utils

I'm pretty sure our Fedora dependencies are flat-out broken so I won't tell you them :)

**Comment by Aluxian** [comment]
@paulcbetts Thanks!

I wish Electron had an official recommendation in the docs. I will stick to what Atom uses, for now.

**Comment by paulcbetts** [comment]
@Aluxian If you copied whatever dependencies Google Chrome uses, you probably would be pretty close

**Comment by zcbenz** [comment]
You can find the list of libraries used by Electron in:
https://github.com/atom/brightray/blob/master/brightray.gyp#L4

Copying what Chromium uses should be a very safe choice:
http://copr-dist-git.fedorainfracloud.org/cgit/spot/chromium/chromium.git/tree/chromium.spec
