### ISSUE TITLE
Create shortcut on Windows

### ISSUE THREAD

**Issue by KochiyaOcean** [atom/electron#4381]
Our project is trying to use toast notification on Windows, which requires a shortcut with AppUserModelID on Windows 8.1. 
Is it possile to provide a method to create a shortcut with customizable AppUserModelID?
Similar to `gui.App.createShortcut` on the bottom of https://github.com/nwjs/nw.js/wiki/Notification

**Comment by felixrieseberg** [comment]
It's not a bad idea, I can build that. @kevinsawicki: The code is fairly simple, I'm just not sure which object should host the method. Thoughts?

**Comment by kevinsawicki** [comment]
Sorry, just want to get more context here, how would this be different than the `app. setAppUserModelId` API http://electron.atom.io/docs/v0.36.5/api/app/#app-setappusermodelid-id-windows ?

**Comment by felixrieseberg** [comment]
The only addition would be to have an API that automatically creates a shortcut on the user's start menu. From my point of view, there's no definite need to put it into Electron - in theory, an external module and some documentation here would probably already do the trick for most people.

**Comment by kevinsawicki** [comment]
Yeah, I thought https://github.com/Squirrel/Squirrel.Windows handled this correctly already so I'm not sure if a core API is needed here. I'd be curious what others think.

**Comment by paulcbetts** [comment]
Squirrel.Windows does indeed already create shortcuts with AppUserModelID set, it's always:

```
com.squirrel.{YOUR NUGET PACKAGE ID}.{YOUR EXE NAME MINUS DOT EXE}
```

So:

```
com.squirrel.atom.Atom
```

or

```
com.squirrel.slack.Slack
```

**Comment by paulcbetts** [comment]
One thing that's been On My List is to have Electron itself just automatically set your App User Model ID for you if you're Squirrel-installed, something like:

1. If "{My Executable's Directory}/../Update.exe" exists
1. Get the name of "{My Executable's Directory}/../.." which is the NuGet Package ID
1. Combine it with the executable name, bingo bango, we can build an AppUserModelID

**Comment by KochiyaOcean** [comment]
I don't want to use Squirrel so I forked from https://github.com/j201/windows-shortcuts and add set appUserModelId function to it. This module works well now so I'll close this issue.
https://github.com/KochiyaOcean/windows-shortcuts

**Comment by Chaaaaap** [comment]
Does the AppUserModelID have to be "com.squirrel.xx.yy" in order for Squirrel to correctly update pins and shortcuts?
