### ISSUE TITLE
[Question] Live Editor w/ Electron?

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [atom/electron#4383]
Hey team,

I was wondering if there is something similar to supervisor's npm package, but for electron? I know we can just work inside codepen or jsfiddle then just package to electron, but I'm wanting to test some stuff natively and get the 'feel' if you will of developing inside electron instead.

So I am asking if there is something similar to supervisor in the way that it auto updates the files, but instead, updates the electron window?

Thank you,

-- The Fonz

**Comment by kevinsawicki** [comment]
There isn't one that I know of but others may have better tips.

This might be a better question for the discussion forums if you haven't looked there already, https://discuss.atom.io/c/electron

**Comment by paulcbetts** [comment]
You could probably adapt some pieces from https://github.com/atom/dev-live-reload to do what you want - it's hard to write this code as a generic "Works for every Electron app" lib because it's somewhat dependent on how your app works

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
I see, thank you guys. Will take a look.
