### ISSUE TITLE
Consistent directory folder while getting AppPath

### ISSUE THREAD

**Issue by gabrielstuff** [atom/electron#4385]
Hi !
We would like to know how to achieve a consistent get on the running directory folder.

Here is the tree :

```
remote
├── README.md
├── bin
│   └── remote-darwin-x64
├── data
│   ├── custom_option.json
│   ├── export.json
│   ├── images
│   └── stock.json
├── electron-app
│   ├── app
│   ├── main.js
│   ├── node_modules
│   └── package.json
└── package.json
```

What we would like to do, is being able to run in dev mode with : `electron electron-app` and when building being able to do the same. We require the folder `data` as follow : `var pathExport = pathHelper.join(__dirname, '..', 'data', 'export.json')`
Unfortunately, when the app is package, the tree change and the main.js file is in `Contents/Resources/app`

How would it be possible to always get the running app, where the user double click ?

thanks, 
g

**Comment by jprichardson** [comment]
@gabrielstuff see: https://github.com/maxogden/electron-packager or https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md

**Comment by gabrielstuff** [comment]
Hi @jprichardson and thanks for you help. Unfortunately this does not give me any conventions, nore a function to get the running path.
What I do now is using a `helper.js` file which contains : 

```
'use strict'

const os = require('os').platform()
const path = require('path')

module.exports = {
  getPathLevel: function () {
    if (os === 'darwin') {
      return 3
    } else {
      return 2
    }
  },
  isPackaged: function () {
    return __dirname.toLowerCase().indexOf('resources/app') > 0
  },
  getAbsRealAppPath: function () {
    if (this.isPackaged()) {
      var explodedPath = __dirname.split(path.sep)
      var level = this.getPathLevel()
      while (level--) {
        explodedPath.pop()
      }
      return explodedPath.join(path.sep)
    } else {
      return __dirname
    }
  }
}
```
To me the AppPath should be consistent along darwin / osx / windows and not being related to the OS nor the environment.

**Comment by zcbenz** [comment]
You can put your data inside your app.

**Comment by gabrielstuff** [comment]
Hi,
This is not a solution if you want to give user the opportunity to modify elements : add images, add text, etc

See the use case ?
