### ISSUE TITLE
Audio not working with screencapture

### ISSUE THREAD

**Issue by steelbrain** [atom/electron#4386]
Set `audio: true` in the example in [docs](http://electron.atom.io/docs/v0.36.5/api/desktop-capturer/#desktopcapturer) and it'll fail

**Comment by deepak1556** [comment]
As far as i know chromium doesnt allow loopback audio capture along with screen capture, you need to create a separate stream for it.

**Comment by steelbrain** [comment]
Oh interesting, is there an easy way to merge those streams together then?

**Comment by zcbenz** [comment]
I'm closing this since it is a limitation of Chrome, I would suggest reporting this to Chromium's issues list if you want it fixed.

**Comment by Raj123456788** [comment]
Can anyone please answer [this Question](https://github.com/atom/electron/issues/4504)
