### ISSUE TITLE
Modules for the Main Process: Menu Error

### ISSUE THREAD

**Issue by brody182** [atom/electron#4387]
When I create an application menu in the render process with the simple template API:  I get an error in the console

Uncaught TypeError: Cannot read property 'getName' of undefined

**Comment by enlight** [comment]
Is this where we all have to guess what your code looks like? :)

**Comment by brody182** [comment]
http://electron.atom.io/docs/v0.36.5/api/menu/


if (process.platform == 'darwin') {
  var name = require('electron').app.getName();
  template.unshift({
    label: name,
    submenu: [
      {
        label: 'About ' + name,
        role: 'about'
      },
      {
        type: 'separator'
      },
      {
        label: 'Services',
        role: 'services',
        submenu: []
      },
      {
        type: 'separator'
      },
      {
        label: 'Hide ' + name,
        accelerator: 'Command+H',
        role: 'hide'
      },
      {
        label: 'Hide Others',
        accelerator: 'Command+Alt+H',
        role: 'hideothers'
      },
      {
        label: 'Show All',
        role: 'unhide'
      },
      {
        type: 'separator'
      },
      {
        label: 'Quit',
        accelerator: 'Command+Q',
        click: function() { app.quit(); }
      },
    ]
  });

**Comment by enlight** [comment]
OK, there's a small mistake in the sample code, the `app` module is only available in the main process, so to call `app.getName()` in the renderer process you'd need to do:

```
var name = require('electron').remote.app.getName();
```
