### ISSUE TITLE
Trouble finding ATOM_SHELL_ASAR.js

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [atom/electron#4388]
Hey team,

I am trying to edit the source for `ATOM_SHELL_ASAR.js` because I want to use a custom file extension for my `asar` file.

And when trying to use a custom extension, you get:
![image](https://cloud.githubusercontent.com/assets/17089298/12864729/2c6f2e88-cc4a-11e5-80d6-0d5372a46ab0.png)

Which is derivative from:
![image](https://cloud.githubusercontent.com/assets/17089298/12864730/46f30b30-cc4a-11e5-8adc-278a7604533c.png)

I downloaded the entire electron source, and searched for it, but came up with no luck:
![image](https://cloud.githubusercontent.com/assets/17089298/12864737/76fb7786-cc4a-11e5-8eeb-4c5a4a212e74.png)

-- The Fonz

**Comment by enlight** [comment]
I believe this is the file you're looking for: https://github.com/atom/electron/blob/master/atom/common/lib/asar.js

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
@enlight Hmm, yeah that's it! Weird how it shows up as a different name in chrome tools, thank you!!
