### ISSUE TITLE
Dart language support

### ISSUE THREAD

**Issue by acterhd** [atom/electron#4390]
Hello. WIll Electron support Dart language, or not?

**Comment by enlight** [comment]
Electron runs JavaScript and native Node addons (C++), so you can use any language that can be compiled to JavaScript, Dart included.

**Comment by acterhd** [comment]
But can I use custom canvas context, get access to DOM with C++?!

**Comment by enlight** [comment]
I don't know about custom canvas contexts, but you can't access the DOM in C++, nor access the Blink API directly. You can only access the parts of the Chromium APIs that Electron explicitly exposes via JavaScript.

**Comment by kevinsawicki** [comment]
Closing this out, thanks @enlight for providing valuable information :+1:
