### ISSUE TITLE
Mac Launcher PATH Incorrect

### ISSUE THREAD

**Issue by patrickhousley** [atom/electron#4394]
I was wondering if electron could/should implement something like https://github.com/sindresorhus/fix-path to correct the PATH issue on Mac. I am still having this issue when launching atom from the launcher. See https://github.com/andischerer/atom-svn/issues/10

**Comment by zcbenz** [comment]
From 10.9 OS X stops assigning $PATH for programs launched from Finder, so we are just following the default behavior of OS X, if we change it we are probably doing the wrong thing.
