### ISSUE TITLE
Overwrite Origin header

### ISSUE THREAD

**Issue by paul321** [atom/electron#4397]
Hi

Currently in Electro the header: Origin cannot be set, if you make an ajax call to a website the Origin will be Origin: file:// which you can get blocked for this.

The error it's following: Refused to set unsafe header "Origin"

**Comment by kevinsawicki** [comment]
This looks very similar to https://github.com/atom/electron/issues/2245 which talks about limitations in Chrome's security policy regarding this.

You might want to use a node module to make requests to get around any Chrome limitations, closing this out.
