### ISSUE TITLE
Can't send callback functions via IPC

### ISSUE THREAD

**Issue by bartim** [atom/electron#4400]
Hi, 

Electron seems to have problems with sending callback functions via IPC. Here is a short example:

main.js: 
```
'use strict';

const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

var mainWindow = null;

app.on('window-all-closed', function() {
  app.quit();
});

app.on('ready', function() {
  const electron = require('electron');
  const ipcMain = electron.ipcMain;

  mainWindow = new BrowserWindow({width: 800, height: 600});

  // and load the index.html of the app.
  mainWindow.loadURL('file://' + __dirname + '/index.html');

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function(event) {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });

  setTimeout(function() {
    mainWindow.send('callbackIPC', "This will be sent", function(para, meter) { /* Does nothing */ }, "This too");
  }, 1000);
});
```

index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Demo Case</title>

    <script>
    "use strict";
    require("electron").ipcRenderer.on("callbackIPC", function(event, firstStr, func, secondStr) {
      console.log("Executing callback. Arguments: ");;
      console.log(firstStr);
      console.log(func);
      console.log(secondStr);
    });

    </script>
  </head>
  <body>
  </body>
</html>
```

In index.html, the argument func to the inner function starting at line 9 is null. 

I was hoping to send a callback to the renderer thread which can be sent back to the main thread with additional arguments to be executed (note, I'm not trying to call that function from main thread in the rendering thread), but that doesn't seem to work because you can't send functions via IPC. Of course, there are a lot of workarounds for that problem, but in my opinion, they all have some sort of arkward syntax. 

Sadly, this isn't stated in the docs, quite the opposite. http://electron.atom.io/docs/v0.36.5/api/ipc-main/ says that 

> When the event occurs the callback is called with an event object and **arbitrary arguments**.

(Emphasis mine)

Now my question, am I right that one can't send functions via IPC? Am I also right that this is not documented?

**Comment by deepak1556** [comment]
> Now my question, am I right that one can't send functions via IPC? Am I also right that this is not documented?

Yes it just does a `JSON.stringify` on the native side.

**Comment by sbruchmann** [comment]
@bartim If you **really** have to send dynamic generated functions via `ipc` then you should checkout [LJSON](https://www.npmjs.com/package/ljson).

**Comment by lukeapage** [comment]
We listen for a reply chanel then send the message. The browser then sends a reply message back. It should be easy to abstract a reply mechanism if you need to in multiple places.

**Comment by bartim** [comment]
Thanks for the clarification and assistance, guys :-)

**Comment by zcbenz** [comment]
Closing since the behavior is expected.

**Comment by JasinYip** [comment]
Is that possible we could implement it like Socket.io?
