### ISSUE TITLE
Google login flow crashes renderer (?)

### ISSUE THREAD

**Issue by codl** [atom/electron#4401]
If I open a browser window to Google's centralized login page, <https://accounts.google.com/ServiceLogin>, and log in successfully, I get a blank, white page, although my mouse cursor still reacts to links that should be on the page. WebViews created in another window after this exhibit the same problem.

I'm using electron-prebuilt 0.36.7 on linux x64.

**Comment by deepak1556** [comment]
Related to https://github.com/atom/electron/issues/3471

**Comment by zcbenz** [comment]
I'm unable to reproduce on OS X, can you provide an reproducible example?

**Comment by deepak1556** [comment]
@zcbenz i tried the url with default electron app on linux. A log-net-log trace showed that a 302 POST request to `https://accounts.google.com/ServiceLoginAuth` gets aborted. The cause seems to be same as #3471

**Comment by zcbenz** [comment]
Cool, I'm merging this to #3471.
