### ISSUE TITLE
Windows: App: addRecentDocument does nothing

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4405]
Windows 8.1. Version: 0.36.7. Called with relative and absolute paths, after `ready` is fired (even after a one second timeout).

**Comment by adam-lynch** [comment]
Ugh, missed the registration part in the docs.

**Comment by pflannery** [comment]
@adam-lynch Did you manage to get the registration process to work? I can't get it to work on my Windows 10 64bit machine. 
I noticed that atom 1.5.4 isn't showing any recents either.

**Comment by adam-lynch** [comment]
@pflannery I never got back to actually testing this thoroughly I'm afraid. My only note I took on this is that this would be handling when creating shortcuts for the app.
