### ISSUE TITLE
BrowserWindow.capturePage() larger than window size?

### ISSUE THREAD

**Issue by danburzo** [atom/electron#4417]
As far as I understand (and have tested), you can't capture an area larger than the window size as an image, which in turn forces you to make the browser window as large as the page you're exporting.

This will inevitably lead to segmentation faults past a certain size, so I'm wondering if anyone could point me towards an alternative approach within Electron / Chromium. Much appreciated!

Solutions outside Electron I'm considering:

* Exporting as PDF and using a third-party library to convert from PDF to PNG;
* Tiling the image into manageable chunks and using imagemagick or similar tools to stitch it back together.

**Comment by felicienfrancois** [comment]
Have you tried to play with zoomFactor / pixelAspectRatio?

Another solution may be to capture in several steps: scroll between captures, and then re-assemble the full image.

**Comment by zcbenz** [comment]
`capturePage` can only exports what's already drawn, so it can not capture the page larger than window size. Usually unless your page is unreasonably large, creating a large window should be an ideal solution.

**Comment by ronalb** [comment]
hi, 
any progress on this issue?
i have created a large window (larger then my screen size) ,
i can see all my content when i scroll
but when i capturePage to get PNG , the largest image i can get is the size of my screen size.
anyone can help on this?

**Comment by Svennisen** [comment]
@ronalb There is a setting: enableLargerThanScreen. If set to true browserWindow will render outside your screen borders.

**Comment by ronalb** [comment]
thx @Svennisen I will check if this will solve it.
just to be clear, I did managed to render outside my screen borders (when i scroll i see all data)
the problem was when trying to capture the page the png image was cutted at the end of my physical screen size.

**Comment by Svennisen** [comment]
@ronalb That is definitely possible, I do it with a hidden window with these settings:

    {
     show: false,
     webPreferences: {
            webSecurity: false,
            backgroundThrottling: false,
            webgl: false
      },
      frame: false,
      enableLargerThanScreen: true
    }

And it works fine. You should only need enableLargerThanScreen, but it might be possible that the fact that it is visible affects what area you can capture.

**Comment by gearcoded** [comment]
You can launch the browser with the `enableLargerThanScreen` option then resize the Window:
```
{
  webPreferences: {
    nodeIntegration: true,
  },
  enableLargerThanScreen: true,
}
win.setContentSize(20000,20000);
```
It works the same way as if the page is not displayed.

Unfortunately, there are still size limitations like with Canvas. An Image cannot be greater than `16384 x 16384`:
```
win.webContents.capturePage({
  x: 100,
  y: 100,
  width: 16384,
  height: 16384
}).then(data => {
  fs.writeFile('./print.png', data.toPNG(), (error) => {
    if (error) throw error
    console.log('Write PNG successfully.')
  })
}).catch(error => {
  console.log(error)
})
```
When the image is saved the electron process can take around 6GB RAM.

If you set the sizes to `17000 x 17000` you will get the insufficient memory error:
> tcmalloc: large alloc 1073741824 bytes == 0x29e1d1951000

I read that it is possible to increase the available memory limits. 

I can use `printToPDF` with `2000000000 x 2000000000` sizes without any issues. And I wonder why it doesn't work so easily with PNG.
