### ISSUE TITLE
maximize / unmaximize error on windows

### ISSUE THREAD

**Issue by zh99998** [atom/electron#4419]
frameless window maximize / unmaximize event may cause a error on windows.

it unable to reproduce stable, maybe a GC problem?

screenshot:

https://ygobbs.com/t/%E7%AA%97%E5%8F%A3%E5%81%9A%E5%A4%A7%E5%8C%96%E5%90%8E%E5%86%8D%E6%AC%A1%E7%82%B9%E5%87%BB%E6%97%A0%E6%B3%95%E7%BC%A9%E5%B0%8F%E5%9B%9E%E5%8E%9F%E6%9D%A5%E5%B0%BA%E5%AF%B8/78751

my code: 
https://github.com/mycard/mycard/blob/master/js/app.js#L5-L25

```
const current_window = remote.getCurrentWindow();

document.getElementById("minimize").onclick = ()=> {
    current_window.minimize()
};
document.getElementById("maximize").onclick = ()=> {
    current_window.maximize();
};
document.getElementById("restore").onclick = ()=> {
    current_window.unmaximize();
};
document.getElementById("close").onclick = ()=> {
    current_window.close();
};

current_window.on('maximize', ()=> {
    document.body.className = process.platform + ' maximized'
});
current_window.on('unmaximize', ()=> {
    document.body.className = process.platform
});
```

**Comment by zcbenz** [comment]
This is a duplicate of #4324.
