### ISSUE TITLE
Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#4420]
Getting this error on OS X:

    2016-02-08 09:43:16.059 Electron Helper[36152:2174695] Couldn't set selectedTextBackgroundColor from default ()

I have a style that looks like this that I believe is triggering the error:

    #myId::selection {
        background: #3399ff;
    }

This `::selection` selector allows you to apply a specific style to the selected text, in my case in a `<textarea>` tag.

**Comment by zcbenz** [comment]
You can get the same warning for Chrome browser, it is not actually related to the style, if happens when you select some text in page.

If you really care about this I would suggest reporting this to Chromium's issues list.

**Comment by jiyinyiyong** [comment]
I got this error in a transparent window. I didn't have `::selection` in my case. Is there any way to bypass this warning?

**Comment by bansalvks** [comment]
I am getting the same issue in Electron 1.1.0. Please suggest what should I do. Also, the link mentioned **Couldn't set selectedTextBackgroundColor from default ()** is broken.

**Comment by jlord** [comment]
I have been able to reproduce this message with [maxogden/tabby](https://github.com/maxogden/tabby) using `v0.36.12` but I cannot reproduce from `v0.37.8` and on.

**Comment by zcbenz** [comment]
This warning can be safely ignored, and it should be reported to [Chromium's issues list](https://bugs.chromium.org/p/chromium/issues/list) if anyone is actually affected by this, this is an upstream bug and we are not able to fix it on Electron's side.

**Comment by wuqunfei** [comment]
After half year, the problem is still there.

**Comment by wuqunfei** [comment]
I have simple solution, put 
`<style>
        ::selection {
            background: white; /* WebKit/Blink Browsers */
        }

    </style>`
in the enterence of html, like index.html

This bug will disappear.

**Comment by RichLewis007** [comment]
Taking the idea from wuqunfei, here is CSS that when added to the normal CSS file of your Electron project will prevent this error message from showing in the console when a user selects some text:

::-moz-selection {
    background:transparent;
}
::-webkit-selection {
    background:transparent;
}
::selection {
    background:transparent;
}

If you want the user's text selection to look normal, then change the "transparent" above to a color like rgba(255, 255, 125, 0.99)

**Comment by saurik** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=641509

**Comment by SMotaal** [comment]
@saurik it's back in 3.0.0-beta.1 [darwin]... do you know if this was resolved previously?

```log
2018-06-30 08:27:32.079 Electron Helper[2103:148925] Couldn't set selectedControlColor from default ()
2018-06-30 08:27:32.080 Electron Helper[2103:148925] Couldn't set selectedControlTextColor from default ()
2018-06-30 08:27:32.080 Electron Helper[2103:148925] Couldn't set selectedTextBackgroundColor from default ()
2018-06-30 08:27:32.080 Electron Helper[2103:148925] Couldn't set selectedTextColor from default ()
[2101:0630/082732.465501:ERROR:CONSOLE(17)] "Uncaught (in promise) TypeError: Cannot read property 'setMainWidget' of undefined", source: chrome-devtools://devtools/bundled/inspector.js (17)
```

**Comment by kid-wumeng** [comment]
@wuqunfei @RichLewis007

Hi, I'm try the way to set <style> but still receive the warning.

My Electron is newist, how should i resolve the issue now ? thank you

**Comment by pitops** [comment]
the fixes do not work any more apparently. any other workarounds?

**Comment by davidjconnelly** [comment]
Unless I'm very much mistaken, the solution is simply to set a background colour on your main.js file.  Having that being set when the app initially loads seems to solve the problem.  I dare say, it's probably a good practice also.

For example

`mainWindow = new BrowserWindow({width: 800, height: 600, backgroundColor: '#ff0000'})`

Hope this helps somebody.

**Comment by davidjconnelly** [comment]
Of course, the idea of adding CSS - as described above - is also a valid solution.  So, an example of a full page would be:

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style>
        ::selection {
            background: #fff;
        }
    </style>
</head>
<body>
    <h1>Helo World</h1>
</body>
</html>`


[web development bootcamp](https://www.speedcodingacademy.com)

**Comment by zacharyzh** [comment]
3.0.13

This issue only appears when you open the dev tools.
