### ISSUE TITLE
browserWindow.webContents.session.cookies.set requires URL property on cookie

### ISSUE THREAD

**Issue by aaronfrost** [atom/electron#4422]
None of the cookies I am saving from my session have a `url` property. However, when I call `win.webContents.session.cookie.set(cookie, cb)` I get an error cause the cookie I am trying to set doesn't have a `url` property. If they cookie didn't have a url on it when I called `win.webContents.session.cookies.get()`, then electron shouldn't require me to have a `url` property on the cookie to set it.

**Comment by deepak1556** [comment]
The `url` attribute is required to know if the cookie can be set for the scheme, also given a domain value it needs to validate if a cookie can be set for it. You can form the `url` with the domain and scheme in your case.

**Comment by aaronfrost** [comment]
By "form the `url` with the domain" do you mean that I should just use the domain as the url?

**Comment by deepak1556** [comment]
Yup

```
const scheme = secure ? "https" : "http";
const host = domain[0] === "." ? domain.substr(1) : domain;
const url = scheme + "://" + host;
```

**Comment by aaronfrost** [comment]
Thank you!!!!!!!!

**Comment by Noitidart** [comment]
Yessss I had this same issue! Thanks for sharing how to fix it! I am doing a fetch in the renderer, and then in main I get the session cookeis from Cookie API. Then I save that to disk. Then on next app startup, I read from disk and was trying to set it. But my cookies looked like this from `session.defaultSession.cookies.get({}, .....)`:

```
[ { name: 'sails.sid',
    value:
     's%3A7gXgst26C1Cp0SpeonPRagS9doJmVuJG.x9lRDR%2FlL6JS3%2FW6YZmEwA99FacMFMgxmDsBceeIV5U',
    domain: 'localhost',
    hostOnly: true,
    path: '/',
    secure: false,
    httpOnly: true,
    session: true } ]
```

getPref('cookies')
