### ISSUE TITLE
Incorrect header values on 401 unauthorized response

### ISSUE THREAD

**Issue by olalonde** [atom/electron#4425]
In the process of porting a SPA to electron, I think I stumbled on a bug in electron.

I'm using https://github.com/matthew-andrews/isomorphic-fetch to make requests to an HTTP API. Each API request returns an `API_VERSION` header even on Unauthorized responses. 

I can always retrieve that header value with `response.headers.get('API_VERSION')` in Google Chrome (same bundle.js script).

In Electron for some reason, the only available header is `content-type` (verified with `Array.from(response.headers.keys()).forEach(console.log)`). Using the Electron developer console, Network tab, I can see that the header is correctly returned by the API server but it seems it is inaccessible from my code.

**Comment by deepak1556** [comment]
Would it be possible to provide a minimal example ?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by olalonde** [comment]
I think it was an issue with my webpack config.
