### ISSUE TITLE
Uncaught (in promise) TypeError not throwing error in console

### ISSUE THREAD

**Issue by mmahalwy** [atom/electron#4426]
For some reason, errors that are related to reactjs rendering are not logged in electron but are if I use the same files in the web. 

For example, an error from the web that does not show up in electron:
```
web.bundle.js:38 Uncaught (in promise) TypeError: Cannot read property 'taskId' of undefined(…)t.content @ sentTaskStateChange.js:9
t.default @ sentTaskStateChange.js:22t.default @ index.js:14
(anonymous function) @ index.js:43d.value @ index.js:42d.value @ 
...
```

update:
I can determine the root of the error _only_ when I Pause on exceptions, but it still does not log the error to console.

**Comment by kevinsawicki** [comment]
Are you able to share a simplified code snippet that exhibits the issue?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by cjb** [comment]
I see the same thing (no console output) on Linux, but my coworker *does* see "Uncaught (in promise)" messages on OSX.  Both of us are running the same application code, same version of babel, Electron, etc.

@mmahalwy In case it helps narrow it down, would be curious to know more about your platform.
