### ISSUE TITLE
Can I inject custom scripts into the browser window?

### ISSUE THREAD

**Issue by superfunkminister** [atom/electron#4428]
Can I inject custom scripts into the browser window from the back end side of things?

For example, I want to add an admin panel in Kiosk mode regardless of what page is displaying.

**Comment by OlsonDev** [comment]
Yes, refer to the documentation:

http://electron.atom.io/docs/v0.36.7/api/browser-window/ `Ctrl+F` for "preload"

http://electron.atom.io/docs/v0.36.7/api/web-view-tag/#preload

Questions like this should be asked in [this community](https://github.com/atom/electron#community).

**Comment by kevinsawicki** [comment]
Closing this out, thanks for the helpful information @OlsonDev
