### ISSUE TITLE
If you pass a non-integer to BrowserWindow.setPosition it gives confusing error

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#4429]
```
browserWindow.setPosition(0.5, 0.5);
```

results in

```
[TypeError: Error processing argument -1.]
```

it would be nice if it was more informative e.g.

```
[TypeError: Argument must be an integer.]
```

or it just coped with it..

**Comment by deepak1556** [comment]
Related https://github.com/atom/electron/issues/4307 and has been fixed on master. Also the reason for not showing `Argument must be an integer` is because we build with `no-rtti`. More info [here](https://github.com/zcbenz/native-mate/blob/master/native_mate/function_template.h#L150)

**Comment by lukeapage** [comment]
Ok, will retry after next release. Closing to reduce noise. Thanks for info!
