### ISSUE TITLE
ipc deprecated but ipcMain not available

### ISSUE THREAD

**Issue by srad** [atom/electron#4431]
I just saw in the console the deprecation warning to use `require("electron").ipcMain` instead of `require('ipc')`. But the new function doesn't exist in the current prebuilt version, am I missing something?

**Comment by kevinsawicki** [comment]
Are you seeing this warning logged from a render process or the main process?

If you are in the render process you should be using:

```js
require('electron').ipcRenderer
```

and in the main process:

```js
require('electron').ipcMain
```

Hope this helps, closing this out.
