### ISSUE TITLE
Unable to obtain Display desktop picker dialog 

### ISSUE THREAD

**Issue by Raj123456788** [atom/electron#4432]
Hey Guys,
I am unable to get desktop picker dialog for available sources. I am newbie can someone guide me what am I missing? In chrome we use "chrome.desktopCapture.chooseDesktopMedia"? I obtained source from below code.
function onAccessApproved(error, sources) {
    if (error) throw error;
    for (var i = 0; i < sources.length; ++i) {
     //   if (sources[i].name == "Electron") {
            navigator.webkitGetUserMedia({
                audio: false,
                video: {
                    mandatory: {
                        chromeMediaSource: 'desktop',
                        chromeMediaSourceId: sources[i].id,
                        minWidth: 1280,
                        maxWidth: 1280,
                        minHeight: 720,
                        maxHeight: 720
                    }
                }
            }, gotShareStream, errorCallback);
            return;
       // }
    }
```
Thanks!

**Comment by hokein** [comment]
Electron's [`desktopCapturer`](https://github.com/atom/electron/blob/master/docs/api/desktop-capturer.md) API doesn't provide a chromium style desktop picker dialog, so you need to implement on your own. You can also get more details from https://github.com/hokein/electron-sample-apps/tree/master/desktop-capture.
