### ISSUE TITLE
it occured a weird situation.

### ISSUE THREAD

**Issue by licongmu** [atom/electron#4433]
i'm a electron trainee.i want to achive a simple function that alert sth.so,i program my main.js like below:
main.js:
var app = require('app');
var BrowserWindow = require('browser-window'); 
var dialog = require('dialog');
var ipc = require('electron').ipcMain;
//omit other code
  ipc.on('alert',function(event,args){
    dialog.showMessageBox({buttons:['check','cancle','del']});
  });
i know i should use ipc to build contract bettween main process and render process.
so the index.js like below:
//omit other code
`<button`class='op'>click me`</button>`
`<script>window.$ = window.jQuery = require('./js/jquery.min.js');</script>`
`<script type='text/javascript'>`
	var ipc = require('electron').ipcRenderer;
	var op = document.querySelector('.op');
	op.addEventListener('click',function(){
		ipc.send('alert');
	});
but,the button doesn't reponse the click event.nothing happend.
what's wrong?

**Comment by kevinsawicki** [comment]
> what's wrong?

Are you able to add ` console.log('here')` in the `click` event handler and see what if it logs anything in the Console tab of the dev tools?

Can you try with this simplified example and see if it works for you?

### main.js

```js
require('electron').ipcMain.on('alert', function () {
  require('electron').dialog.showMessageBox({message: 'hi', buttons: ['OK']});
})

```

### index.html

```html
<!DOCTYPE html>
<html>
  <body>
    <button class='op'>click me</button>
    <script>
      document.querySelector('.op').addEventListener('click', function() {
        require('electron').ipcRenderer.send('alert')
      })
    </script>
  </body>
</html>
```

**Comment by licongmu** [comment]
thank you!
