### ISSUE TITLE
Using electron.remote during an event handler changes w3c semantics

### ISSUE THREAD

**Issue by alexandrudima** [atom/electron#4438]
Issue found via Microsoft/vscode#2829

Reproducible only on OS X El Capitan 10.11.3
Tried with Electron 0.35.6

To reproduce, append to the `default_app/index.html` right before the `</body>`:
```html
<textarea id="tt" rows="10" cols="50"></textarea>
<script>
(function() {
	var electron = require('electron');
	var remote = electron.remote;
	var t = document.getElementById("tt");
	t.value = "Just some text\nAnd more\nAnd more";
	t.setSelectionRange(0, t.value.length);
	t.focus();

	t.addEventListener('keydown', function (e) {
		console.log('entering keydown handler');
		if (e.keyCode === 9) {
			e.preventDefault();
			console.log('preventing default on TAB, text should not chage (i.e. no input event should follow!)');

			var win = remote.getCurrentWindow();
			win.setDocumentEdited(true);
		}

		console.log('leaving keydown handler');
	});

	t.addEventListener('input', function (e) {
		console.log("received input event!");
	});

})();
</script>
```

Open Electron and press <kbd>TAB</kbd>.

Expected behaviour:
* the textarea contents do not change because the keydown event calls `e.preventDefault()`
```
entering keydown handler
preventing default on TAB, text should not chage (i.e. no input event should follow!)
leaving keydown handler
```

Actual behaviour:
* tab gets inserted inside the texture and the following log:
```
entering keydown handler
preventing default on TAB, text should not chage (i.e. no input event should follow!)
received input event!
leaving keydown handler
```

The expected behaviour can be obtained by removing the two lines in the event handler that use `remote`, so it must be something in how electron implements `remote` that breaks some Chromium event handling expectations.

**Comment by kevinsawicki** [comment]
Are you able to reproduce this as well on Electron `0.36.x`?

**Comment by alexandrudima** [comment]
@kevinsawicki It does not reproduce in Electron `0.36.7`.

I'm sorry I didn't check before creating the issue.
