### ISSUE TITLE
feature request: Safe Browsing integration

### ISSUE THREAD

**Issue by diracdeltas** [atom/electron#4440]
Chromium's Safe Browsing feature (https://developers.google.com/safe-browsing/developers_guide_v3; also included in Firefox and Safari) checks URLs to see if they are on a known malware/phishing blacklist so they can be blocked. It would be cool if Electron could hook into `chrome/browser/safe_browsing` to expose this feature.

**Comment by zcbenz** [comment]
Safe Browsing is only meaningful for browsers, Electron is designed for desktop apps so we will not integrate it.
