### ISSUE TITLE
Rebuild node modules for a different OS

### ISSUE THREAD

**Issue by MathijsvVelde** [atom/electron#4443]
I'm am building an app on Mac (OSX 10.11.3) for all platforms (Linux, Mac and Windows), but some modules are not cross-platform compatible. (e.g.: [Node-Speaker](https://github.com/TooTallNate/node-speaker))

Is there a way to rebuild the node app for a different OS?
Just a guess, running [Electron-Rebuild](https://github.com/electronjs/electron-rebuild) using [wine](https://www.winehq.org/)([bottler](http://winebottler.kronenberg.org/)) for Windows.
But then what for Linux?

The only option I see is build and package each app on its own OS...
I hope you can help me with this stuff

**Comment by paulcbetts** [comment]
@MathijsvVelde This isn't possible, sorry

> The only option I see is build and package each app on its own OS...

This is what you have to do

**Comment by MathijsvVelde** [comment]
||:cry:||:cry:||
|----|----|----|----|----|
|:droplet:||||
||||||
||:cry:|:cry:|:cry:||
|:cry:||||:cry:|

**Comment by MathijsvVelde** [comment]
Thanks anyway!
