### ISSUE TITLE
interceptBufferProtocol but fallback to default

### ISSUE THREAD

**Issue by mattdesl** [atom/electron#4444]
Hey there!

I'm trying to intercept `'file'` protocol so that a different `index.html` is served depending on some variables. I currently have something like this:

```js
  var url = 'file://' + __dirname + '/index.html';

  // Replace index.html with custom one
  electron.protocol.interceptBufferProtocol('file', function (request, callback) {
    if (request.url === url) {
      callback({
        data: customHTML,
        mimeType: 'text/html'
      });
    } else {
      // ... Fall back to default??
    }
  }, function (err) {
    if (err) throw err;
  });
```

However, this breaks browser features like `Image` and other media (audio/video). I can add a custom `fs.readFile` and send the result to `callback({ data, mimeType })`, which works with `image.onload`, but errors are not handled as they should be by the browser and `image.onerror` won't get called.

Is there another approach to replacing the HTML dynamically from `file://` protocol? Or a way to fall back to default protocol behaviour? Or some means of only targeting a specific URL?

**Comment by deepak1556** [comment]
Invoking callback with chromium net_err_codes does call onerror event handler. But if you are just serving local files why not use `interceptFileProtocol` ?

**Comment by zcbenz** [comment]
You can also use [webRequest.onBeforeRequest](http://electron.atom.io/docs/v0.36.7/api/session/#seswebrequestonbeforerequestfilter-listener) API to redirect the request to your custom HTML file.

**Comment by mattdesl** [comment]
Thanks @zcbenz, it seems like the one issue with that approach is that it changes the "base directory" for resources like `<img src="">`, so that now the browsers loads them relative to the new `path/to/custom/index.html`. I will keep poking around, though.

**Comment by baconface** [comment]
You can override that behavior using the [base tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base).
```html
<base href="file://whatever/">
```
or
```html
<base href="http://whatever.com/">
```
