### ISSUE TITLE
GPU process memory leak

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#4445]
We've had a few reports from Slack users saying that their memory usage was growing out of control. On further investigation, it's always the GPU process, and may be related to Nvidia GPU's. This user had a dGPU + iGPU setup (will attach the `dxdiag` when he sends it).

Has anyone on the Atom team heard similar reports?

![gpu leak](https://cloud.githubusercontent.com/assets/1865957/12985924/ad635880-d0a9-11e5-8838-b06258041faa.png)

**Comment by zcbenz** [comment]
I'm assume upgrading to Chrome 49 has fixed this.
