### ISSUE TITLE
OS X Context Menu Has Extra Menu Items When Triggered from Selected Text

### ISSUE THREAD

**Issue by kirkouimet** [atom/electron#4446]
I've getting two extra menu items when I trigger my context menu while I have text selected:

"Search with Google"
"Add to iTunes as a Spoken Track"

Is there anyway to remove these? I'm guessing the operating system injecting these.

![screen shot 2016-02-11 at 11 07 42 am](https://cloud.githubusercontent.com/assets/62191/12987243/00bf3a02-d0b0-11e5-85be-cab5131ba9b8.png)

**Comment by zcbenz** [comment]
This is a feature of OS X, I don't think there is a way to remove them.
