### ISSUE TITLE
Text To Speech in Electron

### ISSUE THREAD

**Issue by francoislaberge** [atom/electron#4452]
Is there anyway to use the text to speech capabilities of chromium? I see text to speech code in electron:
https://github.com/atom/electron/blob/c1673eb666540b2891794bcb2f477f4b0cee78de/chromium_src/chrome/browser/speech/tts_controller_impl.h

**Comment by deepak1556** [comment]
Should be able to get things working with web speech api. For linux you need to have `speech-dispatcher`, verify things work the normal way using `spd-say` etc. Then in electron app you need to have the following flag set.

```
app.commandLine.appendSwitch('enable-speech-dispatcher');
```

Tested with 
```
var utter = new SpeechSynthesisUtterance();
utter.text = 'Hello World';
utter.onend = function(event) { console.log('Speech complete'); }
speechSynthesis.speak(utter);
```

**Comment by francoislaberge** [comment]
Awesome, you rock. Worked like a charm.

**Comment by bhanuc** [comment]
I cannot get it work on ubuntu 64 bit system. I also cannot see any error. Am I missing something ?
Also I have checked  speech-dispatcher on my system. It is working fine.

**Comment by olivierlesnicki** [comment]
https://github.com/noffle/electron-speech/issues/9
