### ISSUE TITLE
print "We suggest not running this as root, unless you're really sure."

### ISSUE THREAD

**Issue by xtsolucoes** [atom/electron#4454]
Hi everyone, 
I'm trying to run in windows over this appearing this message. What can it be

![error](https://cloud.githubusercontent.com/assets/11356150/13008070/5a1e6660-d17b-11e5-876d-a8590e21fed7.png)

**Comment by enlight** [comment]
My guess is you're trying to run the `bootstrap.py` script using Python 3 instead of Python 2.

**Comment by xtsolucoes** [comment]
Yes, you are right will reinstall.
thanks enlight

**Comment by xtsolucoes** [comment]
Sorry new erro.
![screen shot 2016-02-12 at 11 55 29 am](https://cloud.githubusercontent.com/assets/11356150/13008789/9bfcf2d2-d17f-11e5-8efb-039efc3c0c99.png)

**Comment by enlight** [comment]
I don't know Portuguese, but I think it means it can't find Git, did you add it to your `PATH`?

**Comment by xtsolucoes** [comment]
ok now worked thanks again

**Comment by xtsolucoes** [comment]
thank you so much, show now.
![screen shot 2016-02-12 at 1 11 31 pm](https://cloud.githubusercontent.com/assets/11356150/13010696/46ef29d0-d18a-11e5-9862-21c873a3ae3f.png)
