### ISSUE TITLE
[globalShortcut] Registering `command` on Linux throws error, rather than binding with `super`

### ISSUE THREAD

**Issue by mitchhentges** [atom/electron#4456]
If I have the following as my app js:
```
const electron = require('electron');
const globalShortcut = electron.globalShortcut;
const app = electron.app;
app.on('ready', () => {
    globalShortcut.register('Command+Alt+U', () => console.log('ooops'));
});
```
Then it will throw an error on launch. If the X11 server isn't allowing the shortcut to be bound, then don't register it.

**To reproduce:**
1. Build app with above JS
2. Launch app on Linux

![screenshot from 2016-02-12 16-50-41](https://cloud.githubusercontent.com/assets/7784737/13011775/c509f5e8-d1a8-11e5-99bb-d5d31ea6a0b3.png)

**Comment by deepak1556** [comment]
Mapping `Command` to `Super` on linux would just cause confusion with existing `CommandOrCtrl` option.

**Comment by mitchhentges** [comment]
`command` _is_ `super`. Try plugging a regular windows keyboard into a Mac. There shouldn't be confusion

**Comment by deepak1556** [comment]
Yup this is just convenience, so can be achieved at user level. But if you would like to fix the  conversion error thrown, then the necessary change has to be made in `accelerator_util.cc`.

**Comment by zcbenz** [comment]
It throws exception because an invalid parameter is passed (Command is not a valid key on Linux).

**Comment by mitchhentges** [comment]
Isn't Electron for allowing developers to easily target multiple platforms
for their desktop application? I fell like it's a little weird that my
application crashes just because the "command" key is called "super" in
Linux

**Comment by zcbenz** [comment]
I'm cool making `command` available on other platforms, it does no harm anyway.
