### ISSUE TITLE
BrowserWindow preload script not executed

### ISSUE THREAD

**Issue by tomkel** [atom/electron#4459]
Hello,

I have downloaded the [atom/electron-quick-start](https://github.com/atom/electron-quick-start), and changed the `main.js` to preload a script.
```javascript
mainWindow = new BrowserWindow({
    width: 800, 
    height: 600,
    webPreferences: {
        nodeIntegration: false,
        preload: './preload.js'
    }
});
```
```javascript
// preload.js
var _process = process;
process.once('loaded', function() {
  global.process= _process;
});
```
However I get an error.
```
index.html:9 Uncaught ReferenceError: process is not defined
```
How can I get this working?

**Comment by brenca** [comment]
This works for me:

```javascript
const path = require('path')

mainWindow = new BrowserWindow({
    width: 800, 
    height: 600,
    webPreferences: {
        nodeIntegration: false,
        preload: path.join(__dirname, 'preload.js')
    }
})
```

**Comment by tomkel** [comment]
@brenca Not for me. In the dev tools console I get the same error message. Does this mean there is something wrong with my environment? I am executing with `npm start`.

**Comment by brenca** [comment]
@tomkel It should work, I've tried it with the sample app too, and it's working for me this way. I zipped the modified sample app for you, maybe you just missed something, but in case you didn't - what OS and electron version are you using? I'm on Windows 10 and electron v0.36.7.
[app.zip](https://github.com/atom/electron/files/128909/app.zip)

**Comment by tomkel** [comment]
It works with `path.join(__dirname, 'preload.js')`, just `./preload.js` doesn't work.

Thanks for your help on this, @brenca.

**Comment by Dillybob92** [comment]
Hey guys,

I just came here after searching for a while... because I couldn't get the preload to work either.

I was reading here: http://electron.atom.io/docs/api/browser-window/

> preload String - Specifies a script that will be loaded before other scripts run in the page. This script will always have access to node APIs no matter whether node integration is turned on or off. The value should be the absolute file path to the script. When node integration is turned off, the preload script can reintroduce Node global symbols back to the global scope. See example here.

And I just used `preload:__dirname + '/preload.js'`, because that's the 'absolute' path? And it wasn't working. I think we should edit the docs and include that we need to use `preload: path.join(__dirname, 'preload.js')`

**Comment by ArktekniK** [comment]
I know this is old but thought I would just mention that I had this issue and resolved it within the page with:
```html
<script>window.$ = window.jQuery = require('jquery');</script>
```
This was after the preload script and obviously only works if you have node integration enabled for the browser window. Without node integration, regular script includes should work fine.

**Comment by dovk** [comment]
This might help other with similiar issues regarding preload
https://github.com/dovk/electron-security-example/blob/master/README.md

**Comment by totymedli** [comment]
Keep in mind that in your preload script you have to use `require` instead of `import`.
