### ISSUE TITLE
Prevent PDF Download from webview

### ISSUE THREAD

**Issue by ahazelwood** [atom/electron#4461]
I am currently investigating using electron to supplement one of our internal apps.  However, the lack of being able to view pdfs is not ideal.  I can work around this by potentially opening up the pdf in chrome proper.  However there doesn't appear to be a way to stop electron from prompting a pdf to be saved when a link is clicked in a webview.  I've tried everything from a will-navigate event handler to a new-window event handler.  None of them appear to allow me to cancel this event so that I can handle it myself.

Any ideas?  Thanks.

**Comment by deepak1556** [comment]
Did you try [session#will-download](https://github.com/atom/electron/blob/master/docs/api/session.md#event-will-download) event

**Comment by ahazelwood** [comment]
That did the job.  It would be nice if there was a reference to this from the webview page with a note stating that this is where you can potentially cancel a url from being loaded.  Also, there doesn't appear to be a good way to get access to the parent app and/or the session from the code associated with a  browserwindow?  Am I missing anything?  Thanks for your help.

**Comment by deepak1556** [comment]
[session.fromPartition](https://github.com/atom/electron/blob/master/docs/api/session.md#sessionfrompartitionpartition) should you help get the session associated with a browserWindow or webview.

**Comment by ahazelwood** [comment]
That all works great.  Thanks for your help.  One of the things that I would like to be able to do in conjunction with this, is to be able to rewrite the url for an iframe that is showing a pdf through my external pdf viewer, or even something like pdf.js.  I did find where I could rewrite the url for the session in the main application through the 'will-download' event, but there doesn't seem to be a way to do this for an embedded iframe/or frame of a frameset.  Am I missing something?

Thanks.

**Comment by zcbenz** [comment]
Closing since the original question has been solved. For other questions, [the community](https://github.com/atom/electron#community) might be a better place.
