### ISSUE TITLE
Windows: shell.openItem opens files behind the application.

### ISSUE THREAD

**Issue by quicksnap** [atom/electron#4464]
Common use case for `openItem` for us is to open a native file, such as a photo. Having it appear behind Electron isn't great. On OSX, files open in the foreground. On Windows, Electron will remain in front.

I am not seeing much affordance for options here: https://github.com/atom/electron/blob/05aeceeb52eede7d11a1dcfd0761cc8b2e1b6a56/atom/common/platform_util_win.cc#L297-L302

Would this requiring patching chromium to achieve this behavior? Would a PR be accepted? I've done a little Chromium patching, so I could try to fix if it sounds good.

**Comment by zcbenz** [comment]
I'm merging this to #4349.

**Comment by catalin-testenv** [comment]
+1 Please fix this for Windows. Thank you !

**Comment by jazucker** [comment]
was this ever fixed? Is there a workaround? I'm still seeing it.

**Comment by Maus3rSR** [comment]
Same here
