### ISSUE TITLE
setInterval no longer functions if the electron process is no longer the foreground process.

### ISSUE THREAD

**Issue by Oceanswave** [atom/electron#4465]
It seems that if my electron app is the following:

```
const electron = require('electron');
const app = electron.app;

app.commandLine.appendSwitch('page-visibility');
app.commandLine.appendSwitch("disable-renderer-backgrounding");
app.commandLine.appendSwitch("disable-background-timer-throttling");

app.on('ready', function() {
    setInterval(function(){
        console.log("the time is now", new Date());
    }, 1000);
});
```

At some point if the electron process is no longer the foreground process, after a period of time, it becomes throttled and messages are no longer written to the console.
If the process becomes the foreground process once more, it once again starts writing to the console.
The included switches don't seem to have any effect on OSx.

While very cool, is there a way to prevent this behavior?

**Comment by Oceanswave** [comment]
Disregard, this is related to app suspension. Sorry!

```
const powerSaveBlocker = require('electron').powerSaveBlocker;
powerSaveBlocker.start('prevent-app-suspension');
```

**Comment by Booligoosh** [comment]
@Oceanswave When I try the `const powerSaveBlocker = require('electron').powerSaveBlocker;` it says it's undefined. Any idea why this is?

**Comment by fretman92** [comment]
hello @Oceanswave, was your problem reported on macOS or Windows?
We noticed the pb on macOS because of the new [http://osxdaily.com/2014/05/13/disable-app-nap-mac-os-x/](App Nap feature), but we're still wondering if `powerSaveBlocker` is really useful on Windows.
