### ISSUE TITLE
<webview>.insertCSS(css) not work

### ISSUE THREAD

**Issue by 5uper** [atom/electron#4467]
i try the insertCSS(css) method but its not working

this is my code:
```
var webview = document.querySelector('webview');

webview.addEventListener("dom-ready", function(){
    webview.insertCSS("body{ background-color: #404041; color: #fff;}");
});
```
I tried it with different sides. what is wrong?

someone knows an example how to use the method?

**Comment by deepak1556** [comment]
Did you verify the injected stylesheet content in devtools? most likely your styles were overriden, which can be workaround.

**Comment by zcbenz** [comment]
Please make sure your rule was not overridden by other rules.
