### ISSUE TITLE
process.env.npm_package_version is undefined when packaged

### ISSUE THREAD

**Issue by okonovalenko** [atom/electron#4468]
Hi
process.env.npm_package_version is undefined when running after electron-packager distribution is created. Doesn't seam to read it from package.json, which is located in /resources/app/package.json
in renderer window
var remote = require("remote");
console.log(process.env.npm_package_version) // undefined

But in development when running manually cmd "electron ./main.js --enable-logging" works fine, reads correctly version from package.json

**Comment by zcbenz** [comment]
`npm_package_version` is set by npm, not Electron.

**Comment by okonovalenko** [comment]
I understand that, but electron is reading location of main.js from package.json before launching it, it might as well populate those process.env variables. 
Unless there are better ways to get the name and version of your web app?

**Comment by zcbenz** [comment]
You can use the `app` module.

**Comment by tomachinz** [comment]
which app module where? sorry. im having trouble accessing process.env.npm_package_version

**Comment by movingobjects** [comment]
@tomachinz, had the same issue but figured it out.

You can get the version from your `package.json` from the `app` module like so:

Main process:
```js
const { app } = require('electron');

console.log(app.getVersion());
```

Renderer process:
```js
const { remote } = require('electron');

console.log(remote.app.getVersion());
```
