### ISSUE TITLE
Render process crashed - white screen

### ISSUE THREAD

**Issue by PlugaruT** [atom/electron#4470]
I am building a small photo editor and I am using `CamanJS` to apply some effects to photo. When I want to save the photo, I am using `this.save()` function from `CamanJS`. Sometimes the shows download file prompt appears and the photo is saved, but most of the time I get a white screen. In console I don't get nothing.

**Comment by deepak1556** [comment]
Can you provide an example app that causes the crash ? Also the electron version and OS you are running.

**Comment by PlugaruT** [comment]
Sure,
https://github.com/PlugaruT/electron-photo-editor

**Comment by deepak1556** [comment]
So `Caman.Save` works by creating a `dataURL` from canvas and loading it with `document.location.href`, there is a known problem with the size of URL. The number of characters allowed is 2MB which is defined [here](https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/content_constants.cc&sq=package:chromium&l=29&q=kMaxURL) beyond which chromium refuses to load the URL and here is the related chromium [issue](https://code.google.com/p/chromium/issues/detail?id=69227). There is a [workaround](https://code.google.com/p/chromium/issues/detail?id=69227#c37) pointed in that issue which i tried to patch `Caman.Save` and it works.

```
diff --git a/app/js/caman.full.js b/app/js/caman.full.js
index cd3150d..4841435 100644
--- a/app/js/caman.full.js
+++ b/app/js/caman.full.js
@@ -1334,7 +1334,15 @@
     }
     type = type.toLowerCase();
     image = this.toBase64(type).replace("image/" + type, "image/octet-stream");
-    return document.location.href = image;
+    var parts = image.match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/);
+    var binStr = atob(parts[3]);
+    var buf = new ArrayBuffer(binStr.length);
+    var view = new Uint8Array(buf);
+    for(var i = 0; i < view.length; i++)
+      view[i] = binStr.charCodeAt(i);
+    var blob = new Blob([view], {'type': parts[1]});
+    var URL = webkitURL.createObjectURL(blob)
+    return document.location.href = URL;
   };
 
   Caman.prototype.nodeSave = function(file, overwrite) {
```

From chrome 50 there is `Canvas.toBlob` method which would effectively reduce this patch to two lines, I suggest reporting this to Caman JS and getting it fixed there. Another easier thing would be to use `WebContents::DownloadURL` and use it for saving the image.

**Comment by PlugaruT** [comment]
Thanks a lot for help. I have noticed that with some photos, the save button worked, but with another didn't work. Didn't think that the file size matters. The issue can be closed now. Also I will report this issue to the creator of CamanJS and will suggest to fix this. Thanks.

**Comment by zcbenz** [comment]
Closing since it is an upstream Chromium bug and we are not able to fix it on our side.
