### ISSUE TITLE
event.preventDefault() in 'close' event does not prevent remote.BrowserWindow closing

### ISSUE THREAD

**Issue by duncanwerner** [atom/electron#4473]
This only applies to remote.BrowserWindow (i.e. the one used in renderer processess).  It works fine for the other BrowserWindow.  

Not sure if this is a documentation issue or an implementation issue, but the docs don't specify a difference.

Ubuntu 15.10 / Electron 0.36.7

**Comment by zcbenz** [comment]
This is a limitation of `remote` module, you can find more about it in http://electron.atom.io/docs/v0.36.7/api/remote/#passing-callbacks-to-the-main-process.

**Comment by duncanwerner** [comment]
That's what I meant when I said it was a documentation issue.  While I understand the limitation, it would be helpful if the docs made a note of it.
