### ISSUE TITLE
Chrome flashes previous page

### ISSUE THREAD

**Issue by taha** [atom/electron#4475]
Consider the following case:

1. Create new `BrowserWindow`
2. Load a URL
3. Hide window `win.hide()`
4. Load a different URL
5. Show window `win.show()` (showed after `did-finish-load` is triggered)

I've noticed the on the second URL loading and upon re-showing the window, the content from the old URL flashes for a split second before showing the new one. I've experienced the same issue before with Chrome the browser.

Windows 7 / Electron v0.36.7

**Comment by zcbenz** [comment]
It sounds very likely a bug of Chrome's GPU acceleration, I suggest reporting this to [Chromium's issues list](https://crbug.com) instead, because we are just using Chromium to render the page and we are not able to fix this on our side.
