### ISSUE TITLE
Documentation unclear for app.makeSingleInstance

### ISSUE THREAD

**Issue by apoco** [atom/electron#4478]
One thing is unclear in the documentation for `app.makeSingleInstance`. The docs say that calling that returns true or false indicating whether the application should continue launching, but it doesn't mention anything about the return value of the _callback_. The sample shows the callback returning `true`, but it's not clear whether this return value has a causal affect on the return value of `makeSingleInstance`. And I've seen other code samples where nothing is returned from the callback at all.

Should the callback to `makeSingleInstance` return something? If so, what does the return value mean? Should the docs be updated to make this clearer?

**Comment by paulcbetts** [comment]
@apoco The return value of the callback used to do something but now afaik does nothing particularly useful. Just return true

**Comment by apoco** [comment]
Will returning nothing work just as well? The more I looked into it, the more it looked like it had no effect, but I'm not completely clear on that still.

If it truly does nothing, I humbly propose https://github.com/atom/electron/pull/4480

**Comment by zcbenz** [comment]
Closed with #4480.

**Comment by thinkdj** [comment]
```

/* Single Instance Check */
var iShouldQuit = app.makeSingleInstance(function(commandLine, workingDirectory) {
    if (mainWindow) {
        if (mainWindow.isMinimized()) mainWindow.restore();
        mainWindow.show();
        mainWindow.focus();
    }
    return true;
});
if(iShouldQuit){app.quit();return;}

```

**Comment by nidhir-systango** [comment]
@thinkdj  i have done exactly same,
 
var iShouldQuit = app.makeSingleInstance(function(commandLine, workingDirectory) {
    if (mainWindow) {
        if (mainWindow.isMinimized()) mainWindow.restore();
        mainWindow.show();
        mainWindow.focus();
    }
    return true;
});
if(iShouldQuit){app.quit();return;}

But when one instance of app is open it do not open new intsance(which is correct),but is not restoring the current instance(which is Minimized)
Any idea?

**Comment by MarshallOfSound** [comment]
@nidhir-systango Your code looks correct but I must say again 👍 

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

You are much more likely to get an answer on Slack or in the Discussion Forums than posting on a several month old closed issue.

**Comment by dominikfiala** [comment]
Just run into this issue when trying to make `makeSingleInstance` work, was getting `Error: Object has been destroyed` untill i added `return` after app.quit(), so i vote for updating the docs at https://electron.atom.io/docs/api/app/#appmakesingleinstancecallback

```
if (shouldQuit) {
  app.quit()
  return // super important
}
```
