### ISSUE TITLE
Add a way to get host BrowserWindow of webview

### ISSUE THREAD

**Issue by lukeapage** [atom/electron#4481]
Ive worked around this but spent some time puzzling.. my webview sends an ipc message to the main process.. now i want to do something to the window containing the webview.. if i use fromWebContents I get undefined.

A similar issue occurs if i want to broadcast an ipc message to all webcontents and webviews, I must enumerate browserWindows, then write code in each browserWindow that receives the message and forwards to every webview.

**Comment by baconface** [comment]
Isn't that by the design of the webview? That it can't interface and manipulate directly with the parent? And that it is it's own process outside of your application? You need to [send an IPC message to the parent with an instruction or event handle](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#event-ipc-message) and then have the parent be the interpreter and manipulate itself based on that instruction. IE, the IPC message is doSomething and your capture in the parent calls a function doSomething() with or without arguments sent with the IPC.

**Comment by lukeapage** [comment]
I definitely want a webview in its own process and im fine with no *direct* manipulation of parent. I want the main thread to be able to work out what window a webview message is coming from.

When you send an ipc message from the webview, it goes to the main process, not the parent webview.. How do you send a message to the parent? I assume its postMessage on opener ?

Btw that link you provided is just to the webview documentation, where i cant see a mention pf parent.

**Comment by lukeapage** [comment]
(In my case the main thread is deciding what to do thats why i dont want to post to parent and have the parent do it)
