### ISSUE TITLE
`isMaximized()` on browser window returns wrong value when resizable is set to false

### ISSUE THREAD

**Issue by alvin-777** [atom/electron#4483]
In our app we need to record the window size and position depending on whether the window is maximised. However, there is a problem when setting the window resizable to false. As shown below:
![image](https://cloud.githubusercontent.com/assets/13615512/13042423/df71e520-d40b-11e5-9335-b5cd04b06273.png)

OS: OS X Yosemite 10.10.5 (haven't tested on other platforms)
Electron version: v0.36.7

**Comment by enlight** [comment]
Looks like a duplicate of https://github.com/atom/electron/issues/3764

**Comment by zcbenz** [comment]
Seems like a common trouble of GUI frameworks, we can reuse the patch in wxWidgets:
http://trac.wxwidgets.org/ticket/11734
