### ISSUE TITLE
How to set navigator property

### ISSUE THREAD

**Issue by sintanial** [atom/electron#4487]
I create scraper based on electron (and in particular on nightmare.js), and for properly hiding, i need change in accordance with my custom user-agent
```javascript
navigator.appCodeName
navigator.appName
navigator.vendor
etc...
```

how can i do this ?

**Comment by zcbenz** [comment]
You can change them in `preload` scripts. [This answer](http://stackoverflow.com/a/2166671/682252) would show you how to change them.

**Comment by sintanial** [comment]
thx you so match

**Comment by spike-the-coder** [comment]
Super helpful, thanks!

**Comment by iwiedenm** [comment]
Does @zcbenz answer still apply in electron `8.3.0`? I can't get it to work with any of these:

```
// preload.js
// method 1
Object.defineProperty(navigator, "language", {
  get: function () {
    return 'en-GB'
  }
});

// method 2
navigator.__defineGetter__("language", function () {
  return 'en-GB';
});
```

```
// index.html
setInterval(function() {
  console.log(navigator.language); // expected 'en-GB' but it's 'en-US'
}, 1000);
```
