### ISSUE TITLE
Notifications appearing as Alerts on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by madhav-datt** [atom/electron#4489]
Apologies in advance if this is a duplicate. 

This is more about the aesthetics of the notifications (functionally, no problems). Even when I try to create them manually with `new Notification("abc")`, I get an alert box instead of the notification one.

This does not seem like an OS issue as `$ notify-send abc xyz` and other applications give notifications as expected.

**Comment by zcbenz** [comment]
This is a duplicate of #465.
