### ISSUE TITLE
Date object can not be passed in webContents.send

### ISSUE THREAD

**Issue by VladimirPal** [atom/electron#4490]
If you will send async message with Date object, on client you will get empty object.
```
event.sender.send('async-message', {date: new Date()});
```
But if you will send sync message, everything's fine.

```
event.returnValue =  {date: new Date();
```

**Comment by subwaymatch** [comment]
My guess is that the date object is garbage collected when sent via async-message.

**Comment by zcbenz** [comment]
This is because `webContents.send` uses a different way of serialization from `event.returnValue`.
