### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by Juul** [atom/electron#4492]
./script/build.py fails during final linking when building for arm with the following error from clang++:

```
/usr/bin/arm-linux-gnueabihf-ld: /home/juul/electron/vendor/brightray/vendor/download/libchromiumcontent/shared_library/libsystem_wrappers.a(system_wrappers.tick_util.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
/home/juul/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

This is happening on a completely clean install of Ubuntu 14.04 (64 bit), following the build instructions in docs/development/build-instructions-linux.md to the letter

More details on this issue available in my previous report: #3977

**Comment by zcbenz** [comment]
Sorry but we don't provide support for building Electron on your own Linux environments, because it is just too hard to solve all possible problems on different Linux distributions with various toolchains. We only ensure Electron builds on Travis CI, and our own build machines.

**Comment by Juul** [comment]
On Tue, Feb 16, 2016 at 6:36 AM, Cheng Zhao <notifications@github.com>
wrote:

> Sorry but we don't provide support for building Electron on your own Linux
> environments, because it is just too hard to solve all possible problems on
> different Linux distributions with various toolchains. We only ensure
> Electron builds on Travis CI, and our own build machines.
>
Then can you please provide information on the Linux environment needed to
build Electron? The reply to my previous issue just stated that it was
Ubuntu 14.04. Can you give me the full list of prerequisites including
distro and toolchain?
