### ISSUE TITLE
Docs: Broken links on Desktop Environment Integration Page

### ISSUE THREAD

**Issue by eugirdor** [atom/electron#4500]
All the links to APIs on the http://electron.atom.io/docs/v0.36.7/tutorial/desktop-environment-integration/ page are broken. (e.g., app.addRecentDocument, Tray API, etc.)

For instance "Tray API" leads to http://electron.atom.io/docs/v0.36.7/tutorial/api/tray.md#traydisplayballoonoptions-windows when it should lead to http://electron.atom.io/docs/v0.36.7/api/tray#traydisplayballoonoptions-windows

**Comment by jlord** [comment]
Thanks for catching this @eugirdor. The website should be handling the parsing of the links from the original docs (here) so I'm going to open the issue in that repo and cross :link: to here :+1:
