### ISSUE TITLE
Audio Not working for screen Capture

### ISSUE THREAD

**Issue by Raj123456788** [atom/electron#4504]
According to [https://code.google.com/p/chromium/issues/detail?id=223639](this) chromium issue audio Loopback is implemented but it never works with Electron app. Can anyone share some links and explaination to why is this not working?

**Comment by zcbenz** [comment]
Any example code?

**Comment by Raj123456788** [comment]
Can you please give me an example for the constraints that need to be set? I have tried code below
`video: {
  mandatory: {                
      chromeMediaSource:'screen',
      chromeMediaSourceId: id
  }
},
audio: {
  mandatory: {
    chromeMediaSource: 'system',
    chromeMediaSourceId: id, 
  }
}`

**Comment by zcbenz** [comment]
I suggest asking for help from [the community](https://github.com/atom/electron#community).
