### ISSUE TITLE
Support Chrome --use-file-for-fake-video-capture flag

### ISSUE THREAD

**Issue by erikdonohoo** [atom/electron#4505]
Any idea how much work it would be to support the `--use-file-for-fake-video-capture` flag?  We do a lot of webcam stuff and it would be awesome for testing purposes to be able to use this flag.

I would be happy to help, just may need some direction on where the work would need to be done.

**Comment by zcbenz** [comment]
I think it is already in our code.

**Comment by erikdonohoo** [comment]
Oh it is?  I just didn't see it [here](https://github.com/atom/electron/blob/a34618866f4fe0dddf6e3d0d5a259c281d746ea6/docs/api/chrome-command-line-switches.md)

Is it documented somewhere else?

**Comment by zcbenz** [comment]
Not all command line switches are listed in that page, because there are just too much of them (I think there are hundreds).

Electron is reusing Chromium's content module, when a command line switch is implemented in content module, we inherit it for free.

**Comment by cap-mfm** [comment]
Hi, @zcbenz . This definitely doesn't work in Electron: https://github.com/cypress-io/cypress/issues/21407
