### ISSUE TITLE
Rendering crashes (white screen) when FontAwesome is used (Archlinux)

### ISSUE THREAD

**Issue by xurei** [atom/electron#4513]
With version 0.36.7 on Archlinux, if the html contains any glyph from FontAwesome, the rendering crashes and gives a white screen.

This only happens if the glyph is actually rendered, i.e. not hidden by CSS.

This can be reproduced using this example :
&lt;!DOCTYPE html&gt;

&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
	&lt;meta charset=&quot;utf-8&quot; /&gt;
	&lt;title&gt;Font Awesome Crash&lt;/title&gt;
	&lt;link href=&quot;css/font-awesome.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
&lt;/head&gt;
&lt;body&gt;
	&lt;i class=&quot;fa fa-trash-o&quot;&gt;&lt;/i&gt;
	&lt;!-- Remove the line above and the rendering works fine --&gt;
	Hello World !
&lt;/body&gt;
&lt;/html&gt;

**Comment by zcbenz** [comment]
I'm unable to reproduce on Ubuntu, probably a distribution specific problem.

**Comment by xurei** [comment]
That's my feeling too.

**Comment by JavierJF** [comment]
Same problem here, I hadn't any problem until yesterday when I make an upgrade, probably the issue is due to the new version of the following packages:

mesa (11.1.1-1 -> 11.1.2-1)
mesa-libgl (11.1.1-1 -> 11.1.2-1)
freetype2 (2.6.2-1 -> 2.6.3-1)

Probably is related to last one, but I haven't being able to confirm it yet.

**Comment by SangSatori** [comment]
Seems to be a freetype2 (2.6.3-1) thing on my end too using Arch - I had GitKraken giving blank white screen; downgrading it to cached `freetype2-2.6.2-1` makes the app usable again -- their changelog for the new version can be [found on SourceForge](https://sourceforge.net/projects/freetype/files/freetype2/2.6.3/).

**Comment by cadecairos** [comment]
@SangSatori Yup, I had the same issue! I used https://wiki.archlinux.org/index.php/Arch_Linux_Archive to grab the previous version of freetype2 and downgrade. Problem solved for now.

**Comment by Pomax** [comment]
did someone file that over on the freetype2 bug tracker? That seems like an important thing to let them know...

**Comment by SangSatori** [comment]
@Pomax Good idea - I filed a bug about this on [NonGNU Savannah bug tracker](https://savannah.nongnu.org/bugs/index.php?47202).

**Comment by lemzwerg** [comment]
I can't repeat the problem with ftview from current FreeType git.  Can you?  BTW, *which* font is actually the problem?  Additionally, can you bisect FreeType to find the exact problem?  Otherwise, a backtrace would be helpful also.

**Comment by antelle** [comment]
I've got a report from user about this issue as well. The app which crashes contains Fontawesome glyphs on the start screen: https://github.com/antelle/keeweb
As you can see on the following screenshot, these glyphs are not rendered. The app is totally stuck after start. Currently it's using Electron v0.36.7 and fails.
Electron version v0.35.6 works.
![screenshot from 2016-02-21 09-19-22](https://cloud.githubusercontent.com/assets/633557/13203201/92bf3572-d8c3-11e5-929f-b4fee04150f1.png)
I'll post more details about config if they are available.

**Comment by denysvitali** [comment]
+1 Same here, IIRC I had to use the ttf version of the font to fix the issue

**Comment by oconnor663** [comment]
I've filed an [Arch bug report](https://bugs.archlinux.org/task/48300) in case the maintainers want to downgrade the official package in the meantime.

**Comment by lemzwerg** [comment]
Folks, this doesn't help me since I can't reproduce the issue!  I need a full stacktrace, ideally produced within gdb (executing the 'bt full' command after the crash) – and FreeType should be compiled *with* debugging symbols, so that I get proper line numbers and variable values.

**Comment by Pomax** [comment]
to help clear up a possible confusion: @lemzwerg leads the Freetype project, so if there's any information that can be provided that helps him concretely, that'd be awesome.

**Comment by oconnor663** [comment]
@lemzwerg I'm not able to see a stacktrace in our logs on the Keybase side of this issue (not sure why), but I can bisect the commit that causes it:  24aa9c665e3a8bbfbc5ae016354ffba7a1377fd3, "[autofit] Rewrite HarfBuzz interface to support character clusters."

**Comment by heftig** [comment]
There's a trace here:
https://gist.github.com/anonymous/14aaa3095b9cc8f31330

I think I've seen this before and it's actually https://github.com/behdad/harfbuzz/issues/143. Which harfbuzz version does electron ship?

**Comment by oconnor663** [comment]
@heftig is it possible for you to rebuild FreeType with debugging symbols on, and then reproduce that stacktrace? (I'll admit I don't know how to do that.) I think that would help lemzwerg track down what's going on.

**Comment by heftig** [comment]
@oconnor663 The trace is not mine; it's from https://github.com/atom/atom/issues/10918.

**Comment by lemzwerg** [comment]
I think @heftig is right. Please try to upgrade HarfBuzz to version 1.0.6 or newer and report whether you still experience the problem.

**Comment by cjb** [comment]
@heftig @lemzwerg Electron uses the system harfbuzz, which on Arch (where the bug's being seen) is at 1.2.0.  So it's doesn't appear to be the case that this problem is caused by harfbuzz <1.0.6.

**Comment by cjb** [comment]
@behdad Hey, any ideas what might be wrong here?  Crash when rendering FontAwesome glyphs with the combination of freetype 2.6.3 and harfbuzz 1.2.0.  Thanks!

**Comment by behdad** [comment]
> @behdad Hey, any ideas what might be wrong here? Crash when rendering FontAwesome glyphs with the combination of freetype 2.6.3 and harfbuzz 1.2.0. Thanks!

Without a stacktrace, impossible for me or @lemzwerg to help.  It's not even clear to me if it's a crash, or just blank page.  This bug report is not consistent on that either.

**Comment by heftig** [comment]
@cjb Are you sure? The stacktrace from @drewmnoel shows that Harfbuzz has been statically linked into the `atom` binary, but FreeType comes from the system.

**Comment by behdad** [comment]
Quite possibly mixing some calls from bundled harfbuzz with some code from system harfbuzz.  Sure to crash.

**Comment by behdad** [comment]
Eg, like this: https://bugs.freedesktop.org/show_bug.cgi?id=94009

**Comment by cjb** [comment]
@heftig Oh, I was going on `ldd` reporting linking against the system harfbuzz.

@oconnor663 I wonder if making the system harfbuzz inaccessible to Electron would do anything useful, like having it fall back to only use bundled code.  Please could you test that?

@behdad Electron's use of harfbuzz comes from Chromium.  I think it is a segfault, but it's a rendering thread crashing so it doesn't kill the whole app.

**Comment by zcbenz** [comment]
Electron is linking with freetype dynamically while with harfbuzz statically, that should be the cause of the crash. Changing Electron to link with harfbuzz dynamically should be able to fix this.

**Comment by zcbenz** [comment]
Hmm Chromium is not very happy about using system harfbuzz on certain distributions, I'll try to just apply [the patch](https://github.com/behdad/harfbuzz/commit/ca97ea7aa2cb7186f432aaba76f4f151aa90c1d0).
