### ISSUE TITLE
WidevineCDM - "DRM: Unable to instantiate a key system supporting the required combinations"

### ISSUE THREAD

**Issue by kimak** [atom/electron#4519]
- Electron v0.36.7
- OSX v10.11.3
- widevine-cdm-version 1.4.8.866

I try to playback a Widevine encrypted MPEG Dash content from http://www.dash-player.com/demo/drm-test-area/ with latest electron and i got the following error: "DRM: Failed to create and initialize a MediaKeys object".

However, i follow the good doc here: https://github.com/atom/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md and i try to identify all commons problems from here: https://github.com/atom/electron/issues/2085 

<img width="1268" alt="capture d ecran 2016-02-17 a 15 16 58" src="https://cloud.githubusercontent.com/assets/1573707/13112324/86c480a6-d58a-11e5-88db-793b2a534955.png">

**Comment by zcbenz** [comment]
Please make sure:

* Both `widevinecdm` and `widevinecdmadapter` files are copied.
* The path of `widevinecdmadapter` is passed to `widevine-cdm-path`.

**Comment by kimak** [comment]
@zcbenz yes, i check the two points:

- Files are copied : cf. screenshot:
![capture d ecran 2016-02-17 a 16 30 34](https://cloud.githubusercontent.com/assets/1573707/13114463/e1b84840-d593-11e5-9175-e16d51ff5db4.png)

- The widevinecdmadapter path is passed like this:

`let widevine_adapter_path = app.getPath('appData').concat('/electron-quick-start/widevine/1.4.8.866/_platform_specific/mac_x64/widevinecdmadapter.plugin');
app.commandLine.appendSwitch('widevine-cdm-path', widevine_adapter_path);
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.866');`

**Comment by zcbenz** [comment]
Did you turn on `plugins` in `webPreferences`?

It might help if you post a simple example app.

**Comment by kimak** [comment]
Yes, webPreferences.plugins is set to "true". Maybe i miss something but i don't see wich point.

I just create a simple app with my test here:
https://github.com/kimak/electron-widevine-test

**Comment by zcbenz** [comment]
Weird, I can not get this to work anymore, even on another platform with apps used to work.

/cc @simongregory FWeinb Is WidevineCDM still working for you guys?

**Comment by simongregory** [comment]
I'm currently working with v47.0.2526.111 of the widevinecdmadapter.plugin without any trouble, however using the later v48.0.2564.97 fails. Both of these versions use an identical libwidevinecdm.dylib (checked with md5). This is unexpected as I understood the component to be compatible within 3 versions of Chrome.

**Comment by kimak** [comment]
Ok, thanks for the quick answer.
Did you know where i can download the 47.0.2526.111 version of widevinecdmadapter.plugin for testing it ?

**Comment by simongregory** [comment]
There isn't a direct download of each version that I know of. You might find it bundled inside older versions of Chrome. To update Google use Chromes component updater, this applies patches (created with courgette) to the pre-existing binaries.

If you have trouble then drop me a line directly and I'll send you a copy to try. Email address is on my profile.

**Comment by zcbenz** [comment]
I can verify the version of Chrome has to match Electron's one, once I switched to Chrome 47's widevine plugin, the problem is solved. I'll update the docs.

**Comment by kimak** [comment]
Yes, with the 47.0.2526.111 version of widevinecdmadapter.plugin it also works for me. Thanks for the help.

**Comment by mbrechet** [comment]
Hi,

I've tried @kimak sample on windows os.

Here's my configuration :

* Electron version: v0.36.7
* Operating system: Windows 10 PRO 64 bit
* widevine-cdm-version 1.4.8.866

As it's hard to find the right widevinecmadapter.dll, I've found the `47.0.2526.73` version which is a little more old than electron chromium version.

When I tests your sample as is with the `http://www.dash-player.com/demo/drm-test-area/`. It works. 

If I modify the code of `main.js` to load shaka player I faced to EME error
`
 mainWindow.loadURL('http://shaka-player-demo.appspot.com/');
`
error :
`Unable to create the CDM for the key system com.widevine.alpha.`

on the other side 

If I let the "dash-player test page" by default and navigate to the "shaka player" page by changing the location url all shaka player widevine streams are playing well.

I've you met the same problem on other OS ? I'm interested about some solution or workaround, and if someone has a way to find the exact version of the dll I'm also interested.

Regards

**Comment by kimak** [comment]
@mbrechet can you send me the widevinecmadapter.dll version 47.0.2526.73, then i could make a test on windows platform ?

**Comment by simongregory** [comment]
@mbrechet I've found that with Shaka I sometimes have to nudge Electron into recognising widevine. Running `navigator.plugins` in the console and refreshing the page is enough. Clearly this isn't a production compatible workaround!

**Comment by mbrechet** [comment]
Hi 

@kimak  I've created a [pull request](https://github.com/kimak/electron-widevine-test/pull/1) to your project with the dll I've used in my test.

@simongregory I've tried your workaround and it does nothing in my test page. 
What is strange is that the `http://www.dash-player.com/demo/drm-test-area/ ` works in all my tests.

Regards

mbrechet

**Comment by chiragrr** [comment]
Did anyone get this to work? I tried with older version of Chrome (widevinecdm version 1.4.7.771). However with http://www.dash-player.com/demo/drm-test-area/ I always still get "DRM: Failed to create and initialize a MediaKeys object"

**Comment by mbrechet** [comment]
It's working for me on Windows 10 and I think @kimak made the sample working on mac and Window 7
If you want you can add a PR with the cdm you use for linux and I'll test it on ubuntu.

But as mentionned @simongregory it's quite unstable for production use

**Comment by kimak** [comment]
@chiragrr, agreed with @mbrechet: not tested on Ubuntu yet. But PR are Welcome here https://github.com/kimak/electron-widevine-test and i will give you my results too.

**Comment by chiragrr** [comment]
@kimak & @mbrechet I got the package from https://github.com/kimak/electron-widevine-test and did a "npm install" followed by "npm start". The app starts fine but I get the same exact error on your package as well. Any suggestions? 

Please note that I am fairly new to electron and thus it could be something basic. I am open to any of your suggestions

**Comment by chiragrr** [comment]
I finally figured out the problem was using the wrong Chrome plugins. Working OK now.

**Comment by ulisinn** [comment]
Hi - 

I get the same error as described above. Please advise!
![screen shot 2016-04-25 at 15 51 02](https://cloud.githubusercontent.com/assets/156169/14801371/a4ebba1a-0afd-11e6-89ea-f63c62ecc873.png)
![screen shot 2016-04-25 at 15 48 33](https://cloud.githubusercontent.com/assets/156169/14801372/a5144174-0afd-11e6-80a1-935931c91d56.png)

**Comment by ulisinn** [comment]
I tried 3 different versions:
1.4.7.771 from a Canary install
1.4.8.866 from kimak git hub site
1.4.8.885 current chrome

result is always the same. Is there another version of that plug-in out there? Thank you for your help!

**Comment by kimak** [comment]
@ulisinn Strangely the version on my github stop working, even on my computer.

So i just push the widevine plugin that i use on my personal project (version 1.4.8.866) and it's works.
https://github.com/kimak/electron-widevine-test

Could you test the update please ?

**Comment by ulisinn** [comment]
Kimak -

looks good on my mac, thank you very much! 
We did get the older version to run on Win (a 32/64 bit issue, I don't know more about this yet). We'll check later.

The interesting thing is although outwardly the plugin has the same version number, inside of CdmAdapterVersion it says: 
47.0.2526.106 
for the version you just sent.
(electron-widevine-test-master-2/electron-widevine-test-master/widevine/1.4.8.866/_platform_specific/mac_x64)

But: 
48.0.2564.109 
in the version I downloaded yesterday.
(electron-widevine-test-master/electron-widevine-test-master/widevine/1.4.8.866/_platform_specific/mac_x64)

**Comment by soualid** [comment]
Got the same issue, and got @simongregory workaround works here under macosx 10.11.3 and electron  0.37.7 prebuilt. Also, I was able to automate the workaround using the following code when catching a CDM initialization error :
 
```console.log(navigator.plugins);
  setTimeout(function() {
    document.location.reload();
  }, 100);

**Comment by ulisinn** [comment]
Chrome/49.0.2623.75 Electron/1.0.1

Do we need a new widevine plugin for the matching browser version?

**Comment by jbleuzen** [comment]
@ulisinn I successfully update my app **on OSX** with widevine `1.4.8.885` the previous version we used `1.4.8.866` doesn't work anymore with electron `1.0.0`.

It's more complicated on Win10, I tested both  `1.4.8.866` and `1.4.8.885`but both don't work... :(

Might need to make a list of which version of widevine can be used with each version of electron...

**Comment by XanderEmu** [comment]
I just tried that on my Mac. I am using node 6.1.0, Chrome 51.0.2704.106, and Electron 1.2.7.
I have widevine CDM 1.4.8.885. It works, but...

It works only if I type `navigator.plugins` in console or if I execute `console.log(navigator.plugins);` (with console open). Otherwise it won't work.

I tried it with shaka player demo and with local dashjs-based player.
