### ISSUE TITLE
Cannot create BrowserWindow 1920x1080 (same resolution as monitor)

### ISSUE THREAD

**Issue by jfgilliam** [atom/electron#4521]
When I try to create a BrowserWindow the same size as my screen, it shortens the height. It appears to be adjusting the height for the windows task bar. The windows task bar is not on the monitor that I'm trying to create the browser window on. It is on a different monitor. Is there a way to override this behavior to use the height I gave it? Tested this with version 0.36.6 and 0.36.1 on Windows 7.

**Comment by zcbenz** [comment]
You can use the `enableLargerThanScreen` option to bypass the size limitation.

**Comment by jfgilliam** [comment]
That did not work. I can drag it to the size of the monitor. But, when creating the window with width and height equal to the monitor resolution, it adjusts the height. I think this is a bug due to the fact the task bar is not even on this monitor at all.
