### ISSUE TITLE
Tweak folder layout of source code

### ISSUE THREAD

**Issue by kevinsawicki** [atom/electron#4525]
Currently all the source code is in a root folder named `atom` with the `.cc`/`.h` files co-located with the `.js` files.

I'd like to propose separating them out into two new root folders `src/` and `lib/` where native code lives in `src/` and JavaScript code lives in `lib/`.

* `src/`
  * `app/`
  * `browser/`
     * `auto_updater.cc`
     * `auto_updater.h`
     * `...`
  * `common/`
  * `renderer/`

* `lib/`
  * `browser/`
    * `init.js`
    * `...`
  * `common/`
  * `renderer/`

This would hopefully make it easier to navigate the sources since a previous path such as `atom/common/api/lib/clipboard.js` will now be at `lib/common/api/clipboard.js`.

/cc @jlord @zcbenz any thoughts on this? Does this go against any Chromium conventions currently being followed?

**Comment by zcbenz** [comment]
Currently we pretend Electron is a component of Chromium, like this:

```
src/
├── atom
├── brightray
├── base
├── chrome
├── content
├── ui
...
```

It makes our source code look seamless with Chromium's ones, for example the headers:

```c++
#include "atom/browser/atom_browser_context.h"
#include "atom/browser/atom_browser_main_parts.h"
#include "base/files/file_util.h"
#include "brightray/browser/inspectable_web_contents.h"
#include "content/public/browser/navigation_entry.h"
```

the namespace and the header guard:

```c++
#ifndef ATOM_BROWSER_NATIVE_WINDOW_H_
#define ATOM_BROWSER_NATIVE_WINDOW_H_

namespace atom {
}  // namespace atom

#endif  // ATOM_BROWSER_NATIVE_WINDOW_H_
```

So anyone familiar with Chromium's source code or Google C++ style guide can quickly understand the structure of our source code, and we are free to reuse the tools in Chromium like `cpplint`. And vice verso for developers of Electron who want to explore the source code of Chromium.

Switching to the `src` and `lib` style makes Electron more like a node module, but it is not true, Electron is more Chromium than Node.

**Comment by kevinsawicki** [comment]
> So anyone familiar with Chromium's source code or Google C++ style guide can quickly understand the structure of our source code

Great to know, thanks so much for the detailed writeup, the current structure makes a ton of sense to me now :+1: 

So how do you feel about possibly just moving the `.js` to be co-located under a folder then? Leave all the native code as-is though. Do you think that is worth it at all?

**Comment by zcbenz** [comment]
I'm good moving `.js` files out. :+1:
