### ISSUE TITLE
Add support for Issue and PR Templates

### ISSUE THREAD

**Issue by KevinMartin** [atom/electron#4526]
GitHub recently published the ability to add templates for Issues and Pull Requests.

Would be nice the see them implemented here as it could help when finding issues between versions (for example).

https://github.com/blog/2111-issue-and-pull-request-templates

For Issues, at a minimum Electron version and platform(s) affected could be added.

**Comment by lee-dohm** [comment]
I'm working on it right now. I'll be deploying it as soon as I can.
