### ISSUE TITLE
Missing documentation for app.dock.setMenu

### ISSUE THREAD

**Issue by apoco** [atom/electron#4533]
[The documentation for app.dock.setMenu](http://electron.atom.io/docs/v0.36.7/api/app/#appdocksetmenumenu-os-x) omits details on what the `menu` parameter should be. There is a link to some Apple documentation, but it is not clear how to create the expected JavaScript object. Is there perhaps additional documentation to clarify this that could be linked to?

**Comment by apoco** [comment]
I assume this is correct:

https://github.com/atom/electron/pull/4534

**Comment by zcbenz** [comment]
Closed with #4534.
