### ISSUE TITLE
autoUpdater.checkForUpdates() throws "Can not find Squirrel"

### ISSUE THREAD

**Issue by kumarharsh** [atom/electron#4535]
I'm trying to get autoUpdater working in my app, and when I call 'checkForUpdates', it just throws this error:

```
Error: Can not find Squirrel
    at AutoUpdater.emitError (D:\Workspace\myApp\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\auto-updater\auto-updater-win.js:58:31)
    at AutoUpdater.checkForUpdates (D:\Workspace\myApp\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\auto-updater\auto-updater-win.js:26:19)
    at Object.<anonymous> (D:\Workspace\myApp\main.js:28:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (D:\Workspace\myApp\node_modules\electron-prebuilt\dist\resources\default_app\main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by paulcbetts** [comment]
You can't call `checkForUpdates` unless you're an installed app

**Comment by kumarharsh** [comment]
Is there a way to check if the app is 'installed' or in development?

**Comment by paulcbetts** [comment]
Call that method and see if it throws :)

**Comment by kumarharsh** [comment]
Lol, was thinking of doing that as a last resort. Seems like it is the first resort :stuck_out_tongue_closed_eyes:

**Comment by paulcbetts** [comment]
The canonical way to detect if you are a Squirrel-installed app if you're not into that is:

```js
fs.existsSync(path.resolve(path.dirname(process.execPath), '..', 'update.exe));
```

**Comment by kumarharsh** [comment]
OK, thanks for that :) I was thinking of writing a transparent wrapper over autoUpdater, which would just silently log stuff to console in dev environment (or maybe even do actual requests using `http`, just to check if the URLs are working, etc). Just thinking, haven't had time to actually write it yet. Maybe next week...

**Comment by mzmousa** [comment]
@paulcbetts when you say installed app, does that mean it _must_ be run through a windows installer? I'm trying to get this to work as well, and apparently my app isn't Squirrel-installed.

**Comment by paulcbetts** [comment]
Is your Setup.exe built via Squirrel.Windows? If you're using something like Inno Setup, none of the auto-update stuff will work

**Comment by mzmousa** [comment]
Yes. I used grunt-electron-installer to make my setup.exe file, which I believe uses Squirrel.Windows. The setup.exe got put in the same directory as the setup.msi, nupkg, and RELEASES files, and started up with the pretty animation and made a new entry to my programs and features, so I'm sure it executed correctly.

**Comment by paulcbetts** [comment]
Cool, in that case you are squirrel-installed - it's still throwing errors?

**Comment by mzmousa** [comment]
Yeah. I'm getting a similar error message to @kumarharsh . I get "Error: Can not find Squirrel ... " whenever I try to run the checkForUpdates() method in server.js (main entry file for my app). setFeedURL(...) works fine though

**Comment by paulcbetts** [comment]
Does the check at https://github.com/electron/electron/issues/4535#issuecomment-186662815 pass?

**Comment by mzmousa** [comment]
No. Even though there is an "Update.exe" is in the same folder as where my app is located, it doesn't pass. I've tried a number of different variations, like instead of one level (..) I would do multiple levels (../.., ../../.., ../../../..) and it still never seems to find Update.exe.

**Comment by kumarharsh** [comment]
You can only trigger the `checkForUpdates` from the installed location. Squirrel barfs when you try triggering the checkForUpdates from the source-code...

Also, you'll need to run the `update.exe` file from command-line, not `electron`.

**Comment by mzmousa** [comment]
Ah. So is there a simple way to go from source code to testing the ```checkForUpdates``` function ?

**Comment by mzmousa** [comment]
Update: a similar check to the one posted at #4535 is passing. I am now running the installed app ``` App.exe ``` as opposed to running the source code in electron.
```
fs.existsSync(path.resolve(path.dirname(process.execPath), '.', 'update.exe'));
```
However, it still cannot find squirrel. I will keep investigating

**Comment by mzmousa** [comment]
@kumarharsh could you give an example of how and where to use ```checkForUpdates()``` ? Do we just have it in our code, then install the app, then run ```./Update.exe update="C:/ReleaseFileLocation" ``` ? Other commands such as ```./Update.exe uninstall ``` are working fine but I can't get around to doing a single update.

**Comment by adampoh** [comment]
What is installed app? I packaged my app and install it. But Can not find squirrel errer is...re-occured. What should I do?

**Comment by ThomasOrlita** [comment]
Add this to scripts:
`"start": "set NODE_ENV=dev && electron ."`

and then just check before running squirell
```
if(process.env.NODE_ENV.trim() !== 'dev') {
//check for updates
}
```

**Comment by randomgithubuser1** [comment]
I just ran into this issue with my electron app.

The app is packaged using electron-builder and is installed on windows, but throws the error "Can not find Squirrel" when it checks for updates on Windows.  It works find on Mac.

Every thread I can find says the issue is related to the app not being installed, but the app is definitely installed.

**Comment by PhuHoaJC** [comment]
@anaisbetts can you support this one? 
i have same issue with @randomgithubuser1
after my app is installed. i trigger checkForUpdates function then i got that error as well =(((

**Comment by ni-binada** [comment]
Same issue here with electron-builder 22.9.1 and electron 11.3.0.

**Comment by huuson235** [comment]
I have the same problem, maybe it causes by electron-builder?

**Comment by x89-h** [comment]
Same problem using electron-builder on both NSIS and Squirrel

**Comment by nuochong** [comment]
me to

**Comment by aam1r** [comment]
Discussion continued in https://github.com/electron/electron/issues/28158

**Comment by freddy777-01** [comment]
has this issue ever been solved ???

**Comment by YeetOrBeYate** [comment]
@randomgithubuser1

Same issue on my end. I went through electron-builder's source code and it appears that the electron-updater->src folder there isn't a file that extends the native electron auto-updater 

for example in MacUpdater.ts we have this line:

`  private readonly nativeUpdater: AutoUpdater = require("electron").autoUpdater
`

And in that file you can see that nativeUpdater is handling the update events described in electron's documentation.

**Comment by LCTcode** [comment]
It’s 2024, and I also encountered this problem. How did everyone solve it?

**Comment by veena-mandhan-iphtech** [comment]
I am also facing the same. Any help will be appreciated.

The app is packaged using electron-builder and is installed on windows, but throws the error "Can not find Squirrel" when it checks for updates on Windows. It works find on Mac.

Every thread I can find says the issue is related to the app not being installed, but the app is definitely installed.

**Comment by LukasZubal** [comment]
> import { autoUpdater } from "electron-updater"

Same for me, using electron-updater package directly resolved the problems
