### ISSUE TITLE
Electron can't find libffmpeg.so

### ISSUE THREAD

**Issue by capouch** [atom/electron#4536]
After recent build from master electron can't find libffmpeg.so.

Symlinking it from ~/out/D into ~/dist fixes issue.  Of course I'm certain that's not the proper fix.

**Comment by zcbenz** [comment]
Thanks for head up, it is now fixed in master branch.

**Comment by naiduv** [comment]
On windows I get this on the -R build:

LINK : fatal error LNK1181: cannot open input file 'c:/Users/venkat.naidu/electr
on/vendor/brightray/vendor/download/libchromiumcontent/static_library/ffmpeg.dll.lib'


I got it to work by manually copying the ffmpeg.dll.lib from electron\vendor\brightray\vendor\download\libchromiumcontent\shared_library to static_library

Might be related?

**Comment by johannesjo** [comment]
Still an issue for me on Ubuntu 16.10 when building via
```
./script/bootstrap.py --dev
./script/create-dist.py
```
