### ISSUE TITLE
How to pass data to preload script and communicate with many BrowserWindow instances ?

### ISSUE THREAD

**Issue by sintanial** [atom/electron#4540]
If i have many BrowserWindow instance (about 20-30). 
1. How can i passed some data from main process to  preload script for individually BrowserWindow ? I used ```win.webContents.send``` but it doesn't worked !?
2. And another question. How to communicate with renderer process individually ? I can send data from win to renderer by ```win.webContents.send```, but how to receive response for win which send data ? Now it's only one way is use app.ipcMain, but it's global for all BrowserWindow instances.
3. It's very uncomfortable use preload script only as a file ! For example, if i can set preload script directly from main process, it's solved to me problem (1), because i can dynamically change data for each BrowserWindow

**Comment by zcbenz** [comment]
For questions, it is recommended to seek help from [the community](https://github.com/atom/electron#community).
