### ISSUE TITLE
Mac: Line between Window Title Bar and  Content 

### ISSUE THREAD

**Issue by ghost** [atom/electron#455]
On OS X most apps have a subtle line between the window's title bar and the window content. Unfortunately, in Atom Shell this line is not visible.
![Without Line](https://cloud.githubusercontent.com/assets/4000489/3472399/517ef8e2-02cb-11e4-85c1-f9c4b8e43604.png)

To better illustrate, which line I mean, I have included a screen shot of Mac's Terminal app.
![With Line](https://cloud.githubusercontent.com/assets/4000489/3472406/5c956644-02cb-11e4-8c98-5bacef787498.png)

Of course it is possible to add that line with a bit of HTML/CSS/JavaScript, but as it is there by default, it shouldn't be too difficult to make it visible. Unfortunately I don't know why and where in the code the line is hidden / not displayed in Atom Shell.

**Comment by joshaber** [comment]
Fixed by #1585 :boom:
