### ISSUE TITLE
Question: IndexedDB size limit

### ISSUE THREAD

**Issue by Frozenfire92** [atom/electron#4550]
* Electron version: newest
* Operating system: any

Is there a limit on IndexedDB for electron apps? I know it is somewhat dynamic between browsers [link](http://pouchdb.com/faq.html#data_limits) but I would assume it would be hard drive size dependent on electron apps. Asking because it wasn't in [FAQ](https://github.com/atom/electron/blob/v0.36.8/docs/faq/electron-faq.md)

**Comment by zcbenz** [comment]
We have the same size limitation with Chrome browser, which is "1/3 of the of available disk space".

**Comment by Frozenfire92** [comment]
Thank you

**Comment by wtoalabi** [comment]
It so happens that a new api that can help you determine your quota has been exposed.
https://developers.google.com/web/updates/2017/08/estimating-available-storage-space
What I would do is: know the quota and have a way of informing /warning my user when they are about to hit the quota.

**Comment by mann-david** [comment]
This is the API I am using (that post is 2 years old), and it is for Chrome.   I'm looking for something Electron specific, as it appears to override the spec.

Thanks, though.

________________________________
