### ISSUE TITLE
event.getModifierState() always returns false.

### ISSUE THREAD

**Issue by mschnee** [atom/electron#4556]
* Electron version: 0.36.8
* Operating system: Windows 10 Pro x64 Version 1151 Build 10586.104

The following code, conforming to [DOM Level 3](https://w3c.github.io/uievents/#widl-KeyboardEvent-getModifierState), is typically used to notify on the state of certain keyboard modifiers, including the current state of CapsLock, NumLock, and ScrollLock.
```
window.addEventListener('keydown', function(e){ console.log(e.getModifierState('CapsLock'))} );
```

 [More information from MDN Information](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState)

However, for all events, the function `e.getModifierState()` given any of the proper parameters, __always returns false__.

Uses: informing the user visually when the keyboard is in a capslock or numlock state for things such as number pad input and password input.

### Other browsers this currently functions in as expected:
Internet Explorer 11.103.10586.0
Edge 25.10586.0.0
Firefox 44.0.2
Chrome 48.0.2564.109 m

**Comment by zcbenz** [comment]
`event.getModifierState` is implemented in Chrome 48 and Electron is still using Chrome 47, we will get this solved once Electron is upgraded to Chrome 48. You can watch https://github.com/atom/libchromiumcontent/pull/175 for the progress.
