### ISSUE TITLE
Question: Anyone has access to WideVine CDM plugin for OSX that compatible for the latest release of Electron (v0.36.8)?

### ISSUE THREAD

**Issue by diorahman** [atom/electron#4557]
* Electron version: v0.36.8
* Operating system: OS X 10.11.2 (15C50)

Anyone has access to WideVine CDM plugin for OSX that compatible for the latest release of Electron (v0.36.8)? Since the latest Chrome is 48.x I have no access to Chrome 47's WideVine.

Thank you!

**Comment by zcbenz** [comment]
I suggest seeking help from the community:
https://github.com/atom/electron#community
