### ISSUE TITLE
Discussion - Purging irrelevant/fixed issues from open status

### ISSUE THREAD

**Issue by baconface** [atom/electron#4559]
Setting the issue filter to oldest and reading through issues I noticed quite a few of them are either now irrelevant or have a merged commit referencing them.Yet are still open. The extent of what I can do is leave a comment it should be closed but I didn't want to flood the issue manager with that. I was wondering how a clean up of issues can be done without such noise. An advantage to a clean up is hopefully to target or attract developers to long standing issues without having to dig deeper than needed. At the very least an Atom member can add an archive/on hold label to some of them and remove them from the open issues listing.

**Comment by zcbenz** [comment]
Feel free to leave a comment if you think an issue should be closed, I usually went through all old issues every few months, it would be awesome if you can help with this.

Also notice that Electron is a cross-platform framework, so for issues that are only partly fixed/implemented on certain platforms, we would keep them open.

**Comment by baconface** [comment]
Awesome. :+1:
