### ISSUE TITLE
blinkFeatures: CSSGridLayout not working

### ISSUE THREAD

**Issue by samgranger** [atom/electron#4565]
* Electron version: v0.36.8
* Operating system: OS X Yosemite 10.10.5

`new BrowserWindow({width: 1200, height: 800, experimentalFeatures: true, blinkFeatures: 'CSSGridLayout'});`

Grid is not working as expected, HTML:

```
<div class="wrapper">
  <div class="box a">A</div>
  <div class="box b">B</div>
  <div class="box c">C</div>
  <div class="box d">D</div>
</div>
```

CSS:
```
body {
  margin: 40px;
}

.wrapper {
  display: grid;
  grid-template-columns: 100px 10px 100px 10px 100px;
  grid-template-rows: auto 10px auto;
  background-color: #fff;
  color: #444;
}

.box {
  background-color: #444;
  color: #fff;
  border-radius: 5px;
  padding: 20px;
  font-size: 150%;
}

.a {
  grid-column: 1 / 4;
  grid-row: 1 / 2;
}

.b {
  grid-column: 5 / 6;
  grid-row: 1 / 4;
}

.c {
  grid-column: 1 / 2;
  grid-row: 3 / 4;
}

.d {
  grid-column: 3 / 4;
  grid-row: 3 / 4;
}
```

This should be displayed as following:
![example5](https://cloud.githubusercontent.com/assets/1847151/13202970/a43ac57c-d8ab-11e5-9d0a-71681b580c44.png)

Unfortunately, the div's just fall under each other.

**Comment by zcbenz** [comment]
Does it work in Chrome browser?

**Comment by samgranger** [comment]
It works in Chrome browser after enabling "Enable experimental Web Platform features." in chrome://flags

**Comment by zcbenz** [comment]
`experimentalFeatures` should be put in `webPreferences`:

```js
new BrowserWindow({
  webPreferences: {
    experimentalFeatures: true,
  }
});
```

**Comment by thompsonemerson** [comment]
@zcbenz Yes, chrome support already exists!

**Comment by John-AZ1** [comment]
Its still not working for me. I have put in   ```
webPreferences: {
    experimentalFeatures: true,
  }

```
And it works in chrome with the features eneabled.

**Comment by jnthnjns** [comment]
@zcbenz This still doesn't work. 

[There appears to be full support in chrome](http://caniuse.com/#search=grid):

<kbd>[Demo](https://jsfiddle.net/jnthnjns/Lby5q2m6/2/)</kbd>

I tried turning on `experimentalFeatures` as you mentioned and it starts to recognize `display: flex` but no `grid-` property is recognized.

```javascript
new BrowserWindow({
    width: 1250,
    height: 750,
    center: false,
    webPreferences: { experimentalFeatures: true }
});
```

![](http://i.imgur.com/chHtYFo.png)

![](http://imgur.com/HEFHPHl.png)


This is a much desired feature for our suite of electron applications. Is it a limitation of where chromium is at in the electron environment?

**Comment by enlight** [comment]
@jnthnjns Which version of Electron are you on? CSS Grid should be on by default as of Electron 1.6 (which is based on Chromium 57), no need to enabled experimental features.

**Comment by Septh** [comment]
@enlight Doesn't work for me neither without the `experimentalFeatures` turned on. Using Electron 1.6.11.

**Comment by enlight** [comment]
@Septh Yeah, sorry I got the Chromium/Electron versions mixed up, Electron 1.7.X is the one that's based on Chromium 57. The example in the OP works for me in 1.7.4.

**Comment by jnthnjns** [comment]
@enlight I was running electron@latest (at the time of writing this 1.6.11). I did pull down 1.7.5 and grid is now working for me.

Any timeline on taking 1.7.x out of beta? I may have to do some convincing to use an "unstable" version, doing what I do.  I work for a local government and we use Electron for some of our client applications for our 911 Dispatchers.

Thanks for your help.

**Comment by mathe42** [comment]
It does not work for me with electron v. 1.7.5 :(

**Comment by highri5e** [comment]
yep no joy in 1.7.5

**Comment by enlight** [comment]
@mathe42 @highri5e You must be running an old Electron version, open DevTools and run `process.versions.electron` to check the Electron version.

**Comment by highri5e** [comment]
@enlight Thank you for a quick response. I'm on 1.7.5 but what i just found out is that the issue was with the '@supports' feature statements that were not recognized and thus preventing the css to be applied.

**Comment by mathe42** [comment]
It works.... Thanks.

**Comment by limeandcoconut** [comment]
Can't get this to work in 1.7.9 with or without the flag. Properties don't error but they don't work either.
