### ISSUE TITLE
How to share BrowserWindow's cookie to Node modules?

### ISSUE THREAD

**Issue by xieranmaya** [atom/electron#4567]
* Electron version: *
* Operating system: *

For instance, the user loged in to my website and got some cookie in the BrowserWindow, now I want to use the cookie in Node's module like `request` how can I supply the cookie to `request`? Don't tell me to read out the cookie and set it to the relevant method.

**Comment by paulcbetts** [comment]
> Don't tell me to read out the cookie and set it to the relevant method.

This is the only way to do it. In general though, if you're in a BrowserWindow you should use DOM APIs to make network requests because your app will handle things like system-wide proxy settings more Correct'er

**Comment by xieranmaya** [comment]
What if user loged in by an online page(i.e. a passport page) and Electron developer can not control the page thus can not read out the cookie? Any other way to read out the cookie or share the cookie?

**Comment by paulcbetts** [comment]
Why would the Electron developer not be able to control the page - with a preload script you can always control the page

**Comment by xieranmaya** [comment]
`Preload script`, thank you very much, I'm going to dive into the docs.

**Comment by zcbenz** [comment]
Closing since it has been answered.
