### ISSUE TITLE
Session.setProxy fails with TypeError if callback is null

### ISSUE THREAD

**Issue by akrieger** [atom/electron#4569]
* Electron version: v0.36.5, v0.36.8
* Operating system: Win10 x64

In JS, this is the call I'm making. I'm making it from the correct process. We use ipc to send a string from 
```
url = 'http://localhost:8888'; // debug force set a url
logError('Setting proxy url to: [' + url + ']');
this.window.webContents.session.setProxy({proxyRules: url}, null);
```

This is the debug output that I have:
```
Setting proxy url to: [http://localhost:8888]
Browser process crashed with exception: TypeError: Error processing argument 0.
TypeError: Error processing argument 0.
    at TypeError (native)
    at EventEmitter.<anonymous> (SkylineWindow.js:60:39)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Personal\src\electron\out\R\resources\atom.asar\browser\api\lib\web-contents.js:119:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

I was thrown off by the 'argument 0' part. I kept trying to figure out if I was setting the dictionary wrong, 'proxyRules' vs .proxyRules. Even an empty string for url caused it. Finally I got fed up, compiled electron locally, attached to both processes, set breakpoints in SetProxy and in `Converter<net::ProxyConfig>::FromV8,` and verified that the dictionary is fine. So, then I took a shot in the dark and changed the callback from null to `() => {}`, and things magically started working.

Can the documentation either specify callback must not be null (or is that implied if not specified)? Or can the function be fixed to accept a null callback?

**Comment by zcbenz** [comment]
The documentation makes it clear that the `callback` has to be a `Function`, and `null` is not a `Function`.

**Comment by akrieger** [comment]
TIL. Thank you!
