### ISSUE TITLE
Docs: globalShortcut is listened as a main process module but example uses console.log

### ISSUE THREAD

**Issue by adam-lynch** [atom/electron#4571]

**Comment by jlord** [comment]
Could you explain the issue in more detail? You can use `console.log` in the main process.

**Comment by adam-lynch** [comment]
@jlord I definitely have misunderstood something so. It has never worked for me. Instead, I've used `window.webContents.send('log', 'something')`, listened for `log` in a renderer process with `ipcRenderer`, then `console.log`d it.

**Comment by zcbenz** [comment]
A reproducible example would help, also please list your Electron version and operating system,

**Comment by zcbenz** [comment]
Closing until more information is provided.
