### ISSUE TITLE
Make Electron available as system-wide runtime environment

### ISSUE THREAD

**Issue by kushalpandya** [atom/electron#4572]
* Electron version: 0.30+
* Operating system: Windows, Mac & Linux

There are plenty of small & large desktop applications [made in Electron](https://github.com/sindresorhus/awesome-electron), and while core application logic may be under a few megabytes, the installer (having its own Electron bundled) itself adds over 60 MB of weight. Once I have couple of Electron based apps installed, I have multiple Electron binaries installed dedicated for each single app.

Now, I'm aware that each such app **may be using a different version of Electron itself (relying on features & bugs of a particular version to get the job done)**, but that's the point here, to make sure that run-time serves the platform and apps carry just its own dependencies (NPM modules unrelated of Electron), thus making resulting installers way less in size. Look at JVM or Adobe AIR, for example.

Obviously there can be special scenarios where Electron is patched for a particular app ([Brave](https://github.com/brave/browser-laptop) browser for instance, has process sandboxing enabled, a feature not natively supported in Electron itself), in such case installer can carry runtime along, but trivial applications don't need it.

[Abricotine](https://github.com/brrd/Abricotine/releases) is one such example, where it is plain Markdown editor (and source is measly **2 MB**), but 64bit Windows installer is **75 MB!**.

This problem of redundant installations is only going to add bloat as adoption of technologies like Electron & NW.js increases to create Desktop applications (being dead simple to get apps running instead of going a native route).

Thanks.

**Comment by enlight** [comment]
See existing issue https://github.com/atom/electron/issues/673

**Comment by kushalpandya** [comment]
@enlight Oops, my bad! thanks for pointing to the existing issue (Github really needs recommendation system like Quora). Closing this issue as duplicate of #673.
