### ISSUE TITLE
Cannot embed webview with invalid certificate, whatever web preferences I set

### ISSUE THREAD

**Issue by naholyr** [atom/electron#4575]
* Electron version: 0.36.7
* Operating system: Linux (Ubuntu)

In ``main.js``:

```js
  let window = new BrowserWindow({
    center: true,
    width: 1024,
    height: 728,
    resizable: true,
    webPreferences: {
      webSecurity: false,
      allowDisplayingInsecureContent: true, // useless as webSecurity = false
      allowRunningInsecureContent: true // idem
    }
  })
  window.loadURL('file://' + __dirname + '/app/index.html')
```

In ``index.html``:

```html
<webview
  style="width:1000px;height:600px"
  src="https://www.cepos.dk"
  disablewebsecurity="on"
></webview>
```

Still, it will always display a blank square :( Is there a way to force a webview to display an URL with invalid certificate? I could intercept the error, then give choice to user and finally force-render the page, but at this point I can't give this choice.

Thanks

**Comment by zcbenz** [comment]
You can use the `certificate-error` event to ignore certificate errors:
http://electron.atom.io/docs/v0.36.8/api/app/#event-certificate-error

**Comment by naholyr** [comment]
Thanks I would have never thought about searching in global app's API :D
