### ISSUE TITLE
How am I supposed to require Electron modules?

### ISSUE THREAD

**Issue by Ericat** [atom/electron#4576]
* Electron version: ^0.4.1
* Operating system:  Yosemite 10.10.5

I don't seem to be able to require any of the Electron modules (ipc, remote etc.) and I have tried everything:

`const remote = require('electron').remote;`

or

`const remote = require('remote');`
...

or 

`import { ipcRenderer } from 'electron';`

Webpack fails to compile

```
ERROR in ../~/electron/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib-cov/electron in /Users/ericat/hoot/node_modules/electron
 @ ../~/electron/index.js 2:4-33

ERROR in ../~/drip/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib-cov/drip in /Users/ericat/hoot/node_modules/drip
 @ ../~/drip/index.js 2:4-29

ERROR in ../~/tea-concat/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib-cov/concat in /Users/ericat/hoot/node_modules/tea-concat
 @ ../~/tea-concat/index.js 2:4-31
```

I assume this is webpack-related? I use "webpack-target-electron-renderer": "^0.4.0", can anybody please help?

Thanks for your time

**Comment by paulcbetts** [comment]
Webpack is stomping `require` with its own version. A way easier way to get react to work is to use [electron-compile](https://github.com/electronjs/electron-compile)

**Comment by Ericat** [comment]
@paulcbetts the issue was that I had somehow mistakenly installed a conflicting module that is called 'electron'. :( will close this, hopefully webpack won't cause problems at all. Thank you anyway!
