### ISSUE TITLE
ffmpeg.dll.lib Not found: Build error on windows 

### ISSUE THREAD

**Issue by naiduv** [atom/electron#4578]
* Electron version: commit 537ead89171f5978183ea1 (since atleast 2/19)
* Operating system: Windows 8 64 bit

[6/6] LINK_EMBED electron.exe 
FAILED: c:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True electron.exe "c:\Python27\python.exe gyp-win-tool link-wrapper environment. x86 False link.exe /nologo /OUT:electron.exe @electron.exe.rsp" 1 mt.exe rc.exe "obj\electron.electron.exe.intermediate.manifest" obj\electron.electron.exe.gene \rated.manifest ..\..\atom\browser\resources\win\atom.manifest
LINK : fatal error LNK1181: cannot open input file 'c:/Users/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/ffmpeg.dll.lib'

Error only occurs in the Release version.
Error is fixed when manually copying the ffmpeg.dll.lib file from shared_library to static_library

**Comment by zcbenz** [comment]
It seems that you are still using an old version of libchromiumcontent, running `bootstrap` script should be able to fix this.

**Comment by vietquocnguyen** [comment]
@zcbenz can you please elaborate on this "bootstrap" script?
