### ISSUE TITLE
Electron based applications on Windows 10: There are always console windows opened

### ISSUE THREAD

**Issue by webarchymeta** [atom/electron#4582]
* Electron version: 0.36.x
* Operating system: Windows 10
Ref: #3846 
When the following is added to the `main.js` file:
```js
app.commandLine.appendSwitch('enable-logging');
```
Multiple console windows are opened. It also happens to the demo program that comes with electron distribution. However this does not happen to other OSs tested (other Windows system and Linux).

**Comment by zcbenz** [comment]
The purpose of `enable-logging` switch is to print internal logs and make debugging easy, if you don't need this, just do not use it.
