### ISSUE TITLE
error while loading shared libraries: libnode.so

### ISSUE THREAD

**Issue by cyphunk** [atom/electron#4583]
* Electron version: v0.36.7
* Operating system: Ubuntu 14.04 lts

After giving electron permissions to monitor packet device (setcap) this error occurs:

    $ sudo setcap cap_net_raw,cap_net_admin=eip /home/user/git/myapp/myapp-linux-x64/myapp
    $ /home/user/git/myapp/myapp-linux-x64/myapp
    /home/user/git/myapp/myapp-linux-x64/myapp: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory

The same is true when executing electron-prebuilt from my applications directory:

    $ cd /home/user/git/myapp/
    $ sudo setcap cap_net_raw,cap_net_admin=eip /home/user/git/myapp/node_modules/electron-prebuilt/dist/electron
    $ ./node_modules/.bin/electron .

Once setcap permissions are removed (-r) everything works again.

**Comment by zcbenz** [comment]
This is unfortunately a limitation of Linux:
http://stackoverflow.com/questions/9843178/linux-capabilities-setcap-seems-to-disable-ld-library-path

**Comment by cyphunk** [comment]
Thank you for the background information. I'm confused a little though as the discussion at the link you give has 50% people saying it's by design and the other saying it's due to an app improperly compiled (in this case it would be whatever is responsible for generating the .so)? Or I could have read it wrong.

**Comment by zcbenz** [comment]
Electron relies on the ability to search for dynamically libraries under the binary's directory, while calling `setcap` would disable this ability for security reasons. For some people in the original issue, they don't actually need this ability and are able to work around this.

**Comment by liamcmitchell** [comment]
I worked around this by using `capsh` to set capabilities on the shell process:

```sh
sudo capsh --user=$(whoami) --iab="^cap_net_raw" -- -c "/opt/MyElectronApp/MyElectronBinary"
```

References:
* https://unix.stackexchange.com/a/503546
* https://man7.org/linux/man-pages/man1/capsh.1.html
* https://man7.org/linux/man-pages/man7/capabilities.7.html
* https://sites.google.com/site/fullycapable/inheriting-privilege

I also tried to avoid sudo by setting capabilities on the user as described [here](https://github.com/astral-sh/python-build-standalone/issues/576#issuecomment-2776416831) and [here](https://sites.google.com/site/fullycapable/pam_cap-so) but no luck.
