### ISSUE TITLE
Possible to use http-parser-js in an Electron app?

### ISSUE THREAD

**Issue by robwilkerson** [atom/electron#4585]
* Electron version: 0.36.7
* Operating system: OS X

My electron app needs to make an HTTP request to a service that returns malformed headers:

    $ curl -IS 'http://192.168.0.1/getdeviceinfo/info.bin'
    HTTP/1.1 200 OK
    Date: Wed, 02 Dec 2015 16:42:45 GMT
    Server: nostradamus 1.9.5
    Connection: close
    Etag: Aug 28 2015, 07:57:20
    Transfer-Encoding: chunked
    HTTP/1.0 200 OK
    Content-Type: text/html

Notice the duplicate `200 OK` header? Yeah, so does the native Node.js parser and it chokes. In a standalone test script, I've found that I can use the `http-parser-js` library to make the same request and it handles the bad headers gracefully.

Now I need to make that work within the Electron app that needs to actually make the call and retrieve the data and it's failing with the same `HPE_INVALID_HEADER_TOKEN` I've been getting all along. I assume, for that reason, that the native HTTP parser is not getting overridden the way that it does in the test script.

In my electron app's main process, I have the same code I used in my test script:

    process.binding('http_parser').HTTPParser = require('http-parser-js').HTTPParser;
    var http = require('http');

    var req = http.request( ... )

Is there an alternate process binding syntax I can use within Electron? Or some other means of making an HTTP request without taxing the Node parser?

**Comment by zcbenz** [comment]
Do you mean the same code works in Node but not in Electron? If so can you provide an example app?

**Comment by robwilkerson** [comment]
@zcbenz That's correct. It will take me a bit to build up a stripped down app, but I've created a [gist of the standalone script](https://gist.github.com/robwilkerson/00481a56a730015beaae) I can execute via `$ node modem-request

Will follow up with an example app as quickly as possible.

**Comment by robwilkerson** [comment]
The simplest case almost always works. In this case, it was a real PITA to create that simple case from where I am now, but it surely helped me see that Electron wasn't the problem. My app required a separate module that, in turn, required the `request-promise` library which seems to reset the original parser. Once I removed that include, the new parser worked nicely.

Thanks for the push.
