### ISSUE TITLE
autoUpdater: How to use GithubUpdateManager?

### ISSUE THREAD

**Issue by kumarharsh** [atom/electron#4589]
* Electron version: 0.36.7
* Operating system: Windows 10 x64

Is there a way to use the [GithubUpdateManager](https://github.com/Squirrel/Squirrel.Windows/blob/66ae056a2ad158917c5d07c3a498a1068712f0bd/docs/using/github.md)? I can't find any documentation [here](http://electron.atom.io/docs/v0.33.0/api/auto-updater/) about that.

**Comment by zcbenz** [comment]
No, the autoUpdater in Electron relies on the command line interface of Squirrel, while `GithubUpdateManager` only provides programming interface in C#.

**Comment by zcbenz** [comment]
No, the autoUpdater in Electron relies on the command line interface of Squirrel, while `GithubUpdateManager` only provides programming interface in C#.

**Comment by kumarharsh** [comment]
OK. thanks for the clarification. Any plans to add it?

**Comment by zcbenz** [comment]
It would need a command line interface in [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) first, and we probably need to add the same thing in Squirrel.Mac too. We don't have a plan to add it, but I will accept PRs adding that.
