### ISSUE TITLE
webSecurity option not working

### ISSUE THREAD

**Issue by surdu** [atom/electron#4590]
* Electron version: v0.36.8
* Operating system: Ubuntu 14.04

I have the same problem as stated here: http://stackoverflow.com/questions/32691670/electron-use-post-request-fails

Just in case the question is deleted in the mean time, I'll pasted it below:

> I am trying to turn my node app into a desktop using Electron. In my current code I use a "POST" request and the res.send() to return data back from my node script. Express handles the end points.
> 
> However, when I try and use the same code with Electron I get
> 
> `net::ERR_CONNECTION_REFUSED`
> 
> I have spent lots of time trying to figure a solution and it seems this could be caused by the CORS issue and so have added
> 
> ```
> "web-preferences": {
>   "web-security": false
> }
> ```
> To my Electron BrowserWindow config but this has not helped.

> Can anyone share a sample of doing a JQuery POST request in Electron. Be a big help. Thanks

**Comment by zcbenz** [comment]
You have to use the [webFrame.registerURLSchemeAsBypassingCSP](http://electron.atom.io/docs/v0.36.8/api/web-frame/#webframeregisterurlschemeasbypassingcspscheme) API to make the URL scheme bypass CSP rules. I would like to make `webSecurity` turn off all security settings, however the design of Chromium and blink force us to provide a separate API for it.
