### ISSUE TITLE
Canvas rendering issue on OS X

### ISSUE THREAD

**Issue by rhysd** [atom/electron#4594]
* Electron version: 0.36.1 and 0.36.8
* Operating system: OS X 10.11 and OS X 10.10

I'm creating Electron application and was reported [an issue](https://github.com/rhysd/NyaoVim/issues/3) at end of last year.
Below is a screenshot reported in the issue.

![screenshot](https://cloud.githubusercontent.com/assets/245343/11973263/1e3ea114-a958-11e5-97c9-40f84321a1ab.png)

In this app window, everything is rendered to `<canvas>`.  And all characters are wrongly rendered as square.  In console, reporter said that below error was shown many times.  Other some people reported this issue and all of their OS were OS X.  (And another one reported that this occurred in other application.)

```
[48303:1223/093014:ERROR:gles2_cmd_decoder.cc(7333)] [.Offscreen-MainThread-0x7fecb3451ed0]GL ERROR :GL_INVALID_OPERATION : glUseProgram: program not linked
```

I investigated this but I could not reproduce although I was using the same OS version.  I made [a question in forum](https://discuss.atom.io/t/gl-error-in-canvas/24058) but I could not get the answer.  I also searched Chromium bug tracker with above error message but I could only get unrelated old issues.

**Comment by zcbenz** [comment]
The search for "glUseProgram: program not linked" found some issues in Chromium and they were all merged into https://crbug.com/473891, in it there are two workarounds that you can have a try:

* Use command line --use-gl=egl
* Define env MESA_GLSL_VERSION_OVERRIDE=1.30

I'm closing this since it is an upstream Chromium bug and we are not able to fix this on Electron's side.

**Comment by rhysd** [comment]
@zcbenz 

Thank you very much for the investigation.  I'll try the solution and, when it doesn't solve this issue, I'll make bug issue on Chromium project.

**Comment by rhysd** [comment]
I note that above configuration didn't help to solve this issue :sob:
