### ISSUE TITLE
Partially re-rendered window

### ISSUE THREAD

**Issue by scholtzm** [atom/electron#4597]
* Electron version: 0.36.7 (but also 0.35.4)
* Operating system: Windows 8.1

This issue has been happening to me consistently for a while. Electron window gets only partially re-rendered or not re-rendered at all if I come back to my PC after I have been AFK for a while (Windows 8.1 will by default shut down computer screen after ~10 minutes). At this point, the window won't get re-rendered unless the Electron window is focused - at which point the window is correctly re-rendered.

However, I have noticed that if I hover my mouse over the Electron window, it will get sometimes partially re-rendered:

![render-bug](https://cloud.githubusercontent.com/assets/2640934/13302265/4a1597f2-db49-11e5-96e0-820044a40db5.png)

**Comment by zcbenz** [comment]
Is it possible to dump a HTML page and see if it reproduces in Chrome browser? Most of the rendering bugs in Electron are inherited from Chromium, so unless you can reproduce it in Chrome browser, the only solution is to wait for the upgrade of Chrome and see whether it fixes the problem.

**Comment by scholtzm** [comment]
I'll have a look and see if I can replicate this in regular Chrome browser.

**Comment by zcbenz** [comment]
Closing until more information is provided.
