### ISSUE TITLE
Module for node v0.12.x   Error: Module did not self-register.

### ISSUE THREAD

**Issue by azamatsmith** [atom/electron#4598]
* Electron version: v0.36.8
* Operating system: Windows Server 2008r2  64bit

When I run `process.version` I get `v5.1.1` and I assume that this is the node version that is running the program? Is there a way I can change that to v0.12.9 so that I can use the module that I am trying to use?

The module is a connector to a "cache" database fyi.

**Comment by paulcbetts** [comment]
Peep https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md to solve this

**Comment by azamatsmith** [comment]
So I followed all of the instructions there, but I must be doing something wrong? This is a module that was provided to me. It is actually a windows dll file that I `var globals = require('./cache')` in my file.
