### ISSUE TITLE
No icon for applications in Linux taskbar

### ISSUE THREAD

**Issue by gromain** [atom/electron#4600]
The problem appears with the latest Rocket.chat version (1.0.0) and the latest Boostnote version (0.5.4).
There is no icon for the application in the taskbar.

![electron icon problem](https://cloud.githubusercontent.com/assets/2188885/13316107/ac714daa-dbae-11e5-9810-08b14abc3ed3.png)

However the application icon still appears correctly in Plank (a dock application for Linux).

* Electron version: 0.36.0 for Rocket.chat, 0.35.4 for Boostnote.
* Operating system: Manjaro 15.12, up to date as of February 25th

**Comment by zcbenz** [comment]
On Linux you have to provide a `.desktop` file for your app to make sure the desktop environment can show your app's icon correctly, for more about this you can see:
https://wiki.archlinux.org/index.php/Desktop_entries

**Comment by gromain** [comment]
Well, I'm sorry, but I do have `.desktop` files for those two applications...

Here is the one for Rocket.chat (installed directly by the application in `/usr/share/applications/`:
```
[Desktop Entry]
Version=1.0
Type=Application
Encoding=UTF-8
Name=Rocket.Chat
Comment=Rocket.Chat Native Cross-Platform Desktop Application via Electron.
Exec=/opt/rocketchat/rocketchat
Path=/opt/rocketchat/
Icon=/opt/rocketchat/icon.png
Terminal=false
Categories=Application;
```

And here is the one for Boostnote, this one I created myself, also in `/usr/share/applications/`:
```
[Desktop Entry]
Type=Application
Version=0.5.4
Name=Boostnote
Comment=Note-taking application for programmers
Icon=/home/rbazile/bin/boostnote/logo.png
Exec=/home/rbazile/bin/boostnote/Boostnote
Path=/home/rbazile/bin/boostnote
Categories=Development;
Name[en_US]=Boostnote
```

So yeah, I do believe it's a genuine problem (it did not happen before when I was using rocket.chat only).

**Comment by gromain** [comment]
Ok, I installed Atom to test. And... It worked. The main difference was in the `atom.desktop` file where the Icon part was not a full path, but just the name of the application.
So I think I narrowed down the problem to my desktop environment.
Apparently the problem comes from the `.desktop` file. Maybe Cinnamon (my desktop environment) doesn't like absolute path for the Icon. If I replace the path by respectively `rocketchat` and `boostnote` the icons are displayed on launch.
Anyway, thanks!

**Comment by chenqk123** [comment]
Hi @gromain  Do you mean you set Icon=/home/rbazile/bin/boostnote/logo.png is Icon=boostnote or  Icon=/home/rbazile/bin/boostnote in .desktop file? I have happend to this question too .The app icon is blank in taskbar in linux Ubuntu.

**Comment by gromain** [comment]
Hi @chenqk123,

Right now, for Boostnote, my the `.desktop` file looks like this:
```
[Desktop Entry]
Name=Boostnote
GenericName=Boostnote is an open source note-taking app made for programmers just like you.
Comment=Boostnote is an open source note-taking app made for programmers just like you.
Exec=/usr/bin/boostnote %U
Icon=boostnote
Type=Application
StartupNotify=true
Categories=Development;Utility;
MimeType=text/plain;
```
