### ISSUE TITLE
Cannot get process.pid when require a module

### ISSUE THREAD

**Issue by varHarrie** [atom/electron#4601]
* Electron version:0.36.8
* Operating system:Win10 x64

![image](https://cloud.githubusercontent.com/assets/14304201/13318991/7b68e74a-dbf9-11e5-9b40-6b633ef4893e.png)

The problem appear in module(Linvodb3) which try to get the pid.

**Comment by zcbenz** [comment]
Can you provide an example app?

**Comment by varHarrie** [comment]
Thx to reply.
In my app I use webpack. I just replace the 'require' from 'nodeRequire' and there is no error any more.
