### ISSUE TITLE
Cannot read property 'on' of undefined.

### ISSUE THREAD

**Issue by havenchyk** [atom/electron#4602]
* Electron version: 0.36.8
* Operating system: Win7 x64

Suddenly electron have stopped working on my machine.

An error occurs on the code like 

```
const ipc = require('electron').ipcMain;
ipc.on('myEvent', () => console.log('an error before!'));
```

The error text is: `Cannot read property 'on' of undefined`.

**Comment by petrvecera** [comment]
We are experiencing the same issue in our team! 
However it doesn't work only on Linux in our case and in doesn't work only in our project.

When we test the same code in some new template electron app - everything is ok. Also we are not facing this issue on Windows, OS X - where the code of our project is the same.

- Electron version: 0.36.8
- OS: Ubuntu 14.04, 15.10 , Mint 17.2

**Comment by havenchyk** [comment]
In my case everything works fine on Ubuntu 14.04, but before the today it worked on Win7 also. Weird.

What I did:
`npm cache clean`
event reinstall node and npm.
clean `.atom` folder
restart of windows machine

There is no changes, still the same error.

**Comment by zcbenz** [comment]
Please see the FAQ entry:
http://electron.atom.io/docs/v0.36.8/faq/electron-faq/#requireelectronxxx-is-undefined

**Comment by havenchyk** [comment]
You're right. There were `node_modules` with electron on the two levels upper from my repository. Unpredictable. `path.resolve(require('electron'))` is a great catch, thanks
