### ISSUE TITLE
video h264 hardware decode

### ISSUE THREAD

**Issue by priestnot** [atom/electron#4604]
* Electron version: 0.34.1 (It also appends with 0.36.8)
* Operating system: Ubuntu 14.04 32b
* Hardware Intel J1800 CPU. Intel Graphics HD Graphics (Bay Trail).

I activated the following flags in on my electron app:
app.commandLine.appendSwitch('ignore-gpu-blacklist', 'true');
app.commandLine.appendSwitch('enable-gpu-rasterization', 'true');
app.commandLine.appendSwitch('enable-zero-copy', 'true');
app.commandLine.appendSwitch('disable-software-rasterizer', 'true');

And if I Run the chrome://gpu page it gives me the following result:
```
**Graphics Feature Status**
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Rasterization: Hardware accelerated
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
```

But I do not notice any diference in the cpu load. Electron is still decoding the h.264 video using software decoder.

**Comment by simongregory** [comment]
You can use `chrome://media-internals/` to find debug information on how Electron is handling any media it is currently playing. So far, on my Mac, I've seen `FFmpegVideoDecoder` with `--disable-gpu` switch, `DecryptingVideoDecoder` with Widevine content, and `GpuVideoDecoder`.

However Electron will be inheriting the decoding capabilities from upstream projects - Chromium and FFmpeg. I would expect you to see the same behaviour in Chrome if you tried playback there.

**Comment by priestnot** [comment]
Yes I get the same results using chrome and chromium. They both return FFmpegVideoDecoder.

As far as I got hardware decoding has been disable on chromium because of instability (because of not so good graphic driver in linux).

But that would be fixed by now based on this issue, but i do not understand how:
https://github.com/atom/libchromiumcontent/issues/92

**Comment by zcbenz** [comment]
How Chrome decides whether to enable hardware acceleration is very complex, it is not just a few command line switches, I'm afraid you have to debug into Chrome's source code to find out why hardware acceleration is not enabled on your machine.

I'm closing this since the behavior is expected.

**Comment by priestnot** [comment]
Thanks for your help...

But is there some one that has Hardware accelerated video decoding on linux using electron?
Is this a hardware/driver problem?

**Comment by alberto2000** [comment]
Very interested too to get Hardware Accelerated Video Decoding in Linux/Ubuntu. Any update on this?

**Comment by priestnot** [comment]
I never tested it on the later versions of electron. So I do not know if in the newest version the Hardware Accelerated Video Decoding is working.

I think that it is drivers/hardware dependent. Some work some do not. But I could be wrong.

**Comment by manast** [comment]
If you manage to make standard chrome working with acceleration, then if electron still does not use the acceleration it may be a issue specific for chrome, otherwise drivers or chromium issue.

**Comment by freechelmi** [comment]
Intel has submitted a patch to chromium source years ago to support vaapi
https://chromium-review.googlesource.com/c/chromium/src/+/532294

Google do their best to reject it every release to be sure that chrome on linux will not be able to decode video using the GPU even with a flag
