### ISSUE TITLE
Building native module with electron-packager for Windows OS

### ISSUE THREAD

**Issue by gabrielstuff** [atom/electron#4606]
* Electron version: 0.35
* Operating system: Windows 7 / 10

Hi !

We are really happy to use electron, and so far it works like a charm. For an app we are currently developing we use : leveldown and node-mdns. We manage to compile the native module to make them run on electron.

So after packaging the app with this npm script : 

`electron-packager . %npm_package_name% --out=bin --platform=win32 --arch=x64 --ignore='^/bin$' --prune --version=%npm_package_electronVersion% --overwrite -icon=lucca.ico`

It works on Windows 10 and Windows 7 but only on the machine we have built the app.

If we move the app on an other computer and try to run it the following error popup : 

![error](https://cloud.githubusercontent.com/assets/285033/13328804/fb9060f0-dbf0-11e5-8c12-95979f839a7c.jpg)

Any help would be appreciated !

Thanks !

**Comment by paulcbetts** [comment]
This isn't a native module error, this is an issue with your app or the node-mdns module

**Comment by gabrielstuff** [comment]
@paulcbetts could you be a bit more specific ? If i package the app on the machine i've got error from, then It works like a charm.

**Comment by zcbenz** [comment]
node-mdns relies on some external library/SDK and you only installed it on your build machine.

**Comment by gabrielstuff** [comment]
Thanks @zcbenz, I hope it could be that, but we tried to install Bonjour SDK on the running machine and it does not fix the issue. 
Error message still the same. We also tried to simply run the app on a machine which runs a full copy :) 
Visual Express / python / node / etc... but it does not change a damn thing...

**Comment by gabrielstuff** [comment]
For references, here is the issue on mdns side : https://github.com/agnat/node_mdns/issues/159
