### ISSUE TITLE
Cannot use absolute path at html

### ISSUE THREAD

**Issue by ibufu** [atom/electron#4612]
* Electron version: 0.36.8
* Operating system: win7

I use absolute path at html for img css and js,but it cannot load these because electron load these from E:\ instead of my project path.

**Comment by enlight** [comment]
See http://stackoverflow.com/questions/35568293/can-you-use-absolute-paths-in-electron

**Comment by ibufu** [comment]
@enlight 
```
protocol.interceptFileProtocol('file', function(req, callback) {
    var url = req.url.substr(7);
    callback({path: path.normalize(__dirname + url)})
  })
```
but console show:
Not allowed to load local resource: file:///E:/electron-v0.36.8-win32-x64/resources/app.asar/login.html

**Comment by enlight** [comment]
Are you sure that `login.html` is in `app.asar`? [This issue](https://github.com/atom/electron/issues/2662) seems to indicate it could just be a missing file.

**Comment by ibufu** [comment]
yes, I am sure.
If i remove the code above, the electron can run successfully.Just fail to load img and css of absolute path.

**Comment by ibufu** [comment]
@enlight 
Maybe the code above make login.html is not in app.asar.

**Comment by ibufu** [comment]
```
app.on('ready', function() {

  var protocol = electron.protocol;
  protocol.interceptFileProtocol('file', function(req, callback) {
    var url = req.url.substr(7);
    callback({path: path.normalize(__dirname + url)})
  },function (error) {
    if (error)
      console.error('Failed to register protocol')
  })
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 1200, height: 800});

  // and load the index.html of the app.
  mainWindow.loadURL('file://' + __dirname + '/login.html');

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});

```

**Comment by enlight** [comment]
If the path is correct then [try setting `webSecurity` to `false`](https://github.com/atom/electron/issues/483#issuecomment-51785479).

**Comment by ibufu** [comment]
Its so strange, when I set webSecurity to false, the electron is just a blank page and console show nothing. If press F5, Network catch nothing.

**Comment by zcbenz** [comment]
This behavior is expected in browsers, to work around this it is usually recommended to register a new scheme instead of intercepting `file://`, because browsers have many weird behaviors on `file://` protocol.
