### ISSUE TITLE
How to focus devTools ?

### ISSUE THREAD

**Issue by remss** [atom/electron#4614]
On F12 i open the devtools like this

    electron.remote.getCurrentWindow().webContents.openDevTools()

If the user focus the main window and press F12, then nothing happens because the devtools are already opened. I wish the devtools window to be focused (like Chrome does) but i don't know how to do that.

Thanks for your help.

**Comment by zcbenz** [comment]
You can call:

```js
require('remote').getCurrentWindow().devToolsWebContents.focus();
```

**Comment by remss** [comment]
It does not work. 
If think that is the BrowserWindow instance of the debugger that should be focus() but i don't know how to get its reference.

**Comment by remss** [comment]
Can you reopen this issue since the answer does not work ?

**Comment by remss** [comment]
I just tried with Electron 3.10 and devToolsWebContents.focus() works fine.

**Comment by dwieeb** [comment]
I am using `openDevTools()` on an Electron `<webview>` tag and attempting to focus it, but it doesn't focus the window.

```js
const webContents = webviewElement.getWebContents();
webContents.devToolsWebContents.focus();
```

I haven't tried porting everything to a `BrowserView` yet.
