### ISSUE TITLE
Any way to control contextMenu position?

### ISSUE THREAD

**Issue by beshur** [atom/electron#4617]
* Electron version: 0.36.8
* Operating system: OSX

I was asked a question why the context menu is so down the screen?
![Alt text](https://monosnap.com/file/SXWOUWwLRewPBv9WVf0HlmYUDBdzzG.png)
See other apps (like Chrome or Skype) where you do need to scroll long menus as they all have their last element at the bottom of the screen and it is visible.

**Comment by zcbenz** [comment]
It seems that Safari has the same behavior?
<img width="696" alt="screen shot 2016-02-26 at 10 21 26 pm" src="https://cloud.githubusercontent.com/assets/639601/13354644/5b0d30ee-dcd7-11e5-81ed-58145c88506b.png">

**Comment by beshur** [comment]
@zcbenz, tried in Safari (all's good):
![Alt text](https://monosnap.com/file/RBeCZ13V95nrz7mdyqZIcz2u4jE8Xm.png)

**Comment by zcbenz** [comment]
The arrow only shows when the menu is too long.
