### ISSUE TITLE
Question: Is there a way to pass cookies or headers when calling shell.openExternal?

### ISSUE THREAD

**Issue by ccnokes** [atom/electron#4618]
* Electron version: 0.36.0
* Operating system: Mac OSX 10.11.3

I'm using the same authentication for my electron app as my web app does and when a user clicks my company's logo, I'd like to take them to my web app and have them already be logged in. It doesn't look like `openExternal` supports this (unless I missed something in the documentation). Is there a way to work around that? If not, would that be a feature that could be added?

**Comment by MarshallOfSound** [comment]
`openExternal` simply fires a URL at the OS and the OS decides which app to use to open it.  I don't think that it is possible to send headers/cookies with that URL.

Perhaps you could implement an instant login feature inside your app that passes a token as a *GET* parameter to the `openExternal` URL and logs them in to your website when that token is valid?

**Comment by ccnokes** [comment]
Gotcha. After looking around I think that's the best way to go. Too bad it's not possible though because it would be cool. Thanks for the help!
