### ISSUE TITLE
Global shortcut register -> Add a force option?

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4620]
* Electron version: `0.36.9`
* Operating system: `Windows`

Is there any way we can **force** a global shortcut registration.  My app at the moment seems to fail at shortcut registration randomly on other peoples machines and we have no idea what is stealing the shortcut we want (MediaPlayPause).

Is there a way that either

* (Preferably) We can force the shortcut to register
* *or* The register call fails with an explanation as to why it failed (which app is currently holding the shortcut)

**Comment by paulcbetts** [comment]
> Is there any way we can force a global shortcut registration

Nope! It's first-come, first served, this is how Windows works, it doesn't have anything to do with Electron.

**Comment by MarshallOfSound** [comment]
@paulcbetts Can we possibly then change how electron implements this and use low level keyboard hooks instead of the functionality windows offers.  Then we don't have a "race for the shortcut" issue.

Or is this the kind of thing that would be better server as a native module?

**Comment by paulcbetts** [comment]
> Or is this the kind of thing that would be better server as a native module?

I think it would make more sense there, yeah

**Comment by MarshallOfSound** [comment]
For history's sake, if anyone stumbles across this issue wanting the same thing there is now a node module for it

https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win

Don't forget to follow the native module compilation steps in the electron docs
