### ISSUE TITLE
Permission to create file in the .app file

### ISSUE THREAD

**Issue by amoinier** [atom/electron#4621]
* Electron version: last version
* Operating system: MacOSx El Capitan

Hi everyone, I post today because I have a problem with electron/node.js. For my application, I need to create and/or modify file who is store in my .app (after electron-packager) but I have already an error of permission denied. I would like know if it's possible to do that.

Thanks a lot.

PS : Sorry for english, but i'm french.

**Comment by paulcbetts** [comment]
You can't do that, it will break the signature

**Comment by amoinier** [comment]
Ok thank you !
