### ISSUE TITLE
How would I do Facebook Login?

### ISSUE THREAD

**Issue by Jonovono** [atom/electron#4624]
Hi. I am trying to figure out how I can let users of my electron app log in via Facebook. Is this possible? Any examples or suggestions?

Thanks!

**Comment by baconface** [comment]
Not really an Electron issue. But you can use the [Facebook JavaScript SDK](https://developers.facebook.com/docs/facebook-login/web) like you would a website.

**Comment by sbruchmann** [comment]
In future, please use the [discussion forum](https://discuss.atom.io/c/electron) for questions. GitHub Issues are for bug tracking only.

**Comment by goldsquare** [comment]
https://github.com/nageshpodilapu/Using-Facebook-Twitter-API-with-Electron-Application/blob/master/index.js 

good example that works

**Comment by rainmak33r** [comment]
Any solution ? The example above got removed, help please !

**Comment by adrienjoly** [comment]
This, maybe: https://competenepal.com/lets-make-a-facebook-login-system-in-electron-that-actually-works/

**Comment by Pablodotnet** [comment]
For everyone searching a working example here is mine:
https://github.com/Pablodotnet/electron-facebook-login-example
