### ISSUE TITLE
BrowserWindow.fromWebContents return null from DevTools webcontents

### ISSUE THREAD

**Issue by parro-it** [atom/electron#4625]
* Electron version: 0.36.8
* Operating system: Lubuntu 14.04.3

I'm trying to [focus an open `DevTools` window](https://github.com/sindresorhus/electron-debug/issues/32).
I'm able to get `DevTools` webContents using `webContents.devToolsWebContents` method.
Then I want to get a `BrowserWindow` instance from it that I could use to focus, but `BrowserWindow.fromWebContents` always return null.

**Comment by zcbenz** [comment]
You can call `BrowserWindow.fromDevToolsWebContents` to get it.

**Comment by parro-it** [comment]
Thank you @zcbenz, I'll try it... is this documented somewhere?

**Comment by parro-it** [comment]
I tried `BrowserWindow.fromDevToolsWebContents`, but it appear it return `BrowserWindow`of my app window. What I need is instead to retrieve `BrowserWindow` instance of DevTools itself.
I need this to give focus to the DevTools window.

**Comment by zcbenz** [comment]
There is no `BrowserWindow` attached to devtools, the window you saw is not exposed in JavaScript. We will change this when #2835 is implemented.

**Comment by parro-it** [comment]
Thank toy, @zcbenz I will track that issue.
