### ISSUE TITLE
undefined references when building on Linux

### ISSUE THREAD

**Issue by brenca** [atom/electron#4626]
* Electron version: 36.9
* Operating system: Ubuntu 15.10 64bit

When I tried to build the latest version on Ubuntu, I got a bunch of undefined references, all related to `std::__cxx11::basic_string` in some way.

I've found a fix, I've added the [`'-D_GLIBCXX_USE_CXX11_ABI=0'`](http://developerblog.redhat.com/2015/02/05/gcc5-and-the-c11-abi/) option to [`'cflags_cc'`](https://github.com/atom/electron/blob/master/toolchain.gypi#L80). This seems to work on Ubuntu and on Windows, but I can't try it on Mac right now.

**Comment by zcbenz** [comment]
We should probably use sysroot for building x64 target by default, like ia32 and arm builds.

**Comment by zcbenz** [comment]
Closed with #4729.
