### ISSUE TITLE
Support for non-focusable toolbox/palette

### ISSUE THREAD

**Issue by romannurik** [atom/electron#4627]
It'd be great to see support for toolbox/palette-style windows that don't steal focus on click. Ideally these windows could still be interacted with but they wouldn't take focus from other apps. An example on OSX is Colors palette windows:

![image](https://cloud.githubusercontent.com/assets/100155/13375760/23eeff62-dd76-11e5-8ac1-e3e5a29f533c.png)

The docs for `win.setAlwaysOnTop` mention toolbox windows but there's no way to actually do that AFAICT:

> Sets whether the window should show always on top of other windows. After setting this, the window is still a normal window, not a toolbox window which can not be focused on.

**Comment by zcbenz** [comment]
I'm merging this to #2180.

**Comment by blakewatson** [comment]
Is this window type ever going to be available on macOS? I would like to make an onscreen keyboard for people with disabilities, but I need a non-focusable window in order for it to function properly.
