### ISSUE TITLE
OSX path issues

### ISSUE THREAD

**Issue by willwh** [atom/electron#4628]
* Electron version: v0.36.9
* Operating system: OSX 10.10.5

Hi Folks,

It seems that depending on how an electron app is loaded on OSX, will determine the $PATH available on app load, which is causing me some problems, and I'm hoping some others have some advice.

I'm trying to build a UI for [Drupal Console](https://drupalconsole.com/) (a CLI tool) using electron + shelljs.

My packaged app (I used [electron-packager](https://github.com/electron-userland/electron-packager)) works on all platforms when run with `npm start` or `open /Applications/dcapp.app`

My code is pretty straightforward at this point, but I am having real problems with the $PATH available to the application on OSX when it's loaded via Finder/double clicking the icon in /Applications

My app code is here: https://github.com/willwh/dcapp

Digging around, I did find this: https://github.com/sindresorhus/fix-path

This has helped somewhat, in that my [$PATH coming back over ipc](https://github.com/willwh/dcapp/blob/master/js/client.js#L13-L15) now looks like this:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`

However, Drupal console still doesn't seem to work in my app when loaded from finder.

It all works beautifully if I either:

`ln -s /usr/local/bin/drupal /usr/bin/drupal` or just run `open /Applications/dcapp.app`

Neither of these are ideal as the current Drupal Console docs suggest moving the binary to `/usr/local/bin/drupal`

I chimed in on an issue in [electron-userland/electron-packager](https://github.com/electron-userland/electron-packager/issues/183) - where I got some great advice and still didn't have success.

Does anyone have any advice on handling this stuff?

**Comment by zcbenz** [comment]
You can probably pass a explicit `env` option to `spawn` or `exec`, and see if works.

I'm closing this since it is not really a issue of Electron.
