### ISSUE TITLE
Load jQuery in preload script: type Error: cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by dude8** [atom/electron#4633]
I need to load jquery in the preload script of my app.
If i load `page.html`, there are no problems, but if i navigate to `other.html` loading jQuery failes with "Type Error: cannot read property 'createElement' of undefined".

```javascript
//preload.js
 "use strict";
console.log('called');
if(document)
    console.log("document!!!");
console.log(document);
window.$ = window.jQuery = require('jquery');
```

```javascript
//window settings
win = new BrowserWindow({
    width: width,
    height: height,
    resizable: false,
    maximizable: false,
    useContentSize: true,
    webPreferences: {
        preload: path.resolve('./preload.js'),
        nodeIntegration: false //doesn't matter if node integration turned off or on, same result
    }
});
```

page.hml
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="other.html">link</a>
</body>
</html>
```

other.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
```
loading page.html:
![image](https://cloud.githubusercontent.com/assets/11646216/13106347/08565b9e-d568-11e5-9ce7-0d26c52996fa.png)

loading other.html:
![image](https://cloud.githubusercontent.com/assets/11646216/13106314/d918eebe-d567-11e5-9100-ef719c62c2ff.png)

* Electron version: 0.36.7
* Operating system: Windows 7

**Comment by dude8** [comment]
The same error appears upon reloading the first page.

**Comment by positlabs** [comment]
What happens when you load jquery via script tag?

**Comment by zhou-yg** [comment]
once you "require("jquery")" ,the jquery code will execute in node env not in browser env.so that this error

**Comment by dude8** [comment]
loading jquery via the script tag is not an option, because i have no influence over the page i load, but it worked in previous versions with the script tag.

@zhou-yg yes, therefore i assign it to the window with:

```javascript
window.$ = window.jQuery = require('jquery');
```

as suggested [here](https://github.com/atom/electron/issues/254#issuecomment-42351776).

**Comment by zcbenz** [comment]
When the `preload` script is executed some essential DOM elements have not been created, and jQuery is not happy with that. You can probably delay the loading of jQuery until DOM is ready.

**Comment by f0rmiga** [comment]
Little late to the party, but I managed to load jQuery this way:

```javascript
window.onload = () => {
  const $ = require('jquery')
  console.log($('body div').length)
}
```

What I needed to do is just `require('jquery')` after the window loaded. Thanks @zcbenz, you have enlightened me.
