### ISSUE TITLE
showSaveDialog should replace extension when switching filters

### ISSUE THREAD

**Issue by ricardomatias** [atom/electron#4634]
This is a common feature seen throughout several editors (gimp, inkscape, etc.), that when the user switches a filter the file path gets updated with the new filtered extension. 
This is aimed at singular extensions and should be toggled on through the `options` object that `showSaveDialog` accepts. In the end, the method should also return the updated file path.

*Example:*
If the `showSaveDialog` is called with the file name `hello.foo` and then there's a filter for an extension called `bar`, the dialog should update the file name to `hello.bar` so the user can get a proper feedback to what type of file is he saving to.

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by ricardomatias** [comment]
Arch Linux. Should this be already working in other operating systems ?

**Comment by zcbenz** [comment]
This is a regression on Linux.

**Comment by ricardomatias** [comment]
I've downloaded 0.37.2 and it still has the same behavior as before. Is this functionality supposed to be working with other OS'es ?

**Comment by zcbenz** [comment]
I only implemented it on Linux. On other platforms this behavior is not expected in most apps as far as I know.

**Comment by bsivanov** [comment]
As of now (Electron 7.1.10), the extension chosen in the dialog is still (or again?) not added to the file name on Linux.
