### ISSUE TITLE
Moving from 0.36.7 => 0.36.9, `spyOn(dialog)` no longer works

### ISSUE THREAD

**Issue by bengotow** [atom/electron#4636]
Was trying to move N1 from Electron 0.36.7 to 0.36.9 this morning. Unfortunately, it breaks many of our specs. It may be a straightforward issue—maybe someone could shed some light on this.

It appears that this code no longer works as expected:

```
dialog = remote.require('dialog')

// jasmine 1.3 syntax - wraps dialog.showMessageBox
spyOn(dialog, "showMessageBox")

// run code which calls dialog.showMessageBox
```

For some reason, the calls to showMessageBox are reaching the original implementation (the spyOn line is not having any effect.) Maybe this is related to the caching added to the remote module?

**Comment by zcbenz** [comment]
I think that's because the members of remote objects are not configurable in 0.36.9.

Refs #4568.
