### ISSUE TITLE
Access showSaveDialog filters

### ISSUE THREAD

**Issue by armaldio** [atom/electron#4638]
* Electron version: 0.36.8
* Operating system: Linux - Xubuntu

Hello, 

Is it possible to access the showSaveDialog filters inside the callback function ?
I'm on linux and i want to append the extension at the end of the file on save but since there are multiples filters I dont' know how to determine which extension is selected.

Thanks !

**Comment by zcbenz** [comment]
No, there is no way to get the selected filter. But the filename will be appended with the extension automatically so there is no need to do it yourself.

**Comment by armaldio** [comment]
I'm on Linux and it's not appended automatically. 
Is it a bug, or am I doing something good wrong?

**Comment by zcbenz** [comment]
Which desktop environment are you using? And can you show how you are using showSaveDialog?

**Comment by armaldio** [comment]
I'm on Xubuntu / gdm / Gnome

```js
  var filepath = dialog.showSaveDialog({
    title: 'title',
    filters: [{
      name: 'Construct 2 Plugin File',
      extensions: ['c2p']
    }, {
      name: 'Archive',
      extensions: ['zip']
    }]
  }, function(path) {
      fs.writeFile(path, JSON.stringify(graph), function(err) {});
  });

```

**Comment by zcbenz** [comment]
This is a bug, I'm merging this to #4638.

**Comment by armaldio** [comment]
Thanks :)

**Comment by ainz-95** [comment]
Hi, this issue is still happening on Ubuntu.

* **Electron Version:** v8.2.0
* **Operating System:** Ubuntu 18.04.4 x64
```
const { canceled, filePath } = await electron.dialog.showSaveDialog({
  filters: [
    { name: 'JSON Files', extensions: ['json'] },
    { name: 'All Files', extensions: ['*'] },
  ],
});

if (canceled) {
  return;
}

console.log(filePath);
```

`filePath` doesn't contain any extension even if `JSON Files` filter is selected.

**Comment by flo00008** [comment]
- **Electron Version:** v8.4.1
- **Operating System:** Ubuntu 20.04.1

Issue is still not fixed I also tested the exactly same code above

**Comment by VanDeny** [comment]
- Electron Version: v22.0.8
- Operating System: Ubuntu 22.04.2 LTS


Issue still relevant, could anybody look into this?
