### ISSUE TITLE
Crach renderer process on trying load high resolution image

### ISSUE THREAD

**Issue by AndreySudarchikov** [atom/electron#4639]
* Electron version: 0.36.9
* Operating system: Windows 7, Windows 10  x86, 64

Renderer process (browserWindow) crash on load images with high resolution more than 8000x4000 px
files size makes no effect, file can be 5mb or 30mb it's doesn't matter
only thing is important is resolution.

reproduce the problem: open empty browserWindow and drag high res image file to window = crash!
try it yourself. works fine if drag image to Chrome, so i think the problem is in Electron itself
![bed_b](https://cloud.githubusercontent.com/assets/8150754/13412270/b4c1623e-df4a-11e5-8a89-1e98cfe67300.jpg)

 for our project It's very important, makes possible works with high res files.
Any suggestions would be appreciated 

Thanks in advance
Andrey

**Comment by zcbenz** [comment]
I'm closing this and reopening #1562.
