### ISSUE TITLE
Intermittent electron app crash - with backtrace pointing to RegexPattern::operator!=

### ISSUE THREAD

**Issue by chandrachivukula** [atom/electron#4640]
Tagging folks so this issue can get some feedback - Looking forward to finding how we can determine the next steps to isolate and fix this issue. @defunkt @Caged @schacon @bkeepers @jnunemaker 

* Electron version: v0.36.0
* Operating system: Win 10.0.10586

One of the hobby projects I am helping with is running into an intermittent electron crash when loading a web url (an internet facing url). I was able to capture the backtrace using following commands.
ELECTRON_ENABLE_LOGGING=true
ELECTRON_ENABLE_STACK_DUMPING=true
electron app --v=4

The BrowserWindow is navigating to a website that is app-cache enabled, and as you can see from the log-traces (below the stack trace) its actually completed the loading the manifest and seems to be executing the app code when it crashes. When this happens the electron app exits with code - Exit Status: -1073741819

I've seen similar stacktrace reported in chromium in 2012, but wasnt sure if its the same.

Backtrace:

rn::operator!= [0x01AC9479+23129]
        icu_54::RegexPattern::operator!= [0x01AC9B05+24805]
        icu_54::RegexPattern::operator!= [0x01AC94EB+23243]
        icu_54::RegexPattern::operator!= [0x01AC9B05+24805]
        icu_54::RegexPattern::operator!= [0x01AC94EB+23243]
        icu_54::RegexPattern::operator!= [0x01AC799E+16254]
        icu_54::RegexPattern::operator!= [0x01AC63D0+10672]
        icu_54::TimeZone::setID [0x006DF6BB+205371]
        icu_54::BreakIterator::isBufferClone [0x00629A08+513032]
        icu_54::BreakIterator::isBufferClone [0x006475E9+634857]
        icu_54::BreakIterator::isBufferClone [0x00648793+639379]
        GetHandleVerifier [0x00543A75+123653]
        (No symbol) [0x0050D87C]
        (No symbol) [0x0050CF59]
        GetHandleVerifier [0x00544C92+128290]
        GetHandleVerifier [0x0054555D+130541]
        (No symbol) [0x0050D670]
        icu_54::TimeZone::setID [0x007828BD+873533]
        icu_54::TimeZone::setID [0x007839B9+877881]
        icu_54::BreakIterator::isBufferClone [0x0069A70B+975115]
        icu_54::BreakIterator::isBufferClone [0x0061D85E+463454]
        icu_54::BreakIterator::isBufferClone [0x0061D70D+463117]
        icu_54::BreakIterator::isBufferClone [0x0061AB93+451987]
        (No symbol) [0x003C9FBD]
        icu_54::Transliterator::setID [0x0245FBCC+184572]
        BaseThreadInitThunk [0x75F738F4+36]
        RtlUnicodeStringToInteger [0x77625E13+595]
        RtlUnicodeStringToInteger [0x77625DDE+542]

-------------
verbose logs

[5424:0229/170733:INFO:CONSOLE(0)] "Creating Application Cache with manifest https://www.internetsite.com/myapps.appcache", source: https://www.internetsite.com/_ (0)
[5424:0229/170733:INFO:CONSOLE(0)] "Application Cache Checking event", source: https://www.internetsite.com/_ (0)
[5424:0229/170733:INFO:CONSOLE(0)] "Application Cache Downloading event", source: https://www.internetsite.com/_ (0)
[5424:0229/170733:INFO:CONSOLE(0)] "Application Cache Progress event (0 of 6) https://www.internetsite.com/min-691b86c7.js", source: https://www.internetsite.com/_ (0)
[5424:0229/170733:INFO:CONSOLE(0)] "Application Cache Progress event (1 of 6) https://www.internetsite.com/4750bfd1.js", source: https://www.internetsite.com/_ (0)
[5424:0229/170733:INFO:CONSOLE(0)] "Application Cache Progress event (2 of 6) https://www.internetsite.com/403d154f.css", source: https://www.internetsite.com/_ (0)
[5424:0229/170733:INFO:CONSOLE(0)] "Application Cache Progress event (3 of 6) https://www.internetsite.com/512f4f57.js", source: https://www.internetsite.com/_ (0)
[5424:0229/170734:INFO:CONSOLE(0)] "Application Cache Progress event (4 of 6) https://www.internetsite.com/ad708125.js", source: https://www.internetsite.com/_ (0)
[5424:0229/170735:INFO:CONSOLE(0)] "Application Cache Progress event (5 of 6) https://www.internetsite.com/06fea0c1.js", source: https://www.internetsite.com/_ (0)
[5424:0229/170735:INFO:CONSOLE(0)] "Application Cache Progress event (6 of 6) ", source: https://www.internetsite.com/_ (0)
[5424:0229/170735:INFO:CONSOLE(0)] "Application Cache Cached event", source: https://www.internetsite.com/_ (0)
[5424:0229/170737:INFO:CONSOLE(111)] "Detected schema version mismatch in localStorage current version:0.0.1, stored version:null; purging localStorage cache.", source: https://www.internetsite.com/min-691b86c7.js (111)
[5424:0229/170737:INFO:CONSOLE(111)] "Config: Primary preferred locale not supported, falling back to secondary", source: https://www.internetsite.com/min-691b86c7.js (111)
[5424:0229/170737:INFO:CONSOLE(111)] "pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.", source: https://www.internetsite.com/min-691b86c7.js (111)

[24328:0229/170737:INFO:systeminfo.cc(82)] Available number of cores: 6
[24328:0229/170737:VERBOSE1:child_thread_impl.cc(367)] Mojo is disabled on child
[17964:0229/170737:VERBOSE1:gles2_cmd_decoder.cc(2799)] GL_OES_packed_depth_stencil supported.
[24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
[24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
[24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(490)] shutdown event is signaled
[24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
**[24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(490)] shutdown event is signaled**
[24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
B[a24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
c[k24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
tr[a24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
ce[:24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends

[       i24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
c[u24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
_[524328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
4:[:24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
R[e24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
ge[x24328:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
P[a17964:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
t[[24328:0229/170738:VERBOSE1:statistics_recorder.cc(332)] Collections of all histograms
Histogram: Compositing.NumActiveLayers recorded 1 samples, average = 10.0 (flags = 0x1)
0   ...
10  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
14  ...

Histogram: Compositing.Renderer.DisplayListRecordingSource.UpdateInvalidatedAreaPerMs recorded 1 samples, average = 1745454.0 (flags = 0x1)
0        ...
1000000  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}

Histogram: Compositing.Renderer.DisplayListRecordingSource.UpdateUs recorded 1 samples, average = 176.0 (flags = 0x1)
0    ...
149  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
196  ...

Histogram: Compositing.Renderer.PictureMemoryUsageKb recorded 1 samples, average = 20.0 (flags = 0x1)
0   ...
16  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
21  ...

Histogram: Event.AggregatedLatency.Renderer2 recorded 2 samples, average = 241272.5 (flags = 0x1)
0       ...
209152  ------------------------------------------------------------------------O (1 = 50.0%) {0.0%}
244143  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
284987  ...

Histogram: Event.HitTest recorded 2 samples, average = 1.5 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 50.0%)
1  ...
3  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
4  O                                                                         (0 = 0.0%) {100.0%}

Histogram: Event.Latency.Renderer2.MouseMove recorded 2 samples, average = 241272.5 (flags = 0x1)
0       ...
209152  ------------------------------------------------------------------------O (1 = 50.0%) {0.0%}
244143  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
284987  ...

Histogram: Renderer.AcceleratedFixedRootBackground recorded 7 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (7 = 100.0%)
1  ...

Histogram: Renderer.DrawDuration recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: Renderer.DrawDurationOverestimate recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: Renderer.DrawDurationUnderestimate recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: Renderer4.GpuRasterizationEnabled recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: Scheduling.Renderer.ActivateDuration recorded 1 samples, average = 58.0 (flags = 0x1)
0   ...
53  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
60  ...

Histogram: Scheduling.Renderer.ActivateDuration.Overestimate recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: Scheduling.Renderer.ActivateDuration.Underestimate recorded 1 samples, average = 58.0 (flags = 0x1)
0   ...
53  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
60  ...

Histogram: Scheduling.Renderer.BeginMainFrameToCommitDuration recorded 2 samples, average = 334.0 (flags = 0x1)
0    ...
68   ------------------------------------------------------------------------O (1 = 50.0%) {0.0%}
77   ...
536  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
610  ...

Histogram: Scheduling.Renderer.BeginMainFrameToCommitDuration.Overestimate recorded 2 samples, average = 263.0 (flags = 0x1)
0    ------------------------------------------------------------------------O (1 = 50.0%)
1    ...
471  --------------O                                                           (1 = 50.0%) {50.0%}
536  ...

Histogram: Scheduling.Renderer.BeginMainFrameToCommitDuration.Underestimate recorded 2 samples, average = 298.5 (flags = 0x1)
0    ------------------------------------------------------------------------O (1 = 50.0%)
1    ...
536  --------------O                                                           (1 = 50.0%) {50.0%}
610  ...

Histogram: Scheduling.Renderer.CommitToReadyToActivateDuration recorded 2 samples, average = 11353.0 (flags = 0x1)
0      ...
191    ------------------------------------------------------------------------O (1 = 50.0%) {0.0%}
217    ...
20328  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
23147  ...

Histogram: Scheduling.Renderer.CommitToReadyToActivateDuration.NotUsedForEstimate recorded 1 samples, average = 22510.0 (flags = 0x1)
0      ...
20328  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
23147  ...

Histogram: Scheduling.Renderer.CommitToReadyToActivateDuration.Overestimate recorded 2 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ...

Histogram: Scheduling.Renderer.CommitToReadyToActivateDuration.Underestimate recorded 2 samples, average = 11255.0 (flags = 0x1)
0      ...
191    ------------------------------------------------------------------------O (1 = 50.0%) {0.0%}
217    ...
20328  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
23147  ...

Histogram: Scheduling.Renderer.DrawDuration recorded 1 samples, average = 143.0 (flags = 0x1)
0    ...
130  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
148  ...

Histogram: Scheduling.Renderer.DrawDuration.Overestimate recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: Scheduling.Renderer.DrawDuration.Underestimate recorded 1 samples, average = 143.0 (flags = 0x1)
0    ...
130  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
148  ...

Histogram: Scheduling.Renderer.PrepareTilesDuration recorded 3 samples, average = 42.0 (flags = 0x1)
0   ...
32  ------------------------------------------------------------------------O (1 = 33.3%) {0.0%}
36  ----------------------------------------------------------O               (1 = 33.3%) {33.3%}
41  ...
53  ----------------------------------------------------------O               (1 = 33.3%) {66.7%}
60  ...

Histogram: Scheduling.Renderer.PrepareTilesDuration.Overestimate recorded 3 samples, average = 7.0 (flags = 0x1)
0   ------------------------------------------------------------------------O (2 = 66.7%)
1   ...
19  ------------O                                                             (1 = 33.3%) {66.7%}
22  ...

Histogram: Scheduling.Renderer.PrepareTilesDuration.Underestimate recorded 3 samples, average = 18.0 (flags = 0x1)
0   ------------------------------------------------------------------------O (1 = 33.3%)
1   ...
15  ------------------------------------O                                     (1 = 33.3%) {33.3%}
17  ...
36  --------------O                                                           (1 = 33.3%) {66.7%}
41  ...

Histogram: TileManager.ExceededMemoryBudget recorded 3 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (3 = 100.0%)
1  ...

Histogram: V8.CompileMicroSeconds recorded 3 samples, average = 94.3 (flags = 0x1)
0    ...
28   ------------------------------------------------------------------------O (1 = 33.3%) {0.0%}
37   O                                                                         (0 = 0.0%) {33.3%}
49   -----------------------------------------t17964:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
[-e17964:0229/170738:VERBOSE1:ipc_sync_channel.cc(386)] Canceling pending sends
------------------------------O (1 = 33.3%) {33.3%}
65   ...
196  ------------------------------------------------------------------------O (1 = 33.3%) {66.7%}
258  ...

Histogram: V8.GCIdleNotification recorded 4 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (4 = 100.0%)
1  ...

Histogram: V8.GCIdleTimeAllottedInMS recorded 4 samples, average = 28.3 (flags = 0x1)
0   ...
11  ------------------------------------------------------------------------O (1 = 25.0%) {0.0%}
12  ...
16  ------------------------------------------------------------------------O (1 = 25.0%) {25.0%}
17  ...
36  ------------------------O                                                 (1 = 25.0%) {50.0%}
39  ...
49  ------------------O                                                       (1 = 25.0%) {75.0%}
53  ...

Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: V8.Initializer.OpenV8File.Result recorded 2 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ...

Histogram: V8.ParseLazyMicroSeconds recorded 5 samples, average = 34.0 (flags = 0x1)
0   ...
16  ------------------------------------------------------------------------O (2 = 40.0%) {0.0%}
21  O                                                                         (0 = 0.0%) {40.0%}
28  ------------------------------------O                                     (1 = 20.0%) {40.0%}
37  ------------------------------------O                                     (1 = 20.0%) {60.0%}
49  ------------------------------------O                                     (1 = 20.0%) {80.0%}
65  ...

Histogram: V8.ParseMicroSeconds recorded 3 samples, average = 136.3 (flags = 0x1)
0    ...
21   ------------------------------------------------------------------------O (1 = 33.3%) {0.0%}
28   ...
86   ------------------------------------------------------------------------O (1 = 33.3%) {33.3%}
113  ...
258  ------------------------------------------------------------------------O (1 = 33.3%) {66.7%}
340  ...

Histogram: WebCore.FeatureObserver recorded 2 samples, average = 26.0 (flags = 0x1)
0   ------------------------------------------------------------------------O (1 = 50.0%)
1   ...
52  ------------------------------------------------------------------------O (1 = 50.0%) {50.0%}
53  ...

Histogram: WebCore.ScriptController.clearForClose recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: WebCore.ScriptController.clearWindowProxy recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: WebFont.WebFontsInPage recorded 1 samples, average = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

**Comment by jnunemaker** [comment]
I'm not an electron developer, so I'm not sure I can help you. Pretty sure that atom team keeps track of these and should be by to respond soon.

**Comment by zcbenz** [comment]
Can you try latest version?

**Comment by zcbenz** [comment]
Closing until more information is provided.

**Comment by cretz** [comment]
I have a similar issue that occurs when I use my custom protocol accesses another server to proxy. Here is the stack trace for anyone else. It is going to take me a good bit of time to create a tiny reproducible test case for this.

```
Backtrace:
        icu_54::RuleBasedBreakIterator::operator!= [0x00007FF66094A602+9576962]
        icu_54::RuleBasedBreakIterator::operator!= [0x00007FF66094B5B4+9580980]
        (No symbol) [0x00007FF65F4896CC]
        icu_54::Calendar::weekNumber [0x00007FF660AE523F+18079]
        icu_54::Calendar::weekNumber [0x00007FF660AE3264+9924]
        icu_54::RuleBasedBreakIterator::operator!= [0x00007FF66094B633+9581107]
        icu_54::RuleBasedBreakIterator::operator!= [0x00007FF660A11B99+10393497]
        icu_54::RuleBasedBreakIterator::operator!= [0x00007FF660A15855+10409045]
        icu_54::Calendar::weekNumber [0x00007FF660B30CC1+327969]
        icu_54::Calendar::weekNumber [0x00007FF660B2E706+318310]
        GetHandleVerifier [0x00007FF65F596403+149411]
        (No symbol) [0x00007FF65F554A38]
        (No symbol) [0x00007FF65F553CC6]
        GetHandleVerifier [0x00007FF65F59778E+154414]
        GetHandleVerifier [0x00007FF65F59827B+157211]
        GetHandleVerifier [0x00007FF65F59DD08+180392]
        (No symbol) [0x00007FF65F554670]
        icu_54::BreakIterator::isBufferClone [0x00007FF65F6DCA5E+810574]
        icu_54::BreakIterator::isBufferClone [0x00007FF65F6DD41F+813071]
        (No symbol) [0x00007FF65F556436]
        (No symbol) [0x00007FF65F55F4C7]
        BaseThreadInitThunk [0x00007FFEBAF013D2+34]
        RtlUserThreadStart [0x00007FFEBB1954E4+52]
```

**Comment by raffaeler** [comment]
I have this problem too with version 1.4.13
I load a native plugin that works smoothly under node.exe in console.
The plugin is then rebuilt against Electron 1.4.13 of course.
The plugin is loaded from an Angular2 component constructor (typescript)

When I start electron under Windbg x64 the app crash with this stack:

```
2:029> kp
 # Child-SP          RetAddr           Call Site
00 00000087`027fb370 00007fff`3569d6e0 electron!icu_56::RegexPattern::operator!=+0x2374b8
01 00000087`027fb3a0 00007fff`359de40f node!v8::String::WriteUtf8+0x5540
02 00000087`027fb3d0 00007fff`359e1b40 node!uv_udp_set_ttl+0x166463
03 00000087`027fb400 00007fff`359f3328 node!uv_udp_set_ttl+0x169b94
04 00000087`027fb430 00007fff`356e2bfb node!uv_udp_set_ttl+0x17b37c
05 00000087`027fb800 00007fff`356e04e6 node!v8::String::WriteUtf8+0x4aa5b
06 00000087`027fb850 00007fff`356dccb5 node!v8::String::WriteUtf8+0x48346
07 00000087`027fbb30 00007fff`35c18ae9 node!v8::String::WriteUtf8+0x44b15
08 00000087`027fbb60 00000254`2550614b node!v8::experimental::FastAccessorBuilder::SetLabel+0xf8009
09 00000087`027fbb90 00000087`027fbbe0 0x00000254`2550614b
0a 00000087`027fbb98 000000fb`f7405f09 0x00000087`027fbbe0
0b 00000087`027fbba0 00007fff`35c18a5f 0x000000fb`f7405f09
0c 00000087`027fbba8 0000024d`fce99f00 node!v8::experimental::FastAccessorBuilder::SetLabel+0xf7f7f
0d 00000087`027fbbb0 00000087`027fbc10 0x0000024d`fce99f00
0e 00000087`027fbbb8 0000024d`fce99f00 0x00000087`027fbc10
0f 00000087`027fbbc0 00007fff`3560a38f 0x0000024d`fce99f00
10 00000087`027fbbc8 00000254`25506081 node!v8::Locker::IsLocked+0x85eff
11 00000087`027fbbd0 00000087`027fbb90 0x00000254`25506081
12 00000087`027fbbd8 00000003`00000000 0x00000087`027fbb90
13 00000087`027fbbe0 00000087`027fbc20 0x00000003`00000000
<cut>
```

A bit more details:
```
2:029> ~~[8de4]s;.frame 0n0;dv /t /v
electron!icu_56::RegexPattern::operator!=+0x2374b8:
00007ff7`3d869da8 80b89100000000  cmp     byte ptr [rax+91h],0 ds:00000000`00000092=??
00 00000087`027fb370 00007fff`3569d6e0 electron!icu_56::RegexPattern::operator!=+0x2374b8
```

And also:
```
(431c.8de4): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for electron.exe
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for electron.exe - 
*** WARNING: Unable to verify checksum for <cut>\node_modules\electron\dist\node.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for <cut>\node_modules\electron\dist\node.dll - 
electron!icu_56::RegexPattern::operator!=+0x2374b8:
00007ff7`3d869da8 80b89100000000  cmp     byte ptr [rax+91h],0 ds:00000000`00000092=??
```

Any ideas?
Thank you
