### ISSUE TITLE
electron-v0.36.7-mas-x64 is not MAS compatible

### ISSUE THREAD

**Issue by JamyGolden** [atom/electron#4641]
I'm opening a new issue because it seems like [issue 3823](https://github.com/atom/electron/issues/3823) is remaining closed.

I've submitted my app (with [electron-v0.36.7-mas-x64.zip](electron-v0.36.7-mas-x64.zip) build) for review and Apple failed it for the following reason:
> The use of non-public APIs can lead to a poor user experience should these APIs change in the future, and is therefore not permitted. The app includes ': xpc_mach_send_get_right' from the framework '/usr/lib/libSystem.B.dylib'.

* Electron version: 0.36.7
* Operating system: OS X 10.10.5

**Comment by zcbenz** [comment]
I'm merging this to #3871.
