### ISSUE TITLE
SQLite3 NodeJS native module - SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by joelpinheiro** [atom/electron#4644]
* Electron version: **0.35.1**
* Operating system: **darwin**

Hi all,

I'm trying to install correctly **SQLite3** which is a NodeJS module running above the old V8. I already adapt the **native module** to **Atom Shell** using ([Using Native Node Modules in Atom Shell](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#native-node-module-compatibility) ):
`npm install --save-dev electron-rebuild`
`npm install sqlite3`
`./node_modules/.bin/electron-rebuild`

But I receive the follow when I execute the app:
`A JavaScript error occurred in the main process`
`Uncaught Exception:
Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)`

My code in the **main process** is:
` app.get('/load_all_db', function (req, res) {
            var sqlite3 = require('sqlite3').verbose();
            var db = new sqlite3.Database('scripts_database');

            var posts = [];
            db.serialize(function() {
                
                var query = "SELECT script_name, lua_script, cloud_active, datetime, marketdata_list FROM scripts";
                
                console.log(query);
                
                db.each(query, function (err, row) {
                    posts.push({script_name: row.script_name, lua_script: row.lua_script, cloud_active: row.cloud_active, datetime: row.datetime, marketdata_list: row.marketdata_list})
                }, function() {
                    console.log(posts)
                    res.send(posts);
                })
            })
            
            db.close();
        });`

I have done this too (from: [Sqlite3 with Atom Shell](http://verysimple.com/2015/05/30/using-node_sqlite3-with-electron/):
`cd node_modules/sqlite3`
`npm run prepublish`
`node-gyp configure --module_name=node_sqlite3 --module_path=../lib/binding/node-v47-darwin-x64`
`node-gyp rebuild --target=0.36.1 --arch=x64 --target_platform=darwin --dist-url=https://atom.io/download/atom-shell --module_name=node_sqlite3 --module_path=../lib/binding/node-v47-darwin-x64`

The **SQLITE_CANTOPEN error** code is always present in **every attempt**.

**Comment by joelpinheiro** [comment]
The code above works fine running Electron from the command-line but open the app after running it with electron-packager produces the error.

`electron-packager . iTrading --platform=darwin --arch=x64 --version=0.35.6 --icon /Users/joelpinheiro/Downloads/x.icns --overwrite`
`Packaging app for platform darwin x64 using electron v0.35.6`
`Wrote new app to /Users/joelpinheiro/Dropbox/iTrading/electron_app/iTrading-darwin-x64
`

**Comment by zcbenz** [comment]
That error means the module is unable to open the database file passed by you.

**Comment by nirajmchauhan** [comment]
I am facing the same issue, what should be the sqllite DB path?

**Comment by dcrystalj** [comment]
I cannot think about app without database. But here in electron world looks like you don't need it because no one is talking about it. Why there is no documentation or easy way to persist data in normal database like sqlite. Wath path do i have to specify to ```fs``` so after packaged app so it will be accessible?

**Comment by nirajmchauhan** [comment]
Try this code, it works for me in my electron app


```
const path = require('path');
const dbPath = path.resolve(__dirname, 'database.db')
var db = new sqlite3.Database(dbPath);
```

**Comment by mcscholtz** [comment]
In case anyone else run into this issue and the above solution by nirajmchauhan does not work. Try to use the absolute OS path e.g:

`var db = new sqlite3.Database('/home/msc/Documents/project/src/db/store.db');`

This is the only way I could get it to work. Should probably store the path in a config file somewhere.

**Comment by lencshu** [comment]
The problem is because the the working directory is where the .exe file executes
so,
Here is my solution:
After the packing, find the file where we define the path of database, usually change it to
`/resources/app/yourDatabaseDirName/yourDB.db`

My example:
Former path
'./Database/DataAdas.db'
to
'./resources/app/Database/DataAdas.db'

Done !

**Comment by yosiasz** [comment]
in my case, electron app, I had a seed.js script to seed my database and it was in same folder as

```
.\db\seeds.js
.\db\database.db
``
so the following did work. user console.log to verify/
```
console.log('__dirname', __dirname)
const path = require('path')
const sqlite3 = require('sqlite3').verbose();

const dbPath = path.resolve(__dirname, 'sedule.db');
const db = new sqlite3.Database(dbPath)
```

**Comment by yosiasz** [comment]
In my case this worked 

const path = require('path');
const dbPath = path.resolve(__dirname, 'database.db')
var db = new sqlite3.Database(dbPath);

but I also had to uninstall the installed version of my app using Control Panel in Windows.

**Comment by dijux** [comment]
After trying above suggested solutions, I wanted to ship a db bundled with the app and not create one at lunch of the app, so the perfect solution that I founded is to use [extraRessouces ](https://www.electron.build/configuration/contents#extrafiles) in your package.json and then use [process.resourcesPath](https://www.electronjs.org/docs/api/process#processresourcespath-readonly). here is the snippets for the packages.json and config example. 

```
# packages.json
"build": {
    ...
    "extraResources": [
      "databaseFolder"
    ],
   ...
}
```

```
// connection to db
const knex = require('knex')
const path = require('path')
const config = {
    client: 'sqlite3',
    connection: {
        filename: path.resolve(process.resourcesPath,  'databaseFolder/database.db3')
    },
    useNullAsDefault: true
}

const db = knex(config)

```

**Comment by wenjoy** [comment]
I was tipped by this awesome solution but I not made it with the exactly way, instead, I used forge like below:
NOTE: in my case it's `extraResource` instead of `extraResources`

```typescript
//forge.config.ts
  packagerConfig: {
    asar: true,
    extraResource: ['databaseFolder', 'excelFolder'],
  },

```

> After trying above suggested solutions, I wanted to ship a db bundled with the app and not create one at lunch of the app, so the perfect solution that I founded is to use [extraRessouces ](https://www.electron.build/configuration/contents#extrafiles) in your package.json and then use [process.resourcesPath](https://www.electronjs.org/docs/api/process#processresourcespath-readonly). here is the snippets for the packages.json and config example.
> 
> ```
> # packages.json
> "build": {
>     ...
>     "extraResources": [
>       "databaseFolder"
>     ],
>    ...
> }
> ```
> 
> ```
> // connection to db
> const knex = require('knex')
> const path = require('path')
> const config = {
>     client: 'sqlite3',
>     connection: {
>         filename: path.resolve(process.resourcesPath,  'databaseFolder/database.db3')
>     },
>     useNullAsDefault: true
> }
> 
> const db = knex(config)
> ```
