### ISSUE TITLE
Flicker after hidden window focus

### ISSUE THREAD

**Issue by antelle** [atom/electron#4645]
Hello!

Is it possible to force window re-render while it's in background / hidden by another window?

Minimalistic example:
```html
<script>
    setTimeout(function() { document.body.style.background = 'green'; }, 3000);
</script>
<body style="background: red">
```

1. start the app
2. switch to another window with ⌘⇥
3. wait for 5 seconds
4. return to the app with ⌘⇥

actual: red background flicker
expected: green background

I understand that for most cases it is suitable. But is there any way to force render while the app window is in background? 

* Electron version: v0.36.9
* Operating system: Mac OS X 10.11.3

**Comment by zcbenz** [comment]
I can reproduce the same bug in Chrome browser, I think there is probably an optimisation that delays the rendering of hidden window, but I can not find related code or issues.

I suggesting reporting this to Chromium's issues list or seeking help from the chromium-dev mailing list instead, because the rendering is completely on Chromium's side and there is nothing we can do in Electron.

**Comment by antelle** [comment]
Yes, it's common for browsers.
This is not a bug of browser, as browser matches user expectations: it's not active - it doesn't consume resources.
But, as we're building desktop apps here, there should be a possibility to invalidate a background in some way, e.g. just erase it.

**Comment by zcbenz** [comment]
I agree we can provide a way to force the painting, but as far as I know there is no public API to do that.

**Comment by antelle** [comment]
Hm, yes, using libchromiumcontent, this may be tricky or impossible at all.
It might be helpful, to have a function which will clear the window, e.g. fill it with background color, specified by the app, to erase some information which would not be visible on app focus next time?

**Comment by JerryGoyal** [comment]
I've fixed this issue by using setTimeout() method. I give a very small timeout of 100ms which is not noticiable but works like a charm. An example:
setTimeout(function(){
        let point = electron.screen.getCursorScreenPoint();
        clipboardWindow.setPosition(point.x + 20, 20, false);
    }, 100);
})

Not the best solution but thought this would be helpful for other.
