### ISSUE TITLE
Callback for executeJavascript in webview not working

### ISSUE THREAD

**Issue by AllanVieira** [atom/electron#4647]
Hello.

I'm trying to run a callback to a javascript function sent for execution in a webview.

The function should work below?

`browserWB.executeJavaScript('console.log("hello world")', function(){console.log ('finish')})`

The function is executed successfully, but no callback.

* Electron version:
0.36.9
* Operating system:
Fedora 22 64bit

**Comment by deepak1556** [comment]
callback support is not available in v0.36.9, please wait for the next release. Thanks!

**Comment by AllanVieira** [comment]
Great.

I'm currently using setTimeout and preload, but I have problems at different internet speeds.

  In the case of the call below, which will be executed first, console.log ('hello world') in the webview or callback function?

`browserWB.executeJavaScript('setTimeout(function(){console.log("hello world")}, 3000)', function(){console.log ('finish')})`

Thank you

**Comment by deepak1556** [comment]
callback will be called once script evaluation completes. So in your case `finish` will be printed in the embedders' context before `hello world` in the webview context.

**Comment by AllanVieira** [comment]
Thanks :)

Not sure if this will help me solution: /

There is how to run webview executeJavaScript in the same context that the preload?
