### ISSUE TITLE
Request Origin

### ISSUE THREAD

**Issue by jingweno** [atom/electron#4649]
* Electron version: 0.36.9
* Operating system: Any

I'm trying to talk to a server with Ajax but meeting https://en.wikipedia.org/wiki/Cross-origin_resource_sharing. The server checks any request for its origin. It's a 3rd party service, so I won't be able to change code to ignore this. But I'm able to add domain to whitelist. Is there a way for Electron to send requests with a specified origin?

**Comment by deepak1556** [comment]
You can use the [session.webRequest](https://github.com/atom/electron/blob/master/docs/api/session.md#seswebrequest) api to modify headers related to a request.

**Comment by kevinsawicki** [comment]
@deepak1556 Thanks for the link, closing this out as answered.
