### ISSUE TITLE
Failed window store certification

### ISSUE THREAD

**Issue by emilfrolov** [atom/electron#4650]
* Electron version: v0.36.8
* Operating system: windows

### Windows store doesn't allow us to pass certification. We would like to understand what we should exactly change to pass the certification process

**Error Found: The app manifest test detected the following errors:**
> The contrast ratio of the background color and foreground text color is 1. This ratio should be greater than or equal to 1.5.

**Error Found: The binary analyzer test detected the following errors:**
> File Beeline.Music.exe has failed the AppContainerCheck check.
> File d3dcompiler_47.dll has failed the AppContainerCheck check.
> File ffmpeg.dll has failed the AppContainerCheck check.
> File libEGL.dll has failed the AppContainerCheck check.
> File libGLESv2.dll has failed the AppContainerCheck check.
> File msvcp120.dll has failed the AppContainerCheck check.
> File msvcr120.dll has failed the AppContainerCheck check.
> File node.dll has failed the AppContainerCheck check.
> File pdf.dll has failed the AppContainerCheck check.
> File vccorlib120.dll has failed the AppContainerCheck check.
> File xinput1_3.dll has failed the AppContainerCheck check.
> File xinput1_3.dll has failed the DBCheck check.
> File xinput1_3.dll has failed the ExecutableImportsCheck check.
> Impact if not fixed: If the app doesn’t use the available Windows protections, it can increa

**Error Found: The platform appropriate files test detected the following errors:**

> File Beeline.Music.exe is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File d3dcompiler_47.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File ffmpeg.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File libEGL.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File libGLESv2.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File msvcp120.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File msvcr120.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File node.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File pdf.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File vccorlib120.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.
> File xinput1_3.dll is designed only for x64 processor type; AppX manifest declares 'ProcessorArchitecture' as neutral.

**Error Found: The supported APIs test detected the following errors:**

> API CryptAcquireContextW in advapi32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API CryptGenRandom in advapi32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API CryptReleaseContext in advapi32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API CreateEventW in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API CreateSemaphoreW in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API GetConsoleScreenBufferInfo in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API GetModuleHandleW in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API GetProcessAffinityMask in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API GetStdHandle in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API InitializeCriticalSection in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API SetConsoleTextAttribute in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API Sleep in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API WaitForSingleObject in kernel32.dll is not supported for this application type. ffmpeg.dll calls this API.
> API FreeAddrInfoW in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API GetAddrInfoW in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API GetNameInfoW in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSADuplicateSocketW in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSAGetLastError in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSAIoctl in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSARecv in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSARecvFrom in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSASend in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSASendTo in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSASetLastError in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSASocketW in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API WSAStartup in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API __WSAFDIsSet in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API bind in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API closesocket in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API connect in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API gethostname in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API getpeername in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API getsockname in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API getsockopt in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API htonl in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API htons in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API inet_addr in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API ioctlsocket in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API listen in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API ntohl in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API ntohs in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API recv in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API recvfrom in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API select in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API send in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API setsockopt in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API shutdown in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API socket in ws2_32.dll is not supported for this application type. node.dll calls this API.
> API CreateCompatibleBitmap in gdi32.dll is not supported for this application type. node.dll calls this API.
> API DeleteObject in gdi32.dll is not supported for this application type. node.dll calls this API.
> API GetDIBits in gdi32.dll is not supported for this application type. node.dll calls this API.
> API GetDeviceCaps in gdi32.dll is not supported for this application type. node.dll calls this API.
> API GetObjectW in gdi32.dll is not supported for this application type. node.dll calls this API.
> API CryptAcquireContextW in advapi32.dll is not supported for this application type. node.dll calls this API.
> API CryptGenRandom in advapi32.dll is not supported for this application type. node.dll calls this API.
> API CryptReleaseContext in advapi32.dll is not supported for this application type. node.dll calls this API.
> API DeregisterEventSource in advapi32.dll is not supported for this application type. node.dll calls this API.
> API InitializeSecurityDescriptor in advapi32.dll is not supported for this application type. node.dll calls this API.
> API OpenProcessToken in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegCloseKey in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegEnumKeyExW in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegOpenKeyExA in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegOpenKeyExW in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegQueryValueExA in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegQueryValueExW in advapi32.dll is not supported for this application type. node.dll calls this API.
> API RegisterEventSourceW in advapi32.dll is not supported for this application type. node.dll calls this API.
> API ReportEventW in advapi32.dll is not supported for this application type. node.dll calls this API.
> API SetSecurityDescriptorDacl in advapi32.dll is not supported for this application type. node.dll calls this API.

**Comment by felixrieseberg** [comment]
For now, Electron will not pass the Windows Store Certification - and there's sadly nothing you can do about that (yet). We at Microsoft are aware that a bunch of really cool apps running Electron could do well in the store, but we don't have anything just yet.
