### ISSUE TITLE
[Windows] shell.openExternal with Firefox as default browser not always getting focus

### ISSUE THREAD

**Issue by nantas** [atom/electron#4651]
* Electron version: v0.36.4
* Operating system: Windows 7/8.1

If Firefox is up and running, `shell.openExternal` will open a tab in Firefox but neither the browser window nor the newly opened tab get focused.

if Firefox is not running, `shell.openExternal` will open new Firefox window and focus the tab correctly.

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! I'm not sure that this is actually a bug in Electron - Electron just calls `shellExecute` with an `open` parameter, there's really no more basic way to open a URL in Windows. 

What is your experience if you attempt to click on a link from other apps?

**Comment by zcbenz** [comment]
Closing until more information is provided.
