### ISSUE TITLE
Programmatically set BrowserWindow frame property

### ISSUE THREAD

**Issue by feross** [atom/electron#4652]
I want to programmatically set the `BrowserWindow`'s `frame` property *after* the window has already been created.

For example: 

```js
var win = new electron.BrowserWindow({ frame: true })
// ... some time goes by
win.setFrame(false)
// ... some time goes by
win.setFrame(true)
```

Is there any way to do this with electron? Can we add this?

**Comment by zcbenz** [comment]
No, it is not possible on most platforms.

**Comment by feross** [comment]
It is possible on OS X. Any chance it could be added just for OS X, like the other OS X specific frame stuff

**Comment by ChrisMorrisOrg** [comment]
+1, QuickTime does this. It would be beneficial for video playback apps being built in Electron.
