### ISSUE TITLE
About menu not working in Windows & Ubuntu

### ISSUE THREAD

**Issue by vapits** [atom/electron#4653]
* Electron version: 0.36.8
* Operating system: Windows (ANY) + Ubuntu (ANY)

So the about menu with the specific selector provides an error in both Windows and Ubuntu OS.
On OSX it's ok.

![image](https://cloud.githubusercontent.com/assets/8594758/13463468/a0128d98-e08c-11e5-9201-8a99f10ecd8e.png)

The
```
{
        label: 'MyApp',
        submenu: [{
            label: 'About',
            selector: 'orderFrontStandardAboutPanel:'
        },
        {
            label: 'Quit',
            accelerator: 'CmdOrCtrl+Q',
            click: function() {
                force=true;
                app.quit();
            }
        }
        ]
    }
```

All other options on menu are working correctly.

any ideas?

**Comment by KevinMartin** [comment]
The About menu is a feature only natively supported in OS X. It is something provided by OS X and taken advantage of by Electron.

You can also check the Electron docs for [Menu.sendActionToFirstResponder(action)](https://github.com/atom/electron/blob/master/docs/api/menu.md#user-content-menusendactiontofirstresponderaction-os-x) which is the function that's being referenced in the error.

You should also check out the [Notes on OS X Application Menu](https://github.com/atom/electron/blob/master/docs/api/menu.md#user-content-notes-on-os-x-application-menu).

**Comment by zcbenz** [comment]
Closing since it has been answered.
