### ISSUE TITLE
Windows autoUpdater tutorial

### ISSUE THREAD

**Issue by jpost** [atom/electron#4654]
* Electron version: 0.36.0
* Operating system: Windows

I'm trying to make autoUpdating work on my Electron app, which will only be distributed on Windows.

Regarding the autoUpdater module for Windows, the Electron documentation says "The server-side setup is also different from OS X. You can read the documents of Squirrel.Windows to get more details."

But I've spent hours looking at the [Electron documentation](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md) and the [Squirrel.Windows documentation](https://github.com/Squirrel/Squirrel.Windows), and even looking at the source code of Electron, and I still do not even know where to begin.

Could someone create a basic tutorial for integrating the autoUpdater for a Windows app, from beginning to end?

The really important questions for me are the following: For the autoUpdater.setFeedURL(url) call, what should that url point to? What should be located at that URL? Files? Which files and what should they contain and how do I make them?

The Squirrel Windows documentation seems to be (understandably) very geared for developing in Visual Studio/.Net, so I'm not sure what parts of the process will stay the same when integrating with Electron, and which will need to be changed.

Edit:
I should add that I have successfully used the [grunt-electron-installer](https://github.com/atom/grunt-electron-installer) to create an installer for my app. And I've successfully integrated with Squirrel (in order to create create the app's shortcuts, for example). So, given that I already have this level of integration with Squirrel completed, what is required to get the auto updates working?

**Comment by paulcbetts** [comment]
> So, given that I already have this level of integration with Squirrel completed, what is required to get the auto updates working?

All you have to do is take that folder that gets generated and serve it up on S3 - the `setFeedURL` method should point to that folder on S3 (i.e. not to any one file, to the folder containing the files)

**Comment by jpost** [comment]
That worked great - my app is now downloading and automatically installing updates as expected. Need to finish handling the update events well in my app, but I am now off and running.

**Comment by paulcbetts** [comment]
:sparkles: :sparkles: :sparkles:

**Comment by 756613351** [comment]
i agree with you @jpost
