### ISSUE TITLE
Cannot Run Quick Start - error 404 during download

### ISSUE THREAD

**Issue by sergiotomasello** [atom/electron#4655]
* Electron version:
* Operating system: OSX 10.10.5

I tried the [quick start](http://electron.atom.io/#get-started) but i've got an error during `npm install` when it tried to download a file:

```
> electron-prebuilt@0.36.9 postinstall /Users/sergio/Documents/Test/electron-quick-start/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.36.9-darwin-ia32.zip
Error: GET https://github.com/atom/electron/releases/download/v0.36.9/electron-v0.36.9-darwin-ia32.zip returned 404

/Users/sergio/Documents/Test/electron-quick-start/node_modules/electron-prebuilt/install.js:22
  throw err
        ^
Error: GET https://github.com/atom/electron/releases/download/v0.36.9/electron-v0.36.9-darwin-ia32.zip returned 404
```

**Comment by kevinsawicki** [comment]
@sergiotomasello are you on a 32-bit Mac OS X machine?

It looks like it generated a 32-bit download link and unfortunately only 64-bit builds are available for Mac OS X.

**Comment by sergiotomasello** [comment]
@kevinsawicki thanks for the quick reply. I have a mac book pro with an Intel Core i5, so 64bit.
```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro11,1
Processor Name:	Intel Core i5
Processor Speed:	2,6 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	3 MB
Memory:	8 GB
```
my node version is `v0.10.38`
running the `process` command with node I've got that my architecture is ia32:
```bash
sergio@MacBook-Pro-di-Sergio build (development) $ node
> process
{ title: 'node',
  version: 'v0.10.38',
  moduleLoadList: 
   [ 'Binding evals',
....
....
     modules: '11',
     openssl: '1.0.1m' },
  arch: 'ia32',
  platform: 'darwin',
  argv: [ 'node' ],
  execArgv: [],
  env: 
   { TERM_PROGRAM: 'Apple_Terminal',
     SHELL: '/bin/bash',
....
....

```
any ideas?

**Comment by kevinsawicki** [comment]
Could you try installing the latest node LTS version and see if it reports a different arch? Not really sure what is going on here, really strange.

**Comment by kevinsawicki** [comment]
I downloaded 0.10.38 32-bit on Mac and it appears to report `ia32` for `os.arch()` which is what `electron-download` uses.

If you download any version of 64-bit node this problem should go away.

**Comment by kevinsawicki** [comment]
Closing this out.

The error message in future releases will be more specific about what failed to download.

**Comment by sergiotomasello** [comment]
I was running a 32bit node version. Changing it to a 64bit version I solved the problem. Thank you @kevinsawicki :+1:
