### ISSUE TITLE
Not all session entries are saved (for Google API)

### ISSUE THREAD

**Issue by beshur** [atom/electron#4657]
* Electron version: 0.36.6
* Operating system: Ubuntu 14.x

Hi.

I'm working on a project using Google Drive API.
In our Electron application I get the window asking for permissions every time I load [https://apis.google.com/js/api.js](https://apis.google.com/js/api.js). As I understand it opens a new window in case the token is not detected on the session. I'm new to Electron and not sure what can we control when opening a new window with a scripts - if there are special options for persisting session etc. 

So it saves credentials, I don't need to enter them every time, but the window asking for access to files is shown.
I noticed that our web application (which is loaded into Electron) has session stuff from docs.google.com and accounts.google.com, but Electron only saves the session for docs.google.com.

This is not the same as #4304.

Thanks.

**Comment by zcbenz** [comment]
Can you provide an example app? Electron should behave exactly the same with Chrome on session behaviour.

**Comment by zcbenz** [comment]
Closing until more information is provided.
