### ISSUE TITLE
<webview> tag with `nodeintegration` on require('electron') returns `undefined`

### ISSUE THREAD

**Issue by xieranmaya** [atom/electron#4658]
* Electron version:0.36.8
* Operating system:Windows 7
![image](https://cloud.githubusercontent.com/assets/2993947/13493712/9ebe029e-e17a-11e5-85ce-86444f2ec986.png)

**Comment by xieranmaya** [comment]
Acturally, require will return undefined when you require anything

**Comment by zcbenz** [comment]
Can you provide a reproducible example?

**Comment by xieranmaya** [comment]
The <webview> is loading an online page which I'm `require` in the console, I'll give you a example on Monday, Thank you~

**Comment by xieranmaya** [comment]
I've found the problem, it's because the hosted page defined a `require` function, is there any way to change the electron `require`'s name?

**Comment by zcbenz** [comment]
You can find a solution in http://electron.atom.io/docs/v0.36.8/faq/electron-faq/#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron.

**Comment by xieranmaya** [comment]
Thank you very much~

**Comment by xieranmaya** [comment]
@zcbenz Sorry to bother, but I have another question, what if the page in the webview navigated and the latter page(likely a logedin page) rewrited a `require` and I want to run some script to save node's `require` before the page's any JS starts to run? I've tried the webview's events but none of those can supply my needs.
