### ISSUE TITLE
mainWindow.loadURL() ends in location.href being chromewebdata

### ISSUE THREAD

**Issue by gbaumgart** [atom/electron#4660]
* Electron version:
latest
* Operating system:
windows-7/x32

Hi,
the second time i load an url http://0.0.0.0.... it ends up blank, when running console.log(location.href) it gives me some "chromwebdata"

How can i fix this? I have a preload html from file, when all ready (internal servers started over child_process), it should redirect to another url. 

Is this a bug?

**Comment by paulcbetts** [comment]
Chrome is trying to tell you in a very non-obvious way that navigation to this URL failed for some reason.

**Comment by gbaumgart** [comment]
ru.ning openItem with same url runs fine in an external browser.

**Comment by gbaumgart** [comment]
and if i load that url directly the first time, its all fine too. really weird.
