### ISSUE TITLE
setPosition with computers that have app scaling has odd results with the Position set.

### ISSUE THREAD

**Issue by molster** [atom/electron#4661]
This is an issue with 33.9 and latest 36.9

We have an overlay that we position over another application. This works fine until you come to a computer that has app scaling set to say 150% for example. If the window you are looking at is at position 1200, setting the electron's window position to 1200 will set it off the screen ( due to 150% app scaling effecting the position) 

It would be nice if there was a built in method for setPosition that converts it to real cords based on the scale the user has their comp set to. Luckily we have another app sending window information, so we can get the users scale settings inside that app from the OS, and dynamically change the position cords ourselves for now, but would be great if this was built into electron.

edit: it looks like you CAN calculate this just on the electron side using https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframesetzoomfactorfactor various methods here, get the scale factor, and then divide all your setPositions by the scale factor.

I think think it would be nice to have a setPosition with this built in, however im fine with this being closed if this is not an ideal add.

edit 2: looks like my edit 1 was not correct. using the webFrame only gives you scale changes if you have set it for the app itself, so the issue is still an issue, take back the optional close ;)

**Comment by zcbenz** [comment]
I'm merging this to #3057, once it is implemented you should be able to calculate this.

**Comment by dimdimdimdim** [comment]
For the future readers: the position can be calculated using

require('screen').getPrimaryDisplay().scaleFactor

However, another problem then arises: the position will not be exactly right, and may be one or two pixels off, due to rounding inaccuracies. See https://github.com/electron/electron/issues/10659.
