### ISSUE TITLE
Accelerator for "printscreen" key

### ISSUE THREAD

**Issue by mradionov** [atom/electron#4663]
* Electron version: 0.36.9
* Operating system: Ubuntu 14.04

Currently it is not possible to bind global shortcut for print screen key.
I've found that it has a defined constant in:

https://github.com/atom/electron/blob/v0.36.9/atom/common/keyboard_util.cc#L94

but it's actually never used in a condition which identifies registered key:

https://github.com/atom/electron/blob/v0.36.9/atom/browser/ui/accelerator_util.cc#L62

Is there any reason "printscreen" key is not present in this check? Thanks.

**Comment by mradionov** [comment]
Great, thank you!

**Comment by dmfarcas** [comment]
@mradionov @zcbenz , does this work for you now? It doesn't seem to work on KDE + ArchLinux.

```
    globalShortcut.register('PrintScreen', () => {
      console.log('Say cheese!');
    });
```

This doesn't work for example, but other keyboard shortcuts register fine. Is there a problem between the chair and the keyboard or is the issue still here?

**Comment by AdityaDinesh** [comment]
I have the same problem. PrintScreen doesn't work on Windows OS

**Comment by McPo** [comment]
Its also doesn't appear to work on OSX either. Allow it might be worth clarifying that Im using the normal printscreen combination for OSX cmd+shift+3, and not a printscreen button on a keyboard.

Would be handy to have the printscreen key event launch when any valid combination is used. This may require reading the preferences on each system to determine the users chosen key combination. At the moment Command+Shift+3 works but the user could change it.

**Comment by MarshallOfSound** [comment]
> Allow it might be worth clarifying that Im using the normal printscreen combination for OSX cmd+shift+3, and not a printscreen button on a keyboard.

Yeah, that isn't the printscreen keycode.  That's a combination of 3 different keycodes.  You can listen for that accelerator by listening for `Command+Shift+3`.  It wouldn't make sense for that to be considered "PrintScreen" as "PrintScreen" is actually it's own physical key.

**Comment by 1001v** [comment]
Still doesn't work on linux.

**Comment by arku31** [comment]
Still doesn't work. Guys, did you find any solution or dirty hacks?

**Comment by 0length** [comment]
> I have the same problem. PrintScreen doesn't work on Windows OS

me too.. it is happen when upgrade my electron version..
