### ISSUE TITLE
browserplugin object height does not expand to fill <webview>, when <webview> is used in Flexible Box (flexbox) layout

### ISSUE THREAD

**Issue by christoth** [atom/electron#4664]
The browserplugin object width expands as expected when <webview> is used within a flexbox layout, but the height stays fixed at 150px - the height of the browserplugin object should also expand to the height of the parent <webview>.
* Electron version: 0.36.9
* Operating system: Windows 7 x64, Windows 10 x64

**Comment by zcbenz** [comment]
This is a duplicate of #3948.
