### ISSUE TITLE
Auto Updater Error: Download Fails

### ISSUE THREAD

**Issue by jayalfredprufrock** [atom/electron#4668]
I have been integrating electron's auto update support and have made it pretty far but can't seem to get it entirely working. I am receiving the "checking-for-update" and "update-available" events and have verified that the download url returned by my feedUrl works, however before the file actually downloads I get an error event with the message "Update download failed: (null)"

I should mention a few things about my url that could be a factor:

1. Uses http://   - I found some older issues where this was causing a problem, although the error message was quite different and sounded like it got fixed.

2. The url consists of an IP, port, and query string variable
    i.e. http://xxx.xxx.xxx.xxx:1234?filetype=zip

Could any of this be causing the problem? If not, any other ideas?

* Electron version: 0.36.7
* Operating system: OSX 10.11.3

**Comment by pauliusuza** [comment]
I also see the same behavior on ﻿Electron version: 0.36.9
Error: Update download failed: (null)

**Comment by zcbenz** [comment]
Since the autoUpdater still works fine in Atom, I have to assume there is probably something wrong with your server. Can you try whether a local server would work?

**Comment by jayalfredprufrock** [comment]
A local server worked so it sounds like you're right. You can go ahead and close this out.
