### ISSUE TITLE
Checking document.hidden blocks browser needlessly

### ISSUE THREAD

**Issue by ArekSredzki** [atom/electron#4669]
* Electron version: v0.36.9
* Operating system: ALL

Currently getting document.hidden needlessly calls ipcRenderer.getSync().

This causes unacceptable blocking delays the browser process.
Very popular frameworks (ex. angular) often check this value, and thus this really slows things down, even if the main process **isn't** processing anything.

Instead this should remain a cached value as it only changes onEvent anyway.

**Comment by zcbenz** [comment]
I'm merging this to #3788, since fixing it would also solve this.

**Comment by ArekSredzki** [comment]
@zcbenz I've been looking into this issue further, and I believe it's rooted deeper in the design of electron's browser-side state storage.  The way that it is implemented now there is a lot of dependency on the main process for simple state queries. Instead the renderer process should cache and mirror the state of the main process, updating it via asynchronous messaging.

I'm interested in hearing your thoughts on this, and would be open to implementing the changes.

**Comment by zcbenz** [comment]
We can change it to the way that when window is minimised or hidden a message would be sent to renderer process to toggle the `document.hidden` state.

**Comment by ArekSredzki** [comment]
@zcbenz I just submitted a PR which addresses this issue. perhaps you have some advice on how best to implement it though.
