### ISSUE TITLE
Chrome 49

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron#4671]
Is there any schedule when to upgrade to Chrome 49?

**Comment by bbondy** [comment]
++ it is available and v47 security vulnerabilities will be disclosed soon.

**Comment by havenchyk** [comment]
@herrmannplatz @bbondy please, read http://electron.atom.io/docs/latest/faq/electron-faq/#when-will-electron-upgrade-to-latest-chrome

**Comment by zhulik** [comment]
Yeah, waiting for new chromium smooth scroll in atom on linux!

**Comment by herrmannplatz** [comment]
@havenchyk Thanks for the hint, i am aware of that. Since there were some issues in past, for example with 46 and also 48 was skipped, i was wondering if there might be any concerns against 49.

**Comment by bbondy** [comment]
@havenchyk I think this question is warranted given that we're already a month and a half beyond the 48 that was supposed to happen and the FAQ says within 1-2 weeks. nw.js was upgraded from 48 to 49 already. Published security problems will be disclosed in full details soon for 47 which is the current.

**Comment by havenchyk** [comment]
I don't see a lot of feedback from maintainers so just added the link from the FAQ. I'm also waiting for 49, but it will be as soon as core team integrate it. Try to ping the core contributors or make a PR :smile:

**Comment by felixrieseberg** [comment]
Please see https://github.com/atom/libchromiumcontent/pull/175.

**Comment by herrmannplatz** [comment]
Thanks @felixrieseberg. Haven't checked libchromiumcontent so far. Will follow the discussion there.

**Comment by kidwm** [comment]
track this: https://github.com/atom/electron/pull/4714
