### ISSUE TITLE
Can not load tray icon in the packaged condition

### ISSUE THREAD

**Issue by zgc2537** [atom/electron#4672]
* Electron version:0.36.9
* Operating system:winows7 x64

I set the tray icon as follows:
```javascript
var appIcon = null;
app.on('ready', function () {
    appIcon = new Tray('./app/img/crmlogo.png');

    appIcon.setToolTip("xxx");
    //appIcon.displayBalloon({icon:'./app/img/crmlogo.png',title:'通知',content:'你有新消息'});
    appIcon.on('click', function () {
        mainWindow.minimize();
    });
    appIcon.on('double-click', function () {
        mainWindow.maximize();
    });
    appIcon.on('balloon-click', function () {
        mainWindow.maximize();
    });
});
```

I run it by using npm command as 'npm start', it is ok completely.

But when i run the win64-exe file after i packageed, it will show this error:

![default](https://cloud.githubusercontent.com/assets/8650623/13521826/95189892-e226-11e5-9d0a-547ec1718f0b.PNG)

THX.

**Comment by enlight** [comment]
Try replacing the relative path to the icon with an absolute one.

**Comment by zgc2537** [comment]
Thx,i set "__dirname + '/app/img/crmlogo.png'", and it works.
