### ISSUE TITLE
Where is Electron's resource directory?

### ISSUE THREAD

**Issue by MarioHofer** [atom/electron#4673]
* Electron version: v0.36.9
* Operating system: OS X El Capitan 10.11.3

Sorry, maybe I'm just dumb, but I don't get...

On the "Application Distribution" page there is this text:

> To distribute your app with Electron, the folder containing your app should be named app and placed under Electron's resources directory (on OS X it is Electron.app/Contents/Resources/ and on Linux and Windows it is resources/), like this:

Where are these folders? I don't have any Electron.app on my machine. Is there maybe room for a better description?

Thanks in advance.

**Comment by kevinsawicki** [comment]
@MarioHofer how did you download Electron? `Electron.app` should be what gets unzipped when you download the mac version from https://github.com/atom/electron/releases

**Comment by MarioHofer** [comment]
I use just the CLI. Didn't recognize the releases. Maybe you should write that into the docs :-)

Thanks for the info.

**Comment by Amangupta6** [comment]
Linux users: 
Do sudo npm install -g electron and then run electron. It will open up the default app and will give you the resource directory.
Thanks.

**Comment by MarshallOfSound** [comment]
@Amangupta6 `sudo npm install -g` is a bad plan in any situation.  If you need to `sudo` to install globally you just fix your permissions instead of using `sudo`
