### ISSUE TITLE
Is Angulasr2 supported? Can we call node modules from the browser side

### ISSUE THREAD

**Issue by avrandrei** [atom/electron#4676]
* Electron version:38
* Operating system: Windows

Hello guys,

I'm pretty new to the electron way of doing things and was wondering if Angular2 with Typescript is supported. 

I created a quick test app using the getting started guide from the angular.io website: angular2 with typescript and systemjs as a module loader.

I'm having difficulties with using node modules in the browser side. When using Angular1 it was enough to require the module ( require('nedb')).

I need this in order to be able to have a persistence system in my application (something like nedb or lokijs).

Could you please advise on what route to take? What would be the preferrable architectural approach to achieve data persistance in an electron app?

**Comment by zcbenz** [comment]
A google search of "electron angular 2" will give you some guides.

**Comment by MarioHofer** [comment]
@zcbenz I'm looking for an answer to this for a couple of days now. What you find are tuts about settings up the app, but not one on how to communicate from Angular2 to Electron and back. So any idea would be great!

**Comment by MarioHofer** [comment]
@avrandrei Did you find a solution for that?

**Comment by zaidchauhan** [comment]
@MarioHofer 

I am also looking for the same question?

Did you get any success ?

**Comment by MarioHofer** [comment]
Yes, it works pretty easy. I made a quick Gist for you:
https://gist.github.com/MarioHofer/638e63b5695702b793845c3a29328dac

**Comment by zaidchauhan** [comment]
@MarioHofer 

Thanks Man :+1:

**Comment by MarioHofer** [comment]
I'm sorry, this doesn't seem to work completely. When I get the response, I'm out of my app - somehow. I can still call functions, but it seems, that the view is lost or not connected anymore... Weired.

**Comment by zaidchauhan** [comment]
@MarioHofer - Yes, but I warped ipc communication under promise and just resolve to caller.

Working fine for me.
