### ISSUE TITLE
Electron process just exits

### ISSUE THREAD

**Issue by surdu** [atom/electron#4677]
* Electron version: latest ?
* Operating system: Raspbian Jessie

After installing electron-prebuilt via npm on a raspberry pi 2, whenever I run the electron command, nothing happens, the process just exists.

This is true with both the electron-quick-start and `electron --version` (and my personal project).

What further info can I provide ?

**Comment by zcbenz** [comment]
The prebuilt binaries are probably not compatible with your model, can you try whether the binaries in [the Releases page](https://github.com/atom/electron/releases) would work?

**Comment by surdu** [comment]
I'm installing electron with `sudo npm install electron-prebuilt -g` which appears to use the latest arm build from the release page: `electron-v0.36.10-linux-arm.zip`

I've also tried with a version that I remembered it worked in the past : 0.36.5; Still, the same result.

**Comment by zcbenz** [comment]
So the prebuilt binaries are indeed not compatible with your model, I'm merging this to https://github.com/atom/electron/issues/259.

**Comment by surdu** [comment]
But the why did it worked in the past? As I've said, version 0.36.5 worked
just a month ago on the same system...

**Comment by zcbenz** [comment]
Sorry I didn't notice that, can you set following environment variables and paste the output?

```bash
export ELECTRON_ENABLE_LOGGING=1
export ELECTRON_ENABLE_STACK_DUMPING=1
electron -v
```

**Comment by surdu** [comment]
Hmm... Still there is no output, the process just exits with no output whatsoever :angry:

**Comment by zcbenz** [comment]
Can you use gdb to debug the program and see whether there is stack trace or the reason of the crash?

**Comment by surdu** [comment]
I'm not familiar with gdb debugging, but if you could send me instructions
I'm sure I can follow them

**Comment by MichMich** [comment]
Same problem here. @zcbenz, could you tell us how to debug?

**Comment by surdu** [comment]
This reproduces only on armv6 raspebrry pis. On armv7 and even armv8 works great.

**Comment by MichMich** [comment]
Yes, but not on all armv6's. On some Raspberry Pi 2's it works fine. See: https://github.com/MichMich/MagicMirror/issues/145

**Comment by surdu** [comment]
Pi2 has armv7

**Comment by MichMich** [comment]
Well, then still ... on some Pi2's it works fine. :)

**Comment by surdu** [comment]
My point was that it should work on all Pi2s, as they have armv7. Do you have Pi2s on which this problem occurs ? 

PS: be careful as the Pi 1 B+ looks like a Pi2, I've made that mistake :smile: .

**Comment by MichMich** [comment]
@surdu .... uhhmm ... You might be on to something. 😁 Will check it when I get home.

**Comment by MichMich** [comment]
@surdu You solved the issue! LOL! It was indeed an old B+ I had laying around. *shame*

**Comment by surdu** [comment]
@MichMich Solver YOUR problem, not THE problem 😄

**Comment by suyashkumar** [comment]
@surdu @zcbenz are you folks sure this works on armv8? Currently working on a project and trying to decide if it's limited to just Pi2 hardware, or if the latest Pi3's will be able to run electron apps!

At any rate, I also wanted to explore options for building Electron from source for armv6 (to support the RPi Zeros). Any immediate blockers or reasons as to why trying that may be futile?

**Comment by Zhairgling** [comment]
@suyashkumar 
Hi,
I have make an electron app working on a raspberry pi 3 but I can't get my app working on the pi zero.
Any chance to have electron working on the pi zero ?

**Comment by Baonui9999** [comment]
https://m.xhamster.com

**Comment by Jousboxx** [comment]
Same issue here, I have a Raspberry Pi Zero and can't figure out how to install Electron. Did anyone ever find a solution to this?

**Comment by Jak7774** [comment]
@Jousboxx you should check this link - https://github.com/kevinatown/MMM-Screencast/issues/44
