### ISSUE TITLE
WindowsToastNotification::Show crashes on Windows

### ISSUE THREAD

**Issue by fantasticsid** [atom/electron#4681]
* Electron version: 36.7
* Operating system: Windows 8

Here's the minidump stack trace: 

```
Operating system: Windows NT
                  6.3.9600
CPU: amd64
     family 6 model 26 stepping 5
     4 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0xffffffffffffffff
Assertion: Unknown assertion type 0x00000000
Process uptime: 1889 seconds

Thread 0 (crashed)
 0  ElectronApp.exe!brightray::WindowsToastNotification::Show(std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > const &,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator
<wchar_t> > const &,GURL const &,SkBitmap const &,bool) [windows_toast_notification.cc : 129 + 0x0]
    rax = 0x0000000143560001   rdx = 0x000000000013e280
    rcx = 0x0000000000232de0   rbx = 0x000000000d6591b8
    rsi = 0x000000000d659170   rdi = 0x000000000de1dd58
    rbp = 0x000000000013e699   rsp = 0x000000000013e630
     r8 = 0x0000000000000934    r9 = 0x0000000000008000
    r10 = 0x0000000000000100   r11 = 0x00007ffbae5d5420
    r12 = 0x6666666666666667   r13 = 0x000000000027b440
    r14 = 0x000000000dcab350   r15 = 0x000000000dcab308
    rip = 0x0000000140254332
    Found by: given as instruction pointer in context
 1  0x5f00000000000000
    rbp = 0x5f000000000d6640   rsp = 0x000000000013e6a9
    rip = 0x5f00000000000000
    Found by: previous frame's frame pointer

```

The app is using standard HTML notification APIs.

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! Quick question: With what parameters did you call `new Notification()`?

**Comment by fantasticsid** [comment]
```
var notification = new window.Notification(msg, {body: msg, tag: mid, icon: icon, dir: 'auto', lang: lang, silent: true,});
```

unfortunately I don't have the actual params when the crash happened. It also does not always happen.

**Comment by fantasticsid** [comment]
I was also able to reproduce the bug by creating 10 notifications per second in the developer console:

`setInterval(function() { var notif = new window.Notification('hi!'); console.log('notif!'); }, 100);
`
paste this into developer console and the app crashes after a while (10 ~ 20 seconds).

This is on Electron 36.7

**Comment by zcbenz** [comment]
It seems that we have problems when Notification failed to show.

**Comment by fantasticsid** [comment]
The bug is reproducible on Windows 10 if you turn off App notifications from 'Settings -> Notifications & actions -> Show app notifications'.
The same 

`setInterval(function() { var notif = new window.Notification('hi!'); console.log('notif!'); }, 100);`

crashes the app.

**Comment by kevinsawicki** [comment]
@felixrieseberg will you be able to look into this one?

**Comment by fantasticsid** [comment]
after stepping through the code on Windows, it seems to be related to memory corruption (double free maybe, but I'm not sure where..)

So in brightray/browser/notification_presenter.cc::RemoveNotification, if I remove

`delete notification;`

The app stopped crashing.

I'm not saying the bug is here, maybe by the time we get here the stack is already corrupted earlier.. The weird thing is I don't know why Electron crashes if notification failed, but not if the notification succeeds. Because from windows_toast_notification.cc, it looks like `WindowsToastNotification::NotificationDismissed()` and `WindowsToastNotification::NotificationFailed()` are doing almost the same thing: remove itself from presenter

Anyway I don't much enough about chromium's weak_ptr implementation, so would appreciate if you can provide some help!

**Comment by felixrieseberg** [comment]
I'll gladly fix it. I finally have a feeling that I know my way around Brightray 👀 Now that we have a repro, I'm already happy if we fix the repro case. I should be able to PR by early next week the latest.

@fantasticsid: Thank you for the investigation, that's really helpful!

**Comment by fantasticsid** [comment]
@felixrieseberg that's awesome! Please let me know when you figure out the root cause : - )

**Comment by fantasticsid** [comment]
@felixrieseberg I hope I'm not interrupting your work flow, but one thing I found is that [this line](https://github.com/atom/brightray/blob/3edbdfdf52015309df78fb586143c833e3c01b25/browser/win/windows_toast_notification.cc#L124) **sometimes** calls the failure handler synchronously if the notification center is turned off (or not available at all on Windows < 10).

This means the failure handler [here](https://github.com/atom/brightray/blob/3edbdfdf52015309df78fb586143c833e3c01b25/browser/win/windows_toast_notification.cc#L148) is called immediately before `Show(..)` is returned. The failure handler [frees the notification object itself](https://github.com/atom/brightray/blob/be00b1d551a977612bfe74979bdbfdec5e8c748f/browser/notification_presenter.cc#L28) and the delegate object also [gets deallocated](https://github.com/atom/brightray/blob/be00b1d551a977612bfe74979bdbfdec5e8c748f/browser/notification_delegate_adapter.cc#L18) in the destructor of `Notification`.

So finally on [this line](https://github.com/atom/brightray/blob/3edbdfdf52015309df78fb586143c833e3c01b25/browser/win/windows_toast_notification.cc#L129) when it tries to dereference the delegate object it's already gone and the app crashes..

Weird thing is why the failure handler is called synchronously **sometimes and not other times**. I haven't found good documentation on [MSDN](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.notifications.toastnotification.failed.aspx)

I'm attaching the callstack:

![callstack](https://cloud.githubusercontent.com/assets/203771/13613966/21551ba6-e523-11e5-8888-7d5f4a29d11c.png)

**Comment by btelintelo** [comment]
We are seeing the same crashing issue with notifications on electron 36.7, from a windows surface user.  It is a particular bad crash because we show a notification when the app starts resulting in immediate crash, with no way to update/fix the app without a fresh install.

Here is the JS code I am using to show a notification:
if (("Notification" in window)) {
			var options = {
				body: "some text",
				icon: "assets/images/app-icon.png"
			}
			notification = new Notification("Title", options);
			notification.onclose = function() {
				$modalInstance.close();
			};
		}

Any electron fix or workaround option would be greatly appreciated!

**Comment by btelintelo** [comment]
More info...user on surface disabled notifications in system settings.  So generating a notification with disabled notifications causes the crash.  However, it seems that even if a user disables notifications, Notification.permission still is "granted", so there is no way to check on a notification's availability before dispatching.  So def need a fix on this from electron.

**Comment by btelintelo** [comment]
Hey @zcbenz , we just tried out version 0.37.2 https://github.com/atom/electron/releases/tag/v0.37.2 which makes a reference to notifications failing to show(also referenced here in this bug).  However, we are still seeing crashes on two surface tablets when notifications are disabled at a per app level.  Despite notifications being disabled, Notification.permission is still "granted" and the crash still happens after we dispatch the notification.

**Comment by felixrieseberg** [comment]
I already know how to fix it, and I will - I'm just currently in Beijing (meaning that I'm unable to clone Ghoogle Chrome repos). I'll fly back today - expect a fix within the next 72 hours.

**Comment by felixrieseberg** [comment]
Hey everyone, fix is PRed. I also had a substantially harder time reproducing the original bug with our internal builds of Windows, so together with #205, we should be able to close this issue as soon as @zcbenz gets a chance to take a quick peek and merge.

**Comment by btelintelo** [comment]
Awesome!  We can reproduce almost every time in our app, so once you get a release out, we will give it a try.

**Comment by fantasticsid** [comment]
Awesome! Thank you so much @felixrieseberg

**Comment by fantasticsid** [comment]
By the way do you think we still need to worry about notification object lifetime in case notification display fails for other reasons?
(Though the only case I can imagine is user turning off notification center between checking and displaying, which is indeed very unlikely)..

**Comment by felixrieseberg** [comment]
I believe that this fixes the issue and prevents the race conditions (together with the new builds of Win 10), but let's certainly revisit if the issue pops up again. If any of you would like to [try my build (it's a debug build, but the patch is in there), I'd love to see if it actually fixes things on your end, too](https://onedrive.live.com/redir?resid=4EA869C40F03DA47!239063&authkey=!AG4Kjn-wZy9AETE&ithint=file%2czip).

**Comment by fantasticsid** [comment]
tested on master and the app no longer crashes. Thanks for the fix!
