### ISSUE TITLE
Disable dev tools entirely

### ISSUE THREAD

**Issue by afang** [atom/electron#4687]
Is there an option to disable dev tools (not just by hiding the menu option but also the hotkey)? Any way to make the packaged app not open source?

**Comment by paulcbetts** [comment]
The menu item _is_ the hotkey - if you don't have the menu, there is no way to open DevTools

**Comment by afang** [comment]
If I disable DevTools are there any other ways to view the source?

**Comment by paulcbetts** [comment]
Yes, by opening the source files. See https://github.com/atom/electron/issues/3041 for the discussion on this
