### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by xfactor5** [atom/electron#4689]
Hi,
As I saw, Electron seems to only work on VS2013. When will VS2015 support be added? I can not uninstall my IDE and downgrade it because I am currently using some VS2015 features. We should move forward not backward, it's a bit awkward to ask people to downgrade to old software! and I don't think porting current toolset to 2015 is such a big deal.
Thanks

**Comment by zcbenz** [comment]
Chromium still uses VS 2013 because of a few problems with VS 2015, you can find more about it at https://crbug.com/440500.

**Comment by charles-smith** [comment]
@zcbenz that bug report is listed as fixed.

**Comment by enlight** [comment]
@charles-smith Recent version of Electron are built with VS2015 Update 2.
