### ISSUE TITLE
Problem after build

### ISSUE THREAD

**Issue by fabdelgado** [atom/electron#4691]
* Electron version: 36
* Operating system: OSX Capitan

When electron compiled using the quick start receiving these errors.
OS = Windows & MAC

![js](https://cloud.githubusercontent.com/assets/8621547/13550532/c96c1398-e2fe-11e5-921f-16dcd7cc6760.jpg)

![js2](https://cloud.githubusercontent.com/assets/8621547/13550531/c96b67f4-e2fe-11e5-9d74-e4e1f555a414.jpg)

**Comment by zcbenz** [comment]
Can you try if https://github.com/atom/electron-quick-start works for you?

**Comment by fabdelgado** [comment]
no, if it works with https://github.com/szwacz/electron-boilerplate

**Comment by zcbenz** [comment]
Honestly I don't know why it happens.

**Comment by fabdelgado** [comment]
@zcbenz No problem, thanks
