### ISSUE TITLE
minimizable, maximizable, etc. on Linux

### ISSUE THREAD

**Issue by kminehart** [atom/electron#4696]
* Electron version: 0.36.10
* Operating system: Arch Linux x64, i3 WM

Working on an issue where when the user opts to minimize the application to the tray, it prevents the default close event from firing, and instead minimizes the application.

This does not work on Window Managers which do not have the ability to minimize or maximize, so any efforts to close the application with this option selected results in the window staying open and nothing happening.

See this code for an example:

```JavaScript
mainWindow.on('close', (event) => {
  if ((Settings.get('minToTray', true) || process.platform === 'darwin')) {
    if (process.platform !== 'darwin') {
      mainWindow.minimize();
      mainWindow.setSkipTaskbar(true);
    } else {
      var test2 = mainWindow.hide();
    }
    event.preventDefault();
    return;
  }
});
```

I have tried changing the code to include:

```JavaScript
if(!window.isMinimized()) {
    event.preventDefault();
}
```

However, this does not work in any Window Manager, as window.isMinimized at that point is still false for some reason, even if the WM can correctly handle minimizing.

I've also tried adding an event handler for `minimize`, but on i3, this event is never fired because a minimize never happens.

Ideally I would like to handle it with `window.minimizable`, but this is not possible on Linux because according to the documents it always returns true.

Either way, if `window.minimizable` on Linux is not possible, then why is `window.isMinimized()` returning false after calling `window.minimize()`, even if it is minimized?  Is `window.minimized()` asynchronous?

**Comment by zcbenz** [comment]
The minimize operation is asynchronous on Linux, it works by asking the window manager to minimize the window and then gets informed whether the window would be minimized. On the other hand there is no way to know whether the window manger supports minimize operation in Linux's desktop protocol.

So basically you have following solutions:

* Provide an option to users to let them decide whether to close or minimise the window;
* Get current window manager and decides the behaviour yourself;
* Set timeout when checking whether window is minimised.

**Comment by MarshallOfSound** [comment]
Could we add a note in the docs 

https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winminimize

That indicates the asyncronous nature of window management on linux :smile: 
If you can provide a list of the methods that are async I'll gladly PR in the docs :+1:
