### ISSUE TITLE
Yez! chrome extension support

### ISSUE THREAD

**Issue by rafaelcastrocouto** [atom/electron#4698]
* Electron version: 0.36.10
* Operating system: Windows 7

I got Yez! installed with `BrowserWindow.addDevToolsExtension` but when I click the tab I get a blank screen. Can anyone point me how to start debugging this? Thx a lot!

https://github.com/krasimir/yez/issues/10

**Comment by zcbenz** [comment]
It is probably using some chrome APIs that we do not support, I'm merging this to #915.
