### ISSUE TITLE
Auto Updater spontanteously failing

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4699]
* Electron version: `0.36.7`
* Operating system: `Darwin (OSX)`

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/293

```js
Error: Update check failed: (null)
    at Error (native)
```

No additional logging was available, doesn't appear to be an error with my code but rather an underlying issue with the autoUpdater?

**Comment by zcbenz** [comment]
autoUpdater can fail for networking issues like failed to connect the server or failed to download updates, I suggest just ignore it.

**Comment by MarshallOfSound** [comment]
Sweet, my plan was to just catch all update related errors and toss them.  Just checking there isn't some strange underlying issue :+1:
