### ISSUE TITLE
Features to disable in headless mode?

### ISSUE THREAD

**Issue by fritx** [atom/electron#4701]
* Electron version: 0.36.9
* Operating system: All

If the BrowserWindow has { show: false } for headless use,
would [options](http://electron.atom.io/docs/v0.36.8/api/browser-window/#new-browserwindowoptions) such as `images`, `webaudio`, `webgl` auto disabled?

Or do I have to turn off them manually?

What features should be turned off with headless usage?
Thank you!

**Comment by zcbenz** [comment]
`show: false` is actually not headless mode, it just hides the window, everything else is the same with `show: true`.

**Comment by fritx** [comment]
@zcbenz oh, cool. but what if i want the actual headless mode? :laughing:

**Comment by zcbenz** [comment]
It is tracked at #228.
