### ISSUE TITLE
Global shortcut, media tracking not working in windows

### ISSUE THREAD

**Issue by xabdullahx** [atom/electron#4702]
* Electron version: Latest
* Operating system: Windows 10

Haven't tested the others functions. but: MediaNextTrack, MediaPreviousTrack, MediaStop and MediaPlayPause - do not work, my keyboard is Microsoft Sculpt if that helps

**Comment by zcbenz** [comment]
The media keys can only be registered when they are not taken by other applications, in your case I believe Windows itself has taken all of them.

**Comment by xabdullahx** [comment]
So the solution is: can't be done?

**Comment by xabdullahx** [comment]
I removed the keyboard software and it worked. Now i wonder how i am going to get the media tracking on my bluetooth headset to work.

But now i understand that it has nothing to do with Electron :+1:
