### ISSUE TITLE
Windows Build faulting on boot

### ISSUE THREAD

**Issue by JaredSartin** [atom/electron#4707]
* Electron version: 0.36.9
* Operating system: Windows ???

Sent off a 32-bit build to my client (tested, works fine on our Windows PCs). They returned this message (removed sensitive info in path - replaced with x, y, z):

> Application Crashing Events
> 
> Message:
> Faulting application name: Jumper.exe, version: 0.36.9.0, time stamp: 0x56cfbd8
> Faulting module name: node.dll, version: 6.3.9600.17736, time stamp: 0x550f42c2
> Exception code: 0xc0000135
> Fault offset: 0x0009d4f2
> Faulting process id: 0x2fc
> Faulting application start time: 0x01d17808fac3793d
> Faulting application path: C:\ProgramData\xxxxxx\yyy\share\zzz\documents\108340571\Jumper.exe
> Faulting module path: node.dll
> Report Id: 38751c3d-e3fc-11e5-83b4-0010f34a4cd1
> Faulting package full name:
> Faulting package-relative application ID:

Any pointers to fixing/finding the fix for this?

**Comment by JaredSartin** [comment]
Quick Notes: Jumper.exe is the rename of the Electron app. Full directory was shared with the client.

**Comment by zcbenz** [comment]
No, unless you have the crash dump file or symbolized crash report, there is nothing we can do.

**Comment by zcbenz** [comment]
Closing since we are not able to fix this without more information.
