### ISSUE TITLE
printToPDF ==> printBackground do not work

### ISSUE THREAD

**Issue by nnenadovic** [atom/electron#4708]
* Electron version: "electron-prebuilt": "^0.36.0"
* Operating system: Ubuntu 14.04 LTS

It's not working with 'printBackground': true or printBackground: true.
Images are prinded ok.

code:
```
var webContents = focusedWindow.webContents;
webContents.printToPDF({
    'printBackground': true,
    'pageSize': 'A4'
}, function(err, data) {
    if(err) console.error("[PRINT] err:", err);
    var dist = '/home/neeqola/Desktop/test.pdf'
    fs.writeFile(dist, data, function(err) {
        if(err) console.error('[SAVE PDF] error', err)
    })
})
```

**Comment by MrSaints** [comment]
Have you checked to see if the CSS background for your page is being overwritten? Perhaps by a print media stylesheet?

**Comment by nnenadovic** [comment]
To test it, I create dummy page with ~50 different inner elements with different background-color, and use  only 1 style.css file. How can I check if there is any overwrite? The page is rendered in electron correctly. When page is printed, there is just text.

**Comment by MrSaints** [comment]
How are you importing your `style.css` ?

**Comment by nnenadovic** [comment]
in index.html I have:
```
<link rel="stylesheet" href="css/style.css" media="screen" charset="utf-8">
```

**Comment by nnenadovic** [comment]
Ok, when I removed ```media="screen"```, background print also. Thank you for hint :-D

**Comment by MrSaints** [comment]
On that note, I think it'd probably be nice to have an option to disable using the "print" media.

**Comment by francisberesford** [comment]
Yes, I agree with @MrSaints, I'd like to specify that the PDF render with screen styles instead of print styles. This can't be done in PhantomJS either.
