### ISSUE TITLE
Question: Event: 'open-url' only available in OS X, any way to achieve the same thing on Windows ?

### ISSUE THREAD

**Issue by kimak** [atom/electron#4718]
* Electron version: 0.36.10
* Operating system: OSX 10.11.3

After reading the documentation here: https://github.com/atom/electron/blob/master/docs/api/app.md
I see that the event "open-url" used to open the app from the browser is only available in OSX.

Just a question: Is it possible to open a scheme, (atom://) by example on Windows ? Or any way to achieve the same functionality ?

**Comment by enlight** [comment]
On Windows the URI will be passed as a command line argument, [details can be found on MSDN](https://msdn.microsoft.com/en-us/library/aa767914%28v=vs.85%29.aspx).

**Comment by sbruchmann** [comment]
Dear @kimak 

GitHub Issues is a **bug tracker**. Please use the [official electron forum](https://discuss.atom.io/c/electron) for asking questions.

**Comment by kimak** [comment]
Yes, my bad. The forum is better for that. Thanks.
