### ISSUE TITLE
Configurable location of app profile - feature request

### ISSUE THREAD

**Issue by webarchymeta** [atom/electron#4721]
* Electron version: all future version
* Operating system: all

Reference #1404

It would be useful for Electron to adapt to wider area of applications scenarios beyond what was imagined for it if it could allow the developer to choose where to store application profile other than `%APPDATA%`. In addition to the reasons given in ref #1404, I also can provide more here:

1. There are applications that treat instances on different host nodes as identifiable entities, even in an enterprise environment. For example, we are developing a virtual network system in which each instance of it is a virtual network node of the system within a common user account. Roaming the application profile across the enterprise network will eventually make every node identical and therefore corrupt the network.

2. It could open security holes to some application, like financial ones. Roaming sensitive information user saved in some "trusted nodes" that they control to public nodes or the nodes of other peers will risk leaking their sensitive information, like user credential, card information, etc. without even letting the uninformed developers and end users know.

3. There are applications that has large local databases. Roaming these databases cross enterprise network may create bandwidth problems, like what @tehbilly described in #1404

4. Every other ones are using `%LOCALAPPDATA%` to save application profiles, they include Chrome, Chromium, Firefox, Opera, IE, etc.

I know there could be compatibility issues if the default location is changed. I am for the idea that @etiktin put forth in ref #1404. Better yet, why not let the developer to choose where to put the profile? Some application might want to safe the application profile in some custom location, e.g. at an  encrypted partition of the local storage or even on a secured storage chip?

**Comment by paulcbetts** [comment]
You can already do this with `app.setPath`, you just need to call it super early
