### ISSUE TITLE
Cannot blur BrowserWindowProxy from window.open

### ISSUE THREAD

**Issue by maxbeatty** [atom/electron#4724]
* Electron version: 0.36.10
* Operating system: OS X 10.11.3

When `window.open` returns an instance of `BrowserWindowProxy` ([docs](http://electron.atom.io/docs/v0.36.8/api/window-open/#windowopenurl-framename-features) | [src](https://github.com/atom/electron/blob/v0.36.10/atom/renderer/lib/override.js#L123)), an uncaught exception occurs if you call `blur` on the returned reference of the new window. If you run [my fork of `electron-quick-start`](https://github.com/maxbeatty/electron-quick-start/commit/74d37a6cf161b608cdf83c6d138de4bad880e3d7), you should get this error:

```
Uncaught Exception:
TypeError: Cannot read property 'apply' of undefined
    at EventEmitter.<anonymous> (/path/to/maxbeatty/electron-quick-start/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/guest-window-manager.js:105:71)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/path/to/maxbeatty/electron-quick-start/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

This is my first time digging into the Electron source. From what I can tell, calling `blur` sends an `ATOM_SHELL_GUEST_WINDOW_MANAGER_WINDOW_METHOD` message to `ipcRenderer` ([src](https://github.com/atom/electron/blob/v0.36.10/atom/renderer/lib/override.js#L47)). Then, that message is sent to `ipcMain` via the atom binding (?) ([src](https://github.com/atom/electron/blob/v0.36.10/atom/renderer/api/lib/ipc-renderer.js#L12)). When `ipcMain` receives that message, it tries to apply the method (`blur`) to an instance of `BrowserWindow` which does not have a `blur` method :boom: ([src](https://github.com/atom/electron/blob/v0.36.10/atom/browser/lib/guest-window-manager.js#L105)).

I couldn't find where `BrowserWindow` defines its `focus` method. Maybe there's a good reason it doesn't have a `blur` counterpart. Adding `blur` to `BrowserWindow` is one way to fix this exception. The other is to check for the method before [calling `apply`](https://github.com/atom/electron/blob/v0.36.10/atom/browser/lib/guest-window-manager.js#L105).

```diff
- return (ref1 = BrowserWindow.fromId(guestId)) != null ? ref1[method].apply(ref1, args) : void 0;
+  ref1 = BrowserWindow.fromId(guestId);
+  if (ref1 != null && ref1.hasOwnProperty(method)) {
+    return ref1[method].apply(ref1, args);
+  }
+
+  return void 0;
```

I'd be happy to submit a PR with some direction.

**Comment by kevinsawicki** [comment]
@zcbenz for this one, would proxying `BrowserWindowProxy.blur` to `BrowserWindow.blurWebView` be the right approach?

**Comment by maxbeatty** [comment]
I did do that (when `method` is `blur`, set to `blurWebView`) while debugging this and there weren't any noticeable adverse effects

**Comment by kevinsawicki** [comment]
> I did do that (when method is blur, set to blurWebView) while debugging this and there weren't any noticeable adverse effects

Oh great, would you like to get a pull request going with this change and we can continue discussing there?

**Comment by zcbenz** [comment]
Actually `blurWebView` is not equal to `blur`, `blurWebView` would make the page lose the focus, but `blur` would make the window lose the focus.

I think we can just add a `blur` API for `BrowserWindow`, it is already implemented but just not exposed:

```c++
// In atom_api_window.cc:
void Window::Blur() {
  window_->Focus(false);
}
```
