### ISSUE TITLE
Unclear how appData/userData folder behaves with multiple Electron instances

### ISSUE THREAD

**Issue by bpasero** [atom/electron#4727]
This is more a question or ask to update docs, not an issue: When using Electron, all of Chromes configuration files end up in appData (e.g. local storage, indexdb). It is not clear to me if it is OK to have 2 instances of Electron running at the same time both sharing the same appData folder. 

In the past I have seen at least one case where this was not possible: Using IndexDB seems to lock the appData folder so that a second instance is not fighting over the IndexDB resources. This seems like a valid thing for IndexDB to do. 

However, in which cases is it OK to have multiple instances on the same appData folder and when should it be prevented? Imagine the second instance is not spawning a renderer process and is just there to talk to the "main" instance via some ipc mechanism. Would the appData folder still have resources that both instances would fight over?

**Comment by zcbenz** [comment]
Chromium doesn't have good support for running two instances at the same time, most resources are guarded with file locks, like localStorage, so if you are using localStorage in one instance the accesses in other instances will be refused. And for resources that are not guarded by locks, race conditions might happen and it would be very bad.

**Comment by bpasero** [comment]
@zcbenz but would you say that the appData folder is mainly used for renderers and that it is somewhat safe to have 2 instances of the main process running at the same time as long as they dont both open windows?

**Comment by zcbenz** [comment]
Yeah under that condition it should be OK.

**Comment by bpasero** [comment]
@zcbenz another question: do you think it is possible to migrate the app data folder to another location? I am wondering at which time Electron/Chromium expects the app data folder to be there, e.g. is there a way to do this operation (even if it takes 1 second) before this folder is needed?

**Comment by bpasero** [comment]
@zcbenz actually I did a small experiment and it seems to me that the appdata folder is empty as long as no window is opened, after that, I see the following folders created: GPUCache, Local Storage. So I would assume I could do the migration before any window opens.

**Comment by bpasero** [comment]
The other question is if these folders are fit to be moved to another location or not...

**Comment by zcbenz** [comment]
@bpasero As long as you call `app.setPath` very early it would be safe to set the `userData` folder to anywhere you want, and copying original app data to the new location should be OK. But there is a bug that the `userData` folder is created before running user's main process script (#2668), so after migration the old `userData` folder will still be there.

**Comment by bpasero** [comment]
Allright, thanks for the pointer to the other issue.

**Comment by TimNZ** [comment]
Ok so if I am spawning multiple instances of Electron via multiple simultaneous instances of a Node script that runs Nightmare, then this may explain why the scripts don't execute properly?

E.g.
Master node process (persistent)
-> Spawns runner.js via node-worker-farm module -> new Node process
----> runner.js fires up Nightmare script

Works fine with one spawned process, more than one and Nightmare renderer actions don't work reliably.

**Comment by TimNZ** [comment]
@zcbenz It seems #2668 was solved so using app.setPath and creating diff appData and userData for each instance would solve the conflicts for multiple instances i.e. I presume that is what happens now each for Electron app with a different package name.
