### ISSUE TITLE
Zoom Shortcuts are being absorbed somewhere

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4728]
* Electron version: `0.36.10`
* Operating system: Windows

The shortcuts "Ctrl +" and "Ctrl -" are not coming through on window level keypress event listeners.

```js
window.addEventListener('keypress', (e) => console.log(e));
```

The above code correctly logs events for any other keypress, even "+" by itself.  But as soon as you add the "Ctrl" modifier key it is not firing the event.  This makes implementing the "+" and "-" keys as zoom shortcuts quite tricky :smile: 

Is there a method I am missing somewhere that fires these zoom hotkeys?

**Comment by sbruchmann** [comment]
Modifier keys do not trigger a `keypress` event. Use `keydown`.

**Comment by MarshallOfSound** [comment]
Oh hell to the no....

I feel quite silly now.  Thanks @sbruchmann, I can't believe I didn't catch that
