### ISSUE TITLE
Documentation seems out of date re: Linux and Tray

### ISSUE THREAD

**Issue by MichaelJCole** [atom/electron#4731]
* Electron version:  0.36.10
* Operating system:  Linux

I'm looking at this bug: https://github.com/atom/electron/issues/1715

And this documentation: https://github.com/atom/electron/blob/master/docs/api/tray.md

And trying it on Linux Mint 14.04 and the click event works for me.

**Comment by zcbenz** [comment]
I think your desktop environment is not using app indicator for show tray icons.

**Comment by MichaelJCole** [comment]
@zcbenz Hey Cheng, ok I didn't understand that when reading it.

What linux distros use appindicator?  

Linux Mint w/ Cinnamon:  no - click works on tray
Ubuntu w/ Unity: ?
Ubuntu w/ Gnome: ?

Just curious.  You all have worked with it more than anyone.  Some notes would be super helpful.  Thanks!

Mike

**Comment by zcbenz** [comment]
It actually depends on which desktop environment you use, I'm only sure Unity and GNOME 3 are using app indicator.
