### ISSUE TITLE
Missing docs for how to access ipcRenderer w/ nodeIntegration:false

### ISSUE THREAD

**Issue by MichaelJCole** [atom/electron#4734]
* Electron version:  0.36.10
* Operating system: Mintbuntu 14.04

Hey, I'm looking [here](https://github.com/atom/electron/blob/master/docs/api/ipc-main.md#sending-messages) for howto send a message from renderer to main.  I'd like a button to close the window.

Unfortunately, the docs don't show how to get an ipcRenderer when nodeIntergration is set to false.  There's no require or window.require.

Howto?

Thanks!

Mike

**Comment by zcbenz** [comment]
You can do it in the `preload` script.
