### ISSUE TITLE
-webkit-app-region: drag broken in OS X

### ISSUE THREAD

**Issue by jviotti** [atom/electron#4741]
`-webkit-app-region: drag` seems to do nothing on recent Electron versions, at least in OS X. I tried in both my own app and in Electron's default app, by placing the rule in `body` as well as in many different elements.

- This fails with both `frame: true` and `frame: false`.

***

* Electron version: Tested in v0.36.8 and v0.36.10.
* Operating system: OS X, but could be happening in other OSes.

**Comment by zcbenz** [comment]
Can you give an example? Other applications like https://github.com/nylas/N1 are using it without problems.

**Comment by bbondy** [comment]
I think it is broken when devtools are open within the window but only when docked.

**Comment by jviotti** [comment]
@zcbenz I uploaded a gist here: https://gist.github.com/jviotti/aadc0ba1d5962cfe19cf

@bbondy I tried with DevTools closed and the issue persisted.

**Comment by zcbenz** [comment]
@jviotti Only frameless windows can specify draggable regions.
