### ISSUE TITLE
Get keyboard input when app is not in focus

### ISSUE THREAD

**Issue by nickaversano** [atom/electron#4746]
* Electron version: 0.3.7
* Operating system: Mac

Wondering if it is possible to get keyboard input when the app is not in focus? Similar to electron.screen.getCursorScreenPoint(), I would like something like electron.keyboard.on('keypress'). I don't even need the key codes pressed, trying to implement "idle" detection for my app.

Any advice would be much appreciated

**Comment by enlight** [comment]
You will need to use the native platform APIs to detect system idle time, either by writing a native Node module or using `node-ffi`, this was discussed previously in https://github.com/atom/electron/issues/1528

**Comment by nickaversano** [comment]
Thanks!
