### ISSUE TITLE
How would a normal rendering GBK encoded files ?

### ISSUE THREAD

**Issue by baihuibo** [atom/electron#4748]
* Electron version: 0.36.9
* Operating system: os x 10.11.3

Hello there

When I visit a site generated page , it returns to me is a gbk encoded file , Electron can not be correctly rendered this file , because Electron use utf-8 encoding of the file to parse。
And I use the browser can render this page correctly。

Is there an interface that allows me to process the request stream to convert its encoding format？
```js
var get = require('request');
var iconv = require('iconv-lite');
var fs = require('fs');

get('http://host/ncpai/print/1457661305638.html')
       .pipe(iconv.decodeStream('gbk'))
       .pipe(iconv.encodeStream('utf-8'))
       .pipe(fs.createWriteStream('report.html'));
```

Or how should I do ?

Thank you

file examples  https://github.com/baihuibo/test-gbkToUtf8.git

**Comment by zcbenz** [comment]
You can use the `protocol` module to hijack HTTP requests, or you can probably use `session.webRequest` API to add a header indicating the file is in GBK encoding.

**Comment by baihuibo** [comment]
@zcbenz 

I used `session.webRequest` API, but the file encoding settings did not take effect

```js
var filter = {
    urls: ["http://10.2.3.237:7001/ncpai/print/*.html"]
};
currentWebContents.session.webRequest.onResponseStarted(filter, function (details, callback) {
   details.responseHeaders['Content-Type'] = "text/html; charset=gbk";
   callback({cancel: false , responseHeaders : details.responseHeaders });
});
```

I was not used in the right way ?

**Comment by zcbenz** [comment]
Can you check whether the header is added in devtools? If you are doing this in the renderer process, it may not work since Electron doesn't support adding new property for remote objects.

**Comment by baihuibo** [comment]
I look at the developer tools , set encoding does not take effect
What should I do ?

**Comment by zcbenz** [comment]
You can try using webRequest in the main process.

**Comment by baihuibo** [comment]
Thank you, I successfully set the file encoding
It needs an array, not a string.
```js
ses.webRequest.onHeadersReceived(filter, function (details, callback) {
    details.responseHeaders['content-type'] = ['text/html; charset=gbk'];//array
    callback({responseHeaders: details.responseHeaders})
});
```
