### ISSUE TITLE
how to modify the app version?

### ISSUE THREAD

**Issue by hahaGitHub** [atom/electron#4749]
* Electron version:0.36.10
* Operating system:OS

i use electron-packager to pack the app. after it ,display the electron.app's information.i see the version is 0.36.10.please tell me how to modify the version as my package.json said(eg:1.0.0).

this is the result:
<img width="193" alt="2016-03-11 11 35 09" src="https://cloud.githubusercontent.com/assets/12423630/13693012/69ff6b12-e781-11e5-801e-27dede9b8d58.png">

**Comment by walltex** [comment]
Add --app-version=1.0.0

**Comment by kevinsawicki** [comment]
Thanks for the answer @walltex 

Closing this out.
