### ISSUE TITLE
autoUpdater 'update-downloaded' restores window

### ISSUE THREAD

**Issue by dbkynd** [atom/electron#4750]
* Electron version: 0.36.10
* Operating system: Win10

It seems that when the autoUpdater event 'update-downloaded' is called the application is restored from a minimized state. Is there a way to stop this behavior? I searched the issues here and couldn't find any reference. Or is this more of a Squirrel issue?

<img src="http://dbkynd.com/l/3mowd">

The app is minimized and I've set win.setSkipTaskbar(true); so that the app is only showing in the Tray, but as stated above, with the shown example, when update-downloaded is fired I get the console log, then the app reappears on-screen as if a restore window event was triggered. Then the div I'm showing via jQuery appears.

**Comment by kevinsawicki** [comment]
Yeah, I can't find any code in Electron that would be causing this.

@dbkynd does your app contain any logic that handles the [Squirrel startup commands](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md#application-startup-commands) that could be causing it to unminimize when they fire?

@paulcbetts do you know if this is something Squirrel does?

**Comment by dbkynd** [comment]
Other than creating and removing shortcuts, no
https://github.com/dbkynd/controlcast/blob/master/app.js#L44

**Comment by kevinsawicki** [comment]
@dbkynd have you checked if these lines are executing when you see this behavior? https://github.com/dbkynd/controlcast/blob/611ecb1adbf7d899ea344083f92080df446ee285/app.js#L21-L22

**Comment by dbkynd** [comment]
Oh, I see. Squirrel may be running a new instance of it's Setup.exe when the 'update-downloaded' completes to run what's in the Squirrel handleStartupEvent() on the new version. That makes sense. Nice catch. I'll be able to test shortly.

**Comment by dbkynd** [comment]
Yes indeed. That was the culprit. When Squirrel says to have it's handling at the top it really means it, lol
Moving my 'Force Single Instance' function below the Squirrel handler solved my issue. Thank you for the help.

**Comment by kevinsawicki** [comment]
@dbkynd Glad to hear things are working now, thanks for the update :+1:
