### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by zgc2537** [atom/electron#4754]
* Electron version: 0.36.9
* Operating system: Windows7

I use the electron to load my remote url.I modify the remote website, when function require is not undefined, i load the js file which can run in the electron enviroment. Everything is Ok, except loading wav file, and show the following error:

     Not allowed to load local resource: file:///D:/usbrecord/2016/03/11/2016-03-11_16-09-15_000_18616756861.wav

My code is:
```javascript
audio = new Audio(fileaddr);//fileaddr is local file
```
I tried to use 
```javascript
app.commandLine.appendSwitch('allow-file-access');
```
but it doesn't work

But i read load the other local file such as:
```javascript
fs.readFile(CONFIG_FILE_DIR, "utf8", function (error, data) {

            });
```
it is ok

main.js:
```javascrip
mainWindow.loadUrl('http://XXX.XXXX.COM/');
```

**Comment by zgc2537** [comment]
But i read file such as:
```javascript
fs.readFile(CONFIG_FILE_DIR, "utf8", function (error, data) {

            });
```
it is ok

**Comment by zcbenz** [comment]
You can turn off `webSecurity` in `webPreferences` to enable it.

**Comment by zgc2537** [comment]
thx,how can i do? please tell me the concrete method

**Comment by zgc2537** [comment]
thx,how can i do? please tell me the concrete method。

发自我的 iPhone

在 2016年3月13日，下午6:33，Cheng Zhao <notifications@github.com<mailto:notifications@github.com>> 写道：


You can turn off webSecurity in webPreferences to enable it.

**Comment by zgc2537** [comment]
THX, I have found this setting, and try it tomorrow.THX again.
