### ISSUE TITLE
Can I specify multiple accelerators to one menu item?

### ISSUE THREAD

**Issue by k0kubun** [atom/electron#4758]
* Electron version: 0.36.9
* Operating system: Linux archlinux 4.4.1-2-ARCH

I want to set multiple accelerators to one menu item, otherwise I want to set invisible menu item just for additional hotkey.

**Comment by zcbenz** [comment]
No, the native menu only supports one accelerator for one menu item, you can probably work around it by handling shortcuts with DOM events.

We will have a solution for this when #1334 is implemented.

**Comment by k0kubun** [comment]
Oh I missed it. Thank you for your comment!
