### ISSUE TITLE
"disposition" should be "background-tab" in "new-window" event when clicking link with ctrl/cmd pressed

### ISSUE THREAD

**Issue by jwheare** [atom/electron#4760]
* Electron version: v0.36.9
* Operating system: Windows 10/OS X

In #779 a `disposition` was added to the `new-window` event in [webContents](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#event-new-window) but it always seems to be set to `new-window` when clicking on target="_blank" links in our web app wrapper: https://github.com/irccloud/irccloud-desktop/blob/v0.1.3/app/main.js#L109

If I Ctrl (Win) or Cmd (OS X) or middle click on links, I would expect to see a `background-tab` disposition, as in Chrome that will open links in a background tab, while keeping focus on the current tab. I'd like to catch this behaviour to set `activate` to false in `shell.openExternal`.

Is this possible?

**Comment by deepak1556** [comment]
@zcbenz [WebContentsDelegate::ShouldCreateWebContents](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/web_contents/web_contents_impl.cc&sq=package:chromium&q=web_contents_impl.cc&l=1856) doesnt provide the window disposition as a parameter, cant think of any easy way to decide the navigation policy. Can we patch to provide this parameter ?

**Comment by zcbenz** [comment]
The `window_container_type` parameter is supposed to provide the information, but I'm not sure why it doesn't work.

I'm OK with patching if it is like a one-line patch, otherwise it would be a maintenance nightmare.
