### ISSUE TITLE
Is there a way to focus on main window after calling openDevTools?

### ISSUE THREAD

**Issue by k0kubun** [atom/electron#4764]
I call `openDevTools` after opening BrowserWindow but I don't want to focus on not devTools but main browser window. Is there a way to toggle focus between devTools and browser window?

**Comment by MarshallOfSound** [comment]
Read the docs  
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winfocus

```js
yourBrowserWindow.focus()
```

**Comment by k0kubun** [comment]
I tried it but it didn't work. My code was:

```js
mainWindow = new BrowserWindow(...);
mainWindow.loadURL(...);
mainWindow.openDevTools();
mainWindow.focus();
```

Is the `focus()`'s receiver wrong?

**Comment by zcbenz** [comment]
If you want to focus the page, you can call `win.focusOnWebView` or `win.webContents.focus`.

**Comment by k0kubun** [comment]
Thank you for your comment but still no luck.

I tried following code but all of them didn't work.

```js
mainWindow.openDevTools();
mainWindow.focusOnWebView();

mainWindow.openDevTools();
mainWindow.webContents.focus();

mainWindow.webContents.on('devtools-opened', () => {
  mainWindow.focusOnWebView();
});
mainWindow.openDevTools();

mainWindow.webContents.on('devtools-opened', () => {
  mainWindow.webContents.focus();
});
mainWindow.openDevTools();
```

**Comment by zcbenz** [comment]
`mainWindow.webContents.focus` should work, if not please provide a reproducible example and information of your OS and electron version.

**Comment by k0kubun** [comment]
I have two environments and both of them didn't work:

- Electron: v0.36.9
- OS:
  - OSX El Capitan v10.11.1, Darwin Kernel Version 15.0.0
  - Linux archlinux 4.4.1-2-ARCH

Reproducible example is: https://github.com/k0kubun/Nocturn

here is reproductive steps:

```sh
git clone https://github.com/k0kubun/Nocturn
cd Nocturn
npm install
npm run setup
npm start
# Please authenticate your twitter account... sorry
```

After authentication, mainWindow and devTools will open and mainWindow won't be focused.

**Comment by zcbenz** [comment]
Can you make a minimal example? In a complex app the problem could be in anywhere.

Also the code works for me is:

```js
mainWindow.webContents.on('devtools-opened', () => {
  mainWindow.webContents.focus();
});
```

**Comment by k0kubun** [comment]
Reproductive minimum code with the way you provided:
https://gist.github.com/k0kubun/759c2c18d12a4a8f4c09

Run `npm install && npm start`. Even with this tiny code, main browser window is shown under devTools.

**Comment by zcbenz** [comment]
`mainWindow.webContents.focus` is for focusing on the page, while `mainWindow.focus` is for focusing the window. The former is meaningful for attached devtools and the latter can be used for detached devtools.

You have to call them in `devtools-opened` event since opening devtools is an async operation.

**Comment by k0kubun** [comment]
> You have to call them in devtools-opened event since opening devtools is an async operation.

That makes sense. 

> mainWindow.webContents.focus is for focusing on the page, while mainWindow.focus is for focusing the window. The former is meaningful for attached devtools and the latter can be used for detached devtools.

I see. Then I should call `mainWindow.focus` instead of `mainWindow.webContents.focus`. I changed the gist so, but it didn't work. How can I let `mainWindow.focus` to work? I confirmed that `devtools-opened` event was passed by `console.log` and `mainWindow.focus` did nothing.
https://gist.github.com/k0kubun/759c2c18d12a4a8f4c09

**Comment by zcbenz** [comment]
I see your problem now, the devtools window took the focus after the `devtools-opened` event, so you have to delay focusing to next tick:

```js
  mainWindow.webContents.on('devtools-opened', () => {
    setImmediate(function() {
      mainWindow.focus();
    });
  });
```

We should probably change this behavior or add an option to not focus the devtools window.

**Comment by k0kubun** [comment]
It worked fine for me. Thank you for your help!
