### ISSUE TITLE
Processes keep running after closing electron

### ISSUE THREAD

**Issue by whphhg** [atom/electron#4767]
* Electron version: 0.37.0
* Operating system: Linux raw 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux

After updating from 0.36.11 → 0.37.0 the processes keep running after closing electron using the window close button or ctrl-c from the terminal (as below).

```
[whphhg@raw ~]$ ps -aux | grep "ele"
whphhg    6093  0.1  0.0 683736 22248 pts/6    Sl+  12:19   0:00 node /home/whphhg/ui-electron/source/node_modules/.bin/electron electron/initialize.js
whphhg    6098  2.5  0.2 1145460 85516 pts/6   Sl+  12:19   0:00 /home/whphhg/ui-electron/source/node_modules/electron-prebuilt/dist/electron electron/initialize.js
whphhg    6100  0.0  0.0 346184 30476 pts/6    S+   12:19   0:00 /home/whphhg/ui-electron/source/node_modules/electron-prebuilt/dist/electron --type=zygote --no-sandbox
whphhg    6120  0.5  0.2 550304 73044 pts/6    Sl+  12:19   0:00 /home/whphhg/ui-electron/source/node_modules/electron-prebuilt/dist/electron --type=gpu-process --channel=6098.0.384896596 --no-sandbox --window-depth=24 --supports-dual-gpus=false --gpu-driver-bug-workarounds=3,16,54 --disable-gl-extensions=GL_ARB_occlusion_query GL_ARB_occlusion_query2 --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0412 --gpu-driver-vendor --gpu-driver-version --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd

```

npm 3.8.1
node 5.8.0

**Comment by Darkle** [comment]
I'm getting the same.
electron 0.37.1
node 5.1.1
OSX 10.11.3

**Comment by whphhg** [comment]
Tried with 0.37.1 now, issue persists.

**Comment by zcbenz** [comment]
I'm unable to reproduce with the default app, can you provide a reproducible example?

**Comment by whphhg** [comment]
[Here's](https://github.com/whphhg/electron-reproducible-example) a reproducible example.

electron-compile is at v2.0.7 due to their issue #73, but behaviour persits if you update it to v2.1.2.

To make sure it happens every time, click through chromium devtools tabs and close app after.

**Comment by bbondy** [comment]
Brave's electron is also hanging on app quit as well.   It's not the same sample program as above but probably the same issue.  The hang happens after all shutdown operations work fine.  Particularly on the marked line of code below when freeing the js-env. 

```
void AtomBrowserMainParts::PostMainMessageLoopRun() {
  brightray::BrowserMainParts::PostMainMessageLoopRun();

#if defined(OS_MACOSX)
  FreeAppDelegate();
#endif

  // Make sure destruction callbacks are called before message loop is
  // destroyed, otherwise some objects that need to be deleted on IO thread
  // won't be freed.
  // We don't use ranged for loop because iterators are getting invalided when
  // the callback runs.
  for (auto iter = destructors_.begin(); iter != destructors_.end();) {
    base::Closure& callback = *iter;
    ++iter;
    callback.Run();
  }

  // Destroy JavaScript environment immediately after running destruction
  // callbacks.
  gc_timer_.Stop();
  node_debugger_.reset();
  atom_bindings_.reset();
  node_bindings_.reset();
  js_env_.reset(); <------ hangs here when the pointer is freed.
}
```

**Comment by bbondy** [comment]
Maybe the node submodule needs to be updated

**Comment by paulcbetts** [comment]
Yep, we're seeing this too in the Slack app on 0.37.1

**Comment by bbondy** [comment]
I'm guessing upgrading the node submodule to V8 4.9 will fix this.

**Comment by zcbenz** [comment]
There was [a change in V8](https://chromium.googlesource.com/v8/v8/+/60e7ea8a9970f5a08c14a0aa052c099ac4ea4c08) that makes the main thread waiting for background threads to finish when quitting, it seems that we are not shutting down V8 correctly.

**Comment by bbondy** [comment]
I upgrade the Bave fork of node to 5.8 and was able to revert this shutdown fix.
I did have to revert https://github.com/brave/node/commit/05134726ca2c42b0332db4eacd043775b2148a4c because it was causing dev tools not to work (found by bisecting).
