### ISSUE TITLE
Win7 breakage with 0.37.0 Win8 only API PowerDeterminePlatformRoleEx

### ISSUE THREAD

**Issue by bbondy** [atom/electron#4770]
I'm not sure why this works on Chrome v49 itself but this is a win8 only API.  Maybe the WINVER setting isn't working properly in brightray's gypi

<img width="346" alt="screenshot 2016-03-12 10 23 00" src="https://cloud.githubusercontent.com/assets/831718/13723760/8c13329a-e83c-11e5-8de4-07d1cf42fac7.png">

**Comment by bbondy** [comment]
It could be patched by dynamically loading the api w/ load library and get proc address, but it's strange that chrome itself doesn't need to do this.  Maybe it uses a stub of that api somewhere / somehow.

**Comment by bbondy** [comment]
I don't understand how Chrome can get it to work

From Powerbase.h
```
#if (NTDDI_VERSION >= NTDDI_WIN8)
POWER_PLATFORM_ROLE
WINAPI
PowerDeterminePlatformRoleEx(
    _In_ ULONG Version
    );

#endif
```

So it seems like Chrome has to compile with NTDDI_VERSION set to at least NTDDI_WIN8 or the code isn't included at all for some reason in Chrome.

**Comment by bbondy** [comment]
I'm testing a patch that fixes this here:
https://github.com/brave/libchromiumcontent/commit/a94f0b71bff03ae49929d9ecdfa0b511968df5f9
If it works then I'll upstream to atom/libchromiumcontent

**Comment by zcbenz** [comment]
I would like to find out the root cause first, if we have a bad configuration making electron load with wrong symbols, we might have bigger troubles.

**Comment by bbondy** [comment]
Wouldn't delay loading not solve the problem if the code is hit? Whereas this gracefully handles even if it is called?

**Comment by zcbenz** [comment]
This function is only called on Windows >= 8.

**Comment by bbondy** [comment]
OK I guess Chrome will notice first if that's ever not the case.
