### ISSUE TITLE
electron does nothing

### ISSUE THREAD

**Issue by freakypie** [atom/electron#4771]
* Electron version:0.37.0
* Operating system: windows 7

running electron does nothing as far as i can tell

> /c/GitHub/sandbox (master) $ electron .
> (no output)
> /c/GitHub/sandbox (master) $ electron --help
> (no output)

**Comment by zcbenz** [comment]
This is a duplicate of #4770.

**Comment by freakypie** [comment]
I'm not sure that #4770 is related. I don't get any popups, or any windows at all.

**Comment by ejoebstl** [comment]
1 Up. Not related to #4770.

**Comment by ejoebstl** [comment]
*Heads up* 

Electron and nightmare run nicely on native windows. You can work with them without using Bash for Windows.

**Comment by brenca** [comment]
[This](https://github.com/Microsoft/BashOnWindows/issues/333) might be relevant
