### ISSUE TITLE
Electron Process Hanging Around After Quit or Exit

### ISSUE THREAD

**Issue by ddxdental** [atom/electron#4781]
Hi there,

I'm early on in a first electron project and just started doing some cross platform testing on Windows.  Like in tickets #405, I'm seeing my processes being left around.  To be sure, I am calling `app.quit()` (or `app.exit(0)`) on `window-all-closed`.  Like ticket #2209, I too have the crash reporter enabled, but removing changed nothing.

Following closing my render process window, a function is called that does some clean up and then calls `app.quit()`.  The `will-quit` event is then fired, followed by the `quit` event (with an exists status code of `0`)

Process Explorer is showing the two processes remaining:

```
Z:\ddx-desktop-win\node_modules\electron-prebuilt\dist\electron.exe   ./app --env=test --debug
 - "Z:\ddx-desktop-win\node_modules\electron-prebuilt\dist\electron.exe" --type=gpu-process --channel="5820.0.1402297762\1710269043" --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=3,11,25,54 --gpu-vendor-id=0x80ee --gpu-device-id=0xbeef --gpu-driver-vendor="Oracle Corporation" --gpu-driver-version=5.0.16.0 /prefetch:2
```

* Electron version: 0.37.0
* Operating system: Win 10 64 bit running in a virtualbox VM on a Linux host

Any tips?

Mike

**Comment by zcbenz** [comment]
I'm merging this to #4767, it would be very helpful if you can provide a reproducible example.

**Comment by mhutter** [comment]
Here is a reproducible example:

Code: see https://github.com/mhutter/electron-win-test

Built on CentOS 7 with `node v5.10.1` and `elctron-packager 6.0.1`.

Built with:

    electron-packager . --platform=win32 --arch=x64 --ignore=node_modules --out=target

In Windows (8.1 Enterprise), double-click the EXE. Task Manager shows 3 processes named `Win Test.exe` with description `Electron`.
Close the App, using either Alt+F4 or clicking the `X` button. Task Manager shows 2 processes named `Win Test.exe`.
