### ISSUE TITLE
Find the match index on found-in-page events

### ISSUE THREAD

**Issue by subwaymatch** [atom/electron#4782]
* Electron version: v0.36.10
* Operating system: Windows 7

I'm trying to emulate Chrome's "find in page" functionality in `<webview>` elements. I am wondering if there is any way to get the index of the match. When using `<webview>.findInPage(text[, options])`, the result object returns number of matches, but does not contain the index of match (please refer to the excerpt of `<webview>`'s documentation at the bottom.  

App I'm working on
![image](https://cloud.githubusercontent.com/assets/1064036/13729212/47709b72-e973-11e5-8507-68cedc763dd0.png)

Chrome "Find in page" section
![image](https://cloud.githubusercontent.com/assets/1064036/13729208/39e9b4a2-e973-11e5-8f0c-7892208ea195.png)

## Event: 'found-in-page'
Returns:
- `result` Object
- `requestId` Integer
- `finalUpdate` Boolean - Indicates if more responses are to follow.
- `matches` Integer (optional) - Number of Matches.
- `selectionArea` Object (optional) - Coordinates of first match region.

from `<webview>` documentation
https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md

Thanks for the help.

**Comment by philfreo** [comment]
@subwaymatch Would you care to open source (even if it's not fully polished) your version of implementing a "find in page" in Electron similar to Chrome's functionality? It would be very much appreciated!
