### ISSUE TITLE
Webviews not rendering

### ISSUE THREAD

**Issue by PalmerAL** [atom/electron#4783]
* Electron version: 0.37.1
* Operating system: OS 10.11.3

In my app, I have several webviews that are hidden (using display:none), and then shown (by removing the display:none). Since upgrading to electron 0.37.1, the webviews frequently don't render after they are hidden and then shown. They still take up the right amount of space, and the devtools still show the page source, but the webview is just a blank white square. When the webview is reloaded, the page is rendered again. This worked fine in 0.36.x.

Unfortunately, I don't have any steps to reproduce yet. I'll try and see if I can come up with a testcase that shows the issue.

**Comment by flexpaper** [comment]
Try avoiding using display:block on them when you want to re-show them. Set their display to 'flex' instead and it should work fine

**Comment by PalmerAL** [comment]
Thanks, but I don't use display:block. I have some CSS like this:

```
[hidden] {
     display: none !important;
}
```
To show and hide the webview, I add and remove the ```hidden``` attribute. When the webview is supposed to be shown, there are no styles changing the display other than the ```display:flex``` that electron uses as the default.

**Comment by PalmerAL** [comment]
I think I can reproduce this by hiding, and then showing, the webview between when the ```did-start-loading``` and ```did-stop-loading``` events occur.

**Comment by zcbenz** [comment]
A reproducible example would help here.

**Comment by baconface** [comment]
Likely caused by the upstream. [More information](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-apps/gscfpSCKFtQ)

**Comment by christoth** [comment]
I had the same problem with rendering issues when trying to hide a webview using display:none, probably caused by the upstream issue mentioned above.

Try hiding with with a style using "width: 0px; height:0px;" and avoid hidden and display:none.

**Comment by PalmerAL** [comment]
Thanks for the sugggestions! Using ```visibility:hidden``` appears to solve the issue. After adding this, I haven't seen the issue reoccur.
