### ISSUE TITLE
New lines aren't respected in Developer Tools console

### ISSUE THREAD

**Issue by jerone** [atom/electron#4784]
The console from the Developer Tools isn't respecting new lines in executed JavaScript. 

For example the following line of code:
```js
"a\nb"
```
Should result in:
```js
"a
b"
```
Actual result:
```js
"a b"
```

This works as intended on Google Chrome Version 48.0.2564.116 m and 49.0.2623.87 m.

***

* _Electron version: the one from Atom 1.6.0-beta7 :)_
* _Operating system: Windows 7 64x_

**Comment by zcbenz** [comment]
This is working in 0.37.1.

**Comment by jerone** [comment]
Thanks for verifying.
