### ISSUE TITLE
Deprecated require syntax compatibility broken in Electron 0.36.11

### ISSUE THREAD

**Issue by 50Wliu** [atom/electron#4785]
* Electron version: 0.36.11
* Operating system: Shouldn't matter, but Windows 10 x64 for me

#4722 appears to have broken the deprecated way of requiring Electron modules: `require('shell')`.  Here's an example: https://travis-ci.org/atom/atom/jobs/115624105#L250

The require paths should be updated so that backwards compatibility is maintained.

**Comment by zcbenz** [comment]
Actually this is caused by `module-cache` still using old path:
https://github.com/atom/atom/blob/41161dd462a1be9073752a34b4809612f933da6e/src/module-cache.coffee#L205

**Comment by 50Wliu** [comment]
Awesome, thanks for the update and sorry for opening on the wrong repo.
