### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by hysci** [atom/electron#4789]
* Electron version: 0.37.1
* Operating system: Windows 7

I tried to run the examples at https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md, when I executed command "electron main.js", I got error messages: "Uncaught TypeError: Cannot read property 'on' of undefined".

**Comment by hysci** [comment]
This only happens when one tried to include main.js into html page file.

**Comment by arieldf** [comment]
Did you manage to solve this? I have the same problem - would be very grateful if you could respond.

**Comment by Hum4n01d** [comment]
@arieldf Same. I’m getting this when running an Electron app from within Atom
