### ISSUE TITLE
Javascript codes can not receive `message` event from pepper plugin

### ISSUE THREAD

**Issue by minggo** [atom/electron#4794]
* Electron version: 0.37.1
* Operating system: Mac OS X 10.11.2 

As helped by #3794, i can load `hello.so` pepper plugin, and native module can receive message from JS, but JS can not receive `message` event from native client.

My JS code in `html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello</title>

    <script type="text/javascript">
    HelloTutorialModule = null;  // Global application object.
    statusText = 'NO-STATUS';

    // Indicate load success.
    function buttonClick() {
      HelloTutorialModule = document.getElementById('hello');
      HelloTutorialModule.postMessage('hello');
    }

    function handleMessage(message_event) {
      console.log('handleMessage');
      alert(message_event.data);
    }

  </script>

  </head>
  <body>

    <div id="listener">
      <script type="text/javascript">
        var listener = document.getElementById('listener');
        listener.addEventListener('message', handleMessage, true);
      </script>
    </div>

    <button id='button1' name='click-me' onclick="buttonClick()">Click me</button>
      
    <embed width="0" height="0"
        id="hello"
        type="application/x-hello" />
        
  </body>
</html>

```

and c++ codes:

```c++

namespace {
const char* const kHelloString = "hello";
const char* const kReplyString = "hello from Nacl";
}

...

  virtual void HandleMessage(const pp::Var& var_message) {
    if (!var_message.is_string())
      return;

    std::string log("get message from js: ");
    log.append(var_message.AsString());
    LogToConsole(PP_LOGLEVEL_LOG, pp::Var(log.c_str()) );

    std::string message = var_message.AsString();
    pp::Var var_reply;
    if (message == kHelloString) {
      var_reply = pp::Var(kReplyString);
      PostMessage(var_reply);
    }
  }
};
```

**Comment by minggo** [comment]
@rmsmith Have you met the same issue?

**Comment by rmsmith** [comment]
@minggo messaging from Pepper to Javascript is working fine for me.

I think maybe this code is your problem:

```
var listener = document.getElementById('listener');
listener.addEventListener('message', handleMessage, true);
```

On the Javascript side, you should register the 'message' event listener on the `<embed>` element.

Hope that helps,

**Comment by minggo** [comment]
@rmsmith
I got these codes from nacl SDK demo. I am new to nacl developing. Could you share me your solution?

Thanks.

**Comment by minggo** [comment]
PS: And these codes works on Chrome.

**Comment by minggo** [comment]
> When JavaScript posts a message to the Native Client module, the Pepper HandleMessage() function is invoked on the module side. Similarly, the Native Client module can post a message to JavaScript, and this message triggers a JavaScript event listener for message events in the DOM.

I read the content from [nacl message system](https://developer.chrome.com/native-client/devguide/coding/message-system). It seems Electron doesn't support the message system.

**Comment by rmsmith** [comment]
@minggo the example plugin attached in issue #3794 posts a message from Pepper to Javascript actually, so you can just build and run that to see this working.

Like I said above, you should register the 'message' event listener on the `<embed>` element, or higher up in the tree.  In the link you gave to the nacl documentation, they have:

```
// The NaCl module embed is created within the listenerDiv
var listenerDiv = document.getElementById('listener');
```

So in their example they are placing the `<embed>` as a child of the `listenerDiv` which means the `message` event will bubble up.  In your example code this is not the case (your `listener` div is a sibling of the `embed`) so it never receives that event.

**Comment by minggo** [comment]
@rmsmith Yep, it works if i registered to `embed`. Thanks.
