### ISSUE TITLE
Electron crashed on IPC write?

### ISSUE THREAD

**Issue by frozeman** [atom/electron#4799]
* Electron version: 0.36.9
* Operating system: OSX

Electron crashed, in connection with an IPC write?

https://gist.github.com/frozeman/3ba4d3cc3ad66ea34dad

**Comment by zcbenz** [comment]
Does it happen for recent versions of Electron? And are you able to make a reproducible test case for this?

**Comment by zcbenz** [comment]
Closing until more information is provided.
