### ISSUE TITLE
globalshortcut.register throws an object has been destroyed error

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4800]
* Electron version: `0.37.2`
* Operating system: `OS X`

When using the `globalShortcut.register` method in a ternary expression you get the error

```js
Object has been destroyed
```

```js
// As an example this code breaks
(win ? keyRegisterFn : globalShortcut.register)('MediaPreviousTrack', () => {
    // Do things
});

// But this code is fine
(globalShortcut.register)('MediaPreviousTrack', () => {
    // Do things
});
```

**Comment by kevinsawicki** [comment]
Are you running this code in a main process or a renderer process?

I'm having a little trouble reproducing this, would you be able to provide a `main.js` file that demonstrates this behavior? Thanks!

**Comment by MarshallOfSound** [comment]
This code is in the main process, I'll try spin up a super low level example

**Comment by MarshallOfSound** [comment]
@kevinsawicki 

Here is a minimum demo of the error
https://gist.github.com/MarshallOfSound/b4d2b36f188c8fbca85d

The error occurs on line 20  
https://gist.github.com/MarshallOfSound/b4d2b36f188c8fbca85d#file-main-js-L20

**Comment by MightyPork** [comment]
Tried it... 

This crashes:

```js
let keyRegisterFn = globalShortcut.register

keyRegisterFn('MediaPreviousTrack', () => {
    console.log('a');
});
```

This is fine:

```js
let keyRegisterFn = (...x) => globalShortcut.register(...x)

keyRegisterFn('MediaPreviousTrack', () => {
    console.log('a');
});
```

It's not about a ternary operator at all.

**Comment by zcbenz** [comment]
This code:

```js
(win ? keyRegisterFn : globalShortcut.register)('MediaPreviousTrack', () => {
});
```

is equivalent to something like this:

```js
let fn = globalShortcut.register;
fn('MediaPreviousTrack', () => {
});
```

Which is calling an object's method while replacing `this` with another object, so it is not a bug when it doesn't work in this case.

**Comment by MarshallOfSound** [comment]
@zcbenz Fair enough, the error message is just a bit obscure :+1: 

I'm guessing then (untested yet) that 

```js
(win ? keyRegisterFn : globalShortcut.register.bind(globalShortcut))('MediaPreviousTrack', () => {
});
```

would work
