### ISSUE TITLE
tray.setContextMenu closes the tray menu

### ISSUE THREAD

**Issue by leonardodino** [atom/electron#4801]
* Electron version:  electron-prebuilt@0.37.2
* Operating system: OS X 10.9.5

Is it possible to **update the tray menu without closing it**? It's useful for displaying live metrics, and states, or getting responses inside the tray menu. 

Also, I'm using an immutable backend, so mutating the original object feels somewhat contorted, and  it won't work on linux, as described on #1473.

Thanks! :smile:

**Comment by zcbenz** [comment]
Currently we don't support updating menu's state dynamically, you can track it at #4685.
