### ISSUE TITLE
 The system cannot find message text for message number 0x%1 in the message file for %2

### ISSUE THREAD

**Issue by randianb** [atom/electron#4808]
* Electron version: 0.36.7
* Operating system:win7 32

**Comment by kevinsawicki** [comment]
@randianb Can you include a code sample that demonstrates the behavior you are seeing? Thanks.

**Comment by randianb** [comment]
I have solved the problem.  Version problem, node-gyp rebuild --target=0.36.7 --arch=ia32 --dist-url=https://atom.io/download/atom-shell ,Thanks !
