### ISSUE TITLE
webview freeze on reload after execute new Audio.

### ISSUE THREAD

**Issue by yukixz** [atom/electron#4809]
* Electron version: 0.36.10
* Operating system: Linux x64

Reproduce:
1. Create a electron app with a webview only.
e.g. https://github.com/yukixz/electron_test_app
2. Execute `$('webview').reload()` in console to make sure reload work.
3. Execute `new Audio("https://img.mengniang.org/common/7/70/Akatsuki01.mp3")`
4. Execute `$('webview').reload()` again. 
The webview content is reloaded and even can interact, but its display is frozen.

Screenshot may help.
![screenshot_20160315_165558](https://cloud.githubusercontent.com/assets/3337921/13772441/2b6719c6-eacf-11e5-808b-1e305962302e.png)
![screenshot_20160315_165612](https://cloud.githubusercontent.com/assets/3337921/13772446/3314ec16-eacf-11e5-8c78-9f2b39bb966d.png)

**Comment by kevinsawicki** [comment]
Have you tried this on Electron 0.37.x yet?

**Comment by yukixz** [comment]
Cannot reproduce on 0.37.2.
