### ISSUE TITLE
Is there any way to open a channel between the application and the executed code in a webview ?

### ISSUE THREAD

**Issue by azain** [atom/electron#4810]
* Electron version: 0.37.3
* Operating system: Window7

Today I found out about the[ webview tag](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md), and it's awesome! I noticed that I can execute JS code on the page inside this webview, which is very cool, but is there a way to COMMUNICATE with this code ? Can I send/receive message between the application and the opened web page ? Like the way it's with browsers plugins development; you can embed a_ content script_, and talk to it through a custome channel.

Like in [Chrome](https://developer.chrome.com/extensions/content_scripts).
Any thoughts ?

**Comment by kevinsawicki** [comment]
Have you tried using the `send` method on the `<webview>` tag?

http://electron.atom.io/docs/v0.37.2/api/web-view-tag/#webviewsendchannel-arg1-arg2-
