### ISSUE TITLE
Signed and packaged mas version crashes on startup

### ISSUE THREAD

**Issue by herrmannplatz** [atom/electron#4813]
* Electron version: 0.37.2
* Operating system: OS X 11.11.1

I experienced that when packaging and signing the newest electron version the app will crash immediately after startup. I found a similar issue on the nw project. 

see: https://github.com/alexeyst/node-webkit-macappstore/issues/4

```
[92235:0315/141659:FATAL:process_singleton_posix.cc(215)] Check failed: path.length() < arraysize(addr->sun_path). Socket path too long: /var/folders/y3/v17xjx292n79984hn36rs_gm0000gn/T/com.herrmannplatz.demo.app/.org.chromium.Chromium.cmUTRw/SingletonSocket
```

**Comment by kevinsawicki** [comment]
This seems somewhat similar to https://github.com/atom/electron/issues/4688 in terms of the socket path being too long

**Comment by herrmannplatz** [comment]
Indeed. Thanks will keep an eye on this issue.

**Comment by romannurik** [comment]
I'm now running into this issue for non-MAS builds (platform=darwin in `electron-packager`) :-/
