### ISSUE TITLE
Build fails with clang issue

### ISSUE THREAD

**Issue by capouch** [atom/electron#4819]
* Electron version: fresh clone of master repo
* Operating system: Linux 

I got the same error when building twice, first on a long-maintained tree and second on a fresh checkout.  So I think it's a miscue somewhere in the build system; appears to be related to a clang configuration issue.  

** snip **
[48/1171] LINK dump_syms
FAILED: /usr/src/electron/vendor/llvm-build/Release+Asserts/bin/clang++ --sysroot=/usr/src/electron/vendor/debian_wheezy_amd64-sysroot -L/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/lib/x86_64-linux-gnu -L/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu -L/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -Wl,-rpath-link=/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib -Wl,-rpath-link=/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib -m64 -o dump_syms -Wl,--start-group obj/vendor/breakpad/src/common/dwarf/dump_syms.bytereader.o obj/vendor/breakpad/src/common/dump_syms.dwarf_cfi_to_module.o obj/vendor/breakpad/src/common/dump_syms.dwarf_cu_to_module.o obj/vendor/breakpad/src/common/dwarf/dump_syms.dwarf2diehandler.o obj/vendor/breakpad/src/common/dwarf/dump_syms.dwarf2reader.o obj/vendor/breakpad/src/common/dump_syms.dwarf_line_to_module.o obj/vendor/breakpad/src/common/dump_syms.language.o obj/vendor/breakpad/src/common/linux/dump_syms.crc32.o obj/vendor/breakpad/src/common/linux/dump_syms.dump_symbols.o obj/vendor/breakpad/src/common/linux/dump_syms.elf_symbols_to_module.o obj/vendor/breakpad/src/common/linux/dump_syms.elfutils.o obj/vendor/breakpad/src/common/linux/dump_syms.file_id.o obj/vendor/breakpad/src/common/linux/dump_syms.linux_libc_support.o obj/vendor/breakpad/src/common/linux/dump_syms.memory_mapped_file.o obj/vendor/breakpad/src/common/dump_syms.module.o obj/vendor/breakpad/src/common/dump_syms.stabs_reader.o obj/vendor/breakpad/src/common/dump_syms.stabs_to_module.o obj/vendor/breakpad/src/tools/linux/dump_syms/dump_syms.dump_syms.o -Wl,--end-group  
/usr/bin/ld: this linker was not configured to use sysroots
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[48/1171] ACTION js2asar: js2asar_0392be9f172cf3349ee72b664a8d8a19
ninja: build stopped: subcommand failed.

**Comment by capouch** [comment]
Build now fails at a different place.  Output follows:

* snip **
ninja: Entering directory `out/D'
[32/1126] CXX obj/vendor/brightray/bro...nux/brightray.libnotify_notification.o
FAILED: /usr/src/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/vendor/brightray/browser/linux/brightray.libnotify_notification.o.d -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DDISABLE_NACL -DTOOLKIT_VIEWS -DUSE_AURA -DUSE_X11 -DUSE_NSS_CERTS -DUSE_NSS -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUG -DCOMPONENT_BUILD -DGURL_DLL -DSKIA_DLL -DUSING_V8_SHARED -DWEBKIT_DLL -I../../vendor/brightray -I/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/src -I/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/src/skia/config -I/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/src/third_party/skia/include/core -I/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/src/third_party/mojo/src -I/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/src/third_party/WebKit -I/usr/src/electron/vendor/brightray/vendor/download/libchromiumcontent/shared_library/gen -pthread -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/gtk-2.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib64/gtk-2.0/include -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/pango-1.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/atk-1.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/cairo -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/pixman-1 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/libdrm -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/pango-1.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/freetype2 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/libpng16 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/freetype2 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/libpng16 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/harfbuzz -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/gdk-pixbuf-2.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/libpng16 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/gconf/2 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/dbus-1.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib64/dbus-1.0/include -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib64/glib-2.0/include -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/nss -I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/nspr -Wno-deprecated-register -Wno-sentinel --sysroot=/usr/src/electron/vendor/debian_wheezy_amd64-sysroot -m64 -march=x86-64 -std=c++11 -Wno-reserved-user-defined-literal -D__STRICT_ANSI__ -fno-rtti  -c ../../vendor/brightray/browser/linux/libnotify_notification.cc -o obj/vendor/brightray/browser/linux/brightray.libnotify_notification.o
In file included from ../../vendor/brightray/browser/linux/libnotify_notification.cc:5:
In file included from ../../vendor/brightray/browser/linux/libnotify_notification.h:8:
In file included from ../../vendor/brightray/browser/linux/libnotify_loader.h:9:
In file included from /usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/libnotify/notify.h:25:
In file included from /usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/glib-2.0/glib.h:32:
In file included from /usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/glib-2.0/glib/galloca.h:34:
/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/include/glib-2.0/glib/gtypes.h:34:10: fatal error: 'glibconfig.h' file not found
#include <glibconfig.h>
         ^
1 error generated.

**Comment by mitchhentges** [comment]
Two things:
Use ``` around your output, it makes it easier to read.
Your missing `glibconfih.h`, look at the end of the build output. How to get it depends on your Linux distro.

For future reference, when a build fails, check the first couple lines and the last couple lines, because that's where the important error would be

**Comment by deepak1556** [comment]
@capouch seems like an issue with `pkg-config` step, somehow files are being included from `lib64` dir `I/usr/src/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib64/glib-2.0/include` which shouldnt exist.  Can you paste the output of running the following command in electron folder

```
❯ ./tools/linux/pkg-config-wrapper ./vendor/debian_wheezy_amd64-sysroot x64 lib --cflags libnotify
``` 

Which distro might this be ?

**Comment by capouch** [comment]
$ ./tools/linux/pkg-config-wrapper ./vendor/debian_wheezy_amd64-sysroot x64 lib --cflags libnotify
    -pthread -I./vendor/debian_wheezy_amd64-sysroot/usr/include/gdk-pixbuf-2.0 -I./vendor/debian_wheezy_amd64-sysroot/usr/include/libpng16 -I./vendor/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I./vendor/debian_wheezy_amd64-sysroot/usr/lib64/glib-2.0/include

It's Slackware-64-current, installed during December 2015.

**Comment by zcbenz** [comment]
> /usr/bin/ld: this linker was not configured to use sysroots

Your linker doesn't support sysroot, I suggest upgrading the build toolchains in your system by installing latest clang.

**Comment by capouch** [comment]
@deepak1556 Can you suggest how I could compensate for this issue, which is still preventing me from building electron?  I have been able to build on CentoOS, but not Slackware, and I don't have the chops to figure out where in the build system to remove the errant #include.

**Comment by deepak1556** [comment]
I havnt tried building on slackware, my concern is how much does `pkg-config` respect `PKG_CONFIG_LIBDIR` vs `PKG_CONFIG_PATH` on this system. You could try setting `PKG_CONFIG_PATH` to the following.

```shell
$ export ELECTRON_SYSROOT=/path/to/electron/vendor/debian_wheezy_amd64-sysroot
$ export PKG_CONFIG_PATH=$ELECTRON_SYSROOT/usr/lib/pkgconfig:$ELECTRON_SYSROOT/usr/share/pkgconfig
```

If the glib-2.0.pc in sysroot got picked up everything should work fine. I am not sure why it doesnt even when `PKG_CONFIG_LIBDIR` is specified. I will try to setup a slackware sometime in the next few days.

**Comment by capouch** [comment]
@deepak1556 that worked perfectly!!  Thanks.

**Comment by evgeniyzinoviev** [comment]
I have the same problem on Gentoo, and

**Comment by evgeniyzinoviev** [comment]
I have the same problem on Gentoo
```
$ ./script/build.py -c D
ninja: Entering directory `out/D'
[1/117] SOLINK lib/libnode.so
FAILED: if [ ! -e lib/libnode.so -o ! -e lib/libnode.so.TOC ]; then /home/evgeny/dev/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,noexecstack -Wl,--whole-archive  -Wl,--no-whole-archive -pthread --sysroot=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/lib/x86_64-linux-gnu -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib -m64 -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.TOC; else /home/evgeny/dev/electron/vendor/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-z,noexecstack -Wl,--whole-archive  -Wl,--no-whole-archive -pthread --sysroot=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/lib/x86_64-linux-gnu -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib -Wl,-rpath-link=/home/evgeny/dev/electron/vendor/debian_wheezy_amd64-sysroot/usr/lib -m64 -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.tmp && if ! cmp -s lib/libnode.so.tmp lib/libnode.so.TOC; then mv lib/libnode.so.tmp lib/libnode.so.TOC ; fi; fi
/usr/bin/ld: this linker was not configured to use sysroots
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Any ideas what can be wrong? No luck with suggestions by @deepak1556 :(

**Comment by yunzhenhuan** [comment]
![image](https://user-images.githubusercontent.com/15715661/31593975-a45a1eec-b264-11e7-9f9f-6ab69d2dea59.png)
I have the same problem.But Why?
