### ISSUE TITLE
WebView - Blank(WhiteScreen) after sign OSX app MAS

### ISSUE THREAD

**Issue by kasik96** [atom/electron#4820]
* Electron version: v0.35.4
* Operating system: Mac OS X

Hi, i use Mac App Store Submission Guide to Submit my app to Mac App Store, it work, but after i Sign app it shows only loading(my loading) and after that WebView is blank, never loads. But loading hides after event "did-finish-load", so i think it loads webpage, but doesnt show it, just white screen. Any help? Thanks :)

**Comment by jarek-foksa** [comment]
Related bug: https://github.com/atom/electron/issues/3871

**Comment by zcbenz** [comment]
I'm merging this to #3871.
