### ISSUE TITLE
Can not stop at break point in devtools after refresh a window for v0.37.+

### ISSUE THREAD

**Issue by jwu** [atom/electron#4822]
* Electron version: v0.37.2
* Operating system: Mac OSX

Step:

 - Open a window
 - Open the devtools(detached) for it
 - Set some break point that you sure it will break in some action
 - Refresh the window
 - try to break on the point

It can not break unless you close the devtools and open it again.

**Comment by felixrieseberg** [comment]
This is probably related to #4842

**Comment by zcbenz** [comment]
I'm merging this to #4842.
