### ISSUE TITLE
Can only load one pepper plugin

### ISSUE THREAD

**Issue by minggo** [atom/electron#4824]
* Electron version: 0.37.1
* Operating system: Mac OS X 10.11.2

As said in title, electron can only load one pepper plugin. If i load more than one pepper plugin, then only the lasted loaded pepper plugin takes effect.

**Comment by deepak1556** [comment]
How are you loading the plugins ? `register-pepper-plugins` need to be provided with a comma separated values of plugins to be loaded. Tested with,

```
app.commandLine.appendSwitch('register-pepper-plugins','<path to plugin1>;<mimetype>, <path to plugin2>;<mimetype>');
```

Also there is a limit to number of plugins that can be registered from commandline, which is [64](https://code.google.com/p/chromium/codesearch#chromium/src/content/common/pepper_plugin_list.cc&sq=package:chromium&l=25&rcl=1458199924)

**Comment by minggo** [comment]
@deepak1556 Oh, i misunderstood. I used `app.commandLine.appendSwitch` to register two plugins.
