### ISSUE TITLE
How to upload local file?

### ISSUE THREAD

**Issue by zgc2537** [atom/electron#4826]
* Electron version: 0.36.9
* Operating system: Windows7

I use the electron to load my remote url.I modify the remote website, when function require is not undefined, i load the additional js file which can run in the electron enviroment. I want to upload local audio file to the server by absolute address, rather than using input control to select the file. I only can get the raw data by using readFile method of fs. But only file object can be as parameter for $.ajax.

How can i do? How can i upload the local file? thx.

main.js:
```javascrip
mainWindow.loadUrl('http://XXX.XXXX.COM/');
```

**Comment by kevinsawicki** [comment]
You can use a library like [request](https://github.com/request/request)` to send the file/stream from the `fs` APIs to your server.

Here is a simple example from the README:

```js
request('http://google.com/doodle.png').pipe(fs.createWriteStream('doodle.png'))
```

Closing this out.
