### ISSUE TITLE
Support WebView.setBackgroundColor

### ISSUE THREAD

**Issue by Aluxian** [atom/electron#4827]
* Electron version: Any??
* Operating system: Any??

This is where I found out about it: https://developer.chrome.com/multidevice/webview/tipsandtricks

**Comment by Aluxian** [comment]
I've just found https://github.com/atom/electron/issues/1397, I think it's a duplicate of that...

**Comment by deepak1556** [comment]
@zcbenz with css background style working now for `webview` tag, is this method required ?

**Comment by Aluxian** [comment]
Probably not. I'll check how the latest version works when I update.

**Comment by zcbenz** [comment]
@deepak1556 You are right, setting the background color with CSS would do the job.
