### ISSUE TITLE
Is there a print API for OS X? I am looking for a basic PDF viewer/print support in Electron.

### ISSUE THREAD

**Issue by hp011235** [atom/electron#4830]
I have looked through various discussions here and found that the most feasible solution to have a pdf viewer is pdf.js and print through that.

However, I looked at this thread https://github.com/atom/electron/issues/865 and got to know that Electron does support printing in Windows, but not sure whether it supports pdf viewer for the same or not. Do we have a similar support in OS X as well?

* Electron version: electron v0.36.0
* Operating system: 10.10.5

Thanks in advance,
-Hetal

**Comment by kevinsawicki** [comment]
Have you tried the `printToPDF` API?

http://electron.atom.io/docs/v0.37.2/api/browser-window/#winprinttopdfoptions-callback

http://electron.atom.io/docs/v0.37.2/api/web-contents/#webcontentsprinttopdfoptions-callback

**Comment by hp011235** [comment]
Thanks for your prompt reply Kevin. I haven't tried it yet. Let me give it a shot.

**Comment by kevinsawicki** [comment]
Okay, closing this out.
