### ISSUE TITLE
Does not allow input on Password box for TweetDeck/Twitter Web

### ISSUE THREAD

**Issue by MehediH** [atom/electron#4832]
* Electron version: latest version
* Operating system: Windows 10

So it seems like you can't input inside a password box on TweetDeck login box or Twitter Web login box. I tried testing it with loadURL() and WebView, but none seem to work.

https://twitter.com/Jamacanbacn/status/710164499278503938

**Comment by jamesbroadhead** [comment]
confirmed. the url to try is https://twitter.com/login
console: "Uncaught ReferenceError: jQuery is not defined"

**Comment by MehediH** [comment]
Damn, hopefully someone from the Electron team will address this issue asap. My app is broken right now cause of this :(

**Comment by jlord** [comment]
This is an issue with how jQuery sets itself as global. There is more information on it in #254.

One thing you can do is set `nodeIntegration: false` on the browser window that is loading these login screens. This enables jQuery to pick the right environment and work as expected.

```js
window = new BrowserWindow({width: 800, height: 600, nodeIntegration: false});
```

Another option would be to preload jQuery.

**Comment by MehediH** [comment]
It worked! Thanks a lot!
