### ISSUE TITLE
Is there a way to run a headless electron instance with selenium web driver?

### ISSUE THREAD

**Issue by vladnicula** [atom/electron#4834]
I started a little bit of a journey to figure out if I can use[ `nightwatchjs`](https://github.com/nightwatchjs) to run selenium tests. Knowing about [`nightmarejs`](https://github.com/segmentio/nightmare) - another test runner that runs a headless version of electron to run its tests - I wondered if I could run my selenium tests against electron. 

I was able to run electron with the chrome driver, as indicated in the [electron docs](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md#using-selenium-and-webdriver), but couldn't figure out how to make it headless. It seems that the `binary` option in the configuration that needs to be passed down to selenium cannot use `xvfb-maybe`, it needs the actual binary. 

Any thoughts on this? Could it be achieved? 

PS: [Link to the nightwatchjs discussion](https://github.com/nightwatchjs/nightwatch/issues/856)

**Comment by kevinsawicki** [comment]
You could give `binary` a wrapper script or program that sets things up and then launches the app.

That is what [spectron](https://github.com/kevinsawicki/spectron) uses to pass in custom arguments and environment variables to Chromedriver.

https://github.com/kevinsawicki/spectron/blob/master/lib/launcher.js

**Comment by paulcbetts** [comment]
@vladnicula Run nightmarejs itself under `xvfb-maybe`
