### ISSUE TITLE
Icon not showing up in Ubuntu's launcher

### ISSUE THREAD

**Issue by alexcheninfo** [atom/electron#4835]
* Electron version: Electron prebuilt 0.37.2
* Operating system: Ubuntu 15.10

As you can see in this screenshot I have everything set, still the icon isn't showing on Ubuntu's launcher:

![screenshot from 2016-03-17 00-26-45](https://cloud.githubusercontent.com/assets/1061237/13846537/c9879e00-ec82-11e5-8aa7-bdf95f88d887.png)

I tried everything:

- The usual way:

```
var iconPath = path.join(__dirname, 'icon.png')
app.on('ready', function () {
  var mainWindow = new BrowserWindow( {
    icon: iconPath,
```

- Using `electron-packager`:  `electron-packager . MyApp --platform=linux --arch=x64 --version=0.37.2 && cp icon.png MyApp-linux-x64/atom.png`
- Even cleaning the icons' cache: `gtk-update-icon-cache /usr/share/icons/hicolor`

But nothing has worked so far. Is this a bug, or I'm doing something wrong?

**Comment by zcbenz** [comment]
On Linux you have to provide a .desktop file for your app to make sure the desktop environment can show your app's icon correctly, for more about this you can see:
https://wiki.archlinux.org/index.php/Desktop_entries

**Comment by Autre31415** [comment]
I've done some testing on this and found out icons can work under certain conditions which I detail in #6205.
