### ISSUE TITLE
Application appearing strange in the Volume Mixer

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/electron#4838]
* Electron version: `0.37.2`
* Operating system: Windows 10 x64

The applications appears really strangely in the volume mixer, it's almost as if half of it is "cut off" as you can see in the attached picture

![strangevolume](https://cloud.githubusercontent.com/assets/6634592/13849536/ad74d99e-ecaa-11e5-8d0d-5e1e44336fa1.PNG)

The volume slider is still there, but it is invisible along with the icon and half the program title.  This has been reported by many other users.  It might be worth noting that I am using the experimental audio API's such as `setSinkId`

**Comment by zcbenz** [comment]
Probably some underlying win32 API calls triggered a bug in Windows, but anyway we are not able to fix it on Electron's side.

**Comment by amgrider** [comment]
Have you tried to shorten the name in case its a formatting error caused by the long name?

**Comment by MarshallOfSound** [comment]
@zcbenz Not sure if this should be reopened / documented / fixed.  But it appears that the issue is due to Electron or Windows not re sizing a PNG image that is being used as the icon.  This image is therefore consuming a massive amount of space (1024x1024) and hiding the volume slider.

I'm not sure if scaling the image is something Electron should handle or document but I thought I'd let you know what the issue is

**Comment by MarshallOfSound** [comment]
Using a `.ico` file as the icon on windows appears to scale correctly.
