### ISSUE TITLE
Scroll bar does not work properly under Ubuntu 16.04

### ISSUE THREAD

**Issue by ZenHarbinger** [atom/electron#4844]
* Electron version:
0.37.2

* Operating system:
Ubuntu 16.04 64-bit

Using GooglePlayMusicDesktopPlayer, there is a scroll bar on the right that when mouse-overed, cannot be selected.  I can click above/below the widget to jump the screen.  I can scroll w/ the mouse wheel, but I cannot grab and manually scroll.  The scroll bar seems to expand into the window with mouse over thus blocking mouse control (not sure this is actually what is happening).

Was told to offer issue here as they did not think it was with them (GooglePlayMusicDesktopPlayer)

Did test in Windows7, did not have the same problem.

![scroll](https://cloud.githubusercontent.com/assets/1130510/13887403/f068cb2c-ed11-11e5-92eb-f20a29da6e43.png)

**Comment by kurisubrooks** [comment]
This is most likely a Chromium bug with 16.04, therefore upstream.

**Comment by ZenHarbinger** [comment]
For what it's worth, not happening any more for me.
