### ISSUE TITLE
Option for hiding inspector?

### ISSUE THREAD

**Issue by quantumproducer** [atom/electron#4855]
How do I hide the inspector that pops up by default when I run npm start?

 Electron version:  0.37.2
* Operating system: OSX

**Comment by mitchhentges** [comment]
The inspector? Can you post a screenshot?
Also, are you doing this on the quickstart? Does `npm start` actually run `electron .` in the project that you're using?

**Comment by bbondy** [comment]
You can toggle dev tools with win.toggleDevTools() or just don't call openDevTools to begin with.

Please post future questions to here though:
https://discuss.atom.io/c/electron

**Comment by mitchhentges** [comment]
Yes, if it's the Chrome "Developer Tools" inspector, that doesn't pop up by default, there is something in your app that is calling `openDevTools()`

**Comment by quantumproducer** [comment]
That was it, thank you!
