### ISSUE TITLE
session.setProxy Per Window

### ISSUE THREAD

**Issue by TomAshley303** [atom/electron#4859]
* Electron version: 0.37.2
* Operating system: Linux x64 (Or any)

Is it possible to set the proxy per window that you spawn using session.setProxy? That way I can use a different proxy server for multiple browser windows. If not that would be very desirable.

**Comment by deepak1556** [comment]
You can set corresponding session for the browser window to achieve it.

**Comment by kevinsawicki** [comment]
Thanks for the answer @deepak1556

@TomAshley303 you might want to take a look at the example here to see how to get the `session` for a `BrowserWindow`: http://electron.atom.io/docs/v0.37.2/api/session/#session

Closing this out.

**Comment by SwiTool** [comment]
Well, when I do setProxy on the second window, it also impacts the first one...
```javascript
win = new BrowserWindow({...});
win.webContents.session.setProxy({
    proxyRules: proxyRules,
    proxyBypassRules: 'localhost'
  }, () => {
    win.loadURL('file://' + __dirname + '/../browser/index.html');
})
``` 

Do you have a solution for that ?

**Comment by SwiTool** [comment]
@kevinsawicki ping
