### ISSUE TITLE
Electron application workflow

### ISSUE THREAD

**Issue by AntonYaskevich** [atom/electron#4862]
* Electron version: 0.37.2
* Operating system: Win10

There are a lot info about application (node), and render(chromium) processes in Electron. About the communication between these processes via data marshalling through IPC and separated contexts.

But there is no info about event-loop.

So there is the question. How many event loops are used in Electron: several event-loops (one for each process: app, renders) and then how does libuv work with it?; or is there one event-loop which is shared between these processes?

**Comment by kevinsawicki** [comment]
I believe it is one event loop per process and in render processes the node event loop is integrated with the Chromium event loop so `click` events and `fs` events are fired in the same event loop.

Anything else to add @zcbenz or others?

**Comment by AntonYaskevich** [comment]
@kevinsawicki, thanks a lot for ur opinion and answer. Hope @zcbenz or sm1 else will add more technical information or tell some details about event-loop's implementation in Electron.

**Comment by paulcbetts** [comment]
@kevinsawicki summed it up correctly - what are you trying to do with this information?

**Comment by AntonYaskevich** [comment]
Hi @paulcbetts,
I am just interested in architectural principles of Electron implementation. It's interesting to compare it with NW.js and understand some technical features which aren't mentioned in docs. So I thought that it's more efficient to ask some ppl from dev team about such aspects, than just look through the code in the repository to find answer on such specific question.

**Comment by AntonYaskevich** [comment]
@kevinsawicki, also I will be a participant of technical conference as speaker and want to clarify some details of Electron workflow under the hood.

**Comment by zcbenz** [comment]
There are two types of event loops in Electron: one is the event loop of Chromium, the other one is an event loop that listens for libuv's events.

You can find more information about it in the following slides:
https://speakerdeck.com/zcbenz/practice-on-embedding-node-dot-js-into-atom-editor

The logic of it is also easy to understand:
https://github.com/atom/electron/blob/master/atom/common/node_bindings.cc#L249

We did node integration in this way so there is no need to patch either Chromium or Node, and it is efficient and avoids lots of bugs. In old times of nw.js (the node-webkit age), the node integration was implemented by replacing Chromium's event event with libuv, which was quite buggy. I don't know how it goes now.

**Comment by GnorTech** [comment]
@zcbenz I can't agree with you that node-webkit's integration of Node is buggy: it integrates the renderer event loop and Node's into the same thread so the function call between the 2 worlds is made directly and efficient. While in Electron is 2 event loops in 2 different threads, when a function call is made from DOM to Node or vice versa, you have to do some thread synchronization thing like pausing one thread, or post the the function call into something like a queue and wait for the other thread to pick it up, which is inefficient.

**Comment by AntonYaskevich** [comment]
@zcbenz Thank you very much for your answer and attached links. I appreciate that.
