### ISSUE TITLE
Seems nodejs hasn't been updated for a long time

### ISSUE THREAD

**Issue by darrrk** [atom/electron#4865]
* Electron version: 0.37.2
* Operating system: any

It's strange, that no one talks about it. But nodejs 5.9.0 obviously fresh than 5.1.1

**Comment by kevinsawicki** [comment]
See https://github.com/atom/electron/blob/43cb48295bf1589f0fcbd5b1a4423b703ac467f8/docs/faq/electron-faq.md#when-will-electron-upgrade-to-latest-nodejs for more details.

The node version that pairs with Chrome 49 was recently released.

**Comment by paulcbetts** [comment]
The problem is that node.js has started taking rando V8 snapshots for their releases, so we're in the unenvious position of either creating a Frankenversion of Chromium that runs a mismatching V8, or running behind on Node versions :(
