### ISSUE TITLE
Where or How to get PACKAGE_ID for the `com.squirrel.PACKAGE_ID.YOUR_EXE_WITHOUT_DOT_EXE`?

### ISSUE THREAD

**Issue by xieranmaya** [atom/electron#4866]
* Electron version:any
* Operating system: Windows 7

I'm wondering how/where can I get the PACKAGE_ID, is it in the package.json or anywhere else or how to set it to the installer?
And how can see the generated file's `Application User Model ID`?

**Comment by paulcbetts** [comment]
> I'm wondering how/where can I get the PACKAGE_ID, is it in the package.json or anywhere else or how to set it to the installer?

It's usually your package.json `id`

> And how can see the generated file's Application User Model ID?

Open Process Explorer and look at the command line args passed to the renderer process

**Comment by xieranmaya** [comment]
Thank you very much, I've saw it from the Process Explorer

**Comment by xieranmaya** [comment]
Another question,

https://github.com/atom/electron/blob/master/docs/api/auto-updater.md#windows
>The installer generated with Squirrel will create a shortcut icon with an Application User Model ID in the format of com.squirrel.PACKAGE_ID.YOUR_EXE_WITHOUT_DOT_EXE, examples are com.squirrel.slack.Slack and com.squirrel.code.Code. You have to use the same ID for your app with app.setAppUserModelId API, otherwise Windows will not be able to pin your app properly in task bar.

Does this means that the INTALLER should have the same `Application User Model ID` with the running app instance which set in the main process by `app.setAppUserModelId`? And what is the shortcut icon means? A desktop icon or other? I have install the app but no desktop icon was created.

**Comment by kevinsawicki** [comment]
> And what is the shortcut icon means? A desktop icon or other? I have install the app but no desktop icon was created.

Yeah, a desktop shortcut and/or start menu shortcut. You have to explicitly create it by spawning `Update.exe` with the `--createShortcut` flag.

See https://github.com/atom/atom/blob/32a1d21a0debe14f159b3cbf945827d4fb7bdf30/src/browser/squirrel-update.coffee#L188-L189 for an example

**Comment by xieranmaya** [comment]
OK, thank you very much~
