### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by harrycch** [atom/electron#4867]
* Electron version: 0.36.9
* Operating system: OS X

When I do:
` mainWindow.loadURL('file://' + __dirname + '/somepath/home.html')`
if I have spaces in my app path (e.g. `file:///myPath/My Application/Application.app`    OR    `file:///myPath/Application 1.app`), the HTML is not loaded and it raises the error "Not allowed to load local resource":
<img width="280" alt="screen shot 2016-03-21 at 6 53 43 pm" src="https://cloud.githubusercontent.com/assets/16285382/13916559/4c1b065c-ef96-11e5-96ce-afb8345a838c.png">

I have tried to set `webSecurity: false` and the error disappeared but the screen is still blank without loading my HTML.
<img width="649" alt="screen shot 2016-03-21 at 6 53 07 pm" src="https://cloud.githubusercontent.com/assets/16285382/13916571/58c8116a-ef96-11e5-8414-f30bacbff631.png">

The path works for some special characters such as !@$&~*
but failed for some such as {}#%` and also whitespace

The path works when there are no spaces so the path must be correct.

**Comment by zcbenz** [comment]
I suggest using `url` module to format your URL, unlike browsers, `loadURL` doesn't accept invalid URLs.

**Comment by harrycch** [comment]
I have tried using `url.format(url.parse('file://' + __dirname + '/somepath/home.html'))` to replace `'file://' + __dirname + '/somepath/home.html'` but it still gives the error.
I see in the devTools that the path has already escaped the space to `%20` and the path works on my own google chrome browser.

**Comment by creeperyang** [comment]
I have the same problem. And it works well when run with` env:development`.

**Comment by creeperyang** [comment]
As #5107 described ( @eiriarte ), set:

```js
node: {
    __dirname: false,
    __filename: false
  }
```

Can fix this error.

**Comment by jarjis** [comment]
same error not using Webpack.

**Comment by muscaiu** [comment]
In my stupid ass case blindly following Youtube tutorial not using Webpack.
Used **semicolons** instead of **backticks** in `win.loadURL()` :)

**Comment by zackshapiro** [comment]
I'm also getting this error with webpack trying to build for production

```
mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'public/index.html'),
        protocol: 'file:',
        slashes: true
    }));
```

gives me `not allowed to load local resource: file:///public/index/html`

**Comment by zackshapiro** [comment]
I was able to fix this as @creeperyang said by adding the code above to my webpack config under the `output` object

**Comment by partha-srivi** [comment]
I faced similar issue, the app works as expected in development, but it fails to load after packaging.
I was able to fix this by specifying the name as it is in the folder (case sensitive) i.e. In app folder I created a file "InitializationPage.html" while trying to load it in browser window i specified "initializationpage.html".So, it failed. After  specifying it in browser window as "InitializationPage.html" it started working

**Comment by jeffersonxavier** [comment]
Hi @creeperyang, please, hi can I set this when I use Angular CLI?

**Comment by creeperyang** [comment]
@jeffersonxavier 

See <https://stackoverflow.com/a/42406194>, use `ng eject` to generate `webpack.config.js` and config it.

**Comment by jeffersonxavier** [comment]
@creeperyang 
Thank you so much for this, now it's works.

**Comment by dvdcxn** [comment]
Try using ```path.resolve('home.html')``` instead.

**Comment by anubhab07** [comment]
Try using path.resolve('home.html')

Angular-cli creates a folder by project name inside dist folder.
Try using
`mainWindow.loadURL('file://' + __dirname + '/dist/project-name/home.html')`
I missed this first, now it is working for me.

**Comment by cuixiping** [comment]
Use [`win.loadFile(filePath[, options])`](https://electronjs.org/docs/api/browser-window#winloadfilefilepath-options) for local files.

```
const path = require('path');
mainWindow.loadFile(path.resolve(__dirname, '/somepath/home.html'));
```

**Comment by Custardcs** [comment]
change

  mainWindow.loadFile('index.html')

to 

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
}))

add the required

const path = require('path');
const url = require('url');

**Comment by writingdeveloper** [comment]
It Works!
