### ISSUE TITLE
Document webContents.sendInputEvent({'type:'mouseWheel',... API

### ISSUE THREAD

**Issue by ignjat** [atom/electron#4868]
* Electron version: v0.37.2
* Operating system: OS X 10.11.3

Can you please document a successful call to webContents.sendInputEvent for mouseWheel event?
I tried passing in all kinds of parameters but couldn't get it to work. Thanks in advance.

**Comment by ignjat** [comment]
I still can't get it to work. It might be a bug after all.

**Comment by thyrrestrup** [comment]
You need:
type: "mouseWheel",
x: 0,
y: 0,
deltaX: 0,
deltaY: 0,
canScroll: true

**Comment by ignjat** [comment]
Doesn't work for me, obviously I try to set deltaX/deltaY to something other than 0 but it still doesn't work.

**Comment by ignjat** [comment]
Ah, finally, x/y had to be of the correct div. Appreciated.

**Comment by thyrrestrup** [comment]
Great - Just for completeness..

```javascript
element.sendInputEvent({
    type: 'mouseWheel',
    x: 0,
    y: 0,
    deltaX: 0,
    deltaY: 0,
    canScroll: true
});
```

`x, y` is the mouse position inside `element` where the scroll should occur.
`deltaX, deltaY` is the relative scroll amount.
