### ISSUE TITLE
Entering Mission Control on OS X breaks win.capturePage()

### ISSUE THREAD

**Issue by tma02** [atom/electron#4873]
* Electron version: v0.36.11
* Operating system: OS X 10.11

Upon entering Mission Control on OS X, win.capturePage() breaks and is returning an empty buffer when the window is outside of the bounds of the screen.

**Comment by zcbenz** [comment]
`capturePage` can only capture what's drawn, to achieve this we have to draw the window offscreen. I'm merging this to #228.
