### ISSUE TITLE
How do we move our electron app to show in second screen?

### ISSUE THREAD

**Issue by ahgan84** [atom/electron#4877]
Hi guys, my electron app is showing full screen in my first screen. Now how do I move it to my external screen also in full screen? I have tried the win+shift+left/right using keyboard but it doesn't work in full screen.

And I want the electron to open permanently in the second screen, so, What is the settings I have to make?

**Comment by ahgan84** [comment]
I know that visual studio C# we can write GetWindowPlacement() and SetWindowPlacement() to set the default screen for the window. Does electron have this settings?

**Comment by ahgan84** [comment]
After whole morning of trying and testing. I kinda found a solution. I set the "x" and "y" value (window positioning) of the browser window option to be in the second screen. So, every time my app will open full screen in my second screen.
Is this the best way guys? Any other better ways?

**Comment by OlsonDev** [comment]
While that may work, hardcoding the positions will incur maintenance if you ever change resolutions/monitor positions. It's best if you use the [screen API](http://electron.atom.io/docs/v0.37.2/api/screen/) and use the [`win.setBounds(...)` method](http://electron.atom.io/docs/v0.37.2/api/browser-window/#winsetboundsoptions-animate).

**Comment by zcbenz** [comment]
Thanks @OlsonDev for answering this.

#1836 also tracks a feature request that would make this easier.

**Comment by ahgan84** [comment]
Thanks @OlsonDev, next time I'll post in the community area.

**Comment by davidwang1988** [comment]
const win = new BrowserWindow(...)
const { getCursorScreenPoint, getDisplayNearestPoint } = screen

  const currentScreen = getDisplayNearestPoint(getCursorScreenPoint())
  win.setBounds(currentScreen.workArea)

**Comment by chenzhutian** [comment]
It does not work on macos when the primary screen is not the top left one, ie, I need to move the window to a negative position

**Comment by promotion-xu** [comment]
@davidwang1988 Hello, that can't work for me, I can't move window to the another virtual screen on mac

**Comment by Bug-Reaper** [comment]
I have this un-tested code where my app will try to occupy any newly detected screen. Will report back on how well this works.

```js
  screen.on("display-added",(ev,display)=>{
    const allWindows=BrowserWindow.getAllWindows();
    console.log(ev,display);
    const moveWindow=allWindows[allWindows.length-1];
    moveWindow.setBounds(display.workArea)
  })
```
