### ISSUE TITLE
Multi-process architecture

### ISSUE THREAD

**Issue by uselec** [atom/electron#4880]
Hi, I have question about Electron multi-process architecture.

For example, I created some browser and opened the 3 tabs (tab as `webview`).

When all three tabs in a single `BrowserWindow`, the Electron has 6 processes (main, gpu, render for `BrowserWindow`, and 3 renderer per-tab).

Then, I want to separate tab in the separate window. Since all of the tabs is `webview`, I dont know how to move a `webview `into a separate `BrowserWindow`. But, if I create again new `webview `in separate `BrowserWindow`, the two processes will be used (!two processess for one tab!). If, I use `BrowserWindow` as tab (without `webview`), I cant draw a window controls (adressbar, etc).

So, if user opened many tabs every in a separate window, per tab will be created two render processes (`BrowserWindow `and `webview`). It's not rational. 

If replace `webview` to `iframe `(for render in single process with `BrowserWindow`), there is no way to emulate the behavior of `webview `(disable node-integration, top level frame, web security policy, etc).

How to be?

**Comment by zcbenz** [comment]
Currently there is no way to move webviews between windows, I'm merging this to #1871.
