### ISSUE TITLE
Add support for output to framebuffer

### ISSUE THREAD

**Issue by piranna** [atom/electron#4888]
Add an option to compile Electron to be capable to work on a framebuffer. Chrome is already capable of doing this, so it would be just a matter of enabled a compile flag...

**Comment by zcbenz** [comment]
I don't know Chromium supports outputting to framebuffer directly, can you give more information about that?

**Comment by piranna** [comment]
What kind of info do you need?

**Comment by zcbenz** [comment]
Like, how to make Chromium output to framebuffer?

**Comment by piranna** [comment]
> Like, how to make Chromium output to framebuffer?

It can be achieved with the Ozone layer and the DRI driver:

https://groups.google.com/a/chromium.org/forum/#!topic/ozone-dev/QAEfjQEsemQ
https://www.chromium.org/developers/design-documents/ozone

**Comment by zcbenz** [comment]
Thanks for the information, I'm merging this to #228, which tracks the support for ozone.

**Comment by galvesribeiro** [comment]
@zcbenz does do the support to linux framebuffer got added to Electron? I don't see it in the docs... I have a specific ARM device that has no X or any kind of Window Manager and if Electron works on Framebuffer, I could use on that. Any updates on that?

Thanks

**Comment by danburzo** [comment]
As far as I understand, we're waiting on [this to happen](https://bugs.chromium.org/p/chromium/issues/detail?id=546953) before there can be any progress made on it.

**Comment by simonhochrein** [comment]
Any updates on this?

**Comment by pukichu** [comment]
Again, any updates on this?

**Comment by Tchanu** [comment]
Updates?

**Comment by willswire** [comment]
Updates?

**Comment by rdzidziguri** [comment]
any updates?

**Comment by rsmirnov90** [comment]
Would love to know too...

**Comment by Botspot** [comment]
Updates?

**Comment by Formyown** [comment]
is there any updates?

**Comment by thinkclay** [comment]
bump!

**Comment by Botspot** [comment]
Bump!

**Comment by alwinlubbers** [comment]
I would also love to see this!

**Comment by jim-king-2000** [comment]
Looking forward to seeing this. If it were developed, `electron` will prevail on embedded linux devices.
