### ISSUE TITLE
Electron Installer

### ISSUE THREAD

**Issue by danpottshimself** [atom/electron#4889]
* Electron version: latest
* Operating system: Multi-Platform

After copious research I have found no way to create an installer for the electron app I have created. At the moment it's around 120mb and really need an installer to distribute. I have tried using electron-builder to no avail and can't find anything else. Help?

Thanks in advance

**Comment by lukeapage** [comment]
https://github.com/electronjs/grunt-electron-installer
https://github.com/electronjs/windows-installer

**Comment by danpottshimself** [comment]
@lukeapage  Those seem to only cater for windows and not MAC. Additionally we have been using Gulp as our task-runner, not grunt. :(

**Comment by lukeapage** [comment]
Mac is typically distributed as a dmg

**Comment by RaghuChandrasekaran** [comment]
https://github.com/szwacz/electron-boilerplate

https://github.com/szwacz/electron-boilerplate/blob/master/tasks/release/osx.js

**Comment by sindresorhus** [comment]
- [electron-builder](https://github.com/loopline-systems/electron-builder) - Create installers.
- [electron-installer-debian](https://github.com/unindented/electron-installer-debian) - Create a Debian package.
- [electron-installer-redhat](https://github.com/unindented/electron-installer-redhat) - Create a Red Hat package.
- [electron-installer-windows](https://github.com/unindented/electron-installer-windows) - Create a Windows package.

You can find more tools here:
https://github.com/sindresorhus/awesome-electron/blob/master/readme.md#tools

**Comment by stefanjudis** [comment]
@danpottshimself

When did you try electron-builder... I'd say it's quite solid now.

**Comment by kevinsawicki** [comment]
Closing this out, thanks everyone for all the great links :+1:
