### ISSUE TITLE
System print dialog is shown instead of Print Preview dialog

### ISSUE THREAD

**Issue by RaghuChandrasekaran** [atom/electron#4890]
* Electron version: 0.36.8 and Chrome 47.0.2526.110
* Operating system: Windows 7 & Windows 10

When calling` win.webContents.print() `I expected chrome's default print preview to appear.But the system's default print dialog appeared.
What I expected was,

![print_preview](https://cloud.githubusercontent.com/assets/7160211/13983234/78392fa0-f114-11e5-9257-77155856d54c.png)

But instead the invoked dialog box was,

![print](https://cloud.githubusercontent.com/assets/7160211/13983245/8ada8f46-f114-11e5-8c71-791758e19519.png)

1. Is this the expected behaviour of print function?
2. If so is there any workaround to get the print preview window?

Edit:
I tried in both windows 10 & windows 7.I'll update after trying the same in Ubuntu.

**Comment by felixrieseberg** [comment]
You're not running Chrome - Electron uses the rendering engine, but few of the Chrome APIs. Not all of them are open source to begin with.

**Comment by RaghuChandrasekaran** [comment]
@felixrieseberg Thank you for the clarification.Since electron is based on Chromium I assumed there must be some way to enable the print-preview option like this one mentioned [here].(https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/k-3Cla37rLU)

**Comment by zcbenz** [comment]
Currently print preview is not supported in Electron, the original print preview feature is designed for Chrome browser, to add it we have to redesign a large part of it and import the code to Electron.

We don't have any plan to add print preview, but pull requests to add it would be welcomed.

**Comment by GnorTech** [comment]
@RaghuChandrasekaran NW.js supports the print preview feature.

**Comment by RaghuChandrasekaran** [comment]
@GnorTech Thanks for the ref.

**Comment by ndunks** [comment]
good, keep it simple.

**Comment by MeeranRM** [comment]
Hi,

Does the electron support print preview option now?
If electron supports, please advise.

Thanks

**Comment by SaranArjunan** [comment]
Does the electron support print preview option now ?
If electron supports, please advise.

Thanks

**Comment by schanjr** [comment]
Same question as Saran and Meeran. The current print preview does not work on specialized printers sometimes

**Comment by Leo-Schmit** [comment]
Any plans to fix this?
