### ISSUE TITLE
MenuItem checked property does not work

### ISSUE THREAD

**Issue by erkyrath** [atom/electron#4893]
* Electron version: 0.36.11
* Operating system: OSX 10.11.3/10.11.4; Win 7

I am trying to set a checkmark on some items in a menu. It doesn't seem to work at all.

I have tried adding "checked:true" to the template passed to Menu.buildFromTemplate (both for setApplicationMenu and for a popup displayed with menu.popup.) I have also tried setting the MenuItem property directly, e.g. by saying

         var menu = electron.Menu.buildFromTemplate(template);
         menu.items[2].submenu.items[1].checked =	true;
         win.setMenu(menu);

I see no error messages, but no checkmark appears.

**Comment by erkyrath** [comment]
Still true on Electron 0.37.2, if it matters.

**Comment by kevinsawicki** [comment]
Are you setting the `type: checkbox` value on the specified template?

**Comment by erkyrath** [comment]
Nope! That was the problem. Thanks.

The docs are very unclear about this. But I already have a doc bug filed, so -- now that I know what's going on -- I'll write up a clarification and do a PR.

**Comment by laurent22** [comment]
8 years later and the docs are still unclear about this - the `checked` property mentions nothing about the `type`property and vice-versa.
