### ISSUE TITLE
Angular app built with yeoman and grunt fails to run in Electron

### ISSUE THREAD

**Issue by razvanilin** [atom/electron#4895]
* Electron version: v0.37.2
* Operating system: Windows 10 64bit

I started developing an Electron app and for the front-end I'm using yeoman for scaffolding along with grunt for building. Initially I had my Electron `loadURL()` method pointing to `http://localhost:9000` which is used by `grunt serve` while developing the front-end. This works just fine.

The problem arises when I build the angular application (`grunt build`) and try to run it in Electron. If I point `loadURL` to the `dist` files generated by grunt, I get some angular errors. The same happens of I try to serve these files with express.js and point Electron to the address from where theses are served.

What's even more weirder is that for the past year I had an angular app created in the same way running on my server. I tried passing the url to the `loadURL()` method and, again, I get the same errors.

The angular errors I'm talking about:
![capture](https://cloud.githubusercontent.com/assets/5342321/14002357/625beaae-f143-11e5-910a-847428a815b0.JPG)

Does anybody know anything about this?

**Comment by MarshallOfSound** [comment]
Without having much knowledge of your code.  It looks like you are trying to use a 3rd party global `require` function.

In electron you can use `require` just like you would in node.  You can probably fix this by disabling node integration for that browser window.  (it's an initialisation config option)

**Comment by razvanilin** [comment]
Thank you for your reply @MarshallOfSound 

I fixed this a couple of days ago by initialising the `BrowserWindow` with the `nodeIntegration: false` option.

I will close this issue now.

**Comment by artiya4u** [comment]
@razvanilin I want Electron to load static file from dist directory after 'grunt build'. Any ideas?

**Comment by razvanilin** [comment]
@artiya4u You have to place the full path of the `index.html` file in the `loadURL('file:///full_path/index.html')`

If you get the errors I was getting in the screenshot above, make sure that when you initialise the `BrowserWindow` you do it with the `nodeIntegration` option set to false

`new BrowserWindow({width: 1024, height: 764, title: "yourApp", webPreferences: {"nodeIntegration":false}});`
