### ISSUE TITLE
Socks5 Proxy not working

### ISSUE THREAD

**Issue by xanderlu** [atom/electron#4898]
* Electron version: 0.37.2
* Operating system: OS X El Capitan (10.11.2) and Ubuntu 14.04

On OS X and Ubuntu, I'm having the same issue as https://github.com/atom/electron/issues/4032&mdash; which appears to have been closed. I tried using the exact same repro case in the original thread (and trying different socks5 proxies) and it's not working at all. I noticed #4046 seems to have changed `setProxy()` to accept either a `pacScript` or `proxyRules` object, but it seems like the string method should still work based on https://github.com/atom/electron/pull/4046#issuecomment-170439829.

That being said, I've also tried using a PAC file with `session.setProxy()`, but it doesn't seem to work either. Is there something else I need to do in order to enable proxies per BrowserWindow session?

**Comment by xanderlu** [comment]
Nevermind. Looks like it works if you do `setProxy({ proxyRules: proxy })` instead of `setProxy(proxy)`

**Comment by sheepray** [comment]
Yes, changing setProxy(proxy) to setProxy({ proxyRules: proxy }) do solve my problem. Thanks
