### ISSUE TITLE
Single instance of focused openFileDialog() 

### ISSUE THREAD

**Issue by xdvarpunen** [atom/electron#4904]
Hi,

Is it possible to show only one single instance of the openFileDialog() at the time? Right now when using this example: http://www.mylifeforthecode.com/getting-started-with-standard-dialogs-in-electron/ the button can open multiple dialogs and lets to focus on main window too. 

-XDVarpunen

**Comment by zcbenz** [comment]
You can pass current window to the API to open a modal dialog.
