### ISSUE TITLE
how to send args to chromium

### ISSUE THREAD

**Issue by gustavoxpg** [atom/electron#4908]
* Electron version: 0.37.2
* Operating system: osx

Hi, I need to open chromium with the args below to access webcam and mic freely in a http url.
--unsafely-treat-insecure-origin-as-secure="http://site.com/"
--user-data-dir=/Users/foo/
--test-type
--use-fake-ui-for-media-stream

without these args I got this error: getUserMedia() no longer works on insecure origins

I tried use this but I got the same error:
app.commandLine.appendArgument('--unsafely-treat-insecure-origin-as-secure="http://site.com/" --user-data-dir=/Users/foo/ --test-type --use-fake-ui-for-media-stream');

Note: I can't run my app from localhost or static file or https server

**Comment by simonhochrein** [comment]
I think you will need to do this
```
app.commandLine.appendArgument("unsafely-treat-insecure-origin-as-secure","http://site.com/"
```
and so on
but i might be wrong

**Comment by gustavoxpg** [comment]
Hello Simon,

I already tried it, without success :/

**Comment by simonhochrein** [comment]
Ah OK,
I have been having trouble with those flags as well.
They might not be implemented yet.
I believe it might be part of the C++

**Comment by simonhochrein** [comment]
Here is where that code gets run: https://github.com/atom/electron/blob/6aec1e6949e2cbb8d6c67db8b84a208813a2fb35/atom/browser/api/atom_api_app.cc#L405

**Comment by simonhochrein** [comment]
This might work http://electron.atom.io/docs/v0.37.2/api/web-frame/#webframeregisterurlschemeassecurescheme
It disables those warnings and executes anyway

**Comment by gustavoxpg** [comment]
@simonhochrein thank you for your answer!

the webFrame worked fine, the only issue is that I have to import it into the html file.
as I want to render an external website into the electron, this might be a problem.

**Comment by gustavoxpg** [comment]
if it least I could inject the web-frame's code into the website through electron main process. it will solve the problem.

**Comment by simonhochrein** [comment]
if you use a preload on the browser window it should work
reference: http://electron.atom.io/docs/v0.37.3/api/browser-window/#new-browserwindowoptions ```preload```

**Comment by simonhochrein** [comment]
or if you are loading an external site
you can use 
```javascript 
require()
```
in your scripts

**Comment by gustavoxpg** [comment]
@simonhochrein the preload file works perfectly! 
thank you.

**Comment by qengli** [comment]
@ghost Can you tell me how did you resolve the problem with "preload". I have the same issue, thanks
