### ISSUE TITLE
webview sendInputEvent with mouseEnter doesn't trigger mouseenter event

### ISSUE THREAD

**Issue by KSKS** [atom/electron#4912]
webview.sendInputEvent() doesn't trigger any event in the webview when the argument object's type is "mouseEnter"
e.g.  `webview.sendInputEvent({type: "mouseEnter", modifiers: [], x: 141, y: 25});`

I don't get any response, errors or events. I have no problems using this with mouseDown and mouseUp.

I also tried playing with webContent.sendInputEvent() and doesn't get anything either. Not sure if it is related.

Am I missing some required arguments? Any examples or tests I can use?

* Electron version: v0.36.11
* Operating system: OSX

**Comment by zcbenz** [comment]
The `sendInputEvent` API is simply a wrapper of Chromium API, so we don't have fully control of its behavior in Electron. For certain events you have to emulate the whole chain of input events to make DOM recognize it, you probably have to also send mouse move events to make mouseenter event trigger.
