### ISSUE TITLE
Throttle network of main process

### ISSUE THREAD

**Issue by smeeckaert** [atom/electron#4914]
* Electron version: 3.3.6
* Operating system: Linux 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Hi, i've tried many thing to throttle the network usage of the main process but without much success, is there any way to achieve this ?

I tried to use ```trickle``` but the app doesn't even launch when using it.

I tried using the dev-tools options and while it works for the webContent view, it doesn't seem to affect any network operations in the main process.

**Comment by zcbenz** [comment]
No there is no way to throttle network in main process.
