### ISSUE TITLE
Notification error on OSX

### ISSUE THREAD

**Issue by PierBover** [atom/electron#4918]
* Electron version: 0.37.2
* Operating system: OX 10.11.3

I'm trying to use the HTML5 Notifications API using the example in the [documentation](https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-os-x) after the `ready` app event has been triggered:

```
var myNotification = new Notification('Title', {
  body: 'Lorem Ipsum Dolor Sit Amet'
});

myNotification.onclick = function () {
  console.log('Notification clicked')
}
```

But I'm getting this error: `ReferenceError: Notification is not defined`.

It seems as if some `require()` was needed, but the docs don't mention anything about it.

**Comment by johnmuhl** [comment]
The notification API is only available in the renderer process.

**Comment by PierBover** [comment]
That makes sense... I'm going to clear this out in the docs.
