### ISSUE TITLE
app.getLocale() returnes '' on windows.

### ISSUE THREAD

**Issue by havenchyk** [atom/electron#4919]
* Electron version: 0.37.2
* Operating system: Windows 7

On windows I see the empty string as a result of `app.getLocale()` if I invoke it before the `ready` event.
Should it be in docs?

**Comment by havenchyk** [comment]
The returned value from the ready event is not correct as well. In my case it returned en-us, but i use ru-ru.

**Comment by zcbenz** [comment]
You need to ensure that the `locales` folder is copied along with your app. I'll update the docs for this.

**Comment by havenchyk** [comment]
@zcbenz basically, I'd like to get only the current language(locale) of the system and use it. In the electron-getting-started project there is no any `locales` folder. I'm also able to get the lang inside the `app.on('ready'` callback.

**Comment by havenchyk** [comment]
I can't get the correct value exact in the development mode on windows 7 x64, it's weird.

**Comment by havenchyk** [comment]
@zcbenz @kevinsawicki I understand that you're so busy on all these issues, but please take a look on it once again, I still have this problem and I wouldn't like to post new one.

Thanks for all your work!

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/atom/electron#community), the Issues is only for bug reports and feature requests.
