### ISSUE TITLE
Any way to embed apps?

### ISSUE THREAD

**Issue by cprussin** [atom/electron#4930]
* Electron version: Any
* Operating system: Linux

Does Electron support any way of embedding other electron apps (something like chrome's https://developer.chrome.com/apps/tags/appview)?

**Comment by MarshallOfSound** [comment]
https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md

**Comment by Tribex** [comment]
What degree of embedding are you referring to?

**Comment by cprussin** [comment]
:-/ unfortunate.  It seems like it would be a reasonable feature to implement; is this intentionally not supported or would you guys accept a PR adding it if I created one?

**Comment by paulcbetts** [comment]
I can't imagine any non-trivial app that would work with this use-case

**Comment by cprussin** [comment]
Can you be more descriptive?  I can't imagine what wouldn't work well about something like Atom being embedded in a DOM tag...

**Comment by cprussin** [comment]
Also, regarding my question... is this something that would be accepted if I submitted a PR for it?

**Comment by paulcbetts** [comment]
> Like, what are the specific problems that would make apps not work well?

The entire concept doesn't make much sense - the opening file in an Electron app is a node.js script that creates BrowserWindow objects - that opening script does all kinds of process-wide app startup stuff - like, Atom is much more than just a HTML file loaded in a window

**Comment by zcbenz** [comment]
I'm closing this since we don't have any plan for it.
