### ISSUE TITLE
node-v7.0.0-headers.tar.gz in build script does not download (error 403)

### ISSUE THREAD

**Issue by vulture** [atom/electron#4934]
Something in the build script attempts to download:
  https://atom.io/download/atom-shell/v7.0.0/node-v7.0.0-headers.tar.gz
which always results in ERROR 403: Forbidden:
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v7.0.0/node-v7.0.0-headers.tar.gz

The error seems to be ignored, so maybe it's okay, but... I have no idea what it does since I can't access it., Normally, I'd think it should either (1) download or (2) not be included if it's going to generate errors (even if it ignores them?)

**Comment by zcbenz** [comment]
Version number should never be `7.0.0`, are you modifying the source code for building?

Closing since we don't provide support for custom builds.
