### ISSUE TITLE
electron-v0.37.3-win32-ia32 webpage background color is black

### ISSUE THREAD

**Issue by bin-y** [atom/electron#4937]
* Electron version:electron-v0.37.3-win32-ia32
* Operating system:windows 10 x64

![untitled](https://cloud.githubusercontent.com/assets/8192296/14113185/6c13aca6-f604-11e5-800a-22b6cc35d0b2.png)

**Comment by deepak1556** [comment]
The default UA background color was changed to transparent, so you need to explicitly specify background color for your page.

**Comment by felixrieseberg** [comment]
I guess this is just a documentation issue then. I added a blurb to the FAQ.
