### ISSUE TITLE
openExternal allows a malicious script to execute arbitrary local files

### ISSUE THREAD

**Issue by harupu** [atom/electron#4938]
Since addEventListener with 'new-window' can receive file: scheme, this code will allows a remote user to execute arbitrary local files via injected window.open(). 
https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#event-new-window
> webview.addEventListener('new-window', function(e) {
>   require('electron').shell.openExternal(e.url);
> });

This script in wevbiew with event listener described above could execute calc.exe: 
`
window.open('c:/windows/system32/calc.exe')
`
I tested it with electron v0.37.2 on windows.

I think this sample code should validate e.url before execution with openExternal or file: scheme should be prohibited on openExternal.

**Comment by felixrieseberg** [comment]
Good catch - the correct answer here is that environments with disabled node-integration shouldn't be able to open new windows that do have Node integration, meaning that `openExternal` should not be available in a hostile/non-friendly environment, together with all other Node APIs.

I know that @kevinsawicki did some work around that, so if we have new windows locked down, we could close this issue.

**Comment by harupu** [comment]
Thank you for a new document. :)
However, I confirmed that I could open file scheme with chrome by using this url: 
`http://www.example.com/#" "file://c:/`

It seems that lack of escaping of openExternal cause this strange behavior:
https://github.com/atom/electron/blob/master/atom/common/platform_util_win.cc#L308
This escaping flaw should be addressed to path valid url.
