### ISSUE TITLE
在win10系统下，实现程序内关闭电脑。

### ISSUE THREAD

**Issue by cxshmily** [atom/electron#4946]
用electron写了一个win10的程序，想在里面加一个关机的按钮。 不知道要怎么实现相关功能

**Comment by levythu** [comment]
这个是平台相关的... 请参阅shutdown.exe用法

**Comment by cxshmily** [comment]
@levythu  在mian.js 里面怎么调用shutdown.exe?

**Comment by plrthink** [comment]
@cxshmily 这个可以参阅 https://nodejs.org/api/child_process.html#child_process_asynchronous_process_creation

**Comment by cxshmily** [comment]
@plrthink 仅仅是打开shutdown.exe 好像并不能关闭电脑。

**Comment by plrthink** [comment]
@cxshmily 应该是要传些参数，我没有尝试过，但你可以看看这里 http://superuser.com/questions/1003270/what-are-the-arguments-for-shutdown-exe-in-windows-task-scheduler

**Comment by kevinsawicki** [comment]
Closing this out as an answered question.
