### ISSUE TITLE
style will not change unless the console is opened.

### ISSUE THREAD

**Issue by marcus13345** [atom/electron#4948]
my file setup:
index.html: imports scripts.html
scripts.html: links to stylesheet, javascript and bootstrap.

my javascript file is very simple:
`document.getElementsByTagName("body")[0].style.background = 'red';`

however, this does not update the background color. I opened up the dev tools by uncommenting the line in the main.js file provided in the quick start guide to debug the line. when i restarted the app, the background then changed to red. i flipped dev tools on and off a few times to make sure i wasn't crazy.

I also tried another line, to see if it was an issue with something else:
`document.getElementsByTagName("body")[0].innerHTML = 'this is a test!';`
That line worked fine when the console was opened or closed, it didn't matter.

link to my repo where this is happening is [here](https://github.com/marcus13345/Imgur-Downloader-HTML/tree/2676f5e27b5b94deff0d1fedb337d2492e39265e)
index.html, scripts.html, main.js, and main.css are all in the /html folder.

* Electron version: 0.36.11
* Operating system: OS X 10.11.4

**Comment by sedwards2009** [comment]
I too have seen this kind of weird behaviour and I thought it had more to do with the fact I'm using lots of Shadow DOM and styles inside a shadow tree and that the Shadow DOM implementation in Blink is kind of experimental.

Specifically, I've seen cases where setting a class on an element via JS doesn't cause the CSS rules to be applied and the element to render with the new appearance until later. By "until later" I mean some vague time or event later on. For example, inspecting an element with dev tools often gives it a kick and causes it to render correctly. Changing the focus from my Electron app to another app and then back may also 'fix' the situation.

I'm using Kubuntu Linux 15.10. This behaviour has been going on for quite a few major Electron releases, at least 6 months.

**Comment by marcus13345** [comment]
after doing even more research today, it appears that apparently bootstrap was actually at fault here. by body tag takes on a height of effectively 0 when the viewport is above medium, 768px. thus making it so that when the console was opened, the size dipped below 768 and showed the style. whereas any other time, the width was over 768 and the style wasn't shown.

**Comment by jackesdavid** [comment]
i'm getting the same issue... my lazy styles are not applied to elements ... 

https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=shadow%20dom
