### ISSUE TITLE
"Transparent" webview doesn't show content behind: it renders funky artifacts

### ISSUE THREAD

**Issue by mitchhentges** [atom/electron#4950]
* Electron version: `v0.37.3`
* Operating system: Arch Linux. XFCE

As of `v0.37.3`, there's a new feature:
> \<webview>'s background is now transparent by default.

This has enhanced my app's ability to confuse me:
![out](https://cloud.githubusercontent.com/assets/7784737/14140318/93912f0a-f678-11e5-9026-6df9d83adfa9.gif)

**Comment by deepak1556** [comment]
Does the problem occur if you provide a background for the `webview` tag ?

**Comment by mitchhentges** [comment]
No, it does not. When I set `background-color: white;` it behaves properly

**Comment by zcbenz** [comment]
Closed with #4993.
