### ISSUE TITLE
how to set auto reload if electron can't find the url

### ISSUE THREAD

**Issue by gustavoxpg** [atom/electron#4952]
* Electron version: 0.37.2
* Operating system: osx

Hi, I am using electron to open webpage, but this webpage might not be online full-time, so I want reload electron.BrowserWindow or try to reconnect every minute if the webpage won't return http status 200.

is it possible?

**Comment by felixrieseberg** [comment]
You can use the webcontent events to detect if a page load failed (and then reload using JS): https://github.com/atom/electron/blob/master/docs/api/web-contents.md
