### ISSUE TITLE
electron 0.36 - redraw/refresh issue

### ISSUE THREAD

**Issue by wmira** [atom/electron#4953]
* Electron-prebuilt version: 0.36.0
* Operating system: Linux

I just installed electron-prebuilt 0.36.0 and it seems that there are problems on redraw/re-renders? resizing the window for example just show blank screen

see here: http://imgur.com/nL784ZQ

**Comment by nathggns** [comment]
If it helps, I get this message in the console when opening a window.

```
Gtk-Message: Failed to load module "unity-gtk-module"
```

**Comment by nathggns** [comment]
Adding `* { background: white; }` seems to have fixed it?

**Comment by zcbenz** [comment]
Regarding the original issue, please update to latest versions.
