### ISSUE TITLE
0.37.3 causes a black window for Hain

### ISSUE THREAD

**Issue by quinnjn** [atom/electron#4987]
* Electron version: 0.37.3
* Operating system: Win 10 N 64

Original issue: appetizermonster/hain#81
Reverting to 0.37.2 seems to fix this. Let me know if you need more information from me.

**Comment by zeke** [comment]
I saw something about this other day. Perhaps you need to set a background color with CSS? See https://github.com/atom/electron/pull/4941

**Comment by zcbenz** [comment]
Fixed with #4993.
