### ISSUE TITLE
Window's background color doesn't render the correct Hex value

### ISSUE THREAD

**Issue by Mimieam** [atom/electron#4992]
regarding the **backgroundColor** option of **BrowserWindow**

1 - backgroundColor is ignored unless **transparent** is **true**, is that the desired behavior?
2 - After testing with a couple of Hex value it seems like backgroundColor is rounding up any non 0 value to F    
for instance #66CD00 (green)  [(from the documentation)]  (https://github.com/atom/electron/blob/master/docs/api/browser-window.md)  is correctly rendered in the Webpage, but the Main Process' BrowserWindows render it  #FFFF00  (yellow)
 
![image](https://cloud.githubusercontent.com/assets/834291/14224848/7b2350a2-f870-11e5-8c76-994c3e2095f7.png)

* Electron version: electron-v0.36.12
* Operating system: OS X 10.10.5

**Comment by zcbenz** [comment]
> 1 - backgroundColor is ignored unless transparent is true, is that the desired behavior?

On some platforms backgroundColor is not fully implemented yet, it is tracked at #861.

> 2 - After testing with a couple of Hex value it seems like backgroundColor is rounding up any non 0 value to F

It is a new bug, thanks for reporting this.
