### ISSUE TITLE
How to develop with default_app.asar?

### ISSUE THREAD

**Issue by darrrk** [atom/electron#5004]
* Electron version: 0.37.4
* Operating system: any

When **default_app** was folder, I can easly create instead it symlink to any folder with *package.json*, *electron.js*, e t. c. and process of developing was simple:
edit file -> restart electron app -> see result.

But new feature **default_app.asar** discouraged me. How I can develop? On any file change need to create asar archive of all my files that see result of what I coding?

**Comment by Tribex** [comment]
Thankfully, you don't need to create an asar archive to start an electron project.
In fact, if you install electron globally on your system, all you need is a package.json file with a `main: 'filePath'` entry that points to the bootstrap file.
Then just run the command `electron .` in that directory and your app should attempt to start, provided you've set everything up correctly.

I'd recommend reading the [Quick Start Guide](http://electron.atom.io/docs/latest/tutorial/quick-start/) to help orient you a bit with the standard development practices.

**Comment by darrrk** [comment]
I try that way. Electron runs as node process, without gui.

**Comment by yishn** [comment]
You can use [asar](https://github.com/atom/asar) to unpack the archive yourself. Make sure to unpack it in `/resources/app` for it to work.

**Comment by kevinsawicki** [comment]
If you put your app in the same folder that `default_app.asar` is in but call the folder `app/` then Electron should launch that app at startup instead of the default app.

Closing this out.

**Comment by darrrk** [comment]
Thanks

**Comment by paulcbetts** [comment]
It actually would be pretty nice to not ASAR `default_app`, it's pretty convenient to mess around with it for creating Electron bug repros / samples
