### ISSUE TITLE
I there a way to package Jekyll with Electron?

### ISSUE THREAD

**Issue by jbonigomes** [atom/electron#5006]
* Electron version: latest
* Operating system: OSX

I was wondering if there is a way to package Jekyll with an Electron app, I would like to create a CMS for Jekyll that deploys to gh-pages

**Comment by jlord** [comment]
@jbonigomes It is possible to do so. You could include Ruby and Jekyll in your app and talk to them via a [child process](https://nodejs.org/api/child_process.html). 

You may find more help for questions in the [forum](https://discuss.atom.io/c/electron) ✨

**Comment by jbonigomes** [comment]
Thanks @jlord, btw, love your work

**Comment by mklabs** [comment]
@jbonigomes Have you made some progress on this idea ? I've a similar need and was aiming to use https://github.com/mklabs/jekyll-preview to provide a basic preview feature.

**Comment by jbonigomes** [comment]
Hi @mklabs, I am working on a different project at the moment, so I had to park this idea, however, in order to keep things slimmer, I was no longer considering Jekyll and Ruby, but [Hexo](https://hexo.io/) instead.

**Comment by jbonigomes** [comment]
Btw, nice project

**Comment by mklabs** [comment]
Hey @jbonigomes thx :) didn't know about hexo, looks really realy cool.

I'll let you know if I make some progress on this idea.

**Comment by jbonigomes** [comment]
Thanks @mklabs
