### ISSUE TITLE
Proxy support Basic Authentication?

### ISSUE THREAD

**Issue by rainbo** [atom/electron#625]
I try to use base auth on proxy, But it does't work. atom-shell support it?
```
app.commandLine.appendSwitch('proxy-server', 'http://user:pass@ip:port');
```

**Comment by ds82** [comment]
any progress on this?

**Comment by dusan-kovacik-profiq** [comment]
I need to use proxy authentication too. It's a pity that it is still impossible.

**Comment by flashhhh** [comment]
Me too. It's a very important feature to me.

**Comment by petrfelzmann** [comment]
I'd also vote for this feature (if github would have voting buttons for issues ;)

**Comment by Torquin** [comment]
yes same for me, i'm using electron for schools that must use proxy authentication. Cheers
