### ISSUE TITLE
Judging start the same app at second time

### ISSUE THREAD

**Issue by dounai** [atom/electron#648]
I want to disallow user to run the same app on running, and get the arguments from command line.
Is there any way implement this, just like use 'single-instance' configuration  and 'open' event  in node-webkit.

**Comment by paulcbetts** [comment]
@dounai If you feel up to it, it'd be great if you made a Node Module that implemented this feature, then anyone could use it in their app.

**Comment by f0zi** [comment]
I did the socket/pipe thing and it works great, except on Windows I would need to pass on the foreground activation love ([details here](http://blogs.msdn.com/b/oldnewthing/archive/2009/02/20/9435239.aspx)) by calling [AllowSetForegroundWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632668) which is where now suddenly I have to do native things. I have not found any way of doing this with node.js short of writing a native module. Any chance we could have support for foreground activation love?

**Comment by mnichols** [comment]
I did as @paulcbetts asked and spun this into a isolated node module [here](https://www.npmjs.com/package/monogamous). You can put it as a kind of evented facade in front of your normal main process bootstrap code.
I have a usage example for electron and I am using it on my electron app.
@f0zi if you subscribe to its `reboot` event you can just call `myElectronWindow.focus()` and it seems to Just Work (havent checked on windows yet but OSX works ok).

**Comment by paulcbetts** [comment]
@mnichols Awesome!

**Comment by hhammoud01** [comment]
I am sorry but I don't get how to use @mnichols' solution :( Please help :(

**Comment by paulcbetts** [comment]
> There will be no built-in support for the single-instance feature in atom-shell because everything can be implemented with Node here.

We're actually seeing a compelling counter-example for this - `net.createServer` doesn't let you set the permissions of the pipe, which means that if users run an instance as Elevated Admin, further instances will see the pipe but fail to write to it, resulting in single-instance failing. While I'm totally up for sending PRs to monogamous, it seems like that it might be way easier to build this into Electron

**Comment by mnichols** [comment]
I'd love to see this baked in and have one less project :)

**Comment by lipis** [comment]
Lets have it built in :)

**Comment by twolfson** [comment]
It looks like this was released in `0.34.1` as `app.makeSingleInstance`:

https://github.com/atom/electron/releases/tag/v0.34.1

https://github.com/atom/electron/blob/v0.34.1/docs/api/app.md#appmakesingleinstancecallback

**Comment by mnichols** [comment]
Great! I'll make a note on monogamous.

**Comment by Dono7** [comment]
Since the response are now outdated, and some electron issues points to this issue, I would mention that Electron now has a built-in way to do this. Please refer to the documentation : https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelock

```js
const { app } = require('electron')
let myWindow = null

const gotTheLock = app.requestSingleInstanceLock()

if (!gotTheLock) {
  app.quit()
} else {
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    // Someone tried to run a second instance, we should focus our window.
    if (myWindow) {
      if (myWindow.isMinimized()) myWindow.restore()
      myWindow.focus()
    }
  })

  // Create myWindow, load the rest of the app, etc...
  app.whenReady().then(() => {
    myWindow = createWindow()
  })
}
```
