### ISSUE TITLE
Change default name of shell-only app from Atom to e.g. AtomShell

### ISSUE THREAD

**Issue by natevw** [atom/electron#686]
I'm switching a project over from node-webkit to give atom-shell a good try. When updating the documentation on the atom branch, I noticed that the instructions I gave other developers for launching the project don't really work with Atom shell.

On OS X, we used to be able to simply call `open -n -a node-webkit .` in terminal to open the app. But changing this to `open -n -a Atom .` does not work — it opens the Atom **Editor** instead. The app identifier in the shell releases is the same as the Editor app itself! Can this please be changed?

**Comment by zcbenz** [comment]
Atom Shell is now renamed to Electron.
