### ISSUE TITLE
Break out / duplicate `apm rebuild` here

### ISSUE THREAD

**Issue by thedaniel** [atom/electron#793]
For projects using Atom Shell that are not Atom, using the "Atom Package Manager" to build native modules is a bit strange. It might be useful to have a core component of Atom Shell be a tool to build native modules that is not so deeply connected to the Atom project to make packaging easier for other framework users, perhaps allowing for building a dist of atom-shell (e.g. from a branch) and rebuilding specified modules to match it in one go. I'm curious to hear thoughts on this from @atom/core as well as other people trying to build on this framework.

cc @paulcbetts who brought this up in conversation yesterday

**Comment by zcbenz** [comment]
We already have electron-rebuild, and there is no mention of apm in the docs, so I think we are done here.
