### ISSUE TITLE
Implement Chromium task manager

### ISSUE THREAD

**Issue by swrobel** [atom/electron#820]
It seems to me that this might be the correct place for this feature request. I had also submitted it here: https://github.com/atom/atom/issues/4168

Users frequently report issues with high CPU or memory usage, and the typical response is that it must be a package that is the root cause, not Atom itself. Presently, the operating system task managers just show a bunch of Atom Helper processes, so it is impossible to determine which package is associated with the offending process.

Since Atom is based on Chromium, it would be beneficial to implement the Chromium task manager so that a user can see resource usage by package. Here is what Chromium's task manager looks like:

![screen shot 2014-10-25 at 8 46 34 am](https://cloud.githubusercontent.com/assets/157270/5021790/eb491578-6a97-11e4-81b5-feb2330f2360.png)

**Comment by dylang** [comment]
Hi @zcbenz do you know if the Chromium process API is still in the works? I'm trying to figure out which `BrowserWindow`s created are causing high CPU usage.

**Comment by paulcbetts** [comment]
> Since Atom is based on Chromium, it would be beneficial to implement the Chromium task manager so that a user can see resource usage by package. Here is what Chromium's task manager looks like:

I don't think this will get you what you want. Packages don't get their own Chromium processes, for Atom basically every high CPU bug will just say "Main renderer". Not particularly useful. A better plan would to be to monitor CPU usage and take a trace using the Content Tracing API, which can be done today

**Comment by zcbenz** [comment]
Currently we have no interests in working on this, and since it doesn't actually meet the use cases (show resources usages for Atom packages), I'm closing this.

However pull requests to implement it is still welcomed.
