### ISSUE TITLE
NaCl with atom-shell

### ISSUE THREAD

**Issue by larzconwell** [atom/electron#835]
Is embedding a NACL process support in atom shell currently? In the Chrome browser you have to set the flag `--enable-nacl` which doesn't seem to be supported with atom shell, and the actual embed doesn't seem to work either because none of the [events](https://developer.chrome.com/native-client/devguide/coding/progress-events) ever fire.

**Comment by zcbenz** [comment]
I'm closing this since we don't have any plan to support NaCl, pull requests to add it are still welcomed though.

**Comment by GnorTech** [comment]
@larzconwell and all: NW.js has NaCl support; you could consider it: http://nwjs.io
