### ISSUE TITLE
Pressing "Delete" key backwards the page after page is reloaded

### ISSUE THREAD

**Issue by daiyam** [atom/electron#836]
Hi,

I'm creating a new window with a listener on the event `beforeunload`.

Before any calls to `WebContents.reload()`, if I pressed the key `delete`, nothing happens.

After a `WebContents.reload()`, any press on `delete` will generate the event `beforeunload` like it tries to go back in the history navigation.
Without canceling the event `beforeunload`, the page will reload...

Thx

**Comment by gabepaez** [comment]
@zcbenz how do you recommend capturing the input? In my testing after a reload has occurred my keyup listener is no longer invoked when pressing the back key.
