### ISSUE TITLE
printing is broken on Windows

### ISSUE THREAD

**Issue by bwin** [atom/electron#865]
I tested with atom-shell 0.16.3, 0.17.2 & 0.19.4 (all 32bit) on Windows 7 Home Premium 64bit.
(Also tested on another Win7 HP 64 in a VirtualBox with the same result.)
This [gist](https://gist.github.com/bwin/98dec760d5863a0ae1f0) contains the test-app.
Printing silent or not has no effect on this.
(I can totally live with the button not being printed right, but it has nothing to do with it either. Printing a page without a button leads to the same result.)

This is what the window to be printed looks like:
![screenshot 2014-11-25 20 30 56](https://cloud.githubusercontent.com/assets/1673361/5189997/7684336c-74e2-11e4-8c43-65a21f892831.png)

And this is the result I get (printed throught PDFCreator):
![screenshot 2014-11-25 20 30 59](https://cloud.githubusercontent.com/assets/1673361/5190017/97bfbf7e-74e2-11e4-970e-d4876a65e3a1.png)

This is printed (**edit:** directly) on a real printer:
![atomshellprinting](https://cloud.githubusercontent.com/assets/1673361/5190159/aed05b3c-74e3-11e4-8edc-7612982ad5da.jpg)

What confuses me most, is that the pdf's orientation is different and the text doesn't look the same in pdf vs. printed paper version. (**edit: I chose portrait in PDFCreator**)

**Comment by hokein** [comment]
Hi, all. I'll work on the printing issue this summer. You can see the progress at #1532 .
