### ISSUE TITLE
 Warn about sending messages while handling sync messages in browser process

### ISSUE THREAD

**Issue by alexandrudima** [atom/electron#873]
Hi,

Given I have the following main (in main.js):
```
var app = require('app');
var BrowserWindow = require('browser-window');

var myWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
	app.quit();
});

app.on('ready', function() {
	myWindow = new BrowserWindow({
		title: 'main',
	});
	myWindow.loadUrl('file://' + __dirname + '/main.html');
	myWindow.focus();
	myWindow.toggleDevTools();
  
	var ipc = require('ipc');

	ipc.on('marco', function(event) {
		myWindow.send('unrelated1');
		event.sendReply(JSON.stringify('polo'));
	});

	setInterval(function() {
		myWindow.send('unrelated2');
	}, 100);
}); 
```

And the following in main.html:
```
<!DOCTYPE html><html><head></head><body><script>

var ipc = require('ipc');

ipc.on('unrelated1', function(e) {
	console.log('received unrelated1 event');
});

ipc.on('unrelated2', function(e) {
	console.log('received unrelated2 event');
});

console.log('BEFORE sendSync')
var r = ipc.sendSync('marco');
console.log('AFTER sendSync, result: ' + r);

</script></body></html>
```

When running, I found the following console output surprising:
```
BEFORE sendSync 
received unrelated1 event 
AFTER sendSync, result: polo 
[many of]received unrelated2 event 
```
It looks like the JavaScript on the main.html renderer process reacts to ipc events even while waiting on a reply from a synchronous ipc event. Is this expected behaviour? (i.e. can I build code based on this behaviour?)

---

The other surprising behaviour on the code above I encountered is when adding a breakpoint to the body of the 'unrelated2' event handler with Dev Tools. Although the breakpoint was hit and the Dev Tools was showing the JS VM as being paused in a breakpoint, the console messages for 'unrelated2' still continued to pour in.

**Comment by zcbenz** [comment]
I'm merging this to #1966.
