### ISSUE TITLE
Dialog.showMessageBox() does not distinguish cancel/escape from button press

### ISSUE THREAD

**Issue by bpasero** [atom/electron#876]
Using Atom 0.19.5 on Windows pressing either escape or the little X in the dialog corner, I am getting "0" returned as result, as if the user was pressing the primary button. I would expect undefined or null.

To reproduce just run Atom hello world and on startup do this:

```
var result = dialog.showMessageBox({
  type: 'info',
  message: 'message',
  buttons: ['Yes', 'No']
});
  
console.log(result);
```

Then just press escape or the X in the dialog title.

**Comment by bpasero** [comment]
ping. could this be considered? I think its only an issue on Windows/Linux, not Mac.

**Comment by bpasero** [comment]
Digging a bit further, it seems related to how the buttons are labeled. If I set the label of the non-default button to "Cancel", actually pressing ESC or the X in the dialog, correctly triggers the cancel button.

I had the idea to try it out by reading over http://msdn.microsoft.com/en-us/library/windows/desktop/ms645505%28v=vs.85%29.aspx. Not sure if this is the actual function being used in the end.

**Comment by jorangreef** [comment]
I ran into this as well. I need to have "Accept", "Restore", "Quit" as my buttons and would prefer to make Accept the default button but cannot, because pressing esc or closing the dialog should give "Quit".

**Comment by akashnimare** [comment]
@jorangreef @bpasero 
How can I close the dialog if result is 1? I am not able to close the dialog on choosing Cancel.
```javascript
      var result = dialog.showMessageBox({
        type: 'warning',
        buttons: ['OK', 'Cancel'],        
        message: 'Window is not responsing',
        cancelId: 1,
        detail: 'The window is not responding. Would you like to force close it or just keep waiting?'
      })
      console.log(result);
