### ISSUE TITLE
Native tooltips are not working

### ISSUE THREAD

**Issue by bpasero** [atom/electron#877]
I am on Atom 0.19.5 (Windows) with a simple hello world application and I notice that the native hovers are not working.

I am setting a simple link tag on my index.html:

<a href="http://www.github.com" title="GitHub">http://www.github.com</a>

Hovering over the link I am not seeing any hover.

**Comment by hokein** [comment]
The tooltips works on Windows under the current master branch build.

**Comment by bpasero** [comment]
On Linux, hovers are cropped by the bounds of the window at least when the window is not maximized.

**Comment by facelesspanda** [comment]
my tooltips are broken on electron AND google chrome. Several chromium users have reported experiencing issues with tooltips on Windows too. Maybe it's unrelated, but there's an upstream bug about tooltips.
