### ISSUE TITLE
Pepper plugin is not supported

### ISSUE THREAD

**Issue by mgcrea** [atom/electron#912]
More a question than a bug report, but I haven't found a way to make flash file works with atom.

I'm on latest OSX, I'm trying to use the  PepperFlash plugin from my `Google Chrome.app` with this config:

```
  var config = {
    show: true,
    resizable: false,
    frame: false,
    'enable-larger-than-screen': true,
    'web-preferences': {
      'plugins': true ,
      'extra-plugin-dirs': [
        '/Applications/Google Chrome.app/Contents/Versions/39.0.2171.71/Google Chrome Framework.framework/Internet Plug-Ins'
      ]
    },
    // 'node-integration': false,
    'always-on-top': true
  };
``` 

But I still get `net::ERR_UNKNOWN_URL_SCHEME` while the same code is working with Chrome. Any idea what I should look for?

**Comment by nyagi** [comment]
The relevant work in NW.js is [here](https://github.com/nwjs/nw.js/commit/37585d545f07e5640981a9c8278fbcca3b2d85f3)

[Linux] support pepper flash

**Comment by paulcbetts** [comment]
NPAPI completely nuked in Chrome 42, we probably need to do this sooner rather than later.

**Comment by paulcbetts** [comment]
I'm going to probably have a crack at this next week

**Comment by deepak1556** [comment]
Have started work on ppapi with initial support to flash [here](https://github.com/deepak1556/atom-shell/commit/e2beaf7343babd6188d79f82cd41ecf1ecb4c4ab) based on nw.js work. Will PR once i get it to work and generalise for other plugins. If anyone wants to test with a shared build of libchromiumcontent that has ppapi headers and components can use [this](https://cldup.com/uCL0g1LxzmF/y8Sw9V.zip) , relevant patch [here](https://github.com/deepak1556/libchromiumcontent/commit/0f1619c3a0455840e290837fb30fe0dd9b9ea04a)

**Comment by zcbenz** [comment]
Fixed by #1558.

**Comment by rewiredpictures** [comment]
It looks like currently pepper API support is specifically implemented for Flash via the `--ppapi-flash-path` and `--ppapi-flash-version` command line switch. I haven't been able to find support for the generic `--register-pepper-plugins` chromium command line switch. Does this exist and I am just missing it? It looks like the underlying pepper api support is in the codebase, just not the handling of the command line switch. Any additional information would be great!

**Comment by deepak1556** [comment]
@rewiredpictures `register-pepper-plugins` is supported, tested loading pepper flash with `app.commandLine.appendSwitch('register-pepper-plugins', '<pepperflashpath>;application/x-shockwave-flash')`

**Comment by nicksmetBagaar** [comment]
@deepak1556 I don't know if this is a noob question, but the '<pepperflashpath>' : is that how is should be in the code ? If i put it in like that then i get a warning that the module can't be found

// Specify flash path.
    // On Windows, it might be /path/to/pepflashplayer.dll
    // On Mac, /path/to/PepperFlashPlayer.plugin
    // On Linux, /path/to/libpepflashplayer.so
    app.commandLine.appendSwitch('register-pepper-plugins', '<pepperflashpath>;application/x-shockwave-flash');

![schermafbeelding 2015-07-15 om 12 06 41](https://cloud.githubusercontent.com/assets/8414723/8696332/b6a90728-2aeb-11e5-862c-b0b1cc20ecdf.png)

**Comment by hokein** [comment]
@nicksmetBagaar 
https://github.com/hokein/electron-sample-apps/tree/master/pepper-flash-plugin maybe a good reference to you.

**Comment by deepak1556** [comment]
@nicksmetBagaar `register-pepper-plugins` is not the right way to load pepper flash in `Electron` , please follow the instructions linked by @hokein . However you can use the flag to load other trusted plugins.

**Comment by nicksmetBagaar** [comment]
@deepak1556 

I tied this also, but i can't get it to work in windows. The above did work on mac.

app.commandLine.appendSwitch('ppapi-flash-path', 'file://' + __dirname + '/pepflashplayer.dll' );

// Specify flash version, for example, v17.0.0.169
app.commandLine.appendSwitch('ppapi-flash-version', '18.0.0.209');

any suggestions ?

**Comment by hokein** [comment]
> app.commandLine.appendSwitch('ppapi-flash-path', 'file://' + __dirname + '/pepflashplayer.dll' );

 No `file://` prefix.
