### ISSUE TITLE
Navigate back to previous page: 'require' is not defined

### ISSUE THREAD

**Issue by amgibson** [atom/electron#921]
Reproducible on Windows Atom-Shell 0.19.1 and 0.20.0

To reproduce:

Using the quick-start app as a starting point, replace index.html with

````HTML
<html>
<head>
  <title>First page</title>
</head>
<body>
  <script>
    require('ipc');
  </script>
  <p>
    Click on the link
  </p>
  <a href="next.html">Link</a>
</body>
</html>
````

and add a second file next.html containing

````HTML
<html>
<head>
  <title>Second page</title>
</head>
<body>
  <script>
    require('ipc');
  </script>
  <p>
    Now press backspace to go back to the previous page
  </p>
</body>
</html>
````

Run the app and follow the instructions on the pages. When going back to the first page, the following error appears on the console:

> Uncaught ReferenceError: require is not defined

I expected `require` to be defined, as it was on the first visit to the page.

I added some tracing to resources/atom/renderer/lib/init.js and it appears that `process.argv` contains `--node-integration=true` on the first visit to each page. However, it doesn't contain that argument when going back to the first page. This means that `nodeIntegration` is then `false` and so the code which sets `global.require` (later in the same file) is skipped.

**Comment by jimmcslim** [comment]
I have noticed this behaviour on Windows as well, using Atom Shell 0.20.6.

**Comment by paulcbetts** [comment]
We've been hitting a lot of weird issues with `require` not working as well, every time our app starts for the first time we fail to require a module that is definitely there, refreshing the page makes it work again

**Comment by jimmcslim** [comment]
Have tested the new release 0.20.7 and this is still an issue on Windows. Is it by design... is there something my app should do when a window navigates to a URL?

**Comment by jimmcslim** [comment]
Still a problem on 0.21.0 on Windows.

**Comment by jimmcslim** [comment]
Still an issue in 0.21.3 on Windows.

**Comment by jimmcslim** [comment]
Here's a repro showing that require() stops working when the browser goes back in history (via backspace key) https://github.com/jimmcslim/atomtest

**Comment by jimmcslim** [comment]
Still an issue in 0.22.2 on Windows.

**Comment by jimmcslim** [comment]
Still an issue in 0.25.1 on Windows.

**Comment by jimmcslim** [comment]
Great! A release with these fixes would be awesome!

**Comment by CharlieHess** [comment]
Yesssss :gem:

**Comment by jimmcslim** [comment]
Tested on 0.25.2 and backspace no longer goes back triggering the error. Great, Thanks!
