### ISSUE TITLE
WebView ignores parent zoom level

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#940]
While WebView itself supports `web-frame` inside the WebView context, it doesn't respect the host's zoom level, so if you're attempting to control the zoom level solely via the host renderer, it'll be ignored.

**Comment by pekim** [comment]
I've just hit this problem.

It would be good if either the host webframe's zoom factor is propagated to the webview, or the `<webview>` were to support the `setZoomFactor` (and related) functions. I think that the former makes more sense.

**Comment by kidwm** [comment]
I would like to see that `<webview>` to support setZoomFactor function.

**Comment by paulcbetts** [comment]
WebView does support setZoomFactor, it just doesn't automatically scale to the parent's zoom factor

**Comment by kidwm** [comment]
@paulcbetts I didn't know that, thanks!

**Comment by steelbrain** [comment]
Ouch, I think he accidently closed it.

**Comment by zcbenz** [comment]
Oops.

**Comment by Mingling94** [comment]
Not sure if this is related, but I've found that setting a ZoomFactor of not 1 inversely affects the height and width of the webview. For example, if my general app has a zoom factor of 2, my webview's html and body will have a width 'W' px and height 'H' px where 'W' and 'H' are half of the value of the containing element. If zoom is 1.5, 'W' and 'H' will be 2/3rds of the containing element. Weird, might be a chromium thing.

I'm fairly certain this is not a CSS/HTML issue as I've explored this problem on my app for over a month at varying levels of the webview and renderer levels

**Comment by Rameshv** [comment]
Hi @paulcbetts, as per your comments, there is a way to call setZoomFactor from the preload script. But when i do `window.setZoomFactor(0.5)`, i am getting `undefined method setZoomFactor` error. Can you please explain how can i do this

> WebView does support setZoomFactor, it just doesn't automatically scale to the parent's zoom factor. You need to call it from within the preload script (i.e. in the context of the webView itself, not the renderer host)
