### ISSUE TITLE
When setting the window to be frameless, there is style issue under win7 basic mode.

### ISSUE THREAD

**Issue by lygstate** [atom/electron#946]
When I setting down the window to be frameless, and at the Windows 7 basic mode, when I maximize the window, and then restore the window,
the corner border of the window turn out to be Radian comes from "win7 basic theme", but not the “right angle”.

I've done more investigation, for a frameless window, at the startup, the border is normal, after doing any form of resize, the border turn out to be win 7 basic "Radian".

**Comment by lygstate** [comment]
I investigate the brackets, and brackets doesn't suffering from this issue. Only appear this issue when
switching the theme from win7 aero mode to win7 basic mode. 
https://github.com/adobe/brackets/issues/10400

**Comment by zcbenz** [comment]
Can not reproduce on 0.36.2.
