### ISSUE TITLE
[Ubuntu14.04]-[BrowserWindow]-[options]-[resizable] not work.

### ISSUE THREAD

**Issue by LaoZ** [atom/electron#953]
Code like this does not work on ubuntu 14.04, the window size can be customized by dragging the edge.

    // Create the browser window.
    mainWindow = new BrowserWindow({
        width: 800,
        height: 480,
        resizable: false
    });

Note:We are using node.js v0.11.14 and atom-shell 0.19.5.

**Comment by KeitIG** [comment]
I don't know it it is related, but min-width and max-height do not work too.

**Comment by Rustem** [comment]
Any activity on this issue ?

**Comment by KeitIG** [comment]
well, seems the chromium issue is not really going in a good way

**Comment by zcbenz** [comment]
For people who want to get the Chromium bug more attention, you can leave comments on the Chromium issue and click the star button.

**Comment by damianobarbati** [comment]
doh! same for me, resizable=false not working on osx and chromium bug seems to be ignored
