### ISSUE TITLE
Detect focus on devtools

### ISSUE THREAD

**Issue by jwu** [atom/electron#981]
Hi,

I read the document and only found the ability to detect focus and blur for Browser Window. But in my case, I wish the atom-shell can tell me when I focus on and blur off the dev tools. 

Any idea how can I do this?

**Comment by zcbenz** [comment]
There are [devtools-opened](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#event-devtools-opened) and `devtools-closed` events that can detect the open and close of devtools, there is no way to detect focus/blur on devtools yet.

**Comment by jwu** [comment]
Hi, I test the new `devtools-focused` event for the new version ( v0.23.0, v0.24.0 ) of atom-shell in Mac, and found it didn't works. So I reopen it.

Here is my test code:

```javascript
        mainWin.on( 'devtools-focused', function ( event ) {
            console.log('devtools-focused');
        });
        mainWin.on( 'devtools-opened', function ( event ) {
            console.log('devtools-opened');
        });
        mainWin.on( 'focus', function ( event ) {
            console.log('focus');
        });
```

The `focus` and `devtools-opened` event will be responed as they do, the `devtools-focused` missed.

**Comment by jwu** [comment]
ping @zcbenz @deepak1556 :). Still not working in v0.26.1.

**Comment by deepak1556** [comment]
hmm not sure how its broken, have to fix it. @zcbenz can we reopen this issue ?

**Comment by deepak1556** [comment]
@jwu just tested on v0.30.2 the event seems to be working on linux, could you confirm if this still a problem with mac ?

**Comment by jwu** [comment]
@deepak1556, just tested on mac with v0.30.2. still not work :(

**Comment by bpasero** [comment]
It would be nice if browser window has a boolean flag to tell me if focus is inside dev tools or not.
