### ISSUE TITLE
Mouse cursor disappears when keyboard is used

### ISSUE THREAD

**Issue by marekhrabe** [atom/electron#995]
When I press any key on my keyboard while in atom-shell app, mouse cursor hides until mouse moves again. This might be just the right option for some of the apps, but we are really struggling with this behavior in our atom-shell app [Avocode](https://avocode.com/). 

Our interface is similar to graphic editors - you have big canvas with opened document and set of tools you can use. All tools have keyboard shortcuts for activation and when you press for example shortcut for color picker, then instead of changing cursor to eyedropper (which we do in css), the cursor hides and won't show up again until you move your mouse. The experience seems broken

I went a little further while writing this issue and discovered that this is probably issue just on Mac (although not confirmed) which is caused by this snipped of code from chromium (I searched in [latest stable](https://github.com/zcbenz/chromium-source-tarball/releases/tag/39.0.2171.95) release source)

```objc
// from chromium-39.0.2171.95/content/browser/renderer_host/render_widget_host_view_mac.mm
…
// Determine whether we should autohide the cursor (i.e., hide it until mouse
// move) for the given event. Customize here to be more selective about which
// key presses to autohide on.
+ (BOOL)shouldAutohideCursorForEvent:(NSEvent*)event {
  return ([event type] == NSKeyDown &&
             !([event modifierFlags] & NSCommandKeyMask)) ? YES : NO;
}
```

Is is possible that this could be overridden by atom-shell app via any kind of setting/flag? Thanks for any help

**Comment by ffdd** [comment]
I've run into this multiple times. The way I work around it is to create an element containing the cursor image where the cursor would be after the key is pressed and then on the mouse move event when the cursor reappears I hide the element.

The downsides to this approach are that the cursor would get cut off on the edge of the window, and if you are trying to do anything where you need to hold a key down while moving the cursor... well, hardware cursors feel much more responsive than html elements so it's kind of a *drag*.

**Comment by zcbenz** [comment]
I'll add an option for this in `BrowserWindow`, thanks for finding out the troubling line.

**Comment by MaxGraey** [comment]
Hi, is there some progress in this matter?

**Comment by mark-hahn** [comment]
This is somewhat off-topic but I'm having the same problem but with the text cursor, not the mouse cursor.  I assume it has something to do with losing focus.  Can someone point me to any issue about that?  If not I'll create one.
